TOPIC = {
    "id": "1.2",
    "domain": 1,
    "title": "Manage access to Azure resources.",
    "short": "Azure RBAC",
}

TERMS = [
    ("Azure RBAC", "The authorization system, built on Azure Resource Manager, that controls access to Azure resources through role assignments"),
    ("Role assignment", "A grant of access consisting of exactly three parts: a security principal, a role definition, and a scope"),
    ("Security principal", "The 'who' of an assignment — a user, group, service principal, or managed identity"),
    ("Role definition", "A named collection of permissions (Actions, NotActions, DataActions, etc.) describing what a role can do"),
    ("Scope", "The 'where' of an assignment — management group, subscription, resource group, or individual resource"),
    ("Owner", "Fundamental role with full access to all resources including the ability to grant access to others"),
    ("Contributor", "Fundamental role with full access to create and manage all resources but no ability to assign roles"),
    ("Reader", "Fundamental role that can view all resources but make no changes"),
    ("User Access Administrator", "Fundamental role that manages user access (role assignments) to Azure resources but not the resources themselves"),
    ("Role Based Access Control Administrator", "Least-privilege alternative to User Access Administrator that creates role assignments, optionally constrained by conditions"),
    ("Virtual Machine Contributor", "Workload role that manages VMs but grants no access to the connected virtual network or storage and cannot assign roles"),
    ("Network Contributor", "Workload role that manages all networking resources — VNets, subnets, NSGs, load balancers, public IPs"),
    ("Storage Account Contributor", "Control-plane role that manages storage account objects (including listing keys) but grants no data access under Entra authentication"),
    ("Storage Blob Data Reader", "Data-plane role granting read access to blob containers and data when clients authenticate with Microsoft Entra ID"),
    ("Storage Blob Data Contributor", "Data-plane role granting read, write, and delete access to blob data under Microsoft Entra authentication"),
    ("Actions", "Role-definition property listing the control-plane operations the role allows (wildcards permitted)"),
    ("NotActions", "Role-definition property that subtracts operations from Actions — a scoping subtraction, not a deny"),
    ("DataActions", "Role-definition property listing the data-plane operations the role allows, such as reading blob content"),
    ("AssignableScopes", "Role-definition property listing the scopes at which the role is available for assignment"),
    ("Custom role", "A role you author in JSON (IsCustom: true) when no built-in role fits; free feature, up to 5,000 per tenant"),
    ("Inheritance", "The downward-only flow of a role assignment from its scope to every current and future child scope"),
    ("Additive assignments", "The union rule: effective permissions are the sum of all role assignments at a scope and above, direct or via groups"),
    ("Deny assignment", "A block that prevents specific actions even when roles grant them; created only by Azure (managed applications, deployment stacks)"),
    ("Elevate access", "The Entra ID toggle that grants a Global Administrator User Access Administrator at root scope (/) for emergency recovery"),
    ("Check access", "The IAM blade tool showing a principal's effective role assignments at a scope, including inherited and group-based ones"),
    ("Activity Log", "Where role-assignment writes (Microsoft.Authorization/roleAssignments/write) are recorded for auditing who changed access"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A support engineer must restart and resize the VMs in resource group rg-web but must not modify their virtual network or grant anyone access. Which built-in role at which scope satisfies least privilege?",
        "choices": [
            "Contributor at the rg-web resource group",
            "Virtual Machine Contributor at the rg-web resource group",
            "Virtual Machine Contributor at the subscription",
            "Owner at the rg-web resource group",
        ],
        "answer": 1,
        "explain": "Virtual Machine Contributor manages VMs (create, restart, resize, delete) but deliberately excludes the connected virtual network and storage and cannot create role assignments — exactly the boundaries required. Contributor and Owner would allow network changes (and Owner grants access), and scoping to the subscription reaches far more than rg-web.",
    },
    {
        "type": "mc",
        "q": "An administrator opens Access control (IAM) to grant a colleague access. Which three parts must every Azure role assignment contain?",
        "choices": [
            "Security principal, role definition, and scope",
            "User account, license, and subscription",
            "Group, policy definition, and management group",
            "Identity, access review, and resource lock",
        ],
        "answer": 0,
        "explain": "A role assignment is always who + what + where: a security principal (user, group, service principal, or managed identity), a role definition (the named permission set), and a scope (management group, subscription, resource group, or resource). Licenses, policies, and locks are separate governance features, not parts of an RBAC assignment.",
    },
    {
        "type": "mc",
        "q": "A project lead must be able to create and manage every resource in a subscription but must never change who has access. Which built-in role fits?",
        "choices": ["Owner", "User Access Administrator", "Contributor", "Reader"],
        "answer": 2,
        "explain": "Contributor grants full access to create and manage all resource types but cannot create or delete role assignments — 'everything except access' always means Contributor. Owner adds access management, User Access Administrator manages only access, and Reader can only view.",
    },
    {
        "type": "mc",
        "q": "A security team member should manage who has access to resources in a subscription but must not be able to modify the resources themselves. Which built-in role fits?",
        "choices": ["Contributor", "User Access Administrator", "Owner", "Security Admin"],
        "answer": 1,
        "explain": "User Access Administrator manages user access to Azure resources (role assignments) plus read, without resource-modification rights — 'only manage access' is its signature. Owner and Contributor both manage resources, and Security Admin is a Defender for Cloud role, not the fundamental access-management role.",
    },
    {
        "type": "mc",
        "q": "Reading the Contributor role's JSON, an admin sees Actions: [\"*\"] yet knows Contributor cannot assign roles. What in the definition explains this?",
        "choices": [
            "A deny assignment attached to the role",
            "NotActions subtracts the Microsoft.Authorization write and delete operations",
            "AssignableScopes excludes the Microsoft.Authorization provider",
            "DataActions is empty, which blocks role assignment writes",
        ],
        "answer": 1,
        "explain": "Contributor allows everything via the wildcard, then NotActions subtracts Microsoft.Authorization/*/Write, */Delete, and elevateAccess — removing the ability to create or delete role assignments. NotActions is a subtraction within the role, not a deny; AssignableScopes only controls where the role can be assigned, and DataActions concerns the data plane.",
    },
    {
        "type": "mc",
        "q": "An app's managed identity holds Contributor on a storage account, authenticates to Blob Storage with Microsoft Entra ID, and gets authorization failures reading blobs. What is the least-privilege fix?",
        "choices": [
            "Assign Owner on the storage account",
            "Assign Storage Account Contributor on the storage account",
            "Assign Storage Blob Data Reader on the storage account",
            "Add the identity to the subscription's Reader role",
        ],
        "answer": 2,
        "explain": "Contributor, Owner, and Storage Account Contributor are all control-plane roles — under Entra authentication they grant no access to the data inside. Reading blobs requires a data-plane role, and Storage Blob Data Reader is the least-privilege choice for read-only access (Data Contributor would add write/delete).",
    },
    {
        "type": "mc",
        "q": "A VM operator with Virtual Machine Contributor on rg-prod now also needs to modify the subnets and NSGs the VMs use. What should you assign?",
        "choices": [
            "Nothing — Virtual Machine Contributor already covers networking",
            "Network Contributor on rg-prod, in addition to the existing role",
            "Owner on rg-prod, replacing the existing role",
            "User Access Administrator on rg-prod",
        ],
        "answer": 1,
        "explain": "Virtual Machine Contributor deliberately excludes the virtual network, so network changes require adding Network Contributor (VNets, subnets, NSGs, load balancers, public IPs) — the classic pairing. Owner is far broader than needed and adds access management, and User Access Administrator manages permissions, not networks.",
    },
    {
        "type": "mc",
        "q": "A user holds a custom role whose Actions include Microsoft.Compute/* and whose NotActions include Microsoft.Compute/virtualMachines/delete, plus Contributor on the same resource group. Can the user delete VMs there?",
        "choices": [
            "No — NotActions blocks the delete for all of the user's roles",
            "Yes — NotActions only subtracts from that role's own Actions, and Contributor independently grants the delete",
            "No — the more restrictive role always wins when roles conflict",
            "Yes, but only after a deny assignment is removed",
        ],
        "answer": 1,
        "explain": "NotActions is a scoping subtraction inside a single role definition, not a deny. Effective permissions are the union across all roles, and Contributor grants Microsoft.Compute/virtualMachines/delete on its own. There is no 'most restrictive wins' rule in Azure RBAC, and no deny assignment exists in this scenario.",
    },
    {
        "type": "mc",
        "q": "The audit team must have Reader access to every current AND future resource group in a subscription with a single assignment. What should you do?",
        "choices": [
            "Assign Reader on each existing resource group",
            "Assign Reader at the subscription scope",
            "Assign Reader at the tenant root management group",
            "Create a custom role with all resource groups in AssignableScopes",
        ],
        "answer": 1,
        "explain": "'All current and future' is a scope question: assign once at the subscription and downward inheritance covers every resource group in it, including ones created later. Per-RG assignments miss future groups, the root management group is far broader than one subscription requires, and AssignableScopes controls where a role can be assigned, not who has access.",
    },
    {
        "type": "mc",
        "q": "The platform team needs Contributor across twelve production subscriptions using one role assignment. At which scope should it be created?",
        "choices": [
            "At each subscription individually",
            "At the resource group level in each subscription",
            "At a management group containing the twelve subscriptions",
            "At the tenant's Entra ID directory level",
        ],
        "answer": 2,
        "explain": "Only a management group sits above subscriptions in the RBAC scope hierarchy, so one assignment there inherits down into all child subscriptions, resource groups, and resources. Per-subscription assignments mean twelve assignments, and Entra ID directory roles are a separate system that grants no Azure resource access.",
    },
    {
        "type": "mc",
        "q": "A user has Reader assigned at the subscription and, via a group, Contributor on resource group rg-data. What are her effective permissions inside rg-data?",
        "choices": [
            "Reader — the direct assignment overrides the group assignment",
            "Contributor — assignments are additive, and the union is Contributor",
            "Reader — the least-privileged role always applies",
            "No access — conflicting assignments cancel each other out",
        ],
        "answer": 1,
        "explain": "Effective permissions are the union of every assignment at that scope and above, whether direct or via group membership. Contributor already includes everything Reader grants, so inside rg-data she is a full Contributor; elsewhere in the subscription she remains a Reader. Azure RBAC has no override, least-privilege-wins, or cancellation rule.",
    },
    {
        "type": "mc",
        "q": "A developer has Contributor at the subscription scope. Management wants him limited to Reader on the sensitive rg-finance resource group only. What must you do?",
        "choices": [
            "Add a Reader assignment on rg-finance; it overrides the inherited Contributor there",
            "Add a NotActions entry to the Contributor role for rg-finance",
            "Remove the subscription-level Contributor and re-grant it on each resource group except rg-finance, with Reader on rg-finance",
            "Create a deny assignment on rg-finance from the IAM blade",
        ],
        "answer": 2,
        "explain": "You cannot carve out an exception below an assignment — the union rule keeps him Contributor everywhere the broad assignment reaches, so adding Reader changes nothing. The only RBAC fix is removing the broad grant and re-granting at narrower scopes. You cannot edit a built-in role's NotActions, and deny assignments cannot be created by administrators.",
    },
    {
        "type": "mc",
        "q": "A subscription is approaching its limit of roughly 4,000 role assignments. What is the recommended way to reduce the count while preserving everyone's access?",
        "choices": [
            "Assign roles to groups instead of individual users",
            "Convert all assignments to custom roles",
            "Move all assignments to the resource scope",
            "Request a limit increase from Microsoft support",
        ],
        "answer": 0,
        "explain": "One assignment to a group covers every transitive member, collapsing hundreds of per-user assignments into one — the best practice and the exam's expected answer to the ~4,000-per-subscription limit. Custom roles change what is granted, not how many assignments exist, and pushing assignments to resource scope multiplies the count.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command grants dana@contoso.com the Virtual Machine Contributor role on resource group rg-prod?",
        "choices": [
            "az role definition create --role \"Virtual Machine Contributor\" --assignee dana@contoso.com",
            "az role assignment create --assignee dana@contoso.com --role \"Virtual Machine Contributor\" --scope \"/subscriptions/<sub-id>/resourceGroups/rg-prod\"",
            "az ad user update --id dana@contoso.com --role \"Virtual Machine Contributor\"",
            "az role assignment list --assignee dana@contoso.com --role \"Virtual Machine Contributor\"",
        ],
        "answer": 1,
        "explain": "az role assignment create with --assignee, --role, and --scope is the CLI grant command; the resource-group scope string is /subscriptions/<sub-id>/resourceGroups/<rg-name>. az role definition create authors custom roles, az role assignment list only reads existing assignments, and az ad user update edits directory user properties.",
    },
    {
        "type": "mc",
        "q": "Which PowerShell cmdlet assigns the Reader role to a group by its object ID at subscription scope?",
        "choices": [
            "New-AzRoleAssignment -ObjectId <group-object-id> -RoleDefinitionName \"Reader\" -Scope \"/subscriptions/<sub-id>\"",
            "Set-AzRoleDefinition -ObjectId <group-object-id> -Role \"Reader\"",
            "Add-AzADGroupMember -ObjectId <group-object-id> -Role \"Reader\"",
            "Get-AzRoleAssignment -ObjectId <group-object-id> -RoleDefinitionName \"Reader\"",
        ],
        "answer": 0,
        "explain": "New-AzRoleAssignment creates assignments; groups and service principals are targeted with -ObjectId (users can use -SignInName), and -Scope or -ResourceGroupName selects the scope. Set-AzRoleDefinition edits role definitions, Add-AzADGroupMember manages group membership, and Get-AzRoleAssignment only reads assignments.",
    },
    {
        "type": "mc",
        "q": "Before an access review, an admin must list every role assignment dana@contoso.com holds at every scope in the subscription. Which command does this?",
        "choices": [
            "az role definition list --name dana@contoso.com",
            "az role assignment create --assignee dana@contoso.com --all",
            "az role assignment list --assignee dana@contoso.com --all --output table",
            "az account list --query dana@contoso.com",
        ],
        "answer": 2,
        "explain": "az role assignment list --assignee <principal> --all returns everything the principal holds across scopes in the subscription — the scriptable interpreter of access. az role definition list inspects role definitions (its --name takes a role name, not a user), create makes new grants, and az account list shows subscriptions.",
    },
    {
        "type": "mc",
        "q": "In the Azure portal, which tool shows the effective role assignments a specific user has at a resource group, including inherited and group-based ones?",
        "choices": [
            "Access control (IAM) > Check access",
            "Entra ID > Licenses",
            "Azure Policy > Compliance",
            "Activity Log > Role assignments filter",
        ],
        "answer": 0,
        "explain": "The IAM blade's Check access tool takes a user, group, service principal, or managed identity and displays their effective role assignments at that scope, combining direct, inherited, and group-derived grants. The Activity Log shows who created assignments (auditing), not current effective access, and Policy and Licenses are unrelated.",
    },
    {
        "type": "mc",
        "q": "A newly appointed Global Administrator complains she cannot see any subscriptions or resources in the Azure portal. What explains this?",
        "choices": [
            "Her account is missing an Entra ID P2 license",
            "Entra directory roles grant no Azure resource access by default; she needs an Azure RBAC role assignment",
            "Global Administrators must first register the Microsoft.Authorization resource provider",
            "Subscriptions are hidden until she enables Privileged Identity Management",
        ],
        "answer": 1,
        "explain": "This is correct behavior: Microsoft Entra roles govern the directory while Azure RBAC governs resources, and a Global Administrator holds zero resource access until an Azure role is assigned (or the elevate-access toggle is used in an emergency). Licensing, provider registration, and PIM have nothing to do with the separation.",
    },
    {
        "type": "mc",
        "q": "The only Owner of a subscription left the company, and no one can manage its access. What is the supported recovery path for the Global Administrator?",
        "choices": [
            "Open a support ticket to have Microsoft assign Owner",
            "Enable the 'Access management for Azure resources' toggle to gain User Access Administrator at root scope, re-grant Owner, then disable the toggle",
            "Recreate the subscription and move the resources into it",
            "Use az role definition update to add themselves to the Owner role",
        ],
        "answer": 1,
        "explain": "Elevate access exists exactly for this: the toggle in Entra ID properties grants the Global Administrator User Access Administrator at root scope (/), spanning every subscription, so they can create a new Owner assignment — and it should be switched off immediately after. Editing a role definition changes permissions, not membership, and recreating the subscription is unnecessary and destructive.",
    },
    {
        "type": "mc",
        "q": "An Owner of a resource deployed via an Azure managed application finds she cannot delete it, even though her role clearly allows deletes. What is the most likely cause?",
        "choices": [
            "A NotActions entry in the Owner role definition",
            "A deny assignment created by Azure on the managed application's resources",
            "Her assignment was made at too high a scope",
            "The Contributor role was removed from her account",
        ],
        "answer": 1,
        "explain": "Deny assignments block specific actions even when a role grants them, and deny wins over any role assignment. They cannot be created by administrators — Azure itself creates them on resources protected by managed applications or deployment stacks. Owner's NotActions do not subtract deletes, and a higher scope grants more reach, not less.",
    },
    {
        "type": "mc",
        "q": "Which built-in roles include the Microsoft.Authorization/roleAssignments/write permission needed to grant others access at a scope?",
        "choices": [
            "Owner, User Access Administrator, and Role Based Access Control Administrator",
            "Owner and Contributor",
            "Contributor and User Access Administrator",
            "Any role that includes the wildcard * in Actions",
        ],
        "answer": 0,
        "explain": "Creating role assignments requires roleAssignments/write, held by Owner, User Access Administrator, and the newer Role Based Access Control Administrator (which can be constrained with conditions). Contributor explicitly subtracts Microsoft.Authorization writes via NotActions — which also disqualifies the 'any wildcard role' answer, since Contributor has * in Actions yet still cannot grant access.",
    },
    {
        "type": "mc",
        "q": "A security investigation asks who granted a suspicious Owner assignment on a subscription last week. Where do you look?",
        "choices": [
            "The Activity Log, for Microsoft.Authorization/roleAssignments/write operations",
            "The IAM Check access blade",
            "Entra ID sign-in logs",
            "The role definition's AssignableScopes property",
        ],
        "answer": 0,
        "explain": "Role assignments are write operations recorded in the Activity Log as Microsoft.Authorization/roleAssignments/write, so auditing a grant — who, when, from where — is an Activity Log query. Check access shows current effective permissions, not history; sign-in logs record authentications, not authorization changes.",
    },
    {
        "type": "mc",
        "q": "No built-in role matches a team's needs, so an admin will author a custom Azure role. Which statement about custom roles is TRUE?",
        "choices": [
            "Creating them requires a Microsoft Entra ID P1 or P2 license",
            "They are a free RBAC feature, but creating one requires Microsoft.Authorization/roleDefinitions/write, held by Owner or User Access Administrator",
            "They can only be created by Microsoft support",
            "A tenant supports a maximum of 500 custom roles",
        ],
        "answer": 1,
        "explain": "Custom Azure roles are free — no P1/P2 license — and a tenant supports up to 5,000 of them. Creating or updating one requires the roleDefinitions/write permission, which Owner and User Access Administrator hold. They are authored by customers in JSON (IsCustom: true), typically via az role definition create or New-AzRoleDefinition.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A Microsoft Entra Global Administrator automatically has Owner access to every Azure subscription in the tenant.",
        "answer": False,
        "explain": "Entra roles and Azure RBAC are separate authorization systems: Global Administrator governs the directory and holds no Azure resource access by default. Resource access requires an Azure role assignment — or, in an emergency, the elevate-access toggle, which grants User Access Administrator (not Owner) at root scope and should be disabled after use.",
    },
    {
        "type": "tf",
        "q": "True or False: A role assigned at subscription scope automatically applies to resource groups created in that subscription after the assignment was made.",
        "answer": True,
        "explain": "Inheritance flows downward from the assignment's scope to every current and future child scope. That is precisely why 'all current and future resource groups' stems are answered by assigning once at the subscription (or management group) rather than per resource group.",
    },
    {
        "type": "tf",
        "q": "True or False: Assigning Reader on one resource group to a user who already has Contributor at the subscription reduces their access to Reader in that resource group.",
        "answer": False,
        "explain": "Assignments are additive: effective permissions are the union of all assignments at a scope and above, so the inherited Contributor keeps full effect and the Reader assignment adds nothing. To genuinely restrict access you must remove the broad assignment and re-grant at narrower scopes.",
    },
    {
        "type": "tf",
        "q": "True or False: An administrator can create a deny assignment from the Access control (IAM) blade to block a specific user from deleting a resource.",
        "answer": False,
        "explain": "Deny assignments cannot be created by customers at all — only Azure itself creates them, on resources protected by Azure managed applications or deployment stacks. While a deny assignment does override every role assignment, the admin-authored tools for restricting actions are removing/narrowing role assignments, resource locks, and Azure Policy.",
    },
    {
        "type": "tf",
        "q": "True or False: When a role is assigned to a group, every transitive member of that group receives the role's permissions at that scope.",
        "answer": True,
        "explain": "Group-based assignments apply to all transitive members, which is why a user with no direct assignments can still hold significant access — always check group-derived assignments before declaring someone unprivileged. It is also the best practice for staying under the ~4,000 role assignments per subscription limit.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The fundamental built-in role that can manage user access to Azure resources but cannot modify the resources themselves is ______. (type your answer)",
        "answers": ["user access administrator", "uaa", "user access admin"],
        "explain": "User Access Administrator is the 'only manage access' fundamental role — role assignments plus read, nothing more. Combined with Contributor it approximates Owner, and it is one of the roles holding Microsoft.Authorization/roleAssignments/write.",
    },
    {
        "type": "fill",
        "q": "The role-definition JSON property that lists the scopes at which a custom role is available for assignment is ______. (type your answer)",
        "answers": ["assignablescopes", "assignable scopes"],
        "explain": "AssignableScopes bounds where a role can be offered for assignment — for custom roles, at least one subscription, resource group, or a single management group. It controls availability of the role, not who holds it or what it permits.",
    },
    {
        "type": "fill",
        "q": "Complete the Azure CLI command that grants a role to a principal at a scope: az role ______ create --assignee ... --role ... --scope ... (type the missing word)",
        "answers": ["assignment", "role assignment", "az role assignment create"],
        "explain": "az role assignment create is the grant command — assignee (who), role (what), scope (where) mirror the three parts of every role assignment. Its siblings are az role assignment list to interpret access and az role assignment delete to revoke it, while az role definition commands manage the roles themselves.",
    },
    {
        "type": "fill",
        "q": "The Azure PowerShell cmdlet that lists existing role assignments (for example by -SignInName or -ResourceGroupName) is ______. (type your answer)",
        "answers": ["get-azroleassignment", "get azroleassignment", "get-azroleassignment cmdlet"],
        "explain": "Get-AzRoleAssignment is the PowerShell interpreter of access, filterable by principal (-SignInName, -ObjectId) or scope (-ResourceGroupName, -Scope). New-AzRoleAssignment creates assignments and Remove-AzRoleAssignment deletes them; the CLI equivalent is az role assignment list.",
    },
    {
        "type": "fill",
        "q": "The data-plane built-in role that grants read-only access to blob data when clients authenticate with Microsoft Entra ID is Storage Blob Data ______. (type the missing word)",
        "answers": ["reader", "storage blob data reader"],
        "explain": "Storage Blob Data Reader grants read access to containers and blob data under Entra authentication; Storage Blob Data Contributor adds write and delete. Control-plane roles like Owner, Contributor, and Storage Account Contributor grant no blob data access via Entra sign-in — the exam's favorite trap.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each fundamental Azure role to what it can do.",
        "pairs": [
            ["Owner", "Full access to all resources including granting access to others"],
            ["Contributor", "Create and manage all resources but cannot assign roles"],
            ["Reader", "View all resources but make no changes"],
            ["User Access Administrator", "Manage user access to resources but not the resources themselves"],
        ],
        "explain": "Match the verb to the role: 'everything including access' is Owner, 'everything except access' is Contributor, 'view only' is Reader, and 'only manage access' is User Access Administrator. Owner is approximately Contributor plus User Access Administrator.",
    },
    {
        "type": "match",
        "q": "Match each role-definition JSON property to its meaning.",
        "pairs": [
            ["Actions", "Control-plane operations the role allows, wildcards permitted"],
            ["NotActions", "Operations subtracted from Actions — not a deny"],
            ["DataActions", "Data-plane operations allowed, such as reading blob content"],
            ["NotDataActions", "Data-plane operations subtracted from DataActions"],
            ["AssignableScopes", "Scopes at which the role is available for assignment"],
        ],
        "explain": "Within one role, permissions = (Actions − NotActions) + (DataActions − NotDataActions), then union across all of a principal's roles. AssignableScopes controls where the role can be assigned. Remember NotActions is a scoping subtraction; only a deny assignment actually blocks access.",
    },
    {
        "type": "match",
        "q": "Match each workload role to its defining boundary.",
        "pairs": [
            ["Virtual Machine Contributor", "Manages VMs but grants no access to their virtual network or storage"],
            ["Network Contributor", "Manages VNets, subnets, NSGs, load balancers, and public IPs"],
            ["Storage Account Contributor", "Control-plane management of the account object; no data access via Entra auth"],
            ["Storage Blob Data Contributor", "Data-plane read, write, and delete of blob data under Entra authentication"],
        ],
        "explain": "The exam tests the exclusions: VM Contributor stops at the NIC's network, so Network Contributor is its pairing partner, and Storage Account Contributor is control plane only, so touching blob data under Entra auth requires a Storage Blob Data role. Least privilege means combining narrow roles rather than reaching for Contributor.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the Azure RBAC scope levels from BROADEST to NARROWEST.",
        "items": ["Management group", "Subscription", "Resource group", "Resource"],
        "explain": "The four-level hierarchy is management group > subscription > resource group > resource, and inheritance flows strictly downward — an assignment at any level applies to every current and future child scope. Assign at the highest scope that matches the need, and no higher.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to recover a subscription whose only Owner has left the company, from first to last.",
        "items": [
            "Sign in as a Microsoft Entra Global Administrator",
            "Enable the 'Access management for Azure resources' toggle in Entra ID properties",
            "Receive User Access Administrator at root scope (/)",
            "Create a new Owner role assignment on the orphaned subscription",
            "Disable the elevate-access toggle immediately after the recovery",
        ],
        "explain": "Elevate access is the emergency path: only a Global Administrator can flip the toggle, which grants User Access Administrator at root scope spanning every subscription in the tenant. With that authority they re-grant Owner, then switch the toggle off at once — leaving it enabled is a standing privilege risk.",
    },
    {
        "type": "order",
        "q": "Arrange the portal steps to grant a user a role on a resource group, from first to last.",
        "items": [
            "Navigate to the resource group in the Azure portal",
            "Open the Access control (IAM) blade",
            "Select Add role assignment",
            "Choose the role definition to grant",
            "Select the user, group, or service principal as members",
            "Review and create the assignment",
        ],
        "explain": "Every assignment lives on the scope's Access control (IAM) blade: Add role assignment walks through picking the role (what) and the members (who) at the scope you opened (where). Completing it requires Microsoft.Authorization/roleAssignments/write — Owner, User Access Administrator, or Role Based Access Control Administrator; a Contributor cannot.",
    },
]
