TOPIC = {
    "id": "1.3",
    "domain": 1,
    "title": "Manage Azure subscriptions and governance.",
    "short": "Subscriptions & Governance",
}

TERMS = [
    ("Azure Policy", "Governance service that evaluates resources against JSON if/then rules to report or enforce compliance — it controls WHAT can be deployed regardless of who"),
    ("Policy definition", "A single JSON if/then rule: if a resource matches the conditions, then apply exactly one effect"),
    ("Initiative (policy set definition)", "A group of policy definitions assigned together as one unit with a single compliance score"),
    ("Policy assignment", "The act of applying a definition or initiative at a scope — management group, subscription, or resource group"),
    ("Exemption", "A time-boxed, documented waiver for specific resources under an assignment that stays visible in compliance reporting"),
    ("Remediation task", "The explicit action that makes Modify/DeployIfNotExists policies fix resources that existed before the assignment"),
    ("Deny effect", "Policy effect that blocks the create/update request outright — even for Owners"),
    ("Audit effect", "Policy effect that allows the operation but flags the resource non-compliant in compliance reporting"),
    ("Modify effect", "Policy effect that adds, updates, or removes properties or tags — requires a managed identity, and remediation for existing resources"),
    ("DeployIfNotExists effect", "Policy effect that deploys a missing related resource (agent, diagnostic setting) — requires a managed identity"),
    ("AuditIfNotExists effect", "Policy effect that flags a resource non-compliant when a related resource, such as a diagnostic setting, is missing"),
    ("Resource lock", "Safety switch at subscription, resource group, or resource scope that blocks operations for everyone — including Owners — until removed"),
    ("CanNotDelete lock", "Lock level (Delete lock in the portal) that blocks delete operations but still allows read and modify"),
    ("ReadOnly lock", "Lock level that blocks delete and every write — including POSTs like listing storage account keys"),
    ("Tag", "A name/value pair (e.g., CostCenter=1234) attached to resources for metadata — up to 50 per resource, NOT inherited by default"),
    ("Tag Contributor", "Built-in role that can apply and manage tags on resources without any other write permissions"),
    ("Resource group", "Lifecycle container whose contents are deployed, secured, and deleted together; its location stores metadata only"),
    ("Subscription", "A billing boundary and access-management boundary that trusts one Entra tenant and has exactly one management-group parent"),
    ("Management group", "Container above subscriptions where RBAC and Policy assignments inherit down to every subscription beneath"),
    ("Tenant root management group", "The top of the management-group hierarchy — above all other MGs; cannot be deleted or moved"),
    ("Budget", "Cost Management threshold (actual or forecasted) at a scope that fires alerts when crossed — it never stops spending on its own"),
    ("Cost analysis", "Cost Management view that slices actual and forecasted spend by tag, resource group, service, subscription, or region"),
    ("Azure Advisor", "Free service giving personalized recommendations across Cost, Security, Reliability, Operational excellence, and Performance"),
    ("Action group", "Set of notification and automation actions (email, runbooks, Logic Apps, Functions) triggered by alerts such as budget thresholds"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "Compliance requires that NO ONE — not even subscription Owners — can create resources outside the East US and West US regions. Which control enforces this?",
        "choices": [
            "A custom RBAC role that removes write permissions",
            "An Azure Policy assignment with the Deny effect",
            "A ReadOnly resource lock on the subscription",
            "A budget alert on the subscription",
        ],
        "answer": 1,
        "explain": "Policy controls WHAT can be deployed regardless of who is deploying — a Deny policy blocks the request even for Owners. RBAC only controls WHO can act and can't express a 'no disallowed regions' rule for authorized users, a ReadOnly lock blocks ALL writes everywhere in scope, and budgets only alert on spend.",
    },
    {
        "type": "mc",
        "q": "An admin wants every new VM to automatically receive the Azure Monitor agent if it is missing after deployment. Which policy effect fits?",
        "choices": ["Audit", "AuditIfNotExists", "DeployIfNotExists", "Append"],
        "answer": 2,
        "explain": "DeployIfNotExists deploys the missing related resource (an extension, a diagnostic setting) after creation. AuditIfNotExists only flags the VM as non-compliant without installing anything, Audit just reports on the resource itself, and Append adds fields during the create/update request rather than deploying anything afterward.",
    },
    {
        "type": "mc",
        "q": "Which pair of Azure Policy effects requires the assignment to have a managed identity because they perform actions on your behalf?",
        "choices": [
            "Deny and Audit",
            "Append and Disabled",
            "Audit and AuditIfNotExists",
            "Modify and DeployIfNotExists",
        ],
        "answer": 3,
        "explain": "Modify changes properties or tags and DeployIfNotExists creates missing resources — both act on resources, so the assignment needs a managed identity with the right RBAC roles, plus a remediation task for pre-existing resources. Deny, Audit, AuditIfNotExists, Append, and Disabled never touch resources themselves.",
    },
    {
        "type": "mc",
        "q": "A new Deny policy blocking public IP addresses is assigned to a subscription that already contains 12 public IPs. What happens to those existing resources?",
        "choices": [
            "They are deleted within 24 hours",
            "They are flagged as non-compliant but continue to work",
            "They are automatically moved to a quarantine resource group",
            "They stop working until an exemption is granted",
        ],
        "answer": 1,
        "explain": "Azure Policy never deletes or alters existing resources on its own — existing violators of a Deny policy are only marked non-compliant in compliance reporting. Only an explicit remediation task under a Modify or DeployIfNotExists effect can change existing resources.",
    },
    {
        "type": "mc",
        "q": "A security team has 30 individual policy definitions forming its baseline and wants to assign them as a single unit with one compliance score. What should they create?",
        "choices": ["A management group", "An initiative", "A policy exemption", "A remediation task"],
        "answer": 1,
        "explain": "An initiative (policy set definition) groups policy definitions so they are assigned together and tracked with one compliance score — exactly how regulatory-compliance baselines ship. Management groups are scope containers, exemptions waive assignments for specific resources, and remediation tasks fix existing resources.",
    },
    {
        "type": "mc",
        "q": "One legacy storage account must be temporarily excused from a policy assignment for 90 days, with the waiver documented and still visible in compliance reporting. What should the admin create?",
        "choices": [
            "An exclusion on the assignment scope",
            "A Disabled policy definition",
            "An exemption for the resource",
            "A CanNotDelete lock on the storage account",
        ],
        "answer": 2,
        "explain": "Exemptions are time-boxed, documented waivers for specific resources that remain visible in compliance reporting. An exclusion carves a sub-scope out of the assignment entirely (no visibility, no expiry), Disabled turns evaluation off for everyone, and locks have nothing to do with policy compliance.",
    },
    {
        "type": "mc",
        "q": "A 'Inherit a tag from the resource group' Modify policy is assigned, but resources created BEFORE the assignment still lack the tag. Which Azure CLI command fixes them?",
        "choices": [
            "az policy remediation create",
            "az policy assignment create",
            "az policy definition update",
            "az tag create",
        ],
        "answer": 0,
        "explain": "Policy does not retroactively change existing resources — you must run a remediation task, created with az policy remediation create (PowerShell: Start-AzPolicyRemediation), against the Modify/DeployIfNotExists assignment. Re-creating the assignment or definition doesn't touch existing resources, and az tag create would be manual, one-off tagging.",
    },
    {
        "type": "mc",
        "q": "A production SQL server must be protected against accidental deletion, but DBAs still need to change its configuration daily. Which lock level should be applied?",
        "choices": ["ReadOnly", "CanNotDelete", "NoDelete", "Protected"],
        "answer": 1,
        "explain": "CanNotDelete (shown as 'Delete' in the portal) blocks delete operations while still allowing reads and modifications — the standard answer for 'prevent accidental deletion.' ReadOnly would block the DBAs' daily configuration changes, and NoDelete/Protected are not real Azure lock levels.",
    },
    {
        "type": "mc",
        "q": "After an admin applies a lock to a storage account, an application that authenticates with the account keys suddenly fails — it can no longer retrieve the keys. What is the cause?",
        "choices": [
            "A CanNotDelete lock blocks key retrieval",
            "The application lost its RBAC role assignment",
            "A ReadOnly lock blocks key listing because it is a POST operation",
            "Azure Policy rotated the storage keys",
        ],
        "answer": 2,
        "explain": "Listing storage account keys is a POST request, which Azure classifies as a write — so a ReadOnly lock blocks it even though it feels like a read. CanNotDelete only blocks deletes and would not affect key listing, no RBAC change occurred, and Azure Policy does not rotate keys.",
    },
    {
        "type": "mc",
        "q": "A user with the Owner role on a subscription tries to delete a VM and receives an error saying the operation is disallowed. RBAC shows no deny assignments. What is the MOST likely cause, and the fix?",
        "choices": [
            "An Azure Policy Deny effect; grant an exemption",
            "A resource lock somewhere in the scope chain; remove the lock first, then delete",
            "The VM is in a different region than its resource group; move it first",
            "The subscription hit its vCPU quota; request a quota increase",
        ],
        "answer": 1,
        "explain": "Locks apply regardless of RBAC role — even an Owner is blocked until the lock (which may be inherited from the resource group or subscription) is removed. Deny policies block create/update requests, not deletes of existing resources; RG/resource region mismatch is perfectly legal; and quotas limit creation, not deletion.",
    },
    {
        "type": "mc",
        "q": "Which built-in roles include the Microsoft.Authorization/locks/* permissions needed to create and delete resource locks?",
        "choices": [
            "Owner and User Access Administrator",
            "Contributor and Reader",
            "Owner and Contributor",
            "Security Admin and Global Administrator",
        ],
        "answer": 0,
        "explain": "Lock management lives under Microsoft.Authorization/locks/*, held by Owner and User Access Administrator (or a custom role granting it). Contributor can manage resources but notably cannot manage locks or role assignments — a classic exam discriminator. Global Administrator is an Entra role, not an Azure RBAC role.",
    },
    {
        "type": "mc",
        "q": "The rg-prod resource group carries a CostCenter tag, but a VM created inside it shows no CostCenter tag at all. What is the correct scalable fix?",
        "choices": [
            "Re-create the VM so it picks up the tag at creation",
            "Enable tag inheritance in the resource group's properties blade",
            "Assign the built-in 'Inherit a tag from the resource group' policy (Modify effect) with a remediation task",
            "Apply a ReadOnly lock so tags cannot drift",
        ],
        "answer": 2,
        "explain": "Tags are NOT inherited from the resource group or subscription by default, and there is no inheritance toggle on the RG. The scalable fix is the built-in Modify-effect policy that copies the tag down, plus a remediation task for resources that already exist. Re-creating the VM wouldn't inherit anything either, and locks don't manage tags.",
    },
    {
        "type": "mc",
        "q": "An admin needs to add Env=Prod to a resource that already carries six other tags, without disturbing them. Which command is safe?",
        "choices": [
            "az group update --name rg-prod --tags Env=Prod",
            "az tag update --resource-id $id --operation Merge --tags Env=Prod",
            "az tag update --resource-id $id --operation Replace --tags Env=Prod",
            "az tag delete --resource-id $id",
        ],
        "answer": 1,
        "explain": "The Merge operation adds or updates the named tags while leaving the rest untouched. az group update --tags and the Replace operation both overwrite the entire tag set with only what you specify — wiping the other six tags — and az tag delete removes tags outright. Watch for this replace-versus-merge trap in command questions.",
    },
    {
        "type": "mc",
        "q": "A finance analyst must be able to add and correct tags on resources for chargeback but should receive NO other permissions on those resources. Which built-in role fits?",
        "choices": ["Contributor", "Tag Contributor", "Reader", "Cost Management Contributor"],
        "answer": 1,
        "explain": "Tag Contributor is the narrowly scoped built-in role that can manage tags on entities without granting any other access to the resources themselves. Contributor is far too broad, Reader cannot write tags at all, and Cost Management Contributor manages budgets and cost views, not resource tags.",
    },
    {
        "type": "mc",
        "q": "A project has ended and its 40 resources — VMs, disks, NICs, storage — all live in one resource group. What is the fastest supported way to remove the entire environment?",
        "choices": [
            "Delete each resource individually in dependency order",
            "Apply a Deny policy so the resources expire",
            "Delete the resource group, which deletes every resource inside it",
            "Move the resources to the tenant root management group",
        ],
        "answer": 2,
        "explain": "A resource group is a lifecycle container: deleting it deletes every resource inside in one operation, with no undo — which is exactly why RG design and locks matter. Policies never delete existing resources, resources can't live in a management group, and one-by-one deletion is needless toil.",
    },
    {
        "type": "mc",
        "q": "A resource group was created in East US. An admin now needs to deploy VMs into West Europe. What must be done with the resource group?",
        "choices": [
            "Nothing — the RG location stores metadata only, and its resources can live in any region",
            "Move the resource group to West Europe first",
            "Create a paired resource group in West Europe and link them",
            "Enable multi-region mode on the resource group",
        ],
        "answer": 0,
        "explain": "The resource group's location only determines where its metadata is stored; the resources inside can live in any region, so a West Europe VM in an East US RG is fine. There is no RG 'move to region,' pairing, or multi-region mode — those distractors invent features that don't exist.",
    },
    {
        "type": "mc",
        "q": "While az resource move transfers a VM from rg-app to rg-archive, a teammate tries to deploy a new resource into rg-app and the deployment fails. Why?",
        "choices": [
            "The source group's region is unavailable during the move",
            "Both the source and destination resource groups are locked for write operations until the move completes",
            "A Deny policy is triggered by every move operation",
            "Moving a resource converts the source group to read-only permanently",
        ],
        "answer": 1,
        "explain": "During a resource move, Azure locks both the source AND destination resource groups — no add, update, or delete operations succeed in either group until the move completes, though reads still work. The lock is temporary and automatic; it is not a policy effect and has nothing to do with region availability.",
    },
    {
        "type": "mc",
        "q": "An admin plans to move a storage account from subscription A to subscription B. Which condition MUST be true for the cross-subscription move to succeed?",
        "choices": [
            "Both subscriptions must trust the same Microsoft Entra tenant",
            "Both subscriptions must use the same billing offer type",
            "The storage account must first be moved to the tenant root management group",
            "The destination subscription must be in the same region as the storage account",
        ],
        "answer": 0,
        "explain": "Cross-subscription moves require both subscriptions to be in the same Entra tenant, and you should run the validate-move operation first since not all resource types support moving. Offer types can differ, subscriptions aren't tied to a region, and resources never live in management groups. Also remember: a move never changes the resource's region.",
    },
    {
        "type": "mc",
        "q": "Contoso wants production and development workloads to receive completely separate invoices and separate vCPU quota pools. What should the admin create?",
        "choices": [
            "Two resource groups in one subscription",
            "Two management groups over one subscription",
            "Two separate subscriptions",
            "Two tags, Env=Prod and Env=Dev, with cost analysis",
        ],
        "answer": 2,
        "explain": "A subscription is the billing and access boundary: invoices and quotas (tracked per subscription, per region) roll up at that level, so separate invoices and quota pools require separate subscriptions. Resource groups and tags can only break down costs within one invoice, and management groups organize subscriptions rather than split billing.",
    },
    {
        "type": "mc",
        "q": "A team set a $5,000 monthly budget with an alert at 100%, yet spending reached $7,200 and deployments never stopped. What must be added so overspend triggers actual enforcement?",
        "choices": [
            "Raise the budget threshold to 150%",
            "Attach an action group that triggers automation, such as a runbook that shuts down VMs",
            "Switch the budget from actual to forecasted cost",
            "Apply a ReadOnly lock when creating the budget",
        ],
        "answer": 1,
        "explain": "Budgets alert but never stop or throttle spending on their own — spend sails past 100% unless you wire the alert to an action group that triggers Azure Automation runbooks, Logic Apps, or Functions to take hard action. Changing thresholds or forecast mode only changes when alerts fire, and budgets cannot apply locks.",
    },
    {
        "type": "mc",
        "q": "Management asks which VMs are underutilized and could be downsized or shut down to save money. Which tool answers this directly?",
        "choices": [
            "Cost Management cost analysis",
            "Azure Advisor's Cost recommendations",
            "A budget with a forecasted threshold",
            "Azure Policy compliance view",
        ],
        "answer": 1,
        "explain": "Azure Advisor analyzes your usage and issues free recommendations in five categories — Cost, Security, Reliability, Operational excellence, and Performance — and identifying idle or oversized VMs is squarely a Cost recommendation. Cost analysis shows where money went but doesn't recommend right-sizing, budgets only alert, and Policy reports compliance.",
    },
    {
        "type": "mc",
        "q": "Sixty subscriptions must all receive the same allowed-regions policy and the same Reader role assignment with the least administrative effort. What is the correct approach?",
        "choices": [
            "Assign the policy and role at a management group containing the subscriptions",
            "Script a loop that assigns them to each subscription individually",
            "Assign them at the resource group level in each subscription",
            "Create an initiative — initiatives automatically apply to all subscriptions",
        ],
        "answer": 0,
        "explain": "RBAC and Policy assigned at a management group inherit down to every subscription (and resource) beneath it — one assignment covers all sixty. Scripting per-subscription works but is not least-effort and drifts as subscriptions are added. An initiative bundles policies but still needs to be assigned at a scope; it doesn't self-propagate.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Tags applied to a resource group are automatically inherited by the resources inside it.",
        "answer": False,
        "explain": "Tags are not inherited by default — tagging rg-prod does nothing to the VMs inside it. To propagate tags downward you assign a built-in Azure Policy with the Modify effect (such as 'Inherit a tag from the resource group') plus a remediation task for existing resources.",
    },
    {
        "type": "tf",
        "q": "True or False: When actual spending crosses a budget's 100% threshold, Azure automatically blocks new deployments in that scope.",
        "answer": False,
        "explain": "Budgets are alert-only: crossing a threshold fires notifications, but spending continues unimpeded. Any enforcement — shutting down VMs, blocking deployments — must be wired up yourself via an action group triggering Automation runbooks, Logic Apps, or Functions.",
    },
    {
        "type": "tf",
        "q": "True or False: A user with the Owner role on a subscription is still blocked by an Azure Policy Deny effect assigned to that subscription.",
        "answer": True,
        "explain": "Policy controls WHAT can be deployed regardless of who is deploying, so a Deny effect blocks the request even for Owners. RBAC governs who can perform actions; the two systems are evaluated independently, and Policy cannot be out-ranked by any role.",
    },
    {
        "type": "tf",
        "q": "True or False: Deleting a resource group also deletes every resource contained within it, with no undo.",
        "answer": True,
        "explain": "The resource group is a lifecycle container — everything inside is deleted together when the group is deleted, and there is no recycle bin for the operation. This blast radius is exactly why production resource groups usually carry a CanNotDelete lock.",
    },
    {
        "type": "tf",
        "q": "True or False: A subscription can be placed under two management groups at the same time so it can receive two different policy sets.",
        "answer": False,
        "explain": "Every subscription (and every management group) has exactly one parent at a time — by default the tenant root management group until you move it. To layer multiple policy sets on one subscription, assign them at different levels of the same hierarchy branch and let inheritance stack them.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The Azure Policy effect that adds, updates, or removes properties or tags on resources — and requires a managed identity — is the ______ effect. (type your answer)",
        "answers": ["modify", "modify effect"],
        "explain": "Modify changes resource properties or tags during create/update and, via a remediation task, on existing resources — which is why its assignment needs a managed identity with appropriate RBAC roles. Append also adds fields at creation time but cannot fix existing resources and needs no identity.",
    },
    {
        "type": "fill",
        "q": "The resource lock level that blocks deletion while still allowing reads and modifications is ______. (type your answer)",
        "answers": ["cannotdelete", "can not delete", "delete", "delete lock", "cannotdelete lock"],
        "explain": "CanNotDelete (shown as a 'Delete' lock in the portal) is the answer to 'prevent accidental deletion but still allow changes.' Its sibling ReadOnly blocks deletes AND all writes — including POST operations like listing storage account keys.",
    },
    {
        "type": "fill",
        "q": "The maximum number of tags that can be applied to a single resource or resource group is ______. (type the number)",
        "answers": ["50", "fifty"],
        "explain": "Azure allows up to 50 tag name/value pairs per resource or resource group. Tags feed Cost Management cost analysis for chargeback and showback, which is why governance baselines usually require tags like CostCenter via policy.",
    },
    {
        "type": "fill",
        "q": "Excluding the tenant root and the subscription level, the management group hierarchy supports a maximum depth of ______ levels. (type the number)",
        "answers": ["6", "six", "six levels"],
        "explain": "The hierarchy supports six levels of depth, not counting the tenant root management group at the top or the subscription level at the bottom. Pair that with the other MG numbers: 10,000 management groups per Entra directory, and exactly one parent per MG or subscription.",
    },
    {
        "type": "fill",
        "q": "To switch the Azure CLI's active subscription context, run: az account ______ --subscription \"Production\". (type the missing subcommand)",
        "answers": ["set"],
        "explain": "az account set --subscription changes which subscription subsequent CLI commands target; az account list shows the available subscriptions. The PowerShell equivalents are Set-AzContext and Get-AzSubscription — the exam likes to pair the two toolchains.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each Azure Policy effect to its behavior.",
        "pairs": [
            ["Deny", "Blocks the create or update request outright"],
            ["Audit", "Allows the operation but flags the resource non-compliant"],
            ["Modify", "Adds or corrects properties/tags, using a managed identity"],
            ["DeployIfNotExists", "Deploys a missing related resource after creation"],
            ["Disabled", "Turns evaluation off, useful when testing a definition"],
        ],
        "explain": "Match the verb in the stem to the effect: prevent/block = Deny, report only = Audit, fix a tag or property = Modify, install the missing agent or setting = DeployIfNotExists, and switch evaluation off = Disabled. The two effects that DO something — Modify and DeployIfNotExists — are the two that need a managed identity and remediation.",
    },
    {
        "type": "match",
        "q": "Match each governance control to the job it performs.",
        "pairs": [
            ["Azure Policy", "Controls WHAT can be deployed, regardless of who deploys it"],
            ["RBAC", "Controls WHO can perform which actions at a scope"],
            ["Resource lock", "Blocks delete or write operations for everyone, even Owners"],
            ["Tags", "Name/value metadata used to group and report costs"],
            ["Management group", "Applies policy and roles across many subscriptions via inheritance"],
            ["Budget", "Alerts when actual or forecasted spend crosses a threshold"],
        ],
        "explain": "Each control owns one lane: Policy governs what, RBAC governs who, locks are the everyone-including-Owners safety switch, tags carry cost metadata into cost analysis, management groups scale assignments across subscriptions, and budgets watch spend but never stop it. Exam stems are solved by identifying which lane the requirement lives in.",
    },
    {
        "type": "match",
        "q": "Match each Azure CLI command to the administrative task it performs.",
        "pairs": [
            ["az policy assignment create", "Apply a policy definition or initiative at a scope"],
            ["az lock create --lock-type CanNotDelete", "Protect a scope from accidental deletion"],
            ["az tag update --operation Merge", "Add or update tags without erasing existing ones"],
            ["az resource move", "Transfer a resource to another resource group or subscription"],
            ["az account management-group create", "Create a new container above subscriptions for governance"],
        ],
        "explain": "AZ-104 is hands-on, so map the noun in each command to its service: policy assignment for governance rules, lock for deletion protection, tag update with Merge (never a blind replace) for metadata, resource move for re-homing resources, and account management-group for hierarchy building.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the Azure governance scopes from BROADEST to NARROWEST.",
        "items": [
            "Tenant root management group",
            "Child management group",
            "Subscription",
            "Resource group",
            "Resource",
        ],
        "explain": "The inheritance chain runs tenant root management group, then up to six levels of child management groups, then subscription, resource group, and finally the individual resource. RBAC and Policy assigned at any level flow down to everything beneath it, which is why broad guardrails are assigned high and team-specific settings low.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to make existing resources inherit the CostCenter tag from their resource group, from first to last.",
        "items": [
            "Apply the CostCenter tag to the resource group",
            "Assign the built-in 'Inherit a tag from the resource group' policy (Modify effect), which creates a managed identity",
            "Run a remediation task against the policy assignment",
            "Verify the previously untagged resources now show the CostCenter tag as compliant",
        ],
        "explain": "Because tags are not inherited by default, the tag must first exist on the resource group, then a Modify-effect policy (with its managed identity) is assigned to copy it down to new resources. Existing resources are only fixed when you run a remediation task — policy never retroactively changes anything on its own — and the compliance view confirms the result.",
    },
    {
        "type": "order",
        "q": "An Owner must delete a storage account protected by a lock inherited from its resource group. Arrange the steps from first to last.",
        "items": [
            "Identify the CanNotDelete lock on the resource group in the scope chain",
            "Confirm you hold Owner or User Access Administrator rights for Microsoft.Authorization/locks/*",
            "Remove the lock with az lock delete",
            "Delete the storage account",
            "Re-create the lock to keep protecting the remaining resources",
        ],
        "explain": "Locks bind everyone regardless of RBAC role, so even an Owner must remove the lock before deleting — and since locks inherit, the blocking lock may sit at the resource group or subscription rather than on the resource itself. Managing locks requires Microsoft.Authorization/locks/* permissions (Owner or User Access Administrator), and good hygiene restores the lock afterward.",
    },
]
