TOPIC = {
    "id": "2.1",
    "domain": 2,
    "title": "Configure access to storage.",
    "short": "Storage Access & Security",
}

TERMS = [
    ("Azure Storage firewall", "Per-account network ACL that decides which sources may reach the public endpoint, via the public network access setting plus VNet and IP rules"),
    ("Public network access", "Account-level setting with three modes: Enabled from all networks, Enabled from selected virtual networks and IP addresses, or Disabled"),
    ("Virtual network rule", "Firewall rule that admits a specific subnet; requires the Microsoft.Storage service endpoint enabled on that subnet"),
    ("Service endpoint (Microsoft.Storage)", "Subnet feature that routes storage traffic over the Azure backbone and presents the subnet's identity to the storage firewall"),
    ("IP network rule", "Firewall rule that admits public Internet IPv4 addresses or CIDR ranges only — private RFC 1918 ranges are rejected"),
    ("Trusted services exception", "Firewall bypass ('Allow Azure services on the trusted services list') letting first-party services like Azure Backup through despite deny rules"),
    ("Private endpoint", "Azure Private Link NIC that gives the storage account a private IP inside your VNet and bypasses the public firewall entirely"),
    ("Shared access signature (SAS)", "Signed URI query string delegating limited, time-boxed access to storage resources without exposing the account keys"),
    ("Account SAS", "SAS signed with a storage account key that can span the blob, file, queue, and table services plus service-level operations"),
    ("Service SAS", "Key-signed SAS scoped to a single resource in one service; the only SAS type that can reference a stored access policy"),
    ("User delegation SAS", "SAS signed with Microsoft Entra credentials via a user delegation key — blob service only, 7-day maximum lifetime, most secure"),
    ("User delegation key", "Entra-issued signing key used to create user delegation SAS tokens; revoking it invalidates the tokens it signed"),
    ("Stored access policy", "Named set of SAS parameters (start, expiry, permissions) defined on a container, share, queue, or table — up to 5 per resource — that makes service SAS tokens revocable"),
    ("Access keys (key1/key2)", "Two 512-bit keys per storage account, either granting full Shared Key authorization to all data in the account; two exist to allow zero-downtime rotation"),
    ("Shared Key authorization", "Authorization scheme where requests are signed with an account access key — unscoped root-level data access that RBAC does not constrain"),
    ("Key expiration policy", "Account setting (--key-exp-days) that sets a maximum key age and surfaces rotation reminders and compliance signals when keys go stale"),
    ("Key Vault-managed storage keys", "Pattern where Azure Key Vault stores and automatically regenerates the account keys on a schedule so applications never hard-code them"),
    ("Allow storage account key access", "Account-level switch that, when Disabled, rejects all Shared Key requests — including account and service SAS signed by the keys — forcing Entra authorization"),
    ("Identity-based authentication (Azure Files)", "Kerberos-based SMB access to file shares using directory identities instead of the shared account key, enforced through three stacked layers"),
    ("On-premises AD DS integration", "Azure Files identity source for domain-joined clients with line of sight to on-prem domain controllers; account joined via the AzFilesHybrid module"),
    ("Microsoft Entra Domain Services", "Managed domain identity source for Azure Files in cloud-only environments with no on-premises Active Directory"),
    ("Microsoft Entra Kerberos", "Identity source where Entra ID issues Kerberos tickets directly for hybrid identities on Entra-joined devices that cannot reach a domain controller"),
    ("Storage File Data SMB Share Elevated Contributor", "Built-in role granting read, write, delete, and the ability to modify Windows ACLs on an Azure Files share"),
    ("icacls", "Windows command-line tool used to set file- and directory-level NTFS ACLs on a mounted Azure Files share"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An admin must restrict a storage account so only VMs in subnet app-subnet of vnet1 can reach its public endpoint. Besides adding a virtual network rule on the account, what must be configured on the subnet?",
        "choices": [
            "A NAT gateway to give the subnet a static egress IP",
            "The Microsoft.Storage service endpoint",
            "A private endpoint network interface",
            "The Microsoft.KeyVault service endpoint",
        ],
        "answer": 1,
        "explain": "Virtual network rules ride on service endpoints: the subnet needs the Microsoft.Storage service endpoint so its storage traffic travels the Azure backbone and presents the subnet's identity to the firewall. A NAT gateway would only change the source IP, a private endpoint is a different (bypass) mechanism, and Microsoft.KeyVault is the wrong service.",
    },
    {
        "type": "mc",
        "q": "An intern tries to add 10.1.0.0/16 to a storage account firewall's IP rules and Azure rejects it. Why?",
        "choices": [
            "The range is too large; rules accept /24 or smaller",
            "IP rules require IPv6 addresses",
            "IP rules accept public IPv4 ranges only — private RFC 1918 addresses are rejected",
            "The subnet must first enable a service endpoint",
        ],
        "answer": 2,
        "explain": "IP network rules take public Internet IPv4 addresses or CIDR ranges only. Traffic from inside Azure or over a service endpoint never arrives with a private source IP the firewall could match, so private ranges like 10.0.0.0/8 are rejected outright — use a VNet rule or private endpoint for internal sources instead.",
    },
    {
        "type": "mc",
        "q": "After an admin sets a storage account's firewall default action to Deny, nightly Azure Backup jobs against the account start failing. What is the least-privilege fix?",
        "choices": [
            "Enable the 'Allow Azure services on the trusted services list' exception",
            "Set public network access back to Enabled from all networks",
            "Add every Azure datacenter IP range as IP rules",
            "Give the Backup service the storage account key",
        ],
        "answer": 0,
        "explain": "The trusted services exception lets first-party services such as Azure Backup, Azure Site Recovery, and Log Analytics through the firewall without listing their IPs. Reopening the account to all networks abandons the lockdown, datacenter IP lists are unmanageable and overly broad, and handing out the account key grants root-level data access.",
    },
    {
        "type": "mc",
        "q": "A security baseline demands that a storage account be completely unreachable from the Internet while apps in a VNet keep working. Which configuration satisfies it?",
        "choices": [
            "Public network access Enabled from selected networks, with no rules listed",
            "An IP rule allowing only 0.0.0.0/32",
            "The trusted services exception with default action Deny",
            "Public network access Disabled, with a private endpoint in the VNet",
        ],
        "answer": 3,
        "explain": "Maximum lockdown is public network access Disabled — the public endpoint refuses all traffic — combined with a private endpoint that gives the account a private IP inside the VNet. Selected-networks mode with exceptions still leaves the public endpoint answering, and IP rules only shape who gets through it.",
    },
    {
        "type": "mc",
        "q": "A storage account's firewall default action is Deny with no network rules, yet an app in a spoke VNet still reads blobs successfully. What explains this?",
        "choices": [
            "Deny takes 24 hours to propagate",
            "The app connects through a private endpoint, which bypasses the public firewall",
            "The app authenticates with Microsoft Entra, which skips firewall checks",
            "Blob reads are exempt from firewall rules; only writes are filtered",
        ],
        "answer": 1,
        "explain": "Firewall rules govern only the public endpoint. A private endpoint gives the account a private IP inside the VNet and its traffic ignores the public firewall entirely, so deny-all does not block it. Authorization method (Entra vs. key) never exempts anyone from network rules, and reads and writes are filtered alike.",
    },
    {
        "type": "mc",
        "q": "A subnet already has the Microsoft.Storage service endpoint enabled. Which Azure CLI command actually admits that subnet through the storage account's firewall?",
        "choices": [
            "az network vnet subnet update --service-endpoints Microsoft.Storage",
            "az storage account update --bypass AzureServices",
            "az storage account network-rule add --vnet-name vnet1 --subnet subnet1",
            "az storage account private-endpoint-connection approve",
        ],
        "answer": 2,
        "explain": "Enabling the service endpoint only prepares the subnet; the storage account still needs a virtual network rule, added with az storage account network-rule add. The subnet update command is the prerequisite already done, --bypass configures the trusted services exception, and private endpoint approval belongs to a different connectivity model.",
    },
    {
        "type": "mc",
        "q": "A nightly batch job needs one token that reads blobs, writes queue messages, and lists tables in the same storage account. Which SAS type is required?",
        "choices": [
            "Service SAS",
            "User delegation SAS",
            "Stored access policy",
            "Account SAS",
        ],
        "answer": 3,
        "explain": "Only an account SAS can span multiple services (blob, file, queue, table) and service-level operations in one token. A service SAS is scoped to a single resource in one service, a user delegation SAS covers the blob service only, and a stored access policy is a server-side parameter set, not a token type.",
    },
    {
        "type": "mc",
        "q": "A partner needs read/list access to one blob container for six months, and legal insists the access must be revocable at any time without regenerating account keys. What should you issue?",
        "choices": [
            "An account SAS restricted to the blob service",
            "A service SAS on the container tied to a stored access policy",
            "A user delegation SAS on the container",
            "The storage account's key2, to be rotated when access ends",
        ],
        "answer": 1,
        "explain": "Only a service SAS can reference a stored access policy, and editing or deleting that policy immediately revokes every token tied to it — no key regeneration needed. An account SAS is irrevocable except by key rotation, a user delegation SAS is capped at 7 days (too short for six months), and sharing a key is root-level access.",
    },
    {
        "type": "mc",
        "q": "A security mandate states that delegated blob access must never involve the storage account keys in any way. Which SAS type complies?",
        "choices": [
            "User delegation SAS",
            "Service SAS",
            "Account SAS",
            "Service SAS backed by a stored access policy",
        ],
        "answer": 0,
        "explain": "A user delegation SAS is signed with Microsoft Entra credentials via a user delegation key, so no account key ever touches the process — Microsoft's recommended, most secure SAS. Account SAS and service SAS (with or without a stored access policy) are both signed with an account key, violating the mandate.",
    },
    {
        "type": "mc",
        "q": "A colleague plans to issue a user delegation SAS granting 30 days of access to an Azure Files share. Why must the plan change?",
        "choices": [
            "User delegation SAS requires the account key to sign",
            "User delegation SAS cannot be restricted to HTTPS",
            "User delegation SAS covers the blob service only and is capped at 7 days",
            "User delegation SAS must reference a stored access policy first",
        ],
        "answer": 2,
        "explain": "User delegation SAS has two hard limits: it works only against the blob service (blobs and containers), and its maximum lifetime is 7 days — so neither the Azure Files target nor the 30-day window is possible. It is signed with Entra credentials rather than a key, supports HTTPS-only, and cannot use stored access policies at all.",
    },
    {
        "type": "mc",
        "q": "A service SAS that was NOT tied to any stored access policy has leaked on a public forum. What is the only way to kill it immediately?",
        "choices": [
            "Delete all stored access policies on the container",
            "Remove the RBAC roles of whoever created it",
            "Use the portal's 'Revoke SAS' button on the container blade",
            "Regenerate the account key that signed it, invalidating every SAS signed with that key",
        ],
        "answer": 3,
        "explain": "A SAS is a self-contained signed token with no revocation list, so a non-policy-backed token can only be invalidated by regenerating its signing key — collateral damage to every other SAS that key signed. There is no revoke button, policies it never referenced are irrelevant, and RBAC removal only affects user delegation SAS signers.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command produces a SAS signed with the admin's Microsoft Entra login rather than an account key?",
        "choices": [
            "az storage blob generate-sas --auth-mode login --as-user",
            "az storage account generate-sas --services b --resource-types co",
            "az storage container generate-sas --policy-name partner-read",
            "az storage blob generate-sas --account-key $KEY",
        ],
        "answer": 0,
        "explain": "Passing --auth-mode login --as-user to az storage blob generate-sas requests a user delegation key from Entra and signs the SAS with it — no account key involved. The account-level generate-sas and any command supplying --account-key produce key-signed tokens, and a policy-backed container SAS is still a key-signed service SAS.",
    },
    {
        "type": "mc",
        "q": "SAS URLs for the contracts container are already in partners' hands when legal orders the access window cut from 90 days to 30. The tokens reference a stored access policy. What do you do?",
        "choices": [
            "Regenerate key1 and reissue all tokens",
            "Edit the stored access policy's expiry — every issued token honors the change",
            "Email partners replacement SAS URLs with the shorter expiry",
            "Enable the storage firewall to block the old tokens",
        ],
        "answer": 1,
        "explain": "The service re-reads the stored access policy on every request, so shrinking the policy's expiry (or permissions) instantly retimes every SAS tied to it — no reissuing, no key rotation. Regenerating keys is the blunt fallback for non-policy tokens, new emails don't invalidate the old links, and the firewall filters networks, not tokens.",
    },
    {
        "type": "mc",
        "q": "Which SAS type is the ONLY one that can reference a stored access policy?",
        "choices": [
            "Account SAS",
            "User delegation SAS",
            "Any SAS created in the Azure portal",
            "Service SAS",
        ],
        "answer": 3,
        "explain": "Stored access policies live on a specific resource (container, share, queue, or table) and only service SAS tokens can be issued against them. Account SAS and user delegation SAS embed all their parameters in the token, which is exactly why they cannot be revoked or modified through a policy afterward.",
    },
    {
        "type": "mc",
        "q": "Seconds after you delete a stored access policy to revoke partner access, a partner reports their SAS link still downloads files. What explains it?",
        "choices": [
            "Deleting a policy never affects tokens that were already issued",
            "The browser cached the blob for 24 hours",
            "Policy changes can take up to about 30 seconds to propagate",
            "The SAS must also be deleted from the container's metadata",
        ],
        "answer": 2,
        "explain": "Stored access policy changes — including deletion — can take up to roughly 30 seconds to take effect, so revoked tokens may work briefly. Deleting the policy absolutely does revoke its tokens once propagated; that after-the-fact control is the whole point of policies. There is no SAS list in container metadata to purge.",
    },
    {
        "type": "mc",
        "q": "All applications currently authenticate with key1 in their connection strings. Security requires rotating both storage keys this quarter with zero application downtime. What is the first move?",
        "choices": [
            "Update the applications to use key2, then regenerate key1",
            "Regenerate key1 immediately, then update the applications",
            "Disable shared key access so rotation is unnecessary",
            "Issue user delegation SAS tokens to the applications",
        ],
        "answer": 0,
        "explain": "The two-key dance is: repoint apps to key2, then regenerate key1 while nothing depends on it, then swap back at the next cycle to refresh key2. Regenerating key1 first breaks every app instantly, disabling shared key access breaks them even harder, and moving to SAS is an architecture change, not a rotation procedure.",
    },
    {
        "type": "mc",
        "q": "Compliance requires that storage account keys rotate automatically on a schedule and that applications never store the keys in configuration. Which solution fits?",
        "choices": [
            "Set a key expiration policy with az storage account update --key-exp-days 90",
            "Register the storage account with Azure Key Vault to manage and regenerate the keys",
            "Schedule an Azure Automation runbook that emails the new keys to app owners",
            "Enable the trusted services exception on the account firewall",
        ],
        "answer": 1,
        "explain": "Key Vault-managed storage keys have the vault store and automatically regenerate the account keys on a schedule; applications fetch keys or vault-issued SAS tokens at runtime and never hard-code them. A key expiration policy only surfaces reminders and compliance signals — it rotates nothing — and emailing keys is the anti-pattern being eliminated.",
    },
    {
        "type": "mc",
        "q": "An admin sets 'Allow storage account key access' to Disabled on a hardened account. Which of these continues to work?",
        "choices": [
            "An account SAS signed with key1",
            "A service SAS on the contracts container",
            "Mounting an Azure Files share with the account key",
            "A user delegation SAS on a blob",
        ],
        "answer": 3,
        "explain": "Disabling shared key access rejects every request authorized by the keys — including account SAS and service SAS, which the keys signed — forcing Microsoft Entra authorization. A user delegation SAS keeps working because it is signed with Entra credentials and never touched a key. This is the classic 'why did the app break' stem.",
    },
    {
        "type": "mc",
        "q": "A user holds only the Reader RBAC role on a storage account but obtained key1 from an old runbook. What data access do they effectively have?",
        "choices": [
            "Read-only, because RBAC caps what the key can do",
            "None, because Reader is a control-plane role",
            "Full access to all data in the account — keys ignore RBAC entirely",
            "Full access to blobs only",
        ],
        "answer": 2,
        "explain": "Access keys grant unscoped Shared Key authorization to the entire account's data plane, and RBAC does not constrain them — anyone holding a key has full data access regardless of their roles. That root-level blast radius is why key distribution is minimized and why hardened accounts disable shared key access outright.",
    },
    {
        "type": "mc",
        "q": "Remote employees on Entra-joined laptops — with identities synced from on-prem AD DS but no VPN line of sight to any domain controller — must access an Azure Files SMB share with their own logins. Which identity source do you enable?",
        "choices": [
            "On-premises AD DS integration via the AzFilesHybrid module",
            "Microsoft Entra Kerberos",
            "Microsoft Entra Domain Services",
            "Shared Key authorization with the account key",
        ],
        "answer": 1,
        "explain": "Entra Kerberos has Entra ID issue Kerberos tickets directly for hybrid identities, so Entra-joined or hybrid-joined clients authenticate without ever reaching a domain controller — exactly this remote-worker shape. AD DS integration requires DC line of sight, Entra Domain Services targets cloud-only environments with domain-joined VMs, and the account key is the shared-secret model being replaced.",
    },
    {
        "type": "mc",
        "q": "On an identity-enabled Azure Files share, a help-desk lead must edit folder permissions from the Security tab of a mounted drive. Which built-in role does that require?",
        "choices": [
            "Storage File Data SMB Share Elevated Contributor",
            "Storage File Data SMB Share Contributor",
            "Storage File Data SMB Share Reader",
            "Storage Blob Data Owner",
        ],
        "answer": 0,
        "explain": "Modifying Windows ACLs over SMB is the extra power that Elevated Contributor adds on top of read/write/delete. Plain Contributor can change files but not their ACLs, Reader is read-only, and Storage Blob Data Owner is a blob-service role that has nothing to do with SMB shares.",
    },
    {
        "type": "mc",
        "q": "An audit finds a service account with NO share-level RBAC role and no ACL entries read every file on an identity-enabled Azure Files share. How?",
        "choices": [
            "The share's NTFS ACLs defaulted to Everyone:Full Control",
            "Entra Kerberos grants implicit read to all synced identities",
            "RBAC roles take 24 hours to enforce on file shares",
            "It mounted the share with the storage account key, which bypasses RBAC and ACLs",
        ],
        "answer": 3,
        "explain": "The account key is a superuser back door: mounting with it ignores both the share-level RBAC layer and the NTFS ACL layer, granting unrestricted access to the whole share. That is exactly why hardened designs set 'Allow storage account key access' to Disabled once identity-based auth is proven. No identity source grants implicit access, and RBAC enforcement is not delayed by a day.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Traffic arriving through a private endpoint is still filtered by the storage account firewall's IP and virtual network rules.",
        "answer": False,
        "explain": "Firewall rules apply only to the public endpoint. A private endpoint gives the account a private IP inside your VNet and its traffic bypasses the public firewall entirely — even a default action of Deny does not block it. Controlling private-endpoint traffic is a job for NSGs and Private Link configuration instead.",
    },
    {
        "type": "tf",
        "q": "True or False: A user delegation SAS can be issued for an Azure Files share.",
        "answer": False,
        "explain": "User delegation SAS is restricted to the blob service — blobs and containers only. For files, queues, or tables you need a service SAS or an account SAS, both signed with an account key. This blob-only limit plus the 7-day lifetime cap are the two constraints the exam checks.",
    },
    {
        "type": "tf",
        "q": "True or False: Regenerating key1 immediately invalidates every account SAS and service SAS that was signed with key1.",
        "answer": True,
        "explain": "SAS validation just checks the signature against the current keys, so renewing key1 orphans every token it signed — legitimate and leaked alike — and any app still holding the old key fails at once. That ripple effect is why the two-key rotation pattern repoints apps to key2 before touching key1.",
    },
    {
        "type": "tf",
        "q": "True or False: An account SAS can be tied to a stored access policy so it can be revoked later.",
        "answer": False,
        "explain": "Stored access policies work exclusively with service SAS tokens; account SAS and user delegation SAS cannot reference them. An account SAS is therefore revocable only by regenerating its signing key — which is why revocation-sensitive scenarios always steer toward a policy-backed service SAS.",
    },
    {
        "type": "tf",
        "q": "True or False: With identity-based access to Azure Files, a user's effective permission is the intersection of their share-level RBAC role and the file's NTFS ACL.",
        "answer": True,
        "explain": "The share-level RBAC role is the ceiling and the NTFS ACLs refine below it — a user needs both a role that permits the operation and an ACL that allows it on that file or folder. A Contributor role with a deny ACL gets nothing, and a generous ACL cannot exceed a Reader role.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Before a subnet can be used in a storage account virtual network rule, the ______ service endpoint must be enabled on that subnet. (type the endpoint name)",
        "answers": ["microsoft.storage", "microsoft storage", "microsoftstorage"],
        "explain": "The Microsoft.Storage service endpoint routes the subnet's storage traffic over the Azure backbone and presents the subnet's VNet identity to the firewall, which is what a virtual network rule matches on. Without it, the rule cannot admit the subnet.",
    },
    {
        "type": "fill",
        "q": "A single blob container supports a maximum of ______ stored access policies. (type the number)",
        "answers": ["5", "five"],
        "explain": "The limit is 5 stored access policies per container, and the same cap applies per file share, queue, and table. Plan policy names around groups of consumers rather than one policy per token, because you cannot exceed five.",
    },
    {
        "type": "fill",
        "q": "The maximum lifetime of a user delegation SAS is ______ days. (type the number)",
        "answers": ["7", "seven", "7 days"],
        "explain": "A user delegation SAS is capped at 7 days because the Entra-issued user delegation key that signs it lives at most that long. Longer delegation windows require a key-signed SAS — ideally a service SAS backed by a stored access policy so it stays revocable.",
    },
    {
        "type": "fill",
        "q": "The Windows command-line tool used to set file- and directory-level NTFS permissions on a mounted Azure Files share is ______. (type your answer)",
        "answers": ["icacls", "icacls.exe"],
        "explain": "icacls (or File Explorer's Security tab) manages the third layer of identity-based Azure Files access: NTFS-style ACLs on folders and files. It runs from a mounted client after the identity source is enabled and share-level RBAC is assigned.",
    },
    {
        "type": "fill",
        "q": "Complete the Azure CLI command that regenerates a storage account access key: az storage account keys ______ --key key1. (type the subcommand)",
        "answers": ["renew", "keys renew", "az storage account keys renew"],
        "explain": "az storage account keys renew regenerates the named key (key1 or key2); its PowerShell twin is New-AzStorageAccountKey -KeyName key1. Remember the side effect: renewal instantly invalidates every account and service SAS signed with that key.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each SAS-related item to its defining characteristic.",
        "pairs": [
            ["Account SAS", "Key-signed; can span the blob, file, queue, and table services in one token"],
            ["Service SAS", "Key-signed; scoped to a single resource and the only type that can reference a policy"],
            ["User delegation SAS", "Signed with Microsoft Entra credentials; blob-only with a 7-day maximum"],
            ["Stored access policy", "Named server-side parameter set that makes issued tokens revocable and editable"],
        ],
        "explain": "Sort by signer and scope: account SAS and service SAS are both account-key-signed but differ in breadth (many services vs. one resource), while user delegation SAS swaps the key for Entra credentials at the cost of blob-only scope and a 7-day cap. The stored access policy is not a token — it is the server-side lever that makes service SAS manageable.",
    },
    {
        "type": "match",
        "q": "Match each network-access requirement to the storage firewall mechanism that satisfies it.",
        "pairs": [
            ["Allow only a specific subnet through the firewall", "Virtual network rule (subnet needs the Microsoft.Storage service endpoint)"],
            ["Allow the office's public IP range", "IP network rule with a public CIDR"],
            ["Let Azure Backup work despite default-deny", "'Allow Azure services on the trusted services list' exception"],
            ["Give the account a private IP that ignores the public firewall", "Private endpoint (Azure Private Link)"],
            ["Refuse all traffic at the public endpoint", "Public network access set to Disabled"],
        ],
        "explain": "Map the phrase to the mechanism: subnets ride VNet rules over service endpoints, public office ranges use IP rules (never private RFC 1918 space), first-party services use the trusted services exception, and private endpoints sidestep the public firewall entirely — with Disabled shutting the public door for good.",
    },
    {
        "type": "match",
        "q": "Match each Azure Files identity or permission element to its description.",
        "pairs": [
            ["On-premises AD DS", "Domain-joined clients with line of sight to on-prem domain controllers"],
            ["Microsoft Entra Domain Services", "Cloud-only environments with no on-premises Active Directory"],
            ["Microsoft Entra Kerberos", "Hybrid identities on Entra-joined devices that cannot reach a DC"],
            ["Storage File Data SMB Share Elevated Contributor", "Share-level role that can also modify Windows ACLs"],
            ["icacls", "Tool for file/directory-level NTFS permissions on a mounted share"],
        ],
        "explain": "Choose the identity source by the clients: DC-reachable domain members use AD DS, cloud-only shops use Entra Domain Services, and DC-less hybrid users use Entra Kerberos (hybrid identities only). Then remember the layers above the source: share-level RBAC roles set the ceiling and icacls-managed NTFS ACLs refine beneath it.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the zero-downtime storage key rotation procedure in order, starting from applications using key1.",
        "items": [
            "Repoint all applications from key1 to key2",
            "Regenerate key1 with az storage account keys renew --key key1",
            "At the next rotation cycle, repoint applications to the fresh key1",
            "Regenerate key2",
        ],
        "explain": "Two keys exist precisely so one can be regenerated while the other carries traffic: move apps off key1, renew it safely, then alternate at the next cycle to refresh key2. Renewing a key that apps still use causes an instant outage, because every request and SAS signed with the old key fails immediately.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to give users identity-based, least-privilege access to an Azure Files SMB share, from first to last.",
        "items": [
            "Enable one identity source (AD DS, Entra Domain Services, or Entra Kerberos) on the storage account",
            "Assign a share-level RBAC role such as Storage File Data SMB Share Contributor",
            "Mount the share from an authorized client",
            "Refine file and folder permissions with NTFS ACLs via icacls",
        ],
        "explain": "The three layers stack in strict order: an identity source must exist before RBAC roles mean anything, and share-level RBAC sets the ceiling before NTFS ACLs refine below it. ACL editing happens from a mounted client, which itself requires the earlier layers (or the account key, the superuser bypass hardened designs disable).",
    },
    {
        "type": "order",
        "q": "Arrange the lifecycle of revocable partner access to a blob container using SAS, from setup to early termination.",
        "items": [
            "Create a stored access policy on the container with permissions and expiry",
            "Generate a service SAS that references the policy by name",
            "Distribute the SAS URLs to the partner",
            "When access must end early, edit or delete the stored access policy",
            "Allow up to about 30 seconds for the change to propagate",
        ],
        "explain": "The policy must exist before tokens can reference it, and because the service re-reads the policy on every request, editing or deleting it later revokes every distributed URL at once — no key regeneration, no reissuing. The only caveat is the propagation window of up to roughly 30 seconds during which revoked tokens may still work.",
    },
]
