TOPIC = {
    "id": "2.2",
    "domain": 2,
    "title": "Configure and manage storage accounts.",
    "short": "Storage Accounts",
}

TERMS = [
    ("Storage account", "Top-level Azure resource containing blobs, files, queues, and tables where performance, redundancy, networking, and encryption are configured"),
    ("Standard general-purpose v2", "The default HDD-backed account type supporting blobs, files, queues, and tables with every redundancy option"),
    ("Premium block blobs", "SSD-backed account type for block/append blobs with high transaction rates and low latency — LRS/ZRS only"),
    ("Premium file shares", "SSD-backed account type dedicated to performance-critical SMB and NFS Azure Files shares — LRS/ZRS only"),
    ("Premium page blobs", "SSD-backed account type for random read/write page-blob workloads — LRS only"),
    ("Performance tier", "The Standard-vs-Premium choice made at account creation that can never be changed afterwards"),
    ("Endpoint", "The public DNS URL of an account service, e.g. <account>.blob.core.windows.net, which is why account names must be globally unique"),
    ("Locally redundant storage (LRS)", "Three synchronous copies in a single datacenter — 11 nines of durability, cheapest option"),
    ("Zone-redundant storage (ZRS)", "Three copies spread across three availability zones in one region — 12 nines, survives a zone outage"),
    ("Geo-redundant storage (GRS)", "LRS in the primary region plus asynchronous LRS in the paired secondary — six copies, 16 nines"),
    ("Geo-zone-redundant storage (GZRS)", "ZRS in the primary region plus LRS in the secondary — six copies, 16 nines, survives zone and regional failures"),
    ("RA-GRS / RA-GZRS", "Geo-redundant options whose secondary region is always readable at <account>-secondary.blob.core.windows.net without a failover"),
    ("Redundancy conversion", "The customer-initiated or manual-migration process required for any redundancy change into or out of ZRS"),
    ("Customer-initiated failover", "Promoting the secondary region to primary; un-replicated writes are lost and the account drops to LRS afterwards"),
    ("Last Sync Time", "Account property showing how far geo-replication lags — checked before a failover to measure potential data loss"),
    ("Object replication", "Asynchronous, rule-based copying of block blobs from containers in a source account to containers in a destination account"),
    ("Blob versioning", "Prerequisite feature that must be enabled on BOTH the source and destination accounts before object replication works"),
    ("Change feed", "Ordered log of blob changes that must be enabled on the SOURCE account so object replication can detect writes"),
    ("Storage Service Encryption (SSE)", "Always-on, non-disableable server-side encryption of all Azure Storage data using 256-bit AES"),
    ("Customer-managed keys (CMK)", "Encryption keys you control in Azure Key Vault; the account's managed identity needs wrap/unwrap permission on the vault"),
    ("Customer-provided keys", "Encryption keys the client supplies on each request via REST headers — blob storage only, never stored by Azure"),
    ("Infrastructure encryption", "A second, independent layer of encryption (double encryption) that can only be enabled when the account is created"),
    ("Encryption scope", "A key boundary applied per container or per blob so different projects use different keys inside one account"),
    ("Azure Storage Explorer", "Free cross-platform GUI (Windows, macOS, Linux) for browsing and managing storage data; uses AzCopy under the hood"),
    ("AzCopy", "Command-line utility for high-performance, scriptable, resumable data transfer to blob and file endpoints"),
    ("azcopy sync", "One-directional AzCopy command that makes the destination match the source — never the reverse"),
    ("azcopy jobs resume", "AzCopy command that continues an interrupted transfer from where it left off"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An admin must create one storage account to host blobs, SMB file shares, queues, and tables for a typical line-of-business app with no special latency needs. Which account type should be selected?",
        "choices": ["Premium block blobs", "Standard general-purpose v2", "Premium file shares", "Premium page blobs"],
        "answer": 1,
        "explain": "Standard general-purpose v2 is the default: it is the only account type that supports all four services (blobs, files, queues, tables) and every redundancy option. The Premium types are SSD-backed but each serves only one data shape and tops out at LRS/ZRS, so none can hold all four services.",
    },
    {
        "type": "mc",
        "q": "A trading application needs an NFS file share with consistently low latency. Which storage account type must the admin create?",
        "choices": ["Standard general-purpose v2", "Premium block blobs", "Premium file shares", "Premium page blobs"],
        "answer": 2,
        "explain": "NFS shares in Azure Files require a Premium file shares (FileStorage) account, which is SSD-backed for performance-critical SMB and NFS workloads. Premium block blobs serves block blobs, Premium page blobs serves page blobs, and Standard GPv2 is HDD-backed and does not offer NFS file shares.",
    },
    {
        "type": "mc",
        "q": "An admin creating a Premium block blobs account notices geo-redundant options are missing from the redundancy dropdown. Why?",
        "choices": [
            "Geo-redundancy requires a support ticket for premium accounts",
            "Premium storage accounts support only LRS and ZRS",
            "The selected region has no paired region",
            "Geo-redundancy is only available after the account is created",
        ],
        "answer": 1,
        "explain": "All premium account types are limited to LRS and ZRS (Premium page blobs is LRS only) — geo-redundant options like GRS and GZRS exist only for Standard general-purpose v2. This is by design, not a regional or support limitation, so if a scenario needs both SSD performance and geo-redundancy you must architect around it (e.g., object replication or AzCopy to another account).",
    },
    {
        "type": "mc",
        "q": "An admin tries to create a storage account named 'Contoso-Backup01' and the portal rejects it. What must change?",
        "choices": [
            "Shorten the name to under 15 characters",
            "Remove the uppercase letters and the hyphen",
            "Add the region as a suffix to make it unique",
            "Prefix the name with the subscription ID",
        ],
        "answer": 1,
        "explain": "Storage account names must be 3-24 characters of lowercase letters and numbers only, so 'Contoso-Backup01' fails on both the capitals and the hyphen. The name must also be globally unique across all of Azure because it becomes the DNS prefix of the account's endpoints, but the immediate rejection here is the character rules.",
    },
    {
        "type": "mc",
        "q": "A Standard general-purpose v2 account must be converted to Premium block blobs to meet a new latency requirement. What should the admin do?",
        "choices": [
            "Run az storage account update with the new SKU",
            "Change the performance tier on the account's Configuration blade",
            "Create a new Premium block blobs account and copy the data with AzCopy",
            "Open a support request to migrate the account in place",
        ],
        "answer": 2,
        "explain": "The performance tier (Standard vs. Premium) is fixed at creation and can never be changed — not by CLI, portal, or support. The only path is to create a new Premium account and migrate the data, typically with AzCopy. Redundancy SKUs within the same tier can be updated, but not the tier itself.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command creates a general-purpose v2 storage account with geo-zone-redundant storage?",
        "choices": [
            "az storage account create --kind StorageV2 --sku Standard_GZRS",
            "az storage create --type gpv2 --redundancy gzrs",
            "az storage account new --kind BlobStorage --replication GZRS",
            "az storage account create --kind FileStorage --sku Premium_GZRS",
        ],
        "answer": 0,
        "explain": "The command is az storage account create, with --kind StorageV2 for general-purpose v2 and the redundancy expressed as the SKU (Standard_GZRS). There is no 'az storage create' or 'az storage account new' command, and FileStorage is the premium file shares kind, which cannot use GZRS anyway.",
    },
    {
        "type": "mc",
        "q": "Which PowerShell cmdlet does an admin run to create a new storage account?",
        "choices": ["Set-AzStorageAccount", "New-AzStorageAccount", "Add-AzStorageContainer", "New-AzStorageContext"],
        "answer": 1,
        "explain": "New-AzStorageAccount creates the account, taking parameters like -Kind StorageV2, -SkuName Standard_GZRS, and -AccessTier. Set-AzStorageAccount modifies an existing account, New-AzStorageContext builds a client-side authentication object, and Add-AzStorageContainer is not the account-creation cmdlet.",
    },
    {
        "type": "mc",
        "q": "Which storage account setting CANNOT be changed after the account is created?",
        "choices": [
            "The redundancy SKU (e.g., LRS to GRS)",
            "The default access tier",
            "The minimum TLS version",
            "Infrastructure (double) encryption",
        ],
        "answer": 3,
        "explain": "Infrastructure encryption, like the performance tier and the account name, can only be set at creation — if double encryption is required later, you must create a new account. Redundancy, the default access tier, TLS minimum, and encryption key source are all changeable on an existing account, though some redundancy paths need a conversion.",
    },
    {
        "type": "mc",
        "q": "Compliance requires data to survive the loss of an entire datacenter but forbids it from ever leaving the region. Which redundancy option should the admin configure?",
        "choices": ["LRS", "ZRS", "GRS", "RA-GRS"],
        "answer": 1,
        "explain": "ZRS keeps three copies across three availability zones in one region (12 nines), so a whole zone or datacenter can fail without data loss while the data stays in-region. LRS's three copies sit in a single datacenter, and GRS/RA-GRS replicate to a paired secondary region, violating the residency requirement.",
    },
    {
        "type": "mc",
        "q": "How many total copies of the data does a GZRS storage account maintain, and how are they laid out?",
        "choices": [
            "Three copies across three availability zones in one region",
            "Six copies — ZRS across the primary region's zones plus LRS in the secondary region",
            "Six copies — ZRS in both the primary and secondary regions",
            "Twelve copies — three per zone in both regions",
        ],
        "answer": 1,
        "explain": "GZRS is ZRS in the primary (three copies across three zones) plus asynchronous LRS in the paired secondary (three more copies in one datacenter) for six total and 16 nines of durability. The common trap is assuming the secondary is also zone-redundant — it is not; it is LRS.",
    },
    {
        "type": "mc",
        "q": "A reporting job must read blob data from the secondary region during normal operations, without ever triggering a failover. Which is the least expensive redundancy option that supports this?",
        "choices": ["GRS", "RA-GRS", "GZRS", "RA-GZRS"],
        "answer": 1,
        "explain": "Only the RA- prefix makes the secondary always readable, at the endpoint <account>-secondary.blob.core.windows.net; plain GRS and GZRS keep the secondary inaccessible until failover. Between the two RA options, RA-GRS is cheaper than RA-GZRS because its primary is LRS rather than ZRS.",
    },
    {
        "type": "mc",
        "q": "An admin needs to change an account from LRS to ZRS. What does this redundancy change require?",
        "choices": [
            "Nothing special — az storage account update with the new SKU completes it instantly",
            "A conversion: either customer-initiated in place, or a manual migration to a new account",
            "Deleting and recreating the account with the same name",
            "A customer-initiated account failover to the secondary region",
        ],
        "answer": 1,
        "explain": "Any redundancy path into or out of ZRS requires a conversion: a customer-initiated conversion where Azure moves the data in place, or a manual migration (copy to a new account with AzCopy) when you control the timing. Simple SKU updates only work for non-zonal changes like LRS to GRS/RA-GRS, and failover is for regional outages, not redundancy changes.",
    },
    {
        "type": "mc",
        "q": "The primary region of a GRS account is down and the admin is deciding whether to initiate an account failover. What should be checked FIRST to understand potential data loss?",
        "choices": [
            "The account's Last Sync Time property",
            "The soft delete retention period",
            "The blob change feed",
            "The account's activity log",
        ],
        "answer": 0,
        "explain": "Geo-replication is asynchronous, so writes committed after the Last Sync Time have not reached the secondary and will be lost in a failover. Retrieve it with az storage account show --expand geoReplicationStats or Get-AzStorageAccount -IncludeGeoReplicationStats. Soft delete and change feed are unrelated to failover exposure.",
    },
    {
        "type": "mc",
        "q": "An admin configures object replication between two storage accounts, but policy creation fails. Versioning is enabled on the source account only. What is missing?",
        "choices": [
            "Blob versioning on the destination and change feed on the source",
            "Change feed on the destination account",
            "Soft delete on both accounts",
            "A private endpoint between the two accounts",
        ],
        "answer": 0,
        "explain": "Object replication's prerequisite triad is blob versioning on BOTH the source and destination accounts plus change feed on the source (change feed is how replication detects writes). Change feed is not needed on the destination, and soft delete and private endpoints are unrelated to the feature's requirements.",
    },
    {
        "type": "mc",
        "q": "Users in West Europe complain about slow reads from a blob container homed in East US. The data must remain writable only in East US, but Europe needs fast local reads from its own storage account. What should the admin configure?",
        "choices": [
            "RA-GZRS on the East US account",
            "Object replication to a storage account in West Europe",
            "Azure File Sync between the two regions",
            "A customer-initiated failover to West Europe",
        ],
        "answer": 1,
        "explain": "Object replication asynchronously copies block blobs from source containers to containers in a different storage account, giving Europe an independently readable local copy and cutting read latency. RA-GZRS reads come from the fixed paired region, not a region you choose, and within the same account. File Sync is for Azure Files on Windows Server, and failover would move the primary, not add a copy.",
    },
    {
        "type": "mc",
        "q": "An admin wants an object replication rule to copy only blobs whose names begin with 'invoices/' from the source container. Which rule setting achieves this?",
        "choices": ["A prefix match filter on the rule", "A blob index tag condition", "A lifecycle management policy", "An encryption scope on the container"],
        "answer": 0,
        "explain": "Object replication rules pair a source container with a destination container and can filter by blob name prefix (e.g., --prefix-match invoices/), plus a copy scope of everything, new objects only, or objects after a custom date. Lifecycle policies move blobs between tiers, and encryption scopes control keys — neither filters replication.",
    },
    {
        "type": "mc",
        "q": "A company must control rotation and revocation of the keys that encrypt its storage account, keeping them in Azure Key Vault. Besides pointing the account at the vault, what must the admin configure?",
        "choices": [
            "A managed identity on the account with permission to wrap/unwrap keys in the vault",
            "A shared access signature scoped to the vault",
            "Infrastructure encryption on the vault",
            "An encryption scope on every container",
        ],
        "answer": 0,
        "explain": "Customer-managed keys require the storage account to authenticate to Key Vault, which is done by assigning the account a managed identity and granting it key wrap/unwrap permissions; the vault should also have soft delete and purge protection. SAS tokens authorize storage data access, not vault access, and encryption scopes are a separate per-container key feature.",
    },
    {
        "type": "mc",
        "q": "A SaaS provider hosts multiple customers' containers in ONE storage account and must encrypt each customer's data with a different key. What should the admin configure?",
        "choices": [
            "A separate storage account per customer",
            "Encryption scopes applied per container",
            "Customer-provided keys on the account",
            "Infrastructure encryption per container",
        ],
        "answer": 1,
        "explain": "Encryption scopes create key boundaries within a single account: each scope has its own Microsoft-managed or customer-managed key and is applied per container or per blob, isolating tenants without account sprawl. Customer-provided keys are supplied per request by clients, and infrastructure encryption is an account-wide creation-time flag, not per container. Separate accounts work but contradict the one-account requirement.",
    },
    {
        "type": "mc",
        "q": "A help-desk technician on macOS needs a free graphical tool to browse containers, upload blobs, and manage several storage accounts. Which tool should the admin recommend?",
        "choices": ["AzCopy", "Azure Storage Explorer", "Azure Monitor workbooks", "The Az PowerShell module"],
        "answer": 1,
        "explain": "Azure Storage Explorer is the free cross-platform GUI (Windows, macOS, Linux) for interactive storage management, and it uses AzCopy under the hood for its transfers. AzCopy alone is command-line only, PowerShell is scripting rather than a GUI, and Monitor workbooks visualize metrics, not data management.",
    },
    {
        "type": "mc",
        "q": "An admin signs in to Storage Explorer with a Microsoft Entra account that holds the Contributor role on the subscription, but blob data access is denied. What is the fix?",
        "choices": [
            "Assign a data-plane role such as Storage Blob Data Contributor",
            "Elevate the account to Owner on the subscription",
            "Enable the account's hierarchical namespace",
            "Regenerate the storage account access keys",
        ],
        "answer": 0,
        "explain": "Owner and Contributor are management-plane roles — they govern the account resource, not the data inside it. Entra-based data access requires a data-plane RBAC role like Storage Blob Data Contributor. Regenerating keys only matters for shared-key access, and hierarchical namespace is a Data Lake feature unrelated to authorization.",
    },
    {
        "type": "mc",
        "q": "A contractor needs time-limited access to one container through Storage Explorer, and policy forbids sharing account keys or granting Entra roles. Which connection method fits?",
        "choices": [
            "Account name and key",
            "A shared access signature (SAS) URI",
            "The local Azurite emulator",
            "Anonymous public access",
        ],
        "answer": 1,
        "explain": "A SAS grants delegated, time-limited, scoped access without sharing credentials — exactly the contractor scenario. Account keys grant full account access and violate the policy, Azurite is a local development emulator with no real data, and enabling anonymous public access removes all control rather than delegating it.",
    },
    {
        "type": "mc",
        "q": "Which AzCopy command uploads a local folder and all its subfolders to a blob container?",
        "choices": [
            "azcopy copy ./data \"https://acct.blob.core.windows.net/backups\" --recursive",
            "azcopy sync \"https://acct.blob.core.windows.net/backups\" ./data",
            "azcopy upload ./data acct/backups --all",
            "azcopy jobs create ./data backups",
        ],
        "answer": 0,
        "explain": "azcopy copy with --recursive transfers the folder tree into the container; source comes first, destination second. There is no 'azcopy upload' command, 'jobs' manages existing transfers (list/resume), and the sync example shown has the cloud URL as the source, which would copy in the wrong direction.",
    },
    {
        "type": "mc",
        "q": "A nightly script must make a blob container exactly mirror a local folder, removing destination blobs whose source files were deleted. Which command does this?",
        "choices": [
            "azcopy sync ./data \"https://acct.blob.core.windows.net/backups\" --delete-destination=true",
            "azcopy copy ./data \"https://acct.blob.core.windows.net/backups\" --overwrite=true",
            "azcopy sync \"https://acct.blob.core.windows.net/backups\" ./data --mirror",
            "azcopy copy ./data \"https://acct.blob.core.windows.net/backups\" --recursive --purge",
        ],
        "answer": 0,
        "explain": "azcopy sync copies only deltas from source to destination, and --delete-destination=true additionally removes destination blobs that no longer exist at the source — a true one-way mirror. azcopy copy never deletes anything at the destination (and has no --purge flag), and sync with the cloud URL first would mirror in the wrong direction; there is no --mirror flag.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: An admin can change a storage account's performance tier from Standard to Premium after the account is created.",
        "answer": False,
        "explain": "The performance tier is fixed at creation — no update command or portal blade changes it. If a Standard account must become Premium, the only path is creating a new Premium account and copying the data across, typically with AzCopy. Redundancy SKUs can change; the tier cannot.",
    },
    {
        "type": "tf",
        "q": "True or False: In a GZRS account, the secondary region stores its copies as zone-redundant ZRS.",
        "answer": False,
        "explain": "GZRS is ZRS in the primary region plus plain LRS in the secondary — the secondary's three copies sit in a single datacenter, not across zones. Assuming zone redundancy on both sides is the classic GZRS trap; only the primary gets the zonal layout.",
    },
    {
        "type": "tf",
        "q": "True or False: Object replication can protect Azure Files shares by copying them to a second storage account.",
        "answer": False,
        "explain": "Object replication is strictly for block blobs — it does not support Azure Files, queues, tables, page blobs, or hierarchical-namespace accounts. Any stem involving file shares eliminates object replication; for Files, look at solutions like Azure File Sync or backup instead.",
    },
    {
        "type": "tf",
        "q": "True or False: The azcopy sync command copies changes from the source to the destination only, never in the reverse direction.",
        "answer": True,
        "explain": "azcopy sync is one-directional: it makes the destination match the source and will never pull destination changes back. Bi-directional synchronization is Azure File Sync, a different service for caching Azure Files on Windows Server. Reading the direction in the stem is the whole question.",
    },
    {
        "type": "tf",
        "q": "True or False: Because storage data is encrypted by default with Microsoft-managed keys, switching an existing account to customer-managed keys in Key Vault requires creating a new storage account.",
        "answer": False,
        "explain": "The key source is changeable at any time on an existing account — you assign the account a managed identity, grant it vault access, and update the encryption key source to Key Vault. The creation-time-only encryption setting is infrastructure (double) encryption, not the key-management model.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Before initiating a storage account failover, an admin checks the ______ property to see how much un-replicated data could be lost. (type your answer)",
        "answers": ["last sync time", "lastsynctime", "last synchronization time", "geo last sync time"],
        "explain": "Geo-replication is asynchronous, so writes after the Last Sync Time have not reached the secondary and would be lost in a failover. It is exposed via az storage account show --expand geoReplicationStats or Get-AzStorageAccount -IncludeGeoReplicationStats.",
    },
    {
        "type": "fill",
        "q": "Object replication requires blob versioning on both accounts and the ______ feature enabled on the source account so writes can be detected. (type your answer)",
        "answers": ["change feed", "changefeed", "blob change feed"],
        "explain": "The change feed is an ordered log of blob changes on the source account; object replication reads it to know what to copy. Versioning on both source and destination completes the prerequisite triad the exam loves to test.",
    },
    {
        "type": "fill",
        "q": "All Azure Storage data is automatically encrypted at rest with 256-bit ______ encryption that cannot be disabled. (type the algorithm)",
        "answers": ["aes", "aes-256", "aes 256", "advanced encryption standard"],
        "explain": "Storage Service Encryption uses 256-bit AES, is on for every account and every service, and no one can turn it off. The configurable choice is only the key-management model: Microsoft-managed, customer-managed in Key Vault, or customer-provided per request.",
    },
    {
        "type": "fill",
        "q": "The AzCopy subcommand that continues an interrupted transfer from where it stopped is azcopy jobs ______. (type the word)",
        "answers": ["resume", "jobs resume", "azcopy jobs resume"],
        "explain": "AzCopy tracks every transfer as a job: azcopy jobs list enumerates them and azcopy jobs resume <job-id> picks up an interrupted transfer without redoing completed files. This resumability is why AzCopy is the answer for large or unreliable transfers.",
    },
    {
        "type": "fill",
        "q": "To give different containers in one storage account their own encryption keys, an admin creates encryption ______. (type the word)",
        "answers": ["scopes", "scope", "encryption scopes", "encryption scope"],
        "explain": "Encryption scopes define key boundaries inside a single account — each scope uses a Microsoft-managed or customer-managed key and is applied per container or per blob. They solve multi-tenant key isolation without creating a separate storage account per customer.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each redundancy option to its layout.",
        "pairs": [
            ["LRS", "3 synchronous copies in one datacenter — 11 nines"],
            ["ZRS", "3 copies across three availability zones in one region — 12 nines"],
            ["GRS", "LRS in the primary plus asynchronous LRS in the secondary region — 16 nines"],
            ["GZRS", "ZRS in the primary plus LRS in the secondary region — 16 nines"],
            ["RA-GZRS", "Zone-redundant primary with an always-readable secondary endpoint"],
        ],
        "explain": "Anchor the ladder: 3 copies stay in-region (LRS in one datacenter, ZRS across zones), 6 copies span two regions (GRS/GZRS), durability climbs 11 to 12 to 16 nines, and only the RA- prefix makes the secondary readable without a failover.",
    },
    {
        "type": "match",
        "q": "Match each encryption capability to the scenario it solves.",
        "pairs": [
            ["Microsoft-managed keys", "Compliance with zero key-management effort — the default"],
            ["Customer-managed keys", "Company controls rotation and revocation via Azure Key Vault"],
            ["Customer-provided keys", "Client supplies the key on each blob request; Azure never stores it"],
            ["Infrastructure encryption", "Second independent encryption layer, set only at account creation"],
            ["Encryption scopes", "Different keys for different containers within one account"],
        ],
        "explain": "Map requirement language to model: 'no effort' = Microsoft-managed, 'we control rotation/revocation' = CMK plus managed identity, 'key sent with each request' = customer-provided (blob only), 'double encryption' = infrastructure encryption at creation, 'per-container keys' = encryption scopes.",
    },
    {
        "type": "match",
        "q": "Match each command to what it does.",
        "pairs": [
            ["az storage account create --sku Standard_GZRS", "Create a new geo-zone-redundant storage account"],
            ["az storage account failover", "Promote the secondary region to primary during an outage"],
            ["Invoke-AzStorageAccountFailover", "PowerShell equivalent of initiating an account failover"],
            ["azcopy sync --delete-destination=true", "One-way mirror that removes destination blobs missing from the source"],
            ["azcopy jobs list", "Show transfers that can be resumed after interruption"],
        ],
        "explain": "AZ-104 expects tool fluency: account lifecycle is az storage account create/update/failover (Invoke-AzStorageAccountFailover in PowerShell), while data movement is AzCopy — copy for transfers, sync for one-way mirroring, and jobs list/resume for interrupted work.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps to configure object replication between two storage accounts, from first to last.",
        "items": [
            "Enable blob versioning on the source account",
            "Enable blob versioning on the destination account",
            "Enable change feed on the source account",
            "Create the replication policy with rules pairing source and destination containers",
            "Add prefix filters to the rules if only certain blobs should replicate",
            "Check blob replication status on the source to confirm copies complete",
        ],
        "explain": "The prerequisites come first — versioning on both accounts and change feed on the source — because policy creation fails without them. Then the policy's rules pair containers, optionally filtered by blob prefix, and since replication is asynchronous with no SLA, you verify by checking each blob's replication status on the source.",
    },
    {
        "type": "order",
        "q": "Arrange the runbook steps for a customer-initiated failover of a GRS account during a regional outage, from first to last.",
        "items": [
            "Check the account's Last Sync Time to measure potential data loss",
            "Initiate the failover with az storage account failover",
            "Wait for the secondary region to be promoted to primary",
            "Note that the account is now LRS in the new primary",
            "Re-enable geo-redundancy to restore a secondary copy",
        ],
        "explain": "Because geo-replication is asynchronous, Last Sync Time comes first — it tells you which recent writes will be lost. After the failover promotes the secondary, the account runs as LRS, so the final step is re-enabling GRS/GZRS; Azure does not restore geo-protection automatically.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to move an account from Microsoft-managed keys to customer-managed keys, from first to last.",
        "items": [
            "Create an Azure Key Vault with soft delete and purge protection enabled",
            "Create or import the encryption key in the vault",
            "Assign a managed identity to the storage account",
            "Grant the identity permission to wrap and unwrap keys in the vault",
            "Update the account's encryption key source to point at the Key Vault key",
        ],
        "explain": "CMK is a trust chain: the vault (hardened with soft delete and purge protection) holds the key, the storage account gets a managed identity, that identity is granted wrap/unwrap access, and only then can the account's key source switch to Microsoft.Keyvault. Skipping the identity or its vault permissions is why CMK configuration fails.",
    },
]
