TOPIC = {
    "id": "2.3",
    "domain": 2,
    "title": "Configure Azure Files and Azure Blob Storage.",
    "short": "Azure Files & Blob Storage",
}

TERMS = [
    ("Azure Files", "Fully managed cloud file share inside a storage account, mountable over SMB or NFS 4.1 like a traditional network drive"),
    ("SMB", "File-sharing protocol used by Azure Files for Windows/Linux/macOS clients, traveling over TCP port 445"),
    ("NFS 4.1", "Alternate file share protocol supported only on premium (FileStorage) accounts and only from trusted networks; a share is SMB or NFS, never both"),
    ("TCP port 445", "Outbound port SMB requires; commonly blocked by ISPs and firewalls, causing shares to mount from Azure VMs but fail from home or the office"),
    ("Provisioned model", "Premium file share billing: you provision capacity/IOPS/throughput up front and pay for what you provision, not what you store"),
    ("Share quota", "Per-share size cap in GiB that can be raised with no downtime"),
    ("Transaction optimized tier", "Standard file share tier for heavy churn — highest storage price, lowest transaction price"),
    ("Share snapshot", "Read-only point-in-time copy of an entire file share (up to 200 per share); individual files restorable via Previous Versions"),
    ("File share soft delete", "Retains a deleted file share for 1-365 days; enabled by default at 7 days on new accounts"),
    ("Container", "Folder-like grouping for blobs; names are 3-63 lowercase letters, numbers, and hyphens"),
    ("Anonymous access level", "Per-container setting — Private (nothing), Blob (read blobs by URL, no listing), or Container (read and enumerate)"),
    ("Allow blob anonymous access", "Account-level switch, disabled by default on new accounts, that gates all container-level public access settings"),
    ("Block blob", "Default blob type uploaded in blocks — documents, images, backups; the only type that supports access tiers"),
    ("Append blob", "Blob type optimized for append-only writes such as logs and audit trails"),
    ("Page blob", "Blob type of 512-byte pages for random read/write — the format behind VHDs/unmanaged disks"),
    ("Hot tier", "Online access tier with no minimum duration — highest storage cost, lowest access cost"),
    ("Cool tier", "Online access tier for infrequent access with a 30-day minimum storage duration"),
    ("Cold tier", "Online access tier for rare access with a 90-day minimum storage duration"),
    ("Archive tier", "Offline tier with a 180-day minimum — cheapest storage, but blobs must be rehydrated before they can be read"),
    ("Rehydration", "Bringing an archived blob back online via Set Blob Tier or Copy Blob; Standard priority takes up to 15 hours, High under 1 hour for blobs under 10 GB"),
    ("Early deletion charge", "Prorated fee billed when a blob is deleted or moved to a different tier before its 30/90/180-day tier minimum elapses"),
    ("Lifecycle management", "JSON rule-based policy on the storage account that automatically tiers down or deletes block blobs as they age; runs roughly once a day"),
    ("daysAfterLastAccessTimeGreaterThan", "Lifecycle condition keyed to last read time; requires last access time tracking to be enabled on the account first"),
    ("Blob soft delete", "Retains deleted or overwritten blobs for 1-365 days; undelete restores the blob and its snapshots"),
    ("Container soft delete", "Separate 1-365 day retention setting that protects deleted containers — blob soft delete alone will not recover a container"),
    ("Blob versioning", "Account-level feature that automatically captures a previous version of a blob on every overwrite or delete"),
    ("Blob snapshot", "Manual, per-blob read-only point-in-time copy tied to the base blob — contrast with automatic versioning"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A consultant can mount the finance Azure Files share from an Azure VM, but the same net use command fails from a hotel network. What is the most likely cause?",
        "choices": [
            "The storage account key has expired",
            "The hotel's network blocks outbound TCP port 445",
            "The share's access tier is set to Cool",
            "The share quota has been exceeded",
        ],
        "answer": 1,
        "explain": "SMB travels over TCP port 445, which many ISPs, hotels, and corporate firewalls block outbound — the classic symptom is a share that mounts fine inside Azure but fails from outside. The fix is opening 445 or tunneling over VPN/ExpressRoute/private endpoint. Storage keys do not expire on their own, and tiers and quotas never break connectivity.",
    },
    {
        "type": "mc",
        "q": "An admin must create an NFS 4.1 file share for a Linux workload, but share creation only offers SMB on the existing Standard GPv2 account. What should the admin do?",
        "choices": [
            "Enable large file shares on the GPv2 account",
            "Create a premium FileStorage account and create the NFS share there",
            "Upgrade the GPv2 account to RA-GRS redundancy",
            "Create the share as SMB and switch its protocol to NFS afterward",
        ],
        "answer": 1,
        "explain": "NFS 4.1 shares are supported only on premium (FileStorage) accounts, so the Standard GPv2 account is the flaw in the scenario. The protocol is chosen at share creation and a share is SMB or NFS, never both — there is no post-creation switch. Large file shares and redundancy settings have nothing to do with protocol support.",
    },
    {
        "type": "mc",
        "q": "What is the maximum size of a standard Azure file share on a GPv2 account with large file shares enabled?",
        "choices": ["5 TiB", "10 TiB", "100 TiB", "500 TiB"],
        "answer": 2,
        "explain": "Standard shares scale up to 100 TiB, and large file shares are standard on new accounts. 5 TiB was the old default cap before large file shares existed, which makes it the tempting distractor. Memorize 100 TiB cold — it appears in sizing scenarios.",
    },
    {
        "type": "mc",
        "q": "A database team needs a file share where they pay for a fixed amount of capacity, IOPS, and throughput regardless of how much data is actually stored. Which option delivers this?",
        "choices": [
            "A premium file share on a FileStorage account",
            "A standard share on the transaction optimized tier",
            "A standard share on the cool tier",
            "A standard share with a raised quota",
        ],
        "answer": 0,
        "explain": "Premium shares use a provisioned model: you provision capacity/IOPS/throughput up front and pay for what you provision, not what you store. All standard-tier shares (transaction optimized, hot, cool) bill pay-as-you-go on actual usage. The quota only caps size; it is not a billing model.",
    },
    {
        "type": "mc",
        "q": "A standard file share hosts a busy departmental app with constant reads and writes. Which access tier minimizes cost for this heavy-transaction workload?",
        "choices": ["Cool", "Hot", "Transaction optimized", "Archive"],
        "answer": 2,
        "explain": "Transaction optimized has the highest storage price but the lowest transaction price, making it cheapest when churn is heavy. Cool inverts that trade-off — cheap storage, pricey transactions — for rarely touched team shares. Archive is a blob tier, not a file share tier, and hot sits in the middle.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command creates an Azure file share named finance with a 1024 GiB quota and a specific access tier?",
        "choices": [
            "az storage share-rm create --storage-account stfiles --name finance --quota 1024 --access-tier TransactionOptimized",
            "az storage container create --account-name stfiles --name finance --public-access blob",
            "az storage blob set-tier --account-name stfiles --name finance --tier Hot",
            "az storage account create --name finance --sku Standard_LRS",
        ],
        "answer": 0,
        "explain": "az storage share-rm create works through the management plane and accepts --quota and --access-tier, and share-rm update changes the tier later. az storage container create makes a blob container, set-tier changes a blob's tier, and az storage account create makes the account itself — plausible siblings, wrong scope.",
    },
    {
        "type": "mc",
        "q": "The portal's Connect blade generates a Windows script to map an Azure Files share to drive Z:. Which command does that script wrap?",
        "choices": ["mount.cifs", "net use", "robocopy", "New-AzRmStorageShare"],
        "answer": 1,
        "explain": "On Windows the portal-generated script wraps net use (or New-PSDrive), passing the storage account name as the user and the account key as the password. mount.cifs is the Linux equivalent, robocopy copies files rather than mounting shares, and New-AzRmStorageShare creates a share, it does not mount one.",
    },
    {
        "type": "mc",
        "q": "An admin's request to create a blob container named MyContainer is rejected. Which name would be accepted?",
        "choices": ["my_container", "my-container", "MC", "-mycontainer"],
        "answer": 1,
        "explain": "Container names must be 3-63 characters of lowercase letters, numbers, and hyphens, starting with a letter or number. MyContainer fails on uppercase, my_container on the underscore, MC on both length and case, and -mycontainer on the leading hyphen. my-container satisfies every rule.",
    },
    {
        "type": "mc",
        "q": "A website must let anonymous users download images by direct URL, but visitors must NOT be able to enumerate the container's contents. Which container access level fits?",
        "choices": ["Private", "Blob", "Container", "Read-only"],
        "answer": 1,
        "explain": "The Blob level lets anonymous users read individual blobs if they know the URL but never list the container. Container level adds enumeration, which the requirement forbids, and Private blocks all anonymous access. 'Read-only' is not one of the three anonymous access levels.",
    },
    {
        "type": "mc",
        "q": "An admin sets a container's access level to Blob, yet every anonymous request still returns 403. The container settings look correct. What should the admin check first?",
        "choices": [
            "Whether the blobs are block blobs rather than page blobs",
            "Whether the storage account's 'Allow blob anonymous access' property is disabled",
            "Whether the container name contains uppercase letters",
            "Whether the account's default access tier is Cool",
        ],
        "answer": 1,
        "explain": "Every container-level access setting is subordinate to the account-level 'Allow blob anonymous access' switch, which is disabled by default on new accounts — while off, all containers behave as Private regardless of their level. Blob type and access tier never affect authorization, and an invalid name would have blocked creation entirely.",
    },
    {
        "type": "mc",
        "q": "An application writes audit log entries continuously to the end of a blob. Which blob type should it use?",
        "choices": ["Block blob", "Page blob", "Append blob", "Archive blob"],
        "answer": 2,
        "explain": "Append blobs are optimized for append-only writes, making them the fit for logs and audit trails. Block blobs suit documents and backups uploaded in blocks, and page blobs provide 512-byte-page random I/O for VHDs. 'Archive blob' is a tier, not a blob type — and the type is fixed at upload and cannot be converted later.",
    },
    {
        "type": "mc",
        "q": "A team uploads a VHD for an unmanaged disk into Blob Storage. Which blob type does the VHD require?",
        "choices": ["Page blob", "Append blob", "Block blob", "Any type, chosen after upload"],
        "answer": 0,
        "explain": "Page blobs are made of 512-byte pages supporting random read/write, which is exactly what disk workloads need — VHDs/unmanaged disks are page blobs. Block blobs handle sequential object uploads and append blobs handle log appends. The type is chosen at upload and cannot be changed afterward.",
    },
    {
        "type": "mc",
        "q": "An admin tries to set a storage account's default access tier so that all new blobs land in Archive automatically. Why does this fail?",
        "choices": [
            "Archive requires a premium storage account",
            "The account default tier must be an online tier (Hot, Cool, or Cold); Archive is set per blob or via lifecycle rules",
            "The default tier can only be changed at account creation",
            "Archive can only hold page blobs",
        ],
        "answer": 1,
        "explain": "The account-level default access tier can be any online tier — Hot, Cool, or Cold — but never Archive, which exists strictly per blob or through lifecycle-rule actions. Archive lives in standard accounts and applies only to block blobs, and the default tier is changeable any time with az storage account update --access-tier.",
    },
    {
        "type": "mc",
        "q": "A blob was moved to the Cool tier, and 10 days later a script moves it back to Hot. What is the cost consequence?",
        "choices": [
            "None — tier changes are always free",
            "A prorated early deletion charge for the remaining 20 days of Cool's 30-day minimum",
            "The blob must first be rehydrated, incurring retrieval fees",
            "The whole storage account is billed at the Hot rate retroactively",
        ],
        "answer": 1,
        "explain": "Cool has a 30-day minimum storage duration; deleting a blob or moving it to a different tier early triggers a prorated early deletion charge for the days remaining (here, 20). Rehydration applies only to Archive, since Cool is an online tier. The minimums are 30/90/180 days for Cool/Cold/Archive.",
    },
    {
        "type": "mc",
        "q": "Legal needs an 8 GB archived blob readable within the hour. Which action meets the deadline?",
        "choices": [
            "Set Blob Tier to Hot with Standard rehydration priority",
            "Set Blob Tier to Hot with High rehydration priority",
            "Enable blob versioning on the account",
            "Take a snapshot of the archived blob and read the snapshot",
        ],
        "answer": 1,
        "explain": "High-priority rehydration typically completes in under 1 hour for blobs under 10 GB, at a premium price; Standard priority can take up to 15 hours, missing the deadline. Versioning does nothing for offline data, and snapshots of an archived blob are not a way to read it — the data must come back to an online tier first.",
    },
    {
        "type": "mc",
        "q": "Compliance requires that an archived blob remain in the Archive tier untouched, but an analyst needs to read its contents this week. What is the correct approach?",
        "choices": [
            "Copy Blob to a new blob in an online tier, leaving the archived original in place",
            "Set Blob Tier on the archived blob to Cool, read it, then re-archive it",
            "Download the archived blob directly with azcopy",
            "Promote a previous version of the blob to current",
        ],
        "answer": 0,
        "explain": "Copy Blob rehydrates the data into a new blob in an online tier while the archived source stays exactly where it is — and no early-deletion fee hits the source. Set Blob Tier changes the blob in place, violating the keep-it-archived requirement and risking early-deletion fees on re-archive. Archived blobs cannot be read or downloaded directly by any tool.",
    },
    {
        "type": "mc",
        "q": "How long can a Standard-priority rehydration from the Archive tier take?",
        "choices": ["Up to 15 minutes", "Up to 1 hour", "Up to 15 hours", "Up to 48 hours"],
        "answer": 2,
        "explain": "Standard rehydration may take up to 15 hours; High priority typically finishes in under 1 hour for blobs under 10 GB. The 24-48 hour figure belongs to lifecycle policies taking effect, a different fact the exam likes to swap in as a distractor.",
    },
    {
        "type": "mc",
        "q": "A lifecycle rule must move blobs that have not been READ in 90 days to the Cool tier, but the daysAfterLastAccessTimeGreaterThan condition cannot be used. What is the missing prerequisite?",
        "choices": [
            "Blob versioning must be enabled on the account",
            "Last access time tracking must be enabled on the storage account",
            "The blobs must first be converted to append blobs",
            "The account default tier must be set to Cool",
        ],
        "answer": 1,
        "explain": "The last-access condition requires access tracking (last access time tracking) to be enabled on the account first — that prerequisite is the trap. daysAfterModificationGreaterThan needs no prerequisite, which is why 'modified' vs. 'read' wording matters in the stem. Versioning, blob type, and the default tier are unrelated.",
    },
    {
        "type": "mc",
        "q": "An admin created a lifecycle management policy two hours ago, but no blobs have moved tiers yet. What should the admin conclude?",
        "choices": [
            "The policy JSON is invalid and was silently rejected",
            "Nothing is wrong — the policy runs roughly daily and can take 24-48 hours to take effect",
            "Lifecycle policies only run when triggered manually",
            "The blobs must be rehydrated before the policy can move them",
        ],
        "answer": 1,
        "explain": "The platform evaluates lifecycle policies automatically about once a day, and a new or changed policy can take up to 24-48 hours to take effect — waiting is the answer, nothing is broken. There is no manual trigger requirement, invalid JSON is rejected at creation, and rehydration applies to reading archived blobs, not to policy execution.",
    },
    {
        "type": "mc",
        "q": "A team must automatically retain the prior state of every blob whenever it is overwritten, with no per-blob admin action. Which feature should be enabled?",
        "choices": ["Blob snapshots", "Blob soft delete", "Blob versioning", "Container soft delete"],
        "answer": 2,
        "explain": "Blob versioning, enabled at the storage account level, automatically captures a previous version on every overwrite or delete — 'automatic, no admin action per blob' is its signature phrase. Snapshots are manual per-blob copies, soft delete only retains deleted/overwritten data for a time-boxed window, and container soft delete protects deleted containers.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command enables blob versioning on storage account stcontoso?",
        "choices": [
            "az storage account blob-service-properties update --account-name stcontoso --resource-group rg-data --enable-versioning true",
            "az storage blob set-tier --account-name stcontoso --tier Versioned",
            "az storage account update --name stcontoso --enable-versioning true",
            "az storage container create --account-name stcontoso --name versions",
        ],
        "answer": 0,
        "explain": "Versioning is a blob service property, so it lives under az storage account blob-service-properties update with --enable-versioning true (PowerShell: Update-AzStorageBlobServiceProperty -IsVersioningEnabled $true). az storage account update handles account-level settings like the default access tier but has no versioning flag, and the other two commands manage tiers and containers.",
    },
    {
        "type": "mc",
        "q": "A junior admin deleted an entire container last week. Blob soft delete is enabled with 30-day retention, but the container cannot be recovered. Why?",
        "choices": [
            "Blob soft delete only covers block blobs, not containers of page blobs",
            "Container soft delete is a separate setting that was never enabled",
            "Soft delete never applies to deletions, only to overwrites",
            "The container's access level was Private",
        ],
        "answer": 1,
        "explain": "Container soft delete is its own setting with its own 1-365 day retention — blob soft delete alone will not bring back a deleted container. Each protection maps to a specific loss: blob deleted = blob soft delete, container deleted = container soft delete, share deleted = file share soft delete. Access levels and blob types are irrelevant to recovery.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A single Azure file share can serve both SMB and NFS clients simultaneously.",
        "answer": False,
        "explain": "The protocol is chosen at share creation, and a share is SMB or NFS 4.1 — never both. If a workload needs both protocols, it needs two shares, and the NFS one additionally requires a premium FileStorage account.",
    },
    {
        "type": "tf",
        "q": "True or False: On a new storage account, soft delete for file shares is enabled by default with a 7-day retention period.",
        "answer": True,
        "explain": "File share soft delete is the one soft-delete setting that is on by default (7 days) for new accounts; blob soft delete and container soft delete must be enabled explicitly. All three share the same configurable 1-365 day retention range.",
    },
    {
        "type": "tf",
        "q": "True or False: Enabling blob versioning on a storage account also gives the Azure Files shares in that account automatic version history.",
        "answer": False,
        "explain": "Versioning is strictly a blob feature — Azure Files has no versioning. The Files equivalents are share snapshots (up to 200 per share, restorable via Previous Versions) and file share soft delete. Cross-applying blob features to Files is a standard wrong-answer pattern.",
    },
    {
        "type": "tf",
        "q": "True or False: When you undelete a soft-deleted blob, its snapshots are restored along with it.",
        "answer": True,
        "explain": "Blob soft delete retains deleted or overwritten blobs for the configured 1-365 day window, and undelete restores the blob together with its snapshots. Remember the limit of the net: once the retention window lapses, the data is permanently gone — soft delete is time-boxed recovery, not backup.",
    },
    {
        "type": "tf",
        "q": "True or False: Access tiers (hot, cool, cold, archive) can be applied to block blobs, append blobs, and page blobs alike.",
        "answer": False,
        "explain": "Access tiers apply to block blobs only. Append blobs (logs) and page blobs (VHDs) have no hot/cool/cold/archive setting, which also means lifecycle tiering actions target block blobs. This scoping detail is an easy point the exam checks.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "SMB traffic for Azure Files travels over outbound TCP port ______. (type the number)",
        "answers": ["445", "port 445", "tcp 445"],
        "explain": "Port 445 is the classic troubleshooting fact: many ISPs and corporate firewalls block it outbound, so shares mount from Azure VMs but fail from home or the office. The fixes are opening 445 or tunneling over VPN, ExpressRoute, or a private endpoint.",
    },
    {
        "type": "fill",
        "q": "An Azure file share supports a maximum of ______ snapshots per share. (type the number)",
        "answers": ["200", "200 snapshots", "two hundred"],
        "explain": "Share snapshots are read-only, incremental, point-in-time copies capped at 200 per share, and you are billed only for the differential. Azure Backup for Azure Files is built on these snapshots, adding scheduling and retention policies.",
    },
    {
        "type": "fill",
        "q": "The minimum storage duration for a blob in the Archive tier is ______ days. (type the number)",
        "answers": ["180", "180 days", "one hundred eighty"],
        "explain": "The tier minimums are 30 days for Cool, 90 for Cold, and 180 for Archive; deleting or warming a blob early triggers a prorated early deletion charge for the remaining days. Lifecycle rule day-counts should be aligned with these floors.",
    },
    {
        "type": "fill",
        "q": "On Linux, an Azure Files SMB share is mounted with the command mount -t ______. (type the filesystem type)",
        "answers": ["cifs", "mount.cifs", "mount -t cifs"],
        "explain": "Linux mounts Azure Files over SMB using mount -t cifs (mount.cifs) with the storage account name as the username and the account key as the password. On Windows the portal's Connect blade generates a net use script instead.",
    },
    {
        "type": "fill",
        "q": "The process of copying an Archive-tier blob back to an online tier so it can be read is called ______. (type your answer)",
        "answers": ["rehydration", "rehydrate", "rehydrating", "blob rehydration"],
        "explain": "Archive is offline, so reads fail until the blob is rehydrated via Set Blob Tier (in place) or Copy Blob (to a new blob, leaving the archived original untouched). Standard priority takes up to 15 hours; High priority is typically under 1 hour for blobs under 10 GB.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each data-loss scenario to the protection feature that recovers it.",
        "pairs": [
            ["One file inside a mounted share was overwritten yesterday", "Share snapshot (Previous Versions)"],
            ["An entire file share was deleted", "File share soft delete"],
            ["A single blob was deleted", "Blob soft delete"],
            ["A whole container was deleted", "Container soft delete"],
            ["A blob was overwritten and its prior state must exist automatically", "Blob versioning"],
        ],
        "explain": "Map the loss to the protection: file in a share = share snapshot, whole share = file share soft delete, blob = blob soft delete, container = container soft delete (a separate checkbox), automatic overwrite history = versioning. Each net covers exactly one scope — the exam tests whether you know which checkbox was needed.",
    },
    {
        "type": "match",
        "q": "Match each blob access tier to its minimum storage duration.",
        "pairs": [
            ["Hot", "No minimum"],
            ["Cool", "30 days"],
            ["Cold", "90 days"],
            ["Archive", "180 days"],
        ],
        "explain": "The 30/90/180-day floors drive both early deletion charges and sensible lifecycle rule day-counts. Hot has no minimum, and only Archive is offline — Cool and Cold remain instantly readable despite their minimums.",
    },
    {
        "type": "match",
        "q": "Match each command to the task it performs.",
        "pairs": [
            ["az storage share-rm create", "Create an Azure file share with a quota and access tier"],
            ["net use", "Mount an Azure Files share on Windows"],
            ["az storage blob set-tier", "Change a blob's access tier or start rehydration"],
            ["az storage account management-policy create", "Apply a lifecycle management policy JSON to an account"],
            ["Enable-AzStorageBlobDeleteRetentionPolicy", "Turn on blob soft delete with a retention period"],
        ],
        "explain": "share-rm commands manage file shares through the management plane; net use is the Windows mount command the portal's Connect blade generates; set-tier moves individual blobs (with --rehydrate-priority for archive recalls); management-policy create uploads the lifecycle JSON; the Enable-AzStorageBlobDeleteRetentionPolicy cmdlet is the PowerShell path to blob soft delete.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps to serve website images to anonymous users from Blob Storage, from first to last.",
        "items": [
            "Create a Standard GPv2 storage account",
            "Enable 'Allow blob anonymous access' at the account level",
            "Create a lowercase-named container with access level Blob",
            "Upload the images as block blobs",
            "Distribute the direct blob URLs to the website",
        ],
        "explain": "The account-level 'Allow blob anonymous access' switch is disabled by default and gates everything, so it must be flipped before container-level settings mean anything. Access level Blob permits URL reads without listing, and images are block blobs. Skipping the account switch is why 'public' containers mysteriously stay private.",
    },
    {
        "type": "order",
        "q": "Arrange the events of recovering an archived blob for urgent use, from first to last.",
        "items": [
            "A user requests data that lives in an Archive-tier blob",
            "The admin runs az storage blob set-tier --tier Hot --rehydrate-priority High",
            "The blob rehydrates while remaining unreadable",
            "The blob arrives in the Hot tier and is online",
            "The user downloads the data",
        ],
        "explain": "Archive is offline, so the read request must wait for rehydration; High priority typically completes in under 1 hour for blobs under 10 GB, versus up to 15 hours at Standard. During rehydration the blob still cannot be read. If the original must stay archived, Copy Blob to a new online blob is used instead of set-tier.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to build a lifecycle policy that tiers log blobs based on when they were last read, from first to last.",
        "items": [
            "Enable last access time tracking on the storage account",
            "Author a JSON rule filtering blockBlob with prefix logs/",
            "Add a tierToCool action with daysAfterLastAccessTimeGreaterThan 90",
            "Create the policy with az storage account management-policy create",
            "Wait up to 24-48 hours for the daily policy run to move blobs",
        ],
        "explain": "Access tracking is the prerequisite — without it the last-access condition cannot be used, which is the exam's favorite trap. Rules filter by blob type, prefix, and index tags, then apply actions with conditions. The platform evaluates policies roughly once a day, so a fresh policy taking up to 24-48 hours to act is normal.",
    },
]
