TOPIC = {
    "id": "3.4",
    "domain": 3,
    "title": "Create and configure Azure App Service.",
    "short": "App Service",
}

TERMS = [
    ("App Service plan", "The compute underneath web apps — defines region, OS (Windows or Linux), and pricing tier (SKU), and is shared by every app placed in it"),
    ("Pricing tier (SKU)", "The plan setting that determines VM size, instance limits, and which features (slots, autoscale, backups) are unlocked"),
    ("Free (F1) tier", "Shared-infrastructure tier with 60 CPU minutes/day, no custom domain, and no SLA — dev/test only"),
    ("Shared (D1) tier", "Shared-infrastructure tier that adds custom domain support; still metered CPU, no SLA, Windows only"),
    ("Basic tier (B1-B3)", "First dedicated-VM tier: custom domains plus SNI SSL, manual scale to 3 instances, no slots and no autoscale"),
    ("Standard tier (S1-S3)", "Tier that unlocks autoscale, 5 deployment slots, scheduled backups, and Traffic Manager support, up to 10 instances"),
    ("Premium tier (P1v2-P3v3)", "Faster dedicated hardware with 20 deployment slots, up to 30 instances, VNet features, and zone redundancy on v3"),
    ("Isolated tier / App Service Environment", "Single-tenant App Service deployment injected into your VNet — maximum isolation and up to 100 instances"),
    ("Scale up", "Changing the plan's tier/SKU to get bigger VMs and unlock features such as slots, backups, or VNet integration"),
    ("Scale out", "Changing the plan's instance count so more VMs run copies of the apps — how you handle load"),
    ("Autoscale", "Azure Monitor rules (Standard+) that adjust the plan's instance count automatically by metric or schedule, within min/max/default limits"),
    ("Autoscale cooldown", "The wait (default 5 minutes) after a scale action before autoscale can act again, preventing flapping"),
    ("Default hostname", "The public URL <name>.azurewebsites.net created from the app's globally unique name"),
    ("App settings", "Key/value configuration injected as environment variables at runtime, overriding values in configuration files"),
    ("Always On", "Basic+ setting that keeps the app loaded when idle so it does not unload and cold-start on the next request"),
    ("App Service managed certificate", "Free auto-renewing certificate for an already-mapped custom domain — no wildcards and cannot be exported"),
    ("App Service certificate", "Certificate purchased through Azure, issued by a partner CA, stored in Key Vault; supports wildcard and is exportable"),
    ("SNI SSL", "Free TLS binding type available from Basic tier up, with unlimited bindings for modern SNI-capable clients"),
    ("IP-based SSL", "TLS binding (Standard+) that assigns the app a dedicated inbound IP address at extra cost, for pre-SNI clients or a static app address"),
    ("HTTPS Only", "Platform setting that redirects all inbound HTTP requests to HTTPS"),
    ("Custom domain verification ID", "The value placed in a TXT asuid record to prove domain ownership before a hostname can be added"),
    ("Custom backup (Backup and Restore)", "Standard+ feature snapshotting content, config, and optionally linked databases to a storage account container in the same subscription"),
    ("Access restrictions", "Priority-ordered inbound allow/deny rules by IP/CIDR, service tag, or VNet subnet; the first allow rule creates an implicit deny-all"),
    ("Private endpoint", "Private Link feature giving the app a private IP in your VNet so clients reach it privately — inbound only"),
    ("Regional VNet integration", "Outbound-only feature letting the app call into a VNet through a dedicated delegated subnet — grants no inbound access"),
    ("Hybrid Connections", "Azure Relay-based TCP tunnel from the app to a specific on-premises host:port, no VPN or ExpressRoute required"),
    ("Deployment slot", "A live parallel instance of the app (e.g., staging) with its own hostname and settings, running in the same plan"),
    ("Slot swap", "Zero-downtime exchange of two slots' content and non-sticky settings, with the target warmed up before the swap"),
    ("Deployment slot setting (sticky)", "A setting marked to stay with its slot during a swap — e.g., the production connection string stays in production"),
    ("Traffic routing", "Slot feature sending a percentage of production traffic to another slot for canary testing, pinning users by cookie"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An admin's web app runs on a Basic (B1) plan and the team now needs deployment slots for staged releases. What is the minimum tier the plan must be scaled up to?",
        "choices": ["Basic B3", "Standard", "Premium v3", "Isolated"],
        "answer": 1,
        "explain": "Deployment slots do not exist below Standard: Free, Shared, and Basic all have 0 slots, Standard has 5, and Premium has 20. Scaling within Basic (B3) only adds compute, not features, and Premium or Isolated would work but are not the minimum the question asks for.",
    },
    {
        "type": "mc",
        "q": "A company needs its web app to automatically add instances when CPU exceeds 70%. The app currently runs on a Basic (B2) plan. What must the admin do first?",
        "choices": [
            "Create an Azure Monitor autoscale rule on the Basic plan",
            "Scale up the plan to Standard or higher",
            "Enable Always On in the app's configuration",
            "Move the app to a new Basic plan with more workers",
        ],
        "answer": 1,
        "explain": "Autoscale requires Standard tier or above; a Basic plan can only be scaled out manually, to at most 3 instances. Autoscale rules simply cannot be attached to a Basic plan, Always On only keeps an idle app loaded, and adding workers manually does not react to CPU load.",
    },
    {
        "type": "mc",
        "q": "Five web apps share a single Standard App Service plan. An admin scales the plan out from 2 to 6 instances to handle load on one busy app. What is the effect on the other four apps?",
        "choices": [
            "They are unaffected because scaling is per app",
            "They also run on all 6 instances, since every app in a plan scales together",
            "They are stopped until the scale operation finishes",
            "They are automatically moved to a new plan",
        ],
        "answer": 1,
        "explain": "Apps in a plan share the same VM instances, so scaling the plan scales every app in it — and a runaway app starves its plan-mates. Scaling is configured on the plan, not per app; isolating the noisy app requires moving it to its own plan in the same region and resource group.",
    },
    {
        "type": "mc",
        "q": "A release team requires 8 deployment slots for its testing pipeline. Which is the minimum App Service plan tier that satisfies this?",
        "choices": ["Standard", "Premium", "Basic", "Isolated"],
        "answer": 1,
        "explain": "Standard caps at 5 slots, so 8 slots forces Premium, which provides 20. Basic provides none, and Isolated also offers 20 slots but at App Service Environment pricing, so it is not the minimum. Slot-count stems are pure number recall: Standard = 5, Premium = 20.",
    },
    {
        "type": "mc",
        "q": "A financial services firm requires its web apps to run on single-tenant infrastructure deployed inside its own virtual network, with the ability to scale to dozens of instances. Which offering fits?",
        "choices": [
            "Premium v3 plan with private endpoints",
            "Standard plan with regional VNet integration",
            "Isolated tier in an App Service Environment",
            "Basic plan with access restrictions",
        ],
        "answer": 2,
        "explain": "The Isolated tier runs in an App Service Environment — a single-tenant deployment injected into your VNet with up to 100 instances, covering both inbound and outbound privacy natively. Premium with private endpoints is still multi-tenant compute, and VNet integration or access restrictions do not change the shared platform underneath.",
    },
    {
        "type": "mc",
        "q": "An app needs more memory per instance and VNet integration, while a second app just needs more instances to absorb traffic spikes. Which operations do these map to, respectively?",
        "choices": [
            "Scale out, then scale up",
            "Scale up, then scale out",
            "Scale up for both",
            "Scale out for both",
        ],
        "answer": 1,
        "explain": "Scale up changes the tier/SKU — bigger VMs and feature unlocks such as VNet integration, slots, or backups. Scale out changes the instance count to handle load. 'More memory per instance / unlock a feature' is always scale up; 'more copies for traffic' is always scale out.",
    },
    {
        "type": "mc",
        "q": "An admin creates a single autoscale rule that adds 1 instance when CPU exceeds 70% for 10 minutes, and nothing else. What is the likely long-term result?",
        "choices": [
            "Instances are added during spikes but never removed, increasing cost",
            "Autoscale refuses to save the setting without a schedule rule",
            "The plan scales in automatically after the default cooldown",
            "The rule has no effect because CPU rules require Premium",
        ],
        "answer": 0,
        "explain": "Every scale-out rule should be paired with a scale-in rule (e.g., remove 1 when CPU < 30%); without one, instances accumulate and are never released, burning money. Cooldown only delays the next action — it never removes instances — and CPU metric rules work from Standard tier up.",
    },
    {
        "type": "mc",
        "q": "An admin must create a new Linux App Service plan named plan-api in resource group rg-api using the Standard S1 SKU. Which command is correct?",
        "choices": [
            "az appservice plan create --name plan-api --resource-group rg-api --sku S1 --is-linux",
            "az webapp create --name plan-api --resource-group rg-api --sku S1 --linux",
            "az appservice plan update --name plan-api --resource-group rg-api --sku S1",
            "az vm create --name plan-api --resource-group rg-api --image UbuntuLTS",
        ],
        "answer": 0,
        "explain": "az appservice plan create provisions the plan, with --sku selecting the tier and --is-linux setting the OS, which is fixed at creation. az webapp create makes the app inside an existing plan, plan update changes an existing plan's SKU or worker count, and az vm create builds IaaS VMs, not App Service compute.",
    },
    {
        "type": "mc",
        "q": "While creating a web app, an admin finds the name 'inventory' is rejected even though no app named 'inventory' exists in the subscription. Why?",
        "choices": [
            "App names must be unique only within a resource group, so the group must be changed",
            "The name forms the public URL <name>.azurewebsites.net, so it must be globally unique across Azure",
            "Reserved words like 'inventory' cannot be used in app names",
            "The name conflicts with the App Service plan name",
        ],
        "answer": 1,
        "explain": "The app name becomes the default hostname <name>.azurewebsites.net, so like storage account names it must be unique across all of Azure — someone else already owns inventory.azurewebsites.net. Uniqueness is not scoped to your subscription or resource group, and plan names only need to be unique within their group.",
    },
    {
        "type": "mc",
        "q": "A team must deploy one .NET app on Windows and one Node.js app on Linux, keeping costs minimal. An admin proposes putting both in a single Basic plan. What is wrong with this design?",
        "choices": [
            "Basic plans allow only one app each",
            "A plan's OS is fixed, so Windows and Linux apps require two separate plans",
            "Node.js is not supported on Linux App Service",
            "Nothing — a plan can host both OS types simultaneously",
        ],
        "answer": 1,
        "explain": "The operating system is a property of the plan, chosen at creation and unchangeable — you cannot deploy a Linux app into a Windows plan or vice versa. Any scenario mixing OS types requires two plans. Plans can host many apps of the same OS, and Node.js runs fine on Linux.",
    },
    {
        "type": "mc",
        "q": "An admin has mapped www.contoso.com to a web app and now needs HTTPS with a certificate that renews itself automatically at no cost. Which option fits?",
        "choices": [
            "An App Service certificate purchased through Azure",
            "A wildcard certificate imported from Key Vault",
            "An App Service managed certificate",
            "An IP-based SSL binding with a self-signed certificate",
        ],
        "answer": 2,
        "explain": "The App Service managed certificate is free and auto-renews, but only for a custom domain that is already mapped and validated — and it supports no wildcards and cannot be exported. The purchased App Service certificate and Key Vault imports cost money, and a binding type (IP SSL) is not a certificate source.",
    },
    {
        "type": "mc",
        "q": "A company needs one certificate covering *.contoso.com for several web apps, wants to purchase it through Azure, and wants it stored centrally. Which option fits?",
        "choices": [
            "App Service managed certificate",
            "App Service certificate stored in Azure Key Vault",
            "Free SNI SSL certificate",
            "The default *.azurewebsites.net certificate",
        ],
        "answer": 1,
        "explain": "The App Service certificate is bought through Azure, issued by a partner CA, stored in Key Vault, supports wildcards, and can be imported into multiple apps. The free managed certificate explicitly cannot cover wildcards, SNI is a binding type rather than a certificate, and the platform's azurewebsites.net certificate never covers custom domains.",
    },
    {
        "type": "mc",
        "q": "A legacy client fleet cannot send SNI, so a web app's TLS binding must present its certificate on a dedicated inbound IP address. Which binding and minimum tier are required?",
        "choices": [
            "SNI SSL on Basic or higher",
            "SNI SSL on Standard or higher",
            "IP-based SSL on Standard or higher",
            "IP-based SSL on Basic or higher",
        ],
        "answer": 2,
        "explain": "IP-based SSL assigns the app a dedicated inbound IP so pre-SNI clients can negotiate TLS, requires Standard or above, and incurs an extra charge. SNI SSL is free from Basic up and fine for all modern browsers, but it relies on the client sending the hostname during the handshake — exactly what these clients cannot do.",
    },
    {
        "type": "mc",
        "q": "An admin is mapping the subdomain www.contoso.com to the app contoso-web.azurewebsites.net. Which two DNS records must be created at the registrar?",
        "choices": [
            "An A record for www and a CNAME for asuid.www",
            "A CNAME from www to contoso-web.azurewebsites.net and a TXT record at asuid.www with the verification ID",
            "An A record for www and an MX record for verification",
            "Two CNAME records, one for www and one for the apex",
        ],
        "answer": 1,
        "explain": "Subdomains use a CNAME pointing at the app's default hostname for routing, plus a TXT record named asuid.<subdomain> containing the custom domain verification ID to prove ownership and block subdomain takeover. A records are for the apex, and MX records handle mail, not domain validation.",
    },
    {
        "type": "mc",
        "q": "The marketing team wants the naked domain contoso.com (no www) pointed at a web app. The registrar is not Azure DNS. Which routing record must be used, and why?",
        "choices": [
            "A CNAME to the default hostname, because CNAMEs are required for App Service",
            "An A record to the app's inbound IP address, because DNS forbids a CNAME at the zone apex",
            "A TXT record containing the app's IP address",
            "An NS record delegating the apex to Azure",
        ],
        "answer": 1,
        "explain": "The DNS standard forbids a CNAME at the zone root, so the apex must use an A record pointing to the app's inbound IP, alongside a TXT asuid record for verification. Only Azure DNS users get the alias-record alternative at the apex. TXT records carry verification text, not routing, and NS delegation changes the whole zone's hosting.",
    },
    {
        "type": "mc",
        "q": "A web app on a Basic (B1) plan must run nightly scheduled backups that include its linked SQL database. Which set of changes makes this possible?",
        "choices": [
            "Enable automatic backups on the Basic plan and select the database",
            "Scale up to Standard and configure backups to a storage account container in the same subscription",
            "Create a Recovery Services vault and register the web app",
            "Scale out the Basic plan to 3 instances and enable Backup and Restore",
        ],
        "answer": 1,
        "explain": "Custom (scheduled) backups require the Standard tier or higher plus a storage account and container in the same subscription as the app. Automatic platform backups exist on Basic+ but cannot include databases or be scheduled, App Service does not back up to Recovery Services vaults, and scaling out adds instances without unlocking features.",
    },
    {
        "type": "mc",
        "q": "An admin must inspect the contents of last week's App Service backup without any risk of disturbing the running production app. What is the safest restore approach?",
        "choices": [
            "Restore the backup over the production app during a maintenance window",
            "Restore the backup to a deployment slot or a new app and inspect it there",
            "Download the backup ZIP and redeploy it via FTP to production",
            "Delete the production app and restore the backup in its place",
        ],
        "answer": 1,
        "explain": "Restore targets include overwriting the existing app, restoring to a new app, or restoring to a deployment slot — and the slot/new-app options let you examine a backup with production untouched. Overwriting production, redeploying onto it, or deleting it all carry exactly the risk the scenario forbids.",
    },
    {
        "type": "mc",
        "q": "Compliance requires that users reach an internal web app only over a private IP address from within the corporate VNet, with public access disabled. Which feature provides this?",
        "choices": [
            "Regional VNet integration",
            "Hybrid Connections",
            "A private endpoint for the app",
            "An IP-based SSL binding",
        ],
        "answer": 2,
        "explain": "A private endpoint gives the app a private IP in your VNet via Private Link, handling inbound traffic privately — pair it with disabling public access. VNet integration is outbound-only and changes nothing about how clients reach the app, Hybrid Connections relay outbound TCP to on-premises, and IP SSL provides a dedicated public inbound IP.",
    },
    {
        "type": "mc",
        "q": "A web app must connect to an Azure SQL database that is reachable only on a private IP inside a VNet. The app itself should remain publicly accessible. Which feature does the admin configure?",
        "choices": [
            "A private endpoint on the web app",
            "Regional VNet integration with a delegated subnet",
            "Access restrictions allowing the database subnet",
            "An App Service Environment migration",
        ],
        "answer": 1,
        "explain": "Regional VNet integration lets the app make outbound calls into a VNet through a dedicated subnet delegated to Microsoft.Web/serverFarms — exactly the direction needed to reach a private database. A private endpoint would control inbound access to the app, access restrictions filter who can reach the app, and an ASE is a costly oversolve.",
    },
    {
        "type": "mc",
        "q": "A web app must call a TCP service on port 1433 on a server in an on-premises datacenter, but the company has no VPN or ExpressRoute and does not want one. Which App Service feature fits?",
        "choices": [
            "Hybrid Connections with the Hybrid Connection Manager agent",
            "Regional VNet integration",
            "A private endpoint in the on-premises network",
            "Access restrictions with the on-premises IP range",
        ],
        "answer": 0,
        "explain": "Hybrid Connections use an Azure Relay TCP tunnel from the app to a specific on-premises host:port via the Hybrid Connection Manager agent — no VPN or ExpressRoute required. VNet integration reaches Azure VNets (which would still need a gateway to on-premises), private endpoints are inbound and Azure-side, and access restrictions filter inbound traffic.",
    },
    {
        "type": "mc",
        "q": "All traffic to a web app must come only through Azure Front Door; direct Internet requests must be denied. What should the admin configure on the app?",
        "choices": [
            "An access restriction allow rule using the AzureFrontDoor.Backend service tag",
            "Regional VNet integration into Front Door's VNet",
            "A deployment slot reserved for Front Door traffic",
            "HTTPS Only with minimum TLS version 1.2",
        ],
        "answer": 0,
        "explain": "Access restrictions are ordered inbound allow/deny rules by IP/CIDR, service tag, or subnet — allowing the AzureFrontDoor.Backend service tag creates an implicit deny-all beneath it, blocking direct access. Front Door has no customer VNet to integrate with, slots do not filter traffic, and HTTPS Only enforces encryption, not source.",
    },
    {
        "type": "mc",
        "q": "After a slot swap, the staging database connection string appeared in production and caused an outage. What should the admin have done to prevent this?",
        "choices": [
            "Used swap with preview, which never moves settings",
            "Marked the connection string as a deployment slot (sticky) setting in each slot",
            "Configured the connection string as an app setting instead",
            "Enabled auto swap on the production slot",
        ],
        "answer": 1,
        "explain": "A swap exchanges content and all non-sticky settings; marking a setting as a deployment slot setting pins it to its slot, so production's connection string stays in production. Swap with preview helps validate but does not make settings sticky by itself, plain app settings swap just the same, and auto swap only automates the swap trigger.",
    },
    {
        "type": "mc",
        "q": "Before fully releasing a new build, a team wants 10% of real production users to hit the staging slot while 90% stay on production. Which feature and command accomplish this?",
        "choices": [
            "Autoscale: az monitor autoscale rule create --scale out 1",
            "Slot traffic routing: az webapp traffic-routing set --distribution staging=10",
            "Swap with preview: az webapp deployment slot swap --action preview",
            "Access restrictions: allow 10% of source IP ranges",
        ],
        "answer": 1,
        "explain": "Slot traffic routing sends a configured percentage of production traffic to another slot for canary testing, pinning each user by cookie; az webapp traffic-routing set --distribution staging=10 does exactly that. Autoscale changes instance counts, swap with preview validates settings before a full swap, and access restrictions cannot split traffic by percentage.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Enabling regional VNet integration on a web app allows VMs in that VNet to reach the app over a private IP address.",
        "answer": False,
        "explain": "VNet integration is outbound only — it lets the app call into the VNet through a delegated subnet but provides no inbound access whatsoever. Private inbound reachability requires a private endpoint. Many scenarios legitimately need both features at once, one per direction.",
    },
    {
        "type": "tf",
        "q": "True or False: A web app in a Basic (B1) App Service plan can have up to 5 deployment slots.",
        "answer": False,
        "explain": "Free, Shared, and Basic tiers have zero deployment slots. Five slots is the Standard allowance, and Premium raises it to 20. A Basic-tier scenario that asks for slots is really a scale-up question in disguise.",
    },
    {
        "type": "tf",
        "q": "True or False: During a slot swap, App Service warms up the staging slot's instances before exchanging it with production, so users experience no cold start.",
        "answer": True,
        "explain": "The platform loads the staging instances and sends warm-up requests before completing the swap, which is why slot swaps deliver zero-downtime deployments. Rollback is equally painless — swapping back returns the previous warmed code to production.",
    },
    {
        "type": "tf",
        "q": "True or False: The free App Service managed certificate can secure a wildcard domain such as *.contoso.com and can be exported for use on other services.",
        "answer": False,
        "explain": "The managed certificate is free and auto-renews, but it supports no wildcards and cannot be exported — it is locked to App Service and requires the custom domain to be mapped first. Wildcard or exportable needs mean a purchased App Service certificate (stored in Key Vault) or your own uploaded PFX.",
    },
    {
        "type": "tf",
        "q": "True or False: App settings and connection strings configured in App Service are injected as environment variables at runtime and override matching values in the app's configuration files.",
        "answer": True,
        "explain": "App Service injects app settings and connection strings as environment variables, and they take precedence over values in files like appsettings.json or web.config. This is the standard mechanism for per-environment configuration — and, combined with sticky slot settings, for keeping production secrets in production.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Complete the CLI command that exchanges the staging slot with production: az webapp deployment slot ______ --name contoso-web --resource-group rg-web --slot staging (type the missing word)",
        "answers": ["swap"],
        "explain": "az webapp deployment slot swap performs the warmed, zero-downtime exchange of staging and production. Its PowerShell counterpart is Switch-AzWebAppSlot with -SourceSlotName and -DestinationSlotName.",
    },
    {
        "type": "fill",
        "q": "To route the apex (root) domain contoso.com to a web app at a registrar that is not Azure DNS, the admin must create an ______ record pointing to the app's inbound IP. (type the record type)",
        "answers": ["a", "a record", "a-record"],
        "explain": "A CNAME is forbidden at the zone apex by the DNS standard, so the root domain uses an A record to the app's inbound IP address plus a TXT asuid verification record. Azure DNS users have the extra option of an alias record at the apex.",
    },
    {
        "type": "fill",
        "q": "The TXT record that carries the custom domain verification ID for App Service hostname validation is named ______.www for the www subdomain. (type the record name prefix)",
        "answers": ["asuid", "asuid.www", "txt asuid"],
        "explain": "The TXT asuid.<subdomain> record proves you own the domain before the hostname can be added, preventing subdomain takeover. Validation fails without it even if the CNAME or A record is correct — it is the second required record in every custom-domain mapping.",
    },
    {
        "type": "fill",
        "q": "The Azure PowerShell cmdlet that swaps the staging slot into production is ______-AzWebAppSlot. (type the verb)",
        "answers": ["switch", "switch-azwebappslot"],
        "explain": "Switch-AzWebAppSlot -SourceSlotName staging -DestinationSlotName production performs the slot swap from PowerShell. Remember the CLI twin, az webapp deployment slot swap — the exam likes testing both toolchains.",
    },
    {
        "type": "fill",
        "q": "After an autoscale action, Azure Monitor waits a default cooldown of ______ minutes before it will scale again. (type the number)",
        "answers": ["5", "five", "5 minutes"],
        "explain": "The default 5-minute cooldown gives newly added or removed instances time to influence the metric before the next evaluation, preventing rapid flapping. It applies after each scale action alongside the rule's own metric duration window.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each App Service plan tier to the capability it unlocks or its defining limit.",
        "pairs": [
            ["Free (F1)", "60 CPU minutes/day, no custom domain, no SLA"],
            ["Shared (D1)", "First tier to allow custom domains, still shared CPU"],
            ["Basic (B1-B3)", "Dedicated VMs and SNI SSL, manual scale to 3 instances"],
            ["Standard (S1-S3)", "Autoscale, 5 deployment slots, scheduled backups, 10 instances"],
            ["Premium (v3)", "20 slots, 30 instances, zone redundancy"],
            ["Isolated (ASE)", "Single-tenant deployment in your VNet, up to 100 instances"],
        ],
        "explain": "Learn the ladder as feature unlock points: custom domain at Shared, dedicated compute plus SNI SSL at Basic, autoscale/slots/backups at Standard, 20 slots and zone redundancy at Premium v3, and full single-tenant isolation at Isolated. 'Minimum tier that supports X' stems are answered straight off this table.",
    },
    {
        "type": "match",
        "q": "Match each App Service networking feature to what it does.",
        "pairs": [
            ["Private endpoint", "Inbound: clients reach the app on a private IP via Private Link"],
            ["Regional VNet integration", "Outbound: app calls into a VNet through a delegated subnet"],
            ["Hybrid Connections", "Outbound TCP relay to an on-premises host:port, no VPN"],
            ["Access restrictions", "Priority-ordered inbound allow/deny rules by IP, service tag, or subnet"],
            ["IP-based SSL binding", "Gives the app a dedicated inbound IP address"],
        ],
        "explain": "Direction is everything: private endpoints and access restrictions govern inbound traffic, while VNet integration and Hybrid Connections govern outbound calls. IP-based SSL is the way an app gets its own dedicated inbound address. Picking an outbound tool for an inbound problem is the classic wrong answer.",
    },
    {
        "type": "match",
        "q": "Match each certificate or TLS option to its key characteristic.",
        "pairs": [
            ["App Service managed certificate", "Free, auto-renews, no wildcards, cannot be exported"],
            ["App Service certificate", "Purchased through Azure, stored in Key Vault, supports wildcard"],
            ["Bring your own certificate", "Upload a PFX with private key; you manage renewal"],
            ["SNI SSL", "Free binding type available from Basic tier up"],
            ["IP-based SSL", "Paid binding requiring Standard+, dedicated inbound IP"],
        ],
        "explain": "Sort by cost and constraint: the managed certificate is the free zero-admin option with wildcard and export restrictions, the App Service certificate is the Azure-purchased Key Vault-stored option, and BYO covers everything else at the cost of manual renewal. SNI is the free default binding; IP SSL costs extra and needs Standard.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps to serve a web app on https://www.contoso.com with a free certificate, from first to last.",
        "items": [
            "Create the CNAME and TXT asuid.www records at the DNS registrar",
            "App Service validates the DNS records",
            "Add the hostname www.contoso.com to the web app",
            "Create the free App Service managed certificate for the hostname",
            "Bind the certificate with SNI SSL and enable HTTPS Only",
        ],
        "explain": "Order matters twice here: DNS records must exist before validation can pass and the hostname can be added, and the free managed certificate cannot even be created until the custom domain is mapped. The TLS binding is always the final step — mapping a domain alone never makes it HTTPS.",
    },
    {
        "type": "order",
        "q": "Arrange the App Service plan tiers from lowest to highest capability.",
        "items": ["Free", "Shared", "Basic", "Standard", "Premium", "Isolated"],
        "explain": "The ladder runs Free (shared CPU, no custom domain), Shared (custom domains), Basic (dedicated VMs, SNI SSL, 3 instances), Standard (autoscale, 5 slots, backups, 10 instances), Premium (20 slots, 30 instances, zone redundancy), and Isolated (single-tenant ASE, 100 instances). Each rung is a feature unlock point the exam tests by name.",
    },
    {
        "type": "order",
        "q": "Arrange the steps for a zero-downtime canary release of a new build to an app currently on a Basic plan, from first to last.",
        "items": [
            "Scale the plan up to Standard or higher",
            "Create a staging deployment slot",
            "Deploy the new build to the staging slot",
            "Route a small percentage of production traffic to staging",
            "Swap the staging slot into production",
        ],
        "explain": "Slots require Standard+, so the Basic plan must scale up first; only then can the staging slot be created and receive the build. Traffic routing lets a canary percentage of real users validate the build, and the warmed swap finishes the release — with rollback available by simply swapping back.",
    },
]
