TOPIC = {
    "id": "4.1",
    "domain": 4,
    "title": "Configure and manage virtual networks in Azure.",
    "short": "Virtual Networks & Routing",
}

TERMS = [
    ("Virtual network (VNet)", "Your private network in Azure — a regional resource defined by one or more CIDR address spaces, carved into subnets"),
    ("Subnet", "A range inside a VNet address space where resources like VM NICs get their IPs; cannot overlap another subnet"),
    ("RFC 1918", "The private address ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16) used for VNet address spaces"),
    ("Reserved addresses", "The 5 IPs Azure holds back in every subnet: network, default gateway (.1), two for Azure DNS (.2-.3), and broadcast"),
    ("GatewaySubnet", "The literally named subnet required for a VPN or ExpressRoute gateway — /27 or larger recommended"),
    ("AzureBastionSubnet", "The literally named subnet required for Azure Bastion — /26 or larger"),
    ("AzureFirewallSubnet", "The literally named /26 subnet required for Azure Firewall"),
    ("Subnet delegation", "Handing a subnet to a specific PaaS service (e.g. Microsoft.Web/serverFarms) so it can create service resources there"),
    ("VNet peering", "Connecting two VNets over the Microsoft backbone so resources talk via private IPs — no gateway, no public internet, no downtime"),
    ("Global VNet peering", "Peering between VNets in different regions, still entirely on the private Microsoft backbone"),
    ("Non-transitivity", "The peering rule that A peered to B and B peered to C does NOT let A reach C — fix with mesh or a hub NVA/gateway"),
    ("Allow gateway transit", "Peering option set on the hub so peered spokes may use the hub's VPN/ExpressRoute gateway"),
    ("Use remote gateways", "Peering option set on a spoke to route on-premises traffic through the hub's gateway; only one side of a peering may set it"),
    ("Allow forwarded traffic", "Peering option that accepts traffic a device in the remote VNet forwarded from elsewhere — needed for hub-firewall designs"),
    ("Public IP address", "A standalone resource giving internet reachability, attached to a VM NIC, load balancer frontend, gateway, or firewall"),
    ("Standard SKU public IP", "The current-exam answer: always static, zone-redundant capable, and secure by default until an NSG allows traffic"),
    ("DNS name label", "An optional label giving a public IP a stable FQDN like myapp.eastus.cloudapp.azure.com"),
    ("System routes", "The default routes Azure gives every subnet automatically: intra-VNet, peered VNets, and 0.0.0.0/0 to Internet"),
    ("User-defined route (UDR)", "A custom route in a route table that overrides system routes; on identical prefixes UDR beats BGP beats system"),
    ("Route table", "The resource holding UDRs — it does nothing until associated to one or more subnets"),
    ("Virtual appliance (next hop)", "Next hop type that sends traffic to an NVA/firewall; you must supply its private IP and enable IP forwarding on its NIC"),
    ("None (next hop)", "Next hop type that silently drops (black-holes) traffic to the matched prefix"),
    ("Longest prefix match", "Route selection rule: the most specific matching prefix always wins (a /32 beats a /24 beats 0.0.0.0/0)"),
    ("Forced tunneling", "The classic UDR pattern: 0.0.0.0/0 with next hop Virtual appliance so all internet-bound traffic is inspected by a firewall"),
    ("Effective routes", "The per-NIC merged view of system + BGP + UDR routes — the ground truth of what routing a NIC actually uses"),
    ("Network Watcher", "Azure's regional network diagnostics service — the toolbox for answering 'why can't A reach B?'"),
    ("IP flow verify", "Network Watcher tool that says whether an NSG allows or denies a specific 5-tuple flow, and which rule decided"),
    ("Next hop (tool)", "Network Watcher tool that reveals where traffic from a VM to a destination is routed — exposing bad or missing UDRs"),
    ("Connection troubleshoot", "Network Watcher tool testing end-to-end reachability right now and showing where along the path it fails"),
    ("Packet capture", "Network Watcher tool that remotely records actual packets on a VM (agent/extension based) for deep analysis"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An admin creates a subnet with the prefix 10.0.1.0/24 and is asked how many IP addresses are actually available for VMs. What is the correct answer?",
        "choices": ["254", "251", "256", "250"],
        "answer": 1,
        "explain": "Azure reserves 5 addresses in every subnet: the network address, the default gateway (.1), two for Azure DNS (.2 and .3), and the broadcast address, so usable = 2^(host bits) − 5. A /24 has 256 addresses, leaving 251. Answering 254 is on-premises math (only network + broadcast reserved), which the exam deliberately baits.",
    },
    {
        "type": "mc",
        "q": "Within every Azure subnet, what does Azure use the second address (x.x.x.1) for?",
        "choices": ["Azure DNS mapping", "The broadcast address", "The default gateway", "The first assignable VM address"],
        "answer": 2,
        "explain": "Azure reserves x.x.x.1 as the default gateway for the subnet. The DNS mappings occupy x.x.x.2 and x.x.x.3, the network address is x.x.x.0, and the last address is broadcast — five reserved in all, so the first assignable VM address is actually x.x.x.4.",
    },
    {
        "type": "mc",
        "q": "A developer asks for the smallest subnet Azure will allow for a tiny two-VM test environment. Which prefix should the admin create?",
        "choices": ["/30", "/29", "/28", "/32"],
        "answer": 1,
        "explain": "The smallest subnet Azure permits is a /29, which has 8 addresses minus the 5 reserved, leaving just 3 usable IPs — enough for two VMs. A /30 or /32 is below the floor and cannot be created, and a /28 works but is not the smallest.",
    },
    {
        "type": "mc",
        "q": "An admin must size a subnet for exactly 55 virtual machines with no room wasted. Which is the smallest prefix that fits?",
        "choices": ["/27", "/26", "/25", "/28"],
        "answer": 1,
        "explain": "Add Azure's 5 reserved addresses first: 55 + 5 = 60 total addresses needed, so a /26 (64 addresses, 59 usable) is the smallest fit. A /27 gives only 27 usable (32 − 5), too small, while a /25 (123 usable) wastes space. Always add 5 before sizing.",
    },
    {
        "type": "mc",
        "q": "An admin deploying a VPN gateway into an existing VNet must first create its dedicated subnet. What must the subnet be named, and what size is recommended?",
        "choices": [
            "GatewaySubnet, /27 or larger",
            "VpnGatewaySubnet, /29 or larger",
            "AzureGatewaySubnet, /26 or larger",
            "Gateway-Subnet, /27 or larger",
        ],
        "answer": 0,
        "explain": "VPN and ExpressRoute gateways deploy only into a subnet named exactly GatewaySubnet, with /27 or larger recommended. The name is literal and mandatory — variants like Gateway-Subnet or VpnGatewaySubnet will simply not be offered as a deployment target.",
    },
    {
        "type": "mc",
        "q": "A deployment of Azure Bastion fails because no valid subnet exists. Which subnet must the admin create first?",
        "choices": [
            "A subnet named BastionSubnet sized /27 or larger",
            "A subnet named AzureBastionSubnet sized /26 or larger",
            "A subnet named AzureBastionSubnet sized /29 or larger",
            "Any subnet delegated to Microsoft.Network/bastionHosts",
        ],
        "answer": 1,
        "explain": "Azure Bastion requires a subnet named exactly AzureBastionSubnet and sized /26 or larger — both the name and the minimum size are hard requirements. Bastion does not use subnet delegation, and a /29 is far too small for the service's instances.",
    },
    {
        "type": "mc",
        "q": "An admin wants App Service to integrate with a VNet by giving the service permission to create resources in a dedicated subnet. Which feature accomplishes this?",
        "choices": ["VNet peering", "Subnet delegation", "A service endpoint", "A user-defined route"],
        "answer": 1,
        "explain": "Subnet delegation hands a subnet to a specific PaaS service — for App Service VNet integration that is the Microsoft.Web/serverFarms delegation — granting the service permission to create service-specific resources there. Delegated subnets are generally dedicated to that one service. Peering joins VNets and UDRs steer traffic; neither grants a service rights in a subnet.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command creates a new virtual network with an address space of 10.0.0.0/16?",
        "choices": [
            "az vnet add --address-prefixes 10.0.0.0/16",
            "az network vnet subnet create --address-prefixes 10.0.0.0/16",
            "az network vnet create --address-prefixes 10.0.0.0/16",
            "New-AzVirtualNetworkConfig -AddressPrefix 10.0.0.0/16",
        ],
        "answer": 2,
        "explain": "The CLI verb is az network vnet create, taking --address-prefixes (and optionally an initial subnet). az network vnet subnet create adds a subnet to an existing VNet, 'az vnet add' is not a real command, and the PowerShell equivalent would be New-AzVirtualNetwork, not a -Config cmdlet.",
    },
    {
        "type": "mc",
        "q": "Two VNets in East US and West Europe must exchange traffic using private IPs, with low latency and without any VPN gateway or public internet exposure. What should the admin configure?",
        "choices": ["A site-to-site VPN between the VNets", "Global VNet peering", "ExpressRoute circuits in both regions", "Regional VNet peering"],
        "answer": 1,
        "explain": "Global VNet peering joins VNets in different regions directly over the Microsoft backbone — private IPs, low latency, no gateway or encryption device, and traffic never touches the public internet. Regional peering only works within one region, and VPN/ExpressRoute add gateways and cost the scenario explicitly rules out.",
    },
    {
        "type": "mc",
        "q": "An admin created a peering from vnet-hub to vnet-spoke1, but hours later its status still shows Initiated and no traffic flows. What is the cause?",
        "choices": [
            "The peering link from vnet-spoke1 back to vnet-hub was never created",
            "The address spaces of the two VNets overlap",
            "Global peering requires a support ticket to activate",
            "The VNets are in different subscriptions, which peering does not support",
        ],
        "answer": 0,
        "explain": "A peering is really two links, one created on each VNet pointing at the other; until both exist the state shows Initiated, and only when both sides are configured does it become Connected and pass traffic. Overlapping address spaces would block creation entirely, and peering works fine across subscriptions and tenants with no ticket needed.",
    },
    {
        "type": "mc",
        "q": "An admin tries to peer vnet-a and vnet-b, but the operation fails. Both VNets use the address space 10.0.0.0/16. What must happen before the peering can be created?",
        "choices": [
            "Enable Allow forwarded traffic on both sides",
            "Re-address one VNet so the address spaces do not overlap",
            "Deploy a VPN gateway in one of the VNets",
            "Convert the peering to a global peering",
        ],
        "answer": 1,
        "explain": "Peered address spaces must not overlap — if both VNets use 10.0.0.0/16, Azure cannot build unambiguous routes between them and the peering is refused. The only fix is re-addressing one side. Peering options like Allow forwarded traffic, gateways, or global scope do nothing to resolve an address collision.",
    },
    {
        "type": "mc",
        "q": "VNet-A is peered with VNet-B, and VNet-B is peered with VNet-C. VMs in VNet-A cannot reach VMs in VNet-C. Why?",
        "choices": [
            "The global peering bandwidth limit has been reached",
            "An NSG blocks inter-VNet traffic by default",
            "VNet peering is not transitive, so A has no route to C",
            "Only one peering per VNet is allowed at a time",
        ],
        "answer": 2,
        "explain": "Peering is not transitive: A↔B and B↔C do not connect A and C. The fixes are a direct A↔C peering (full mesh) or routing spoke-to-spoke traffic through a hub NVA/firewall (with UDRs) or hub gateway. NSGs allow VirtualNetwork traffic by default, and a VNet can hold many peerings.",
    },
    {
        "type": "mc",
        "q": "In a hub-and-spoke design, spoke VNets must reach on-premises through the VPN gateway deployed in the hub. How should the peering options be set?",
        "choices": [
            "Hub: Use remote gateways; Spokes: Allow gateway transit",
            "Hub: Allow gateway transit; Spokes: Use remote gateways",
            "Both sides: Allow gateway transit",
            "Both sides: Use remote gateways",
        ],
        "answer": 1,
        "explain": "The side that owns the gateway (the hub) sets Allow gateway transit, and each spoke sets Use remote gateways to send on-premises traffic through it. Only one side of a peering may use remote gateways, and a VNet using a remote gateway cannot have its own gateway — so the reversed and 'both sides' options are invalid.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command establishes one side of a peering between two virtual networks?",
        "choices": [
            "az network vnet peering create",
            "az network vnet-gateway create",
            "az network vnet connection create",
            "az network peering connect",
        ],
        "answer": 0,
        "explain": "az network vnet peering create builds a peering link on one VNet pointing at the remote VNet's resource ID (with flags like --allow-vnet-access, --allow-forwarded-traffic, --allow-gateway-transit); you repeat it mirrored on the other side. az network vnet-gateway create deploys a VPN gateway, and the other two commands do not exist.",
    },
    {
        "type": "mc",
        "q": "In a hub-firewall design, spoke subnets send traffic to the hub firewall, which then forwards it to another spoke. Which peering option must be enabled for the destination spoke to accept that traffic?",
        "choices": ["Use remote gateways", "Allow gateway transit", "Allow forwarded traffic", "Allow virtual network access only"],
        "answer": 2,
        "explain": "Allow forwarded traffic tells a peering link to accept traffic that a device in the remote VNet forwarded from somewhere else — exactly what happens when a hub firewall relays spoke-to-spoke flows. Gateway transit/remote gateways relate to sharing a VPN or ExpressRoute gateway, not to NVA-forwarded packets.",
    },
    {
        "type": "mc",
        "q": "An admin creating a public IP for a new production load balancer in 2026 must pick a SKU. Which statement about the correct choice is true?",
        "choices": [
            "Basic SKU, because dynamic allocation is cheaper for small workloads",
            "Standard SKU, which is always static and secure by default",
            "Basic SKU, because Standard requires availability zones",
            "Standard SKU, which defaults to dynamic allocation unless changed",
        ],
        "answer": 1,
        "explain": "Standard is the only current answer: the Basic public IP SKU retired on September 30, 2025. Standard IPs are always static, offer zone-redundant or zonal options, and are secure by default — inbound stays closed until an NSG explicitly allows it. Zones are optional on Standard, and dynamic allocation belongs to the retired Basic SKU.",
    },
    {
        "type": "mc",
        "q": "An admin attaches a brand-new Standard SKU public IP to a VM's NIC, but RDP from the internet fails. The VM is running and healthy. What is the most likely fix?",
        "choices": [
            "Change the IP allocation from static to dynamic",
            "Recreate the IP as a Basic SKU public IP",
            "Add an NSG rule allowing inbound TCP 3389",
            "Associate a route table with next hop Internet to the subnet",
        ],
        "answer": 2,
        "explain": "Standard public IPs are secure by default: all inbound traffic is closed until an NSG rule explicitly allows it, so the missing piece is an allow rule for the RDP port. This is by design, not a malfunction. Standard is always static (there is no dynamic option), Basic is retired, and system routes already handle internet return traffic.",
    },
    {
        "type": "mc",
        "q": "A team wants clients to reach a public IP through a stable name like contoso-web.eastus.cloudapp.azure.com rather than the raw address. What should the admin configure on the public IP?",
        "choices": ["A DNS name label", "An A record in Azure Private DNS", "A reverse-lookup pointer on the NIC", "A service endpoint"],
        "answer": 0,
        "explain": "A DNS name label on the public IP resource generates the FQDN <label>.<region>.cloudapp.azure.com, giving a stable name to reference instead of the address — the CLI flag is --dns-name and the PowerShell parameter is -DomainNameLabel. Private DNS serves names inside VNets, not public internet clients, and service endpoints are unrelated to naming.",
    },
    {
        "type": "mc",
        "q": "An admin creating a frontend IP for a Standard Load Balancer finds an existing unused public IP but cannot attach it. What is the most likely reason?",
        "choices": [
            "The public IP has a DNS name label configured",
            "The public IP is a Basic SKU, which cannot front a Standard Load Balancer",
            "The public IP is zone-redundant, which load balancers do not support",
            "Public IPs can only attach to virtual machine NICs",
        ],
        "answer": 1,
        "explain": "SKUs must match: a Standard Load Balancer requires a Standard public IP, and you cannot mix SKUs between an LB and its frontend — an old Basic IP is the classic blocker. Zone redundancy is supported (and desirable) on Standard, DNS labels don't block attachment, and public IPs attach to LB frontends, gateways, and firewalls as well as NICs.",
    },
    {
        "type": "mc",
        "q": "Security policy requires that ALL internet-bound traffic from the workload subnets pass through an Azure Firewall at 10.0.0.4 before leaving. What should the admin create?",
        "choices": [
            "A UDR for 0.0.0.0/0 with next hop Internet, associated to the workload subnets",
            "A UDR for 0.0.0.0/0 with next hop Virtual appliance and IP 10.0.0.4, associated to the workload subnets",
            "A UDR for 10.0.0.4/32 with next hop Virtual network gateway",
            "An NSG rule denying all outbound traffic except to 10.0.0.4",
        ],
        "answer": 1,
        "explain": "This is forced tunneling: a UDR for 0.0.0.0/0 with next hop type Virtual appliance pointing at the firewall's private IP, in a route table associated to the workload subnets, overrides the system default route to Internet. Next hop Internet would bypass the firewall, a /32 to the firewall routes almost nothing, and NSGs filter traffic but cannot redirect it.",
    },
    {
        "type": "mc",
        "q": "A subnet's route table holds a UDR for 10.1.0.0/16 pointing to an NVA, but BGP also advertises a route for 10.1.1.0/24 via the VPN gateway. Where does traffic to 10.1.1.5 go?",
        "choices": [
            "To the NVA, because UDRs always beat BGP routes",
            "To the VPN gateway, because 10.1.1.0/24 is the longest prefix match",
            "It is dropped, because the routes conflict",
            "To the NVA, because system routes are evaluated last",
        ],
        "answer": 1,
        "explain": "Route selection applies longest prefix match first, regardless of source: the /24 BGP route is more specific than the /16 UDR, so the gateway wins for 10.1.1.5. The tiebreaker UDR > BGP > system applies only when prefixes are identical — a favorite exam twist. Conflicting routes never cause drops; one always wins.",
    },
    {
        "type": "mc",
        "q": "An admin builds a route table with a correct 0.0.0.0/0 route to the firewall, yet VMs in the target subnet still reach the internet directly. What did the admin most likely forget?",
        "choices": [
            "To enable BGP on the route table",
            "To restart the virtual machines",
            "To associate the route table with the subnet",
            "To add a route for the firewall's own subnet",
        ],
        "answer": 2,
        "explain": "A route table does nothing until it is associated to one or more subnets — creating it and its routes is only half the job, and the VMs keep using the system default route to Internet. Route changes take effect without VM restarts, and BGP settings or extra routes are irrelevant to activation.",
    },
    {
        "type": "mc",
        "q": "Compliance demands that traffic from an app subnet toward a partner range 203.0.113.0/24 be silently discarded, with no NVA involved. Which UDR should the admin create?",
        "choices": [
            "203.0.113.0/24 with next hop None",
            "203.0.113.0/24 with next hop Internet",
            "203.0.113.0/24 with next hop Virtual network",
            "0.0.0.0/0 with next hop None",
        ],
        "answer": 0,
        "explain": "Next hop type None black-holes traffic — packets matching the prefix are silently dropped, which is exactly the requirement. Internet would deliver the traffic, Virtual network keeps it routing inside the VNet, and 0.0.0.0/0 with None would drop ALL non-VNet traffic, far more than the one partner range.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command shows the merged set of system, BGP, and user-defined routes a specific VM NIC is actually using?",
        "choices": [
            "az network route-table route list",
            "az network nic show-effective-route-table",
            "az network watcher show-next-hop",
            "az network vnet list-routes",
        ],
        "answer": 1,
        "explain": "az network nic show-effective-route-table (PowerShell: Get-AzEffectiveRouteTable) displays the effective routes — the ground-truth merge of system + BGP + UDR routes on a NIC. route-table route list shows only the UDRs you authored, show-next-hop tests a single destination rather than listing all routes, and vnet list-routes is not a real command.",
    },
    {
        "type": "mc",
        "q": "A helpdesk ticket asks: 'Was RDP from 203.0.113.50 to VM1 allowed or denied by a network security group — and which rule decided?' Which Network Watcher tool answers this directly?",
        "choices": ["Next hop", "Connection troubleshoot", "IP flow verify", "Packet capture"],
        "answer": 2,
        "explain": "IP flow verify evaluates a specific 5-tuple flow against the NSGs on a VM and reports allow or deny plus the exact rule responsible. Next hop tests routing rather than filtering, connection troubleshoot tests the whole path without focusing on the single deciding rule, and packet capture records traffic instead of adjudicating it.",
    },
    {
        "type": "mc",
        "q": "A VM in a spoke can no longer reach a database at 10.1.1.4, and the admin suspects a bad user-defined route is misdirecting the traffic. Which Network Watcher tool shows where traffic to that destination is being sent?",
        "choices": ["IP flow verify", "Next hop", "Effective security rules", "Topology"],
        "answer": 1,
        "explain": "Next hop reveals the next hop type and IP that traffic from a VM to a given destination will use — the direct way to spot a UDR pointing at a dead NVA or a black-hole None route. IP flow verify only evaluates NSG rules and would happily say 'allowed' while routing is broken; effective security rules and topology don't test a specific destination's path.",
    },
    {
        "type": "mc",
        "q": "An admin wants a single test that checks reachability from VM1 to 10.1.1.4:443 right now and identifies WHERE along the path (NSG, UDR, guest OS, DNS) the connection fails. Which tool fits?",
        "choices": ["Connection troubleshoot", "Packet capture", "IP flow verify", "Effective routes"],
        "answer": 0,
        "explain": "Connection troubleshoot (az network watcher test-connectivity) runs an end-to-end check from source to destination and pinpoints the failing hop — NSG, route, guest firewall, or name resolution. IP flow verify checks only the NSG layer, effective routes lists routing without testing, and packet capture records traffic for offline analysis rather than delivering a verdict.",
    },
    {
        "type": "mc",
        "q": "A VM has NSGs applied at both the subnet and the NIC, and the admin needs the single merged list of rules actually filtering the NIC. Which view provides it?",
        "choices": ["The NSG's overview blade", "IP flow verify", "Effective security rules", "Connection monitor"],
        "answer": 2,
        "explain": "Effective security rules shows the merged set of subnet-level and NIC-level NSG rules actually applied to a NIC — the filtering counterpart to effective routes, and the 'ground truth' view the exam loves. The NSG blade shows one NSG at a time, IP flow verify tests a single flow rather than listing rules, and connection monitor tracks reachability over time.",
    },
    {
        "type": "mc",
        "q": "During an intermittent application issue, a network engineer needs to record the actual packets arriving at an Azure VM without logging into the guest OS interactively. Which Network Watcher capability does this?",
        "choices": ["Topology", "Packet capture", "Next hop", "IP flow verify"],
        "answer": 1,
        "explain": "Packet capture records real traffic on a VM remotely via an agent/extension, producing capture files for deep analysis — the right tool when rule- and route-level checks aren't enough. Topology draws the network diagram, and next hop/IP flow verify test routing and NSG decisions rather than recording packets.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: If VNet-A is peered with VNet-B, and VNet-B is peered with VNet-C, resources in VNet-A can automatically communicate with resources in VNet-C.",
        "answer": False,
        "explain": "Peering is not transitive — each pair of VNets that must communicate needs its own peering, or traffic must be deliberately routed through a hub NVA/firewall or gateway with UDRs and Allow forwarded traffic. Assuming transitivity is the single most common peering trap on the exam.",
    },
    {
        "type": "tf",
        "q": "True or False: After a virtual network is created, an admin can add additional address spaces to it without recreating the VNet.",
        "answer": True,
        "explain": "A VNet can have multiple address spaces, and you can add or extend address spaces after creation — no rebuild required. The constraint is that new ranges must not collide with subnets already defined or with networks you plan to peer or connect to.",
    },
    {
        "type": "tf",
        "q": "True or False: A Standard SKU public IP address can be configured with dynamic allocation to save costs.",
        "answer": False,
        "explain": "Standard SKU public IPs are always static — the address is assigned at creation and never changes, and there is no dynamic option. Dynamic allocation existed only on the Basic SKU, which retired September 30, 2025, so on the current exam static Standard is the only game in town.",
    },
    {
        "type": "tf",
        "q": "True or False: Traffic between two VNets connected by global VNet peering crosses the public internet encrypted with IPsec.",
        "answer": False,
        "explain": "Peered traffic — regional or global — stays entirely on the private Microsoft backbone and never touches the public internet, which is why no gateway or encryption device is needed. IPsec over the internet describes a site-to-site VPN, a different construct with different latency and bandwidth characteristics.",
    },
    {
        "type": "tf",
        "q": "True or False: If a user-defined route sends traffic to a black hole, Network Watcher IP flow verify will still report the traffic as allowed, because it only evaluates NSG rules.",
        "answer": True,
        "explain": "IP flow verify checks a flow against NSG rules only — it knows nothing about routing. A UDR with next hop None (or one pointing at a dead NVA) breaks connectivity while IP flow verify happily reports 'allowed'; next hop and effective routes are the tools that expose routing culprits.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Azure reserves ______ IP addresses in every subnet, which is why a /24 yields 251 usable addresses instead of 254. (type the number)",
        "answers": ["5", "five"],
        "explain": "The five reserved addresses are the network address (.0), the default gateway (.1), two Azure DNS mappings (.2 and .3), and the broadcast address (the last IP). Usable = 2^(host bits) − 5 — the arithmetic behind nearly every subnet-sizing question.",
    },
    {
        "type": "fill",
        "q": "To deploy a VPN or ExpressRoute gateway, an admin must create a subnet with the exact name ______. (type your answer)",
        "answers": ["gatewaysubnet", "gateway subnet"],
        "explain": "GatewaySubnet is a literal, mandatory name — the gateway will not deploy into 'Gateway-Subnet' or any variant — and /27 or larger is the recommended size. Its siblings are AzureBastionSubnet (/26 or larger) for Bastion and AzureFirewallSubnet (/26) for Azure Firewall.",
    },
    {
        "type": "fill",
        "q": "To silently drop all traffic destined for a specific prefix, an admin creates a UDR with the next hop type ______. (type your answer)",
        "answers": ["none", "next hop none"],
        "explain": "Next hop None black-holes matching traffic — packets are discarded with no error returned. A stray None route is a classic root cause behind 'VM can't reach X' tickets, and effective routes (or Network Watcher next hop) is how you find it.",
    },
    {
        "type": "fill",
        "q": "When two routes have IDENTICAL prefixes, Azure prefers the route whose source is ______, then BGP, then system routes. (type the abbreviation)",
        "answers": ["udr", "user-defined route", "user defined route", "user-defined", "custom route"],
        "explain": "On identical prefixes the precedence is UDR > BGP > system — your custom routes always override what Azure or on-premises BGP advertises at the same prefix length. But remember longest prefix match is evaluated first: a more specific BGP /24 still beats a broader UDR /16.",
    },
    {
        "type": "fill",
        "q": "The Network Watcher tool that tests whether a specific inbound or outbound flow is allowed or denied by NSG rules on a VM is called IP ______ verify. (type the missing word)",
        "answers": ["flow", "ip flow", "ipflow"],
        "explain": "IP flow verify (az network watcher test-ip-flow) takes the 5-tuple — direction, protocol, local and remote IP:port — and returns allow/deny plus the exact NSG rule that decided. It evaluates only NSGs, so routing problems require next hop or effective routes instead.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each UDR next hop type to what it does with traffic.",
        "pairs": [
            ["Virtual appliance", "Sends traffic to an NVA or firewall at a private IP you specify"],
            ["Virtual network gateway", "Sends traffic toward the VPN/ExpressRoute gateway to on-premises"],
            ["Internet", "Sends traffic out Azure's internet edge"],
            ["None", "Silently drops (black-holes) the traffic"],
            ["Virtual network", "Routes the traffic within the VNet"],
        ],
        "explain": "Virtual appliance is the only type requiring an IP address (the NVA's, with IP forwarding enabled on its NIC); gateway aims at on-premises; Internet exits Azure; None discards; Virtual network keeps traffic in-VNet. Forced tunneling = 0.0.0.0/0 via Virtual appliance.",
    },
    {
        "type": "match",
        "q": "Match each Network Watcher tool to the question it answers.",
        "pairs": [
            ["IP flow verify", "Is this flow allowed or denied by an NSG, and by which rule?"],
            ["Next hop", "Where is traffic from this VM to this destination routed?"],
            ["Connection troubleshoot", "Can source reach destination now, and where does the path fail?"],
            ["Packet capture", "Record the actual packets on a VM remotely for analysis"],
            ["Topology", "Draw the visual diagram of VNets, subnets, and NICs"],
        ],
        "explain": "Match the verb in the stem: 'allowed/denied' is the NSG layer (IP flow verify), 'where routed' is the routing layer (next hop), 'end to end' is connection troubleshoot, 'capture' is packet capture, and 'see the layout' is topology. Each exam symptom maps to exactly one tool.",
    },
    {
        "type": "match",
        "q": "Match each specially named or configured subnet to its purpose and size rule.",
        "pairs": [
            ["GatewaySubnet", "VPN/ExpressRoute gateway — /27 or larger recommended"],
            ["AzureBastionSubnet", "Azure Bastion — /26 or larger required"],
            ["AzureFirewallSubnet", "Azure Firewall — /26"],
            ["Delegated subnet", "Dedicated to a PaaS service such as Microsoft.Web/serverFarms"],
        ],
        "explain": "The three special subnet names are literal and mandatory — a gateway will not deploy into a subnet with any other name. Delegation is different: any subnet name works, but the subnet is handed to one PaaS service, which gains permission to create its resources there.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps to force all internet-bound traffic from a spoke subnet through a hub firewall (NVA), from first to last.",
        "items": [
            "Create a route table resource",
            "Add a route for 0.0.0.0/0 with next hop Virtual appliance and the firewall's private IP",
            "Enable IP forwarding on the NVA's network interface",
            "Associate the route table with the spoke subnet",
            "Check the VM NIC's effective routes to confirm the override",
        ],
        "explain": "The route table must exist before routes go into it, the 0.0.0.0/0 UDR needs the appliance's IP, the NVA's NIC must have IP forwarding enabled to accept traffic not addressed to it, and nothing happens until the table is associated with the subnet. Effective routes is the ground-truth verification that the UDR now beats the system Internet route.",
    },
    {
        "type": "order",
        "q": "Arrange the lifecycle of a VNet peering between vnet-a and vnet-b, from first event to last.",
        "items": [
            "Create the peering link on vnet-a pointing at vnet-b",
            "The peering state on vnet-a shows Initiated",
            "Create the mirrored peering link on vnet-b pointing at vnet-a",
            "Both links transition to the Connected state",
            "Resources communicate over private IPs across the Microsoft backbone",
        ],
        "explain": "A peering is two links, one authored on each VNet. With only one side created the state is Initiated — the classic 'peering stuck' symptom — and only when the reverse link exists do both sides show Connected and traffic flow privately over the backbone with no downtime to either VNet.",
    },
    {
        "type": "order",
        "q": "Arrange the practical Network Watcher diagnosis flow for 'VM-A cannot reach VM-B', from first tool to last.",
        "items": [
            "Topology — visualize the VNets, subnets, and NICs involved",
            "IP flow verify — test whether NSGs allow the flow",
            "Next hop — test where the traffic is actually routed",
            "Connection troubleshoot — get the end-to-end verdict on the path",
            "Packet capture — record raw traffic for deep analysis",
        ],
        "explain": "The flow moves from map to layers to evidence: see the layout first, test the NSG (filtering) layer, then the routing layer, then run the end-to-end check, and only capture packets when the higher-level tools haven't isolated the fault. Each tool answers one specific question, which is exactly how exam stems are worded.",
    },
]
