TOPIC = {
    "id": "4.3",
    "domain": 4,
    "title": "Configure name resolution and load balancing.",
    "short": "DNS & Load Balancing",
}

TERMS = [
    ("Azure DNS", "Hosting service that answers queries for your DNS zones from Azure's global anycast name-server network — it hosts zones but is NOT a domain registrar"),
    ("DNS delegation", "Replacing the domain's NS records at the registrar with the four Azure name servers assigned to the zone, so the Internet asks Azure for your records"),
    ("Record set", "Collection of DNS records sharing the same name and type, managed as one unit with a single TTL"),
    ("TTL (time to live)", "Seconds a resolver may cache a DNS answer before querying again — set per record set"),
    ("CNAME record", "Record mapping one name to another name (www → app.azurewebsites.net); forbidden at the zone apex by DNS standards"),
    ("Alias record set", "A/AAAA/CNAME record set that points at an Azure resource (public IP, Traffic Manager, Front Door/CDN) and tracks it automatically — the only way to get CNAME-like behavior at the apex"),
    ("Private DNS zone", "Azure DNS zone that resolves names only inside virtual networks attached to it via links — invisible to the Internet"),
    ("Virtual network link", "Object attaching a VNet to a private DNS zone so its VMs can resolve (and optionally register) records in the zone"),
    ("Auto-registration", "Link setting that automatically creates and deletes A records for VMs in the linked VNet; a VNet can be a registration VNet for only ONE private zone"),
    ("Split-horizon DNS", "Hosting the same zone name publicly and privately with different answers — internal clients get private IPs, the Internet gets public ones"),
    ("168.63.129.16", "The Azure virtual public IP: source of Azure-provided DNS for VNets and of every load-balancer health probe"),
    ("Custom DNS servers", "DNS server IPs set on a VNet (or per NIC) to replace Azure-provided DNS; running VMs pick them up only after a restart or DHCP renewal"),
    ("Azure Load Balancer", "Regional layer 4 (TCP/UDP) load balancer distributing inbound flows from a frontend across healthy backend-pool instances — no TLS termination, no URL awareness"),
    ("Standard SKU", "The current Load Balancer SKU: 99.99% SLA, zone-redundant frontends, secure by default (NSG must allow traffic); Basic retired September 30, 2025"),
    ("Internal load balancer", "Load balancer whose frontend is a private IP inside the VNet — reachable only from the VNet, peered VNets, and on-prem, never the Internet"),
    ("Backend pool", "The set of VM/VMSS NICs behind a load balancer that receive distributed traffic — no membership, no traffic"),
    ("Health probe", "TCP or HTTP(S) check from 168.63.129.16 deciding which instances get new flows; an HTTP(S) probe must receive exactly HTTP 200 or the instance is pulled"),
    ("Load-balancing rule", "Rule mapping a frontend port and protocol to a backend port across the whole backend pool (e.g., TCP 443 → 443)"),
    ("Inbound NAT rule", "Rule port-forwarding a frontend port to ONE specific VM — the pattern for per-VM RDP/SSH behind a load balancer"),
    ("Outbound rule", "Explicit SNAT configuration on a Standard public LB giving backend VMs outbound Internet access through the frontend IP"),
    ("HA ports", "Internal Standard LB rule with port 0 / protocol All that balances every port and protocol in one rule — required for highly available NVA firewalls"),
    ("Session persistence", "Distribution setting: None = 5-tuple hash (best spread), Client IP = 2-tuple (source IP affinity), Client IP and protocol = 3-tuple"),
    ("Floating IP", "Direct-server-return option making the backend see the frontend IP as the destination — required for SQL Server Always On availability group listeners"),
    ("AzureLoadBalancer service tag", "NSG service tag covering the health-probe source (168.63.129.16); denying it marks every backend instance unhealthy"),
    ("Application Gateway", "Regional layer 7 HTTP(S) load balancer: URL-path routing, host headers, cookie affinity, TLS termination, WAF"),
    ("Traffic Manager", "Global DNS-based load balancer routing clients by returning endpoints in DNS: performance, priority, weighted, or geographic"),
    ("Azure Front Door", "Global layer 7 anycast entry point: HTTP acceleration at the edge, caching, path routing across regions, WAF"),
    ("SNAT port exhaustion", "Outbound failure mode where backend VMs run out of source NAT ports — fixed with outbound rules allocating more ports or a NAT Gateway"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An admin creates a public DNS zone for contoso.com in Azure and adds A records, but a week later the domain still does not resolve from the Internet. What was missed?",
        "choices": [
            "Delegation — the four Azure name servers were never set as NS records at the registrar",
            "A virtual network link was not created for the zone",
            "The zone's TTL is set too high",
            "An alias record set is required before the zone activates",
        ],
        "answer": 0,
        "explain": "Creating a public zone assigns four Azure name servers, but the Internet only asks Azure once you delegate — replace the NS records at the registrar with those exact four servers. Virtual network links apply to private zones only, TTL affects caching duration (not whether resolution works), and alias records are optional conveniences, not activation steps.",
    },
    {
        "type": "mc",
        "q": "A project manager asks an admin to 'buy contoso.io in Azure DNS.' What should the admin explain?",
        "choices": [
            "Azure DNS sells domains only through the Azure portal Marketplace blade",
            "Azure DNS hosts zones but is not a registrar — buy the domain elsewhere (or via App Service domains), then host its records in an Azure DNS zone",
            "Domains can be purchased with az network dns zone create",
            "Azure DNS registers domains automatically when a zone name is unclaimed",
        ],
        "answer": 1,
        "explain": "Azure DNS is a hosting service, not a registrar — you cannot purchase a domain in it. Buy from a third-party registrar or via App Service domains, then create the zone and delegate. az network dns zone create only creates a hosting zone; it registers nothing, and there is no Marketplace domain purchase in Azure DNS.",
    },
    {
        "type": "mc",
        "q": "The naked root domain contoso.com must point at an Azure Front Door endpoint. A CNAME creation attempt at the apex fails. What should the admin create instead?",
        "choices": [
            "An SRV record targeting the Front Door hostname",
            "A TXT record containing the Front Door endpoint",
            "An alias A record set pointing at the Front Door endpoint",
            "An NS record delegating the apex to Front Door",
        ],
        "answer": 2,
        "explain": "DNS standards forbid a CNAME at the zone apex, and Azure's answer is the alias record set: an alias A (or AAAA) record can point directly at a Front Door endpoint, Traffic Manager profile, or public IP and gives CNAME-like behavior at the root. SRV and TXT records serve service discovery and text verification, and NS records delegate child zones — none point the apex at a resource.",
    },
    {
        "type": "mc",
        "q": "A record for api.contoso.com points at a VM's public IP address, which occasionally changes when the VM is redeployed, breaking the record. What is the lowest-maintenance fix?",
        "choices": [
            "Lower the record set's TTL to 30 seconds",
            "Convert the record to an alias A record set targeting the public IP resource",
            "Create a PTR record for the public IP",
            "Move the record to a private DNS zone",
        ],
        "answer": 1,
        "explain": "An alias record set tracks the Azure resource it targets: if the public IP address changes, the alias updates itself, and if the resource is deleted the record is cleaned up instead of dangling. A low TTL only shortens how long the stale answer is cached, PTR records handle reverse lookups, and private zones do not resolve from the Internet at all.",
    },
    {
        "type": "mc",
        "q": "An admin needs VMs deployed into vnet-hub to automatically get A records in internal.contoso.com, removed again when the VMs are deleted. What must be configured?",
        "choices": [
            "A public DNS zone with dynamic update enabled",
            "Custom DNS servers on the VNet pointing at 168.63.129.16",
            "An alias record set for each VM",
            "A virtual network link from the private zone to vnet-hub with auto-registration enabled",
        ],
        "answer": 3,
        "explain": "Auto-registration is a property of the virtual network link on a private DNS zone: with it enabled, Azure creates and deletes A records for VMs in the linked VNet automatically. Public zones have no auto-registration, 168.63.129.16 is the default anyway (setting it as a custom server changes nothing), and alias records track Azure resources like public IPs, not VM lifecycles.",
    },
    {
        "type": "mc",
        "q": "vnet-app is already a registration VNet for the private zone corp.contoso.com. The admin now wants it to also auto-register into a second private zone. What is the constraint?",
        "choices": [
            "A VNet can be a registration VNet for only one private zone, though it can resolve against many",
            "A VNet can register into up to five private zones",
            "Registration requires a Standard SKU zone for each additional link",
            "Auto-registration works only in the VNet's home region",
        ],
        "answer": 0,
        "explain": "A linked VNet is either a registration VNet (auto-registration on) or a resolution VNet (query-only), and it can be a registration VNet for exactly one private DNS zone. It may hold resolution links to many other zones. Private DNS zones have no SKU tiers, and they are global resources not bound to a region.",
    },
    {
        "type": "mc",
        "q": "An admin runs 'az network vnet update -g rg-net -n vnet-hub --dns-servers 10.0.0.4' to point the VNet at on-prem AD DNS, but running VMs keep using 168.63.129.16. Why?",
        "choices": [
            "The command updates only newly created subnets",
            "Custom DNS requires a private DNS zone to be linked first",
            "VMs get DNS via DHCP and must be restarted (or renew their lease) to pick up the change",
            "10.0.0.4 must be registered as an Azure DNS forwarder first",
        ],
        "answer": 2,
        "explain": "VMs receive their DNS settings through DHCP, so a VNet-level DNS change does not reach running VMs until they restart or renew the lease — this is a propagation issue, not a broken configuration. The command itself is correct and applies VNet-wide; no private zone link or forwarder registration is involved.",
    },
    {
        "type": "mc",
        "q": "The company hosts contoso.com publicly, but internal clients must resolve app.contoso.com to a private IP while the Internet keeps getting the public IP. What pattern achieves this?",
        "choices": [
            "Split-horizon DNS: a private DNS zone named contoso.com linked to the VNets, alongside the public zone",
            "An alias record set that returns different values by source network",
            "Conditional TTLs on the public record set",
            "An inbound NAT rule translating the public IP to the private IP",
        ],
        "answer": 0,
        "explain": "Because the same zone name can exist publicly and privately with different answers, a private zone named contoso.com linked to the VNets gives internal clients private IPs while the public zone serves the Internet — split-horizon DNS. Alias records and TTLs cannot vary answers by source, and NAT rules forward ports on a load balancer; they do not answer DNS queries.",
    },
    {
        "type": "mc",
        "q": "Which az CLI command creates a DNS zone that resolves names only inside linked virtual networks?",
        "choices": [
            "az network dns zone create -g rg-dns -n internal.contoso.com",
            "az network private-dns zone create -g rg-dns -n internal.contoso.com",
            "az network vnet update -g rg-dns -n internal.contoso.com --dns-servers",
            "az network private-dns link vnet create -g rg-dns -n internal.contoso.com",
        ],
        "answer": 1,
        "explain": "Private zones live under 'az network private-dns zone create'; 'az network dns zone create' makes a public zone answering Internet queries. 'az network vnet update --dns-servers' sets custom DNS servers on a VNet, and 'private-dns link vnet create' attaches a VNet to an already-existing private zone — a required second step, but it does not create the zone.",
    },
    {
        "type": "mc",
        "q": "Which PowerShell cmdlet creates a public Azure DNS zone for contoso.com?",
        "choices": [
            "New-AzPrivateDnsZone -ResourceGroupName rg-dns -Name contoso.com",
            "New-AzDnsRecordSet -ResourceGroupName rg-dns -ZoneName contoso.com",
            "New-AzDnsZone -ResourceGroupName rg-dns -Name contoso.com",
            "Set-AzDnsZone -ResourceGroupName rg-dns -Name contoso.com",
        ],
        "answer": 2,
        "explain": "New-AzDnsZone creates the public hosting zone; its private counterpart is New-AzPrivateDnsZone. New-AzDnsRecordSet adds record sets inside an existing zone, and Set-AzDnsZone updates properties of a zone that already exists — neither creates the zone itself.",
    },
    {
        "type": "mc",
        "q": "In a three-tier app, the business-logic tier must be load balanced but must never be reachable from the Internet — only from the web tier in the same VNet. What should front it?",
        "choices": [
            "An internal load balancer with a private frontend IP",
            "A public load balancer with a restrictive load-balancing rule",
            "Azure Front Door with a private origin",
            "A public load balancer in a different resource group",
        ],
        "answer": 0,
        "explain": "An internal (private) load balancer's frontend is a private IP inside the VNet, so it accepts traffic only from internal sources — the VNet, peered VNets, and on-prem links. A public LB's frontend is by definition a public IP, and moving it to another resource group changes nothing about exposure. Front Door is a global Internet-facing entry point, the opposite of the requirement.",
    },
    {
        "type": "mc",
        "q": "Admins must RDP to VM2 specifically — not to whichever VM the pool picks — behind a public Standard load balancer. What should be configured?",
        "choices": [
            "A load-balancing rule mapping frontend 3389 to backend 3389",
            "An inbound NAT rule mapping a frontend port such as 50002 to VM2's port 3389",
            "Client IP session persistence on the RDP rule",
            "An HA ports rule scoped to VM2",
        ],
        "answer": 1,
        "explain": "An inbound NAT rule port-forwards a frontend port to one specific VM — e.g., 50002 → VM2:3389 — which is the only way to guarantee reaching a particular instance. A load-balancing rule always spreads across the whole pool, session persistence only makes repeat connections sticky (the first still lands anywhere), and HA ports rules apply to internal LBs and cannot target a single VM.",
    },
    {
        "type": "mc",
        "q": "A pair of firewall NVAs behind an internal Standard load balancer must inspect traffic on every port and protocol without creating dozens of rules. Which configuration achieves this?",
        "choices": [
            "An HA ports rule with frontend and backend port 0 and protocol All",
            "An outbound rule covering ports 1-65535",
            "One load-balancing rule per well-known port",
            "Floating IP on a TCP 443 rule",
        ],
        "answer": 0,
        "explain": "An HA ports rule (internal Standard LB only) uses port 0 and protocol All to balance every port and protocol in a single rule — the required pattern for highly available NVA clusters. Outbound rules govern SNAT for egress, per-port rules cannot cover all 65,535 ports practically, and floating IP changes the destination IP the backend sees, not port coverage.",
    },
    {
        "type": "mc",
        "q": "A kiosk application breaks unless every connection from a given client IP lands on the same backend VM, regardless of protocol. Which session persistence setting should the admin select?",
        "choices": ["None (5-tuple hash)", "Client IP and protocol (3-tuple)", "Client IP (2-tuple)", "Floating IP"],
        "answer": 2,
        "explain": "Client IP persistence hashes on a 2-tuple, so all traffic from one source IP reaches the same instance — source IP affinity. The default None (5-tuple) includes source port, so each new connection can land elsewhere; 'Client IP and protocol' (3-tuple) would split TCP and UDP from the same client across instances. Floating IP is direct server return, not a persistence mode.",
    },
    {
        "type": "mc",
        "q": "A SQL Server Always On availability group listener sits behind an internal load balancer, and connections to the listener fail. Which load-balancing rule setting is required for this scenario?",
        "choices": ["HA ports", "Floating IP (direct server return)", "TCP reset on idle", "An outbound rule for port 1433"],
        "answer": 1,
        "explain": "Floating IP makes the backend see the frontend IP as the destination, which the Always On listener requires and which also lets multiple rules share a port. HA ports is for NVAs balancing all ports, TCP reset only sends RSTs on idle timeout, and outbound rules govern egress SNAT — none satisfy the listener's direct-server-return requirement.",
    },
    {
        "type": "mc",
        "q": "Which statement about the Standard Load Balancer SKU is TRUE?",
        "choices": [
            "It is open by default, passing traffic until an NSG blocks it",
            "It supports a maximum backend pool of 300 instances in one availability set",
            "It is secure by default — traffic is blocked until an NSG explicitly allows it — and carries a 99.99% SLA",
            "It supports only dynamic public IP frontends without zone options",
        ],
        "answer": 2,
        "explain": "Standard is secure by default (nothing reaches the backend without an explicit NSG allow), offers a 99.99% SLA, and supports zone-redundant or zonal static frontends with pools up to 5,000 instances. The 'open by default,' 300-instance, and no-zone traits all describe the Basic SKU, which retired September 30, 2025 — on the exam, Standard is always the answer.",
    },
    {
        "type": "mc",
        "q": "Minutes after a security team applies a stricter custom NSG to the web subnet, every backend instance behind the load balancer shows unhealthy at once. What is the most likely cause?",
        "choices": [
            "The load balancer's SKU was downgraded by the NSG",
            "All the web VMs crashed simultaneously",
            "The health probe interval is too short",
            "The NSG now blocks the probe source 168.63.129.16 (AzureLoadBalancer service tag) or the probe port",
        ],
        "answer": 3,
        "explain": "Health probes originate from 168.63.129.16, covered by the AzureLoadBalancer service tag; an NSG that denies that source or the probe port marks every instance unhealthy simultaneously — the timing right after the NSG change is the giveaway. Fix the NSG, not the LB. NSGs cannot change SKUs, a simultaneous all-VM crash is implausible, and probe intervals do not cause instant fleet-wide failure.",
    },
    {
        "type": "mc",
        "q": "An HTTP health probe against /health marks instances down even though browsing the site works. The site redirects all HTTP requests to HTTPS with a 302. Why does the probe fail?",
        "choices": [
            "An HTTP(S) probe requires exactly HTTP 200 — a 302 redirect counts as a failure",
            "HTTP probes are only supported on Basic SKU load balancers",
            "The probe needs Floating IP enabled to follow redirects",
            "302 responses are only accepted on probe port 443",
        ],
        "answer": 0,
        "explain": "An HTTP(S) probe must receive exactly HTTP 200 within the timeout; redirects (301/302), auth challenges, and 403s all count as failures — a classic trap when the health path sits behind HTTP-to-HTTPS redirection. Fix the health endpoint to return 200 on the probed port or probe with HTTPS. Probes exist on Standard, floating IP is unrelated to probing, and no port makes a 302 acceptable.",
    },
    {
        "type": "mc",
        "q": "A TCP port-80 probe reports every instance healthy, yet users receive application error pages from the site. What probe change would let the load balancer detect the failing application?",
        "choices": [
            "Shorten the TCP probe interval to one second",
            "Switch to an HTTP probe against a real health path so app-level failures return non-200 and fail the probe",
            "Change the probe to UDP on the same port",
            "Raise the probe port above 1024",
        ],
        "answer": 1,
        "explain": "A TCP probe succeeds whenever the port accepts a connection, even if the app behind it is throwing errors. An HTTP probe against a genuine health path (e.g., /health) fails on anything other than a 200, so broken instances get pulled from rotation. Faster intervals only repeat the same blind check, and UDP or high ports do not add application awareness.",
    },
    {
        "type": "mc",
        "q": "One VM behind a load balancer never receives any traffic, though its twin does. Probes, NSGs, and rules all check out. Which az command would confirm the suspected cause?",
        "choices": [
            "az network nic show -g rg-app -n vm1-nic --query \"ipConfigurations[].loadBalancerBackendAddressPools\" — verify the NIC is in the backend pool",
            "az network lb probe create — recreate the health probe",
            "az network nsg rule list — list the NSG rules again",
            "az network lb rule create — add a second load-balancing rule",
        ],
        "answer": 0,
        "explain": "When everything else checks out, the classic cause is that the VM's NIC was never added to the backend pool — no membership, no traffic, regardless of probes. Querying the NIC's ipConfigurations for loadBalancerBackendAddressPools confirms it. Recreating probes or rules changes configuration blindly, and re-listing NSG rules re-checks something already ruled out.",
    },
    {
        "type": "mc",
        "q": "Backend VMs behind a Standard public load balancer serve inbound traffic fine, but their own outbound calls to external APIs intermittently fail as connections pile up. What is the likely fix?",
        "choices": [
            "Enable Floating IP on the load-balancing rule",
            "Configure outbound rules with more allocated SNAT ports, or front the subnet with a NAT Gateway",
            "Switch session persistence to Client IP",
            "Convert the load balancer to internal",
        ],
        "answer": 1,
        "explain": "Outbound failures under connection load behind a Standard public LB point to missing outbound rules or SNAT port exhaustion; the fix is explicit outbound rules allocating more ports or a NAT Gateway on the subnet. Floating IP and session persistence shape inbound flows, and converting to internal would remove the public outbound path entirely rather than fix it.",
    },
    {
        "type": "mc",
        "q": "In Load Balancer Insights, Data Path Availability is 100% but Health Probe Status is near zero for all instances. What does this combination indicate?",
        "choices": [
            "The Azure platform's data path to the frontend is degraded",
            "The metrics pipeline is broken and both values should be ignored",
            "The platform path is fine — the problem is inside the VMs or their NSGs, so investigate probe responses",
            "The frontend public IP has been deallocated",
        ],
        "answer": 2,
        "explain": "Data Path Availability measures whether Azure's data path to the frontend works; Health Probe Status measures per-instance probe pass rates. Healthy path plus failing probes means the platform is fine and the failure lies in your VMs or NSGs — app not listening, wrong probe path/port, or a blocked 168.63.129.16. A dead frontend or platform issue would drag Data Path Availability down too.",
    },
    {
        "type": "mc",
        "q": "Requests must be routed to different backend pools based on URL path (/images vs /video), with TLS terminated and a web application firewall applied, all within one region. Which service is required?",
        "choices": ["Azure Load Balancer (Standard)", "Azure Traffic Manager", "Application Gateway", "Azure Bastion"],
        "answer": 2,
        "explain": "URL-path routing, TLS termination, cookie affinity, and WAF are layer 7 features — that is Application Gateway, the regional L7 service. Azure Load Balancer is layer 4 and never inspects URLs or terminates TLS, Traffic Manager only returns endpoints via DNS, and Bastion provides browser-based RDP/SSH, not load balancing.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: You can purchase a new domain name directly through Azure DNS.",
        "answer": False,
        "explain": "Azure DNS is a hosting service, not a registrar — it answers queries for zones you create but sells nothing. Purchase the domain at a third-party registrar (or via App Service domains), then create the zone in Azure DNS and delegate the four assigned name servers.",
    },
    {
        "type": "tf",
        "q": "True or False: With a Standard SKU load balancer, backend traffic is blocked until a network security group explicitly allows it.",
        "answer": True,
        "explain": "Standard is secure by default: even a perfectly configured LB passes nothing to the backend until an NSG rule allows the traffic. This is the number-one cause of 'the load balancer doesn't work' in labs and exam stems — and the opposite of the retired Basic SKU's open-by-default behavior.",
    },
    {
        "type": "tf",
        "q": "True or False: An internal load balancer's frontend can be reached from on-premises networks connected via VPN or ExpressRoute.",
        "answer": True,
        "explain": "An internal LB's private frontend IP is reachable from any internal source that can route to it — the VNet itself, peered VNets, and on-premises networks over VPN or ExpressRoute. What it can never receive is traffic directly from the Internet; that requires a public load balancer.",
    },
    {
        "type": "tf",
        "q": "True or False: A load-balancing rule can be used to forward a frontend port to one specific VM in the backend pool.",
        "answer": False,
        "explain": "A load-balancing rule always distributes across the whole backend pool — it cannot target an individual VM. Reaching one specific instance (per-VM RDP/SSH, for example) is the job of an inbound NAT rule, which maps a unique frontend port to that VM's port.",
    },
    {
        "type": "tf",
        "q": "True or False: Azure Load Balancer can terminate TLS connections and route requests based on cookies.",
        "answer": False,
        "explain": "Azure Load Balancer operates at layer 4, balancing TCP/UDP connections — it never inspects URLs, reads cookies, or terminates TLS. When a scenario needs those HTTP-aware features, the answer is Application Gateway (regional) or Front Door (global), and blaming the LB for certificate errors is always wrong.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Azure-provided DNS for VNets and every load-balancer health probe originate from the same Azure virtual IP address: ______. (type the IP)",
        "answers": ["168.63.129.16"],
        "explain": "168.63.129.16 is Azure's virtual public IP: it serves default name resolution inside every VNet and is the source of all load-balancer health probes. Blocking it in an NSG breaks both — which is why the AzureLoadBalancer service tag exists to allow it.",
    },
    {
        "type": "fill",
        "q": "The special type of record set that points at an Azure resource such as a public IP or Front Door endpoint, tracks changes automatically, and works at the zone apex is a(n) ______ record set. (type your answer)",
        "answers": ["alias", "alias record", "alias record set"],
        "explain": "Alias record sets (available for A, AAAA, and CNAME types) target an Azure resource instead of a hard-coded value, updating automatically when the resource's IP changes. Their killer feature is CNAME-like behavior at the zone apex, where DNS standards forbid a real CNAME.",
    },
    {
        "type": "fill",
        "q": "To allow health probes through a custom NSG, an admin should permit inbound traffic from the ______ service tag. (type the tag name)",
        "answers": ["azureloadbalancer", "azure load balancer", "azureloadbalancer service tag"],
        "explain": "The AzureLoadBalancer service tag represents the probe source 168.63.129.16 and appears in the default NSG rules. If a custom rule denies it — or the probe/data port is not allowed — instances go unhealthy and receive no new flows.",
    },
    {
        "type": "fill",
        "q": "The load-balancing rule option that makes the backend see the frontend IP as the destination — required for SQL Server Always On availability group listeners — is called ______ IP. (type the missing word)",
        "answers": ["floating", "floating ip"],
        "explain": "Floating IP (direct server return) preserves the frontend IP as the destination the backend sees, which the Always On listener requires and which also lets multiple rules share the same port. Without it, listener connections through the LB fail.",
    },
    {
        "type": "fill",
        "q": "Complete the az CLI command that port-forwards frontend port 50001 to one VM's RDP port: az network lb ______ create --frontend-port 50001 --backend-port 3389 ... (type the subcommand)",
        "answers": ["inbound-nat-rule", "inbound nat rule", "inboundnatrule"],
        "explain": "az network lb inbound-nat-rule create builds the per-VM port forward — frontend 50001 to a specific VM's 3389 — that a load-balancing rule cannot provide, since rules always spread across the whole pool. Each admin-access VM gets its own unique frontend port.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each DNS record type to its purpose.",
        "pairs": [
            ["A", "Maps a name to an IPv4 address"],
            ["CNAME", "Maps a name to another name; forbidden at the zone apex"],
            ["MX", "Routes mail for the domain, with priority values"],
            ["TXT", "Holds arbitrary text for domain verification and SPF/DKIM"],
            ["PTR", "Maps an IP address back to a name (reverse lookup)"],
            ["SRV", "Locates a service by priority, weight, port, and target"],
        ],
        "explain": "Match by direction and payload: A goes name-to-IPv4 (AAAA for IPv6), CNAME goes name-to-name and is illegal at the apex, MX steers mail, TXT carries verification strings and SPF, PTR reverses IP-to-name, and SRV advertises services like SIP and LDAP. The zone's NS and SOA records are created automatically with the zone.",
    },
    {
        "type": "match",
        "q": "Match each Azure Load Balancer component to what it does.",
        "pairs": [
            ["Frontend IP configuration", "The public or private IP that clients connect to"],
            ["Backend pool", "The VM and VMSS NICs that receive distributed traffic"],
            ["Health probe", "TCP or HTTP(S) check deciding which instances get new flows"],
            ["Load-balancing rule", "Maps a frontend port to a backend port across the whole pool"],
            ["Inbound NAT rule", "Port-forwards a frontend port to one specific VM"],
            ["Outbound rule", "Explicit SNAT giving backend VMs outbound Internet access"],
        ],
        "explain": "The anatomy is fixed: traffic enters at a frontend IP, a rule spreads it across the backend pool among instances the probe reports healthy, NAT rules carve out per-VM port forwards, and outbound rules handle egress SNAT. Exam stems usually hinge on rule-versus-NAT-rule and on what the probe controls.",
    },
    {
        "type": "match",
        "q": "Match each load-balancing service to its signature scenario.",
        "pairs": [
            ["Azure Load Balancer", "Regional layer 4 TCP/UDP distribution with ultra-low latency"],
            ["Application Gateway", "Regional layer 7: URL-path routing, TLS termination, WAF"],
            ["Traffic Manager", "Global DNS-based routing: performance, priority, weighted, geographic"],
            ["Azure Front Door", "Global anycast HTTP entry point with edge caching and WAF"],
        ],
        "explain": "Read the layer and the scope: L4 regional is Load Balancer, L7 regional is Application Gateway, DNS-level global is Traffic Manager, and L7 global at anycast edge locations is Front Door. Any mention of URLs, cookies, or certificates rules out Load Balancer immediately.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps to host an externally purchased domain in Azure DNS, from first to last.",
        "items": [
            "Purchase the domain from a third-party registrar",
            "Create a public DNS zone for the domain in Azure",
            "Note the four Azure name servers assigned to the zone",
            "Update the NS records at the registrar with those four name servers",
            "Create the record sets (A, CNAME, MX, TXT) in the zone",
            "Verify resolution with nslookup against the zone's name servers",
        ],
        "explain": "Azure DNS hosts but never sells domains, so purchase comes first; creating the zone assigns four Azure name servers, and delegation — copying them into the registrar's NS records — is what makes the Internet ask Azure at all. Records can then be added and verified with nslookup. Skipping delegation is the classic 'zone exists but nothing resolves' scenario.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to build a working Standard public load balancer for a web tier, from first to last.",
        "items": [
            "Create a Standard SKU public IP for the frontend",
            "Create the load balancer with its frontend IP configuration and backend pool",
            "Add the web VMs' NICs to the backend pool",
            "Create an HTTP health probe against the application's health path",
            "Create a load-balancing rule mapping frontend port 80 to backend port 80 with that probe",
            "Add an NSG rule allowing the AzureLoadBalancer service tag and port 80 inbound",
        ],
        "explain": "The frontend IP and pool are the LB's skeleton, VM NICs must join the pool or they get no traffic, and the rule needs an existing probe to reference. The final NSG step is what trips people: Standard is secure by default, so without an explicit allow for the probe source and the app port, a perfectly built LB still passes nothing.",
    },
    {
        "type": "order",
        "q": "A backend instance shows unhealthy. Arrange the troubleshooting checklist in the order it should be worked.",
        "items": [
            "Check whether an NSG blocks the probe source 168.63.129.16 or the probe port",
            "Verify the probe configuration — port, protocol, and HTTP path match the app",
            "Confirm the application is listening and its health endpoint returns HTTP 200",
            "Verify the VM's NIC is actually in the backend pool",
            "Check the load-balancing rule for transposed ports or wrong frontend IP",
            "Investigate outbound rules and SNAT port exhaustion for egress failures",
        ],
        "explain": "The checklist runs from the most common cause inward: NSGs blocking the probe are the number-one culprit, then probe misconfiguration, then the app itself (a 302 or 403 counts as a probe failure), then pool membership, rule mismatches, and finally outbound SNAT issues for egress-side symptoms. Working it in order avoids chasing LB settings when the real problem is a firewall rule or a missing pool entry.",
    },
]
