TOPIC = {
    "id": "5.1",
    "domain": 5,
    "title": "Monitor resources in Azure.",
    "short": "Azure Monitor & Insights",
}

TERMS = [
    ("Metrics", "Lightweight numeric time-series values (CPU %, IOPS, request counts) collected automatically, near-real-time, retained 93 days"),
    ("Logs", "Records and events with rich properties that must be routed (diagnostic settings, agents) into a Log Analytics workspace and queried with KQL"),
    ("Metrics Explorer", "Portal tool for charting platform metrics by choosing scope, metric, aggregation, and time range/granularity"),
    ("Aggregation", "How metric samples are rolled up per interval — Average, Minimum, Maximum, Sum (Total), or Count"),
    ("Dimension", "A name/value property on a metric (e.g., API name) that splitting breaks into one line per value and filtering restricts to chosen values"),
    ("Splitting", "Metrics Explorer feature that draws a separate chart line per dimension value, e.g., Transactions per API operation"),
    ("Activity Log", "Subscription-level control-plane record of who created, modified, or deleted what — kept 90 days free with no configuration"),
    ("Resource logs", "Data-plane logs of operations inside a resource (Key Vault reads, storage transactions) — collected only after a diagnostic setting exists"),
    ("Diagnostic setting", "Per-resource configuration that picks log categories/metrics and routes them to up to four destination types; never retroactive"),
    ("Log Analytics workspace", "The KQL-queryable log store — 30-day default interactive retention, extendable to 730 days, archive up to 12 years total"),
    ("Azure Monitor Agent (AMA)", "The only supported VM monitoring agent (MMA/OMS retired August 2024); collects guest data as directed by Data Collection Rules"),
    ("Data Collection Rule (DCR)", "Defines what guest data AMA collects (events, Syslog, counters) and which workspace receives it; one DCR can be associated with many VMs"),
    ("KQL (Kusto Query Language)", "Pipe-based query language for Log Analytics — table first, then operators like where, summarize, project, top, render"),
    ("Heartbeat table", "Log Analytics table with one record per minute per connected agent — the 'which VMs are reporting?' table"),
    ("InsightsMetrics table", "The Log Analytics table where VM insights writes its performance data (Perf holds classic agent-collected counters)"),
    ("Alert rule", "Scope + signal condition + severity + action groups; the object that detects a condition and fires an alert"),
    ("Metric alert", "Stateful alert on a metric threshold (static or dynamic) — fires once and auto-resolves when the condition clears"),
    ("Log search alert", "Alert that runs a KQL query on a schedule (e.g., every 5 minutes over the last 15) and fires when results meet the threshold"),
    ("Action group", "Reusable object holding notifications (email, SMS, push, voice, Email ARM role) and actions (runbook, Function, Logic App, webhook, ITSM, Event Hub)"),
    ("Alert processing rule", "Post-fire rule over a broad scope that suppresses notifications (e.g., maintenance windows) or attaches action groups to many alerts at once"),
    ("Severity scale", "Sev0 = Critical, Sev1 = Error, Sev2 = Warning, Sev3 = Informational, Sev4 = Verbose"),
    ("Azure Monitor Insights", "Curated, prebuilt monitoring experiences per resource type — the 'minimal configuration' answer versus hand-built workbooks"),
    ("VM insights", "Insight showing fleet performance charts plus the Map dependency view of processes and TCP connections; requires AMA + DCR, writes to InsightsMetrics"),
    ("Storage insights", "Agentless insight showing transactions, availability, latency, and capacity — compare end-to-end vs. server latency to place blame"),
    ("Network insights", "Agentless insight with a topology view and health/metrics of network resources (load balancers, gateways, firewalls, public IPs)"),
    ("Network Watcher", "Per-region suite of network diagnostic tools, enabled automatically in a region when a virtual network is created or updated there"),
    ("IP flow verify", "Network Watcher tool that tests whether a specific 5-tuple packet is allowed or denied at a VM and names the deciding NSG rule"),
    ("Next hop", "Network Watcher tool that shows where traffic from a VM routes next and which route table entry applies — catches bad UDRs"),
    ("Packet capture", "Network Watcher tool that remotely records actual traffic on a VM without RDP/SSH access"),
    ("Connection Monitor", "Continuous connectivity, latency, and packet-loss monitoring between Azure VMs, on-premises hosts, and external endpoints; results land in Log Analytics"),
    ("VNet flow logs", "The current continuous IP-traffic flow logging feature — the older NSG flow logs are deprecated (no new ones since June 2025; retirement September 2027)"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An admin needs to see a VM's CPU percentage right now, with no agents installed and no prior configuration. Where does she look?",
        "choices": [
            "The Perf table in a Log Analytics workspace",
            "Platform metrics in Metrics Explorer",
            "VM insights performance charts",
            "The Activity Log for the VM",
        ],
        "answer": 1,
        "explain": "Platform metrics like Percentage CPU are collected automatically for every Azure resource — no agent, no setup — and are near-real-time in Metrics Explorer. The Perf table and VM insights both require the Azure Monitor Agent and a DCR before they contain anything, and the Activity Log records control-plane operations, not performance data.",
    },
    {
        "type": "mc",
        "q": "A VM's CPU chart in Metrics Explorer looks flat at 40%, yet users report brief slowdowns. Which change is most likely to reveal short CPU spikes?",
        "choices": [
            "Switch the aggregation from Average to Maximum and use a finer time granularity",
            "Switch the aggregation from Average to Count",
            "Extend the time range from 1 hour to 30 days",
            "Pin the existing chart to an Azure dashboard",
        ],
        "answer": 0,
        "explain": "Average smooths bursts away; Maximum shows the highest sample per interval, and a finer granularity (e.g., 1 minute) stops short spikes from being averaged into invisibility. Count just tallies samples, a longer range coarsens the intervals and hides spikes further, and pinning changes where the chart lives, not what it shows.",
    },
    {
        "type": "mc",
        "q": "On a storage account's Transactions metric, an admin wants one chart line per API operation (GetBlob, PutBlob, etc.). What should she apply in Metrics Explorer?",
        "choices": [
            "A filter on the Response type dimension",
            "Splitting on the API name dimension",
            "The Sum aggregation",
            "A shorter time range",
        ],
        "answer": 1,
        "explain": "Splitting breaks a single metric into a separate line per value of a chosen dimension — here, API name. A filter would instead restrict the chart to specific dimension values (e.g., only GetBlob), and aggregation or time range changes never create per-operation lines.",
    },
    {
        "type": "mc",
        "q": "A capacity-planning team needs to analyze a VM's CPU trend over the past year, but Metrics Explorer only goes back about three months. What should have been configured?",
        "choices": [
            "A diagnostic setting routing the metrics to a Log Analytics workspace",
            "A longer retention period on the platform metrics database",
            "An alert processing rule to preserve the metric history",
            "The Azure Monitor Agent, which extends metric retention",
        ],
        "answer": 0,
        "explain": "Platform metrics are retained for a fixed 93 days; you cannot extend that store. For longer trend analysis you route metrics to a Log Analytics workspace via a diagnostic setting and query them with KQL. Alert processing rules manage fired alerts, and AMA collects guest data — neither changes platform-metric retention.",
    },
    {
        "type": "mc",
        "q": "An admin opens Metrics Explorer to check available memory inside an Azure Windows VM but cannot find such a metric. Why?",
        "choices": [
            "Memory metrics require a Premium-tier VM SKU",
            "Guest-OS counters like available memory require the Azure Monitor Agent and a Data Collection Rule",
            "Memory metrics are only retained for 24 hours",
            "The VM must first be pinned to a dashboard",
        ],
        "answer": 1,
        "explain": "Metrics Explorer shows host/platform metrics only; counters measured inside the guest OS — memory in use, logical-disk free space — exist only after the Azure Monitor Agent is installed and a DCR tells it to collect performance counters. VM SKU, retention, and dashboards have nothing to do with this gap.",
    },
    {
        "type": "mc",
        "q": "A production VM was deleted last week and management wants to know who deleted it and when. Where is that recorded with zero prior configuration?",
        "choices": [
            "The resource logs of the VM",
            "Boot diagnostics on the VM",
            "The subscription's Activity Log",
            "The Heartbeat table in Log Analytics",
        ],
        "answer": 2,
        "explain": "The Activity Log is the subscription-level control-plane record — who created, modified, or deleted what — kept 90 days free with no setup. Resource logs cover data-plane operations inside a resource and require a diagnostic setting, boot diagnostics show console output, and Heartbeat only reports agent liveness.",
    },
    {
        "type": "mc",
        "q": "A security team asks for a report of which Key Vault secrets were read last month, but the workspace has no such data. What is the most likely cause?",
        "choices": [
            "The Activity Log retention was left at 90 days",
            "No diagnostic setting was ever created on the Key Vault, so resource logs were never collected",
            "The Azure Monitor Agent is not installed on the Key Vault",
            "The workspace's interactive retention is set below 30 days",
        ],
        "answer": 1,
        "explain": "Secret reads are data-plane operations captured in resource logs, which are collected only after a diagnostic setting routes them somewhere — and settings are not retroactive, so last month's data simply does not exist. The Activity Log covers control-plane events, agents apply to VMs not PaaS vaults, and 30 days is the workspace minimum default, not the issue.",
    },
    {
        "type": "mc",
        "q": "Compliance requires streaming NSG and firewall logs to the company's third-party SIEM. Which diagnostic-setting destination should the admin choose?",
        "choices": [
            "Log Analytics workspace",
            "Storage account",
            "Event Hubs",
            "Azure dashboard",
        ],
        "answer": 2,
        "explain": "Event Hubs is the diagnostic-setting destination built for streaming logs to external SIEMs and third-party tools. A Log Analytics workspace is for KQL query and alerting inside Azure, a storage account is cheap archive, and a dashboard is a visualization surface, not a log destination.",
    },
    {
        "type": "mc",
        "q": "An admin must keep Log Analytics workspace data interactively queryable for two years. What is the maximum interactive retention she can configure?",
        "choices": ["90 days", "365 days", "730 days", "12 years"],
        "answer": 2,
        "explain": "Interactive retention on a Log Analytics workspace defaults to 30 days and can be raised to a maximum of 730 days — exactly two years, so the requirement fits. Beyond that, data can move to low-cost archive tiers for a total of up to 12 years, but archived data is not directly interactively queryable; 90 days is the Activity Log's free platform retention.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command routes a Key Vault's audit logs to a Log Analytics workspace?",
        "choices": [
            "az monitor diagnostic-settings create",
            "az monitor log-analytics workspace create",
            "az monitor data-collection rule association create",
            "az monitor activity-log alert create",
        ],
        "answer": 0,
        "explain": "az monitor diagnostic-settings create defines which log categories a resource emits and where they land — including a workspace. Creating a workspace only builds the destination, DCR associations wire the Azure Monitor Agent's guest collection to VMs, and activity-log alerts fire on control-plane events rather than routing logs.",
    },
    {
        "type": "mc",
        "q": "Which KQL query returns the number of events per computer over the last hour?",
        "choices": [
            'Event | where TimeGenerated > ago(1h) | summarize count() by Computer',
            'Event | project Computer | top 1h by TimeGenerated',
            'Event | summarize Computer by count()',
            'Event | render timechart | where TimeGenerated > ago(1h)',
        ],
        "answer": 0,
        "explain": "The canonical shape is table first, filter early with where TimeGenerated > ago(1h), then aggregate with summarize count() by Computer. Option B misuses top (it takes N rows, not a timespan), option C reverses the summarize syntax, and option D pipes operators after render, which must come last.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command runs a KQL query against a Log Analytics workspace from a script?",
        "choices": [
            "az monitor log-analytics query",
            "az monitor metrics list",
            "az monitor scheduled-query create",
            "az monitor log-analytics workspace update",
        ],
        "answer": 0,
        "explain": "az monitor log-analytics query executes an analytics query (e.g., 'Heartbeat | summarize count() by Computer') against a workspace GUID. az monitor metrics list pulls platform metrics, scheduled-query create builds a log search alert rule rather than running a one-off query, and workspace update changes settings like retention.",
    },
    {
        "type": "mc",
        "q": "A CPU alert fired when a VM crossed 80%, and the admin notices it stopped alerting on its own once CPU dropped. Which behavior explains this?",
        "choices": [
            "Metric alerts are stateful and auto-resolve when the condition clears",
            "An alert processing rule deleted the alert",
            "Log search alerts always auto-resolve after one evaluation",
            "The action group expired and closed the alert",
        ],
        "answer": 0,
        "explain": "Metric alerts are stateful: they fire once when the threshold is crossed, do not re-fire every evaluation while the condition persists, and auto-resolve when the metric recovers. Processing rules suppress notifications rather than delete alerts, log search alerts are scheduled and can fire again per matching evaluation, and action groups never close alerts.",
    },
    {
        "type": "mc",
        "q": "An admin needs an alert whenever a KQL query over the last 15 minutes of Perf data finds low disk space, evaluated every 5 minutes. Which alert type is this?",
        "choices": [
            "Metric alert with a dynamic threshold",
            "Activity log alert",
            "Log search alert",
            "Service Health alert",
        ],
        "answer": 2,
        "explain": "A log search alert runs a KQL query on a schedule (evaluation frequency and lookback window) and fires when results meet the threshold — created with az monitor scheduled-query create. Metric alerts evaluate numeric metric streams, and activity log / Service Health alerts fire on control-plane and Azure-platform events, not query results.",
    },
    {
        "type": "mc",
        "q": "Alert notifications must always reach whoever currently holds the Owner role on the subscription, without maintaining an email list as staff change. Which action-group option achieves this?",
        "choices": [
            "A webhook to the HR system",
            "The Email Azure Resource Manager role notification",
            "An SMS receiver per administrator",
            "An ITSM connector",
        ],
        "answer": 1,
        "explain": "The Email Azure Resource Manager role notification mails everyone currently assigned a chosen RBAC role (like Owner) on the subscription — no hardcoded addresses to maintain. SMS receivers and webhooks require explicit, static targets, and the ITSM connector creates tickets in tools like ServiceNow rather than tracking role membership.",
    },
    {
        "type": "mc",
        "q": "During a planned weekend maintenance window, 60 alert rules would page the on-call team. How should the admin silence the noise without editing or disabling any rule?",
        "choices": [
            "Create an alert processing rule that suppresses notifications for the window over the affected scope",
            "Set every alert rule's severity to Sev4 for the weekend",
            "Delete the action groups and recreate them Monday",
            "Set the workspace retention to zero during the window",
        ],
        "answer": 0,
        "explain": "An alert processing rule applies after alerts fire, across a broad scope like a subscription or resource group, and can suppress notifications on a schedule — alerts still fire and are logged, only the pages stop. Editing 60 rules' severity or destroying action groups is exactly the toil processing rules exist to avoid, and retention has nothing to do with notifications.",
    },
    {
        "type": "mc",
        "q": "In Azure Monitor's severity scale, which level indicates Critical?",
        "choices": ["Sev4", "Sev2", "Sev1", "Sev0"],
        "answer": 3,
        "explain": "The scale runs from most to least severe as the number rises: Sev0 = Critical, Sev1 = Error, Sev2 = Warning, Sev3 = Informational, Sev4 = Verbose. It is easy to invert — remember zero is the most severe, not the least.",
    },
    {
        "type": "mc",
        "q": "Before migrating an app server VM, the team must discover every process on it and which TCP connections those processes make. Which feature answers this with minimal effort?",
        "choices": [
            "The Map feature of VM insights",
            "Network insights topology",
            "Metrics Explorer with splitting",
            "Network Watcher packet capture",
        ],
        "answer": 0,
        "explain": "VM insights' Map draws a dependency map of each VM's processes and their inbound/outbound TCP connections — purpose-built for 'what breaks if I move this?' migration discovery. Network insights topology maps Azure network resources, not processes; metrics have no process detail; and packet capture yields raw traffic requiring manual analysis.",
    },
    {
        "type": "mc",
        "q": "Users report slow blob downloads. Storage insights shows end-to-end latency is high while server latency is normal. Where is the problem?",
        "choices": [
            "The storage service itself is overloaded",
            "The network path or the client application",
            "The storage account's redundancy setting",
            "The Log Analytics workspace ingestion delay",
        ],
        "answer": 1,
        "explain": "Server latency measures only the time Azure Storage spent processing; end-to-end covers the full client-to-Azure-and-back round trip. Low server latency with high end-to-end latency means the delay is added in the network or the client app — the storage service is exonerated. Both being high would implicate storage; redundancy and workspace ingestion do not affect these numbers.",
    },
    {
        "type": "mc",
        "q": "Management wants a single topology view showing the health and metrics of all load balancers, gateways, and public IPs with minimal administrative effort. Which feature fits?",
        "choices": [
            "Network insights",
            "VM insights",
            "A custom workbook built from KQL queries",
            "Connection Monitor",
        ],
        "answer": 0,
        "explain": "Network insights is the curated, agentless Insight that provides a topology view plus health and metrics for network resources — 'minimal effort' in a stem is the signal for an Insight over anything hand-built. VM insights covers VM performance and dependencies, a custom workbook is exactly the effort being avoided, and Connection Monitor tests specific endpoint pairs.",
    },
    {
        "type": "mc",
        "q": "Users cannot RDP to a VM, and the admin suspects an NSG. Which Network Watcher tool tests whether TCP 3389 to the VM is allowed and names the exact rule that decides?",
        "choices": ["Next hop", "IP flow verify", "Packet capture", "VPN troubleshoot"],
        "answer": 1,
        "explain": "IP flow verify takes a 5-tuple (source/destination IP and port, protocol, direction) and returns allow or deny plus the specific NSG rule responsible. Next hop diagnoses routing, packet capture records real traffic for offline analysis without naming rules, and VPN troubleshoot examines gateway and connection health.",
    },
    {
        "type": "mc",
        "q": "The network team must continuously track latency and packet loss from Azure VMs to an on-premises application and alert on degradation trends. Which tool fits?",
        "choices": [
            "Connection troubleshoot",
            "Connection Monitor",
            "IP flow verify",
            "Packet capture",
        ],
        "answer": 1,
        "explain": "Connection Monitor runs continuous tests between Azure VMs, on-premises hosts, and external endpoints, measuring reachability, latency, and packet loss, with results in a Log Analytics workspace where alert rules attach. Connection troubleshoot is the point-in-time version of the same question — 'continuously' is the discriminator — while IP flow verify and packet capture answer different questions entirely.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command checks whether a specific inbound packet to a VM would be allowed or denied by its NSGs?",
        "choices": [
            "az network watcher test-ip-flow",
            "az network watcher show-next-hop",
            "az network watcher test-connectivity",
            "az network watcher show-topology",
        ],
        "answer": 0,
        "explain": "az network watcher test-ip-flow submits the 5-tuple (direction, protocol, local and remote IP:port) and returns the allow/deny verdict with the deciding NSG rule. show-next-hop answers routing questions, test-connectivity performs a one-time end-to-end reachability check, and show-topology draws the network resource map.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Creating a diagnostic setting on a Key Vault today lets you query the data-plane events from last week.",
        "answer": False,
        "explain": "Diagnostic settings are not retroactive — collection starts when the setting is created, and events from before that moment were never captured and cannot be recovered. This is why half of the 'the data isn't there' exam stems resolve to a missing diagnostic setting.",
    },
    {
        "type": "tf",
        "q": "True or False: Platform metrics for an Azure resource are collected only after an agent is installed on it.",
        "answer": False,
        "explain": "Platform metrics are collected automatically for every Azure resource with no agent and no configuration — they are the free, near-real-time baseline signal. Agents (AMA plus a DCR) are needed only for guest-OS data such as memory counters, Windows events, and Syslog.",
    },
    {
        "type": "tf",
        "q": "True or False: When an alert processing rule suppresses alerts during maintenance, the alerts still fire and appear in the portal — only the notifications stop.",
        "answer": True,
        "explain": "Suppression acts after the alert rule evaluates: alerts are still created and logged, but the attached action groups do not notify or act. This preserves the audit trail while stopping the noise — and it is why 'disable the alert rules' is the wrong answer to maintenance-window stems.",
    },
    {
        "type": "tf",
        "q": "True or False: A log search alert can react to a matching record in real time, the instant the record is ingested.",
        "answer": False,
        "explain": "Log search alerts run their KQL query on a schedule — for example every 5 minutes over the last 15 — so detection waits for the next evaluation and also trails log ingestion delay. Near-real-time alerting is the domain of metric alerts, which evaluate the metric stream directly.",
    },
    {
        "type": "tf",
        "q": "True or False: Network Watcher is a regional service, so diagnosing a VNet requires Network Watcher enabled in that VNet's region.",
        "answer": True,
        "explain": "Network Watcher operates per region and is enabled automatically in a region when you create or update a virtual network there. A tool run from a region where Network Watcher is not enabled cannot diagnose resources in that region — a subtle trap in multi-region scenarios.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The pipe-based query language used to analyze tables in a Log Analytics workspace is ______. (type the acronym)",
        "answers": ["kql", "kusto query language", "kusto"],
        "explain": "KQL (Kusto Query Language) reads left to right: table first, then piped operators — where to filter, summarize to aggregate, project to shape, top to limit, render to chart. AZ-104 shows queries with blanks, so the operator vocabulary must be automatic.",
    },
    {
        "type": "fill",
        "q": "The only supported agent for collecting guest-OS logs and performance counters from Azure VMs (the legacy MMA/OMS agent retired in August 2024) is the Azure ______ Agent. (type the missing word or the acronym)",
        "answers": ["monitor", "azure monitor agent", "ama"],
        "explain": "The Azure Monitor Agent (AMA) is the sole supported collection agent for VM guest data, and it does nothing until a Data Collection Rule defines what to collect and which workspace receives it. Any answer built on the retired Log Analytics (MMA/OMS) agent is wrong.",
    },
    {
        "type": "fill",
        "q": "To find VMs that have stopped reporting, query the ______ table, which receives one record per minute from every connected agent. (type the table name)",
        "answers": ["heartbeat"],
        "explain": "Heartbeat is the agent-liveness table — a gap in its per-minute records means the agent (or the VM) went silent. Contrast it with Perf (guest counters), InsightsMetrics (VM insights data), Event (Windows logs), and Syslog (Linux logs).",
    },
    {
        "type": "fill",
        "q": "The Network Watcher tool that tests a specific 5-tuple packet against a VM and reports which NSG rule allows or denies it is IP ______ verify. (type the missing word or the full tool name)",
        "answers": ["flow", "ip flow verify", "ipflow"],
        "explain": "IP flow verify is the point-in-time 'is this packet allowed, and which NSG rule decides?' test. Keep its one-line purpose distinct from next hop (routing), connection troubleshoot (one-time reachability), and Connection Monitor (continuous latency and loss).",
    },
    {
        "type": "fill",
        "q": "The reusable Azure Monitor object that holds notification receivers (email, SMS, voice) and automated actions (runbooks, Logic Apps, webhooks) is the ______. (type the object name)",
        "answers": ["action group", "action groups", "azure monitor action group"],
        "explain": "The action group is the who-and-what of alerting: notifications reach people, actions trigger automation, and one group can serve many alert rules. The alert rule detects the condition; the alert processing rule modifies behavior after firing — three objects, three jobs.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each diagnostic-setting destination to the scenario it serves.",
        "pairs": [
            ["Log Analytics workspace", "Query the logs with KQL, correlate, and alert"],
            ["Storage account", "Cheap long-term archive for audit retention"],
            ["Event Hubs", "Stream logs to an external SIEM or third-party tool"],
            ["Partner solutions", "Send logs directly to an integrated ISV such as Datadog"],
        ],
        "explain": "A diagnostic setting can fan chosen log categories out to up to four destination types, and the exam maps each to one verb: workspace = query/alert, storage = archive, Event Hubs = stream out, partner solutions = direct ISV integration. Pick by what the scenario does with the data.",
    },
    {
        "type": "match",
        "q": "Match each KQL operator to what it does in a query pipeline.",
        "pairs": [
            ["where", "Filters rows, e.g., TimeGenerated > ago(1h)"],
            ["summarize", "Aggregates rows (count, avg, max) grouped by columns"],
            ["project", "Selects and renames the output columns"],
            ["top", "Returns the first N rows by a sort expression"],
            ["render", "Charts the query output, e.g., as a timechart"],
        ],
        "explain": "Read every query as a pipeline: filter early with where, aggregate with summarize ... by, shape columns with project, limit with top N by, and visualize last with render. Knowing which operator works on rows versus columns versus presentation resolves most fill-the-blank query stems.",
    },
    {
        "type": "match",
        "q": "Match each Network Watcher capability to the question it answers.",
        "pairs": [
            ["IP flow verify", "Is this packet allowed to the VM, and which NSG rule decides?"],
            ["Next hop", "Where does this VM's traffic route next, and via which route entry?"],
            ["Packet capture", "Record actual traffic on a VM remotely, without RDP/SSH"],
            ["Connection Monitor", "Continuously measure latency and packet loss to an endpoint"],
            ["VPN troubleshoot", "Diagnose the health of a VPN gateway and its connections"],
        ],
        "explain": "Each tool has a one-line purpose, and every exam distractor is a real tool solving a slightly different problem. The sharpest discriminator is time: IP flow verify, next hop, and connection troubleshoot are point-in-time tests, while Connection Monitor runs continuously.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange these KQL pipeline stages in the canonical order for a well-formed query.",
        "items": [
            "Name the source table (e.g., Perf)",
            "Filter rows early with where TimeGenerated > ago(1h)",
            "Aggregate with summarize avg(CounterValue) by Computer",
            "Limit the output with top 10 by avg_CounterValue",
            "Visualize with render timechart",
        ],
        "explain": "KQL flows left to right: table first, then filter early to cut the data down, aggregate, limit, and render last since it only presents whatever rows reach it. Operator order changes results — a top before a where selects different rows than a top after it.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to start collecting Windows event logs from a fleet of Azure VMs into Log Analytics, from first to last.",
        "items": [
            "Create the Log Analytics workspace destination",
            "Install the Azure Monitor Agent on the VMs",
            "Create a Data Collection Rule defining the event logs and counters to collect",
            "Associate the Data Collection Rule with the VMs",
            "Query the Event table with KQL",
        ],
        "explain": "Guest data needs the full chain: a workspace to land in, the AMA on each VM, a DCR that defines what to collect and where to send it, and an association binding the DCR to the machines — one DCR can drive a whole fleet. Only then do tables like Event, Syslog, and Perf begin filling.",
    },
    {
        "type": "order",
        "q": "Arrange the flow of a monitored CPU incident through Azure Monitor's alerting objects, from detection to notification.",
        "items": [
            "The Percentage CPU metric crosses the 80% threshold",
            "The alert rule evaluates the signal condition and fires a Sev2 alert",
            "An alert processing rule checks whether notifications are suppressed for the scope",
            "The action group sends the email and triggers the remediation runbook",
            "CPU recovers and the stateful metric alert auto-resolves",
        ],
        "explain": "The three objects divide the work: the alert rule detects and fires, processing rules intervene after firing (suppress or fan out), and the action group carries the notifications and automated actions. Because metric alerts are stateful, the story ends with auto-resolution when the condition clears — no re-fire storm in between.",
    },
]
