TOPIC = {
    "id": "5.2",
    "domain": 5,
    "title": "Implement backup and recovery by using Azure Backup and Azure Site Recovery.",
    "short": "Backup & Site Recovery",
}

TERMS = [
    ("Recovery Services vault", "Classic vault for Azure Backup and Site Recovery — protects Azure VMs, SQL/SAP HANA in VMs, Azure Files, and on-premises backups via MARS/MABS/DPM"),
    ("Backup vault", "Newer Data Protection vault type for the newer PaaS workloads: Azure Blobs, Azure Disks, Azure Database for PostgreSQL, and AKS — cannot protect VMs"),
    ("Backup storage redundancy", "Vault storage choice of LRS, GRS (default), or ZRS that must be set before the first item is protected — locked once anything is backed up"),
    ("Cross-Region Restore (CRR)", "GRS vault option that lets you restore protected items in the secondary paired region at any time, not only during a regional outage"),
    ("Backup policy", "Vault-attached definition of when backups run (schedule) and how long recovery points are kept (retention)"),
    ("Standard backup policy", "Azure VM policy tier with once-per-day backups and 1-5 day snapshot retention (default 2)"),
    ("Enhanced backup policy", "Azure VM policy tier allowing backups up to every 4 hours — required for Ultra-disk/Premium SSD v2 VMs (Trusted Launch VMs can use standard or enhanced)"),
    ("GFS retention", "Grandfather-father-son model layering daily, weekly, monthly, and yearly retention points in one backup policy"),
    ("Instant restore", "Fast restore served from locally kept snapshots (retained 1-5 days, default 2), skipping the vault transfer entirely"),
    ("Backup extension", "Component installed into the Azure VM agent when protection is enabled — takes VSS app-consistent snapshots on Windows, file-system-consistent on Linux"),
    ("File-level recovery", "Restore option where a downloaded script mounts the recovery point as local drives so individual files/folders can be copied out"),
    ("Replace existing", "VM restore option that swaps the source VM's disks with the recovery point's disks — rolls the same VM back in place"),
    ("Soft delete for backup", "Protection that retains deleted backup data an extra 14 days at no cost before permanent deletion — the defense against ransomware/rogue-admin deletion"),
    ("Stop protection", "Halting backups with a choice to retain backup data (recovery points stay restorable) or delete backup data (soft delete grace begins)"),
    ("MARS agent", "Microsoft Azure Recovery Services agent — backs up on-premises Windows files, folders, and system state only, up to 3 times per day; no Linux, no full VM"),
    ("Azure Site Recovery (ASR)", "Disaster recovery service that continuously replicates Azure VM disks to a secondary region, with crash-consistent points about every 5 minutes"),
    ("Recovery plan", "Site Recovery construct that groups VMs, orders their startup across tiers, and can inject Automation scripts or manual actions between groups"),
    ("Test failover", "Always-first DR drill that brings up VM copies in an isolated test network with zero impact on production or ongoing replication"),
    ("Commit", "Post-failover step that finalizes the failover and deletes the other available recovery points"),
    ("Re-protect", "Post-failover step enabling reverse replication so the now-primary VMs replicate back to the original region, restoring DR protection"),
    ("Backup center", "Cross-vault management hub where backup jobs, alerts, and reports across vaults and subscriptions surface centrally"),
    ("Backup Reports", "Historical/analytical workbook (job success, storage, compliance) fed by vault diagnostic settings streaming to a Log Analytics workspace"),
    ("Built-in Azure Monitor alerts", "Automatic backup alerts — no rules to author — for job failures and destructive operations like deleting backup data or disabling soft delete"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An admin must configure backup for 40 Azure virtual machines and several SQL Server databases running inside those VMs. Which resource should be created to hold the backups?",
        "choices": ["A Backup vault", "A Recovery Services vault", "A geo-redundant storage account", "An Azure Site Recovery fabric"],
        "answer": 1,
        "explain": "Azure VMs, SQL Server and SAP HANA inside VMs, Azure Files, and on-premises backups all go to a Recovery Services vault — the classic container that also handles Site Recovery. The similarly named Backup vault is the trap: it serves only the newer workloads (Blobs, Disks, PostgreSQL, AKS) and cannot protect VMs. A raw storage account holds no backup management, and a fabric is an ASR replication concept.",
    },
    {
        "type": "mc",
        "q": "A company wants to protect its Azure Database for PostgreSQL servers and an AKS cluster with Azure Backup. Which vault type is required?",
        "choices": ["Recovery Services vault", "Key vault", "Backup vault", "Site Recovery vault"],
        "answer": 2,
        "explain": "The newer Data Protection platform's Backup vault covers Azure Blobs, Azure Disks, Azure Database for PostgreSQL, and AKS. A Recovery Services vault cannot protect these workloads — the two vault types have disjoint workload lists. Key Vault stores secrets and certificates, and there is no separate 'Site Recovery vault' resource type.",
    },
    {
        "type": "mc",
        "q": "An admin in the East US region needs a vault to back up VMs that run in East US under subscription Sub-A. Where must the Recovery Services vault be created?",
        "choices": [
            "In East US, in subscription Sub-A",
            "In the paired region (West US), in subscription Sub-A",
            "In any region, as long as it is in Sub-A",
            "In East US, in any subscription the admin can access",
        ],
        "answer": 0,
        "explain": "For backup, the Recovery Services vault must be in the same region AND the same subscription as the VMs it protects — you cannot back up an East US VM to a West Europe vault. Note the contrast with Site Recovery, where the vault must be in a region other than the source VMs. That opposite placement rule is a favorite trick.",
    },
    {
        "type": "mc",
        "q": "An admin opens a Recovery Services vault to change its storage redundancy from GRS to LRS, but the option is greyed out. What is the most likely cause?",
        "choices": [
            "The admin lacks the Backup Contributor role",
            "The vault already contains protected items, so redundancy is locked",
            "LRS is not supported for Recovery Services vaults",
            "A resource lock on the vault must be removed first",
        ],
        "answer": 1,
        "explain": "Backup storage redundancy must be chosen before the first item is protected — once anything in the vault is being backed up, the setting is locked permanently. It is not a permissions or resource-lock problem, and LRS is a fully supported choice alongside GRS (the default) and ZRS. The only fix is a new vault with the desired redundancy and re-protecting the workloads there.",
    },
    {
        "type": "mc",
        "q": "A compliance team requires that VM backups can be restored in the paired secondary region on demand, even when the primary region is healthy. What must the vault have?",
        "choices": [
            "ZRS redundancy with soft delete enabled",
            "LRS redundancy plus an enhanced backup policy",
            "GRS redundancy with Cross-Region Restore enabled",
            "A second vault deployed in the paired region",
        ],
        "answer": 2,
        "explain": "Cross-Region Restore requires geo-redundant (GRS) vault storage plus the CRR flag enabled, and it then works at any time — not only during a Microsoft-declared outage. ZRS and LRS keep no copy in the secondary region, so they can never support it. A second vault would hold no data unless the workloads were separately backed up there.",
    },
    {
        "type": "mc",
        "q": "When a new Recovery Services vault is created and nothing has been changed, which backup storage redundancy is in effect?",
        "choices": ["Locally redundant storage (LRS)", "Zone-redundant storage (ZRS)", "Read-access geo-redundant storage (RA-GRS)", "Geo-redundant storage (GRS)"],
        "answer": 3,
        "explain": "Vault backup storage defaults to GRS; admins downgrade to LRS to save cost or pick ZRS for in-region zone resilience. The choice must be made before the first item is protected because it locks afterwards. RA-GRS is a storage-account redundancy option, not one of the three vault choices.",
    },
    {
        "type": "mc",
        "q": "A database VM must be backed up every 4 hours to meet its RPO. Which Azure Backup configuration achieves this?",
        "choices": [
            "A standard backup policy with GFS retention",
            "An enhanced backup policy",
            "Two standard policies assigned to the same VM",
            "An Azure Site Recovery replication policy",
        ],
        "answer": 1,
        "explain": "A standard policy backs up once per day at most; only an enhanced policy supports multiple backups per day, up to every 4 hours. A VM takes exactly one backup policy, so stacking two standard policies is not possible. Site Recovery replicates for disaster recovery — it is not how you schedule backups.",
    },
    {
        "type": "mc",
        "q": "An admin enables backup for a new virtual machine that uses Ultra disks. Which backup policy type must be used?",
        "choices": ["Standard policy", "Enhanced policy", "Either standard or enhanced", "Ultra-disk VMs cannot be backed up"],
        "answer": 1,
        "explain": "VMs using Ultra disks or Premium SSD v2 require the enhanced backup policy, which also brings up-to-every-4-hours frequency and 1-30 day snapshot retention, at higher cost. Standard policies do not support these disk types, though the VMs are absolutely backable. (Trusted Launch VMs, by contrast, can now be backed up with either a standard or an enhanced policy.)",
    },
    {
        "type": "mc",
        "q": "A retention requirement states: keep daily backups for 30 days, monthly backups for 12 months, and yearly backups for 7 years. How should this be implemented?",
        "choices": [
            "One backup policy using GFS (daily/weekly/monthly/yearly) retention",
            "Three separate backup policies assigned to the VM",
            "An Azure Storage lifecycle management rule on the vault",
            "A soft delete retention extension on the vault",
        ],
        "answer": 0,
        "explain": "A single policy layers daily, weekly, monthly, and yearly retention points — the grandfather-father-son model — so long-term retention never needs multiple policies (a VM can only have one anyway). Lifecycle management moves blobs between tiers, not vault recovery points. Soft delete only governs how long deleted backup data lingers.",
    },
    {
        "type": "mc",
        "q": "With a standard Azure VM backup policy, how long are instant-restore snapshots retained by default?",
        "choices": ["1 day", "2 days", "5 days", "14 days"],
        "answer": 1,
        "explain": "Standard policies keep instant-restore snapshots 1-5 days with a default of 2; enhanced policies allow 1-30. These local snapshots let restores skip the vault transfer and finish in minutes. Fourteen days is the soft-delete grace period — a different dial entirely, and raising snapshot retention changes restore speed and snapshot cost, not how long backups are kept.",
    },
    {
        "type": "mc",
        "q": "A user deleted one spreadsheet from a protected VM three days ago. The admin must recover just that file without disturbing the running VM. Which restore approach fits?",
        "choices": [
            "Restore the VM as a new VM and copy the file over",
            "Replace existing to roll the VM back three days",
            "File-level recovery — run the downloaded script to mount the recovery point as drives",
            "Cross-Region Restore of the VM in the paired region",
        ],
        "answer": 2,
        "explain": "File-level recovery downloads a script that mounts the recovery point as local drives, so you copy out individual files and unmount — no VM restore at all. Creating a new VM works but is wasteful for one file, Replace existing would revert three days of everyone's changes, and Cross-Region Restore solves a regional-outage problem, not a lost-file problem.",
    },
    {
        "type": "mc",
        "q": "After a botched application upgrade, an admin must roll a still-running Azure VM back to yesterday's recovery point in place, keeping the same VM resource. Which restore option does this?",
        "choices": ["Create a new VM", "Restore disks", "File-level recovery", "Replace existing"],
        "answer": 3,
        "explain": "Replace existing swaps the source VM's disks with the disks from the chosen recovery point — the same VM resource rolls back in place (the VM must still exist). Create new VM builds a separate machine, Restore disks lands disks in a staging account for you to attach or template, and file-level recovery only extracts individual files.",
    },
    {
        "type": "mc",
        "q": "An admin wants to restore a VM's backup but attach the recovered data disk to a different machine and customize the configuration before anything runs. Which restore option should be chosen?",
        "choices": ["Restore disks", "Replace existing", "Create a new VM", "Instant restore"],
        "answer": 0,
        "explain": "Restore disks recovers only the disks to a staging storage account/resource group, leaving you free to attach them elsewhere or build a customized VM from a template — the 'customize / attach the disk elsewhere' scenario. Create new VM and Replace existing both produce a running VM directly, and instant restore is a speed tier (restoring from snapshots), not a restore destination option.",
    },
    {
        "type": "mc",
        "q": "An attacker with stolen credentials deleted a VM's backup data 10 days ago. Can the backups be recovered?",
        "choices": [
            "No — deleted backup data is purged immediately",
            "Yes — soft delete retains deleted backup data for 14 extra days at no cost",
            "Only if the vault used GRS redundancy",
            "Only if a resource lock was on the vault",
        ],
        "answer": 1,
        "explain": "Soft delete for backup keeps deleted backup data an additional 14 days at no cost before permanent deletion — precisely the ransomware/rogue-admin defense, and 10 days is inside the window. It works regardless of vault redundancy, and resource locks protect the vault resource, not the recovery points. The window is extendable and soft delete can even be made always-on/irreversible.",
    },
    {
        "type": "mc",
        "q": "A VM is being decommissioned, but its existing recovery points must remain restorable for the rest of their policy-defined lifetime. What should the admin do?",
        "choices": [
            "Stop protection and retain backup data",
            "Stop protection and delete backup data",
            "Delete the Recovery Services vault",
            "Switch the VM to a standard policy",
        ],
        "answer": 0,
        "explain": "Stop protection offers two paths: retain backup data halts future backups while existing recovery points stay restorable per policy, and delete backup data removes them (with soft delete's 14-day grace kicking in). Deleting the vault is impossible while it contains protected items and would defeat the goal anyway. Changing policy keeps backups running, which is not wanted.",
    },
    {
        "type": "mc",
        "q": "An admin plans to use the MARS agent for an on-premises Linux file server. Why will this fail?",
        "choices": [
            "MARS requires a Backup vault, not a Recovery Services vault",
            "MARS backs up Windows files, folders, and system state only — it does not support Linux",
            "MARS only supports full-VM image backup, not file backup",
            "MARS can run only once per day",
        ],
        "answer": 1,
        "explain": "The MARS agent is narrower than people assume: Windows files, folders, and system state only — no Linux support and no full-VM images — running up to 3 times per day into a Recovery Services vault. For full on-premises server/VM backup, the answer is MABS or DPM feeding the vault. The other statements invert MARS facts.",
    },
    {
        "type": "mc",
        "q": "A business requires that if its primary Azure region fails, critical VMs come online in another region within minutes, with minimal data loss. Which service meets this requirement?",
        "choices": ["Azure Backup with a GRS vault", "Azure Site Recovery", "Cross-Region Restore", "Azure Backup with an enhanced policy"],
        "answer": 1,
        "explain": "Low RTO/RPO regional disaster recovery is Site Recovery's job: it continuously replicates VM disks to a secondary region with crash-consistent points about every 5 minutes, ready for failover. Backup — even with GRS or Cross-Region Restore — gives point-in-time restores that take far longer and lose up to a day (or 4 hours) of data. 'Minimize downtime in an outage' = ASR; 'restore last week's data' = Backup.",
    },
    {
        "type": "mc",
        "q": "An admin is setting up Azure Site Recovery for VMs running in East US. Where must the Recovery Services vault used for ASR be located?",
        "choices": [
            "In East US, alongside the VMs",
            "In any region other than East US (commonly the target region)",
            "In the same resource group as the VMs",
            "In a Backup vault in the target region",
        ],
        "answer": 1,
        "explain": "For Site Recovery, the vault must sit in a region different from the source VMs — commonly the target region — because a vault in the failed region would be unavailable exactly when needed. This is the opposite of the backup rule, where the vault must share the VMs' region. ASR is managed from a Recovery Services vault, never a Backup vault.",
    },
    {
        "type": "mc",
        "q": "During a regional failover, a three-tier application's domain controllers must start first, then the database VMs, then the web VMs, with a script run between tiers. Which Site Recovery feature provides this?",
        "choices": ["An enhanced backup policy", "A replication policy", "A recovery plan", "An availability set"],
        "answer": 2,
        "explain": "Recovery plans group VMs, order their startup across tiers, and can inject Azure Automation scripts or manual actions between groups — exactly the multi-tier orchestration described. A replication policy only sets recovery point retention and app-consistent snapshot frequency, backup policies schedule backups, and availability sets are a placement construct, not DR orchestration.",
    },
    {
        "type": "mc",
        "q": "Management wants quarterly proof that the DR plan works, with zero impact on production workloads or ongoing replication. What should the admin run?",
        "choices": [
            "A planned failover during a maintenance window",
            "A test failover into an isolated virtual network, then cleanup",
            "An unplanned failover with the latest recovery point",
            "A Cross-Region Restore of each VM",
        ],
        "answer": 1,
        "explain": "Test failover spins up VM copies in an isolated test network in the target region with no effect on production or replication; you validate the app, then run cleanup to delete the test VMs. Real failovers (planned or unplanned) actually move the workload and disrupt production. Cross-Region Restore is a backup feature, and restoring every VM proves nothing about ASR orchestration.",
    },
    {
        "type": "mc",
        "q": "After failing over to the secondary region and verifying the VMs work, what does the Commit step do?",
        "choices": [
            "Starts reverse replication back to the original region",
            "Deletes the other available recovery points, finalizing the failover",
            "Connects the failed-over VMs to the production virtual network",
            "Creates an app-consistent recovery point in the new region",
        ],
        "answer": 1,
        "explain": "Commit finalizes the failover by deleting the other available recovery points — until you commit, the failover job is not complete. Reverse replication is the separate re-protect step, which restores DR protection in the new direction. Networking was already decided when failover targets were configured.",
    },
    {
        "type": "mc",
        "q": "Which Azure CLI command sets a Recovery Services vault's storage redundancy to geo-redundant before any items are protected?",
        "choices": [
            "az backup vault backup-properties set --backup-storage-redundancy GeoRedundant",
            "az backup vault update --sku GRS",
            "az storage account update --sku Standard_GRS",
            "az dataprotection backup-vault update --type GeoRedundant",
        ],
        "answer": 0,
        "explain": "Vault redundancy is a backup property: az backup vault backup-properties set --backup-storage-redundancy GeoRedundant (optionally with --cross-region-restore-flag True) — and it must run before the first backup, after which the setting locks. There is no --sku on az backup vault update, storage-account commands do not touch vaults, and az dataprotection manages the other vault type.",
    },
    {
        "type": "mc",
        "q": "Which PowerShell cmdlet enables an admin to create a new backup policy for Azure VMs in a Recovery Services vault?",
        "choices": [
            "New-AzRecoveryServicesBackupProtectionPolicy",
            "New-AzRecoveryServicesAsrRecoveryPlan",
            "Set-AzRecoveryServicesBackupProperty",
            "New-AzDataProtectionBackupPolicy",
        ],
        "answer": 0,
        "explain": "New-AzRecoveryServicesBackupProtectionPolicy creates the policy, typically fed schedule and retention objects from Get-AzRecoveryServicesBackupSchedulePolicyObject and Get-AzRecoveryServicesBackupRetentionPolicyObject. The Asr cmdlet builds Site Recovery recovery plans, Set-AzRecoveryServicesBackupProperty sets vault properties like redundancy, and the DataProtection cmdlet targets the newer Backup vault platform.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: An Azure Backup vault (the Data Protection vault type) can be used to back up Azure virtual machines.",
        "answer": False,
        "explain": "Despite the generic-sounding name, a Backup vault protects only the newer workloads: Azure Blobs, Azure Disks, Azure Database for PostgreSQL, and AKS. Azure VMs — plus SQL/SAP HANA in VMs, Azure Files, and on-premises backups — require a Recovery Services vault. When a stem says 'back up an Azure VM,' the Backup vault choice is the trap.",
    },
    {
        "type": "tf",
        "q": "True or False: During a Site Recovery test failover, the test VMs should be connected to the production virtual network so the test is realistic.",
        "answer": False,
        "explain": "A test failover uses an isolated test network precisely so production is untouched — connecting test copies to the production VNet causes IP address and name collisions with the live VMs. The drill has zero impact on production or ongoing replication, and you run cleanup afterwards to delete the test VMs.",
    },
    {
        "type": "tf",
        "q": "True or False: Cross-Region Restore can only be used while Microsoft has declared an outage in the primary region.",
        "answer": False,
        "explain": "Once CRR is enabled on a GRS vault, protected items can be restored in the secondary paired region at any time, entirely on demand — for drills, compliance tests, or convenience, not just disasters. The outage-only limitation is the myth the exam checks. The real prerequisites are GRS redundancy plus the CRR flag.",
    },
    {
        "type": "tf",
        "q": "True or False: When backup data is deleted, soft delete retains it for an additional 14 days at no cost.",
        "answer": True,
        "explain": "Soft delete's 14-day grace period is free, extendable, and can be made always-on/irreversible — it is the safety net against accidental, ransomware, or rogue-admin deletion of backups. The grace applies when data is deleted, including via 'stop protection and delete backup data.'",
    },
    {
        "type": "tf",
        "q": "True or False: For Azure VMs, Azure Site Recovery generates crash-consistent recovery points approximately every 5 minutes.",
        "answer": True,
        "explain": "ASR replicates continuously and produces crash-consistent points about every 5 minutes, with app-consistent points at a configurable (less frequent) interval. This is why ASR's RPO is far lower than any backup schedule — even an enhanced policy backs up at most every 4 hours.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The PowerShell cmdlet that creates a new Recovery Services vault is ______. (type the cmdlet name)",
        "answers": ["new-azrecoveryservicesvault", "new-azrecoveryservicesvault -name", "azrecoveryservicesvault"],
        "explain": "New-AzRecoveryServicesVault -Name ... -ResourceGroupName ... -Location ... creates the vault; Set-AzRecoveryServicesBackupProperty then sets its storage redundancy before anything is protected. The Az.RecoveryServices module covers this vault type, while Az.DataProtection covers Backup vaults.",
    },
    {
        "type": "fill",
        "q": "Backup vaults and their workloads (Blobs, Disks, PostgreSQL, AKS) are managed with the Azure CLI command group az ______. (type the command group)",
        "answers": ["dataprotection", "az dataprotection", "data protection"],
        "explain": "The two vault types use different tooling namespaces: az backup / Az.RecoveryServices for Recovery Services vaults, and az dataprotection / Az.DataProtection for the newer Backup vaults. Recognizing the namespace tells you which platform a question is about.",
    },
    {
        "type": "fill",
        "q": "On Windows VMs, the backup extension achieves application-consistent snapshots using the ______ service. (type the acronym)",
        "answers": ["vss", "volume shadow copy service", "volume shadow copy"],
        "explain": "VSS (Volume Shadow Copy Service) quiesces applications on Windows so snapshots are application-consistent. Linux VMs get file-system-consistent snapshots by default and reach application consistency only with custom pre/post scripts; a stopped VM yields crash-consistent backups at worst.",
    },
    {
        "type": "fill",
        "q": "The on-premises agent that backs up Windows files, folders, and system state directly to a Recovery Services vault, up to 3 times per day, is the ______ agent. (type the acronym)",
        "answers": ["mars", "microsoft azure recovery services", "azure recovery services"],
        "explain": "The MARS (Microsoft Azure Recovery Services) agent handles only Windows files, folders, and system state — no Linux, no full-VM images — running up to 3 backups per day. Full on-premises server or VM protection requires MABS or System Center DPM feeding the vault instead.",
    },
    {
        "type": "fill",
        "q": "The cross-vault hub in the Azure portal where backup jobs, alerts, and reports from many vaults surface centrally is called Backup ______. (type the word)",
        "answers": ["center", "backup center", "centre"],
        "explain": "Backup center is the single management pane across vaults and subscriptions — built-in Azure Monitor alerts and the Backup Reports workbook both surface there. Reports additionally require vault diagnostic settings streaming to a Log Analytics workspace before data appears (allow up to ~24 hours).",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each Azure VM restore option to the scenario it solves.",
        "pairs": [
            ["Create a new VM", "Quickly bring the workload back as a freshly built machine"],
            ["Restore disks", "Recover disks to a staging account to attach or customize elsewhere"],
            ["Replace existing", "Swap the running VM's disks to roll it back in place"],
            ["Cross-Region Restore", "Restore in the secondary paired region (requires GRS + CRR)"],
            ["File-level recovery", "Script mounts the recovery point as drives to copy out single files"],
        ],
        "explain": "Pick the restore option by what the stem asks for: whole workload fast = new VM; disks only for customization = restore disks; same VM rolled back = replace existing; another region = Cross-Region Restore; one file or folder = file-level recovery. Wrong-option traps usually pair a single-file need with a full VM restore.",
    },
    {
        "type": "match",
        "q": "Match each Site Recovery failover term to its meaning.",
        "pairs": [
            ["Test failover", "DR drill in an isolated network with zero production impact"],
            ["Commit", "Finalize the failover and delete the other recovery points"],
            ["Re-protect", "Enable reverse replication from the new primary back to the original region"],
            ["Fail back", "Planned failover in reverse to return to the original region"],
            ["Recovery plan", "Groups VMs, orders startup, and injects scripts between tiers"],
        ],
        "explain": "The drill vocabulary maps cleanly: test failover validates, commit finalizes, re-protect reverses replication, fail back goes home, and recovery plans orchestrate multi-tier startup. Remember that until re-protect runs, there is no DR protection in the new direction.",
    },
    {
        "type": "match",
        "q": "Match each backup component or vault to what it protects or does.",
        "pairs": [
            ["Recovery Services vault", "Azure VMs, SQL/SAP HANA in VMs, Azure Files, on-premises backups"],
            ["Backup vault", "Azure Blobs, Azure Disks, PostgreSQL, and AKS"],
            ["MARS agent", "On-premises Windows files, folders, and system state only"],
            ["MABS / DPM", "Full on-premises server and VM backup feeding a Recovery Services vault"],
            ["Backup extension", "In-VM component taking VSS-consistent snapshots of Azure VMs"],
        ],
        "explain": "Sort by workload noun: classic workloads and anything on-premises or Site Recovery land in the Recovery Services vault; the newer PaaS quartet lands in the Backup vault. MARS covers only Windows files/folders/system state, so full on-prem machines need MABS or DPM, while Azure VMs are snapshotted by the backup extension installed into the VM agent.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the Azure Site Recovery disaster sequence in the correct order, from DR drill through returning home.",
        "items": [
            "Test failover into an isolated network, then cleanup",
            "Failover — pick a recovery point and bring VMs up in the target region",
            "Commit the failover, deleting the other recovery points",
            "Re-protect — enable reverse replication to the original region",
            "Fail back to the original region",
        ],
        "explain": "The exam expects the exact sequence: test failover always comes first (validation with zero impact), then the real failover to a chosen recovery point, commit to finalize, re-protect to restore replication in the reverse direction, and finally fail back home. Skipping commit leaves the job incomplete; skipping re-protect leaves you with no DR protection.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to protect an Azure VM with Azure Backup, from first to last.",
        "items": [
            "Create a Recovery Services vault in the VM's region and subscription",
            "Set the vault's backup storage redundancy (before anything is protected)",
            "Create or choose a backup policy defining schedule and retention",
            "Enable protection on the VM, which installs the backup extension",
            "Run an on-demand backup to create the first recovery point immediately",
        ],
        "explain": "Order matters because redundancy locks once the first item is protected — it must be set right after vault creation. The policy defines schedule and retention before assignment, enabling protection installs the backup extension into the VM agent, and an on-demand backup (az backup protection backup-now) gives an immediate recovery point instead of waiting for the schedule.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to configure Azure Site Recovery for Azure VMs, from first to last.",
        "items": [
            "Create a Recovery Services vault in a region other than the source VMs",
            "Enable replication, choosing target region, resource group, and virtual network",
            "ASR installs the Mobility extension and completes initial replication via a cache storage account",
            "Configure the replication policy's retention and app-consistent snapshot frequency",
            "Build a recovery plan to group VMs, order startup, and add scripts",
            "Run a test failover to validate the configuration",
        ],
        "explain": "ASR's vault placement is the opposite of backup's — it must be outside the source region, commonly in the target region. Enabling replication deploys the Site Recovery (Mobility) extension and stages data through a cache storage account in the source region before continuous delta replication. The replication policy tunes recovery points, the recovery plan orchestrates multi-tier failover, and a test failover proves it all works before you ever need it.",
    },
]
