"""Confusable-term pairs for the AZ-104 Vocab Arcade.

Each pair: two terms candidates mix up, one-line definitions, the key
difference (shown as the teaching line), exam-style discrimination
scenarios (answer must exactly equal a or b), and true/false statements
including definition-swap traps. Validate with: python3 validate.py vocab_data.py
"""

PAIRS = [
    # -------------------------------------------- identity & governance ---
    {
        "a": "System-assigned managed identity", "b": "User-assigned managed identity",
        "def_a": "An identity created on and bound to a single Azure resource, sharing that resource's lifecycle",
        "def_b": "A standalone managed identity resource that can be attached to many Azure resources and outlives any of them",
        "difference": "A system-assigned identity is enabled directly on one resource, cannot be shared, and is deleted automatically when the resource is deleted. A user-assigned identity is its own Azure resource with an independent lifecycle, so many VMs or apps can share it and it survives when they are removed.",
        "scenarios": [
            {"stmt": "An admin enables an identity on a single VM so it can read Key Vault secrets, and wants the identity gone automatically when the VM is deleted.", "answer": "System-assigned managed identity"},
            {"stmt": "Twelve web apps in a scale-out farm must all authenticate to the same storage account with one identity that keeps its role assignments as apps are recreated.", "answer": "User-assigned managed identity"},
            {"stmt": "A CI pipeline tears down and rebuilds VMs nightly, and the team is tired of re-granting Key Vault access each morning, so they attach a pre-created identity that persists across rebuilds.", "answer": "User-assigned managed identity"},
            {"stmt": "The security team requires that when a Logic App is decommissioned its identity must cease to exist with no orphaned principal left behind.", "answer": "System-assigned managed identity"},
        ],
        "tf": [
            {"stmt": "A system-assigned managed identity can be shared across multiple VMs.", "truth": False,
             "why": "System-assigned identities are bound to exactly one resource. Sharing an identity across resources is what user-assigned identities are for."},
            {"stmt": "A user-assigned managed identity continues to exist even after every resource it was attached to has been deleted.", "truth": True,
             "why": "It is a standalone Azure resource with its own lifecycle; you must delete it explicitly."},
            {"stmt": "A user-assigned managed identity is automatically deleted when the resource it is attached to is deleted.", "truth": False,
             "why": "That is the system-assigned lifecycle. User-assigned identities live independently of the resources that use them."},
        ],
    },
    {
        "a": "Security group", "b": "Microsoft 365 group",
        "def_a": "A Microsoft Entra group used to manage access to resources, roles, apps, and licenses",
        "def_b": "A Microsoft Entra group built for collaboration that provisions a shared mailbox, calendar, SharePoint site, and can back a Team",
        "difference": "Security groups exist to grant access: they can contain users, devices, service principals, and other groups, and are what you use for Azure RBAC and license assignment. Microsoft 365 groups exist for collaboration, come with shared resources like a mailbox and SharePoint site, and can only have users as members.",
        "scenarios": [
            {"stmt": "An admin needs a group containing users and their registered devices to target a Conditional Access-style access decision on a file share.", "answer": "Security group"},
            {"stmt": "The marketing department asks for a group that automatically gives everyone a shared calendar, a group mailbox, and a SharePoint document library.", "answer": "Microsoft 365 group"},
            {"stmt": "You must assign the Contributor role on a resource group to forty engineers at once, so you create one group and add it to the role assignment.", "answer": "Security group"},
            {"stmt": "A project team wants a single membership that lights up a Team in Microsoft Teams plus a Planner board for the same people.", "answer": "Microsoft 365 group"},
        ],
        "tf": [
            {"stmt": "A Microsoft 365 group can contain devices and service principals as members.", "truth": False,
             "why": "Microsoft 365 groups accept only users as members. Devices, service principals, and nested groups are supported in security groups."},
            {"stmt": "A security group can be used to assign Azure RBAC roles to many users in a single role assignment.", "truth": True,
             "why": "Assigning a role to a group grants it to all members, which is the recommended way to manage access at scale."},
        ],
    },
    {
        "a": "Assigned membership", "b": "Dynamic membership",
        "def_a": "Group membership where administrators manually add and remove each member",
        "def_b": "Group membership computed automatically by rules that evaluate user or device attributes",
        "difference": "Assigned membership is a static list an admin curates by hand. Dynamic membership uses an attribute rule (like department -eq \"Sales\") to add and remove members automatically as attributes change, requires a Microsoft Entra ID P1 license, and blocks manual member changes while the rule is in charge.",
        "scenarios": [
            {"stmt": "HR updates a new hire's department to Finance and, minutes later, the user appears in the Finance apps group without anyone touching the group.", "answer": "Dynamic membership"},
            {"stmt": "A pilot group must contain exactly the seven testers the project manager named in an email, no more and no less.", "answer": "Assigned membership"},
            {"stmt": "You need every device whose deviceOSType attribute equals Windows to land in a group automatically for update targeting.", "answer": "Dynamic membership"},
            {"stmt": "An admin clicks Add members and picks individual users from the directory picker to populate the group.", "answer": "Assigned membership"},
        ],
        "tf": [
            {"stmt": "In a dynamic membership group, an administrator can still manually add an extra user who does not match the rule.", "truth": False,
             "why": "Membership of a dynamic group is controlled entirely by the rule; manual additions and removals are not allowed."},
            {"stmt": "Dynamic membership rules require Microsoft Entra ID P1 licensing.", "truth": True,
             "why": "Dynamic groups are a premium feature; a P1 (or higher) license is required for the users in scope."},
            {"stmt": "Assigned membership means the group is populated automatically based on user attributes.", "truth": False,
             "why": "That is dynamic membership. Assigned membership is the manual, admin-curated list."},
        ],
    },
    {
        "a": "Member user", "b": "Guest user",
        "def_a": "A user account native to (or fully belonging to) your Microsoft Entra tenant with default member-level directory permissions",
        "def_b": "An external identity invited through B2B collaboration who signs in with their home credentials and has restricted default permissions",
        "difference": "Member users belong to your organization and get the tenant's default member permissions. Guest users are B2B invitees whose UserType is Guest: they authenticate with their own organization's or personal credentials and by default see far less of your directory. The distinction is the UserType attribute, not where they log in from.",
        "scenarios": [
            {"stmt": "A consultant from a partner company is invited by email to collaborate on a resource group and signs in with her own company credentials.", "answer": "Guest user"},
            {"stmt": "A newly onboarded employee gets an account created directly in your tenant with your domain's UPN suffix.", "answer": "Member user"},
            {"stmt": "During an access review you filter the directory for UserType eq Guest to find all external collaborators.", "answer": "Guest user"},
            {"stmt": "By default this account type can read most directory information, such as enumerating other users and groups.", "answer": "Member user"},
        ],
        "tf": [
            {"stmt": "A guest user must have a password created in your tenant before they can sign in.", "truth": False,
             "why": "B2B guests authenticate with their home tenant or personal identity provider; your tenant stores an invitation-linked object, not their credentials."},
            {"stmt": "An administrator can change a user's UserType between Member and Guest after the account exists.", "truth": True,
             "why": "UserType is an editable attribute; for example, you can promote a long-term contractor's guest account to Member."},
        ],
    },
    {
        "a": "Azure Policy", "b": "Azure RBAC",
        "def_a": "A governance service that audits or enforces rules about resource properties, such as allowed regions, SKUs, or required tags",
        "def_b": "An authorization system that controls who can perform which actions on which Azure resources",
        "difference": "RBAC answers \"who can do what\": it grants users, groups, and identities permissions through role assignments and blocks everything not granted. Azure Policy answers \"what is allowed to exist and how must it be configured\": it evaluates resource properties and can deny, audit, or remediate non-compliant resources regardless of who deploys them.",
        "scenarios": [
            {"stmt": "Even the subscription Owner gets an error when creating a VM outside West Europe, because a rule blocks all other regions for everyone.", "answer": "Azure Policy"},
            {"stmt": "A help-desk technician needs to restart VMs in one resource group but must not be able to delete or resize them.", "answer": "Azure RBAC"},
            {"stmt": "A compliance report shows 14 storage accounts flagged as non-compliant because they allow public blob access.", "answer": "Azure Policy"},
            {"stmt": "You add a developer group to the Reader role at the subscription scope so they can view but not change anything.", "answer": "Azure RBAC"},
        ],
        "tf": [
            {"stmt": "Azure RBAC can enforce that all new resources include a CostCenter tag.", "truth": False,
             "why": "Enforcing resource properties like required tags is Azure Policy's job. RBAC only grants or withholds permissions to perform actions."},
            {"stmt": "An Azure Policy deny effect applies even to users who hold the Owner role.", "truth": True,
             "why": "Policy evaluates the request itself, so a non-compliant deployment is rejected no matter how privileged the deployer is."},
            {"stmt": "Azure Policy is the system you use to grant a user permission to read a storage account.", "truth": False,
             "why": "Granting permissions to identities is Azure RBAC. Policy governs resource configuration and compliance, not user access."},
        ],
    },
    {
        "a": "Resource lock", "b": "Azure Policy",
        "def_a": "A CanNotDelete or ReadOnly setting on a subscription, resource group, or resource that blocks deletion or changes for all users",
        "def_b": "A governance service that evaluates resource configurations at scale and can audit, deny, or remediate non-compliant deployments",
        "difference": "A lock is a blunt safety catch on specific existing resources: ReadOnly blocks changes and CanNotDelete blocks deletion, for everyone, until the lock is removed. Azure Policy is rule-based governance across scopes that shapes what may be created and how it is configured. Use locks to prevent accidents on critical resources; use Policy to enforce standards everywhere.",
        "scenarios": [
            {"stmt": "After a junior admin accidentally deleted the production VNet, you add a setting so no one can delete it again without first removing that setting.", "answer": "Resource lock"},
            {"stmt": "Management wants every future storage account in the tenant to be created with HTTPS-only traffic enforced, or the deployment should fail.", "answer": "Azure Policy"},
            {"stmt": "An ExpressRoute circuit must be protected so that even Owners cannot modify it until an explicit protective setting is removed from the resource.", "answer": "Resource lock"},
            {"stmt": "You need a compliance dashboard showing which existing resources are missing the required Environment tag across 40 subscriptions.", "answer": "Azure Policy"},
        ],
        "tf": [
            {"stmt": "A ReadOnly lock on a resource group prevents users with the Owner role from modifying resources inside it until the lock is removed.", "truth": True,
             "why": "Locks apply to all users and roles; Owners must delete the lock first, which is the intended speed bump."},
            {"stmt": "A resource lock can require that all new VMs deploy only approved SKU sizes.", "truth": False,
             "why": "Constraining properties of new deployments is Azure Policy. Locks only prevent delete or modify operations on existing scopes."},
        ],
    },
    # --------------------------------------------------------- storage ---
    {
        "a": "Access keys", "b": "Shared access signature",
        "def_a": "Two root keys on a storage account that grant full, unrestricted access to everything in the account",
        "def_b": "A signed URI that delegates limited access, scoped by permissions, services, resources, IP, and a validity window",
        "difference": "Access keys are the account's root credentials: whoever has one can do anything to any data in the account, and there are only two to rotate. A shared access signature is a delegation token derived from a key (or Entra credentials) that grants only the specific permissions, resources, and time window you choose. Hand out SAS tokens, never keys.",
        "scenarios": [
            {"stmt": "A partner needs to upload files to one specific container for the next 48 hours and must not be able to touch anything else in the account.", "answer": "Shared access signature"},
            {"stmt": "A legacy backup application demands a credential that grants complete control of the entire storage account, including all tables and queues.", "answer": "Access keys"},
            {"stmt": "Security policy requires rotating the storage account's two root credentials every 90 days using the key1/key2 swap pattern.", "answer": "Access keys"},
            {"stmt": "You generate a URL with read-only permission on a single blob that expires in one hour and email it to an auditor.", "answer": "Shared access signature"},
        ],
        "tf": [
            {"stmt": "A shared access signature grants full administrative control over the whole storage account.", "truth": False,
             "why": "That describes the access keys. A SAS is deliberately scoped to specific services, resources, permissions, and a time window."},
            {"stmt": "Regenerating the storage account key that signed a SAS token immediately invalidates that SAS.", "truth": True,
             "why": "A key-signed SAS is only valid while its signing key is valid, so rotating the key is the emergency revocation lever."},
        ],
    },
    {
        "a": "Account SAS", "b": "User delegation SAS",
        "def_a": "A SAS signed with a storage account key that can span blob, file, queue, and table services in one token",
        "def_b": "A SAS secured with Microsoft Entra credentials via a user delegation key, valid only for Blob storage and capped at 7 days",
        "difference": "An account SAS is signed with one of the account keys and can grant access across multiple storage services at once. A user delegation SAS is signed with a user delegation key obtained through Microsoft Entra ID, works only for Blob storage, is limited to a maximum 7-day lifetime, and is Microsoft's recommended option because no account key is ever exposed.",
        "scenarios": [
            {"stmt": "A vendor tool needs a single token that can read blobs, list file shares, and peek queue messages in the same storage account.", "answer": "Account SAS"},
            {"stmt": "Security mandates that blob access tokens be issued without ever touching the storage account keys, using Entra ID sign-in as the root of trust.", "answer": "User delegation SAS"},
            {"stmt": "An engineer tries to create an Entra-secured SAS valid for 30 days and is surprised the platform caps its lifetime at one week.", "answer": "User delegation SAS"},
            {"stmt": "You need a SAS that includes access to Table storage entities, which rules out the Entra-signed option entirely.", "answer": "Account SAS"},
        ],
        "tf": [
            {"stmt": "A user delegation SAS can grant access to Azure Files shares.", "truth": False,
             "why": "User delegation SAS is supported for Blob storage only. Files, queues, and tables need a key-signed account or service SAS."},
            {"stmt": "Microsoft recommends user delegation SAS over key-signed SAS when possible because it avoids exposing the storage account keys.", "truth": True,
             "why": "It is rooted in Entra ID credentials and a short-lived delegation key, so compromise does not burn a root account key."},
        ],
    },
    {
        "a": "SAS token", "b": "Stored access policy",
        "def_a": "A signed query string carrying its own permissions, start time, and expiry that authorizes a request to storage",
        "def_b": "A named server-side policy on a container that centrally defines permissions and expiry for the service SAS tokens referencing it",
        "difference": "An ad-hoc SAS token bakes its permissions and expiry into the token itself, so once issued it cannot be changed without rotating the signing key. A stored access policy lives on the container: service SAS tokens reference it by name, and modifying or deleting the policy instantly changes or revokes every token tied to it. Up to five policies are allowed per container.",
        "scenarios": [
            {"stmt": "A leaked download link must be killed right now without rotating the account keys, so you delete the named policy it references and the link dies instantly.", "answer": "Stored access policy"},
            {"stmt": "You issue a one-off URL whose expiry date and read permission are encoded directly in its query string parameters.", "answer": "SAS token"},
            {"stmt": "Hundreds of client links on a container must all have their expiry extended by a month with a single server-side edit.", "answer": "Stored access policy"},
            {"stmt": "A support engineer pastes ?sv=...&sig=... onto a blob URL so a customer can fetch a diagnostic file.", "answer": "SAS token"},
        ],
        "tf": [
            {"stmt": "Deleting a stored access policy immediately revokes all service SAS tokens that were created referencing it.", "truth": True,
             "why": "Tokens tied to a policy inherit its terms at validation time, so removing the policy invalidates them all at once."},
            {"stmt": "You can change the expiry time of an already-issued ad-hoc SAS token by editing it on the server.", "truth": False,
             "why": "Ad-hoc SAS terms are fixed inside the signed token; only tokens referencing a stored access policy can be centrally modified."},
        ],
    },
    {
        "a": "LRS", "b": "ZRS",
        "def_a": "Locally redundant storage: three synchronous copies of your data within a single datacenter in one region",
        "def_b": "Zone-redundant storage: three synchronous copies spread across three availability zones in one region",
        "difference": "LRS keeps all three replicas in one datacenter, so a datacenter-level disaster can take out every copy; it is the cheapest option with eleven nines of durability. ZRS spreads the three copies across separate availability zones in the region, surviving a full zone outage with twelve nines of durability. Neither protects against loss of the whole region.",
        "scenarios": [
            {"stmt": "A dev/test storage account holds easily recreated data and must simply be the cheapest redundancy available.", "answer": "LRS"},
            {"stmt": "A production account must keep serving reads and writes even if one entire datacenter building in the region loses power.", "answer": "ZRS"},
            {"stmt": "An architect points out that with this redundancy choice, a fire in the single facility hosting the replicas could destroy all three copies.", "answer": "LRS"},
            {"stmt": "Compliance requires data to stay within one region while still being resilient to an availability zone failure.", "answer": "ZRS"},
        ],
        "tf": [
            {"stmt": "ZRS protects your data if the entire Azure region becomes unavailable.", "truth": False,
             "why": "All ZRS copies live in one region, just in different zones. Region-level protection requires geo-redundant options like GRS or GZRS."},
            {"stmt": "LRS keeps all three copies of your data within a single datacenter.", "truth": True,
             "why": "That is exactly its scope, which is why it cannot survive a datacenter-wide disaster but costs the least."},
            {"stmt": "LRS replicates data across three availability zones within a region.", "truth": False,
             "why": "That is ZRS. LRS confines its three replicas to one datacenter."},
        ],
    },
    {
        "a": "Cool tier", "b": "Archive tier",
        "def_a": "An online blob tier for infrequently accessed data, readable in milliseconds, with a 30-day minimum retention",
        "def_b": "An offline blob tier with the lowest storage cost, a 180-day minimum retention, and hours of rehydration before data can be read",
        "difference": "Cool is still online: you can read the blob immediately, you just pay less for storage and more per access, with a 30-day early-deletion window. Archive takes the blob offline: storage is cheapest, but you must rehydrate to an online tier (typically up to 15 hours at standard priority) before reading, and early deletion within 180 days incurs a charge.",
        "scenarios": [
            {"stmt": "Monthly financial reports are rarely opened but must display instantly in the browser when an auditor does click one.", "answer": "Cool tier"},
            {"stmt": "Seven-year compliance archives will almost certainly never be read, and a retrieval delay of many hours is acceptable if one ever is.", "answer": "Archive tier"},
            {"stmt": "An admin requests a blob and gets an error because it must first be rehydrated to an online tier, which could take up to 15 hours.", "answer": "Archive tier"},
            {"stmt": "Data will sit untouched for about 45 days and then be read directly a handful of times before deletion, so an online tier is required.", "answer": "Cool tier"},
        ],
        "tf": [
            {"stmt": "A blob in the archive tier can be read directly the moment a request arrives.", "truth": False,
             "why": "Archive is offline; the blob must be rehydrated to hot, cool, or cold first, which can take hours."},
            {"stmt": "Deleting a blob from the archive tier after only 60 days incurs an early deletion charge.", "truth": True,
             "why": "Archive has a 180-day minimum retention, so removal or tier change before day 180 is billed pro-rata."},
        ],
    },
    {
        "a": "Blob soft delete", "b": "Blob versioning",
        "def_a": "A recycle-bin feature that retains deleted blobs for a configured 1-365 day window so they can be undeleted",
        "def_b": "A feature that automatically preserves the prior state of a blob as a previous version every time it is overwritten or deleted",
        "difference": "Soft delete is protection against deletion: for the retention window you set, a deleted blob can be recovered with an undelete operation. Versioning is protection against modification: every write to a blob captures the old state as a read-only previous version you can promote back. They complement each other and are often enabled together.",
        "scenarios": [
            {"stmt": "A script accidentally deletes a container's blobs, and the admin restores them within the 14-day window using the undelete operation.", "answer": "Blob soft delete"},
            {"stmt": "An application overwrote a config blob with bad content, and you promote yesterday's automatically captured copy back to be the current blob.", "answer": "Blob versioning"},
            {"stmt": "You need every save of a frequently edited document to be retrievable later without the app doing anything special on upload.", "answer": "Blob versioning"},
            {"stmt": "The requirement is simply that anything deleted in the last 30 days can be brought back, like a recycle bin.", "answer": "Blob soft delete"},
        ],
        "tf": [
            {"stmt": "Blob soft delete automatically keeps a copy of a blob's previous contents every time the blob is overwritten with new data.", "truth": False,
             "why": "Capturing prior states on overwrite is blob versioning. Soft delete retains deleted data for a recovery window."},
            {"stmt": "Blob soft delete retention can be configured between 1 and 365 days.", "truth": True,
             "why": "You choose the retention period in that range; deleted blobs are recoverable until it elapses."},
        ],
    },
    # --------------------------------------------------------- compute ---
    {
        "a": "Availability set", "b": "Availability zone",
        "def_a": "A logical grouping that spreads VMs across fault and update domains within a single datacenter",
        "def_b": "A physically separate datacenter location within a region, with independent power, cooling, and networking",
        "difference": "An availability set protects against rack-level hardware failures and host maintenance inside one datacenter, giving a 99.95% VM SLA. Availability zones are physically distinct datacenters in the region, so zone-spread VMs survive an entire datacenter outage and earn a 99.99% SLA. A VM is deployed into one model or the other, not both.",
        "scenarios": [
            {"stmt": "Two VMs must keep the app alive through a rack power-supply failure and host patching, and the region you must use offers no zone support.", "answer": "Availability set"},
            {"stmt": "The design requires the database replicas to survive the loss of an entire datacenter building, including its power and cooling.", "answer": "Availability zone"},
            {"stmt": "An architect needs the 99.99% uptime SLA for a two-VM tier, which means placing the VMs in separate physical locations within the region.", "answer": "Availability zone"},
            {"stmt": "You configure a logical group with 2 fault domains and 5 update domains before deploying the web VMs into it.", "answer": "Availability set"},
        ],
        "tf": [
            {"stmt": "VMs in an availability set are protected if the entire datacenter hosting them fails.", "truth": False,
             "why": "An availability set lives within a single datacenter; surviving a datacenter outage requires availability zones."},
            {"stmt": "Deploying two or more VMs across availability zones qualifies for a 99.99% SLA.", "truth": True,
             "why": "Zone-redundant multi-VM deployments carry the 99.99% connectivity SLA, versus 99.95% for availability sets."},
            {"stmt": "An availability zone is a logical grouping of VMs within one datacenter based on fault and update domains.", "truth": False,
             "why": "That describes an availability set. A zone is a physically separate datacenter location in the region."},
        ],
    },
    {
        "a": "Fault domain", "b": "Update domain",
        "def_a": "A set of hardware sharing a common power source and network switch, like a rack, isolating unplanned failures",
        "def_b": "A group of VMs and hosts that Azure may reboot together during planned platform maintenance",
        "difference": "Fault domains guard against unplanned hardware failure: VMs in different fault domains do not share the same rack's power or switch. Update domains guard against planned maintenance: Azure reboots only one update domain at a time, waiting between domains. Availability sets default to up to 3 fault domains and 5 update domains (expandable to 20).",
        "scenarios": [
            {"stmt": "A top-of-rack switch dies and takes down every VM on that rack, but the second VM keeps serving because it was placed on different hardware.", "answer": "Fault domain"},
            {"stmt": "During scheduled host OS patching, Azure reboots one batch of your VMs, waits for recovery, then moves to the next batch.", "answer": "Update domain"},
            {"stmt": "You raise the count of one domain type to 20 so that planned maintenance restarts as small a slice of the fleet as possible at a time.", "answer": "Update domain"},
            {"stmt": "The concern being mitigated is a shared power supply failing unexpectedly and killing all VMs plugged into it.", "answer": "Fault domain"},
        ],
        "tf": [
            {"stmt": "A fault domain is the group of VMs that Azure reboots together during planned maintenance.", "truth": False,
             "why": "Rebooting together during planned maintenance defines an update domain. A fault domain is hardware sharing power and networking."},
            {"stmt": "During planned maintenance, Azure never reboots two update domains of an availability set at the same time.", "truth": True,
             "why": "Update domains are processed one at a time, which is exactly how they preserve availability through maintenance."},
        ],
    },
    {
        "a": "Scale up", "b": "Scale out",
        "def_a": "Moving a resource to a more powerful size or tier, such as a VM with more vCPUs and RAM",
        "def_b": "Adding more instances of a resource, such as growing a scale set from 3 to 10 identical VMs",
        "difference": "Scale up is vertical: one machine gets bigger, which usually requires a restart and eventually hits a hardware ceiling. Scale out is horizontal: you add identical instances behind a load balancer, which is what VM Scale Sets and App Service autoscale do and has no practical ceiling. Autoscale rules almost always mean scale out.",
        "scenarios": [
            {"stmt": "A SQL VM is CPU-bound and cannot be load balanced, so you resize it from D4s_v5 to D16s_v5 during a maintenance window.", "answer": "Scale up"},
            {"stmt": "An autoscale rule adds three more instances to the VM scale set whenever average CPU stays above 75% for ten minutes.", "answer": "Scale out"},
            {"stmt": "The stateless web tier handles Black Friday by running twenty small identical instances behind the load balancer instead of five.", "answer": "Scale out"},
            {"stmt": "You change an App Service plan from S1 to P2v3 so every app on it gets faster cores and more memory.", "answer": "Scale up"},
        ],
        "tf": [
            {"stmt": "Scaling out means moving a VM to a size with more vCPUs and memory.", "truth": False,
             "why": "Changing to a bigger size is scaling up (vertical). Scaling out adds more instances (horizontal)."},
            {"stmt": "Resizing a running Azure VM to a different size typically requires the VM to restart.", "truth": True,
             "why": "The VM must be reallocated onto hardware that supports the new size, which involves a reboot."},
        ],
    },
    {
        "a": "App Service plan", "b": "App Service",
        "def_a": "The underlying compute: a set of VM resources with a region, size, and pricing tier that hosts one or more apps",
        "def_b": "The web app itself: the code, configuration, custom domains, and endpoints that run on a plan",
        "difference": "The plan is what you pay for and what you scale: its tier decides features (slots, autoscale, VNet integration) and its instance count applies to everything on it. The App Service (web app) is an individual application deployed onto a plan, and multiple apps can share one plan, competing for the same compute.",
        "scenarios": [
            {"stmt": "You bump the pricing tier from Basic to Standard so that deployment slots and autoscale become available to the apps hosted on it.", "answer": "App Service plan"},
            {"stmt": "A developer configures a custom domain, TLS binding, and app settings for the customer-facing site itself.", "answer": "App Service"},
            {"stmt": "Five small internal websites run happily on the same compute, sharing its two instances to save cost.", "answer": "App Service plan"},
            {"stmt": "One of the sites keeps crashing on startup, so you stream its application logs and restart just that one application.", "answer": "App Service"},
        ],
        "tf": [
            {"stmt": "Scaling out an App Service plan adds instances that serve every app hosted on that plan.", "truth": True,
             "why": "Instance count is a property of the plan; all apps on the plan run on all of its instances."},
            {"stmt": "Each web app requires its own dedicated App Service plan.", "truth": False,
             "why": "Multiple apps can share a single plan; that is a common cost-saving pattern, though they then share its compute."},
        ],
    },
    {
        "a": "Deployment slot swap", "b": "Redeploying to production",
        "def_a": "Exchanging a warmed-up staging slot with production so traffic shifts with no downtime and rollback is one swap away",
        "def_b": "Pushing new code directly onto the production app, causing a cold start and offering no instant rollback path",
        "difference": "A slot swap deploys to staging first, warms the instances, then exchanges the slots' contents, so users hit an already-running app and a bad release is undone by swapping back. Redeploying straight to production restarts the live app cold, risks downtime during startup, and rolling back means another full deployment. Slots require Standard tier or higher.",
        "scenarios": [
            {"stmt": "The release goes to a staging environment, gets smoke-tested on real Azure infrastructure, then trades places with the live site with zero downtime.", "answer": "Deployment slot swap"},
            {"stmt": "A hotfix is pushed straight onto the live app, and users see errors for a minute while the site restarts and warms up.", "answer": "Redeploying to production"},
            {"stmt": "The new build is broken, and the on-call engineer restores the previous version in seconds by reversing the earlier exchange.", "answer": "Deployment slot swap"},
            {"stmt": "On the Free tier with no staging environments available, the only option is to publish new code directly over the running site.", "answer": "Redeploying to production"},
        ],
        "tf": [
            {"stmt": "After a slot swap, rolling back to the previous version requires rebuilding and redeploying the old code.", "truth": False,
             "why": "The old version now sits in the staging slot, so swapping again restores it immediately. Rebuild-to-rollback is the direct-deploy pain."},
            {"stmt": "Settings marked as deployment slot settings stay with their slot and do not move during a swap.", "truth": True,
             "why": "Slot-sticky settings (like a staging database connection string) remain attached to the slot rather than following the app content."},
        ],
    },
    {
        "a": "Bicep", "b": "ARM template",
        "def_a": "A domain-specific language with clean, declarative syntax that transpiles to ARM JSON for deployment",
        "def_b": "The native JSON document format that Azure Resource Manager consumes to deploy resources declaratively",
        "difference": "Both describe the same deployments through Azure Resource Manager and neither keeps a state file. Bicep is the friendlier authoring layer: simpler syntax, easy modules, no copy-loops of JSON, and it compiles down to ARM JSON with 'bicep build'. ARM templates are the underlying JSON the platform actually processes, and existing JSON can be decompiled into Bicep.",
        "scenarios": [
            {"stmt": "A team abandons hand-editing 900 lines of JSON with nested quotes and adopts the concise DSL that compiles into that JSON.", "answer": "Bicep"},
            {"stmt": "A vendor ships you the raw JSON file with $schema, parameters, and resources sections that ARM ingests directly.", "answer": "ARM template"},
            {"stmt": "You run a decompile command to convert an existing JSON deployment file into the newer, cleaner authoring language.", "answer": "Bicep"},
            {"stmt": "In the portal you click Export template on a resource group and receive this JSON representation of the deployed resources.", "answer": "ARM template"},
        ],
        "tf": [
            {"stmt": "Bicep deployments require maintaining a state file, similar to Terraform.", "truth": False,
             "why": "Bicep (like ARM JSON) is stateless; Azure Resource Manager compares the template against the actual resources at deployment time."},
            {"stmt": "A Bicep file is transpiled into an ARM JSON template before Azure Resource Manager processes the deployment.", "truth": True,
             "why": "Bicep is an authoring abstraction; the platform ultimately consumes the compiled ARM JSON."},
        ],
    },
    {
        "a": "Incremental mode", "b": "Complete mode",
        "def_a": "The default deployment mode that adds or updates template resources and leaves everything else in the resource group untouched",
        "def_b": "A deployment mode that makes the resource group match the template, deleting existing resources the template does not define",
        "difference": "Incremental mode only acts on what the template declares; unrelated resources in the resource group survive. Complete mode treats the template as the full source of truth for the resource group and deletes resources not present in it, which makes it powerful for drift control and dangerous if you forget something. Complete mode applies only to resource group deployments.",
        "scenarios": [
            {"stmt": "You deploy a template containing one new storage account into a busy resource group, and the twenty unrelated resources there are untouched.", "answer": "Incremental mode"},
            {"stmt": "After a deployment, a VM that someone had created manually in the resource group is gone because it was not defined in the template.", "answer": "Complete mode"},
            {"stmt": "To guarantee the production resource group exactly mirrors the template in source control with no drift, the pipeline deploys in this mode.", "answer": "Complete mode"},
            {"stmt": "An admin runs a deployment without specifying a mode, so Resource Manager uses this behavior automatically.", "answer": "Incremental mode"},
        ],
        "tf": [
            {"stmt": "Incremental mode deletes resources in the resource group that are not defined in the template.", "truth": False,
             "why": "That is complete mode's behavior. Incremental mode leaves resources outside the template alone."},
            {"stmt": "Incremental is the default deployment mode for Azure Resource Manager deployments.", "truth": True,
             "why": "Unless you explicitly specify complete mode, deployments run incrementally."},
        ],
    },
    # ------------------------------------------------------ networking ---
    {
        "a": "Network security group", "b": "Application security group",
        "def_a": "A set of prioritized allow/deny rules that filters traffic by source, destination, port, and protocol at a subnet or NIC",
        "def_b": "A named logical grouping of VM NICs that NSG rules can reference as a source or destination instead of IP addresses",
        "difference": "The NSG is the thing that actually filters packets with its prioritized rules. An ASG filters nothing on its own: it is a label you attach to NICs so that NSG rules can say \"from WebServers to DbServers\" instead of maintaining IP lists. ASGs only have meaning when referenced inside NSG rules, and grouped NICs must be in the same virtual network.",
        "scenarios": [
            {"stmt": "You create a rule with priority 100 allowing TCP 443 from the internet and a rule with priority 4096 denying everything else on the subnet.", "answer": "Network security group"},
            {"stmt": "Instead of updating IP-based rules every time a web VM is added, you tag each new NIC with the WebServers label and the existing rules just apply.", "answer": "Application security group"},
            {"stmt": "A rule needs to allow SQL traffic only from NICs labeled AppTier to NICs labeled DataTier, with no IP addresses written anywhere.", "answer": "Application security group"},
            {"stmt": "Traffic to a VM is being dropped, and you inspect the prioritized inbound rules attached to its subnet to find the deny that matches first.", "answer": "Network security group"},
        ],
        "tf": [
            {"stmt": "An application security group can block traffic on its own without being referenced in any NSG rule.", "truth": False,
             "why": "ASGs are only labels for NICs; all filtering is performed by NSG rules that reference them."},
            {"stmt": "A network security group can be associated with a subnet, a network interface, or both.", "truth": True,
             "why": "NSGs apply at either level, and when both are set, traffic must pass both NSGs."},
            {"stmt": "A network security group is a logical label applied to NICs so rules can reference server roles instead of IP addresses.", "truth": False,
             "why": "That definition belongs to the application security group. The NSG is the rule set that filters the traffic."},
        ],
    },
    {
        "a": "Service endpoint", "b": "Private endpoint",
        "def_a": "A subnet setting that routes traffic to a PaaS service's public endpoint over the Azure backbone and lets the service firewall allow that subnet",
        "def_b": "A NIC with a private IP from your VNet that maps a specific PaaS resource instance into your network via Private Link",
        "difference": "A service endpoint optimizes and secures the path to the service's public endpoint: traffic stays on the backbone and the resource firewall can trust your subnet, but the service keeps a public address and on-premises clients get no benefit. A private endpoint gives one specific resource instance a private IP inside your VNet, is reachable from peered networks and on-premises over VPN/ExpressRoute, and lets you shut off public access entirely.",
        "scenarios": [
            {"stmt": "A storage account must be reachable from the on-premises network over the site-to-site VPN using a private IP address, with its public endpoint disabled.", "answer": "Private endpoint"},
            {"stmt": "You enable Microsoft.Storage on a subnet so VM traffic to storage rides the Azure backbone, then allow that subnet in the storage firewall — at no extra cost.", "answer": "Service endpoint"},
            {"stmt": "nslookup for mystorage.blob.core.windows.net from inside the VNet now returns 10.1.2.5, an address from your own subnet.", "answer": "Private endpoint"},
            {"stmt": "The requirement is only that VNet-to-storage traffic avoid the public internet path and that the account firewall reject everything except your subnet; on-prem access is not needed.", "answer": "Service endpoint"},
        ],
        "tf": [
            {"stmt": "A service endpoint allows on-premises clients connected via VPN to reach the PaaS service over a private IP address.", "truth": False,
             "why": "Service endpoints only work for traffic originating in the VNet's subnets; private IP access from on-premises requires a private endpoint."},
            {"stmt": "A private endpoint assigns the PaaS resource a private IP address from your virtual network's address space.", "truth": True,
             "why": "It creates a NIC in your subnet, so the resource resolves to and is reached at that private IP."},
        ],
    },
    {
        "a": "VNet peering", "b": "VPN gateway",
        "def_a": "A direct, low-latency connection between two virtual networks over the Microsoft backbone, including across regions",
        "def_b": "A gateway resource that builds encrypted IPsec tunnels, connecting VNets to on-premises networks or to each other over the internet",
        "difference": "Peering links VNets privately across the Microsoft backbone with no gateway, no encryption overhead, and near-line-rate bandwidth; it is non-transitive and cannot reach on-premises. A VPN gateway provides encrypted tunnels — site-to-site to on-premises, point-to-site for individual clients, or VNet-to-VNet — with bandwidth bounded by the gateway SKU. Connecting to a datacenter means a gateway; connecting VNet to VNet cheaply and fast means peering.",
        "scenarios": [
            {"stmt": "The hub VNet in East US and a spoke VNet in West Europe need private connectivity with maximum throughput and minimum latency, no encryption devices involved.", "answer": "VNet peering"},
            {"stmt": "The company datacenter's edge firewall must build an encrypted IPsec tunnel to Azure so on-premises servers can reach VNet resources.", "answer": "VPN gateway"},
            {"stmt": "Remote developers each need a point-to-site connection from their laptops into the VNet while working from home.", "answer": "VPN gateway"},
            {"stmt": "Two VNets in the same region must exchange traffic using each other's private IPs with single-digit-millisecond latency and no bandwidth-limited middlebox.", "answer": "VNet peering"},
        ],
        "tf": [
            {"stmt": "VNet peering is transitive: if VNet A peers with B and B peers with C, then A can reach C automatically.", "truth": False,
             "why": "Peering is non-transitive; A needs its own peering to C, or traffic must route through an NVA or gateway in the hub."},
            {"stmt": "Global VNet peering can connect virtual networks that are in different Azure regions.", "truth": True,
             "why": "Global peering links VNets across regions over the Microsoft backbone."},
            {"stmt": "Connecting a VNet to an on-premises network via site-to-site IPsec is a job for VNet peering.", "truth": False,
             "why": "Peering only connects Azure VNets to each other. Site-to-site tunnels to on-premises require a VPN gateway (or ExpressRoute)."},
        ],
    },
    {
        "a": "Azure Load Balancer", "b": "Application Gateway",
        "def_a": "A layer 4 regional load balancer that distributes TCP and UDP traffic based on the 5-tuple, with no payload awareness",
        "def_b": "A layer 7 regional load balancer for HTTP(S) offering URL path routing, TLS termination, cookie affinity, and an optional WAF",
        "difference": "Azure Load Balancer works at the transport layer: it spreads TCP/UDP flows and never looks inside them, which makes it fast and protocol-agnostic. Application Gateway understands HTTP: it can terminate TLS, route /images to one pool and /api to another, use host headers, keep session affinity with cookies, and protect apps with the Web Application Firewall.",
        "scenarios": [
            {"stmt": "RDP (TCP 3389) sessions and a custom UDP telemetry stream must be distributed across a pool of VMs.", "answer": "Azure Load Balancer"},
            {"stmt": "Requests to contoso.com/api must go to the API server pool while contoso.com/images goes to the static content pool.", "answer": "Application Gateway"},
            {"stmt": "Security wants inbound web traffic inspected against SQL injection and cross-site scripting signatures before it reaches the app servers.", "answer": "Application Gateway"},
            {"stmt": "The design needs simple, ultra-fast distribution of non-HTTP traffic with health probes, and nothing may inspect the packets' contents.", "answer": "Azure Load Balancer"},
        ],
        "tf": [
            {"stmt": "Azure Load Balancer can route requests to different backend pools based on the URL path.", "truth": False,
             "why": "URL path-based routing requires layer 7 awareness, which is Application Gateway's territory. Load Balancer operates at layer 4."},
            {"stmt": "Application Gateway can terminate TLS so that backend servers receive decrypted HTTP traffic.", "truth": True,
             "why": "TLS/SSL termination at the gateway offloads certificate handling from the backend pool."},
        ],
    },
    {
        "a": "Traffic Manager", "b": "Azure Front Door",
        "def_a": "A DNS-based global routing service that answers name lookups with the best endpoint but never touches the actual traffic",
        "def_b": "A global layer 7 entry point that proxies HTTP(S) through Microsoft's edge, adding TLS offload, caching, URL routing, and WAF",
        "difference": "Traffic Manager works purely at the DNS layer: it hands the client an endpoint address using routing methods like priority, weighted, performance, or geographic, then steps out of the data path — so it supports any protocol but adds no processing. Front Door is an actual reverse proxy at Microsoft's edge for HTTP(S): traffic flows through it, enabling acceleration, caching, path routing, TLS termination, and WAF inspection.",
        "scenarios": [
            {"stmt": "A global service running on a custom TCP protocol (not HTTP) needs clients directed to the closest healthy region via name resolution alone.", "answer": "Traffic Manager"},
            {"stmt": "A worldwide web app wants requests to enter Microsoft's edge near each user, get TLS terminated there, and have static assets cached at the edge.", "answer": "Azure Front Door"},
            {"stmt": "Because this service only influences which IP the client receives at lookup time, failover speed depends on DNS TTL expiry.", "answer": "Traffic Manager"},
            {"stmt": "The requirement list includes global HTTP load balancing plus a built-in web application firewall at the edge.", "answer": "Azure Front Door"},
        ],
        "tf": [
            {"stmt": "Traffic Manager proxies each HTTP request through its own infrastructure and can cache responses.", "truth": False,
             "why": "That describes Front Door. Traffic Manager only answers DNS queries; client traffic then flows directly to the chosen endpoint."},
            {"stmt": "Traffic Manager can route clients to endpoints using priority, weighted, performance, and geographic methods.", "truth": True,
             "why": "Those are core Traffic Manager routing methods applied when resolving the DNS name."},
        ],
    },
    {
        "a": "Public DNS zone", "b": "Private DNS zone",
        "def_a": "An Azure-hosted DNS zone whose records are resolvable from the internet once the registrar delegates to Azure's name servers",
        "def_b": "An Azure-hosted DNS zone resolvable only from virtual networks linked to it, with optional auto-registration of VM records",
        "difference": "A public zone serves the internet: you delegate your domain's NS records at the registrar to the four Azure name servers and the world can resolve your records. A private zone serves only VNets you explicitly link to it, is invisible to the internet, and a link with auto-registration enabled creates and deletes VM A records automatically.",
        "scenarios": [
            {"stmt": "Customers around the world must resolve www.contoso.com to your web app, so you update the NS records at your registrar to Azure's name servers.", "answer": "Public DNS zone"},
            {"stmt": "VMs across three linked VNets need to resolve each other as vm-name.contoso.internal, with records appearing automatically when VMs are created.", "answer": "Private DNS zone"},
            {"stmt": "An external security scan confirms that the hostnames in this zone cannot be resolved from anywhere on the internet.", "answer": "Private DNS zone"},
            {"stmt": "You add an MX record so that mail servers anywhere can discover where to deliver email for your domain.", "answer": "Public DNS zone"},
        ],
        "tf": [
            {"stmt": "Records in an Azure private DNS zone can be resolved by any client on the internet.", "truth": False,
             "why": "Private zones answer only queries from virtual networks linked to the zone; the internet cannot see them."},
            {"stmt": "With auto-registration enabled on a VNet link, Azure automatically creates A records in the private zone for VMs in that VNet.", "truth": True,
             "why": "Auto-registration maintains VM hostname records for you, adding them at creation and removing them at deletion."},
        ],
    },
    {
        "a": "CNAME record", "b": "A record",
        "def_a": "A DNS record that aliases one name to another domain name, which is then resolved in turn",
        "def_b": "A DNS record that maps a name directly to an IPv4 address",
        "difference": "An A record is the final answer: name to IPv4 address (AAAA for IPv6). A CNAME defers the answer: it points a name at another name, which is handy when the target's IP can change, like an Azure service hostname. A CNAME cannot be created at the zone apex (the bare domain), and no other records may coexist at a CNAME's name.",
        "scenarios": [
            {"stmt": "www.contoso.com should follow myapp.azurewebsites.net wherever that service's IP moves, so you point the name at the hostname rather than an address.", "answer": "CNAME record"},
            {"stmt": "A record set must resolve vpn.contoso.com directly to the static IPv4 address 20.50.10.4.", "answer": "A record"},
            {"stmt": "You try to point the zone apex contoso.com at another hostname and DNS rules refuse this record type at the apex.", "answer": "CNAME record"},
            {"stmt": "The domain apex must resolve to your public IP, so you create the record type that stores an IPv4 address (or use an alias form of it).", "answer": "A record"},
        ],
        "tf": [
            {"stmt": "A CNAME record maps a hostname directly to an IPv4 address.", "truth": False,
             "why": "IPv4 mapping is the A record's job. A CNAME maps a name to another name."},
            {"stmt": "You cannot create a CNAME record at the apex (root) of a DNS zone.", "truth": True,
             "why": "DNS forbids CNAME at the apex because it must coexist with SOA and NS records; Azure alias records are the workaround for apex-to-service pointing."},
        ],
    },
    # -------------------------------------------- monitoring & recovery ---
    {
        "a": "Metrics", "b": "Logs",
        "def_a": "Lightweight numeric time-series values collected at regular intervals, available in near real time",
        "def_b": "Timestamped event and trace records with rich properties, stored in Log Analytics and queried with KQL",
        "difference": "Metrics are numbers over time — CPU percentage, request count — cheap to store, retained 93 days by the platform, ideal for fast alerting, autoscale rules, and charts. Logs are structured event records that land in a Log Analytics workspace where you join, filter, and analyze them with Kusto Query Language; they carry far more context but arrive with more latency.",
        "scenarios": [
            {"stmt": "An autoscale rule needs a near-real-time numeric signal, average CPU over five minutes, to decide when to add instances.", "answer": "Metrics"},
            {"stmt": "An investigation requires joining sign-in events with firewall events using a KQL query across the last 30 days.", "answer": "Logs"},
            {"stmt": "You pin a chart of IOPS and network throughput per minute for a disk to the operations dashboard.", "answer": "Metrics"},
            {"stmt": "The question 'which user deleted which files, from which IP, with what result codes' needs detailed records with many text properties.", "answer": "Logs"},
        ],
        "tf": [
            {"stmt": "Azure Monitor metrics are queried using Kusto Query Language in a Log Analytics workspace by default.", "truth": False,
             "why": "KQL over Log Analytics is how you query logs. Platform metrics live in a time-series store queried via metrics explorer (though they can optionally be routed to a workspace)."},
            {"stmt": "Platform metrics are retained by Azure Monitor for 93 days by default.", "truth": True,
             "why": "The metrics database keeps platform metrics for 93 days; send them to a workspace or archive if you need longer."},
        ],
    },
    {
        "a": "Activity log", "b": "Resource logs",
        "def_a": "The subscription-level record of control-plane operations: who created, changed, or deleted which resource and when",
        "def_b": "Data-plane records emitted from inside a resource, such as queries run, requests served, or secrets retrieved",
        "difference": "The activity log is about operations on resources from the outside — deployments, deletions, role assignments — collected automatically per subscription and kept 90 days for free. Resource logs are about what happened inside a resource — a Key Vault secret read, a storage request — and are collected only after you create a diagnostic setting routing them to a workspace, storage, or event hub.",
        "scenarios": [
            {"stmt": "You need to find out which user deleted the production NSG last Tuesday and from which IP the request came.", "answer": "Activity log"},
            {"stmt": "Auditors ask which applications actually retrieved secrets from Key Vault, which requires enabling a diagnostic setting first.", "answer": "Resource logs"},
            {"stmt": "This telemetry exists automatically for every subscription with no configuration and shows every ARM write operation for the last 90 days.", "answer": "Activity log"},
            {"stmt": "To see individual query performance records emitted from inside an Azure SQL database, you route this category to a Log Analytics workspace.", "answer": "Resource logs"},
        ],
        "tf": [
            {"stmt": "Resource logs are collected automatically for all resources without any configuration.", "truth": False,
             "why": "Resource logs flow only after you create a diagnostic setting choosing categories and a destination. The activity log is the one collected automatically."},
            {"stmt": "The activity log records subscription-level control-plane events, such as creating or deleting a resource.", "truth": True,
             "why": "That is exactly its scope: management operations through Azure Resource Manager, retained 90 days by default."},
        ],
    },
    {
        "a": "Alert rule", "b": "Action group",
        "def_a": "The definition of what to watch: a scope, a signal, and a condition that fires an alert when met",
        "def_b": "A reusable set of notifications and automated actions, such as email, SMS, webhooks, runbooks, or functions, invoked when alerts fire",
        "difference": "The alert rule is the trigger: it binds a resource scope to a signal (metric, log query, activity log event) and a threshold or condition. The action group is the response: who gets notified and what automation runs. Rules reference action groups, and one action group is typically shared by many rules so contact lists live in one place.",
        "scenarios": [
            {"stmt": "You define: scope = production VM, signal = Percentage CPU, condition = average greater than 90% for 15 minutes.", "answer": "Alert rule"},
            {"stmt": "You define: email the on-call DL, send an SMS to the duty phone, and call a webhook that opens a ServiceNow ticket.", "answer": "Action group"},
            {"stmt": "The on-call rotation's phone number changed, and you update it once in a single place so all forty triggers notify the new number.", "answer": "Action group"},
            {"stmt": "The team asks to be triggered when a specific KQL query over Log Analytics returns more than five results in ten minutes.", "answer": "Alert rule"},
        ],
        "tf": [
            {"stmt": "An action group is where you configure the metric threshold that determines when an alert fires.", "truth": False,
             "why": "Thresholds and conditions belong to the alert rule. The action group only defines notifications and actions taken after firing."},
            {"stmt": "A single action group can be referenced by many different alert rules.", "truth": True,
             "why": "Action groups are reusable, so shared contact lists and automations are defined once and attached to any number of rules."},
        ],
    },
    {
        "a": "Recovery Services vault", "b": "Backup vault",
        "def_a": "The classic vault protecting Azure VMs, SQL and SAP HANA in VMs, Azure Files, MARS agent data, and hosting Site Recovery",
        "def_b": "The newer vault type protecting workloads like Azure Blobs, managed disks, Azure Database for PostgreSQL, and AKS",
        "difference": "Both store backups, but they cover different workload lists. The Recovery Services vault is the long-standing vault for IaaS VM backup, in-VM SQL/SAP HANA, Azure Files, on-premises MARS backups, and it is also where Azure Site Recovery replication lives. The Backup vault serves the newer data-protection workloads: blobs, disks, PostgreSQL, and AKS. Picking the wrong vault type means the workload simply is not offered.",
        "scenarios": [
            {"stmt": "You are setting up nightly backup for twenty Azure VMs plus SQL Server running inside one of them, and you must pick the vault type that supports both.", "answer": "Recovery Services vault"},
            {"stmt": "The task is configuring operational backup for Azure Blob storage and protection for several standalone managed disks.", "answer": "Backup vault"},
            {"stmt": "Before enabling Azure Site Recovery replication to a secondary region, you must create this vault type because ASR only works with it.", "answer": "Recovery Services vault"},
            {"stmt": "An Azure Database for PostgreSQL flexible server needs long-term backup retention, which requires this vault type.", "answer": "Backup vault"},
        ],
        "tf": [
            {"stmt": "Azure Site Recovery replication is configured inside a Backup vault.", "truth": False,
             "why": "ASR lives in a Recovery Services vault. Backup vaults handle newer backup workloads only, not replication."},
            {"stmt": "Backing up Azure Blobs and Azure managed disks uses a Backup vault rather than a Recovery Services vault.", "truth": True,
             "why": "Those workloads are served by the newer Backup vault; the Recovery Services vault covers VMs, in-VM databases, Files, and MARS."},
        ],
    },
    {
        "a": "Azure Backup", "b": "Azure Site Recovery",
        "def_a": "A service that takes point-in-time copies of data and VMs so they can be restored after loss, corruption, or ransomware",
        "def_b": "A disaster recovery service that continuously replicates workloads to a secondary region and orchestrates failover and failback",
        "difference": "Backup answers \"give me my data back as it was\": scheduled recovery points, long retention, granular restores of files, disks, or whole VMs. Site Recovery answers \"keep the business running elsewhere\": near-continuous replication of running workloads to another region, recovery plans that orchestrate ordered failover, and non-disruptive test failovers. Backup is data protection; ASR is business continuity.",
        "scenarios": [
            {"stmt": "Ransomware encrypted a file server's disks, and you restore the whole VM from last night's recovery point.", "answer": "Azure Backup"},
            {"stmt": "If East US 2 goes down, the production VMs must come up in Central US within minutes, in dependency order, driven by a recovery plan.", "answer": "Azure Site Recovery"},
            {"stmt": "Compliance requires retaining monthly recovery points for seven years with item-level file restore capability.", "answer": "Azure Backup"},
            {"stmt": "The DR runbook calls for a quarterly test failover to the secondary region that must not disturb the ongoing replication or production traffic.", "answer": "Azure Site Recovery"},
        ],
        "tf": [
            {"stmt": "Azure Site Recovery's main purpose is keeping long-term point-in-time copies of data for granular file restores.", "truth": False,
             "why": "Long-retention recovery points and granular restore are Azure Backup. ASR replicates workloads for regional failover."},
            {"stmt": "Azure Site Recovery supports running a test failover without impacting production workloads or ongoing replication.", "truth": True,
             "why": "Test failovers spin up the replicated VMs in an isolated network so DR drills do not touch production."},
        ],
    },
    {
        "a": "RPO", "b": "RTO",
        "def_a": "Recovery point objective: the maximum acceptable amount of data loss, measured as the age of the last usable recovery point",
        "def_b": "Recovery time objective: the maximum acceptable downtime before service must be restored after an incident",
        "difference": "RPO is measured backward from the incident: how much recent data you can afford to lose, which dictates replication or backup frequency. RTO is measured forward from the incident: how long until users are working again, which dictates your failover and restore speed. An RPO of 15 minutes with an RTO of 2 hours means: lose at most 15 minutes of data, be back within 2 hours.",
        "scenarios": [
            {"stmt": "The business states that at most five minutes of committed transactions may ever be lost, so replication must run near-continuously.", "answer": "RPO"},
            {"stmt": "The contract says the ordering portal must be operational again within four hours of a regional outage.", "answer": "RTO"},
            {"stmt": "Because backups run only nightly, a failure at 5 PM could lose the whole working day, violating this objective.", "answer": "RPO"},
            {"stmt": "Stakeholders time a full DR drill from outage declaration to users successfully logging in, comparing the result against this objective.", "answer": "RTO"},
        ],
        "tf": [
            {"stmt": "RPO defines how quickly services must be restored after a disaster.", "truth": False,
             "why": "Time-to-restore is RTO. RPO defines how much data, measured in time, you can afford to lose."},
            {"stmt": "Increasing backup or replication frequency improves (lowers) your achievable RPO.", "truth": True,
             "why": "More frequent recovery points shrink the window of data that can be lost between the last point and the failure."},
            {"stmt": "An RTO of one hour means the organization accepts losing up to one hour of data.", "truth": False,
             "why": "That would be an RPO of one hour. An RTO of one hour means service must be running again within an hour."},
        ],
    },
]
