"""Confusable-term pairs for the AZ-900 Vocab Arcade.

Each pair: two terms candidates mix up, one-line definitions, the key
difference (shown as the teaching line), exam-style discrimination
scenarios (answer must exactly equal a or b), and true/false statements
including definition-swap traps. Validate with: python3 validate.py vocab_data.py
"""

PAIRS = [
    # ------------------------------------------------- cloud concepts ---
    {
        "a": "Scalability", "b": "Elasticity",
        "def_a": "The ability of a system to increase or decrease resources to handle changes in demand",
        "def_b": "The ability to automatically and rapidly add or remove resources as demand changes in real time",
        "difference": "Scalability is the capability to resize (even manually, even planned); elasticity is that scaling happening automatically and dynamically with demand. Elastic systems are scalable, but a scalable system is not elastic unless it adjusts itself.",
        "scenarios": [
            {"stmt": "During the holiday sale the web tier automatically grew from 2 to 8 VMs, then shrank back overnight with no human involved.", "answer": "Elasticity"},
            {"stmt": "An architect confirms the design can grow from 100 to 100,000 users by adding more instances when the team chooses to.", "answer": "Scalability"},
            {"stmt": "An admin manually resizes a database server to a larger tier ahead of a planned marketing campaign.", "answer": "Scalability"},
            {"stmt": "Resources expand within minutes of a traffic spike and are released the moment demand drops, so you never pay for idle capacity.", "answer": "Elasticity"},
        ],
        "tf": [
            {"stmt": "Elasticity means an administrator can manually add servers to a system when planning for future growth.", "truth": False,
             "why": "That describes scalability. Elasticity specifically means the system adjusts capacity automatically as demand changes."},
            {"stmt": "A system can be scalable without being elastic.", "truth": True,
             "why": "If you can resize it manually it is scalable; it only becomes elastic when the resizing happens automatically with demand."},
        ],
    },
    {
        "a": "Vertical scaling", "b": "Horizontal scaling",
        "def_a": "Increasing (or decreasing) the power of a single resource, such as moving a VM to a size with more CPU and RAM",
        "def_b": "Adding or removing instances of a resource, such as going from 3 web servers to 10 identical ones",
        "difference": "Vertical (scale up/down) changes the size of one machine; horizontal (scale out/in) changes the number of machines. Autoscaling and load balancing pair naturally with horizontal scaling.",
        "scenarios": [
            {"stmt": "A database VM is moved from 4 vCPUs to 16 vCPUs to handle heavier queries.", "answer": "Vertical scaling"},
            {"stmt": "A VM scale set adds five more identical web servers behind a load balancer at lunchtime.", "answer": "Horizontal scaling"},
            {"stmt": "The fix for slow renders was upgrading the workstation VM to a size with a bigger GPU and double the memory.", "answer": "Vertical scaling"},
            {"stmt": "To survive instance failures and spread traffic, the app runs as many small identical nodes instead of one big one.", "answer": "Horizontal scaling"},
        ],
        "tf": [
            {"stmt": "Scaling out means moving a VM to a larger size with more CPU and RAM.", "truth": False,
             "why": "Scaling out is horizontal: adding more instances. Moving to a larger VM size is scaling up (vertical)."},
            {"stmt": "Horizontal scaling typically works together with a load balancer to spread traffic across the added instances.", "truth": True,
             "why": "When you scale out to multiple identical instances, a load balancer distributes requests among them."},
        ],
    },
    {
        "a": "High availability", "b": "Reliability",
        "def_a": "Keeping a service up and accessible with minimal downtime, usually expressed as an uptime percentage like 99.99%",
        "def_b": "The ability of a system to recover from failures and continue to function",
        "difference": "High availability is about maximizing uptime (measured in nines); reliability is the broader ability to withstand and recover from failures — a pillar of the Well-Architected Framework that includes resiliency and self-healing.",
        "scenarios": [
            {"stmt": "The design goal for the customer portal is 99.99% uptime.", "answer": "High availability"},
            {"stmt": "After an entire zone went down, the workload detected the failure, failed over, and returned itself to full function.", "answer": "Reliability"},
            {"stmt": "VMs are spread across availability zones so users experience as little downtime as possible.", "answer": "High availability"},
            {"stmt": "The Well-Architected pillar concerned with a system's ability to recover from failures and keep working.", "answer": "Reliability"},
        ],
        "tf": [
            {"stmt": "High availability is defined as a system's ability to recover from failures and continue functioning.", "truth": False,
             "why": "That is the definition of reliability. High availability is about keeping the service up with minimal downtime (uptime percentage)."},
            {"stmt": "Availability is commonly expressed in nines, such as 99.9% or 99.99% uptime.", "truth": True,
             "why": "SLAs state availability as a percentage of uptime; each extra nine cuts allowed downtime roughly tenfold."},
        ],
    },
    {
        "a": "High availability", "b": "Fault tolerance",
        "def_a": "Designing so a service stays up with minimal interruption when components fail, allowing brief downtime during failover",
        "def_b": "Designing with instant redundancy so a component failure causes zero interruption to the service",
        "difference": "Fault tolerance means no downtime at all when a component fails (redundant parts take over seamlessly); high availability tolerates a brief interruption while recovery happens. Fault tolerance is the stricter, more expensive goal.",
        "scenarios": [
            {"stmt": "When a node dies, a standby takes over within a couple of minutes and users barely notice the blip.", "answer": "High availability"},
            {"stmt": "A power supply fails and the server keeps running with zero interruption because a redundant supply carries the load instantly.", "answer": "Fault tolerance"},
            {"stmt": "The SLA promises 99.95% uptime, accepting a few minutes of downtime a month during failovers.", "answer": "High availability"},
            {"stmt": "The design requirement is that no single component failure may cause even one second of service interruption.", "answer": "Fault tolerance"},
        ],
        "tf": [
            {"stmt": "A highly available system guarantees zero downtime when any component fails.", "truth": False,
             "why": "Zero-interruption operation is fault tolerance. High availability minimizes downtime but allows brief interruptions during recovery."},
            {"stmt": "Fault tolerance generally costs more than high availability because fully redundant components must run simultaneously.", "truth": True,
             "why": "Seamless takeover requires duplicate capacity running at all times, which is more expensive than fast-recovery designs."},
        ],
    },
    {
        "a": "High availability", "b": "Disaster recovery",
        "def_a": "Surviving routine component failures so the service keeps running day to day",
        "def_b": "Recovering services and data after a catastrophic event, such as the loss of an entire region",
        "difference": "High availability handles everyday failures (a VM, a rack, a zone) to prevent downtime; disaster recovery is the plan — backups, replication to another region, RPO/RTO targets — for getting back up after a major catastrophe.",
        "scenarios": [
            {"stmt": "A plan defines how quickly the app must be restored in the paired region if the primary region is destroyed by a flood.", "answer": "Disaster recovery"},
            {"stmt": "Two extra instances in other zones absorb the load whenever one VM crashes, so the site never goes down.", "answer": "High availability"},
            {"stmt": "The team documents RPO and RTO targets and rehearses region failover twice a year.", "answer": "Disaster recovery"},
            {"stmt": "Spreading VMs across availability zones keeps the service running through a datacenter power failure.", "answer": "High availability"},
        ],
        "tf": [
            {"stmt": "Disaster recovery is primarily about preventing any downtime from routine hardware failures.", "truth": False,
             "why": "That is high availability's job. Disaster recovery is about restoring service and data after a catastrophic event like losing a region."},
            {"stmt": "RPO (how much data you can afford to lose) and RTO (how fast you must be back) are disaster recovery metrics.", "truth": True,
             "why": "Recovery point objective and recovery time objective quantify a DR plan's data-loss and downtime tolerances."},
        ],
    },
    {
        "a": "Capital expenditure (CapEx)", "b": "Operational expenditure (OpEx)",
        "def_a": "Large upfront spending on physical assets like servers and datacenters that depreciate over time",
        "def_b": "Ongoing pay-as-you-consume spending on services, with no upfront investment",
        "difference": "CapEx is buying assets up front (the on-premises model); OpEx is renting capability as you go (the cloud model). Cloud computing shifts IT spending from CapEx to OpEx.",
        "scenarios": [
            {"stmt": "The company signs a purchase order for 40 servers and a new UPS system for its datacenter.", "answer": "Capital expenditure (CapEx)"},
            {"stmt": "The monthly Azure invoice varies with exactly how many VM-hours and GBs the teams consumed.", "answer": "Operational expenditure (OpEx)"},
            {"stmt": "Finance depreciates the storage array over five years on the balance sheet.", "answer": "Capital expenditure (CapEx)"},
            {"stmt": "A startup avoids all upfront hardware costs by paying only for the cloud resources it uses each month.", "answer": "Operational expenditure (OpEx)"},
        ],
        "tf": [
            {"stmt": "Cloud computing's consumption-based model is a form of capital expenditure.", "truth": False,
             "why": "Pay-as-you-consume cloud spending is operational expenditure. CapEx is the upfront purchase of physical assets."},
            {"stmt": "Moving from on-premises datacenters to Azure typically shifts IT spending from CapEx to OpEx.", "truth": True,
             "why": "Instead of buying depreciating hardware up front, you pay operating costs for services as you consume them."},
        ],
    },
    {
        "a": "Pay-as-you-go", "b": "Reserved instances",
        "def_a": "Standard metered pricing with no commitment — start and stop anytime at full rates",
        "def_b": "A 1- or 3-year commitment to specific capacity in exchange for a significant discount",
        "difference": "Pay-as-you-go maximizes flexibility for variable or unpredictable workloads at the highest rate; reserved instances trade a long-term commitment for deep discounts (up to about 72%) on steady, predictable workloads.",
        "scenarios": [
            {"stmt": "A dev/test environment runs a few hours a week and gets deleted between sprints, billed at standard rates.", "answer": "Pay-as-you-go"},
            {"stmt": "A domain controller VM that will run 24/7 for the next three years is prepaid for a large discount.", "answer": "Reserved instances"},
            {"stmt": "A team spinning up an unpredictable proof-of-concept wants no commitment at all.", "answer": "Pay-as-you-go"},
            {"stmt": "Finance wants to cut the bill for a steady production database that has run around the clock for years.", "answer": "Reserved instances"},
        ],
        "tf": [
            {"stmt": "Reserved instances are the best choice for short-lived, unpredictable workloads.", "truth": False,
             "why": "Reservations require a 1- or 3-year commitment, so they suit steady predictable workloads; unpredictable ones fit pay-as-you-go."},
            {"stmt": "Reserved instances can reduce VM costs by up to roughly 72% compared with pay-as-you-go rates.", "truth": True,
             "why": "Microsoft advertises up to about 72% savings for 1- or 3-year reservations versus standard metered pricing."},
        ],
    },
    {
        "a": "Reserved instances", "b": "Spot pricing",
        "def_a": "Discounted pricing in exchange for a 1- or 3-year commitment, with guaranteed capacity for steady workloads",
        "def_b": "Deep discounts on Azure's spare capacity, which can be evicted with little notice when Azure needs it back",
        "difference": "Reservations trade commitment for a discount and keep your capacity guaranteed; spot trades reliability for the deepest discount — your VM can be taken away, so it only suits interruptible work like batch jobs.",
        "scenarios": [
            {"stmt": "An overnight batch-rendering job can be stopped and resumed at any time, so it runs on the cheapest evictable capacity.", "answer": "Spot pricing"},
            {"stmt": "A production ERP server that must never be interrupted is committed for three years to cut its cost.", "answer": "Reserved instances"},
            {"stmt": "Azure reclaims the VM mid-job because a paying on-demand customer needs the capacity.", "answer": "Spot pricing"},
            {"stmt": "Capacity is locked in and billed at a discount for the full term whether usage dips or not.", "answer": "Reserved instances"},
        ],
        "tf": [
            {"stmt": "Spot VMs guarantee your workload will run uninterrupted for the term you select.", "truth": False,
             "why": "Spot capacity can be evicted whenever Azure needs it back; guaranteed steady capacity at a discount is what reservations provide."},
            {"stmt": "Spot pricing is appropriate for interruptible workloads such as batch processing and experiments.", "truth": True,
             "why": "Because eviction can happen at any time, spot suits work that tolerates stopping and restarting."},
        ],
    },
    {
        "a": "Public cloud", "b": "Private cloud",
        "def_a": "Services delivered over the internet from a provider's shared, multitenant infrastructure, available to anyone who wants to buy them",
        "def_b": "Cloud infrastructure dedicated to a single organization, hosted in its own datacenter or by a third party",
        "difference": "Public cloud shares a provider's hardware among many customers with no upfront cost; private cloud dedicates the whole environment to one organization, giving maximum control at maximum cost and responsibility.",
        "scenarios": [
            {"stmt": "A startup deploys everything on Azure's shared infrastructure and never buys a single server.", "answer": "Public cloud"},
            {"stmt": "A government agency runs cloud-style self-service infrastructure that only its own departments can use, on hardware it controls.", "answer": "Private cloud"},
            {"stmt": "The organization gets complete control over hardware and security but must buy and maintain all the equipment itself.", "answer": "Private cloud"},
            {"stmt": "Resources are multitenant — many unrelated companies share the same physical hosts, isolated logically.", "answer": "Public cloud"},
        ],
        "tf": [
            {"stmt": "In a private cloud, hardware is shared with other organizations to reduce costs.", "truth": False,
             "why": "Sharing infrastructure among many organizations is the public cloud model; a private cloud is dedicated to one organization."},
            {"stmt": "A private cloud can be hosted by a third party and still be a private cloud, as long as it is dedicated to one organization.", "truth": True,
             "why": "What makes it private is single-organization dedication, not who owns the building."},
        ],
    },
    {
        "a": "Hybrid cloud", "b": "Multi-cloud",
        "def_a": "An environment that connects a private cloud or on-premises datacenter with a public cloud so workloads span both",
        "def_b": "Using two or more public cloud providers, such as Azure and AWS, at the same time",
        "difference": "Hybrid links private/on-premises with public cloud; multi-cloud means multiple public providers. A company can be both at once, but the terms answer different questions: private+public vs provider+provider.",
        "scenarios": [
            {"stmt": "Sensitive records stay in the company datacenter while the web front end runs in Azure, connected by ExpressRoute.", "answer": "Hybrid cloud"},
            {"stmt": "The analytics team runs on AWS while the app platform runs on Azure, and IT manages both providers.", "answer": "Multi-cloud"},
            {"stmt": "During demand spikes, workloads burst from the on-premises datacenter into the public cloud.", "answer": "Hybrid cloud"},
            {"stmt": "To avoid dependence on a single vendor, the company deliberately spreads workloads across two public cloud platforms.", "answer": "Multi-cloud"},
        ],
        "tf": [
            {"stmt": "Multi-cloud means connecting your on-premises datacenter to a public cloud provider.", "truth": False,
             "why": "That is hybrid cloud. Multi-cloud is using two or more public cloud providers simultaneously."},
            {"stmt": "Azure Arc can extend Azure management to servers running on-premises and even in other public clouds.", "truth": True,
             "why": "Arc projects non-Azure machines into Azure Resource Manager so hybrid and multi-cloud estates are governed from one place."},
        ],
    },
    {
        "a": "IaaS", "b": "PaaS",
        "def_a": "Infrastructure as a Service — you rent VMs, storage, and networks, and you manage everything from the operating system up",
        "def_b": "Platform as a Service — the provider manages the OS, runtime, and middleware; you deploy and manage only your applications and data",
        "difference": "The dividing line is the operating system: in IaaS you patch and manage the OS yourself (maximum control); in PaaS the provider handles OS and runtime so you focus on code. Shared-responsibility questions hinge on this line.",
        "scenarios": [
            {"stmt": "The ops team schedules monthly OS patching windows for its fleet of Azure VMs.", "answer": "IaaS"},
            {"stmt": "Developers push code to Azure App Service and never see or patch the underlying operating system.", "answer": "PaaS"},
            {"stmt": "A legacy app needs a custom kernel module and full administrator access to the server.", "answer": "IaaS"},
            {"stmt": "The database engine's patching, backups, and high availability are handled by the platform; the team just manages schemas and data.", "answer": "PaaS"},
        ],
        "tf": [
            {"stmt": "In IaaS, the cloud provider is responsible for patching the guest operating system on your VMs.", "truth": False,
             "why": "OS patching in IaaS belongs to the customer. The provider manages physical hosts, network, and datacenter — the OS shifts to the provider only in PaaS/SaaS."},
            {"stmt": "Lift-and-shift migrations most commonly land on IaaS because the applications move with the fewest changes.", "truth": True,
             "why": "Rehosting VMs as Azure VMs preserves the existing OS and app stack, which is why lift-and-shift targets IaaS."},
        ],
    },
    {
        "a": "PaaS", "b": "SaaS",
        "def_a": "A managed platform (OS, runtime, middleware) on which you build and host your own applications",
        "def_b": "A finished application delivered over the internet that you simply sign in and use, like Microsoft 365",
        "difference": "PaaS gives you a platform to build your own software; SaaS gives you someone else's finished software. In SaaS you manage only your data, devices, and identities — everything else is the provider's.",
        "scenarios": [
            {"stmt": "The company subscribes to a ready-made email and collaboration suite and just manages users and mailboxes.", "answer": "SaaS"},
            {"stmt": "A dev team deploys its custom ordering API to a managed runtime it doesn't patch.", "answer": "PaaS"},
            {"stmt": "No development happens at all — staff open a browser, sign in, and use the vendor's application.", "answer": "SaaS"},
            {"stmt": "Azure App Service and Azure SQL Database are the foundation the team builds its product on.", "answer": "PaaS"},
        ],
        "tf": [
            {"stmt": "Microsoft 365 is an example of Platform as a Service.", "truth": False,
             "why": "Microsoft 365 is finished software you consume, which makes it SaaS. PaaS is a platform for building your own apps, like App Service."},
            {"stmt": "Even in SaaS, the customer remains responsible for its data, devices, and user identities.", "truth": True,
             "why": "Information and data, devices, and accounts/identities never transfer to the provider in any service model."},
        ],
    },
    {
        "a": "PaaS", "b": "Serverless computing",
        "def_a": "A managed application platform where you still choose a plan or tier that runs continuously",
        "def_b": "An execution model where code runs on demand, scales to zero when idle, and is billed per execution",
        "difference": "Both hide the OS, but PaaS keeps provisioned capacity running (you pick a plan and pay while it exists); serverless allocates resources only when events fire, scales to zero, and bills only for actual executions.",
        "scenarios": [
            {"stmt": "A function runs for 200 milliseconds whenever a file lands in storage and costs nothing the rest of the day.", "answer": "Serverless computing"},
            {"stmt": "The web app runs on a Standard-tier plan that is billed around the clock whether traffic arrives or not.", "answer": "PaaS"},
            {"stmt": "Billing is per execution, and idle time is free because capacity scales to zero.", "answer": "Serverless computing"},
            {"stmt": "You select an instance size and count for the hosting plan, but never touch the OS.", "answer": "PaaS"},
        ],
        "tf": [
            {"stmt": "In serverless computing there are literally no servers involved anywhere.", "truth": False,
             "why": "Servers still exist — the provider manages them entirely and invisibly; 'serverless' means you never provision or see them."},
            {"stmt": "Azure Functions can scale to zero, so no compute charges accrue while no events are firing.", "truth": True,
             "why": "Scale-to-zero and per-execution billing are the defining traits of the serverless model (Consumption plan)."},
        ],
    },
    # ---------------------------------------------- architecture: compute ---
    {
        "a": "Region", "b": "Availability zone",
        "def_a": "A geographic area containing one or more datacenters connected by a low-latency network",
        "def_b": "A physically separate group of datacenters within a region, with independent power, cooling, and networking",
        "difference": "A region is the geography you deploy into; availability zones are the isolated datacenter groups inside that region (minimum three where supported). Zones protect against datacenter failure; separate regions protect against regional disaster.",
        "scenarios": [
            {"stmt": "You pick 'East US' from a dropdown when creating the resource.", "answer": "Region"},
            {"stmt": "The VM tier is deployed across three physically separate facilities in the same geography, each with its own power and cooling.", "answer": "Availability zone"},
            {"stmt": "Choosing where in the world your data physically resides for compliance and latency.", "answer": "Region"},
            {"stmt": "Protection against the failure of an entire datacenter, while staying within the same geographic area.", "answer": "Availability zone"},
        ],
        "tf": [
            {"stmt": "An availability zone is a geographic area that may contain several regions.", "truth": False,
             "why": "It is the other way round: a region contains availability zones. Zones are isolated datacenter groups inside one region."},
            {"stmt": "Regions that support availability zones have a minimum of three separate zones.", "truth": True,
             "why": "Microsoft builds at least three zones in every zone-enabled region so workloads can survive a full zone outage."},
        ],
    },
    {
        "a": "Availability zone", "b": "Availability set",
        "def_a": "Physically separate datacenters within a region that protect workloads from a whole-datacenter failure",
        "def_b": "A logical grouping that spreads VMs across fault and update domains within a datacenter to survive rack failures and maintenance",
        "difference": "Availability sets protect you inside a single datacenter (different racks, staggered reboots); availability zones protect you across datacenters. Zones give the stronger 99.99% VM SLA versus 99.95% for sets.",
        "scenarios": [
            {"stmt": "Two VMs are placed on different racks with separate power and staggered maintenance reboots, all in the same building.", "answer": "Availability set"},
            {"stmt": "The database replicas run in three separate facilities miles apart within the region.", "answer": "Availability zone"},
            {"stmt": "This deployment survives the loss of an entire datacenter, including its power and cooling.", "answer": "Availability zone"},
            {"stmt": "This grouping distributes VMs across fault domains and update domains.", "answer": "Availability set"},
        ],
        "tf": [
            {"stmt": "An availability set protects your VMs if an entire datacenter loses power.", "truth": False,
             "why": "A set only spreads VMs across racks within one datacenter; surviving a whole-datacenter failure requires availability zones."},
            {"stmt": "Deploying VMs across availability zones carries a higher uptime SLA than using an availability set.", "truth": True,
             "why": "Zone-spread VMs get a 99.99% SLA; availability sets get 99.95%, because zones remove the single-datacenter risk."},
        ],
    },
    {
        "a": "Fault domain", "b": "Update domain",
        "def_a": "A group of hardware sharing a common power source and network switch — essentially a rack",
        "def_b": "A group of VMs that Azure reboots together during planned platform maintenance",
        "difference": "Fault domains isolate you from unplanned hardware failures (power/switch on a rack); update domains isolate you from planned maintenance reboots. Availability sets spread VMs across both.",
        "scenarios": [
            {"stmt": "A rack's power supply dies and takes down every host on it — but only one of your VMs was there.", "answer": "Fault domain"},
            {"stmt": "During planned platform maintenance, Azure reboots your VMs one group at a time so some always stay up.", "answer": "Update domain"},
            {"stmt": "The boundary defined by a shared power source and network switch.", "answer": "Fault domain"},
            {"stmt": "Only one of these groups is ever rebooted at a time, and Azure waits for it to recover before moving on.", "answer": "Update domain"},
        ],
        "tf": [
            {"stmt": "An update domain is a set of hardware that shares a single power source and network switch.", "truth": False,
             "why": "That describes a fault domain. Update domains group VMs that undergo planned maintenance reboots together."},
            {"stmt": "Availability sets place your VMs across multiple fault domains and multiple update domains automatically.", "truth": True,
             "why": "That spread is exactly what an availability set does, protecting against both hardware failure and maintenance."},
        ],
    },
    {
        "a": "Virtual Machine Scale Sets", "b": "Availability Sets",
        "def_a": "A service that deploys and automatically scales a group of identical, load-balanced VMs",
        "def_b": "A grouping that spreads individually managed VMs across fault and update domains for resilience, with no autoscaling",
        "difference": "Scale sets are for elasticity: identical VMs that grow and shrink automatically behind a load balancer. Availability sets are purely for resilience of a fixed set of (possibly different) VMs — they never change the VM count.",
        "scenarios": [
            {"stmt": "The web tier automatically grows from 5 to 40 identical instances during a traffic surge.", "answer": "Virtual Machine Scale Sets"},
            {"stmt": "Three differently configured VMs (app, database, utility) are spread across racks so maintenance never reboots them together.", "answer": "Availability Sets"},
            {"stmt": "Instances are stamped from the same image and automatically load balanced as they scale.", "answer": "Virtual Machine Scale Sets"},
            {"stmt": "The VM count never changes by itself; the feature only controls placement across fault and update domains.", "answer": "Availability Sets"},
        ],
        "tf": [
            {"stmt": "An availability set automatically increases the number of VMs when CPU load rises.", "truth": False,
             "why": "Availability sets never autoscale — that is what VM scale sets do. Sets only control placement for resilience."},
            {"stmt": "VM scale sets are built for identical instances, making them a natural fit for stateless web tiers.", "truth": True,
             "why": "All instances come from the same image and configuration, which suits horizontally scaled stateless workloads."},
        ],
    },
    {
        "a": "Azure Container Instances", "b": "Azure Kubernetes Service",
        "def_a": "The fastest way to run a single container on demand, with no servers or orchestrator to manage",
        "def_b": "A managed Kubernetes orchestrator for deploying, scaling, and operating fleets of containers",
        "difference": "ACI is for quick, simple, isolated containers — no orchestration, per-second billing. AKS is for many containers that need scheduling, self-healing, service discovery, and rolling upgrades at scale.",
        "scenarios": [
            {"stmt": "A one-off data-cleanup container needs to run for 20 minutes and disappear, with zero infrastructure setup.", "answer": "Azure Container Instances"},
            {"stmt": "A microservices platform of 60 containers needs automated scheduling, self-healing, and rolling upgrades.", "answer": "Azure Kubernetes Service"},
            {"stmt": "The team wants full orchestration — pods, services, and cluster autoscaling.", "answer": "Azure Kubernetes Service"},
            {"stmt": "The simplest possible way to get one container running in Azure right now.", "answer": "Azure Container Instances"},
        ],
        "tf": [
            {"stmt": "Azure Container Instances provides full container orchestration, including self-healing and rolling upgrades.", "truth": False,
             "why": "ACI runs containers without any orchestration; orchestration features belong to AKS."},
            {"stmt": "In AKS, Microsoft manages the Kubernetes control plane for you.", "truth": True,
             "why": "AKS is managed Kubernetes: Azure operates the control plane while you manage your node pools and workloads."},
        ],
    },
    {
        "a": "Containers", "b": "Virtual machines",
        "def_a": "Lightweight packages that virtualize the operating system, share the host kernel, and start in seconds",
        "def_b": "Full emulated computers that virtualize the hardware, each running its own complete guest operating system",
        "difference": "VMs virtualize hardware and each carries a whole OS you must patch; containers virtualize at the OS level, share the host kernel, and are far smaller and faster to start. Containers trade some isolation for density and agility.",
        "scenarios": [
            {"stmt": "Each instance boots a full copy of Windows Server that the ops team must patch monthly.", "answer": "Virtual machines"},
            {"stmt": "Dozens of isolated app instances share one host kernel and each starts in about a second.", "answer": "Containers"},
            {"stmt": "You need a completely different operating system kernel than the host for this workload.", "answer": "Virtual machines"},
            {"stmt": "The app ships as a small immutable image that runs identically on a laptop, a server, and in Azure.", "answer": "Containers"},
        ],
        "tf": [
            {"stmt": "Containers each include their own full guest operating system that must be patched separately.", "truth": False,
             "why": "That describes VMs. Containers share the host OS kernel and package only the app and its dependencies."},
            {"stmt": "Containers are generally more lightweight and faster to start than virtual machines.", "truth": True,
             "why": "With no guest OS to boot, containers start in seconds and pack more densely onto the same hardware."},
        ],
    },
    {
        "a": "Azure Functions", "b": "Azure Logic Apps",
        "def_a": "Serverless compute that runs your code in response to events — a code-first approach for developers",
        "def_b": "A serverless designer-first service that builds automated workflows from prebuilt connectors, with little or no code",
        "difference": "Both are serverless, but Functions executes code you write, while Logic Apps orchestrates workflows you assemble visually from hundreds of connectors. Developers write Functions; workflow builders (or the same developer!) draw Logic Apps.",
        "scenarios": [
            {"stmt": "A developer writes a C# method that thumbnails every image uploaded to Blob Storage.", "answer": "Azure Functions"},
            {"stmt": "A business analyst drags connectors onto a design surface: when a form arrives, add a SharePoint row and post to Teams.", "answer": "Azure Logic Apps"},
            {"stmt": "The solution is code-first and event-driven, billed per execution.", "answer": "Azure Functions"},
            {"stmt": "The integration chains SaaS services together using a gallery of prebuilt connectors and a visual designer.", "answer": "Azure Logic Apps"},
        ],
        "tf": [
            {"stmt": "Azure Logic Apps is a code-first service where you write functions in C# or Python.", "truth": False,
             "why": "Logic Apps is designer-first (visual workflows with connectors); writing event-driven code is Azure Functions."},
            {"stmt": "Both Azure Functions and Logic Apps are serverless offerings.", "truth": True,
             "why": "Neither requires provisioning servers — both scale on demand and bill on consumption."},
        ],
    },
    # ------------------------------------------- architecture: networking ---
    {
        "a": "Azure VPN Gateway", "b": "Azure ExpressRoute",
        "def_a": "An encrypted IPsec tunnel that connects on-premises networks to Azure over the public internet",
        "def_b": "A dedicated private circuit into Microsoft's network that never touches the public internet",
        "difference": "VPN Gateway rides the public internet inside an encrypted tunnel — cheaper, quicker to set up, but subject to internet variability. ExpressRoute is a private physical connection with higher bandwidth, consistency, and reliability.",
        "scenarios": [
            {"stmt": "Traffic between headquarters and Azure crosses the public internet, protected by IPsec encryption.", "answer": "Azure VPN Gateway"},
            {"stmt": "A bank orders a dedicated 10 Gbps circuit through a connectivity provider so its Azure traffic never touches the internet.", "answer": "Azure ExpressRoute"},
            {"stmt": "The branch office needs a secure connection to Azure by Friday, using its existing internet line.", "answer": "Azure VPN Gateway"},
            {"stmt": "The workload demands consistent latency and guaranteed private connectivity for regulatory reasons.", "answer": "Azure ExpressRoute"},
        ],
        "tf": [
            {"stmt": "ExpressRoute sends your traffic across the public internet inside an encrypted tunnel.", "truth": False,
             "why": "That is a VPN. ExpressRoute is a private dedicated connection that bypasses the public internet entirely."},
            {"stmt": "A site-to-site VPN is typically cheaper and faster to provision than ExpressRoute.", "truth": True,
             "why": "A VPN reuses existing internet connectivity; ExpressRoute requires provisioning a physical circuit with a provider."},
        ],
    },
    {
        "a": "Site-to-site VPN", "b": "Point-to-site VPN",
        "def_a": "A tunnel between an on-premises VPN device and Azure that connects an entire network to a VNet",
        "def_b": "A tunnel from an individual computer to Azure, connecting just that one device",
        "difference": "Site-to-site joins whole networks (office to Azure) through a VPN appliance; point-to-site connects a single client machine — ideal for remote workers who need access from anywhere.",
        "scenarios": [
            {"stmt": "Every server in the branch office can reach the VNet through the office firewall's always-on tunnel.", "answer": "Site-to-site VPN"},
            {"stmt": "A consultant working from a hotel connects her laptop's VPN client directly to the company VNet.", "answer": "Point-to-site VPN"},
            {"stmt": "The connection terminates on the datacenter's network appliance and serves the whole subnet behind it.", "answer": "Site-to-site VPN"},
            {"stmt": "Each remote employee starts the tunnel from their own device when they need it.", "answer": "Point-to-site VPN"},
        ],
        "tf": [
            {"stmt": "A point-to-site VPN connects an entire on-premises network to Azure through a VPN device.", "truth": False,
             "why": "Connecting a whole network via an appliance is site-to-site; point-to-site connects one individual computer."},
            {"stmt": "Point-to-site VPNs suit remote workers because no on-premises VPN hardware is required.", "truth": True,
             "why": "The client software on the user's device builds the tunnel, so travelers can connect from anywhere."},
        ],
    },
    {
        "a": "Virtual network peering", "b": "Azure VPN Gateway",
        "def_a": "Directly connecting two Azure virtual networks over the Microsoft backbone so they operate as one network",
        "def_b": "A gateway providing encrypted tunnels, chiefly to connect on-premises networks or clients to a VNet",
        "difference": "Peering is VNet-to-VNet inside Azure — private backbone traffic, no gateway, no internet. VPN Gateway's main job is bringing external networks (offices, laptops) into Azure over encrypted internet tunnels.",
        "scenarios": [
            {"stmt": "The hub VNet and three spoke VNets exchange traffic privately across Microsoft's backbone with no encryption devices involved.", "answer": "Virtual network peering"},
            {"stmt": "The Chicago office's network is joined to Azure through an encrypted IPsec tunnel.", "answer": "Azure VPN Gateway"},
            {"stmt": "Two VNets in different regions are linked so their VMs talk using private IPs, never crossing the public internet.", "answer": "Virtual network peering"},
            {"stmt": "Remote laptops establish encrypted tunnels into the VNet.", "answer": "Azure VPN Gateway"},
        ],
        "tf": [
            {"stmt": "Traffic between peered virtual networks travels across the public internet.", "truth": False,
             "why": "Peered VNet traffic stays on Microsoft's private backbone; it never touches the public internet."},
            {"stmt": "Virtual network peering can connect VNets that live in different Azure regions.", "truth": True,
             "why": "Global VNet peering links VNets across regions, still over the Microsoft backbone."},
        ],
    },
    {
        "a": "Network Security Group", "b": "Azure Firewall",
        "def_a": "Free, basic allow/deny rules filtering traffic by IP, port, and protocol, attached to subnets or NICs",
        "def_b": "A managed, centralized firewall service with advanced features like FQDN filtering and threat intelligence across VNets",
        "difference": "NSGs are simple 5-tuple packet filters you attach near the workload; Azure Firewall is a full managed firewall for centralized protection — application-level rules (FQDNs), threat intelligence, and unified logging. Many designs use both.",
        "scenarios": [
            {"stmt": "A rule on the subnet allows TCP 443 in and blocks everything else — configured in minutes at no cost.", "answer": "Network Security Group"},
            {"stmt": "All outbound traffic from every spoke VNet is forced through one central service that blocks known-malicious domains.", "answer": "Azure Firewall"},
            {"stmt": "Filtering is attached directly to a VM's network interface.", "answer": "Network Security Group"},
            {"stmt": "Rules allow outbound traffic only to *.windowsupdate.com by domain name.", "answer": "Azure Firewall"},
        ],
        "tf": [
            {"stmt": "A network security group can filter outbound traffic by fully qualified domain name using threat intelligence.", "truth": False,
             "why": "FQDN filtering and threat intelligence are Azure Firewall capabilities; NSGs filter only by IP, port, and protocol."},
            {"stmt": "NSGs can be associated with both subnets and individual network interfaces.", "truth": True,
             "why": "You can apply an NSG at the subnet level, the NIC level, or both — rules from both levels apply."},
        ],
    },
    {
        "a": "Public endpoint", "b": "Private endpoint",
        "def_a": "A service address reachable over the internet via a public IP",
        "def_b": "A private IP address inside your VNet that connects to a PaaS service, keeping traffic off the public internet",
        "difference": "A public endpoint exposes the service to the internet (even if secured); a private endpoint injects the service into your VNet with a private IP via Private Link so only your network can reach it.",
        "scenarios": [
            {"stmt": "The storage account answers at an address anyone on the internet can attempt to reach.", "answer": "Public endpoint"},
            {"stmt": "The SQL database gets the address 10.1.2.5 inside the VNet and is unreachable from the internet.", "answer": "Private endpoint"},
            {"stmt": "Compliance requires that traffic to the PaaS service never leave the private network.", "answer": "Private endpoint"},
            {"stmt": "Default connectivity for a newly created PaaS service, secured by keys and firewall rules but internet-facing.", "answer": "Public endpoint"},
        ],
        "tf": [
            {"stmt": "A private endpoint gives a PaaS service a public IP address so it can be reached from anywhere.", "truth": False,
             "why": "A private endpoint does the opposite: it assigns a private IP inside your VNet so the service is reached privately."},
            {"stmt": "Private endpoints use Azure Private Link to bring PaaS services into your virtual network.", "truth": True,
             "why": "Private Link is the underlying technology that maps the service to a private IP in your VNet."},
        ],
    },
    # ------------------------------------------------------------ storage ---
    {
        "a": "Locally redundant storage (LRS)", "b": "Zone-redundant storage (ZRS)",
        "def_a": "Three synchronous copies of your data within a single datacenter — the cheapest redundancy",
        "def_b": "Three synchronous copies spread across three availability zones in the primary region",
        "difference": "Both keep three copies in one region; LRS keeps them all in one datacenter (vulnerable to a datacenter disaster), while ZRS spreads them across zones so data survives a whole-datacenter failure.",
        "scenarios": [
            {"stmt": "All three copies of the data sit in the same building, and a fire there could destroy every copy.", "answer": "Locally redundant storage (LRS)"},
            {"stmt": "Each of the three copies lives in a different datacenter with independent power within the region.", "answer": "Zone-redundant storage (ZRS)"},
            {"stmt": "The lowest-cost redundancy option offered by Azure Storage.", "answer": "Locally redundant storage (LRS)"},
            {"stmt": "Data stays available for reads and writes even if one zone in the region goes down.", "answer": "Zone-redundant storage (ZRS)"},
        ],
        "tf": [
            {"stmt": "LRS protects your data against the failure of an entire datacenter.", "truth": False,
             "why": "All three LRS copies are in one datacenter; surviving a datacenter failure requires ZRS (or geo-redundant options)."},
            {"stmt": "Both LRS and ZRS keep exactly three copies of your data within the primary region.", "truth": True,
             "why": "The difference is placement: one datacenter for LRS versus three availability zones for ZRS."},
        ],
    },
    {
        "a": "Geo-redundant storage (GRS)", "b": "Geo-zone-redundant storage (GZRS)",
        "def_a": "LRS in the primary region plus three asynchronous copies in the secondary paired region — six copies total",
        "def_b": "ZRS in the primary region plus three asynchronous copies in the secondary paired region — six copies total",
        "difference": "Both replicate to a secondary region; the difference is the primary: GRS starts from LRS (one datacenter), GZRS starts from ZRS (three zones). GZRS is the maximum-durability option, protecting against zone AND regional failures.",
        "scenarios": [
            {"stmt": "In the primary region all three copies sit in a single datacenter, with three more copies in the paired region.", "answer": "Geo-redundant storage (GRS)"},
            {"stmt": "The primary region's copies are spread across three availability zones before replicating to the paired region.", "answer": "Geo-zone-redundant storage (GZRS)"},
            {"stmt": "Microsoft's recommended choice for applications needing maximum consistency, durability, and availability.", "answer": "Geo-zone-redundant storage (GZRS)"},
            {"stmt": "Cheaper geo-protection that still leaves the primary copies vulnerable to a single-datacenter disaster.", "answer": "Geo-redundant storage (GRS)"},
        ],
        "tf": [
            {"stmt": "GZRS uses LRS in the primary region and ZRS in the secondary region.", "truth": False,
             "why": "GZRS is ZRS in the primary plus LRS-style copies in the secondary. The zone-spreading happens in the primary region."},
            {"stmt": "Both GRS and GZRS maintain six total copies of your data across two regions.", "truth": True,
             "why": "Three copies in the primary (single datacenter for GRS, across zones for GZRS) plus three in the paired secondary."},
        ],
    },
    {
        "a": "Geo-redundant storage (GRS)", "b": "Read-access geo-redundant storage (RA-GRS)",
        "def_a": "Geo-replication where the secondary region's copy is unavailable unless Microsoft or you initiate failover",
        "def_b": "Geo-replication where you can read from the secondary region at any time, not just after failover",
        "difference": "Same six copies in two regions — the difference is access: with plain GRS the secondary is dormant until a failover; RA-GRS lets applications read (not write) from the secondary continuously.",
        "scenarios": [
            {"stmt": "A reporting app continuously reads data from the paired region's copy while the primary handles all writes.", "answer": "Read-access geo-redundant storage (RA-GRS)"},
            {"stmt": "The secondary copy exists purely as insurance and cannot be queried unless failover occurs.", "answer": "Geo-redundant storage (GRS)"},
            {"stmt": "The design requires the secondary endpoint to be readable even while the primary region is perfectly healthy.", "answer": "Read-access geo-redundant storage (RA-GRS)"},
            {"stmt": "Geo-protected storage at the lower price point, with no everyday access to the second region.", "answer": "Geo-redundant storage (GRS)"},
        ],
        "tf": [
            {"stmt": "With RA-GRS, applications can write to both the primary and secondary regions simultaneously.", "truth": False,
             "why": "RA-GRS adds read access to the secondary only; all writes still go to the primary region."},
            {"stmt": "With standard GRS, data in the secondary region is not readable unless a failover happens.", "truth": True,
             "why": "The secondary is standby-only in GRS; continuous read access is exactly what the RA- prefix adds."},
        ],
    },
    {
        "a": "Azure Blob Storage", "b": "Azure Files",
        "def_a": "Object storage for massive amounts of unstructured data, accessed over REST/HTTP with access tiers",
        "def_b": "Fully managed file shares mounted over SMB or NFS, appearing as a normal network drive",
        "difference": "Blobs are objects reached through URLs and APIs — ideal for images, backups, logs, and data lakes. Azure Files is a real file system with paths and locking that existing apps can mount like any network share.",
        "scenarios": [
            {"stmt": "A legacy app expects a mapped drive letter pointing to a shared folder, and it works unchanged in Azure.", "answer": "Azure Files"},
            {"stmt": "Millions of user-uploaded images are stored and served to browsers via URLs.", "answer": "Azure Blob Storage"},
            {"stmt": "Data is organized in containers and offers Hot, Cool, Cold, and Archive tiers.", "answer": "Azure Blob Storage"},
            {"stmt": "Multiple VMs and on-premises servers mount the same share over SMB simultaneously.", "answer": "Azure Files"},
        ],
        "tf": [
            {"stmt": "Azure Files stores unstructured objects that are accessed through REST APIs and organized in containers.", "truth": False,
             "why": "Objects in containers over REST describes Blob Storage. Azure Files provides SMB/NFS file shares with directories."},
            {"stmt": "Azure Files shares can be mounted concurrently from cloud VMs and on-premises machines.", "truth": True,
             "why": "SMB/NFS shares work like any network drive and can be mounted from both Azure and on-premises simultaneously."},
        ],
    },
    {
        "a": "Azure Files", "b": "Azure Managed Disks",
        "def_a": "Shared network file storage that many machines can mount at once over SMB or NFS",
        "def_b": "Block-level virtual hard disks attached to a virtual machine as its drives",
        "difference": "A managed disk is a VM's own hard drive (OS or data disk); Azure Files is a shared network location independent of any single VM. Disks belong to a machine; file shares are mounted by many.",
        "scenarios": [
            {"stmt": "The VM's operating system volume and its data volume D: are stored as virtual hard disks.", "answer": "Azure Managed Disks"},
            {"stmt": "Twenty machines all read and write the same shared folder of departmental documents.", "answer": "Azure Files"},
            {"stmt": "Block-level storage that behaves exactly like a physical drive inside one server.", "answer": "Azure Managed Disks"},
            {"stmt": "A lift-and-shift file server is replaced by a cloud share that clients access over SMB.", "answer": "Azure Files"},
        ],
        "tf": [
            {"stmt": "A managed disk is designed to be mounted simultaneously by dozens of VMs as shared folder storage.", "truth": False,
             "why": "Disks are block storage for a VM; shared concurrent file access is the role of Azure Files."},
            {"stmt": "Azure manages the storage infrastructure behind managed disks — you just pick the size and type.", "truth": True,
             "why": "That is the 'managed' part: no storage accounts to run; Azure handles placement, durability, and scaling."},
        ],
    },
    {
        "a": "Azure Queue Storage", "b": "Azure Table Storage",
        "def_a": "Storage for large numbers of small messages that lets application components communicate asynchronously",
        "def_b": "A NoSQL key/attribute store for large amounts of structured, non-relational data",
        "difference": "Queues hold messages waiting to be processed — decoupling producers from consumers. Tables hold data at rest as schemaless rows looked up by key. Queues are about communication; tables are about storage of structured records.",
        "scenarios": [
            {"stmt": "The web front end drops an order message that a background worker picks up and processes later.", "answer": "Azure Queue Storage"},
            {"stmt": "Millions of device-telemetry rows are stored schemalessly and fetched by partition and row key.", "answer": "Azure Table Storage"},
            {"stmt": "Two application components are decoupled so a burst of requests just makes the backlog longer instead of dropping work.", "answer": "Azure Queue Storage"},
            {"stmt": "A simple, cheap NoSQL store for user profile attributes that don't need relational joins.", "answer": "Azure Table Storage"},
        ],
        "tf": [
            {"stmt": "Azure Queue Storage is a NoSQL database for storing structured non-relational rows.", "truth": False,
             "why": "That describes Table Storage. Queue Storage stores messages passed between application components."},
            {"stmt": "Queues help applications scale by decoupling the component that creates work from the one that processes it.", "truth": True,
             "why": "Producers and consumers run independently; spikes queue up rather than overloading the processor."},
        ],
    },
    {
        "a": "Hot access tier", "b": "Cool access tier",
        "def_a": "Blob tier for frequently accessed data: highest storage cost, lowest access cost",
        "def_b": "Blob tier for infrequently accessed data stored at least 30 days: lower storage cost, higher access cost",
        "difference": "The tradeoff flips: hot charges more to store but little to access; cool charges less to store but more to read, with a 30-day minimum. Pick by how often the data is touched.",
        "scenarios": [
            {"stmt": "Product images served to customers thousands of times per hour.", "answer": "Hot access tier"},
            {"stmt": "Monthly invoices kept for occasional lookup, each retained at least 30 days.", "answer": "Cool access tier"},
            {"stmt": "The tier with the cheapest reads but the most expensive storage per GB.", "answer": "Hot access tier"},
            {"stmt": "Short-term backups accessed rarely, where storage price matters more than read price.", "answer": "Cool access tier"},
        ],
        "tf": [
            {"stmt": "The cool tier has higher storage costs and lower access costs than the hot tier.", "truth": False,
             "why": "It is the reverse: cool storage is cheaper to keep but costs more to access; hot is the opposite."},
            {"stmt": "Data in the cool tier is expected to remain there for at least 30 days.", "truth": True,
             "why": "Cool has a 30-day minimum retention; deleting or moving earlier incurs an early-deletion charge."},
        ],
    },
    {
        "a": "Cold access tier", "b": "Archive access tier",
        "def_a": "An online tier for rarely accessed data stored at least 90 days — still readable instantly",
        "def_b": "An offline tier for data stored at least 180 days that must be rehydrated for hours before it can be read",
        "difference": "Cold is still online — reads work immediately, just at a higher access price. Archive takes blobs offline at the lowest storage price; retrieving one requires rehydration that can take hours.",
        "scenarios": [
            {"stmt": "Compliance data that is almost never read, but when auditors ask, it must open immediately.", "answer": "Cold access tier"},
            {"stmt": "Seven-year retention records where waiting several hours for retrieval is perfectly acceptable.", "answer": "Archive access tier"},
            {"stmt": "The blob must be rehydrated to an online tier before it can be read at all.", "answer": "Archive access tier"},
            {"stmt": "Rarely used data with a 90-day minimum that stays instantly available.", "answer": "Cold access tier"},
        ],
        "tf": [
            {"stmt": "Data in the archive tier can be read instantly, just at a higher access cost.", "truth": False,
             "why": "Archive is offline; blobs must first be rehydrated (which can take hours). Instant reads at higher cost describes cool/cold."},
            {"stmt": "Archive offers the lowest storage cost of all the blob access tiers.", "truth": True,
             "why": "Archive trades accessibility for price — the cheapest per-GB storage in exchange for offline, hours-long retrieval."},
        ],
    },
    {
        "a": "Azure Data Box", "b": "AzCopy",
        "def_a": "A rugged physical appliance Microsoft ships to you for offline transfer of very large datasets (around 80 TB)",
        "def_b": "A command-line tool that copies blobs and files to or from storage accounts over the network",
        "difference": "Data Box moves data by truck — for huge datasets or sites with poor bandwidth. AzCopy moves data over the wire — scriptable day-to-day transfers. Rule of thumb: if the internet transfer would take weeks, ship a box.",
        "scenarios": [
            {"stmt": "A studio must move 70 TB from a site with a slow uplink, so Microsoft ships a sealed device to load and return.", "answer": "Azure Data Box"},
            {"stmt": "A nightly script pushes the day's export files into a blob container over the internet.", "answer": "AzCopy"},
            {"stmt": "Data physically travels through a shipping carrier rather than over the network.", "answer": "Azure Data Box"},
            {"stmt": "An engineer types one command in the terminal to sync a local folder with a container.", "answer": "AzCopy"},
        ],
        "tf": [
            {"stmt": "AzCopy is a physical appliance used for offline bulk data transfer into Azure.", "truth": False,
             "why": "The physical appliance is Data Box. AzCopy is a command-line utility that transfers data over the network."},
            {"stmt": "Data Box makes sense when network transfer of a dataset would take too long or bandwidth is limited.", "truth": True,
             "why": "Offline shipment beats the wire when datasets are huge or connectivity is poor — that is Data Box's purpose."},
        ],
    },
    # -------------------------------------------------- identity/security ---
    {
        "a": "Authentication", "b": "Authorization",
        "def_a": "Proving who you are — verifying an identity with credentials like passwords, biometrics, or tokens",
        "def_b": "Determining what an authenticated identity is allowed to do — its permissions and access level",
        "difference": "Authentication (AuthN) is the identity check at the door; authorization (AuthZ) decides which rooms you may enter once inside. AuthN always comes first; RBAC is Azure's main authorization system.",
        "scenarios": [
            {"stmt": "A user signs in with a password and then approves the push notification on her phone.", "answer": "Authentication"},
            {"stmt": "The system checks whether the signed-in user holds the Contributor role before allowing the VM to be deleted.", "answer": "Authorization"},
            {"stmt": "Verifying a fingerprint matches the registered identity.", "answer": "Authentication"},
            {"stmt": "Deciding that the finance group can read the reports folder but cannot modify it.", "answer": "Authorization"},
        ],
        "tf": [
            {"stmt": "Authorization is the process of verifying a user's identity with credentials such as a password.", "truth": False,
             "why": "Verifying identity is authentication. Authorization determines what the verified identity is permitted to do."},
            {"stmt": "Authentication must happen before authorization can take place.", "truth": True,
             "why": "You cannot decide what someone may do until you know who they are."},
        ],
    },
    {
        "a": "Microsoft Entra ID", "b": "Active Directory Domain Services",
        "def_a": "Microsoft's cloud-based identity and access management service, using modern protocols and features like MFA and Conditional Access",
        "def_b": "The traditional on-premises directory running on domain controllers, using Kerberos/NTLM and Group Policy",
        "difference": "Entra ID is cloud-native IAM (OAuth/SAML/OpenID Connect, SSO to thousands of SaaS apps, Conditional Access); AD DS is the on-premises domain world of domain controllers, Kerberos, LDAP, and GPOs. They can be synchronized but are not the same product.",
        "scenarios": [
            {"stmt": "Users get single sign-on to Microsoft 365 and thousands of SaaS apps, protected by Conditional Access policies.", "answer": "Microsoft Entra ID"},
            {"stmt": "Domain controllers in the server room authenticate desktops with Kerberos and push settings via Group Policy.", "answer": "Active Directory Domain Services"},
            {"stmt": "The identity platform formerly known as Azure Active Directory.", "answer": "Microsoft Entra ID"},
            {"stmt": "Legacy applications require LDAP and domain-join to a traditional domain.", "answer": "Active Directory Domain Services"},
        ],
        "tf": [
            {"stmt": "Microsoft Entra ID is simply the marketing name for on-premises domain controllers running in Azure VMs.", "truth": False,
             "why": "Entra ID is a distinct cloud-native identity service using modern protocols — not hosted domain controllers (that would be running AD DS on IaaS, or Entra Domain Services)."},
            {"stmt": "An organization can synchronize its on-premises AD DS identities into Microsoft Entra ID for a hybrid identity setup.", "truth": True,
             "why": "Entra Connect synchronizes on-premises directory identities to the cloud so users sign in everywhere with one identity."},
        ],
    },
    {
        "a": "Single sign-on (SSO)", "b": "Multifactor authentication (MFA)",
        "def_a": "Signing in once with one identity to access multiple applications without re-entering credentials",
        "def_b": "Requiring two or more kinds of proof — something you know, have, or are — before granting sign-in",
        "difference": "SSO is about convenience and fewer credentials (one sign-in, many apps); MFA is about security strength (extra proof at sign-in). They complement each other: one strong MFA-protected sign-in unlocking all apps.",
        "scenarios": [
            {"stmt": "After one morning sign-in, the user opens email, the CRM, and the HR portal without seeing another login prompt.", "answer": "Single sign-on (SSO)"},
            {"stmt": "The sign-in requires a password plus a six-digit code from an authenticator app.", "answer": "Multifactor authentication (MFA)"},
            {"stmt": "Something you know combined with something you have.", "answer": "Multifactor authentication (MFA)"},
            {"stmt": "IT reduces password fatigue by letting one corporate identity open every SaaS app.", "answer": "Single sign-on (SSO)"},
        ],
        "tf": [
            {"stmt": "Single sign-on means users must provide a second verification factor for every application they open.", "truth": False,
             "why": "SSO is the opposite — sign in once, access many apps. Extra verification factors are MFA."},
            {"stmt": "Using a password plus a fingerprint counts as multifactor authentication.", "truth": True,
             "why": "Those are two different factor types: something you know and something you are."},
        ],
    },
    {
        "a": "Conditional Access", "b": "Multifactor authentication (MFA)",
        "def_a": "A policy engine that evaluates signals — user, location, device, risk — and then allows, blocks, or challenges the sign-in",
        "def_b": "The additional verification challenge itself, such as an authenticator code or phone approval",
        "difference": "Conditional Access is the if-then brain deciding what a sign-in requires based on context; MFA is one of the actions it can demand. Example: 'if outside the corporate network, then require MFA.'",
        "scenarios": [
            {"stmt": "Sign-ins from the office proceed normally, but sign-ins from unfamiliar countries are blocked outright.", "answer": "Conditional Access"},
            {"stmt": "The user taps Approve in the Microsoft Authenticator app to finish signing in.", "answer": "Multifactor authentication (MFA)"},
            {"stmt": "A rule requires extra verification only when the device is unmanaged or the sign-in looks risky.", "answer": "Conditional Access"},
            {"stmt": "The second proof of identity after the password — a code, push approval, or hardware key.", "answer": "Multifactor authentication (MFA)"},
        ],
        "tf": [
            {"stmt": "Conditional Access and MFA are two names for the same Azure feature.", "truth": False,
             "why": "Conditional Access is the policy engine that decides when to demand controls; MFA is one control it can require."},
            {"stmt": "A Conditional Access policy can require MFA only when a sign-in comes from outside trusted locations.", "truth": True,
             "why": "Location is one of the signals; policies commonly skip MFA on the corporate network and require it elsewhere."},
        ],
    },
    {
        "a": "Role-based access control (RBAC)", "b": "Conditional Access",
        "def_a": "Authorization that grants identities specific permissions (roles) over Azure resources at a chosen scope",
        "def_b": "Sign-in-time access control that allows, blocks, or challenges authentication based on signals",
        "difference": "Conditional Access governs whether and how you get in (authentication time); RBAC governs what you can do once you're in (authorization on resources). Different gates at different moments.",
        "scenarios": [
            {"stmt": "Maria can restart VMs in the dev resource group but cannot touch production, because of the role assigned to her.", "answer": "Role-based access control (RBAC)"},
            {"stmt": "Sign-ins from jailbroken phones are refused before any resource is ever touched.", "answer": "Conditional Access"},
            {"stmt": "Granting the Reader role at the subscription scope.", "answer": "Role-based access control (RBAC)"},
            {"stmt": "Requiring a compliant, managed device before allowing access to company apps.", "answer": "Conditional Access"},
        ],
        "tf": [
            {"stmt": "RBAC policies evaluate sign-in risk and device state to decide whether to allow authentication.", "truth": False,
             "why": "Signal evaluation at sign-in is Conditional Access. RBAC assigns resource permissions to identities at a scope."},
            {"stmt": "RBAC roles can be assigned at management group, subscription, resource group, or individual resource scope.", "truth": True,
             "why": "RBAC follows the Azure scope hierarchy, and assignments inherit downward from where they are granted."},
        ],
    },
    {
        "a": "Azure DDoS Protection", "b": "Azure Firewall",
        "def_a": "A service that absorbs and mitigates massive volumetric traffic floods aimed at overwhelming your applications",
        "def_b": "A managed service that filters network traffic with centralized allow/deny rules, FQDN filtering, and threat intelligence",
        "difference": "DDoS Protection defends availability against flood attacks at the network edge; Azure Firewall enforces which traffic is allowed to flow at all. One fights volume, the other enforces policy.",
        "scenarios": [
            {"stmt": "Millions of junk requests per second from a botnet are absorbed before they can take the site down.", "answer": "Azure DDoS Protection"},
            {"stmt": "Outbound traffic is denied by default and allowed only to an approved list of destinations and domains.", "answer": "Azure Firewall"},
            {"stmt": "The attack's goal is to exhaust capacity so legitimate users cannot get through.", "answer": "Azure DDoS Protection"},
            {"stmt": "A central rule set inspects and filters traffic flowing between VNets and the internet.", "answer": "Azure Firewall"},
        ],
        "tf": [
            {"stmt": "Azure Firewall's primary purpose is to absorb large-scale volumetric traffic-flood attacks.", "truth": False,
             "why": "Flood mitigation is DDoS Protection's job. Azure Firewall filters and controls traffic according to rules."},
            {"stmt": "DDoS attacks aim to exhaust an application's resources so real users cannot reach it.", "truth": True,
             "why": "Denial of service is an attack on availability — overwhelming capacity with junk traffic."},
        ],
    },
    # ------------------------------------------- management & governance ---
    {
        "a": "Azure Policy", "b": "Role-based access control (RBAC)",
        "def_a": "A governance service that enforces rules about what resources can be created and how they must be configured",
        "def_b": "An authorization system that controls which identities can perform which actions on resources",
        "difference": "RBAC controls WHO can do things; Policy controls WHAT things can exist and how they're configured — and Policy applies even to users with full RBAC rights. 'No public IPs allowed' is Policy; 'Bob can create VMs' is RBAC.",
        "scenarios": [
            {"stmt": "Every deployed resource must carry a CostCenter tag, and non-compliant resources are flagged — no matter who creates them.", "answer": "Azure Policy"},
            {"stmt": "The helpdesk team receives rights to restart VMs but not to delete them.", "answer": "Role-based access control (RBAC)"},
            {"stmt": "Deployments outside the West Europe region are denied for everyone, including subscription owners.", "answer": "Azure Policy"},
            {"stmt": "A new engineer is granted Contributor on the dev resource group.", "answer": "Role-based access control (RBAC)"},
        ],
        "tf": [
            {"stmt": "A user with the Owner role is exempt from Azure Policy restrictions.", "truth": False,
             "why": "Policy evaluates resource operations regardless of the caller's RBAC rights — even Owners cannot deploy non-compliant resources where a deny policy applies."},
            {"stmt": "Azure Policy can automatically remediate certain non-compliant resources, not just report them.", "truth": True,
             "why": "Policies with modify/deployIfNotExists effects can bring resources into compliance automatically."},
        ],
    },
    {
        "a": "Policy definition", "b": "Initiative",
        "def_a": "A single rule that evaluates resources, such as requiring a tag or restricting locations",
        "def_b": "A group of related policy definitions assigned and tracked together toward a larger goal",
        "difference": "A policy is one rule; an initiative bundles many policies so you assign and monitor them as a unit — like the dozens of policies that together track a regulatory compliance standard.",
        "scenarios": [
            {"stmt": "One rule: storage accounts must disable public blob access.", "answer": "Policy definition"},
            {"stmt": "A bundle of 40 related rules is assigned in one step to track an ISO 27001 compliance goal.", "answer": "Initiative"},
            {"stmt": "Compliance for a whole security standard is monitored as a single assignment in the portal.", "answer": "Initiative"},
            {"stmt": "The smallest unit of governance: a single evaluatable rule.", "answer": "Policy definition"},
        ],
        "tf": [
            {"stmt": "An initiative is a single rule that checks one specific resource setting.", "truth": False,
             "why": "A single rule is a policy definition; an initiative is a collection of policy definitions grouped toward a goal."},
            {"stmt": "Assigning one initiative can apply dozens of policies at a scope in a single operation.", "truth": True,
             "why": "That is the point of initiatives: manage many related policies as one assignment with combined compliance reporting."},
        ],
    },
    {
        "a": "Resource locks", "b": "Role-based access control (RBAC)",
        "def_a": "A safety switch on a resource, group, or subscription that blocks deletion or modification for everyone until removed",
        "def_b": "Permission assignments that define what each identity is allowed to do",
        "difference": "RBAC is per-identity permission management; a lock is a blanket safeguard that overrides everyone's permissions — even Owners must consciously remove the lock before deleting. Locks protect against accidents, not attackers.",
        "scenarios": [
            {"stmt": "Even the subscription Owner gets an error deleting the production database until a safeguard is removed first.", "answer": "Resource locks"},
            {"stmt": "Interns can view resources but every change attempt is denied because of their assigned role.", "answer": "Role-based access control (RBAC)"},
            {"stmt": "A two-step 'remove the guard, then delete' process protects the critical VNet from accidental deletion.", "answer": "Resource locks"},
            {"stmt": "Access reviews confirm each team holds only the permissions its job requires.", "answer": "Role-based access control (RBAC)"},
        ],
        "tf": [
            {"stmt": "A user with the Owner role can delete a locked resource directly because RBAC overrides locks.", "truth": False,
             "why": "Locks apply regardless of RBAC. Even an Owner must remove the lock first — that deliberate extra step is the feature."},
            {"stmt": "Resource locks primarily protect against accidental deletion or modification, not against malicious insiders.", "truth": True,
             "why": "Anyone with sufficient rights can remove the lock; its value is forcing a conscious step that prevents accidents."},
        ],
    },
    {
        "a": "Tags", "b": "Resource groups",
        "def_a": "Name/value metadata attached to resources for organizing, filtering, and cost reporting across any boundary",
        "def_b": "Logical containers that hold resources sharing a lifecycle — deleting the container deletes everything in it",
        "difference": "A resource lives in exactly ONE resource group but can carry MANY tags. Groups define lifecycle and management boundaries; tags cut across them for searching, billing rollups, and ownership metadata.",
        "scenarios": [
            {"stmt": "Finance breaks down the monthly bill by CostCenter values attached to resources across every subscription.", "answer": "Tags"},
            {"stmt": "When the pilot project ends, one delete operation removes all fifteen of its resources at once.", "answer": "Resource groups"},
            {"stmt": "A resource can carry many of these at the same time — environment, owner, department.", "answer": "Tags"},
            {"stmt": "Every resource must belong to exactly one of these.", "answer": "Resource groups"},
        ],
        "tf": [
            {"stmt": "A resource can belong to several resource groups at the same time.", "truth": False,
             "why": "A resource lives in exactly one resource group. If you need cross-cutting classification, that is what tags are for."},
            {"stmt": "Deleting a resource group deletes every resource contained in it.", "truth": True,
             "why": "The group defines a shared lifecycle — its deletion cascades to all members, which is both its power and its danger."},
        ],
    },
    {
        "a": "Management group", "b": "Subscription",
        "def_a": "A container above subscriptions used to apply governance — policy and access — across many subscriptions at once",
        "def_b": "A billing and access boundary that contains resource groups and their resources",
        "difference": "Management groups organize and govern subscriptions (policies and RBAC assigned there inherit downward); a subscription is the unit of billing and a boundary for resources. Hierarchy: management groups → subscriptions → resource groups → resources.",
        "scenarios": [
            {"stmt": "One policy assignment forces MFA requirements across all 30 of the company's subscriptions at once.", "answer": "Management group"},
            {"stmt": "Each department receives its own separate monthly invoice boundary for its Azure usage.", "answer": "Subscription"},
            {"stmt": "The container that sits directly above subscriptions in the Azure hierarchy.", "answer": "Management group"},
            {"stmt": "Creating any resource requires having at least one of these to put it under.", "answer": "Subscription"},
        ],
        "tf": [
            {"stmt": "A subscription is a container used to group and govern multiple management groups.", "truth": False,
             "why": "The hierarchy is the other way: management groups contain subscriptions, not vice versa."},
            {"stmt": "Policies assigned at a management group are inherited by every subscription beneath it.", "truth": True,
             "why": "Inheritance flows down the hierarchy: management group assignments cascade to child subscriptions and their resources."},
        ],
    },
    {
        "a": "Subscription", "b": "Resource group",
        "def_a": "The billing and access boundary that contains resource groups; usage is invoiced per this unit",
        "def_b": "A logical container inside a subscription that groups resources sharing a lifecycle",
        "difference": "Subscriptions are the billing/account boundary; resource groups organize resources within a subscription for shared lifecycle and management. A resource group belongs to exactly one subscription.",
        "scenarios": [
            {"stmt": "The company separates production and development billing by giving each its own boundary with its own invoice.", "answer": "Subscription"},
            {"stmt": "All the components of one application — VM, database, VNet — are grouped so they can be managed and deleted together.", "answer": "Resource group"},
            {"stmt": "Offers like pay-as-you-go or Enterprise Agreement apply at this level.", "answer": "Subscription"},
            {"stmt": "The container you pick in the portal right before naming a new resource.", "answer": "Resource group"},
        ],
        "tf": [
            {"stmt": "A resource group can span multiple subscriptions.", "truth": False,
             "why": "A resource group lives inside exactly one subscription (though its resources can be in different regions)."},
            {"stmt": "A resource group's resources can reside in different Azure regions than the group itself.", "truth": True,
             "why": "The group's location only stores its metadata; member resources can be deployed to any region."},
        ],
    },
    {
        "a": "Azure Advisor", "b": "Azure Monitor",
        "def_a": "A free consultant that analyzes your resources and recommends improvements for cost, security, reliability, performance, and operational excellence",
        "def_b": "The platform that collects, analyzes, and acts on metrics and logs from your resources — dashboards, alerts, and insights",
        "difference": "Advisor gives you recommendations (what you should change); Monitor gives you telemetry (what is happening right now and historically). Advisor advises; Monitor observes and alerts.",
        "scenarios": [
            {"stmt": "The portal suggests resizing three underused VMs to save an estimated $400 a month.", "answer": "Azure Advisor"},
            {"stmt": "A chart shows CPU utilization over the last 24 hours, and an alert fires when it crosses 90%.", "answer": "Azure Monitor"},
            {"stmt": "Recommendations are organized into five categories including cost and reliability.", "answer": "Azure Advisor"},
            {"stmt": "Metrics and logs from every resource flow into one place for dashboards and alert rules.", "answer": "Azure Monitor"},
        ],
        "tf": [
            {"stmt": "Azure Advisor's main job is collecting metrics and logs from your resources for dashboards and alerts.", "truth": False,
             "why": "Telemetry collection and alerting is Azure Monitor. Advisor analyzes your setup and offers recommendations."},
            {"stmt": "Azure Advisor recommendations cover cost, security, reliability, performance, and operational excellence.", "truth": True,
             "why": "Those are Advisor's five recommendation categories."},
        ],
    },
    {
        "a": "Azure Monitor", "b": "Azure Service Health",
        "def_a": "Telemetry about YOUR resources — their metrics, logs, performance, and alerts",
        "def_b": "Status of the AZURE PLATFORM itself — outages, planned maintenance, and health advisories affecting your regions and services",
        "difference": "Monitor watches your stuff; Service Health watches Microsoft's platform. 'My VM's CPU is high' is Monitor; 'Azure Storage is having an incident in East US' is Service Health.",
        "scenarios": [
            {"stmt": "A dashboard tracks your web app's response times and memory usage.", "answer": "Azure Monitor"},
            {"stmt": "A notice warns of upcoming planned maintenance affecting VMs in your region next weekend.", "answer": "Azure Service Health"},
            {"stmt": "Microsoft reports a platform outage impacting a service you rely on in West Europe.", "answer": "Azure Service Health"},
            {"stmt": "An alert rule you configured fires because your database's DTU usage exceeded the threshold.", "answer": "Azure Monitor"},
        ],
        "tf": [
            {"stmt": "Azure Service Health is where you view your own application's CPU and memory metrics.", "truth": False,
             "why": "Your resources' metrics live in Azure Monitor. Service Health reports the Azure platform's incidents and maintenance."},
            {"stmt": "Azure Service Health can alert you about planned maintenance before it affects your resources.", "truth": True,
             "why": "Service Health covers incidents, planned maintenance, and advisories relevant to your subscriptions and regions."},
        ],
    },
    {
        "a": "Azure Service Health", "b": "Resource Health",
        "def_a": "Platform-wide view of Azure incidents, planned maintenance, and advisories affecting your regions and services",
        "def_b": "The health of one specific resource instance — for example, whether YOUR individual VM is up, and why it rebooted",
        "difference": "Service Health is the wide-angle lens (is Azure having a problem?); Resource Health zooms into a single resource (is THIS VM healthy, and was that downtime caused by Azure?). Resource Health is part of the Service Health experience.",
        "scenarios": [
            {"stmt": "A region-wide storage incident is posted, listing every affected service.", "answer": "Azure Service Health"},
            {"stmt": "The blade shows your specific VM was unavailable for 6 minutes yesterday due to a platform-initiated repair.", "answer": "Resource Health"},
            {"stmt": "Checking whether a single database instance's current status is Available or Degraded.", "answer": "Resource Health"},
            {"stmt": "Advisories about upcoming changes to Azure services you use across your subscriptions.", "answer": "Azure Service Health"},
        ],
        "tf": [
            {"stmt": "Resource Health reports region-wide Azure outages affecting all customers.", "truth": False,
             "why": "Region-wide platform incidents are Service Health's domain; Resource Health covers the status of your individual resource."},
            {"stmt": "Resource Health can tell you whether your VM's downtime was caused by an Azure platform event.", "truth": True,
             "why": "It distinguishes platform-initiated events (like host repairs) from issues inside your own configuration."},
        ],
    },
    {
        "a": "Log Analytics", "b": "Application Insights",
        "def_a": "The Azure Monitor workspace and tool where you write KQL queries against collected log data",
        "def_b": "The Azure Monitor feature that instruments live applications to track requests, response times, failures, and dependencies",
        "difference": "Both live under Azure Monitor: Log Analytics is the general-purpose log store and query tool (KQL); Application Insights is application performance monitoring (APM) — telemetry from inside your running app. App Insights data can be queried in Log Analytics.",
        "scenarios": [
            {"stmt": "An engineer writes a KQL query joining VM heartbeat logs with security events.", "answer": "Log Analytics"},
            {"stmt": "The dashboard shows the web app's average response time, failed request rate, and slowest dependency calls.", "answer": "Application Insights"},
            {"stmt": "Instrumenting a live web application to trace individual user requests through its services.", "answer": "Application Insights"},
            {"stmt": "The central workspace where diagnostic logs from many resources are collected for querying.", "answer": "Log Analytics"},
        ],
        "tf": [
            {"stmt": "Application Insights is primarily a tool for writing KQL queries against infrastructure logs.", "truth": False,
             "why": "KQL querying of collected logs is Log Analytics. Application Insights is APM for live applications."},
            {"stmt": "Both Log Analytics and Application Insights are features of Azure Monitor.", "truth": True,
             "why": "Azure Monitor is the umbrella; Log Analytics handles log querying and Application Insights handles app telemetry."},
        ],
    },
    {
        "a": "ARM templates", "b": "Bicep",
        "def_a": "JSON files that declaratively define the infrastructure to deploy through Azure Resource Manager",
        "def_b": "A simpler domain-specific language for the same declarative deployments, which transpiles to ARM JSON",
        "difference": "Same engine, different syntax: ARM templates are verbose JSON; Bicep is a cleaner, human-friendly language that compiles down to ARM JSON. Both are declarative infrastructure as code with repeatable, idempotent results.",
        "scenarios": [
            {"stmt": "The infrastructure definition is raw JSON with nested brackets, parameters, and functions.", "answer": "ARM templates"},
            {"stmt": "The team switched to a cleaner syntax that reads almost like a scripting language and compiles to JSON.", "answer": "Bicep"},
            {"stmt": "The native template format Azure Resource Manager consumes directly.", "answer": "ARM templates"},
            {"stmt": "A newer language designed to make Azure IaC easier to read and write than JSON.", "answer": "Bicep"},
        ],
        "tf": [
            {"stmt": "Bicep uses an imperative approach, listing step-by-step commands to run, unlike declarative ARM templates.", "truth": False,
             "why": "Bicep is just as declarative as ARM JSON — you describe the desired end state; Bicep is only a friendlier syntax."},
            {"stmt": "Deploying the same declarative template repeatedly produces the same environment (idempotence).", "truth": True,
             "why": "Declarative IaC describes the goal state, so repeat deployments converge on the same result instead of duplicating."},
        ],
    },
    {
        "a": "Pricing calculator", "b": "TCO calculator",
        "def_a": "Estimates the monthly cost of the Azure resources you plan to deploy",
        "def_b": "Compares the full cost of running on-premises infrastructure against Azure to project multi-year savings",
        "difference": "Pricing calculator answers 'what will my Azure bill be?'; the Total Cost of Ownership calculator answers 'what would I save by migrating?' — it includes on-premises costs like power, space, and IT labor.",
        "scenarios": [
            {"stmt": "An architect prices out 4 VMs, a database, and storage to forecast next month's Azure bill.", "answer": "Pricing calculator"},
            {"stmt": "A report shows the company would save $2M over five years by closing its datacenter, counting electricity and admin labor.", "answer": "TCO calculator"},
            {"stmt": "You enter your current on-premises servers, storage, and networking to model migration savings.", "answer": "TCO calculator"},
            {"stmt": "Estimating the monthly cost of a planned new Azure workload before deploying it.", "answer": "Pricing calculator"},
        ],
        "tf": [
            {"stmt": "The TCO calculator estimates the monthly bill for a set of Azure services you are about to deploy.", "truth": False,
             "why": "Monthly Azure estimates come from the pricing calculator; TCO compares on-premises costs to Azure over years."},
            {"stmt": "The TCO calculator accounts for on-premises costs like electricity, datacenter space, and IT labor.", "truth": True,
             "why": "Those hidden ownership costs are exactly what a total-cost-of-ownership comparison includes."},
        ],
    },
    {
        "a": "CanNotDelete lock", "b": "ReadOnly lock",
        "def_a": "A lock that allows reading and modifying a resource but blocks deleting it",
        "def_b": "A lock that allows only reading — both modification and deletion are blocked",
        "difference": "CanNotDelete still lets teams change settings — it only stops deletion. ReadOnly freezes the resource entirely (which can surprise you: even some 'read-like' operations that require write access will fail).",
        "scenarios": [
            {"stmt": "Admins can still resize the VM and change its tags, but attempts to delete it fail.", "answer": "CanNotDelete lock"},
            {"stmt": "Every change attempt fails — the resource is effectively frozen in its current configuration.", "answer": "ReadOnly lock"},
            {"stmt": "The stricter lock level of the two.", "answer": "ReadOnly lock"},
            {"stmt": "Configuration updates continue as normal; only removal of the resource is blocked.", "answer": "CanNotDelete lock"},
        ],
        "tf": [
            {"stmt": "A CanNotDelete lock prevents all modifications to a resource's configuration.", "truth": False,
             "why": "CanNotDelete blocks only deletion; blocking modifications too is what ReadOnly does."},
            {"stmt": "A ReadOnly lock blocks both modifying and deleting the locked resource.", "truth": True,
             "why": "ReadOnly is the stricter level: the resource can be read but nothing about it can change."},
        ],
    },
]
