TOPIC = {
    "id": "1.1",
    "domain": 1,
    "title": "Compare and contrast various types of security controls.",
    "short": "Security Controls",
}

TERMS = [
    ("Security control", "Any safeguard or countermeasure that reduces risk to systems, data, or facilities; classified by category (who/how implemented) and type (what it does)"),
    ("Control category", "How a control is implemented: Technical (systems), Managerial (oversight/policy), Operational (people/processes), or Physical (real-world barriers)"),
    ("Control type", "The function/goal of a control: Preventive, Deterrent, Detective, Corrective, Compensating, or Directive"),
    ("Technical control", "Control implemented by hardware or software systems: firewalls, encryption, antivirus, ACLs, authentication mechanisms"),
    ("Managerial control", "Administrative control focused on security governance, oversight, and planning: policies, risk assessments, standard operating procedures"),
    ("Operational control", "Control carried out by people in day-to-day operations: security awareness training, log reviews by staff, incident response activities"),
    ("Physical control", "Control that limits physical access to facilities and equipment: fences, locks, bollards, lighting, badge readers, access control vestibules"),
    ("Preventive control", "Control that blocks or stops an unwanted event before it happens, e.g., a locked door, firewall rule, or account lockout"),
    ("Deterrent control", "Control that discourages an attacker from attempting an intrusion but does not directly block it, e.g., warning signs or visible cameras"),
    ("Detective control", "Control that identifies and records an event during or after it occurs, e.g., IDS alerts, log review, motion sensors, camera footage"),
    ("Corrective control", "Control applied after an incident to reverse damage or restore normal operations, e.g., restoring from backup or using a fire extinguisher"),
    ("Compensating control", "Alternative control used when the primary/required control is not feasible, providing similar protection by other means, e.g., segmentation for an unpatchable system"),
    ("Directive control", "Control that directs or compels behavior toward secure practices through policy, procedure, or instruction, e.g., an acceptable use policy"),
    ("Acceptable use policy (AUP)", "Document defining how employees may use company systems and data; a classic directive control that users acknowledge and sign"),
    ("Access control list (ACL)", "Technical rule set on firewalls, routers, or file systems that permits or denies access; a preventive technical control"),
    ("Intrusion detection system (IDS)", "Technical control that monitors traffic and generates alerts on suspicious activity; detective because it identifies but does not block"),
    ("Intrusion prevention system (IPS)", "Technical control placed inline that detects and actively blocks malicious traffic in real time; preventive in function"),
    ("Access control vestibule", "Physical control (formerly mantrap) with two interlocking doors that allows only one authenticated person through at a time"),
    ("Bollards", "Short sturdy posts that physically block vehicles from approaching a building entrance; a preventive/deterrent physical control"),
    ("Video surveillance (CCTV)", "Physical/technical monitoring control; visible cameras deter intruders, while recorded footage reviewed after an event is detective"),
    ("Warning signage", "Posted notices such as 'Area under surveillance' that discourage intrusion attempts; a classic deterrent control"),
    ("Risk assessment", "Managerial activity that identifies and prioritizes threats and vulnerabilities to guide control selection and security planning"),
    ("Security awareness training", "Operational control that teaches users to recognize threats such as phishing; changes people's behavior rather than system configuration"),
    ("Backup and restore", "Copying data so it can be recovered after loss or compromise; restoring after an incident is the textbook corrective control"),
    ("Defense in depth", "Layering multiple control categories and types so that if one control fails, others still protect the asset"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A network administrator configures firewall access control lists to block inbound traffic from untrusted networks. Which control CATEGORY does this represent?",
        "choices": ["Technical", "Managerial", "Operational", "Physical"],
        "answer": 0,
        "explain": "Firewall ACLs are enforced by hardware/software systems, making them technical controls. Managerial controls are policies and oversight, operational controls are performed by people, and physical controls restrict real-world access to facilities.",
    },
    {
        "type": "mc",
        "q": "An organization performs quarterly risk assessments and maintains a formal set of security policies that guide the security program. Which control category do these represent?",
        "choices": ["Technical", "Physical", "Managerial", "Operational"],
        "answer": 2,
        "explain": "Risk assessments, security policies, and other governance/planning activities are managerial (administrative) controls — they address security design and oversight. They are not enforced by systems (technical) or performed as day-to-day hands-on tasks (operational).",
    },
    {
        "type": "mc",
        "q": "The security team runs monthly phishing-awareness training sessions for all employees. Which control category BEST describes this activity?",
        "choices": ["Managerial", "Operational", "Technical", "Physical"],
        "answer": 1,
        "explain": "Security awareness training is an operational control — it is carried out by and for people as part of day-to-day operations rather than enforced by a system. Managerial controls set policy and direction; the hands-on execution of training is operational.",
    },
    {
        "type": "mc",
        "q": "A server room is protected by a badge reader and an electronic door lock so only authorized staff can enter. Which control category is this?",
        "choices": ["Physical", "Technical", "Directive", "Managerial"],
        "answer": 0,
        "explain": "Door locks, badge readers, fences, and vestibules control real-world access to spaces and equipment, so they are physical controls. Note that 'directive' is a control type, not a category — a common trap on category-versus-type questions.",
    },
    {
        "type": "mc",
        "q": "A company posts signs reading 'Warning: premises monitored by video surveillance' around its perimeter. The signs do not physically stop anyone. Which control TYPE is this?",
        "choices": ["Preventive", "Deterrent", "Detective", "Corrective"],
        "answer": 1,
        "explain": "Warning signage discourages an intruder from attempting an attack without directly blocking it, which is the definition of a deterrent control. A preventive control (like a lock) would actually stop the intrusion; a detective control would identify it after or as it happens.",
    },
    {
        "type": "mc",
        "q": "An intrusion detection system generates an alert when it observes suspicious traffic on the network but takes no blocking action. Which control type is the IDS?",
        "choices": ["Preventive", "Compensating", "Detective", "Directive"],
        "answer": 2,
        "explain": "An IDS identifies and reports events during or after they occur, making it a detective control. Because it only alerts and does not block, it is not preventive — that would be an IPS, which sits inline and stops malicious traffic.",
    },
    {
        "type": "mc",
        "q": "After a ransomware infection encrypts a file server, administrators wipe the system and restore the data from last night's backup. Restoring from backup is which control type?",
        "choices": ["Detective", "Deterrent", "Preventive", "Corrective"],
        "answer": 3,
        "explain": "Corrective controls reverse damage and restore normal operations after an incident has occurred — restoring from backup is the textbook example. Preventive controls act before the event, and detective controls only identify that it happened.",
    },
    {
        "type": "mc",
        "q": "A legacy medical device cannot run antivirus software or receive patches. The security team places it on an isolated network segment with strict firewall rules and extra monitoring. This is BEST described as which control type?",
        "choices": ["Compensating", "Corrective", "Directive", "Deterrent"],
        "answer": 0,
        "explain": "When the primary or required control (patching/antivirus) is not feasible, an alternative that provides similar risk reduction — here, segmentation and monitoring — is a compensating control. It is not corrective because no incident is being recovered from.",
    },
    {
        "type": "mc",
        "q": "All new hires must read and sign an acceptable use policy describing permitted use of company systems. Which control TYPE does the AUP represent?",
        "choices": ["Detective", "Directive", "Compensating", "Corrective"],
        "answer": 1,
        "explain": "Directive controls direct or compel subjects toward secure behavior through policies, procedures, and instructions — an AUP is the classic example. It does not detect events, recover from incidents, or substitute for another control.",
    },
    {
        "type": "mc",
        "q": "Full-disk encryption is deployed on all corporate laptops to protect data if a device is stolen. Which control category is encryption?",
        "choices": ["Operational", "Physical", "Managerial", "Technical"],
        "answer": 3,
        "explain": "Encryption is implemented and enforced by software/hardware, making it a technical control. Even though it mitigates a physical theft scenario, the control itself operates within the system, not in the physical world.",
    },
    {
        "type": "mc",
        "q": "Which of the following is an example of a MANAGERIAL control?",
        "choices": ["A perimeter fence", "A vulnerability scanner", "A risk assessment", "A motion-detecting camera"],
        "answer": 2,
        "explain": "A risk assessment is a governance and planning activity, which places it in the managerial category. The fence and camera are physical controls, and the vulnerability scanner is a technical control.",
    },
    {
        "type": "mc",
        "q": "Concrete bollards are installed in front of a data center entrance to stop vehicles from ramming the doors. Which control category is this?",
        "choices": ["Physical", "Operational", "Technical", "Managerial"],
        "answer": 0,
        "explain": "Bollards are a physical barrier that restricts real-world access, so they belong to the physical category. Functionally they are also preventive (they actually stop a vehicle) — one control can be described by both a category and a type.",
    },
    {
        "type": "mc",
        "q": "During a routine SIEM log review, an analyst discovers evidence that an attacker accessed a database three weeks ago. The log review that uncovered the breach is which control type?",
        "choices": ["Preventive", "Detective", "Corrective", "Deterrent"],
        "answer": 1,
        "explain": "Reviewing logs identifies security events after they have occurred, which is the role of a detective control. It did not stop the breach (preventive), fix the damage (corrective), or discourage the attacker (deterrent) — it revealed that the event happened.",
    },
    {
        "type": "mc",
        "q": "A next-generation firewall blocks disallowed traffic before it can reach internal servers. Which combination of category and type BEST describes it?",
        "choices": [
            "Technical, preventive",
            "Technical, detective",
            "Operational, preventive",
            "Physical, deterrent",
        ],
        "answer": 0,
        "explain": "A firewall is implemented in hardware/software (technical category) and stops unwanted traffic before it causes harm (preventive type). Every control has both a category and a type — exam questions often ask you to identify the pair.",
    },
    {
        "type": "mc",
        "q": "A uniformed guard patrols the parking lot in a clearly marked vehicle. Management's main goal is for would-be intruders to see the patrol and decide not to attempt a break-in. Which control TYPE is emphasized here?",
        "choices": ["Corrective", "Compensating", "Deterrent", "Directive"],
        "answer": 2,
        "explain": "The visible presence is intended to discourage the attempt, which is a deterrent function. If the guard physically stopped an intruder at the door, that action would be preventive — the same control can serve different types depending on how it operates.",
    },
    {
        "type": "mc",
        "q": "User accounts automatically lock after five failed login attempts, stopping password-guessing attacks before they succeed. Which control type is account lockout?",
        "choices": ["Detective", "Corrective", "Compensating", "Preventive"],
        "answer": 3,
        "explain": "Account lockout blocks the attack from succeeding before compromise occurs, making it preventive. A detective control would only alert on the failed attempts, and a corrective control would act after the account had already been compromised.",
    },
    {
        "type": "mc",
        "q": "A small server-room fire breaks out and an employee extinguishes it with a fire extinguisher, limiting the damage. Using the fire extinguisher is which control type?",
        "choices": ["Corrective", "Preventive", "Deterrent", "Detective"],
        "answer": 0,
        "explain": "The extinguisher is used after the incident (the fire) has begun in order to stop and reverse the damage, which makes it corrective. A preventive control would have kept the fire from starting; a detective control (like a smoke alarm) would have identified it.",
    },
    {
        "type": "mc",
        "q": "An inline intrusion prevention system detects an exploit attempt and drops the malicious packets in real time before they reach the target. Functionally, the IPS is acting as which control type?",
        "choices": ["Detective", "Preventive", "Directive", "Compensating"],
        "answer": 1,
        "explain": "Because the IPS actively blocks the attack before it succeeds, it functions as a preventive control. This is the key IDS-versus-IPS contrast: an IDS only detects and alerts (detective), while an inline IPS detects AND prevents.",
    },
    {
        "type": "mc",
        "q": "Which control type discourages a potential attacker from acting but does NOT directly stop the attack if the attacker proceeds anyway?",
        "choices": ["Preventive", "Corrective", "Deterrent", "Detective"],
        "answer": 2,
        "explain": "Deterrent controls (warning signs, visible cameras, lighting) work on the attacker's decision-making, reducing the likelihood of an attempt. Preventive controls actually block the action, which is the key contrast tested on the exam.",
    },
    {
        "type": "mc",
        "q": "The security office publishes a standard operating procedure instructing administrators exactly how to harden new servers before deployment. Which control TYPE is the SOP?",
        "choices": ["Directive", "Detective", "Compensating", "Corrective"],
        "answer": 0,
        "explain": "Procedures and policies that tell people what they must do are directive controls — they compel or guide behavior toward security compliance. The hardening settings themselves, once applied, would be technical preventive controls.",
    },
    {
        "type": "mc",
        "q": "An auditor requires multifactor authentication on a legacy application, but the application cannot support MFA. The company instead enforces 16-character passwords and adds enhanced logon monitoring. The added measures are BEST described as what?",
        "choices": ["Corrective controls", "Compensating controls", "Deterrent controls", "Directive controls"],
        "answer": 1,
        "explain": "The company cannot implement the required control, so it deploys alternatives that achieve comparable risk reduction — the definition of compensating controls. They are not corrective because there is no incident being remediated.",
    },
    {
        "type": "mc",
        "q": "Security controls are classified along two dimensions: category and type. Which of the following lists contains the four control CATEGORIES?",
        "choices": [
            "Preventive, Deterrent, Detective, Corrective",
            "Technical, Preventive, Physical, Directive",
            "Technical, Managerial, Operational, Physical",
            "Managerial, Compensating, Operational, Detective",
        ],
        "answer": 2,
        "explain": "The four categories describe how/by whom a control is implemented: Technical, Managerial, Operational, and Physical. Preventive, Deterrent, Detective, Corrective, Compensating, and Directive are the six control TYPES, which describe what the control does.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A single security control can belong to one category but function as more than one control type — for example, a visible CCTV camera can be both deterrent and detective.",
        "answer": True,
        "explain": "Categories and types are independent dimensions, and many controls serve multiple types. A visible camera deters intruders who see it, and its recorded footage detects/documents events that do occur.",
    },
    {
        "type": "tf",
        "q": "True or False: Firewalls and intrusion prevention systems are examples of managerial controls.",
        "answer": False,
        "explain": "Firewalls and IPSs are technical controls because they are implemented in hardware and software. Managerial controls are administrative — policies, risk assessments, and other governance activities.",
    },
    {
        "type": "tf",
        "q": "True or False: A compensating control is used when the primary or required control cannot feasibly be implemented, providing similar protection through alternative means.",
        "answer": True,
        "explain": "That is the definition of a compensating control — an alternative that delivers comparable risk reduction when the preferred control is impractical, such as isolating an unpatchable legacy system. It is often intended as a stopgap rather than a permanent design choice.",
    },
    {
        "type": "tf",
        "q": "True or False: Detective controls stop an attack before it can occur.",
        "answer": False,
        "explain": "Detective controls identify and record events during or after they happen — they do not block anything. Stopping an attack before it succeeds is the job of a preventive control such as a firewall rule or a locked door.",
    },
    {
        "type": "tf",
        "q": "True or False: Directive controls guide or compel behavior through policies, procedures, and instructions, such as an acceptable use policy.",
        "answer": True,
        "explain": "Directive controls tell people what they must (or must not) do — AUPs, security policies, and mandated procedures are the standard examples. They shape behavior rather than technically enforcing it.",
    },
    {
        "type": "tf",
        "q": "True or False: Fences, bollards, lighting, and access control vestibules are all examples of physical controls.",
        "answer": True,
        "explain": "All of these restrict or influence real-world access to facilities, which defines the physical category. Lighting is also commonly cited as a deterrent type because it discourages intruders who fear being seen.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The control category implemented by hardware and software systems — such as firewalls, encryption, and antivirus — is called ______. (type your answer)",
        "answers": ["technical", "technical controls", "technical control"],
        "explain": "Technical controls are enforced by technology rather than by people or paperwork. Firewalls, ACLs, encryption, antivirus, and authentication systems are the classic exam examples.",
    },
    {
        "type": "fill",
        "q": "A control type that identifies and records a security event during or after it occurs — such as an IDS alert or log review — is called a ______ control. (type your answer)",
        "answers": ["detective"],
        "explain": "Detective controls reveal that something happened; they do not stop it. IDS alerts, SIEM log reviews, motion sensors, and reviewing camera footage are all detective examples.",
    },
    {
        "type": "fill",
        "q": "When a required control is not feasible and an alternative measure is used to provide similar protection, that alternative is called a ______ control. (type your answer)",
        "answers": ["compensating", "compensatory"],
        "explain": "Compensating controls substitute for a primary control that cannot be implemented — for example, network segmentation and extra monitoring in place of patching an end-of-life system.",
    },
    {
        "type": "fill",
        "q": "A control type that discourages attackers from attempting an intrusion — such as warning signs or visible security cameras — without directly blocking them is called a ______ control. (type your answer)",
        "answers": ["deterrent"],
        "explain": "Deterrent controls influence the attacker's decision to act, reducing the likelihood of an attempt. They contrast with preventive controls, which physically or technically stop the action itself.",
    },
    {
        "type": "fill",
        "q": "The control category that covers security governance activities such as policies, standard operating procedures, and risk assessments is called ______. (type your answer)",
        "answers": ["managerial", "managerial controls", "administrative", "management"],
        "explain": "Managerial (administrative) controls address the design, planning, and oversight of the security program. Policies, risk assessments, and SOP documentation are standard examples on the exam.",
    },
    {
        "type": "fill",
        "q": "A control type applied after an incident to reverse damage and restore normal operations — such as restoring data from backup — is called a ______ control. (type your answer)",
        "answers": ["corrective"],
        "explain": "Corrective controls come into play once an event has already happened: restoring backups, re-imaging infected machines, or extinguishing a fire. Preventive and deterrent controls, by contrast, act before the event.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each control CATEGORY to its example.",
        "pairs": [
            ["Technical", "Firewall access control list"],
            ["Managerial", "Annual risk assessment"],
            ["Operational", "Delivering security awareness training to staff"],
            ["Physical", "Bollards at the building entrance"],
        ],
        "explain": "Categories describe how a control is implemented: technical controls live in systems (firewall ACLs), managerial controls are governance activities (risk assessments), operational controls are performed by people (training), and physical controls restrict real-world access (bollards).",
    },
    {
        "type": "match",
        "q": "Match each control TYPE to its example.",
        "pairs": [
            ["Preventive", "Electronic door lock on the server room"],
            ["Deterrent", "'Area under video surveillance' warning sign"],
            ["Detective", "Reviewing camera footage after a break-in"],
            ["Corrective", "Restoring files from backup after ransomware"],
            ["Compensating", "Isolating an unpatchable legacy system on its own segment"],
            ["Directive", "Acceptable use policy signed by all employees"],
        ],
        "explain": "The six types describe what a control does: prevent the event, deter the attempt, detect the occurrence, correct the damage, compensate for a missing primary control, or direct behavior through policy. Being able to sort concrete examples into these six buckets is exactly how objective 1.1 is tested.",
    },
    {
        "type": "match",
        "q": "Match each control type to WHEN or HOW it acts relative to a security event.",
        "pairs": [
            ["Preventive", "Blocks the event before it can happen"],
            ["Deterrent", "Discourages the attacker from even attempting it"],
            ["Detective", "Identifies and records the event during or after it occurs"],
            ["Corrective", "Restores systems and reverses damage after the event"],
        ],
        "explain": "Thinking in a timeline helps: deterrent and preventive act before the event (discourage vs. actually block), detective acts during/after (identify), and corrective acts after (recover). Compensating and directive sit outside the timeline — one substitutes for another control, the other mandates behavior.",
    },
]
