TOPIC = {
    "id": "1.2",
    "domain": 1,
    "title": "Summarize fundamental security concepts.",
    "short": "Fundamental Security Concepts",
}

TERMS = [
    ("Confidentiality", "Ensuring information is accessible only to authorized parties; enforced with encryption, access controls, and data classification"),
    ("Integrity", "Ensuring data is accurate and unmodified by unauthorized parties; verified with hashing, checksums, and digital signatures"),
    ("Availability", "Ensuring systems and data are accessible to authorized users when needed; supported by redundancy, backups, and fault tolerance"),
    ("Non-repudiation", "Assurance that a party cannot deny having performed an action, such as sending a message; provided by digital signatures"),
    ("Authentication", "Proving a claimed identity is genuine, e.g., with passwords, biometrics, tokens, or certificates; the first A of AAA"),
    ("Authorization", "Determining what an authenticated identity is permitted to do, based on policies and permission/authorization models"),
    ("Accounting", "Tracking and logging user and system activity (who did what, when) to support audits, billing, and investigations"),
    ("Gap analysis", "Comparing an organization's current security posture against a desired state or framework to identify what is missing"),
    ("Zero Trust", "Security model that removes implicit trust: 'never trust, always verify' — every access request is authenticated and evaluated"),
    ("Control plane (Zero Trust)", "Decision-making layer of Zero Trust; includes adaptive identity, threat scope reduction, policy-driven access control, Policy Engine, and Policy Administrator"),
    ("Data plane (Zero Trust)", "Layer where traffic actually flows and decisions are enforced; includes the subject/system, Policy Enforcement Point, and implicit trust zones"),
    ("Adaptive identity", "Real-time identity validation that considers context such as location, device, and behavior when evaluating an access request"),
    ("Threat scope reduction", "Limiting the possible impact ('blast radius') of a compromise through least privilege and segmentation of access"),
    ("Policy-driven access control", "Granting or denying access by evaluating identity and context against centrally defined security policies"),
    ("Policy Engine", "Zero Trust control-plane component that evaluates each access request against policy and makes the grant/deny decision"),
    ("Policy Administrator", "Zero Trust control-plane component that communicates the Policy Engine's decision, instructing the enforcement point to establish or tear down the session"),
    ("Policy Enforcement Point (PEP)", "Data-plane gatekeeper that allows, monitors, and terminates connections between subjects and resources based on control-plane decisions"),
    ("Implicit trust zone", "Portion of the data plane beyond the PEP where traffic is allowed to flow after an access request has been approved"),
    ("Bollards", "Short sturdy posts that physically block vehicles from driving into a protected area or building entrance"),
    ("Access control vestibule", "Two-door entry area where the first door must close before the second opens; defeats tailgating/piggybacking"),
    ("Access badge", "Physical credential (often smart card or proximity card) presented to a reader to authenticate and unlock doors, and to log entry"),
    ("Sensors (physical security)", "Detection devices: infrared (body heat), pressure (weight on a surface), microwave (reflected emitted energy), ultrasonic (reflected sound waves)"),
    ("Honeypot", "Intentionally vulnerable-looking decoy system deployed to attract attackers so their tools and techniques can be observed"),
    ("Honeynet", "An entire decoy network of multiple honeypots simulating servers, hosts, and services to study attacker behavior at scale"),
    ("Honeyfile", "Decoy file with enticing content (e.g., 'passwords.xlsx') planted so that any access to it signals an intrusion"),
    ("Honeytoken", "Fake data element such as bogus credentials, API keys, or database records that triggers an alert when used or accessed"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company encrypts customer records stored on its database servers so that only authorized staff can read them. Which element of the CIA triad does this primarily protect?",
        "choices": ["Confidentiality", "Integrity", "Availability", "Non-repudiation"],
        "answer": 0,
        "explain": "Encryption of data at rest keeps information secret from anyone without the key, which is the definition of confidentiality. Integrity is about preventing unauthorized modification, availability is about keeping systems accessible, and non-repudiation is about preventing denial of an action.",
    },
    {
        "type": "mc",
        "q": "An administrator publishes SHA-256 hashes alongside software downloads so users can verify the files were not altered in transit. Which security concept is being supported?",
        "choices": ["Availability", "Confidentiality", "Integrity", "Accounting"],
        "answer": 2,
        "explain": "Hashing lets a recipient detect any modification: if even one bit changes, the hash will not match. That is integrity. Hashes do not hide the content (confidentiality) or keep the service online (availability).",
    },
    {
        "type": "mc",
        "q": "An e-commerce site adds redundant web servers, an uninterruptible power supply, and offsite backups. Which element of the CIA triad do these measures primarily support?",
        "choices": ["Confidentiality", "Availability", "Integrity", "Authorization"],
        "answer": 1,
        "explain": "Redundancy, backup power, and backups all keep systems and data accessible when components fail — that is availability. A DDoS attack is the classic attack against availability; these controls build resilience against outages.",
    },
    {
        "type": "mc",
        "q": "A finance manager digitally signs a wire-transfer approval. Later he claims he never approved it, but the signature proves otherwise. Which security concept does the digital signature provide?",
        "choices": ["Confidentiality", "Availability", "Accounting", "Non-repudiation"],
        "answer": 3,
        "explain": "Non-repudiation means a party cannot credibly deny an action they performed. A digital signature is created with the signer's private key, which only they control, so it proves origin. Accounting logs activity but does not by itself cryptographically prove who acted.",
    },
    {
        "type": "mc",
        "q": "A user signs in with a password and then must enter a one-time code from an authenticator app before access is granted. Which part of AAA is taking place?",
        "choices": ["Authorization", "Authentication", "Accounting", "Non-repudiation"],
        "answer": 1,
        "explain": "Verifying that the person is who they claim to be — with a password plus a second factor — is authentication of people. Authorization happens afterward, when the system decides what the proven identity may access; accounting records what they did.",
    },
    {
        "type": "mc",
        "q": "A network requires every laptop to present a device certificate via 802.1X before it is allowed onto the LAN. This is an example of what?",
        "choices": ["Authenticating systems", "Authorization", "Accounting", "Gap analysis"],
        "answer": 0,
        "explain": "AAA applies to machines as well as people. Using 802.1X with device certificates authenticates the system (the device itself) before granting network access. It is not authorization (deciding permissions) or accounting (logging activity).",
    },
    {
        "type": "mc",
        "q": "After Maria logs in successfully, the file server checks her group memberships to decide which shared folders she can open. Which AAA element is the server performing?",
        "choices": ["Authentication", "Accounting", "Authorization", "Identification"],
        "answer": 2,
        "explain": "Authorization determines what an already-authenticated identity is allowed to do — here, which folders Maria can access based on her groups. Authentication already happened at login, and accounting would be the logging of her actions.",
    },
    {
        "type": "mc",
        "q": "Security policy requires that every administrative action on the firewall be logged with the admin's username and a timestamp for later audit. Which AAA element does this describe?",
        "choices": ["Accounting", "Authentication", "Authorization", "Adaptive identity"],
        "answer": 0,
        "explain": "Accounting is the tracking and logging of activity — who did what and when — to support audits and investigations. It is the third A of AAA, following authentication (proving identity) and authorization (granting rights).",
    },
    {
        "type": "mc",
        "q": "An organization assigns permissions to job functions such as 'Help Desk' and 'HR Manager,' and users receive access by being placed into those roles. What is this an example of?",
        "choices": ["A gap analysis", "An authorization model", "Threat scope reduction", "Accounting"],
        "answer": 1,
        "explain": "Role-based access control is one of several authorization models — frameworks that define how permissions are assigned and evaluated (role-based, rule-based, attribute-based, discretionary). Authorization models are how the 'authorization' part of AAA is implemented.",
    },
    {
        "type": "mc",
        "q": "A new CISO compares the company's existing controls against the NIST Cybersecurity Framework to identify which recommended protections are missing. What is this activity called?",
        "choices": ["Penetration test", "Risk transference", "Threat scope reduction", "Gap analysis"],
        "answer": 3,
        "explain": "A gap analysis measures the current security state against a desired state or framework and identifies the 'gaps' to remediate. A penetration test actively attacks systems, and threat scope reduction is a Zero Trust concept about limiting blast radius.",
    },
    {
        "type": "mc",
        "q": "A security architect insists that no user or device be trusted by default — even on the internal LAN — and that every access request be verified before it is granted. Which security model is this?",
        "choices": ["Zero Trust", "Defense in depth", "Implicit trust", "Perimeter security"],
        "answer": 0,
        "explain": "'Never trust, always verify' is the core principle of Zero Trust: network location no longer confers trust, and every request is authenticated and evaluated against policy. Traditional perimeter security assumed anything inside the firewall was trustworthy.",
    },
    {
        "type": "mc",
        "q": "In a Zero Trust architecture, which control-plane component evaluates each access request against policy and makes the ultimate grant-or-deny decision?",
        "choices": ["Policy Enforcement Point", "Policy Administrator", "Policy Engine", "Implicit trust zone"],
        "answer": 2,
        "explain": "The Policy Engine is the decision-maker: it weighs identity, context, and policy and decides grant or deny. The Policy Administrator communicates that decision, and the Policy Enforcement Point in the data plane actually allows or blocks the traffic.",
    },
    {
        "type": "mc",
        "q": "In Zero Trust, which component takes the Policy Engine's decision and instructs the enforcement point to establish or tear down the communication session?",
        "choices": ["Policy Administrator", "Policy Enforcement Point", "Subject/system", "Honeytoken"],
        "answer": 0,
        "explain": "The Policy Administrator sits in the control plane and executes the Policy Engine's decision by signaling the Policy Enforcement Point to open or close the session. Together the Policy Engine and Policy Administrator form the policy decision point.",
    },
    {
        "type": "mc",
        "q": "Which Zero Trust component sits in the data plane and acts as the gatekeeper that actually allows, monitors, and terminates connections between subjects and enterprise resources?",
        "choices": ["Policy Engine", "Policy Enforcement Point", "Policy Administrator", "Adaptive identity"],
        "answer": 1,
        "explain": "The Policy Enforcement Point (PEP) is the data-plane gatekeeper: all traffic to a resource passes through it, and it enforces whatever the control plane decides. The Policy Engine and Policy Administrator decide and direct from the control plane but do not carry the traffic.",
    },
    {
        "type": "mc",
        "q": "A login system evaluates each request in real time — where the user is connecting from, what device they are using, and how they normally behave — and adjusts authentication requirements accordingly. Which Zero Trust concept is this?",
        "choices": ["Implicit trust zone", "Threat scope reduction", "Honeynet", "Adaptive identity"],
        "answer": 3,
        "explain": "Adaptive identity validates identity using real-time context — location, device posture, behavior — rather than relying on a static credential check alone. A risky context can trigger step-up authentication or denial. It is part of the Zero Trust control plane.",
    },
    {
        "type": "mc",
        "q": "To limit how far an attacker could move if one account were compromised, an organization tightly segments access so each identity can reach only the few resources it truly needs. Which Zero Trust concept does this describe?",
        "choices": ["Threat scope reduction", "Adaptive identity", "Non-repudiation", "Gap analysis"],
        "answer": 0,
        "explain": "Threat scope reduction shrinks the 'blast radius' of a compromise by applying least privilege and segmentation, so a single compromised subject exposes as little as possible. Adaptive identity is about context-aware authentication, not limiting reach.",
    },
    {
        "type": "mc",
        "q": "Instead of granting access based on network location, a Zero Trust deployment grants access by evaluating the user's identity, device, and context against centrally defined rules. What is this called?",
        "choices": ["Implicit trust", "Policy-driven access control", "Accounting", "Perimeter-based access control"],
        "answer": 1,
        "explain": "Policy-driven access control makes every access decision by evaluating identity and context against central security policies — a core control-plane function of Zero Trust. It replaces the old model in which being 'inside the network' implicitly granted access.",
    },
    {
        "type": "mc",
        "q": "In Zero Trust terminology, what is the implicit trust zone?",
        "choices": [
            "The internal LAN, which is always fully trusted",
            "The portion of the network past the Policy Enforcement Point where approved traffic is allowed to flow",
            "The list of users exempted from multifactor authentication",
            "A decoy network segment used to trap attackers",
        ],
        "answer": 1,
        "explain": "Once the control plane approves a request, traffic flows through the PEP into an implicit trust zone — the area beyond the gatekeeper for that approved session. Zero Trust aims to keep these zones as small as possible; it never treats the whole LAN as trusted, and a decoy segment describes a honeynet.",
    },
    {
        "type": "mc",
        "q": "In the Zero Trust data plane, what does the term 'subject/system' refer to?",
        "choices": [
            "The user or device requesting access to a resource",
            "The server that stores the security policies",
            "The component that makes the access decision",
            "The area of the network where traffic is trusted",
        ],
        "answer": 0,
        "explain": "The subject (a person) or system (a device/service) is the entity requesting access; its request travels through the data plane to the Policy Enforcement Point. The decision-maker is the Policy Engine, and the trusted area past the PEP is the implicit trust zone.",
    },
    {
        "type": "mc",
        "q": "In Zero Trust architecture, which plane contains the Policy Enforcement Point?",
        "choices": ["Control plane", "Management plane", "Data plane", "Application plane"],
        "answer": 2,
        "explain": "The PEP lives in the data plane, where actual traffic flows, so it can allow or block connections in line. The control plane holds the decision-making components: adaptive identity, threat scope reduction, policy-driven access control, the Policy Engine, and the Policy Administrator.",
    },
    {
        "type": "mc",
        "q": "After a car crashed through a storefront in a smash-and-grab burglary, a retailer wants a physical control to stop vehicles from reaching the entrance. Which control BEST meets this need?",
        "choices": ["Bollards", "Access control vestibule", "Video surveillance", "Lighting"],
        "answer": 0,
        "explain": "Bollards are sturdy posts designed specifically to stop vehicles while still letting pedestrians pass. A vestibule controls people entering a doorway, and cameras and lighting deter and detect but cannot physically stop a vehicle.",
    },
    {
        "type": "mc",
        "q": "A data center wants to stop employees from holding the door open so others can slip in behind them without badging. Which physical control BEST prevents this tailgating?",
        "choices": ["Bollards", "Access control vestibule", "Pressure sensor", "Honeypot"],
        "answer": 1,
        "explain": "An access control vestibule (mantrap) uses two interlocking doors — the first must close before the second opens — so only one authenticated person passes at a time, defeating tailgating and piggybacking. Bollards stop vehicles, and a honeypot is a decoy system, not a physical control.",
    },
    {
        "type": "mc",
        "q": "A security team deploys an intentionally vulnerable-looking server on an isolated segment to lure attackers away from production and record their tools and techniques. What is this system called?",
        "choices": ["Honeyfile", "Honeytoken", "Honeypot", "Policy Enforcement Point"],
        "answer": 2,
        "explain": "A honeypot is a decoy system built to attract attackers so defenders can observe their methods safely. A honeyfile is a single decoy file, and a honeytoken is fake data such as bogus credentials — both smaller-scale deception than a full decoy host.",
    },
    {
        "type": "mc",
        "q": "An administrator places a fake spreadsheet named 'passwords.xlsx' on a file share and configures an alert to fire if anyone opens it. What is this deception technique called?",
        "choices": ["Honeynet", "Honeyfile", "Gap analysis", "Access badge"],
        "answer": 1,
        "explain": "A honeyfile is a decoy file with an enticing name whose only purpose is to be touched by an intruder — any access is a high-confidence intrusion signal. A honeynet is an entire decoy network, and the other options are unrelated concepts.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Non-repudiation ensures that the sender of a message cannot later deny having sent it.",
        "answer": True,
        "explain": "That is the definition of non-repudiation. It is typically achieved with digital signatures, because a signature made with a sender's private key could only have come from the holder of that key.",
    },
    {
        "type": "tf",
        "q": "True or False: In a Zero Trust architecture, the Policy Engine is located in the data plane.",
        "answer": False,
        "explain": "The Policy Engine is a control-plane component — it makes the access decisions along with the Policy Administrator. The data plane contains the subject/system, the Policy Enforcement Point, and the implicit trust zones where approved traffic flows.",
    },
    {
        "type": "tf",
        "q": "True or False: A honeynet is a single decoy file planted on a server to detect intruders.",
        "answer": False,
        "explain": "A honeynet is an entire decoy network made of multiple honeypots simulating hosts and services. The single decoy file described here is a honeyfile. Remember the scale: honeytoken (data) < honeyfile (file) < honeypot (system) < honeynet (network).",
    },
    {
        "type": "tf",
        "q": "True or False: Video surveillance can serve as both a deterrent control and a detective control.",
        "answer": True,
        "explain": "Visible cameras discourage would-be intruders (deterrent), while recorded footage detects and documents incidents for review and investigation (detective). Many physical controls serve multiple control categories at once.",
    },
    {
        "type": "tf",
        "q": "True or False: Redundant power supplies and regular backups primarily protect the confidentiality of data.",
        "answer": False,
        "explain": "Redundancy and backups keep systems running and data recoverable, which supports availability, not confidentiality. Confidentiality is protected by controls like encryption and access restrictions that keep unauthorized parties from reading data.",
    },
    {
        "type": "tf",
        "q": "True or False: A security guard is a physical control that can both deter intruders and actively verify the identity of people entering a facility.",
        "answer": True,
        "explain": "Guards are flexible physical controls: their presence deters attackers, and unlike passive controls they can check badges and IDs, challenge unfamiliar visitors, and respond to incidents in real time.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "An entire decoy network of interconnected fake servers and services built to study attacker behavior is called a ______. (type your answer)",
        "answers": ["honeynet", "honey net"],
        "explain": "A honeynet is a network of honeypots that simulates a realistic environment so defenders can observe attacker tools, techniques, and lateral movement at scale. A single decoy host is a honeypot; a decoy file is a honeyfile.",
    },
    {
        "type": "fill",
        "q": "The process of comparing an organization's current security posture against a desired standard to identify missing controls is called a gap ______. (type your answer)",
        "answers": ["analysis", "gap analysis"],
        "explain": "A gap analysis maps where the organization is today against where it wants (or is required) to be — often against a framework like NIST CSF or ISO 27001 — and produces a list of gaps to remediate.",
    },
    {
        "type": "fill",
        "q": "In Zero Trust, the data-plane gatekeeper that enforces access decisions on traffic between subjects and resources is the policy ______ point. (type your answer)",
        "answers": ["enforcement", "policy enforcement point", "pep"],
        "explain": "The Policy Enforcement Point (PEP) sits in the path of traffic and allows, monitors, or terminates sessions as directed by the control plane. Decisions come from the Policy Engine and are relayed by the Policy Administrator.",
    },
    {
        "type": "fill",
        "q": "Fake database records or bogus credentials planted so that any use of them triggers an alert are known as ______. (type your answer)",
        "answers": ["honeytokens", "honeytoken", "honey tokens", "honey token"],
        "explain": "A honeytoken is a piece of fake data — credentials, API keys, database rows — with no legitimate purpose, so any access or use of it is a reliable indicator of compromise and can even reveal which data store was breached.",
    },
    {
        "type": "fill",
        "q": "The security model summarized by the phrase 'never trust, always verify' is called ______ trust. (type your answer)",
        "answers": ["zero", "zero trust"],
        "explain": "Zero Trust removes implicit trust based on network location: every request is authenticated, authorized, and evaluated against policy regardless of where it originates. It is implemented through control-plane decisions enforced in the data plane.",
    },
    {
        "type": "fill",
        "q": "A downloaded file's hash does not match the published value, showing the file was altered. The CIA property that has been violated is ______. (type your answer)",
        "answers": ["integrity", "data integrity"],
        "explain": "Integrity means data remains accurate and unmodified; a hash mismatch proves the file changed after the original hash was computed. Confidentiality would involve unauthorized disclosure, and availability would involve loss of access.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each physical security control to its primary purpose.",
        "pairs": [
            ["Bollards", "Stop vehicles from reaching a protected area"],
            ["Access control vestibule", "Prevent tailgating through interlocking doors"],
            ["Fencing", "Define and secure the perimeter boundary"],
            ["Video surveillance", "Monitor and record activity for deterrence and review"],
            ["Lighting", "Deter intruders and improve visibility for cameras and guards"],
            ["Access badge", "Authenticate the holder at a door reader and log entry"],
        ],
        "explain": "Each control addresses a different physical threat: bollards counter vehicles, vestibules counter tailgating people, fencing establishes the perimeter, cameras deter and detect, lighting removes the cover of darkness, and badges provide auditable electronic entry control.",
    },
    {
        "type": "match",
        "q": "Match each sensor type to how it detects an intruder.",
        "pairs": [
            ["Infrared", "Detects the heat emitted by a human body"],
            ["Pressure", "Detects weight applied to a floor, mat, or surface"],
            ["Microwave", "Emits microwave energy and detects changes in the reflections"],
            ["Ultrasonic", "Emits sound waves and detects changes in the reflections"],
        ],
        "explain": "Infrared sensors are passive heat detectors; pressure sensors react to physical weight; microwave and ultrasonic sensors are active — they emit energy (radio waves vs. sound waves respectively) and alarm when movement changes the reflected signal.",
    },
    {
        "type": "match",
        "q": "Match each Zero Trust component to its role.",
        "pairs": [
            ["Policy Engine", "Evaluates requests against policy and makes the grant/deny decision"],
            ["Policy Administrator", "Tells the enforcement point to establish or tear down the session"],
            ["Policy Enforcement Point", "Data-plane gatekeeper that allows or blocks the traffic"],
            ["Adaptive identity", "Validates identity using real-time context such as location and device"],
            ["Implicit trust zone", "Area past the enforcement point where approved traffic flows"],
        ],
        "explain": "The control plane decides: adaptive identity feeds context, the Policy Engine decides, and the Policy Administrator communicates the decision. The data plane enforces: the PEP gates the traffic, and approved sessions flow into a (deliberately small) implicit trust zone.",
    },
]
