TOPIC = {
    "id": "1.4",
    "domain": 1,
    "title": "Explain the importance of using appropriate cryptographic solutions.",
    "short": "Cryptographic Solutions",
}

TERMS = [
    ("Public key", "The freely shareable half of an asymmetric key pair; used to encrypt data for the key owner and to verify their digital signatures"),
    ("Private key", "The secret half of an asymmetric key pair; used to decrypt data encrypted with the matching public key and to create digital signatures"),
    ("Key escrow", "Arrangement in which copies of cryptographic keys are held by a trusted third party (or internal authority) so encrypted data can be recovered if keys are lost"),
    ("Symmetric encryption", "Encryption using one shared secret key for both encryption and decryption (e.g., AES); fast and suited to bulk data, but key distribution is the challenge"),
    ("Asymmetric encryption", "Encryption using a mathematically related public/private key pair (e.g., RSA, ECC); slower, but solves key distribution and enables digital signatures"),
    ("Key exchange", "Process of establishing a shared secret key between parties, e.g., Diffie-Hellman, which derives a shared secret over an insecure channel without transmitting the key"),
    ("Key length", "The size of a key in bits; longer keys create a larger keyspace and greater resistance to brute-force attacks at the cost of performance"),
    ("Full-disk encryption (FDE)", "Encrypts an entire drive including the OS (e.g., BitLocker, FileVault) so data is unreadable if the device is lost or stolen"),
    ("Trusted Platform Module (TPM)", "Dedicated cryptographic chip on a device's motherboard that stores keys and platform measurements; commonly protects full-disk encryption keys"),
    ("Hardware security module (HSM)", "Tamper-resistant appliance or card that generates, stores, and uses cryptographic keys at scale; commonly protects CA and enterprise keys"),
    ("Key management system", "Centralized platform for the key lifecycle: generation, distribution, storage, rotation, revocation, and destruction of cryptographic keys"),
    ("Secure enclave", "Isolated coprocessor/protected region within a device's main processor that handles keys and sensitive data separately from the main OS"),
    ("Steganography", "Obfuscation technique that hides a secret message inside another file, such as an image, audio, or video file, to conceal that a message exists"),
    ("Tokenization", "Replacing sensitive data (e.g., a credit card number) with a non-sensitive token that has no mathematical relationship to the original, which is stored in a secure vault"),
    ("Data masking", "Obfuscation that hides part of the original data, such as displaying only the last four digits of a card number to a support agent"),
    ("Hashing", "One-way function producing a fixed-length digest of input data (e.g., SHA-256); used for integrity checks and password storage, and cannot be reversed"),
    ("Salting", "Adding a unique random value to each password before hashing so identical passwords produce different hashes, defeating rainbow-table attacks"),
    ("Digital signature", "Hash of a message encrypted with the sender's private key; provides integrity, authentication, and non-repudiation when verified with the sender's public key"),
    ("Key stretching", "Strengthening a weak key/password by running it through thousands of hashing iterations (e.g., PBKDF2, bcrypt) to slow brute-force attacks"),
    ("Blockchain", "Distributed, immutable ledger in which each block contains a hash of the previous block, making recorded transactions extremely difficult to alter"),
    ("Open public ledger", "Blockchain ledger model that anyone can read and verify (e.g., Bitcoin's ledger), in contrast to permissioned/private ledgers restricted to vetted participants"),
    ("Certificate authority (CA)", "Trusted entity that validates identities, signs and issues digital certificates, and publishes revocation information"),
    ("Certificate revocation list (CRL)", "CA-published list of revoked certificate serial numbers that clients download to check whether a certificate should no longer be trusted"),
    ("Online Certificate Status Protocol (OCSP)", "Protocol that lets a client query a certificate's revocation status in real time instead of downloading a full CRL"),
    ("Self-signed certificate", "Certificate signed by its own creator rather than a trusted CA; free and fast for internal/test use but triggers browser trust warnings"),
    ("Certificate signing request (CSR)", "File generated on a server containing its public key and identity details, submitted to a CA to request a signed certificate"),
    ("Wildcard certificate", "Certificate issued to *.domain.com that secures the domain's first-level subdomains with a single certificate"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A user wants to send an encrypted email that only the recipient can read. Which key should the sender use to encrypt the message?",
        "choices": ["The sender's private key", "The recipient's public key", "The sender's public key", "The recipient's private key"],
        "answer": 1,
        "explain": "To provide confidentiality, you encrypt with the RECIPIENT'S public key so only the recipient's matching private key can decrypt it. Encrypting with the sender's private key is what a digital signature does — anyone with the sender's public key could read it, so it proves origin, not secrecy.",
    },
    {
        "type": "mc",
        "q": "A developer digitally signs a software update before release. Which key is used to create the signature?",
        "choices": ["The developer's private key", "The developer's public key", "The user's public key", "A shared symmetric session key"],
        "answer": 0,
        "explain": "A digital signature is created by hashing the data and encrypting that hash with the signer's PRIVATE key. Anyone can then verify the signature with the signer's public key, proving the update came from the developer and was not modified.",
    },
    {
        "type": "mc",
        "q": "A company requires that copies of employees' decryption keys be stored with a trusted third party so encrypted files can be recovered if an employee leaves or loses a key. What is this practice called?",
        "choices": ["Key stretching", "Key exchange", "Key escrow", "Tokenization"],
        "answer": 2,
        "explain": "Key escrow places copies of keys with a trusted third party (or an internal recovery authority) so the organization can recover encrypted data when the original key holder is unavailable. Key stretching strengthens weak passwords, and key exchange establishes shared secrets between parties.",
    },
    {
        "type": "mc",
        "q": "An organization wants to ensure that if a traveling employee's laptop is stolen, none of the data on the drive — including the operating system — can be read. Which solution BEST meets this need?",
        "choices": ["File-level encryption", "Transport encryption (TLS)", "Data masking", "Full-disk encryption"],
        "answer": 3,
        "explain": "Full-disk encryption (e.g., BitLocker or FileVault) encrypts the entire drive including the OS, protecting data at rest on a lost or stolen device. File-level encryption protects only selected files, TLS protects data in transit, and data masking only hides displayed values.",
    },
    {
        "type": "mc",
        "q": "A security analyst wants to protect credentials and web traffic while they travel across the internet between clients and a web server. Which type of encryption addresses this?",
        "choices": ["Full-disk encryption", "Transport/communication encryption such as TLS", "Database-level encryption", "Partition encryption"],
        "answer": 1,
        "explain": "Data in transit is protected by transport/communication encryption — TLS is the standard example, using asymmetric cryptography to exchange a symmetric session key and then symmetric encryption for the bulk traffic. Disk, partition, and database encryption protect data at rest, not data moving over the network.",
    },
    {
        "type": "mc",
        "q": "An engineer must encrypt terabytes of backup data as quickly as possible using a single shared secret key. Which type of cryptography is the BEST fit?",
        "choices": ["Symmetric encryption", "Asymmetric encryption", "Hashing", "Steganography"],
        "answer": 0,
        "explain": "Symmetric algorithms like AES use one shared key and are much faster than asymmetric algorithms, making them the choice for bulk data encryption. Asymmetric cryptography is slower and is typically used for key exchange and digital signatures; hashing is one-way and does not encrypt.",
    },
    {
        "type": "mc",
        "q": "An organization with thousands of external partners does not want to pre-share a unique secret key with every partner before communicating securely. Which approach solves this key distribution problem?",
        "choices": ["Symmetric encryption only", "Key stretching", "Asymmetric encryption", "Salting"],
        "answer": 2,
        "explain": "Asymmetric encryption solves key distribution: each party publishes a public key that anyone can use to encrypt messages to them, and no secret ever needs to be pre-shared. Pure symmetric encryption requires a shared secret per relationship, which does not scale. Key stretching and salting are password-protection techniques, not key distribution solutions.",
    },
    {
        "type": "mc",
        "q": "Two parties need to establish a shared secret key over an untrusted network without ever transmitting the key itself. Which algorithm is designed for this?",
        "choices": ["SHA-256", "AES", "MD5", "Diffie-Hellman"],
        "answer": 3,
        "explain": "Diffie-Hellman is a key exchange algorithm: each side combines its own private value with the other side's public value to independently derive the same shared secret, which never crosses the network. SHA-256 and MD5 are hash functions, and AES is the symmetric cipher you would use AFTER the key is established.",
    },
    {
        "type": "mc",
        "q": "Which of the following is a symmetric encryption algorithm?",
        "choices": ["RSA", "AES", "ECC", "Diffie-Hellman"],
        "answer": 1,
        "explain": "AES (Advanced Encryption Standard) is the modern symmetric standard, using the same key to encrypt and decrypt with key lengths of 128, 192, or 256 bits. RSA and ECC are asymmetric algorithms, and Diffie-Hellman is a key exchange algorithm.",
    },
    {
        "type": "mc",
        "q": "A new laptop includes a dedicated cryptographic chip on the motherboard that securely stores the keys used by its full-disk encryption software. What is this component?",
        "choices": ["Hardware security module (HSM)", "Secure enclave", "Trusted Platform Module (TPM)", "Key management system"],
        "answer": 2,
        "explain": "A TPM is a cryptographic chip built into a device's motherboard that stores keys and platform integrity measurements — BitLocker famously uses it to protect disk encryption keys. An HSM is a separate appliance or card used at enterprise scale, and a key management system is software for managing the key lifecycle.",
    },
    {
        "type": "mc",
        "q": "A certificate authority needs a dedicated tamper-resistant appliance to generate and protect its private signing keys and offload cryptographic operations. Which tool should it deploy?",
        "choices": ["Trusted Platform Module (TPM)", "Hardware security module (HSM)", "Secure enclave", "Self-signed certificate"],
        "answer": 1,
        "explain": "An HSM is a dedicated tamper-resistant device built for high-volume key generation, storage, and cryptographic processing — the standard way CAs and enterprises protect critical private keys. A TPM serves a single device's needs, and a secure enclave is an isolated processor region inside a consumer device.",
    },
    {
        "type": "mc",
        "q": "A cloud team must centrally generate, rotate, revoke, and track thousands of encryption keys used across many services. Which solution is designed for this?",
        "choices": ["A key management system", "A certificate revocation list", "Key escrow", "A wildcard certificate"],
        "answer": 0,
        "explain": "A key management system (KMS) centralizes the entire key lifecycle — generation, distribution, storage, rotation, revocation, and destruction — which becomes essential at cloud scale. A CRL lists revoked certificates, escrow is third-party key recovery storage, and a wildcard certificate covers subdomains.",
    },
    {
        "type": "mc",
        "q": "A smartphone stores biometric templates and encryption keys in an isolated coprocessor that even the main operating system cannot directly read. What is this feature called?",
        "choices": ["Key escrow", "Trusted Platform Module (TPM)", "Blockchain", "Secure enclave"],
        "answer": 3,
        "explain": "A secure enclave is an isolated processor region/coprocessor that handles sensitive data such as keys and biometric information separately from the main OS, so even a compromised OS cannot extract it. It is similar in purpose to a TPM but is built into the main processor package rather than being a separate motherboard chip.",
    },
    {
        "type": "mc",
        "q": "A payment processor replaces stored credit card numbers with random substitute values that have no mathematical relationship to the originals; the real numbers are kept in a secure vault. What is this technique?",
        "choices": ["Hashing", "Tokenization", "Data masking", "Key stretching"],
        "answer": 1,
        "explain": "Tokenization swaps sensitive data for a meaningless token and stores the real value in a secure token vault — because the token is not derived mathematically from the original, stealing tokens reveals nothing. Hashing is a one-way mathematical function, and data masking only hides part of a displayed value.",
    },
    {
        "type": "mc",
        "q": "Customer service representatives can see only the last four digits of customers' credit card numbers on their screens (e.g., ****-****-****-1234). Which technique is in use?",
        "choices": ["Data masking", "Steganography", "Tokenization", "Full-disk encryption"],
        "answer": 0,
        "explain": "Data masking obscures part of the original data so it can be used or displayed without exposing the full sensitive value — showing only the last four card digits is the classic example. Tokenization would replace the entire stored value with a token, and steganography hides data inside another file.",
    },
    {
        "type": "mc",
        "q": "After downloading an ISO image, an administrator computes its SHA-256 value and compares it to the value published by the vendor. What is the administrator verifying?",
        "choices": ["Confidentiality of the file", "Non-repudiation of the vendor", "Integrity of the file", "Availability of the download server"],
        "answer": 2,
        "explain": "Comparing hash digests verifies integrity: if even one bit of the file changed, the hash would differ. Hashing alone provides no confidentiality (the file is not encrypted) and no non-repudiation — that would require the vendor to digitally sign the hash with its private key.",
    },
    {
        "type": "mc",
        "q": "A signed contract is transmitted with a digital signature. Later, the sender denies ever sending it, but the signature proves otherwise. Which security property of digital signatures does this demonstrate?",
        "choices": ["Confidentiality", "Non-repudiation", "Obfuscation", "Key stretching"],
        "answer": 1,
        "explain": "Because only the sender's private key could have produced a signature that verifies with the sender's public key, the sender cannot plausibly deny signing — that is non-repudiation. Digital signatures also provide integrity and authentication, but they do not encrypt the message, so they provide no confidentiality.",
    },
    {
        "type": "mc",
        "q": "In a blockchain, each block includes the hash of the previous block. What security benefit does this design provide?",
        "choices": [
            "It keeps all transactions confidential",
            "It allows transactions to be reversed by the ledger owner",
            "It compresses the ledger to save storage",
            "It makes recorded transactions extremely difficult to alter",
        ],
        "answer": 3,
        "explain": "Chaining each block to the previous block's hash means altering any historical record would change that block's hash and break every subsequent block, and the tampering would be rejected by the distributed copies of the ledger. This gives blockchain its immutability; it does not provide confidentiality — a public blockchain's ledger is openly viewable.",
    },
    {
        "type": "mc",
        "q": "A browser needs to check whether a single web server certificate has been revoked, in real time, without downloading the CA's entire list of revoked certificates. Which mechanism does this?",
        "choices": ["Certificate revocation list (CRL)", "Certificate signing request (CSR)", "Online Certificate Status Protocol (OCSP)", "Key escrow"],
        "answer": 2,
        "explain": "OCSP lets a client query the status of one specific certificate and get a real-time good/revoked response, avoiding the overhead of downloading a full CRL. A CRL is the older approach — a periodically published list of revoked serial numbers — and a CSR is used to request a new certificate, not check one.",
    },
    {
        "type": "mc",
        "q": "Which entity is responsible for validating an applicant's identity and then signing and issuing the applicant's digital certificate?",
        "choices": ["A certificate authority", "A key management system", "A hardware security module", "A Trusted Platform Module"],
        "answer": 0,
        "explain": "The certificate authority (CA) is the trusted entity at the heart of PKI: it validates identities, signs certificates with its private key, and publishes revocation information via CRLs and OCSP. An HSM may protect the CA's keys and a KMS manages key lifecycles, but neither issues certificates.",
    },
    {
        "type": "mc",
        "q": "A browser trusts a web server's certificate because the chain of signatures leads back to a self-signed CA certificate pre-installed in the operating system's trust store. What does this top-level certificate represent?",
        "choices": ["A wildcard certificate", "The root of trust", "A certificate signing request", "A certificate revocation list"],
        "answer": 1,
        "explain": "The root CA certificate is the root of trust (trust anchor): every certificate in the chain is trusted because its signatures ultimately lead back to this pre-trusted root. Hardware can also serve as a root of trust (e.g., a TPM anchoring secure boot), but in PKI the root CA certificate plays that role.",
    },
    {
        "type": "mc",
        "q": "A company is launching a public e-commerce website. Why should it obtain its TLS certificate from a third-party CA instead of using a self-signed certificate?",
        "choices": [
            "Third-party certificates use stronger encryption algorithms than self-signed ones",
            "Self-signed certificates cannot contain a public key",
            "Third-party certificates never need to be renewed",
            "Customers' browsers already trust the third-party CA, so no warnings appear",
        ],
        "answer": 3,
        "explain": "Public browsers ship with trusted third-party root CAs, so a certificate chaining to one is accepted silently — a self-signed certificate triggers trust warnings that drive customers away. The encryption strength can be identical either way; the difference is trust validation, and all certificates (including third-party) expire and need renewal.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Data encrypted with a public key can only be decrypted with the corresponding private key from the same key pair.",
        "answer": True,
        "explain": "Asymmetric key pairs are mathematically linked: what one key encrypts, only the other can decrypt. This is why publishing the public key is safe — only the holder of the matching private key can read messages encrypted with it.",
    },
    {
        "type": "tf",
        "q": "True or False: Asymmetric encryption is faster than symmetric encryption, so it is preferred for encrypting large volumes of data.",
        "answer": False,
        "explain": "It is the opposite: symmetric encryption (e.g., AES) is much faster and is used for bulk data, while slower asymmetric encryption is used for key exchange and digital signatures. Real systems like TLS combine them — asymmetric to establish a session key, then symmetric for the traffic.",
    },
    {
        "type": "tf",
        "q": "True or False: Increasing an encryption key's length generally increases its resistance to brute-force attacks.",
        "answer": True,
        "explain": "Each additional bit doubles the keyspace an attacker must search, so longer keys (e.g., AES-256 vs. AES-128) are exponentially harder to brute-force. The trade-off is more computational overhead, which is why key length is balanced against performance needs.",
    },
    {
        "type": "tf",
        "q": "True or False: A hashed password can be decrypted back to the original plaintext by anyone who knows the hashing algorithm used.",
        "answer": False,
        "explain": "Hashing is a one-way function — there is no key and no decryption. Attackers instead guess inputs and compare hashes (brute force, dictionaries, rainbow tables), which is exactly why salting and key stretching are used to make those attacks impractical.",
    },
    {
        "type": "tf",
        "q": "True or False: A public blockchain records its transactions on an open public ledger that anyone can view and verify.",
        "answer": True,
        "explain": "Blockchain functions as an open public ledger: transactions are recorded in a distributed ledger shared across many nodes, and anyone can inspect and verify the chain. Its trust comes from this transparency plus immutability — not from confidentiality, which it does not provide.",
    },
    {
        "type": "tf",
        "q": "True or False: A self-signed certificate is validated by a trusted third-party certificate authority.",
        "answer": False,
        "explain": "A self-signed certificate is signed by its own creator, with no third-party CA vouching for the identity, which is why browsers show trust warnings for it. Self-signed certificates are acceptable for internal or test systems but not for public-facing services.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The unique random value added to each password before hashing, so identical passwords produce different hashes, is called a ______. (type your answer)",
        "answers": ["salt", "salting", "a salt"],
        "explain": "A salt is a random value combined with each password before hashing. Because every user's salt differs, identical passwords hash differently, and precomputed rainbow tables become useless against the stolen hash database.",
    },
    {
        "type": "fill",
        "q": "The periodically published list from a CA containing the serial numbers of certificates that should no longer be trusted is called a ______. (type the acronym or full name)",
        "answers": ["crl", "certificate revocation list", "certificate revocation list (crl)"],
        "explain": "A certificate revocation list (CRL) is the CA's published list of revoked certificates. Clients download it to check validity, though many now prefer OCSP, which queries the status of a single certificate in real time instead.",
    },
    {
        "type": "fill",
        "q": "Hiding a secret message inside an ordinary-looking image or audio file so that observers do not even know a message exists is called ______. (type your answer)",
        "answers": ["steganography", "stego"],
        "explain": "Steganography conceals the existence of data by embedding it inside another file, such as tweaking pixel values in an image. Unlike encryption, which makes data unreadable but visible, steganography hides that there is anything to find at all.",
    },
    {
        "type": "fill",
        "q": "A certificate issued to *.example.com that secures www.example.com, mail.example.com, and shop.example.com with a single certificate is called a ______ certificate. (type your answer)",
        "answers": ["wildcard", "wild card", "wildcard certificate"],
        "explain": "A wildcard certificate uses *.domain.com to cover the domain's first-level subdomains, simplifying management and cost. The trade-off is risk concentration: if the wildcard's private key is compromised, every subdomain it protects is affected.",
    },
    {
        "type": "fill",
        "q": "PBKDF2 and bcrypt strengthen stored passwords by running them through thousands of hashing iterations. This technique is called key ______. (type your answer)",
        "answers": ["stretching", "key stretching"],
        "explain": "Key stretching deliberately makes each password guess computationally expensive by iterating the hash function thousands of times. A user barely notices the delay at login, but a brute-force attacker must pay that cost for every single guess.",
    },
    {
        "type": "fill",
        "q": "Before a CA will issue a certificate, the administrator generates a file on the server containing its public key and identity details and submits it to the CA. This file is called a ______. (type the acronym or full name)",
        "answers": ["csr", "certificate signing request", "certificate signing request (csr)"],
        "explain": "A certificate signing request (CSR) contains the server's public key and identifying information (such as the common name). The private key never leaves the server — the CA validates the request and returns a signed certificate binding the identity to the public key.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each level of encryption to what it protects.",
        "pairs": [
            ["Full-disk", "The entire drive, including the operating system"],
            ["Partition", "One defined section of a drive, leaving others unencrypted"],
            ["Volume", "A logical storage container/set of files mounted as a unit"],
            ["File", "An individual document, leaving the rest of the disk unencrypted"],
            ["Database", "An entire database's stored contents"],
            ["Record", "Individual rows or fields, such as only the SSN column"],
        ],
        "explain": "SY0-701 expects you to pick the right encryption granularity: full-disk for lost-device protection, partition/volume for sections of storage, file for individual documents, and database vs. record level for whole databases vs. specific sensitive fields. Finer granularity limits exposure but adds management overhead.",
    },
    {
        "type": "match",
        "q": "Match each cryptographic tool to its description.",
        "pairs": [
            ["Trusted Platform Module (TPM)", "Cryptographic chip on a device motherboard protecting disk encryption keys"],
            ["Hardware security module (HSM)", "Tamper-resistant appliance protecting keys at enterprise/CA scale"],
            ["Key management system", "Centralized software managing key generation, rotation, and revocation"],
            ["Secure enclave", "Isolated coprocessor region keeping keys away from the main OS"],
        ],
        "explain": "Scope is the differentiator: a TPM serves one device, an HSM serves an enterprise or CA, a key management system handles the lifecycle of many keys across systems, and a secure enclave isolates secrets inside a device's processor. Exam questions usually hinge on scale and location.",
    },
    {
        "type": "match",
        "q": "Match each data protection technique to its description.",
        "pairs": [
            ["Steganography", "Conceals a message inside an image or audio file"],
            ["Tokenization", "Substitutes data with a vault-stored value having no mathematical link to the original"],
            ["Data masking", "Displays only a portion of a value, such as the last four digits"],
            ["Hashing", "Produces a one-way, fixed-length digest for integrity checks"],
            ["Salting", "Adds a random value to each password before it is hashed"],
        ],
        "explain": "Steganography, tokenization, and data masking are the three obfuscation methods on the SY0-701 objective, while hashing provides one-way integrity and salting hardens hashes against rainbow tables. Distinguish tokenization (random substitute, vault lookup) from hashing (mathematical one-way digest).",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps for obtaining a CA-signed certificate for a new web server in the correct order.",
        "items": [
            "Generate a public/private key pair on the server",
            "Create a certificate signing request (CSR) containing the public key and identity details",
            "Submit the CSR to a certificate authority",
            "The CA validates the identity and signs the certificate",
            "Install the issued certificate on the web server",
        ],
        "explain": "The key pair must exist first because the CSR carries the public key plus identity information. The CA validates the requester, signs the certificate with its own private key, and the returned certificate is installed on the server — the server's private key never leaves the server during this process.",
    },
]
