TOPIC = {
    "id": "2.1",
    "domain": 2,
    "title": "Compare and contrast common threat actors and motivations.",
    "short": "Threat Actors & Motivations",
}

TERMS = [
    ("Threat actor", "Any individual or group that poses a threat by attempting to access, exfiltrate, or damage an organization's assets"),
    ("Nation-state actor", "Government-sponsored attacker with the highest funding and sophistication; motivated by espionage, war, and data exfiltration"),
    ("Advanced persistent threat (APT)", "Long-term, stealthy intrusion campaign that maintains access over months or years; classically associated with nation-state actors"),
    ("Unskilled attacker (script kiddie)", "Low-sophistication actor who runs pre-made tools and scripts written by others without understanding how they work"),
    ("Hacktivist", "Actor who attacks to promote a philosophical or political cause; tactics include defacement, DDoS, doxxing, and data leaks"),
    ("Insider threat", "Threat from a current or former employee, contractor, or partner with authorized access; can be malicious or unintentional"),
    ("Organized crime", "Professional criminal syndicates motivated almost exclusively by financial gain; run ransomware, fraud, and data-theft operations"),
    ("Shadow IT", "Hardware, software, or cloud services deployed by employees without IT department approval; internal and usually non-malicious"),
    ("Internal threat actor", "Actor operating from inside the organization with some level of legitimate/authorized access (insiders, shadow IT)"),
    ("External threat actor", "Actor outside the organization with no authorized access who must break in (nation-states, organized crime, hacktivists, script kiddies)"),
    ("Resources/funding", "Actor attribute describing the money, tools, and personnel available; nation-states highest, unskilled attackers lowest"),
    ("Level of sophistication/capability", "Actor attribute describing technical skill — from running canned scripts up to developing custom malware and zero-day exploits"),
    ("Data exfiltration", "Motivation/act of stealing data and transferring it out of the organization, often for sale or intelligence value"),
    ("Espionage", "Spying to steal secrets — national intelligence for governments or trade secrets in corporate/industrial espionage"),
    ("Service disruption", "Motivation to take systems or services offline (e.g., DDoS against a website) rather than steal data"),
    ("Blackmail", "Motivation of coercing a victim by threatening to release stolen sensitive information unless demands are met"),
    ("Financial gain", "Profit motive behind ransomware, fraud, and selling stolen data; the defining motivation of organized crime"),
    ("Philosophical/political beliefs", "Ideological motivation to advance a cause or protest; the defining motivation of hacktivists"),
    ("Ethical motivation", "Motivation of authorized (white-hat) hackers who find and responsibly disclose vulnerabilities to improve security"),
    ("Revenge", "Motivation to harm an organization for a perceived wrong; classic driver of disgruntled current or former employees"),
    ("Disruption/chaos", "Motivation to cause damage or outages for their own sake, with no financial or political goal; common for unskilled attackers"),
    ("War (cyberwarfare)", "Motivation of nation-states using cyberattacks against critical infrastructure and military targets to support armed conflict"),
    ("Ransomware-as-a-service (RaaS)", "Organized-crime business model where developers lease ransomware to affiliates in exchange for a share of the profits"),
    ("False flag", "Technique of planting evidence to make an attack look like it came from a different actor; used by nation-states to defeat attribution"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A defense contractor discovers a stealthy intrusion that has quietly harvested weapons-design documents for over a year. Forensics reveal custom malware and previously unknown (zero-day) exploits. Which threat actor is MOST likely responsible?",
        "choices": ["Nation-state actor", "Unskilled attacker", "Hacktivist", "Shadow IT"],
        "answer": 0,
        "explain": "Long-term stealthy access, custom malware, zero-day exploits, and military targets all point to a nation-state actor running an advanced persistent threat (APT) campaign. Unskilled attackers lack the capability, hacktivists seek publicity rather than stealth, and shadow IT is unsanctioned internal technology, not an intrusion.",
    },
    {
        "type": "mc",
        "q": "A teenager downloads an attack tool from an online forum and runs it against their school's website without understanding how it works. Which type of threat actor is this?",
        "choices": ["Organized crime", "Insider threat", "Unskilled attacker", "Nation-state actor"],
        "answer": 2,
        "explain": "An unskilled attacker (script kiddie) uses pre-made tools and scripts written by others without technical understanding. They have low sophistication and minimal funding, but their attacks can still cause real damage because the tools themselves are powerful.",
    },
    {
        "type": "mc",
        "q": "A group defaces a corporation's homepage with slogans protesting the company's environmental record and launches a DDoS attack against its web store. Which threat actor BEST fits this activity?",
        "choices": ["Organized crime", "Hacktivist", "Nation-state actor", "Unskilled attacker"],
        "answer": 1,
        "explain": "Hacktivists attack to promote philosophical or political beliefs, and defacement plus DDoS to publicize a cause is their signature playbook. Organized crime would seek payment, nation-states seek intelligence or wartime advantage, and an unskilled attacker has no consistent ideological message.",
    },
    {
        "type": "mc",
        "q": "A database administrator who learns she is about to be laid off copies the entire customer database to a personal USB drive. Which threat actor does this describe?",
        "choices": ["Insider threat", "Hacktivist", "External nation-state actor", "Shadow IT"],
        "answer": 0,
        "explain": "An insider threat is a current or former employee, contractor, or partner who abuses authorized access. The DBA's legitimate credentials and internal position are what make the theft possible. Shadow IT is also internal but refers to unapproved technology, not deliberate data theft.",
    },
    {
        "type": "mc",
        "q": "A group operates a ransomware-as-a-service platform, leasing malware to affiliates and taking a percentage of every ransom paid. Which threat actor does this describe?",
        "choices": ["Hacktivist collective", "Nation-state actor", "Unskilled attacker", "Organized crime"],
        "answer": 3,
        "explain": "Organized crime groups run cybercrime as a profit-driven business, and ransomware-as-a-service is their hallmark business model. Their motivation is financial gain, unlike hacktivists (ideology) or nation-states (espionage/war), and their operations are far too sophisticated for an unskilled attacker.",
    },
    {
        "type": "mc",
        "q": "The marketing department signs up for an unapproved cloud file-sharing service to exchange large files with vendors, bypassing the IT department entirely. What does this represent?",
        "choices": ["Shadow IT", "A malicious insider threat", "An advanced persistent threat", "Data exfiltration by organized crime"],
        "answer": 0,
        "explain": "Shadow IT is technology deployed by employees without IT approval. The users are internal and their intent is productivity, not harm, but unsanctioned services bypass security controls and expand the attack surface. A malicious insider acts with intent to harm, which is absent here.",
    },
    {
        "type": "mc",
        "q": "Which threat actor typically has the GREATEST level of resources and funding?",
        "choices": ["Unskilled attacker", "Hacktivist", "Nation-state actor", "Insider threat"],
        "answer": 2,
        "explain": "Nation-state actors are backed by government budgets, giving them the deepest funding, dedicated personnel, and the ability to develop custom tooling and zero-day exploits. Organized crime is next best funded; hacktivists, insiders, and unskilled attackers generally have far fewer resources.",
    },
    {
        "type": "mc",
        "q": "Which threat actor is characterized by the LOWEST level of sophistication and capability?",
        "choices": ["Organized crime", "Unskilled attacker", "Nation-state actor", "Hacktivist"],
        "answer": 1,
        "explain": "The unskilled attacker (script kiddie) sits at the bottom of the capability scale, relying entirely on tools and scripts built by others. Nation-states sit at the top, organized crime is highly capable and well funded, and hacktivists vary but typically exceed script-kiddie skill.",
    },
    {
        "type": "mc",
        "q": "During an investigation, analysts find that an attacker compressed sensitive files into archives and slowly transferred them out of the network hidden inside DNS queries. Which motivation does this activity BEST demonstrate?",
        "choices": ["Service disruption", "Data exfiltration", "Disruption/chaos", "Ethical hacking"],
        "answer": 1,
        "explain": "Staging data and covertly moving it out of the organization is data exfiltration — the goal is stealing the information itself. Service disruption and chaos aim to break things rather than steal quietly, and an ethical hacker operates with authorization and does not smuggle data out.",
    },
    {
        "type": "mc",
        "q": "A rival company secretly pays a hacker to steal a manufacturer's proprietary product designs and formulas. Which motivation does this BEST describe?",
        "choices": ["Espionage", "Revenge", "Blackmail", "Service disruption"],
        "answer": 0,
        "explain": "Stealing trade secrets for a competitor is corporate (industrial) espionage — spying to gain a competitive or intelligence advantage. Nation-states conduct the political version of the same activity. There is no coercion (blackmail), personal grievance (revenge), or outage (service disruption) involved.",
    },
    {
        "type": "mc",
        "q": "A bank's online banking portal is knocked offline for hours by a massive DDoS attack. No data is stolen and no ransom demand is ever made. Which motivation BEST explains the attack?",
        "choices": ["Data exfiltration", "Financial gain", "Service disruption", "Espionage"],
        "answer": 2,
        "explain": "The attackers' objective was to make the service unavailable — that is service disruption. Nothing was stolen, ruling out data exfiltration and espionage, and the absence of any ransom or profit mechanism rules out financial gain.",
    },
    {
        "type": "mc",
        "q": "An attacker breaches an executive's mailbox, then emails the executive threatening to publish embarrassing messages unless a cryptocurrency payment is made. Which motivation does this BEST illustrate?",
        "choices": ["Blackmail", "Espionage", "Philosophical/political beliefs", "Service disruption"],
        "answer": 0,
        "explain": "Blackmail is coercing a victim by threatening to release stolen sensitive information unless demands are met. It differs from simple financial gain in that the leverage is the threat of exposure; espionage would involve quietly using the information rather than confronting the victim with it.",
    },
    {
        "type": "mc",
        "q": "Which motivation is MOST characteristic of organized crime threat actors?",
        "choices": ["Philosophical/political beliefs", "Financial gain", "War", "Ethical disclosure"],
        "answer": 1,
        "explain": "Organized crime exists to make money — through ransomware, payment fraud, and selling stolen data on dark-web markets. Political beliefs drive hacktivists, war drives nation-states in conflict, and ethical motivation belongs to authorized security researchers.",
    },
    {
        "type": "mc",
        "q": "A security researcher discovers a vulnerability in a vendor's product, reports it privately through the vendor's bug bounty program, and waits for a patch before discussing it publicly. Which motivation does this describe?",
        "choices": ["Blackmail", "Espionage", "Ethical", "Revenge"],
        "answer": 2,
        "explain": "This is the ethical motivation: authorized (white-hat) hacking with responsible disclosure to improve security, often rewarded through bug bounty programs. Threatening to release the flaw unless paid would instead be blackmail, and selling it to a foreign government would support espionage.",
    },
    {
        "type": "mc",
        "q": "Two weeks after being fired, a former system administrator logs in with credentials that were never disabled and deletes critical servers. Which motivation BEST explains this attack?",
        "choices": ["Revenge", "Espionage", "Philosophical/political beliefs", "War"],
        "answer": 0,
        "explain": "A terminated employee striking back at the organization for a perceived wrong is the classic revenge scenario, and ex-employees with lingering access are a well-known insider threat. The failure to disable accounts at offboarding is what made the attack possible.",
    },
    {
        "type": "mc",
        "q": "An attacker randomly wipes systems and triggers outages at organizations they have no relationship with, bragging online that they did it 'for fun.' Which motivation does this BEST describe?",
        "choices": ["Financial gain", "Disruption/chaos", "Espionage", "Blackmail"],
        "answer": 1,
        "explain": "Disruption/chaos is destruction for its own sake — there is no profit motive, no cause being promoted, and no data being sought. This motivation is commonly associated with unskilled attackers seeking thrills or notoriety.",
    },
    {
        "type": "mc",
        "q": "As military forces invade a neighboring country, coordinated cyberattacks simultaneously disable that country's power grid and government communications. Which motivation does this BEST represent?",
        "choices": ["Financial gain", "Ethical", "War", "Blackmail"],
        "answer": 2,
        "explain": "Cyberattacks on critical infrastructure conducted in support of armed conflict reflect the war motivation — cyberwarfare used to degrade an adversary's ability to function and fight. Nation-state actors are the actors behind warfare-motivated attacks.",
    },
    {
        "type": "mc",
        "q": "The term 'advanced persistent threat (APT)' is MOST closely associated with which threat actor?",
        "choices": ["Nation-state actor", "Unskilled attacker", "Shadow IT", "Hacktivist"],
        "answer": 0,
        "explain": "APTs are long-duration, stealthy campaigns that require deep funding and expert personnel to maintain undetected access for months or years — capabilities characteristic of nation-state (state-sponsored) actors. Some elite organized crime groups reach APT-level capability, but the exam associates APT primarily with nation-states.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST distinguishes shadow IT from a malicious insider threat?",
        "choices": [
            "Shadow IT is an external actor, while insiders are internal",
            "Shadow IT users typically act without malicious intent, while a malicious insider deliberately causes harm",
            "Shadow IT requires nation-state funding, while insiders are self-funded",
            "Shadow IT only involves hardware, while insiders only abuse software",
        ],
        "answer": 1,
        "explain": "Both are internal, but intent separates them: shadow IT is employees adopting unapproved technology to get work done, creating risk unintentionally, while a malicious insider deliberately abuses authorized access to steal or destroy. Neither is external, and neither is defined by funding or a hardware/software split.",
    },
    {
        "type": "mc",
        "q": "Two different attackers deface websites. One posts manifestos supporting a political movement; the other posts memes to impress friends online. What PRIMARILY differentiates these two threat actors?",
        "choices": ["Their motivation", "Whether they are internal or external", "The attack technique used", "The port numbers they targeted"],
        "answer": 0,
        "explain": "The technique (defacement) is identical; what differs is motivation — philosophical/political beliefs make the first a hacktivist, while notoriety and chaos mark the second as an unskilled attacker. Objective 2.1 tests exactly this skill: classifying actors by motivation and attributes, not just by technique.",
    },
    {
        "type": "mc",
        "q": "Which of the following threat actors is BEST classified as an internal threat?",
        "choices": [
            "A hacktivist collective targeting the company's public website",
            "An employee running an unapproved personal Wi-Fi router in the office",
            "A foreign intelligence service probing the VPN gateway",
            "A criminal gang sending phishing emails to staff",
        ],
        "answer": 1,
        "explain": "The employee with an unauthorized router is shadow IT — an internal actor with legitimate access acting without approval. Hacktivists, nation-state intelligence services, and organized crime gangs all attack from outside the organization, making them external threat actors.",
    },
    {
        "type": "mc",
        "q": "Analysts attribute an attack to a hacktivist group, but deeper investigation reveals the tooling and infrastructure belong to a foreign intelligence agency imitating that group. What is this deception technique called?",
        "choices": ["Shadow IT", "Ransomware-as-a-service", "A false flag operation", "An unintentional insider threat"],
        "answer": 2,
        "explain": "A false flag operation plants evidence to make an attack appear to come from a different actor, and nation-states use it to defeat attribution and avoid political consequences. It is one reason attributing attacks to specific actors is difficult.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Hacktivists are primarily motivated by financial gain.",
        "answer": False,
        "explain": "Hacktivists are driven by philosophical or political beliefs — they attack to protest, promote a cause, or embarrass an organization they oppose. Financial gain is the defining motivation of organized crime, not hacktivism.",
    },
    {
        "type": "tf",
        "q": "True or False: An insider threat can be unintentional, such as an employee who accidentally emails a sensitive file to the wrong recipient.",
        "answer": True,
        "explain": "Insider threats include both malicious insiders (theft, sabotage, revenge) and unintentional insiders whose carelessness — misdirected emails, weak passwords, falling for phishing — exposes the organization. Both types originate from people with authorized access.",
    },
    {
        "type": "tf",
        "q": "True or False: Because unskilled attackers use tools they do not understand, their attacks are incapable of causing serious damage.",
        "answer": False,
        "explain": "The tools themselves are powerful even if the operator is not — freely available ransomware kits, DDoS booters, and exploit frameworks let unskilled attackers cause real outages and losses. Low sophistication describes the actor, not the potential impact.",
    },
    {
        "type": "tf",
        "q": "True or False: Shadow IT introduces risk even though the employees involved usually have no malicious intent.",
        "answer": True,
        "explain": "Shadow IT users are trying to be productive, but unapproved apps, cloud services, and devices bypass patching, monitoring, and data-protection controls. That expands the attack surface and can expose data without anyone intending harm.",
    },
    {
        "type": "tf",
        "q": "True or False: Nation-state actors are typically the most sophisticated and best-funded category of threat actor.",
        "answer": True,
        "explain": "Backed by government budgets and professional intelligence services, nation-states can develop custom malware, stockpile zero-day exploits, and sustain multi-year APT campaigns. No other actor category matches their combined funding and capability.",
    },
    {
        "type": "tf",
        "q": "True or False: An attack motivated by war would typically be carried out by an organized crime group seeking ransom payments.",
        "answer": False,
        "explain": "War as a motivation belongs to nation-state actors, who use cyberattacks against infrastructure and military targets to support armed conflict. Organized crime is motivated by financial gain — ransom payments — not by warfare objectives.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "A low-skill attacker who relies on pre-made hacking tools and scripts written by others is commonly called a script ______. (type your answer)",
        "answers": ["kiddie", "kiddy", "script kiddie", "kiddies"],
        "explain": "'Script kiddie' is the common name for the unskilled attacker in SY0-701 — someone who runs other people's tools without understanding them. They rank lowest in sophistication and funding among the threat actor categories.",
    },
    {
        "type": "fill",
        "q": "Hardware, software, or cloud services used inside an organization without the IT department's knowledge or approval is called ______ IT. (type your answer)",
        "answers": ["shadow", "shadow it"],
        "explain": "Shadow IT is technology adopted outside official channels. It is an internal threat vector that is usually non-malicious, but it bypasses security controls such as patching, backups, and monitoring.",
    },
    {
        "type": "fill",
        "q": "A prolonged, stealthy intrusion campaign in which a well-funded attacker maintains undetected access for months or years is known as an ______ (give the three-letter acronym).",
        "answers": ["apt", "advanced persistent threat", "a.p.t."],
        "explain": "APT stands for advanced persistent threat: 'advanced' for the sophisticated tooling, 'persistent' for the long-term foothold, and 'threat' for the well-resourced adversary — most often a nation-state actor.",
    },
    {
        "type": "fill",
        "q": "The unauthorized transfer of stolen data out of an organization's network is called data ______. (type your answer)",
        "answers": ["exfiltration", "exfil", "data exfiltration"],
        "explain": "Data exfiltration is both an attacker goal and a motivation category in objective 2.1 — the data itself is the prize, whether it is sold for profit, used for espionage, or leveraged for blackmail.",
    },
    {
        "type": "fill",
        "q": "A threat actor who attacks organizations to advance a political or social cause is called a ______. (type your answer)",
        "answers": ["hacktivist", "hactivist", "hacktivists"],
        "explain": "A hacktivist (hacker + activist) is motivated by philosophical/political beliefs. Typical tactics include website defacement, DDoS attacks, doxxing, and leaking stolen documents to embarrass the target.",
    },
    {
        "type": "fill",
        "q": "Threatening to publicly release a victim's stolen sensitive information unless a payment is made is a motivation known as ______. (type your answer)",
        "answers": ["blackmail", "extortion"],
        "explain": "Blackmail (a form of extortion) uses the threat of exposure as leverage. Double-extortion ransomware combines it with financial gain: attackers encrypt data and also threaten to leak it if the ransom is not paid.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each threat actor to its MOST typical motivation.",
        "pairs": [
            ["Nation-state actor", "Espionage"],
            ["Organized crime", "Financial gain"],
            ["Hacktivist", "Philosophical/political beliefs"],
            ["Disgruntled former employee", "Revenge"],
            ["Unskilled attacker", "Disruption/chaos"],
        ],
        "explain": "Motivation is the fastest way to identify an actor on the exam: nation-states spy (espionage, plus war), organized crime profits, hacktivists push a cause, fired employees retaliate, and script kiddies cause chaos for thrills or notoriety.",
    },
    {
        "type": "match",
        "q": "Match each threat actor to its defining attributes.",
        "pairs": [
            ["Nation-state actor", "External; highest funding and sophistication"],
            ["Organized crime", "External; well-funded, profit-driven operations"],
            ["Insider threat", "Internal; abuses authorized access"],
            ["Shadow IT", "Internal; unapproved technology, non-malicious intent"],
            ["Unskilled attacker", "External; low funding and low capability"],
        ],
        "explain": "SY0-701 compares actors along internal/external, resources/funding, and sophistication/capability. Nation-states top both scales, organized crime is close behind, insiders and shadow IT are the internal categories, and script kiddies rank lowest in skill and money.",
    },
    {
        "type": "match",
        "q": "Match each scenario to the motivation it BEST demonstrates.",
        "pairs": [
            ["Ransomware demands cryptocurrency to decrypt files", "Financial gain"],
            ["Stolen fighter-jet blueprints delivered to a foreign government", "Espionage"],
            ["DDoS floods a government portal to protest a new law", "Philosophical/political beliefs"],
            ["Attacker threatens to leak stolen HR records unless paid", "Blackmail"],
            ["Ex-employee deletes payroll data after being fired", "Revenge"],
            ["Wartime attack disables an enemy nation's power grid", "War"],
        ],
        "explain": "Read the attacker's goal, not the technique: profit means financial gain, stolen secrets for a government means espionage, protest means political beliefs, coercion via threatened exposure means blackmail, retaliation means revenge, and supporting armed conflict means war.",
    },
]
