TOPIC = {
    "id": "2.2",
    "domain": 2,
    "title": "Explain common threat vectors and attack surfaces.",
    "short": "Threat Vectors & Attack Surfaces",
}

TERMS = [
    ("Threat vector", "The path or means an attacker uses to gain access to a target — email, USB drives, open ports, phone calls, supply chain, etc."),
    ("Attack surface", "The sum of all points where an attacker could try to enter or extract data; reduced by disabling services, closing ports, and removing unused software"),
    ("Message-based vector", "Attacks delivered through email, SMS, or instant messaging platforms — the most common delivery channel for phishing and malware links"),
    ("Image-based vector", "Malicious code delivered inside image files, such as scripts embedded in SVG files or payloads hidden with steganography"),
    ("File-based vector", "Malware delivered inside files such as PDFs, Office documents with macros, or executables shared via email or downloads"),
    ("Removable device vector", "Attacks using USB flash drives or other portable media, e.g., malware-laden drives dropped in parking lots for victims to plug in"),
    ("Client-based software", "Software monitoring/management that requires an agent installed on each endpoint; the agent itself adds to the attack surface and must be patched"),
    ("Agentless", "Monitoring or scanning performed without installing software on the endpoint, typically over the network using credentials or APIs"),
    ("Unsupported system", "Hardware, OS, or application past end-of-life that no longer receives security patches, leaving known vulnerabilities permanently exposed"),
    ("Evil twin", "A rogue wireless access point configured to mimic a legitimate SSID so victims connect through the attacker's hardware"),
    ("Bluesnarfing", "Unauthorized access to data (contacts, messages) on a device over a Bluetooth connection"),
    ("Open service port", "A listening network port exposing a service to connection attempts; each unnecessary open port expands the attack surface"),
    ("Default credentials", "Factory-set usernames/passwords (e.g., admin/admin) left unchanged on devices, allowing trivial unauthorized access"),
    ("Supply chain attack", "Compromising a target indirectly through its MSPs, vendors, or suppliers — e.g., tampered hardware, poisoned software updates, or a breached service provider"),
    ("Managed service provider (MSP)", "Third party that remotely manages a customer's IT; its privileged access makes it a high-value supply chain target"),
    ("Phishing", "Fraudulent email designed to trick recipients into revealing credentials, clicking malicious links, or opening malicious attachments"),
    ("Vishing", "Voice phishing — social engineering conducted over phone calls, often spoofing caller ID to appear legitimate"),
    ("Smishing", "Phishing conducted via SMS text messages, typically containing malicious links or requests for sensitive information"),
    ("Business email compromise (BEC)", "Attack using a compromised or spoofed legitimate business email account (often an executive's) to authorize fraudulent payments or data transfers"),
    ("Pretexting", "Social engineering using an invented scenario (the pretext) to justify a request, e.g., posing as an auditor who 'needs' records"),
    ("Impersonation", "Pretending to be another person or role — IT support, a delivery driver, an executive — to gain trust and access"),
    ("Watering hole attack", "Compromising a third-party website the target group is known to visit, so victims are infected when they browse a trusted site"),
    ("Brand impersonation", "Using a trusted company's logos, branding, and look-and-feel in fake emails or websites to make an attack appear legitimate"),
    ("Typosquatting", "Registering domain names that are common misspellings of legitimate sites (e.g., gooogle.com) to capture mistyped traffic"),
    ("Misinformation", "False information spread without malicious intent by people who believe it is true"),
    ("Disinformation", "False information created and spread deliberately to deceive, often as part of an influence campaign"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An employee receives an unsolicited email with an 'unpaid invoice' attachment that installs malware when opened. Which threat vector was used to deliver this attack?",
        "choices": ["Email (message-based)", "Removable device", "Voice call", "Watering hole"],
        "answer": 0,
        "explain": "The delivery path was an email message carrying a malicious attachment, making this a message-based (email) threat vector. Email remains the most common malware delivery channel. A watering hole would require compromising a website the victim visits, and removable device attacks use physical media like USB drives.",
    },
    {
        "type": "mc",
        "q": "A security analyst discovers that an SVG graphic uploaded to the company forum contains embedded JavaScript that executes when users view the image. Which threat vector does this represent?",
        "choices": ["File-based", "Message-based", "Image-based", "Voice call"],
        "answer": 2,
        "explain": "Malicious code hidden inside image files — such as scripts embedded in SVG files or payloads concealed with steganography — is the image-based threat vector. It is dangerous because users and some filters treat images as harmless. Generic documents and executables fall under the file-based vector.",
    },
    {
        "type": "mc",
        "q": "A user downloads a PDF from a file-sharing site; the PDF exploits a vulnerability in the reader software to execute code. Which threat vector is this?",
        "choices": ["Image-based", "File-based", "Open service ports", "Default credentials"],
        "answer": 1,
        "explain": "Malware delivered inside a document — PDFs, Office files with macros, or executables — is the file-based threat vector. The file itself is the delivery mechanism. Image-based attacks specifically use image formats, and the other options are not delivery mechanisms for a downloaded document.",
    },
    {
        "type": "mc",
        "q": "An attacker phones an employee, claims to be from the IT help desk, and asks the employee to read back the MFA code just sent to their phone. Which attack is being performed?",
        "choices": ["Smishing", "Phishing", "Business email compromise", "Vishing"],
        "answer": 3,
        "explain": "Social engineering conducted over a voice call is vishing (voice phishing). The attacker also uses impersonation of IT support, but the delivery vector — a phone call — makes this vishing. Smishing uses SMS texts and phishing uses email.",
    },
    {
        "type": "mc",
        "q": "Several USB flash drives labeled 'Payroll Q3' are found scattered in the company parking lot. A curious employee plugs one into a workstation and malware executes. Which threat vector was used?",
        "choices": ["Removable device", "Unsecure wired network", "File-based only, not a vector", "Supply chain"],
        "answer": 0,
        "explain": "The classic USB drop attack uses the removable device threat vector: attackers rely on curiosity to get malicious media plugged into a trusted machine. Disabling autorun and blocking unauthorized USB storage are common mitigations. Supply chain attacks come through vendors and providers, not planted media.",
    },
    {
        "type": "mc",
        "q": "A vulnerability management tool scans endpoints over the network using provided credentials, with no software installed on the targets. Which approach is this?",
        "choices": ["Client-based", "Agentless", "Watering hole", "Open service port scanning only"],
        "answer": 1,
        "explain": "Scanning or monitoring without installing anything on the endpoint is agentless — it typically authenticates over the network or via APIs. Client-based approaches install an agent on each device, which gives deeper visibility but adds software that itself must be secured and patched.",
    },
    {
        "type": "mc",
        "q": "An endpoint monitoring product requires installing an agent on every laptop. From an attack surface perspective, what is a key security consideration of this client-based approach?",
        "choices": [
            "The agent software itself can contain vulnerabilities and must be patched",
            "Agents eliminate the need for OS patching",
            "Client-based tools cannot collect detailed endpoint data",
            "Agents automatically close all open service ports",
        ],
        "answer": 0,
        "explain": "Every agent installed on an endpoint is additional software that expands the attack surface — a vulnerable agent can itself become the entry point. Client-based tools actually provide deeper visibility than agentless ones, but they add maintenance and patching burden; they do nothing to replace OS patching or close ports.",
    },
    {
        "type": "mc",
        "q": "A hospital still runs a critical application on Windows Server 2008, which no longer receives vendor security updates. What BEST describes the threat vector this creates?",
        "choices": ["Default credentials", "Open service ports", "Unsupported system", "Client-based software"],
        "answer": 2,
        "explain": "An OS or application past end-of-life is an unsupported system: newly discovered vulnerabilities will never be patched, so the exposure only grows over time. Mitigations include isolation/segmentation, compensating controls, or migration — but the vector itself is the lack of vendor support.",
    },
    {
        "type": "mc",
        "q": "At an airport, an attacker sets up an access point broadcasting the SSID 'Free_Airport_WiFi' that mimics the legitimate hotspot, then captures traffic from travelers who connect. What is this attack called?",
        "choices": ["Bluesnarfing", "Watering hole", "Typosquatting", "Evil twin"],
        "answer": 3,
        "explain": "A rogue AP that imitates a legitimate SSID so victims connect through attacker-controlled hardware is an evil twin — a classic unsecure wireless network vector. Bluesnarfing is Bluetooth data theft, a watering hole compromises a website, and typosquatting relies on mistyped domain names.",
    },
    {
        "type": "mc",
        "q": "A visitor in a building lobby plugs a laptop into an unused, active Ethernet wall jack and gains access to the internal network. Which threat vector was exploited?",
        "choices": ["Unsecure wireless network", "Unsecure wired network", "Bluetooth", "Supply chain"],
        "answer": 1,
        "explain": "An active, unprotected network jack is an unsecure wired network vector — physical access to the port grants network access. Mitigations include disabling unused ports and using 802.1X port-based network access control so devices must authenticate before joining the LAN.",
    },
    {
        "type": "mc",
        "q": "An attacker within radio range connects to an employee's phone over Bluetooth and copies the contact list without the owner's knowledge. What is this attack called?",
        "choices": ["Bluesnarfing", "Evil twin", "Smishing", "Vishing"],
        "answer": 0,
        "explain": "Bluesnarfing is the unauthorized access and theft of data over a Bluetooth connection, illustrating why Bluetooth is listed as an unsecure network threat vector. An evil twin is a rogue Wi-Fi AP; smishing and vishing are social engineering over SMS and voice, not Bluetooth data theft.",
    },
    {
        "type": "mc",
        "q": "A port scan of an internet-facing server shows TCP port 23 accepting connections, though the admin team never uses Telnet. What should the security team recognize this as?",
        "choices": [
            "Normal — Telnet is required for remote management",
            "A default credential issue",
            "An unnecessary open service port expanding the attack surface",
            "A watering hole attack in progress",
        ],
        "answer": 2,
        "explain": "Every listening port exposes a service to attack; an unused Telnet service (TCP 23, which also transmits in cleartext) is an unnecessary open service port that should be disabled. Closing unneeded ports and services is a core attack surface reduction step. Nothing here indicates credentials or a watering hole compromise.",
    },
    {
        "type": "mc",
        "q": "A newly installed network camera is compromised within days because it was still using the manufacturer's published admin username and password. Which threat vector does this illustrate?",
        "choices": ["Open service ports", "Default credentials", "Unsupported system", "Removable device"],
        "answer": 1,
        "explain": "Factory-set default credentials are widely published and are among the first things attackers try, especially against IoT and network devices. Changing default passwords immediately upon deployment is the mitigation. The device may also have open ports, but the specific weakness exploited was the unchanged credentials.",
    },
    {
        "type": "mc",
        "q": "Attackers breach a company that remotely administers IT for hundreds of small businesses, then use its remote-management tools to deploy ransomware to all of those customers. Which threat vector does this describe?",
        "choices": [
            "Supply chain via a managed service provider (MSP)",
            "Business email compromise",
            "Watering hole",
            "Unsecure wireless network",
        ],
        "answer": 0,
        "explain": "Compromising an MSP gives attackers privileged access into every customer the MSP manages — a supply chain attack with massive reach. This is why MSP access should be tightly monitored and limited. BEC targets email-based payment fraud, and a watering hole compromises a website victims visit.",
    },
    {
        "type": "mc",
        "q": "A company discovers that network appliances purchased from a hardware supplier shipped with malicious firmware pre-installed before delivery. Which threat vector is this?",
        "choices": ["Removable device", "File-based", "Unsupported systems", "Supply chain"],
        "answer": 3,
        "explain": "Tampering that occurs at a vendor or supplier before the product ever reaches the customer is a supply chain attack — the trust placed in suppliers, vendors, and MSPs becomes the path in. Mitigations include vendor assessments, trusted sourcing, and firmware/integrity verification on receipt.",
    },
    {
        "type": "mc",
        "q": "Thousands of organizations are breached after installing a digitally signed software update for a commercial product — attackers had inserted malicious code into the software maker's build process before release. Which supply chain vector does this describe?",
        "choices": [
            "Managed service provider (MSP)",
            "Vendor",
            "Supplier",
            "Watering hole",
        ],
        "answer": 1,
        "explain": "When malicious code arrives inside the product itself — a legitimate, signed software update — the vendor is the supply chain vector (the SolarWinds pattern). An MSP attack instead abuses a provider's remote administrative access to client networks, and a supplier attack tampers with upstream components before the product is built. A watering hole compromises a website victims visit, not an update channel.",
    },
    {
        "type": "mc",
        "q": "The finance director receives an email that appears to come from the CEO's actual corporate account, urgently instructing a wire transfer to a new vendor account. There are no links or attachments. What type of attack is this?",
        "choices": ["Brand impersonation", "Watering hole", "Business email compromise", "Typosquatting"],
        "answer": 2,
        "explain": "Business email compromise (BEC) uses a compromised or convincingly spoofed legitimate business account — often an executive's — to authorize fraudulent payments. It relies on authority and urgency rather than malware, which is why it evades many technical filters. Brand impersonation mimics an outside company's branding, not an internal executive.",
    },
    {
        "type": "mc",
        "q": "An attacker calls the records department claiming to be an external auditor conducting a compliance review and requests copies of financial statements. The fabricated 'audit' story is an example of what technique?",
        "choices": ["Pretexting", "Typosquatting", "Watering hole", "Disinformation"],
        "answer": 0,
        "explain": "Pretexting is inventing a believable scenario (the pretext) that gives the attacker a plausible reason for their request — here, a fake compliance audit. It often combines with impersonation and vishing. Disinformation is deliberately spreading false narratives to a broad audience, not a one-on-one access ploy.",
    },
    {
        "type": "mc",
        "q": "Attackers want to breach several defense contractors. Instead of attacking them directly, they compromise an industry association website the contractors' engineers visit regularly and plant an exploit there. What type of attack is this?",
        "choices": ["Typosquatting", "Watering hole", "Brand impersonation", "Supply chain via MSP"],
        "answer": 1,
        "explain": "A watering hole attack compromises a legitimate third-party site the target group is known to frequent, infecting victims through a site they trust — like predators waiting at a water source. Typosquatting relies on mistyped URLs, and brand impersonation fakes a company's look rather than compromising a real trusted site.",
    },
    {
        "type": "mc",
        "q": "Users receive a professional-looking email using a well-known bank's exact logo, colors, and formatting, directing them to a fake login page styled identically to the bank's real site. Which technique makes this phishing attack more convincing?",
        "choices": ["Pretexting", "Misinformation", "Vishing", "Brand impersonation"],
        "answer": 3,
        "explain": "Brand impersonation copies a trusted company's logos, branding, and design so fraudulent messages and sites appear legitimate. It is a common amplifier for phishing and credential harvesting. Pretexting is a fabricated scenario, and vishing would involve a voice call rather than email.",
    },
    {
        "type": "mc",
        "q": "An attacker registers 'paypa1.com' and 'paypall.com' and hosts credential-harvesting pages there, catching users who mistype the real address. What is this technique called?",
        "choices": ["Typosquatting", "Watering hole", "Business email compromise", "Evil twin"],
        "answer": 0,
        "explain": "Typosquatting (URL hijacking) registers domains that are near-misses of legitimate ones to capture users who mistype or don't look closely at a link. It frequently supports phishing and brand impersonation. An evil twin is a rogue wireless AP, not a lookalike domain.",
    },
    {
        "type": "mc",
        "q": "A nation-state group creates fake news articles and coordinated social media accounts to deliberately spread a false story and influence public opinion before an election. What is this called?",
        "choices": ["Misinformation", "Impersonation", "Disinformation", "Pretexting"],
        "answer": 2,
        "explain": "Disinformation is false information created and spread deliberately to deceive — intent is the defining feature. Misinformation is false information shared by people who genuinely believe it is true. Both are listed human vectors on SY0-701 because influence campaigns can target organizations as well as the public.",
    },
    {
        "type": "mc",
        "q": "Employees receive a message through the company's Teams/Slack workspace from a compromised coworker account containing a link to a 'shared project file' that harvests credentials. Which threat vector delivered this attack?",
        "choices": ["Instant messaging (message-based)", "Email (message-based)", "Image-based", "Removable device"],
        "answer": 0,
        "explain": "Attacks delivered through chat platforms are the instant messaging variant of the message-based threat vector. Users often trust internal IM more than email, and IM traffic may bypass email security gateways — which is exactly why attackers pivot to it after compromising one account.",
    },
    {
        "type": "mc",
        "q": "A person wearing a copier company uniform and fake badge tells the receptionist they are 'here for scheduled printer maintenance' and is escorted into the office, where they access an unlocked workstation. Which human vector is the person primarily using?",
        "choices": ["Business email compromise", "Impersonation", "Typosquatting", "Smishing"],
        "answer": 1,
        "explain": "Impersonation is pretending to be someone with a legitimate role — a technician, delivery driver, or IT support — to gain trust and physical or logical access. The uniform and badge sell the false identity. BEC, typosquatting, and smishing are all remote/technical vectors, not in-person deception.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Smishing is a phishing attack delivered through SMS text messages.",
        "answer": True,
        "explain": "Smishing = SMS + phishing: fraudulent text messages containing malicious links or requests for sensitive data. Its cousins are vishing (voice calls) and standard phishing (email). Knowing which channel maps to which term is a frequent exam point.",
    },
    {
        "type": "tf",
        "q": "True or False: Misinformation is always spread with deliberate intent to deceive.",
        "answer": False,
        "explain": "Intent is what separates the two terms: misinformation is false information spread by people who believe it is true, while disinformation is deliberately fabricated and distributed to deceive. The exam expects you to distinguish them by the spreader's intent.",
    },
    {
        "type": "tf",
        "q": "True or False: Agentless monitoring requires installing a software agent on every endpoint being monitored.",
        "answer": False,
        "explain": "That describes client-based monitoring. Agentless approaches work without installing anything on the target, typically using network-based scans, credentials, or APIs. Agentless deployment is faster and adds no software to the endpoint's attack surface, though agents usually provide deeper visibility.",
    },
    {
        "type": "tf",
        "q": "True or False: An application that has reached end-of-life and no longer receives vendor patches remains a growing security risk even if it currently works fine.",
        "answer": True,
        "explain": "Unsupported systems and applications never receive fixes for newly discovered vulnerabilities, so their exposure increases over time even though functionality is unchanged. Compensating controls like network segmentation and isolation can reduce — but not eliminate — the risk until the system is replaced.",
    },
    {
        "type": "tf",
        "q": "True or False: Typosquatting relies on users mistyping or misreading a web address.",
        "answer": True,
        "explain": "Typosquatting registers lookalike domains (misspellings, extra letters, swapped characters) so that mistyped URLs or careless link-reading lands victims on attacker-controlled sites. It is frequently combined with brand impersonation to make the fake site convincing.",
    },
    {
        "type": "tf",
        "q": "True or False: Because Bluetooth only works over short distances, it is not considered a meaningful threat vector on the SY0-701 exam.",
        "answer": False,
        "explain": "Bluetooth is explicitly listed as an unsecure network threat vector in objective 2.2. Attacks like bluesnarfing (data theft) and exploitation of Bluetooth stack vulnerabilities are possible whenever an attacker is within radio range — short range limits, but does not eliminate, the risk.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Social engineering conducted over a telephone call — often with spoofed caller ID — is called ______. (type your answer)",
        "answers": ["vishing", "voice phishing"],
        "explain": "Vishing (voice phishing) uses phone calls to extract credentials, MFA codes, or payments, frequently combined with impersonation of IT support, banks, or executives. Caller ID spoofing makes the call appear to come from a trusted number.",
    },
    {
        "type": "fill",
        "q": "A phishing attempt delivered as a text message with a malicious link is called ______. (type your answer)",
        "answers": ["smishing", "sms phishing"],
        "explain": "Smishing is phishing over SMS (Short Message Service). Common lures include fake package-delivery notices, bank alerts, and MFA prompts. Because texts feel personal and urgent, click rates can be higher than email phishing.",
    },
    {
        "type": "fill",
        "q": "Registering a domain like 'micros0ft.com' to capture users who mistype the real site is called ______. (type your answer)",
        "answers": ["typosquatting", "typo squatting", "url hijacking"],
        "explain": "Typosquatting (also called URL hijacking) exploits typing mistakes and inattentive reading of URLs. The lookalike domain can host credential-harvesting pages, malware, or ad fraud, and is often paired with brand impersonation.",
    },
    {
        "type": "fill",
        "q": "An attack in which a spoofed or compromised executive email account is used to instruct staff to make fraudulent wire transfers is known as ______ (give the full term or its 3-letter abbreviation).",
        "answers": ["business email compromise", "bec"],
        "explain": "Business email compromise (BEC) abuses the trust placed in legitimate business email accounts, typically requesting payments or sensitive data with urgency and authority. Because BEC messages usually contain no malware or links, technical filters often miss them — verification procedures for payment changes are the key defense.",
    },
    {
        "type": "fill",
        "q": "Compromising a website that a targeted group of victims is known to visit, so they are infected when they browse it, is called a ______ attack. (type your answer)",
        "answers": ["watering hole", "waterhole", "watering-hole"],
        "explain": "A watering hole attack poisons a legitimate site the targets already trust and visit, sidestepping the need to lure them anywhere. It is favored for targeting specific industries or organizations whose browsing habits are predictable.",
    },
    {
        "type": "fill",
        "q": "The factory-set username and password shipped on a device, which should be changed immediately at deployment, are called ______ credentials. (type your answer)",
        "answers": ["default", "default credentials", "factory default"],
        "explain": "Default credentials are published in vendor documentation and compiled into attacker wordlists, so any device still using them is trivially compromised. Changing them at deployment is a baseline hardening step, especially for IoT and network equipment.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each social engineering attack to its delivery method or defining trait.",
        "pairs": [
            ["Phishing", "Fraudulent email with malicious links or attachments"],
            ["Vishing", "Deceptive phone call, often with spoofed caller ID"],
            ["Smishing", "Malicious link sent in an SMS text message"],
            ["Business email compromise", "Spoofed/compromised executive account requests a wire transfer"],
            ["Pretexting", "Invented scenario used to justify a request for data"],
        ],
        "explain": "Sort these by channel and technique: phishing = email, vishing = voice, smishing = SMS, BEC = abuse of a legitimate business account for fraud, pretexting = the fabricated backstory that makes any of these requests believable.",
    },
    {
        "type": "match",
        "q": "Match each scenario to the threat vector it represents.",
        "pairs": [
            ["Malware-laden USB drive left in a parking lot", "Removable device"],
            ["Unused Telnet service listening on a server", "Open service ports"],
            ["Router still using admin/admin login", "Default credentials"],
            ["End-of-life OS that no longer gets patches", "Unsupported system"],
            ["Evil twin access point at a coffee shop", "Unsecure wireless network"],
        ],
        "explain": "Each scenario maps to a distinct attack surface entry point from objective 2.2: physical media, exposed services, unchanged factory logins, unpatched EOL systems, and rogue Wi-Fi. Identifying the vector tells you which hardening step applies.",
    },
    {
        "type": "match",
        "q": "Match each attack or technique to its description.",
        "pairs": [
            ["Watering hole", "Compromise a site the target group regularly visits"],
            ["Typosquatting", "Register misspelled versions of a legitimate domain"],
            ["Brand impersonation", "Copy a company's logos and design to look legitimate"],
            ["Disinformation", "Deliberately fabricated falsehoods spread to deceive"],
            ["Misinformation", "False information shared without malicious intent"],
        ],
        "explain": "Watering holes poison trusted sites; typosquatting exploits typing errors; brand impersonation borrows a trusted look; disinformation is intentional deception while misinformation is spread in good faith. Intent is the discriminator between the last two.",
    },
]
