TOPIC = {
    "id": "2.5",
    "domain": 2,
    "title": "Explain the purpose of mitigation techniques used to secure the enterprise.",
    "short": "Mitigation Techniques",
}

TERMS = [
    ("Segmentation", "Dividing a network into smaller zones (VLANs, subnets, firewalled segments) so a compromise in one zone cannot spread freely to others; also limits lateral movement"),
    ("Access control list (ACL)", "Ordered list of rules on a router, firewall, or file system that permits or denies access based on attributes such as source/destination IP, port, or user identity"),
    ("Permissions", "Rights assigned to users or groups that define what actions (read, write, execute, modify) they may perform on a file, folder, or resource"),
    ("Application allow list", "Policy that permits ONLY explicitly approved applications to run; everything not on the list is blocked by default (opposite of a deny/block list)"),
    ("Application block/deny list", "Policy that blocks specific known-bad applications while allowing everything else to run; weaker than an allow list because new malware is not yet listed"),
    ("Isolation", "Separating a system or process from other systems entirely (air gap, sandbox, quarantine VLAN) so it cannot interact with — or infect — the rest of the environment"),
    ("Patching", "Applying vendor-supplied updates to fix known vulnerabilities and bugs; the primary mitigation for exploitation of unpatched software"),
    ("Encryption", "Converting plaintext to ciphertext so data is unreadable without the key; protects confidentiality of data at rest (FDE) and in transit (TLS/VPN)"),
    ("Full-disk encryption (FDE)", "Encrypting an entire drive (e.g., BitLocker) so data at rest is unreadable if the device is lost or stolen; keys often protected by a TPM"),
    ("Monitoring", "Continuous collection and review of logs, alerts, and metrics (SIEM, IDS) to detect malicious activity and policy violations as they occur"),
    ("Least privilege", "Granting users, processes, and services only the minimum access required to perform their job function — nothing more"),
    ("Configuration enforcement", "Automatically verifying and correcting system settings against a secure baseline (e.g., via group policy, MDM, posture checks) so hosts cannot drift out of compliance"),
    ("Secure baseline", "The documented, approved set of secure configuration settings that all systems of a given type must match; the reference point for configuration enforcement"),
    ("Decommissioning", "Formally retiring a system at end of life: removing it from the network, revoking credentials/certificates, and sanitizing or destroying its storage media"),
    ("Data sanitization", "Securely removing data from media before disposal or reuse (wiping/overwriting, degaussing, or physical destruction) so it cannot be recovered"),
    ("Hardening", "Reducing a system's attack surface by securing its configuration: patching, disabling unneeded services/ports, removing default credentials and unnecessary software"),
    ("Endpoint protection", "Security software installed on hosts — antivirus/anti-malware and EDR — that detects, blocks, and responds to malicious code and behavior on the endpoint"),
    ("Endpoint detection and response (EDR)", "Advanced endpoint agent that continuously records host activity, detects suspicious behavior, and enables investigation and automated response"),
    ("Host-based firewall", "Software firewall running on an individual host that filters inbound/outbound traffic for that machine only (e.g., Windows Defender Firewall)"),
    ("Host-based intrusion prevention system (HIPS)", "Software on a host that inspects traffic and system activity and actively BLOCKS detected attacks in real time (a HIDS only detects and alerts)"),
    ("Disabling ports/protocols", "Turning off unneeded network services and closing unused ports (e.g., disabling Telnet in favor of SSH) to shrink the attack surface"),
    ("Default password changes", "Replacing vendor-set factory credentials on new devices immediately, because default logins are publicly documented and routinely tried by attackers"),
    ("Removal of unnecessary software", "Uninstalling applications and services a system does not need, eliminating their vulnerabilities and reducing what must be patched"),
    ("Attack surface", "The sum of all points where an attacker could try to enter or extract data from a system; hardening aims to make it as small as possible"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "After ransomware on one workstation spread to servers across the entire flat network, the security team wants to ensure a future infection cannot move laterally between departments. Which mitigation BEST accomplishes this?",
        "choices": ["Segmentation", "Patching", "Default password changes", "Monitoring"],
        "answer": 0,
        "explain": "Segmentation divides the network into zones (VLANs/subnets separated by firewalls or ACLs) so traffic between departments is restricted and lateral movement is contained. Patching prevents initial exploitation but does not stop spread across an open network, and monitoring detects rather than blocks movement.",
    },
    {
        "type": "mc",
        "q": "A network administrator configures a router rule set that denies inbound traffic from a specific IP range and permits established sessions only. What has the administrator configured?",
        "choices": ["An application allow list", "An access control list (ACL)", "A host-based intrusion prevention system", "Configuration enforcement"],
        "answer": 1,
        "explain": "An ACL is an ordered set of permit/deny rules evaluated against traffic attributes such as source IP, destination IP, and port. An application allow list controls which programs may execute on a host, not network traffic, and a HIPS actively blocks detected attack patterns rather than static rule matches.",
    },
    {
        "type": "mc",
        "q": "A user in the marketing department can open files in the finance share. The security team wants to restrict each department's file access to only what its members need. Which two concepts apply MOST directly?",
        "choices": [
            "Permissions and least privilege",
            "Isolation and decommissioning",
            "Encryption and monitoring",
            "Segmentation and patching",
        ],
        "answer": 0,
        "explain": "File/folder permissions define who can read, write, or modify a resource, and least privilege is the principle that users get only the minimum access their job requires. Isolation and segmentation are network/system separation techniques, and encryption protects confidentiality but does not by itself limit an authorized user's access.",
    },
    {
        "type": "mc",
        "q": "A hospital wants to guarantee that ONLY a specific, approved set of applications can execute on clinical workstations; anything else must be blocked by default. Which mitigation should be deployed?",
        "choices": ["Application block list", "Antivirus signatures", "Application allow list", "Host-based firewall"],
        "answer": 2,
        "explain": "An allow list (whitelist) is default-deny for software: only explicitly approved executables run, which blocks unknown malware automatically. A block list only stops applications already known to be bad, antivirus depends on detecting malice, and a host-based firewall filters network traffic rather than program execution.",
    },
    {
        "type": "mc",
        "q": "An analyst discovers an infected laptop actively beaconing to a command-and-control server. What is the BEST immediate mitigation for this specific host?",
        "choices": ["Apply the latest patches", "Isolate the host from the network", "Enable full-disk encryption", "Review its file permissions"],
        "answer": 1,
        "explain": "Isolation (quarantine) cuts the compromised host off from the network, stopping C2 communication and preventing further spread while the incident is investigated. Patching and permission reviews are preventive controls that do not help once compromise has occurred, and encrypting the disk does nothing against active malware.",
    },
    {
        "type": "mc",
        "q": "A vulnerability scan shows hundreds of hosts are exploitable via a flaw the vendor fixed three months ago. What is the MOST effective mitigation?",
        "choices": ["Deploy a HIPS on every host", "Enable monitoring and alerting", "Segment the vulnerable hosts", "Apply the vendor patch"],
        "answer": 3,
        "explain": "Patching removes the vulnerability itself, which is the definitive fix for a known, vendor-remediated flaw. HIPS, segmentation, and monitoring are compensating controls that reduce or detect exploitation but leave the underlying weakness in place.",
    },
    {
        "type": "mc",
        "q": "A company laptop containing customer records was stolen from a car. Which mitigation would have BEST protected the confidentiality of the data on the stolen device?",
        "choices": ["Host-based firewall", "Full-disk encryption", "Application allow list", "Least privilege"],
        "answer": 1,
        "explain": "Full-disk encryption renders data at rest unreadable without the decryption key, so a thief with physical possession of the drive cannot recover the records. Firewalls and allow lists protect a running system, and least privilege limits logical access — none protect data on a drive an attacker physically controls.",
    },
    {
        "type": "mc",
        "q": "A security team wants to detect unusual authentication patterns and policy violations across the enterprise by aggregating and correlating logs from servers, firewalls, and endpoints. Which mitigation technique is this?",
        "choices": ["Configuration enforcement", "Monitoring", "Segmentation", "Hardening"],
        "answer": 1,
        "explain": "Monitoring is the ongoing collection and analysis of logs and alerts — typically centralized in a SIEM — to detect malicious activity. It is a detective control; configuration enforcement, segmentation, and hardening are preventive measures that do not themselves provide visibility into events.",
    },
    {
        "type": "mc",
        "q": "A database administrator's account was compromised, and the attacker used its domain-admin rights to take over the network. Which principle, if followed, would have limited the damage?",
        "choices": ["Least privilege", "Decommissioning", "Isolation", "Default password changes"],
        "answer": 0,
        "explain": "Least privilege means every account holds only the minimum rights needed for its role; a DBA account should not have had domain-admin privileges. When a least-privileged account is compromised, the blast radius is small. The other options do not address over-privileged accounts.",
    },
    {
        "type": "mc",
        "q": "An organization uses group policy and an MDM platform to automatically detect and revert any workstation setting that drifts from the approved secure baseline. Which mitigation technique is being used?",
        "choices": ["Monitoring", "Application allow listing", "Configuration enforcement", "Patching"],
        "answer": 2,
        "explain": "Configuration enforcement continuously compares systems against the secure baseline and corrects noncompliant settings automatically. Monitoring would only observe and alert on drift, patching fixes software flaws rather than settings, and allow listing controls which programs execute.",
    },
    {
        "type": "mc",
        "q": "An old file server is being retired. Which set of actions BEST describes proper decommissioning?",
        "choices": [
            "Power it off and store it in a closet with data intact",
            "Remove it from the network, revoke its credentials and certificates, and sanitize its drives",
            "Reformat the drives with a quick format and resell the server",
            "Move it to a guest VLAN and disable monitoring for it",
        ],
        "answer": 1,
        "explain": "Proper decommissioning removes the asset from the network and inventory, revokes any accounts/certificates tied to it, and sanitizes or destroys storage so data cannot be recovered. A quick format leaves recoverable data, and powering off or relocating a server with live data and credentials leaves residual risk.",
    },
    {
        "type": "mc",
        "q": "During hardening, an administrator disables Telnet and FTP on all servers and closes their listening ports, requiring SSH and SFTP instead. What is the PRIMARY security purpose of this change?",
        "choices": [
            "To reduce the attack surface and eliminate insecure cleartext protocols",
            "To enforce least privilege on user accounts",
            "To segment the servers from the user VLAN",
            "To satisfy the application allow list policy",
        ],
        "answer": 0,
        "explain": "Disabling unneeded ports and insecure protocols shrinks the attack surface — fewer listening services means fewer entry points — and replaces cleartext protocols (Telnet, FTP) with encrypted ones (SSH, SFTP). This is host hardening, not account privilege management or network segmentation.",
    },
    {
        "type": "mc",
        "q": "An attacker logs in to a newly installed network camera using 'admin/admin' found in the vendor's public documentation. Which hardening step would have prevented this?",
        "choices": ["Removal of unnecessary software", "Installing endpoint protection", "Changing default passwords", "Enabling full-disk encryption"],
        "answer": 2,
        "explain": "Factory default credentials are published in manuals and attacker wordlists, so changing them immediately upon deployment is a fundamental hardening step — especially on IoT and embedded devices. The other options do not address a valid login with known credentials.",
    },
    {
        "type": "mc",
        "q": "Which hardening technique detects an exploit attempt against a host and actively blocks the malicious traffic in real time, rather than only generating an alert?",
        "choices": ["Host-based IDS (HIDS)", "Host-based IPS (HIPS)", "SIEM correlation", "Access control list"],
        "answer": 1,
        "explain": "A HIPS sits inline on the host and prevents attacks by blocking malicious activity as it is detected. A HIDS is detective only — it alerts but does not block. SIEMs correlate and alert centrally, and ACLs apply static permit/deny rules rather than dynamic attack detection.",
    },
    {
        "type": "mc",
        "q": "A workstation build includes a game, an unused PDF toolbar, and an old Java runtime that no business application requires. Why does hardening call for removing this software?",
        "choices": [
            "It frees licenses for reuse elsewhere",
            "Unused software still contains vulnerabilities that expand the attack surface",
            "It is required before an ACL can be applied",
            "Removal automatically patches the operating system",
        ],
        "answer": 1,
        "explain": "Every installed application is code that can contain exploitable vulnerabilities and must be patched; removing software that serves no business purpose eliminates those risks entirely and shrinks the attack surface. License savings are a side benefit, not the security purpose.",
    },
    {
        "type": "mc",
        "q": "An administrator wants each individual laptop to filter its own inbound connections — blocking all except remote-management traffic from the IT subnet — even when the laptop is off the corporate network. Which control fits BEST?",
        "choices": ["Network firewall at the perimeter", "Host-based firewall", "Application allow list", "Network segmentation"],
        "answer": 1,
        "explain": "A host-based firewall runs on the endpoint itself and enforces traffic rules wherever the device goes, including home and public networks. A perimeter firewall or segmentation only protects devices while they are behind it, and an allow list governs program execution, not network connections.",
    },
    {
        "type": "mc",
        "q": "As part of endpoint hardening, a company deploys an agent to every laptop that continuously records process activity, detects suspicious behavior such as credential dumping, and can automatically kill processes and quarantine files. What was deployed?",
        "choices": ["A SIEM", "A host-based firewall", "Endpoint detection and response (EDR)", "A configuration baseline scanner"],
        "answer": 2,
        "explain": "EDR is modern endpoint protection: it records host telemetry, detects malicious behavior (not just known signatures), and supports automated response like process termination and quarantine. A SIEM aggregates logs centrally but has no host agent response, and a firewall filters traffic rather than analyzing process behavior.",
    },
    {
        "type": "mc",
        "q": "Researchers need to detonate suspected malware samples safely. Which mitigation allows the malware to run without any possibility of reaching production systems?",
        "choices": ["An isolated sandbox environment", "A segmented VLAN with ACLs", "An application block list", "A HIPS on production servers"],
        "answer": 0,
        "explain": "Isolation — a sandbox or air-gapped analysis environment — completely separates the malware from production so it cannot interact with real systems. A segmented VLAN still has controlled connectivity and is weaker than true isolation; block lists and HIPS try to stop malware on live systems rather than contain deliberate execution.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST distinguishes segmentation from isolation?",
        "choices": [
            "Segmentation divides the network into controlled zones; isolation completely separates a system from other systems",
            "Segmentation encrypts traffic; isolation blocks applications",
            "Segmentation applies only to hosts; isolation applies only to networks",
            "They are identical techniques with different names",
        ],
        "answer": 0,
        "explain": "Segmentation splits a network into zones with restricted, policy-controlled communication between them, while isolation removes connectivity altogether (quarantine, sandbox, air gap). Both limit spread, but isolation is the more absolute separation.",
    },
    {
        "type": "mc",
        "q": "A financial firm requires that all data moving between its branch offices over the internet be unreadable to anyone intercepting it. Which mitigation meets this requirement?",
        "choices": ["Access control lists on the routers", "Encryption of data in transit (VPN/TLS)", "Network monitoring with a SIEM", "Configuration enforcement"],
        "answer": 1,
        "explain": "Encryption in transit — an IPSec VPN between sites or TLS for applications — protects confidentiality of data crossing untrusted networks so intercepted traffic is ciphertext. ACLs control who may connect, and monitoring detects events, but neither makes intercepted data unreadable.",
    },
    {
        "type": "mc",
        "q": "A legacy medical device cannot be patched because the vendor no longer supports it, yet it must remain in service. Which is the BEST compensating mitigation?",
        "choices": [
            "Place it on an isolated/segmented network with strict ACLs limiting who can reach it",
            "Install an application allow list agent on it",
            "Decommission it immediately",
            "Change its default password and take no further action",
        ],
        "answer": 0,
        "explain": "When patching is impossible, segmentation/isolation with tight ACLs is the classic compensating control: the vulnerable device is walled off so attackers cannot reach it. Legacy devices often cannot run modern agents, decommissioning conflicts with the requirement to keep it in service, and a password change alone leaves the unpatched flaw reachable.",
    },
    {
        "type": "mc",
        "q": "New servers are deployed from an image that already has unneeded services disabled, default accounts removed, the OS fully patched, and endpoint protection installed. Which term BEST describes this overall process?",
        "choices": ["Decommissioning", "Hardening", "Monitoring", "Isolation"],
        "answer": 1,
        "explain": "Hardening is the umbrella process of reducing a system's attack surface through secure configuration: patching, disabling unnecessary services and ports, removing default credentials and software, and installing protective agents. The image encodes a hardened secure baseline for every new deployment.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: An application allow list is generally more restrictive than an application block list, because anything not explicitly approved is denied.",
        "answer": True,
        "explain": "Allow listing is default-deny: only approved software runs, so brand-new malware is blocked even though nobody has identified it yet. Block listing is default-allow and only stops applications already known to be bad, which is why the exam treats allow lists as the stronger control.",
    },
    {
        "type": "tf",
        "q": "True or False: A host-based intrusion prevention system (HIPS) can only generate alerts; it cannot block malicious activity.",
        "answer": False,
        "explain": "The 'P' in HIPS means prevention — it actively blocks detected attacks in real time. It is the host-based intrusion DETECTION system (HIDS) that is limited to detecting and alerting without blocking.",
    },
    {
        "type": "tf",
        "q": "True or False: Monitoring is a preventive control that stops attacks before they occur.",
        "answer": False,
        "explain": "Monitoring is a detective control: it identifies and alerts on suspicious activity so responders can act, but it does not itself block anything. Preventive mitigations from this objective include patching, ACLs, allow lists, encryption, and hardening.",
    },
    {
        "type": "tf",
        "q": "True or False: Proper decommissioning includes sanitizing or destroying storage media so residual data cannot be recovered.",
        "answer": True,
        "explain": "Retired drives frequently still contain sensitive data, so decommissioning requires sanitization — secure overwriting, degaussing, or physical destruction — along with removing the asset from the network and revoking its credentials and certificates. Simply deleting files or quick-formatting leaves data recoverable.",
    },
    {
        "type": "tf",
        "q": "True or False: Granting a service account full administrator rights 'just in case it needs them later' is consistent with the principle of least privilege.",
        "answer": False,
        "explain": "Least privilege means granting only the minimum rights currently required — never extra access for hypothetical future needs. Over-privileged service accounts are a favorite target because compromising one hands the attacker all of those unnecessary rights.",
    },
    {
        "type": "tf",
        "q": "True or False: Full-disk encryption protects the confidentiality of data on a laptop that is lost or stolen while powered off.",
        "answer": True,
        "explain": "With FDE (such as BitLocker), everything on the disk is ciphertext at rest, so a thief who removes the drive or boots another OS recovers nothing readable without the key. Note that FDE does not protect data on a running, unlocked system — that requires access controls and endpoint protection.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Dividing a network into separate zones such as VLANs so that a compromise in one zone cannot spread freely to others is called network ______. (type your answer)",
        "answers": ["segmentation", "segmenting", "network segmentation"],
        "explain": "Segmentation breaks a flat network into controlled zones separated by firewalls, routers, or VLAN ACLs. It limits lateral movement, contains outbreaks, and lets you apply different security policies to different zones.",
    },
    {
        "type": "fill",
        "q": "The security principle stating that users and processes should receive only the minimum access needed to do their jobs is called least ______. (type your answer)",
        "answers": ["privilege", "privileges", "least privilege"],
        "explain": "Least privilege minimizes the damage any single compromised or misused account can cause. It is enforced through careful permission assignment and regular access reviews to remove rights that are no longer needed.",
    },
    {
        "type": "fill",
        "q": "Applying vendor-released software updates to fix known vulnerabilities is called ______. (type your answer)",
        "answers": ["patching", "patch management", "applying patches"],
        "explain": "Patching directly removes known vulnerabilities and is the primary defense against exploitation of unpatched systems. A formal patch management process tests and deploys updates promptly after release.",
    },
    {
        "type": "fill",
        "q": "A software mitigation that permits ONLY pre-approved applications to execute and blocks all others by default is an application ______ list. (type your answer)",
        "answers": ["allow", "allowlist", "allow list", "white", "whitelist"],
        "explain": "An application allow list (formerly whitelist) is default-deny for execution: unknown or unauthorized programs — including new malware — simply will not run. Its inverse, the block/deny list, only stops software explicitly identified as bad.",
    },
    {
        "type": "fill",
        "q": "The host-based hardening component that inspects activity on a single machine and actively blocks detected attacks is abbreviated ______. (type the acronym)",
        "answers": ["hips", "h.i.p.s", "host-based intrusion prevention system", "host based intrusion prevention system"],
        "explain": "HIPS stands for host-based intrusion prevention system. Unlike a HIDS, which only detects and alerts, a HIPS sits inline on the host and prevents the malicious activity from succeeding.",
    },
    {
        "type": "fill",
        "q": "The process of reducing a system's attack surface by disabling unneeded services, changing default passwords, patching, and removing unnecessary software is called ______. (type your answer)",
        "answers": ["hardening", "system hardening", "host hardening"],
        "explain": "Hardening secures a system's configuration so it exposes as few attack vectors as possible. SY0-701 lists encryption, endpoint protection, host-based firewalls, HIPS, disabling ports/protocols, default password changes, and removing unnecessary software as hardening techniques.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each mitigation technique to its primary purpose.",
        "pairs": [
            ["Segmentation", "Limit lateral movement between network zones"],
            ["Patching", "Remove known software vulnerabilities"],
            ["Encryption", "Protect data confidentiality at rest and in transit"],
            ["Monitoring", "Detect malicious activity through logs and alerts"],
            ["Decommissioning", "Securely retire systems at end of life"],
        ],
        "explain": "Each mitigation answers a different risk: segmentation contains spread, patching eliminates known flaws, encryption keeps intercepted or stolen data unreadable, monitoring provides detection, and decommissioning ensures retired assets and their data cannot come back to haunt you.",
    },
    {
        "type": "match",
        "q": "Match each hardening technique to the risk it addresses.",
        "pairs": [
            ["Default password changes", "Attackers logging in with published factory credentials"],
            ["Disabling ports/protocols", "Exposure through unneeded listening services"],
            ["Removal of unnecessary software", "Vulnerabilities in applications no one uses"],
            ["Host-based firewall", "Unwanted network connections to an individual host"],
            ["Installation of endpoint protection", "Malware executing on the host"],
        ],
        "explain": "Hardening pairs each configuration step with a specific exposure: defaults are publicly known, every open port and installed program is potential attack surface, the host firewall filters the machine's own traffic, and endpoint protection (AV/EDR) catches malicious code that reaches the host.",
    },
    {
        "type": "match",
        "q": "Match each scenario to the mitigation technique it describes.",
        "pairs": [
            ["An infected laptop is moved to a quarantine network with no access to anything", "Isolation"],
            ["A firewall rule set permits only HTTPS from the branch subnet to the web server", "Access control list (ACL)"],
            ["Group policy automatically reverts registry settings that drift from the baseline", "Configuration enforcement"],
            ["HR staff get read-only access to payroll reports instead of full control", "Permissions / least privilege"],
        ],
        "explain": "Quarantining a compromised host is isolation; permit/deny traffic rules form an ACL; automatic correction back to a secure baseline is configuration enforcement; and scoping file rights to the minimum needed applies permissions under the least privilege principle.",
    },
]
