TOPIC = {
    "id": "3.1",
    "domain": 3,
    "title": "Compare and contrast security implications of different architecture models.",
    "short": "Architecture Models",
}

TERMS = [
    ("Cloud responsibility matrix", "Document defining which security tasks the cloud provider handles and which the customer handles; the split shifts with the service model (IaaS/PaaS/SaaS)"),
    ("Hybrid cloud", "Architecture combining on-premises/private infrastructure with public cloud; adds complexity: consistent policies, identity, and monitoring must span both environments"),
    ("Third-party vendors", "External providers in the cloud supply chain; require vendor risk assessments, contracts/SLAs, and monitoring because their weaknesses become your weaknesses"),
    ("Infrastructure as code (IaC)", "Defining and deploying infrastructure through machine-readable definition files (e.g., templates/playbooks); enables consistent, repeatable, auditable deployments"),
    ("Serverless", "Cloud model (function as a service) where the provider manages all servers and scaling; customer secures only code, identities, and data — but is provider-dependent"),
    ("Microservices", "Application built as many small, loosely coupled services communicating over APIs; scales and deploys independently but greatly expands the API attack surface"),
    ("Physical isolation", "Separating a system or network with no physical connectivity to other networks; strongest form is the air gap"),
    ("Air-gapped network", "Network physically disconnected from all other networks; data moves only by removable media, which becomes the main attack vector (e.g., infected USB drives)"),
    ("Logical segmentation", "Separating networks with software constructs such as VLANs or subnets rather than physical separation; enforced by switch/firewall configuration"),
    ("Software-defined networking (SDN)", "Architecture separating the network control plane from the data (forwarding) plane, enabling centralized, programmable network management"),
    ("On-premises", "Infrastructure hosted in an organization's own facility; gives full control over data and security but the organization bears all cost, staffing, and maintenance"),
    ("Centralized architecture", "All processing/control in one location; simpler to secure and manage but creates a single point of failure"),
    ("Decentralized architecture", "Processing/control distributed across multiple locations or nodes; more resilient but harder to manage and monitor consistently"),
    ("Containerization", "OS-level virtualization where apps share the host kernel but run in isolated user spaces; lightweight and fast, but a kernel compromise affects all containers"),
    ("Virtualization", "Running multiple virtual machines, each with its own OS, on shared hardware via a hypervisor; risks include VM escape and VM sprawl"),
    ("VM escape", "Attack in which malicious code breaks out of a virtual machine to attack the hypervisor or other VMs on the same host"),
    ("Internet of Things (IoT)", "Network-connected embedded devices (sensors, cameras, appliances); often ship with weak default credentials and receive few or no security updates"),
    ("ICS/SCADA", "Industrial control systems and supervisory control and data acquisition — systems that monitor/control physical industrial processes; prioritize availability and are hard to patch"),
    ("Real-time operating system (RTOS)", "OS that guarantees processing within strict deterministic time constraints; used in embedded/industrial devices where a delay (e.g., from scanning agents) is unacceptable"),
    ("Embedded system", "Computer built into a larger device for a dedicated function (e.g., medical device, vehicle ECU); constrained compute, long lifespan, and often an inability to patch"),
    ("High availability", "Designing systems to maximize uptime through redundancy and failover, often measured against uptime targets such as 99.999% (five nines)"),
    ("Resilience", "A system's ability to withstand faults or attacks and recover quickly to a working state"),
    ("Scalability", "Ability to increase (or decrease) capacity to match demand; cloud elasticity scales automatically, on-premises requires buying hardware"),
    ("Risk transference", "Shifting risk to a third party, such as a cloud provider (per the responsibility matrix) or a cybersecurity insurance policy"),
    ("Ease of recovery", "How quickly an architecture can be restored after failure; virtualization/IaC allow rapid redeployment from snapshots or definition files"),
    ("Compute", "Processing capacity consideration; constrained devices (IoT/embedded) may lack the compute to run encryption or endpoint agents, while cloud offers near-unlimited compute"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company moving to IaaS wants to know who must patch the guest operating systems on its cloud virtual machines. Which document defines this division of security duties?",
        "choices": ["Service level agreement (SLA)", "Responsibility matrix", "Acceptable use policy", "Statement of work"],
        "answer": 1,
        "explain": "The cloud (shared) responsibility matrix maps each security task to either the provider or the customer for a given service model. In IaaS, the provider secures the physical hosts and hypervisor while the customer patches guest OSs, applications, and data. An SLA defines service levels like uptime, not the security task split.",
    },
    {
        "type": "mc",
        "q": "An organization keeps sensitive workloads in its own data center but bursts seasonal workloads to a public cloud provider. Which security concern is MOST specific to this hybrid architecture?",
        "choices": [
            "Inability to patch the on-premises servers",
            "Maintaining consistent security policies and identity across both environments",
            "Lack of physical control over the on-premises hardware",
            "The public cloud cannot scale to meet seasonal demand",
        ],
        "answer": 1,
        "explain": "Hybrid clouds add complexity: authentication, monitoring, and security policy must be applied consistently across on-premises and cloud, and data moving between them must be protected. The organization does have physical control of its own data center, and elasticity is a cloud strength, not a weakness.",
    },
    {
        "type": "mc",
        "q": "A company relies on a SaaS vendor for payroll. Which practice BEST addresses the risk introduced by this third-party dependency?",
        "choices": [
            "Air-gapping the payroll network",
            "Ongoing vendor risk assessments and contractual security requirements",
            "Installing endpoint agents on the vendor's servers",
            "Rewriting the payroll application as microservices",
        ],
        "answer": 1,
        "explain": "With third-party vendors you cannot directly control their infrastructure, so risk is managed through due diligence: vendor assessments, contracts/SLAs with security requirements, right-to-audit clauses, and ongoing monitoring. You cannot install your own agents on a SaaS provider's systems, and air-gapping defeats the purpose of SaaS.",
    },
    {
        "type": "mc",
        "q": "A DevOps team deploys identical, pre-approved cloud environments by running template files through an automated pipeline. Which architecture concept does this describe?",
        "choices": ["Software-defined networking", "Serverless computing", "Infrastructure as code", "Containerization"],
        "answer": 2,
        "explain": "Infrastructure as code (IaC) defines infrastructure in machine-readable template/definition files so environments are deployed consistently and repeatably. This reduces configuration drift and human error — but a flaw in the template is replicated into every deployment, so templates must be reviewed and version-controlled.",
    },
    {
        "type": "mc",
        "q": "A developer uploads individual functions that run only when triggered by events; the cloud provider handles all server provisioning, scaling, and OS patching. Which model is this?",
        "choices": ["Serverless", "On-premises virtualization", "Thick-client architecture", "Bare-metal hosting"],
        "answer": 0,
        "explain": "Serverless (function as a service) executes code on demand while the provider fully manages the underlying servers and their patching. The customer's security focus narrows to the function code, its permissions, and its data — but the trade-off is heavy dependency on (and limited visibility into) the provider.",
    },
    {
        "type": "mc",
        "q": "An application is decomposed into dozens of small, independently deployed services that communicate over APIs. What is the PRIMARY security implication of this design?",
        "choices": [
            "The application can no longer scale individual components",
            "A much larger attack surface of service-to-service APIs that must be authenticated and monitored",
            "All services fail if one service fails, creating a single point of failure",
            "The services cannot be updated without redeploying the whole application",
        ],
        "answer": 1,
        "explain": "Microservices multiply the number of network-exposed APIs, so each inter-service call needs authentication, authorization, and encryption, and monitoring becomes more complex. Independent scaling and independent deployment are the model's benefits, and loose coupling actually reduces single-point-of-failure risk — the opposite of the distractors.",
    },
    {
        "type": "mc",
        "q": "A defense contractor stores classified data on a network with no physical connection of any kind to other networks. Which architecture concept is this?",
        "choices": ["Logical segmentation", "Air gap", "Screened subnet", "Software-defined networking"],
        "answer": 1,
        "explain": "An air gap is the strongest form of physical isolation — no cables or wireless links connect the network to any other. Logical segmentation (VLANs) still shares physical infrastructure. Remember the residual risk: removable media and portable devices can still carry malware across an air gap, as Stuxnet demonstrated.",
    },
    {
        "type": "mc",
        "q": "A network administrator uses VLANs on shared switches to separate the accounting department from guest Wi-Fi traffic. Which concept does this illustrate?",
        "choices": ["Physical isolation", "Air gapping", "Logical segmentation", "Risk transference"],
        "answer": 2,
        "explain": "VLANs create logical segmentation: traffic is separated in software while sharing the same physical switches and cabling. It is flexible and cheap but depends on correct configuration — a misconfigured trunk or VLAN-hopping attack can defeat it, unlike true physical isolation.",
    },
    {
        "type": "mc",
        "q": "In software-defined networking (SDN), which two functions are separated?",
        "choices": [
            "The control plane and the data (forwarding) plane",
            "The application layer and the presentation layer",
            "Encryption and authentication",
            "The public cloud and the private cloud",
        ],
        "answer": 0,
        "explain": "SDN decouples the control plane (decisions about where traffic goes) from the data plane (the actual forwarding), placing control in centralized, programmable software. This enables rapid, automated network changes — but the SDN controller becomes a high-value target: compromise it and you control the entire network.",
    },
    {
        "type": "mc",
        "q": "Compared with cloud hosting, which statement BEST describes the security trade-off of an on-premises architecture?",
        "choices": [
            "Full control over data and hardware, but the organization bears all costs, staffing, and maintenance responsibility",
            "Lower upfront cost, but no control over physical security",
            "Automatic elasticity, but shared responsibility for patching",
            "No responsibility for patching, but higher latency",
        ],
        "answer": 0,
        "explain": "On-premises gives the organization complete control and visibility — attractive for strict regulatory or data-sovereignty needs — but it must fund the hardware (capital expense), hire the expertise, and handle every security task itself. Elasticity and shifting responsibility to a provider are cloud characteristics.",
    },
    {
        "type": "mc",
        "q": "A retailer runs all inventory processing on one central mainframe at headquarters; every store depends on it. What is the main security implication of this centralized design?",
        "choices": [
            "It is impossible to apply consistent security policy",
            "The mainframe is a single point of failure whose outage stops every store",
            "Each store must independently secure its own copy of the data",
            "Monitoring is more difficult than in a distributed design",
        ],
        "answer": 1,
        "explain": "Centralized architectures are easier to secure, monitor, and manage consistently — but everything depends on the central system, so it is a single point of failure and a concentrated target. Decentralized designs trade that risk for harder, less consistent management across many nodes.",
    },
    {
        "type": "mc",
        "q": "Which statement accurately compares containers with virtual machines?",
        "choices": [
            "Containers each include a full guest operating system, making them heavier than VMs",
            "Containers share the host OS kernel, so a kernel compromise can affect every container on the host",
            "VMs share a single kernel, so hypervisor patches are unnecessary",
            "Containers cannot be deployed faster than VMs",
        ],
        "answer": 1,
        "explain": "Containers virtualize at the OS level: they share the host kernel and isolate only user space, which makes them lightweight and fast to deploy but means weaker isolation — a kernel exploit or container escape threatens all containers on that host. VMs each run a full guest OS on a hypervisor, giving stronger isolation at higher overhead.",
    },
    {
        "type": "mc",
        "q": "An administrator discovers dozens of forgotten, unpatched virtual machines that were spun up for old projects and never decommissioned. Which virtualization problem is this?",
        "choices": ["VM escape", "Resource reuse", "VM sprawl", "Live migration"],
        "answer": 2,
        "explain": "VM sprawl occurs because VMs are so easy to create that they proliferate without lifecycle management, leaving unpatched, unmonitored machines as easy targets. The fix is governance: an approval process, inventory/asset tracking, and decommissioning procedures. VM escape is an isolation-breaking attack, not a management failure.",
    },
    {
        "type": "mc",
        "q": "Smart cameras, thermostats, and badge readers on the corporate network still use vendor default passwords and have no update mechanism. Which architecture category do these devices belong to, and what is the classic mitigation?",
        "choices": [
            "SDN devices; replace the controller",
            "IoT devices; change default credentials and isolate them on their own network segment",
            "High-availability nodes; add a load balancer",
            "IaC artifacts; re-run the deployment template",
        ],
        "answer": 1,
        "explain": "IoT devices are embedded, network-connected devices notorious for weak default credentials, weak or absent patching, and limited compute for security controls. Standard mitigations are changing defaults, disabling unneeded services, and placing IoT on a segmented network so a compromised device cannot reach critical systems.",
    },
    {
        "type": "mc",
        "q": "A water utility's SCADA system monitors and controls pumps across the region. Which security priority and constraint MOST distinguish this environment from ordinary IT systems?",
        "choices": [
            "Confidentiality is paramount, and patches are applied daily",
            "Availability is paramount, and patching is difficult because downtime or an untested patch could disrupt a physical process",
            "Integrity is irrelevant because the data is not sensitive",
            "The systems are always cloud-hosted, so the provider handles patching",
        ],
        "answer": 1,
        "explain": "ICS/SCADA environments control physical processes, so availability and safety outrank confidentiality — an outage can shut down water, power, or manufacturing. Components run legacy software that may lack vendor patches entirely, and any patch requires careful testing and scheduled downtime, so these networks are typically isolated/segmented instead of frequently patched.",
    },
    {
        "type": "mc",
        "q": "Why do industrial and medical devices often run a real-time operating system (RTOS)?",
        "choices": [
            "It provides the strongest built-in malware protection of any OS",
            "It guarantees processing occurs within strict, deterministic time constraints",
            "It automatically applies security patches without downtime",
            "It allows unlimited multitasking of user applications",
        ],
        "answer": 1,
        "explain": "An RTOS is designed for deterministic, time-critical processing — a control action must complete within its deadline, every time. The security implication is that anything that could introduce delay, such as antivirus scanning or heavyweight patching, is often unacceptable, so RTOS devices depend on network isolation and compensating controls.",
    },
    {
        "type": "mc",
        "q": "A hospital's infusion pumps run vendor firmware that can no longer be updated, yet the pumps must stay in service for years. Which compensating control BEST addresses this inability to patch?",
        "choices": [
            "Install host-based antivirus on each pump",
            "Isolate the pumps on a dedicated, tightly restricted network segment",
            "Migrate the pumps' firmware to a public cloud",
            "Enable automatic OS updates on the pumps",
        ],
        "answer": 1,
        "explain": "When patching is impossible — common with embedded/medical devices — the standard answer is a compensating control: segment or isolate the devices and strictly filter what can reach them. Embedded devices typically lack the compute and vendor support to run antivirus agents, and 'enable updates' contradicts the premise.",
    },
    {
        "type": "mc",
        "q": "A company requires 99.999% uptime for its e-commerce platform. Which architecture consideration does this requirement describe, and how is it typically achieved?",
        "choices": [
            "High availability, achieved through redundancy and automatic failover",
            "Risk transference, achieved through cybersecurity insurance",
            "Ease of deployment, achieved through infrastructure as code",
            "Physical isolation, achieved through an air gap",
        ],
        "answer": 0,
        "explain": "'Five nines' (99.999%) is a high-availability uptime target — about five minutes of downtime per year — met by eliminating single points of failure with redundant components, clustering, load balancing, and automatic failover. Insurance transfers financial risk but does not keep a system running.",
    },
    {
        "type": "mc",
        "q": "During a regional traffic surge, a cloud application automatically adds instances and then releases them when demand drops. Which consideration does this demonstrate?",
        "choices": ["Risk transference", "Scalability (elasticity)", "Patch availability", "Physical isolation"],
        "answer": 1,
        "explain": "Automatically matching capacity to demand is elasticity, the cloud's form of scalability — a key advantage over on-premises, where scaling means purchasing and installing hardware. It supports availability and responsiveness under load, but costs must be monitored since usage-based billing grows with the scale-out.",
    },
    {
        "type": "mc",
        "q": "A CFO compares architectures: one has large upfront hardware purchases; the other has ongoing usage-based operational fees. Which pairing is correct?",
        "choices": [
            "On-premises = capital expenditure; cloud = operational, pay-as-you-go expenditure",
            "Cloud = capital expenditure; on-premises = pay-as-you-go",
            "Both models have identical cost structures",
            "Serverless requires the largest upfront hardware purchase",
        ],
        "answer": 0,
        "explain": "On-premises infrastructure is a capital expense — buy servers, facilities, power, cooling up front and staff to maintain them. Cloud converts this to an operational expense billed on usage. Cost is an explicit 3.1 consideration: cloud lowers entry cost but can grow unpredictably with consumption.",
    },
    {
        "type": "mc",
        "q": "An architecture review notes that new application instances can be stood up in minutes as containers from existing images, whereas the legacy alternative required weeks of hardware procurement and manual configuration. Which consideration favors the container approach?",
        "choices": ["Ease of deployment", "Risk transference", "Inability to patch", "Physical isolation"],
        "answer": 0,
        "explain": "Ease of deployment describes how quickly and simply an architecture can be rolled out. Containers, IaC templates, and cloud services deploy in minutes with consistent configurations, while on-premises hardware requires procurement, installation, and manual setup. Risk transference concerns shifting risk to third parties, not deployment speed.",
    },
    {
        "type": "mc",
        "q": "After a server failure, a team redeploys its entire environment in minutes from version-controlled IaC templates and VM snapshots. Which consideration does this BEST illustrate?",
        "choices": ["Inability to patch", "Ease of recovery", "Risk transference", "Physical isolation"],
        "answer": 1,
        "explain": "Ease of recovery measures how quickly an architecture can be restored after failure. Virtualization (snapshots, migration) and IaC (rebuild from definition files) make recovery dramatically faster than reinstalling physical servers by hand — a major resilience benefit of these models.",
    },
    {
        "type": "mc",
        "q": "A data center design review flags that a site has only one utility feed and no UPS or generators. Which architecture consideration is unaddressed?",
        "choices": ["Compute", "Responsiveness", "Power", "Patch availability"],
        "answer": 2,
        "explain": "Power is a listed consideration: resilient architectures need redundant utility feeds, UPS units for short outages, and generators for extended ones — otherwise power loss defeats every other availability measure. Compute concerns processing capacity, and responsiveness concerns how quickly the system reacts to requests.",
    },
    {
        "type": "mc",
        "q": "A security team wants to run full-disk encryption and an EDR agent on smart sensors, but the devices' processors and memory cannot support them. Which consideration explains the limitation?",
        "choices": ["Ease of deployment", "Compute", "Risk transference", "Availability"],
        "answer": 1,
        "explain": "Compute refers to available processing capacity. Constrained IoT/embedded hardware often cannot run encryption, agents, or other standard controls, forcing reliance on network-level compensating controls like segmentation. In contrast, cloud architectures offer effectively on-demand compute.",
    },
    {
        "type": "mc",
        "q": "While comparing a SaaS suite, a mainstream server OS, and a legacy application whose vendor has gone out of business, a security team asks: 'Does the vendor still release security updates, and how easily can we apply them?' Which architecture consideration are they evaluating?",
        "choices": ["Patch availability", "Risk transference", "Responsiveness", "Ease of deployment"],
        "answer": 0,
        "explain": "Patch availability asks whether a vendor supplies updates at all and how easily they can be applied: SaaS is patched automatically by the provider, mainstream OSs receive routine vendor patches, and abandoned legacy products may receive none — which slides into the related 'inability to patch' consideration and forces compensating controls.",
    },
    {
        "type": "mc",
        "q": "Which architecture characteristic BEST describes 'resilience' as used in objective 3.1?",
        "choices": [
            "The ability of a system to withstand faults or attacks and return quickly to normal operation",
            "The guarantee that data is never read by unauthorized parties",
            "The speed at which new features are coded",
            "The physical distance between redundant data centers",
        ],
        "answer": 0,
        "explain": "Resilience is the capacity to absorb failures and recover rapidly — achieved through redundancy, failover, backups, and tested recovery procedures. It complements availability (staying up) by focusing on how well the system bounces back when something does go wrong. Confidentiality is a separate CIA property.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: In a SaaS model, the customer is responsible for patching the application and the underlying operating system.",
        "answer": False,
        "explain": "In SaaS the provider manages everything from hardware up through the application itself — the customer's responsibilities shrink to their data, user accounts, and access configuration. Customer patching of the guest OS applies to IaaS, not SaaS.",
    },
    {
        "type": "tf",
        "q": "True or False: Logical segmentation with VLANs provides the same level of isolation assurance as an air-gapped network.",
        "answer": False,
        "explain": "VLANs separate traffic in software on shared physical infrastructure, so misconfiguration or VLAN-hopping attacks can breach the boundary. An air gap has no physical connectivity at all, making it a far stronger (though less convenient) isolation control.",
    },
    {
        "type": "tf",
        "q": "True or False: Because containers share the host operating system kernel, they provide weaker isolation between workloads than virtual machines do.",
        "answer": True,
        "explain": "Each VM has its own guest OS separated by the hypervisor, while containers share one kernel and isolate only user space. That makes containers lightweight and fast, but a kernel vulnerability or container-escape flaw can expose every container on the host.",
    },
    {
        "type": "tf",
        "q": "True or False: ICS/SCADA environments generally prioritize availability over confidentiality.",
        "answer": True,
        "explain": "Industrial control systems run physical processes — power, water, manufacturing — where an outage causes real-world harm, so keeping the process running is the top priority. This is the reverse of many IT systems, where confidentiality of data often ranks first.",
    },
    {
        "type": "tf",
        "q": "True or False: A serverless architecture eliminates the customer's security responsibilities entirely.",
        "answer": False,
        "explain": "Serverless shifts server and OS management to the provider, but the customer still must secure function code, dependencies, secrets, permissions, and data. Insecure code or over-privileged functions remain fully exploitable in a serverless design.",
    },
    {
        "type": "tf",
        "q": "True or False: A decentralized architecture is generally more resilient to a single-site failure than a centralized one, but harder to manage and monitor consistently.",
        "answer": True,
        "explain": "Distributing processing across nodes removes the single point of failure inherent in centralization — losing one node does not stop the whole system. The trade-off is management: patching, policy, and monitoring must be replicated correctly across every location.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "A network that is physically disconnected from all other networks, with no wired or wireless links, is said to be ______. (type your answer)",
        "answers": ["air-gapped", "air gapped", "airgapped", "an air gap", "air gap"],
        "explain": "An air gap is the strongest form of physical isolation — used for classified, industrial, and backup networks. Its residual weakness is removable media, since USB drives are the only practical way to move data in or out.",
    },
    {
        "type": "fill",
        "q": "Defining and provisioning servers and networks through version-controlled template files rather than manual configuration is called infrastructure as ______. (type your answer)",
        "answers": ["code", "iac", "infrastructure as code"],
        "explain": "Infrastructure as code (IaC) treats environment definitions like software: stored in version control, reviewed, and deployed automatically. It gives consistent, repeatable, auditable deployments — but template mistakes replicate everywhere the template is used.",
    },
    {
        "type": "fill",
        "q": "The attack in which malware inside a guest virtual machine breaks out to compromise the hypervisor or other guests is called VM ______. (type your answer)",
        "answers": ["escape", "vm escape", "escaping"],
        "explain": "VM escape defeats the core isolation promise of virtualization, exposing every VM on the physical host. Keeping the hypervisor patched is the primary defense, since escapes rely on hypervisor vulnerabilities.",
    },
    {
        "type": "fill",
        "q": "SDN separates the data (forwarding) plane from the centralized, programmable ______ plane. (type your answer)",
        "answers": ["control", "control plane"],
        "explain": "In software-defined networking, the control plane makes forwarding decisions in centralized software while switches simply forward per its instructions. Securing the controller and its APIs is critical because it commands the whole network.",
    },
    {
        "type": "fill",
        "q": "An operating system designed to process inputs within guaranteed, deterministic time limits — common in industrial and medical devices — is a real-time operating system, abbreviated ______. (type your answer)",
        "answers": ["rtos", "r.t.o.s."],
        "explain": "An RTOS guarantees deterministic response times for time-critical control functions. Security tools that add latency, such as scanners or agents, usually cannot run on it, so protection relies on isolation and compensating network controls.",
    },
    {
        "type": "fill",
        "q": "Shifting security risk to another party — for example through cyber insurance or a cloud provider contract — is known as risk ______. (type your answer)",
        "answers": ["transference", "transfer", "transferring", "sharing"],
        "explain": "Risk transference moves defined risk (often its financial impact) to a third party via insurance or contracts such as a cloud responsibility matrix. The organization remains ultimately accountable for its data even when responsibility is transferred.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each architecture model to its defining characteristic.",
        "pairs": [
            ["Serverless", "Provider runs functions on demand; customer manages only code and data"],
            ["Microservices", "Many small, loosely coupled services communicating via APIs"],
            ["Containerization", "Isolated app environments sharing the host OS kernel"],
            ["Virtualization", "Multiple full guest operating systems on one host via a hypervisor"],
            ["Infrastructure as code", "Environments defined and deployed from version-controlled templates"],
        ],
        "explain": "Serverless abstracts servers entirely; microservices decompose apps into API-connected services; containers share a kernel (light but weaker isolation); VMs run full OSs under a hypervisor (heavier but stronger isolation); IaC builds infrastructure from definition files.",
    },
    {
        "type": "match",
        "q": "Match each specialized system to its key security implication.",
        "pairs": [
            ["IoT device", "Weak default credentials and little or no update mechanism"],
            ["ICS/SCADA", "Availability-first systems controlling physical industrial processes"],
            ["RTOS", "Deterministic timing means security agents that add delay are unacceptable"],
            ["Embedded system", "Dedicated-function device with long lifespan and frequent inability to patch"],
            ["Air-gapped network", "No network connectivity; removable media is the main attack vector"],
        ],
        "explain": "These constrained and operational-technology systems share a theme: standard IT controls (patching, agents, scanning) often cannot be applied, so security depends on segmentation, hardening defaults, and compensating controls.",
    },
    {
        "type": "match",
        "q": "Match each 3.1 consideration to the scenario that illustrates it.",
        "pairs": [
            ["Scalability", "Cloud app automatically adds instances during a demand spike"],
            ["Risk transference", "Contract makes the provider liable for infrastructure security failures"],
            ["Ease of recovery", "Environment is rebuilt in minutes from snapshots and IaC templates"],
            ["Inability to patch", "Medical device firmware has no supported update path"],
            ["Power", "Data center adds UPS units and generators against utility outages"],
            ["Responsiveness", "System is tuned so requests are processed with minimal delay under load"],
        ],
        "explain": "Objective 3.1's considerations frame how you compare architectures: elasticity (scalability), shifting risk by contract (transference), fast restore paths (ease of recovery), compensating controls where patching is impossible, redundant power, and quick reaction to demand (responsiveness).",
    },
]
