TOPIC = {
    "id": "3.2",
    "domain": 3,
    "title": "Given a scenario, apply security principles to secure enterprise infrastructure.",
    "short": "Securing Enterprise Infrastructure",
}

TERMS = [
    ("Device placement", "Positioning security devices and servers in the network location that matches their function and the trust level of the zone (e.g., firewalls at zone borders, public servers in a screened subnet)"),
    ("Security zone", "Logical network segment grouping systems with similar trust and security requirements (internal, guest, perimeter); traffic between zones is controlled by firewall policy"),
    ("Screened subnet", "Perimeter zone (formerly DMZ) between the internet and the internal network that hosts public-facing servers, limiting exposure of the internal LAN if a server is compromised"),
    ("Attack surface", "The sum of all points where an attacker could attempt entry — open ports, running services, interfaces, applications; reduced by disabling anything not needed"),
    ("Connectivity", "Infrastructure consideration covering every path devices use to communicate — wired, wireless, and WAN/remote links — and how each path is secured, typically with encryption"),
    ("Fail-open", "Failure mode in which a failed security device passes traffic uninspected, preserving availability at the cost of security"),
    ("Fail-closed", "Failure mode in which a failed security device blocks all traffic, preserving security at the cost of availability"),
    ("Active vs. passive", "Device attribute: an active device (e.g., IPS) can act on and block traffic in real time; a passive device (e.g., IDS on a tap) only observes copies of traffic and alerts"),
    ("Inline vs. tap/monitor", "Deployment attribute: inline devices sit in the traffic path and can block it (but add a failure point); tap/monitor devices receive a copy of traffic out-of-band"),
    ("Jump server", "Hardened, heavily logged intermediary host that administrators must connect through to manage devices in a secured zone; provides a single controlled entry point"),
    ("Proxy server", "Server that makes requests on behalf of clients; a forward proxy filters/caches outbound web traffic, while a reverse proxy sits in front of web servers handling inbound requests"),
    ("Intrusion detection system (IDS)", "Passive monitoring system that inspects traffic (usually from a tap or SPAN port), detects suspicious activity, and alerts — but cannot block"),
    ("Intrusion prevention system (IPS)", "Active, inline system that detects malicious traffic and can block it in real time before it reaches the target"),
    ("Load balancer", "Appliance that distributes client requests across multiple servers for performance and availability, using health checks to stop sending traffic to failed servers"),
    ("Sensor", "Monitoring component placed at key network points to collect traffic data and telemetry and feed it to analysis systems such as an IDS or SIEM"),
    ("Port security", "Switch-level access controls that restrict which devices may connect to a physical port, including MAC limiting and 802.1X authentication"),
    ("802.1X", "IEEE standard for port-based network access control: a supplicant authenticates through an authenticator (switch/AP) to an authentication server (RADIUS) before the port passes traffic"),
    ("Extensible Authentication Protocol (EAP)", "Authentication framework used within 802.1X that carries multiple authentication methods, such as certificate-based EAP-TLS and PEAP"),
    ("Web application firewall (WAF)", "Firewall that inspects HTTP/HTTPS traffic to protect web applications from attacks such as SQL injection and cross-site scripting (XSS)"),
    ("Unified threat management (UTM)", "All-in-one security appliance combining firewall, IPS, antivirus, URL/content filtering, and spam filtering; popular with small and midsize organizations"),
    ("Next-generation firewall (NGFW)", "Application-aware firewall performing deep packet inspection at Layer 7, identifying applications regardless of port and integrating IPS and threat intelligence"),
    ("Layer 4 vs. Layer 7 firewall", "A Layer 4 firewall filters on IP addresses, ports, and protocol/session state; a Layer 7 firewall understands application content and can block based on payload"),
    ("Virtual private network (VPN)", "Encrypted tunnel across an untrusted network; site-to-site VPNs permanently link whole networks, while remote-access (client-to-site) VPNs connect individual users"),
    ("Transport Layer Security (TLS)", "Tunneling/encryption protocol used for HTTPS and for remote-access VPNs, including clientless browser-based VPN portals"),
    ("Internet Protocol Security (IPSec)", "Suite that secures IP traffic using AH (integrity/authentication) and ESP (encryption); tunnel mode protects the entire packet, transport mode only the payload"),
    ("Software-defined WAN (SD-WAN)", "WAN architecture that uses centralized policy to intelligently steer traffic across multiple links (broadband, LTE, MPLS) based on performance and application"),
    ("Secure access service edge (SASE)", "Cloud-delivered model combining SD-WAN networking with security services — secure web gateway, CASB, zero-trust access, firewall-as-a-service — close to the user"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company is deploying a new public-facing web server. Following secure device placement principles, where should the server be located?",
        "choices": [
            "On the internal server VLAN with the database servers",
            "In a screened subnet between the internet and the internal network",
            "Directly on the internet, outside the perimeter firewall",
            "On the management network with the jump server",
        ],
        "answer": 1,
        "explain": "Public-facing services belong in a screened subnet (formerly called a DMZ), a perimeter security zone isolated from the internal LAN. If the web server is compromised, firewall policy still stands between the attacker and internal systems. Placing it inside the LAN or outside the firewall would expose far more.",
    },
    {
        "type": "mc",
        "q": "An architect divides the network into internal, guest, and perimeter segments, each with a different trust level and firewall rules controlling traffic between them. Which infrastructure consideration is this?",
        "choices": ["Attack surface", "Failure modes", "Security zones", "Device attributes"],
        "answer": 2,
        "explain": "Grouping systems into segments by trust level and policing traffic between them is the definition of security zones. Attack surface is about the number of exposed entry points, failure modes describe fail-open/fail-closed behavior, and device attributes cover active/passive and inline/tap.",
    },
    {
        "type": "mc",
        "q": "A hardening project disables unused services, closes unneeded firewall ports, and uninstalls unnecessary software from servers. What is the team reducing?",
        "choices": ["The attack surface", "The security zone count", "The failure mode", "The broadcast domain"],
        "answer": 0,
        "explain": "The attack surface is the sum of all points an attacker could target — open ports, running services, installed applications, exposed interfaces. Removing or disabling anything not required shrinks that surface, which is a core principle of securing enterprise infrastructure.",
    },
    {
        "type": "mc",
        "q": "While designing infrastructure security, an architect inventories every path devices use to communicate — wired links, wireless, and site-to-site WAN circuits — and requires encryption on each path. Which infrastructure consideration is being addressed?",
        "choices": ["Device placement", "Connectivity", "Failure modes", "Port security"],
        "answer": 1,
        "explain": "Connectivity is the consideration of how devices and sites link together and how each communication path is secured, typically with encryption such as TLS or IPSec. Device placement is about where devices sit, and failure modes are about behavior when a device fails.",
    },
    {
        "type": "mc",
        "q": "An inline security appliance loses power. Traffic continues to flow through the segment but is no longer inspected. Which failure mode is the appliance configured for?",
        "choices": ["Fail-closed", "Passive", "Tap/monitor", "Fail-open"],
        "answer": 3,
        "explain": "Fail-open means that when the device fails, traffic keeps flowing uninspected — availability is preserved at the cost of security. Fail-closed would have blocked all traffic instead. Passive and tap/monitor are device attributes, not failure modes.",
    },
    {
        "type": "mc",
        "q": "A firewall protecting a high-security research enclave must never pass uninspected traffic, even if the firewall itself crashes; an availability outage is acceptable. Which failure mode should be selected?",
        "choices": ["Fail-closed", "Fail-open", "Active/inline", "Tap/monitor"],
        "answer": 0,
        "explain": "Fail-closed blocks all traffic when the device fails, guaranteeing nothing crosses the boundary uninspected. This trades availability for security, which fits high-security environments. Fail-open is the opposite trade-off, chosen where uptime matters more than inspection.",
    },
    {
        "type": "mc",
        "q": "A monitoring device receives a copy of traffic from a switch SPAN port, analyzes it, and generates alerts, but it can never block a single packet. How is this device BEST described?",
        "choices": ["Active and inline", "Passive", "Fail-open", "A Layer 7 firewall"],
        "answer": 1,
        "explain": "A device that only observes copies of traffic and alerts is passive — the classic IDS deployment. Active devices sit inline in the traffic path and can block or modify traffic in real time. Fail-open describes failure behavior, not normal operation.",
    },
    {
        "type": "mc",
        "q": "Which device attribute is REQUIRED for an intrusion prevention system to block malicious traffic in real time?",
        "choices": [
            "It must be deployed inline, in the actual traffic path",
            "It must be connected to a network tap",
            "It must be configured to fail-open",
            "It must operate passively from a monitor port",
        ],
        "answer": 0,
        "explain": "To drop or block packets, a device must sit inline so traffic physically flows through it. A tap or monitor port only delivers a copy of the traffic, so a device fed that way can detect and alert (IDS behavior) but cannot stop the original packets.",
    },
    {
        "type": "mc",
        "q": "A security team wants to analyze production traffic without adding latency or a new point of failure to the traffic path. Which deployment should they choose?",
        "choices": [
            "An inline IPS configured to fail-closed",
            "An inline transparent proxy",
            "A network tap feeding a passive monitoring device",
            "An active appliance in the traffic path",
        ],
        "answer": 2,
        "explain": "A tap (or SPAN/monitor port) copies traffic out-of-band to a passive analyzer, so production traffic is untouched — no added latency and no new failure point. Any inline deployment puts the device in the path, where its failure or slowness affects live traffic.",
    },
    {
        "type": "mc",
        "q": "Administrators must manage servers inside a restricted security zone. Policy requires every administrative session to pass through a single hardened, heavily logged intermediary host before reaching those servers. Which appliance fits this requirement?",
        "choices": ["Proxy server", "Jump server", "Load balancer", "Intrusion prevention system"],
        "answer": 1,
        "explain": "A jump server (jump box) is a hardened host that acts as the sole controlled entry point for administration of a secure zone, concentrating access control, MFA, and session logging in one place. A proxy handles client web traffic, not privileged admin access paths.",
    },
    {
        "type": "mc",
        "q": "A company wants to inspect employees' outbound web browsing, block prohibited URL categories, and cache frequently accessed pages. Which appliance BEST meets the need?",
        "choices": ["A forward proxy server", "A web application firewall", "A jump server", "A load balancer"],
        "answer": 0,
        "explain": "A forward proxy makes web requests on behalf of internal clients, which lets it filter URLs, inspect content, and cache pages. A WAF protects inbound traffic to your own web servers, not outbound employee browsing — a classic exam distinction.",
    },
    {
        "type": "mc",
        "q": "Which statement correctly distinguishes an IDS from an IPS?",
        "choices": [
            "An IDS blocks attacks inline, while an IPS only generates alerts",
            "An IDS detects and alerts, while an IPS sits inline and can also block traffic",
            "An IDS works only at Layer 7, while an IPS works only at Layer 4",
            "An IDS requires an agent on every host, while an IPS is agentless",
        ],
        "answer": 1,
        "explain": "The core difference is response capability: an IDS is typically passive (tap/SPAN-fed) and can only detect and alert, while an IPS is deployed inline and can actively block malicious traffic. Neither is restricted to a single OSI layer, and network IDS/IPS do not require host agents.",
    },
    {
        "type": "mc",
        "q": "A busy web application on a single server is slow, so the company adds two more identical servers. Which appliance distributes client requests across all three and stops sending traffic to any server that fails its health checks?",
        "choices": ["Web application firewall", "Unified threat management appliance", "Load balancer", "Jump server"],
        "answer": 2,
        "explain": "A load balancer spreads requests across a pool of servers and uses health checks to remove failed servers from rotation, improving both performance and availability. A WAF inspects web traffic for attacks and a UTM is an all-in-one security appliance — neither distributes load.",
    },
    {
        "type": "mc",
        "q": "A SOC places devices at key points in the network to collect traffic data and forward telemetry and alerts to the SIEM for analysis. Which network appliance is described?",
        "choices": ["Jump servers", "Sensors", "Load balancers", "Proxy servers"],
        "answer": 1,
        "explain": "Sensors are monitoring components positioned at strategic network points to gather traffic data and feed analysis platforms such as an IDS or SIEM. They observe and report; they are not access gateways (jump servers) or traffic distributors (load balancers).",
    },
    {
        "type": "mc",
        "q": "A company requires every device plugging into an office switch port to authenticate with a certificate or credentials before the port will pass any network traffic. Which technology enforces this?",
        "choices": ["802.1X port-based network access control", "A web application firewall", "IPSec tunnel mode", "SD-WAN"],
        "answer": 0,
        "explain": "802.1X is the IEEE standard for port-based network access control: the switch port stays blocked until the connecting device (supplicant) authenticates through the switch (authenticator) to an authentication server, typically RADIUS. It is the standard answer for authenticating devices at the port level.",
    },
    {
        "type": "mc",
        "q": "Within an 802.1X deployment, what role does EAP play?",
        "choices": [
            "It is the authentication framework that carries methods such as EAP-TLS between the supplicant and the authentication server",
            "It encrypts all user traffic after the port is authorized",
            "It replaces the RADIUS server in small deployments",
            "It assigns IP addresses to authenticated devices",
        ],
        "answer": 0,
        "explain": "EAP (Extensible Authentication Protocol) is a framework, not a single method: it transports the chosen authentication exchange — EAP-TLS, PEAP, and others — between the supplicant and the authentication server during 802.1X. It does not encrypt post-authentication traffic or hand out IP addresses (DHCP does that).",
    },
    {
        "type": "mc",
        "q": "An e-commerce site is being hit with SQL injection and cross-site scripting attempts against its checkout pages. Which control is designed specifically to inspect HTTP traffic and block these attacks?",
        "choices": ["A Layer 4 firewall", "An IDS on a network tap", "A web application firewall (WAF)", "A load balancer"],
        "answer": 2,
        "explain": "A WAF understands HTTP/HTTPS and inspects requests for web-application attacks such as SQL injection and XSS, blocking them before they reach the application. A Layer 4 firewall only sees IPs and ports, and a tap-fed IDS could alert on the attack but not stop it.",
    },
    {
        "type": "mc",
        "q": "A small business with no dedicated security staff wants a single appliance that provides firewall, IPS, antivirus, URL filtering, and spam filtering. Which solution BEST fits?",
        "choices": [
            "A unified threat management (UTM) appliance",
            "A next-generation firewall focused on application identification",
            "A web application firewall",
            "A jump server",
        ],
        "answer": 0,
        "explain": "UTM is the classic all-in-one answer: one appliance bundling firewall, IPS, antivirus, content/URL filtering, and spam filtering, ideal for small or midsize organizations wanting simple management. An NGFW centers on application-aware deep packet inspection; 'many security functions in one box for a small office' points to UTM.",
    },
    {
        "type": "mc",
        "q": "Which firewall type performs deep packet inspection to identify applications regardless of the port they use, and can integrate intrusion prevention and threat intelligence feeds?",
        "choices": [
            "A packet-filtering Layer 4 firewall",
            "A next-generation firewall (NGFW)",
            "A web application firewall",
            "A forward proxy",
        ],
        "answer": 1,
        "explain": "An NGFW is application-aware: deep packet inspection lets it recognize the actual application even on nonstandard ports, and it commonly integrates IPS functionality and threat intelligence. A Layer 4 firewall sees only addresses and ports, and a WAF is specialized for protecting web applications.",
    },
    {
        "type": "mc",
        "q": "A firewall permits TCP port 443 to a server but has no ability to examine the content of the HTTPS requests passing through. At which layer is this firewall operating?",
        "choices": ["Layer 7", "Layer 2", "Layer 4", "Layer 1"],
        "answer": 2,
        "explain": "Filtering by IP address, protocol, and port number is Layer 4 (transport-level) firewalling. Inspecting the actual content of requests — URLs, payloads, application commands — requires a Layer 7 (application-aware) firewall such as an NGFW or WAF.",
    },
    {
        "type": "mc",
        "q": "A company needs a permanent encrypted tunnel connecting its branch office network to headquarters across the internet, with no software required on individual user devices. Which solution fits BEST?",
        "choices": [
            "A site-to-site IPSec VPN between the two office gateways",
            "A clientless TLS VPN portal for each employee",
            "A remote-access VPN client on every branch PC",
            "802.1X on all branch switch ports",
        ],
        "answer": 0,
        "explain": "A site-to-site VPN is an always-on tunnel between two network gateways — typically IPSec — so every device at the branch reaches HQ transparently with no per-user software. Clientless TLS portals and remote-access clients serve individual users, and 802.1X controls local port access, not site connectivity.",
    },
    {
        "type": "mc",
        "q": "Traveling employees need to reach a few internal web applications from personal devices and kiosks where installing VPN client software is not allowed. Which remote access option is BEST?",
        "choices": [
            "A site-to-site IPSec VPN",
            "A clientless TLS VPN accessed through a web browser",
            "An SD-WAN overlay to each employee",
            "A jump server exposed directly to the internet",
        ],
        "answer": 1,
        "explain": "A clientless TLS VPN (browser-based portal) needs only a standard web browser, making it ideal when client software cannot be installed. Site-to-site VPNs connect networks, not roaming individuals; SD-WAN is for enterprise WAN links; and exposing a jump server directly to the internet defeats its purpose.",
    },
    {
        "type": "mc",
        "q": "A retailer with 200 stores wants to retire expensive MPLS circuits and instead steer traffic across broadband and LTE links automatically, based on centrally managed policies and real-time link performance. Which technology should it deploy?",
        "choices": ["SASE", "Software-defined WAN (SD-WAN)", "IPSec transport mode", "A UTM appliance at each store"],
        "answer": 1,
        "explain": "SD-WAN uses centralized, software-defined policy to intelligently route traffic over multiple transport links — broadband, LTE, MPLS — based on application needs and link quality, typically cutting WAN cost. SASE builds on SD-WAN by adding cloud-delivered security services, but the scenario asks only for intelligent multi-link WAN routing.",
    },
    {
        "type": "mc",
        "q": "A company with a mostly remote workforce wants to move network security to the cloud so users everywhere get firewalling, secure web gateway, CASB, and zero-trust access without backhauling traffic to headquarters. Which framework describes this?",
        "choices": [
            "Secure access service edge (SASE)",
            "SD-WAN by itself",
            "A UTM appliance in the data center",
            "A screened subnet",
        ],
        "answer": 0,
        "explain": "SASE combines SD-WAN connectivity with a cloud-delivered security stack — SWG, CASB, zero-trust network access, firewall-as-a-service — enforced near the user rather than at a central office. SD-WAN alone lacks the security services, and a data-center UTM would force the backhaul the company wants to avoid.",
    },
    {
        "type": "mc",
        "q": "After a risk assessment, an architect must choose security controls for a new system. Which approach reflects effective control selection?",
        "choices": [
            "Deploy every available control regardless of cost or impact",
            "Choose only preventive controls and skip detection entirely",
            "Copy whichever controls a competitor advertises",
            "Select controls that mitigate the identified risks, proportionate to the value of the assets being protected",
        ],
        "answer": 3,
        "explain": "Effective control selection matches controls to the specific risks identified and to the value and sensitivity of the assets — balancing security benefit against cost and operational impact. Buying everything wastes resources, relying on prevention alone leaves detection gaps, and copying others ignores your own risk profile.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: An IDS deployed passively from a network tap can block attacks in real time.",
        "answer": False,
        "explain": "A tap-fed IDS only sees a copy of the traffic, so the original packets have already passed — it can detect and alert but cannot block. Blocking in real time requires an active device deployed inline, which is what makes an IPS different.",
    },
    {
        "type": "tf",
        "q": "True or False: A device configured to fail-closed blocks all traffic when the device itself fails.",
        "answer": True,
        "explain": "Fail-closed means failure results in no traffic passing, favoring security over availability. Fail-open is the reverse: traffic keeps flowing uninspected so availability is preserved. Which mode to choose is a risk decision based on the zone being protected.",
    },
    {
        "type": "tf",
        "q": "True or False: IPSec transport mode encrypts the entire original IP packet, including its IP header.",
        "answer": False,
        "explain": "Transport mode protects only the payload, leaving the original IP header exposed; it is used mainly for host-to-host connections. Tunnel mode is the one that encapsulates and protects the entire original packet, including the header, and is the standard choice for site-to-site VPNs.",
    },
    {
        "type": "tf",
        "q": "True or False: A jump server should be hardened, require strong authentication, and log all sessions, because it is the single entry point for administering a secure zone.",
        "answer": True,
        "explain": "Concentrating all administrative access through one host only improves security if that host is locked down: minimal services, patched, MFA-protected, and fully audited. If the jump server is compromised, the attacker gains a path into everything it manages, so it is a high-value target.",
    },
    {
        "type": "tf",
        "q": "True or False: SASE combines SD-WAN connectivity with security services delivered from the cloud.",
        "answer": True,
        "explain": "Secure access service edge merges SD-WAN networking with a cloud-delivered security stack — secure web gateway, CASB, zero-trust network access, and firewall-as-a-service — so policy is enforced close to users wherever they are, instead of backhauling traffic to a central site.",
    },
    {
        "type": "tf",
        "q": "True or False: A Layer 4 firewall can inspect the contents of HTTP requests to block SQL injection attacks.",
        "answer": False,
        "explain": "A Layer 4 firewall makes decisions on IP addresses, protocols, and port numbers only — it cannot see application payloads. Blocking SQL injection requires application-layer (Layer 7) inspection, which is the job of a WAF or an NGFW performing deep packet inspection.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The IEEE standard for port-based network access control, which requires devices to authenticate before a switch port passes traffic, is ______. (type your answer)",
        "answers": ["802.1x", "802.1X", "ieee 802.1x", "802.1 x", "8021x"],
        "explain": "802.1X uses three roles — supplicant (the device), authenticator (the switch or AP), and authentication server (usually RADIUS) — and carries the authentication exchange inside EAP. Until authentication succeeds, the port stays in an unauthorized state.",
    },
    {
        "type": "fill",
        "q": "The failure mode in which a security device that fails continues to pass traffic uninspected is called fail-______. (type your answer)",
        "answers": ["open", "fail-open", "fail open", "failopen"],
        "explain": "Fail-open prioritizes availability: when the device dies, traffic flows on without inspection. Fail-closed prioritizes security by blocking everything instead. The right choice depends on whether an outage or uninspected traffic is the bigger risk for that zone.",
    },
    {
        "type": "fill",
        "q": "The firewall type placed in front of web servers to block application attacks such as SQL injection and XSS is a ______. (type the acronym or full name)",
        "answers": ["waf", "web application firewall", "web app firewall"],
        "explain": "A WAF inspects HTTP/HTTPS requests and responses at Layer 7, applying rules that recognize web attack patterns like SQL injection, XSS, and path traversal. It protects your own web applications from inbound attacks — unlike a forward proxy, which filters your users' outbound browsing.",
    },
    {
        "type": "fill",
        "q": "The hardened intermediary host that administrators must connect through before managing devices in a secured network zone is called a ______. (type your answer)",
        "answers": ["jump server", "jump box", "jumpbox", "jump host", "bastion host"],
        "explain": "A jump server (jump box) funnels all administrative access into one controlled, monitored chokepoint. Admins authenticate to it — ideally with MFA — and only from there open sessions to protected systems, so direct management access from user workstations can be blocked entirely.",
    },
    {
        "type": "fill",
        "q": "The technology that uses centralized software-defined policies to route branch traffic intelligently across multiple WAN links such as broadband and LTE is ______. (type the acronym)",
        "answers": ["sd-wan", "sdwan", "sd wan", "software-defined wan", "software defined wan", "software-defined wide area network"],
        "explain": "SD-WAN abstracts the WAN from the underlying circuits: a central controller pushes policies, and edge devices pick the best link per application based on performance and cost. It commonly reduces dependence on expensive MPLS and is the networking foundation that SASE builds on.",
    },
    {
        "type": "fill",
        "q": "The IPSec protocol that provides confidentiality by encrypting packet payloads is ______. (type the acronym or full name)",
        "answers": ["esp", "encapsulating security payload"],
        "explain": "ESP (Encapsulating Security Payload) provides encryption for confidentiality, plus integrity and authentication of the protected data. AH (Authentication Header) provides integrity and authentication only — no encryption — which is why ESP is the component used when confidentiality is required.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each security appliance or firewall type to its description.",
        "pairs": [
            ["Web application firewall (WAF)", "Inspects HTTP traffic to block SQL injection and XSS against web apps"],
            ["Unified threat management (UTM)", "All-in-one appliance: firewall, IPS, antivirus, and content filtering"],
            ["Next-generation firewall (NGFW)", "Application-aware firewall using deep packet inspection at Layer 7"],
            ["Layer 4 firewall", "Filters traffic based only on IP addresses, protocols, and port numbers"],
            ["Intrusion detection system (IDS)", "Passively monitors traffic and generates alerts but cannot block"],
        ],
        "explain": "The WAF is specialized for protecting web applications; UTM bundles many functions for simpler management; NGFW identifies applications via deep packet inspection; a Layer 4 firewall sees only addresses and ports; and an IDS detects without blocking — blocking requires an inline IPS.",
    },
    {
        "type": "match",
        "q": "Match each secure communication technology to its description.",
        "pairs": [
            ["Site-to-site VPN", "Always-on encrypted tunnel linking two office networks over the internet"],
            ["Clientless TLS VPN", "Browser-based remote access requiring no installed VPN software"],
            ["IPSec tunnel mode", "Encrypts the entire original IP packet, including its header"],
            ["SD-WAN", "Policy-driven routing of traffic across multiple WAN transport links"],
            ["SASE", "Cloud-delivered combination of SD-WAN and security services near the user"],
        ],
        "explain": "Site-to-site VPNs (usually IPSec tunnel mode) connect whole networks; clientless TLS VPNs serve individual users through a browser; tunnel mode's full-packet encapsulation is what hides internal addressing; SD-WAN handles intelligent multi-link routing; and SASE layers cloud security services on top of SD-WAN connectivity.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps of an 802.1X port-based authentication in the order they occur.",
        "items": [
            "A device (supplicant) connects to a switch port, which starts in the unauthorized state",
            "The authenticator (switch) requests the device's identity",
            "The switch relays the EAP authentication exchange to the RADIUS authentication server",
            "The RADIUS server validates the credentials or certificate",
            "The switch port transitions to the authorized state and forwards normal traffic",
        ],
        "explain": "802.1X keeps the port blocked until authentication completes: the supplicant connects, the authenticator asks for its identity, EAP messages are relayed to the authentication server (RADIUS), the server validates the credentials, and only then does the port open for normal traffic.",
    },
]
