TOPIC = {
    "id": "3.3",
    "domain": 3,
    "title": "Compare and contrast concepts and strategies to protect data.",
    "short": "Data Protection",
}

TERMS = [
    ("Regulated data", "Data whose handling is mandated by law or industry rules (e.g., healthcare records under HIPAA, cardholder data under PCI DSS, personal data under GDPR)"),
    ("Trade secret", "Proprietary business information that gives a competitive advantage (formulas, processes, recipes) and is protected by keeping it secret rather than by public registration"),
    ("Intellectual property (IP)", "Creations of the mind owned by an organization or person — patents, copyrights, trademarks, designs, source code"),
    ("Legal information", "Data related to legal matters such as contracts, litigation records, and attorney-client privileged communications; often subject to retention and privilege rules"),
    ("Financial information", "Data about monetary matters — bank accounts, payment card numbers, payroll, financial statements; a prime target for fraud and often regulated"),
    ("Human-readable data", "Data a person can directly read and understand, such as text documents, spreadsheets, and emails"),
    ("Non-human-readable data", "Data not directly interpretable by people without processing, such as binary files, machine code, or encrypted output"),
    ("Public classification", "Data that causes no harm if disclosed and can be freely shared, such as marketing brochures and press releases"),
    ("Private classification", "Data about an individual or internal to the organization that should not be shared externally, such as employee personnel records"),
    ("Sensitive classification", "Data that could harm the organization or individuals if disclosed and therefore needs protection above public data"),
    ("Confidential classification", "Highly protected internal data whose disclosure could seriously damage the organization; access limited to approved persons, often under NDA"),
    ("Restricted classification", "The most tightly controlled classification level; access is limited to a small, explicitly authorized set of people, often requiring special permission"),
    ("Critical classification", "Data essential to the organization's mission or operations; its loss or unavailability would severely impact the business"),
    ("Data at rest", "Data stored on media such as disks, databases, backups, or USB drives; typically protected with full-disk, volume, or database encryption"),
    ("Data in transit", "Data moving across a network between systems; protected with transport encryption such as TLS, IPSec, or VPN tunnels"),
    ("Data in use", "Data actively being processed in memory (RAM/CPU); the hardest state to protect, addressed by secure enclaves and memory protections"),
    ("Data sovereignty", "The principle that data is subject to the laws of the country or jurisdiction where it is collected or stored"),
    ("Geolocation", "Identifying the physical location of data or a user (e.g., via IP address or GPS), used for compliance and access decisions"),
    ("Geographic restrictions", "Limiting where data may be stored or accessed from based on location (geofencing), e.g., blocking logins from foreign countries or keeping data in-region"),
    ("Encryption", "Reversibly transforming plaintext into ciphertext with an algorithm and key so only authorized key holders can recover the data"),
    ("Hashing", "One-way transformation of data into a fixed-length digest; used for integrity checks and password storage, and cannot be reversed to reveal the original"),
    ("Masking", "Hiding portions of sensitive data by substituting characters (e.g., showing only the last four digits of a card number) while preserving the data's format"),
    ("Tokenization", "Replacing sensitive data with a non-sensitive token that has no mathematical relationship to the original; the real value is held in a secure token vault"),
    ("Obfuscation", "Making data or code intentionally difficult to understand (masking, tokenization, and steganography are forms of it) without necessarily encrypting it"),
    ("Segmentation", "Isolating networks or systems that hold sensitive data from the rest of the environment to limit access and contain breaches"),
    ("Permission restrictions", "Controlling who can access data through ACLs and authorization rules, following the principle of least privilege"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A hospital must handle patient health records according to HIPAA requirements. Which data type BEST describes these records?",
        "choices": ["Trade secret", "Regulated data", "Public data", "Non-human-readable data"],
        "answer": 1,
        "explain": "Data whose storage, processing, and disclosure are governed by law or industry mandates (HIPAA, GDPR, PCI DSS) is regulated data. A trade secret is competitive business information, not legally mandated personal data, and health records are certainly not public.",
    },
    {
        "type": "mc",
        "q": "A beverage company keeps its unpatented drink formula secret because it provides a competitive advantage. What type of data is this?",
        "choices": ["Regulated data", "Legal information", "Trade secret", "Financial information"],
        "answer": 2,
        "explain": "A trade secret is proprietary information (formulas, processes, recipes) protected by secrecy rather than public registration like a patent. It is intellectual property, but 'trade secret' is the most specific answer; it is not regulated personal data or legal/financial records.",
    },
    {
        "type": "mc",
        "q": "A software company wants to protect its copyrighted source code and registered trademarks. Which data type category do these assets fall under?",
        "choices": ["Intellectual property", "Regulated data", "Financial information", "Legal information"],
        "answer": 0,
        "explain": "Patents, copyrights, trademarks, and proprietary source code are intellectual property — creations of the mind the organization owns. Legal information refers to contracts and litigation records, while regulated data is data governed by external laws such as HIPAA or PCI DSS.",
    },
    {
        "type": "mc",
        "q": "An organization stores attorney-client privileged communications and records from an ongoing lawsuit. How should this data be categorized?",
        "choices": ["Trade secret", "Public data", "Financial information", "Legal information"],
        "answer": 3,
        "explain": "Litigation records, contracts, and privileged attorney-client communications are legal information, which often carries special retention and privilege requirements. It is not a trade secret (competitive business info) or financial data (monetary records).",
    },
    {
        "type": "mc",
        "q": "Which of the following is the BEST example of non-human-readable data?",
        "choices": [
            "A plaintext email message",
            "A compiled binary executable",
            "A printed marketing brochure",
            "A spreadsheet of employee names",
        ],
        "answer": 1,
        "explain": "A compiled binary is machine-interpretable but not directly understandable by a person, making it non-human-readable. Emails, brochures, and spreadsheets are human-readable — a person can open and understand them directly.",
    },
    {
        "type": "mc",
        "q": "A company's press releases and marketing brochures would cause no harm if disclosed. Which classification label applies?",
        "choices": ["Confidential", "Restricted", "Public", "Critical"],
        "answer": 2,
        "explain": "Public data can be freely shared with no damage to the organization, so it receives the lowest classification. Confidential and restricted labels are reserved for data whose disclosure would cause harm, and critical describes data essential to operations.",
    },
    {
        "type": "mc",
        "q": "An organization labels its merger negotiation documents so that only a small, explicitly named group of executives may view them, and any other access requires special approval. Which classification BEST fits?",
        "choices": ["Restricted", "Private", "Public", "Sensitive"],
        "answer": 0,
        "explain": "Restricted is the most tightly controlled classification: access is limited to a specific, explicitly authorized set of people, often with per-person approval. Private typically covers individual or internal-only data, and sensitive is a broader label without the explicit named-access requirement.",
    },
    {
        "type": "mc",
        "q": "Employee personnel files containing home addresses and performance reviews are internal data about individuals that must not be shared outside the company. Which classification BEST applies?",
        "choices": ["Public", "Critical", "Private", "Trade secret"],
        "answer": 2,
        "explain": "Private classification covers data about individuals or internal matters that should stay within the organization, such as HR personnel records. Critical refers to data the business cannot operate without, and trade secret is a data type, not a classification level.",
    },
    {
        "type": "mc",
        "q": "A manufacturing firm identifies the production database that its entire assembly line depends on. Losing this data would halt operations. Which classification concept BEST describes it?",
        "choices": ["Public", "Critical", "Private", "Confidential"],
        "answer": 1,
        "explain": "Critical data is data the organization's mission or operations cannot function without — its loss or unavailability severely impacts the business. Confidential and private describe sensitivity to disclosure, whereas critical emphasizes importance to availability and operations.",
    },
    {
        "type": "mc",
        "q": "A company's unreleased source code and M&A plans are limited to authorized personnel under NDA because disclosure would seriously damage its competitive position. Which classification label BEST fits?",
        "choices": ["Public", "Confidential", "Critical", "Private"],
        "answer": 1,
        "explain": "Confidential data is limited to authorized personnel — often under NDA — and its disclosure would cause serious competitive or legal damage; trade secrets, M&A plans, and source code are classic examples. Private covers personal or internal-only data, and critical describes data operations cannot run without.",
    },
    {
        "type": "mc",
        "q": "An internal document describing the company's firewall rule sets and security configurations could cause harm if exposed, but access is not limited to an explicitly named list of individuals. Which classification BEST applies?",
        "choices": ["Sensitive", "Public", "Critical", "Restricted"],
        "answer": 0,
        "explain": "Sensitive data could harm the organization or individuals if disclosed — security configurations, intellectual property, and financial details are typical examples — so it sits above public without requiring the explicit named-access controls of restricted. Critical instead describes data the business cannot operate without.",
    },
    {
        "type": "mc",
        "q": "Database records sitting on a SAN volume, nightly backup tapes in a vault, and files on a laptop SSD are all examples of data in which state?",
        "choices": ["Data in transit", "Data in use", "Data at rest", "Data sovereignty"],
        "answer": 2,
        "explain": "Data stored on any media — disks, databases, backups, removable drives — is data at rest, typically protected with full-disk or database encryption. Data in transit is moving across a network, and data in use is being processed in memory. Data sovereignty is a legal concept, not a state.",
    },
    {
        "type": "mc",
        "q": "Which control BEST protects data in transit between a branch office and headquarters?",
        "choices": [
            "Full-disk encryption on the file server",
            "An IPSec VPN tunnel between the sites",
            "Hashing the files before storage",
            "Applying restrictive NTFS permissions",
        ],
        "answer": 1,
        "explain": "Data in transit is protected with transport encryption such as TLS or an IPSec VPN, which encrypts traffic as it crosses the network. Full-disk encryption and file permissions protect data at rest, and hashing provides integrity verification, not confidentiality in motion.",
    },
    {
        "type": "mc",
        "q": "An attacker scrapes decrypted credit card numbers directly from a point-of-sale terminal's RAM while transactions are processed. Which data state was targeted?",
        "choices": ["Data at rest", "Data in transit", "Data in use", "Data sovereignty"],
        "answer": 2,
        "explain": "Data being actively processed in memory or CPU registers is data in use — the hardest state to protect, because it must be in usable (often decrypted) form. Memory-scraping malware exploits exactly this. At-rest and in-transit protections do not help once data is loaded into RAM.",
    },
    {
        "type": "mc",
        "q": "A cloud customer in Germany is told that any personal data collected there remains subject to EU law even when replicated to servers abroad. Which concept does this describe?",
        "choices": ["Geolocation", "Data sovereignty", "Tokenization", "Segmentation"],
        "answer": 1,
        "explain": "Data sovereignty means data is subject to the laws of the jurisdiction where it is collected or stored, which drives decisions about where cloud providers may host it. Geolocation is the technique of determining physical location; sovereignty is the legal consequence of that location.",
    },
    {
        "type": "mc",
        "q": "A SaaS application determines a user's physical location from their IP address before deciding whether to allow a login. Which concept is being applied?",
        "choices": ["Geolocation", "Hashing", "Data sovereignty", "Masking"],
        "answer": 0,
        "explain": "Geolocation identifies where a user or system is physically located, commonly via IP address or GPS. That location data can then drive geographic restrictions or compliance decisions. Data sovereignty is the legal principle about which laws apply, not the locating technique itself.",
    },
    {
        "type": "mc",
        "q": "To comply with EU rules, a company configures its cloud tenancy so customer data can only be stored in EU-region data centers, and blocks access attempts originating outside the EU. Which data protection method is this?",
        "choices": ["Tokenization", "Obfuscation", "Permission restrictions", "Geographic restrictions"],
        "answer": 3,
        "explain": "Restricting where data may be stored or accessed from based on location — region-locking storage and geofencing access — is a geographic restriction. Permission restrictions control who can access data regardless of place, and tokenization/obfuscation change how the data itself appears.",
    },
    {
        "type": "mc",
        "q": "A stolen laptop's SSD cannot be read by the thief because the entire drive was transformed into ciphertext recoverable only with the user's key. Which method protected the data?",
        "choices": ["Hashing", "Masking", "Encryption", "Segmentation"],
        "answer": 2,
        "explain": "Full-disk encryption reversibly converts stored data to ciphertext that only the key holder can decrypt, protecting data at rest on lost or stolen devices. Hashing is one-way and unsuitable for recovering data, and masking only hides displayed portions of values.",
    },
    {
        "type": "mc",
        "q": "A security team stores user passwords as one-way digests so that even administrators cannot recover the original passwords. Which technique is being used?",
        "choices": ["Encryption", "Hashing", "Tokenization", "Masking"],
        "answer": 1,
        "explain": "Hashing produces a fixed-length, one-way digest that cannot be reversed to reveal the input, which is exactly what password storage requires. Encryption is reversible with the key, tokenization stores the real value in a vault, and masking merely hides characters on display.",
    },
    {
        "type": "mc",
        "q": "A customer service screen displays a stored credit card as ****-****-****-4821 so agents can confirm the card without seeing the full number. Which method is this?",
        "choices": ["Masking", "Hashing", "Encryption", "Segmentation"],
        "answer": 0,
        "explain": "Masking substitutes characters (often asterisks) for part of a sensitive value while leaving enough visible for legitimate use, preserving the format. Hashing would produce an unrecognizable digest, and encryption would make the whole value unreadable without decryption.",
    },
    {
        "type": "mc",
        "q": "A retailer replaces stored card numbers with random surrogate values that have no mathematical relationship to the originals; the real numbers live only in a secure vault at the payment provider. Which method is this?",
        "choices": ["Encryption", "Masking", "Hashing", "Tokenization"],
        "answer": 3,
        "explain": "Tokenization swaps sensitive data for a meaningless token and keeps the real value in a separate token vault; a stolen token is useless because there is no key or algorithm that derives the original from it. Encryption, by contrast, is mathematically reversible with the key.",
    },
    {
        "type": "mc",
        "q": "What is the KEY difference between tokenization and encryption?",
        "choices": [
            "Tokenization is one-way and can never retrieve the original data",
            "A token has no mathematical relationship to the original value, while ciphertext can be decrypted with the key",
            "Encryption preserves the data format, while tokens never do",
            "Tokenization only works on data in transit",
        ],
        "answer": 1,
        "explain": "Tokens are random substitutes mapped to the real value in a vault — nothing about the token mathematically derives from the original. Ciphertext is derived from plaintext and reversible with the key. Tokenization is not one-way like hashing (the vault allows lookup), and it is commonly used for stored payment data.",
    },
    {
        "type": "mc",
        "q": "A developer hides a watermark inside an image file so its presence is not apparent, and also renames variables in released code to meaningless strings to hinder reverse engineering. Which general technique covers both actions?",
        "choices": ["Obfuscation", "Hashing", "Geographic restriction", "Permission restriction"],
        "answer": 0,
        "explain": "Obfuscation makes data or code intentionally difficult to understand without necessarily encrypting it — steganography (hiding data in images) and code obfuscation are classic examples, and masking and tokenization are also considered obfuscation techniques. It obscures rather than mathematically protects.",
    },
    {
        "type": "mc",
        "q": "A company moves its cardholder-data environment onto an isolated network zone, separated by firewalls from the general corporate LAN, to limit exposure and reduce PCI DSS audit scope. Which data protection method is this?",
        "choices": ["Tokenization", "Masking", "Segmentation", "Hashing"],
        "answer": 2,
        "explain": "Segmentation isolates systems holding sensitive data from the rest of the network so a compromise elsewhere cannot easily reach them, and it can shrink compliance scope. Tokenization and masking change the data's representation, not the network architecture around it.",
    },
    {
        "type": "mc",
        "q": "An administrator configures ACLs so only the payroll group can read the salary database, following least privilege. Which method of securing data does this represent?",
        "choices": ["Encryption", "Permission restrictions", "Geographic restrictions", "Obfuscation"],
        "answer": 1,
        "explain": "Permission restrictions control who may access data using access control lists and authorization rules under the principle of least privilege. Geographic restrictions control where access can occur, and encryption/obfuscation change the data's form rather than gating access by identity.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Hashing is reversible, so an administrator with the right key can recover the original data from its hash.",
        "answer": False,
        "explain": "Hashing is a one-way function producing a fixed-length digest; there is no key and no way to reverse it to obtain the input. Encryption is the reversible, key-based transformation. This one-way property is why hashes are used for integrity checks and password storage.",
    },
    {
        "type": "tf",
        "q": "True or False: Data in use refers to data being actively processed in a system's memory or CPU.",
        "answer": True,
        "explain": "Data in use is data loaded into RAM, CPU caches, or registers during processing. It is the hardest state to protect because it generally must be decrypted to be worked on, which is why memory-scraping attacks target it.",
    },
    {
        "type": "tf",
        "q": "True or False: Data sovereignty means data stored in a country is subject to that country's laws.",
        "answer": True,
        "explain": "Data sovereignty ties data to the legal jurisdiction where it is collected or stored, so hosting data in another country can subject it to that country's regulations. This is why organizations use geographic restrictions to control where cloud data resides.",
    },
    {
        "type": "tf",
        "q": "True or False: Masking permanently destroys the original sensitive data so it can never be viewed again.",
        "answer": False,
        "explain": "Masking only hides part of the value on display or in a copy (e.g., ****-4821); the complete original data still exists in the underlying system for authorized use. It limits exposure, but it is not destruction or sanitization.",
    },
    {
        "type": "tf",
        "q": "True or False: A TLS session protecting a web transaction is an example of securing data in transit.",
        "answer": True,
        "explain": "TLS encrypts data as it moves across the network between client and server, which is precisely the data-in-transit state. Protections like full-disk encryption cover data at rest instead, and secure enclaves address data in use.",
    },
    {
        "type": "tf",
        "q": "True or False: Encrypting a file converts it from human-readable to non-human-readable form.",
        "answer": True,
        "explain": "Plaintext documents are human-readable, while ciphertext is unintelligible to a person without decryption, making it non-human-readable. This mapping between the two data types is a common exam angle: encryption is one way human-readable data becomes non-human-readable.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Replacing a credit card number with a random surrogate value stored in a secure vault, with no mathematical link to the original, is called ______. (type your answer)",
        "answers": ["tokenization", "tokenisation", "tokenizing"],
        "explain": "Tokenization substitutes sensitive data with a meaningless token and keeps the real value in a token vault. Unlike encryption there is no algorithm or key that derives the original from the token, so stolen tokens are worthless.",
    },
    {
        "type": "fill",
        "q": "Data stored on backup tapes, hard drives, or in a database — not currently moving or being processed — is called data at ______. (type your answer)",
        "answers": ["rest", "data at rest"],
        "explain": "The three data states are at rest (stored), in transit (moving across a network), and in use (being processed in memory). Data at rest is typically protected with full-disk, volume, or database encryption.",
    },
    {
        "type": "fill",
        "q": "The legal principle that data is governed by the laws of the country where it is collected or stored is known as data ______. (type your answer)",
        "answers": ["sovereignty", "data sovereignty"],
        "explain": "Data sovereignty means the jurisdiction hosting the data determines which laws apply to it. Organizations respond with geographic restrictions on cloud regions to keep regulated data under the intended legal regime.",
    },
    {
        "type": "fill",
        "q": "A one-way function that converts data of any size into a fixed-length digest used for integrity verification is called ______. (type your answer)",
        "answers": ["hashing", "a hash", "hash", "hash function"],
        "explain": "Hashing produces a fixed-length digest that changes completely if even one bit of input changes, making it ideal for integrity checks and password storage. It is one-way — the original data cannot be recovered from the digest.",
    },
    {
        "type": "fill",
        "q": "Isolating the systems that hold sensitive data onto their own firewalled network zone, separate from the general LAN, is a data protection method called ______. (type your answer)",
        "answers": ["segmentation", "network segmentation", "segmenting"],
        "explain": "Segmentation separates sensitive systems from the rest of the environment so attackers who compromise the general network cannot easily reach them. It also limits breach blast radius and can reduce compliance audit scope.",
    },
    {
        "type": "fill",
        "q": "Displaying a Social Security number as ***-**-6789 so that only the last four digits are visible is an example of ______. (type your answer)",
        "answers": ["masking", "data masking"],
        "explain": "Masking hides part of a sensitive value with substitute characters while preserving the format and enough of the value for legitimate use. The full value still exists in the system; only its display or copy is obscured.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each data state to the control that BEST protects it.",
        "pairs": [
            ["Data at rest", "Full-disk encryption on storage drives"],
            ["Data in transit", "TLS/VPN transport encryption"],
            ["Data in use", "Secure enclave protecting memory during processing"],
            ["Data location compliance", "Geographic restrictions on storage regions"],
        ],
        "explain": "Each state calls for a different control: stored data gets disk/database encryption, moving data gets TLS or IPSec/VPN, and data being processed relies on memory protections like secure enclaves. Location-based compliance concerns are handled with geographic restrictions.",
    },
    {
        "type": "match",
        "q": "Match each scenario to the data protection method it demonstrates.",
        "pairs": [
            ["Card number replaced by a random value mapped in a secure vault", "Tokenization"],
            ["Only the last four digits of an account number are displayed", "Masking"],
            ["File converted to ciphertext recoverable with a key", "Encryption"],
            ["Password stored as an irreversible fixed-length digest", "Hashing"],
            ["ACLs limit the salary file to the payroll group only", "Permission restrictions"],
        ],
        "explain": "Tokenization substitutes a vault-mapped surrogate; masking hides displayed characters; encryption is reversible with a key; hashing is one-way and fixed-length; permission restrictions gate access by identity via ACLs and least privilege. Distinguishing these is a core exam skill for 3.3.",
    },
    {
        "type": "match",
        "q": "Match each example to its data type.",
        "pairs": [
            ["Cardholder data governed by PCI DSS", "Regulated data"],
            ["Secret manufacturing process kept unpublished", "Trade secret"],
            ["Company-owned patents and copyrighted source code", "Intellectual property"],
            ["Litigation records and privileged attorney communications", "Legal information"],
            ["Payroll records and corporate bank statements", "Financial information"],
        ],
        "explain": "Regulated data is governed by external law or industry mandate; trade secrets are competitive secrets protected by nondisclosure; intellectual property covers patents, copyrights, and trademarks; legal information relates to legal proceedings and privilege; financial information concerns money and accounts.",
    },
]
