TOPIC = {
    "id": "3.4",
    "domain": 3,
    "title": "Explain the importance of resilience and recovery in security architecture.",
    "short": "Resilience & Recovery",
}

TERMS = [
    ("High availability (HA)", "Designing systems to maximize uptime through redundancy such as load balancing and clustering; often measured in 'nines' of uptime"),
    ("Load balancing", "Distributing incoming requests across multiple servers; health checks pull failed nodes out of rotation, improving performance and availability"),
    ("Clustering", "Multiple servers operating as a single logical system with shared state; if one node fails, another node in the cluster takes over the workload"),
    ("Active/active vs. active/passive", "Active/active: all nodes serve load simultaneously; active/passive: a standby node takes over (fails over) only when the active node fails"),
    ("Hot site", "Fully equipped alternate site with hardware, connectivity, and near-real-time data; ready in minutes to hours; the most expensive site option"),
    ("Warm site", "Alternate site with power, connectivity, and some hardware staged, but current data must be restored from backup; a mid-cost, mid-speed compromise"),
    ("Cold site", "Alternate site providing only space, power, and connectivity; equipment and data must be brought in after the disaster; cheapest but slowest to activate"),
    ("Geographic dispersion", "Placing redundant sites far enough apart that a single regional disaster (hurricane, earthquake, grid failure) cannot affect them all"),
    ("Platform diversity", "Using different vendors, operating systems, or hardware so one vulnerability or flaw cannot compromise every system at once"),
    ("Multi-cloud system", "Using services from more than one cloud provider to avoid vendor lock-in and to survive an outage of any single provider"),
    ("Continuity of operations (COOP)", "Planning that ensures mission-essential functions continue during and after a disruption, covering alternate sites, processes, and personnel"),
    ("Capacity planning", "Forecasting future needs for people, technology, and infrastructure so resources are sufficient for normal demand and for recovery"),
    ("Tabletop exercise", "Discussion-based walkthrough of a disaster scenario with stakeholders; low cost and low risk because no production systems are touched"),
    ("Fail over (testing)", "Deliberately switching production workload to the redundant system or alternate site to prove that failover actually works as designed"),
    ("Simulation", "Exercise that recreates a realistic incident so teams actually perform their response procedures; more hands-on than a tabletop, without production impact"),
    ("Parallel processing (testing)", "Running the same workload at the recovery site alongside the primary and comparing results, validating the alternate site without taking the primary offline"),
    ("Onsite backup", "Backup copy kept at the primary facility; fastest to restore but exposed to the same fire, flood, or theft as the production systems"),
    ("Offsite backup", "Backup copy stored at another location or in the cloud; survives a site-wide disaster and supports the 3-2-1 backup principle"),
    ("Backup frequency", "How often backups run; driven by the recovery point objective (RPO) — the maximum amount of data loss the organization can tolerate"),
    ("Snapshot", "Point-in-time image of a VM, volume, or filesystem that can be quickly reverted to; commonly taken before patches and upgrades"),
    ("Replication", "Continuously copying data (synchronously or asynchronously) to another system or site; minimizes data loss but also propagates corruption and deletions"),
    ("Journaling", "Recording every change or transaction in a log so data can be rolled forward and reconstructed to a precise point in time after a failure"),
    ("Recovery point objective (RPO)", "Maximum acceptable amount of data loss measured in time; determines how frequently backups or replication must occur"),
    ("Recovery time objective (RTO)", "Maximum acceptable time to restore a service after a disruption; drives site and technology choices such as hot vs. warm vs. cold"),
    ("Uninterruptible power supply (UPS)", "Battery system that provides immediate, short-term power to ride out brief outages and bridge the gap until a generator starts or systems shut down cleanly"),
    ("Generator", "Fuel-powered device that supplies long-term electrical power during extended outages; needs startup time, refueling arrangements, and regular testing"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company places a device in front of its three web servers that distributes incoming HTTPS requests across them and automatically stops sending traffic to any server that fails its health checks. Which resilience technique is this?",
        "choices": ["Clustering", "Load balancing", "Replication", "Journaling"],
        "answer": 1,
        "explain": "A load balancer distributes client requests across a pool of servers and uses health checks to remove failed nodes from rotation, improving both performance and availability. Clustering is different: cluster nodes act as a single logical system with shared state, whereas load-balanced servers are independent nodes behind a distribution point.",
    },
    {
        "type": "mc",
        "q": "Two database servers are configured to operate as a single logical system with shared storage. When the primary node fails, the second node automatically assumes the workload with the same data and configuration. Which technique is described?",
        "choices": ["Load balancing", "Snapshots", "Clustering", "Platform diversity"],
        "answer": 2,
        "explain": "Clustering joins multiple servers into one logical unit that shares state, so a surviving node can take over transparently when another fails. Load balancing merely spreads requests across independent servers; it does not make them share configuration and storage as one system.",
    },
    {
        "type": "mc",
        "q": "After a datacenter fire, a financial firm must resume trading within an hour. Its alternate facility already contains identical servers, network equipment, and data replicated in near real time. Which site type is this?",
        "choices": ["Warm site", "Hot site", "Cold site", "Geographic dispersion"],
        "answer": 1,
        "explain": "A hot site is fully equipped and kept synchronized with production data, so operations can resume in minutes to hours — at the highest cost. A warm site has hardware but stale data that must be restored, and a cold site is essentially an empty shell.",
    },
    {
        "type": "mc",
        "q": "An organization with a very limited recovery budget contracts for an empty facility that provides only floor space, power, and network connectivity. After a disaster it would still need to acquire equipment and restore data before operating. Which site type is this?",
        "choices": ["Warm site", "Hot site", "Cold site", "Multi-cloud site"],
        "answer": 2,
        "explain": "A cold site offers just the basics — space, power, and connectivity — with no staged hardware or data. It is the cheapest alternate-site option but has the longest recovery time, often weeks, because everything must be procured, installed, and restored after the disaster.",
    },
    {
        "type": "mc",
        "q": "A recovery facility already has racks, servers, and network links installed, but the latest data must be restored from offsite backups before operations can resume — a process expected to take about a day. Which site type is this?",
        "choices": ["Hot site", "Cold site", "Warm site", "Onsite datacenter"],
        "answer": 2,
        "explain": "A warm site is the middle option: hardware and connectivity are in place, but current data is not, so recovery takes hours to days while backups are restored. A hot site would already have near-real-time data, and a cold site would have no equipment at all.",
    },
    {
        "type": "mc",
        "q": "A company's primary datacenter is in Miami. When selecting a secondary site, the architect rejects a location 20 miles away because a single hurricane could disable both facilities. Which resilience consideration is being applied?",
        "choices": ["Platform diversity", "Geographic dispersion", "Parallel processing", "Capacity planning"],
        "answer": 1,
        "explain": "Geographic dispersion places redundant sites far enough apart that one regional disaster — hurricane, earthquake, flood, or grid failure — cannot take out both. Platform diversity addresses vendor/OS variety, not physical distance, and parallel processing is a DR testing method.",
    },
    {
        "type": "mc",
        "q": "A security architect specifies that the two layers of perimeter firewalls must come from different vendors so that a single exploitable flaw cannot defeat every layer of defense. Which resilience concept is this?",
        "choices": ["Multi-cloud systems", "Geographic dispersion", "Platform diversity", "High availability"],
        "answer": 2,
        "explain": "Platform diversity uses different vendors, operating systems, or hardware so one vulnerability cannot compromise everything at once. Multi-cloud is the analogous idea applied specifically to cloud providers, and geographic dispersion addresses physical location rather than technology variety.",
    },
    {
        "type": "mc",
        "q": "To ensure that a major outage at any single cloud provider cannot take its customer-facing services offline, a company deploys its workloads across two different IaaS providers. Which strategy is this?",
        "choices": ["Platform diversity", "Multi-cloud system", "Geographic dispersion", "Clustering"],
        "answer": 1,
        "explain": "A multi-cloud system uses more than one cloud provider, so a provider-wide outage (or vendor lock-in) cannot cripple the business. It is closely related to platform diversity, but multi-cloud is the specific term for spreading across cloud vendors.",
    },
    {
        "type": "mc",
        "q": "Which planning effort ensures that an organization's mission-essential functions continue during and after a disaster, addressing alternate sites, personnel, and procedures?",
        "choices": ["Capacity planning", "Continuity of operations (COOP)", "Tabletop exercise", "Journaling"],
        "answer": 1,
        "explain": "Continuity of operations (COOP) planning keeps essential functions running through a disruption and guides recovery afterward. Capacity planning forecasts resource needs, and a tabletop exercise is a way to test plans like COOP — not the plan itself.",
    },
    {
        "type": "mc",
        "q": "A continuity coordinator discovers that only one engineer knows how to fail over the payment platform; if that person is unavailable during a disaster, recovery stalls. Cross-training additional staff addresses which element of capacity planning?",
        "choices": ["Technology", "Infrastructure", "People", "Testing"],
        "answer": 2,
        "explain": "Capacity planning covers people, technology, and infrastructure. Ensuring enough trained personnel — through hiring, cross-training, and documented procedures — is the people element, eliminating single points of failure in human knowledge.",
    },
    {
        "type": "mc",
        "q": "During capacity planning, a team forecasts whether current server compute, storage, and software licensing can absorb projected growth plus a full failover load. Which element of capacity planning is this?",
        "choices": ["People", "Technology", "Infrastructure", "Continuity of operations"],
        "answer": 1,
        "explain": "The technology element of capacity planning ensures systems — compute, storage, licenses, and applications — can scale to meet demand, including surge demand during failover. Infrastructure focuses on the supporting facilities such as power, cooling, and network capacity.",
    },
    {
        "type": "mc",
        "q": "Evaluating whether the datacenter has sufficient electrical capacity, cooling, rack space, and network bandwidth to host additional failover systems addresses which element of capacity planning?",
        "choices": ["People", "Technology", "Infrastructure", "Platform diversity"],
        "answer": 2,
        "explain": "Infrastructure capacity planning covers the physical foundation — power, cooling, space, and connectivity — that everything else depends on. Technology planning covers the systems themselves, and people planning covers staffing and skills.",
    },
    {
        "type": "mc",
        "q": "The incident response team gathers in a conference room and verbally walks through a ransomware disaster-recovery scenario step by step. No systems are touched. Which type of test is this?",
        "choices": ["Simulation", "Fail over test", "Parallel processing", "Tabletop exercise"],
        "answer": 3,
        "explain": "A tabletop exercise is a discussion-based walkthrough of a scenario — cheap, low risk, and great for finding gaps in a plan, but it proves nothing about whether the technology actually works. A simulation or failover test would involve actually performing actions on systems.",
    },
    {
        "type": "mc",
        "q": "To prove its secondary datacenter can actually carry production, an organization deliberately shifts live workloads from the primary site to the secondary site during a scheduled maintenance window. Which type of test is this?",
        "choices": ["Tabletop exercise", "Fail over test", "Simulation", "Parallel processing"],
        "answer": 1,
        "explain": "A failover test deliberately switches production to the redundant system or site to verify that failover mechanisms, data, and capacity all work under real load. It is the most convincing test but also carries the most operational risk, which is why it is scheduled carefully.",
    },
    {
        "type": "mc",
        "q": "A company runs a realistic mock outage scenario in a test environment so responders actually execute their recovery procedures hands-on, without any impact to production. Which testing type is this?",
        "choices": ["Tabletop exercise", "Parallel processing", "Simulation", "Journaling"],
        "answer": 2,
        "explain": "A simulation recreates a realistic incident so teams practice performing their actual response steps, going beyond the talk-only tabletop while still protecting production. Parallel processing instead runs real workloads at both sites and compares results.",
    },
    {
        "type": "mc",
        "q": "During a disaster-recovery test, the recovery site processes the same transactions as the primary site at the same time, and the outputs are compared for accuracy. The primary site is never taken offline. Which testing method is this?",
        "choices": ["Fail over", "Parallel processing", "Tabletop exercise", "Replication"],
        "answer": 1,
        "explain": "Parallel processing runs the workload at both the primary and recovery sites simultaneously and compares the results, validating the alternate site with no disruption to production. A failover test, in contrast, actually moves production onto the secondary system.",
    },
    {
        "type": "mc",
        "q": "Ransomware encrypts a company's file servers and also the backup NAS sitting in the same server room. Which practice would MOST likely have preserved a usable backup?",
        "choices": [
            "Storing encrypted backup copies offsite",
            "Taking more frequent onsite snapshots",
            "Enabling journaling on the file server",
            "Clustering the backup server",
        ],
        "answer": 0,
        "explain": "Offsite (and offline/immutable) copies survive events that destroy everything at the primary location, whether ransomware, fire, or flood — the heart of the 3-2-1 backup principle. More onsite snapshots or clustering would have been reachable by the same ransomware, and journaling alone does not protect the data store itself.",
    },
    {
        "type": "mc",
        "q": "A courier loses a box of backup tapes while transporting them to an offsite storage vendor. Which control BEST reduces the risk of data exposure from this incident?",
        "choices": [
            "Increasing backup frequency",
            "Encrypting the backups",
            "Using snapshots instead of tapes",
            "Replicating to a second NAS",
        ],
        "answer": 1,
        "explain": "Encrypting backups ensures that lost or stolen media are unreadable without the key, protecting confidentiality wherever the media ends up. Frequency, snapshots, and replication affect how much data you can recover — none of them prevents someone who finds the tapes from reading them.",
    },
    {
        "type": "mc",
        "q": "Before applying a major OS patch to a virtual machine, an administrator wants a way to instantly revert the VM to its pre-patch state if the update fails. Which option BEST meets this need?",
        "choices": ["A full offsite backup", "Journaling", "A snapshot", "A failover cluster"],
        "answer": 2,
        "explain": "A snapshot captures the point-in-time state of a VM or volume and can be reverted almost instantly, making it ideal insurance before patches and upgrades. A full backup would work but restores far more slowly, and journaling and clustering solve different problems (transaction recovery and availability).",
    },
    {
        "type": "mc",
        "q": "A hospital requires that the copy of its patient database at the secondary site be no more than a few seconds behind the primary at all times. Which data-protection technology BEST meets this requirement?",
        "choices": ["Nightly offsite backups", "Replication", "Weekly snapshots", "Tabletop exercises"],
        "answer": 1,
        "explain": "Replication continuously copies data to another system or site, keeping the secondary within seconds of the primary and supporting a near-zero RPO. Nightly backups or weekly snapshots could lose up to a day or a week of data — far outside the stated tolerance.",
    },
    {
        "type": "mc",
        "q": "A database server crashes mid-afternoon. Administrators restore last night's backup, then use a log of every transaction recorded since that backup to roll the database forward to the moment of the crash. Which capability enabled this?",
        "choices": ["Journaling", "Snapshots", "Load balancing", "Geographic dispersion"],
        "answer": 0,
        "explain": "Journaling records every change or transaction in a log, so after restoring a backup you can replay the journal and reconstruct data right up to the point of failure. A snapshot only returns you to the moment it was taken; it cannot replay the changes made afterward.",
    },
    {
        "type": "mc",
        "q": "Every quarter, an administrator restores randomly selected files and one complete VM from backup media into a test environment to confirm the data is intact and usable. Which backup consideration is being validated?",
        "choices": ["Frequency", "Encryption", "Recovery", "Replication"],
        "answer": 2,
        "explain": "A backup has no value unless it can actually be restored, so regularly testing recovery is essential — media can fail, jobs can silently miss data, and procedures can be wrong. Frequency governs how often backups run, which is a separate consideration from whether they restore successfully.",
    },
    {
        "type": "mc",
        "q": "During a brief utility brownout, a company's servers keep running on battery power for several minutes until normal power returns. Which device provided this protection?",
        "choices": ["Backup generator", "Uninterruptible power supply (UPS)", "Dual power supplies", "A snapshot"],
        "answer": 1,
        "explain": "A UPS delivers immediate battery power the instant utility power sags or fails, riding out short outages or buying time for a clean shutdown or generator start. A generator handles extended outages but takes time to start, and dual power supplies protect against PSU failure, not loss of the utility feed.",
    },
    {
        "type": "mc",
        "q": "A hospital datacenter must remain fully operational through a projected three-day regional power outage. Which solution provides this capability?",
        "choices": [
            "Additional UPS battery capacity",
            "A standby generator with refueling contracts",
            "Dual power supplies in every server",
            "A parallel processing test",
        ],
        "answer": 1,
        "explain": "Only a generator can supply power for days, as long as fuel is available — hence the refueling contracts. UPS batteries last minutes, not days; their job is to bridge the gap until the generator starts. Dual power supplies do nothing when the entire facility has no power.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A cold site provides the fastest recovery time of the three alternate site types.",
        "answer": False,
        "explain": "It is the opposite: a hot site recovers fastest (minutes to hours) because hardware and near-real-time data are already in place, while a cold site is slowest (often weeks) because equipment and data must be brought in after the disaster. Cold sites win on cost, not speed.",
    },
    {
        "type": "tf",
        "q": "True or False: In an active/passive cluster, the standby node processes production traffic only after the active node fails.",
        "answer": True,
        "explain": "In active/passive, the passive node sits idle (or only synchronizes state) until failover, when it takes over the workload. In active/active, all nodes carry production load simultaneously, so a node failure reduces capacity but service continues.",
    },
    {
        "type": "tf",
        "q": "True or False: Because replication continuously copies data to a second site, it eliminates the need for traditional backups.",
        "answer": False,
        "explain": "Replication faithfully copies everything — including corruption, ransomware encryption, and accidental deletions — to the secondary within seconds. Point-in-time backups and snapshots are still required so you can go back to a clean state before the damage occurred.",
    },
    {
        "type": "tf",
        "q": "True or False: A UPS is designed to power a datacenter for several days during an extended outage.",
        "answer": False,
        "explain": "A UPS is a short-term battery bridge measured in minutes: it rides out brief outages and keeps systems up until a generator spins up or systems shut down cleanly. Multi-day outages require a generator with an adequate fuel supply.",
    },
    {
        "type": "tf",
        "q": "True or False: A tabletop exercise requires failing over live production systems to the recovery site.",
        "answer": False,
        "explain": "A tabletop exercise is purely discussion-based: participants talk through the scenario and their responses without touching any systems. Actually moving production to the recovery site is a failover test, the highest-risk and most conclusive form of DR testing.",
    },
    {
        "type": "tf",
        "q": "True or False: Backup frequency should be driven by the organization's recovery point objective (RPO) — the maximum amount of data it can afford to lose.",
        "answer": True,
        "explain": "The RPO defines tolerable data loss in time; backups (or replication) must run at least that often. For example, an RPO of one hour cannot be met with nightly backups — you would need hourly backups, snapshots, journaling, or replication.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "An alternate facility that provides only empty space, power, and connectivity — with no hardware or data staged — is called a ______ site. (type your answer)",
        "answers": ["cold", "cold site"],
        "explain": "A cold site is the cheapest recovery site because nothing is pre-staged, but it has the longest recovery time: servers, network gear, and data must all be brought in and set up after the disaster. Warm sites add hardware; hot sites add hardware plus current data.",
    },
    {
        "type": "fill",
        "q": "The battery-based device that provides immediate short-term power so systems can ride out brief outages or shut down cleanly is a(n) ______. (type your answer)",
        "answers": ["ups", "uninterruptible power supply", "uninterruptable power supply", "u.p.s."],
        "explain": "An uninterruptible power supply (UPS) switches to battery instantly when utility power fails, protecting against short outages, sags, and surges. Its runtime is minutes — just enough to bridge to a generator or perform a graceful shutdown.",
    },
    {
        "type": "fill",
        "q": "A point-in-time image of a virtual machine or storage volume that can be quickly reverted to is called a ______. (type your answer)",
        "answers": ["snapshot", "snapshots"],
        "explain": "Snapshots capture the exact state of a VM, volume, or filesystem at a moment in time and allow near-instant rollback, which is why administrators take one before patches and risky changes. They complement, but do not replace, full backups stored on separate media.",
    },
    {
        "type": "fill",
        "q": "Recording every change or transaction in a log so data can be rolled forward and rebuilt to an exact point in time is called ______. (type your answer)",
        "answers": ["journaling", "journalling", "transaction journaling"],
        "explain": "Journaling keeps a running log of every transaction or change. After restoring the most recent backup, replaying the journal reconstructs all activity up to the moment of failure, enabling very fine-grained recovery that periodic backups alone cannot provide.",
    },
    {
        "type": "fill",
        "q": "A discussion-based exercise in which stakeholders talk through a disaster scenario without touching any systems is a ______ exercise. (type your answer)",
        "answers": ["tabletop", "table top", "table-top", "tabletop exercise"],
        "explain": "Tabletop exercises are the lowest-cost, lowest-risk form of continuity testing: the team walks through the plan verbally to find gaps and clarify roles. They should be complemented by hands-on tests like simulations, parallel processing, and failover tests.",
    },
    {
        "type": "fill",
        "q": "Deploying workloads across two or more different cloud providers so that no single provider outage can take services down is called a ______ strategy. (type your answer)",
        "answers": ["multi-cloud", "multicloud", "multi cloud"],
        "explain": "A multi-cloud system spreads services across multiple cloud vendors, protecting against a provider-wide outage and reducing vendor lock-in. It is essentially platform diversity applied to cloud service providers.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each site consideration to its description.",
        "pairs": [
            ["Hot site", "Fully equipped with near-real-time data; ready in minutes to hours"],
            ["Warm site", "Hardware and connectivity in place, but data must be restored from backup"],
            ["Cold site", "Empty facility with only space, power, and connectivity"],
            ["Geographic dispersion", "Sites separated so one regional disaster cannot affect them all"],
        ],
        "explain": "Site types trade cost against recovery speed: hot sites are the fastest and most expensive, cold sites are the cheapest and slowest, and warm sites fall in between. Geographic dispersion is a separate consideration about physical distance between sites.",
    },
    {
        "type": "match",
        "q": "Match each resilience test type to its description.",
        "pairs": [
            ["Tabletop exercise", "Discussion-based walkthrough; no systems are touched"],
            ["Fail over", "Deliberately shift production onto the redundant system or site"],
            ["Simulation", "Responders execute procedures in a realistic mock scenario"],
            ["Parallel processing", "Run the workload at both sites simultaneously and compare results"],
        ],
        "explain": "Test types escalate in realism and risk: tabletop (talk only), simulation (hands-on practice without production impact), parallel processing (both sites run at once, primary stays up), and failover (production actually moves — the ultimate proof, and the riskiest).",
    },
    {
        "type": "match",
        "q": "Match each backup concept to its description.",
        "pairs": [
            ["Snapshot", "Point-in-time image of a VM or volume for quick rollback"],
            ["Replication", "Continuous copying of data to another system or site"],
            ["Journaling", "Log of every transaction, enabling roll-forward to a point in time"],
            ["Onsite backup", "Fast restores, but vulnerable to a disaster at the primary facility"],
            ["Offsite backup", "Survives a fire or flood that destroys the primary site"],
        ],
        "explain": "These techniques layer together: snapshots give fast local rollback, replication keeps a second site current, journaling fills the gap between backups, and keeping copies both onsite (speed) and offsite (disaster survival) follows the 3-2-1 principle.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the power events in the order they occur during an extended utility outage at a well-designed datacenter.",
        "items": [
            "Utility power fails",
            "The UPS batteries immediately carry the electrical load",
            "The standby generator starts and stabilizes",
            "The load transfers from the UPS to generator power",
            "Utility power is restored and the load transfers back",
        ],
        "explain": "The UPS reacts instantly, bridging the seconds-to-minutes gap while the generator starts and reaches stable output; the generator then carries the load for the duration of the outage. This is why both are needed: the UPS alone cannot last, and the generator alone cannot react instantly.",
    },
]
