TOPIC = {
    "id": "4.1",
    "domain": 4,
    "title": "Given a scenario, apply common security techniques to computing resources.",
    "short": "Securing Computing Resources",
}

TERMS = [
    ("Secure baseline", "A documented set of minimum-security configuration settings for a system type; the lifecycle is establish, deploy, and maintain"),
    ("Hardening", "Reducing a system's attack surface by removing unnecessary software/services, closing ports, patching, and changing default credentials"),
    ("Attack surface", "The total set of points where an attacker could interact with or exploit a system; hardening aims to shrink it"),
    ("Mobile device management (MDM)", "Centralized platform to enforce policy on mobile devices: passcodes, encryption, app control, containerization, and remote wipe"),
    ("BYOD (bring your own device)", "Deployment model where employees use personally owned devices for work; the user owns the hardware, raising privacy and control challenges"),
    ("COPE (corporate-owned, personally enabled)", "Deployment model where the company owns and issues the device but permits reasonable personal use"),
    ("CYOD (choose your own device)", "Deployment model where employees select a device from a company-approved list; the organization retains ownership and control"),
    ("Site survey", "Assessment of a facility's RF environment (coverage, interference, obstacles) performed to plan wireless access point placement"),
    ("Heat map", "Color-coded graphical representation of wireless signal strength across a floor plan, typically produced from site survey data"),
    ("WPA3 (Wi-Fi Protected Access 3)", "Current Wi-Fi security standard using AES encryption; Personal mode replaces the WPA2 PSK handshake with SAE"),
    ("SAE (Simultaneous Authentication of Equals)", "WPA3-Personal key exchange that resists offline dictionary attacks and provides forward secrecy"),
    ("RADIUS", "Centralized AAA server protocol; in enterprise wireless it works with 802.1X to authenticate each user individually"),
    ("AAA (authentication, authorization, accounting)", "Framework that verifies identity, grants appropriate access, and logs activity; implemented by servers such as RADIUS"),
    ("802.1X", "Port-based network access control standard that forces devices to authenticate (via EAP to a RADIUS server) before gaining network access"),
    ("EAP (Extensible Authentication Protocol)", "Authentication framework used within 802.1X that supports many methods (e.g., certificates, protected credentials)"),
    ("Input validation", "Application security technique that checks and rejects malformed or malicious user input before processing, blocking injection attacks"),
    ("Secure cookies", "Cookies flagged with the Secure attribute so browsers transmit them only over encrypted HTTPS connections"),
    ("Static code analysis", "Examining application source code for flaws without executing the program, often with automated SAST tools"),
    ("Code signing", "Applying a digital signature to software so users can verify the publisher's identity and that the code has not been altered"),
    ("Sandboxing", "Running code in an isolated environment so it cannot affect production systems; used for testing and malware detonation"),
    ("Monitoring", "Continuous observation of systems, logs, and configurations to detect anomalies and deviations from the secure baseline"),
    ("ICS/SCADA", "Industrial control and supervisory systems that run physical processes; hardened primarily through network segmentation and isolation"),
    ("Embedded system", "Computer built into a larger device for a dedicated function; often hard to patch and has a long service life"),
    ("RTOS (real-time operating system)", "Operating system that guarantees deterministic, time-critical task scheduling; common in industrial and vehicle controllers"),
    ("IoT (Internet of Things)", "Network-connected smart devices (cameras, sensors, appliances); hardened by changing default credentials, patching firmware, and segmentation"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An administrator wants a documented standard of minimum-security configuration settings that every newly built server must match before going into production. What is this called?",
        "choices": ["A secure baseline", "A heat map", "A sandbox", "An acceptable use policy"],
        "answer": 0,
        "explain": "A secure baseline is the documented set of required security configurations for a system type. New systems are built to the baseline, and existing systems are compared against it. A heat map shows wireless coverage, and a sandbox is an isolated execution environment — neither is a configuration standard.",
    },
    {
        "type": "mc",
        "q": "A security team is establishing a secure baseline for the company's Windows workstations. Which of the following is the BEST starting point?",
        "choices": [
            "A packet capture of typical workstation traffic",
            "An industry benchmark such as a CIS or vendor hardening guide",
            "A wireless site survey of the office",
            "The results of last year's phishing simulation",
        ],
        "answer": 1,
        "explain": "Establishing a baseline should start from trusted, community-vetted sources such as CIS Benchmarks or vendor security guides, then be tailored to the organization. Packet captures, site surveys, and phishing results do not define secure configuration settings.",
    },
    {
        "type": "mc",
        "q": "After a secure baseline is approved, the team must apply it consistently to 2,000 workstations. Which approach BEST accomplishes the deploy step?",
        "choices": [
            "Email each user instructions to change their own settings",
            "Manually configure each machine during lunch breaks",
            "Use Group Policy or a configuration management tool to push the settings automatically",
            "Wait for the settings to propagate during the next hardware refresh",
        ],
        "answer": 2,
        "explain": "Baselines should be deployed with automation — Group Policy, MDM, or configuration management tooling — so every system receives identical, verifiable settings. Manual or user-driven configuration is slow, error-prone, and impossible to audit at scale.",
    },
    {
        "type": "mc",
        "q": "A monthly compliance scan shows that dozens of servers no longer match the approved secure baseline because admins made ad hoc changes. Which activity addresses this problem?",
        "choices": [
            "Maintaining the baseline by detecting and remediating configuration drift",
            "Re-establishing a brand-new baseline from scratch each month",
            "Performing a wireless site survey",
            "Code signing the servers' applications",
        ],
        "answer": 0,
        "explain": "The maintain phase of the baseline lifecycle means continuously auditing systems for deviation (drift) and remediating it, as well as updating the baseline when threats and patches change. Rebuilding the baseline monthly does not fix undisciplined changes, and site surveys and code signing are unrelated.",
    },
    {
        "type": "mc",
        "q": "Which of the following actions BEST hardens an end-user workstation?",
        "choices": [
            "Enable the guest account for troubleshooting convenience",
            "Remove unneeded software, disable unused services, and keep patches current",
            "Grant all users local administrator rights to reduce help-desk tickets",
            "Disable the host-based firewall to improve performance",
        ],
        "answer": 1,
        "explain": "Workstation hardening shrinks the attack surface: uninstall unnecessary applications, disable unused services and ports, apply patches promptly, and run a host firewall and endpoint protection. Enabling guest accounts, granting admin rights, and disabling the firewall all expand the attack surface.",
    },
    {
        "type": "mc",
        "q": "A network technician is hardening an access switch in a shared office lobby. Which combination of actions is MOST appropriate?",
        "choices": [
            "Enable all ports and broadcast the management password to staff",
            "Replace the switch with a hub to simplify monitoring",
            "Move all VLANs onto VLAN 1 for consistency",
            "Disable unused ports and enable port security to limit learned MAC addresses",
        ],
        "answer": 3,
        "explain": "Switch hardening includes shutting down unused ports and using port security so only a limited set of MAC addresses can connect, preventing rogue devices in accessible areas. Consolidating onto the default VLAN and using hubs weaken security rather than improve it.",
    },
    {
        "type": "mc",
        "q": "During an audit, a router is found still using the vendor's default administrator password and running an unencrypted web management interface. What should be done FIRST to harden it?",
        "choices": [
            "Change the default credentials and disable or encrypt the management services",
            "Add more RAM to the router",
            "Enable SSID broadcasting",
            "Sign the router's configuration file with a code-signing certificate",
        ],
        "answer": 0,
        "explain": "Default credentials are one of the most exploited weaknesses on network devices — change them immediately and restrict management to secure, encrypted methods. SSID broadcasting applies to wireless APs, and code signing applies to software distribution, not router logins.",
    },
    {
        "type": "mc",
        "q": "A cloud security review finds a storage bucket containing customer records that is readable by anyone on the internet. Which hardening principle was violated?",
        "choices": [
            "Failure to conduct a wireless site survey",
            "Secure configuration and least-privilege access to cloud resources",
            "Lack of an RTOS on the storage nodes",
            "Missing Bluetooth pairing controls",
        ],
        "answer": 1,
        "explain": "Hardening cloud infrastructure means applying secure configurations — private-by-default storage, least-privilege IAM permissions, and encryption — because misconfiguration is a leading cause of cloud data exposure. Site surveys, RTOS, and Bluetooth have nothing to do with storage bucket permissions.",
    },
    {
        "type": "mc",
        "q": "A water treatment plant's SCADA network currently shares a flat network with corporate office computers. Which control BEST hardens the SCADA environment?",
        "choices": [
            "Install a consumer antivirus product on the PLCs",
            "Enable BYOD so operators can monitor pumps from personal phones",
            "Segment the SCADA systems onto an isolated network separated from the corporate LAN",
            "Publish the HMI to the internet so vendors can assist remotely",
        ],
        "answer": 2,
        "explain": "ICS/SCADA systems are hardened primarily through network segmentation or isolation (even air-gapping), because the controllers often cannot run endpoint agents or be patched frequently. Exposing HMIs to the internet or mixing them with corporate and personal devices dramatically increases risk.",
    },
    {
        "type": "mc",
        "q": "A hospital uses infusion pumps with an embedded operating system that the vendor no longer patches. The devices must remain in service. What is the BEST compensating control?",
        "choices": [
            "Isolate the pumps on a dedicated, segmented network with restricted access",
            "Install host-based EDR agents on each pump",
            "Rewrite the pump firmware in-house",
            "Enroll the pumps in the corporate BYOD program",
        ],
        "answer": 0,
        "explain": "Embedded systems often cannot be patched or run security agents, so the standard compensating control is network segmentation with tight access restrictions to limit exposure. Installing EDR or rewriting vendor firmware is typically impossible or unsupported, and BYOD is unrelated.",
    },
    {
        "type": "mc",
        "q": "Which system MOST likely runs a real-time operating system (RTOS)?",
        "choices": [
            "A marketing employee's laptop running office software",
            "A virtualized web server farm in the cloud",
            "A file server hosting departmental shares",
            "An industrial robot controller that must respond to sensor input within strict time limits",
        ],
        "answer": 3,
        "explain": "An RTOS guarantees deterministic, time-bound processing, which is essential for industrial controllers, vehicles, and medical hardware where a late response is a failure. General-purpose laptops and servers use conventional operating systems that prioritize throughput over timing guarantees.",
    },
    {
        "type": "mc",
        "q": "An organization is installing dozens of IP cameras and smart sensors. Which action should be performed FIRST when hardening these IoT devices?",
        "choices": [
            "Run static code analysis on the camera firmware source",
            "Change the default credentials on every device",
            "Perform a heat map of camera coverage",
            "Enable SAE on the cameras' wired interfaces",
        ],
        "answer": 1,
        "explain": "IoT devices ship with well-known default usernames and passwords that botnets actively exploit, so changing default credentials is the first hardening step, followed by firmware updates and network segmentation. Vendors rarely release firmware source for analysis, and SAE is a WPA3 wireless key exchange, not a wired setting.",
    },
    {
        "type": "mc",
        "q": "An executive reports that a corporate smartphone containing sensitive email was left in a taxi. Which capability allows the security team to protect the data immediately?",
        "choices": [
            "Remote wipe issued through the MDM platform",
            "A wireless site survey of the taxi route",
            "Static code analysis of the mail app",
            "Re-imaging the executive's desktop workstation",
        ],
        "answer": 0,
        "explain": "MDM platforms provide remote lock and remote wipe so a lost or stolen device's data can be erased before it is compromised, backed by enforced passcodes and full-device encryption. The other options do nothing to protect data on the missing phone.",
    },
    {
        "type": "mc",
        "q": "Before installing wireless access points in a newly leased office, a network engineer walks the floor with analysis software to measure RF interference and identify optimal AP placement. What is this activity called?",
        "choices": ["A vulnerability scan", "War driving", "A site survey", "Penetration testing"],
        "answer": 2,
        "explain": "A site survey assesses the RF environment — existing signals, interference sources, building materials, and coverage needs — before deploying wireless. Its output often includes a heat map. War driving is an attacker technique for discovering wireless networks, not a planned installation step.",
    },
    {
        "type": "mc",
        "q": "A company adopting BYOD wants to keep corporate email and documents in an encrypted, managed workspace on employee phones while leaving personal photos and apps untouched. Which MDM feature accomplishes this?",
        "choices": ["Containerization", "Code signing", "A captive portal", "Port security"],
        "answer": 0,
        "explain": "Containerization creates a separate, policy-controlled and encrypted workspace for corporate data on a personal device, enabling selective wipe of only the corporate container. Code signing verifies software integrity, captive portals handle guest network sign-on, and port security is a switch control.",
    },
    {
        "type": "mc",
        "q": "A firm purchases smartphones for all employees and permits reasonable personal use of the company-owned devices. Which mobile deployment model is this?",
        "choices": ["BYOD", "COPE", "CYOD", "VDI"],
        "answer": 1,
        "explain": "COPE (corporate-owned, personally enabled) means the organization buys and controls the device but allows personal use. BYOD is employee-owned hardware, and CYOD lets employees pick from an approved list of company-purchased devices.",
    },
    {
        "type": "mc",
        "q": "To balance user preference with corporate control, an organization lets each employee select a smartphone from a short list of approved models that the company purchases and manages. Which deployment model is this?",
        "choices": ["BYOD", "COPE", "Jailbreaking", "CYOD"],
        "answer": 3,
        "explain": "CYOD (choose your own device) gives users a choice among company-approved, company-owned devices, simplifying support and security while offering some flexibility. COPE typically issues a standard corporate device, and BYOD relies on hardware the employee already owns.",
    },
    {
        "type": "mc",
        "q": "A security policy requires that company phones be non-discoverable and that this short-range wireless radio be disabled when not in use, to reduce eavesdropping and unauthorized pairing risks. Which connection method does this address?",
        "choices": ["Cellular", "Bluetooth", "Wi-Fi", "Ethernet"],
        "answer": 1,
        "explain": "Bluetooth is a short-range pairing-based technology; leaving it discoverable exposes devices to attacks such as bluejacking and bluesnarfing, so hardening guidance says disable it when unused and avoid pairing in public. Cellular and Wi-Fi have different threat profiles and controls.",
    },
    {
        "type": "mc",
        "q": "Employees have been tethering laptops to their phones' mobile hotspots, which routes traffic around the corporate firewall and web filtering. Which connection method creates this bypass?",
        "choices": ["Bluetooth", "NFC", "Cellular", "802.1X"],
        "answer": 2,
        "explain": "Cellular connections go through the carrier's network rather than the corporate perimeter, so security controls like firewalls, proxies, and DLP never see the traffic. This is a classic risk of hotspot tethering. Bluetooth and NFC are short-range links, and 802.1X is an authentication standard, not a connection method.",
    },
    {
        "type": "mc",
        "q": "A small office wants to stop attackers from capturing its Wi-Fi handshake and cracking the passphrase offline. Which wireless upgrade BEST addresses this?",
        "choices": [
            "Migrate to WPA3-Personal, which uses SAE",
            "Re-enable WEP for compatibility",
            "Hide the SSID",
            "Switch encryption from AES to TKIP",
        ],
        "answer": 0,
        "explain": "WPA3-Personal replaces the WPA2 pre-shared key handshake with SAE, which resists offline dictionary attacks and provides forward secrecy. WEP and TKIP are deprecated, broken protocols, and hiding the SSID provides no cryptographic protection.",
    },
    {
        "type": "mc",
        "q": "An enterprise wants each employee to log in to the corporate Wi-Fi with individual credentials that are validated by a central authentication server, instead of sharing one passphrase. Which solution meets this requirement?",
        "choices": [
            "WPA3-Personal with a stronger shared passphrase",
            "802.1X authentication against a RADIUS server (WPA3-Enterprise)",
            "MAC address filtering on each access point",
            "A captive portal with a shared guest password",
        ],
        "answer": 1,
        "explain": "Enterprise wireless uses 802.1X, where the access point passes EAP credentials to a central RADIUS server for per-user AAA — authentication, authorization, and accounting. A shared passphrase (even WPA3-Personal) cannot identify individual users, and MAC filtering is easily spoofed.",
    },
    {
        "type": "mc",
        "q": "A company wants the strongest wireless authentication available: every laptop must present its own client certificate and mutually authenticate with the RADIUS server over 802.1X. Which EAP variant meets this requirement?",
        "choices": ["PEAP", "EAP-FAST", "EAP-TLS", "EAP-TTLS"],
        "answer": 2,
        "explain": "EAP-TLS performs mutual, certificate-based TLS authentication — the server and every client each present a certificate — making it the most secure EAP variant, though it requires a PKI to issue client certificates. PEAP and EAP-TTLS require only a server certificate and tunnel an inner credential exchange, and EAP-FAST builds its tunnel from a Protected Access Credential rather than client certificates.",
    },
    {
        "type": "mc",
        "q": "While configuring a new access point, an administrator reviews the available wireless cryptographic protocols. Which option pairs the standards with strong, non-deprecated encryption?",
        "choices": [
            "WEP with RC4",
            "WPA with TKIP",
            "WPA2 with AES-CCMP and WPA3 with AES-GCMP",
            "WPA3 with RC4 per-packet keys",
        ],
        "answer": 2,
        "explain": "WPA2 uses AES-CCMP and WPA3 uses AES-GCMP — the acceptable, AES-based cryptographic protocols. WEP and WPA/TKIP are deprecated RC4-based schemes that are trivially attacked, and WPA3 does not use RC4 at all.",
    },
    {
        "type": "mc",
        "q": "A web application passes user-supplied text from a search box directly into database queries, and testers were able to inject SQL commands. Which application security technique BEST prevents this?",
        "choices": [
            "Server-side input validation",
            "Setting the Secure attribute on cookies",
            "Code signing the deployed binaries",
            "Generating a wireless heat map",
        ],
        "answer": 0,
        "explain": "Input validation checks user-supplied data against expected formats and rejects or sanitizes anything malicious before it reaches the database, and it must be enforced server-side because client-side checks can be bypassed. Secure cookies protect session tokens in transit, and code signing verifies software publishers — neither stops injection.",
    },
    {
        "type": "mc",
        "q": "An assessment finds that a web app's session cookies are transmitted over unencrypted HTTP connections, where they could be intercepted. Which cookie setting fixes this?",
        "choices": [
            "The Secure attribute, so cookies are sent only over HTTPS",
            "A longer cookie expiration time",
            "Storing the session ID in the URL instead",
            "Base64-encoding the cookie value",
        ],
        "answer": 0,
        "explain": "The Secure attribute instructs browsers to send the cookie only over encrypted HTTPS, preventing interception on plaintext connections; HttpOnly additionally blocks script access to the cookie. Longer expirations increase exposure, URLs leak session IDs in logs, and Base64 is encoding, not encryption.",
    },
    {
        "type": "mc",
        "q": "A malware analyst receives a suspicious email attachment and wants to observe its behavior without any risk to production systems. Where should the file be executed?",
        "choices": [
            "On the analyst's daily-use workstation",
            "On the domain controller, where logging is best",
            "In an isolated sandbox environment",
            "On a random user's machine to simulate real conditions",
        ],
        "answer": 2,
        "explain": "Sandboxing runs untrusted code in an isolated environment — often a disposable virtual machine — so its behavior can be observed safely and any damage is contained. Detonating malware on production systems, especially a domain controller, risks a full compromise.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Static code analysis identifies vulnerabilities by executing the application and observing its runtime behavior.",
        "answer": False,
        "explain": "Static code analysis examines source code without running it, typically with automated SAST tools that flag issues such as missing input validation or hardcoded credentials. Testing that observes a running application is dynamic analysis.",
    },
    {
        "type": "tf",
        "q": "True or False: In a BYOD deployment model, the organization purchases and owns the mobile devices that employees use.",
        "answer": False,
        "explain": "In BYOD (bring your own device), the employee owns the hardware and the organization manages only corporate data and access, which creates privacy and control challenges. COPE and CYOD are the models where the organization owns the device.",
    },
    {
        "type": "tf",
        "q": "True or False: A heat map is a color-coded visualization of wireless signal strength across a floor plan, commonly produced from site survey data.",
        "answer": True,
        "explain": "Heat maps display measured signal coverage over a building layout, revealing dead zones, overlap, and interference so AP placement can be tuned. They are a standard output of the wireless site survey process.",
    },
    {
        "type": "tf",
        "q": "True or False: Once a secure baseline has been deployed to all systems, the baseline process is complete and no further action is required.",
        "answer": False,
        "explain": "The baseline lifecycle is establish, deploy, and maintain. Maintenance is ongoing: systems must be monitored for configuration drift, deviations remediated, and the baseline itself updated as new vulnerabilities, patches, and business needs emerge.",
    },
    {
        "type": "tf",
        "q": "True or False: A real-time operating system (RTOS) is designed to guarantee that critical tasks complete within strict, predictable time constraints.",
        "answer": True,
        "explain": "An RTOS uses deterministic scheduling so time-critical operations always execute within their deadlines, which is why it appears in industrial controllers, vehicles, and medical devices. General-purpose operating systems optimize for overall throughput instead and cannot make such timing guarantees.",
    },
    {
        "type": "tf",
        "q": "True or False: Removing unneeded roles, features, and services from a server reduces its attack surface.",
        "answer": True,
        "explain": "Server hardening follows the principle of least functionality: every unnecessary service, role, or open port is a potential entry point, so removing them shrinks the attack surface. This is combined with patching, strong authentication, and secure configuration per the baseline.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "WPA3-Personal replaces the WPA2 pre-shared key handshake with ______, a key exchange that resists offline dictionary attacks. (type the acronym or name)",
        "answers": ["sae", "simultaneous authentication of equals"],
        "explain": "SAE (Simultaneous Authentication of Equals) is WPA3-Personal's password-authenticated key exchange. It prevents attackers from capturing a handshake and brute-forcing the passphrase offline, and it provides forward secrecy for each session.",
    },
    {
        "type": "fill",
        "q": "The color-coded diagram overlaid on a floor plan that shows measured wireless signal strength is called a ______. (type your answer)",
        "answers": ["heat map", "heatmap", "wireless heat map"],
        "explain": "A heat map visualizes Wi-Fi coverage and dead zones across a building and is typically generated during or after a site survey. It guides access point placement and power adjustments during wireless installation.",
    },
    {
        "type": "fill",
        "q": "Digitally signing software so users can verify the publisher's identity and confirm the code has not been modified is called ______. (type your answer)",
        "answers": ["code signing", "codesigning"],
        "explain": "Code signing applies a digital signature, backed by a certificate, to executables and scripts. Operating systems and browsers use the signature to confirm authenticity and integrity, warning users when software is unsigned or has been tampered with.",
    },
    {
        "type": "fill",
        "q": "In WPA3-Enterprise wireless, 802.1X forwards user credentials to a centralized AAA server running the ______ protocol. (type the acronym)",
        "answers": ["radius", "remote authentication dial-in user service"],
        "explain": "RADIUS (Remote Authentication Dial-In User Service) is the centralized AAA protocol behind enterprise wireless: the access point acts as an authenticator, relaying EAP credentials to the RADIUS server, which authenticates each user and logs the activity.",
    },
    {
        "type": "fill",
        "q": "The centralized platform used to enforce passcodes, push configurations, and remotely wipe smartphones and tablets is known by the acronym ______. (type your answer)",
        "answers": ["mdm", "mobile device management"],
        "explain": "MDM (mobile device management) enrolls devices — corporate-owned or BYOD — and enforces security policy: encryption, screen locks, app restrictions, containerization, and remote lock/wipe when a device is lost or an employee departs.",
    },
    {
        "type": "fill",
        "q": "The ongoing practice of watching systems, logs, and configurations to detect anomalies and deviations from the secure baseline is called ______. (type your answer)",
        "answers": ["monitoring", "continuous monitoring", "security monitoring"],
        "explain": "Monitoring closes the loop on security operations: after baselines are deployed and systems hardened, continuous monitoring detects drift, suspicious behavior, and policy violations so they can be remediated quickly.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each mobile solution term to its description.",
        "pairs": [
            ["BYOD", "Employees use devices they personally own for work"],
            ["COPE", "Company owns the device but permits personal use"],
            ["CYOD", "Employee picks from a company-approved device list"],
            ["MDM", "Central platform enforcing policy and remote wipe on devices"],
        ],
        "explain": "The three deployment models differ by ownership and choice: BYOD is user-owned, COPE is corporate-owned with personal use allowed, and CYOD offers user choice among corporate-owned approved models. MDM is the management technology applied across all of them.",
    },
    {
        "type": "match",
        "q": "Match each wireless security term to its role.",
        "pairs": [
            ["SAE", "WPA3-Personal key exchange resisting offline dictionary attacks"],
            ["802.1X", "Port-based access control requiring authentication before network access"],
            ["RADIUS", "Centralized AAA server validating user credentials"],
            ["EAP", "Framework supporting multiple authentication methods"],
            ["AES", "Symmetric block cipher providing WPA2/WPA3 encryption"],
        ],
        "explain": "Enterprise wireless chains these together: the supplicant uses an EAP method inside 802.1X, the access point relays credentials to RADIUS for AAA, and traffic is encrypted with AES. In WPA3-Personal, SAE replaces the shared-passphrase handshake used by WPA2.",
    },
    {
        "type": "match",
        "q": "Match each application security technique to what it accomplishes.",
        "pairs": [
            ["Input validation", "Rejects malformed or malicious user-supplied data"],
            ["Secure cookies", "Ensures cookies travel only over encrypted HTTPS"],
            ["Static code analysis", "Finds flaws in source code without executing it"],
            ["Code signing", "Proves publisher identity and code integrity via digital signature"],
            ["Sandboxing", "Runs untrusted code in an isolated environment"],
        ],
        "explain": "These are the objective's core application security controls: validate input to stop injection, flag cookies Secure to protect sessions in transit, analyze source statically before release, sign code so tampering is detectable, and sandbox untrusted execution to contain damage.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the secure baseline lifecycle activities in the order they occur.",
        "items": [
            "Research industry benchmarks and vendor hardening guides",
            "Establish the baseline configuration for the system type",
            "Deploy the baseline to systems using automated tooling",
            "Monitor systems for deviation from the baseline",
            "Update the baseline as new threats and patches emerge",
        ],
        "explain": "The SY0-701 baseline lifecycle is establish, deploy, maintain. Establishment starts from trusted references like CIS Benchmarks, deployment is automated for consistency, and maintenance is continuous — monitoring for drift and revising the baseline as the threat landscape changes.",
    },
]
