TOPIC = {
    "id": "4.2",
    "domain": 4,
    "title": "Explain the security implications of proper hardware, software, and data asset management.",
    "short": "Asset Management",
}

TERMS = [
    ("Acquisition/procurement process", "Formal process for requesting, vetting, and purchasing hardware/software/services; a security checkpoint that evaluates vendors and requirements before assets enter the environment"),
    ("Assignment/accounting", "Recording each asset and allocating it to a responsible owner so someone is accountable for its security throughout its life"),
    ("Ownership", "Designation of the person or role accountable for an asset's protection, proper use, and lifecycle decisions"),
    ("Data owner", "Senior role with overall accountability for a data set; decides its classification and the access/handling requirements"),
    ("Data custodian/steward", "Role that implements the owner's decisions day to day: backups, permissions, secure storage, and handling per classification"),
    ("Classification", "Labeling assets and data by sensitivity (e.g., public, private, confidential, restricted) so controls and handling match the value of what is protected"),
    ("Monitoring/asset tracking", "Continuously verifying what assets exist, where they are, who has them, and their status throughout the lifecycle"),
    ("Inventory", "The authoritative record (list or database) of all hardware and software assets the organization owns and must protect"),
    ("Enumeration", "Actively identifying/scanning the network to discover devices, software, and services that actually exist — including ones missing from the inventory"),
    ("Asset tagging", "Attaching barcodes, RFID tags, or labels to hardware so physical devices can be linked to inventory records and tracked"),
    ("Standard naming convention", "Consistent scheme for naming assets and hosts that makes inventory, tracking, and management easier and less error-prone"),
    ("Decommissioning", "Formally removing an asset from service: sanitizing data, revoking accounts/certificates/licenses, and updating the inventory"),
    ("Disposal", "Final lifecycle stage — selling, donating, recycling, or destroying an asset only after its data has been properly removed"),
    ("Sanitization", "Process of removing data from storage media so it cannot be recovered, allowing safe reuse or disposal of the media"),
    ("Overwriting (wiping)", "Sanitization by writing patterns over every sector of a drive; effective for magnetic disks but unreliable on SSDs due to wear leveling"),
    ("Cryptographic erase", "Sanitizing a self-encrypting drive by securely destroying its encryption key, leaving only unreadable ciphertext; fast and effective for SSDs"),
    ("Degaussing", "Applying a powerful magnetic field to scramble data on magnetic media (HDDs, tapes); ineffective on SSDs and optical media, and usually leaves the drive unusable"),
    ("Destruction", "Physically destroying media — shredding, pulverizing, incinerating, or drilling — so data can never be recovered and the media cannot be reused"),
    ("Shredding/pulverizing", "Mechanically cutting or grinding media into small fragments or particles; a common physical destruction method for drives and disks"),
    ("Incineration", "Physical destruction by burning media to ash, providing the highest assurance the data is unrecoverable"),
    ("Certification (certificate of destruction)", "Documented attestation — often from a third-party destruction vendor — that specific media was sanitized or destroyed; provides an audit trail"),
    ("Data retention", "Policy defining how long data must be kept, and when it must be destroyed, based on legal, regulatory, and business requirements"),
    ("Legal hold", "Requirement to preserve data relevant to litigation or investigation; it suspends normal retention schedules and automated deletion"),
    ("NIST SP 800-88", "Media sanitization guidelines defining three levels: clear (logical overwrite), purge (recovery infeasible even in a lab, e.g., degauss or crypto erase), and destroy"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "Employees at a company routinely buy SaaS subscriptions and USB devices on corporate cards with no review, and IT often discovers them months later. Which asset-management process is MISSING?",
        "choices": [
            "A formal acquisition/procurement process",
            "Sanitization",
            "Enumeration",
            "Certification of destruction",
        ],
        "answer": 0,
        "explain": "A formal acquisition/procurement process ensures every purchase is reviewed and approved before it enters the environment, preventing shadow IT and unvetted vendors. Enumeration might later discover the rogue assets, but the missing control is the front-door procurement gate; sanitization and certification apply at end of life.",
    },
    {
        "type": "mc",
        "q": "Before purchasing network switches, a security team reviews the vendor's supply chain and security track record. In which phase of the asset lifecycle does this occur?",
        "choices": [
            "Disposal/decommissioning",
            "Monitoring/asset tracking",
            "Acquisition/procurement",
            "Assignment/accounting",
        ],
        "answer": 2,
        "explain": "Vendor vetting and supply-chain risk evaluation happen during acquisition/procurement, before the asset is bought. Catching risky vendors at this stage is far cheaper than discovering compromised or unsupported hardware after deployment.",
    },
    {
        "type": "mc",
        "q": "A new laptop arrives; the help desk records its serial number, applies an asset tag, enters it into the tracking database, and assigns it to a named employee. Which practice does this BEST describe?",
        "choices": [
            "Enumeration",
            "Assignment/accounting",
            "Sanitization",
            "Data retention",
        ],
        "answer": 1,
        "explain": "Assignment/accounting means every asset is recorded and allocated to a responsible owner so someone is accountable for it. Enumeration is active discovery of what is on the network, not the intake/recording step; sanitization and retention are data-lifecycle concerns.",
    },
    {
        "type": "mc",
        "q": "Who is responsible for deciding the classification level of a data set?",
        "choices": [
            "The data custodian",
            "The end users who access it most often",
            "The backup administrator",
            "The data owner",
        ],
        "answer": 3,
        "explain": "The data owner is accountable for the data and decides its classification and access requirements. The data custodian then implements those decisions technically (permissions, backups, storage). Users and backup admins follow the rules; they do not set them.",
    },
    {
        "type": "mc",
        "q": "A spreadsheet is labeled 'Confidential — Internal Use Only,' which triggers encryption and restricted-access requirements. Which asset-management concept is being applied?",
        "choices": [
            "Classification",
            "Enumeration",
            "Certification",
            "Procurement",
        ],
        "answer": 0,
        "explain": "Classification labels data by sensitivity (public, private, confidential, restricted, etc.) so that handling requirements and controls match its value. The label directly drives which safeguards — like encryption and access limits — must be applied.",
    },
    {
        "type": "mc",
        "q": "Which of the following BEST describes the primary security benefit of classifying data assets?",
        "choices": [
            "It guarantees data can never be exfiltrated",
            "It ensures protection and handling are proportional to the data's sensitivity",
            "It removes the need for a data retention policy",
            "It transfers liability to the procurement team",
        ],
        "answer": 1,
        "explain": "Classification lets the organization apply stronger, costlier controls to the most sensitive data and lighter controls to public data — protection proportional to value. It does not guarantee prevention of theft, and retention policies are still required regardless of classification.",
    },
    {
        "type": "mc",
        "q": "An analyst runs a network scan to identify every device and service currently connected, then compares the results to the official asset list. What is the scanning activity called?",
        "choices": [
            "Certification",
            "Classification",
            "Enumeration",
            "Decommissioning",
        ],
        "answer": 2,
        "explain": "Enumeration is actively identifying the devices, software, and services that actually exist on the network. Comparing enumeration results against the inventory reveals unauthorized or forgotten assets that are not being patched or monitored.",
    },
    {
        "type": "mc",
        "q": "Which of the following serves as the authoritative record of all hardware and software an organization must protect?",
        "choices": [
            "The asset inventory",
            "The certificate of destruction",
            "The data retention schedule",
            "The procurement request form",
        ],
        "answer": 0,
        "explain": "The asset inventory is the master list/database of everything the organization owns. Security programs depend on it: you can only patch, monitor, and protect assets you know exist. The other documents cover disposal evidence, retention periods, and purchasing.",
    },
    {
        "type": "mc",
        "q": "What is the MAIN security implication of an incomplete hardware inventory?",
        "choices": [
            "Depreciation reports will be inaccurate",
            "Unknown assets go unpatched and unmonitored, creating hidden attack surface",
            "The company cannot obtain a certificate of destruction",
            "Data classification labels will expire",
        ],
        "answer": 1,
        "explain": "You cannot protect what you do not know you have. Devices missing from inventory are excluded from patching, vulnerability scanning, and monitoring, making them prime footholds for attackers. Depreciation accuracy is a financial issue, not the main security implication.",
    },
    {
        "type": "mc",
        "q": "A critical vulnerability is announced in a software library. Within minutes, the security team produces a list of every server running the affected version. Which practice made this possible?",
        "choices": [
            "Maintaining an up-to-date software asset inventory",
            "Cryptographic erase",
            "A data retention policy",
            "Certified media destruction",
        ],
        "answer": 0,
        "explain": "A current software inventory (tracking installed applications and versions) lets the team instantly scope which systems are affected by a new vulnerability. Without it, the response starts with days of discovery work instead of remediation.",
    },
    {
        "type": "mc",
        "q": "A file server is being retired, and its drives will be reused inside the company. Which process makes the old data unrecoverable while keeping the drives usable?",
        "choices": [
            "Physical destruction",
            "Degaussing",
            "Sanitization by overwriting",
            "Incineration",
        ],
        "answer": 2,
        "explain": "Sanitization methods like overwriting (wiping) remove data while leaving the media functional for reuse. Physical destruction and incineration render drives unusable, and degaussing typically destroys a hard drive's servo data, making it unusable as well.",
    },
    {
        "type": "mc",
        "q": "An organization must quickly sanitize hundreds of self-encrypting SSDs before returning them to the leasing vendor. Which method is FASTEST and effective?",
        "choices": [
            "Cryptographic erase",
            "Degaussing",
            "Multi-pass overwriting",
            "Pulverizing",
        ],
        "answer": 0,
        "explain": "Cryptographic erase destroys the drive's encryption key, instantly leaving only unreadable ciphertext — ideal for self-encrypting drives that must be returned intact. Degaussing does not work on flash media, overwriting SSDs is slow and unreliable, and pulverizing would destroy the leased drives.",
    },
    {
        "type": "mc",
        "q": "Why is simply overwriting every logical sector considered unreliable for sanitizing an SSD?",
        "choices": [
            "SSDs cannot accept write commands after formatting",
            "Wear leveling and spare blocks can retain copies of data the overwrite never touches",
            "Overwriting only works on optical media",
            "SSDs automatically re-encrypt overwritten data",
        ],
        "answer": 1,
        "explain": "SSD controllers use wear leveling and reserve spare/overprovisioned blocks, so writes are remapped and old data can persist in cells the operating system cannot address. That is why cryptographic erase, vendor secure-erase functions, or destruction are preferred for flash media.",
    },
    {
        "type": "mc",
        "q": "Which media type is NOT effectively sanitized by degaussing?",
        "choices": [
            "Magnetic backup tape",
            "A traditional spinning hard disk drive",
            "A solid-state drive",
            "A floppy disk",
        ],
        "answer": 2,
        "explain": "Degaussing scrambles data with a strong magnetic field, which only works on magnetic media such as HDDs, tapes, and floppies. SSDs store data as electrical charges in flash cells, so a degausser has no effect on their contents.",
    },
    {
        "type": "mc",
        "q": "Drives that held top-secret research must be disposed of with the HIGHEST assurance that data can never be recovered; the media will not be reused. Which approach is BEST?",
        "choices": [
            "Single-pass overwrite",
            "Physical destruction such as shredding or incineration",
            "Deleting all files and emptying the recycle bin",
            "Reformatting and reinstalling the operating system",
        ],
        "answer": 1,
        "explain": "When media will never be reused and maximum assurance is required, physical destruction (shredding, pulverizing, incinerating) is the strongest option. Deleting files or reformatting only removes pointers — the underlying data remains recoverable with forensic tools.",
    },
    {
        "type": "mc",
        "q": "A third-party vendor shreds a company's retired drives and provides a signed document listing each drive's serial number and destruction date. What is this document called?",
        "choices": [
            "A certificate of destruction",
            "A data retention schedule",
            "A chain of custody form",
            "An asset classification report",
        ],
        "answer": 0,
        "explain": "A certificate of destruction (or certificate of sanitization) is the vendor's attestation that specific media was destroyed, providing audit evidence that disposal was handled properly. Retention schedules define how long data is kept, and chain of custody tracks evidence handling.",
    },
    {
        "type": "mc",
        "q": "A regulation requires a firm to keep financial transaction records for seven years and then dispose of them. Which policy implements this requirement?",
        "choices": [
            "Acquisition policy",
            "Enumeration policy",
            "Data retention policy",
            "Asset tagging policy",
        ],
        "answer": 2,
        "explain": "A data retention policy defines how long each type of data must be kept — driven by legal, regulatory, and business needs — and when it must be destroyed. Keeping data too briefly risks noncompliance; keeping it too long increases breach exposure and discovery costs.",
    },
    {
        "type": "mc",
        "q": "A company's retention policy says emails are deleted after three years, but the company is now being sued and older emails are relevant to the case. What MUST the company do?",
        "choices": [
            "Continue automated deletion to stay consistent with policy",
            "Place the relevant data under legal hold and suspend its deletion",
            "Degauss the mail server drives",
            "Reclassify the emails as public",
        ],
        "answer": 1,
        "explain": "A legal hold requires preserving data relevant to litigation and overrides normal retention schedules and automated purges. Destroying data under legal hold can constitute spoliation of evidence and lead to severe legal penalties.",
    },
    {
        "type": "mc",
        "q": "Besides sanitizing its storage, which of the following should ALSO occur when a server is decommissioned?",
        "choices": [
            "Update the inventory and revoke the server's accounts, certificates, and licenses",
            "Increase the server's data classification level",
            "Issue a new procurement request for the same server",
            "Enumerate the server's open ports",
        ],
        "answer": 0,
        "explain": "Decommissioning is more than wiping disks: the asset must be removed from inventory, and its credentials, certificates, DNS records, and licenses revoked or reclaimed. Leaving stale accounts or certificates active gives attackers valid-looking credentials tied to a dead system.",
    },
    {
        "type": "mc",
        "q": "An employee configures backup jobs and applies file permissions according to rules set by another role. Which role is the employee performing?",
        "choices": [
            "Data owner",
            "Procurement officer",
            "Data custodian",
            "Auditor",
        ],
        "answer": 2,
        "explain": "The data custodian (steward) handles the day-to-day technical protection of data — backups, permissions, storage — implementing the requirements the data owner sets. The owner decides classification and access rules; the custodian carries them out.",
    },
    {
        "type": "mc",
        "q": "A charity receives donated PCs from a company that only deleted user folders and reinstalled Windows. A student later recovers customer records from a drive. What was the company's mistake?",
        "choices": [
            "It failed to properly sanitize the drives before disposal",
            "It failed to enumerate the donated hardware",
            "It skipped the acquisition process for the PCs",
            "It applied the wrong asset tags",
        ],
        "answer": 0,
        "explain": "Deleting files or reinstalling an OS does not remove the underlying data, which remains recoverable with basic forensic tools. Media must be properly sanitized — overwritten, cryptographically erased, or destroyed — before leaving the organization's control.",
    },
    {
        "type": "mc",
        "q": "A hospital attaches RFID tags to portable medical devices so their location and assigned department can be checked at any time. Which asset-management function does this support?",
        "choices": [
            "Data retention",
            "Monitoring/asset tracking",
            "Sanitization",
            "Certification",
        ],
        "answer": 1,
        "explain": "Asset tagging with barcodes or RFID supports monitoring/asset tracking — knowing where each asset is, who has it, and its status. Tracking deters theft, speeds audits, and ensures mobile devices holding sensitive data do not silently disappear.",
    },
    {
        "type": "mc",
        "q": "Under NIST SP 800-88 terminology, which sanitization level makes data recovery infeasible even using state-of-the-art laboratory techniques, for example via degaussing or cryptographic erase?",
        "choices": [
            "Clear",
            "Purge",
            "Retain",
            "Classify",
        ],
        "answer": 1,
        "explain": "NIST SP 800-88 defines three levels: clear (logical techniques like a standard overwrite, protecting against simple recovery), purge (techniques like degaussing or cryptographic erase that defeat even laboratory recovery), and destroy (physical destruction of the media).",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Quick-formatting a hard drive is sufficient sanitization before the drive leaves the organization.",
        "answer": False,
        "explain": "Formatting mainly rebuilds file system structures; the underlying data remains on the platters and is easily recovered with forensic tools. Proper sanitization requires overwriting, cryptographic erase, degaussing, or physical destruction.",
    },
    {
        "type": "tf",
        "q": "True or False: Degaussing a modern hard disk drive typically renders the drive permanently unusable.",
        "answer": True,
        "explain": "The magnetic field erases not just the data but also the factory-written servo and firmware information the drive needs to operate, so a degaussed HDD generally cannot be reused. Choose overwriting or cryptographic erase if the drive must remain functional.",
    },
    {
        "type": "tf",
        "q": "True or False: Data retention periods are set purely for business convenience and are never dictated by laws or regulations.",
        "answer": False,
        "explain": "Retention requirements are frequently imposed by laws and regulations (financial, healthcare, tax, and privacy rules), which mandate minimum keep periods and sometimes maximum ones. Retention policy must satisfy these legal obligations, not just business preference.",
    },
    {
        "type": "tf",
        "q": "True or False: Enumeration can reveal devices connected to the network that are missing from the official asset inventory.",
        "answer": True,
        "explain": "Enumeration actively discovers what is really on the network, so comparing its results to the inventory exposes rogue, forgotten, or shadow-IT assets. Those unaccounted devices are a security risk because nothing unknown gets patched or monitored.",
    },
    {
        "type": "tf",
        "q": "True or False: The data custodian, rather than the data owner, is responsible for deciding how data should be classified.",
        "answer": False,
        "explain": "Classification decisions belong to the data owner, who is accountable for the data and understands its business value. The custodian's job is to implement the owner's decisions through technical controls like permissions, encryption, and backups.",
    },
    {
        "type": "tf",
        "q": "True or False: A certificate of destruction provides documented, auditable evidence that specific media was destroyed.",
        "answer": True,
        "explain": "The certificate — usually listing serial numbers, method, date, and the responsible party — proves to auditors and regulators that end-of-life media was properly destroyed. Without it, an organization cannot demonstrate that disposed drives did not leak data.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Sanitizing magnetic tapes by exposing them to a powerful magnetic field is called ______. (type your answer)",
        "answers": ["degaussing", "degauss", "degaussing the media", "using a degausser"],
        "explain": "Degaussing scrambles the magnetic domains that store data on tapes and hard drives, making the data unrecoverable. It only works on magnetic media — it is useless against SSDs and optical discs — and usually leaves hard drives inoperable.",
    },
    {
        "type": "fill",
        "q": "Sanitizing a self-encrypting drive by securely destroying its encryption key is called ______ erase. (type your answer)",
        "answers": ["cryptographic", "crypto", "cryptographic erase", "crypto erase"],
        "explain": "Cryptographic erase deletes the media encryption key so the remaining ciphertext can never be decrypted. It is nearly instant and works well on SSDs, where traditional overwriting is unreliable because of wear leveling.",
    },
    {
        "type": "fill",
        "q": "The signed document a destruction vendor provides to prove specific drives were destroyed is a certificate of ______. (type your answer)",
        "answers": ["destruction", "sanitization", "destruction/sanitization"],
        "explain": "A certificate of destruction (or sanitization) attests that listed media was destroyed or sanitized, when, and by what method. It is the audit evidence that closes out the disposal phase of the asset lifecycle.",
    },
    {
        "type": "fill",
        "q": "The policy that defines how long each type of data must be kept before disposal is the data ______ policy. (type your answer)",
        "answers": ["retention", "retention policy", "data retention"],
        "explain": "Data retention policy balances legal and regulatory keep requirements against the risk and cost of holding data too long. Data kept beyond its required period only increases breach exposure and e-discovery burden.",
    },
    {
        "type": "fill",
        "q": "Actively scanning the network to identify all connected devices and services, often to compare against the inventory, is called ______. (type your answer)",
        "answers": ["enumeration", "enumerating", "asset enumeration"],
        "explain": "Enumeration discovers what actually exists on the network rather than what records say should exist. Gaps between enumeration results and the inventory expose rogue or unmanaged assets that need to be brought under control.",
    },
    {
        "type": "fill",
        "q": "The role accountable for a data set who determines its classification is the data ______. (type your answer)",
        "answers": ["owner", "data owner"],
        "explain": "The data owner holds ultimate accountability for the data and sets its classification and access requirements. This differs from the custodian/steward, who implements those requirements through day-to-day technical controls.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each sanitization or destruction method to its description.",
        "pairs": [
            ["Overwriting (wiping)", "Writing patterns across every sector so prior data cannot be read"],
            ["Degaussing", "Strong magnetic field scrambles data on magnetic media"],
            ["Cryptographic erase", "Destroying the encryption key so only unreadable ciphertext remains"],
            ["Shredding/pulverizing", "Mechanically reducing media to small fragments or particles"],
            ["Incineration", "Burning media to ash for maximum assurance"],
        ],
        "explain": "Overwriting and cryptographic erase sanitize media that may be reused; degaussing works only on magnetic media and usually kills the drive; shredding, pulverizing, and incineration are physical destruction methods used when media will never be reused.",
    },
    {
        "type": "match",
        "q": "Match each asset-management term to its description.",
        "pairs": [
            ["Data owner", "Accountable for the data; decides its classification"],
            ["Data custodian", "Implements backups and permissions per the owner's rules"],
            ["Inventory", "Authoritative record of all hardware and software assets"],
            ["Enumeration", "Active discovery of devices and services on the network"],
            ["Asset tagging", "Physical labels/RFID linking hardware to tracking records"],
        ],
        "explain": "Owners make classification and access decisions while custodians execute them. The inventory is the record of what should exist, enumeration verifies what actually exists, and asset tags tie physical devices to their inventory entries.",
    },
    {
        "type": "match",
        "q": "Match each asset lifecycle phase to its key security activity.",
        "pairs": [
            ["Acquisition/procurement", "Vetting vendors and requirements before purchase"],
            ["Assignment/accounting", "Recording the asset and giving it an owner and classification"],
            ["Monitoring/asset tracking", "Maintaining inventory and enumerating what is deployed"],
            ["Disposal/decommissioning", "Sanitizing or destroying media and obtaining certification"],
        ],
        "explain": "Each phase has a distinct security job: procurement filters what comes in, assignment creates accountability, monitoring keeps records true over time, and disposal ensures data does not walk out the door on retired equipment.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange these asset lifecycle steps in the order they occur, from first to last.",
        "items": [
            "Acquisition/procurement of the asset",
            "Assignment of an owner and classification",
            "Ongoing monitoring, inventory, and tracking",
            "Sanitization of data at decommissioning",
            "Destruction or disposal with certification",
        ],
        "explain": "The lifecycle runs acquisition, then assignment/accounting (ownership and classification), then continuous monitoring/tracking during use, and finally decommissioning: data is sanitized, and media is destroyed or disposed of with a certificate documenting the process.",
    },
]
