TOPIC = {
    "id": "4.3",
    "domain": 4,
    "title": "Explain various activities associated with vulnerability management.",
    "short": "Vulnerability Management",
}

TERMS = [
    ("Vulnerability scan", "Automated tool that probes systems and compares software versions and configurations against a database of known flaws; identification, not exploitation"),
    ("Static analysis (SAST)", "Examining an application's source code for flaws without executing the program; done early in development"),
    ("Dynamic analysis (DAST)", "Testing an application while it is running by sending inputs (including fuzzing) and observing behavior; no source code needed"),
    ("Package monitoring", "Tracking third-party libraries and dependencies used by applications and alerting when new vulnerabilities are published for them"),
    ("Threat feed", "Continuously updated stream of threat and vulnerability intelligence consumed by security teams and tools; can be open source or proprietary/paid"),
    ("Open-source intelligence (OSINT)", "Threat and vulnerability information gathered from publicly available sources: blogs, vendor advisories, social media, government alerts"),
    ("Information-sharing organization", "Industry group (e.g., an ISAC) whose members exchange threat and vulnerability intelligence relevant to their sector"),
    ("Dark web", "Hidden networks/forums reached via anonymizing tools such as Tor; monitored for stolen credentials, breach data, and planned attacks"),
    ("Penetration testing", "Authorized simulated attack in which testers actively exploit weaknesses to prove real-world impact, going beyond scanning"),
    ("Responsible disclosure program", "Published process letting outside researchers privately report vulnerabilities so the vendor can fix them before public release"),
    ("Bug bounty program", "Responsible disclosure with rewards: the organization pays external researchers for valid reported vulnerabilities"),
    ("System/process audit", "Formal review of systems, configurations, and operating procedures against policy or standards to uncover gaps and weaknesses"),
    ("False positive", "Scanner reports a vulnerability that does not actually exist; wastes analyst time and must be weeded out during confirmation"),
    ("False negative", "Scanner fails to report a vulnerability that really is present; dangerous because it creates a false sense of security"),
    ("Common Vulnerability Scoring System (CVSS)", "Open industry standard that rates vulnerability severity on a 0-10 scale (higher = more severe) to support prioritization"),
    ("Common Vulnerabilities and Exposures (CVE)", "Public catalog assigning each disclosed vulnerability a unique identifier (e.g., CVE-2024-12345); identifies, does not score"),
    ("Vulnerability classification", "Grouping findings by type or category (OS flaw, misconfiguration, web app weakness) to route and manage remediation"),
    ("Exposure factor (EF)", "The percentage of an asset's value expected to be lost if a given vulnerability is exploited"),
    ("Environmental variables", "The system's real-world context — internet-facing vs. isolated, data sensitivity, existing controls — used to adjust vulnerability priority"),
    ("Risk tolerance", "The amount of risk an organization is willing to accept; drives how quickly (or whether) vulnerabilities must be remediated"),
    ("Patching", "Applying the vendor's software fix; the most direct and preferred remediation for a confirmed vulnerability"),
    ("Cybersecurity insurance", "Transfers the financial impact of exploitation to an insurer; covers losses but does not remove the underlying vulnerability"),
    ("Segmentation", "Isolating a vulnerable or unpatchable system on a restricted network (e.g., separate VLAN with strict firewall rules) to limit exposure"),
    ("Compensating control", "Alternative safeguard (e.g., a WAF or IPS rule) that reduces risk when the primary fix cannot be applied yet"),
    ("Exception/exemption", "Formal, documented management approval to leave a vulnerability unremediated, with accepted risk and a review date"),
    ("Rescanning", "Running the vulnerability scanner again after remediation to validate that the finding no longer appears; paired with audit and verification"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A security analyst schedules an automated tool to probe all servers weekly, comparing detected software versions and settings against a database of known flaws. Which identification method is this?",
        "choices": ["Penetration testing", "Vulnerability scan", "System/process audit", "Package monitoring"],
        "answer": 1,
        "explain": "A vulnerability scan is an automated check of systems against a database of known vulnerabilities — it identifies weaknesses but does not exploit them. Penetration testing actively exploits flaws, an audit is a formal review against policy, and package monitoring watches third-party libraries.",
    },
    {
        "type": "mc",
        "q": "During development, a tool analyzes an application's source code for insecure functions and coding flaws without ever executing the program. Which application security technique is this?",
        "choices": ["Dynamic analysis", "Fuzzing", "Static analysis", "Package monitoring"],
        "answer": 2,
        "explain": "Static analysis (SAST) examines source code without running it, catching flaws early in development. Dynamic analysis — including fuzzing — requires the application to be executing. Package monitoring tracks third-party dependencies, not your own code.",
    },
    {
        "type": "mc",
        "q": "A tester runs a web application in a lab and feeds it thousands of random and malformed inputs while it executes, watching for crashes and unexpected behavior. Which technique is being used?",
        "choices": ["Static analysis", "Dynamic analysis", "Package monitoring", "System/process audit"],
        "answer": 1,
        "explain": "Dynamic analysis tests the application while it is running; sending malformed/random input and watching for crashes is fuzzing, a classic dynamic technique. Static analysis inspects source code without execution, so it could not observe runtime crashes.",
    },
    {
        "type": "mc",
        "q": "A development team receives an automated alert that a third-party open-source library bundled with their application has a newly published critical vulnerability. Which identification method produced this alert?",
        "choices": ["Package monitoring", "Static analysis", "Penetration testing", "Dark web monitoring"],
        "answer": 0,
        "explain": "Package monitoring tracks the third-party libraries and dependencies an application uses and alerts when new vulnerabilities are disclosed for them. Static analysis inspects your own source code, and neither pen testing nor dark web monitoring watches dependency advisories.",
    },
    {
        "type": "mc",
        "q": "An analyst gathers vulnerability and threat information from public blogs, vendor advisories, social media, and freely available government alerts. This is BEST described as which type of threat intelligence?",
        "choices": ["Proprietary/third-party feed", "Open-source intelligence (OSINT)", "Information-sharing organization", "Dark web intelligence"],
        "answer": 1,
        "explain": "OSINT is intelligence collected from publicly available sources at no cost. Proprietary feeds are paid commercial products, information-sharing organizations are membership groups like ISACs, and dark web intelligence comes from hidden forums and marketplaces.",
    },
    {
        "type": "mc",
        "q": "A company pays a commercial vendor a subscription fee for curated, timely threat intelligence that is not available to the public. Which threat feed type is this?",
        "choices": ["Open-source intelligence", "Information-sharing organization", "Proprietary/third-party feed", "Responsible disclosure program"],
        "answer": 2,
        "explain": "A proprietary (third-party) threat feed is a paid commercial service offering curated intelligence, often with better timeliness and analysis than free sources. OSINT is free and public, and an ISAC is a sector-based sharing community rather than a commercial vendor.",
    },
    {
        "type": "mc",
        "q": "A regional bank joins FS-ISAC to exchange threat and vulnerability intelligence with other financial institutions in its sector. This is an example of which intelligence source?",
        "choices": ["Information-sharing organization", "Open-source intelligence", "Bug bounty program", "Proprietary threat feed"],
        "answer": 0,
        "explain": "Information Sharing and Analysis Centers (ISACs) are industry-specific groups whose members share threat intelligence relevant to their sector — FS-ISAC serves financial services. It is a membership community, not a commercial feed or a public OSINT source.",
    },
    {
        "type": "mc",
        "q": "A threat intelligence team monitors hidden forums and marketplaces accessible only through Tor for mentions of the company's stolen credentials and data. Which intelligence source is being used?",
        "choices": ["Open-source intelligence", "Information-sharing organization", "Dark web", "Package monitoring"],
        "answer": 2,
        "explain": "The dark web consists of hidden services reached through anonymizing networks such as Tor; monitoring its forums and marketplaces can reveal stolen credentials, breach data for sale, and attack planning. OSINT covers openly accessible sources, which these hidden forums are not.",
    },
    {
        "type": "mc",
        "q": "Management wants to know not just whether vulnerabilities exist, but whether an attacker could actually chain them together to reach sensitive data. Authorized testers attempt real exploitation. Which identification method is this?",
        "choices": ["Vulnerability scan", "Penetration testing", "System/process audit", "Responsible disclosure program"],
        "answer": 1,
        "explain": "Penetration testing goes beyond scanning: authorized testers actively exploit weaknesses to demonstrate real-world impact. A vulnerability scan only identifies potential flaws, an audit reviews processes against policy, and responsible disclosure relies on outside researchers reporting findings.",
    },
    {
        "type": "mc",
        "q": "An independent security researcher discovers a flaw in a company's public website and reports it privately through the company's published intake process, giving the company time to fix it before any public release. What is this an example of?",
        "choices": ["A responsible disclosure program", "Penetration testing", "A system/process audit", "A proprietary threat feed"],
        "answer": 0,
        "explain": "A responsible disclosure program gives outside researchers a sanctioned channel to privately report vulnerabilities so the organization can remediate before details go public. If the company also paid a reward for the report, it would specifically be a bug bounty program.",
    },
    {
        "type": "mc",
        "q": "An external assessor formally reviews the organization's account-provisioning procedures and server configurations against documented policy to find gaps. Which identification activity is this?",
        "choices": ["System/process audit", "Vulnerability scan", "Penetration testing", "Dynamic analysis"],
        "answer": 0,
        "explain": "A system/process audit is a formal review of systems, configurations, and operating procedures against a policy or standard. It finds procedural and configuration gaps that automated scans miss; scans and pen tests probe technical flaws, and dynamic analysis tests running applications.",
    },
    {
        "type": "mc",
        "q": "A scanner reports a critical vulnerability on a server, but the administrator verifies the patch was already applied and the flaw does not actually exist. How should this finding be classified?",
        "choices": ["False negative", "True positive", "False positive", "Exposure factor"],
        "answer": 2,
        "explain": "A false positive is a reported finding that turns out not to be real — the scanner flagged a flaw that is not present. A false negative is the opposite (a real flaw the scanner missed), and a true positive is a real, correctly reported finding. Confirmation weeds these out before prioritization.",
    },
    {
        "type": "mc",
        "q": "After a scan returns hundreds of confirmed findings, the practice of ranking them so the most dangerous vulnerabilities are remediated first is known as what?",
        "choices": ["Prioritization", "Classification", "Confirmation", "Reporting"],
        "answer": 0,
        "explain": "Prioritization ranks confirmed vulnerabilities — typically using CVSS scores, exploitability, asset criticality, and exposure — so limited resources fix the riskiest issues first. Classification groups findings by type, confirmation rules out false positives, and reporting communicates results.",
    },
    {
        "type": "mc",
        "q": "Which of the following provides a standardized numeric score from 0 to 10 that represents the severity of a vulnerability?",
        "choices": ["CVE", "CVSS", "OSINT", "Exposure factor"],
        "answer": 1,
        "explain": "The Common Vulnerability Scoring System (CVSS) rates severity on a 0-10 scale, with higher scores meaning more severe. CVE only assigns a unique identifier to each vulnerability — it does not score it. Exposure factor is the percentage of asset value lost if the flaw is exploited.",
    },
    {
        "type": "mc",
        "q": "Two servers have the same vulnerability with the same CVSS base score. One is internet-facing; the other sits on an isolated internal segment. The analyst raises the priority of the internet-facing server. Which analysis concept is being applied?",
        "choices": ["Environmental variables", "False positive confirmation", "Vulnerability classification", "Risk tolerance"],
        "answer": 0,
        "explain": "Environmental variables adjust priority based on the system's real-world context — internet exposure, data sensitivity, and existing controls. The base CVSS score alone ignores context; an internet-facing system is far more likely to be attacked, so its identical flaw is a higher priority.",
    },
    {
        "type": "mc",
        "q": "A hospital prioritizes a vulnerability in medical device software far higher than a retailer would prioritize the same flaw, because exploitation could endanger patient safety. Which analysis consideration does this illustrate?",
        "choices": ["Industry/organizational impact", "Exposure factor", "Package monitoring", "False negative"],
        "answer": 0,
        "explain": "Industry/organizational impact recognizes that the same vulnerability carries different consequences in different sectors — patient safety in healthcare, uptime in utilities, cardholder data in retail. Exposure factor is a percentage-of-loss metric, not a sector consideration.",
    },
    {
        "type": "mc",
        "q": "A company decides that low-severity findings on isolated lab machines may remain unpatched for up to 90 days because leadership accepts that level of risk. This decision reflects the organization's what?",
        "choices": ["Risk tolerance", "Exposure factor", "Vulnerability classification", "Compensating control"],
        "answer": 0,
        "explain": "Risk tolerance is how much risk an organization is willing to accept, and it directly drives remediation timelines and SLAs. A high tolerance permits longer patch windows for low-risk findings; a low tolerance demands rapid remediation. No control is being substituted, so it is not a compensating control.",
    },
    {
        "type": "mc",
        "q": "What is the MOST direct and preferred remediation for a confirmed software vulnerability?",
        "choices": ["Purchasing cybersecurity insurance", "Applying the vendor's patch", "Documenting an exemption", "Isolating the host with segmentation"],
        "answer": 1,
        "explain": "Patching actually removes the flaw, making it the preferred remediation whenever feasible. Insurance only transfers financial impact, an exemption formally accepts the risk without fixing it, and segmentation merely limits exposure — all fallbacks for when patching is not possible.",
    },
    {
        "type": "mc",
        "q": "A company cannot economically eliminate all residual risk from vulnerabilities in a legacy platform, so it buys a policy that covers breach-related financial losses. Which vulnerability response is this?",
        "choices": ["Compensating control", "Insurance", "Exception", "Segmentation"],
        "answer": 1,
        "explain": "Cybersecurity insurance transfers the financial impact of exploitation to an insurer. It does not reduce the likelihood of compromise or remove the vulnerability — it only softens the monetary loss, which is why it complements rather than replaces technical remediation.",
    },
    {
        "type": "mc",
        "q": "A production-line controller runs an operating system the vendor no longer patches. The security team moves it to an isolated VLAN with strict firewall rules limiting which hosts can reach it. Which remediation approach is this?",
        "choices": ["Segmentation", "Patching", "Insurance", "Rescanning"],
        "answer": 0,
        "explain": "Segmentation isolates a vulnerable or unpatchable system on a restricted network so attackers and malware cannot easily reach it. Patching is impossible here since the vendor no longer supplies fixes, and rescanning is a validation activity, not a remediation.",
    },
    {
        "type": "mc",
        "q": "A critical web application vulnerability cannot be patched until a maintenance window in three weeks. Meanwhile, the team deploys a WAF rule that blocks the known exploit. The WAF rule is an example of which response?",
        "choices": ["Compensating control", "Exemption", "Validation of remediation", "Patching"],
        "answer": 0,
        "explain": "A compensating control is an alternative safeguard that reduces risk when the primary fix (the patch) cannot be applied yet. The WAF rule blocks exploitation in the interim but does not remove the flaw, so the patch must still be applied at the maintenance window.",
    },
    {
        "type": "mc",
        "q": "A required patch would break a business-critical application, so management formally approves and documents leaving the vulnerability unremediated, accepts the risk, and sets a review date. What is this called?",
        "choices": ["An exception/exemption", "A false negative", "A compensating control", "Rescanning"],
        "answer": 0,
        "explain": "An exception (or exemption) is a formal, documented management decision to accept the risk of leaving a vulnerability unremediated, typically time-bound with periodic review. It differs from a compensating control, which adds an alternative safeguard rather than simply accepting the risk.",
    },
    {
        "type": "mc",
        "q": "An analyst groups scan findings into categories such as OS flaws, misconfigurations, and web application weaknesses so each responsible team can address its own findings. What is this activity called?",
        "choices": ["Vulnerability classification", "Prioritization", "Verification", "Reporting"],
        "answer": 0,
        "explain": "Vulnerability classification organizes findings by type or category, which helps route work to the right teams and reveals systemic patterns. Prioritization ranks findings by risk, verification confirms fixes worked, and reporting communicates status to stakeholders.",
    },
    {
        "type": "mc",
        "q": "After a quarterly vulnerability management cycle, the security team prepares a summary for leadership showing open findings, remediation trends, and SLA compliance. Which activity is this?",
        "choices": ["Reporting", "Rescanning", "Confirmation", "Classification"],
        "answer": 0,
        "explain": "Reporting communicates vulnerability status, metrics, and trends to stakeholders so leadership can track risk and resource decisions. Rescanning validates individual fixes, confirmation rules out false positives, and classification groups findings by type — none of them produce the leadership summary.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A higher CVSS base score indicates a more severe vulnerability.",
        "answer": True,
        "explain": "CVSS scores run from 0 to 10, and higher means more severe — a 9.8 is close to worst-case, while a 2.0 is low risk. Severity bands (low/medium/high/critical) map onto this scale and commonly drive remediation SLAs.",
    },
    {
        "type": "tf",
        "q": "True or False: A false negative occurs when a scanner reports a vulnerability that does not actually exist.",
        "answer": False,
        "explain": "That describes a false positive. A false negative is the reverse and more dangerous case: the scanner fails to report a vulnerability that really is present, leaving the organization blind to a genuine risk.",
    },
    {
        "type": "tf",
        "q": "True or False: Dynamic analysis examines an application's source code without executing the program.",
        "answer": False,
        "explain": "That is static analysis. Dynamic analysis requires the application to be running — the tester sends inputs (such as fuzzing payloads) and observes runtime behavior like crashes or data leakage. Static analysis works on the code itself and needs no execution.",
    },
    {
        "type": "tf",
        "q": "True or False: Cybersecurity insurance transfers the financial impact of a breach but does not remove the underlying vulnerability.",
        "answer": True,
        "explain": "Insurance is a risk-transfer response: the insurer absorbs monetary losses after an incident, but the flaw remains exploitable. That is why insurance supplements — and never replaces — remediation activities such as patching, segmentation, and compensating controls.",
    },
    {
        "type": "tf",
        "q": "True or False: Validating remediation can include rescanning the system, auditing the change, and manually verifying that the fix works as intended.",
        "answer": True,
        "explain": "The SY0-701 objective lists rescanning, audit, and verification as the validation-of-remediation activities. Rescanning confirms the scanner no longer flags the issue, an audit reviews that the change was made properly, and verification manually confirms the fix behaves as intended.",
    },
    {
        "type": "tf",
        "q": "True or False: Once management approves an exemption for a vulnerability, it no longer needs to be documented or periodically reviewed.",
        "answer": False,
        "explain": "Exceptions and exemptions must be formally documented, risk-accepted by management, and revisited on a review schedule. The vulnerability still exists, so the organization must track it — an undocumented, forgotten exemption becomes permanent hidden risk.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Each publicly disclosed vulnerability receives a unique identifier in the format ______-2024-12345. (type the abbreviation)",
        "answers": ["cve", "common vulnerabilities and exposures"],
        "explain": "CVE (Common Vulnerabilities and Exposures) is the public catalog that assigns each disclosed vulnerability a unique ID, letting tools, vendors, and analysts all refer to the same flaw unambiguously. CVE identifies; CVSS is what scores severity.",
    },
    {
        "type": "fill",
        "q": "The industry-standard system that rates vulnerability severity on a 0-10 scale is known by the abbreviation ______. (type your answer)",
        "answers": ["cvss", "common vulnerability scoring system"],
        "explain": "The Common Vulnerability Scoring System (CVSS) produces a 0-10 severity score from metrics like attack vector, complexity, privileges required, and impact. Organizations use CVSS bands (critical/high/medium/low) to set remediation priorities and SLAs.",
    },
    {
        "type": "fill",
        "q": "A program that pays external security researchers rewards for responsibly reporting vulnerabilities is called a bug ______ program. (type your answer)",
        "answers": ["bounty", "bug bounty"],
        "explain": "A bug bounty program is a responsible disclosure program with financial incentives: researchers who privately report valid flaws receive payment. It crowdsources vulnerability identification from outside talent while keeping disclosure controlled.",
    },
    {
        "type": "fill",
        "q": "The percentage of an asset's value expected to be lost if a vulnerability is exploited is called the ______ factor. (type your answer)",
        "answers": ["exposure", "exposure factor", "ef"],
        "explain": "Exposure factor (EF) expresses expected loss as a percentage of the asset's value — an EF of 50% on a $100,000 asset means a $50,000 single loss expectancy. It feeds quantitative risk analysis and helps prioritize vulnerabilities on high-value assets.",
    },
    {
        "type": "fill",
        "q": "Running the vulnerability scanner again after applying a patch to confirm the finding no longer appears is called ______. (type your answer)",
        "answers": ["rescanning", "rescan", "a rescan", "re-scanning", "re-scan"],
        "explain": "Rescanning is the primary validation-of-remediation activity: repeat the original scan and confirm the finding is gone. It is complemented by auditing the change and manually verifying the fix works — remediation is not complete until it is validated.",
    },
    {
        "type": "fill",
        "q": "A continuously updated stream of threat and vulnerability intelligence consumed by security teams and tools is called a threat ______. (type your answer)",
        "answers": ["feed", "threat feed", "intelligence feed"],
        "explain": "A threat feed delivers ongoing intelligence about new vulnerabilities, indicators, and attacker activity. Feeds can come from open-source intelligence (OSINT), paid proprietary/third-party vendors, information-sharing organizations like ISACs, or dark web monitoring.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each vulnerability identification method to its description.",
        "pairs": [
            ["Vulnerability scan", "Automated check of systems against a database of known flaws"],
            ["Penetration testing", "Authorized testers actively exploit weaknesses to prove impact"],
            ["Bug bounty program", "External researchers are paid rewards for reported flaws"],
            ["Package monitoring", "Tracks third-party libraries for newly published vulnerabilities"],
            ["System/process audit", "Formal review of configurations and procedures against policy"],
        ],
        "explain": "Scans identify known flaws automatically; pen tests exploit them to show real impact; bug bounties crowdsource discovery to paid outside researchers; package monitoring watches application dependencies; audits compare systems and processes to documented policy.",
    },
    {
        "type": "match",
        "q": "Match each vulnerability analysis term to its meaning.",
        "pairs": [
            ["False positive", "Scanner reports a flaw that does not actually exist"],
            ["False negative", "Scanner misses a flaw that really is present"],
            ["CVSS", "Standard 0-10 severity scoring system"],
            ["CVE", "Public catalog of unique identifiers for known vulnerabilities"],
            ["Exposure factor", "Percentage of asset value lost if the flaw is exploited"],
        ],
        "explain": "Confirmation separates false positives (reported but not real) from false negatives (real but missed). CVSS scores severity 0-10 while CVE only names the vulnerability, and exposure factor quantifies expected loss as a percentage of asset value.",
    },
    {
        "type": "match",
        "q": "Match each vulnerability response or follow-up activity to its description.",
        "pairs": [
            ["Patching", "Apply the vendor's fix to remove the flaw"],
            ["Segmentation", "Isolate an unpatchable system on a restricted network"],
            ["Compensating control", "Alternative safeguard when the primary fix is not yet feasible"],
            ["Insurance", "Transfer the financial impact of exploitation to a third party"],
            ["Reporting", "Communicate vulnerability status and metrics to stakeholders"],
        ],
        "explain": "Patching eliminates the flaw; segmentation contains what cannot be patched; compensating controls (like a WAF rule) reduce risk until the real fix lands; insurance transfers financial risk without fixing anything; reporting keeps stakeholders informed of program status.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the vulnerability management activities in their typical lifecycle order.",
        "items": [
            "Identify vulnerabilities (scans, threat feeds, pen tests)",
            "Confirm findings and rule out false positives",
            "Prioritize using CVSS scores and environmental factors",
            "Remediate (patch, segment, or apply compensating controls)",
            "Validate remediation by rescanning and verification",
            "Report results and metrics to stakeholders",
        ],
        "explain": "Vulnerability management is a cycle: identify weaknesses, confirm they are real, prioritize by severity and context, remediate, validate that the fix actually worked, then report status to stakeholders — and the cycle repeats continuously.",
    },
]
