TOPIC = {
    "id": "4.4",
    "domain": 4,
    "title": "Explain security alerting and monitoring concepts and tools.",
    "short": "Alerting & Monitoring",
}

TERMS = [
    ("Systems monitoring", "Watching individual hosts at the OS level: CPU/memory/disk utilization, service status, authentication logs, and process activity"),
    ("Application monitoring", "Watching software behavior: application logs, error rates, availability, response times, and failed transactions"),
    ("Infrastructure monitoring", "Watching the underlying plumbing: routers, switches, firewalls, links/bandwidth, cloud platforms, and facility environment"),
    ("Log aggregation", "Collecting logs from many disparate sources into one central location and normalizing formats so events can be searched and correlated"),
    ("Alerting", "Automated notification that a rule, threshold, or correlation match fired and something needs analyst attention"),
    ("Scanning", "Scheduled, recurring, proactive probing of the environment for vulnerabilities, configuration drift, and unknown devices"),
    ("Reporting", "Turning monitoring data into communication: dashboards, trends, posture summaries, and compliance evidence for each audience"),
    ("Archiving", "Long-term retention of logs beyond immediate use, for regulatory compliance and later forensic investigation"),
    ("Quarantine", "Isolating a suspicious file or host so it cannot execute or spread — containment that preserves evidence for analysis"),
    ("Alert tuning", "Adjusting alert rules, thresholds, and exceptions to reduce false positives while avoiding new false negatives"),
    ("False positive (alerting)", "An alert that fires on activity that was not actually malicious; the driver of alert fatigue"),
    ("False negative (alerting)", "Malicious activity that generates no alert — the dangerous, silent failure mode"),
    ("Alert fatigue", "Analysts desensitized by floods of noisy alerts start ignoring the console, so real attacks slip through"),
    ("Security Content Automation Protocol (SCAP)", "NIST suite of open standardized formats (OVAL, XCCDF, CPE, CCE, CVE, CVSS) letting different vendors' tools automate and share configuration/vulnerability checks"),
    ("Benchmark", "A published secure configuration baseline for a specific product (e.g., CIS Benchmarks) that compliance scans measure systems against"),
    ("Agent-based monitoring", "Software installed on each host collects rich, continuous data and keeps working off the corporate network — at the cost of deployment and maintenance overhead"),
    ("Agentless monitoring", "Collecting data remotely via existing interfaces (SSH, WMI, SNMP, APIs) with nothing installed on targets; shallower data, only when reachable/polled"),
    ("Security information and event management (SIEM)", "Central platform providing log aggregation, normalization, correlation, real-time alerting, dashboards, and retention"),
    ("Correlation", "SIEM analysis that links events from multiple sources into one recognized attack pattern no single log reveals"),
    ("Antivirus", "Host software detecting malware via signatures (known threats) and heuristics/behavior (unknown variants); quarantines what it finds"),
    ("Data loss prevention (DLP)", "Tool that recognizes sensitive data and alerts on or blocks it leaving the organization — via email, uploads, USB — in use, in motion, and at rest"),
    ("SNMP trap", "Unsolicited, asynchronous notification a managed device sends to the monitoring station (UDP 162) the moment a significant event occurs"),
    ("SNMPv3", "The SNMP version that adds authentication and encryption; v1/v2c rely on plaintext community strings"),
    ("NetFlow", "Cisco-originated collection of traffic-flow metadata — IPs, ports, protocol, timestamps, byte counts — without capturing packet payloads"),
    ("Vulnerability scanner", "Tool that probes systems on a schedule for known flaws and misconfigurations, reporting findings with CVE references and CVSS severity"),
    ("Credentialed scan", "Vulnerability scan that logs in to targets for a deeper, more accurate inside view with fewer false positives"),
    ("Syslog", "Traditional protocol for shipping log messages to a central collector; UDP port 514 (TLS variant on TCP 6514)"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A monitoring dashboard tracks CPU utilization, disk space, running services, and failed login attempts on each server. Which computing resource category is being monitored?",
        "choices": ["Applications", "Systems", "Infrastructure", "Data loss prevention"],
        "answer": 1,
        "explain": "Host-level metrics — CPU, memory, disk, services, and authentication logs on individual servers — are systems monitoring. Application monitoring watches software behavior like error rates, and infrastructure monitoring watches network devices and links.",
    },
    {
        "type": "mc",
        "q": "A team watches a customer-facing web portal for spikes in error rates, slow response times, and failed transactions. Which monitoring category is this?",
        "choices": ["Systems", "Infrastructure", "Applications", "Archiving"],
        "answer": 2,
        "explain": "Error rates, response times, availability, and transaction behavior describe the software layer — application monitoring. A spike in application errors can indicate injection attempts or abuse that host CPU/disk metrics would never show.",
    },
    {
        "type": "mc",
        "q": "Administrators receive notifications about interface utilization on core switches, firewall status, and VPN concentrator health. Which computing resource category is being monitored?",
        "choices": ["Infrastructure", "Applications", "Systems", "Endpoints"],
        "answer": 0,
        "explain": "Routers, switches, firewalls, links/bandwidth, and supporting platforms are infrastructure. Systems monitoring covers individual hosts at the OS level, and application monitoring covers software behavior.",
    },
    {
        "type": "mc",
        "q": "A security team configures every server, firewall, and application to forward its logs to one central platform where they are normalized into a common format. Which activity is this?",
        "choices": ["Alert tuning", "Archiving", "Scanning", "Log aggregation"],
        "answer": 3,
        "explain": "Log aggregation centralizes logs from disparate sources and normalizes their differing formats so events can be searched and correlated in one place. Archiving is long-term retention; tuning adjusts alert rules; scanning proactively probes for weaknesses.",
    },
    {
        "type": "mc",
        "q": "During an investigation, analysts cannot reliably sequence events across servers because each device's clock shows a different time. Which service should have been used to prevent this?",
        "choices": ["SNMP", "NTP", "NetFlow", "SCAP"],
        "answer": 1,
        "explain": "NTP (Network Time Protocol) synchronizes clocks across devices so log timestamps line up — a prerequisite for correlating events from multiple sources. SNMP monitors devices, NetFlow records traffic metadata, and SCAP standardizes compliance checking.",
    },
    {
        "type": "mc",
        "q": "When a correlation rule matches, the SIEM automatically notifies the on-call analyst by console message and ticket. Which monitoring activity does this describe?",
        "choices": ["Alerting", "Reporting", "Log aggregation", "Quarantine"],
        "answer": 0,
        "explain": "Alerting is the automated notification that something needing attention occurred — a rule, threshold, or correlation match fired. Reporting is the human-oriented summary/dashboard activity, and quarantine is an isolation response after an alert.",
    },
    {
        "type": "mc",
        "q": "Every week, an automated tool probes all hosts for missing patches and checks configurations against the approved baseline, flagging drift. Which monitoring activity is this?",
        "choices": ["Alerting", "Archiving", "Scanning", "Quarantine"],
        "answer": 2,
        "explain": "Scanning is the scheduled, recurring, proactive examination of the environment — vulnerability scans, compliance/configuration scans, and discovery scans. Rather than waiting for an event, the organization actively probes for weaknesses and drift.",
    },
    {
        "type": "mc",
        "q": "Each month the security team produces a summary of security posture, open findings, and trends for leadership, plus compliance evidence for auditors. Which activity is this?",
        "choices": ["Reporting", "Alerting", "Log aggregation", "Alert tuning"],
        "answer": 0,
        "explain": "Reporting turns monitoring data into communication tailored to each audience — operational detail for analysts, trends and risk for management, evidence for auditors. Alerting is the real-time automated notification, not the periodic summary.",
    },
    {
        "type": "mc",
        "q": "A regulation requires the company to retain security logs for at least 12 months. Older logs are compressed, moved to low-cost storage, and protected from tampering. Which activity is this?",
        "choices": ["Log aggregation", "Archiving", "Reporting", "Scanning"],
        "answer": 1,
        "explain": "Archiving is long-term retention of logs beyond immediate operational use — driven by compliance mandates and the need for forensic data when breaches are discovered months later. Aggregation is the real-time centralizing of logs, not their long-term storage.",
    },
    {
        "type": "mc",
        "q": "An EDR tool detects malware on a laptop and immediately isolates the machine from the network while preserving a management channel for investigation. Which response action is this?",
        "choices": ["Alert tuning", "Archiving", "Quarantine", "Reporting"],
        "answer": 2,
        "explain": "Quarantine isolates a suspicious host (or file) so it cannot spread or reach command-and-control while it is investigated — containment that preserves evidence. Alert tuning adjusts detection rules; it does not isolate anything.",
    },
    {
        "type": "mc",
        "q": "Analysts are overwhelmed by alerts that keep firing on the vulnerability scanner's routine activity. An engineer adds an exception for the scanner's IP and raises a noisy threshold. Which activity is this?",
        "choices": ["Alert tuning", "Quarantine", "Log aggregation", "Archiving"],
        "answer": 0,
        "explain": "Alert tuning adjusts rules, thresholds, and exceptions so alerts stay accurate and actionable — cutting false positives (like alerts on the scanner's known-benign probes) without suppressing detection of real attacks.",
    },
    {
        "type": "mc",
        "q": "A SIEM alert fires on activity that an analyst confirms was completely benign. What is this alert an example of?",
        "choices": ["A false negative", "A true positive", "A false positive", "A trap"],
        "answer": 2,
        "explain": "A false positive is an alert on activity that was not actually malicious. Enough of them cause alert fatigue. A false negative is the reverse — real malicious activity that generated no alert — and is the more dangerous failure.",
    },
    {
        "type": "mc",
        "q": "After aggressive alert suppression to quiet the console, a real intrusion proceeds without any alert firing. What has the over-tuning created?",
        "choices": ["A false positive", "A false negative", "Alert fatigue", "A benchmark deviation"],
        "answer": 1,
        "explain": "Suppressing too much converts noise reduction into missed attacks — false negatives, where malicious activity generates no alert. Tuning must improve signal quality (fewer bogus alerts AND no missed real ones), not just reduce volume.",
    },
    {
        "type": "mc",
        "q": "An organization wants vulnerability and configuration-compliance checks automated so that tools from different vendors can consume the same checklist content and report results in the same standardized formats. Which NIST protocol suite enables this?",
        "choices": ["SNMP", "SCAP", "NetFlow", "Syslog"],
        "answer": 1,
        "explain": "SCAP (Security Content Automation Protocol) is NIST's suite of open standards — including OVAL, XCCDF, CPE, CCE, CVE, and CVSS — that lets different vendors' tools automate configuration/vulnerability checking and share results in a common language.",
    },
    {
        "type": "mc",
        "q": "Within SCAP, which component standard expresses security checklists and benchmarks in a machine-readable format?",
        "choices": ["XCCDF", "CPE", "CVE", "CVSS"],
        "answer": 0,
        "explain": "XCCDF (Extensible Configuration Checklist Description Format) encodes checklists/benchmarks machine-readably. OVAL defines the system-state tests, CPE names platforms, CVE identifies vulnerabilities, and CVSS scores their severity.",
    },
    {
        "type": "mc",
        "q": "An administrator downloads the CIS-published hardened configuration guide for Windows Server and uses compliance scans to compare every server against it. What is this guide called?",
        "choices": ["A benchmark", "A NetFlow record", "An SNMP MIB", "A quarantine policy"],
        "answer": 0,
        "explain": "A benchmark is a published secure configuration baseline for a specific product — CIS Benchmarks are the best-known example. In monitoring, the benchmark is the measuring stick that compliance scans check systems against to detect drift.",
    },
    {
        "type": "mc",
        "q": "A company must continuously monitor traveling employees' laptops, including when they are away from the corporate network. Which monitoring approach fits BEST?",
        "choices": ["Agentless monitoring", "SNMP polling", "Agent-based monitoring", "NetFlow collection"],
        "answer": 2,
        "explain": "An installed agent collects rich host data continuously and keeps working (or caches and forwards) when the laptop is off the corporate network. Agentless monitoring and SNMP polling require the target to be reachable over the network to collect anything.",
    },
    {
        "type": "mc",
        "q": "A security team must gather configuration data from hundreds of network appliances that cannot run installed software. The tool queries them remotely using SSH and SNMP credentials. Which approach is this?",
        "choices": ["Agent-based monitoring", "Agentless monitoring", "Quarantine", "Static analysis"],
        "answer": 1,
        "explain": "Agentless monitoring collects data remotely via existing interfaces (SSH, WMI, SNMP, APIs) with nothing installed on the targets — ideal for appliances that can't run agents. The trade-off is shallower data, collected only when the device is reachable/polled.",
    },
    {
        "type": "mc",
        "q": "Which is an advantage of agentless monitoring over agent-based monitoring?",
        "choices": [
            "It provides richer, continuous host-interior data",
            "It keeps collecting when the device leaves the network",
            "There is no software to deploy, update, or maintain on each target",
            "It consumes more CPU and memory on each host",
        ],
        "answer": 2,
        "explain": "Agentless monitoring's advantage is zero per-host software footprint — nothing to deploy or maintain. Richer continuous data and off-network collection are agent-based advantages, and higher per-host resource consumption is a drawback, not an advantage.",
    },
    {
        "type": "mc",
        "q": "Which platform aggregates and normalizes logs from across the enterprise, correlates events from multiple sources, raises real-time alerts, and provides dashboards and retention?",
        "choices": ["DLP", "SIEM", "Antivirus", "Vulnerability scanner"],
        "answer": 1,
        "explain": "That is the SIEM (security information and event management) — the central platform combining log aggregation, correlation, alerting, dashboards, reporting, and retention. DLP watches sensitive data movement; antivirus and scanners are individual detection tools.",
    },
    {
        "type": "mc",
        "q": "A SIEM links failed logins on many different systems, a subsequent successful login, and a large outbound file transfer into a single high-priority incident. Which SIEM capability does this demonstrate?",
        "choices": ["Archiving", "Normalization", "Correlation", "Quarantine"],
        "answer": 2,
        "explain": "Correlation applies rules and analytics across events from multiple sources to recognize an attack pattern that no single log reveals — the SIEM's signature capability. Normalization just converts differing log formats into a common schema first.",
    },
    {
        "type": "mc",
        "q": "Why can purely signature-based antivirus fail to stop a brand-new strain of malware?",
        "choices": [
            "Signature matching only works on encrypted files",
            "No definition exists yet for malware that has never been seen",
            "Antivirus cannot quarantine files, only delete them",
            "Signatures only detect network attacks, not files",
        ],
        "answer": 1,
        "explain": "Signature-based detection matches against a database of known-malware definitions, so zero-day/unknown malware has no signature to match until vendors publish one. Heuristic/behavior-based detection exists precisely to catch unknown variants.",
    },
    {
        "type": "mc",
        "q": "An employee tries to email a spreadsheet of customer credit card numbers to a personal account, and the message is automatically blocked based on its content. Which tool did this?",
        "choices": ["Antivirus", "NetFlow", "SNMP", "DLP"],
        "answer": 3,
        "explain": "Data loss prevention (DLP) recognizes sensitive content — card number patterns, SSNs, keywords, classification labels — and alerts on or blocks it leaving the organization via email, uploads, or removable media. Antivirus detects malware, not outbound sensitive data.",
    },
    {
        "type": "mc",
        "q": "A router's interface fails and the router immediately sends an unsolicited notification to the network monitoring station without being polled. What is this notification called?",
        "choices": ["A syslog archive", "An SNMP trap", "A NetFlow export", "A benchmark alert"],
        "answer": 1,
        "explain": "An SNMP trap is a device-initiated, asynchronous notification sent to the manager (received on UDP 162) the moment a significant event occurs — no waiting for the next polling cycle. Regular SNMP polling is manager-initiated on UDP 161.",
    },
    {
        "type": "mc",
        "q": "On which port does a network management station receive SNMP traps?",
        "choices": ["UDP 161", "UDP 162", "UDP 514", "TCP 6514"],
        "answer": 1,
        "explain": "Traps are received on UDP 162. Manager-to-agent polling queries use UDP 161. UDP 514 is traditional syslog, and TCP 6514 is syslog over TLS.",
    },
    {
        "type": "mc",
        "q": "A network team wants device monitoring traffic authenticated and encrypted instead of protected only by plaintext community strings. Which version should they deploy?",
        "choices": ["SNMPv1", "SNMPv2c", "SNMPv3", "NetFlow v9"],
        "answer": 2,
        "explain": "SNMPv3 adds authentication and encryption. SNMPv1 and v2c authenticate only with plaintext community strings, which can be sniffed. NetFlow v9 is a flow-export format, not an SNMP version.",
    },
    {
        "type": "mc",
        "q": "Investigators need to know which internal hosts communicated with a suspicious external IP over the past month — when, how often, and how much data — but full packet captures were never taken. Which data source can answer this?",
        "choices": ["NetFlow records", "Antivirus quarantine logs", "SCAP results", "CIS Benchmarks"],
        "answer": 0,
        "explain": "NetFlow records traffic-flow metadata — source/destination IPs and ports, protocol, timestamps, and byte counts — and its compactness makes long retention practical. It shows who talked to whom and how much, though not the packet contents.",
    },
    {
        "type": "mc",
        "q": "What is the key limitation of NetFlow data compared with full packet capture?",
        "choices": [
            "It cannot record source and destination IP addresses",
            "It does not contain the packet payloads/contents",
            "It only works on wireless networks",
            "It must be collected by an installed host agent",
        ],
        "answer": 1,
        "explain": "NetFlow is metadata only: IPs, ports, protocol, timestamps, and byte/packet counts — never the payload. It can prove that and how much communication occurred, but not exactly what data was transferred; full packet capture is needed for contents.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST describes why a credentialed vulnerability scan is preferred over a non-credentialed scan for internal assessment?",
        "choices": [
            "It shows exactly what an outside attacker with no access would see",
            "It logs in to targets, producing deeper, more accurate results with fewer false positives",
            "It requires no accounts or permissions to run",
            "It captures full packet payloads from the network",
        ],
        "answer": 1,
        "explain": "A credentialed scan authenticates to targets and inspects them from inside — seeing installed patches, configurations, and software directly, which yields deeper findings and fewer false positives. The unauthenticated attacker's view is the non-credentialed scan's purpose.",
    },
    {
        "type": "mc",
        "q": "A security platform automatically executes a playbook when a phishing alert fires: it enriches the alert, quarantines the affected host, and opens a ticket. Which technology extends the SIEM this way?",
        "choices": ["SOAR", "SCAP", "DLP", "NetFlow"],
        "answer": 0,
        "explain": "SOAR (security orchestration, automation, and response) automates response playbooks on top of SIEM detection — the SIEM detects, SOAR reacts. SCAP standardizes compliance content, DLP guards data movement, and NetFlow records traffic metadata.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: An SNMP trap is initiated by the managed device itself, not requested by the management station.",
        "answer": True,
        "explain": "A trap is an unsolicited, asynchronous, device-initiated notification sent to the manager on UDP 162 when a significant event occurs. Ordinary SNMP monitoring is the reverse direction: the manager polls agents with queries to UDP 161.",
    },
    {
        "type": "tf",
        "q": "True or False: NetFlow captures the full contents of every packet so analysts can read the data that was transferred.",
        "answer": False,
        "explain": "NetFlow records flow metadata only — IPs, ports, protocol, timestamps, and byte/packet counts. It reveals who communicated with whom and how much, but never the payload; reading transferred contents requires full packet capture.",
    },
    {
        "type": "tf",
        "q": "True or False: Agentless monitoring continues collecting data from a laptop even after it leaves the corporate network.",
        "answer": False,
        "explain": "Agentless monitoring queries targets remotely, so it collects nothing when the device is unreachable. Continuous off-network collection is the strength of agent-based monitoring — the installed agent keeps gathering data and forwards it when connected.",
    },
    {
        "type": "tf",
        "q": "True or False: The goal of alert tuning is to reduce false positives without introducing false negatives.",
        "answer": True,
        "explain": "Tuning adjusts rules, thresholds, and exceptions to improve signal quality — fewer bogus alerts and no missed real attacks. Over-suppressing alerts just to quiet the console trades false positives for the more dangerous false negatives.",
    },
    {
        "type": "tf",
        "q": "True or False: Archiving logs serves only short-term troubleshooting and has no role in compliance or forensics.",
        "answer": False,
        "explain": "Archiving is exactly the opposite: long-term retention driven by regulatory mandates (often a year or more) and by forensics — breaches are frequently discovered months after compromise, and only archived logs can support that investigation.",
    },
    {
        "type": "tf",
        "q": "True or False: When antivirus quarantines a file, the file is moved to an isolated area where it cannot execute, rather than being immediately destroyed.",
        "answer": True,
        "explain": "Quarantine places the detected file in a restricted holding area where it cannot run — containing the threat while preserving it for analysis or restoration if the detection proves to be a false positive. Deletion would destroy that evidence.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "SCAP stands for Security Content ______ Protocol. (type the missing word)",
        "answers": ["automation"],
        "explain": "SCAP is the Security Content Automation Protocol — NIST's suite of open standards (OVAL, XCCDF, CPE, CCE, CVE, CVSS) that lets tools from different vendors automate configuration and vulnerability checking with shared, standardized content.",
    },
    {
        "type": "fill",
        "q": "The central platform that aggregates logs, correlates events, and raises real-time security alerts is known by the four-letter abbreviation ______. (type your answer)",
        "answers": ["siem", "security information and event management"],
        "explain": "The SIEM (security information and event management) system combines log aggregation and normalization, correlation across sources, real-time alerting, dashboards, reporting, and retention into one central monitoring platform.",
    },
    {
        "type": "fill",
        "q": "SNMP traps are sent by managed devices to the management station on UDP port ______. (type the number)",
        "answers": ["162"],
        "explain": "Traps arrive at the manager on UDP 162; the manager's routine polling queries go to agents on UDP 161. Remember: 161 = manager asks, 162 = device tells.",
    },
    {
        "type": "fill",
        "q": "Isolating an infected host or suspicious file so it cannot spread or execute while being investigated is called ______. (type your answer)",
        "answers": ["quarantine", "quarantining", "quarantined"],
        "explain": "Quarantine is the containment element of alert response: antivirus moves detected files to an isolated holding area, and EDR/NAC can isolate whole hosts from the network — stopping spread while preserving evidence.",
    },
    {
        "type": "fill",
        "q": "The Cisco-originated technology that records metadata about network traffic flows — IPs, ports, protocol, and byte counts — without capturing payloads is called ______. (type your answer)",
        "answers": ["netflow", "net flow"],
        "explain": "NetFlow summarizes each network conversation as a compact flow record, making it ideal for spotting exfiltration, beaconing, and traffic anomalies and for retaining months of communication history cheaply. IPFIX is the IETF standard derived from NetFlow v9.",
    },
    {
        "type": "fill",
        "q": "The tool category that detects and blocks sensitive data — like SSNs or card numbers — from leaving the organization is abbreviated ______. (type your answer)",
        "answers": ["dlp", "data loss prevention"],
        "explain": "DLP (data loss prevention) identifies sensitive content by patterns, keywords, fingerprints, and classification labels, then alerts on or blocks exfiltration attempts — covering data in use (endpoint), in motion (network), and at rest (storage).",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each monitoring tool to its description.",
        "pairs": [
            ["SIEM", "Central platform that aggregates, correlates, and alerts on events"],
            ["DLP", "Blocks sensitive data from leaving via email, uploads, or USB"],
            ["NetFlow", "Records traffic-flow metadata without capturing payloads"],
            ["Vulnerability scanner", "Probes systems for known flaws and misconfigurations"],
            ["Antivirus", "Detects malware via signatures and heuristics, then quarantines it"],
        ],
        "explain": "The SIEM is the central aggregation/correlation/alerting platform; DLP guards sensitive data movement; NetFlow summarizes who-talked-to-whom traffic metadata; vulnerability scanners find known weaknesses; antivirus detects and quarantines malware on hosts.",
    },
    {
        "type": "match",
        "q": "Match each monitoring activity to its description.",
        "pairs": [
            ["Log aggregation", "Centralize and normalize logs from many sources"],
            ["Alerting", "Automated notification when a rule or threshold fires"],
            ["Scanning", "Scheduled proactive probing for weaknesses and drift"],
            ["Reporting", "Communicate posture, trends, and compliance to audiences"],
            ["Archiving", "Retain logs long-term for compliance and forensics"],
        ],
        "explain": "Aggregation centralizes the raw material; alerting notifies in real time; scanning probes proactively on a schedule; reporting communicates results to people; archiving preserves logs long-term for regulators and future investigations.",
    },
    {
        "type": "match",
        "q": "Match each SCAP component standard to its role.",
        "pairs": [
            ["OVAL", "Language defining tests of a system's state"],
            ["XCCDF", "Machine-readable format for checklists and benchmarks"],
            ["CPE", "Standard naming scheme for platforms and products"],
            ["CVE", "Unique identifiers for publicly known vulnerabilities"],
            ["CVSS", "Standard 0-10 vulnerability severity scoring"],
        ],
        "explain": "OVAL (Open Vulnerability and Assessment Language) defines how to test system state; XCCDF (Extensible Configuration Checklist Description Format) encodes benchmarks; CPE names platforms; CVE identifies vulnerabilities; CVSS scores their severity 0-10.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the alert lifecycle steps in order, from raw event to improved detection.",
        "items": [
            "Devices generate events and forward logs to the central platform",
            "The SIEM correlates events and raises an alert",
            "An analyst triages and validates the alert (true or false positive)",
            "The affected host or file is quarantined and remediated",
            "Remediation is validated and the incident is documented",
            "Alert rules are tuned to reduce future false positives",
        ],
        "explain": "Monitoring flows from raw events through aggregation and correlation to an alert; analysts validate it, contain and remediate real threats (quarantine), verify the fix, then feed lessons back into detection by tuning the rules — a continuous improvement loop.",
    },
]
