TOPIC = {
    "id": "4.5",
    "domain": 4,
    "title": "Given a scenario, modify enterprise capabilities to enhance security.",
    "short": "Enterprise Security Capabilities",
}

TERMS = [
    ("Firewall rules", "Ordered permit/deny statements matching source, destination, protocol, and port; processed top-down, first match wins, ending in implicit deny"),
    ("Implicit deny", "The unwritten rule at the end of every firewall ruleset/ACL: any traffic not explicitly permitted is dropped — default-deny policy"),
    ("Access control list (ACL)", "Sequential list of permit/deny statements filtering packets by IP, protocol, and port; applied to an interface in a direction, first match wins"),
    ("Screened subnet", "Isolated segment (formerly DMZ) between the internet and the LAN hosting public-facing servers; compromise there does not expose the internal network"),
    ("Intrusion detection system (IDS)", "Passive/out-of-band monitor (fed by TAP or SPAN port) that alerts on malicious traffic but cannot block it"),
    ("Intrusion prevention system (IPS)", "Inline device in the traffic path that can actively block malicious traffic in real time; false positives can block legitimate traffic"),
    ("Signature-based detection", "Matching traffic against a database of known attack patterns; accurate for known threats but cannot detect zero-day attacks"),
    ("Trend/anomaly-based detection", "Baselines normal behavior and alerts on deviations; can catch novel/zero-day attacks but produces more false positives and needs a training period"),
    ("Agent-based web filtering", "Filter software installed on each device so policy follows the user everywhere, including off the corporate network — the answer for remote/roaming users"),
    ("Centralized proxy", "A proxy server all web traffic routes through for inspection, filtering, caching, and logging — a single on-network choke point for web policy"),
    ("URL scanning", "Checking the requested URL against databases/lists of known-malicious or prohibited sites before allowing the connection"),
    ("Content categorization", "Grouping websites into categories (gambling, adult, social media, malware) so administrators can allow or block whole categories at once"),
    ("Block rules", "The web filter's explicit deny entries — specific URLs/domains, categories, or file types — the enforcement layer of the filter"),
    ("Reputation (web filter)", "Risk/trust score assigned to a site from its history, hosting, and behavior; low-reputation sites are blocked even if not on any known-bad list"),
    ("Group Policy", "Windows/Active Directory mechanism enforcing configuration centrally via GPOs linked to sites, domains, or OUs — password policy, lockout, service restrictions"),
    ("SELinux", "Security-Enhanced Linux: kernel-level mandatory access control using security labels; confines even root processes to policy; modes are enforcing, permissive, disabled"),
    ("Protocol selection", "Choosing the secure protocol over the legacy cleartext one: Telnet→SSH, HTTP→HTTPS, FTP→SFTP/FTPS, SNMPv1/v2c→SNMPv3, LDAP→LDAPS, RTP→SRTP"),
    ("Port selection", "Choosing the correct well-known port for the secure protocol: SSH 22, HTTPS 443, LDAPS 636, POP3S 995, IMAPS 993, submission 587 (STARTTLS)/465 (implicit TLS)"),
    ("Transport method", "How in-transit encryption is provided: TLS for application traffic, IPsec (tunnel mode = whole packet, transport mode = payload only) for VPNs, WPA3 for wireless"),
    ("DNS filtering", "Blocking malicious/prohibited sites at the name-resolution step — the resolver refuses to return the real address, stopping phishing clicks and malware C2 callbacks"),
    ("Sender Policy Framework (SPF)", "DNS TXT record listing the mail servers/IPs authorized to send email for a domain; receivers check the connecting sender's IP against it"),
    ("DomainKeys Identified Mail (DKIM)", "Sending server signs outgoing mail with the domain's private key; receivers verify using the public key published in DNS — proves origin and integrity"),
    ("DMARC", "Domain-based Message Authentication, Reporting, and Conformance: builds on SPF/DKIM, requires From-domain alignment, sets failure policy (none/quarantine/reject), adds reporting"),
    ("Email security gateway", "Appliance/cloud service all mail flows through: filters spam/phishing, scans attachments for malware, enforces SPF/DKIM/DMARC, applies outbound DLP"),
    ("File integrity monitoring (FIM)", "Detects unauthorized changes to critical files by comparing current cryptographic hashes/attributes against a known-good baseline; detective, not preventive"),
    ("Data loss prevention (DLP)", "Identifies sensitive data (card numbers, SSNs, PHI) and blocks or alerts when it moves contrary to policy — email, web upload, USB, cloud; anti-exfiltration"),
    ("Network access control (NAC)", "Decides whether a device may join the network based on identity and health/posture; non-compliant devices are denied or quarantined for remediation"),
    ("IEEE 802.1X", "Port-based network authentication underpinning NAC: supplicant (device) authenticates through the authenticator (switch/AP) to an authentication server (RADIUS)"),
    ("Posture assessment", "NAC health check of a connecting device — patch level, antivirus current, disk encryption, required configuration — before granting network access"),
    ("Quarantine/remediation VLAN", "Restricted network segment where NAC places non-compliant devices, allowing access only to update servers until they pass re-checks"),
    ("Endpoint detection and response (EDR)", "Agent continuously records endpoint telemetry, applies behavioral analytics to catch fileless/novel attacks, and can isolate hosts, kill processes, quarantine files"),
    ("Extended detection and response (XDR)", "Correlates telemetry across endpoints plus network, email, identity, and cloud in one platform, with coordinated response across those layers"),
    ("User behavior analytics", "Baselines each user's normal activity (times, locations, systems, data volumes) and flags anomalies — catches insider threats and compromised credentials"),
    ("Forward proxy", "Server between internal users and the internet that fetches, inspects, filters, caches, and logs web content on behalf of clients — the centralized web-filter model"),
    ("Group Policy Object (GPO)", "Package of Group Policy settings linked to a site, domain, or organizational unit; domain-joined machines apply linked GPOs automatically"),
    ("SELinux permissive mode", "SELinux mode in which policy violations are logged but allowed — used for testing and troubleshooting policy before enforcing it"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "An administrator adds a rule to block a workstation's internet access, but the workstation still gets out. The new deny rule sits below an existing rule allowing the entire subnet. Why does the block fail?",
        "choices": [
            "The implicit deny at the end of the ruleset overrides the new rule",
            "Firewall rules are processed top-down and the first matching rule wins, so the broad allow matches first",
            "Deny rules require a firewall reboot before they take effect",
            "Workstation traffic is exempt from subnet-level rules",
        ],
        "answer": 1,
        "explain": "Rules are evaluated top-down and processing stops at the first match. The workstation's traffic matches the broader subnet allow before it ever reaches the specific deny below it, making the deny unreachable. The fix is to move the specific deny above the broad allow.",
    },
    {
        "type": "mc",
        "q": "A packet arrives at a firewall and matches none of the configured rules. What happens to it?",
        "choices": [
            "It is allowed, because no rule denied it",
            "It is dropped by the implicit deny at the end of the ruleset",
            "It is quarantined for administrator review",
            "It is forwarded to the screened subnet",
        ],
        "answer": 1,
        "explain": "Every secure firewall ruleset ends in an implicit deny: any traffic not explicitly permitted by a rule is dropped. This is default-deny policy — permit only what the business requires, and everything unlisted dies at the bottom of the list.",
    },
    {
        "type": "mc",
        "q": "A network engineer configures an ordered list of permit/deny statements on a router interface to filter packets by source IP, destination IP, protocol, and port, applied inbound. What is this called?",
        "choices": ["A screened subnet", "An access control list (ACL)", "A DMARC policy", "A reputation filter"],
        "answer": 1,
        "explain": "Access lists (ACLs) are the ordered permit/deny statements that implement packet filtering on routers and network devices. Like firewall rules, they are evaluated sequentially top-down, first match wins, with an implicit deny all at the end, and are applied to interfaces in a direction.",
    },
    {
        "type": "mc",
        "q": "A security review requires blocking unencrypted remote-terminal traffic at the perimeter firewall. Which port should be blocked?",
        "choices": ["TCP 22", "TCP 23", "TCP 443", "TCP 636"],
        "answer": 1,
        "explain": "Telnet, the unencrypted remote-terminal protocol, uses TCP port 23 and should be blocked (and replaced by SSH on TCP 22). Port 443 is HTTPS and 636 is LDAPS — both secure protocols you would typically allow, not block.",
    },
    {
        "type": "mc",
        "q": "A company must host a public web server that internet users can reach, without exposing the internal LAN if the server is compromised. Where should the server be placed?",
        "choices": [
            "On the internal LAN behind the firewall",
            "In a screened subnet between the internet and the internal network",
            "Directly on the internet outside the firewall",
            "In a quarantine VLAN managed by NAC",
        ],
        "answer": 1,
        "explain": "A screened subnet (formerly DMZ) is an isolated segment hosting public-facing services, built with two firewalls or a three-interface firewall. Internet users reach only the screened-subnet hosts on published ports, and those hosts have minimal access inward — a compromise is contained there.",
    },
    {
        "type": "mc",
        "q": "The security team wants a device that sits in the traffic path and automatically blocks known exploits in real time, not just alerts on them. What should be deployed?",
        "choices": [
            "An IDS fed by a SPAN port",
            "An inline IPS",
            "A file integrity monitor",
            "A DNS sinkhole",
        ],
        "answer": 1,
        "explain": "An IPS sits inline in the traffic path and can actively block malicious traffic; an IDS is passive/out-of-band (TAP or SPAN-fed) and can only alert. The IPS trade-off: a false positive can block legitimate traffic, and an inline failure can disrupt the network.",
    },
    {
        "type": "mc",
        "q": "Which is the PRIMARY limitation of signature-based IDS/IPS detection?",
        "choices": [
            "It generates far more false positives than anomaly detection",
            "It cannot detect brand-new (zero-day) attacks because no signature exists yet",
            "It requires a lengthy training period to learn normal traffic",
            "It cannot be updated once deployed",
        ],
        "answer": 1,
        "explain": "Signature detection matches known attack patterns, so it is accurate with few false positives for known threats — but a zero-day attack has no signature yet and slips through. The training period and higher false-positive rate describe anomaly/trend-based detection instead.",
    },
    {
        "type": "mc",
        "q": "An IPS builds a baseline of normal traffic volumes, protocols, and times, then alerts when activity deviates significantly from that baseline. Which detection method is this, and what is its main drawback?",
        "choices": [
            "Signature-based; it misses zero-day attacks",
            "Trend/anomaly-based; it produces more false positives and needs a learning period",
            "Reputation-based; it depends on third-party scores",
            "Heuristic; it cannot be tuned",
        ],
        "answer": 1,
        "explain": "Trend/anomaly-based detection baselines normal behavior and flags deviations, so it can catch novel/zero-day attacks a signature would miss — at the cost of more false positives and a training period to learn what 'normal' looks like.",
    },
    {
        "type": "mc",
        "q": "Remote employees working from home and coffee shops keep reaching sites the on-premises web filter would block. Which web-filter deployment model fixes this?",
        "choices": [
            "Centralized proxy",
            "Agent-based filtering installed on each laptop",
            "URL scanning at the perimeter firewall",
            "A screened subnet for remote users",
        ],
        "answer": 1,
        "explain": "Agent-based filtering runs on each device, so policy follows the user everywhere — including off the corporate network. A centralized proxy only sees traffic that routes through it, and home/remote traffic never touches the on-premises proxy.",
    },
    {
        "type": "mc",
        "q": "An organization routes all employee web requests through a single server that inspects, filters, caches, and logs the traffic on behalf of clients. Which web-filter model is this?",
        "choices": ["Agent-based filtering", "Centralized proxy (forward proxy)", "DNS filtering", "Reputation scoring"],
        "answer": 1,
        "explain": "A centralized (forward) proxy sits between internal users and the internet: clients send requests to the proxy, which fetches content, inspects and filters it, caches it, and logs activity — a single on-network choke point for web policy.",
    },
    {
        "type": "mc",
        "q": "Before allowing a connection, the web filter examines each requested web address and checks it against a database of known-malicious sites. Which sub-feature is this?",
        "choices": ["Content categorization", "URL scanning", "Reputation", "Block rules"],
        "answer": 1,
        "explain": "URL scanning examines the requested URL and checks it against databases/lists of known-malicious or prohibited sites before permitting the connection. Categorization groups sites by type, and reputation scores sites by risk even when they are not yet on a known-bad list.",
    },
    {
        "type": "mc",
        "q": "Management wants to block all gambling and adult websites at once without listing individual sites. Which web-filter capability accomplishes this?",
        "choices": ["URL scanning", "Content categorization", "Agent-based filtering", "Reputation"],
        "answer": 1,
        "explain": "Content categorization groups sites into categories (gambling, adult, social media, malware, etc.) so administrators can allow or block entire categories rather than maintaining lists of individual sites.",
    },
    {
        "type": "mc",
        "q": "A brand-new website is not on any blocklist, but the web filter blocks it anyway because the domain is days old, oddly hosted, and scored as risky. Which capability made the decision?",
        "choices": ["Block rules", "URL scanning", "Reputation", "Content categorization"],
        "answer": 2,
        "explain": "Reputation filtering assigns each site a risk/trust score based on history, hosting, age, and observed behavior, and blocks low-reputation sites even when they are not yet on any known-bad list — exactly the gap new malicious domains exploit.",
    },
    {
        "type": "mc",
        "q": "An administrator configures the web filter to explicitly deny a specific competitor's URL and all .exe downloads. Which web-filter component holds these entries?",
        "choices": ["Block rules", "Reputation scores", "Content categories", "The proxy cache"],
        "answer": 0,
        "explain": "Block rules are the explicit deny entries of the filter — specific URLs/domains, categories, or file types — the enforcement layer that defines exactly what is denied.",
    },
    {
        "type": "mc",
        "q": "A Windows administrator must enforce password length, account lockout, and disable an insecure service on every domain-joined computer centrally. Which capability should be used?",
        "choices": ["SELinux", "Group Policy (GPOs)", "File integrity monitoring", "Local user account settings on each PC"],
        "answer": 1,
        "explain": "Group Policy is the Windows/Active Directory mechanism for central configuration enforcement: settings are packaged in GPOs linked to sites, domains, or OUs, and domain-joined machines apply them automatically (refresh via gpupdate). SELinux is the Linux MAC mechanism.",
    },
    {
        "type": "mc",
        "q": "A Linux web service is compromised and the attacker escalates to root, yet still cannot read other users' files or replace system binaries. Which OS security capability most likely confined the attacker?",
        "choices": [
            "Group Policy",
            "SELinux enforcing mandatory access control",
            "File integrity monitoring",
            "Discretionary file permissions",
        ],
        "answer": 1,
        "explain": "SELinux adds kernel-enforced mandatory access control: every process and resource carries a security label, and policy dictates exactly which labeled processes may access which resources. Even a root-level process is confined to what its policy permits — discretionary permissions alone could not stop root.",
    },
    {
        "type": "mc",
        "q": "Network devices are still managed over Telnet. What is the correct secure replacement and port?",
        "choices": ["HTTPS on 443", "SSH on 22", "SFTP on 21", "LDAPS on 636"],
        "answer": 1,
        "explain": "Telnet (TCP 23) sends credentials and sessions in cleartext; the secure replacement for remote shell/device management is SSH on TCP 22. SFTP also rides SSH on port 22 — it does not use 21, which is plain FTP's control port.",
    },
    {
        "type": "mc",
        "q": "A monitoring system polls network devices with SNMPv2c using community strings. What should it be migrated to, and why?",
        "choices": [
            "SNMPv3, because it adds authentication and encryption that v1/v2c lack",
            "SNMPv3, because it moves to a new dedicated secure port",
            "SNMP over Telnet for an encrypted channel",
            "Syslog, because SNMP cannot be secured",
        ],
        "answer": 0,
        "explain": "SNMPv1/v2c send community strings in cleartext. SNMPv3 adds authentication and encryption — but it keeps the same ports (UDP 161 for queries, 162 for traps); the protocol version changes, not the port. That port fact makes the second choice wrong.",
    },
    {
        "type": "mc",
        "q": "A mail client must submit outgoing email over an encrypted connection using STARTTLS. Which port is the standard choice?",
        "choices": ["25", "110", "587", "993"],
        "answer": 2,
        "explain": "Port 587 is the standard mail-submission port using STARTTLS to upgrade the connection to encrypted; 465 is implicit TLS submission. Port 25 is server-to-server SMTP, 110 is cleartext POP3, and 993 is IMAPS (retrieval, not submission).",
    },
    {
        "type": "mc",
        "q": "Two branch offices must exchange traffic securely across the internet, encrypting entire original packets gateway-to-gateway. Which transport method fits?",
        "choices": [
            "IPsec in transport mode",
            "IPsec in tunnel mode (site-to-site VPN)",
            "TLS on each application",
            "WPA3",
        ],
        "answer": 1,
        "explain": "IPsec tunnel mode protects the entire original packet and is the basis of gateway-to-gateway site-to-site VPNs. Transport mode protects only the payload and is used host-to-host. WPA3 secures the wireless link, and per-application TLS does not create the office-to-office tunnel.",
    },
    {
        "type": "mc",
        "q": "Which statement about IPsec modes is TRUE?",
        "choices": [
            "Transport mode encrypts the entire original packet including its IP header",
            "Tunnel mode protects the entire original packet; transport mode protects only the payload",
            "Tunnel mode is only usable between two hosts, never gateways",
            "Transport mode is the basis of most site-to-site VPNs",
        ],
        "answer": 1,
        "explain": "Tunnel mode encapsulates and protects the whole original packet (typical gateway-to-gateway/site-to-site VPN); transport mode protects only the payload and is used host-to-host. The other options invert these facts.",
    },
    {
        "type": "mc",
        "q": "Malware on an infected host tries to contact its command-and-control server by domain name, but the query returns a sinkhole address and the callback fails. Which capability did this?",
        "choices": ["EDR", "DNS filtering", "A centralized proxy", "DLP"],
        "answer": 1,
        "explain": "DNS filtering blocks malicious domains at the name-resolution step: the filtering resolver refuses to return the real address (returning a block page or sinkhole instead), so the connection never begins. It is protocol-agnostic and cripples C2 callbacks — though direct-to-IP traffic bypasses it.",
    },
    {
        "type": "mc",
        "q": "A company publishes a DNS TXT record listing the IP addresses of mail servers authorized to send email for its domain. Which email security standard is this?",
        "choices": ["DKIM", "DMARC", "SPF", "S/MIME"],
        "answer": 2,
        "explain": "SPF (Sender Policy Framework) publishes, in a DNS TXT record, the mail servers/IPs authorized to send for the domain; receivers check the connecting sender's IP against it. SPF authenticates the sending server — DKIM signs messages, and DMARC is the policy/reporting layer above both.",
    },
    {
        "type": "mc",
        "q": "Receiving mail servers verify a cryptographic signature on incoming messages by fetching the sending domain's public key from DNS, proving origin and that the message was not altered in transit. Which standard is this?",
        "choices": ["SPF", "DKIM", "DMARC", "STARTTLS"],
        "answer": 1,
        "explain": "DKIM (DomainKeys Identified Mail): the sending server signs selected headers and the body with the domain's private key, and receivers verify with the public key published in DNS — integrity plus origin authentication. SPF lists authorized senders; DMARC adds alignment, failure policy, and reporting.",
    },
    {
        "type": "mc",
        "q": "A domain publishes a record at _dmarc.example.com with p=quarantine. What does this instruct receiving mail servers to do with messages that fail SPF/DKIM alignment?",
        "choices": [
            "Refuse delivery outright",
            "Deliver them to the recipient's spam/junk folder",
            "Deliver them normally but log the failure",
            "Strip attachments before delivery",
        ],
        "answer": 1,
        "explain": "DMARC's p= policy tells receivers how to handle authentication failures: none (monitor only), quarantine (send to spam/junk), or reject (refuse outright). p=quarantine is the middle setting. DMARC also provides aggregate reporting back to the domain owner.",
    },
    {
        "type": "mc",
        "q": "All inbound company mail flows through a service that filters spam and phishing, detonates and scans attachments for malware, enforces SPF/DKIM/DMARC checks, and applies DLP to outbound messages. What is this?",
        "choices": ["A DNS filter", "An email security gateway", "A forward proxy", "An XDR platform"],
        "answer": 1,
        "explain": "An email security gateway is the appliance/cloud choke point all mail traverses: spam/phishing filtering, attachment and link scanning, SPF/DKIM/DMARC enforcement, outbound encryption, and email DLP — the mail analog of a web proxy.",
    },
    {
        "type": "mc",
        "q": "An administrator must be alerted if /etc/passwd or any system binary is modified without an authorized change. Which capability provides this?",
        "choices": ["DLP", "File integrity monitoring", "NAC", "DNS filtering"],
        "answer": 1,
        "explain": "File integrity monitoring (FIM) records a known-good baseline of cryptographic hashes and attributes for critical files, then recomputes and compares; any unexplained difference signals possible compromise. Classic tool: Tripwire. FIM is detective — it catches changes, it does not prevent them.",
    },
    {
        "type": "mc",
        "q": "Employees must be prevented from emailing customer credit card numbers outside the company or copying them to USB drives. Which capability enforces this?",
        "choices": ["File integrity monitoring", "Data loss prevention (DLP)", "User behavior analytics", "IPS signatures"],
        "answer": 1,
        "explain": "DLP identifies sensitive data via content inspection (e.g., 16-digit card patterns, keywords, fingerprints) and classification labels, then blocks or alerts when it moves contrary to policy — endpoint DLP covers USB/print, network DLP covers email and uploads, cloud DLP covers SaaS sharing.",
    },
    {
        "type": "mc",
        "q": "Company policy: any laptop missing patches or current antivirus must be placed on a restricted network segment with access only to update servers until it is fixed. Which capability implements this?",
        "choices": [
            "NAC with posture assessment and a remediation VLAN",
            "EDR host isolation",
            "A screened subnet",
            "Agent-based web filtering",
        ],
        "answer": 0,
        "explain": "NAC decides whether a device may join the network based on identity and health/posture (patch level, AV, encryption). Non-compliant devices are denied or quarantined in a remediation VLAN with access only to update servers, then re-checked and admitted once fixed.",
    },
    {
        "type": "mc",
        "q": "In the 802.1X architecture used by NAC, what role does the network switch or wireless access point play?",
        "choices": ["Supplicant", "Authenticator", "Authentication server", "Certificate authority"],
        "answer": 1,
        "explain": "In 802.1X the connecting device is the supplicant, the switch or AP is the authenticator (it blocks traffic until authentication succeeds), and the authentication server — typically RADIUS — makes the decision.",
    },
    {
        "type": "mc",
        "q": "A security tool continuously records process launches, file changes, and network connections on each laptop, detects a fileless attack behaviorally, and lets the SOC isolate the infected host from the network. What is this tool?",
        "choices": ["Signature antivirus", "EDR", "FIM", "A web filter agent"],
        "answer": 1,
        "explain": "Endpoint detection and response (EDR) goes beyond signature AV: continuous endpoint telemetry, behavioral analytics that catch fileless and novel attacks, and response actions — isolate the host, kill processes, quarantine files — plus forensic investigation of recorded activity.",
    },
    {
        "type": "mc",
        "q": "The SOC wants one platform that correlates endpoint telemetry with email, network, identity, and cloud events so individually benign signals combine into a single detected incident. Which capability is this?",
        "choices": ["EDR", "XDR", "UBA", "NAC"],
        "answer": 1,
        "explain": "Extended detection and response (XDR) widens EDR's lens: it correlates telemetry across endpoints plus network, email, identity, and cloud workloads in one platform, with coordinated response across those layers. EDR alone covers endpoints only.",
    },
    {
        "type": "mc",
        "q": "A valid employee account suddenly logs in at 3 a.m. from an unusual country and downloads gigabytes from a file server it rarely touches. No malware is present and the credentials are genuine. Which capability is designed to flag this?",
        "choices": ["Signature-based IPS", "File integrity monitoring", "User behavior analytics", "DNS filtering"],
        "answer": 2,
        "explain": "User behavior analytics (UBA/UEBA) baselines each user's normal login times, locations, systems, and data volumes, then flags anomalous deviations. Its specialty is insider threats and compromised credentials — the credentials are valid either way; only the behavior is wrong.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: An IDS deployed on a SPAN port can actively block an attack it detects.",
        "answer": False,
        "explain": "An IDS is passive/out-of-band — fed by a TAP or SPAN/mirror port — and can only alert, never block. Blocking requires an IPS deployed inline in the traffic path.",
    },
    {
        "type": "tf",
        "q": "True or False: Keeping IPS signatures continuously updated allows signature-based detection to catch zero-day attacks.",
        "answer": False,
        "explain": "By definition a zero-day attack has no signature yet, so signature-based detection cannot catch it no matter how current the database is. Updates keep you protected against newly published known threats; catching truly novel attacks requires trend/anomaly-based detection.",
    },
    {
        "type": "tf",
        "q": "True or False: In SELinux permissive mode, policy violations are logged but still allowed to proceed.",
        "answer": True,
        "explain": "Permissive mode logs what would have been blocked without actually blocking it, making it the mode for testing and troubleshooting policy. Enforcing mode blocks and logs violations; disabled turns SELinux off entirely.",
    },
    {
        "type": "tf",
        "q": "True or False: SPF verifies that the content of an email message was not altered in transit.",
        "answer": False,
        "explain": "SPF authenticates only the sending server — the receiver checks the connecting IP against the domain's DNS TXT list of authorized senders. Message integrity (and origin) is proven by DKIM's cryptographic signature, verified via the public key published in DNS.",
    },
    {
        "type": "tf",
        "q": "True or False: STARTTLS upgrades a connection to encrypted on the same standard port rather than moving to a new dedicated port.",
        "answer": True,
        "explain": "STARTTLS begins as a plaintext connection on the standard port and upgrades it to TLS in place — e.g., mail submission on port 587. Implicit TLS instead uses a separate dedicated port, such as 465 for submission or 990 for FTPS control.",
    },
    {
        "type": "tf",
        "q": "True or False: File integrity monitoring prevents attackers from modifying critical system files.",
        "answer": False,
        "explain": "FIM is a detective control: it compares current hashes/attributes against a known-good baseline and alerts on unauthorized changes after they occur. It does not block the modification itself — prevention comes from access controls like SELinux or file permissions.",
    },
    {
        "type": "tf",
        "q": "True or False: DMARC provides useful protection on its own even if a domain publishes neither SPF nor DKIM.",
        "answer": False,
        "explain": "DMARC is the policy and reporting layer built on top of SPF and DKIM: it requires their results to align with the visible From: domain and tells receivers what to do on failure. With neither SPF nor DKIM underneath, there is nothing to align or evaluate — DMARC does nothing by itself.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The unwritten rule at the bottom of every firewall ruleset that drops all unmatched traffic is called the implicit ______. (type your answer)",
        "answers": ["deny", "implicit deny"],
        "explain": "The implicit deny drops any traffic not explicitly permitted by a rule — the foundation of default-deny policy. If no rule matched at all, the implicit deny is what killed the traffic.",
    },
    {
        "type": "fill",
        "q": "The screened subnet that isolates public-facing servers between the internet and the LAN was previously called the ______. (type the abbreviation)",
        "answers": ["dmz", "demilitarized zone"],
        "explain": "Screened subnet is the current SY0-701 term for what was long called the DMZ (demilitarized zone) — a small isolated segment for public web, mail, and DNS servers, built with two firewalls or one three-interface firewall.",
    },
    {
        "type": "fill",
        "q": "LDAPS — LDAP secured over TLS/SSL — uses TCP port ______. (type the number)",
        "answers": ["636"],
        "explain": "Plain LDAP uses port 389 and exposes directory queries and simple-bind credentials in cleartext; LDAPS encrypts the session on TCP 636. Swapping 389 for 636 is a classic secure-protocol implementation on the exam.",
    },
    {
        "type": "fill",
        "q": "SSH, the encrypted replacement for Telnet, uses TCP port ______. (type the number)",
        "answers": ["22"],
        "explain": "SSH provides an encrypted remote shell on TCP 22, replacing cleartext Telnet on TCP 23. SFTP, the SSH file transfer protocol, also runs over port 22.",
    },
    {
        "type": "fill",
        "q": "The DMARC policy value that tells receiving servers to refuse delivery of failing messages outright is p=______. (type your answer)",
        "answers": ["reject"],
        "explain": "DMARC's three policy actions are none (monitor only), quarantine (deliver to spam/junk), and reject (refuse delivery outright). Organizations typically roll out none → quarantine → reject as confidence in their SPF/DKIM setup grows.",
    },
    {
        "type": "fill",
        "q": "The SELinux mode in which violations are logged but allowed — used for testing policy — is ______ mode. (type your answer)",
        "answers": ["permissive"],
        "explain": "Permissive mode logs would-be violations without blocking them, letting administrators troubleshoot policy safely. Enforcing mode blocks and logs; disabled turns SELinux off.",
    },
    {
        "type": "fill",
        "q": "File integrity monitoring detects changes by comparing current file hashes against a known-good ______. (type your answer)",
        "answers": ["baseline"],
        "explain": "FIM records a baseline of cryptographic hashes and attributes for monitored files, then periodically recomputes and compares. Any unexplained difference from the baseline signals a possible compromise, such as malware replacing system binaries.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each web-filter sub-feature to its description.",
        "pairs": [
            ["Agent-based", "Software on each device; policy follows roaming/remote users"],
            ["Centralized proxy", "All web traffic routes through one inspecting choke point"],
            ["URL scanning", "Requested address checked against known-malicious lists"],
            ["Content categorization", "Allow or block whole groups of sites (gambling, adult)"],
            ["Block rules", "Explicit deny entries: specific URLs, categories, file types"],
            ["Reputation", "Risk score blocks suspicious sites not yet on any list"],
        ],
        "explain": "Agent-based follows the user off-network; the centralized proxy is the on-network choke point; URL scanning checks requests against known-bad lists; categorization blocks by site type; block rules are the explicit deny layer; reputation scores block risky sites before they hit any blocklist.",
    },
    {
        "type": "match",
        "q": "Match each email security mechanism to its role.",
        "pairs": [
            ["SPF", "DNS TXT record listing servers authorized to send for the domain"],
            ["DKIM", "Private-key signature verified via a public key in DNS"],
            ["DMARC", "Alignment + failure policy (none/quarantine/reject) + reporting"],
            ["Gateway", "Choke-point appliance filtering spam, phishing, and malware"],
        ],
        "explain": "SPF says which servers may send; DKIM cryptographically signs mail for origin and integrity; DMARC sits on top of both, enforcing From-domain alignment, setting failure policy, and returning reports; the gateway is the appliance that filters all mail flow and enforces the trio.",
    },
    {
        "type": "match",
        "q": "Match each enterprise capability to the problem it solves.",
        "pairs": [
            ["DNS filtering", "Stop hosts from ever resolving known-malicious domains"],
            ["File integrity monitoring", "Detect unauthorized changes to critical system files"],
            ["DLP", "Block sensitive data from leaving by email, web, or USB"],
            ["NAC", "Keep unhealthy or unknown devices off the network"],
            ["User behavior analytics", "Flag valid accounts behaving abnormally (insider threat)"],
        ],
        "explain": "DNS filtering kills connections at name resolution; FIM compares hashes against a baseline to catch tampering; DLP is the anti-exfiltration control; NAC gates admission on identity and posture; UBA baselines normal user activity to catch insiders and compromised credentials.",
    },
    {
        "type": "match",
        "q": "Match each insecure protocol to its secure replacement.",
        "pairs": [
            ["Telnet", "SSH"],
            ["HTTP", "HTTPS"],
            ["LDAP", "LDAPS"],
            ["SNMPv1/v2c", "SNMPv3"],
            ["RTP", "SRTP"],
        ],
        "explain": "Telnet→SSH (22), HTTP→HTTPS (443), LDAP→LDAPS (636), SNMPv1/v2c→SNMPv3 (same ports 161/162, protocol upgrade only), and RTP→SRTP for encrypted real-time voice/video. FTP similarly goes to SFTP or FTPS, and cleartext mail protocols to their TLS versions.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps of NAC admission using 802.1X and posture assessment in order.",
        "items": [
            "Device (supplicant) connects and authenticates through the switch/AP (authenticator) to the RADIUS server",
            "NAC performs a posture/health assessment of the device",
            "Non-compliant device is placed in a quarantine/remediation VLAN with access only to update servers",
            "Device is remediated (patched, AV updated)",
            "Device is re-checked and admitted to the production network",
        ],
        "explain": "802.1X authenticates the supplicant via the authenticator to the authentication server first; then posture is assessed. Failing devices go to a remediation VLAN, get fixed, and are re-checked before admission — identity plus health, enforced at connection time.",
    },
    {
        "type": "order",
        "q": "Arrange the typical rollout of email authentication for a domain in order.",
        "items": [
            "Publish an SPF record listing authorized sending servers",
            "Configure DKIM signing and publish the public key in DNS",
            "Publish a DMARC record with p=none to monitor",
            "Review aggregate reports and fix legitimate senders that fail",
            "Tighten the DMARC policy to quarantine, then reject",
        ],
        "explain": "SPF and DKIM are the underlying authentication mechanisms, so they come first. DMARC starts at p=none to gather reports without affecting delivery; reports reveal legitimate senders that need fixing; only then is the policy escalated to quarantine and finally reject.",
    },
]
