TOPIC = {
    "id": "4.6",
    "domain": 4,
    "title": "Given a scenario, implement and maintain identity and access management.",
    "short": "Identity & Access Management",
}

TERMS = [
    ("Provisioning", "Creating a user account and granting the access rights, group memberships, and resources the person's job requires, typically at onboarding"),
    ("De-provisioning", "Disabling or removing an account and revoking all its access when the user leaves or changes roles; must be prompt to prevent orphaned accounts"),
    ("Orphaned account", "An active account belonging to someone who has left the organization; valid credentials with no owner watching them — a prime attacker target"),
    ("Privilege creep", "Gradual accumulation of permissions as a user changes roles without old access being revoked; countered by access reviews and revocation at transfer"),
    ("Identity proofing", "Verifying that a person really is who they claim to be (e.g., government ID checks) before an account or credential is issued"),
    ("Attestation", "Formal periodic review in which a manager or resource owner certifies that each user's access rights are still appropriate; catches privilege creep"),
    ("Federation", "Trust arrangement letting users authenticate with their own organization's identity provider to access another organization's resources"),
    ("Single sign-on (SSO)", "Authenticate once, then access multiple applications without re-entering credentials; centralizes authentication and reduces password fatigue"),
    ("Identity provider (IdP)", "The system that authenticates the user and issues assertions or tokens vouching for their identity in SSO/federation"),
    ("Service provider (SP)", "The application or resource that trusts the identity provider's assertion and grants the user access"),
    ("Lightweight Directory Access Protocol (LDAP)", "Protocol for querying and modifying directory services such as Active Directory; port 389, or 636 for LDAPS (over SSL/TLS)"),
    ("Open authorization (OAuth)", "Authorization framework for delegated access: a user grants a third-party app limited, token-based access to resources without sharing a password"),
    ("Security Assertions Markup Language (SAML)", "XML-based standard for exchanging authentication assertions between an identity provider and a service provider; classic web federated SSO"),
    ("OpenID Connect (OIDC)", "Authentication/identity layer built on top of OAuth 2.0; what modern 'log in with...' web and mobile SSO actually uses"),
    ("Interoperability", "Ability of different vendors' identity systems to work together, achieved through open standards such as SAML, OAuth, OIDC, LDAP, and SCIM"),
    ("Mandatory access control (MAC)", "OS-enforced model using classification labels on objects and clearances on subjects; not even the data owner can override the policy"),
    ("Discretionary access control (DAC)", "Model in which the owner of each resource decides at their discretion who may access it; standard file-system permissions"),
    ("Role-based access control (RBAC)", "Permissions attached to job roles/groups; users receive access by being placed in a role rather than by individual grants"),
    ("Rule-based access control", "System-wide predefined rules applied to everyone regardless of identity, such as firewall ACLs or blocking all after-hours logons"),
    ("Attribute-based access control (ABAC)", "Fine-grained decisions combining attributes of the user, resource, action, and environment (department, device health, location, time)"),
    ("Time-of-day restrictions", "Access control limiting when an account can log on or reach resources, shrinking the window in which stolen credentials work"),
    ("Least privilege", "Principle that every user, account, and process gets only the minimum access required to do its job, and no more"),
    ("Multifactor authentication (MFA)", "Requiring proof from two or more different factor categories (know/have/are/somewhere); two of the same category is not MFA"),
    ("Something you know", "Knowledge factor: password, PIN, or security-question answer"),
    ("Something you have", "Possession factor: smart card, hardware token, security key, or phone running an authenticator app"),
    ("Something you are", "Inherence factor: biometrics such as fingerprint, face, iris, or voice"),
    ("Somewhere you are", "Location factor: GPS/geolocation, IP address range, or geofencing used as evidence in authentication"),
    ("Biometrics", "Authentication by physical characteristic; accuracy measured by FAR (impostor accepted), FRR (legit user rejected), and CER where they cross"),
    ("Hard authentication token", "Dedicated physical device proving possession, such as a key fob displaying one-time passwords or a smart card"),
    ("Soft authentication token", "Software-based token, typically an authenticator app generating TOTP (time-based) or HOTP (counter-based) one-time passwords"),
    ("Security key", "Physical USB/NFC key (e.g., FIDO2/WebAuthn) that signs origin-bound challenges; the phishing-resistant MFA implementation"),
    ("Password manager", "Vault application that generates, stores, and fills strong unique passwords for every account under one master password"),
    ("Passwordless authentication", "Replacing passwords with possession/inherence proofs (passkeys, FIDO2 keys, platform biometrics); no shared secret to phish or breach"),
    ("Just-in-time (JIT) permissions", "PAM approach granting elevated rights only on request, for a specific task and limited time, then automatically revoking them"),
    ("Password vaulting", "PAM tool storing privileged credentials in an encrypted vault; admins check them out, use is logged, and passwords rotate after check-in"),
    ("Ephemeral credentials", "Temporary, short-lived credentials created on demand that expire automatically, leaving nothing long-lived behind to steal"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A new employee starts Monday. The IT team creates her account, adds her to the standard groups for her department, and grants access to the applications her role requires. Which IAM process is this?",
        "choices": ["Identity proofing", "Provisioning", "Attestation", "Federation"],
        "answer": 1,
        "explain": "Provisioning is creating an account and granting the role-appropriate access a new user needs. Identity proofing happens earlier (verifying who the person is), attestation is the later periodic review of access, and federation is cross-organization identity trust.",
    },
    {
        "type": "mc",
        "q": "An employee is terminated Friday afternoon. Which action BEST prevents the account from becoming a security risk?",
        "choices": [
            "Delete the account after the standard 90-day retention period",
            "Disable the account immediately upon termination",
            "Reduce the account's permissions to read-only",
            "Change the account password at the next scheduled rotation",
        ],
        "answer": 1,
        "explain": "De-provisioning must be prompt: disable the account immediately (deletion can follow later so files and audit trails are preserved). Waiting 90 days, leaving read-only access, or waiting for a rotation window all leave a live orphaned account an attacker or the ex-employee could use.",
    },
    {
        "type": "mc",
        "q": "An audit finds that an employee who moved from accounting to marketing two years ago can still approve invoices. Permissions from each previous role were never removed. What is this condition called?",
        "choices": ["Privilege creep", "Identity proofing failure", "Password reuse", "Federation"],
        "answer": 0,
        "explain": "Privilege creep (authorization creep) is the accumulation of permissions across role changes when old access is never revoked. The fixes are revoking unneeded access at every transfer and periodic attestation/access reviews to catch what slips through.",
    },
    {
        "type": "mc",
        "q": "Before issuing credentials to a remote new hire, the company requires a scan of her government-issued ID and a live selfie match. Which IAM concept does this describe?",
        "choices": ["Attestation", "Single sign-on", "Identity proofing", "Password vaulting"],
        "answer": 2,
        "explain": "Identity proofing verifies that a person actually is who they claim to be before an account or credential is issued — document checks and live photo matching are classic methods. Attestation, by contrast, is the periodic recertification of existing access rights.",
    },
    {
        "type": "mc",
        "q": "Every quarter, each department manager receives a report of their employees' access rights and must formally confirm that each permission is still required, flagging any that are not. What is this process called?",
        "choices": ["Attestation", "Enumeration", "Identity proofing", "Provisioning"],
        "answer": 0,
        "explain": "Attestation (access review/recertification) is a responsible party formally certifying that users' access rights are still appropriate. It is the standing countermeasure to privilege creep and orphaned accounts, and auditors commonly require it on a schedule.",
    },
    {
        "type": "mc",
        "q": "Users at Company A log in with their own corporate credentials and can then access a supplier portal run by Company B, which trusts Company A's identity provider. Which concept does this BEST illustrate?",
        "choices": ["Discretionary access control", "Federation", "Password vaulting", "Attestation"],
        "answer": 1,
        "explain": "Federation extends identity trust across organizational boundaries: users authenticate with their own organization's IdP, and the partner's service provider accepts that authentication instead of issuing separate credentials. SSO within one company becomes federation between companies.",
    },
    {
        "type": "mc",
        "q": "After authenticating once in the morning, a user can open email, the HR portal, and the CRM without entering credentials again. Which capability is in use?",
        "choices": ["Multifactor authentication", "Just-in-time permissions", "Single sign-on", "Mandatory access control"],
        "answer": 2,
        "explain": "Single sign-on lets a user authenticate once and access multiple applications without re-authenticating. It centralizes login where strong controls (MFA, logging) can be applied — and because the SSO identity is a single point of compromise, it should be protected with MFA.",
    },
    {
        "type": "mc",
        "q": "An application needs to look up users and group memberships in the corporate Active Directory. Which protocol is it MOST likely using, and on which port is the encrypted version?",
        "choices": ["SAML over port 443", "LDAPS over port 636", "OAuth over port 389", "LDAP over port 88"],
        "answer": 1,
        "explain": "LDAP is the protocol for querying directory services such as Active Directory; unencrypted LDAP uses port 389, and LDAPS (LDAP over SSL/TLS) uses TCP 636. SAML carries web SSO assertions, OAuth is an authorization framework (not a directory protocol), and port 88 is Kerberos.",
    },
    {
        "type": "mc",
        "q": "A user grants a third-party scheduling app permission to read her cloud calendar. The app receives a limited-scope access token and never learns her password. Which standard makes this possible?",
        "choices": ["OAuth", "LDAP", "SAML", "MAC"],
        "answer": 0,
        "explain": "OAuth (Open authorization) is a delegated-authorization framework: the resource service issues the third-party app a scoped access token instead of the user sharing a password. SAML handles authentication assertions, and LDAP queries directories — neither does delegated app authorization.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST describes SAML?",
        "choices": [
            "A JSON-based framework for delegating API authorization to third-party apps",
            "An XML-based standard for exchanging authentication assertions between an identity provider and a service provider",
            "A directory access protocol used to query user and group objects",
            "A protocol for rotating privileged passwords stored in a vault",
        ],
        "answer": 1,
        "explain": "SAML (Security Assertions Markup Language) is XML-based and carries signed authentication/authorization assertions from an IdP to an SP — the classic protocol for browser-based federated SSO. The JSON/API-delegation description fits OAuth, and directory queries are LDAP.",
    },
    {
        "type": "mc",
        "q": "Which protocol is primarily an AUTHORIZATION framework rather than an authentication protocol?",
        "choices": ["SAML", "OpenID Connect", "OAuth", "Kerberos"],
        "answer": 2,
        "explain": "OAuth is about delegated authorization — what an application may do — not proving who a user is. SAML and OpenID Connect (which layers identity on top of OAuth 2.0) are authentication protocols, as is Kerberos. 'OAuth authorizes; SAML/OIDC authenticate' is a reliable exam heuristic.",
    },
    {
        "type": "mc",
        "q": "When selecting a new SaaS product, the security team requires support for SAML, OIDC, and SCIM so the product can plug into the existing identity provider and automated provisioning pipeline. Which IAM consideration is driving this requirement?",
        "choices": ["Interoperability", "Least privilege", "Identity proofing", "Time-of-day restrictions"],
        "answer": 0,
        "explain": "Interoperability is the ability of different vendors' identity systems to work together, which comes from supporting open standards such as SAML, OAuth/OIDC, LDAP, and SCIM. Proprietary-only identity integrations create lock-in and gaps that become security gaps.",
    },
    {
        "type": "mc",
        "q": "On a military network, every document carries a classification label and every user holds a clearance. The operating system alone decides access, and not even a document's creator can share it with an uncleared user. Which access control model is this?",
        "choices": ["Discretionary access control", "Role-based access control", "Mandatory access control", "Rule-based access control"],
        "answer": 2,
        "explain": "Mandatory access control (MAC) uses labels and clearances enforced by the operating system/policy — users, even resource owners, cannot override it. Military and other classified systems (and SELinux) are the classic examples. In DAC the owner could share the file at will.",
    },
    {
        "type": "mc",
        "q": "A user creates a spreadsheet on the file server and personally sets permissions so only two teammates can edit it. Which access control model allows this?",
        "choices": ["Mandatory access control", "Discretionary access control", "Attribute-based access control", "Rule-based access control"],
        "answer": 1,
        "explain": "Discretionary access control (DAC) puts access decisions in the hands of each resource's owner, who grants or denies access at their discretion — exactly how standard NTFS/Linux file permissions work. Under MAC, the system's labels, not the owner, would decide.",
    },
    {
        "type": "mc",
        "q": "A hospital grants access by job function: everyone assigned the 'Nurse' role automatically receives the same set of permissions, and a user's access changes when their role assignment changes. Which model is this?",
        "choices": ["Role-based access control", "Discretionary access control", "Mandatory access control", "Attribute-based access control"],
        "answer": 0,
        "explain": "Role-based access control (RBAC) attaches permissions to job roles rather than individuals; placing a user in a role grants the role's permissions. It is consistent and auditable, and it simplifies provisioning and reviews compared with per-user grants.",
    },
    {
        "type": "mc",
        "q": "A firewall applies the same ordered list of allow/deny entries to every connection, no matter which user generates the traffic. Which access control model does this represent?",
        "choices": ["Discretionary access control", "Role-based access control", "Attribute-based access control", "Rule-based access control"],
        "answer": 3,
        "explain": "Rule-based access control applies predefined, system-wide rules to everyone regardless of identity — firewall ACLs are the textbook example. RBAC (role-based) instead keys on who the user is via their job role; here identity is irrelevant to the decision.",
    },
    {
        "type": "mc",
        "q": "Access to a finance application is granted only when the user is in the Finance department, on a corporate-managed device that passes a health check, connecting from an approved country, during business hours. Which model evaluates all of these conditions together?",
        "choices": ["Rule-based access control", "Attribute-based access control", "Discretionary access control", "Mandatory access control"],
        "answer": 1,
        "explain": "Attribute-based access control (ABAC) combines attributes of the user (department), the resource, and the environment (device health, location, time) into fine-grained, context-aware decisions. It is the most granular of the models — multiple combined attributes is the giveaway.",
    },
    {
        "type": "mc",
        "q": "A retail company configures cashier accounts so they can only log on between 8 a.m. and 10 p.m., matching store hours. What is the PRIMARY security benefit?",
        "choices": [
            "It prevents cashiers from reusing passwords across systems",
            "Stolen cashier credentials cannot be used during the blocked hours, shrinking the attack window",
            "It guarantees least privilege for all cashier accounts",
            "It eliminates the need for de-provisioning",
        ],
        "answer": 1,
        "explain": "Time-of-day restrictions limit when an account can authenticate, so even valid stolen credentials fail outside the allowed window — attackers favor off-hours activity. They complement but do not replace least privilege, password policy, or de-provisioning.",
    },
    {
        "type": "mc",
        "q": "A new junior analyst is given read access to only the two dashboards his job requires, rather than the full reporting suite 'in case he needs it later.' Which principle is being applied?",
        "choices": ["Least privilege", "Separation of duties", "Federation", "Identity proofing"],
        "answer": 0,
        "explain": "Least privilege grants every user, account, and process only the minimum access required for the job — nothing speculative. It limits the blast radius if the account is phished or misused, and it underpins JIT permissions, role design, and access reviews.",
    },
    {
        "type": "mc",
        "q": "When tuning a fingerprint reader, an administrator wants the metric that indicates the rate at which UNAUTHORIZED users are incorrectly granted access. Which metric is that?",
        "choices": ["False rejection rate (FRR)", "Crossover error rate (CER)", "False acceptance rate (FAR)", "Failure to enroll rate"],
        "answer": 2,
        "explain": "The false acceptance rate (FAR) measures impostors wrongly accepted — the security-critical error. FRR measures legitimate users wrongly rejected (a usability problem), and CER is the point where FAR equals FRR; a lower CER indicates a more accurate biometric system overall.",
    },
    {
        "type": "mc",
        "q": "Employees authenticate with a password plus a six-digit code from an authenticator app on their phones that changes every 30 seconds. The app is an example of which MFA implementation?",
        "choices": ["Hard authentication token", "Soft authentication token", "Security key", "Biometric"],
        "answer": 1,
        "explain": "An authenticator app generating time-based one-time passwords (TOTP) is a soft (software-based) token. A hard token is a dedicated physical device such as an OTP key fob or smart card, and a security key is a physical FIDO2/WebAuthn device — neither is an app.",
    },
    {
        "type": "mc",
        "q": "An organization wants MFA that resists phishing: even if a user is lured to a convincing fake login page, the second factor should not work there. Which implementation BEST meets this need?",
        "choices": ["SMS one-time codes", "TOTP authenticator app", "FIDO2 security key", "Security questions"],
        "answer": 2,
        "explain": "FIDO2/WebAuthn security keys sign challenges cryptographically bound to the legitimate site's origin, so a look-alike phishing site cannot obtain a usable response — they are the phishing-resistant option. SMS and TOTP codes can be phished in real time and relayed; security questions are weakest of all.",
    },
    {
        "type": "mc",
        "q": "A user authenticates with a smart card and a PIN. Which factor combination is this?",
        "choices": [
            "Something you have and something you know",
            "Something you know and something you are",
            "Something you have and somewhere you are",
            "Two instances of something you know",
        ],
        "answer": 0,
        "explain": "The smart card is a possession factor (something you have) and the PIN is a knowledge factor (something you know) — two different categories, so this is true multifactor authentication. Count categories, not credentials: password + PIN would be two of the same factor.",
    },
    {
        "type": "mc",
        "q": "A conditional-access policy adds the user's GPS-verified location as evidence during login, blocking authentication attempts from outside approved regions. Which authentication factor is the location?",
        "choices": ["Something you know", "Something you have", "Something you are", "Somewhere you are"],
        "answer": 3,
        "explain": "Location-based evidence — GPS, IP address range, geofencing — is the 'somewhere you are' factor. It is typically used to supplement other factors or feed risk-based/conditional access decisions rather than serve as the sole proof of identity.",
    },
    {
        "type": "mc",
        "q": "According to current NIST guidance, which password attribute contributes MOST to password strength?",
        "choices": ["Mandatory special characters", "Length", "Requiring a change every 30 days", "Using the same strong password everywhere"],
        "answer": 1,
        "explain": "Length is the dominant strength factor — each added character multiplies the search space, which is why long passphrases beat short complex strings. Forced composition rules yield predictable patterns, frequent expiration breeds incremental passwords, and reuse anywhere is always wrong.",
    },
    {
        "type": "mc",
        "q": "Why does a password history setting often need to be paired with a MINIMUM password age?",
        "choices": [
            "Minimum age forces users to change passwords more frequently",
            "Without it, users can rapidly change passwords repeatedly to flush the history and return to an old favorite",
            "Minimum age increases password complexity automatically",
            "History settings expire unless an age policy renews them",
        ],
        "answer": 1,
        "explain": "Password history blocks recent passwords from being reused, but without a minimum age a user can burn through many quick changes in minutes to push the old favorite out of the history list and set it again. Minimum age forces each new password to be kept for a while, defeating the trick.",
    },
    {
        "type": "mc",
        "q": "An attacker takes username/password pairs leaked in a breach of an unrelated website and tries them against your company's webmail, succeeding for several employees. Which password best-practice violation made this credential-stuffing attack work?",
        "choices": ["Password reuse", "Insufficient password length", "Missing complexity requirements", "No password expiration policy"],
        "answer": 0,
        "explain": "Credential stuffing works only because users reuse the same password across sites — one breached site unlocks every account sharing that credential. Length, complexity, and expiration settings do not help if the exact password is already known; prohibiting reuse (unique passwords per site) is the countermeasure.",
    },
    {
        "type": "mc",
        "q": "An organization wants every employee to have a long, random, unique password for each of dozens of SaaS accounts without writing them down. Which tool BEST enables this?",
        "choices": ["A password manager", "Single sign-on federation for every site", "A password expiration policy", "Shared team credential spreadsheets"],
        "answer": 0,
        "explain": "A password manager generates, encrypts, stores, and fills strong unique passwords, so users only remember one master password (ideally protected by MFA). It makes non-reuse practical, containing any single site breach. Spreadsheets are insecure, and expiration does nothing for uniqueness.",
    },
    {
        "type": "mc",
        "q": "A company replaces passwords entirely: users sign in with a passkey where the device's biometric unlocks a private key that signs the site's challenge. Which statement about this passwordless approach is TRUE?",
        "choices": [
            "It still transmits a shared secret that the server must store",
            "There is no reusable shared secret for attackers to phish or breach from the server",
            "It cannot be combined with multifactor authentication",
            "It requires users to memorize longer secrets than passwords",
        ],
        "answer": 1,
        "explain": "Passwordless/FIDO2 authentication is public-key based: the server stores only a public key, and the private key signs challenges locally after a biometric or PIN unlock. No shared secret exists to phish, intercept, or steal in a database breach — and device + biometric is itself multifactor.",
    },
    {
        "type": "mc",
        "q": "Administrators at a company hold no standing admin rights. When a change ticket is approved, elevated permissions are granted for the duration of the task and automatically removed afterward. Which PAM capability is this?",
        "choices": ["Password vaulting", "Ephemeral credentials", "Just-in-time permissions", "Attestation"],
        "answer": 2,
        "explain": "Just-in-time (JIT) permissions grant elevated rights only on request, for a specific task and limited time, then revoke them automatically — least privilege applied to time. An attacker who compromises the admin's account between tasks gets no admin rights at all.",
    },
    {
        "type": "mc",
        "q": "Privileged account passwords are stored in a hardened encrypted repository. Admins must check a credential out with MFA, every use is logged, and the password is automatically rotated when checked back in. Which PAM tool is described?",
        "choices": ["Password vaulting", "Just-in-time permissions", "A password manager for end users", "Federation"],
        "answer": 0,
        "explain": "Password vaulting centralizes privileged credentials in an encrypted vault with check-out/check-in workflows, full usage auditing, and automatic rotation — nobody 'knows' the root password day-to-day. An end-user password manager protects personal logins, not shared privileged accounts with brokered access.",
    },
    {
        "type": "mc",
        "q": "A cloud automation pipeline requests credentials at run time; each credential is generated on demand and automatically expires 15 minutes later. Which PAM concept does this illustrate?",
        "choices": ["Password reuse", "Ephemeral credentials", "Discretionary access control", "Identity proofing"],
        "answer": 1,
        "explain": "Ephemeral credentials are temporary, short-lived credentials created on demand that expire automatically. Because they self-destruct in minutes, stolen ones quickly become useless and no long-lived secrets are left behind to leak or be forgotten in scripts.",
    },
    {
        "type": "mc",
        "q": "In a SAML-based federated login, which component authenticates the user and issues the signed assertion?",
        "choices": ["The service provider", "The identity provider", "The LDAP client", "The password vault"],
        "answer": 1,
        "explain": "The identity provider (IdP) authenticates the user and issues the digitally signed SAML assertion; the service provider (SP) validates the signature and grants access based on it. The user's password is only ever entered at the IdP, never at the SP.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Requiring a password plus a PIN counts as multifactor authentication.",
        "answer": False,
        "explain": "A password and a PIN are both knowledge factors — something you know — so this is two credentials from one category, which is still single-factor. MFA requires proofs from two or more different categories, such as a password (know) plus a security key (have).",
    },
    {
        "type": "tf",
        "q": "True or False: OAuth is primarily an authentication protocol used to prove a user's identity to a website.",
        "answer": False,
        "explain": "OAuth is an authorization framework for delegated access — it governs what an application may do with a user's resources via scoped tokens. Proving identity is authentication, handled by SAML or by OpenID Connect, which adds an identity layer on top of OAuth 2.0.",
    },
    {
        "type": "tf",
        "q": "True or False: Under mandatory access control, a file's owner can grant any user access at their own discretion.",
        "answer": False,
        "explain": "That describes discretionary access control. Under MAC, the operating system enforces access using classification labels and clearances, and not even the resource's owner or creator can override the policy — which is why classified environments use it.",
    },
    {
        "type": "tf",
        "q": "True or False: A lower crossover error rate (CER) indicates a more accurate biometric system.",
        "answer": True,
        "explain": "The CER is the point where the false acceptance rate equals the false rejection rate; the lower that crossover point, the fewer errors of both kinds the system makes. Comparing CERs is the standard way to compare overall biometric accuracy across products.",
    },
    {
        "type": "tf",
        "q": "True or False: Current NIST guidance recommends forcing all users to change their passwords every 60 to 90 days as a best practice.",
        "answer": False,
        "explain": "Modern NIST guidance (SP 800-63B) drops routine periodic expiration because it drives predictable incremental passwords (Password1 → Password2). Instead, require a change when compromise is known or suspected, favor length, and screen candidates against breached-password lists.",
    },
    {
        "type": "tf",
        "q": "True or False: Modern NIST guidance emphasizes password length over mandatory complexity rules, because forced composition requirements (must include symbols, numbers, etc.) lead users to predictable patterns.",
        "answer": True,
        "explain": "Length is the dominant strength factor, while forced complexity rules produce predictable substitutions like 'P@ssw0rd1!'. NIST SP 800-63B therefore favors long passphrases and screening against known-breached password lists over mandatory composition rules.",
    },
    {
        "type": "tf",
        "q": "True or False: An account that remains active after its owner has left the organization is called an orphaned account and should be caught by de-provisioning processes and access reviews.",
        "answer": True,
        "explain": "Orphaned accounts hold valid credentials and real permissions with nobody watching them, making them prime attacker targets. Prompt de-provisioning at offboarding prevents them, and periodic attestation/access reviews catch any that slip through.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "LDAP secured with SSL/TLS (LDAPS) uses TCP port ______. (type the number)",
        "answers": ["636"],
        "explain": "LDAPS wraps directory traffic in SSL/TLS on TCP port 636; plain, unencrypted LDAP uses port 389 and exposes queries and simple-bind credentials in cleartext. Always prefer LDAPS (or LDAP with StartTLS) in production directories.",
    },
    {
        "type": "fill",
        "q": "The XML-based standard that carries signed authentication assertions from an identity provider to a service provider in federated SSO is ______. (type the abbreviation)",
        "answers": ["saml", "security assertions markup language", "security assertion markup language"],
        "explain": "SAML (Security Assertions Markup Language) is the XML-based protocol of classic browser-based federated SSO: the IdP authenticates the user and sends a digitally signed assertion that the SP validates before granting access.",
    },
    {
        "type": "fill",
        "q": "Verifying a person's real-world identity — for example by checking a government ID — before issuing them credentials is called identity ______. (type your answer)",
        "answers": ["proofing", "identity proofing"],
        "explain": "Identity proofing establishes that a person is who they claim to be at enrollment time, before any account or credential exists. Weak proofing (for example, at a help desk password reset) is how many account-takeover attacks begin.",
    },
    {
        "type": "fill",
        "q": "The principle of granting every user and process only the minimum access required to do its job is called least ______. (type your answer)",
        "answers": ["privilege", "least privilege"],
        "explain": "Least privilege limits every account to the minimum permissions its function requires, containing the damage from phishing, malware, or insider misuse. It is the rationale behind role design, JIT permissions, and periodic access reviews.",
    },
    {
        "type": "fill",
        "q": "The PAM approach in which admin rights are granted only when needed, for a limited time, and then automatically revoked is called ______ permissions. (type your answer)",
        "answers": ["just-in-time", "just in time", "jit"],
        "explain": "Just-in-time (JIT) permissions eliminate standing privilege: elevation is requested for a specific task, time-boxed, and revoked automatically. Outside those windows the admin's account holds no elevated rights for an attacker to steal.",
    },
    {
        "type": "fill",
        "q": "Temporary credentials that are generated on demand and expire automatically after a short time are called ______ credentials. (type your answer)",
        "answers": ["ephemeral", "ephemeral credentials"],
        "explain": "Ephemeral credentials are short-lived by design — cloud tokens, one-time certificates, temporary accounts — so theft yields something that stops working within minutes and no long-lived secrets accumulate in scripts or configuration files.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each access control model to its description.",
        "pairs": [
            ["Mandatory (MAC)", "OS enforces labels and clearances; owners cannot override"],
            ["Discretionary (DAC)", "Each resource's owner decides who gets access"],
            ["Role-based", "Permissions attached to job functions/groups"],
            ["Rule-based", "Same predefined rules applied to everyone regardless of identity"],
            ["Attribute-based (ABAC)", "Decisions combine user, resource, and environment attributes"],
        ],
        "explain": "MAC is centrally imposed via labels/clearances; DAC leaves decisions to owners; role-based keys on job function; rule-based applies identity-blind system rules like firewall ACLs; ABAC evaluates combined attributes (department, device, location, time) for the finest granularity.",
    },
    {
        "type": "match",
        "q": "Match each authentication factor category to its example.",
        "pairs": [
            ["Something you know", "A password or PIN"],
            ["Something you have", "A hardware security key"],
            ["Something you are", "A fingerprint scan"],
            ["Somewhere you are", "Login allowed only from an approved geographic region"],
        ],
        "explain": "Knowledge (password/PIN), possession (token, key, enrolled phone), inherence (biometrics), and location (GPS/IP/geofencing) are the four factor categories. True MFA combines two or more different categories, not two credentials from the same one.",
    },
    {
        "type": "match",
        "q": "Match each identity/SSO technology to its role.",
        "pairs": [
            ["LDAP", "Queries users and groups in a directory service (port 389/636)"],
            ["OAuth", "Delegated authorization via scoped access tokens"],
            ["SAML", "XML assertions from identity provider to service provider"],
            ["OpenID Connect", "Authentication layer built on top of OAuth 2.0"],
            ["Federation", "Trusting another organization's identity provider"],
        ],
        "explain": "LDAP is the directory query protocol; OAuth delegates authorization without password sharing; SAML carries XML authentication assertions for web SSO; OIDC adds identity on top of OAuth 2.0; federation is the cross-organization trust these protocols enable.",
    },
    {
        "type": "match",
        "q": "Match each privileged access / password tool to its description.",
        "pairs": [
            ["Just-in-time permissions", "Elevation granted per task, time-boxed, auto-revoked"],
            ["Password vaulting", "Privileged credentials checked out, audited, and rotated"],
            ["Ephemeral credentials", "Auto-expiring short-lived credentials issued on demand"],
            ["Password manager", "Generates and stores unique passwords for a user's accounts"],
            ["Passwordless", "Replaces the shared secret with key-based proof such as passkeys"],
        ],
        "explain": "JIT, vaulting, and ephemeral credentials are the three PAM tools that eliminate standing privilege. A password manager serves ordinary users' many accounts, and passwordless authentication removes the password (shared secret) entirely in favor of public-key proofs.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps of a SAML-based federated SSO login in order.",
        "items": [
            "User requests access to the application (service provider)",
            "Service provider redirects the user's browser to the identity provider",
            "User authenticates at the identity provider",
            "Identity provider sends a signed SAML assertion back for the service provider",
            "Service provider validates the assertion and grants access",
        ],
        "explain": "The SP never sees the user's password: it redirects to the IdP, the user authenticates there (ideally with MFA), and the IdP returns a digitally signed assertion that the SP validates before granting access. This is the classic browser-based SAML flow.",
    },
    {
        "type": "order",
        "q": "Arrange the identity lifecycle activities in their typical order.",
        "items": [
            "Identity proofing verifies who the person really is",
            "Provisioning creates the account and grants role-appropriate access",
            "Permissions are adjusted as the user's role changes, revoking old access",
            "Periodic attestation certifies that access rights are still appropriate",
            "De-provisioning disables the account and revokes all access at departure",
        ],
        "explain": "Proof the identity first, then provision the account with least-privilege access. During employment, revoke old permissions at role changes (preventing privilege creep) and recertify access through attestation. At departure, de-provision promptly so no orphaned account remains.",
    },
]
