TOPIC = {
    "id": "4.8",
    "domain": 4,
    "title": "Explain appropriate incident response activities.",
    "short": "Incident Response",
}

TERMS = [
    ("Incident", "An event that actually or imminently jeopardizes the confidentiality, integrity, or availability of systems or data — more than a mere observable event"),
    ("Incident response plan", "Documented procedures, roles, and communication paths for handling incidents; written and maintained during preparation"),
    ("Preparation", "Everything done before an incident: IR plan, playbooks, team roles, communication plan, jump bag/tools, training, and exercises"),
    ("Detection", "Recognizing that a potential incident may have occurred — via SIEM/IDS/EDR alerts, user reports, or external notification"),
    ("Analysis", "Investigating a detected event to confirm it is a real incident and determine its scope, severity, and priority; weeds out false positives"),
    ("Containment", "Limiting damage and stopping spread: isolate hosts, disable switch ports/accounts, block attacker IPs — done before removal"),
    ("Eradication", "Removing the cause of the incident: delete malware and persistence, reset breached credentials, patch the exploited vulnerability, reimage"),
    ("Recovery", "Restoring normal operations: rebuild systems, restore from clean backups, verify hardening, and monitor closely after return to production"),
    ("Lessons learned", "Post-incident review held soon after recovery; produces the final report and improvements that feed back into preparation"),
    ("Training", "Preparing the IR team on roles/tools/playbooks and teaching general users to recognize and report suspicious activity"),
    ("Tabletop exercise", "Discussion-based walkthrough of an incident scenario; no production systems touched; low cost; validates plan, roles, and decisions"),
    ("Simulation", "Hands-on exercise mimicking a real incident (e.g., mock phishing campaign); tests actual detection and response; must be scoped to avoid disruption"),
    ("Root cause analysis", "Determining the underlying reason an incident could occur (e.g., unpatched appliance) rather than just the symptom, so fixes prevent recurrence"),
    ("Threat hunting", "Proactive, hypothesis-driven search for threats already in the environment that evaded automated detection; assumes breach; uses intel, IoCs, TTPs"),
    ("Indicators of compromise (IoC)", "Observable artifacts of an intrusion — file hashes, IP addresses, domains, registry keys — used to detect and hunt for threats"),
    ("Digital forensics", "Identification, collection, preservation, analysis, and presentation of digital evidence in a legally admissible manner"),
    ("Legal hold", "Formal notice (usually from legal counsel) to preserve all data potentially relevant to litigation; overrides normal retention and deletion schedules"),
    ("Chain of custody", "Unbroken documented record of evidence handling — who collected it, every transfer, and how it was stored; gaps can make evidence inadmissible"),
    ("Acquisition", "Collecting the evidence: bit-for-bit forensic imaging with hash verification, gathered in order of volatility, including live capture of RAM"),
    ("Order of volatility", "Collect the most short-lived data first: CPU registers/cache, then RAM and network state, then swap, then disk, then remote logs, then archival media"),
    ("Forensic image", "A bit-for-bit copy of storage media capturing every sector, including deleted files and slack space — not a simple file copy"),
    ("Write blocker", "Hardware or software that permits reading a drive but prevents any writes to it during acquisition, preserving evidence integrity"),
    ("Preservation", "Protecting evidence from alteration: write blockers, analyzing copies rather than originals, secure storage, and verified hashes"),
    ("Reporting (forensic)", "Documenting evidence, methods, tools, and findings reproducibly and in language non-technical audiences (executives, courts) can understand"),
    ("E-discovery", "The legal process of identifying, collecting, reviewing, and producing electronically stored information (ESI) for litigation or investigation"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A security team writes ransomware and phishing playbooks, assembles a forensic jump bag, and updates the incident response contact list — all while no incident is occurring. Which phase of the incident response process is this?",
        "choices": ["Detection", "Preparation", "Recovery", "Lessons learned"],
        "answer": 1,
        "explain": "Preparation is everything done before an incident exists: the IR plan, playbooks, team roles, communication plans, tooling, and training. Detection begins only when a potential incident is noticed, and recovery and lessons learned occur after one has been handled.",
    },
    {
        "type": "mc",
        "q": "Place them in order: which is the correct sequence of the SY0-701 incident response process?",
        "choices": [
            "Preparation, Detection, Analysis, Containment, Eradication, Recovery, Lessons learned",
            "Preparation, Analysis, Detection, Eradication, Containment, Recovery, Lessons learned",
            "Detection, Preparation, Containment, Analysis, Recovery, Eradication, Lessons learned",
            "Preparation, Detection, Containment, Analysis, Recovery, Eradication, Lessons learned",
        ],
        "answer": 0,
        "explain": "The seven phases run Preparation, Detection, Analysis, Containment, Eradication, Recovery, Lessons learned. Analysis confirms and scopes what detection surfaced, containment comes before eradication (stop the spread, then remove the cause), and recovery precedes the post-incident review.",
    },
    {
        "type": "mc",
        "q": "A SIEM correlation rule fires on unusual authentication activity, and a user simultaneously reports a suspicious email. In the incident response process, these alerts and reports represent which phase?",
        "choices": ["Analysis", "Detection", "Containment", "Threat hunting"],
        "answer": 1,
        "explain": "Detection is the recognition that a potential incident may have occurred — SIEM/IDS/EDR alerts, user reports, or outside notification. Analysis is the follow-on investigation that confirms and scopes it. Threat hunting is proactive searching without any alert at all.",
    },
    {
        "type": "mc",
        "q": "An analyst reviews a fired alert to determine whether an actual compromise occurred, which systems and data are affected, and how severe the incident is. Which phase is being performed?",
        "choices": ["Detection", "Eradication", "Analysis", "Preparation"],
        "answer": 2,
        "explain": "Analysis (triage/investigation) confirms whether a detected event is a real incident, rules out false positives, and establishes scope, severity, and priority. Detection is merely the alert or report arriving; eradication removes the cause after containment.",
    },
    {
        "type": "mc",
        "q": "EDR confirms active ransomware on a workstation that is encrypting files on network shares. What should the responder do FIRST?",
        "choices": [
            "Reimage the workstation from a golden image",
            "Restore the encrypted shares from backup",
            "Isolate the workstation from the network",
            "Hold a lessons-learned meeting",
        ],
        "answer": 2,
        "explain": "Containment comes first once an active incident is confirmed: isolating the host (disconnect, disable the switch port, EDR quarantine) stops the spread while preserving its state. Reimaging is eradication and restoring backups is recovery — both come after containment.",
    },
    {
        "type": "mc",
        "q": "A responder disables the switch port of an infected server and blocks the attacker's IP address at the firewall to stop lateral movement. Which incident response phase do these actions belong to?",
        "choices": ["Containment", "Eradication", "Recovery", "Detection"],
        "answer": 0,
        "explain": "Isolating hosts, disabling ports/accounts, and blocking attacker addresses limit damage and stop spread — that is containment. Eradication would remove the malware and its cause; recovery would restore normal operations afterward.",
    },
    {
        "type": "mc",
        "q": "After isolating a compromised server, the team deletes the attacker's web shell, removes a rogue admin account, and patches the vulnerability that was exploited to gain entry. Which phase is this?",
        "choices": ["Containment", "Recovery", "Analysis", "Eradication"],
        "answer": 3,
        "explain": "Eradication removes the cause of the incident: malware and persistence mechanisms, attacker accounts, and the exploited vulnerability. Containment (already done) only isolated the threat, and recovery is the later restoration of normal operations.",
    },
    {
        "type": "mc",
        "q": "The team restores data from backups verified to predate the compromise, returns rebuilt servers to production, and monitors them closely for signs of reinfection. Which phase is this?",
        "choices": ["Recovery", "Eradication", "Containment", "Preparation"],
        "answer": 0,
        "explain": "Recovery restores systems to normal operation — rebuilding, restoring from clean backups, verifying hardening, and monitoring closely afterward, since attackers often return right after restoration. Eradication was the earlier removal of the malware and root cause.",
    },
    {
        "type": "mc",
        "q": "Two weeks after a major incident is closed, the response team meets to review what went well, what failed, and how the playbooks should change; a final report is written. Which phase is this?",
        "choices": ["Analysis", "Lessons learned", "Recovery", "Root cause analysis"],
        "answer": 1,
        "explain": "Lessons learned is the post-incident review that produces the final report and concrete improvements. Root cause analysis is one activity performed within it, but the review meeting and report as a whole are the lessons learned phase. Its output feeds back into preparation.",
    },
    {
        "type": "mc",
        "q": "The improvements identified during a lessons-learned review — updated playbooks, new detection rules, additional training — feed directly back into which phase of the incident response cycle?",
        "choices": ["Preparation", "Detection", "Containment", "Recovery"],
        "answer": 0,
        "explain": "Incident response is a cycle: lessons learned outputs (revised plans, playbooks, controls, training) flow back into preparation, improving readiness for the next incident. That feedback loop is why the process is drawn as a circle rather than a line.",
    },
    {
        "type": "mc",
        "q": "New members of the incident response team practice forensic imaging and EDR quarantine procedures, while all employees complete a course on recognizing and reporting phishing. Which IR activity does this describe?",
        "choices": ["Testing", "Threat hunting", "Training", "E-discovery"],
        "answer": 2,
        "explain": "Training covers both the IR team (roles, tools, playbook execution, evidence handling) and general users (recognize and report suspicious activity). Testing exercises the plan itself via tabletops and simulations rather than teaching individual skills.",
    },
    {
        "type": "mc",
        "q": "A facilitator presents a hypothetical data-breach scenario in a conference room, and the response team verbally walks through the decisions, notifications, and playbook steps they would take. No systems are touched. What type of exercise is this?",
        "choices": ["Simulation", "Tabletop exercise", "Threat hunt", "Root cause analysis"],
        "answer": 1,
        "explain": "A tabletop exercise is a discussion-based walkthrough of a scenario — low cost, zero risk to production, and good for validating roles, decision-making, and communication paths. A simulation is hands-on and actually exercises tools and technical response.",
    },
    {
        "type": "mc",
        "q": "To test real-world readiness, the security team launches a mock phishing campaign and injects simulated malware alerts that responders must actually detect, contain, and investigate with their production tools. What type of exercise is this?",
        "choices": ["Tabletop exercise", "Simulation", "Legal hold", "Lessons learned"],
        "answer": 1,
        "explain": "A simulation is a hands-on exercise mimicking a real incident — it tests actual detection tooling, technical skills, and response speed. It is more realistic and more expensive than a tabletop and must be carefully scoped to avoid disrupting production.",
    },
    {
        "type": "mc",
        "q": "Which is the PRIMARY advantage of a tabletop exercise over a simulation?",
        "choices": [
            "It proves detection tooling works end to end",
            "It tests responders' hands-on technical speed",
            "It is low cost and poses no risk to production systems",
            "It generates real indicators of compromise for hunting",
        ],
        "answer": 2,
        "explain": "Tabletops are discussion-based, so they are cheap, easy to schedule, and touch no systems — zero operational risk. The trade-off is realism: only a simulation exercises the actual tools, telemetry, and hands-on skills of the responders.",
    },
    {
        "type": "mc",
        "q": "After a ransomware incident, investigators determine the infection was possible because an internet-facing VPN appliance had been missing a critical patch for two years. Identifying the unpatched appliance as the underlying issue is an example of what?",
        "choices": ["Root cause analysis", "Chain of custody", "Containment", "E-discovery"],
        "answer": 0,
        "explain": "Root cause analysis finds the underlying reason the incident could occur — the unpatched appliance — rather than just the symptom (the ransomware). Fixing only the symptom leaves the entry point open and invites the identical incident again.",
    },
    {
        "type": "mc",
        "q": "Why is removing the malware alone insufficient if root cause analysis is skipped?",
        "choices": [
            "Malware cannot be removed without a legal hold",
            "The underlying weakness remains and the same incident can recur",
            "Removal invalidates the chain of custody",
            "Backups cannot be restored until the RCA report is filed",
        ],
        "answer": 1,
        "explain": "Eradicating malware treats the symptom. If the root cause — an unpatched flaw, a misconfiguration, a process failure — is not identified and fixed, the same or another attacker can walk through the same door. RCA-driven corrective action is what prevents recurrence.",
    },
    {
        "type": "mc",
        "q": "With no alerts pending, an analyst forms the hypothesis that an attacker with stolen credentials would create scheduled tasks for persistence, then searches endpoint telemetry and logs for that behavior. Which activity is this?",
        "choices": ["Detection", "Incident analysis", "Threat hunting", "Tabletop exercise"],
        "answer": 2,
        "explain": "Threat hunting is the proactive, hypothesis-driven search for threats that have evaded automated detection — it assumes breach and goes looking without waiting for an alert. Detection and analysis are reactive steps triggered by an alert or report.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST distinguishes threat hunting from the incident response process?",
        "choices": [
            "Threat hunting is proactive and hypothesis-driven; incident response is reactive and begins after detection",
            "Threat hunting is fully automated; incident response is manual",
            "Threat hunting occurs only after eradication; incident response occurs before",
            "Threat hunting is performed by legal counsel; incident response by analysts",
        ],
        "answer": 0,
        "explain": "Hunters assume compromise and search before any alert fires, guided by hypotheses, threat intelligence, IoCs, and attacker TTPs. Incident response is reactive — it starts when detection surfaces a potential incident. Hunting is human-driven, not automated; automation is what it compensates for.",
    },
    {
        "type": "mc",
        "q": "During a threat hunt, analysts search the environment for known-malicious file hashes, IP addresses, and domains published in a threat intelligence feed. What are these artifacts called?",
        "choices": ["Playbooks", "Indicators of compromise", "Chain of custody records", "Exposure factors"],
        "answer": 1,
        "explain": "Indicators of compromise (IoCs) are observable artifacts of an intrusion — hashes, IPs, domains, registry keys — used to detect and hunt for threats. Playbooks are response procedures, and chain-of-custody records document evidence handling.",
    },
    {
        "type": "mc",
        "q": "A company is sued, and its general counsel issues a notice requiring preservation of all email and files related to the dispute, suspending the normal 90-day mailbox auto-deletion for the affected data. What is this notice called?",
        "choices": ["E-discovery", "Chain of custody", "Legal hold", "Data retention policy"],
        "answer": 2,
        "explain": "A legal hold (litigation hold) requires preservation of all data potentially relevant to litigation and overrides normal retention and deletion schedules. E-discovery is the later process of finding and producing that data; destroying held data is spoliation of evidence.",
    },
    {
        "type": "mc",
        "q": "A form accompanying a seized hard drive lists who collected it, the date and time, each person who has handled it since, and where it has been stored. What does this documentation establish?",
        "choices": ["Order of volatility", "Chain of custody", "Legal hold", "Root cause analysis"],
        "answer": 1,
        "explain": "The chain of custody is the unbroken documented record of evidence handling — collection, every transfer, storage, and analysis. It proves the evidence presented in court is the same unaltered evidence collected; any gap invites a challenge to its admissibility.",
    },
    {
        "type": "mc",
        "q": "A forensic examiner creates a bit-for-bit image of a suspect drive, then computes SHA-256 hashes of the original and the copy. What does a matching hash pair prove?",
        "choices": [
            "The drive contained no malware",
            "The image is an exact, unaltered copy of the original",
            "The drive was properly degaussed",
            "The evidence is exempt from legal hold",
        ],
        "answer": 1,
        "explain": "Matching hashes demonstrate the forensic image is bit-identical to the original; re-verifying the hash later proves the evidence has not changed since acquisition. Hashing provides integrity proof — it says nothing about malware presence or legal status.",
    },
    {
        "type": "mc",
        "q": "During evidence acquisition on a running system, which data should be collected FIRST?",
        "choices": [
            "Contents of RAM and active network connections",
            "Files on the hard disk",
            "Archived backup tapes",
            "Logs stored on a remote syslog server",
        ],
        "answer": 0,
        "explain": "The order of volatility says to collect the most short-lived data first. RAM, process tables, and active connections vanish at power-off; disk contents persist, remote logs persist longer, and archival media is the least volatile of all.",
    },
    {
        "type": "mc",
        "q": "Why would an examiner perform a live acquisition of a running computer rather than powering it down and imaging the disk?",
        "choices": [
            "Live acquisition avoids the need for a chain of custody",
            "Powering off destroys volatile evidence such as RAM contents and encryption keys",
            "Disk images cannot be hashed after shutdown",
            "Live acquisition is required by e-discovery rules",
        ],
        "answer": 1,
        "explain": "Powering off erases everything volatile: RAM-resident malware, running process state, active connections, and decryption keys for mounted encrypted volumes. Live acquisition captures that evidence first. Chain of custody and hashing apply either way.",
    },
    {
        "type": "mc",
        "q": "A forensic technician attaches a suspect drive through a device that allows reading but physically prevents any writes to the drive during imaging. Which forensic activity does this device support?",
        "choices": ["Reporting", "E-discovery", "Preservation", "Detection"],
        "answer": 2,
        "explain": "A write blocker preserves evidence integrity by preventing any modification of the original media during acquisition. Preservation also includes analyzing copies rather than originals, secure evidence storage, and hash verification.",
    },
    {
        "type": "mc",
        "q": "A forensic report is being prepared for possible use in court. Which characteristic is MOST important?",
        "choices": [
            "It documents methods and findings so another examiner could reproduce the results, in language non-experts can understand",
            "It includes only raw log output with no interpretation",
            "It is kept verbal to avoid discovery by opposing counsel",
            "It speculates about the attacker's identity to aid prosecution",
        ],
        "answer": 0,
        "explain": "Forensic reporting must record evidence, tools, methods, findings, and conclusions with enough rigor to be reproducible, while remaining understandable to judges, juries, and executives. It sticks to supportable facts — speculation and undocumented verbal findings undermine admissibility.",
    },
    {
        "type": "mc",
        "q": "In response to litigation, a company must identify, collect, review, and produce relevant emails, chat logs, and documents (including metadata) for opposing counsel. What is this process called?",
        "choices": ["Threat hunting", "E-discovery", "Chain of custody", "Sanitization"],
        "answer": 1,
        "explain": "E-discovery (electronic discovery) is the legal process of identifying, collecting, reviewing, and producing electronically stored information (ESI) for litigation or investigation. It works hand-in-hand with the legal hold that preserved the data in the first place.",
    },
    {
        "type": "mc",
        "q": "Which pairing of forensic activity to description is INCORRECT?",
        "choices": [
            "Acquisition — creating a bit-for-bit image of the media",
            "Legal hold — notice to preserve data relevant to litigation",
            "Chain of custody — proactive search for threats that evaded detection",
            "E-discovery — producing electronically stored information for legal proceedings",
        ],
        "answer": 2,
        "explain": "The proactive search for threats that evaded automated detection is threat hunting, not chain of custody. Chain of custody is the documented, unbroken record of who has handled evidence. The other three pairings are correct.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: In the incident response process, eradication should be performed before containment.",
        "answer": False,
        "explain": "Containment comes first: isolate the threat and stop the spread, then eradicate the cause. Attempting to remove malware while the attack is still spreading (or the attacker still has access) lets the damage continue and can tip off the attacker.",
    },
    {
        "type": "tf",
        "q": "True or False: A tabletop exercise involves hands-on response actions against production systems.",
        "answer": False,
        "explain": "A tabletop is discussion-based — the team talks through a scenario without touching any systems, which is exactly why it is low cost and risk-free. Hands-on exercises that mimic real incidents with real tools are simulations.",
    },
    {
        "type": "tf",
        "q": "True or False: A legal hold overrides normal data retention and automatic deletion schedules for the data it covers.",
        "answer": True,
        "explain": "Once a legal hold is issued, potentially relevant data must be preserved regardless of routine retention rules — auto-purges, log rotation, and scheduled destruction must be suspended for it. Destroying held data can constitute spoliation of evidence and bring court sanctions.",
    },
    {
        "type": "tf",
        "q": "True or False: Threat hunting begins only after an automated alert notifies the team of a potential incident.",
        "answer": False,
        "explain": "That describes reactive detection. Threat hunting is proactive: hunters assume the environment may already be compromised and search on a hypothesis, using threat intelligence, IoCs, and TTPs — precisely to find what automated tooling failed to alert on.",
    },
    {
        "type": "tf",
        "q": "True or False: A gap in the chain of custody can render digital evidence inadmissible in court.",
        "answer": True,
        "explain": "The chain of custody must be unbroken — any interval where no one can account for the evidence lets opposing counsel argue it could have been altered, and the court may exclude it. Every transfer, handler, and storage location must be documented.",
    },
    {
        "type": "tf",
        "q": "True or False: Forensic analysis should be performed on a verified copy of the evidence, not on the original media.",
        "answer": True,
        "explain": "Preservation practice is to image the original (through a write blocker), verify the copy by hash, seal and store the original securely, and perform all analysis on the copy. This keeps the original pristine so its integrity can be demonstrated later.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "In the seven-phase incident response process, the phase between Analysis and Eradication — where the spread of the incident is stopped — is ______. (type your answer)",
        "answers": ["containment"],
        "explain": "Containment sits between analysis and eradication: once the incident is confirmed and scoped, the team isolates affected hosts, disables accounts, and blocks attacker infrastructure to limit damage before removing the cause.",
    },
    {
        "type": "fill",
        "q": "The documented, unbroken record of everyone who has collected, handled, or stored a piece of evidence is the chain of ______. (type your answer)",
        "answers": ["custody", "chain of custody"],
        "explain": "The chain of custody documents collection, every transfer, and storage of evidence with dates, times, and signatures. It proves the evidence presented later is the same unaltered evidence originally collected — gaps invite challenges to admissibility.",
    },
    {
        "type": "fill",
        "q": "The proactive, hypothesis-driven search for attackers who have evaded existing automated defenses is called threat ______. (type your answer)",
        "answers": ["hunting", "threat hunting"],
        "explain": "Threat hunting assumes breach: analysts form a hypothesis about attacker behavior and actively search logs, endpoint telemetry, and network data for evidence of it, guided by threat intelligence, IoCs, and TTPs — no alert required.",
    },
    {
        "type": "fill",
        "q": "A formal notice requiring the preservation of data relevant to current or anticipated litigation is a legal ______. (type your answer)",
        "answers": ["hold", "legal hold", "litigation hold"],
        "explain": "A legal hold, typically issued by legal counsel, suspends normal retention and deletion for potentially relevant data until the hold is released. Violating it — letting held data be destroyed — can constitute spoliation of evidence.",
    },
    {
        "type": "fill",
        "q": "Collecting RAM contents before disk contents because short-lived evidence disappears first follows the order of ______. (type your answer)",
        "answers": ["volatility", "order of volatility"],
        "explain": "The order of volatility ranks evidence from most to least perishable: CPU registers/cache, RAM and network state, swap/temp files, disk, remote logs, then archival media. Acquisition proceeds most-volatile-first so nothing is lost.",
    },
    {
        "type": "fill",
        "q": "A discussion-based incident response exercise in which the team verbally walks through a scenario without touching any systems is a ______ exercise. (type your answer)",
        "answers": ["tabletop", "table top", "table-top"],
        "explain": "A tabletop exercise is a facilitated scenario walkthrough — cheap, safe, and effective at validating the plan, roles, decisions, and communication paths. Its hands-on counterpart, the simulation, tests the actual tools and technical response.",
    },
    {
        "type": "fill",
        "q": "Determining the underlying reason an incident was able to occur — rather than just its symptom — is called ______ cause analysis. (type your answer)",
        "answers": ["root", "root cause"],
        "explain": "Root cause analysis digs past the symptom (malware on a server) to the underlying cause (an unpatched internet-facing appliance, a missing control). Performed with lessons learned, it drives the corrective actions that prevent recurrence.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each incident response phase to its activity.",
        "pairs": [
            ["Preparation", "Write playbooks and assemble the response team before any incident"],
            ["Containment", "Isolate the infected host to stop the spread"],
            ["Eradication", "Remove the malware and patch the exploited flaw"],
            ["Recovery", "Restore systems from clean backups and monitor closely"],
            ["Lessons learned", "Hold the post-incident review and update the plan"],
        ],
        "explain": "Preparation readies the team in advance; containment isolates; eradication removes the cause; recovery restores normal operations; lessons learned reviews the response and feeds improvements back into preparation.",
    },
    {
        "type": "match",
        "q": "Match each digital forensics term to its description.",
        "pairs": [
            ["Legal hold", "Notice to preserve data relevant to litigation"],
            ["Chain of custody", "Documented record of everyone who handled the evidence"],
            ["Acquisition", "Bit-for-bit imaging of media with hash verification"],
            ["Preservation", "Write blockers and analyzing copies to keep evidence unaltered"],
            ["E-discovery", "Producing electronically stored information for legal proceedings"],
        ],
        "explain": "Legal hold preserves relevant data; chain of custody documents handling; acquisition collects the evidence forensically; preservation keeps it unaltered; e-discovery identifies and produces ESI for litigation.",
    },
    {
        "type": "match",
        "q": "Match each readiness or investigation activity to its description.",
        "pairs": [
            ["Tabletop exercise", "Discussion-based walkthrough; no systems touched"],
            ["Simulation", "Hands-on mock incident using real tools"],
            ["Threat hunting", "Proactive, hypothesis-driven search for hidden compromises"],
            ["Root cause analysis", "Finding the underlying reason the incident could occur"],
            ["Training", "Teaching responders their roles and users to report suspicious activity"],
        ],
        "explain": "Tabletops validate the plan through discussion; simulations test real technical response; threat hunting proactively seeks what detection missed; RCA identifies the underlying cause; training builds the skills and awareness that make it all work.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the seven phases of the incident response process in the correct order.",
        "items": [
            "Preparation",
            "Detection",
            "Analysis",
            "Containment",
            "Eradication",
            "Recovery",
            "Lessons learned",
        ],
        "explain": "Preparation readies the organization; detection surfaces a potential incident; analysis confirms and scopes it; containment stops the spread; eradication removes the cause; recovery restores operations; lessons learned improves the plan — feeding back into preparation.",
    },
    {
        "type": "order",
        "q": "Arrange these evidence sources in the order they should be collected according to the order of volatility (most volatile first).",
        "items": [
            "CPU registers and cache",
            "RAM contents and active network connections",
            "Swap space and temporary files",
            "Data on the hard disk",
            "Logs on a remote monitoring server",
            "Archival backup media",
        ],
        "explain": "Collect the most perishable evidence first: CPU registers/cache vanish instantly, RAM and network state die at power-off, swap/temp files change constantly, disk data persists, remote logs persist longer, and archival backups are the least volatile.",
    },
]
