TOPIC = {
    "id": "5.1",
    "domain": 5,
    "title": "Summarize elements of effective security governance.",
    "short": "Security Governance",
}

TERMS = [
    ("Policy", "High-level, mandatory statement of management intent and expectations; technology-neutral and slow to change — the 'why/what' layer of governance"),
    ("Standard", "Mandatory, specific, measurable requirements that implement policy — e.g., minimum password length, approved encryption algorithms"),
    ("Procedure", "Mandatory step-by-step instructions for performing a task consistently — the 'how' layer of governance"),
    ("Guideline", "Recommended best practices and advice; the only NON-mandatory governance document type — flexible where judgment is acceptable"),
    ("Acceptable use policy (AUP)", "Policy defining what users may and may not do with organizational systems, networks, and data; typically signed during onboarding"),
    ("Information security policies", "The overarching set of management-approved rules protecting the confidentiality, integrity, and availability of information"),
    ("Business continuity (BC) policy", "Policy for keeping critical business operations running during and after a disruption — the broader discipline that contains DR"),
    ("Disaster recovery (DR) policy", "IT-focused subset of business continuity: restoring systems and data after a disaster — backups, recovery sites, RTO/RPO targets"),
    ("Incident response policy", "Policy defining how the organization prepares for, detects, reports, and responds to security incidents, including team roles and escalation"),
    ("SDLC policy", "Software development lifecycle policy — builds security into every development phase: requirements, design, coding, testing, deployment, maintenance"),
    ("Change management policy", "Policy requiring changes to systems to follow a formal request/approval/testing process so changes don't cause outages or vulnerabilities"),
    ("Password standard", "Mandatory password construction/handling requirements: minimum length, screening or complexity, history, lockout, hashed-and-salted storage"),
    ("Access control standard", "Mandatory requirements for granting, reviewing, and revoking access: least privilege, need-to-know, role-based assignment, periodic reviews"),
    ("Physical security standard", "Mandatory physical-protection requirements: badges, visitor handling, locks, access-control vestibules, camera coverage, server-room rules"),
    ("Encryption standard", "Mandatory list of approved algorithms, key lengths, and protocol versions (e.g., AES-256 at rest, TLS 1.2+ in transit) plus key management"),
    ("Change management procedure", "Ordered steps for a change: request, risk assessment/approval (often via CAB), scheduled window, implement with backout plan, verify, document"),
    ("Onboarding procedure", "Steps for bringing in a new hire: background screening, signing the AUP/NDA, least-privilege account provisioning, equipment, security training"),
    ("Offboarding procedure", "Steps for departure: promptly disable accounts and revoke access, recover assets, exit interview/NDA reminder; failures leave stale accounts"),
    ("Playbook", "Checklist-style, step-by-step response guide for one specific scenario or incident type (e.g., phishing); often automated via SOAR"),
    ("Regulatory consideration", "External governance driver: rules imposed and enforced by government regulators (e.g., HIPAA, SOX, GLBA) with fines for non-compliance"),
    ("Legal consideration", "External driver from the broader legal system: breach-notification duties, e-discovery/legal hold, contracts, liability, due care/due diligence"),
    ("Industry consideration", "Sector-specific requirements, including contractual standards that are not laws — PCI DSS for payment cards is the classic example"),
    ("Local/regional consideration", "Laws of a state, province, or region — e.g., CCPA (California) or state breach-notification statutes"),
    ("National consideration", "Country-level laws applying across an entire nation — e.g., HIPAA and SOX in the US"),
    ("Global consideration", "Requirements that follow the organization across borders — e.g., GDPR reaches any organization worldwide handling EU residents' data"),
    ("Monitoring and revision", "Treating governance documents as living documents: track compliance/effectiveness and revise on a schedule and after incidents, legal, business, or technology changes"),
    ("Board (of directors)", "Governance structure with ultimate accountability: sets strategic direction and risk appetite and provides top-level oversight of security"),
    ("Committee", "Smaller focused governance group with subject expertise (security steering, audit, risk committee) that reviews policy and makes recommendations"),
    ("Government entities", "Legislatures, regulators, and agencies acting as external governance by creating and enforcing law; the governing structure for the public sector"),
    ("Centralized governance", "A single central authority makes security decisions for the whole organization — consistent and uniform, but slower and less locally tailored"),
    ("Decentralized governance", "Decision authority distributed to business units or regions — faster and flexible, but risks inconsistent controls between units"),
    ("Owner", "Role ultimately accountable for a system or data set: decides classification, approves access, accepts risk"),
    ("Controller", "Organization/role that determines the purposes and means of processing personal data — the 'why and how' decision-maker (GDPR term)"),
    ("Processor", "Entity that processes personal data on behalf of, and on the instructions of, the controller — never decides the purpose of processing"),
    ("Custodian/steward", "Hands-on role for day-to-day handling and protection of data — implements controls, backups, and permissions per the owner's decisions"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A security document states: 'Employees are encouraged to use a password manager for personal accounts; consider a passphrase of four unrelated words.' Compliance is optional. What type of document is this?",
        "choices": [
            "Policy",
            "Standard",
            "Guideline",
            "Procedure",
        ],
        "answer": 2,
        "explain": "Guidelines are recommended best practices and advice — the only NON-mandatory governance document type. Policies, standards, and procedures are all mandatory; the words 'encouraged' and 'consider' signal a guideline.",
    },
    {
        "type": "mc",
        "q": "A document states that laptops must use AES-256 full-disk encryption and web servers must support TLS 1.2 or higher. What type of governance document is this?",
        "choices": [
            "Guideline",
            "Standard",
            "Policy",
            "Playbook",
        ],
        "answer": 1,
        "explain": "Specific, measurable, mandatory requirements — exact algorithms, key lengths, and protocol versions — belong to a standard (here, an encryption standard). Policies state high-level intent; the moment exact numbers and algorithms appear, think 'standard.'",
    },
    {
        "type": "mc",
        "q": "Which governance document provides mandatory, numbered step-by-step instructions for completing a specific task the same way every time?",
        "choices": [
            "Procedure",
            "Policy",
            "Guideline",
            "Standard",
        ],
        "answer": 0,
        "explain": "Procedures are detailed step-by-step instructions — the 'how' layer. Policies state intent, standards state specific requirements, and guidelines are optional recommendations. Step-by-step task instructions are a procedure.",
    },
    {
        "type": "mc",
        "q": "During orientation, a new employee signs a document describing permitted personal use of company internet, prohibited activities, and the company's right to monitor. What did the employee sign?",
        "choices": [
            "An encryption standard",
            "A disaster recovery plan",
            "A service level agreement",
            "An acceptable use policy (AUP)",
        ],
        "answer": 3,
        "explain": "The AUP defines what users may and may not do with organizational systems, networks, and data, and typically includes a monitoring notice. Having new hires sign it during onboarding is the classic exam scenario.",
    },
    {
        "type": "mc",
        "q": "Which term describes the overarching, management-approved set of rules that establishes the overall direction for protecting the confidentiality, integrity, and availability of an organization's information?",
        "choices": [
            "Playbooks",
            "Information security policies",
            "Password standards",
            "Onboarding procedures",
        ],
        "answer": 1,
        "explain": "Information security policies are the umbrella policy set that defines the security program's overall direction and expectations for protecting CIA. More specific policies, standards, and procedures sit underneath them.",
    },
    {
        "type": "mc",
        "q": "During a week-long power outage, a company follows a plan to keep taking customer orders by phone from an alternate site while IT works separately on its systems. Keeping the business functions running is governed by which policy?",
        "choices": [
            "Business continuity policy",
            "Change management policy",
            "Acceptable use policy",
            "SDLC policy",
        ],
        "answer": 0,
        "explain": "Business continuity is the broader discipline of keeping critical business operations running during and after a disruption — people, processes, and facilities, not just IT. Restoring the IT systems themselves is the disaster recovery subset.",
    },
    {
        "type": "mc",
        "q": "A policy defines backup requirements, a warm recovery site, and the maximum time allowed to restore servers after a datacenter fire. Which policy is this?",
        "choices": [
            "Acceptable use policy",
            "Incident response policy",
            "Disaster recovery policy",
            "Access control standard",
        ],
        "answer": 2,
        "explain": "Disaster recovery is the IT-focused subset of business continuity: restoring systems and data after a disaster using backups, recovery sites, and RTO/RPO targets. Scenarios about restoring servers, backups, and sites map to DR.",
    },
    {
        "type": "mc",
        "q": "What is the relationship between disaster recovery (DR) and business continuity (BC)?",
        "choices": [
            "They are unrelated disciplines handled by different regulators",
            "DR is the IT-restoration subset of the broader BC discipline",
            "BC is a subset of DR focused on restoring servers",
            "DR replaces BC once a disaster is declared",
        ],
        "answer": 1,
        "explain": "BC is the broader discipline — keeping the business delivering its critical functions through a disruption. DR is the narrower, IT-focused component: restoring systems and data. BC contains DR, not the other way around.",
    },
    {
        "type": "mc",
        "q": "A policy defines severity levels for security events, names the response team, and specifies who must be notified when a breach is detected. Which policy is this?",
        "choices": [
            "Incident response policy",
            "Business continuity policy",
            "SDLC policy",
            "Password standard",
        ],
        "answer": 0,
        "explain": "The incident response policy defines how the organization prepares for, detects, reports, and responds to security incidents — including team roles, severity classification, and escalation/notification requirements.",
    },
    {
        "type": "mc",
        "q": "A company requires threat modeling during design, secure coding standards, and mandatory code review and security testing before any application release. Which policy establishes these requirements?",
        "choices": [
            "Acceptable use policy",
            "Disaster recovery policy",
            "Physical security standard",
            "Software development lifecycle (SDLC) policy",
        ],
        "answer": 3,
        "explain": "An SDLC policy builds security into every phase of software development — requirements, design, coding, testing, deployment, and maintenance. Security requirements aimed at developers and the release process are SDLC policy territory.",
    },
    {
        "type": "mc",
        "q": "An administrator reconfigured a production firewall on a whim, causing an outage; no request, approval, or testing occurred. Which policy was violated?",
        "choices": [
            "Change management policy",
            "Acceptable use policy",
            "Business continuity policy",
            "Encryption standard",
        ],
        "answer": 0,
        "explain": "Change management policy requires changes to go through a formal request/approval/testing process precisely so ad-hoc changes don't introduce outages or vulnerabilities. An unauthorized, untested production change is the classic violation scenario.",
    },
    {
        "type": "mc",
        "q": "A document requires passwords to be at least 14 characters, screened against known-breached password lists, and stored only as salted hashes. What is this document?",
        "choices": [
            "A password standard",
            "A password guideline",
            "An incident response policy",
            "A playbook",
        ],
        "answer": 0,
        "explain": "Specific, mandatory, measurable password requirements form the password standard. (Modern NIST SP 800-63B guidance favors length and breach-list screening over forced complexity and arbitrary expiration — but wherever the rules land, they live in the standard.)",
    },
    {
        "type": "mc",
        "q": "A document mandates least privilege, role-based access assignment, quarterly access reviews, and manager approval before any privilege is granted. Which named standard is this?",
        "choices": [
            "Encryption standard",
            "Access control standard",
            "Physical security standard",
            "Password standard",
        ],
        "answer": 1,
        "explain": "The access control standard defines mandatory requirements for how access is granted, reviewed, and revoked — least privilege, need-to-know, role-based assignment, approvals, and periodic reviews.",
    },
    {
        "type": "mc",
        "q": "A standard requires badge access on all exterior doors, escorted visitors, an access-control vestibule at the datacenter entrance, and camera coverage of server rooms. Which standard is this?",
        "choices": [
            "Access control standard applied to file permissions",
            "Encryption standard",
            "Physical security standard",
            "Password standard",
        ],
        "answer": 2,
        "explain": "Badges, visitor handling, vestibules (mantraps), and camera requirements are physical protections, so they belong to the physical security standard — distinct from the (logical) access control standard governing accounts and permissions.",
    },
    {
        "type": "mc",
        "q": "What is the PRIMARY purpose of an encryption standard?",
        "choices": [
            "To recommend optional privacy practices for home users",
            "To specify the approved algorithms, key lengths, and protocol versions that must be used",
            "To describe step-by-step how to respond to a ransomware infection",
            "To state management's general commitment to protecting data",
        ],
        "answer": 1,
        "explain": "An encryption standard mandates approved algorithms, minimum key lengths, and protocol versions (e.g., AES-256, TLS 1.2+) plus key-management rules, preventing teams from choosing weak or deprecated crypto. General commitments are policy; optional advice is a guideline.",
    },
    {
        "type": "mc",
        "q": "Per a typical change management procedure, what should be prepared BEFORE implementing a change, in case the change fails?",
        "choices": [
            "A new acceptable use policy",
            "A certificate of destruction",
            "An onboarding checklist",
            "A backout (rollback) plan",
        ],
        "answer": 3,
        "explain": "The change management procedure requires a backout plan — a tested way to reverse the change and restore the prior state — before implementation, so a failed change becomes a rollback instead of an extended outage.",
    },
    {
        "type": "mc",
        "q": "A new hire's first day includes signing the AUP and NDA, receiving accounts provisioned with least privilege, and completing security awareness training. Which procedure governs these steps?",
        "choices": [
            "Offboarding",
            "Onboarding",
            "Change management",
            "A playbook",
        ],
        "answer": 1,
        "explain": "Onboarding covers bringing a new person into the organization: screening, signing the AUP/NDA, least-privilege provisioning, equipment issuance, and training. Offboarding is the reverse process at departure.",
    },
    {
        "type": "mc",
        "q": "Three weeks after a system administrator was terminated, auditors find the admin's VPN and domain accounts are still active. Which procedure failed?",
        "choices": [
            "Offboarding",
            "Onboarding",
            "The SDLC policy",
            "Monitoring and revision of policy documents",
        ],
        "answer": 0,
        "explain": "Offboarding requires promptly disabling accounts and revoking access when someone leaves — ideally coordinated with HR at termination. Stale accounts from failed offboarding are a classic attack path, especially for privileged ex-employees.",
    },
    {
        "type": "mc",
        "q": "A SOC uses a documented, checklist-style set of steps that analysts follow every time a phishing email is reported, and much of it is automated in a SOAR platform. What is this document called?",
        "choices": [
            "A guideline",
            "An acceptable use policy",
            "A playbook",
            "A standard",
        ],
        "answer": 2,
        "explain": "A playbook is a step-by-step response guide for one specific scenario or incident type (phishing, ransomware, lost laptop). Playbooks make responses fast and consistent and are frequently automated through SOAR.",
    },
    {
        "type": "mc",
        "q": "A US hospital must implement specific safeguards for patient health information because a federal law enforced by a government agency requires it. Which external consideration does this BEST illustrate?",
        "choices": [
            "Industry",
            "Regulatory",
            "Guideline",
            "Decentralized governance",
        ],
        "answer": 1,
        "explain": "HIPAA is a government-imposed, agency-enforced requirement — a regulatory consideration (and, being a US federal law, also national). Regulatory drivers carry fines and sanctions for non-compliance.",
    },
    {
        "type": "mc",
        "q": "A retailer that accepts credit cards must comply with PCI DSS. Which type of external consideration is PCI DSS?",
        "choices": [
            "A national law passed by Congress",
            "A local ordinance",
            "An industry (contractual) standard",
            "A voluntary internal guideline",
        ],
        "answer": 2,
        "explain": "PCI DSS is not a law — it is an industry standard imposed contractually by the payment-card brands and acquiring banks. When answer choices split 'regulatory' from 'industry,' payment-card requirements are industry.",
    },
    {
        "type": "mc",
        "q": "A company doing business in California must honor consumer privacy rights under the CCPA, a state law. Which external consideration category does this BEST represent?",
        "choices": [
            "Local/regional",
            "Global",
            "Industry",
            "A playbook requirement",
        ],
        "answer": 0,
        "explain": "CCPA is a California state law — a local/regional consideration. National considerations are country-wide laws (like HIPAA or SOX in the US), while global considerations follow the organization across borders (like GDPR).",
    },
    {
        "type": "mc",
        "q": "A US-based company with no EU offices sells online to customers in Europe and must still comply with the GDPR for those customers' personal data. Which external consideration does this BEST illustrate?",
        "choices": [
            "Local/regional only, since GDPR is just an EU matter",
            "Global",
            "Industry",
            "None — laws cannot apply beyond their own borders",
        ],
        "answer": 1,
        "explain": "GDPR is the classic global consideration: its reach extends to any organization worldwide that handles EU residents' personal data. Multinational operations must satisfy every jurisdiction they touch, even without a physical presence there.",
    },
    {
        "type": "mc",
        "q": "After a breach, a company must notify affected individuals under breach-notification laws and must preserve relevant records under a legal hold for expected litigation. Which external consideration category covers these obligations?",
        "choices": [
            "Legal",
            "Industry",
            "Centralized governance",
            "Guidelines",
        ],
        "answer": 0,
        "explain": "Legal considerations are the broader obligations of the legal system beyond specific regulators: breach-notification duties, e-discovery and legal holds, contract law, liability, and due care/due diligence.",
    },
    {
        "type": "mc",
        "q": "Auditors discover a company's security policies were last reviewed eight years ago and never updated for its move to the cloud. Which element of effective governance is missing?",
        "choices": [
            "Playbooks",
            "A physical security standard",
            "Monitoring and revision",
            "Decentralized governance",
        ],
        "answer": 2,
        "explain": "Governance documents are living documents: monitoring tracks whether they are followed and still fit, and revision updates them on a schedule and after incidents, legal changes, business changes (like cloud adoption), and audit findings.",
    },
    {
        "type": "mc",
        "q": "Which of the following events should trigger a review and possible revision of security policies? (Choose the BEST answer.)",
        "choices": [
            "Only the retirement of the CISO",
            "A major incident, a new privacy law, or a merger — in addition to the scheduled periodic review",
            "Nothing — approved policies must remain unchanged to stay authoritative",
            "Only a change in the company logo or branding",
        ],
        "answer": 1,
        "explain": "Common revision triggers: the scheduled (often annual) review, post-incident lessons learned, new or changed laws/regulations, business changes such as mergers, technology changes, and audit findings. Frozen policies quietly become wrong.",
    },
    {
        "type": "mc",
        "q": "Which governance structure holds ULTIMATE accountability for the organization, sets strategic direction and risk appetite, and receives reports from the CISO?",
        "choices": [
            "A phishing playbook",
            "The help desk",
            "The data processor",
            "The board of directors",
        ],
        "answer": 3,
        "explain": "The board of directors sits at the top of organizational governance: ultimate accountability, strategic direction, risk appetite, and oversight of the security program. Committees are focused subgroups that support and report to the board.",
    },
    {
        "type": "mc",
        "q": "An organization charters a small group of executives and subject-matter experts to meet monthly, review security policies and risk metrics, and make recommendations to leadership. What is this group?",
        "choices": [
            "A (security steering) committee",
            "A government entity",
            "A data controller",
            "A CSIRT playbook",
        ],
        "answer": 0,
        "explain": "Committees are smaller, focused governance groups with subject expertise — security steering, audit, or risk committees — that review policy, track risk, and advise the board or executives in their area.",
    },
    {
        "type": "mc",
        "q": "Legislatures and regulatory agencies that create and enforce the laws organizations must build into their security policies are which type of governance structure?",
        "choices": [
            "Committees",
            "Government entities",
            "Data custodians",
            "Centralized corporate security teams",
        ],
        "answer": 1,
        "explain": "Government entities — legislatures, regulators, agencies — act as external governance by creating and enforcing law, and they serve as the governing structure for public-sector organizations.",
    },
    {
        "type": "mc",
        "q": "In one company, a single corporate security office sets identical policies for every business unit worldwide. In another, each division writes its own security rules. How are these governance models described, respectively?",
        "choices": [
            "Decentralized; centralized",
            "Regulatory; industry",
            "Centralized; decentralized",
            "Board-driven; committee-driven",
        ],
        "answer": 2,
        "explain": "One central authority deciding for the whole organization is centralized (consistent but slower); distributing decision authority to business units is decentralized (flexible and fast but prone to inconsistent controls).",
    },
    {
        "type": "mc",
        "q": "Which of the following is the main RISK of a decentralized governance structure?",
        "choices": [
            "Decisions are too slow because everything requires central approval",
            "Inconsistent security controls and duplicated effort across business units",
            "The board is legally forbidden from overseeing security",
            "It prevents compliance with any national law",
        ],
        "answer": 1,
        "explain": "Decentralized governance trades consistency for speed and local flexibility: units can diverge, producing uneven baselines and duplicated work. Slowness from central approval is the weakness of centralized governance, not decentralized.",
    },
    {
        "type": "mc",
        "q": "An online retailer decides which customer personal data to collect and for what purposes. Under privacy frameworks such as GDPR, what role does the retailer hold?",
        "choices": [
            "Processor",
            "Custodian",
            "Controller",
            "Steward",
        ],
        "answer": 2,
        "explain": "The controller determines the purposes and means of processing personal data — the why and how. The processor merely processes data on the controller's behalf, and custodians/stewards handle day-to-day care of data internally.",
    },
    {
        "type": "mc",
        "q": "A cloud payroll provider processes employee personal data strictly on the instructions of its client companies. What role does the payroll provider hold?",
        "choices": [
            "Processor",
            "Controller",
            "Owner",
            "Board",
        ],
        "answer": 0,
        "explain": "A processor processes personal data on behalf of, and on the instructions of, the controller — it never determines the purpose of processing. Third-party service providers handling client data are the standard processor example.",
    },
    {
        "type": "mc",
        "q": "The head of finance is accountable for the payroll database, decides its classification, and approves who may access it. A database administrator applies the permissions and runs backups. Which roles do they hold, respectively?",
        "choices": [
            "Processor; controller",
            "Custodian; owner",
            "Owner; custodian/steward",
            "Controller; processor",
        ],
        "answer": 2,
        "explain": "The owner is accountable and decides — classification, access approval, risk acceptance. The custodian/steward implements day to day: permissions, backups, secure storage. Controller/processor are privacy-law roles about personal-data processing between organizations.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Guidelines are the only type of governance document whose compliance is optional.",
        "answer": True,
        "explain": "Policies, standards, and procedures are all mandatory. Guidelines are recommendations and best-practice advice — helpful where flexibility and judgment are acceptable — and not following one is not a policy violation.",
    },
    {
        "type": "tf",
        "q": "True or False: A standard states high-level management intent, while a policy specifies exact technical values like minimum key lengths.",
        "answer": False,
        "explain": "It is the reverse: the policy is the high-level statement of management intent, and the standard carries the specific, measurable, mandatory requirements such as minimum password lengths or approved algorithms and key lengths.",
    },
    {
        "type": "tf",
        "q": "True or False: Disaster recovery is a subset of business continuity focused on restoring IT systems and data.",
        "answer": True,
        "explain": "Business continuity is the broader discipline of keeping critical business functions running through a disruption; disaster recovery is its IT-focused component — restoring systems and data via backups, recovery sites, and RTO/RPO targets.",
    },
    {
        "type": "tf",
        "q": "True or False: A data processor determines the purposes and means of processing personal data.",
        "answer": False,
        "explain": "Determining the purposes and means of processing is the controller's defining responsibility. The processor acts only on the controller's behalf and instructions — a processor never decides why personal data is processed.",
    },
    {
        "type": "tf",
        "q": "True or False: Centralized governance tends to produce more consistent security controls across the organization than decentralized governance.",
        "answer": True,
        "explain": "With one central authority making decisions, policy and enforcement are uniform everywhere — consistency is centralization's main advantage. Decentralized governance gains speed and local flexibility but risks divergent, inconsistent controls between units.",
    },
    {
        "type": "tf",
        "q": "True or False: Once a security policy is formally approved, it should never be revised, because changes would undermine its authority.",
        "answer": False,
        "explain": "Policies are living documents. Effective governance requires monitoring their effectiveness and revising them on a scheduled cadence and after incidents, new laws, business changes (mergers, cloud adoption), and audit findings.",
    },
    {
        "type": "tf",
        "q": "True or False: Disabling a departing employee's accounts and recovering company equipment are parts of the offboarding procedure.",
        "answer": True,
        "explain": "Offboarding covers the departure steps: promptly disabling accounts and revoking access (coordinated with HR), recovering assets, and the exit interview/NDA reminder. Skipping it leaves stale accounts — a classic attack path.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The policy that new hires typically sign defining what they may and may not do with company systems is the ______ use policy. (type your answer)",
        "answers": ["acceptable", "acceptable use", "acceptable use policy", "aup"],
        "explain": "The acceptable use policy (AUP) defines permitted and prohibited use of organizational systems, networks, and data, and usually notifies users of monitoring. Signing it is a standard onboarding step.",
    },
    {
        "type": "fill",
        "q": "A checklist-style, step-by-step response guide for one specific incident type, such as phishing, is called a ______. (type your answer)",
        "answers": ["playbook", "playbooks", "a playbook"],
        "explain": "Playbooks give responders an exact sequence of steps for a specific scenario, making responses fast and consistent; SOAR platforms often automate them.",
    },
    {
        "type": "fill",
        "q": "Under GDPR terminology, the organization that determines the purposes and means of processing personal data is the data ______. (type your answer)",
        "answers": ["controller", "data controller"],
        "explain": "The controller decides why and how personal data is processed. The processor, by contrast, processes the data only on the controller's behalf and instructions.",
    },
    {
        "type": "fill",
        "q": "A non-mandatory governance document offering recommended best practices where flexibility is acceptable is a ______. (type your answer)",
        "answers": ["guideline", "guidelines", "a guideline"],
        "explain": "Guidelines are advice, not requirements — the only optional layer in the policy/standard/procedure/guideline hierarchy.",
    },
    {
        "type": "fill",
        "q": "Mandatory, specific, measurable requirements — such as a minimum password length or an approved encryption algorithm — are documented in a ______. (type your answer)",
        "answers": ["standard", "standards", "a standard", "security standard"],
        "explain": "Standards implement policy intent with exact requirements: password construction rules, access control requirements, physical security measures, and approved cryptography all live in standards.",
    },
    {
        "type": "fill",
        "q": "The departure process of promptly disabling a leaver's accounts, revoking access, and recovering assets is called ______. (type your answer)",
        "answers": ["offboarding", "off-boarding", "offboarding procedure"],
        "explain": "Offboarding is onboarding's mirror image. Its most security-critical step is disabling accounts and revoking access immediately, so no stale credentials survive the person's departure.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each governance document type to its description.",
        "pairs": [
            ["Policy", "High-level, mandatory statement of management intent"],
            ["Standard", "Mandatory specific requirements, e.g., minimum password length"],
            ["Procedure", "Mandatory step-by-step instructions for a task"],
            ["Guideline", "Optional recommended best practices"],
        ],
        "explain": "The hierarchy runs from broad to specific: policies state intent, standards set exact mandatory requirements, procedures give the steps, and guidelines — the only optional layer — offer advice where flexibility is acceptable.",
    },
    {
        "type": "match",
        "q": "Match each exam-named policy to the situation it governs.",
        "pairs": [
            ["Acceptable use policy", "What employees may do with company systems and internet"],
            ["Business continuity", "Keeping critical operations running during a disruption"],
            ["Disaster recovery", "Restoring IT systems and data after a catastrophe"],
            ["Incident response", "Detecting, reporting, and responding to security incidents"],
            ["SDLC", "Building security into each software development phase"],
            ["Change management", "Requiring formal approval and testing before system changes"],
        ],
        "explain": "These are six of the seven named 5.1 policies — the seventh, information security policies, is the overarching umbrella. BC keeps the business running; DR restores IT; IR handles security incidents; SDLC secures development; change management prevents risky ad-hoc changes.",
    },
    {
        "type": "match",
        "q": "Match each external consideration to its classic example.",
        "pairs": [
            ["Regulatory", "HIPAA safeguards enforced by a government agency"],
            ["Industry", "PCI DSS contractual requirements for card payments"],
            ["Local/regional", "CCPA, a California state privacy law"],
            ["National", "SOX, a US federal law for public companies"],
            ["Global", "GDPR reaching organizations worldwide that handle EU residents' data"],
        ],
        "explain": "Regulatory = government-imposed and agency-enforced; industry = sector/contractual standards like PCI DSS (not a law); local/regional = state or provincial law; national = country-wide law; global = obligations that follow the organization across borders.",
    },
    {
        "type": "match",
        "q": "Match each systems/data role to its responsibility.",
        "pairs": [
            ["Owner", "Accountable for the data; decides classification and approves access"],
            ["Controller", "Determines the purposes and means of processing personal data"],
            ["Processor", "Processes personal data only on another party's instructions"],
            ["Custodian/steward", "Implements day-to-day protection: backups, permissions, storage"],
        ],
        "explain": "Owner and custodian split accountability from implementation inside the organization; controller and processor are privacy-law roles describing which organization decides why data is processed and which one merely processes it on instruction.",
    },
    {
        "type": "match",
        "q": "Match each governance structure to its description.",
        "pairs": [
            ["Board", "Holds ultimate accountability and sets strategic direction"],
            ["Committee", "Focused expert subgroup that reviews policy and advises"],
            ["Government entities", "External bodies that create and enforce laws"],
            ["Centralized", "One authority makes decisions for the whole organization"],
            ["Decentralized", "Business units make their own security decisions"],
        ],
        "explain": "Boards oversee; committees specialize and advise; government entities impose external requirements; centralized structures maximize consistency while decentralized ones maximize local speed and flexibility at the cost of uniformity.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps of a change management procedure in the order they occur.",
        "items": [
            "Submit a change request",
            "Assess risk and obtain approval (e.g., from the CAB)",
            "Schedule the change in a maintenance window",
            "Implement the change with a backout plan ready",
            "Test and verify the change succeeded",
            "Document the results and close the request",
        ],
        "explain": "Changes flow request → risk assessment/approval → scheduling → implementation (with a backout plan ready in case of failure) → verification → documentation/closure. The formal sequence exists so changes cannot skip approval or verification.",
    },
    {
        "type": "order",
        "q": "Arrange the lifecycle of a security policy from creation through ongoing upkeep.",
        "items": [
            "Draft the policy",
            "Obtain management review and formal approval",
            "Publish and communicate the policy to staff",
            "Monitor compliance and effectiveness",
            "Revise the policy on schedule or when triggers occur",
        ],
        "explain": "A policy is drafted, approved by management, then published and communicated so staff can follow it. Governance then continues: monitoring checks that it is followed and still fits, and revision updates it on a cadence or after incidents, legal, business, or technology changes.",
    },
]
