TOPIC = {
    "id": "5.2",
    "domain": 5,
    "title": "Explain elements of the risk management process.",
    "short": "Risk Management",
}

TERMS = [
    ("Risk identification", "First step of risk management: systematically recognizing and documenting the risks (threats exploiting vulnerabilities against assets) the organization faces"),
    ("Risk assessment", "Evaluating identified risks — estimating likelihood and impact so risks can be prioritized; performed ad hoc, recurring, one-time, or continuously"),
    ("Ad hoc risk assessment", "Assessment performed as needed in response to a specific situation or trigger (e.g., news of an attack on a competitor) — no fixed schedule"),
    ("Recurring risk assessment", "Assessment repeated at regular scheduled intervals (annual, quarterly), often compliance-driven — discrete assessments with gaps between them"),
    ("One-time risk assessment", "Assessment performed once for a specific purpose or project (e.g., a merger or new system) and never repeated"),
    ("Continuous risk assessment", "Constant, real-time evaluation of risk, typically via automated monitoring tooling — always on, no gaps"),
    ("Risk analysis", "Determining the magnitude of each risk using qualitative (subjective categories) and/or quantitative (numeric, usually dollar) methods"),
    ("Qualitative risk analysis", "Subjective analysis expressing risk as categories (low/medium/high, 1-5 scores), often on a risk matrix/heat map; fast but inconsistent between assessors"),
    ("Quantitative risk analysis", "Objective, numbers-based analysis expressing risk in dollars using SLE, ARO, and ALE; defensible for cost/benefit decisions but data-hungry"),
    ("Asset value (AV)", "The monetary value of the asset at risk — the starting input for quantitative analysis"),
    ("Exposure factor (EF)", "The PERCENTAGE of an asset's value expected to be lost in a single occurrence of a risk event"),
    ("Single loss expectancy (SLE)", "Expected dollar loss from ONE occurrence of a risk event: SLE = AV x EF"),
    ("Annualized rate of occurrence (ARO)", "How many times per YEAR the event is expected to occur — can be fractional (once every 10 years = 0.1)"),
    ("Annualized loss expectancy (ALE)", "Expected dollar loss per YEAR from a risk: ALE = SLE x ARO — the cost/benefit yardstick for control spending"),
    ("Probability", "Quantitative, statistical measure of the chance an event occurs, expressed numerically (e.g., 10%, 0.1)"),
    ("Likelihood", "Qualitative, subjective estimate of the chance an event occurs, typically expressed as low/medium/high"),
    ("Impact", "The magnitude of harm to the organization if a risk is realized: financial loss, downtime, reputational damage, safety, legal penalties"),
    ("Risk register", "The central document/ledger tracking every identified risk with its description, scores, treatment, status, owner, KRIs, and thresholds"),
    ("Key risk indicator (KRI)", "Forward-looking metric that gives early warning that risk exposure is rising before an incident occurs (e.g., phishing click-through rate)"),
    ("Risk owner", "The named person or role accountable for a specific risk — chooses its treatment, tracks its status, and answers for it"),
    ("Risk threshold", "The defined level of risk at which action must be taken — the boundary line between acceptable and unacceptable exposure"),
    ("Risk appetite", "The broad, strategic amount and type of risk an organization is willing to accept in pursuit of its objectives; set by senior leadership"),
    ("Expansionary risk appetite", "Willing to take on MORE risk to pursue growth, innovation, and higher returns — e.g., a startup racing for market share"),
    ("Conservative risk appetite", "Prefers to MINIMIZE risk, prioritizing safety, stability, and compliance — e.g., a bank or hospital in a regulated industry"),
    ("Neutral risk appetite", "Balanced posture — weighs risk against reward case by case, neither seeking nor shunning risk"),
    ("Risk tolerance", "The acceptable degree of deviation from the risk appetite — the maximum risk the organization can actually withstand for a given activity"),
    ("Transfer", "Risk strategy that shifts the financial impact to a third party — cybersecurity insurance, contract clauses, outsourcing; residual risk remains"),
    ("Accept", "Risk strategy: a deliberate, documented decision to take no action and bear the risk — appropriate when the control costs more than the ALE"),
    ("Exemption", "Acceptance mechanism: a waiver relieving a system/process from a requirement it cannot or should not meet, usually with compensating safeguards"),
    ("Exception", "Acceptance mechanism: a temporary, approved deviation from a policy/requirement with compensating controls and an expiration/review date"),
    ("Avoid", "Risk strategy that eliminates the risk by not engaging in (or discontinuing) the risky activity — the only strategy that removes the risk entirely"),
    ("Mitigate", "Risk strategy that applies controls (patching, MFA, backups, training) to reduce likelihood and/or impact to an acceptable level"),
    ("Residual risk", "The risk that remains after a treatment (mitigation/transfer) is applied; it should fall within the risk tolerance"),
    ("Risk reporting", "Communicating risk posture to stakeholders (executives, board, regulators) via register summaries, heat maps, KRI dashboards, and trend reports"),
    ("Business impact analysis (BIA)", "Identifies mission-critical functions and quantifies the effect of their disruption over time; its outputs drive BC/DR planning and recovery targets"),
    ("Recovery time objective (RTO)", "The maximum acceptable time a system/process can be down before it must be restored — 'how long can we afford to be down?'"),
    ("Recovery point objective (RPO)", "The maximum acceptable amount of data loss, measured in time — dictates backup/replication frequency"),
    ("Mean time to repair (MTTR)", "The average time to fix a failed component/system and restore it to operation — must be shorter than the RTO for recovery to succeed"),
    ("Mean time between failures (MTBF)", "The average operating time between one failure and the next for a repairable system — a reliability measure; higher is better"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A web server is valued at $200,000. A risk assessment estimates a successful attack would destroy 30% of its value. What is the single loss expectancy (SLE)?",
        "choices": [
            "$6,000",
            "$60,000",
            "$140,000",
            "$200,000",
        ],
        "answer": 1,
        "explain": "SLE = AV x EF = $200,000 x 0.30 = $60,000 — the expected dollar loss from ONE occurrence of the event. The exposure factor is the percentage of the asset's value lost in a single incident.",
    },
    {
        "type": "mc",
        "q": "A risk has an SLE of $50,000 and is expected to occur once every two years. What is the annualized loss expectancy (ALE)?",
        "choices": [
            "$100,000",
            "$50,000",
            "$25,000",
            "$12,500",
        ],
        "answer": 2,
        "explain": "Once every two years gives ARO = 0.5. ALE = SLE x ARO = $50,000 x 0.5 = $25,000 per year. ARO is frequently fractional — do not multiply by the number of years.",
    },
    {
        "type": "mc",
        "q": "A database is valued at $100,000. A flood would destroy 40% of it, and floods are expected once every 10 years. What is the ALE?",
        "choices": [
            "$40,000",
            "$4,000",
            "$10,000",
            "$400",
        ],
        "answer": 1,
        "explain": "SLE = AV x EF = $100,000 x 0.40 = $40,000. ARO = once every 10 years = 0.1. ALE = SLE x ARO = $40,000 x 0.1 = $4,000 per year. $40,000 (the SLE alone) is the classic distractor.",
    },
    {
        "type": "mc",
        "q": "An event is expected to occur once every 20 years. What is its annualized rate of occurrence (ARO)?",
        "choices": [
            "20",
            "0.2",
            "0.05",
            "5",
        ],
        "answer": 2,
        "explain": "ARO is occurrences per YEAR: 1 event / 20 years = 0.05. ARO can be (and often is) less than 1 — 'once every N years' is 1/N, not N.",
    },
    {
        "type": "mc",
        "q": "In quantitative risk analysis, what does the exposure factor (EF) represent?",
        "choices": [
            "The percentage of an asset's value expected to be lost in a single occurrence of the event",
            "The number of times per year the event is expected to occur",
            "The total dollar value of the asset at risk",
            "The expected annual dollar loss from the risk",
        ],
        "answer": 0,
        "explain": "EF is the percentage of the asset's value lost in one occurrence; it multiplies against asset value to produce the SLE (SLE = AV x EF). Occurrences per year is ARO; total asset value is AV; expected annual loss is ALE.",
    },
    {
        "type": "mc",
        "q": "Which formula pair is correct?",
        "choices": [
            "SLE = ALE x ARO and ALE = AV x EF",
            "SLE = AV x ARO and ALE = SLE x EF",
            "SLE = AV x EF and ALE = SLE x ARO",
            "SLE = AV x EF and ALE = AV x ARO",
        ],
        "answer": 2,
        "explain": "SLE = AV x EF (loss from one incident) and ALE = SLE x ARO (loss per year). The other combinations are the wrong-formula distractors the exam likes to offer.",
    },
    {
        "type": "mc",
        "q": "A team rates each risk low, medium, or high on a color-coded heat map based on the assessors' judgment. What type of risk analysis is this?",
        "choices": [
            "Quantitative",
            "Qualitative",
            "Continuous",
            "Ad hoc",
        ],
        "answer": 1,
        "explain": "Subjective categories (low/medium/high) and likelihood-x-impact heat maps are qualitative analysis — fast and cheap but inconsistent between assessors. Quantitative analysis uses objective numbers, usually dollars (SLE/ARO/ALE).",
    },
    {
        "type": "mc",
        "q": "What is the PRIMARY advantage of quantitative risk analysis over qualitative analysis?",
        "choices": [
            "It requires no historical data or asset valuation",
            "It is faster and cheaper to perform",
            "It works better for intangibles such as reputation",
            "It expresses risk in dollars, enabling defensible cost/benefit decisions",
        ],
        "answer": 3,
        "explain": "Quantitative analysis produces objective monetary figures (SLE, ALE) that management can weigh directly against control costs. Its downsides are the opposite of the other choices: it needs reliable data, takes longer, and struggles with intangibles.",
    },
    {
        "type": "mc",
        "q": "One analyst states a risk has 'a 10% chance of occurring this year'; another rates the same risk 'medium likelihood.' How does SY0-701 distinguish these two expressions?",
        "choices": [
            "The 10% figure is probability (quantitative); 'medium' is likelihood (qualitative)",
            "The 10% figure is likelihood (qualitative); 'medium' is probability (quantitative)",
            "Both are probability; likelihood only describes impact",
            "Both are likelihood; probability only applies to hardware failures",
        ],
        "answer": 0,
        "explain": "Probability is the quantitative, statistical, numeric measure of chance (10%, 0.1); likelihood is the qualitative, subjective estimate (low/medium/high). Both describe the chance of occurrence — neither describes impact.",
    },
    {
        "type": "mc",
        "q": "In risk analysis, which term describes the magnitude of harm — financial loss, downtime, reputational damage — the organization would suffer if a risk is realized?",
        "choices": [
            "Probability",
            "Exposure factor",
            "Impact",
            "Risk threshold",
        ],
        "answer": 2,
        "explain": "Impact is the magnitude of harm if the risk occurs. Risk is fundamentally likelihood/probability x impact. EF is narrower — the percentage of one asset's value lost — while impact covers all consequences, including reputational and legal harm.",
    },
    {
        "type": "mc",
        "q": "A security team builds an asset inventory, reviews threat intelligence and past incidents, and interviews business units to produce a documented list of risks the company faces. Which element of the risk management process is this?",
        "choices": [
            "Risk reporting",
            "Risk identification",
            "Risk transference",
            "Business impact analysis",
        ],
        "answer": 1,
        "explain": "Risk identification is the first step: systematically recognizing and documenting the risks the organization faces. You cannot assess, register, or treat a risk you have not identified.",
    },
    {
        "type": "mc",
        "q": "After a competitor suffers a highly publicized ransomware attack, the CISO orders an immediate, unscheduled risk assessment of the company's own exposure. What type of assessment is this?",
        "choices": [
            "Recurring",
            "One-time",
            "Continuous",
            "Ad hoc",
        ],
        "answer": 3,
        "explain": "Ad hoc assessments are performed as needed in response to a specific situation or trigger — no schedule. 'In response to,' 'after news of,' and 'leadership suddenly requests' are the scenario keywords.",
    },
    {
        "type": "mc",
        "q": "A company performs a risk assessment every October because its compliance program requires one at least annually. What type of assessment is this?",
        "choices": [
            "Recurring",
            "Ad hoc",
            "One-time",
            "Continuous",
        ],
        "answer": 0,
        "explain": "Assessments repeated at regular scheduled intervals (annual, quarterly) are recurring — often compliance-driven. A compliance-mandated annual assessment repeats, so it is recurring, not one-time.",
    },
    {
        "type": "mc",
        "q": "Before acquiring another firm, a company commissions a single risk assessment specifically for the merger; it will not be repeated afterward. What type of assessment is this?",
        "choices": [
            "Continuous",
            "One-time",
            "Recurring",
            "Ad hoc",
        ],
        "answer": 1,
        "explain": "A one-time assessment is performed once for a specific purpose or project — a merger, a new system deployment — and never repeated. It differs from ad hoc mainly in framing: one-time is tied to a defined project, not an unexpected trigger.",
    },
    {
        "type": "mc",
        "q": "An organization streams telemetry from its security tools into a dashboard that evaluates and updates its risk posture in real time, around the clock. What type of assessment is this?",
        "choices": [
            "Continuous",
            "Recurring",
            "Ad hoc",
            "One-time",
        ],
        "answer": 0,
        "explain": "Continuous assessment is constant, automated, real-time evaluation with no gaps. Recurring is the trap answer — recurring means discrete assessments repeated on a schedule, with gaps between them.",
    },
    {
        "type": "mc",
        "q": "Which document is the central ledger listing every identified risk along with its description, scores, treatment, status, and accountable owner?",
        "choices": [
            "The business impact analysis",
            "The risk register",
            "The KRI dashboard",
            "The statement of risk appetite",
        ],
        "answer": 1,
        "explain": "The risk register (often a spreadsheet or GRC-tool record) is the central tracking document for all identified risks, including their owners, thresholds, and KRIs. The BIA ranks business functions; a KRI dashboard reports metrics.",
    },
    {
        "type": "mc",
        "q": "The security team tracks the phishing click-through rate and the number of unpatched critical systems, watching for upward trends that warn of growing exposure BEFORE an incident occurs. What are these metrics called?",
        "choices": [
            "Recovery point objectives",
            "Annualized loss expectancies",
            "Key risk indicators (KRIs)",
            "Risk thresholds",
        ],
        "answer": 2,
        "explain": "KRIs are forward-looking metrics that give early warning that risk exposure is rising. When a KRI trends the wrong way, the associated risk is growing — before any incident happens.",
    },
    {
        "type": "mc",
        "q": "In a risk register, who is the named person accountable for a specific risk — choosing its treatment, tracking its status, and answering for it?",
        "choices": [
            "The risk owner",
            "The data custodian",
            "The auditor",
            "The incident responder",
        ],
        "answer": 0,
        "explain": "Each register entry names a risk owner: the person or role accountable for that risk's treatment and status. A risk without an owner is a risk nobody manages.",
    },
    {
        "type": "mc",
        "q": "A risk register flags any risk scoring above 15 for mandatory escalation and action. What does the value 15 represent?",
        "choices": [
            "The risk appetite",
            "The annualized rate of occurrence",
            "The exposure factor",
            "The risk threshold",
        ],
        "answer": 3,
        "explain": "The risk threshold is the defined level of risk at which action must be taken — the boundary between acceptable and unacceptable exposure. Crossing it triggers the register's response process.",
    },
    {
        "type": "mc",
        "q": "Senior leadership publishes a statement that the company 'is willing to accept moderate risk in pursuit of innovation.' Which concept does this statement express?",
        "choices": [
            "Risk threshold",
            "Risk appetite",
            "Residual risk",
            "Risk tolerance",
        ],
        "answer": 1,
        "explain": "Risk appetite is the broad, strategic amount and type of risk the organization is willing to accept in pursuit of its objectives — set by senior leadership, before any specific risk is on the table. Tolerance is the practical deviation allowed around that appetite; threshold is the concrete trigger line.",
    },
    {
        "type": "mc",
        "q": "A company's appetite statement accepts moderate risk, but the risk committee also sets the maximum exposure any single business unit may actually carry in practice. What does this maximum represent?",
        "choices": [
            "Risk tolerance",
            "Risk appetite",
            "Key risk indicator",
            "Annualized loss expectancy",
        ],
        "answer": 0,
        "explain": "Risk tolerance is the acceptable degree of deviation from the appetite — the maximum level of risk the organization can actually withstand for a given activity. Appetite is the broad strategy; tolerance is the specific working boundary.",
    },
    {
        "type": "mc",
        "q": "A startup knowingly accepts significant security trade-offs to ship products fast and capture market share. Which risk appetite posture is this?",
        "choices": [
            "Conservative",
            "Neutral",
            "Expansionary",
            "Residual",
        ],
        "answer": 2,
        "explain": "An expansionary appetite takes on MORE risk to pursue growth, innovation, and higher returns — the startup racing for market share is the classic example. Conservative minimizes risk; neutral balances case by case.",
    },
    {
        "type": "mc",
        "q": "A heavily regulated bank prioritizes stability and compliance and works to minimize risk wherever possible. Which risk appetite posture is this?",
        "choices": [
            "Conservative",
            "Expansionary",
            "Neutral",
            "Ad hoc",
        ],
        "answer": 0,
        "explain": "A conservative appetite prefers to minimize risk, prioritizing safety, stability, and compliance — typical of banks, hospitals, and utilities in regulated industries.",
    },
    {
        "type": "mc",
        "q": "A mature enterprise neither seeks out risk nor avoids it reflexively; it weighs each opportunity's risk against its reward case by case. Which risk appetite posture is this?",
        "choices": [
            "Expansionary",
            "Neutral",
            "Conservative",
            "Continuous",
        ],
        "answer": 1,
        "explain": "A neutral appetite is the balanced middle posture: measured, analyzed risk-taking that weighs risk against reward case by case — neither expansionary (risk-seeking) nor conservative (risk-minimizing).",
    },
    {
        "type": "mc",
        "q": "To deal with the potential financial impact of a data breach, a company purchases a cyber-liability insurance policy. Which risk management strategy is this?",
        "choices": [
            "Mitigate",
            "Avoid",
            "Accept",
            "Transfer",
        ],
        "answer": 3,
        "explain": "Insurance shifts the financial impact of the risk to a third party — transfer. Note that transfer does not remove the risk: operational and reputational damage still lands on the company, and residual risk remains.",
    },
    {
        "type": "mc",
        "q": "Rather than invest in securing a legacy customer portal, the company permanently shuts the portal down. Which risk management strategy is this?",
        "choices": [
            "Avoid",
            "Transfer",
            "Mitigate",
            "Accept",
        ],
        "answer": 0,
        "explain": "Discontinuing the risky activity eliminates the risk entirely — avoidance, the only strategy that removes the risk completely (along with whatever benefit the activity provided).",
    },
    {
        "type": "mc",
        "q": "A company deploys MFA and aggressive patching to reduce the likelihood of account takeover. Which risk management strategy is this?",
        "choices": [
            "Accept",
            "Transfer",
            "Mitigate",
            "Avoid",
        ],
        "answer": 2,
        "explain": "Applying controls (MFA, patching, firewalls, backups, training) to reduce a risk's likelihood and/or impact is mitigation — most day-to-day security work. Residual risk remains afterward and should fall within tolerance.",
    },
    {
        "type": "mc",
        "q": "A control that would eliminate a low-impact risk costs $40,000 per year, but the risk's ALE is only $5,000. Management formally documents a decision to take no action. Which strategy is this, and why is it appropriate?",
        "choices": [
            "Avoid — the activity should be discontinued",
            "Accept — the control costs more per year than the expected annual loss",
            "Transfer — the cost is shifted to the control vendor",
            "Mitigate — any control spending reduces risk",
        ],
        "answer": 1,
        "explain": "When the annual control cost exceeds the ALE it would remove, a deliberate, documented decision to bear the risk (acceptance) is the financially rational response. Acceptance must be conscious and documented — ignoring a risk is not acceptance.",
    },
    {
        "type": "mc",
        "q": "A legacy medical device cannot run the mandated endpoint security agent, so management formally waives that requirement for the device and applies compensating safeguards. Which acceptance mechanism is this?",
        "choices": [
            "Exception",
            "Avoidance",
            "Exemption",
            "Transference",
        ],
        "answer": 2,
        "explain": "An exemption is a waiver relieving a system or process from a requirement it cannot (or should not) meet — the requirement is formally set aside for that asset, usually with compensating safeguards. An exception is instead a temporary, approved deviation with an expiration/review date.",
    },
    {
        "type": "mc",
        "q": "A critical application breaks when a required patch is applied, so management approves a 90-day deviation from the patching policy with compensating controls and a review date. Which acceptance mechanism is this?",
        "choices": [
            "Exception",
            "Exemption",
            "Risk avoidance",
            "Risk threshold",
        ],
        "answer": 0,
        "explain": "An exception is a temporary, approved deviation from a policy or requirement, typically with compensating controls, an expiration/review date, and a plan to return to compliance. The 90-day window and review date are the exception giveaways.",
    },
    {
        "type": "mc",
        "q": "Each quarter, the security team presents heat maps, KRI dashboards, and risk register summaries to the board so it can allocate budget and verify the company is operating within its appetite. Which element of risk management is this?",
        "choices": [
            "Risk identification",
            "Risk reporting",
            "Risk avoidance",
            "Continuous assessment",
        ],
        "answer": 1,
        "explain": "Risk reporting communicates risk posture to the stakeholders who must act on it — executives, board, regulators — via register summaries, heat maps, KRI dashboards, and trend reports. It turns the register into a decision tool.",
    },
    {
        "type": "mc",
        "q": "What is the PRIMARY purpose of a business impact analysis (BIA)?",
        "choices": [
            "To identify mission-critical functions and quantify the effect of their disruption over time",
            "To assign a named owner to every risk in the register",
            "To calculate the ALE for each threat facing the organization",
            "To determine which employees need security awareness training",
        ],
        "answer": 0,
        "explain": "The BIA identifies the organization's mission-critical functions and quantifies the cost of their disruption over time. Its outputs — criticality rankings and recovery targets like RTO/RPO — drive business continuity and disaster recovery planning.",
    },
    {
        "type": "mc",
        "q": "A BIA states that the email system must be restored within four hours of an outage. Which metric is the four-hour figure?",
        "choices": [
            "RPO",
            "MTBF",
            "MTTR",
            "RTO",
        ],
        "answer": 3,
        "explain": "The recovery time objective (RTO) is the maximum acceptable time a system can be down before it must be restored — 'how long can we afford to be down?' RPO measures tolerable data loss, not downtime.",
    },
    {
        "type": "mc",
        "q": "A BIA states the company can afford to lose no more than 15 minutes of transaction data. Which metric is this, and what does it dictate?",
        "choices": [
            "RTO — it dictates the failover time",
            "RPO — it dictates backup/replication frequency",
            "MTTR — it dictates repair staffing",
            "MTBF — it dictates hardware purchasing",
        ],
        "answer": 1,
        "explain": "The recovery point objective (RPO) is the maximum acceptable data loss measured in time — it looks backward to the last good copy of the data. An RPO of 15 minutes means backups or replication must capture data at least every 15 minutes.",
    },
    {
        "type": "mc",
        "q": "Which metric is the AVERAGE time required to fix a failed component or system and restore it to operation?",
        "choices": [
            "MTBF",
            "RTO",
            "MTTR",
            "RPO",
        ],
        "answer": 2,
        "explain": "Mean time to repair (MTTR) is the average time to fix a failure — a measured engineering value, not a business objective. RTO is the business's maximum tolerable downtime; the two are compared but distinct.",
    },
    {
        "type": "mc",
        "q": "When comparing two server models, an engineer chooses the one that runs an average of 10,000 hours between failures instead of 6,000. Which metric guided the decision?",
        "choices": [
            "MTBF",
            "MTTR",
            "RPO",
            "ALE",
        ],
        "answer": 0,
        "explain": "Mean time between failures (MTBF) is the average operating time between one failure and the next for a repairable system — a reliability measure. Higher MTBF is better; it guides hardware purchasing and redundancy planning.",
    },
    {
        "type": "mc",
        "q": "A system's measured MTTR is 8 hours, but the BIA sets its RTO at 4 hours. What does this comparison reveal?",
        "choices": [
            "The recovery capability cannot meet the business requirement — repairs take longer than the allowed downtime",
            "The system exceeds requirements, since MTTR is twice the RTO",
            "Nothing — MTTR and RTO measure unrelated things and cannot be compared",
            "The RPO must be increased to 8 hours to compensate",
        ],
        "answer": 0,
        "explain": "For recovery to succeed, MTTR must be SHORTER than RTO. If repairs average 8 hours but the business can only tolerate 4 hours of downtime, the capability fails the requirement — the organization must improve repair capability or adjust its plans. RPO is about data loss and is unaffected.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Transferring a risk (for example, by purchasing cyber insurance) removes the risk from the organization entirely.",
        "answer": False,
        "explain": "Transfer shifts only the FINANCIAL impact to a third party. The operational and reputational damage of an incident still lands on the organization, and residual risk always remains. Only avoidance eliminates a risk entirely.",
    },
    {
        "type": "tf",
        "q": "True or False: Avoidance is the only risk management strategy that eliminates the risk entirely.",
        "answer": True,
        "explain": "By not engaging in (or discontinuing) the risky activity, avoidance removes the risk completely — but it also removes whatever benefit the activity would have brought. Transfer and mitigation both leave residual risk; acceptance keeps the whole risk.",
    },
    {
        "type": "tf",
        "q": "True or False: The annualized rate of occurrence (ARO) can be a fraction less than 1.",
        "answer": True,
        "explain": "ARO is occurrences per year, so an event expected once every 10 years has an ARO of 0.1, and once every 20 years is 0.05. Treating 'once every 20 years' as ARO = 20 is a classic calculation trap.",
    },
    {
        "type": "tf",
        "q": "True or False: The recovery point objective (RPO) defines the maximum time a system may be down before it must be restored.",
        "answer": False,
        "explain": "That is the RTO. The RPO is the maximum acceptable amount of DATA LOSS, measured in time — how far back the last good copy of the data may be — and it dictates backup/replication frequency.",
    },
    {
        "type": "tf",
        "q": "True or False: A higher MTBF indicates a more reliable system.",
        "answer": True,
        "explain": "MTBF is the average operating time between failures — the longer a system runs between failures, the more reliable it is. Conversely, a LOWER MTTR is better, because it means faster recovery.",
    },
    {
        "type": "tf",
        "q": "True or False: A compliance-mandated risk assessment performed every year is an example of continuous assessment.",
        "answer": False,
        "explain": "Scheduled, repeating assessments (annual, quarterly) are RECURRING — discrete assessments with gaps between them. Continuous assessment is always-on, automated, real-time evaluation with no gaps.",
    },
    {
        "type": "tf",
        "q": "True or False: Simply ignoring a risk and taking no action qualifies as risk acceptance.",
        "answer": False,
        "explain": "Acceptance must be a conscious, documented, risk-owner-approved decision to bear the risk. Ignoring a risk is not a strategy at all — undocumented inaction is unmanaged risk, not acceptance.",
    },
    {
        "type": "tf",
        "q": "True or False: An exception is typically a temporary, approved deviation from a requirement, with compensating controls and an expiration or review date.",
        "answer": True,
        "explain": "That is the defining shape of an exception: temporary, approved, compensated, and time-boxed with a plan to return to compliance. An exemption, by contrast, formally waives the requirement for an asset that cannot or should not meet it.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Single loss expectancy is calculated as asset value multiplied by the ______ factor. (type your answer)",
        "answers": ["exposure", "exposure factor", "ef"],
        "explain": "SLE = AV x EF. The exposure factor is the percentage of the asset's value expected to be lost in a single occurrence of the event.",
    },
    {
        "type": "fill",
        "q": "Annualized loss expectancy is calculated as SLE multiplied by the ______. (type your answer or the acronym)",
        "answers": ["aro", "annualized rate of occurrence", "annual rate of occurrence", "rate of occurrence"],
        "explain": "ALE = SLE x ARO. The ARO is how many times per year the event is expected to occur, and it can be fractional (once every 10 years = 0.1).",
    },
    {
        "type": "fill",
        "q": "The central document that tracks every identified risk with its owner, scores, treatment, and status is the risk ______. (type your answer)",
        "answers": ["register", "risk register", "the risk register"],
        "explain": "The risk register is the central ledger of risks — often a spreadsheet or GRC-tool record — containing each risk's description, scores, treatment, status, owner, KRIs, and thresholds.",
    },
    {
        "type": "fill",
        "q": "Purchasing cybersecurity insurance is the classic example of the risk management strategy called ______. (type your answer)",
        "answers": ["transfer", "transference", "risk transfer", "transferring"],
        "explain": "Insurance shifts the financial impact of a risk to a third party — transfer. The risk itself is not eliminated; operational and reputational consequences still land on the insured organization.",
    },
    {
        "type": "fill",
        "q": "The BIA metric defining the maximum acceptable amount of data loss, measured in time, is the ______. (type the acronym)",
        "answers": ["rpo", "recovery point objective"],
        "explain": "The recovery point objective (RPO) looks backward from a failure to the last good copy of the data, and it dictates how frequently backups or replication must run.",
    },
    {
        "type": "fill",
        "q": "A forward-looking metric, such as phishing click-through rate, that gives early warning of rising risk exposure is a key risk ______. (type your answer)",
        "answers": ["indicator", "indicators", "key risk indicator", "kri"],
        "explain": "Key risk indicators (KRIs) warn that exposure is increasing before an incident occurs. When a KRI trends the wrong way, the associated risk is growing.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each risk assessment type to its scenario.",
        "pairs": [
            ["Ad hoc", "Assessment ordered immediately after news of an attack on a competitor"],
            ["Recurring", "Assessment run every October for the compliance program"],
            ["One-time", "Single assessment performed specifically for an acquisition"],
            ["Continuous", "Automated tooling evaluates risk in real time around the clock"],
        ],
        "explain": "Ad hoc = triggered, as needed; recurring = scheduled, repeating intervals; one-time = single specific purpose, never repeated; continuous = always-on, automated, real-time. Recurring vs. continuous is the pair the exam likes to confuse.",
    },
    {
        "type": "match",
        "q": "Match each risk management strategy to its scenario.",
        "pairs": [
            ["Transfer", "Purchasing a cyber-liability insurance policy"],
            ["Accept", "Documenting a decision to live with a risk whose fix costs more than its ALE"],
            ["Avoid", "Shutting down a legacy portal rather than securing it"],
            ["Mitigate", "Deploying MFA to reduce account-takeover likelihood"],
        ],
        "explain": "Insurance = transfer; documented decision to bear the risk = accept; discontinuing the activity = avoid; applying controls = mitigate. Only avoidance eliminates the risk entirely; the others leave residual risk.",
    },
    {
        "type": "match",
        "q": "Match each BIA metric to its definition.",
        "pairs": [
            ["RTO", "Maximum acceptable time a system can be down before restoration"],
            ["RPO", "Maximum acceptable data loss, measured in time"],
            ["MTTR", "Average time to fix a failed system and restore operation"],
            ["MTBF", "Average operating time between one failure and the next"],
        ],
        "explain": "RTO and RPO are business objectives set by the BIA (downtime and data loss the business can tolerate); MTTR and MTBF are measured engineering values (how fast repairs go, how often failures occur). MTTR must be shorter than RTO for recovery to succeed.",
    },
    {
        "type": "match",
        "q": "Match each quantitative risk analysis term to its meaning.",
        "pairs": [
            ["Asset value (AV)", "The monetary value of the asset at risk"],
            ["Exposure factor (EF)", "Percentage of the asset's value lost in one occurrence"],
            ["SLE", "Expected dollar loss from a single occurrence (AV x EF)"],
            ["ARO", "Expected number of occurrences per year, possibly fractional"],
            ["ALE", "Expected dollar loss per year (SLE x ARO)"],
        ],
        "explain": "The chain runs AV -> EF -> SLE -> ARO -> ALE: value times exposure gives the per-incident loss, and per-incident loss times annual frequency gives the annualized loss used for cost/benefit decisions.",
    },
    {
        "type": "match",
        "q": "Match each risk governance concept to its description.",
        "pairs": [
            ["Risk appetite", "Broad, strategic willingness to take risk, set by leadership"],
            ["Risk tolerance", "Acceptable degree of deviation from the appetite in practice"],
            ["Risk threshold", "Concrete trigger level at which action must be taken"],
            ["Risk owner", "Named person accountable for managing a specific risk"],
            ["Key risk indicator", "Metric giving early warning that exposure is rising"],
        ],
        "explain": "Appetite, tolerance, and threshold nest broad -> specific -> trigger: the strategic statement, the working boundary around it, and the register's action line. Owners and KRIs live in the risk register alongside the thresholds.",
    },
    {
        "type": "match",
        "q": "Match each risk appetite posture to its description.",
        "pairs": [
            ["Expansionary", "Takes on more risk to pursue growth and higher returns"],
            ["Conservative", "Minimizes risk, prioritizing safety, stability, and compliance"],
            ["Neutral", "Balances risk against reward case by case"],
            ["Risk tolerance", "The acceptable deviation from the stated appetite"],
        ],
        "explain": "The three exam-named appetite postures are expansionary (risk-seeking startup), conservative (regulated bank or hospital), and neutral (balanced, measured enterprise). Tolerance is the companion concept: how much practical deviation from the appetite is acceptable.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the elements of the risk management process in their typical order.",
        "items": [
            "Identify risks to the organization's assets",
            "Assess and analyze likelihood and impact",
            "Record each risk in the risk register with an owner",
            "Select a response: transfer, accept, avoid, or mitigate",
            "Report risk posture and monitor against thresholds",
        ],
        "explain": "The cycle runs identify -> assess/analyze -> register -> respond -> report/monitor, and monitoring feeds back into identification. Responses are chosen in light of the organization's risk appetite and tolerance.",
    },
    {
        "type": "order",
        "q": "Arrange the steps of a quantitative risk calculation in order.",
        "items": [
            "Determine the asset value (AV)",
            "Estimate the exposure factor (EF) for the event",
            "Calculate the SLE (AV x EF)",
            "Estimate the ARO (occurrences per year)",
            "Calculate the ALE (SLE x ARO)",
        ],
        "explain": "Quantitative analysis builds from the asset's dollar value: apply the exposure factor to get the per-incident loss (SLE), then apply the annual frequency (ARO) to get the annualized loss (ALE) used to justify control spending.",
    },
]
