TOPIC = {
    "id": "5.3",
    "domain": 5,
    "title": "Explain the processes associated with third-party risk assessment and management.",
    "short": "Third-Party Risk",
}

TERMS = [
    ("Third-party risk", "Risk imported through vendors, suppliers, and service providers; their weaknesses, outages, and breaches become yours"),
    ("Vendor assessment", "Evaluating a third party's security posture before signing and periodically afterward, using tests, audits, and evidence"),
    ("Penetration testing (vendor)", "Authorized simulated attack against a vendor's systems to prove whether their defenses actually hold, beyond self-reported claims"),
    ("Right-to-audit clause", "Contract provision giving the customer the right to examine the vendor's security controls, records, and operations, usually with notice"),
    ("Evidence of internal audits", "The vendor's own audit reports and remediation records; shows self-monitoring but is the least objective form of evidence"),
    ("Independent assessment", "Evaluation performed by an objective third party with no stake in the outcome, e.g., a SOC 2 Type II report or ISO/IEC 27001 certification"),
    ("Supply chain analysis", "Assessing the vendor's own upstream suppliers, components, software dependencies, and subcontractors (fourth-party risk)"),
    ("Vendor selection", "The process of choosing which third party to do business with, driven by due diligence and free of conflicts of interest"),
    ("Due diligence", "Pre-contract investigation of a vendor's financial stability, reputation, breach history, compliance, and security posture"),
    ("Conflict of interest", "A personal or organizational interest that could bias vendor decisions (e.g., owning stock in a bidder); must be disclosed and managed"),
    ("Service-level agreement (SLA)", "Agreement defining specific measurable performance targets (uptime %, response times) and the penalties for missing them"),
    ("Memorandum of understanding (MOU)", "Informal document declaring mutual intent and common goals; broad terms, generally not legally binding"),
    ("Memorandum of agreement (MOA)", "More formal than an MOU; documents the specific responsibilities and actions each party agrees to take"),
    ("Master service agreement (MSA)", "Umbrella/framework contract establishing general terms for a long-term relationship; individual jobs are added under it"),
    ("Work order (WO)/statement of work (SOW)", "Document issued under an MSA defining one specific project: scope, deliverables, timeline, milestones, payment"),
    ("Non-disclosure agreement (NDA)", "Legally binds one or both parties to keep shared confidential information secret; can be unilateral or mutual"),
    ("Business partners agreement (BPA)", "Governs a business partnership: responsibilities, investment, division of profits and losses, decision-making, exit terms"),
    ("Vendor monitoring", "Ongoing review of a vendor throughout the relationship: SLA/KPI tracking, periodic reassessment, and watching external risk signals"),
    ("Questionnaire", "Standardized set of security/compliance questions vendors answer during selection and periodically after; self-reported, so verify key claims"),
    ("Rules of engagement", "Ground rules for an assessment such as a penetration test: scope, timing, allowed techniques, communication, and authorization"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A contract with a cloud provider guarantees 99.9% uptime and a 4-hour incident response time, with service credits owed if either target is missed. Which agreement defines these terms?",
        "choices": ["Memorandum of understanding (MOU)", "Service-level agreement (SLA)", "Business partners agreement (BPA)", "Statement of work (SOW)"],
        "answer": 1,
        "explain": "An SLA sets specific, measurable performance targets — uptime percentages, response times — and the remedies or penalties for missing them. An MOU is a non-binding statement of intent, a BPA governs a business partnership, and a SOW defines one project's deliverables.",
    },
    {
        "type": "mc",
        "q": "A company and an IT consultancy sign one overarching contract covering payment terms, liability, and confidentiality for their long-term relationship, so future projects will not need those terms renegotiated. Which agreement is this?",
        "choices": ["Service-level agreement (SLA)", "Statement of work (SOW)", "Master service agreement (MSA)", "Memorandum of understanding (MOU)"],
        "answer": 2,
        "explain": "A master service agreement (MSA) is the umbrella/framework contract that establishes the general terms of a long-term relationship once. Each individual project is then authorized by a work order or statement of work issued under the MSA.",
    },
    {
        "type": "mc",
        "q": "Under an existing master service agreement, a client authorizes a network-upgrade project by signing a document listing that project's scope, deliverables, milestones, timeline, and price. Which document is this?",
        "choices": ["Work order/statement of work (WO/SOW)", "Business partners agreement (BPA)", "Memorandum of agreement (MOA)", "Non-disclosure agreement (NDA)"],
        "answer": 0,
        "explain": "A work order (WO) or statement of work (SOW) defines one specific project under the MSA: its scope, deliverables, milestones, schedule, and payment. The MSA is the long-term framework; each SOW/WO is a single job executed within it.",
    },
    {
        "type": "mc",
        "q": "Before demonstrating an unreleased product to a potential manufacturing partner, a company requires the partner to sign a document legally obligating it to keep the design details secret. Which agreement is this?",
        "choices": ["Memorandum of understanding (MOU)", "Service-level agreement (SLA)", "Business partners agreement (BPA)", "Non-disclosure agreement (NDA)"],
        "answer": 3,
        "explain": "A non-disclosure agreement (NDA) legally binds a party to keep shared confidential information secret. NDAs can be unilateral or mutual, are commonly signed before sensitive discussions begin, and their obligations typically survive the end of the relationship.",
    },
    {
        "type": "mc",
        "q": "Two companies launch a joint venture and sign an agreement defining each party's responsibilities, investment shares, how profits and losses are divided, and how decisions will be made. Which agreement is this?",
        "choices": ["Business partners agreement (BPA)", "Master service agreement (MSA)", "Service-level agreement (SLA)", "Memorandum of understanding (MOU)"],
        "answer": 0,
        "explain": "A business partners agreement (BPA) governs entities going into business together: roles, investment, profit/loss division, decision-making, and exit terms. Profit-and-loss sharing between partners is the giveaway — no customer-vendor agreement covers that.",
    },
    {
        "type": "mc",
        "q": "Two organizations draft an informal document stating their shared goals and intention to collaborate. It sketches broad terms but is generally not legally binding. Which agreement is this?",
        "choices": ["Memorandum of agreement (MOA)", "Memorandum of understanding (MOU)", "Master service agreement (MSA)", "Service-level agreement (SLA)"],
        "answer": 1,
        "explain": "A memorandum of understanding (MOU) declares mutual intent and common goals in broad, informal terms and is generally not legally binding — a handshake on paper. An MOA is the more formal next step that documents each party's specific responsibilities.",
    },
    {
        "type": "mc",
        "q": "Two agencies move beyond a statement of intent and sign a more formal document that spells out the specific responsibilities and actions each party agrees to take. Which agreement is this?",
        "choices": ["Memorandum of understanding (MOU)", "Non-disclosure agreement (NDA)", "Memorandum of agreement (MOA)", "Statement of work (SOW)"],
        "answer": 2,
        "explain": "A memorandum of agreement (MOA) is more formal than an MOU: it documents the specific responsibilities and actions each party will take, rather than just broad intent. MOU = understanding/intent; MOA = agreement/defined responsibilities.",
    },
    {
        "type": "mc",
        "q": "A security team wants the contractual ability to inspect a vendor's security controls, records, and operations itself in the future, with 30 days' notice. What should be negotiated into the contract?",
        "choices": ["A right-to-audit clause", "A memorandum of understanding", "A questionnaire requirement", "Rules of engagement"],
        "answer": 0,
        "explain": "A right-to-audit clause is a contract provision giving the customer the right to audit the vendor's operations directly (or via a designated auditor), usually with defined notice. It preserves the ability to verify compliance instead of trusting the vendor's word.",
    },
    {
        "type": "mc",
        "q": "During assessment, a vendor provides a current SOC 2 Type II report prepared by an accredited external auditing firm. Which vendor assessment method is this?",
        "choices": ["Evidence of internal audits", "Independent assessment", "Supply chain analysis", "Questionnaire"],
        "answer": 1,
        "explain": "An independent assessment is performed by a qualified third party with no stake in the outcome — a SOC 2 report or ISO/IEC 27001 certification are classic examples. Because the assessor is external and objective, it carries more weight than the vendor's own audit reports.",
    },
    {
        "type": "mc",
        "q": "A prospective vendor shares reports produced by its own audit team, showing the control gaps it found in itself and the remediation it performed. Which vendor assessment method is this?",
        "choices": ["Independent assessment", "Penetration testing", "Evidence of internal audits", "Right-to-audit clause"],
        "answer": 2,
        "explain": "Evidence of internal audits is the vendor's own self-examination — its internal audit reports, findings, and remediation records. It shows the vendor monitors itself, but because the vendor is grading its own homework it is the least objective form of assessment evidence.",
    },
    {
        "type": "mc",
        "q": "Before signing with a payment processor, a company requires the processor to undergo an authorized simulated attack against its systems and to share the results. Which vendor assessment method is this?",
        "choices": ["Penetration testing", "Supply chain analysis", "Due diligence", "Vendor monitoring"],
        "answer": 0,
        "explain": "A penetration test is an authorized simulated attack that proves whether the vendor's defenses actually hold, going beyond documentation and self-reported claims. Because it actively probes systems, it must be governed by agreed rules of engagement.",
    },
    {
        "type": "mc",
        "q": "A hardware manufacturer is being evaluated, and the customer investigates where the manufacturer sources its chips, which software libraries it builds on, and which subcontractors handle customer data. Which assessment activity is this?",
        "choices": ["Evidence of internal audits", "Conflict of interest review", "Independent assessment", "Supply chain analysis"],
        "answer": 3,
        "explain": "Supply chain analysis evaluates the vendor's own upstream dependencies — component sources, software libraries, service providers, and subcontractors (fourth parties). Risks include counterfeit or tampered hardware and subcontractors weaker than the vendor itself.",
    },
    {
        "type": "mc",
        "q": "Before signing a contract, a company verifies a vendor's financial stability, checks references and breach history, and reviews its regulatory compliance record. What is this process called?",
        "choices": ["Vendor monitoring", "Due diligence", "Supply chain analysis", "Rules of engagement"],
        "answer": 1,
        "explain": "Due diligence is the pre-contract investigation of a vendor: financial viability, reputation, breach and litigation history, compliance, and security posture. Vendor monitoring is the ongoing, post-contract version of the same discipline.",
    },
    {
        "type": "mc",
        "q": "A procurement manager scoring vendor bids owns a significant amount of stock in one of the bidding vendors. What does this situation represent?",
        "choices": ["A conflict of interest", "Due diligence", "A right-to-audit issue", "A supply chain vulnerability"],
        "answer": 0,
        "explain": "A conflict of interest is a personal or organizational interest that could compromise objective judgment in vendor decisions — such as owning stock in a bidder. Conflicts must be disclosed and managed, typically by recusing the conflicted person from the decision.",
    },
    {
        "type": "mc",
        "q": "A year into a contract, a company tracks the vendor's actual uptime against SLA targets, re-issues its security questionnaire, and requests the vendor's newest SOC 2 report. Which process is this?",
        "choices": ["Vendor selection", "Due diligence", "Vendor monitoring", "Supply chain analysis"],
        "answer": 2,
        "explain": "Vendor monitoring is the ongoing, continuous review of a vendor throughout the relationship: tracking SLA/KPI compliance, periodic reassessment (questionnaires, updated independent assessments), and watching external risk signals. Signing the contract is the beginning, not the end.",
    },
    {
        "type": "mc",
        "q": "To compare several candidate vendors on equal footing, a company sends each one the same standardized set of questions about encryption, access control, incident response, and compliance. Which tool is being used?",
        "choices": ["Rules of engagement", "A questionnaire", "A right-to-audit clause", "A statement of work"],
        "answer": 1,
        "explain": "Questionnaires are standardized sets of security and compliance questions used during selection (and periodically afterward during monitoring). They are efficient and let candidates be compared consistently — but the answers are self-reported.",
    },
    {
        "type": "mc",
        "q": "What is the main limitation of relying on vendor security questionnaires alone?",
        "choices": ["They are legally binding on both parties", "The answers are self-reported and may need independent verification", "They can only be used after the contract is signed", "They automatically expire after 30 days"],
        "answer": 1,
        "explain": "Questionnaire answers are self-attestation — the vendor describes its own practices. For higher-risk relationships those claims should be verified through independent assessments, audits, or testing. Questionnaires are not contracts, are usable pre- and post-contract, and have no fixed expiry.",
    },
    {
        "type": "mc",
        "q": "Before a penetration test of a vendor-hosted portal, both parties sign a document defining which systems are in scope, the approved testing window, forbidden techniques, and emergency contacts. What is this document?",
        "choices": ["A service-level agreement", "A memorandum of understanding", "The rules of engagement", "A business partners agreement"],
        "answer": 2,
        "explain": "Rules of engagement define how an assessment is allowed to happen: scope, timing, permitted techniques, communication and escalation, and written authorization. They protect the testers (documented permission) and the organization (no surprises).",
    },
    {
        "type": "mc",
        "q": "Which of the following agreement types is generally NOT legally binding?",
        "choices": ["Service-level agreement (SLA)", "Non-disclosure agreement (NDA)", "Master service agreement (MSA)", "Memorandum of understanding (MOU)"],
        "answer": 3,
        "explain": "An MOU is an informal declaration of mutual intent and common goals — generally not legally binding or enforceable. SLAs, NDAs, and MSAs are contracts: an SLA has enforceable performance targets, an NDA has enforceable confidentiality duties, and an MSA sets binding relationship terms.",
    },
    {
        "type": "mc",
        "q": "A vendor was thoroughly vetted at selection, but two years later it suffers layoffs, an ownership change, and a publicized breach. Which process is designed to catch this change in risk?",
        "choices": ["Due diligence", "Vendor monitoring", "Conflict of interest disclosure", "Supply chain analysis"],
        "answer": 1,
        "explain": "Vendor monitoring watches the vendor for as long as the relationship lasts — SLA metrics plus external signals like breaches, financial trouble, ownership changes, and layoffs. Due diligence is the one-time pre-contract investigation; a vendor secure at selection can drift into weakness.",
    },
    {
        "type": "mc",
        "q": "An attacker compromises a small HVAC contractor and uses the contractor's remote access to breach a large retailer's network. Which risk category does this illustrate?",
        "choices": ["Conflict of interest", "Third-party (vendor) risk", "Service-level violation", "Insider threat"],
        "answer": 1,
        "explain": "This is third-party risk: every vendor you connect to or share access with extends your attack surface, and attackers routinely compromise a weaker supplier to pivot into the real target. It is why vendor assessment, agreements, and ongoing monitoring exist.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A service-level agreement (SLA) defines specific measurable performance targets, such as uptime percentage and response time, and the penalties for missing them.",
        "answer": True,
        "explain": "The SLA turns service quality into numbers — uptime, response and resolution times — plus remedies (credits, penalties, termination rights) when targets are missed. SLA metrics are also the primary yardstick used during vendor monitoring.",
    },
    {
        "type": "tf",
        "q": "True or False: A memorandum of understanding (MOU) is a formal, legally binding contract with enforceable financial penalties.",
        "answer": False,
        "explain": "An MOU is the opposite: an informal declaration of mutual intent and common goals that is generally not legally binding. Enforceable performance penalties belong in an SLA; binding relationship terms belong in contracts such as an MSA.",
    },
    {
        "type": "tf",
        "q": "True or False: A right-to-audit clause is a contract provision that lets the customer examine the vendor's security controls, records, and operations.",
        "answer": True,
        "explain": "The right-to-audit clause is written into the agreement and preserves the customer's ability to verify the vendor's compliance directly (or through a designated auditor), usually with defined notice, instead of relying on the vendor's own claims.",
    },
    {
        "type": "tf",
        "q": "True or False: An independent assessment is an evaluation of the vendor performed by the vendor's own internal audit team.",
        "answer": False,
        "explain": "That describes evidence of internal audits — the vendor's self-assessment. An independent assessment is performed by an objective external third party (e.g., a SOC 2 Type II report or ISO/IEC 27001 certification) and therefore carries more assurance.",
    },
    {
        "type": "tf",
        "q": "True or False: Once the vendor contract is signed, third-party risk management for that vendor is complete.",
        "answer": False,
        "explain": "Signing is the beginning, not the end. Vendor monitoring continues throughout the relationship: tracking SLA compliance, periodically reassessing with questionnaires and updated independent assessments, and watching external signals like breaches or financial trouble.",
    },
    {
        "type": "tf",
        "q": "True or False: A non-disclosure agreement can be mutual, binding both parties to protect the information each shares with the other.",
        "answer": True,
        "explain": "NDAs can be unilateral (one party discloses, the other must protect) or mutual/bilateral (both share and both protect). Confidentiality obligations typically survive the end of the business relationship.",
    },
    {
        "type": "tf",
        "q": "True or False: Rules of engagement for a penetration test specify which systems may be tested, when testing may occur, and which techniques are off-limits.",
        "answer": True,
        "explain": "Rules of engagement set the ground rules before active work begins: scope (systems in and out), timing windows, allowed and forbidden techniques, communication and escalation contacts, and written authorization — protecting both the testers and the organization.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The agreement that guarantees measurable targets like 99.9% uptime and defines penalties for missing them is the ______. (type the abbreviation)",
        "answers": ["sla", "service-level agreement", "service level agreement"],
        "explain": "The service-level agreement (SLA) defines specific, measurable performance expectations — uptime, response times, resolution times — and the remedies owed when the vendor misses them. It is the agreement to name whenever a scenario quotes performance numbers.",
    },
    {
        "type": "fill",
        "q": "The umbrella contract that establishes general terms for a long-term vendor relationship, with individual projects added later, is the ______. (type the abbreviation)",
        "answers": ["msa", "master service agreement", "master services agreement"],
        "explain": "The master service agreement (MSA) settles the general terms — payment, liability, confidentiality, security requirements — once. Each individual project is then authorized by a work order/statement of work (WO/SOW) issued under the MSA.",
    },
    {
        "type": "fill",
        "q": "The agreement that legally binds parties to keep shared confidential information secret is the ______. (type the abbreviation)",
        "answers": ["nda", "non-disclosure agreement", "nondisclosure agreement", "non disclosure agreement"],
        "explain": "The non-disclosure agreement (NDA) creates enforceable confidentiality obligations, can be unilateral or mutual, and is often signed before vendor evaluation even begins so sensitive information can be shared safely during discussions.",
    },
    {
        "type": "fill",
        "q": "Investigating a vendor's financial stability, reputation, breach history, and security posture before signing a contract is called due ______. (type your answer)",
        "answers": ["diligence", "due diligence"],
        "explain": "Due diligence is the pre-contract investigation that turns a sales pitch into documented, evidence-based confidence. Its post-contract counterpart is vendor monitoring, which continues the same scrutiny throughout the relationship.",
    },
    {
        "type": "fill",
        "q": "The contract provision that gives a customer the ability to inspect a vendor's operations, controls, and records is the right-to-______ clause. (type your answer)",
        "answers": ["audit", "right to audit", "right-to-audit"],
        "explain": "The right-to-audit clause is negotiated into the agreement and lets the customer (or a designated auditor) verify the vendor's compliance directly, usually with defined notice and frequency. A vendor that refuses one is a red flag.",
    },
    {
        "type": "fill",
        "q": "The document defining the scope, timing, allowed techniques, and authorization for a penetration test is called the rules of ______. (type your answer)",
        "answers": ["engagement", "rules of engagement", "roe"],
        "explain": "Rules of engagement (ROE) are the agreed ground rules for an active assessment: what may be tested, when, how, who to contact, and the written permission that makes the test legal. They protect both the testers and the organization being tested.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each agreement type to its description.",
        "pairs": [
            ["SLA", "Measurable performance targets (uptime, response time) with penalties"],
            ["MOU", "Informal statement of mutual intent; generally not legally binding"],
            ["MSA", "Umbrella contract setting general terms for a long-term relationship"],
            ["SOW", "Defines one specific project's scope, deliverables, timeline, and price"],
            ["NDA", "Binds parties to keep shared confidential information secret"],
        ],
        "explain": "SLA = enforceable performance numbers; MOU = broad non-binding intent; MSA = the long-term framework contract; SOW/WO = one job executed under the MSA; NDA = confidentiality, unilateral or mutual.",
    },
    {
        "type": "match",
        "q": "Match each vendor assessment method to its description.",
        "pairs": [
            ["Penetration testing", "Authorized simulated attack proving the vendor's defenses hold"],
            ["Right-to-audit clause", "Contract provision letting the customer inspect the vendor"],
            ["Evidence of internal audits", "Vendor's own audit reports; least objective evidence"],
            ["Independent assessment", "Objective third-party evaluation such as a SOC 2 report"],
            ["Supply chain analysis", "Review of the vendor's own suppliers and dependencies"],
        ],
        "explain": "Pen tests demonstrate real-world resilience; the right-to-audit clause preserves your ability to verify; internal audit evidence is self-assessment; independent assessments come from external auditors; supply chain analysis follows risk upstream to fourth parties.",
    },
    {
        "type": "match",
        "q": "Match each third-party risk concept to its description.",
        "pairs": [
            ["Due diligence", "Pre-contract investigation of a vendor's stability and posture"],
            ["Conflict of interest", "Personal stake that could bias a vendor decision"],
            ["Vendor monitoring", "Ongoing post-contract tracking of performance and risk"],
            ["Questionnaire", "Standardized self-reported security answers from the vendor"],
            ["Rules of engagement", "Ground rules for scope and timing of an assessment"],
        ],
        "explain": "Due diligence happens before signing; conflicts of interest must be disclosed and managed; monitoring continues for the life of the relationship; questionnaires are efficient but self-attested; rules of engagement bound active assessments like penetration tests.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps of establishing and managing a vendor relationship in typical order.",
        "items": [
            "Sign an NDA so sensitive information can be shared during evaluation",
            "Perform due diligence and send security questionnaires to candidates",
            "Sign the master service agreement (MSA) establishing general terms",
            "Issue a work order/SOW defining the first project's deliverables",
            "Monitor vendor performance against SLA targets throughout the relationship",
        ],
        "explain": "Confidentiality (NDA) comes first so candidates can be evaluated with real information; due diligence and questionnaires drive selection; the MSA frames the relationship; each project is authorized by a SOW/WO under it; and vendor monitoring against SLA metrics continues for the life of the contract.",
    },
]
