TOPIC = {
    "id": "5.5",
    "domain": 5,
    "title": "Explain types and purposes of audits and assessments.",
    "short": "Audits & Assessments",
}

TERMS = [
    ("Attestation", "Formal declaration by a responsible party that controls or reports are accurate and effective; e.g., an executive signing off under SOX or a CPA firm issuing a SOC 2 opinion"),
    ("Internal audit", "Review performed by the organization's own personnel; cheaper and continuous but less independent than an external review"),
    ("Internal compliance", "Internal function that verifies the organization follows its own policies plus external legal, regulatory, and contractual requirements"),
    ("Audit committee", "Subgroup of the board of directors that oversees audit and compliance activity; commissions audits and receives results but does not perform them"),
    ("Self-assessment", "A team's checklist-based review of its own controls against a standard; good audit preparation but the least independent review type"),
    ("External audit", "Review performed by parties outside the organization; more expensive but independent, so its results are credible to customers and regulators"),
    ("Regulatory audit", "Audit required by law or regulation (e.g., HIPAA, SOX, GLBA) and conducted by or for the regulating authority; failure can bring fines or sanctions"),
    ("Examination", "Formal inspection by an external authority — e.g., a government bank examiner reviewing a financial institution's records and practices"),
    ("Assessment (external)", "In-depth analysis by an outside party to identify gaps and recommend improvements; advisory, with no formal pass/fail opinion"),
    ("Independent third-party audit", "Audit by an unaffiliated outside firm with no stake in the outcome (e.g., SOC 2, ISO 27001); the most trusted form of assurance"),
    ("Penetration testing", "Authorized simulated attack that actively exploits weaknesses to demonstrate real-world impact, governed by written rules of engagement"),
    ("Physical penetration testing", "Testing facility security via tailgating, badge cloning, lock picking, and dumpster diving rather than attacking the network"),
    ("Offensive testing (red team)", "Attack-side testing that emulates real adversaries: reconnaissance, exploitation, persistence, and exfiltration"),
    ("Defensive testing (blue team)", "Defense-side exercise measuring how well the organization detects, responds to, and contains attacks"),
    ("Integrated testing (purple team)", "Offense and defense working together in a real-time feedback loop: red runs a technique, blue verifies detection, gaps get fixed"),
    ("Known environment", "Pen test where testers get full knowledge — diagrams, documentation, credentials; legacy name: white box"),
    ("Partially known environment", "Pen test where testers get some information (e.g., IP ranges or a user account) but not full internals; legacy name: gray box"),
    ("Unknown environment", "Pen test where testers start with no information, like a real outside attacker; legacy name: black box"),
    ("Passive reconnaissance", "Gathering target information from public sources (WHOIS, DNS records, social media, job postings) without directly interacting with target systems"),
    ("Active reconnaissance", "Directly probing the target — ping sweeps, port scans, banner grabbing, vulnerability scans; detailed but detectable"),
    ("Rules of engagement", "Written scope, targets, timing, and permissions agreed before a penetration test; the authorization that separates testing from crime"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "Under Sarbanes-Oxley, a company's CFO formally signs a statement taking personal responsibility for the accuracy of the company's financial reports and the internal controls behind them. What is this signed declaration called?",
        "choices": ["Attestation", "Self-assessment", "Examination", "Due diligence"],
        "answer": 0,
        "explain": "Attestation is a formal declaration by a responsible party that controls or reports are accurate — the signer puts their name and liability behind the claim. A self-assessment is a team grading its own controls, and an examination is an inspection by an external authority.",
    },
    {
        "type": "mc",
        "q": "A company's own compliance staff continuously verify that password policies are enforced, access reviews are performed, and required training is completed, checking against both internal policy and applicable regulations. Which review type is this?",
        "choices": ["Independent third-party audit", "Internal compliance review", "Regulatory audit", "Examination"],
        "answer": 1,
        "explain": "An internal compliance function uses the organization's own personnel to verify adherence to internal policies and external requirements on an ongoing basis. Regulatory audits and examinations are conducted by outside authorities, and a third-party audit uses an unaffiliated firm.",
    },
    {
        "type": "mc",
        "q": "Which body is a subgroup of the board of directors responsible for overseeing an organization's audit and compliance activities, receiving audit results, and ensuring findings are remediated?",
        "choices": ["The internal audit team", "The compliance department", "The audit committee", "The change advisory board"],
        "answer": 2,
        "explain": "The audit committee is a board subgroup that oversees audit activity — it commissions audits, selects external auditors, and reviews results, but does not perform audits itself. Internal auditors report to it, which is what preserves their independence from management.",
    },
    {
        "type": "mc",
        "q": "Before an upcoming PCI DSS engagement, a payment team walks through the official Self-Assessment Questionnaire and scores its own compliance with each requirement. Which type of review is this?",
        "choices": ["Self-assessment", "Independent third-party audit", "Examination", "Attestation"],
        "answer": 0,
        "explain": "A self-assessment is a review a team performs on itself against a checklist or standard — inexpensive and great audit preparation, but the least independent review type because the assessors grade their own work. Outside parties rarely accept it as proof on its own.",
    },
    {
        "type": "mc",
        "q": "A hospital undergoes a mandatory audit of its handling of protected health information because HIPAA requires it. Which audit type does this BEST describe?",
        "choices": ["Self-assessment", "Internal compliance review", "Regulatory audit", "Voluntary external assessment"],
        "answer": 2,
        "explain": "A regulatory audit is required by law or regulation — HIPAA, SOX, and GLBA are classic examples — and is conducted by or on behalf of the regulating authority. It is not optional, and failing it can bring fines, sanctions, or loss of the ability to operate.",
    },
    {
        "type": "mc",
        "q": "Government examiners arrive at a bank, some visits unannounced, to formally inspect its records, practices, and controls. The bank has no say in the scope or timing. Which external review type is this?",
        "choices": ["Assessment", "Examination", "Self-assessment", "Penetration test"],
        "answer": 1,
        "explain": "An examination is a formal inspection by an external authority — bank examiners are the classic case. Examinations are typically regulator-driven, broad, and may be unannounced. An assessment, by contrast, is voluntary, advisory, and scoped by the organization that requests it.",
    },
    {
        "type": "mc",
        "q": "A company hires an outside consulting firm to evaluate its security program against the NIST Cybersecurity Framework and deliver a gap analysis with an improvement roadmap — no formal pass/fail opinion. Which review type is this?",
        "choices": ["An external assessment", "A regulatory audit", "An examination", "An attestation"],
        "answer": 0,
        "explain": "An external assessment is an in-depth, voluntary analysis by an outside party aimed at identifying gaps and recommending improvements rather than issuing a formal verdict. Audits and examinations are evidence-driven and verdict-oriented; attestation is a signed declaration of accuracy.",
    },
    {
        "type": "mc",
        "q": "A cloud provider wants a single formal report it can hand to thousands of customers as trusted proof of its security controls, so it engages an unaffiliated CPA firm to perform a SOC 2 audit. Which review type is this?",
        "choices": ["Self-assessment", "Internal compliance review", "Examination", "Independent third-party audit"],
        "answer": 3,
        "explain": "An independent third-party audit is performed by an unaffiliated outside firm with no stake in the outcome, which is exactly why customers and partners trust the resulting report. SOC 2 and ISO 27001 certification audits are the standard examples.",
    },
    {
        "type": "mc",
        "q": "What is the PRIMARY advantage of an independent third-party audit over a self-assessment?",
        "choices": ["It is cheaper and faster to perform", "Its independence makes the results credible to outside parties", "It never requires evidence collection", "It can only be performed by government regulators"],
        "answer": 1,
        "explain": "Because third-party auditors are unaffiliated and follow professional standards, their opinion carries credibility a self-assessment cannot — customers and regulators can rely on it. It is slower and more expensive than self-assessment, requires extensive evidence, and is performed by private firms, not only regulators.",
    },
    {
        "type": "mc",
        "q": "What is the key distinction between an INTERNAL and an EXTERNAL audit?",
        "choices": ["Whether the audit is technical or procedural", "Who performs the audit", "Whether findings are documented", "How long the audit takes"],
        "answer": 1,
        "explain": "The internal/external split is about who performs the review: internal audits use the organization's own personnel, while external audits are performed by outside parties such as regulators, examiners, or independent firms. Both document findings and can cover technical and procedural controls.",
    },
    {
        "type": "mc",
        "q": "During an authorized engagement, a tester tailgates an employee through a badge-controlled door, clones an access badge, and retrieves sensitive documents from a dumpster. Which type of penetration testing is this?",
        "choices": ["Defensive", "Integrated", "Physical", "Offensive network testing"],
        "answer": 2,
        "explain": "Physical penetration testing targets the facility rather than the network: tailgating, badge cloning, lock picking, and dumpster diving all test whether an attacker can simply walk in. Offensive network testing attacks systems remotely, and defensive testing exercises detection and response.",
    },
    {
        "type": "mc",
        "q": "A red team emulates a real adversary over several weeks — performing reconnaissance, exploiting systems, establishing persistence, and attempting data exfiltration. Which penetration testing approach is this?",
        "choices": ["Offensive", "Defensive", "Integrated", "Physical"],
        "answer": 0,
        "explain": "Offensive testing is attack-side work performed by the red team, emulating real adversaries end to end. Defensive (blue team) testing measures detection and response, integrated (purple team) testing combines both sides cooperatively, and physical testing targets the facility.",
    },
    {
        "type": "mc",
        "q": "An exercise focuses on how well the security operations team detects, responds to, and contains simulated attacks — testing monitoring, alerting, and incident response. Which penetration testing approach is being exercised?",
        "choices": ["Offensive", "Unknown environment", "Physical", "Defensive"],
        "answer": 3,
        "explain": "Defensive testing exercises the blue team — the protection side — measuring whether alarms actually ring and responders actually respond. Offensive testing is the attacking red team, and 'unknown environment' describes how much knowledge testers start with, not which side is exercised.",
    },
    {
        "type": "mc",
        "q": "During an exercise, the attacking team runs a technique, the defending team immediately checks whether it was detected, detection gaps are fixed, and the technique is run again — a continuous real-time feedback loop. Which testing approach is this?",
        "choices": ["Offensive", "Defensive", "Integrated", "Regulatory"],
        "answer": 2,
        "explain": "Integrated testing — commonly called purple teaming — combines offensive and defensive work in a cooperative loop, improving detection in real time instead of delivering a report weeks later. Pure offensive or defensive exercises keep the two sides separate.",
    },
    {
        "type": "mc",
        "q": "Before a penetration test, the testers are given full network diagrams, system documentation, source code, and administrative credentials. Which test environment is this?",
        "choices": ["Unknown environment", "Known environment", "Partially known environment", "Integrated environment"],
        "answer": 1,
        "explain": "A known environment (legacy term: white box) gives testers full knowledge, simulating a malicious insider and maximizing depth and coverage per hour of testing. Partially known provides only some information, and unknown provides none.",
    },
    {
        "type": "mc",
        "q": "Penetration testers are given the target's external IP ranges and one standard user account, but no documentation or internal details. Which test environment is this?",
        "choices": ["Known environment", "Unknown environment", "Partially known environment", "Physical environment"],
        "answer": 2,
        "explain": "A partially known environment (legacy term: gray box) gives testers some information — such as IP ranges or a standard user account — but not full internals, simulating an attacker with limited inside knowledge or a compromised user.",
    },
    {
        "type": "mc",
        "q": "A company hires testers and gives them nothing but the company name — no IP ranges, no documentation, no credentials — to simulate a real external attacker as realistically as possible. Which test environment is this?",
        "choices": ["Unknown environment", "Known environment", "Partially known environment", "Defensive environment"],
        "answer": 0,
        "explain": "An unknown environment (legacy term: black box) starts testers from scratch like a real outsider — the most realistic simulation of an external attack, but the slowest, and it may miss flaws that a known-environment test would find quickly.",
    },
    {
        "type": "mc",
        "q": "Which legacy term corresponds to a 'partially known environment' penetration test?",
        "choices": ["White box", "Black box", "Gray box", "Purple box"],
        "answer": 2,
        "explain": "Partially known = gray box: testers get some knowledge but not everything. Known environment maps to white box (full knowledge) and unknown environment maps to black box (no knowledge). 'Purple' refers to integrated purple teaming, not a knowledge level.",
    },
    {
        "type": "mc",
        "q": "Before attacking, a tester researches the target using WHOIS records, public DNS data, the company website, employee LinkedIn profiles, and job postings that reveal the technology stack — never sending a single packet to the target's systems. Which activity is this?",
        "choices": ["Active reconnaissance", "Passive reconnaissance", "Vulnerability scanning", "Exploitation"],
        "answer": 1,
        "explain": "Passive reconnaissance gathers information from public sources without directly interacting with the target's systems, which makes it essentially undetectable. Active reconnaissance — ping sweeps, port scans, vulnerability scans — probes the target directly and can be detected and logged.",
    },
    {
        "type": "mc",
        "q": "A penetration tester runs Nmap port scans and ping sweeps against the target's public IP range to identify live hosts, open ports, and service versions. Which activity is this?",
        "choices": ["Passive reconnaissance", "Attestation", "Active reconnaissance", "Self-assessment"],
        "answer": 2,
        "explain": "Active reconnaissance directly probes the target — port scanning, ping sweeps, banner grabbing, vulnerability scanning. It yields far more detail than passive methods, but every probe touches the target's systems and can therefore be detected and logged.",
    },
    {
        "type": "mc",
        "q": "What is the MAIN drawback of active reconnaissance compared with passive reconnaissance?",
        "choices": ["It gathers less detailed information", "It can be detected and logged by the target", "It requires no authorization", "It only works from inside the network"],
        "answer": 1,
        "explain": "Active reconnaissance sends traffic to the target, so IDS/IPS and logging can detect it — passive reconnaissance never touches the target and is essentially undetectable. Active recon actually gathers more detail, still requires authorization in a pen test, and works from outside.",
    },
    {
        "type": "mc",
        "q": "How does a penetration test fundamentally differ from a vulnerability scan?",
        "choices": ["A penetration test actively exploits weaknesses to demonstrate real impact", "A penetration test is always performed without authorization", "A vulnerability scan requires physical access to the facility", "A penetration test cannot be performed by external parties"],
        "answer": 0,
        "explain": "A vulnerability scan only identifies potential weaknesses; a penetration test goes further and actively exploits them to prove what an attacker could actually accomplish. Pen tests always require written authorization (rules of engagement) and are very commonly performed by external firms.",
    },
    {
        "type": "mc",
        "q": "Before a penetration test begins, the testers and the organization agree in writing on scope, targets, timing windows, and permitted techniques. What is this document called?",
        "choices": ["Attestation letter", "Rules of engagement", "Audit charter", "Statement of applicability"],
        "answer": 1,
        "explain": "The rules of engagement define the authorized scope, targets, timing, and permissions for a penetration test — the written authorization that separates a legal test from a crime. An attestation letter is a signed declaration of accuracy, unrelated to test scoping.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST describes the purpose of the audit committee with respect to audits?",
        "choices": ["It performs the technical testing during internal audits", "It oversees audit activity on behalf of the board and reviews the results", "It conducts regulatory examinations of other companies", "It replaces the need for external auditors"],
        "answer": 1,
        "explain": "The audit committee provides oversight on behalf of the board of directors: it commissions audits, oversees the internal audit function, selects and communicates with external auditors, and ensures findings are remediated. It does not perform audits or replace external auditors.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Passive reconnaissance involves directly probing the target's systems with tools such as port scanners.",
        "answer": False,
        "explain": "That describes active reconnaissance. Passive reconnaissance gathers information from public sources — WHOIS, DNS records, social media, job postings — without directly interacting with the target's systems, which is why it is essentially undetectable.",
    },
    {
        "type": "tf",
        "q": "True or False: An unknown environment penetration test corresponds to the legacy term 'black box,' where testers begin with no knowledge of the target.",
        "answer": True,
        "explain": "Unknown environment = black box: testers start from scratch like a real external attacker. Known environment maps to white box (full knowledge) and partially known environment maps to gray box (some knowledge).",
    },
    {
        "type": "tf",
        "q": "True or False: An internal audit is performed by the organization's own personnel.",
        "answer": True,
        "explain": "Internal reviews — compliance monitoring, self-assessments, internal audits — are performed by the organization's own staff. They are cheaper and can run continuously, but they lack the independence that makes external audit results credible to outside parties.",
    },
    {
        "type": "tf",
        "q": "True or False: An independent third-party audit is conducted by the organization's own internal audit department.",
        "answer": False,
        "explain": "An independent third-party audit is performed by an unaffiliated outside firm — the auditors are not employees and do not report to management. That independence is precisely what makes the report trustworthy to customers, partners, and regulators.",
    },
    {
        "type": "tf",
        "q": "True or False: Integrated penetration testing, often called purple teaming, combines offensive and defensive activities in a cooperative exercise.",
        "answer": True,
        "explain": "Integrated testing pairs the red (offensive) and blue (defensive) teams in a real-time feedback loop: red runs a technique, blue verifies whether it was detected, gaps are fixed, and the cycle repeats. The mix of red and blue is why it is called purple teaming.",
    },
    {
        "type": "tf",
        "q": "True or False: A regulatory audit is optional, and an organization may decline it without consequence.",
        "answer": False,
        "explain": "Regulatory audits are mandated by law or regulation — HIPAA, SOX, GLBA — and are conducted by or on behalf of the regulating authority. Refusing or failing one can bring fines, sanctions, or loss of the ability to operate. Voluntary reviews are assessments, not regulatory audits.",
    },
    {
        "type": "tf",
        "q": "True or False: The audit committee typically performs the organization's audits itself.",
        "answer": False,
        "explain": "The audit committee oversees audits rather than performing them: it is a board subgroup that commissions audits, reviews results, oversees internal audit, and liaises with external auditors. The actual audit work is done by internal auditors or external firms.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "A formal declaration in which a responsible party certifies that controls or reports are accurate and effective is called ______. (type your answer)",
        "answers": ["attestation", "an attestation"],
        "explain": "Attestation puts a named, accountable party behind a claim — an executive attesting to financial controls under SOX, or a CPA firm attesting to a SOC 2 report. That accountability is what lets outside parties rely on the statement.",
    },
    {
        "type": "fill",
        "q": "The subgroup of the board of directors that oversees an organization's audit and compliance activities is the audit ______. (type your answer)",
        "answers": ["committee", "audit committee"],
        "explain": "The audit committee provides board-level oversight of audit activity: commissioning audits, reviewing results, overseeing internal audit, and selecting external auditors. Internal auditors report to it rather than to management, preserving their independence.",
    },
    {
        "type": "fill",
        "q": "In penetration testing, the attack-side group that emulates real adversaries is known as the ______ team. (type the color)",
        "answers": ["red", "red team"],
        "explain": "The red team performs offensive testing — reconnaissance, exploitation, persistence, exfiltration — emulating a real adversary. The blue team defends, and when the two work together in an integrated exercise it is called purple teaming.",
    },
    {
        "type": "fill",
        "q": "The defensive team that focuses on detecting and responding to attacks during an exercise is known as the ______ team. (type the color)",
        "answers": ["blue", "blue team"],
        "explain": "The blue team is the defensive side — monitoring, alerting, log analysis, and incident response. Defensive testing measures whether attacks are detected and contained, complementing the red team's offensive work.",
    },
    {
        "type": "fill",
        "q": "A penetration test in which testers receive some information about the target, but not full internals, is called a ______ known environment test. (type your answer)",
        "answers": ["partially", "partially known", "partially-known"],
        "explain": "A partially known environment test — legacy term gray box — gives testers limited information such as IP ranges or a standard user account. It sits between known (white box, full knowledge) and unknown (black box, no knowledge).",
    },
    {
        "type": "fill",
        "q": "Gathering information about a target from public sources such as WHOIS, DNS records, and social media without touching the target's systems is called ______ reconnaissance. (type your answer)",
        "answers": ["passive", "passive reconnaissance", "passive recon"],
        "explain": "Passive reconnaissance never interacts directly with the target, so it cannot be detected by the target's monitoring. Active reconnaissance — port scans, ping sweeps, vulnerability scans — probes the target directly and shows up in logs.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each audit or assessment type to its description.",
        "pairs": [
            ["Regulatory audit", "Required by law and conducted by or for the regulating authority"],
            ["Examination", "Formal inspection by an external authority such as a bank examiner"],
            ["External assessment", "Voluntary outside analysis that identifies gaps and recommends improvements"],
            ["Independent third-party audit", "Unaffiliated firm issues a formal report others can trust (e.g., SOC 2)"],
            ["Self-assessment", "A team reviews its own controls against a checklist; least independent"],
        ],
        "explain": "Regulatory audits are legally mandated; examinations are formal regulator-driven inspections; assessments are voluntary and advisory; independent third-party audits provide trusted formal opinions like SOC 2 or ISO 27001; self-assessments are internal checklist reviews with the least independence.",
    },
    {
        "type": "match",
        "q": "Match each penetration testing approach to its description.",
        "pairs": [
            ["Physical", "Tailgating, badge cloning, and lock picking against the facility"],
            ["Offensive", "Red team emulates real adversaries attacking systems"],
            ["Defensive", "Blue team exercises detection, response, and containment"],
            ["Integrated", "Red and blue collaborate in a real-time feedback loop (purple teaming)"],
        ],
        "explain": "Physical testing targets the building; offensive testing is the attacking red team; defensive testing exercises the blue team's detection and response; integrated (purple) testing combines both sides cooperatively so detection gaps get fixed immediately.",
    },
    {
        "type": "match",
        "q": "Match each penetration test environment or reconnaissance type to its description.",
        "pairs": [
            ["Known environment", "Testers receive full documentation and credentials (white box)"],
            ["Partially known environment", "Testers receive limited information such as IP ranges (gray box)"],
            ["Unknown environment", "Testers start with no knowledge of the target (black box)"],
            ["Passive reconnaissance", "Public-source research with no direct contact with the target"],
            ["Active reconnaissance", "Directly probing the target with scans; can be detected"],
        ],
        "explain": "Known/partially known/unknown map to the legacy white/gray/black box terms and describe how much testers know at the start. Passive reconnaissance uses only public sources and is undetectable; active reconnaissance probes the target directly and can be logged.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the phases of a typical penetration test in order, from first to last.",
        "items": [
            "Agree on scope and rules of engagement",
            "Passive reconnaissance from public sources",
            "Active reconnaissance (port and vulnerability scanning)",
            "Exploitation of discovered weaknesses",
            "Reporting findings and remediation recommendations",
        ],
        "explain": "A pen test starts with written authorization (rules of engagement), then gathers intelligence — passive first because it is undetectable, then active probing — before exploiting weaknesses to demonstrate impact and finally reporting findings with remediation guidance.",
    },
]
