TOPIC = {
    "id": "5.6",
    "domain": 5,
    "title": "Given a scenario, implement security awareness practices.",
    "short": "Security Awareness",
}

TERMS = [
    ("Phishing campaign", "Controlled exercise in which the security team sends simulated phishing emails to its own users to measure susceptibility (click rate, report rate) and deliver immediate remedial training to those who fall for it"),
    ("Recognizing a phishing attempt", "Spotting red flags: mismatched/spoofed sender addresses, urgency and threats, generic greetings, hover-revealed suspicious URLs, unexpected attachments, and requests for credentials or payment changes"),
    ("Responding to reported suspicious messages", "Defined workflow: user reports via a report button, security analyzes the message, confirmed-malicious copies are removed and indicators blocked, clickers are identified and credentials reset, and the reporter gets feedback"),
    ("Risky behavior", "Deliberately unsafe (though usually not malicious) user actions: disabling antivirus, installing unauthorized software, plugging in personal USB drives, sharing passwords, bypassing controls to save time"),
    ("Unexpected behavior", "Activity out of pattern for a user or account — logons at odd hours or from unfamiliar locations, impossible travel, access to systems never used before, abnormally large downloads; may signal account compromise"),
    ("Unintentional behavior", "Honest mistakes: emailing a sensitive file to the wrong recipient, losing a device, misconfiguring a share, clicking a phishing link without realizing; met with correction and training, not blame"),
    ("Policy/handbooks", "Written, accessible security expectations — the employee handbook, acceptable use policy (AUP), and related policies — reviewed and acknowledged during onboarding"),
    ("Acceptable use policy (AUP)", "Policy defining how employees may use organizational systems, networks, and data; a core document referenced in security awareness training"),
    ("Situational awareness", "Staying alert to physical and digital surroundings: noticing tailgating, strangers without badges, shoulder surfing, out-of-place USB drives, or oddly behaving systems — and reporting them"),
    ("Insider threat awareness", "Training users to recognize and report indicators of a malicious insider: data hoarding, access attempts beyond the role, repeatedly bypassing controls, unusual hours, expressed disgruntlement"),
    ("Password management", "Modern guidance per NIST SP 800-63B: long unique passphrases (length over complexity), a password manager, MFA everywhere possible, and changing passwords on evidence of compromise rather than on a fixed schedule"),
    ("Password manager", "Application that generates and stores a strong, unique password for every account so users only memorize one master credential"),
    ("Removable media and cables", "Guidance never to plug in found or untrusted USB drives (baiting) or unknown cables/chargers, since malicious cables and drives can inject keystrokes or install malware"),
    ("Juice jacking", "Attack in which a public USB charging port attempts data theft or malware installation; defeated by using an AC wall adapter, battery pack, or USB data blocker"),
    ("Social engineering awareness", "Training to recognize manipulation across channels — phishing, vishing (voice), smishing (SMS), pretexting, impersonation, business email compromise — and to verify unusual requests out-of-band"),
    ("Operational security (OPSEC)", "Viewing day-to-day activity from an adversary's perspective and protecting small, aggregable pieces of information: no badge photos or whiteboards on social media, clean desk, shred documents"),
    ("Hybrid/remote work guidance", "Extra rules for remote workers: change home router defaults and use WPA3/WPA2, use the company VPN on untrusted networks, lock screens, keep family off work devices, mind video-call exposure"),
    ("Initial reporting", "The program's first measurement — the baseline: the first campaign's click rate or first training completion figures, against which all later results are compared"),
    ("Recurring reporting", "Ongoing, repeated measurement — quarterly simulations, annual refresher completion, monthly dashboards — revealing trends and proving the program changes behavior over time"),
    ("Development (awareness program)", "Building the program: define scope and objectives, identify audiences, tailor content to roles and the actual threat landscape, pick metrics, secure executive support (NIST SP 800-50 is common guidance)"),
    ("Execution (awareness program)", "Running the program: onboarding and recurring training, phishing campaigns, continuous reinforcement (newsletters, posters), tracking completion, and feeding results back into the next cycle"),
    ("Clean desk policy", "OPSEC-supporting rule requiring sensitive papers and media to be locked away when unattended so passersby cannot read or take them"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A security team sends its own employees a fake 'password expiration' email. Employees who click the link land on a page explaining the red flags they missed, and the team records who clicked and who reported it. What is this exercise called?",
        "choices": ["A phishing simulation campaign", "A penetration test", "A vulnerability scan", "A tabletop exercise"],
        "answer": 0,
        "explain": "A phishing campaign (simulation) sends controlled fake phishing emails to the organization's own users to measure susceptibility and deliver immediate training. A penetration test exploits technical weaknesses broadly, a vulnerability scan only identifies them, and a tabletop exercise is a discussion-based IR drill.",
    },
    {
        "type": "mc",
        "q": "What is the PRIMARY purpose of running internal phishing simulation campaigns?",
        "choices": ["To identify employees for disciplinary action", "To measure user susceptibility and provide immediate training", "To test whether the email server can handle load", "To collect employee credentials for auditing"],
        "answer": 1,
        "explain": "Campaigns exist to measure real-world susceptibility (click rate, report rate) and to train the users who fall for them at the teachable moment. Punishing or shaming clickers is counterproductive because it discourages the reporting culture the program depends on.",
    },
    {
        "type": "mc",
        "q": "Which two metrics BEST show whether repeated phishing campaigns are improving user behavior over time?",
        "choices": ["Server uptime and patch level", "Click rate and report rate", "Password length and MFA enrollment", "Firewall rule count and IDS alerts"],
        "answer": 1,
        "explain": "A falling click rate (fewer users falling for the simulated phish) and a rising report rate (more users reporting it) are the standard indicators that awareness training is working. The other metrics measure technical posture, not user behavior.",
    },
    {
        "type": "mc",
        "q": "An email's display name reads 'Microsoft Support' but the actual sender address is support@micros0ft-security.com, and the message threatens account closure within 24 hours. Which awareness skill do these clues exercise?",
        "choices": ["Recognizing a phishing attempt", "Password management", "Operational security", "Clean desk compliance"],
        "answer": 0,
        "explain": "A mismatched/spoofed sender domain and manufactured urgency are two classic phishing red flags, along with generic greetings, hover-revealed URLs, unexpected attachments, and credential requests. Recognizing these indicators is a core phishing-awareness skill.",
    },
    {
        "type": "mc",
        "q": "Before clicking a link in an email, a trained user hovers the mouse over it and sees that the destination URL is completely different from the displayed text. What has the user just done?",
        "choices": ["Performed active reconnaissance", "Checked a phishing indicator before acting", "Violated the acceptable use policy", "Executed the link in a sandbox"],
        "answer": 1,
        "explain": "Hovering to reveal the true destination URL is a standard technique for recognizing a phishing attempt — a mismatch between displayed text and the real link is a major red flag. No packet is sent by hovering, and nothing has been executed.",
    },
    {
        "type": "mc",
        "q": "A user clicks the 'Report Phishing' button on a suspicious email. What should the security team do FIRST?",
        "choices": ["Reset every user's password immediately", "Delete the reporting user's mailbox", "Analyze the message to determine whether it is malicious", "Reply to the sender asking them to stop"],
        "answer": 2,
        "explain": "The first step after a report is triage and analysis — examining headers, links, and attachments (in a sandbox) to confirm whether the message is malicious. Containment actions like purging copies, blocking indicators, and resetting affected credentials follow only after confirmation.",
    },
    {
        "type": "mc",
        "q": "The security team confirms a reported email is a real phishing attack that reached 40 mailboxes. Which set of actions is the appropriate response?",
        "choices": ["Remove all copies from mailboxes, block the sender and URLs, and identify users who clicked", "Format the mail server and restore from backup", "Forward the email to all staff as a warning example", "Ignore it, since one user already reported it"],
        "answer": 0,
        "explain": "Once confirmed malicious, the team contains the threat: purge remaining copies from all mailboxes, block the sender/domain/URLs in email filters, then identify anyone who clicked or entered credentials and reset those credentials. Forwarding the live phish would spread the danger.",
    },
    {
        "type": "mc",
        "q": "Why should users who report suspicious messages receive feedback and thanks — even when the message turns out to be harmless?",
        "choices": ["It is required by federal law", "Positive reinforcement keeps users reporting in the future", "It reduces the mail server storage load", "It automatically trains the spam filter"],
        "answer": 1,
        "explain": "Reporting is the behavior the program most needs, and positive reinforcement sustains it. If reports disappear into a void — or users are criticized for false alarms — they stop reporting, and the security team loses its best early-warning sensor.",
    },
    {
        "type": "mc",
        "q": "An employee disables the endpoint antivirus agent because it 'slows down the build server' and installs an unauthorized file-sharing tool to move data faster. Which anomalous behavior category is this?",
        "choices": ["Unexpected", "Unintentional", "Risky", "Recurring"],
        "answer": 2,
        "explain": "Risky behavior is a deliberate unsafe act, usually done for convenience rather than malice: disabling security tools, installing unauthorized software, using personal USB drives, sharing passwords. It is intentional (unlike a mistake) but not necessarily out of the account's usage pattern.",
    },
    {
        "type": "mc",
        "q": "A user account that normally works 9-to-5 from Ohio logs on at 3 a.m. from an unfamiliar foreign IP address and begins downloading gigabytes from a server it has never accessed. Which anomalous behavior category is this?",
        "choices": ["Risky", "Unexpected", "Unintentional", "Operational"],
        "answer": 1,
        "explain": "Unexpected behavior is activity out of pattern for that user or account — odd hours, unfamiliar locations, impossible travel, never-before-touched systems, abnormal download volumes. It often indicates a compromised account or insider problem and warrants investigation.",
    },
    {
        "type": "mc",
        "q": "An accountant emails a spreadsheet containing employee salaries to the wrong recipient because the mail client auto-completed a similar name. Which anomalous behavior category is this?",
        "choices": ["Risky", "Unexpected", "Unintentional", "Malicious insider"],
        "answer": 2,
        "explain": "Unintentional behavior is an honest mistake — misdirected email, a lost laptop, an accidental misconfiguration, clicking a link without realizing. The right response is correction and training, not blame. Risky behavior, by contrast, is a deliberate unsafe choice.",
    },
    {
        "type": "mc",
        "q": "Security logs show a user logged on from Chicago and then, 20 minutes later, from Eastern Europe. What is this indicator commonly called, and which behavior category does it belong to?",
        "choices": ["Impossible travel; unexpected behavior", "Juice jacking; risky behavior", "Pretexting; unintentional behavior", "Shoulder surfing; unexpected behavior"],
        "answer": 0,
        "explain": "Two logons from locations too far apart to travel between in the elapsed time is called impossible travel — a classic unexpected-behavior indicator suggesting the credentials are being used by someone else. Juice jacking, pretexting, and shoulder surfing are attacks, not logon anomalies.",
    },
    {
        "type": "mc",
        "q": "During onboarding, a new hire reviews and signs the acceptable use policy and receives the employee handbook describing security expectations. Which user guidance and training element is this?",
        "choices": ["Policy/handbooks", "Situational awareness", "Operational security", "Anomalous behavior recognition"],
        "answer": 0,
        "explain": "Policy/handbooks is the training element covering written, accessible rules — the employee handbook, AUP, and related security policies — which new hires review and acknowledge at onboarding so they know both the rules and where to find them.",
    },
    {
        "type": "mc",
        "q": "While badging into the office, an employee notices a stranger with no visible badge slip through the door close behind her, and she reports it to security. Which awareness practice did she demonstrate?",
        "choices": ["Operational security", "Situational awareness", "Password management", "Attestation"],
        "answer": 1,
        "explain": "Situational awareness is staying alert to physical and digital surroundings — noticing tailgating, strangers without badges, shoulder surfing, out-of-place USB drives — and reporting what is out of place. OPSEC is about protecting aggregable information from an adversary's viewpoint.",
    },
    {
        "type": "mc",
        "q": "A coworker who recently complained bitterly about being passed over for promotion begins copying large amounts of project data unrelated to his job and asking for access beyond his role. According to insider threat training, what should an employee who notices this do?",
        "choices": ["Confront the coworker directly and demand an explanation", "Report the indicators through defined channels such as security or a manager", "Delete the coworker's account", "Ignore it unless data actually leaves the company"],
        "answer": 1,
        "explain": "Data hoarding, access attempts beyond the role, and disgruntlement are classic insider threat indicators. Awareness training tells employees to report indicators through defined channels (manager, security team, or an anonymous hotline) — not to confront the person or take action themselves.",
    },
    {
        "type": "mc",
        "q": "Which password guidance BEST reflects modern recommendations aligned with NIST SP 800-63B?",
        "choices": ["Use long, unique passphrases in a password manager and change them when compromise is suspected", "Change all passwords every 30 days and require special characters", "Use one strong password across all accounts so it is never forgotten", "Write passwords on paper stored under the keyboard"],
        "answer": 0,
        "explain": "Modern guidance favors length over composition rules: long unique passphrases, stored in a password manager, protected by MFA, and changed when there is evidence of compromise rather than on a fixed calendar. Forced frequent rotation and password reuse both weaken security.",
    },
    {
        "type": "mc",
        "q": "An employee finds a USB flash drive in the office parking lot labeled 'Payroll Q3.' According to security awareness training, what should the employee do?",
        "choices": ["Plug it in on an isolated personal laptop to see who owns it", "Plug it into a work computer but only open PDF files", "Hand it to the security team without connecting it to anything", "Throw it in the trash immediately"],
        "answer": 2,
        "explain": "Dropped drives are a classic baiting attack — the tempting label is the lure. Found media should never be connected to any machine; it goes to the security team, who can examine it safely. Discarding it destroys evidence the security team may want.",
    },
    {
        "type": "mc",
        "q": "A traveling employee needs to charge a phone at an airport and has only the public USB charging kiosk available. Which awareness guidance addresses the risk, and what is the risk called?",
        "choices": ["Removable media and cables guidance; juice jacking", "Password management; credential stuffing", "Situational awareness; tailgating", "Policy/handbooks; pretexting"],
        "answer": 0,
        "explain": "Juice jacking is the risk that a public USB charging port attempts data theft or malware installation. Removable media and cables training covers it: use an AC wall adapter, a battery pack, or a USB data blocker, and never trust unknown cables — malicious cables with embedded implants exist.",
    },
    {
        "type": "mc",
        "q": "A caller claiming to be from the IT help desk tells an employee there is a problem with her account and asks her to confirm her password so he can fix it. What attack is this, and what does awareness training say to do?",
        "choices": ["Vishing; refuse and verify through a known-good IT contact", "Smishing; reply asking for the ticket number", "Juice jacking; unplug the phone", "Shoulder surfing; cover the keyboard"],
        "answer": 0,
        "explain": "A social engineering attack over a voice call is vishing. Training says legitimate IT will never ask for your password: refuse, hang up, and verify the request out-of-band by calling the help desk at its known number. Smishing is the SMS variant; the others are unrelated.",
    },
    {
        "type": "mc",
        "q": "An employee posts a selfie from his desk. Visible in the photo are his access badge and a whiteboard covered with server names and IP addresses. Which awareness topic does this violate?",
        "choices": ["Password management", "Operational security (OPSEC)", "Removable media and cables", "Recurring reporting"],
        "answer": 1,
        "explain": "OPSEC means viewing everyday activity from an adversary's perspective and protecting small, seemingly harmless pieces of information that an attacker could aggregate — badge designs, internal hostnames, whiteboard contents. Social media oversharing is the classic OPSEC failure.",
    },
    {
        "type": "mc",
        "q": "Which practice belongs in security guidance for hybrid/remote work environments?",
        "choices": ["Leave the home router's default admin password so IT can access it", "Use open public Wi-Fi for sensitive work to save VPN licenses", "Change home router defaults, use WPA3/WPA2, and connect through the company VPN on untrusted networks", "Share the work laptop with family members to reduce hardware costs"],
        "answer": 2,
        "explain": "Remote-work guidance covers hardening the home network (change default credentials, use WPA3 or at minimum WPA2, update firmware), using the company VPN on untrusted networks, locking screens, and keeping work devices off-limits to family. The other options are the opposite of the guidance.",
    },
    {
        "type": "mc",
        "q": "A brand-new awareness program runs its first phishing campaign and records a 28% click rate, and first-round training completion is logged. In the reporting and monitoring element, what do these first measurements represent?",
        "choices": ["Recurring reporting", "Initial reporting — the baseline", "Execution failure", "Attestation"],
        "answer": 1,
        "explain": "Initial reporting is the program's first measurement — the baseline click rate, completion rate, or knowledge survey against which all future results are compared. Recurring reporting is the ongoing repetition of those measurements that reveals trends over time.",
    },
    {
        "type": "mc",
        "q": "Every quarter the security team runs another phishing simulation, and every month it sends leadership a dashboard showing click-rate and report-rate trends. Which reporting and monitoring element is this?",
        "choices": ["Initial", "Recurring", "Development", "Unintentional"],
        "answer": 1,
        "explain": "Recurring reporting and monitoring is the ongoing, repeated measurement — quarterly simulations, annual refresher completion, monthly dashboards — that shows trends and proves the program is actually changing behavior. Initial reporting is only the first baseline measurement.",
    },
    {
        "type": "mc",
        "q": "A security manager is defining the scope of a new awareness program, identifying role-based audiences (finance, developers, executives), choosing topics based on recent incidents, and securing executive sponsorship. Which program phase is this?",
        "choices": ["Execution", "Recurring monitoring", "Development", "Initial reporting"],
        "answer": 2,
        "explain": "Development is building the program: defining scope and objectives, identifying audiences, tailoring content to roles and the real threat landscape, choosing delivery methods and metrics, and obtaining executive support. Delivering the training is execution, which comes next.",
    },
    {
        "type": "mc",
        "q": "The awareness team is now delivering onboarding sessions, running the quarterly phishing campaigns, publishing the monthly newsletter, and tracking training completion in the LMS. Which program phase is this?",
        "choices": ["Development", "Execution", "Initial reporting", "Assessment"],
        "answer": 1,
        "explain": "Execution is running the program — delivering onboarding and recurring training, running simulation campaigns, reinforcing with newsletters and posters, and tracking completion and results. Development was the earlier design phase; reporting feeds the results back for the next cycle.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Employees who click links in a phishing simulation should be publicly named and formally disciplined to deter others.",
        "answer": False,
        "explain": "Simulations exist to measure susceptibility and deliver training at the teachable moment. Public shaming or punishment discourages users from reporting real phishing later — it destroys the reporting culture the program depends on. Clickers get immediate remedial training instead.",
    },
    {
        "type": "tf",
        "q": "True or False: A sense of urgency combined with a sender address that does not match the claimed organization are common indicators of a phishing attempt.",
        "answer": True,
        "explain": "Manufactured urgency ('act within 24 hours') and mismatched or spoofed sender domains are two of the classic phishing red flags, along with generic greetings, hover-revealed suspicious URLs, unexpected attachments, and requests for credentials or payment changes.",
    },
    {
        "type": "tf",
        "q": "True or False: Accidentally sending a sensitive file to the wrong email recipient is classified as risky behavior.",
        "answer": False,
        "explain": "A misdirected email is unintentional behavior — an honest mistake met with correction and training. Risky behavior is a deliberate unsafe act, such as disabling antivirus, installing unauthorized software, or sharing passwords.",
    },
    {
        "type": "tf",
        "q": "True or False: Operational security (OPSEC) includes protecting small, seemingly harmless pieces of information — like badge photos or internal hostnames on a whiteboard — that an adversary could aggregate.",
        "answer": True,
        "explain": "OPSEC means looking at daily activity through an adversary's eyes. Individually trivial details — badge designs, whiteboard contents, job postings revealing the tech stack — can be aggregated into an attack plan, so training covers social media care, clean desks, and shredding.",
    },
    {
        "type": "tf",
        "q": "True or False: Modern password guidance aligned with NIST SP 800-63B recommends forcing all users to change passwords every 30 days.",
        "answer": False,
        "explain": "NIST SP 800-63B recommends against arbitrary periodic expiration: passwords should be changed when there is evidence of compromise. Forced frequent rotation drives users toward weak, predictable patterns. Guidance favors long unique passphrases, a password manager, and MFA.",
    },
    {
        "type": "tf",
        "q": "True or False: After confirming a reported email is malicious, the security team should remove remaining copies from other users' mailboxes and block the sender and embedded URLs.",
        "answer": True,
        "explain": "Containment follows confirmation: purge every remaining copy from mailboxes, block the sender/domain/URLs in the email filters, then identify anyone who clicked or entered credentials and reset those credentials. Finally, the reporter gets feedback and thanks.",
    },
    {
        "type": "tf",
        "q": "True or False: Malicious USB cables that look identical to ordinary charging cables can inject keystrokes or exfiltrate data.",
        "answer": True,
        "explain": "Attack cables (the O.MG cable is the well-known example) hide implants inside an ordinary-looking cable and can inject keystrokes or exfiltrate data. That is why removable media and cables training says to use only trusted, organization-issued cables and chargers.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "A controlled exercise in which the security team sends simulated malicious emails to its own users is called a ______ campaign. (type your answer)",
        "answers": ["phishing", "phishing simulation", "simulated phishing"],
        "explain": "A phishing campaign measures user susceptibility with click and report rates and trains clickers at the teachable moment. Repeated campaigns show whether awareness training is actually reducing the click rate over time.",
    },
    {
        "type": "fill",
        "q": "Deliberately disabling security tools or installing unauthorized software is classified as ______ behavior. (type your answer)",
        "answers": ["risky"],
        "explain": "Risky behavior is a deliberate unsafe act done for convenience rather than malice. Unexpected behavior is out-of-pattern account activity, and unintentional behavior is an honest mistake — the three categories of anomalous behavior recognition.",
    },
    {
        "type": "fill",
        "q": "Viewing day-to-day operations from an adversary's perspective to protect seemingly harmless, aggregable information is called operational ______. (type your answer)",
        "answers": ["security", "operational security", "opsec"],
        "explain": "Operational security (OPSEC) protects the small details — badge photos, whiteboards, oversharing on social media — that an attacker could piece together. Clean desk policies and document shredding support it.",
    },
    {
        "type": "fill",
        "q": "An application that generates and stores a unique, strong password for every account is called a password ______. (type your answer)",
        "answers": ["manager", "password manager", "vault"],
        "explain": "A password manager lets users follow the 'unique passphrase per account' rule without memorizing dozens of credentials — they remember one strong master credential, ideally protected with MFA.",
    },
    {
        "type": "fill",
        "q": "The first measurement of an awareness program, which establishes the baseline for all later comparisons, is the ______ report. (type your answer)",
        "answers": ["initial"],
        "explain": "Initial reporting is the baseline — the first campaign's click rate or first training completion numbers. Recurring reporting is the ongoing repetition of those measurements that reveals trends and proves the program works.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each anomalous behavior category or phishing concept to its example.",
        "pairs": [
            ["Risky behavior", "User disables antivirus and installs unauthorized software"],
            ["Unexpected behavior", "Account logs on at 3 a.m. from an unfamiliar country"],
            ["Unintentional behavior", "Employee emails a sensitive file to the wrong recipient"],
            ["Phishing campaign", "Security team sends simulated malicious emails to its own users"],
        ],
        "explain": "Risky = deliberate unsafe act; unexpected = out-of-pattern account activity (odd hours, odd places, impossible travel); unintentional = honest mistake. A phishing campaign is the controlled simulation the security team runs to measure and train.",
    },
    {
        "type": "match",
        "q": "Match each user guidance and training topic to its content.",
        "pairs": [
            ["Situational awareness", "Noticing tailgating, shoulder surfing, and out-of-place items"],
            ["Operational security", "Protecting aggregable details; clean desk; careful social media"],
            ["Password management", "Long unique passphrases, a password manager, and MFA"],
            ["Removable media and cables", "Never plug in found USB drives or untrusted chargers"],
            ["Hybrid/remote work", "Harden the home router and use the company VPN on untrusted networks"],
        ],
        "explain": "Situational awareness is alertness to surroundings; OPSEC guards small aggregable details from an adversary's viewpoint; password management follows NIST-style guidance; removable media/cables training counters baiting, malicious cables, and juice jacking; remote-work guidance secures the home environment.",
    },
    {
        "type": "match",
        "q": "Match each awareness program element to its description.",
        "pairs": [
            ["Development", "Define scope, audiences, role-based content, and metrics"],
            ["Execution", "Deliver training, run campaigns, and track completion"],
            ["Initial reporting", "First measurement that establishes the baseline"],
            ["Recurring reporting", "Ongoing measurement that reveals trends over time"],
        ],
        "explain": "Development designs the program, execution delivers it, initial reporting captures the baseline, and recurring reporting/monitoring repeats the measurements to show trends — then the results feed back into the next development cycle.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps for handling a reported suspicious message in order, from first to last.",
        "items": [
            "User reports the message via the report-phishing button",
            "Security team analyzes the message to determine if it is malicious",
            "Copies are removed from all mailboxes and the sender/URLs are blocked",
            "Users who clicked are identified and their credentials reset",
            "The reporter receives feedback and thanks",
        ],
        "explain": "The workflow runs report → analyze → contain (purge copies, block indicators) → remediate affected users (identify clickers, reset credentials) → close the loop with feedback to the reporter, which reinforces the reporting culture.",
    },
    {
        "type": "order",
        "q": "Arrange the phases of a security awareness program lifecycle in order, from first to last.",
        "items": [
            "Development: define scope, audiences, and role-based content",
            "Execution: deliver training and run phishing campaigns",
            "Initial reporting: first measurements establish the baseline",
            "Recurring reporting: ongoing measurements track trends",
            "Update the program based on results and new threats",
        ],
        "explain": "The lifecycle is development (design) then execution (delivery), after which the first measurements form the initial baseline, recurring monitoring tracks trends against it, and the findings drive updates in the next development cycle.",
    },
]
