TOPIC = {
    "id": "1.1",
    "domain": 1,
    "title": "Describe cloud computing.",
    "short": "Cloud Computing",
}

TERMS = [
    ("Cloud computing", "Delivery of computing services — compute, storage, databases, networking, software — over the internet on a pay-as-you-go basis"),
    ("Shared responsibility model", "Division of security/management duties between provider and customer that shifts with the service model (IaaS vs PaaS vs SaaS)"),
    ("Public cloud", "Cloud model where many organizations share a provider's multitenant infrastructure over the internet with no upfront hardware cost"),
    ("Private cloud", "Cloud infrastructure dedicated to a single organization, whether hosted in its own datacenter or by a third party"),
    ("Hybrid cloud", "Environment that connects and integrates a private cloud or on-premises datacenter with a public cloud so workloads can span both"),
    ("Multi-cloud", "Using two or more public cloud providers (e.g., Azure and AWS) at the same time"),
    ("Azure Arc", "Azure service that extends the Azure control plane to manage resources across on-premises, hybrid, and other-cloud environments"),
    ("Azure VMware Solution", "Azure service for running existing VMware workloads in Azure with seamless integration, easing hybrid migration"),
    ("Consumption-based model", "Pricing approach with no upfront cost where you pay only for resources you actually use and stop paying when you stop using them"),
    ("Capital expenditure (CapEx)", "Large upfront spending on physical assets (servers, datacenters) that depreciates over time"),
    ("Operational expenditure (OpEx)", "Ongoing spending on services as they are consumed — the accounting model of cloud computing"),
    ("Pay-as-you-go", "Pricing model with no commitment: standard metered rates, start and stop anytime, best for variable or unpredictable workloads"),
    ("Reserved instances", "Pricing model trading a 1- or 3-year commitment for a significant discount on steady, predictable workloads"),
    ("Spot pricing", "Deeply discounted unused Azure capacity that can be evicted with little notice — for interruptible workloads only"),
    ("Serverless computing", "Execution model where the provider manages all infrastructure; code runs on demand, scales to zero, and is billed per execution"),
    ("Azure Functions", "Azure's serverless service for running event-driven code without provisioning or managing servers"),
    ("Azure Logic Apps", "Azure's serverless low/no-code service for building automated workflows and integrations"),
    ("Microsoft Entra ID", "Microsoft's cloud identity and access management service, formerly known as Azure Active Directory"),
    ("Microsoft Cost Management", "Azure tool for monitoring, analyzing, alerting on, and optimizing cloud spending"),
    ("Cloud bursting", "Hybrid-cloud technique where workloads overflow from private infrastructure into the public cloud during demand spikes"),
    ("Multitenancy", "Many logically isolated customers sharing the same physical cloud infrastructure — the economics behind public cloud"),
    ("Scale to zero", "Serverless trait where resources shrink to nothing when no events occur, so idle time costs nothing"),
    ("Eviction", "Azure reclaiming spot capacity from a running workload when it needs the capacity back"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A CTO explains to the board why the company is closing its server room. Which statement BEST defines cloud computing?",
        "choices": [
            "Renting a dedicated rack in a nearby colocation facility",
            "The delivery of computing services over the internet, paid for on a pay-as-you-go basis",
            "Running virtual machines instead of physical servers in your own datacenter",
            "Outsourcing the IT help desk to a managed service provider",
        ],
        "answer": 1,
        "explain": "Cloud computing is the delivery of computing services — compute, storage, databases, networking, and more — over the internet with pay-as-you-go pricing. Virtualizing your own datacenter is just virtualization, and colocation or outsourced staffing still leaves you owning and managing the infrastructure.",
    },
    {
        "type": "mc",
        "q": "A project team needs 20 servers for a 6-week pilot. On-premises procurement would take two months. What core advantage of cloud computing solves this?",
        "choices": [
            "Resources are provisioned on demand in minutes and released when no longer needed",
            "Cloud servers never require patching",
            "Cloud providers guarantee the pilot will succeed",
            "Hardware is shipped overnight to the company's datacenter",
        ],
        "answer": 0,
        "explain": "The cloud provisions capacity in minutes rather than weeks and lets you deallocate it the moment the pilot ends, paying only for the six weeks used. Patching responsibility still exists (it just depends on the service model), and no hardware ever ships to you — that is the point.",
    },
    {
        "type": "mc",
        "q": "An Azure IaaS virtual machine is compromised through an operating-system vulnerability whose patch had been available for months. Under the shared responsibility model, who was responsible for applying it?",
        "choices": ["Microsoft", "The customer", "The ISP", "Responsibility is always split 50/50"],
        "answer": 1,
        "explain": "In IaaS the provider manages the physical hosts, network, and datacenter, but everything from the operating system up — patching, middleware, applications, data — belongs to the customer. Only in PaaS and SaaS does OS maintenance shift to the provider.",
    },
    {
        "type": "mc",
        "q": "A company moves entirely to SaaS applications. Which set of responsibilities does it STILL retain under the shared responsibility model?",
        "choices": [
            "Patching the application and its runtime",
            "Maintaining the hypervisor and physical network",
            "Its information and data, devices, and accounts and identities",
            "None — SaaS transfers all responsibility to the provider",
        ],
        "answer": 2,
        "explain": "Three responsibilities never transfer in any service model: information and data, devices (mobile and PCs), and accounts and identities. The provider handles the application, OS, and physical infrastructure in SaaS, but classifying data, securing endpoints, and managing who signs in remain the customer's job.",
    },
    {
        "type": "mc",
        "q": "Regardless of whether a workload is IaaS, PaaS, or SaaS, which responsibility ALWAYS belongs to the cloud provider?",
        "choices": [
            "Managing user accounts and identities",
            "Classifying and protecting business data",
            "Securing employee laptops and phones",
            "Operating the physical hosts, network, and datacenter",
        ],
        "answer": 3,
        "explain": "The physical layer — hosts, network, and datacenter — is always the provider's responsibility in every cloud service model; customers never touch Microsoft's hardware. The other three options are the responsibilities that always remain with the customer.",
    },
    {
        "type": "mc",
        "q": "A team runs its application on an Azure PaaS database service. Which pairing of responsibilities is correct?",
        "choices": [
            "Customer patches the OS; Microsoft manages the data",
            "Microsoft patches the OS; the customer remains responsible for the data",
            "Microsoft manages both the OS and the customer's data classification",
            "The customer manages the physical servers; Microsoft manages accounts",
        ],
        "answer": 1,
        "explain": "In PaaS the provider takes over the operating system and runtime, so OS patching is Microsoft's job. But information and data are always the customer's responsibility in every model — the provider hosts the database, the customer owns what goes into it and who can access it.",
    },
    {
        "type": "mc",
        "q": "Under the shared responsibility model, a customer manages sign-ins and access rights for its cloud users. Which Azure service is used for this identity management?",
        "choices": [
            "Microsoft Entra ID (formerly Azure Active Directory)",
            "Microsoft Defender for Cloud",
            "Azure Arc",
            "Microsoft Cost Management",
        ],
        "answer": 0,
        "explain": "Accounts and identities are always the customer's responsibility, and Microsoft Entra ID — renamed from Azure Active Directory — is Azure's cloud identity and access management service. Defender for Cloud is a security-posture tool, Arc manages resources across environments, and Cost Management tracks spending.",
    },
    {
        "type": "mc",
        "q": "A bootstrapped startup with no hardware budget and unpredictable growth wants to launch its app with zero upfront infrastructure investment. Which cloud model fits BEST?",
        "choices": ["Private cloud", "Public cloud", "Community cloud", "On-premises datacenter"],
        "answer": 1,
        "explain": "The public cloud offers services on the provider's shared multitenant infrastructure with no capital expenditure — ideal for startups that need to scale unpredictably without buying hardware. A private cloud or on-premises build requires exactly the upfront investment the startup is avoiding.",
    },
    {
        "type": "mc",
        "q": "A hosting company operates a cloud environment on ITS premises, but the hardware is used exclusively by one insurance firm. Which cloud model is this?",
        "choices": ["Public cloud", "Multi-cloud", "Private cloud", "Hybrid cloud"],
        "answer": 2,
        "explain": "A private cloud is defined by exclusive single-organization use, not by physical location — a third party can host it and it remains private. It would only be public if the infrastructure were shared among many tenants.",
    },
    {
        "type": "mc",
        "q": "A hospital keeps its patient-records database in its own datacenter for compliance but runs its appointment-booking website in Azure, with the two integrated. Which cloud model is this?",
        "choices": ["Hybrid cloud", "Public cloud", "Private cloud", "Multi-cloud"],
        "answer": 0,
        "explain": "Connecting and integrating on-premises (or private cloud) infrastructure with a public cloud so workloads span both is the hybrid model — it lets the hospital choose where each workload runs. Multi-cloud would mean using a second public provider such as AWS, not on-premises plus Azure.",
    },
    {
        "type": "mc",
        "q": "After an acquisition, a company runs production workloads in both Azure and AWS, with no on-premises infrastructure at all. What is this environment called?",
        "choices": ["Hybrid cloud", "Private cloud", "Cloud bursting", "Multi-cloud"],
        "answer": 3,
        "explain": "Using two or more public cloud providers simultaneously is multi-cloud. It is not hybrid, because hybrid specifically means integrating private/on-premises infrastructure with a public cloud — and this company has no private footprint.",
    },
    {
        "type": "mc",
        "q": "An enterprise wants to manage and govern its servers running on-premises, in Azure, and in another public cloud — all from a single Azure control plane. Which service enables this?",
        "choices": ["Azure VMware Solution", "Azure Arc", "Microsoft Entra ID", "Azure Functions"],
        "answer": 1,
        "explain": "Azure Arc extends Azure's management plane to resources living outside Azure — on-premises, at the edge, or in other clouds — so everything is governed from one place. Azure VMware Solution is for running VMware workloads in Azure, not for cross-environment management.",
    },
    {
        "type": "mc",
        "q": "A company with a large on-premises VMware estate wants to move those workloads into Azure quickly, without re-architecting them. Which offering is designed for this?",
        "choices": ["Azure Logic Apps", "Azure Arc", "Azure VMware Solution", "Microsoft Cost Management"],
        "answer": 2,
        "explain": "Azure VMware Solution lets an organization run its existing VMware workloads natively in Azure with seamless integration, making it the fast path for hybrid migration of a VMware estate. Arc manages resources across environments but does not host VMware workloads.",
    },
    {
        "type": "mc",
        "q": "A defense contractor requires complete control over its hardware and security configuration and must guarantee no other organization ever shares its infrastructure. Which cloud model fits, and what is the trade-off?",
        "choices": [
            "Public cloud — trade-off is limited scalability",
            "Private cloud — trade-off is higher cost and self-managed maintenance",
            "Multi-cloud — trade-off is vendor lock-in",
            "Hybrid cloud — trade-off is no internet connectivity",
        ],
        "answer": 1,
        "explain": "A private cloud dedicates all infrastructure to one organization, delivering maximum control for strict compliance — at the price of buying, maintaining, and staffing it yourself. Public cloud is multitenant by nature, which is exactly what this scenario forbids.",
    },
    {
        "type": "mc",
        "q": "A retailer's on-premises systems handle normal traffic, but during holiday sales it automatically overflows extra web capacity into Azure. What is this technique, and which model does it require?",
        "choices": [
            "Cloud bursting, requiring a hybrid cloud",
            "Eviction, requiring spot pricing",
            "Scale to zero, requiring serverless",
            "Multitenancy, requiring a public cloud",
        ],
        "answer": 0,
        "explain": "Cloud bursting overflows workloads from private infrastructure into public cloud capacity during demand spikes, which is a signature use case of the hybrid model. Eviction is Azure reclaiming spot capacity, and scale to zero is serverless shrinking when idle — different concepts entirely.",
    },
    {
        "type": "mc",
        "q": "A CFO complains that the company keeps buying servers sized for peak demand that sit 70% idle. Which cloud benefit MOST directly addresses this?",
        "choices": [
            "The consumption-based model — pay only for resources actually used",
            "Reserved instances — commit to three years of capacity",
            "Private cloud — dedicated hardware for every workload",
            "Multitenancy — share servers with other companies' data",
        ],
        "answer": 0,
        "explain": "The consumption-based model eliminates paying for predicted-but-unused capacity: usage is metered, there is no upfront purchase, and billing stops when resources are deallocated. Reserved instances are a discount mechanism for steady usage, not a cure for overprovisioning.",
    },
    {
        "type": "mc",
        "q": "Moving from buying datacenter hardware every three years to renting metered Azure services shifts the company's spending from ______ to ______.",
        "choices": [
            "OpEx to CapEx",
            "CapEx to OpEx",
            "Fixed cost to capital cost",
            "Consumption to commitment",
        ],
        "answer": 1,
        "explain": "Buying depreciating physical assets upfront is capital expenditure (CapEx); paying an ongoing metered bill for services consumed is operational expenditure (OpEx). The consumption-based cloud model is the textbook CapEx-to-OpEx shift.",
    },
    {
        "type": "mc",
        "q": "A finance team wants to monitor Azure spending, analyze usage trends, and receive alerts when costs exceed a threshold. Which tool should it use?",
        "choices": ["Microsoft Entra ID", "Azure Arc", "Microsoft Defender for Cloud", "Microsoft Cost Management"],
        "answer": 3,
        "explain": "Microsoft Cost Management is Azure's tool for monitoring, analyzing, alerting on, and optimizing cloud spend under the consumption-based model. Entra ID handles identity, Arc handles cross-environment management, and Defender for Cloud handles security posture.",
    },
    {
        "type": "mc",
        "q": "A production database VM will run 24/7 for at least the next three years with steady usage. Which pricing model minimizes its cost SAFELY?",
        "choices": ["Spot pricing", "Pay-as-you-go", "Reserved instances", "Per-execution billing"],
        "answer": 2,
        "explain": "Reserved instances trade a 1- or 3-year commitment for a significant discount (up to roughly 72%) and are ideal for steady, predictable, long-running workloads. Spot would be cheaper per hour but can be evicted at any time — unacceptable for a production database.",
    },
    {
        "type": "mc",
        "q": "A rendering farm processes overnight batch jobs that checkpoint their progress and can restart after any interruption. Which pricing model offers the DEEPEST savings for this workload?",
        "choices": ["Reserved instances", "Spot pricing", "Pay-as-you-go", "A 3-year enterprise agreement"],
        "answer": 1,
        "explain": "Spot pricing sells unused Azure capacity at the steepest discount (up to ~90%) in exchange for evictability — Azure can reclaim the VMs with little notice. Because these batch jobs checkpoint and restart, eviction is tolerable, making spot the best fit.",
    },
    {
        "type": "mc",
        "q": "A startup's traffic is spiky and unpredictable, and it cannot commit to any minimum usage. Which pricing model should it start with?",
        "choices": ["Pay-as-you-go", "3-year reserved instances", "Spot pricing for its production web tier", "A capital hardware purchase"],
        "answer": 0,
        "explain": "Pay-as-you-go has no commitment: standard metered rates, start and stop anytime — the right default for variable or unknown workloads. Reserved instances would lock in spend the startup cannot predict, and spot is wrong for a production web tier because it can be evicted mid-request.",
    },
    {
        "type": "mc",
        "q": "What is the main RISK of running a workload on Azure spot pricing?",
        "choices": [
            "It requires a mandatory 3-year commitment",
            "It is billed at a premium above pay-as-you-go rates",
            "Azure can evict the workload with little notice when it needs the capacity back",
            "It only supports SaaS applications",
        ],
        "answer": 2,
        "explain": "Spot capacity is Azure's spare capacity — you get it at a deep discount precisely because Azure may reclaim (evict) it whenever paying demand returns. That is why spot suits only interruptible workloads like batch jobs, rendering, and dev/test.",
    },
    {
        "type": "mc",
        "q": "An order-confirmation function runs only when a customer places an order, costs nothing overnight when no orders arrive, and requires no server management. Which cloud approach is this?",
        "choices": ["IaaS with auto-shutdown schedules", "Serverless computing", "Reserved instances", "A private cloud"],
        "answer": 1,
        "explain": "Serverless computing means the provider manages all infrastructure while your code runs on demand in response to events, scales to zero when idle, and is billed per execution. IaaS with shutdown schedules still leaves you managing VMs and paying while they run.",
    },
    {
        "type": "mc",
        "q": "A developer wants to run small pieces of event-driven code in Azure without provisioning any infrastructure, and an ops teammate wants low-code automated workflows. Which pair of services fits?",
        "choices": [
            "Azure Virtual Machines and Azure Arc",
            "Azure Functions and Azure Logic Apps",
            "Microsoft Entra ID and Microsoft Cost Management",
            "Azure VMware Solution and Azure Virtual Desktop",
        ],
        "answer": 1,
        "explain": "Azure Functions is the serverless service for event-driven code; Azure Logic Apps is the serverless low/no-code service for automated workflows and integrations. The other pairs are IaaS/management, identity/cost, and VMware/desktop services — none serverless.",
    },
    {
        "type": "mc",
        "q": "Both PaaS and serverless hide the operating system from you. What MOST distinguishes serverless from typical PaaS?",
        "choices": [
            "Serverless requires the customer to patch the OS",
            "Serverless runs per event, scales to zero when idle, and bills per execution",
            "PaaS is only available in private clouds",
            "Serverless workloads cannot access the internet",
        ],
        "answer": 1,
        "explain": "PaaS typically keeps an application running on provisioned capacity you pay for continuously, while serverless spins up per event, disappears between events (scale to zero), and bills per execution. Neither model leaves OS patching to the customer — that is IaaS.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A private cloud must be physically located in the organization's own datacenter.",
        "answer": False,
        "explain": "A private cloud is defined by exclusive use by a single organization, not by where it runs — a third party can host it and it remains private. Tenancy, not geography, determines the cloud model.",
    },
    {
        "type": "tf",
        "q": "True or False: When a company adopts SaaS, the provider becomes responsible for the company's data, user accounts, and employee devices.",
        "answer": False,
        "explain": "Information and data, devices, and accounts and identities always remain the customer's responsibility in every service model — even SaaS. The provider takes over the application, OS, and physical infrastructure, but never your data or identities.",
    },
    {
        "type": "tf",
        "q": "True or False: Under the consumption-based model, deallocating a resource stops its usage-based charges.",
        "answer": True,
        "explain": "The consumption-based model means no upfront cost, paying only for what you actually use, and ceasing payment when you stop using it. This OpEx behavior is the core economic difference from CapEx hardware, which costs the same whether idle or busy.",
    },
    {
        "type": "tf",
        "q": "True or False: 'Serverless' means the application code runs without any physical servers involved.",
        "answer": False,
        "explain": "Servers absolutely exist in serverless computing — the provider simply owns, provisions, patches, and scales them so the customer never sees or manages them. The name describes the customer's experience, not the physics.",
    },
    {
        "type": "tf",
        "q": "True or False: Azure spot pricing offers deeper discounts than reserved instances, but Azure may reclaim the capacity at any time.",
        "answer": True,
        "explain": "Spot pricing sells spare capacity at the steepest discount of any pricing model, with the catch that workloads can be evicted with little notice. Reserved instances offer smaller (but still significant) discounts in exchange for a 1- or 3-year commitment — and are never evicted.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The cloud pricing philosophy with no upfront cost, where you pay only for the resources you actually use, is the ______-based model. (type your answer)",
        "answers": ["consumption", "consumption based", "usage", "usage based"],
        "explain": "The consumption-based model meters actual usage — per second of compute, per GB of storage, per execution — with no upfront purchase, and billing stops when you stop using resources. It is the reason cloud spending is OpEx rather than CapEx.",
    },
    {
        "type": "fill",
        "q": "Ongoing spending on services as they are consumed — the accounting category cloud computing shifts you INTO — is called ______. (type the acronym or term)",
        "answers": ["opex", "operational expenditure", "operating expenditure", "operational expenses", "operating expenses", "operational expense", "operating expense"],
        "explain": "OpEx (operational expenditure) is pay-as-you-consume spending, in contrast to CapEx (capital expenditure) — large upfront purchases of depreciating assets like servers. Cloud's consumption-based model converts infrastructure costs from CapEx to OpEx.",
    },
    {
        "type": "fill",
        "q": "Deeply discounted Azure capacity that can be reclaimed (evicted) by Azure with little notice is called ______ pricing. (type your answer)",
        "answers": ["spot", "spot instance", "spot vm", "spot virtual machine"],
        "explain": "Spot pricing offers the deepest discounts — up to around 90% — on Azure's unused capacity, in exchange for the risk of eviction. It suits interruptible workloads such as batch processing, rendering, and dev/test, never systems that must not stop.",
    },
    {
        "type": "fill",
        "q": "Microsoft's cloud identity and access management service — formerly named Azure Active Directory — is now called Microsoft ______. (type your answer)",
        "answers": ["entra id", "entra", "microsoft entra id", "microsoft entra"],
        "explain": "Azure Active Directory was renamed Microsoft Entra ID after the 2023 refresh, and the exam uses the new name. It is the service through which customers exercise their never-transferable responsibility for accounts and identities.",
    },
    {
        "type": "fill",
        "q": "The Azure service that extends Azure's management control plane to servers running on-premises and in other public clouds is Azure ______. (type your answer)",
        "answers": ["arc", "azure arc"],
        "explain": "Azure Arc projects non-Azure resources — on-premises, edge, and other-cloud servers — into Azure so they can be organized, governed, and managed from a single control plane. It is the key tool for hybrid and multi-cloud management scenarios.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each cloud model to its defining scenario.",
        "pairs": [
            ["Public cloud", "Many organizations share the provider's infrastructure with no upfront cost"],
            ["Private cloud", "All infrastructure dedicated to one organization, wherever it is hosted"],
            ["Hybrid cloud", "On-premises datacenter integrated with Azure so workloads span both"],
            ["Multi-cloud", "Production workloads running in both Azure and AWS"],
        ],
        "explain": "Tenancy and composition define the models: public is shared/multitenant, private is single-organization (location irrelevant), hybrid integrates private with public, and multi-cloud spans two or more public providers.",
    },
    {
        "type": "match",
        "q": "Match each pricing approach to the workload it fits best.",
        "pairs": [
            ["Pay-as-you-go", "Spiky, unpredictable traffic with no commitment possible"],
            ["Reserved instances", "Steady 24/7 workload the company will run for 3 years"],
            ["Spot pricing", "Restartable batch jobs that tolerate eviction"],
            ["Serverless", "Event-driven code that should cost nothing while idle"],
        ],
        "explain": "Pay-as-you-go trades a higher rate for total flexibility; reserved instances trade a 1/3-year commitment for a large discount on predictable usage; spot trades evictability for the deepest discount; serverless bills per execution and scales to zero between events.",
    },
    {
        "type": "match",
        "q": "Match each responsibility to how the shared responsibility model assigns it.",
        "pairs": [
            ["Information and data", "The customer's job in every service model"],
            ["Physical hosts, network, and datacenter", "The provider's job in every cloud service model"],
            ["Operating system in IaaS", "The customer must patch and maintain it"],
            ["Operating system in PaaS and SaaS", "The provider patches and maintains it"],
        ],
        "explain": "Data (with devices and identities) never leaves the customer's side of the chart, and the physical layer never leaves the provider's. The OS is the classic shifting layer: customer-managed in IaaS, provider-managed in PaaS and SaaS.",
    },
    {
        "type": "match",
        "q": "Match each Azure service or tool to its purpose.",
        "pairs": [
            ["Azure Arc", "Manage resources across on-premises, Azure, and other clouds"],
            ["Azure VMware Solution", "Run existing VMware workloads in Azure"],
            ["Microsoft Cost Management", "Monitor, analyze, and alert on cloud spending"],
            ["Azure Functions", "Run event-driven serverless code"],
            ["Azure Logic Apps", "Build serverless low-code automated workflows"],
        ],
        "explain": "Arc is the cross-environment control plane and Azure VMware Solution the VMware migration path — the two hybrid/multi-cloud enablers. Cost Management operationalizes the consumption-based model, while Functions and Logic Apps are Azure's flagship serverless services for code and workflows respectively.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange these approaches by increasing PROVIDER responsibility under the shared responsibility model (least provider-managed first).",
        "items": ["On-premises", "IaaS", "PaaS", "SaaS"],
        "explain": "On-premises leaves the provider managing nothing; IaaS hands over the physical layer and virtualization; PaaS adds the OS and runtime; SaaS puts the entire application stack on the provider. Even at SaaS, though, data, devices, and identities stay with the customer.",
    },
]
