TOPIC = {
    "id": "1.2",
    "domain": 1,
    "title": "Describe the benefits of using cloud services.",
    "short": "Cloud Benefits",
}

TERMS = [
    ("High availability (HA)", "Maximizing the time a service is up and reachable — users keep getting service despite component failures, achieved through redundancy"),
    ("Service-level agreement (SLA)", "A provider's formal uptime commitment expressed as a percentage; missing it earns the customer service credits"),
    ("Nines of availability", "Shorthand for SLA percentages (99%, 99.9%, 99.99%, 99.999%); each additional nine cuts allowed downtime by roughly 10x"),
    ("Composite SLA", "The combined guarantee of an app that chains multiple services — SLAs multiply downward, so more dependencies mean a lower overall percentage"),
    ("Scalability", "The ability to adjust resources to meet demand — adding capacity when load grows without over-buying idle hardware"),
    ("Vertical scaling (scale up)", "Making one instance bigger — moving a VM to a larger size with more vCPUs/RAM; simple but has a ceiling and usually needs a restart"),
    ("Horizontal scaling (scale out)", "Adding more instances behind a load balancer; near-limitless growth that also adds redundancy"),
    ("Elasticity", "Automatic scaling in BOTH directions — resources grow when demand spikes and shrink back when demand falls, with no human intervention"),
    ("Autoscaling", "Platform rules that add or remove instances automatically based on metrics such as CPU or request count — the mechanism behind elasticity"),
    ("Load balancing", "Distributing incoming traffic across multiple instances so no single node is overwhelmed; supports HA and performance predictability"),
    ("Reliability", "A system's ability to recover from failures and continue to function — self-healing, decentralized, multi-region design"),
    ("Decentralized design", "Spreading a solution's resources across multiple regions/locations so no single failure — even a regional outage — stops the application"),
    ("Azure Well-Architected Framework", "Microsoft's guidance for building quality workloads; its pillars include reliability, cost optimization, performance efficiency, security, and operational excellence"),
    ("Predictability", "The confidence to move forward knowing how the solution will perform (performance predictability) and what it will cost (cost predictability)"),
    ("Performance predictability", "A consistent user experience even as load changes, delivered by autoscaling, load balancing, and high-availability design"),
    ("Cost predictability", "Knowing cloud spend in advance and in real time via the pricing calculator, TCO calculator, and Microsoft Cost Management"),
    ("Pricing calculator", "Azure tool that estimates the cost of a planned set of Azure resources before you deploy them"),
    ("Total cost of ownership (TCO) calculator", "Azure tool that compares the cost of a current on-premises environment against running the same workloads in Azure"),
    ("Microsoft Cost Management", "Azure service (formerly Azure Cost Management) that tracks actual spending in real time, sets budgets, sends alerts, and forecasts costs"),
    ("Governance", "Keeping all resources compliant with corporate standards and regulatory requirements, enforced automatically through policies and templates"),
    ("Azure Policy", "Azure service that defines and enforces rules across resources so deployments meet corporate standards and flag or block drift"),
    ("Regulatory compliance", "Meeting government and industry standards; cloud providers' certifications and audit reports help customers satisfy these requirements"),
    ("DDoS protection", "Provider-operated, Internet-scale mitigation of distributed denial-of-service attacks — a security burden the cloud absorbs for you"),
    ("Automatic patching (PaaS)", "In PaaS/SaaS the provider applies OS and software patches automatically — a built-in security benefit versus self-managed IaaS"),
    ("Microsoft Defender for Cloud", "Azure's security posture management and threat protection service for cloud and hybrid resources"),
    ("Microsoft Entra ID", "Microsoft's cloud identity and access management service, formerly named Azure Active Directory"),
    ("Management OF the cloud", "What the platform does to manage your resources: auto-scale, template-based deployment, automatic health monitoring, automatic alerts"),
    ("Management IN the cloud", "How you administer cloud resources: the web portal, command-line interface (CLI), APIs, and PowerShell"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company runs its web app on several Azure VMs across availability zones behind a load balancer. When one VM fails during a hardware fault, users notice nothing. Which cloud benefit does this demonstrate?",
        "choices": ["Elasticity", "High availability", "Cost predictability", "Governance"],
        "answer": 1,
        "explain": "High availability means maximizing uptime so users keep getting service despite component failures — achieved here with redundant instances, zones, and load balancing. Elasticity is about automatic capacity change, not surviving failures, and the scenario says nothing about cost or standards enforcement.",
    },
    {
        "type": "mc",
        "q": "Which document formally expresses a cloud service's availability guarantee as a percentage and entitles the customer to service credits if the guarantee is missed?",
        "choices": ["The Well-Architected Framework", "A resource template", "A service-level agreement (SLA)", "A compliance certification"],
        "answer": 2,
        "explain": "The SLA is the provider's contractual uptime commitment, written in 'nines' (99.9%, 99.99%). Missing it earns the customer service credits — not restored time. The Well-Architected Framework is design guidance, and templates and certifications address deployment standards and compliance, not uptime guarantees.",
    },
    {
        "type": "mc",
        "q": "An application is covered by a 99.9% SLA. Approximately how much downtime does that permit per month?",
        "choices": ["4.32 minutes", "43.2 minutes", "1.68 hours", "5 minutes per year"],
        "answer": 1,
        "explain": "Three nines (99.9%) allows about 43.2 minutes of downtime per month. 4.32 minutes/month is four nines (99.99%), 1.68 hours is what 99% allows per WEEK, and roughly 5 minutes per YEAR is five nines (99.999%).",
    },
    {
        "type": "mc",
        "q": "Moving a service's SLA from 99.9% to 99.99% changes the allowed downtime how?",
        "choices": [
            "It roughly halves the allowed downtime",
            "It cuts the allowed downtime by about 10 times",
            "It adds about 10 times more allowed downtime",
            "It has no effect until 99.999% is reached",
        ],
        "answer": 1,
        "explain": "Each additional nine reduces permitted downtime by roughly a factor of ten: 43.2 minutes/month at 99.9% drops to 4.32 minutes/month at 99.99%. That extra nine usually also means a big jump in architecture cost — more instances and zones.",
    },
    {
        "type": "mc",
        "q": "An app depends on two Azure services in series, each with a 99.9% SLA. What can you say about the app's overall (composite) availability guarantee?",
        "choices": [
            "It remains exactly 99.9%",
            "It rises to 99.99% because the services back each other up",
            "It falls below 99.9% because chained SLAs multiply downward",
            "SLAs cannot be combined across services",
        ],
        "answer": 2,
        "explain": "Composite SLAs multiply: 99.9% x 99.9% is about 99.8%, so every added dependency lowers the overall guarantee. Chaining services never raises availability by itself — that requires redundancy, not serial dependency.",
    },
    {
        "type": "mc",
        "q": "A database VM is running out of memory, so an administrator resizes it to a larger VM size with more vCPUs and RAM. What is this called?",
        "choices": ["Horizontal scaling (scale out)", "Elasticity", "Vertical scaling (scale up)", "Decentralization"],
        "answer": 2,
        "explain": "Vertical scaling (scaling up) makes a single instance more powerful — a bigger VM size. It is simple but capped by the largest available size and usually needs a restart. Horizontal scaling would add more instances instead, and elasticity requires automatic bidirectional scaling.",
    },
    {
        "type": "mc",
        "q": "To handle growing traffic, a team adds four more identical web server instances behind the load balancer. Which approach is this, and what side benefit does it bring?",
        "choices": [
            "Scale up — lower licensing costs",
            "Scale out — added redundancy that also improves availability",
            "Scale up — automatic cost reduction",
            "Scale in — reduced attack surface",
        ],
        "answer": 1,
        "explain": "Adding more instances is horizontal scaling (scale out), which is near-limitless and inherently adds redundancy — if one instance fails, the rest keep serving, improving availability too. Scale up changes one node's size, and scale in REMOVES instances.",
    },
    {
        "type": "mc",
        "q": "During a flash sale, an App Service automatically grows from 3 to 30 instances, then automatically returns to 3 that evening. Which benefit does this BEST demonstrate?",
        "choices": ["Elasticity", "Vertical scalability", "Reliability", "Governance"],
        "answer": 0,
        "explain": "Elasticity is automatic scaling in BOTH directions — expanding for the spike and contracting afterward with no human action, so you pay only for what you use. The shrink-back plus automation is what elevates this beyond plain scalability; nothing failed, so reliability is not the theme.",
    },
    {
        "type": "mc",
        "q": "What distinguishes elasticity from plain scalability on the AZ-900 exam?",
        "choices": [
            "Elasticity only applies to storage, scalability to compute",
            "Elasticity is manual, scalability is automatic",
            "Elasticity is automatic and works in both directions — growing and shrinking with demand",
            "There is no difference; the terms are interchangeable",
        ],
        "answer": 2,
        "explain": "Scalability is the general ability to change capacity, which can be planned and manual. Elasticity adds two markers: it happens automatically, and it goes both ways — resources shrink back when demand falls. If an admin manually resizes a VM, that is scalability, not elasticity.",
    },
    {
        "type": "mc",
        "q": "A solution is deployed across three Azure regions. When an entire region goes down, the application self-heals and continues serving users from the other regions. Which cloud benefit is this?",
        "choices": ["Cost predictability", "Reliability", "Manageability", "Vertical scaling"],
        "answer": 1,
        "explain": "Reliability is the ability to recover from failures and continue to function — delivered here by a decentralized, multi-region design that absorbs even a regional outage. High availability focuses on maximizing uptime via redundancy; the recovery-and-keep-functioning wording signals reliability.",
    },
    {
        "type": "mc",
        "q": "Reliability — the ability of a system to recover from failures and continue to function — is a pillar of which piece of Microsoft guidance?",
        "choices": [
            "The Microsoft Cost Management framework",
            "The Azure Well-Architected Framework",
            "The shared responsibility model",
            "The Cloud Adoption SLA",
        ],
        "answer": 1,
        "explain": "Reliability is one of the pillars of the Azure Well-Architected Framework, alongside cost optimization, performance efficiency, security, and operational excellence. The shared responsibility model divides duties between provider and customer; Cost Management is a spending tool, not a design framework.",
    },
    {
        "type": "mc",
        "q": "A streaming service wants users to experience consistent response times even when viewership triples during live events. Which combination of cloud capabilities delivers this PERFORMANCE predictability?",
        "choices": [
            "Budgets and spending alerts",
            "Autoscaling, load balancing, and high-availability design",
            "Azure Policy and resource templates",
            "The TCO calculator and pricing calculator",
        ],
        "answer": 1,
        "explain": "Performance predictability means a consistent user experience as load changes, which autoscaling (right amount of capacity), load balancing (spread the work), and HA design (survive failures) provide together. Budgets and calculators serve COST predictability, and Policy/templates serve governance.",
    },
    {
        "type": "mc",
        "q": "Before deploying a new workload, an architect wants to estimate what a planned set of Azure VMs, storage, and databases will cost per month. Which tool should the architect use?",
        "choices": ["The pricing calculator", "The TCO calculator", "Microsoft Defender for Cloud", "Azure Policy"],
        "answer": 0,
        "explain": "The pricing calculator estimates the cost of a planned Azure deployment before you build it. The TCO calculator instead compares an existing on-premises environment against Azure to justify a migration, Defender for Cloud is a security tool, and Azure Policy enforces standards.",
    },
    {
        "type": "mc",
        "q": "A CFO asks, 'What does our current on-premises datacenter cost us, and what would the same workloads cost in Azure?' Which tool answers this migration question?",
        "choices": [
            "Microsoft Cost Management budgets",
            "The pricing calculator",
            "The total cost of ownership (TCO) calculator",
            "The Azure SLA page",
        ],
        "answer": 2,
        "explain": "The TCO calculator's whole purpose is comparing current on-premises costs (hardware, power, IT labor) against running the same workloads in Azure. The pricing calculator only estimates a future Azure deployment, and budgets track spending that is already happening.",
    },
    {
        "type": "mc",
        "q": "After migrating, a company wants real-time visibility into Azure spending, a monthly budget, and an alert when spending is forecast to exceed it. Which service provides this?",
        "choices": ["The TCO calculator", "Microsoft Entra ID", "The pricing calculator", "Microsoft Cost Management"],
        "answer": 3,
        "explain": "Microsoft Cost Management (formerly Azure Cost Management) tracks actual spend in real time, supports budgets, fires threshold and anomaly alerts, and forecasts future costs. The two calculators are pre-deployment estimation tools, and Entra ID is the identity service.",
    },
    {
        "type": "mc",
        "q": "A company must ensure every resource deployed by any team meets corporate standards — required tags, approved regions, allowed VM sizes — automatically and auditable from one place. Which cloud benefit and Azure service fit?",
        "choices": [
            "Elasticity, via autoscale rules",
            "Governance, via Azure Policy and templates",
            "Performance predictability, via load balancing",
            "High availability, via availability zones",
        ],
        "answer": 1,
        "explain": "Governance means keeping the whole estate compliant with corporate standards, and Azure Policy plus template-based deployment enforces those standards at creation time, flags or blocks drift, and provides central audit. The other options address capacity, performance, and uptime — not standards enforcement.",
    },
    {
        "type": "mc",
        "q": "Which security burden shifts from the customer to the provider when moving workloads to a public cloud like Azure?",
        "choices": [
            "Classifying the company's data",
            "Managing which users can access the application",
            "DDoS mitigation and physical datacenter security",
            "Writing secure application code",
        ],
        "answer": 2,
        "explain": "Internet-scale DDoS mitigation and hardened physical security (guarded, certified datacenters) are things few individual companies can do well, and the cloud provider absorbs them. Data classification, user access, and secure code always remain the customer's responsibility in every service model.",
    },
    {
        "type": "mc",
        "q": "A team moves its web app from self-managed VMs (IaaS) to Azure App Service (PaaS). Which SECURITY benefit do they gain automatically?",
        "choices": [
            "The provider now patches the operating system and platform software",
            "The app no longer needs user authentication",
            "Their application code is automatically rewritten to be secure",
            "Their data is exempt from compliance requirements",
        ],
        "answer": 0,
        "explain": "In PaaS the provider applies OS and platform patches automatically — closing the classic unpatched-system breach vector that customers must handle themselves in IaaS. Authentication, secure code, and compliance obligations for data remain the customer's job in every model.",
    },
    {
        "type": "mc",
        "q": "A government agency must prove its workloads meet strict national and industry regulations. How does using a major cloud provider HELP rather than hinder this?",
        "choices": [
            "Regulations do not apply to resources hosted in the cloud",
            "The provider maintains certifications and audit reports customers can leverage to meet government and industry standards",
            "The agency can disable compliance checks in the portal",
            "Cloud data is automatically anonymized",
        ],
        "answer": 1,
        "explain": "Cloud providers invest heavily in certifications and attestations (government, industry, regional), letting customers build on infrastructure already audited against those standards — often more than the agency could certify alone. Regulations still fully apply; the cloud makes meeting them easier, not optional.",
    },
    {
        "type": "mc",
        "q": "Which Azure service manages user identities and access, and was formerly named Azure Active Directory?",
        "choices": ["Microsoft Defender for Cloud", "Azure Policy", "Microsoft Entra ID", "Microsoft Cost Management"],
        "answer": 2,
        "explain": "Microsoft Entra ID is the current (post-2023) name for the identity and access management service formerly called Azure Active Directory — the exam uses the new name. Defender for Cloud handles security posture, Policy enforces standards, and Cost Management tracks spend.",
    },
    {
        "type": "mc",
        "q": "A security team wants a single Azure service that assesses the security posture of its cloud and hybrid resources and provides threat protection recommendations. Which should it use?",
        "choices": ["Microsoft Defender for Cloud", "Microsoft Entra ID", "The pricing calculator", "Azure autoscale"],
        "answer": 0,
        "explain": "Microsoft Defender for Cloud is Azure's security posture management and threat protection service, scoring configuration weaknesses and surfacing threats across cloud and hybrid workloads. Entra ID is identity, and the other two options address cost estimation and capacity.",
    },
    {
        "type": "mc",
        "q": "Which of the following is an example of management OF the cloud rather than management IN the cloud?",
        "choices": [
            "An engineer runs Azure CLI commands from a laptop",
            "An admin signs in to the Azure portal",
            "Resources automatically scale and raise alerts when health degrades",
            "A script calls Azure REST APIs",
        ],
        "answer": 2,
        "explain": "Management OF the cloud is what the platform does for your resources: auto-scaling, template deployment, automatic health monitoring, and automatic alerts. The CLI, portal, and APIs are all interfaces a human administers WITH — that is management IN the cloud.",
    },
    {
        "type": "mc",
        "q": "Which list correctly names the ways you manage your Azure environment 'IN the cloud'?",
        "choices": [
            "Autoscale, templates, automatic monitoring, automatic alerts",
            "Web portal, command-line interface, APIs, PowerShell",
            "SLAs, service credits, budgets, forecasts",
            "Regions, zones, load balancers, scale sets",
        ],
        "answer": 1,
        "explain": "Management IN the cloud describes HOW you administer: through the web portal, the CLI, APIs, and PowerShell. The first option lists management OF the cloud (what the platform automates); the others mix availability and cost vocabulary that belongs to different benefits.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Elasticity refers only to automatically ADDING resources during demand spikes.",
        "answer": False,
        "explain": "Elasticity is bidirectional: resources grow during spikes AND shrink back automatically when demand falls. The shrink-back is what makes pay-as-you-go economical — automatic growth alone is only half of elasticity.",
    },
    {
        "type": "tf",
        "q": "True or False: A 99.99% SLA permits roughly one-tenth the downtime of a 99.9% SLA.",
        "answer": True,
        "explain": "Each additional nine cuts allowed downtime by about 10x: 99.9% permits 43.2 minutes/month while 99.99% permits 4.32 minutes/month. Continuing the pattern, 99.999% allows only about five minutes per YEAR.",
    },
    {
        "type": "tf",
        "q": "True or False: Reliability — the ability of a system to recover from failures and continue to function — is one of the pillars of the Azure Well-Architected Framework.",
        "answer": True,
        "explain": "Reliability is a Well-Architected Framework pillar, alongside cost optimization, performance efficiency, security, and operational excellence. The cloud supports it through self-healing services and decentralized, multi-region deployment.",
    },
    {
        "type": "tf",
        "q": "True or False: An administrator using PowerShell to configure Azure resources is an example of management IN the cloud.",
        "answer": True,
        "explain": "Management IN the cloud is about the interfaces humans administer with: the web portal, CLI, APIs, and PowerShell. Management OF the cloud, by contrast, is what the platform automates — auto-scaling, template deployment, and automatic monitoring and alerts.",
    },
    {
        "type": "tf",
        "q": "True or False: When using a PaaS offering such as Azure App Service, the customer is responsible for applying operating system security patches.",
        "answer": False,
        "explain": "Automatic OS and platform patching is a built-in security benefit of PaaS — the provider handles it. Customers patch the OS themselves only in IaaS, where they manage everything from the operating system upward.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The cloud benefit in which resources automatically increase during demand spikes AND automatically decrease when demand falls is called ______. (type your answer)",
        "answers": ["elasticity", "elastic", "elastic scaling"],
        "explain": "Elasticity pairs autoscaling with pay-as-you-go economics: capacity expands for peaks and contracts afterward with no human action. Its exam markers are 'automatic' and 'both directions', which distinguish it from plain scalability.",
    },
    {
        "type": "fill",
        "q": "A cloud provider's formal uptime guarantee, expressed as a percentage such as 99.99%, is documented in a ______. (type the acronym)",
        "answers": ["sla", "service level agreement", "service level agreements"],
        "explain": "The service-level agreement (SLA) states the availability commitment in nines and entitles customers to service credits when it is missed. Composite SLAs for chained services multiply downward, lowering the overall guarantee.",
    },
    {
        "type": "fill",
        "q": "Adding more VM instances behind a load balancer — rather than making one VM bigger — is known as ______ scaling. (type your answer)",
        "answers": ["horizontal", "scale out", "scaling out", "horizontal scaling", "out"],
        "explain": "Horizontal scaling (scaling out) adds instances that share the load, offering near-limitless growth plus redundancy. Vertical scaling (up) instead resizes a single instance and eventually hits the largest available size.",
    },
    {
        "type": "fill",
        "q": "The Azure service used to track real-time spending, create budgets, and receive alerts when costs exceed thresholds is Microsoft ______. (type your answer)",
        "answers": ["cost management", "microsoft cost management", "azure cost management", "cost management and billing"],
        "explain": "Microsoft Cost Management (the current name; older material says Azure Cost Management) delivers cost predictability after deployment: real-time tracking, budgets, alerts, and forecasts. The pricing and TCO calculators, by contrast, estimate costs BEFORE deployment.",
    },
    {
        "type": "fill",
        "q": "The calculator that compares the cost of your current on-premises datacenter against running the same workloads in Azure is the ______ calculator. (type the acronym)",
        "answers": ["tco", "total cost of ownership"],
        "explain": "The total cost of ownership (TCO) calculator is the migration business-case tool: current on-prem costs versus Azure. The pricing calculator estimates a planned Azure deployment, and Microsoft Cost Management tracks actual spend once you are running.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each cloud benefit to its description.",
        "pairs": [
            ["High availability", "Maximizing uptime so users get service despite component failures"],
            ["Reliability", "Recovering from failures and continuing to function via decentralized design"],
            ["Elasticity", "Automatic resource growth and shrinkage matched to real-time demand"],
            ["Governance", "Enforcing corporate and regulatory standards across all resources"],
            ["Predictability", "Confidence in both future performance and future cost"],
        ],
        "explain": "HA is staying up despite failures (measured in SLA nines); reliability is bouncing back and continuing to function; elasticity is automatic bidirectional scaling; governance enforces standards through policies and templates; predictability spans consistent performance and knowable cost.",
    },
    {
        "type": "match",
        "q": "Match each Azure tool or service to its purpose.",
        "pairs": [
            ["Pricing calculator", "Estimate the cost of a planned Azure deployment"],
            ["TCO calculator", "Compare on-premises costs with running the workloads in Azure"],
            ["Microsoft Cost Management", "Track real-time spend, set budgets, and alert on overspend"],
            ["Azure Policy", "Enforce corporate standards on all deployed resources"],
            ["Microsoft Defender for Cloud", "Security posture management and threat protection"],
            ["Microsoft Entra ID", "Identity and access management (formerly Azure Active Directory)"],
        ],
        "explain": "The three cost tools split by time: pricing calculator before deployment, TCO calculator for the migration comparison, Cost Management during operation. Policy is the governance enforcer, Defender for Cloud watches security posture, and Entra ID (the post-2023 name for Azure AD) handles identity.",
    },
    {
        "type": "match",
        "q": "Match each SLA percentage to the downtime it allows.",
        "pairs": [
            ["99%", "1.68 hours per week"],
            ["99.9%", "43.2 minutes per month"],
            ["99.99%", "4.32 minutes per month"],
            ["99.999%", "About 5 minutes per year"],
        ],
        "explain": "Note the units shift as the nines climb: two nines is measured in hours per week, three and four nines in minutes per month (43.2 then 4.32 — the 10x cut), and five nines in minutes per YEAR. Each added nine reduces allowed downtime by roughly a factor of ten.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange these SLA levels from the MOST allowed downtime to the LEAST.",
        "items": ["99%", "99.9%", "99.99%", "99.999%"],
        "explain": "More nines means less downtime: 99% allows 1.68 hours per week, 99.9% allows 43.2 minutes per month, 99.99% allows 4.32 minutes per month, and 99.999% allows only about five minutes per year. Each step is roughly a tenfold reduction.",
    },
    {
        "type": "order",
        "q": "Arrange the lifecycle of an elastic autoscaling event, from first to last.",
        "items": [
            "Incoming traffic spikes and instance CPU climbs",
            "Automatic monitoring detects the autoscale threshold is breached",
            "The platform automatically adds new instances",
            "The load balancer spreads traffic across the enlarged pool",
            "Demand falls and the extra instances are automatically removed",
        ],
        "explain": "Elasticity in motion: metrics rise, the autoscale rule fires, capacity scales out, load balancing keeps the user experience consistent (performance predictability), and — the step that makes it elasticity rather than mere scalability — capacity automatically scales back in when demand subsides.",
    },
]
