TOPIC = {
    "id": "1.3",
    "domain": 1,
    "title": "Describe cloud service types.",
    "short": "Cloud Service Types",
}

TERMS = [
    ("Infrastructure as a service (IaaS)", "Provider supplies virtualized compute, network, and storage; customer manages everything from the OS up — maximum control and flexibility (e.g., Azure Virtual Machines)"),
    ("Platform as a service (PaaS)", "Provider manages OS, middleware, runtime, and development tools; customer manages only application code and data (e.g., Azure App Service)"),
    ("Software as a service (SaaS)", "Provider delivers a complete, finished application by subscription; customer manages only data, devices, and accounts/identities (e.g., Microsoft 365)"),
    ("Shared responsibility model", "The division of management and security duties between Microsoft and the customer, which shifts with the service type (IaaS vs PaaS vs SaaS)"),
    ("Lift and shift (rehosting)", "Migrating existing servers/workloads to cloud VMs with minimal or no changes — the classic IaaS use case"),
    ("Azure Virtual Machines", "IaaS compute service providing rentable VMs on which the customer installs, configures, and patches the operating system"),
    ("Azure virtual network (VNet)", "IaaS networking service — a logically isolated network in Azure where you define subnets and private IP ranges for your resources"),
    ("Azure Storage", "IaaS storage building block offering disks, blobs, and file shares managed by Microsoft at the hardware level"),
    ("Azure App Service", "PaaS offering for hosting web applications and APIs — Microsoft manages the OS, web server, runtime, and patching"),
    ("Azure SQL Database", "PaaS managed relational database — no database licenses to buy and no OS or engine patching for the customer"),
    ("Azure Functions", "Event-driven serverless compute in the PaaS category — upload code that runs when triggered, billed only while executing"),
    ("Serverless computing", "A PaaS execution model where the provider allocates servers invisibly and on demand; the customer never provisions or manages them"),
    ("Microsoft 365", "SaaS productivity suite (email, calendaring, Office apps) delivered by subscription over the Internet"),
    ("Dynamics 365", "SaaS business application suite for CRM/ERP — a complete finished product with nothing for the customer to host"),
    ("Middleware", "Software layer between the OS and applications (e.g., message queues, app servers) — customer-managed in IaaS, provider-managed in PaaS/SaaS"),
    ("Runtime", "The environment that executes application code (e.g., .NET, Node.js) — customer-managed in IaaS, provider-managed in PaaS/SaaS"),
    ("Guest OS patching", "Applying operating system updates inside a VM — always the CUSTOMER'S responsibility in IaaS, the provider's in PaaS and SaaS"),
    ("Virtualization layer (hypervisor)", "The software that hosts VMs on physical servers — Microsoft's responsibility in every cloud service type, including IaaS"),
    ("Microsoft Entra ID", "Microsoft's cloud identity and access service (formerly Azure Active Directory) — how customers manage the accounts/identities they retain in every service type"),
    ("Development framework (PaaS use case)", "Using a provider-managed platform and tools to build web or mobile apps without buying or maintaining the underlying software stack"),
    ("Analytics/business intelligence (PaaS use case)", "Using platform-supplied tools to mine and analyze data for insight, without managing the analysis infrastructure"),
    ("Microsoft Cost Management", "Azure tool for tracking and analyzing cloud spend — useful for comparing consumption costs across IaaS, PaaS, and SaaS choices"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company is closing its datacenter and wants to move 40 existing Windows and Linux servers to Azure with as few changes as possible. Which cloud service type fits this lift-and-shift migration?",
        "choices": ["SaaS", "PaaS", "IaaS", "Serverless"],
        "answer": 2,
        "explain": "Lift-and-shift (rehosting) moves workloads unchanged onto Azure Virtual Machines — IaaS — because the workloads expect a full operating system the customer controls. PaaS would require re-platforming the apps, and SaaS would mean replacing them with finished products entirely.",
    },
    {
        "type": "mc",
        "q": "Which set of Azure services are all examples of infrastructure as a service (IaaS)?",
        "choices": [
            "Azure App Service, Azure SQL Database, Azure Functions",
            "Azure Virtual Machines, virtual networks, Azure Storage",
            "Microsoft 365, Dynamics 365, Teams",
            "Azure Functions, Microsoft 365, virtual networks",
        ],
        "answer": 1,
        "explain": "IaaS is the raw building blocks: Virtual Machines (compute), virtual networks (networking), and Azure Storage (storage). App Service, SQL Database, and Functions are PaaS, while Microsoft 365 and Dynamics 365 are SaaS finished products.",
    },
    {
        "type": "mc",
        "q": "An Azure VM running Windows Server is missing critical security updates. Under the shared responsibility model, who is responsible for applying them?",
        "choices": [
            "Microsoft, because it operates the Azure datacenter",
            "Microsoft, because Azure automatically patches all VMs",
            "The customer, because guest OS patching is the customer's job in IaaS",
            "No one — VMs in the cloud do not require patching",
        ],
        "answer": 2,
        "explain": "In IaaS the provider manages only the physical hosts, network, and hypervisor; everything from the guest OS upward — including patching — belongs to the customer. This is the exam's favorite dividing line: OS patching is yours in IaaS, Microsoft's in PaaS and SaaS.",
    },
    {
        "type": "mc",
        "q": "A development team wants to deploy a web application to Azure 'without managing the underlying operating system or runtime.' Which service should they choose?",
        "choices": ["Azure Virtual Machines", "Azure App Service", "Microsoft 365", "An Azure virtual network"],
        "answer": 1,
        "explain": "'Without managing the underlying operating system' is the signature PaaS phrase, and Azure App Service is the PaaS web-hosting example: Microsoft manages the OS, web server, and runtime while the team deploys only code. Virtual Machines would leave the OS with the customer, and Microsoft 365 is a finished SaaS product, not a place to deploy your own app.",
    },
    {
        "type": "mc",
        "q": "A company wants a relational database in Azure but refuses to buy database licenses or perform any engine or OS patching. Which offering meets this requirement?",
        "choices": [
            "SQL Server installed on an Azure Virtual Machine",
            "Azure SQL Database",
            "A database exported to Azure Storage blobs",
            "Dynamics 365",
        ],
        "answer": 1,
        "explain": "Azure SQL Database is PaaS: licensing, OS, and database-engine patching are all Microsoft's responsibility, leaving the customer only schema and data. SQL Server on a VM is IaaS — the customer would still license and patch it — and blobs are raw storage, not a managed database service.",
    },
    {
        "type": "mc",
        "q": "Every time an image lands in a storage account, a short piece of code must run to create a thumbnail. The team wants no pre-provisioned servers and to pay only while the code executes. Which Azure service fits?",
        "choices": ["Azure Functions", "Azure Virtual Machines", "Azure virtual network", "Dynamics 365"],
        "answer": 0,
        "explain": "Event-driven code, no server provisioning, and per-execution billing describe serverless computing, and Azure Functions is Azure's serverless example within the PaaS category. A VM would run (and bill) continuously and leave the OS with the customer.",
    },
    {
        "type": "mc",
        "q": "A ten-person startup needs company email, calendaring, and document apps running by tomorrow, with zero infrastructure to deploy or maintain. Which cloud service type fits?",
        "choices": ["IaaS", "PaaS", "SaaS", "A hybrid deployment"],
        "answer": 2,
        "explain": "Email/calendaring and productivity apps are the textbook SaaS use cases — a complete finished product (Microsoft 365) consumed by subscription through a browser. IaaS and PaaS would both require the startup to build or run something itself.",
    },
    {
        "type": "mc",
        "q": "An organization subscribes to Dynamics 365 for customer relationship management. Which cloud service type is it consuming?",
        "choices": ["PaaS, because Dynamics 365 is a development platform", "IaaS, because CRM data is stored on VMs", "Serverless, because there are no servers", "SaaS, because it is a complete finished application"],
        "answer": 3,
        "explain": "Dynamics 365 is a finished CRM/ERP product delivered by subscription — SaaS. The customer builds nothing and hosts nothing; Microsoft runs the entire stack, from datacenter to application code, while the customer keeps its data and user identities.",
    },
    {
        "type": "mc",
        "q": "A company moved its email to Microsoft 365 (SaaS). Which of the following is STILL the customer's responsibility?",
        "choices": [
            "Patching the mail server's operating system",
            "Managing user accounts, devices, and the mailbox data",
            "Upgrading the hypervisor hosting the service",
            "Maintaining the physical network in the datacenter",
        ],
        "answer": 1,
        "explain": "Even in SaaS — the least-responsibility model — the customer always retains its data, connected devices, and accounts/identities, which it governs through Microsoft Entra ID (formerly Azure Active Directory). The OS, hypervisor, and physical plant are all Microsoft's in SaaS.",
    },
    {
        "type": "mc",
        "q": "Which cloud service type gives the customer the MOST control and flexibility over its cloud computing resources?",
        "choices": ["SaaS", "PaaS", "IaaS", "All three offer identical control"],
        "answer": 2,
        "explain": "IaaS is the closest cloud analog to owning servers: the customer controls the OS, installed software, middleware, and configuration. That maximum control is paired with maximum responsibility — the trade-off runs the opposite direction for SaaS, which offers the least of both.",
    },
    {
        "type": "mc",
        "q": "Which cloud service type places the LEAST management responsibility on the customer?",
        "choices": ["IaaS", "PaaS", "On-premises", "SaaS"],
        "answer": 3,
        "explain": "In SaaS the provider manages everything from the datacenter through the application itself; the customer keeps only data, devices, and identities. IaaS is the opposite end of the ladder, and on-premises means the customer manages the entire stack including hardware.",
    },
    {
        "type": "mc",
        "q": "A team runs its application on Azure App Service (PaaS). Which pair of responsibilities remains with the CUSTOMER?",
        "choices": [
            "The application code and its data",
            "The operating system and the runtime",
            "The hypervisor and physical storage",
            "The middleware and development tools",
        ],
        "answer": 0,
        "explain": "PaaS transfers the OS, middleware, runtime, and development tools to the provider, leaving the customer exactly two rungs: application code and data. If the question hands you PaaS and asks what's left for the customer, the answer is always 'code and data.'",
    },
    {
        "type": "mc",
        "q": "Under the shared responsibility model, which layer is Microsoft's responsibility in ALL THREE cloud service types (IaaS, PaaS, and SaaS)?",
        "choices": [
            "Application code",
            "The guest operating system",
            "Physical hosts, physical network, and the virtualization layer",
            "User accounts and identities",
        ],
        "answer": 2,
        "explain": "The physical datacenter, physical servers and networking, and the hypervisor are always the provider's, even in IaaS. The guest OS is the customer's in IaaS only, and data plus accounts/identities are always the customer's — the mirror-image constant on the other side.",
    },
    {
        "type": "mc",
        "q": "A finance director wants to stop buying software licenses and paying staff to apply patches, but the company must keep running its own custom-built application. Which service type solves this?",
        "choices": [
            "SaaS, by subscribing to an equivalent finished product",
            "PaaS, so the provider handles the OS, runtime, and licensing beneath their code",
            "IaaS, so the company can patch on its own schedule",
            "On-premises, using volume licensing",
        ],
        "answer": 1,
        "explain": "The company still runs its OWN application, so SaaS is out — SaaS would replace the app, not host it. PaaS sheds exactly the burdens named (license purchasing and patch management for the platform layers) while keeping the custom code and data with the customer.",
    },
    {
        "type": "mc",
        "q": "A data team wants to mine and analyze large datasets using tools built into a cloud platform, without standing up or maintaining any analysis infrastructure. This is a classic use case for which service type?",
        "choices": ["IaaS", "SaaS", "PaaS", "A private cloud"],
        "answer": 2,
        "explain": "Analytics and business intelligence are named PaaS use cases: the provider supplies the managed analysis platform and tools, and the customer brings the data and questions. IaaS would make the team build the analytics stack itself on raw VMs.",
    },
    {
        "type": "mc",
        "q": "A QA team needs to spin up full test environments quickly, install specific OS versions and low-level agents, and tear everything down after each cycle. Which service type fits?",
        "choices": ["SaaS", "IaaS", "PaaS", "Dynamics 365"],
        "answer": 1,
        "explain": "Testing and development that requires full control of the operating system is a named IaaS use case — only IaaS leaves the OS rung with the customer, allowing specific OS builds and kernel-level agents. PaaS hides the OS entirely, which is exactly what this team cannot accept.",
    },
    {
        "type": "mc",
        "q": "When a workload moves from Azure Virtual Machines (IaaS) to Azure App Service (PaaS), which responsibilities SHIFT from the customer to Microsoft?",
        "choices": [
            "Application code and data",
            "User identities and connected devices",
            "The operating system, middleware, and runtime",
            "The physical hosts and hypervisor",
        ],
        "answer": 2,
        "explain": "Moving up the ladder from IaaS to PaaS hands the OS, middleware, and runtime to the provider. Code and data stay with the customer in both models, identities and devices are always the customer's, and the physical/virtualization layers were already Microsoft's even in IaaS.",
    },
    {
        "type": "mc",
        "q": "An Azure VM was breached because a well-known OS vulnerability was left unpatched for months. Under the shared responsibility model, why does this failure fall on the customer?",
        "choices": [
            "Because Microsoft never patches anything in Azure",
            "Because in IaaS everything from the guest OS upward is customer-managed",
            "Because security is always solely the customer's job in the cloud",
            "Because the customer chose the wrong Azure region",
        ],
        "answer": 1,
        "explain": "IaaS splits the stack at the hypervisor: Microsoft secures the physical and virtualization layers, and the customer owns the guest OS, patches, middleware, apps, and data. Security is shared — not solely either party's — which is what makes choice C wrong.",
    },
    {
        "type": "mc",
        "q": "Which pairing of Azure offering and cloud service type is correct?",
        "choices": [
            "Azure Virtual Machines — SaaS",
            "Microsoft 365 — PaaS",
            "Azure SQL Database — IaaS",
            "Azure Functions — PaaS (serverless)",
        ],
        "answer": 3,
        "explain": "Azure Functions is serverless compute, which sits within the PaaS category — the provider manages everything below the customer's code. Virtual Machines are IaaS, Microsoft 365 is SaaS, and Azure SQL Database is PaaS, so each other pairing is inverted.",
    },
    {
        "type": "mc",
        "q": "Which description defines software as a service (SaaS)?",
        "choices": [
            "A complete, finished application licensed by subscription and used over the Internet",
            "Rentable virtual machines on which the customer installs an operating system",
            "A managed platform where developers deploy code without managing servers",
            "A dedicated physical circuit into the cloud provider's network",
        ],
        "answer": 0,
        "explain": "SaaS is the finished-product model: the provider builds, hosts, patches, and operates the entire application, and the customer subscribes and uses it. Rentable VMs describe IaaS, the managed code platform describes PaaS, and the dedicated circuit is a connectivity option, not a service type.",
    },
    {
        "type": "mc",
        "q": "A regulated firm must control exactly which OS build, security agents, and installed software run on its cloud servers to satisfy auditors. Which service type must it choose, and what is the trade-off?",
        "choices": [
            "SaaS — trade-off: it must write its own application",
            "IaaS — trade-off: it takes on OS patching and management itself",
            "PaaS — trade-off: it must manage the physical hardware",
            "IaaS — trade-off: Microsoft controls the guest OS configuration",
        ],
        "answer": 1,
        "explain": "Only IaaS leaves the operating system under customer control, so it is the required choice — and the price of that control is responsibility for patching and managing that OS. PaaS never exposes the OS, and no cloud model has the customer managing physical hardware.",
    },
    {
        "type": "mc",
        "q": "In SaaS, users still need to sign in securely with company-managed accounts. Which Microsoft service does the customer use to manage those identities?",
        "choices": [
            "Microsoft Entra ID (formerly Azure Active Directory)",
            "Azure Storage",
            "Azure App Service",
            "The SaaS provider manages all identities; the customer manages none",
        ],
        "answer": 0,
        "explain": "Accounts and identities remain the customer's responsibility in every service type, and Microsoft Entra ID — the renamed Azure Active Directory — is the cloud identity service used to manage them. Storage and App Service are IaaS/PaaS resources unrelated to identity, and choice D contradicts the shared responsibility model.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: In IaaS, the customer is responsible for managing the virtualization (hypervisor) layer that hosts its virtual machines.",
        "answer": False,
        "explain": "Even in IaaS — the most customer-managed cloud model — Microsoft owns the hypervisor, physical hosts, storage hardware, and datacenter network. The customer's responsibility begins at the guest operating system inside the VM.",
    },
    {
        "type": "tf",
        "q": "True or False: When an application runs on a PaaS service such as Azure App Service, the customer must still schedule and apply operating system patches.",
        "answer": False,
        "explain": "OS patching is precisely what PaaS takes off the customer's plate: Microsoft manages the OS, middleware, and runtime beneath the app. The customer's remaining duties are its application code and data — OS patching is customer work only in IaaS.",
    },
    {
        "type": "tf",
        "q": "True or False: Adopting SaaS removes ALL management responsibility from the customer.",
        "answer": False,
        "explain": "SaaS minimizes but never eliminates customer responsibility: the customer still governs its data, the devices that connect, and user accounts/identities (via Microsoft Entra ID). No cloud service type reduces the customer's share to zero.",
    },
    {
        "type": "tf",
        "q": "True or False: Azure Functions is an example of serverless computing, which falls within the PaaS category of cloud service types.",
        "answer": True,
        "explain": "Serverless is a PaaS pattern taken to its extreme: the platform (including invisible servers) is entirely provider-managed, code runs per event, and billing is per execution. 'Serverless' means the customer never sees or manages servers — not that servers don't exist.",
    },
    {
        "type": "tf",
        "q": "True or False: Compared with rehosting on Azure Virtual Machines, moving a workload to Azure SQL Database and App Service reduces the customer's patching and licensing workload.",
        "answer": True,
        "explain": "That move is IaaS to PaaS: the OS, runtime, and database engine — along with their patch cycles and licenses — shift to Microsoft's side of the shared responsibility model. Avoiding license purchasing and patch management is a named PaaS use case.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The cloud service type that offers maximum control and flexibility, where the customer manages everything from the operating system up, is ______. (type the acronym)",
        "answers": ["iaas", "infrastructure as a service"],
        "explain": "Infrastructure as a service supplies raw compute, network, and storage (Azure VMs, VNets, Azure Storage) and leaves the OS, patches, middleware, apps, and data to the customer — the most control and the most responsibility of the three types.",
    },
    {
        "type": "fill",
        "q": "A scenario says developers must deploy their application 'without managing the underlying operating system.' The cloud service type being described is ______. (type the acronym)",
        "answers": ["paas", "platform as a service"],
        "explain": "That phrase is the signature PaaS keyword: the provider manages the OS, middleware, runtime, and development tools, and the customer keeps only code and data. Azure examples are App Service, Azure SQL Database, and Azure Functions.",
    },
    {
        "type": "fill",
        "q": "Subscribing to a complete, finished product such as Microsoft 365 — with only data, devices, and identities left to manage — is the ______ cloud service type. (type the acronym)",
        "answers": ["saas", "software as a service"],
        "explain": "Software as a service delivers the entire application as a ready-to-use product over the Internet. It carries the least customer responsibility and the least flexibility — you configure and use it, but you never build, host, or patch it.",
    },
    {
        "type": "fill",
        "q": "Migrating existing servers to Azure Virtual Machines with minimal changes — the classic IaaS use case — is known as a ______ migration. (two hyphenated words + 'shift')",
        "answers": ["lift and shift", "lift-and-shift", "lift shift", "rehost", "rehosting"],
        "explain": "Lift-and-shift (rehosting) moves workloads as-is onto IaaS: the applications and OS are unchanged, only the physical layer changes hands to Microsoft. It is fast and low-risk, but the customer keeps OS patching and management duties afterward.",
    },
    {
        "type": "fill",
        "q": "The PaaS execution model in which the provider invisibly allocates compute on demand and bills only while code runs — as with Azure Functions — is called ______ computing. (type your answer)",
        "answers": ["serverless", "server less", "serverless computing"],
        "explain": "Serverless computing abstracts servers away completely: no provisioning, automatic scaling (including to zero), and per-execution billing. Servers still exist — the customer simply never manages or even sees them.",
    },
    {
        "type": "fill",
        "q": "Even in SaaS, the customer manages its accounts and identities using Microsoft's cloud identity service, now named ______ (formerly Azure Active Directory). (type your answer)",
        "answers": ["microsoft entra id", "entra id", "entra", "microsoft entra"],
        "explain": "Microsoft Entra ID is the current name for Azure Active Directory following the post-2023 rebrand, and the exam uses the new name. Identity management is one of the responsibilities the customer retains in every cloud service type, including SaaS.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each Azure offering to its cloud service type and role.",
        "pairs": [
            ["Azure Virtual Machines", "IaaS — rentable VMs; the customer manages and patches the OS"],
            ["Azure App Service", "PaaS — managed web app hosting; customer deploys only code"],
            ["Azure SQL Database", "PaaS — managed relational database; no licensing or patching for the customer"],
            ["Azure Functions", "PaaS (serverless) — event-driven code billed per execution"],
            ["Microsoft 365", "SaaS — complete productivity suite consumed by subscription"],
        ],
        "explain": "Virtual Machines (with VNets and Storage) are the IaaS building blocks; App Service, SQL Database, and Functions are PaaS because Microsoft manages the platform beneath your code; Microsoft 365 (like Dynamics 365) is a finished SaaS product.",
    },
    {
        "type": "match",
        "q": "Match each cloud service type to what the CUSTOMER manages under the shared responsibility model.",
        "pairs": [
            ["On-premises", "The entire stack, including physical hardware and the datacenter"],
            ["IaaS", "Operating system, middleware, runtime, applications, and data"],
            ["PaaS", "Only application code and data"],
            ["SaaS", "Only data, devices, and accounts/identities"],
        ],
        "explain": "Customer responsibility shrinks rung by rung: on-premises means everything; IaaS starts the customer at the guest OS; PaaS strips that down to code and data; SaaS leaves just data, devices, and identities. Microsoft absorbs whatever the customer sheds.",
    },
    {
        "type": "match",
        "q": "Match each business scenario to the cloud service type that best fits it.",
        "pairs": [
            ["Test/dev environments requiring full control of the OS", "IaaS — only this type leaves the OS with the customer"],
            ["Ship a web app with no OS, runtime, or license management", "PaaS — the provider manages the platform beneath the code"],
            ["Company-wide email and calendaring, nothing to host", "SaaS — a finished product; customer keeps data and identities"],
            ["Run code only when an event fires, pay per execution", "Serverless (Azure Functions) — a consumption pattern within PaaS"],
            ["Move aging datacenter servers to the cloud unchanged", "IaaS lift-and-shift — the workload still expects its own OS"],
        ],
        "explain": "Use-case questions are responsibility questions in disguise: match what the scenario says the customer wants to control (or shed) to the service type whose ladder fits. Full OS control forces IaaS; 'no OS management' signals PaaS; a finished app is SaaS; per-event execution is serverless.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the cloud service types from MOST customer management responsibility to LEAST.",
        "items": ["On-premises", "IaaS", "PaaS", "SaaS"],
        "explain": "On-premises means the customer runs the entire stack including hardware; IaaS hands Microsoft the physical and virtualization layers; PaaS adds the OS, middleware, and runtime to Microsoft's side; SaaS leaves the customer only data, devices, and identities. Provider responsibility grows in exactly the same order.",
    },
    {
        "type": "order",
        "q": "As a workload moves up the ladder (IaaS → PaaS → SaaS), arrange these stack layers from the FIRST handed to Microsoft to the one the customer NEVER gives up.",
        "items": [
            "Physical datacenter, servers, and network",
            "Virtualization (hypervisor)",
            "Operating system",
            "Middleware and runtime",
            "Applications",
            "Data, devices, and accounts/identities",
        ],
        "explain": "The physical plant and hypervisor go to Microsoft the moment you enter the cloud (IaaS); the OS, middleware, and runtime transfer at PaaS; the application itself transfers at SaaS. Data, devices, and identities never transfer — they are the customer's in every service type.",
    },
]
