TOPIC = {
    "id": "2.2",
    "domain": 2,
    "title": "Describe Azure compute and networking services.",
    "short": "Compute & Networking",
}

TERMS = [
    ("Azure Virtual Machines", "IaaS compute providing full OS control on Azure hypervisors — you choose size and image, install software, and patch the OS yourself"),
    ("Container", "Lightweight virtualized application environment that virtualizes the OS rather than hardware — shares the host kernel, so there is no guest OS to manage"),
    ("Azure Container Instances (ACI)", "The simplest and fastest way to run a single container in Azure, with no VMs or orchestration to manage"),
    ("Azure Kubernetes Service (AKS)", "Managed Kubernetes service for orchestrating, deploying, and scaling fleets of containers"),
    ("Azure Container Apps", "Serverless container service with built-in features such as automatic scaling and load balancing, without managing orchestration infrastructure"),
    ("Azure Functions", "Serverless, event-driven compute that runs code in response to triggers, scales automatically to zero, and bills per execution on the consumption plan"),
    ("Serverless computing", "Model where the cloud provider fully manages the servers — they still exist but are invisible to you; you deploy only code"),
    ("Azure Virtual Machine Scale Sets", "A group of identical, load-balanced VMs built from one image that can automatically scale instance count with demand or a schedule"),
    ("Availability set", "Placement grouping that spreads VMs across fault domains and update domains within a datacenter, at no extra cost, to survive hardware failure and maintenance"),
    ("Fault domain", "Group of VMs sharing a common power source and network switch — spreading across them protects against unplanned hardware/rack failure"),
    ("Update domain", "Group of VMs that undergo planned maintenance (and reboots) together — Azure updates one update domain at a time"),
    ("Azure Virtual Desktop (AVD)", "Cloud-hosted desktop and application virtualization service delivering full Windows desktops to any device, with multi-session Windows support"),
    ("Managed disk", "Azure-managed virtual disk (OS or data) attached to a VM — Azure handles the underlying storage accounts"),
    ("Network interface (NIC)", "The resource that connects a VM to a subnet of a virtual network; every VM needs at least one"),
    ("Azure App Service", "PaaS for hosting web apps, REST APIs, and mobile back ends in multiple languages, with built-in scaling and load balancing and no infrastructure to manage"),
    ("Deployment slot", "App Service feature that hosts a separate app instance (e.g., staging) that can be swapped into production"),
    ("Virtual network (VNet)", "Logically isolated private network in Azure with a self-defined private IP address space"),
    ("Subnet", "A segment of a VNet's address space used to group resources and apply security and routing per segment"),
    ("Virtual network peering", "Connects two VNets so resources communicate over the Microsoft private backbone, never the public Internet; cross-region peering is called global peering"),
    ("Azure DNS", "Hosting service for DNS domains that resolves records on Azure's global anycast infrastructure using standard Azure credentials and tools"),
    ("Azure VPN Gateway", "Gateway creating encrypted IPsec tunnels over the public Internet between an Azure VNet and other networks"),
    ("Site-to-site VPN", "VPN Gateway connection linking an entire on-premises network (via its VPN device) to an Azure VNet"),
    ("Point-to-site VPN", "VPN Gateway connection linking a single device, such as a remote worker's laptop, to an Azure VNet"),
    ("Azure ExpressRoute", "Private, dedicated connection to Microsoft's cloud via a connectivity provider — traffic never touches the public Internet; not encrypted by default"),
    ("Network security group (NSG)", "Azure resource that filters network traffic to and from subnets and NICs using allow/deny security rules"),
    ("Public endpoint", "A public IP address that makes a service reachable from the Internet"),
    ("Private endpoint", "A private IP address from your VNet's address space assigned to a PaaS service via Private Link, keeping traffic off the public Internet"),
    ("Azure Private Link", "The service behind private endpoints — provides private connectivity from a VNet to Azure PaaS services over the Microsoft network"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company is migrating a legacy application that requires full control over the operating system, custom kernel settings, and specific installed software. Which Azure compute option fits?",
        "choices": ["Azure Functions", "Azure Virtual Machines", "Azure Container Apps", "Azure App Service"],
        "answer": 1,
        "explain": "Azure Virtual Machines are IaaS: you get a complete virtualized computer with full OS access, so anything requiring OS-level customization or a lift-and-shift of legacy software lands here. The trade-off is that you install, configure, and patch the OS yourself — Functions, Container Apps, and App Service all hide the OS from you.",
    },
    {
        "type": "mc",
        "q": "Which statement correctly distinguishes containers from virtual machines?",
        "choices": [
            "Containers virtualize the hardware; VMs virtualize the operating system",
            "Containers each boot their own guest OS, making them faster than VMs",
            "Containers virtualize the operating system and share the host kernel, so there is no guest OS to manage",
            "Containers can only run on Windows hosts, while VMs run any OS",
        ],
        "answer": 2,
        "explain": "A VM virtualizes hardware and carries a full guest OS you must patch; a container virtualizes the OS itself, sharing the host's kernel. That is why containers are lightweight, start in seconds, and leave you no operating system to maintain — the first choice states the distinction exactly backwards.",
    },
    {
        "type": "mc",
        "q": "A team needs to run a short piece of code every time a message lands in a queue. Executions last a few seconds, demand is unpredictable, and the team wants to pay nothing while idle. Which service fits best?",
        "choices": ["Azure Virtual Machine Scale Sets", "Azure Kubernetes Service", "Azure Virtual Desktop", "Azure Functions"],
        "answer": 3,
        "explain": "Azure Functions is serverless, event-driven compute: code runs in response to a trigger (queue message, HTTP request, timer, blob upload), scales automatically — including down to zero — and consumption-plan billing charges only for actual executions. Scale Sets and AKS still bill for running instances even when idle.",
    },
    {
        "type": "mc",
        "q": "A developer wants the simplest, fastest way to run a single container in Azure without managing any virtual machines or orchestration. Which service should they use?",
        "choices": ["Azure Container Instances", "Azure Kubernetes Service", "Azure Virtual Machines", "Azure DNS"],
        "answer": 0,
        "explain": "Azure Container Instances (ACI) is Azure's simplest container option: point it at an image and it runs, PaaS-style, with no VM fleet or orchestrator to operate. AKS is the answer only when the scenario involves orchestrating many containers at scale.",
    },
    {
        "type": "mc",
        "q": "An enterprise runs hundreds of microservice containers and needs automated deployment, scaling, and management of the whole fleet. Which Azure service is designed for this?",
        "choices": ["Azure Container Instances", "Azure Kubernetes Service", "Azure App Service", "Azure Virtual Desktop"],
        "answer": 1,
        "explain": "Azure Kubernetes Service (AKS) is managed Kubernetes — the orchestration layer that deploys, scales, heals, and manages large numbers of containers. ACI is for simple single containers; the keyword that flips the answer to AKS is orchestration 'at scale' or 'fleets of containers'.",
    },
    {
        "type": "mc",
        "q": "A team wants to run containers without managing any orchestration infrastructure, and needs built-in automatic scaling and load balancing. Which service matches?",
        "choices": ["Azure Virtual Machines", "Azure Container Apps", "Azure ExpressRoute", "Availability sets"],
        "answer": 1,
        "explain": "Azure Container Apps is the serverless container service: it adds built-in capabilities like autoscaling and load balancing on top of container hosting, with no cluster for you to run. It sits between ACI (simplest, few built-ins) and AKS (full orchestration you configure).",
    },
    {
        "type": "mc",
        "q": "In Azure, what does the term 'serverless' actually mean?",
        "choices": [
            "The code runs on the client device instead of in the cloud",
            "No physical servers are involved at any point",
            "Microsoft manages the servers entirely; they exist but are invisible to you",
            "The service is free because no servers are billed",
        ],
        "answer": 2,
        "explain": "Serverless does not mean server-free — it means the provider owns all server provisioning, scaling, and maintenance, so servers are simply not your concern. You deploy code (Functions) or containers (Container Apps), which can scale to zero, and you pay for consumption rather than for idle machines.",
    },
    {
        "type": "mc",
        "q": "A web front end must run on many identical VMs behind a load balancer, automatically adding instances during peak hours and removing them overnight. What should be deployed?",
        "choices": ["An availability set", "A single large VM", "Azure Virtual Machine Scale Sets", "Azure DNS"],
        "answer": 2,
        "explain": "VM Scale Sets create a group of identical, load-balanced VMs from one image and adjust the instance count automatically with demand or a schedule — Azure even deploys the load balancer for you. An availability set changes VM placement for resilience but never changes the number of VMs.",
    },
    {
        "type": "mc",
        "q": "What protection does an availability set provide for a group of VMs?",
        "choices": [
            "It replicates the VMs to a second Azure region",
            "It spreads VMs across fault and update domains so hardware failure or planned maintenance cannot take them all down at once",
            "It automatically increases the number of VMs when CPU usage rises",
            "It encrypts traffic between the VMs",
        ],
        "answer": 1,
        "explain": "An availability set distributes VMs across fault domains (separate power and network) and update domains (separate maintenance windows) within a datacenter, so an unplanned rack failure or a planned reboot affects only some of the VMs. It is not autoscaling and not cross-region replication.",
    },
    {
        "type": "mc",
        "q": "Within an availability set, what do VMs in the same FAULT domain share?",
        "choices": [
            "A maintenance and reboot schedule",
            "A common power source and network switch",
            "The same subscription spending limit",
            "A single public IP address",
        ],
        "answer": 1,
        "explain": "A fault domain is a group of hardware sharing power and a network switch — essentially a rack — so a power or switch failure downs the whole domain at once. Spreading VMs across fault domains protects against this unplanned failure; shared maintenance timing describes an update domain instead.",
    },
    {
        "type": "mc",
        "q": "Azure needs to apply planned maintenance that reboots hosts. How does an availability set keep the application running during this?",
        "choices": [
            "VMs are spread across update domains, and Azure reboots only one update domain at a time",
            "All VMs are migrated to another region during maintenance",
            "Maintenance is skipped for VMs in availability sets",
            "The fault domains take over networking during the reboot",
        ],
        "answer": 0,
        "explain": "Update domains group VMs by maintenance window: Azure walks through them one at a time, so VMs in other update domains keep serving while one group reboots. Fault domains address the different problem of unplanned power/network hardware failure.",
    },
    {
        "type": "mc",
        "q": "A company wants employees to access full Windows desktops and corporate apps from personal laptops, tablets, and browsers anywhere in the world, with data kept in the cloud. Which service fits?",
        "choices": ["Azure Virtual Machine Scale Sets", "Azure Container Instances", "Azure Virtual Desktop", "Azure VPN Gateway"],
        "answer": 2,
        "explain": "Azure Virtual Desktop is Azure's desktop and application virtualization service: users get a cloud-hosted Windows desktop from almost any device, and data stays in Azure rather than on the endpoint. Its multi-session Windows capability even lets multiple users share one VM concurrently, cutting cost.",
    },
    {
        "type": "mc",
        "q": "Which set of resources is required (or created) alongside a new Azure virtual machine so it can store data and communicate?",
        "choices": [
            "A managed disk, a virtual network with a subnet, and a network interface",
            "An ExpressRoute circuit, a DNS zone, and a deployment slot",
            "A Kubernetes cluster and a container registry",
            "Only a public IP address — everything else is optional",
        ],
        "answer": 0,
        "explain": "A VM never travels alone: it needs at least an OS disk (a managed disk), a place on the network (a subnet within a VNet), and a NIC connecting it to that subnet. A public IP and an NSG are common but optional companions; ExpressRoute, DNS zones, and clusters are unrelated to basic VM creation.",
    },
    {
        "type": "mc",
        "q": "Which resource directly connects an Azure VM to a subnet of a virtual network?",
        "choices": ["A managed disk", "A network interface (NIC)", "A deployment slot", "An update domain"],
        "answer": 1,
        "explain": "The NIC is the VM's attachment point into a subnet — every VM needs at least one. Disks provide storage, deployment slots belong to App Service, and update domains are an availability-set placement concept, not a connectivity resource.",
    },
    {
        "type": "mc",
        "q": "When creating an Azure VM, which two choices determine its CPU/memory profile and its operating system?",
        "choices": [
            "Fault domain and update domain",
            "VM size and VM image",
            "Peering type and DNS zone",
            "Endpoint type and NSG rule set",
        ],
        "answer": 1,
        "explain": "The size selects the hardware profile (vCPUs, RAM, disk performance) and the image selects what the VM boots — Windows or a Linux distribution, from the Marketplace or your own custom image. Domains relate to availability sets, and the other options are networking concepts.",
    },
    {
        "type": "mc",
        "q": "A team wants to host a REST API in Azure using Python, with built-in scaling and load balancing, and absolutely no servers or OS to manage. Which hosting option fits best?",
        "choices": ["Azure Virtual Machines", "Azure App Service", "An availability set", "Azure ExpressRoute"],
        "answer": 1,
        "explain": "Azure App Service is PaaS purpose-built for web apps, REST APIs, and mobile back ends in multiple languages (.NET, Java, Node.js, Python, PHP and more), with automatic scaling and load balancing included. VMs would give more control but bring back OS patching — exactly what the team wants to avoid.",
    },
    {
        "type": "mc",
        "q": "A company hosts its web app in Azure App Service and wants to test a new version with real settings, then move it into production with no downtime. Which feature enables this?",
        "choices": ["Deployment slots", "Fault domains", "VNet peering", "Point-to-site VPN"],
        "answer": 0,
        "explain": "Deployment slots are separate live instances of an App Service app (e.g., a staging slot) that can be swapped with production instantly — the new version is warmed up before the swap, so users see no downtime. The other options are availability and networking concepts, not App Service features.",
    },
    {
        "type": "mc",
        "q": "When would hosting an application on Azure Virtual Machines be a better choice than Azure App Service?",
        "choices": [
            "When the team wants the least infrastructure management possible",
            "When the app is a standard web app that needs built-in scaling",
            "When the app requires OS-level customization or software App Service cannot run",
            "When the app must scale to zero between requests",
        ],
        "answer": 2,
        "explain": "VMs win when you need control the platform layers hide: registry/kernel tweaks, custom agents, unsupported runtimes, or legacy dependencies. If the requirement is 'least management' or 'standard web app', App Service is better; 'scale to zero' points at serverless options like Functions.",
    },
    {
        "type": "mc",
        "q": "What is the primary purpose of an Azure virtual network (VNet)?",
        "choices": [
            "To provide a logically isolated private network in Azure with an address space you define",
            "To convert a VM's private IP address into a public one",
            "To host DNS zones for public domain names",
            "To provide dedicated physical connectivity to on-premises datacenters",
        ],
        "answer": 0,
        "explain": "A VNet is your isolated private network inside Azure: you define its private IP address space, and resources inside it communicate securely with each other, the Internet, and on-premises networks. DNS hosting is Azure DNS and dedicated physical connectivity is ExpressRoute.",
    },
    {
        "type": "mc",
        "q": "Why would an administrator divide a virtual network into multiple subnets?",
        "choices": [
            "To connect the VNet to another region",
            "To segment the address space so groups of resources get their own security and routing",
            "To encrypt traffic between VMs",
            "Because Azure requires one subnet per VM",
        ],
        "answer": 1,
        "explain": "Subnets carve the VNet's address space into segments — web tier here, data tier there — so NSGs and routes can be applied per group. Cross-region connectivity is peering's job, and many VMs can share one subnet.",
    },
    {
        "type": "mc",
        "q": "Two Azure virtual networks in different regions must communicate privately, and traffic must not cross the public Internet. What should be configured?",
        "choices": ["A public endpoint on each VNet", "Global virtual network peering", "Azure DNS", "A deployment slot"],
        "answer": 1,
        "explain": "VNet peering joins two VNets so their resources communicate as one network, with traffic riding the Microsoft private backbone — never the public Internet. When the VNets are in different regions it is called global virtual network peering, which works the same way.",
    },
    {
        "type": "mc",
        "q": "A company wants to host and resolve the DNS records for its domain using the same credentials, tools, and billing as its other Azure resources. Which service does this?",
        "choices": ["Azure VPN Gateway", "Azure Private Link", "Azure DNS", "Network security groups"],
        "answer": 2,
        "explain": "Azure DNS hosts DNS domains and answers queries from Azure's global anycast name-server infrastructure, managed with standard Azure credentials, APIs, and tools. Note it hosts zones — you still purchase the domain name from a registrar.",
    },
    {
        "type": "mc",
        "q": "A branch office must connect its entire on-premises network to an Azure VNet using an encrypted tunnel over its existing Internet connection. Which option fits?",
        "choices": [
            "A site-to-site VPN through Azure VPN Gateway",
            "A point-to-site VPN for each employee",
            "ExpressRoute",
            "Global VNet peering",
        ],
        "answer": 0,
        "explain": "A site-to-site VPN links a whole on-premises network (via its VPN device) to the VNet through an encrypted IPsec tunnel over the public Internet — quick and inexpensive. Point-to-site connects individual devices, ExpressRoute avoids the Internet entirely at higher cost, and peering connects VNets, not offices.",
    },
    {
        "type": "mc",
        "q": "A remote developer working from home needs a secure connection from just her laptop into the company's Azure VNet. Which connection type is designed for this?",
        "choices": ["Site-to-site VPN", "ExpressRoute", "Point-to-site VPN", "VNet peering"],
        "answer": 2,
        "explain": "A point-to-site VPN connects a single device to a VNet over an encrypted tunnel — exactly the remote-worker scenario. Site-to-site links whole networks via a VPN appliance, and ExpressRoute is a provisioned private circuit, overkill and impractical for one laptop.",
    },
    {
        "type": "mc",
        "q": "A financial firm requires connectivity between its datacenter and Azure with high bandwidth, consistent latency, and a guarantee that traffic never traverses the public Internet. Which service is required?",
        "choices": ["Site-to-site VPN", "Azure ExpressRoute", "Point-to-site VPN", "A NAT rule on the NSG"],
        "answer": 1,
        "explain": "ExpressRoute is a private, dedicated connection into Microsoft's cloud through a connectivity provider — traffic bypasses the public Internet entirely, giving higher bandwidth and predictable performance. Any VPN option rides the public Internet, which violates the stated requirement.",
    },
    {
        "type": "mc",
        "q": "An administrator must allow HTTPS into a subnet's web servers while blocking RDP from the Internet. Which Azure resource applies these allow/deny rules?",
        "choices": ["Azure DNS", "A network security group", "A deployment slot", "An availability set"],
        "answer": 1,
        "explain": "Network security groups filter traffic to and from Azure resources with security rules (source, destination, port, protocol, allow/deny) and attach to subnets or NICs. DNS resolves names, slots belong to App Service, and availability sets govern VM placement — none of them filter traffic.",
    },
    {
        "type": "mc",
        "q": "An application in an Azure VNet must reach an Azure SQL database over a private IP address so that traffic to the database never crosses the public Internet. What should be configured?",
        "choices": [
            "A public endpoint on the database",
            "A private endpoint for the database using Azure Private Link",
            "A point-to-site VPN from each VM",
            "An additional update domain",
        ],
        "answer": 1,
        "explain": "A private endpoint gives the PaaS service a private IP address from the VNet's own address space via Private Link, so the app reaches the database across the private network and the public endpoint can be disabled. P2S VPNs connect external devices to a VNet — they do not privatize PaaS access.",
    },
    {
        "type": "mc",
        "q": "What is a public endpoint in Azure?",
        "choices": [
            "A private IP address allocated from a VNet's address space",
            "A dedicated fiber connection to Microsoft's network",
            "A public IP address through which a service can be reached from the Internet",
            "A DNS record hosted in Azure DNS",
        ],
        "answer": 2,
        "explain": "A public endpoint exposes a service on a public IP address reachable from the Internet — appropriate for customer-facing services, and controllable with security rules. Its opposite is the private endpoint, which is a private IP inside your VNet provided through Private Link.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Configuring an availability set costs extra — Azure charges a fee for the availability set itself in addition to the VMs.",
        "answer": False,
        "explain": "There is no charge for an availability set itself; you pay only for the VM instances you place inside it. That makes spreading VMs across fault and update domains one of the cheapest resilience wins on the exam.",
    },
    {
        "type": "tf",
        "q": "True or False: ExpressRoute traffic is encrypted by default because the connection uses IPsec.",
        "answer": False,
        "explain": "ExpressRoute provides a private dedicated path that never touches the public Internet, but privacy of the route is not encryption — no IPsec is inherent. It is the VPN Gateway option that encrypts by design; organizations needing encryption over ExpressRoute add it on top.",
    },
    {
        "type": "tf",
        "q": "True or False: Each container includes its own full guest operating system, which the customer must patch and maintain.",
        "answer": False,
        "explain": "Containers virtualize the operating system, not the hardware: they share the host's kernel and bundle only the app and its dependencies. That absence of a guest OS is exactly why containers are lightweight, start in seconds, and leave you no OS to patch — that burden belongs to VMs.",
    },
    {
        "type": "tf",
        "q": "True or False: Virtual network peering can connect VNets located in different Azure regions, with traffic staying on the Microsoft private backbone.",
        "answer": True,
        "explain": "Cross-region peering is called global virtual network peering, and like regional peering the traffic travels Microsoft's private backbone, never the public Internet. This lets you build private connectivity between resources worldwide.",
    },
    {
        "type": "tf",
        "q": "True or False: A private endpoint assigns a PaaS service an IP address taken from your virtual network's own address space.",
        "answer": True,
        "explain": "That is the defining trait: through Azure Private Link, the service (a storage account, Azure SQL database, etc.) gets a private IP inside your VNet, so traffic to it stays on the private network. A public endpoint, by contrast, is a public IP reachable from the Internet.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The Azure service providing a private, dedicated connection to Microsoft's cloud that never touches the public Internet is Azure ______. (type your answer)",
        "answers": ["expressroute", "express route", "azure expressroute", "azure express route"],
        "explain": "ExpressRoute connects on-premises networks to Azure through a connectivity provider over a private circuit — higher bandwidth and consistent latency, but not encrypted by default. The encrypted-over-the-Internet alternative is VPN Gateway.",
    },
    {
        "type": "fill",
        "q": "The Azure service that delivers cloud-hosted Windows desktops and apps to any device, including multi-session Windows support, is Azure ______ ______. (type your answer)",
        "answers": ["virtual desktop", "azure virtual desktop", "avd"],
        "explain": "Azure Virtual Desktop provides desktop and application virtualization in the cloud: full Windows desktops from a browser or client app anywhere, with data centralized in Azure and multiple concurrent users allowed on one VM via multi-session Windows.",
    },
    {
        "type": "fill",
        "q": "Connecting two Azure virtual networks so they communicate over the Microsoft private backbone is called virtual network ______. (type your answer)",
        "answers": ["peering", "vnet peering", "virtual network peering", "global peering"],
        "explain": "VNet peering links two VNets into one communication space with traffic on Microsoft's private backbone, never the public Internet. When the VNets sit in different regions, it is global virtual network peering.",
    },
    {
        "type": "fill",
        "q": "In an availability set, the group of VMs that shares a common power source and network switch is called a ______ domain. (type your answer)",
        "answers": ["fault", "fault domain"],
        "explain": "A fault domain is effectively a rack — shared power and network switch — so spreading VMs across fault domains protects against unplanned hardware failure. The companion concept, the update domain, groups VMs by planned-maintenance window instead.",
    },
    {
        "type": "fill",
        "q": "The resource that attaches an Azure VM to a subnet so it can communicate on the virtual network is the network ______. (type your answer)",
        "answers": ["interface", "nic", "network interface", "network interface card", "interface card"],
        "explain": "The network interface (NIC) is the VM's connection into its subnet; every VM requires at least one. It is one of the standard companion resources of a VM alongside managed disks and the VNet/subnet itself.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each Azure compute service to its one-line identity.",
        "pairs": [
            ["Azure Virtual Machines", "IaaS with full OS control — you patch and maintain the OS"],
            ["Azure Container Instances", "Simplest, fastest way to run a single container"],
            ["Azure Kubernetes Service", "Orchestrates and manages fleets of containers at scale"],
            ["Azure Functions", "Event-driven serverless code that scales to zero"],
            ["Azure App Service", "PaaS hosting for web apps, REST APIs, and mobile back ends"],
        ],
        "explain": "These identities are the exam's bread and butter: VMs give the most control (and most management), ACI is the no-frills single container, AKS is orchestration at scale, Functions is trigger-driven consumption-billed code, and App Service is the managed home for standard web workloads.",
    },
    {
        "type": "match",
        "q": "Match each Azure networking service to its purpose.",
        "pairs": [
            ["Virtual network peering", "Connects VNets over the Microsoft private backbone"],
            ["Azure DNS", "Hosts and resolves DNS domains in Azure"],
            ["Azure VPN Gateway", "Encrypted IPsec tunnels over the public Internet"],
            ["Azure ExpressRoute", "Private dedicated circuit that avoids the public Internet"],
            ["Network security group", "Filters traffic with allow/deny rules on subnets and NICs"],
        ],
        "explain": "Peering is Azure-to-Azure; VPN Gateway and ExpressRoute are on-premises-to-Azure, split by encrypted-over-Internet versus private-circuit; Azure DNS answers name queries; and NSGs are the traffic filter. Anchoring each service to one purpose prevents the classic mix-ups.",
    },
    {
        "type": "match",
        "q": "Match each virtual machine option to the scenario it solves.",
        "pairs": [
            ["Single Azure VM", "One lift-and-shift server needing full OS control"],
            ["VM Scale Sets", "Identical load-balanced instances that autoscale with demand"],
            ["Availability set", "Spread VMs across fault/update domains to survive failures and maintenance"],
            ["Azure Virtual Desktop", "Full Windows desktops delivered to any device"],
        ],
        "explain": "The four VM options answer different questions: a single VM is the basic building block, scale sets solve capacity, availability sets solve resilience within a datacenter, and AVD solves end-user desktop delivery. The scale-set-versus-availability-set contrast — scaling versus surviving — is the most-tested pair.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange these Azure compute options from MOST customer infrastructure-management responsibility to LEAST.",
        "items": [
            "Azure Virtual Machines",
            "Azure Kubernetes Service",
            "Azure Container Apps",
            "Azure Functions",
        ],
        "explain": "VMs leave you the whole OS and everything above it; AKS removes the OS but you still configure and operate cluster orchestration; Container Apps is serverless containers — no orchestration infrastructure at all; and Functions strips it down to nothing but your code, event-triggered and consumption-billed. Management responsibility shrinks at every step down this ladder.",
    },
]
