TOPIC = {
    "id": "2.3",
    "domain": 2,
    "title": "Describe Azure storage services.",
    "short": "Storage",
}

TERMS = [
    ("Azure Blob Storage", "Object storage for massive amounts of unstructured data (text, binary, images, video, backups), accessed over HTTP/HTTPS via REST APIs and SDKs"),
    ("Azure Files", "Fully managed SMB/NFS file shares in the cloud, mountable simultaneously from cloud and on-premises machines with no file server to manage"),
    ("Azure Queue Storage", "Service for storing large numbers of messages (up to 64 KB each) enabling asynchronous communication between application components"),
    ("Azure Table Storage", "NoSQL store for structured, non-relational key/attribute data with a schemaless design"),
    ("Azure Managed Disks", "Block-level storage volumes managed by Azure and attached to virtual machines as OS and data disks"),
    ("Storage account", "Top-level Azure resource with a globally unique name that contains blobs, files, queues, and tables and sets performance and redundancy for them"),
    ("Hot tier", "Blob access tier optimized for frequently accessed data — highest storage cost, lowest access cost"),
    ("Cool tier", "Online blob access tier for infrequently accessed data stored at least 30 days — lower storage cost, higher access cost than Hot"),
    ("Cold tier", "Online blob access tier for rarely accessed data stored at least 90 days — cheaper storage than Cool with higher access costs"),
    ("Archive tier", "Offline blob access tier for data stored at least 180 days — cheapest storage, highest retrieval cost, hours-long rehydration latency"),
    ("Rehydration", "The hours-long process of copying an Archive-tier blob back to an online tier (Hot/Cool/Cold) so it can be read"),
    ("Locally redundant storage (LRS)", "Three synchronous copies of data within a single datacenter — cheapest option, no protection against zone or regional failure"),
    ("Zone-redundant storage (ZRS)", "Three copies of data spread across three availability zones in one region, surviving the loss of an entire datacenter"),
    ("Geo-redundant storage (GRS)", "LRS in the primary region plus asynchronous replication to a secondary region (six copies total); secondary readable only after failover"),
    ("Geo-zone-redundant storage (GZRS)", "ZRS in the primary region combined with replication to a secondary region — protection against both zone and regional failures"),
    ("Read-access geo-redundant storage (RA-GRS)", "GRS with the addition of always-available read access to the data in the secondary region, without requiring a failover"),
    ("Standard general-purpose v2", "The default HDD-backed storage account type supporting blobs, files, queues, and tables and all redundancy options — recommended for most scenarios"),
    ("Premium storage account", "SSD-backed account type (block blobs, file shares, or page blobs) delivering consistently low latency and high throughput at higher cost"),
    ("AzCopy", "Command-line utility for copying or synchronizing blobs and files to and from storage accounts; its sync runs in one direction only"),
    ("Azure Storage Explorer", "Free cross-platform GUI application (Windows, macOS, Linux) for browsing and managing storage account data; uses AzCopy under the hood"),
    ("Azure File Sync", "Service that caches Azure Files shares on an on-premises Windows Server with bi-directional synchronization, combining local performance with cloud centralization"),
    ("Azure Migrate", "Unified hub for discovering, assessing, and migrating on-premises servers, databases, web apps, and virtual desktops to Azure over the network"),
    ("Azure Data Box", "Ruggedized physical appliance (~80 TB usable) shipped by Microsoft for offline bulk data import to or export from Azure when networks are too slow or data too large"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A streaming startup needs to store millions of video files and thumbnails, served to a web app over HTTPS. Which Azure storage service fits?",
        "choices": ["Azure Files", "Azure Blob Storage", "Azure Table Storage", "Azure Managed Disks"],
        "answer": 1,
        "explain": "Blob Storage is object storage built for massive amounts of unstructured data — text, binary, images, video, backups — accessed over HTTP/HTTPS via REST. Azure Files is a mountable SMB/NFS share, Tables hold NoSQL structured data, and Managed Disks attach to VMs.",
    },
    {
        "type": "mc",
        "q": "A legacy application being lifted to Azure writes to a mapped network drive over SMB, and the same share must remain accessible from on-premises PCs. Which service replaces the file server?",
        "choices": ["Azure Blob Storage", "Azure Queue Storage", "Azure Files", "Azure Data Box"],
        "answer": 2,
        "explain": "Azure Files provides fully managed SMB (and NFS) file shares that can be mounted like a network drive simultaneously from cloud and on-premises machines — ideal for lift-and-shift apps expecting a share. Blob Storage is reached over REST, not mounted via SMB.",
    },
    {
        "type": "mc",
        "q": "A web front end must hand off order records to a backend processor that runs at its own pace, so the two components stay decoupled. Which service should carry the messages?",
        "choices": ["Azure Queue Storage", "Azure Table Storage", "Azure Files", "Azure Blob Storage"],
        "answer": 0,
        "explain": "Queue Storage stores large numbers of messages (up to 64 KB each) that components consume asynchronously, letting the front end and backend scale and fail independently. Tables store NoSQL data, and Blob/Files store objects and file shares, not message streams.",
    },
    {
        "type": "mc",
        "q": "An IoT platform needs cheap storage for structured but NON-relational device readings with a flexible schema. Which service fits?",
        "choices": ["Azure Managed Disks", "Azure Files", "Azure Blob Storage", "Azure Table Storage"],
        "answer": 3,
        "explain": "Table Storage is a NoSQL store for structured, non-relational key/attribute data with no fixed schema — perfect for device telemetry and metadata. It is not a relational SQL database; blobs are for unstructured objects and disks are block storage for VMs.",
    },
    {
        "type": "mc",
        "q": "Which Azure storage service provides block-level volumes that are attached to virtual machines as their OS and data drives?",
        "choices": ["Azure Blob Storage", "Azure Managed Disks", "Azure Files", "Azure Queue Storage"],
        "answer": 1,
        "explain": "Managed Disks are block-level storage volumes managed by Azure and attached to VMs — you pick size and performance, and Azure handles the underlying storage plumbing. Blob is object storage over REST, Files are SMB/NFS shares, and Queues carry messages.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST captures the difference between Azure Blob Storage and Azure Files?",
        "choices": [
            "Blob is accessed over REST/HTTP(S) as object storage; Files is a mountable SMB/NFS share",
            "Blob is for structured data; Files is for unstructured data",
            "Blob can only be used from within Azure; Files works from anywhere",
            "Blob requires a Premium account; Files requires Standard",
        ],
        "answer": 0,
        "explain": "Both can hold 'files,' but Blob is object storage addressed over HTTP(S)/REST, while Azure Files presents a real SMB/NFS share you can mount as a network drive from cloud and on-premises. Both hold unstructured data, both are reachable from outside Azure, and both work in Standard GPv2 accounts.",
    },
    {
        "type": "mc",
        "q": "What is the maximum size of a single message in Azure Queue Storage?",
        "choices": ["64 KB", "1 MB", "256 KB", "4 GB"],
        "answer": 0,
        "explain": "Queue Storage messages can be up to 64 KB each — the service is designed for large numbers of small messages passed asynchronously between components, not for bulk payloads. Large data should go in Blob Storage with a queue message pointing to it.",
    },
    {
        "type": "mc",
        "q": "A firm keeps scanned contracts that are opened perhaps once a quarter but MUST be readable immediately when requested, and are retained for at least 90 days. Which blob access tier is the most cost-effective fit?",
        "choices": ["Hot", "Archive", "Cold", "Premium"],
        "answer": 2,
        "explain": "Cold is an online tier for rarely accessed data stored at least 90 days — cheaper than Cool while still allowing instant reads. Archive would be cheaper still but is offline, requiring hours of rehydration, which violates the immediate-read requirement. Premium is an account performance type, not an access tier.",
    },
    {
        "type": "mc",
        "q": "Seven-year compliance archives are essentially never read, and when auditors do request one, waiting several hours is acceptable. Which tier minimizes cost?",
        "choices": ["Cool", "Cold", "Hot", "Archive"],
        "answer": 3,
        "explain": "Archive offers the cheapest storage of all tiers in exchange for offline status: blobs must be rehydrated to an online tier, which can take hours, and carry the highest retrieval cost with a 180-day minimum. Since hours of latency is acceptable here, Archive wins on price.",
    },
    {
        "type": "mc",
        "q": "Which statement about the Archive access tier is TRUE?",
        "choices": [
            "It offers the lowest access latency of all tiers",
            "Blobs are offline and must be rehydrated to an online tier before they can be read",
            "It requires a Premium storage account",
            "Data must be deleted after 180 days",
        ],
        "answer": 1,
        "explain": "Archive is the only offline tier: archived blobs cannot be read until rehydrated to Hot, Cool, or Cold, which can take hours. The 180 days is a MINIMUM storage duration (early deletion incurs a fee), not an expiry, and Archive lives in Standard accounts, not Premium.",
    },
    {
        "type": "mc",
        "q": "At which level of granularity can a blob access tier be assigned?",
        "choices": [
            "Only for an entire subscription",
            "Only for an entire storage account",
            "Per individual blob, in addition to an account-level default",
            "Only per container",
        ],
        "answer": 2,
        "explain": "The tier can be set on each individual blob, and an account-level default (Hot or Cool) applies to blobs without an explicit tier. Lifecycle management policies commonly move individual blobs between tiers automatically as they age.",
    },
    {
        "type": "mc",
        "q": "Which access tier carries the HIGHEST storage cost but the LOWEST access cost?",
        "choices": ["Hot", "Cool", "Cold", "Archive"],
        "answer": 0,
        "explain": "The tiers are a see-saw: Hot charges the most to store data but the least to access it, which suits frequent access. Moving toward Archive, storage gets cheaper while access costs and latency rise — Archive has the cheapest storage and the highest retrieval cost.",
    },
    {
        "type": "mc",
        "q": "A dev/test team wants the cheapest possible redundancy and accepts that data could be lost if the datacenter itself is destroyed. Which option fits?",
        "choices": ["ZRS", "GRS", "LRS", "GZRS"],
        "answer": 2,
        "explain": "Locally redundant storage keeps three synchronous copies within a single datacenter — the lowest-cost option, protecting against drive or rack failure but not against loss of the datacenter, zone, or region. All the other options add zone or regional protection at higher cost.",
    },
    {
        "type": "mc",
        "q": "Data must survive the failure of an entire datacenter, but compliance rules forbid it from leaving its Azure region. Which redundancy option fits?",
        "choices": ["LRS", "ZRS", "GRS", "RA-GRS"],
        "answer": 1,
        "explain": "Zone-redundant storage spreads three copies across three availability zones within one region, so a whole-datacenter failure is survivable while data never leaves the region. GRS and RA-GRS replicate to a secondary region, violating the residency rule, and LRS stays inside one datacenter.",
    },
    {
        "type": "mc",
        "q": "How many total copies of your data exist with geo-redundant storage (GRS)?",
        "choices": ["Three in one region", "Six — three in the primary region and three in a secondary region", "Two — one per region", "Four across two zones"],
        "answer": 1,
        "explain": "GRS is LRS in the primary region (three synchronous copies in one datacenter) plus asynchronous replication to a secondary region where three more copies are kept — six in total. The secondary copies are readable only after a failover unless you use RA-GRS.",
    },
    {
        "type": "mc",
        "q": "A reporting application must READ data from the secondary region during normal operations — without any failover. Which is the least expensive redundancy option that allows this?",
        "choices": ["GRS", "GZRS", "RA-GRS", "ZRS"],
        "answer": 2,
        "explain": "The RA- (read-access) prefix is what makes the secondary region readable at all times; plain GRS and GZRS keep the secondary inaccessible until a failover occurs. ZRS has no secondary region at all. RA-GRS is cheaper than RA-GZRS, making it the minimal fit.",
    },
    {
        "type": "mc",
        "q": "Which redundancy option combines copies across three availability zones in the primary region WITH replication to a secondary region?",
        "choices": ["GZRS", "ZRS", "GRS", "LRS"],
        "answer": 0,
        "explain": "Geo-zone-redundant storage is ZRS in the primary region (three copies across three zones) plus replication to a secondary region — protecting against both a zone failure and a regional disaster. GRS uses LRS (single datacenter) in the primary rather than zones.",
    },
    {
        "type": "mc",
        "q": "Which statement about geo-redundant replication is TRUE?",
        "choices": [
            "Replication to the secondary region is synchronous, so no data can ever be lost",
            "Replication to the secondary region is asynchronous, so the latest writes could be lost in a failover",
            "The secondary region must be chosen by the customer from any region worldwide",
            "GRS keeps twelve copies of the data",
        ],
        "answer": 1,
        "explain": "Geo-replication is asynchronous: writes commit in the primary region first and copy to the paired secondary later, so a regional failover may lose the most recent writes (a small RPO). GRS totals six copies, and the secondary is the region's fixed pair, not free choice.",
    },
    {
        "type": "mc",
        "q": "Why must an Azure storage account name be globally unique?",
        "choices": [
            "Because Azure bills by account name",
            "Because the name forms part of the account's public endpoint URL",
            "Because names are reused as encryption keys",
            "Because each subscription allows only one storage account",
        ],
        "answer": 1,
        "explain": "The account name becomes part of DNS endpoints such as mydata.blob.core.windows.net, so it must be unique across all of Azure, not just within your subscription. Subscriptions can hold many storage accounts, and the name has nothing to do with billing identity or encryption.",
    },
    {
        "type": "mc",
        "q": "A company needs one storage account for blobs, file shares, queues, and tables for a typical business workload with no extreme latency demands. Which account type should it choose?",
        "choices": ["Premium block blobs", "Premium file shares", "Standard general-purpose v2", "Premium page blobs"],
        "answer": 2,
        "explain": "Standard general-purpose v2 is the recommended default: it supports all four data services and every redundancy option at HDD-backed pricing. Premium accounts are SSD-backed, cost more, are each limited to one storage type, and are justified only by low-latency/high-throughput needs.",
    },
    {
        "type": "mc",
        "q": "A database workload requires an NFS file share with consistently low latency and high throughput. Which storage account type is required?",
        "choices": ["Standard general-purpose v2", "Premium file shares", "Premium block blobs", "Premium page blobs"],
        "answer": 1,
        "explain": "Premium file shares are SSD-backed accounts dedicated to performance-critical SMB and NFS shares. Each Premium account type serves one storage type — block blobs for high-transaction blob workloads, page blobs for disk-style random I/O — while Standard GPv2 is HDD-backed general purpose.",
    },
    {
        "type": "mc",
        "q": "An administrator wants to script an automated nightly upload of log files to Blob Storage from the command line. Which tool fits?",
        "choices": ["Azure Storage Explorer", "Azure File Sync", "AzCopy", "Azure Data Box"],
        "answer": 2,
        "explain": "AzCopy is the command-line utility for copying and synchronizing blobs and files to and from storage accounts — ideal for scripting and automation. Storage Explorer is a GUI for interactive use, File Sync caches file shares on Windows Server, and Data Box is a physical appliance.",
    },
    {
        "type": "mc",
        "q": "A support technician on a Mac needs a graphical application to browse containers, upload blobs, and manage several storage accounts interactively. Which tool fits?",
        "choices": ["Azure Storage Explorer", "AzCopy", "Azure Migrate", "Azure File Sync"],
        "answer": 0,
        "explain": "Azure Storage Explorer is the free cross-platform GUI (Windows, macOS, Linux) for visually managing storage account data — and it actually uses AzCopy under the hood for transfers. AzCopy alone is command-line only, and Migrate/File Sync solve different problems.",
    },
    {
        "type": "mc",
        "q": "A company wants branch-office users to keep fast LAN access to shared files via their local Windows Server, while the authoritative copies live centrally in an Azure Files share and changes flow BOTH ways. Which service fits?",
        "choices": ["AzCopy scheduled tasks", "Azure Data Box", "Azure Storage Explorer", "Azure File Sync"],
        "answer": 3,
        "explain": "Azure File Sync installs an agent on Windows Server that caches an Azure Files share locally with bi-directional synchronization — users get local SMB performance while the cloud holds the central copy. AzCopy's sync is one-direction, and the other tools are not ongoing sync services.",
    },
    {
        "type": "mc",
        "q": "Before moving 300 on-premises VMware virtual machines to Azure, a company wants to discover them, assess their readiness, and estimate their Azure running costs. Which service provides this?",
        "choices": ["Azure Data Box", "Azure Migrate", "Azure File Sync", "AzCopy"],
        "answer": 1,
        "explain": "Azure Migrate is the unified hub for discovering, assessing, and migrating on-premises servers (VMware, Hyper-V, physical), databases, web apps, and virtual desktops — including readiness ratings, right-sizing, and cost estimates. Data Box only moves raw data offline and performs no assessment.",
    },
    {
        "type": "mc",
        "q": "A research lab must move 150 TB of instrument data to Azure, but its site has only a 20 Mbps Internet uplink. What is the most practical option?",
        "choices": [
            "Upload with AzCopy over the existing link",
            "Order Azure Data Box appliances, load them locally, and ship them to Microsoft",
            "Mount an Azure Files share and drag the data across",
            "Use Azure File Sync to replicate the data",
        ],
        "answer": 1,
        "explain": "At 20 Mbps, 150 TB would take well over a year to upload — this is exactly the 'data too large or bandwidth too limited' case Azure Data Box exists for. Microsoft ships a rugged ~80 TB-usable appliance you load and return for offline import; any network-based option is impractical here.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: With standard geo-redundant storage (GRS), applications can read data from the secondary region at any time during normal operations.",
        "answer": False,
        "explain": "With plain GRS the secondary region's copies become accessible only after a failover. Always-on read access to the secondary is exactly what the RA- prefix adds — RA-GRS and RA-GZRS. This distinction is a favorite exam trap.",
    },
    {
        "type": "tf",
        "q": "True or False: An Azure storage account name only needs to be unique within your own subscription.",
        "answer": False,
        "explain": "Storage account names must be globally unique across all of Azure, because the name forms part of the account's public endpoint URLs (for example, name.blob.core.windows.net). If someone anywhere has taken the name, you cannot use it.",
    },
    {
        "type": "tf",
        "q": "True or False: A blob in the Archive tier can be downloaded immediately, just at a higher per-GB price.",
        "answer": False,
        "explain": "Archive is an offline tier: an archived blob cannot be read at all until it is rehydrated to an online tier (Hot, Cool, or Cold), a process that can take hours. Hot, Cool, and Cold are the online tiers with immediate access; Archive trades availability for the cheapest storage price.",
    },
    {
        "type": "tf",
        "q": "True or False: An Azure Files share can be mounted concurrently by cloud VMs and on-premises machines.",
        "answer": True,
        "explain": "Azure Files provides managed SMB/NFS shares that can be mounted simultaneously from Windows, Linux, and macOS clients whether they run in Azure or on-premises. That concurrent cloud-plus-on-prem access is a defining feature that plain Blob Storage does not offer.",
    },
    {
        "type": "tf",
        "q": "True or False: The AzCopy sync command keeps two locations synchronized in both directions.",
        "answer": False,
        "explain": "AzCopy's sync is one-direction only — you designate a source and a destination and changes flow one way. Bi-directional synchronization is the domain of Azure File Sync, which keeps an on-premises Windows Server cache and an Azure Files share mutually up to date.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The command-line utility used to copy or synchronize blobs and files to and from Azure Storage is called ______. (type your answer)",
        "answers": ["azcopy", "az copy"],
        "explain": "AzCopy is the scriptable command-line tool for bulk transfers into and out of storage accounts, including copies between accounts. Remember its sync mode moves changes in one direction only, unlike the bi-directional Azure File Sync service.",
    },
    {
        "type": "fill",
        "q": "The only OFFLINE blob access tier, which requires hours-long rehydration before data can be read, is the ______ tier. (type your answer)",
        "answers": ["archive", "archive tier"],
        "explain": "Archive offers the cheapest storage in exchange for offline status, a 180-day minimum retention, and the highest retrieval costs. Hot, Cool, and Cold are all online tiers whose data can be read instantly.",
    },
    {
        "type": "fill",
        "q": "The cheapest redundancy option, which keeps three synchronous copies of data within a single datacenter, is ______. (type the acronym)",
        "answers": ["lrs", "locally redundant storage", "locally redundant"],
        "explain": "Locally redundant storage protects against drive and rack failures inside one datacenter but offers no protection if the datacenter, availability zone, or region is lost. Zone or regional protection requires ZRS, GRS, or GZRS.",
    },
    {
        "type": "fill",
        "q": "The physical appliance Microsoft ships to customers for offline bulk data transfer into Azure (about 80 TB usable capacity) is Azure ______. (type your answer)",
        "answers": ["data box", "azure data box", "databox"],
        "explain": "Azure Data Box is a ruggedized device for offline import (and export) when data volumes are too large or bandwidth too limited for network transfer — think 40+ TB moves, one-time migrations, and remote sites. You load it locally and ship it back to Microsoft for upload.",
    },
    {
        "type": "fill",
        "q": "The service that caches an Azure Files share on an on-premises Windows Server with bi-directional synchronization is Azure ______. (type your answer)",
        "answers": ["file sync", "azure file sync", "filesync"],
        "explain": "Azure File Sync keeps local SMB performance for users while centralizing the authoritative file share in Azure Files, syncing changes in both directions. It is an ongoing service — distinct from one-off copy tools like AzCopy or Storage Explorer.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each Azure storage service to its description.",
        "pairs": [
            ["Blob Storage", "Object storage for unstructured data accessed over HTTP/HTTPS"],
            ["Azure Files", "Managed SMB/NFS file shares mountable from cloud and on-premises"],
            ["Queue Storage", "Asynchronous messages up to 64 KB between application components"],
            ["Table Storage", "NoSQL store for structured, non-relational data"],
            ["Managed Disks", "Block-level storage volumes attached to virtual machines"],
        ],
        "explain": "Match by data shape: unstructured objects go to Blob, mountable shares to Files, small asynchronous messages to Queues, schemaless structured data to Tables, and VM volumes to Managed Disks. AZ-900 rarely asks more than which shape maps to which service.",
    },
    {
        "type": "match",
        "q": "Match each data-movement or migration tool to its role.",
        "pairs": [
            ["AzCopy", "Command-line copy/sync of blobs and files (one-direction sync)"],
            ["Azure Storage Explorer", "Cross-platform GUI for managing storage account data"],
            ["Azure File Sync", "Bi-directional caching of an Azure Files share on Windows Server"],
            ["Azure Migrate", "Hub for discovering, assessing, and migrating on-premises workloads"],
            ["Azure Data Box", "Shipped physical appliance for offline bulk data transfer"],
        ],
        "explain": "Sort by interface and scale: AzCopy is the scriptable CLI, Storage Explorer the GUI, File Sync the ongoing two-way share cache, Migrate the workload assessment-and-migration hub, and Data Box the offline appliance for data too big or links too slow.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the blob access tiers from HOTTEST (most frequent access) to COLDEST (least frequent access).",
        "items": ["Hot", "Cool", "Cold", "Archive"],
        "explain": "Hot serves frequently accessed data; Cool covers infrequent access with a 30-day minimum; Cold covers rare access with a 90-day minimum; Archive is offline with a 180-day minimum. Storage cost falls and access cost/latency rises in the same order.",
    },
    {
        "type": "order",
        "q": "Arrange the steps of an Azure Data Box import, from first to last.",
        "items": [
            "Order the Data Box device through the Azure portal",
            "Microsoft ships the physical appliance to your site",
            "Copy your data onto the device over the local network",
            "Ship the device back to Microsoft",
            "Microsoft uploads the data into your storage account and wipes the device",
        ],
        "explain": "Data Box is an offline transfer workflow: you order it in the portal, Microsoft ships the ~80 TB-usable appliance, you fill it locally at LAN speed, return it, and Microsoft ingests the data into Azure Storage before securely erasing the device. No production bandwidth is consumed.",
    },
]
