TOPIC = {
    "id": "2.4",
    "domain": 2,
    "title": "Describe Azure identity, access, and security.",
    "short": "Identity & Security",
}

TERMS = [
    ("Microsoft Entra ID", "Cloud-based identity and access management service (formerly Azure Active Directory) providing sign-in, SSO, MFA, and app/device management for cloud and on-prem resources"),
    ("Microsoft Entra Domain Services", "Managed domain service supplying domain join, Group Policy, LDAP, and Kerberos/NTLM without customers deploying or patching domain controllers"),
    ("Microsoft Entra Connect", "Synchronization tool that syncs on-premises Active Directory identities to Microsoft Entra ID for a single hybrid identity"),
    ("Single sign-on (SSO)", "Authenticating once with one credential to access multiple applications without signing in to each separately"),
    ("Multifactor authentication (MFA)", "Requiring two or more different categories of evidence at sign-in: something you know, something you have, something you are"),
    ("Passwordless authentication", "Sign-in that removes the password entirely, combining a registered device with a biometric or PIN for high security and high convenience"),
    ("Windows Hello for Business", "Passwordless sign-in using biometrics or a PIN tied to a specific PC"),
    ("Microsoft Authenticator app", "Phone app used for passwordless sign-in (number match plus biometric/PIN) or as an MFA verification method"),
    ("FIDO2 security key", "Unphishable hardware key (USB/NFC/Bluetooth) used as a passwordless authentication method"),
    ("B2B collaboration", "External-identity feature that invites partners, suppliers, and other guests to access your resources using their own work, school, or social credentials"),
    ("B2C", "Customer-facing identity solution letting consumers sign in to your public applications with social or local accounts, stored in a separate customer directory"),
    ("Guest user", "The account object created in your tenant when an external partner is invited through B2B collaboration"),
    ("Microsoft Entra Conditional Access", "Signal-based if-then policy engine that evaluates user, location, device, application, and risk to allow access, require MFA, or block"),
    ("Azure role-based access control (RBAC)", "Azure's authorization system: assign roles (permission sets) to security principals at a scope; assignments are inherited by child scopes"),
    ("Owner role", "Built-in RBAC role with full access to resources, including the right to grant access to others"),
    ("Contributor role", "Built-in RBAC role that can create and manage all resource types but cannot grant access to others"),
    ("Reader role", "Built-in RBAC role that can view existing resources but cannot change them or grant access"),
    ("Security principal", "The identity a role is assigned to in RBAC: a user, group, service principal, or managed identity"),
    ("Scope (RBAC)", "The level at which an RBAC role assignment applies: management group, subscription, resource group, or individual resource"),
    ("Least privilege", "Security principle of granting only the permissions needed to perform a task, at the narrowest sensible scope"),
    ("Zero Trust", "Security model that trusts no user, device, or network by default: verify explicitly, use least-privilege access, assume breach"),
    ("Defense-in-depth", "Layered security strategy (physical, identity & access, perimeter, network, compute, application, data) where each layer slows an attack"),
    ("Microsoft Defender for Cloud", "Cloud security posture management plus workload protection: secure score, hardening recommendations, regulatory compliance view, and threat alerts across Azure, on-prem, and multicloud"),
    ("Secure score", "Defender for Cloud metric quantifying your current security posture; improves as you remediate recommendations"),
    ("Azure Arc", "Service that connects on-premises and other-cloud machines to Azure so tools like Defender for Cloud can manage and protect them"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company needs a cloud-based service to store employee identities and control sign-in and access to Azure, Microsoft 365, and third-party SaaS apps. Which service should it use?",
        "choices": ["Microsoft Entra Domain Services", "Microsoft Entra ID", "Azure RBAC", "Microsoft Defender for Cloud"],
        "answer": 1,
        "explain": "Microsoft Entra ID (formerly Azure Active Directory) is Microsoft's cloud identity and access management service — sign-in, SSO, MFA, and app/device management for cloud and on-prem resources. Entra Domain Services provides legacy domain features, RBAC is authorization within Azure, and Defender for Cloud is security posture management.",
    },
    {
        "type": "mc",
        "q": "An admin who manages on-premises Active Directory assumes Microsoft Entra ID works the same way. Which capability will they NOT find in Entra ID?",
        "choices": ["Single sign-on to SaaS applications", "Multifactor authentication", "Group Policy and Kerberos authentication", "Self-service password reset"],
        "answer": 2,
        "explain": "Entra ID is not a cloud copy of Active Directory: it uses modern web protocols (SAML, OAuth/OIDC) and has no Group Policy, Kerberos/NTLM, or classic domain join. Those legacy features are exactly what Microsoft Entra Domain Services provides. SSO, MFA, and password reset are core Entra ID features.",
    },
    {
        "type": "mc",
        "q": "A 12-year-old line-of-business app being lifted to Azure VMs requires domain join, Group Policy, and Kerberos, but the company refuses to deploy and patch domain controllers. What should it use?",
        "choices": ["Microsoft Entra ID with Conditional Access", "Domain controllers on Azure VMs", "Microsoft Entra Domain Services", "Azure RBAC custom roles"],
        "answer": 2,
        "explain": "Microsoft Entra Domain Services is a managed domain: it provides domain join, Group Policy, LDAP, and Kerberos/NTLM while Azure deploys, operates, and patches the domain controllers. Entra ID alone lacks these legacy protocols, and running your own DC VMs is exactly the management burden the company wants to avoid.",
    },
    {
        "type": "mc",
        "q": "Which statement about Microsoft Entra Domain Services is TRUE?",
        "choices": [
            "The customer receives Domain Admin rights on the managed domain controllers",
            "Azure operates and patches the domain controllers; the customer never administers them directly",
            "It replaces Microsoft Entra ID for cloud app sign-in",
            "It requires an on-premises Active Directory forest to function",
        ],
        "answer": 1,
        "explain": "Entra Domain Services runs a replica set of managed domain controllers that Azure deploys, updates, and patches — customers get domain features without DC administration and never receive Domain Admin or local access to them. It complements (not replaces) Entra ID, from which it receives a one-way sync, and it works without any on-prem AD.",
    },
    {
        "type": "mc",
        "q": "A hybrid organization wants users to have one identity and password that works for both on-premises Active Directory and Microsoft Entra ID. Which component makes this possible?",
        "choices": ["Microsoft Entra Connect", "Azure Arc", "Conditional Access", "A FIDO2 security key"],
        "answer": 0,
        "explain": "Microsoft Entra Connect synchronizes identities from on-premises Active Directory to Entra ID, giving each user a single hybrid identity across both environments. Arc connects non-Azure machines for management, Conditional Access controls sign-in conditions, and FIDO2 keys are a passwordless method.",
    },
    {
        "type": "mc",
        "q": "After deploying single sign-on, a company's users authenticate once and reach all their apps. Which security benefit does SSO primarily provide?",
        "choices": [
            "It encrypts all application traffic end to end",
            "Fewer credentials exist to manage and attack, shrinking the identity attack surface",
            "It eliminates the need for any authorization checks",
            "It guarantees passwords can never be phished",
        ],
        "answer": 1,
        "explain": "With SSO, one identity replaces many per-app passwords, so there are fewer credentials for users to reuse or forget and for attackers to steal — plus disabling one account removes all access at once. SSO does not encrypt traffic, replace authorization, or make phishing impossible.",
    },
    {
        "type": "mc",
        "q": "A security architect warns that the new SSO rollout has one critical dependency. Which statement captures it?",
        "choices": [
            "SSO is only as secure as the initial authenticator that protects the single credential",
            "SSO requires all applications to share one database",
            "SSO cannot be combined with MFA",
            "SSO only works for on-premises applications",
        ],
        "answer": 0,
        "explain": "Because one credential unlocks many applications, compromising that single sign-in compromises everything behind it — SSO is only as secure as the initial authenticator. That is precisely why SSO is paired with MFA or passwordless methods, which it fully supports.",
    },
    {
        "type": "mc",
        "q": "A user signs in with a password and then approves a push notification in the Microsoft Authenticator app on her phone. Which two MFA factor categories is she using?",
        "choices": [
            "Something you know and something you are",
            "Something you have and something you are",
            "Something you know and something you have",
            "Two instances of something you know",
        ],
        "answer": 2,
        "explain": "The password is something you know; the registered phone running Authenticator is something you have. Something you are would be a biometric such as a fingerprint or face scan. MFA requires factors from at least two different categories.",
    },
    {
        "type": "mc",
        "q": "Which of the following is NOT one of Microsoft's passwordless authentication options for Entra ID?",
        "choices": ["Windows Hello for Business", "FIDO2 security keys", "Microsoft Authenticator app", "SMS one-time passcode combined with a password"],
        "answer": 3,
        "explain": "The three passwordless options to memorize are Windows Hello for Business, the Microsoft Authenticator app, and FIDO2 security keys — all remove the password entirely. An SMS code combined with a password is traditional MFA, not passwordless, since the password is still in play.",
    },
    {
        "type": "mc",
        "q": "Employees sign in to their assigned workstations using facial recognition or a PIN that is tied to that specific PC. Which passwordless method is this?",
        "choices": ["FIDO2 security key", "Windows Hello for Business", "Microsoft Entra Connect", "Self-service password reset"],
        "answer": 1,
        "explain": "Windows Hello for Business replaces the password with biometric or PIN sign-in bound to a specific device, which makes it very hard for anyone but the owner on that PC to use. FIDO2 keys are portable hardware tokens, and the other options are not authentication methods at all.",
    },
    {
        "type": "mc",
        "q": "Your company wants engineers from a partner firm to access a shared project site in your tenant using the partner firm's own credentials. Which capability fits?",
        "choices": ["B2C", "B2B collaboration", "Microsoft Entra Domain Services", "Azure RBAC"],
        "answer": 1,
        "explain": "B2B collaboration invites external partners as guest users who authenticate with their own work, school, or social identities — you never manage their passwords. B2C is for consumer-facing applications, not partner collaboration.",
    },
    {
        "type": "mc",
        "q": "A retailer is building a public shopping app and wants customers to register and sign in with their Google or Facebook accounts, or a local email account. Which solution fits?",
        "choices": ["B2B guest invitations", "Microsoft Entra Domain Services", "B2C", "Conditional Access"],
        "answer": 2,
        "explain": "B2C (Azure AD B2C) is the customer-facing identity solution: consumers use social or local accounts kept in a separate customer-focused directory, apart from the workforce tenant. B2B is for inviting business partners into your own tenant, not for serving customers at scale.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST distinguishes B2B from B2C in Microsoft Entra external identities?",
        "choices": [
            "B2B is for customers with social accounts; B2C is for invited partners",
            "B2B invites partner guests into your tenant; B2C serves customers of your public apps in a separate directory",
            "B2B requires creating passwords for partners; B2C requires corporate credentials",
            "B2B works only on-premises; B2C works only in the cloud",
        ],
        "answer": 1,
        "explain": "B2B collaboration brings business partners in as guest users who keep their own credentials, while B2C manages consumer identities (social or local accounts) for customer-facing applications in a directory separate from your workforce. In both cases you never manage the external users' passwords.",
    },
    {
        "type": "mc",
        "q": "Security wants users to skip MFA when signing in from the corporate office but be required to complete MFA from any other location. Which Entra capability implements this?",
        "choices": ["Azure RBAC", "Microsoft Entra Connect", "Conditional Access", "Defender for Cloud"],
        "answer": 2,
        "explain": "Conditional Access applies if-then policies based on signals such as location, so MFA can be enforced only when needed — for example, off the corporate network. RBAC controls what users can do after sign-in, not how they authenticate.",
    },
    {
        "type": "mc",
        "q": "When a Conditional Access policy matches a sign-in, which set of decisions can it apply?",
        "choices": [
            "Allow access, require MFA, or block access",
            "Assign a role, remove a role, or create a role",
            "Encrypt, compress, or archive the session",
            "Only log the event for later review",
        ],
        "answer": 0,
        "explain": "Conditional Access evaluates signals (user, location, device, application, real-time risk) and then decides to allow the sign-in, allow it with extra controls such as requiring MFA, or block it outright. Role assignment is RBAC's job, and Conditional Access actively enforces decisions rather than only logging.",
    },
    {
        "type": "mc",
        "q": "An organization wants to stop authentication attempts from older email clients that cannot perform modern authentication. Which tool addresses this?",
        "choices": ["Microsoft Entra Domain Services", "Conditional Access", "Azure Arc", "The Reader role"],
        "answer": 1,
        "explain": "Blocking legacy clients that cannot do modern authentication is a classic Conditional Access use case — the client app is one of the signals a policy can evaluate and block. Entra Domain Services actually serves legacy protocols rather than blocking them.",
    },
    {
        "type": "mc",
        "q": "A new engineer must create and manage virtual machines and other resources in the Production resource group only, without being able to grant access to anyone. Which assignment follows least privilege?",
        "choices": [
            "Owner at the subscription scope",
            "Contributor at the Production resource group scope",
            "Contributor at the subscription scope",
            "Reader at the Production resource group scope",
        ],
        "answer": 1,
        "explain": "Contributor can create and manage resources but cannot grant access, and assigning it at the resource group scope confines the permissions to Production only — least privilege on both the role and the scope axis. Owner adds unneeded access-granting rights, subscription scope is too broad, and Reader cannot create anything.",
    },
    {
        "type": "mc",
        "q": "An external auditor needs to review the configuration of all resources in a subscription but must not be able to change anything. Which built-in role fits?",
        "choices": ["Contributor", "Owner", "Reader", "Virtual Machine Contributor"],
        "answer": 2,
        "explain": "Reader grants view-only access to existing resources — ideal for audits and reviews. Contributor and Owner can modify resources, and Virtual Machine Contributor is a service-specific management role, not a read-only one.",
    },
    {
        "type": "mc",
        "q": "A user is assigned the Reader role at the subscription scope. What access does she have to a resource group inside that subscription?",
        "choices": [
            "None until a role is assigned at the resource group",
            "Reader access, because RBAC assignments are inherited by child scopes",
            "Contributor access, because child scopes are elevated",
            "Owner access on resources she created herself",
        ],
        "answer": 1,
        "explain": "RBAC assignments flow down the hierarchy: a role granted at a parent scope (management group, subscription) is inherited by all child scopes (resource groups, resources). Inheritance never elevates the role — she remains a Reader everywhere within that subscription.",
    },
    {
        "type": "mc",
        "q": "A project lead with the Contributor role on a resource group tries to give a teammate access to it and is denied. Why?",
        "choices": [
            "Contributor can manage resources but cannot grant access; that requires Owner (or a role with access-management rights)",
            "Access can only be granted at the subscription scope",
            "The teammate must first enable MFA",
            "RBAC denies all requests by default until Conditional Access approves them",
        ],
        "answer": 0,
        "explain": "The classic Owner-vs-Contributor distinction: both manage resources fully, but only Owner also carries the right to grant access to others. Access can be granted at any scope, MFA is unrelated to role assignment rights, and RBAC is an allow model, not a Conditional Access dependency.",
    },
    {
        "type": "mc",
        "q": "A security team implements just-in-time, just-enough access so admins receive only the permissions they need, only when needed. Which Zero Trust principle is this?",
        "choices": ["Assume breach", "Verify explicitly", "Use least-privilege access", "Defense-in-depth"],
        "answer": 2,
        "explain": "Just-in-time and just-enough access (JIT/JEA) are the textbook expressions of the least-privilege principle. Verify explicitly means authenticating and authorizing on all available signals, and assume breach means segmenting, encrypting, and minimizing blast radius. Defense-in-depth is a separate layered model, not a Zero Trust principle.",
    },
    {
        "type": "mc",
        "q": "Under the Zero Trust model, what replaces the corporate network boundary as the primary security perimeter?",
        "choices": ["The datacenter firewall", "Identity", "The VPN concentrator", "Physical building security"],
        "answer": 1,
        "explain": "Zero Trust abandons the idea that being inside the corporate network earns trust; instead, every request is verified and identity becomes the new perimeter. Users and devices must prove themselves wherever they connect, so protecting identities matters more than protecting a network edge.",
    },
    {
        "type": "mc",
        "q": "What is the primary purpose of the defense-in-depth model?",
        "choices": [
            "To replace firewalls with identity checks",
            "To use multiple layers of protection so that an attacker who breaches one layer is slowed by the next",
            "To centralize all security into a single hardened gateway",
            "To guarantee attacks can never occur",
        ],
        "answer": 1,
        "explain": "Defense-in-depth stacks independent protective layers — physical, identity & access, perimeter, network, compute, application, data — so no single point of failure exposes the data at the center, and each breached layer slows the attack and generates alerts. It complements rather than replaces perimeter controls and cannot make attacks impossible.",
    },
    {
        "type": "mc",
        "q": "In the defense-in-depth model, DDoS protection that filters large-scale attacks before they reach users belongs to which layer?",
        "choices": ["Network", "Compute", "Perimeter", "Application"],
        "answer": 2,
        "explain": "The perimeter layer defends the edge of your environment — DDoS protection and perimeter firewalls live here. The network layer is about segmentation and limiting connectivity with NSGs, compute covers VM patching and endpoint protection, and application covers secure code.",
    },
    {
        "type": "mc",
        "q": "A CISO asks for a single tool that shows a secure score, prioritized hardening recommendations, a regulatory compliance view, and threat alerts for Azure workloads. Which service is it?",
        "choices": ["Microsoft Entra Conditional Access", "Azure RBAC", "Microsoft Entra Domain Services", "Microsoft Defender for Cloud"],
        "answer": 3,
        "explain": "Microsoft Defender for Cloud combines cloud security posture management (secure score, recommendations, compliance dashboard) with workload protection (threat detection and alerts). The other options handle authentication policy, authorization, and legacy domain services — none of them assess security posture.",
    },
    {
        "type": "mc",
        "q": "A company wants Microsoft Defender for Cloud to also monitor its on-premises servers and AWS virtual machines. What enables this?",
        "choices": [
            "Connecting the machines through Azure Arc",
            "Moving all servers into Azure first",
            "Installing Microsoft Entra Connect on each server",
            "Assigning the machines the Reader role",
        ],
        "answer": 0,
        "explain": "Defender for Cloud is not limited to Azure: on-premises and other-cloud machines are connected through Azure Arc, which projects them into Azure for management and protection. Entra Connect syncs identities (not servers), and RBAC roles apply to security principals, not machines being monitored.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Passwordless authentication is less secure than a traditional password because it removes a factor.",
        "answer": False,
        "explain": "Passwordless removes the weakest factor and replaces it with something you have (a registered device or FIDO2 key) plus something you know or are (PIN or biometric) — it is both more secure and more convenient. The biometric or PIN never leaves the device, making phishing far harder.",
    },
    {
        "type": "tf",
        "q": "True or False: A user with the Contributor role on a subscription can grant other users access to that subscription.",
        "answer": False,
        "explain": "Contributor can create and manage all types of resources but cannot grant access to others — that is the defining difference from Owner, which includes access management. This distinction is one of the most frequently tested RBAC facts.",
    },
    {
        "type": "tf",
        "q": "True or False: Azure RBAC is an allow model — role assignments grant permissions, and multiple assignments add together rather than subtract.",
        "answer": True,
        "explain": "RBAC grants what roles allow; it does not carry deny-first semantics. If one assignment grants read at the subscription and another grants write on a resource group, the user has both there. Least privilege is achieved by granting narrowly, not by denying broadly.",
    },
    {
        "type": "tf",
        "q": "True or False: Microsoft Defender for Cloud can only assess and protect resources that are hosted in Azure.",
        "answer": False,
        "explain": "Defender for Cloud covers Azure natively and extends to on-premises and other clouds such as AWS and GCP, with hybrid machines connected through Azure Arc. Its foundational CSPM features (secure score and recommendations) are free for Azure subscriptions, with paid Defender plans adding workload protections.",
    },
    {
        "type": "tf",
        "q": "True or False: In a B2C scenario, customer identities are stored in the same directory as the organization's employee identities.",
        "answer": False,
        "explain": "B2C keeps consumer identities in a separate customer-focused directory, isolated from the workforce tenant. This separation is a key contrast with B2B collaboration, where invited partners appear as guest objects inside your own tenant.",
    },
    {
        "type": "tf",
        "q": "True or False: Requiring a password plus a PIN at sign-in satisfies the definition of multifactor authentication.",
        "answer": False,
        "explain": "A password and a PIN are both something you know — the same factor category — so together they are still single-factor. MFA requires evidence from at least two different categories: something you know, something you have, and something you are.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The Microsoft Entra feature that applies if-then policies based on signals such as user, location, device, and risk to allow, require MFA, or block sign-ins is ______ ______. (type your answer)",
        "answers": ["conditional access", "microsoft entra conditional access", "entra conditional access"],
        "explain": "Conditional Access is Entra ID's signal-based policy engine: if the sign-in matches the conditions, then apply the decision. It enables MFA only when needed and can block legacy clients that cannot perform modern authentication.",
    },
    {
        "type": "fill",
        "q": "Microsoft Defender for Cloud quantifies your current security posture with a single metric called the ______ score. (type your answer)",
        "answers": ["secure", "secure score", "security"],
        "explain": "The secure score summarizes your posture and rises as you remediate the prioritized hardening recommendations Defender for Cloud generates. It is part of the free foundational CSPM tier available to every Azure subscription.",
    },
    {
        "type": "fill",
        "q": "The security model built on 'verify explicitly, use least-privilege access, and assume breach' is called ______ ______. (type your answer)",
        "answers": ["zero trust", "the zero trust model", "zero trust security", "zerotrust"],
        "explain": "Zero Trust treats every request as if it came from an open, untrusted network — never trust, always verify. Under this model identity becomes the new perimeter, replacing reliance on a trusted corporate network location.",
    },
    {
        "type": "fill",
        "q": "Azure's authorization system that assigns roles like Owner, Contributor, and Reader to security principals at a scope is Azure ______. (acronym accepted)",
        "answers": ["rbac", "role based access control", "role-based access control", "azure rbac"],
        "explain": "Azure role-based access control grants permissions by assigning a role to a user, group, service principal, or managed identity at a management group, subscription, resource group, or resource scope. Assignments are inherited by child scopes and follow an allow model.",
    },
    {
        "type": "fill",
        "q": "The unphishable hardware security keys (USB, NFC, or Bluetooth) supported as a passwordless sign-in method in Microsoft Entra ID follow the ______ standard. (type your answer)",
        "answers": ["fido2", "fido 2", "fido"],
        "explain": "FIDO2 security keys are one of Microsoft's three passwordless options, alongside Windows Hello for Business and the Microsoft Authenticator app. Because the key performs cryptographic sign-in with no shared secret to type, it resists phishing and works well in shared or restricted environments.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each built-in Azure RBAC role to its capability.",
        "pairs": [
            ["Owner", "Full access to resources, including granting access to others"],
            ["Contributor", "Create and manage all resources, but cannot grant access"],
            ["Reader", "View existing resources only"],
            ["Virtual Machine Contributor", "Service-specific role limited to managing virtual machines"],
        ],
        "explain": "Owner = Contributor plus access management; Reader is view-only. Service-specific roles like Virtual Machine Contributor narrow permissions to one resource type, supporting least privilege on the role axis just as scope narrows it on the resource axis.",
    },
    {
        "type": "match",
        "q": "Match each Microsoft Entra capability to its purpose.",
        "pairs": [
            ["Microsoft Entra ID", "Cloud identity and access management: sign-in, SSO, MFA"],
            ["Microsoft Entra Domain Services", "Managed domain join, Group Policy, LDAP, and Kerberos without customer-run DCs"],
            ["Microsoft Entra Connect", "Syncs on-premises Active Directory identities to the cloud"],
            ["B2B collaboration", "Invites partner guests who use their own credentials"],
            ["B2C", "Lets customers sign in to public apps with social or local accounts"],
        ],
        "explain": "Entra ID is the core cloud directory; Domain Services adds legacy protocols as a managed service; Connect bridges on-prem AD to the cloud; and the two external-identity options split by audience — B2B for business partners, B2C for consumers.",
    },
    {
        "type": "match",
        "q": "Match each defense-in-depth layer to an example protection.",
        "pairs": [
            ["Perimeter", "DDoS protection filtering large-scale attacks at the edge"],
            ["Network", "NSGs and limiting connectivity between resources"],
            ["Compute", "Keeping VMs patched with endpoint protection installed"],
            ["Application", "Secure code with no secrets stored in it"],
            ["Data", "Encryption at rest and in transit with access controls"],
        ],
        "explain": "Perimeter guards the edge (DDoS, perimeter firewalls); network limits lateral connectivity with NSGs; compute hardens the machines; application hardens the code (secrets belong in a vault); and data — the attacker's ultimate target — sits encrypted at the center.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the defense-in-depth layers from OUTERMOST to INNERMOST.",
        "items": [
            "Physical security",
            "Identity & access",
            "Perimeter",
            "Network",
            "Compute",
            "Application",
            "Data",
        ],
        "explain": "The seven layers run from the datacenter building at the outside to the data at the core: physical security, identity & access, perimeter (DDoS), network (NSGs), compute (patching), application (secure code), data (encryption). Each layer an attacker penetrates slows them down and buys defenders time to detect and respond.",
    },
    {
        "type": "order",
        "q": "Arrange the Azure RBAC scope levels from BROADEST to NARROWEST.",
        "items": [
            "Management group",
            "Subscription",
            "Resource group",
            "Resource",
        ],
        "explain": "Management groups sit above subscriptions, which contain resource groups, which contain individual resources. A role assigned at any level is inherited by everything below it, which is why least privilege means assigning at the narrowest scope that gets the job done.",
    },
]
