TOPIC = {
    "id": "3.2",
    "domain": 3,
    "title": "Describe features and tools in Azure for governance and compliance.",
    "short": "Governance & Compliance",
}

TERMS = [
    ("Microsoft Purview", "Unified data-governance and compliance family that discovers, classifies, and traces sensitive data across Azure, on-premises, Microsoft 365, and other clouds"),
    ("Automated data discovery", "Purview capability that scans registered data sources on a schedule and catalogs what data exists and where — no manual inventorying"),
    ("Sensitive-data classification", "Purview capability that labels discovered data (credit card numbers, national IDs, health records) so regulated data can be located and protected"),
    ("Data lineage", "End-to-end trace of where data originated and how it moves and transforms across systems, from source database through pipelines into reports"),
    ("Data estate map", "Purview's holistic, up-to-date view of an organization's data spanning Azure, on-premises, Microsoft 365, and other clouds"),
    ("Risk and compliance solutions (Purview)", "Purview solution area anchored in Microsoft 365 data: protecting sensitive data and meeting regulatory requirements such as GDPR"),
    ("Unified data governance (Purview)", "Purview solution area that maps and manages data across the entire multicloud, on-premises, and SaaS estate"),
    ("Azure Policy", "Service for creating, assigning, and managing rules that enforce standards on Azure resources — allowed regions, required tags, permitted SKUs"),
    ("Policy definition", "A single Azure Policy rule, such as 'allowed locations = East US' or 'resources must carry a costCenter tag'"),
    ("Initiative", "A group of related Azure Policy definitions that are defined, assigned, and tracked for compliance as a single unit"),
    ("Policy assignment", "Applying a policy or initiative at a scope — management group, subscription, or resource group — from which it inherits downward"),
    ("Deny effect", "Azure Policy effect that blocks the creation or update of a non-compliant resource so it never comes into existence"),
    ("Audit effect", "Azure Policy effect that allows the resource but flags it as non-compliant on the compliance dashboard for reporting"),
    ("Append/Modify effect", "Azure Policy remediation effect that automatically adds a required setting, such as a missing mandatory tag"),
    ("Resource lock", "Safeguard on a subscription, resource group, or resource that prevents accidental deletion or modification and applies regardless of RBAC roles"),
    ("CanNotDelete lock", "Delete lock: authorized users can still read and modify the resource, but deletion is blocked until the lock is removed"),
    ("ReadOnly lock", "Lock that permits reads only — both modification and deletion of the resource are blocked"),
    ("Lock inheritance", "Locks applied at a parent scope (subscription or resource group) automatically apply to every resource within that scope"),
    ("Role-based access control (RBAC)", "Authorization system governing WHO can perform which actions on resources — contrast with Azure Policy, which governs WHAT resources may look like"),
    ("Cloud Adoption Framework", "Microsoft's collected best practices, documentation, and tools that guide an organization's journey to the cloud"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A multinational must automatically discover, classify, and trace the lineage of sensitive customer data stored in Azure SQL, on-premises file servers, Microsoft 365, and an AWS S3 bucket. Which service should it use?",
        "choices": ["Azure Policy", "Microsoft Purview", "Azure Monitor", "Microsoft Entra ID"],
        "answer": 1,
        "explain": "Microsoft Purview is the unified data-governance and compliance family: automated discovery, sensitive-data classification, and end-to-end lineage across Azure, on-premises, Microsoft 365, and other clouds. Azure Policy governs resource configuration (not data content), Azure Monitor collects telemetry, and Microsoft Entra ID (formerly Azure Active Directory) handles identity.",
    },
    {
        "type": "mc",
        "q": "Auditors ask to see exactly how the figures in a quarterly report trace back through data pipelines to the original source database. Which Microsoft Purview capability provides this?",
        "choices": ["Sensitive-data classification", "Automated data discovery", "End-to-end data lineage", "Compliance dashboard"],
        "answer": 2,
        "explain": "Data lineage traces where data originated and how it moved and transformed across systems — source to pipeline to report — which is precisely what an audit trail of report figures requires. Discovery finds and catalogs data sources, classification labels sensitive content, and the compliance dashboard belongs to Azure Policy, not Purview.",
    },
    {
        "type": "mc",
        "q": "Microsoft Purview brings together which TWO solution areas?",
        "choices": [
            "Risk and compliance solutions, and unified data governance",
            "Monitoring and alerting, and cost management",
            "Identity management, and access reviews",
            "Backup and recovery, and site resilience",
        ],
        "answer": 0,
        "explain": "Purview combines risk and compliance solutions (anchored in Microsoft 365 data — protecting sensitive information and meeting regulations like GDPR) with unified data governance (mapping and managing data across Azure, on-premises, multicloud, and SaaS). The other pairings describe Azure Monitor/Cost Management, Entra ID, and business-continuity services.",
    },
    {
        "type": "mc",
        "q": "A compliance officer wants to locate every place credit-card numbers are stored across the company's Azure services and on-premises file shares. A junior admin proposes Azure Policy. Why is that wrong, and what is right?",
        "choices": [
            "Azure Policy only works on-premises; use Azure Arc instead",
            "Azure Policy governs resource configuration, not data content; use Microsoft Purview's classification",
            "Azure Policy cannot span subscriptions; use a management group instead",
            "Nothing is wrong — Azure Policy classifies sensitive data natively",
        ],
        "answer": 1,
        "explain": "Azure Policy evaluates the configuration of Azure resources (regions, tags, SKUs); it never inspects the data inside them. Finding and labeling sensitive content like credit-card numbers — including on-premises sources — is Microsoft Purview's sensitive-data classification. Management groups only broaden policy scope; they don't add data awareness.",
    },
    {
        "type": "mc",
        "q": "Your company requires that ALL Azure resources, no matter who creates them, can only be deployed in the East US region. What should you use?",
        "choices": ["Role-based access control (RBAC)", "A ReadOnly resource lock", "Azure Policy", "Azure Advisor"],
        "answer": 2,
        "explain": "An Azure Policy with an allowed-locations rule (deny effect) blocks resource creation outside East US for everyone, including Owners — Policy governs WHAT resources may be. RBAC governs WHO can act, locks prevent accidental deletion/change of existing resources, and Advisor only recommends.",
    },
    {
        "type": "mc",
        "q": "Governance requires a costCenter tag on every resource, and resources created without it should have the tag added automatically. What accomplishes this?",
        "choices": [
            "A CanNotDelete lock on each resource",
            "An Azure Policy with an append/modify remediation effect",
            "Microsoft Purview data classification",
            "Assigning all users the Contributor role",
        ],
        "answer": 1,
        "explain": "Azure Policy can not only detect missing required tags but automatically remediate by appending them — the classic costCenter tag scenario. Locks control deletion/modification, Purview classifies data content, and RBAC role assignments say nothing about tagging standards.",
    },
    {
        "type": "mc",
        "q": "A security team has authored 20 individual policies that together implement a regulatory standard. They want to assign and track compliance for all 20 as one unit. What should they create?",
        "choices": ["A management group", "An initiative", "A resource lock", "A subscription"],
        "answer": 1,
        "explain": "An initiative is a group of related policy definitions defined, assigned, and monitored for compliance as a single unit — assign it once instead of twenty separate policies. A management group is a scope container for subscriptions, not a bundle of policies; locks and subscriptions are unrelated to grouping rules.",
    },
    {
        "type": "mc",
        "q": "An initiative is assigned at a management group containing 12 subscriptions. What is the effect?",
        "choices": [
            "Only resources created in the management group itself are evaluated",
            "Each subscription owner must accept the assignment before it applies",
            "The assignment inherits downward to every subscription, resource group, and resource beneath the management group",
            "The initiative applies only to new subscriptions added after the assignment",
        ],
        "answer": 2,
        "explain": "Policy and initiative assignments inherit downward from their scope: a management-group assignment automatically covers all 12 subscriptions and everything inside them, with no opt-in required. Existing resources are evaluated too, showing up on the compliance dashboard if they violate the rules.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST captures the difference between Azure Policy and role-based access control (RBAC)?",
        "choices": [
            "Policy governs WHO can act on resources; RBAC governs WHAT resources may look like",
            "Policy governs WHAT resources can be created and how they are configured; RBAC governs WHO can perform which actions",
            "Policy applies only to subscriptions; RBAC applies only to resource groups",
            "They are interchangeable ways of granting permissions",
        ],
        "answer": 1,
        "explain": "Azure Policy enforces standards on resources themselves — allowed regions, required tags, permitted SKUs — regardless of the creator. RBAC controls which identities may perform which operations. The exam loves this contrast: a deny policy blocks even a user whose RBAC role fully permits the action.",
    },
    {
        "type": "mc",
        "q": "Which Azure Policy effect ensures a non-compliant resource is never created in the first place?",
        "choices": ["Audit", "Append", "Deny", "ReadOnly"],
        "answer": 2,
        "explain": "The deny effect blocks the creation or update of a resource that violates the policy, stopping non-compliance before it exists. Audit allows the resource but flags it, append/modify remediates by adding required settings, and ReadOnly is a resource-lock type, not a policy effect.",
    },
    {
        "type": "mc",
        "q": "A new policy requiring encryption is assigned to a subscription that already contains 50 unencrypted storage accounts. What happens to those existing accounts?",
        "choices": [
            "They are deleted automatically after a grace period",
            "They are highlighted as non-compliant on the compliance dashboard",
            "They are moved to a quarantine resource group",
            "Nothing — Azure Policy only evaluates future deployments",
        ],
        "answer": 1,
        "explain": "Azure Policy continuously evaluates existing resources as well as new deployments, and violators are flagged as non-compliant on the compliance dashboard (or remediated if the effect supports it). Policy never deletes or relocates existing resources — that is a common distractor.",
    },
    {
        "type": "mc",
        "q": "A user with the Owner role tries to create a storage account without the corporate encryption setting and the deployment fails, even though the role permits creating storage accounts. Why?",
        "choices": [
            "The user also needs the Global Administrator role",
            "A deny-effect Azure Policy applies regardless of the user's RBAC permissions",
            "A CanNotDelete lock is blocking the creation",
            "Storage accounts always require encryption to deploy",
        ],
        "answer": 1,
        "explain": "Deny policies evaluate the resource being created, not the identity creating it, so even a fully-permissioned Owner is blocked. RBAC and Policy are independent gates: RBAC said yes (WHO), Policy said no (WHAT). Locks only protect existing resources from deletion or modification, not new deployments.",
    },
    {
        "type": "mc",
        "q": "A production SQL database must never be deleted, but DBAs still need to change its performance tier and settings. Which safeguard fits?",
        "choices": ["A ReadOnly lock", "A CanNotDelete lock", "An Azure Policy audit effect", "Removing all RBAC assignments"],
        "answer": 1,
        "explain": "CanNotDelete (the Delete lock) blocks deletion while still allowing reads and modifications — exactly the tune-but-never-delete requirement. A ReadOnly lock would also block the DBAs' configuration changes, an audit policy only reports, and stripping RBAC would lock the DBAs out entirely.",
    },
    {
        "type": "mc",
        "q": "The network team requires that the hub virtual network's configuration cannot be modified OR deleted by anyone until a formal change window. Which lock type enforces this?",
        "choices": ["CanNotDelete", "ReadOnly", "Deny", "Audit"],
        "answer": 1,
        "explain": "A ReadOnly lock allows reading only — both modification and deletion are blocked, freezing the configuration. CanNotDelete would still permit changes, and deny/audit are Azure Policy effects for evaluating deployments, not locks on existing resources.",
    },
    {
        "type": "mc",
        "q": "An administrator with the Owner role attempts to delete a storage account and receives an error that the operation is blocked. What must happen before the deletion can succeed?",
        "choices": [
            "The administrator must be granted the Global Administrator role",
            "The resource lock must be removed first, then the deletion retried",
            "The policy initiative must be unassigned from the subscription",
            "The storage account must first be moved to another resource group",
        ],
        "answer": 1,
        "explain": "Resource locks apply regardless of RBAC — even an Owner is blocked until the lock (applied directly or inherited from the resource group or subscription) is removed. This deliberate two-step process is the point: it forces a pause before destructive actions. No identity role or policy change lifts a lock.",
    },
    {
        "type": "mc",
        "q": "At which scopes can an Azure resource lock be applied?",
        "choices": [
            "Management group only",
            "Tenant and management group",
            "Subscription, resource group, or individual resource",
            "Individual resource only",
        ],
        "answer": 2,
        "explain": "Locks can be applied at the subscription, resource group, or resource level, and they are inherited by everything beneath the locked scope. Management groups are a scope for policy and RBAC assignments, but resource locks are not applied there — a favorite distractor.",
    },
    {
        "type": "mc",
        "q": "A CanNotDelete lock is applied to a resource group containing 30 resources. What is the result?",
        "choices": [
            "Only the resource group object itself is protected",
            "All 30 resources inherit the lock and cannot be deleted",
            "Each resource must be individually locked to gain protection",
            "The resources become read-only",
        ],
        "answer": 1,
        "explain": "Locks are inherited: a lock at the resource-group scope protects every resource inside it, current and future. One lock covers the whole group — no per-resource work needed. The resources are not read-only, because CanNotDelete still allows modification; only deletion is blocked.",
    },
    {
        "type": "mc",
        "q": "Which threat do resource locks actually protect against?",
        "choices": [
            "Malicious insiders determined to destroy resources",
            "External attackers with stolen credentials",
            "Accidental deletion or modification by authorized users",
            "Distributed denial-of-service attacks",
        ],
        "answer": 2,
        "explain": "Locks are a guardrail against honest mistakes: an authorized admin fat-fingering a delete is stopped and forced to consciously remove the lock first. They are not a security control — anyone with permission to manage locks can remove one, so malicious scenarios call for RBAC, auditing, and identity protections instead.",
    },
    {
        "type": "mc",
        "q": "After a ReadOnly lock is placed on a storage account, an application unexpectedly fails to list the account's access keys. Why?",
        "choices": [
            "The lock deleted the access keys",
            "Listing keys is a management (POST) operation, which the ReadOnly lock blocks",
            "ReadOnly locks disable all network traffic to the resource",
            "The application lacks the Reader RBAC role",
        ],
        "answer": 1,
        "explain": "Listing storage account keys looks like a read but is actually a POST management operation, so a ReadOnly lock blocks it. This is the classic ReadOnly-lock side effect: operations that technically modify or invoke management APIs fail even though they feel like reads. The lock does not touch data-plane network traffic or keys themselves.",
    },
    {
        "type": "mc",
        "q": "Which pairing of governance need and Azure tool is CORRECT?",
        "choices": [
            "Trace data lineage across clouds — resource lock",
            "Block resource creation outside approved regions — Microsoft Purview",
            "Prevent accidental deletion of a production resource — Azure Policy audit effect",
            "Require a costCenter tag on all resources — Azure Policy",
        ],
        "answer": 3,
        "explain": "Tag enforcement is a textbook Azure Policy job (deny or append/modify). The other pairs are crossed: lineage belongs to Purview, region restrictions belong to Azure Policy, and preventing accidental deletion is a resource lock — an audit effect only reports, it never blocks.",
    },
    {
        "type": "mc",
        "q": "A company beginning its move to Azure wants Microsoft's proven best practices, documentation, and tools for planning and governing its cloud journey. What should it consult?",
        "choices": ["The Cloud Adoption Framework", "Microsoft Purview", "The Azure compliance dashboard", "A ReadOnly lock"],
        "answer": 0,
        "explain": "The Cloud Adoption Framework is Microsoft's collected guidance — strategy, planning, governance, and management best practices — for the cloud adoption journey. Purview governs data, the compliance dashboard shows Azure Policy results, and locks protect individual resources; none of them are guidance frameworks.",
    },
    {
        "type": "mc",
        "q": "Management wants a single dashboard showing which resources across all subscriptions meet corporate configuration standards and which do not. Which tool provides this?",
        "choices": ["Microsoft Purview", "Azure Policy", "Resource locks", "Microsoft Entra ID"],
        "answer": 1,
        "explain": "Azure Policy continuously evaluates resources against assigned policies and initiatives and highlights compliant versus non-compliant resources on its compliance dashboard. Purview maps and classifies data (not resource configuration), locks prevent deletion/change, and Entra ID is the identity service.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Microsoft Purview can only discover and classify data that is stored in Azure services.",
        "answer": False,
        "explain": "Purview's defining strength is breadth: it spans Azure, on-premises systems, Microsoft 365, and other clouds such as AWS and Google Cloud, building a single map of the entire data estate. An Azure-only scope is a classic distractor.",
    },
    {
        "type": "tf",
        "q": "True or False: Azure Policy can automatically remediate certain non-compliance, such as appending a required tag to a resource created without it.",
        "answer": True,
        "explain": "Beyond deny (block) and audit (flag), Azure Policy supports remediation effects like append/modify that automatically bring resources into compliance — the required-tag scenario is the standard example. Policy is not limited to reporting.",
    },
    {
        "type": "tf",
        "q": "True or False: When a new deny policy is assigned, Azure automatically deletes existing resources that violate it.",
        "answer": False,
        "explain": "Deny only blocks new creations and updates that violate the policy. Resources that already exist are evaluated and marked non-compliant on the compliance dashboard — they are never deleted by Policy. Cleanup of existing violators is a human (or scripted remediation) decision.",
    },
    {
        "type": "tf",
        "q": "True or False: A user with the Owner role can delete a locked resource without removing the lock, because RBAC permissions override resource locks.",
        "answer": False,
        "explain": "It is the other way around: locks apply regardless of RBAC, so even an Owner is blocked until the lock is removed. That forced pause is the entire purpose of locks — making destructive actions deliberate rather than accidental.",
    },
    {
        "type": "tf",
        "q": "True or False: A CanNotDelete lock still allows authorized users to read and modify the resource.",
        "answer": True,
        "explain": "CanNotDelete (the Delete lock) blocks only deletion; reading and modifying remain allowed for users with the right RBAC permissions. If modification must also be blocked, the stricter ReadOnly lock is required.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "A group of related Azure Policy definitions that is defined, assigned, and tracked as a single unit is called an ______. (type your answer)",
        "answers": ["initiative", "policy initiative", "initiatives"],
        "explain": "An initiative bundles related policies — for example, twenty rules implementing one regulatory standard — so you assign and monitor compliance once instead of per policy. It is not a management group, which is a scope container for subscriptions.",
    },
    {
        "type": "fill",
        "q": "The Azure service used to ensure that resources can only be created in approved regions, such as East US, is Azure ______. (type your answer)",
        "answers": ["policy", "azure policy"],
        "explain": "Azure Policy enforces standards on resources — allowed locations, required tags, permitted SKUs — and with a deny effect it blocks non-compliant creations for everyone, including Owners. RBAC could not express this because it governs identities, not resource properties.",
    },
    {
        "type": "fill",
        "q": "The resource lock type that blocks deletion but still allows reading and modifying the resource is the ______ lock. (type your answer)",
        "answers": ["cannotdelete", "cannot delete", "can not delete", "delete", "delete lock"],
        "explain": "CanNotDelete (also shown as the Delete lock in the portal) permits reads and modifications while blocking deletion — ideal for resources that must be tunable but never destroyed. ReadOnly is the stricter type that blocks changes as well.",
    },
    {
        "type": "fill",
        "q": "The resource lock type that blocks BOTH modification and deletion, allowing only reads, is the ______ lock. (type your answer)",
        "answers": ["readonly", "read only", "read only lock"],
        "explain": "A ReadOnly lock freezes the resource entirely — no changes, no deletion, reads only. Beware its side effects: management operations that look like reads (such as listing storage account keys, a POST call) are also blocked.",
    },
    {
        "type": "fill",
        "q": "Microsoft's unified data-governance service that maps, classifies, and traces data across Azure, on-premises, Microsoft 365, and other clouds is Microsoft ______. (type your answer)",
        "answers": ["purview", "microsoft purview", "azure purview"],
        "explain": "Microsoft Purview (which absorbed the former Azure Purview and Microsoft 365 compliance tools) provides automated data discovery, sensitive-data classification, and end-to-end lineage — a single map of the entire data estate.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each governance tool or concept to its purpose.",
        "pairs": [
            ["Microsoft Purview", "Discover, classify, and trace data across the entire estate"],
            ["Azure Policy", "Enforce configuration standards on Azure resources"],
            ["Initiative", "Group of related policies assigned as one unit"],
            ["Resource lock", "Prevent accidental deletion or modification of resources"],
            ["RBAC", "Control who can perform which actions on resources"],
        ],
        "explain": "Purview governs data, Policy governs resource configuration (with initiatives bundling related policies), locks freeze critical resources against accidents, and RBAC — outside this objective but its favorite distractor — governs identities and their permitted actions.",
    },
    {
        "type": "match",
        "q": "Match each Azure Policy effect or lock type to its behavior.",
        "pairs": [
            ["Deny effect", "Blocks creation of a non-compliant resource"],
            ["Audit effect", "Allows the resource but flags it as non-compliant"],
            ["Append/Modify effect", "Automatically adds a required setting such as a tag"],
            ["CanNotDelete lock", "Read and modify allowed; delete blocked"],
            ["ReadOnly lock", "Read allowed; modify and delete blocked"],
        ],
        "explain": "The three policy effects act at deployment/evaluation time — block, report, or fix. The two lock types protect existing resources: CanNotDelete stops only deletion, while ReadOnly freezes the resource completely. Effects belong to Azure Policy; locks are a separate mechanism.",
    },
    {
        "type": "match",
        "q": "Match each Microsoft Purview capability to its description.",
        "pairs": [
            ["Automated data discovery", "Scans registered sources and catalogs what data exists and where"],
            ["Sensitive-data classification", "Labels data such as credit-card numbers and health records"],
            ["Data lineage", "Traces data's origin and movement from source to report"],
            ["Data estate map", "Holistic view of data across clouds, on-premises, and Microsoft 365"],
        ],
        "explain": "The pipeline builds on itself: discovery finds the data, classification labels its sensitivity, lineage traces its journey, and together they populate the data estate map — the single pane answering what data you have, where it is, and how it flows.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the Azure scope hierarchy for policy assignment and inheritance, from BROADEST to NARROWEST.",
        "items": [
            "Management group",
            "Subscription",
            "Resource group",
            "Resource",
        ],
        "explain": "Assignments inherit downward through this hierarchy: a policy or initiative assigned at a management group covers every subscription beneath it, each subscription covers its resource groups, and each resource group covers its resources. Assign high to standardize broadly; assign low to scope narrowly.",
    },
    {
        "type": "order",
        "q": "An administrator must delete a critical resource protected by a lock. Arrange the events from first to last.",
        "items": [
            "The administrator attempts to delete the locked resource",
            "Azure blocks the operation because of the lock, regardless of the admin's RBAC role",
            "The administrator deliberately removes the resource lock",
            "The administrator retries and successfully deletes the resource",
            "Locks are re-applied to the remaining critical resources",
        ],
        "explain": "Locks override RBAC, so even an Owner's delete fails until the lock is consciously removed — that forced pause is the design goal. After the intended deletion, re-applying locks restores protection for what remains. The sequence shows locks guard against accidents, not determined authorized users.",
    },
]
