TOPIC = {
    "id": "3.3",
    "domain": 3,
    "title": "Describe features and tools for managing and deploying Azure resources.",
    "short": "Manage & Deploy",
}

TERMS = [
    ("Azure portal", "Web-based graphical interface for building, managing, and monitoring everything in Azure, with customizable dashboards and no CLI knowledge required"),
    ("Azure mobile app", "Phone/tablet app for on-the-go Azure management — check health and alerts, view metrics, restart VMs, and run Cloud Shell commands away from a computer"),
    ("Azure Cloud Shell", "Browser-based shell hosted in the Azure portal — nothing to install locally, automatically authenticated, offering both Azure CLI and Azure PowerShell"),
    ("Azure CLI", "Cross-platform command-line tool using bash-style commands that start with 'az' (e.g., az vm create) to create, manage, and script Azure resources"),
    ("Azure PowerShell", "Cross-platform tool using cmdlets from the Az module (e.g., New-AzVM) to create, manage, and script Azure resources"),
    ("Az module", "The PowerShell module containing the Azure cmdlets used by Azure PowerShell"),
    ("Azure Arc", "Service that extends the Azure management plane (Policy, RBAC, tags, Monitor) to resources outside Azure — on-prem servers, Kubernetes, SQL Server, VMs in other clouds"),
    ("Single pane of glass", "One consistent management and governance view across hybrid and multicloud resources — the core value proposition of Azure Arc"),
    ("Infrastructure as code (IaC)", "Defining infrastructure in files so deployments are repeatable, consistent, versionable, and reviewable, avoiding manual configuration"),
    ("Declarative approach", "IaC style that describes the desired END STATE ('what'); the platform determines the steps — ARM templates and Bicep are declarative"),
    ("Imperative approach", "Automation style that lists the step-by-step COMMANDS to run in order ('how'), such as a bash script of az commands"),
    ("Configuration drift", "Environments gradually diverging from their intended state through manual, untracked changes — prevented by redeploying from IaC definitions"),
    ("Azure Resource Manager (ARM)", "Azure's deployment and management layer — every request from portal, CLI, PowerShell, REST, or SDKs is authenticated, authorized, and routed by ARM"),
    ("ARM template", "Declarative JSON file defining the resources to deploy; validated before deployment, idempotent, with dependencies orchestrated by ARM"),
    ("Bicep", "Domain-specific language with simpler declarative syntax (no JSON boilerplate) that transpiles to ARM template JSON; supports all resource types immediately"),
    ("Idempotence", "Property of ARM template/Bicep deployments where re-running the same file yields the same environment — no duplicates, no unintended changes"),
    ("Transpilation", "The conversion of a Bicep file into standard ARM template JSON at deployment time"),
    ("Resource provider", "The Azure service (e.g., Microsoft.Compute) that ARM routes an authorized request to so the actual resource operation is performed"),
    ("Template validation", "ARM's pre-deployment check of an ARM template so a broken definition fails before any resources are touched"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A new administrator with no scripting experience needs to create, manage, and monitor Azure resources through a graphical interface with customizable dashboards. What should they use?",
        "choices": ["Azure Cloud Shell", "Azure portal", "Azure CLI", "ARM templates"],
        "answer": 1,
        "explain": "The Azure portal is the web-based GUI for building, managing, and monitoring everything in Azure, with dashboards and guided wizards — no command-line knowledge needed. Cloud Shell, the CLI, and ARM templates all require typing commands or authoring files.",
    },
    {
        "type": "mc",
        "q": "An on-call engineer commuting home gets an alert that a VM is unhealthy and needs to check its metrics and restart it from a phone. Which tool is designed for this?",
        "choices": ["Azure mobile app", "Azure Arc", "Bicep", "Azure Resource Manager"],
        "answer": 0,
        "explain": "The Azure mobile app provides on-the-go management: viewing health, alerts, and metrics, restarting VMs, and even running Cloud Shell commands from a phone or tablet. Arc is for non-Azure resources, Bicep is an IaC language, and ARM is the underlying management layer, not a mobile client.",
    },
    {
        "type": "mc",
        "q": "A consultant at a client site is given a locked-down loaner laptop with only a web browser and must immediately run several az commands against her subscription. What should she use?",
        "choices": [
            "Install the Azure CLI locally with admin rights",
            "Azure Cloud Shell from the browser",
            "Remote Desktop into an Azure VM",
            "The REST API with curl",
        ],
        "answer": 1,
        "explain": "Azure Cloud Shell is a browser-based shell inside the Azure portal that requires no local installation and is automatically authenticated as the signed-in user — ideal when you cannot install software. Installing tools needs admin rights she lacks, and the other options add setup the scenario forbids.",
    },
    {
        "type": "mc",
        "q": "Which TWO command-line environments does Azure Cloud Shell provide?",
        "choices": [
            "Azure CLI and Azure PowerShell",
            "Command Prompt and Git Bash",
            "Python shell and Ruby shell",
            "Azure CLI and AWS CLI",
        ],
        "answer": 0,
        "explain": "Cloud Shell offers both a Bash environment with the Azure CLI and a PowerShell environment with the Az module, and you can switch between them. It is a hosted environment containing both official Azure command-line tools, not a separate third language.",
    },
    {
        "type": "mc",
        "q": "An operations team of long-time Linux administrators fluent in bash wants to script Azure resource management. Which tool is the most natural fit?",
        "choices": ["Azure PowerShell", "The Azure portal", "Azure CLI", "Azure Arc"],
        "answer": 2,
        "explain": "The Azure CLI uses bash-style commands beginning with 'az', so it feels familiar to Linux/bash administrators. Both CLI and PowerShell can do the same work — the deciding factor is which scripting language the team already knows, and here that is bash.",
    },
    {
        "type": "mc",
        "q": "A script contains the command New-AzVM to create a virtual machine. Which tool is being used?",
        "choices": ["Azure CLI", "Azure Cloud Shell only", "Bicep", "Azure PowerShell"],
        "answer": 3,
        "explain": "Verb-Noun cmdlets from the Az module, like New-AzVM, are the signature of Azure PowerShell. The Azure CLI would use 'az vm create' instead; Cloud Shell can host either tool but is not itself the language; Bicep is a declarative file format, not a command.",
    },
    {
        "type": "mc",
        "q": "Both the Azure CLI and Azure PowerShell can perform the same Azure management tasks. According to Microsoft, what should drive the choice between them?",
        "choices": [
            "The scripting language your team already knows",
            "The CLI works only on Linux, PowerShell only on Windows",
            "PowerShell can manage more Azure services than the CLI",
            "Only the CLI can run inside Cloud Shell",
        ],
        "answer": 0,
        "explain": "The tools are functionally equivalent and both are cross-platform (Windows, Linux, macOS), so the practical differentiator is team familiarity — bash shops pick the CLI, PowerShell shops pick the Az module. Both are available locally and in Cloud Shell.",
    },
    {
        "type": "mc",
        "q": "A company runs 40 on-premises servers and 15 VMs in AWS. It wants to apply Azure Policy, RBAC, and tags to ALL of them and see them in the Azure portal alongside its Azure resources. What enables this?",
        "choices": ["Azure Resource Manager alone", "Azure Arc", "An ARM template", "Azure Cloud Shell"],
        "answer": 1,
        "explain": "Azure Arc extends the Azure management plane to resources outside Azure — on-prem servers, other clouds, Kubernetes, SQL Server — projecting them into ARM so Policy, RBAC, tags, and Monitor apply to them. ARM by itself only governs resources inside Azure.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST describes what happens when a server is connected to Azure Arc?",
        "choices": [
            "The workload is migrated into an Azure datacenter",
            "The server is converted into an Azure VM",
            "The server stays where it is but becomes manageable with Azure tools",
            "The server's operating system is replaced with Azure Stack",
        ],
        "answer": 2,
        "explain": "Arc moves the MANAGEMENT of a resource into Azure, not the resource itself — the server keeps running on-premises or in another cloud while being governed through the Azure portal like a native resource. Arc performs no migration or conversion.",
    },
    {
        "type": "mc",
        "q": "Which set of resource types can be managed through Azure Arc?",
        "choices": [
            "Only Azure virtual machines",
            "On-premises servers, Kubernetes clusters, SQL Server instances, and VMs in other clouds",
            "Only Microsoft 365 tenants",
            "Only resources deployed with Bicep",
        ],
        "answer": 1,
        "explain": "Arc-enabled resources include physical and virtual servers on-premises, Kubernetes clusters anywhere, SQL Server instances, and virtual machines hosted in other public clouds such as AWS or GCP. Native Azure VMs do not need Arc — ARM already manages them.",
    },
    {
        "type": "mc",
        "q": "A team's dev, test, and prod environments keep diverging because engineers build each one manually in the portal. Which practice directly solves this?",
        "choices": [
            "Granting fewer portal permissions",
            "Defining the environments as infrastructure as code and deploying from those files",
            "Switching from the CLI to PowerShell",
            "Connecting the environments to Azure Arc",
        ],
        "answer": 1,
        "explain": "Infrastructure as code describes environments declaratively in files, so every deployment from the same file produces the same result — eliminating the configuration drift caused by manual clicks. Changing CLI dialects or adding Arc does nothing to make deployments repeatable.",
    },
    {
        "type": "mc",
        "q": "Which of the following is an example of a DECLARATIVE approach to deploying Azure infrastructure?",
        "choices": [
            "A bash script that runs twelve az commands in sequence",
            "An administrator clicking through the portal's VM wizard",
            "A Bicep file describing the desired resources and their properties",
            "A PowerShell script that loops through New-AzVM calls",
        ],
        "answer": 2,
        "explain": "Declarative IaC states the desired end state and lets the platform work out the steps — that is exactly what Bicep and ARM templates do. Scripts of CLI or PowerShell commands are imperative (they list the 'how'), and portal clicks are manual, not code at all.",
    },
    {
        "type": "mc",
        "q": "Which of the following is NOT a benefit of managing infrastructure as code?",
        "choices": [
            "Deployments are repeatable and consistent across environments",
            "Definitions can be version-controlled and peer-reviewed",
            "Configuration drift can be avoided by redeploying from the definition",
            "Resources no longer require authentication to deploy",
        ],
        "answer": 3,
        "explain": "IaC delivers repeatability, consistency, versioning, review, and drift avoidance — but every deployment request is still authenticated and authorized by Azure Resource Manager regardless of how it is submitted. IaC changes how you define infrastructure, not Azure's security model.",
    },
    {
        "type": "mc",
        "q": "One admin creates a storage account in the portal; another creates one with the Azure CLI; a CI pipeline creates one via the REST API. Which single Azure component handled ALL three requests?",
        "choices": ["Azure Arc", "Azure Cloud Shell", "Azure Resource Manager", "The Azure mobile app"],
        "answer": 2,
        "explain": "Azure Resource Manager is the deployment and management layer that every request passes through, no matter which tool submitted it — portal, CLI, PowerShell, REST APIs, or SDKs. That single entry point is why all the tools deliver consistent capabilities and results.",
    },
    {
        "type": "mc",
        "q": "When Azure Resource Manager receives a request to create a resource, what does it do FIRST, before the resource is created?",
        "choices": [
            "Authenticates and authorizes the request",
            "Transpiles the request into Bicep",
            "Creates a customizable dashboard",
            "Copies the resource to another region",
        ],
        "answer": 0,
        "explain": "ARM first authenticates and authorizes every request, then routes it to the appropriate Azure service (resource provider) to perform the action. Transpilation is what happens to Bicep files, and dashboards belong to the portal — neither is part of ARM's request handling.",
    },
    {
        "type": "mc",
        "q": "Which capability is enabled BECAUSE all Azure management requests flow through Azure Resource Manager?",
        "choices": [
            "Applying access control, tags, and locks consistently across all services and tools",
            "Running bash scripts without authentication",
            "Hosting on-premises servers inside Azure datacenters",
            "Editing JSON templates directly in the mobile app",
        ],
        "answer": 0,
        "explain": "Because ARM is the single management layer, platform features like RBAC, organizing tags, resource locks, and group-based management apply uniformly whatever tool you use. The other options are either false (unauthenticated scripts) or unrelated to ARM's role.",
    },
    {
        "type": "mc",
        "q": "A deployment engineer accidentally runs the same ARM template against the same resource group twice. What happens, and why?",
        "choices": [
            "Duplicate copies of every resource are created",
            "The second run fails because the resources already exist",
            "The environment ends up in the same defined state, because template deployments are idempotent",
            "The first deployment is deleted and rebuilt from scratch",
        ],
        "answer": 2,
        "explain": "ARM template (and Bicep) deployments are idempotent: deploying the same declarative definition repeatedly converges on the same end state, without duplicating or needlessly rebuilding resources that already match. This safety is a core advantage over imperative scripts, which can fail or duplicate on re-run.",
    },
    {
        "type": "mc",
        "q": "An ARM template defines a VM that depends on a virtual network and a storage account. Who determines the creation order, and how are independent resources handled?",
        "choices": [
            "The author must script the exact sequence of steps",
            "ARM orchestrates the dependencies and creates independent resources in parallel",
            "Resources are always created alphabetically",
            "Each resource must be placed in a separate template",
        ],
        "answer": 1,
        "explain": "With declarative templates, Azure Resource Manager works out the dependency graph — dependent resources wait, and resources with no interdependencies are created in parallel for faster deployments. Not having to hand-script ordering is a key benefit over imperative automation.",
    },
    {
        "type": "mc",
        "q": "What advantage does ARM template validation give you before a deployment starts?",
        "choices": [
            "It encrypts the template contents",
            "A broken template fails up front, before a half-completed deployment touches any resources",
            "It converts the JSON into Bicep automatically",
            "It grants the deploying user Owner rights temporarily",
        ],
        "answer": 1,
        "explain": "ARM validates the template before beginning deployment, so errors surface before anything is created — avoiding half-finished environments. Validation is a correctness check, not encryption, format conversion, or a permissions change.",
    },
    {
        "type": "mc",
        "q": "A team finds ARM template JSON verbose and hard to review, and wants a simpler authoring language WITHOUT losing any deployment capability. What should they adopt?",
        "choices": ["Bicep", "The Azure mobile app", "Azure Arc", "Imperative CLI scripts"],
        "answer": 0,
        "explain": "Bicep is a domain-specific language with cleaner declarative syntax and none of the JSON boilerplate; it transpiles to standard ARM template JSON, so the deployment engine, validation, and idempotency are identical. Switching to imperative scripts would sacrifice the declarative benefits they already rely on.",
    },
    {
        "type": "mc",
        "q": "Microsoft releases a brand-new Azure resource type today. What is true about defining it in Bicep?",
        "choices": [
            "You must wait for the next Bicep release to add support",
            "Bicep supports all resource types and API versions immediately upon release",
            "Only ARM template JSON can deploy new resource types",
            "New types require the Azure portal for the first deployment",
        ],
        "answer": 1,
        "explain": "Bicep supports all Azure resource types and API versions the day they ship — there is no lag waiting for language updates, because Bicep compiles straight to ARM template JSON. That day-one coverage is one of its selling points over some third-party IaC tools.",
    },
    {
        "type": "mc",
        "q": "Which statement correctly distinguishes Azure Resource Manager from an ARM template?",
        "choices": [
            "ARM is a JSON file; the template is the management service",
            "ARM is the management layer every request passes through; an ARM template is a declarative JSON file describing what to deploy",
            "They are two names for the same downloadable tool",
            "ARM handles only portal requests; templates handle only CLI requests",
        ],
        "answer": 1,
        "explain": "'ARM' the service is Azure's deployment and management layer that authenticates, authorizes, and routes every request from every tool; an 'ARM template' is a file — declarative JSON handed to that service. The exam loves this service-vs-file ambiguity, so read for context.",
    },
    {
        "type": "mc",
        "q": "Which statement correctly contrasts Azure Arc with Azure Resource Manager?",
        "choices": [
            "Arc replaces ARM for all Azure-native resources",
            "ARM manages resources inside Azure; Arc projects outside resources into ARM so they can be governed the same way",
            "Arc is the JSON format that ARM deploys",
            "ARM works only on-premises while Arc works only in Azure",
        ],
        "answer": 1,
        "explain": "ARM is the management layer for everything inside Azure; Azure Arc extends that same management plane outward by projecting on-premises and other-cloud resources into ARM. Arc builds on ARM rather than replacing it, and neither is a file format.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Azure PowerShell can only be installed and run on Windows operating systems.",
        "answer": False,
        "explain": "Azure PowerShell runs on Windows, Linux, and macOS, just like the Azure CLI — both official tools are cross-platform. Don't let the 'PowerShell = Windows' instinct trick you; the choice between the tools comes down to preferred scripting language, not operating system.",
    },
    {
        "type": "tf",
        "q": "True or False: Before using Azure Cloud Shell, you must install the Azure CLI on your local computer and sign in separately.",
        "answer": False,
        "explain": "Cloud Shell runs entirely in the browser from the Azure portal — no local installation of any kind — and it is automatically authenticated as the signed-in Azure user. Zero setup and built-in authentication are precisely its selling points.",
    },
    {
        "type": "tf",
        "q": "True or False: A Bicep file is converted (transpiled) into standard ARM template JSON when it is deployed.",
        "answer": True,
        "explain": "Bicep is a friendlier authoring layer on top of ARM templates: at deployment time the Bicep file transpiles to ARM template JSON, which Azure Resource Manager then processes. That is why Bicep inherits ARM's validation, idempotency, and dependency orchestration unchanged.",
    },
    {
        "type": "tf",
        "q": "True or False: Connecting an on-premises server to Azure Arc migrates that server's workload into an Azure datacenter.",
        "answer": False,
        "explain": "Arc extends Azure's MANAGEMENT plane to the server — Policy, RBAC, tags, Monitor — while the workload keeps running exactly where it is, on-premises or in another cloud. Arc is about governance from a single pane of glass, not migration.",
    },
    {
        "type": "tf",
        "q": "True or False: A request made through an Azure SDK bypasses Azure Resource Manager and goes directly to the target service.",
        "answer": False,
        "explain": "Every management request — portal, Azure CLI, Azure PowerShell, REST APIs, and SDKs — passes through Azure Resource Manager, which authenticates and authorizes it before routing it to the service. No supported tool bypasses ARM; that single layer is what keeps tooling consistent.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Azure CLI commands all begin with the two-letter prefix ______. (type it)",
        "answers": ["az"],
        "explain": "Azure CLI commands are bash-style and start with 'az', as in 'az vm create' or 'az group list'. Azure PowerShell instead uses Verb-Noun cmdlets from the Az module, such as New-AzVM.",
    },
    {
        "type": "fill",
        "q": "The Azure service that lets you govern on-premises servers and VMs in other clouds with Azure Policy, RBAC, and tags is Azure ______. (type your answer)",
        "answers": ["arc", "azure arc"],
        "explain": "Azure Arc extends the Azure management plane to resources outside Azure — on-prem servers, Kubernetes clusters, SQL Server, and other-cloud VMs — giving a single pane of glass for hybrid and multicloud governance.",
    },
    {
        "type": "fill",
        "q": "The deployment and management layer through which EVERY Azure request passes — from the portal, CLI, PowerShell, REST, or SDKs — is Azure ______ ______. (type its name or acronym)",
        "answers": ["resource manager", "arm", "azure resource manager"],
        "explain": "Azure Resource Manager (ARM) authenticates and authorizes each request and routes it to the appropriate service, which is why every tool offers consistent capabilities and why RBAC, tags, and locks apply platform-wide.",
    },
    {
        "type": "fill",
        "q": "The domain-specific language that offers simpler declarative syntax than ARM template JSON and transpiles to it at deployment is called ______. (type your answer)",
        "answers": ["bicep", "azure bicep"],
        "explain": "Bicep removes the JSON boilerplate while keeping full ARM capability: it compiles to standard ARM template JSON and supports every resource type and API version immediately on release.",
    },
    {
        "type": "fill",
        "q": "Managing infrastructure by defining it declaratively in versionable files rather than manual steps is known as infrastructure as ______. (type the word or the acronym)",
        "answers": ["code", "iac", "infrastructure as code"],
        "explain": "Infrastructure as code (IaC) makes deployments repeatable, consistent, reviewable, and version-controlled, and rebuilding environments from the definition prevents configuration drift. ARM templates and Bicep are Azure's native IaC formats.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each management tool to its description.",
        "pairs": [
            ["Azure portal", "Web-based GUI with customizable dashboards; no scripting needed"],
            ["Azure mobile app", "Monitor resources and take quick actions from a phone"],
            ["Azure Cloud Shell", "Browser-based shell in the portal; no install, auto-authenticated"],
            ["Azure CLI", "Bash-style commands beginning with 'az'"],
            ["Azure PowerShell", "Verb-Noun cmdlets from the Az module"],
        ],
        "explain": "The portal is the graphical experience and the mobile app its on-the-go companion; Cloud Shell is the zero-install hosted command line that contains both the Azure CLI (bash-style 'az') and Azure PowerShell (Az-module cmdlets).",
    },
    {
        "type": "match",
        "q": "Match each deployment/governance concept to its description.",
        "pairs": [
            ["Azure Arc", "Extends Azure governance to on-prem and other-cloud resources"],
            ["Infrastructure as code", "Repeatable, versionable deployments defined in files"],
            ["Azure Resource Manager", "Authenticates, authorizes, and routes every management request"],
            ["ARM template", "Declarative JSON file defining resources to deploy"],
            ["Bicep", "Simpler DSL that transpiles to ARM template JSON"],
        ],
        "explain": "ARM is the layer every request crosses; ARM templates and Bicep are the declarative files it deploys (Bicep compiling down to template JSON); IaC is the practice they implement; and Arc stretches that same management plane beyond Azure's borders.",
    },
    {
        "type": "match",
        "q": "Match each infrastructure-as-code property to its meaning.",
        "pairs": [
            ["Declarative", "Describe the desired end state; the platform determines the steps"],
            ["Imperative", "List the exact commands to run, in order"],
            ["Idempotent", "Re-running the same deployment yields the same resulting environment"],
            ["Configuration drift", "Environments silently diverging from their intended state via manual changes"],
        ],
        "explain": "Declarative definitions state 'what', imperative scripts state 'how'. Idempotence is why re-deploying an ARM template or Bicep file is safe, and redeploying from those definitions is the antidote to configuration drift.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the journey of a 'create VM' request submitted with the Azure CLI, from first to last.",
        "items": [
            "Admin runs 'az vm create' in Azure Cloud Shell",
            "The request arrives at Azure Resource Manager",
            "ARM authenticates and authorizes the request",
            "ARM routes the request to the appropriate resource provider",
            "The Azure service creates the virtual machine",
        ],
        "explain": "Whatever the tool — CLI, portal, PowerShell, REST, or SDK — the request first reaches Azure Resource Manager, which authenticates and authorizes it, then hands it to the responsible Azure service (resource provider) to perform the action. This single pipeline is what makes all the tools consistent.",
    },
    {
        "type": "order",
        "q": "Arrange the lifecycle of a Bicep deployment, from first to last.",
        "items": [
            "Engineer authors a Bicep file describing the desired resources",
            "The Bicep file is transpiled to ARM template JSON",
            "ARM validates the template before touching any resources",
            "ARM orders dependencies and deploys resources, in parallel where possible",
            "The environment matches the declared end state (idempotent result)",
        ],
        "explain": "Bicep is authored first, then transpiled to standard ARM template JSON. ARM validates the template up front, orchestrates the dependency graph during deployment, and converges the environment on the declared state — re-running produces the same result because the process is idempotent.",
    },
]
