TOPIC = {
    "id": "3.4",
    "domain": 3,
    "title": "Describe monitoring tools in Azure.",
    "short": "Monitoring Tools",
}

TERMS = [
    ("Azure Advisor", "Free service that analyzes your deployed resources and gives personalized, actionable best-practice recommendations in five categories"),
    ("Advisor's five categories", "Reliability, Security, Performance, Operational Excellence, and Cost — the areas Azure Advisor recommendations cover"),
    ("Azure Service Health", "Service reporting the health of the Azure platform itself as it affects you: outages, planned maintenance, and health advisories"),
    ("Azure Status", "Public web page showing service-wide outages across all Azure services and regions, for everyone — the global view"),
    ("Service Health (personalized view)", "View scoped to YOUR services and regions: service issues, planned maintenance, and health advisories that affect what you actually use"),
    ("Resource Health", "View showing the current and historical health of one individual resource — e.g., whether a VM's downtime was caused by an Azure platform issue"),
    ("Service Health alert", "Notification you configure so you are told when an Azure service issue, planned maintenance, or advisory affects your services or regions"),
    ("Root cause analysis (RCA)", "Microsoft's post-incident explanation of an Azure outage, stored in Service Health for later review and sharing"),
    ("Azure Monitor", "Umbrella platform that collects, stores, analyzes, visualizes, and acts on metrics and logs from applications, OS, resources, subscription, and tenant — plus on-premises and other clouds"),
    ("Metrics", "Numeric time-series values (e.g., CPU percentage) collected by Azure Monitor into its metrics store"),
    ("Logs", "Records and events collected by Azure Monitor into its log store, queryable through Log Analytics"),
    ("Log Analytics", "The Azure Monitor tool where you write and run queries against collected log data, from simple filtering to advanced multi-table queries"),
    ("Log Analytics workspace", "The container that stores Azure Monitor log data and against which Log Analytics queries run"),
    ("Kusto Query Language (KQL)", "The query language used in Log Analytics to sort, filter, and analyze Azure Monitor log data"),
    ("Azure Monitor alerts", "Automated notifications that fire when a metric or log threshold is crossed, triggering an action group"),
    ("Metric alert", "Azure Monitor alert type that watches numeric values — e.g., fire when VM CPU exceeds 80%"),
    ("Log alert", "Azure Monitor alert type that fires based on the results of a log query rather than a numeric metric"),
    ("Action group", "The alert component defining WHO is notified (email/SMS/push/voice) and WHAT runs automatically (webhook, function, runbook) when an alert fires"),
    ("Application Insights", "Azure Monitor's application performance management (APM) feature — instruments apps via agent or SDK to track requests, response times, failure rates, and dependencies"),
    ("Availability test", "Application Insights capability that sends synthetic requests to probe whether an application is up, even during periods with no real user traffic"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A finance manager asks which Azure resources are underutilized and how to reduce the monthly bill. Which free tool provides personalized recommendations such as resizing or shutting down idle VMs?",
        "choices": ["Azure Monitor", "Azure Advisor", "Azure Service Health", "Log Analytics"],
        "answer": 1,
        "explain": "Azure Advisor analyzes your deployed resources and offers free, personalized best-practice recommendations, including Cost recommendations like eliminating underutilized VMs or buying reserved instances. Monitor collects telemetry, Service Health reports platform incidents, and Log Analytics queries log data — none of them recommend savings.",
    },
    {
        "type": "mc",
        "q": "Which of the following is NOT one of Azure Advisor's five recommendation categories?",
        "choices": ["Reliability", "Operational Excellence", "Scalability", "Cost"],
        "answer": 2,
        "explain": "Advisor's five categories are Reliability, Security, Performance, Operational Excellence, and Cost. 'Scalability' sounds plausible but is not a category — the exam loves slipping a fake category into the list, so memorize the real five.",
    },
    {
        "type": "mc",
        "q": "An Azure Advisor recommendation suggests enabling backup on production virtual machines to ensure business continuity. Which Advisor category does this fall under?",
        "choices": ["Cost", "Performance", "Operational Excellence", "Reliability"],
        "answer": 3,
        "explain": "Reliability recommendations are about ensuring the continuity of business-critical applications — backups and redundancy are classic examples. Cost is about spend, Performance about speed, and Operational Excellence about process, workflow, and manageability improvements.",
    },
    {
        "type": "mc",
        "q": "A cloud governance lead wants new Advisor recommendations delivered to the right team automatically instead of requiring someone to check the portal. What should be configured?",
        "choices": [
            "Advisor alerts and periodic digests",
            "A Resource Health check",
            "An Application Insights availability test",
            "A Log Analytics workspace",
        ],
        "answer": 0,
        "explain": "Advisor recommendations are actionable in the portal (act, postpone, or dismiss), and they can also be set up as alerts and periodic digests so new findings are pushed to stakeholders automatically. Resource Health, availability tests, and Log Analytics workspaces are monitoring constructs — they don't deliver Advisor recommendations.",
    },
    {
        "type": "mc",
        "q": "Your application went down and you suspect the problem is on Microsoft's side. Which tool reports service outages, planned maintenance, and health advisories for the Azure platform as they affect YOUR services and regions?",
        "choices": ["Azure Advisor", "Application Insights", "Azure Service Health", "Azure Monitor alerts"],
        "answer": 2,
        "explain": "Azure Service Health is the tool for the health of Azure itself as it affects you — incidents, planned maintenance, and advisories scoped to the services and regions you use. Advisor recommends improvements, Application Insights watches your app's performance, and Monitor alerts react to thresholds on your own telemetry.",
    },
    {
        "type": "mc",
        "q": "A journalist (with no Azure subscription) wants to check whether Azure is experiencing a global outage right now. Where can they look?",
        "choices": [
            "Resource Health in the portal",
            "The Azure Status public web page",
            "A Log Analytics workspace",
            "Azure Advisor's Reliability tab",
        ],
        "answer": 1,
        "explain": "Azure Status is a public web page showing service-wide outages across all of Azure — no subscription or sign-in required. Resource Health and Log Analytics require access to your resources, and Advisor gives recommendations, not outage status.",
    },
    {
        "type": "mc",
        "q": "A single production VM was unavailable for 40 minutes last night. The admin needs to determine whether the downtime was caused by an Azure platform issue or by something in the VM itself. Which view should be checked?",
        "choices": ["Azure Status", "Service Health's planned maintenance list", "Resource Health", "Azure Advisor"],
        "answer": 2,
        "explain": "Resource Health reports the current and historical health of an individual resource and indicates whether problems were platform-caused — exactly the 'was it Azure or was it me?' question. Azure Status is global, planned maintenance is about future work, and Advisor makes recommendations.",
    },
    {
        "type": "mc",
        "q": "Which statement correctly orders the three Azure Service Health views from BROADEST scope to NARROWEST?",
        "choices": [
            "Resource Health, Service Health, Azure Status",
            "Azure Status, Service Health, Resource Health",
            "Service Health, Azure Status, Resource Health",
            "Azure Status, Resource Health, Service Health",
        ],
        "answer": 1,
        "explain": "Azure Status covers all of Azure globally (public page), Service Health narrows to the services and regions you use, and Resource Health zooms all the way in to one individual resource. Think of it as three zoom levels of the same lens.",
    },
    {
        "type": "mc",
        "q": "After a regional Azure incident is resolved, where can an organization find Microsoft's root cause analysis (RCA) to review and share internally?",
        "choices": ["Azure Service Health", "Azure Advisor", "Application Insights", "An action group"],
        "answer": 0,
        "explain": "Service Health stores incident RCAs after outages are resolved, so teams can review what happened and share the explanation. Advisor recommends best practices, Application Insights is APM, and action groups define alert notifications — none of them archive incident RCAs.",
    },
    {
        "type": "mc",
        "q": "An operations team wants to be notified automatically whenever planned maintenance is scheduled for the Azure services and regions they use. What should they set up?",
        "choices": [
            "A metric alert on CPU percentage",
            "A Service Health alert",
            "An Advisor cost digest",
            "A KQL query in Log Analytics",
        ],
        "answer": 1,
        "explain": "Service Health alerts notify you when service issues, planned maintenance, or health advisories affect your services and regions. Metric alerts watch your own telemetry thresholds, Advisor digests deliver recommendations, and a KQL query only returns data when you run it.",
    },
    {
        "type": "mc",
        "q": "Which service is BEST described as the umbrella platform for collecting, analyzing, visualizing, and acting on metrics and log data from your entire environment?",
        "choices": ["Azure Service Health", "Azure Advisor", "Microsoft Entra ID", "Azure Monitor"],
        "answer": 3,
        "explain": "Azure Monitor is the platform that gathers metrics and logs from every layer and feeds them to insights, visualizations, analysis tools, and automated actions. Service Health covers platform incidents, Advisor covers recommendations, and Microsoft Entra ID (formerly Azure Active Directory) is identity, not monitoring.",
    },
    {
        "type": "mc",
        "q": "A company runs workloads in Azure, in AWS, and in its own datacenter, and wants ONE platform to collect metrics and logs from all of them. Which Azure service can do this?",
        "choices": ["Azure Monitor", "Resource Health", "Azure Status", "Azure Advisor"],
        "answer": 0,
        "explain": "Azure Monitor is not limited to Azure — it can collect telemetry from on-premises servers and resources in other clouds as well, providing full-stack visibility in one place. Resource Health and Azure Status only report on Azure platform health, and Advisor only analyzes your Azure deployments.",
    },
    {
        "type": "mc",
        "q": "From which layers can Azure Monitor collect data?",
        "choices": [
            "Only from Azure PaaS services",
            "Only from virtual machine guest operating systems",
            "From the application, guest OS, Azure resources, subscription, and tenant layers",
            "Only from resources inside a single resource group",
        ],
        "answer": 2,
        "explain": "Azure Monitor collects telemetry from every layer: the application, the OS the app runs on, the Azure resources it depends on, the subscription, and the tenant — plus on-premises and multicloud sources. That full-stack reach is what makes it the umbrella monitoring platform.",
    },
    {
        "type": "mc",
        "q": "Into which two data stores does Azure Monitor route the telemetry it collects?",
        "choices": [
            "Blobs and queues",
            "Metrics and logs",
            "Snapshots and archives",
            "Events and traces only",
        ],
        "answer": 1,
        "explain": "Azure Monitor funnels everything into a metrics store (numeric time-series values) and a logs store (records and events). From those two stores the data flows onward to insights, visualizations, analysis tools like Log Analytics, and actions like alerts and autoscale.",
    },
    {
        "type": "mc",
        "q": "A DevOps engineer must search several weeks of collected VM event logs for a recurring error, sorting and filtering records with a query language. Which tool should be used?",
        "choices": ["Azure Advisor", "Resource Health", "Azure Status", "Log Analytics"],
        "answer": 3,
        "explain": "Log Analytics is the Azure Monitor tool where you write and run queries — from simple sorting and filtering up to advanced queries — against collected log data using Kusto Query Language (KQL). Advisor, Resource Health, and Azure Status have no query capability.",
    },
    {
        "type": "mc",
        "q": "Which language is used to write queries in Log Analytics?",
        "choices": ["SQL Server T-SQL", "Kusto Query Language (KQL)", "PowerShell DSC", "GraphQL"],
        "answer": 1,
        "explain": "Log Analytics queries are written in Kusto Query Language (KQL), which supports everything from quick filters to complex multi-table analysis whose results can be charted or pinned to dashboards. T-SQL, DSC, and GraphQL are real technologies but not the Log Analytics query language.",
    },
    {
        "type": "mc",
        "q": "An admin wants an email and an SMS sent to the on-call engineer whenever a database VM's CPU utilization exceeds 80%. Which capability provides this?",
        "choices": [
            "Azure Monitor alerts with an action group",
            "Azure Advisor's Performance category",
            "Resource Health",
            "An Application Insights availability test",
        ],
        "answer": 0,
        "explain": "A metric alert in Azure Monitor fires when the CPU threshold is crossed, and its action group defines the notifications (email/SMS) and any automated response. Advisor gives best-practice recommendations rather than threshold notifications, Resource Health reports platform-caused issues, and availability tests probe web apps.",
    },
    {
        "type": "mc",
        "q": "In Azure Monitor, what does an ACTION GROUP define?",
        "choices": [
            "The KQL query an alert rule evaluates",
            "The resource group where alerts are stored",
            "Who is notified and what automated actions run when an alert fires",
            "The five categories of Advisor recommendations",
        ],
        "answer": 2,
        "explain": "An action group is the reusable bundle of notification preferences (email, SMS, push, voice) and automated actions (webhooks, Azure Functions, runbooks) triggered when an alert fires. The alert rule holds the condition; the action group holds the response.",
    },
    {
        "type": "mc",
        "q": "Which pair correctly describes the two main kinds of Azure Monitor alerts?",
        "choices": [
            "Status alerts and advisory alerts",
            "Metric alerts and log alerts",
            "Push alerts and pull alerts",
            "Regional alerts and global alerts",
        ],
        "answer": 1,
        "explain": "Metric alerts evaluate numeric time-series values (like CPU percentage) against thresholds, while log alerts fire based on the results of a log query. Both hand off to action groups for notification and automated response.",
    },
    {
        "type": "mc",
        "q": "A web team needs per-request telemetry for their production application: response times, failure rates, and the performance of external dependencies. Which Azure Monitor feature provides this?",
        "choices": ["Log Analytics", "Azure Service Health", "Application Insights", "Azure Advisor"],
        "answer": 2,
        "explain": "Application Insights is Azure Monitor's application performance management (APM) feature, tracking requests, response times, failure rates, dependency performance, and page views from inside the app. Log Analytics queries collected logs generally, Service Health covers platform incidents, and Advisor makes recommendations.",
    },
    {
        "type": "mc",
        "q": "How does Application Insights collect telemetry from an application?",
        "choices": [
            "By reading the Azure Status page",
            "By instrumenting the application with an agent or SDK",
            "By scanning the subscription's activity log",
            "It works automatically on any app with no configuration",
        ],
        "answer": 1,
        "explain": "Application Insights requires instrumentation: you either install an agent or add the SDK to the application code, which then streams telemetry to Azure. Because instrumentation (not hosting) is the hook, the app can run in Azure, on-premises, or in another cloud.",
    },
    {
        "type": "mc",
        "q": "An online store gets almost no traffic between 2 a.m. and 5 a.m., but the team still wants to know immediately if the site goes down during those hours. Which capability fits?",
        "choices": [
            "Application Insights availability tests (synthetic probes)",
            "Azure Advisor's Operational Excellence category",
            "A Service Health planned-maintenance alert",
            "Resource Health history",
        ],
        "answer": 0,
        "explain": "Application Insights can probe an application's availability by sending synthetic requests on a schedule, so outages are detected even when no real users are active. Advisor recommends practices, Service Health alerts cover Azure platform events, and Resource Health explains past resource issues rather than actively probing an app.",
    },
    {
        "type": "mc",
        "q": "Which scenario calls for Azure SERVICE HEALTH rather than Azure Monitor?",
        "choices": [
            "Charting a VM's memory usage over the last week",
            "Finding out whether a Microsoft datacenter incident in your region caused last night's downtime",
            "Querying application logs for failed sign-ins",
            "Emailing the team when disk space drops below 10%",
        ],
        "answer": 1,
        "explain": "Service Health covers the health of the Azure platform itself — incidents, planned maintenance, advisories — as it affects you. Charting metrics, querying logs, and threshold-based emails are all about YOUR resources' telemetry, which is Azure Monitor territory.",
    },
    {
        "type": "mc",
        "q": "What is the key difference between an Azure Advisor recommendation and an Azure Monitor alert?",
        "choices": [
            "Advisor is a paid add-on; Monitor alerts are free",
            "Advisor reacts to thresholds you define; Monitor alerts offer best-practice suggestions",
            "Advisor proactively recommends best-practice improvements; Monitor alerts fire when a condition you defined is met",
            "There is no difference — they are two names for the same feature",
        ],
        "answer": 2,
        "explain": "Advisor is proactive guidance: it compares your deployment against best practices and recommends improvements, with no thresholds involved. Monitor alerts are reactive: they fire when a metric or log condition you configured is crossed. Choice B reverses the two, and Advisor is free, not paid.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: Azure Advisor is a free service — you do not pay extra to receive its recommendations.",
        "answer": True,
        "explain": "Advisor is included at no additional cost with your subscription; it continuously analyzes your resources and surfaces recommendations across its five categories. Acting on some recommendations may change your spend, but the recommendations themselves are free.",
    },
    {
        "type": "tf",
        "q": "True or False: Application Insights can only monitor applications that are hosted inside Azure.",
        "answer": False,
        "explain": "Because Application Insights hooks into the application through an agent or SDK, it can monitor apps running in Azure, on-premises, or in other clouds. The instrumentation, not the hosting location, is what connects the app to the service.",
    },
    {
        "type": "tf",
        "q": "True or False: The Azure Status page requires an Azure subscription and shows only the resources you own.",
        "answer": False,
        "explain": "Azure Status is a public web page showing service-wide outages across all of Azure — anyone can view it without signing in. The personalized, subscription-scoped experience is the Service Health view; the single-resource view is Resource Health.",
    },
    {
        "type": "tf",
        "q": "True or False: Log Analytics is the Azure Monitor tool where you write and run queries against collected log data.",
        "answer": True,
        "explain": "Log Analytics is exactly that: the portal tool for writing and running KQL queries — from simple sorts and filters to advanced multi-table analysis — against the log data Azure Monitor has gathered into a workspace.",
    },
    {
        "type": "tf",
        "q": "True or False: The personalized Service Health view shows only active outages — it does not cover upcoming planned maintenance.",
        "answer": False,
        "explain": "Service Health covers three kinds of events for your services and regions: service issues (active incidents), planned maintenance (upcoming work), and health advisories. Planned maintenance visibility is one of its headline features, and you can be alerted about it in advance.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The free Azure service that provides personalized best-practice recommendations across Reliability, Security, Performance, Operational Excellence, and Cost is Azure ______. (type your answer)",
        "answers": ["advisor", "azure advisor"],
        "explain": "Azure Advisor is the built-in, no-cost consultant that analyzes your deployed resources and recommends improvements in those five categories, actionable directly in the portal or deliverable as alerts and digests.",
    },
    {
        "type": "fill",
        "q": "Log Analytics queries are written in the ______ query language. (type the name or acronym)",
        "answers": ["kusto", "kql", "kusto query language"],
        "explain": "Kusto Query Language (KQL) is the language of Log Analytics, scaling from simple sorting and filtering of records up to advanced queries whose results can be visualized on dashboards.",
    },
    {
        "type": "fill",
        "q": "The Azure Service Health view that reports whether an INDIVIDUAL resource, such as a single VM, is healthy or was affected by a platform issue is ______ Health. (type one word)",
        "answers": ["resource", "resource health", "azure resource health"],
        "explain": "Resource Health is the narrowest of the three Service Health views: it tracks one specific resource's current and past health, answering 'was my VM's downtime Azure's fault or mine?' Azure Status is global and Service Health is scoped to your services and regions.",
    },
    {
        "type": "fill",
        "q": "When an Azure Monitor alert fires, the set of notifications and automated responses that run is defined by an ______ group. (type one word)",
        "answers": ["action", "action group", "actions"],
        "explain": "Action groups are the reusable response bundles attached to alert rules: they list who gets email/SMS/push/voice notifications and which webhooks, functions, or runbooks execute automatically when the alert fires.",
    },
    {
        "type": "fill",
        "q": "The application performance management (APM) feature of Azure Monitor that tracks request rates, response times, and failure rates is Application ______. (type your answer)",
        "answers": ["insights", "application insights", "app insights"],
        "explain": "Application Insights instruments an application via agent or SDK to monitor it from the inside — requests, response times, failure rates, dependency performance, page views — and can even probe availability with synthetic requests during quiet periods.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each Azure monitoring tool to its job.",
        "pairs": [
            ["Azure Advisor", "Free personalized best-practice recommendations in five categories"],
            ["Azure Service Health", "Reports Azure platform outages, planned maintenance, and advisories affecting you"],
            ["Log Analytics", "Write and run KQL queries against collected log data"],
            ["Azure Monitor alerts", "Notify people and trigger actions when a threshold is crossed"],
            ["Application Insights", "Monitor application requests, response times, and failure rates (APM)"],
        ],
        "explain": "This is the core tool-picker map for objective 3.4: Advisor recommends, Service Health reports on Azure itself, and Azure Monitor's features divide the telemetry work — Log Analytics queries, alerts notify, Application Insights watches the app.",
    },
    {
        "type": "match",
        "q": "Match each Azure Advisor category to an example recommendation.",
        "pairs": [
            ["Reliability", "Enable VM backup to ensure business continuity"],
            ["Security", "Remediate a configuration gap that could lead to a breach"],
            ["Performance", "Upgrade an undersized SKU to speed up an application"],
            ["Operational Excellence", "Improve deployment practices and resource manageability"],
            ["Cost", "Shut down or resize an underutilized virtual machine"],
        ],
        "explain": "Advisor's five categories each have a signature flavor: Reliability = continuity and redundancy, Security = threat and configuration gaps, Performance = speed, Operational Excellence = process and manageability, Cost = spend reduction. Being able to sort examples into categories is a common exam ask.",
    },
    {
        "type": "match",
        "q": "Match each Azure Service Health capability to its description.",
        "pairs": [
            ["Azure Status", "Public page showing global outages across all of Azure"],
            ["Service Health view", "Issues, planned maintenance, and advisories scoped to your services and regions"],
            ["Resource Health", "Health of one individual resource, including platform-caused downtime"],
            ["Service Health alerts", "Notifications when a platform event affects your services or regions"],
        ],
        "explain": "Think zoom levels plus a notifier: Azure Status is the widest (public, global), the Service Health view narrows to what you use, Resource Health narrows to a single resource, and Service Health alerts push those platform events to you instead of waiting to be checked.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the flow of an Azure Monitor metric alert, from first to last.",
        "items": [
            "Azure Monitor collects the CPU metric from the virtual machine",
            "The metric value crosses the 80% threshold defined in the alert rule",
            "The alert rule fires",
            "The attached action group is triggered",
            "Email/SMS notifications go out and a runbook runs automatically",
        ],
        "explain": "The pipeline is collect, evaluate, fire, respond: Monitor gathers the metric into its store, the alert rule evaluates it against the threshold, firing hands off to the action group, and the action group performs the configured notifications and automated actions.",
    },
]
