TOPIC = {
    "id": "1.1",
    "domain": 1,
    "title": "Explain concepts related to the Open Systems Interconnection (OSI) reference model.",
    "short": "OSI Model",
}

TERMS = [
    ("Physical layer (Layer 1)", "Transmits raw bits over media; defines cables, connectors, voltages, radio; devices: hubs, repeaters, media converters, transceivers"),
    ("Data link layer (Layer 2)", "Node-to-node delivery of frames on the local segment using MAC addresses; devices: switches, bridges, NICs, APs; adds FCS trailer"),
    ("Network layer (Layer 3)", "Routes packets between networks using logical IP addresses; devices: routers, Layer 3 switches; protocols: IP, ICMP, OSPF, BGP"),
    ("Transport layer (Layer 4)", "End-to-end delivery using port numbers; TCP (reliable segments) and UDP (connectionless datagrams); segmentation, flow control"),
    ("Session layer (Layer 5)", "Establishes, maintains, and terminates sessions (dialogs) between applications; examples: NetBIOS, RPC, SIP session control"),
    ("Presentation layer (Layer 6)", "Translates data formats between systems: encryption/decryption, compression, character encoding (ASCII/Unicode), JPEG/MPEG formats"),
    ("Application layer (Layer 7)", "Interface between network services and user applications; protocols: HTTP, DNS, SMTP, FTP, SSH, DHCP, SNMP"),
    ("Encapsulation", "Process of wrapping data with protocol headers as it moves down the OSI stack on the sending host; L2 also adds a trailer"),
    ("De-encapsulation", "Process of stripping headers at each layer as data moves up the stack on the receiving host"),
    ("Protocol data unit (PDU)", "The named unit of data at each layer: bits (L1), frames (L2), packets (L3), segments/datagrams (L4), data (L5-L7)"),
    ("Frame", "Layer 2 PDU containing source/destination MAC addresses, payload, and an FCS trailer for error detection"),
    ("Packet", "Layer 3 PDU containing source/destination IP addresses and a TTL field; routed hop by hop between networks"),
    ("Segment", "Layer 4 TCP PDU containing source/destination port numbers, sequence and acknowledgment numbers"),
    ("MAC address", "48-bit hardware address at Layer 2, written in hex (e.g., 00:1A:2B:3C:4D:5E); first 24 bits are the vendor OUI"),
    ("IP address", "Logical Layer 3 address (32-bit IPv4 or 128-bit IPv6) providing hierarchical end-to-end addressing across networks"),
    ("Port number", "16-bit Layer 4 identifier (0-65535) that directs traffic to the correct application/service; well-known ports are 0-1023"),
    ("Socket", "The combination of an IP address and a port number identifying one endpoint of a conversation (e.g., 192.168.1.10:443)"),
    ("MAC address table (CAM table)", "Table a switch builds by learning source MACs of incoming frames, used to forward frames only out the correct port"),
    ("Frame check sequence (FCS)", "CRC error-detection value in the Layer 2 trailer; receivers discard frames whose FCS does not match"),
    ("Broadcast domain", "Set of hosts that receive each other's broadcasts; bounded by routers (Layer 3), spans all switch ports in a VLAN"),
    ("Collision domain", "Network segment where transmissions can collide; each switch port is its own collision domain, a hub is one big one"),
    ("TCP/IP model", "Practical four-layer model: Application (OSI 5-7), Transport (OSI 4), Internet (OSI 3), Network Access (OSI 1-2)"),
    ("Logical Link Control (LLC)", "Upper sublayer of Layer 2 (802.2) that identifies the encapsulated Layer 3 protocol and provides flow-control hooks"),
    ("Media Access Control (MAC) sublayer", "Lower sublayer of Layer 2 handling physical addressing and media access methods such as CSMA/CD and CSMA/CA"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "Which OSI layer is responsible for routing packets between different networks using logical addressing?",
        "choices": ["Layer 2 - Data link", "Layer 3 - Network", "Layer 4 - Transport", "Layer 5 - Session"],
        "answer": 1,
        "explain": "The Network layer (Layer 3) uses logical IP addresses and routing tables to forward packets between networks. Routers are the classic Layer 3 device. Layer 2 delivers frames only within the local segment using MAC addresses.",
    },
    {
        "type": "mc",
        "q": "What is the PDU (protocol data unit) at Layer 2 of the OSI model?",
        "choices": ["Packet", "Segment", "Frame", "Bit"],
        "answer": 2,
        "explain": "Layer 2 encapsulates data into frames, which carry source and destination MAC addresses and an FCS trailer. Remember bottom-up: bits (L1), frames (L2), packets (L3), segments/datagrams (L4), data (L5-7).",
    },
    {
        "type": "mc",
        "q": "A standard (non-multilayer) network switch makes forwarding decisions based on which piece of information?",
        "choices": ["Destination IP address", "Destination port number", "TTL value", "Destination MAC address"],
        "answer": 3,
        "explain": "Switches are Layer 2 devices: they learn source MAC addresses into their CAM table and forward frames based on the destination MAC address. Routing by IP address is a Layer 3 function.",
    },
    {
        "type": "mc",
        "q": "TCP and UDP operate at which OSI layer?",
        "choices": ["Layer 3 - Network", "Layer 4 - Transport", "Layer 5 - Session", "Layer 7 - Application"],
        "answer": 1,
        "explain": "TCP and UDP are the two Transport layer (Layer 4) protocols. They provide end-to-end delivery between applications using port numbers — TCP reliably with a handshake, UDP connectionless with minimal overhead.",
    },
    {
        "type": "mc",
        "q": "Which OSI layer handles encryption, compression, and translation between character encodings such as ASCII and Unicode?",
        "choices": ["Layer 5 - Session", "Layer 7 - Application", "Layer 6 - Presentation", "Layer 4 - Transport"],
        "answer": 2,
        "explain": "The Presentation layer (Layer 6) is the network's translator: it formats/translates data, encrypts/decrypts (TLS is classically placed here on the exam), and compresses/decompresses so the receiving application can read the data.",
    },
    {
        "type": "mc",
        "q": "Which OSI layer establishes, maintains, and terminates the dialog between two communicating applications?",
        "choices": ["Layer 5 - Session", "Layer 4 - Transport", "Layer 6 - Presentation", "Layer 3 - Network"],
        "answer": 0,
        "explain": "The Session layer (Layer 5) manages the ongoing conversation (session) between applications — setup, maintenance/checkpointing, and teardown. NetBIOS and RPC are common Layer 5 examples.",
    },
    {
        "type": "mc",
        "q": "A hub that simply regenerates and repeats an electrical signal out all ports operates at which OSI layer?",
        "choices": ["Layer 3", "Layer 1", "Layer 2", "Layer 4"],
        "answer": 1,
        "explain": "Hubs and repeaters are Physical layer (Layer 1) devices — they work with raw bits and make no forwarding decisions. A switch, by contrast, reads MAC addresses and is a Layer 2 device.",
    },
    {
        "type": "mc",
        "q": "Which addressing is used at Layer 4 of the OSI model?",
        "choices": ["MAC addresses", "IP addresses", "Port numbers", "Hostnames"],
        "answer": 2,
        "explain": "Layer 4 uses 16-bit port numbers (0-65535) to identify which application or service the traffic belongs to. MAC addresses are Layer 2, IP addresses are Layer 3, and hostnames are resolved by DNS at Layer 7.",
    },
    {
        "type": "mc",
        "q": "During encapsulation on a sending host, in which order are headers added to application data?",
        "choices": [
            "IP header, then TCP header, then Ethernet header",
            "TCP header, then IP header, then Ethernet header",
            "Ethernet header, then IP header, then TCP header",
            "TCP header, then Ethernet header, then IP header",
        ],
        "answer": 1,
        "explain": "Data moves DOWN the stack: Layer 4 adds the TCP/UDP header (segment), Layer 3 adds the IP header (packet), then Layer 2 adds the Ethernet header and FCS trailer (frame). On the wire, the outermost header is therefore Ethernet, then IP, then TCP.",
    },
    {
        "type": "mc",
        "q": "A user can ping a web server by IP address, but browsing to the server by its name fails. At which OSI layer is the problem MOST likely located?",
        "choices": ["Layer 1", "Layer 3", "Layer 7", "Layer 2"],
        "answer": 2,
        "explain": "Ping succeeding proves Layers 1-3 are working end to end. Name resolution is performed by DNS, an Application layer (Layer 7) service, so the failure is most likely a DNS/Layer 7 issue.",
    },
    {
        "type": "mc",
        "q": "Which device separates broadcast domains?",
        "choices": ["Router", "Switch", "Hub", "Repeater"],
        "answer": 0,
        "explain": "Routers (Layer 3) do not forward broadcasts, so each router interface bounds a broadcast domain. Switches separate collision domains per port but forward broadcasts to all ports in the VLAN; hubs and repeaters separate nothing.",
    },
    {
        "type": "mc",
        "q": "In the TCP/IP model, which layer corresponds to the OSI Application, Presentation, and Session layers combined?",
        "choices": ["Internet", "Transport", "Network Access", "Application"],
        "answer": 3,
        "explain": "The four-layer TCP/IP model collapses OSI Layers 5, 6, and 7 into a single Application layer. Likewise, OSI Layers 1 and 2 combine into the Network Access (link) layer, OSI 3 maps to Internet, and OSI 4 maps to Transport.",
    },
    {
        "type": "mc",
        "q": "Which of the following is a valid MAC address?",
        "choices": ["192.168.10.45", "00:1B:44:11:3A:B7", "2001:db8::1", "443"],
        "answer": 1,
        "explain": "MAC addresses are 48-bit Layer 2 hardware addresses written as six hexadecimal byte pairs, e.g., 00:1B:44:11:3A:B7. 192.168.10.45 is an IPv4 address (L3), 2001:db8::1 is IPv6 (L3), and 443 is a port number (L4).",
    },
    {
        "type": "mc",
        "q": "Which OSI layer adds a trailer (the FCS) to the data being transmitted?",
        "choices": ["Layer 4 - Transport", "Layer 3 - Network", "Layer 1 - Physical", "Layer 2 - Data link"],
        "answer": 3,
        "explain": "The Data link layer is the only layer that adds a trailer: the Frame Check Sequence (FCS), a CRC value used by the receiver to detect corrupted frames. All other layers add only headers.",
    },
    {
        "type": "mc",
        "q": "A technician finds that a newly run cable has a damaged connector, causing no link light on the switch port. At which OSI layer is this problem?",
        "choices": ["Layer 1", "Layer 2", "Layer 3", "Layer 7"],
        "answer": 0,
        "explain": "Cables, connectors, pinouts, and link signaling all belong to the Physical layer (Layer 1). A missing link light is the classic Layer 1 symptom — check cabling, connectors, transceivers, and ports first.",
    },
    {
        "type": "mc",
        "q": "TCP flow control, in which the receiver advertises how much data it can accept, is known as what?",
        "choices": ["Buffering", "Windowing", "Sequencing", "Fragmentation"],
        "answer": 1,
        "explain": "TCP uses a sliding window for flow control: the receiver advertises a window size and the sender may not send more unacknowledged data than that. This Layer 4 mechanism prevents overwhelming the receiver's buffer.",
    },
    {
        "type": "mc",
        "q": "Which two sublayers make up the OSI Data link layer?",
        "choices": [
            "MAC and LLC",
            "TCP and UDP",
            "IP and ICMP",
            "PHY and MDI",
        ],
        "answer": 0,
        "explain": "Layer 2 is split into the Logical Link Control (LLC) sublayer, which identifies the Layer 3 protocol being carried, and the Media Access Control (MAC) sublayer, which handles physical addressing and access to the medium (CSMA/CD, CSMA/CA).",
    },
    {
        "type": "mc",
        "q": "At which OSI layer does the Internet Control Message Protocol (ICMP) operate?",
        "choices": ["Layer 7", "Layer 4", "Layer 3", "Layer 2"],
        "answer": 2,
        "explain": "ICMP works alongside IP at the Network layer (Layer 3) to provide diagnostics and error reporting (ping, traceroute, unreachable messages). It has no ports because it does not use TCP or UDP.",
    },
    {
        "type": "mc",
        "q": "As a packet crosses three routers from source to destination (no NAT), which addresses change at each hop?",
        "choices": [
            "The source and destination IP addresses",
            "The source and destination MAC addresses",
            "The source and destination port numbers",
            "No addresses change at any hop",
        ],
        "answer": 1,
        "explain": "Each router strips the incoming Layer 2 frame and builds a new one for the next segment, so the MAC addresses change hop by hop. The Layer 3 IP addresses (and Layer 4 ports) stay the same end to end unless NAT is involved.",
    },
    {
        "type": "mc",
        "q": "Which protocol resolves a known IP address into the corresponding MAC address and is associated with Layer 2?",
        "choices": ["DNS", "DHCP", "ICMP", "ARP"],
        "answer": 3,
        "explain": "ARP (Address Resolution Protocol) broadcasts 'who has this IP?' and the owner replies with its MAC address, bridging Layer 3 addressing to Layer 2 delivery. DNS resolves names to IPs (L7), and DHCP assigns IP configuration.",
    },
    {
        "type": "mc",
        "q": "A load balancer that distributes client requests based on TCP port numbers and IP addresses is operating at which OSI layer?",
        "choices": ["Layer 2", "Layer 4", "Layer 6", "Layer 1"],
        "answer": 1,
        "explain": "Making decisions on IP + port (socket) information is a Transport layer function, so this is a Layer 4 load balancer. A load balancer that inspects URLs, cookies, or HTTP headers would be operating at Layer 7.",
    },
    {
        "type": "mc",
        "q": "Which OSI layer converts frames into bits for transmission on the medium?",
        "choices": ["Physical", "Data link", "Network", "Transport"],
        "answer": 0,
        "explain": "The Physical layer (Layer 1) takes the Layer 2 frame and transmits it as raw bits — electrical voltages, light pulses, or radio waves — according to the signaling rules of the medium in use.",
    },
    {
        "type": "mc",
        "q": "Which of the following protocols operates at the Application layer (Layer 7)?",
        "choices": ["STP", "UDP", "SMTP", "IPSec"],
        "answer": 2,
        "explain": "SMTP (email transfer) is an Application layer protocol. STP is a Layer 2 loop-prevention protocol, UDP is Layer 4 transport, and IPSec secures traffic at Layer 3.",
    },
    {
        "type": "mc",
        "q": "In a packet capture, a technician sees a unit of data with a destination value of FF:FF:FF:FF:FF:FF. What does this indicate?",
        "choices": [
            "A Layer 3 multicast packet",
            "A corrupted FCS",
            "An IPv6 anycast packet",
            "A Layer 2 broadcast frame",
        ],
        "answer": 3,
        "explain": "FF:FF:FF:FF:FF:FF is the Layer 2 broadcast MAC address — the frame is delivered to every host in the broadcast domain. ARP requests and DHCP Discover messages are common examples of broadcast frames.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: The PDU at the Transport layer when using UDP is called a datagram.",
        "answer": True,
        "explain": "TCP's Layer 4 PDU is the segment, while UDP's is the datagram. Both carry port numbers, but only TCP adds sequencing and acknowledgment fields for reliability.",
    },
    {
        "type": "tf",
        "q": "True or False: A router decrements the TTL field of a frame at Layer 2 each time it forwards it.",
        "answer": False,
        "explain": "TTL is a field in the Layer 3 IP header of a packet, not in a Layer 2 frame. Routers decrement TTL by 1 per hop and discard the packet (sending ICMP Time Exceeded) when it reaches 0.",
    },
    {
        "type": "tf",
        "q": "True or False: Each port on a switch is its own collision domain.",
        "answer": True,
        "explain": "Switches microsegment the network so every port is a separate collision domain, and full-duplex operation eliminates collisions entirely. A hub, in contrast, places all connected devices into one shared collision domain.",
    },
    {
        "type": "tf",
        "q": "True or False: In the OSI model, the Session layer is Layer 6 and the Presentation layer is Layer 5.",
        "answer": False,
        "explain": "It is the reverse: Session is Layer 5 and Presentation is Layer 6. Use the bottom-up mnemonic 'Please Do Not Throw Sausage Pizza Away' — Physical, Data link, Network, Transport, Session, Presentation, Application.",
    },
    {
        "type": "tf",
        "q": "True or False: The TCP/IP model's Internet layer corresponds to the OSI Network layer.",
        "answer": True,
        "explain": "The TCP/IP Internet layer performs logical addressing and routing with IP, exactly matching OSI Layer 3. The mapping is: Application = OSI 5-7, Transport = OSI 4, Internet = OSI 3, Network Access = OSI 1-2.",
    },
    {
        "type": "tf",
        "q": "True or False: During de-encapsulation, the receiving host processes the Transport layer header before the Network layer header.",
        "answer": False,
        "explain": "De-encapsulation moves UP the stack in order: the frame (L2) is processed first, then the IP packet header (L3), and only then the TCP/UDP header (L4) before data reaches the application. Headers are removed outside-in.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The PDU at Layer 3 of the OSI model is called a ______. (type your answer)",
        "answers": ["packet", "packets"],
        "explain": "Layer 3 (Network) PDUs are packets, which carry source and destination IP addresses plus the TTL field. Frames are Layer 2, segments/datagrams are Layer 4, and bits are Layer 1.",
    },
    {
        "type": "fill",
        "q": "The 48-bit hardware address burned into a network interface card and used at Layer 2 is called a ______ address. (type your answer)",
        "answers": ["mac", "media access control", "mac address"],
        "explain": "The MAC (Media Access Control) address is the 48-bit physical address used for frame delivery on the local segment. Its first 24 bits are the OUI identifying the manufacturer.",
    },
    {
        "type": "fill",
        "q": "The process of adding headers to data as it moves down the OSI stack on the sending host is called ______. (type your answer)",
        "answers": ["encapsulation", "data encapsulation"],
        "explain": "Encapsulation wraps data in a new header at each layer going down (and a trailer at Layer 2); the receiver reverses this with de-encapsulation going up the stack.",
    },
    {
        "type": "fill",
        "q": "A multilayer switch that can route traffic between VLANs is commonly called a Layer ______ switch. (type your answer or number)",
        "answers": ["3", "three", "layer 3"],
        "explain": "A Layer 3 (multilayer) switch performs normal Layer 2 switching within VLANs and also routes packets between VLANs using IP addresses, combining switch and router functions in one device.",
    },
    {
        "type": "fill",
        "q": "The combination of an IP address and a port number (e.g., 10.1.1.5:443) is known as a ______. (type your answer)",
        "answers": ["socket", "socket address"],
        "explain": "A socket uniquely identifies one endpoint of a network conversation by pairing the Layer 3 IP address with the Layer 4 port number. A TCP connection is defined by its two sockets.",
    },
    {
        "type": "fill",
        "q": "Wireless access points and network switches primarily operate at OSI Layer ______. (type the number)",
        "answers": ["2", "two", "layer 2", "data link"],
        "explain": "Both switches and APs forward frames based on MAC addresses, making them Layer 2 (Data link) devices. An AP bridges 802.11 wireless frames onto the 802.3 wired network.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each OSI layer to its PDU.",
        "pairs": [
            ["Layer 1 - Physical", "Bits"],
            ["Layer 2 - Data link", "Frames"],
            ["Layer 3 - Network", "Packets"],
            ["Layer 4 - Transport", "Segments"],
        ],
        "explain": "Bottom-up the PDUs are bits, frames, packets, segments (TCP) or datagrams (UDP); Layers 5-7 simply use 'data'. Knowing the PDU instantly reveals the layer in packet-capture questions.",
    },
    {
        "type": "match",
        "q": "Match each device to the OSI layer at which it primarily operates.",
        "pairs": [
            ["Hub/repeater", "Layer 1"],
            ["Switch", "Layer 2"],
            ["Router", "Layer 3"],
            ["Layer 4 load balancer", "Layer 4"],
            ["NGFW with deep packet inspection", "Layer 7"],
        ],
        "explain": "Hubs repeat bits (L1); switches forward frames by MAC (L2); routers route packets by IP (L3); L4 load balancers and stateful firewalls work with ports/sessions; NGFWs and proxies inspect application content (L7).",
    },
    {
        "type": "match",
        "q": "Match each protocol to its OSI layer.",
        "pairs": [
            ["Ethernet (802.3)", "Layer 2"],
            ["ICMP", "Layer 3"],
            ["TCP", "Layer 4"],
            ["TLS encryption", "Layer 6"],
            ["HTTP", "Layer 7"],
        ],
        "explain": "Ethernet frames operate at the Data link layer; ICMP rides with IP at the Network layer; TCP is Transport; encryption/formatting is Presentation (Layer 6 on the exam); HTTP is an Application layer protocol.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the OSI layers in order from Layer 1 (bottom) to Layer 7 (top).",
        "items": ["Physical", "Data link", "Network", "Transport", "Session", "Presentation", "Application"],
        "explain": "Bottom-up: Physical, Data link, Network, Transport, Session, Presentation, Application — 'Please Do Not Throw Sausage Pizza Away'. Top-down the mnemonic is 'All People Seem To Need Data Processing'.",
    },
    {
        "type": "order",
        "q": "Arrange the encapsulation steps in the order they occur on a SENDING host.",
        "items": [
            "Application data is created and formatted",
            "TCP header with port numbers is added (segment)",
            "IP header with addresses is added (packet)",
            "MAC header and FCS trailer are added (frame)",
            "Bits are transmitted onto the medium",
        ],
        "explain": "Encapsulation flows down the stack: data (L7-5), then the L4 transport header creates a segment, the L3 IP header creates a packet, the L2 header/trailer create a frame, and finally L1 transmits bits on the wire.",
    },
]
