TOPIC = {
    "id": "1.2",
    "domain": 1,
    "title": "Compare and contrast networking appliances, applications, and functions.",
    "short": "Appliances & Functions",
}

TERMS = [
    ("Router", "Layer 3 device that forwards packets between networks based on IP addresses using a routing table; separates broadcast domains"),
    ("Switch", "Layer 2 device that forwards frames within a network based on MAC addresses learned into its CAM table; each port is a collision domain"),
    ("Layer 3 switch", "Multilayer switch that switches frames within VLANs and also routes packets between VLANs using switch virtual interfaces (SVIs)"),
    ("Firewall", "Security appliance that permits or denies traffic between zones based on rules; may be stateless, stateful, or next-generation"),
    ("Stateful firewall", "Firewall that tracks connection state in a table and automatically allows return traffic for established outbound sessions"),
    ("Next-generation firewall (NGFW)", "Firewall adding Layer 7 application awareness, deep packet inspection, user identity, and integrated IPS"),
    ("Intrusion detection system (IDS)", "Passive, out-of-band sensor that receives copied traffic (mirror/tap), detects attacks, and alerts — cannot block"),
    ("Intrusion prevention system (IPS)", "Inline sensor placed in the traffic path that detects AND actively blocks malicious traffic in real time"),
    ("Signature-based detection", "IDS/IPS method matching traffic against a database of known attack patterns; accurate but blind to zero-day attacks"),
    ("Anomaly-based detection", "IDS/IPS method that baselines normal behavior and flags deviations; can catch new attacks but yields more false positives"),
    ("Load balancer", "Distributes client requests across a pool of servers via a virtual IP for scalability and high availability; uses health checks"),
    ("Round-robin", "Load-balancing algorithm that hands each new request to the next server in rotation, assuming roughly equal capacity"),
    ("Least connections", "Load-balancing algorithm that sends the next request to the server with the fewest active connections"),
    ("Proxy (forward)", "Intermediary in front of clients handling their outbound requests — content filtering, caching, logging, hiding client identity"),
    ("Reverse proxy", "Intermediary in front of servers handling inbound requests — hides servers, offloads TLS, caches, and distributes load"),
    ("Network-attached storage (NAS)", "File-level storage appliance on the existing LAN, accessed as shared folders via SMB/CIFS or NFS"),
    ("Storage area network (SAN)", "Dedicated network providing block-level storage that servers see as local disks; uses Fibre Channel or iSCSI"),
    ("iSCSI", "Protocol carrying SCSI block-storage commands over standard TCP/IP Ethernet networks, enabling SANs without Fibre Channel hardware"),
    ("Access point (AP)", "Layer 2 device bridging 802.11 wireless clients onto the wired LAN; broadcasts SSIDs; often PoE-powered"),
    ("Wireless LAN controller (WLC)", "Centrally manages lightweight APs: pushes config/SSIDs, tunes channels and power, enables seamless roaming"),
    ("Content delivery network (CDN)", "Geographically distributed edge servers that cache content close to users to cut latency and offload the origin server"),
    ("Virtual private network (VPN)", "Encrypted tunnel across an untrusted network; site-to-site connects offices, client-to-site connects remote users"),
    ("Quality of service (QoS)", "Classifying and prioritizing traffic so latency-sensitive applications like VoIP get preferential queuing during congestion"),
    ("DSCP", "Differentiated Services Code Point — 6-bit QoS marking in the Layer 3 IP header used to classify traffic end to end"),
    ("Class of Service (CoS)", "3-bit 802.1p priority marking carried in the Layer 2 802.1Q VLAN tag on trunk links"),
    ("Time to live (TTL)", "IP header field decremented by 1 at each router hop; at 0 the packet is dropped and ICMP Time Exceeded is returned — prevents routing loops"),
    ("Virtual appliance", "Network function (router, firewall, load balancer) delivered as software/VM instead of dedicated hardware; rapid to deploy and scale"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "Which device connects multiple networks together and makes forwarding decisions based on IP addresses?",
        "choices": ["Switch", "Router", "Hub", "Access point"],
        "answer": 1,
        "explain": "A router is a Layer 3 device that routes packets between different networks using its routing table and destination IP addresses. Switches forward frames within one network using MAC addresses.",
    },
    {
        "type": "mc",
        "q": "A firewall automatically permits return traffic for sessions that were initiated from the inside network, without explicit inbound rules. What type of firewall is this?",
        "choices": ["Stateless packet filter", "Application-layer proxy", "Stateful firewall", "Honeypot"],
        "answer": 2,
        "explain": "A stateful firewall records each outbound connection in a state table and automatically allows the matching return traffic. A stateless packet filter evaluates every packet in isolation and would need explicit rules in both directions.",
    },
    {
        "type": "mc",
        "q": "Which capability MOST distinguishes a next-generation firewall (NGFW) from a traditional stateful firewall?",
        "choices": [
            "It can block traffic based on TCP port numbers",
            "It performs deep packet inspection and application awareness at Layer 7",
            "It tracks the state of TCP connections",
            "It supports NAT for outbound traffic",
        ],
        "answer": 1,
        "explain": "NGFWs add Layer 7 application awareness/deep packet inspection (plus user identity and integrated IPS), letting them identify and block specific applications regardless of port. Port rules, state tracking, and NAT are traditional firewall features.",
    },
    {
        "type": "mc",
        "q": "A security team wants to monitor network traffic for attacks and receive alerts, but must guarantee the monitoring device can never delay or drop production traffic. What should they deploy?",
        "choices": [
            "An IPS deployed inline",
            "A stateful firewall",
            "An IDS fed by a port mirror or tap",
            "A reverse proxy",
        ],
        "answer": 2,
        "explain": "An IDS is passive and out-of-band: it analyzes a COPY of traffic delivered via a SPAN/mirror port or network tap, so it can alert but never block or delay real traffic. An inline IPS can block attacks but adds latency and is a potential point of failure.",
    },
    {
        "type": "mc",
        "q": "How must an IPS be deployed so it can actively block malicious traffic?",
        "choices": ["Inline, in the traffic path", "Out-of-band on a mirror port", "On a honeypot VLAN", "As a DNS forwarder"],
        "answer": 0,
        "explain": "An IPS must sit inline — directly in the flow of traffic — so packets pass through it and it can drop malicious ones in real time. A sensor on a mirror port only sees copies and can merely detect and alert (that is an IDS).",
    },
    {
        "type": "mc",
        "q": "An IDS flags traffic by comparing it against a database of known attack patterns. Which detection method is this, and what is its main weakness?",
        "choices": [
            "Anomaly-based; too many false positives",
            "Signature-based; cannot detect brand-new (zero-day) attacks",
            "Heuristic-based; requires inline deployment",
            "Signature-based; cannot detect known attacks",
        ],
        "answer": 1,
        "explain": "Signature-based detection matches known attack patterns, so it is accurate for documented threats but blind to zero-day attacks that have no signature yet. Anomaly-based detection baselines normal behavior and can catch novel attacks at the cost of more false positives.",
    },
    {
        "type": "mc",
        "q": "A load balancer distributes requests sequentially to each web server in rotation: server 1, server 2, server 3, then back to server 1. Which algorithm is in use?",
        "choices": ["Least connections", "Source IP hash", "Weighted response time", "Round-robin"],
        "answer": 3,
        "explain": "Round-robin simply rotates through the server pool in order, which works well when servers are equal and requests are similar. Least connections instead picks the server with the fewest active sessions — better when connection durations vary.",
    },
    {
        "type": "mc",
        "q": "Some sessions on a server farm last minutes while others last hours, leaving some servers overloaded under round-robin. Which load-balancing algorithm would BEST even out the load?",
        "choices": ["Least connections", "Round-robin", "Random", "First available"],
        "answer": 0,
        "explain": "Least connections sends each new request to the server currently handling the fewest active connections, naturally compensating for long-lived sessions that pile up on some servers under simple rotation.",
    },
    {
        "type": "mc",
        "q": "What is the purpose of a load balancer's health checks?",
        "choices": [
            "To encrypt traffic between clients and servers",
            "To automatically remove failed servers from the pool",
            "To assign IP addresses to backend servers",
            "To compress responses before sending them to clients",
        ],
        "answer": 1,
        "explain": "Health checks (ping, TCP connect, or HTTP probes) continuously verify each backend server is responsive; servers that fail are pulled from rotation so clients are only sent to working nodes. This is central to the high-availability role of load balancing.",
    },
    {
        "type": "mc",
        "q": "A company wants to filter and log employees' outbound web browsing and cache frequently visited pages. Which device fits best?",
        "choices": ["Reverse proxy", "Load balancer", "Forward proxy", "IDS"],
        "answer": 2,
        "explain": "A forward proxy sits in front of CLIENTS and intermediates their outbound requests, enabling URL/content filtering, caching, logging, and hiding internal client identities. A reverse proxy does the opposite — it fronts servers for inbound traffic.",
    },
    {
        "type": "mc",
        "q": "A device sits in front of a web server farm, terminates TLS, caches static content, and hides the real servers from the Internet. What is it?",
        "choices": ["Forward proxy", "Reverse proxy", "NAS", "Wireless controller"],
        "answer": 1,
        "explain": "A reverse proxy represents the SERVERS: Internet clients connect to it, and it forwards requests to backends. Along the way it can offload TLS, cache, compress, and shield the server identities — overlapping with Layer 7 load balancing.",
    },
    {
        "type": "mc",
        "q": "Which storage solution provides FILE-level access over the existing LAN using SMB or NFS?",
        "choices": ["SAN", "NAS", "iSCSI target", "Fibre Channel fabric"],
        "answer": 1,
        "explain": "Network-attached storage (NAS) serves shared folders/files over the regular network using file protocols like SMB/CIFS (Windows) and NFS (Linux/Unix). SANs instead provide block-level storage over a dedicated network via Fibre Channel or iSCSI.",
    },
    {
        "type": "mc",
        "q": "Virtualization hosts need shared storage that appears to each server as a raw local disk, with the highest possible performance on a dedicated storage network. Which technology fits?",
        "choices": ["A SAN using Fibre Channel", "A NAS using SMB", "A file server using FTP", "A NAS using NFS"],
        "answer": 0,
        "explain": "A storage area network (SAN) provides block-level storage — LUNs the servers format like local disks — over a dedicated high-speed network, classically Fibre Channel (or iSCSI over Ethernet). NAS provides file-level shares, not raw block devices.",
    },
    {
        "type": "mc",
        "q": "Which protocol carries block-level SCSI storage commands over a standard TCP/IP Ethernet network?",
        "choices": ["NFS", "SMB", "iSCSI", "SNMP"],
        "answer": 2,
        "explain": "iSCSI encapsulates SCSI block commands in TCP/IP, letting organizations build SANs on ordinary Ethernet without dedicated Fibre Channel switches and HBAs. SMB and NFS are file-level protocols used by NAS.",
    },
    {
        "type": "mc",
        "q": "A business is growing to 150 access points across multiple buildings and needs centralized configuration, RF/channel tuning, and seamless roaming. What should be added?",
        "choices": [
            "A wireless LAN controller managing lightweight APs",
            "More autonomous APs configured individually",
            "A forward proxy",
            "A Layer 2 switch with more PoE ports",
        ],
        "answer": 0,
        "explain": "A wireless LAN controller centrally manages lightweight APs — pushing SSIDs and security settings, dynamically tuning channels/power, and coordinating fast roaming between APs. Managing 150 autonomous APs one by one does not scale.",
    },
    {
        "type": "mc",
        "q": "Users worldwide complain that images and video from a company's web site load slowly outside its home region. Which solution addresses this MOST directly?",
        "choices": ["A stateful firewall", "A content delivery network (CDN)", "An IDS", "A site-to-site VPN"],
        "answer": 1,
        "explain": "A CDN caches static content on geographically distributed edge servers, so each user is served from a nearby node rather than the distant origin. This cuts latency, speeds page loads, and reduces load on the origin server.",
    },
    {
        "type": "mc",
        "q": "Where does a CDN store cached copies of content to minimize latency for end users?",
        "choices": [
            "On the origin server only",
            "On each user's local hard drive",
            "On edge servers geographically close to users",
            "On the authoritative DNS server",
        ],
        "answer": 2,
        "explain": "CDNs place cache (edge) servers in many locations worldwide and steer each user — often via DNS or anycast — to the nearest edge node. Content is served locally when cached; only cache misses go back to the origin.",
    },
    {
        "type": "mc",
        "q": "Which technology creates an encrypted tunnel across the public Internet so a remote employee's laptop can securely access the corporate LAN?",
        "choices": ["QoS", "Client-to-site VPN", "CDN", "Reverse proxy"],
        "answer": 1,
        "explain": "A client-to-site (remote access) VPN encrypts traffic between an individual user's device and the corporate VPN gateway, making the remote host behave as if it were on the private network. A site-to-site VPN instead permanently links two office networks.",
    },
    {
        "type": "mc",
        "q": "VoIP calls break up whenever large file transfers saturate the WAN link. Which function should be configured to fix this?",
        "choices": ["TTL", "Port mirroring", "NAT", "QoS"],
        "answer": 3,
        "explain": "Quality of service classifies and prioritizes traffic so latency-sensitive voice packets are queued and forwarded ahead of bulk data during congestion. Voice is highly sensitive to latency, jitter, and packet loss, so it should be marked and prioritized.",
    },
    {
        "type": "mc",
        "q": "Which QoS marking is a 6-bit value carried in the IP header at Layer 3?",
        "choices": ["CoS (802.1p)", "DSCP", "VLAN ID", "MPLS label"],
        "answer": 1,
        "explain": "DSCP (Differentiated Services Code Point) is a 6-bit field in the IP header, so the marking survives across routed hops end to end. CoS is a 3-bit 802.1p priority in the Layer 2 802.1Q VLAN tag, meaningful only on trunked LAN segments.",
    },
    {
        "type": "mc",
        "q": "A packet arrives at a router with its TTL value at 1, and the destination is still several hops away. What happens?",
        "choices": [
            "The router forwards it with TTL reset to 64",
            "The router queues the packet until TTL increases",
            "The router discards it and sends an ICMP Time Exceeded message to the source",
            "The router forwards it with TTL 0 as a final warning",
        ],
        "answer": 2,
        "explain": "Each router decrements TTL by 1; when it hits 0 the packet is dropped and ICMP Time Exceeded (Type 11) is returned to the sender. This prevents packets from circling forever in routing loops, and traceroute exploits it to map paths hop by hop.",
    },
    {
        "type": "mc",
        "q": "An administrator changed a server's DNS record, but many users continue reaching the old IP address for hours. Which value controls how long resolvers cache the old record?",
        "choices": ["The DNS record's TTL", "The IP header TTL", "The DHCP lease time", "The BGP hold timer"],
        "answer": 0,
        "explain": "DNS TTL specifies how many seconds resolvers may cache a record before re-querying. Until cached entries expire, clients keep using the old answer — which is why admins lower the TTL before planned IP changes. This is separate from the hop-count TTL in the IP header.",
    },
    {
        "type": "mc",
        "q": "Which is an advantage of deploying a firewall as a VIRTUAL appliance rather than a physical one?",
        "choices": [
            "It never competes for CPU or memory resources",
            "It can be deployed and scaled in minutes without new hardware",
            "It always provides higher throughput than hardware ASICs",
            "It removes the need for security rule configuration",
        ],
        "answer": 1,
        "explain": "Virtual appliances are software images, so they can be spun up, cloned, snapshotted, and scaled rapidly with no procurement or rack space — ideal for cloud and NFV designs. The trade-off is shared host resources and hypervisor-dependent performance, not superiority in raw throughput.",
    },
    {
        "type": "mc",
        "q": "Which device separates collision domains on every port but keeps all ports in one broadcast domain (single VLAN)?",
        "choices": ["Router", "Hub", "Switch", "Firewall"],
        "answer": 2,
        "explain": "Each switch port is its own collision domain, but broadcasts are flooded to every port in the VLAN, so the whole VLAN is one broadcast domain. Routers are what separate broadcast domains; hubs separate nothing.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: An IDS deployed on a SPAN (mirror) port can block an attack in real time.",
        "answer": False,
        "explain": "A sensor on a mirror port only receives a copy of traffic after it has already been forwarded, so it can detect and alert but cannot block. Real-time blocking requires an IPS deployed inline in the traffic path.",
    },
    {
        "type": "tf",
        "q": "True or False: A Layer 3 switch can route traffic between VLANs.",
        "answer": True,
        "explain": "Layer 3 (multilayer) switches combine hardware-speed Layer 2 switching with routing between VLANs, typically via switch virtual interfaces (SVIs). They are the standard choice for inter-VLAN routing inside a LAN.",
    },
    {
        "type": "tf",
        "q": "True or False: A SAN provides block-level storage, while a NAS provides file-level storage.",
        "answer": True,
        "explain": "SAN storage is presented as raw blocks (LUNs) that servers format like local disks, over Fibre Channel or iSCSI. NAS presents complete file shares over the LAN via SMB or NFS — the NAS appliance's own OS manages the file system.",
    },
    {
        "type": "tf",
        "q": "True or False: CoS (802.1p) markings are carried in the IP header and survive across every routed hop.",
        "answer": False,
        "explain": "CoS is a 3-bit priority field inside the Layer 2 802.1Q VLAN tag, so it exists only on trunked Ethernet segments and is lost when the frame is rebuilt. DSCP, carried in the Layer 3 IP header, is the marking that persists across routed hops.",
    },
    {
        "type": "tf",
        "q": "True or False: In a split-tunnel VPN configuration, only traffic destined for the corporate network goes through the encrypted tunnel.",
        "answer": True,
        "explain": "Split tunneling sends corporate-bound traffic through the VPN while regular Internet traffic exits the user's local connection directly. Full tunneling forces ALL traffic through the tunnel — more control and inspection, but more bandwidth and latency.",
    },
    {
        "type": "tf",
        "q": "True or False: An anomaly-based IDS can potentially detect a zero-day attack that has no published signature.",
        "answer": True,
        "explain": "Anomaly-based detection compares traffic against a learned baseline of normal behavior, so novel attacks that deviate from the baseline can be flagged even without a signature. The trade-off is a higher false-positive rate than signature-based detection.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "A proxy server that sits in front of web servers and handles inbound requests from Internet clients is called a ______ proxy. (type your answer)",
        "answers": ["reverse", "reverse proxy"],
        "explain": "A reverse proxy represents the servers: clients connect to it, and it forwards requests to the real backends, providing TLS offload, caching, and server protection. A forward proxy does the mirror image for outbound client traffic.",
    },
    {
        "type": "fill",
        "q": "The load-balancing algorithm that sends each new request to the server with the fewest active sessions is called ______. (type your answer)",
        "answers": ["least connections", "least connection", "least-connections"],
        "explain": "Least connections balances by current load rather than simple rotation, which handles variable-length sessions better than round-robin. Health checks then ensure only responsive servers stay in the pool.",
    },
    {
        "type": "fill",
        "q": "The two common file-sharing protocols used by NAS devices are NFS and ______. (type the acronym)",
        "answers": ["smb", "cifs", "smb/cifs", "server message block"],
        "explain": "NAS appliances serve file-level shares using SMB/CIFS (native to Windows, TCP 445) and NFS (native to Unix/Linux). Block-level SAN protocols, by contrast, are Fibre Channel and iSCSI.",
    },
    {
        "type": "fill",
        "q": "An access point that has minimal local intelligence and depends on a WLC for its configuration is called a ______ AP. (type your answer)",
        "answers": ["lightweight", "lightweight ap", "controller based", "controller-based"],
        "explain": "Lightweight APs offload control functions to a wireless LAN controller, which pushes configuration, tunes RF, and coordinates roaming. Autonomous APs are self-contained and must be configured individually.",
    },
    {
        "type": "fill",
        "q": "The QoS marking carried as a 6-bit field in the Layer 3 IP header is known by the acronym ______. (type the acronym)",
        "answers": ["dscp", "differentiated services code point"],
        "explain": "DSCP (Differentiated Services Code Point) marks packet priority inside the IP header, so the classification travels end to end across routers. Layer 2's equivalent is the 3-bit CoS value in the 802.1Q tag.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each appliance to its primary role.",
        "pairs": [
            ["Router", "Forwards packets between networks using IP addresses"],
            ["Switch", "Forwards frames within a LAN using MAC addresses"],
            ["Load balancer", "Distributes client requests across a pool of servers"],
            ["IPS", "Sits inline and blocks malicious traffic in real time"],
            ["IDS", "Passively monitors copied traffic and raises alerts"],
        ],
        "explain": "Routers route (L3), switches switch (L2), load balancers spread load across server farms for availability, and the IDS/IPS pair differ by placement and action: IDS = passive detection/alerting, IPS = inline prevention.",
    },
    {
        "type": "match",
        "q": "Match each storage or wireless term to its description.",
        "pairs": [
            ["NAS", "File-level storage shared over the LAN via SMB/NFS"],
            ["SAN", "Block-level storage on a dedicated network via FC/iSCSI"],
            ["Autonomous AP", "Self-contained access point configured individually"],
            ["Wireless controller", "Centrally manages many lightweight APs"],
        ],
        "explain": "NAS = files over the ordinary network; SAN = blocks over a dedicated storage network. For wireless, autonomous APs stand alone while lightweight APs are managed at scale by a controller for config, RF tuning, and roaming.",
    },
    {
        "type": "match",
        "q": "Match each function to the problem it solves.",
        "pairs": [
            ["VPN", "Encrypted tunnel across an untrusted network"],
            ["QoS", "Prioritizes voice/video over bulk traffic"],
            ["IP TTL", "Prevents packets from looping forever"],
            ["DNS TTL", "Controls how long resolvers cache a record"],
            ["CDN", "Caches content at edge locations near users"],
        ],
        "explain": "VPNs give confidentiality over public networks; QoS classifies and prioritizes latency-sensitive traffic; the IP header TTL is decremented per hop to kill looping packets; DNS TTL is a cache lifetime in seconds; CDNs shorten the distance between users and content.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps of a QoS-enabled router handling traffic during congestion, from first to last.",
        "items": [
            "Traffic is classified by application or port",
            "Packets are marked with DSCP values",
            "Packets are placed into priority queues",
            "Higher-priority queues are serviced and transmitted first",
        ],
        "explain": "QoS works in stages: classify (identify the traffic), mark (tag it with DSCP/CoS), queue (sort into priority queues), then schedule (service the important queues first). Policing/shaping may also drop or delay traffic exceeding limits.",
    },
    {
        "type": "order",
        "q": "A packet is sent with TTL 3 toward a destination 5 router hops away. Arrange the events in order.",
        "items": [
            "Router 1 decrements TTL to 2 and forwards the packet",
            "Router 2 decrements TTL to 1 and forwards the packet",
            "Router 3 decrements TTL to 0 and discards the packet",
            "Router 3 sends ICMP Time Exceeded back to the source",
        ],
        "explain": "Every router decrements TTL by 1 before forwarding; the router that decrements it to 0 drops the packet and returns ICMP Time Exceeded (Type 11). Traceroute deliberately sends TTL 1, 2, 3... to harvest these messages and reveal each hop.",
    },
]
