TOPIC = {
    "id": "1.3",
    "domain": 1,
    "title": "Summarize cloud concepts and connectivity options.",
    "short": "Cloud Concepts",
}

TERMS = [
    ("Network functions virtualization (NFV)", "Running network functions (routers, firewalls, load balancers) as software on commodity servers instead of dedicated hardware"),
    ("Virtual network function (VNF)", "A single virtualized network appliance instance (e.g., a virtual firewall VM) deployed under an NFV architecture"),
    ("Virtual private cloud (VPC)", "A logically isolated private virtual network you define inside a public cloud, with your own CIDR range, subnets, and route tables"),
    ("Network security group (NSG)", "Virtual firewall rules applied at the individual instance/vNIC level for fine-grained, per-workload filtering"),
    ("Network security list (NSL)", "Virtual firewall rules applied at the subnet level, affecting every instance within that subnet"),
    ("Internet gateway", "VPC component enabling bidirectional Internet connectivity for resources with public IPs in public subnets"),
    ("NAT gateway", "Cloud gateway allowing instances in private subnets to initiate outbound-only Internet connections while blocking unsolicited inbound traffic"),
    ("Cloud VPN (site-to-site)", "IPSec-encrypted tunnel over the public Internet connecting an on-premises network to a VPC; quick and cheap but Internet-dependent"),
    ("Direct Connect", "Dedicated private physical circuit from on-premises into the cloud provider, bypassing the public Internet for consistent high bandwidth and low latency"),
    ("Public cloud", "Deployment model where many organizations share a provider's multitenant infrastructure on a pay-as-you-go basis"),
    ("Private cloud", "Cloud infrastructure dedicated to a single organization, whether hosted on-premises or by a third party"),
    ("Hybrid cloud", "Integrated combination of private and public clouds, enabling data/workload portability and cloud bursting"),
    ("Software as a service (SaaS)", "Provider delivers complete ready-to-use applications (e.g., Microsoft 365, Salesforce); customer manages only data, users, settings"),
    ("Infrastructure as a service (IaaS)", "Provider supplies VMs, storage, and networks; customer manages OS, patches, middleware, and applications (e.g., EC2)"),
    ("Platform as a service (PaaS)", "Provider manages OS/runtime/middleware; customer deploys and manages only application code and data (e.g., Azure App Service)"),
    ("Shared responsibility model", "Division of security/management duties between cloud provider and customer, varying by service model (IaaS vs PaaS vs SaaS)"),
    ("Scalability", "A system's ability to handle growth by adding resources — vertically (bigger node) or horizontally (more nodes)"),
    ("Elasticity", "Automatic, dynamic scaling in BOTH directions — resources grow with demand spikes and shrink when demand falls"),
    ("Vertical scaling (scale up)", "Adding CPU/RAM/storage to an existing single node; simple but has hardware ceilings and often requires downtime"),
    ("Horizontal scaling (scale out)", "Adding more nodes/instances behind a load balancer; near-limitless and adds redundancy"),
    ("Multitenancy", "One physical infrastructure or software instance serving many logically isolated customers (tenants) simultaneously"),
    ("Cloud bursting", "Hybrid-cloud technique where workloads overflow from the private cloud into the public cloud during demand spikes"),
    ("Public subnet", "VPC subnet whose route table points to an internet gateway, allowing directly reachable public-facing resources"),
    ("Private subnet", "VPC subnet with no direct route from the Internet; instances reach out only via a NAT gateway"),
]

QUESTIONS = [
    # --- multiple choice ---
    {
        "type": "mc",
        "q": "A company replaces its hardware routers, firewalls, and load balancers with software versions running as virtual machines on standard servers. What is this called?",
        "choices": ["Software-defined WAN", "Network functions virtualization (NFV)", "Infrastructure as code", "Multitenancy"],
        "answer": 1,
        "explain": "NFV decouples network functions from dedicated hardware and runs them as software (VNFs) on commodity servers, enabling rapid deployment, cloning, and scaling. SDN, by contrast, is about separating the control plane from the data plane.",
    },
    {
        "type": "mc",
        "q": "Which cloud construct gives an organization its own logically isolated network — with self-defined subnets, IP ranges, and route tables — inside a public cloud provider?",
        "choices": ["Network security group", "Direct Connect", "Virtual private cloud (VPC)", "Internet gateway"],
        "answer": 2,
        "explain": "A VPC (called a VNet in Azure) is a logically isolated virtual network within the provider's infrastructure where you choose the CIDR block, create public/private subnets, and control routing and security — your own private network in their cloud.",
    },
    {
        "type": "mc",
        "q": "Which statement BEST describes the difference between a network security group and a network security list?",
        "choices": [
            "Groups filter at the subnet level; lists filter per instance",
            "Groups filter at the instance/vNIC level; lists filter at the subnet level",
            "Groups only allow traffic; lists only deny traffic",
            "Groups work at Layer 2; lists work at Layer 7",
        ],
        "answer": 1,
        "explain": "Network security groups attach to individual resources (VM vNICs) for fine-grained per-workload rules, while network security lists apply to an entire subnet, filtering every instance inside it. Anchor: group = instance, list = subnet.",
    },
    {
        "type": "mc",
        "q": "A cloud admin needs one baseline rule — 'block Telnet' — applied to every current and future VM in a subnet with a single configuration. What should be used?",
        "choices": [
            "A network security list on the subnet",
            "A network security group on each VM",
            "An internet gateway route",
            "A DHCP option set",
        ],
        "answer": 0,
        "explain": "Because network security lists operate at the subnet level, one rule automatically governs every instance in that subnet — ideal for broad baselines. Security groups would need to be attached and maintained per instance.",
    },
    {
        "type": "mc",
        "q": "Database servers in a private subnet must download OS patches from the Internet, but must never accept connections initiated FROM the Internet. Which component provides this?",
        "choices": ["Internet gateway", "NAT gateway", "Direct Connect", "VPC peering"],
        "answer": 1,
        "explain": "A NAT gateway translates private source addresses to its public IP for outbound sessions and only admits the return traffic of those sessions — outbound-only by design. An internet gateway allows bidirectional access and would expose the servers.",
    },
    {
        "type": "mc",
        "q": "What does an internet gateway provide in a VPC?",
        "choices": [
            "Outbound-only Internet access for private subnets",
            "An encrypted tunnel to on-premises networks",
            "Bidirectional Internet connectivity for resources with public IPs",
            "Block-level storage for cloud instances",
        ],
        "answer": 2,
        "explain": "The internet gateway connects the VPC to the public Internet in both directions: public-subnet resources can be reached from the Internet and can initiate traffic to it. Outbound-only access for private subnets is the NAT gateway's job.",
    },
    {
        "type": "mc",
        "q": "What makes a VPC subnet a 'public' subnet?",
        "choices": [
            "It uses public IP addresses larger than /24",
            "Its route table sends default (0.0.0.0/0) traffic to an internet gateway",
            "It has a network security list attached",
            "It is replicated across regions",
        ],
        "answer": 1,
        "explain": "A subnet is public when its route table points default traffic at the internet gateway, allowing its instances (with public IPs) to be reachable from the Internet. Private subnets lack this route and typically reach out through a NAT gateway instead.",
    },
    {
        "type": "mc",
        "q": "A startup needs on-premises-to-cloud connectivity TODAY, at minimal cost, using its existing Internet circuit. Which option fits?",
        "choices": ["Direct Connect", "A site-to-site VPN to the VPC", "Dark fiber", "MPLS"],
        "answer": 1,
        "explain": "A cloud site-to-site VPN builds an IPSec-encrypted tunnel over the existing Internet connection and can be running within hours at low cost. The trade-off is Internet-dependent performance — bandwidth and latency are variable.",
    },
    {
        "type": "mc",
        "q": "A hospital must connect its data center to the cloud with guaranteed bandwidth, consistent low latency, and traffic that never touches the public Internet. Which option is required?",
        "choices": ["Split-tunnel VPN", "Client-to-site VPN", "Direct Connect", "An internet gateway"],
        "answer": 2,
        "explain": "Direct Connect (generically, a dedicated interconnect; Azure's is ExpressRoute) is a private physical circuit into the cloud provider, bypassing the Internet entirely for predictable high performance. VPNs ride the public Internet and cannot guarantee latency.",
    },
    {
        "type": "mc",
        "q": "Which is a common enterprise design combining the two cloud connectivity options?",
        "choices": [
            "VPN as primary with Direct Connect as failover, since VPNs are faster",
            "Direct Connect as primary with a site-to-site VPN as backup",
            "Two VPNs, since Direct Connect cannot carry production traffic",
            "An internet gateway as primary and a NAT gateway as backup",
        ],
        "answer": 1,
        "explain": "The standard pattern is Direct Connect for consistent production performance, with a low-cost Internet VPN standing by as failover if the dedicated circuit goes down. Note Direct Connect is private but not inherently encrypted, while the VPN is.",
    },
    {
        "type": "mc",
        "q": "Which cloud deployment model dedicates all infrastructure to a single organization, whether hosted on-premises or by a third party?",
        "choices": ["Public cloud", "Community cloud", "Hybrid cloud", "Private cloud"],
        "answer": 3,
        "explain": "A private cloud serves exactly one organization — the defining trait is exclusive use, not physical location, so it can live in your data center or be hosted for you. It offers maximum control at the highest cost.",
    },
    {
        "type": "mc",
        "q": "A retailer keeps its sensitive database on a private cloud but automatically expands its web tier into a public cloud during holiday traffic spikes. Which deployment model is this?",
        "choices": ["Hybrid cloud", "Public cloud", "Private cloud", "Multitenant cloud"],
        "answer": 0,
        "explain": "Integrating private and public clouds so workloads can move between them is the hybrid model; overflowing into public capacity on demand is called cloud bursting. Hybrid designs depend on connectivity such as VPN or Direct Connect.",
    },
    {
        "type": "mc",
        "q": "An organization subscribes to Microsoft 365 email and Salesforce CRM, accessed through a browser with no servers to manage. Which service model is this?",
        "choices": ["IaaS", "PaaS", "SaaS", "NFV"],
        "answer": 2,
        "explain": "Software as a service delivers complete, ready-to-use applications over the Internet; the provider runs everything from hardware to the app itself. The customer manages only data, user accounts, and settings.",
    },
    {
        "type": "mc",
        "q": "In which service model is the CUSTOMER responsible for patching the operating system of their virtual machines?",
        "choices": ["SaaS", "IaaS", "PaaS", "All service models equally"],
        "answer": 1,
        "explain": "In IaaS the provider supplies the hardware, hypervisor, and network, but everything from the OS upward — patching, middleware, apps, data — is the customer's responsibility under the shared responsibility model. In PaaS and SaaS the provider patches the OS.",
    },
    {
        "type": "mc",
        "q": "Developers want to push application code to the cloud without managing servers, operating systems, or runtimes. Which service model fits?",
        "choices": ["IaaS", "SaaS", "Private cloud", "PaaS"],
        "answer": 3,
        "explain": "Platform as a service provides a managed platform — OS, runtime, middleware, often databases — so developers manage only their code and data. Examples include Azure App Service, Google App Engine, and AWS Elastic Beanstalk.",
    },
    {
        "type": "mc",
        "q": "Which lists the service models from MOST customer management responsibility to LEAST?",
        "choices": [
            "SaaS, PaaS, IaaS",
            "IaaS, PaaS, SaaS",
            "PaaS, IaaS, SaaS",
            "IaaS, SaaS, PaaS",
        ],
        "answer": 1,
        "explain": "IaaS leaves the customer managing the OS and everything above it; PaaS reduces that to code and data; SaaS reduces it to essentially configuration and data. The provider's share of responsibility grows in the same order.",
    },
    {
        "type": "mc",
        "q": "An e-commerce platform automatically adds instances during a flash sale and terminates them when traffic subsides, minimizing cost. Which characteristic is demonstrated?",
        "choices": ["Elasticity", "Vertical scalability", "Multitenancy", "High availability"],
        "answer": 0,
        "explain": "Elasticity is automatic scaling in BOTH directions — expanding under load and contracting afterward so you pay only for what you use. Scalability alone is the general capacity to grow; the automatic shrink-back is what marks elasticity.",
    },
    {
        "type": "mc",
        "q": "Adding more CPU and RAM to a single existing database server is an example of what?",
        "choices": ["Horizontal scaling (scale out)", "Elasticity", "Vertical scaling (scale up)", "Cloud bursting"],
        "answer": 2,
        "explain": "Vertical scaling (scale up) makes one node more powerful, which is simple but hits hardware ceilings and often needs downtime. Horizontal scaling (scale out) instead adds more nodes behind a load balancer, which also adds redundancy.",
    },
    {
        "type": "mc",
        "q": "Adding three more web servers behind a load balancer to handle growing traffic is an example of what?",
        "choices": ["Vertical scaling", "Horizontal scaling", "Multitenancy", "NFV"],
        "answer": 1,
        "explain": "Horizontal scaling (scaling out) adds more instances that share the load, offering near-limitless growth plus fault tolerance — if one node dies, the rest carry on. It requires applications designed to run across multiple nodes.",
    },
    {
        "type": "mc",
        "q": "Multiple companies run workloads on the same physical cloud hardware, yet each company's data and traffic remain logically isolated. What is this property called?",
        "choices": ["Elasticity", "Hybrid deployment", "Redundancy", "Multitenancy"],
        "answer": 3,
        "explain": "Multitenancy means one shared physical infrastructure (or software instance) serves many logically isolated tenants. It is the economic engine of public cloud — high utilization and low cost — mitigated by strong hypervisor and network isolation.",
    },
    {
        "type": "mc",
        "q": "Which is a legitimate security consideration of multitenancy in a public cloud?",
        "choices": [
            "Tenants must share user accounts with each other",
            "A failure of logical isolation could expose one tenant's data to another",
            "All tenants' traffic is unencrypted by design",
            "Tenants cannot use firewalls in a shared environment",
        ],
        "answer": 1,
        "explain": "Because tenants share hardware, the core risk is a breakdown of logical isolation (hypervisor escape, side channels, noisy neighbors). Providers mitigate this with hypervisor separation, VPC isolation, and encryption — but it remains the key trade-off versus dedicated hosting.",
    },
    {
        "type": "mc",
        "q": "In the shared responsibility model for SaaS, which of these remains the CUSTOMER'S responsibility?",
        "choices": [
            "Patching the application",
            "Maintaining the physical data center",
            "Managing user access and protecting account credentials/data",
            "Upgrading the hypervisor",
        ],
        "answer": 2,
        "explain": "Even in SaaS, the customer always owns its data and identities: account provisioning, MFA, access rights, and appropriate use of data. The provider handles the application, OS, virtualization, and physical infrastructure.",
    },
    {
        "type": "mc",
        "q": "Which pairing of cloud connectivity option and characteristic is correct?",
        "choices": [
            "VPN — dedicated physical circuit with guaranteed bandwidth",
            "Direct Connect — encrypted by default because it uses IPSec",
            "VPN — encrypted tunnel whose performance depends on the public Internet",
            "Direct Connect — deployable in a few hours at minimal cost",
        ],
        "answer": 2,
        "explain": "A cloud VPN is an IPSec tunnel across the Internet: encrypted, fast to deploy, cheap, but with variable performance. Direct Connect is a private dedicated circuit — consistent and fast but costly, weeks to provision, and NOT inherently encrypted.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: A NAT gateway allows Internet hosts to initiate inbound connections to instances in a private subnet.",
        "answer": False,
        "explain": "A NAT gateway is outbound-only: private instances can initiate connections out (updates, API calls) and receive replies to those sessions, but unsolicited inbound connections from the Internet are blocked. Bidirectional access requires an internet gateway and public IPs.",
    },
    {
        "type": "tf",
        "q": "True or False: A private cloud must be physically located in the organization's own data center.",
        "answer": False,
        "explain": "What defines a private cloud is exclusive use by one organization, not location — it can be on-premises or hosted by a third party. Public vs. private is about tenancy, not geography.",
    },
    {
        "type": "tf",
        "q": "True or False: Every elastic system is scalable, but not every scalable system is elastic.",
        "answer": True,
        "explain": "Elasticity is scalability plus automation in both directions — resources grow and shrink dynamically with demand. A system that can grow only through planned manual capacity additions is scalable but not elastic.",
    },
    {
        "type": "tf",
        "q": "True or False: Direct Connect traffic is automatically encrypted because it uses the IPSec protocol suite.",
        "answer": False,
        "explain": "Direct Connect provides a PRIVATE physical path, but privacy of the route is not encryption — no IPSec is inherent. Organizations requiring encryption run a VPN or MACsec over the dedicated circuit. It is the Internet VPN option that is IPSec-encrypted by nature.",
    },
    {
        "type": "tf",
        "q": "True or False: In a typical cloud design, both a subnet-level security list and an instance-level security group can filter the same traffic.",
        "answer": True,
        "explain": "The controls stack: traffic entering an instance may first pass the subnet's security list and then the instance's security group. Broad subnet baselines plus fine-grained per-instance rules together implement defense in depth.",
    },
    {
        "type": "tf",
        "q": "True or False: NFV and SDN are the same technology under two names.",
        "answer": False,
        "explain": "NFV virtualizes the network DEVICES themselves (firewall as a VM on commodity hardware), while SDN separates the control plane from the data plane for centralized programmable control. They complement each other but solve different problems.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "The cloud gateway that provides outbound-only Internet access for instances in private subnets is the ______ gateway. (type your answer)",
        "answers": ["nat", "network address translation"],
        "explain": "The NAT gateway translates private addresses to its public IP for outbound sessions and admits only the return traffic of those sessions, keeping private instances unreachable from the Internet.",
    },
    {
        "type": "fill",
        "q": "An organization's logically isolated, self-defined network inside a public cloud provider is called a ______. (type the acronym)",
        "answers": ["vpc", "virtual private cloud", "vnet", "virtual network"],
        "explain": "A virtual private cloud (VPC; Azure calls it a VNet) is your isolated slice of the provider's network where you define CIDR blocks, subnets, route tables, gateways, and security filtering.",
    },
    {
        "type": "fill",
        "q": "The service model in which the provider manages everything except the customer's application code and data is ______. (type the acronym)",
        "answers": ["paas", "platform as a service"],
        "explain": "Platform as a service handles the OS, runtime, and middleware so developers only deploy code and manage data. IaaS gives more control (customer manages the OS); SaaS gives less (customer just uses the app).",
    },
    {
        "type": "fill",
        "q": "The cloud characteristic where resources automatically grow AND shrink to match real-time demand is called ______. (type your answer)",
        "answers": ["elasticity", "elastic scaling", "elastic"],
        "explain": "Elasticity pairs auto-scaling with pay-as-you-go economics: capacity expands during spikes and contracts afterward. Its keyword markers are 'automatic' and 'both directions', distinguishing it from plain scalability.",
    },
    {
        "type": "fill",
        "q": "AWS's dedicated private-circuit service for connecting on-premises networks to the cloud without using the public Internet is called ______. (type your answer)",
        "answers": ["direct connect", "aws direct connect", "directconnect"],
        "explain": "Direct Connect is a dedicated physical link into the provider's network — consistent bandwidth and latency, higher cost, weeks to provision. Azure's equivalent is ExpressRoute and Google's is Cloud Interconnect; the exam uses the AWS/generic term.",
    },
    {
        "type": "fill",
        "q": "Running one instance of infrastructure or software for many logically isolated customers at once is called ______. (type your answer)",
        "answers": ["multitenancy", "multi-tenancy", "multitenant", "multi tenancy"],
        "explain": "Multitenancy shares physical resources among tenants while keeping their data and traffic logically separated. It maximizes utilization and drives down cost, which is why public cloud pricing works.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each cloud component to its function.",
        "pairs": [
            ["Internet gateway", "Bidirectional Internet access for public subnets"],
            ["NAT gateway", "Outbound-only Internet access for private subnets"],
            ["Network security group", "Firewall rules at the instance/vNIC level"],
            ["Network security list", "Firewall rules at the subnet level"],
            ["VPC", "Logically isolated virtual network in a public cloud"],
        ],
        "explain": "The VPC is the container; gateways define Internet reachability (IGW bidirectional, NAT outbound-only); and the two security constructs differ by scope — groups per instance, lists per subnet.",
    },
    {
        "type": "match",
        "q": "Match each service model to what the CUSTOMER manages.",
        "pairs": [
            ["IaaS", "Operating system, middleware, applications, and data"],
            ["PaaS", "Only application code and data"],
            ["SaaS", "Only data, users, and application settings"],
            ["On-premises", "The entire stack including hardware"],
        ],
        "explain": "Responsibility shrinks up the ladder: on-prem = everything; IaaS = OS and above; PaaS = code and data; SaaS = essentially configuration and data. The provider absorbs whatever the customer sheds — that is the shared responsibility model.",
    },
    {
        "type": "match",
        "q": "Match each deployment model or characteristic to its description.",
        "pairs": [
            ["Public cloud", "Shared provider infrastructure, pay-as-you-go"],
            ["Private cloud", "Dedicated to a single organization"],
            ["Hybrid cloud", "Integrated mix enabling cloud bursting"],
            ["Scalability", "Ability to grow capacity to meet demand"],
            ["Elasticity", "Automatic growth and shrinkage with demand"],
        ],
        "explain": "Deployment models describe who shares the infrastructure; scalability vs. elasticity describes how capacity changes — the ability to grow versus automatic bidirectional adjustment in real time.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the path of a patch download initiated by a VM in a PRIVATE subnet, from first to last.",
        "items": [
            "VM in the private subnet initiates an outbound request",
            "The private subnet's route table forwards the traffic to the NAT gateway",
            "The NAT gateway translates the source address to its public IP",
            "Traffic exits to the Internet through the internet gateway",
            "Return traffic is matched to the session and delivered back to the VM",
        ],
        "explain": "Private instances have no public IPs, so their outbound traffic is routed to the NAT gateway, which translates addresses and (sitting in a public subnet) uses the internet gateway to reach the Internet. Only reply traffic for that session is allowed back in.",
    },
    {
        "type": "order",
        "q": "Arrange the service models by increasing PROVIDER responsibility (least provider-managed first).",
        "items": ["On-premises", "IaaS", "PaaS", "SaaS"],
        "explain": "On-premises means the provider manages nothing; with IaaS the provider takes hardware and virtualization; with PaaS it adds the OS and runtime; with SaaS it manages the entire application stack, leaving the customer only data and settings.",
    },
]
