TOPIC = {
    "id": "1.4",
    "domain": 1,
    "title": "Explain common networking ports, protocols, services, and traffic types.",
    "short": "Ports & Protocols",
}

TERMS = [
    ("FTP (File Transfer Protocol)", "TCP 20/21 - cleartext file transfer; port 21 carries control/commands, port 20 carries data in active mode"),
    ("SFTP (Secure File Transfer Protocol)", "TCP 22 - encrypted file transfer running as a subsystem of SSH, so it shares SSH's port"),
    ("SSH (Secure Shell)", "TCP 22 - encrypted remote command-line administration; the secure replacement for Telnet"),
    ("Telnet", "TCP 23 - legacy cleartext remote CLI access; sends credentials unencrypted and should be replaced by SSH"),
    ("SMTP (Simple Mail Transfer Protocol)", "TCP 25 - sends/relays email between mail servers, unencrypted"),
    ("DNS (Domain Name System)", "Port 53 - resolves names to IP addresses; UDP for normal queries, TCP for zone transfers and large responses"),
    ("DHCP (Dynamic Host Configuration Protocol)", "UDP 67/68 - automatic IP configuration; server listens on 67, client on 68 (DORA process)"),
    ("TFTP (Trivial File Transfer Protocol)", "UDP 69 - minimal, unauthenticated file transfer used for firmware, configs, and PXE boot"),
    ("HTTP (Hypertext Transfer Protocol)", "TCP 80 - unencrypted web traffic; secure replacement is HTTPS on 443"),
    ("NTP (Network Time Protocol)", "UDP 123 - synchronizes device clocks across the network using a stratum hierarchy"),
    ("SNMP (Simple Network Management Protocol)", "UDP 161/162 - device monitoring; manager polls agents on 161, agents send traps to manager on 162"),
    ("LDAP (Lightweight Directory Access Protocol)", "TCP 389 - queries directory services such as Active Directory, unencrypted; LDAPS on 636 is the secure form"),
    ("HTTPS (HTTP Secure)", "TCP 443 - web traffic encrypted with TLS"),
    ("SMB (Server Message Block)", "TCP 445 - Windows file and printer sharing; also used by NAS appliances"),
    ("Syslog", "UDP 514 - forwards event/log messages from devices to a central logging collector"),
    ("SMTPS (SMTP Secure)", "TCP 587 - authenticated, TLS-encrypted email submission from clients to mail servers"),
    ("LDAPS (LDAP over SSL)", "TCP 636 - encrypted directory service queries"),
    ("SQL Server", "TCP 1433 - Microsoft SQL Server database connections"),
    ("RDP (Remote Desktop Protocol)", "TCP 3389 - graphical remote control of Windows systems"),
    ("SIP (Session Initiation Protocol)", "Ports 5060/5061 - sets up and tears down VoIP calls; 5060 unencrypted, 5061 TLS-encrypted"),
    ("ICMP (Internet Control Message Protocol)", "IP protocol 1, Layer 3, no ports - diagnostics: Echo Request/Reply (ping), Destination Unreachable, Time Exceeded"),
    ("TCP (Transmission Control Protocol)", "Connection-oriented Layer 4 transport - three-way handshake, sequencing, ACKs, retransmission, windowing; PDU is the segment"),
    ("UDP (User Datagram Protocol)", "Connectionless Layer 4 transport - no handshake or reliability, minimal overhead for real-time traffic; PDU is the datagram"),
    ("GRE (Generic Routing Encapsulation)", "IP protocol 47 - tunnels packets (including multicast/routing protocols) inside IP; provides no encryption"),
    ("IPSec", "Layer 3 security framework for VPNs providing authentication, integrity, and encryption via AH, ESP, and IKE"),
    ("AH (Authentication Header)", "IPSec protocol 51 - integrity and origin authentication only, NO encryption; breaks through NAT"),
    ("ESP (Encapsulating Security Payload)", "IPSec protocol 50 - encryption plus integrity and authentication; the workhorse of real IPSec VPNs"),
    ("IKE (Internet Key Exchange)", "UDP 500 - authenticates IPSec peers and negotiates security associations/session keys; NAT-T uses UDP 4500"),
    ("Unicast", "One-to-one traffic from a single sender to a single specific receiver - most network traffic"),
    ("Multicast", "One-to-many traffic delivered only to hosts that joined a group; IPv4 range 224.0.0.0/4, managed by IGMP"),
    ("Anycast", "One-to-nearest: the same IP is advertised from multiple locations and routing delivers to the closest instance (DNS root servers, CDNs)"),
    ("Broadcast", "One-to-all traffic to every host on the segment (255.255.255.255 / FF:FF:FF:FF:FF:FF); blocked by routers; absent in IPv6"),
]

QUESTIONS = [
    # --- multiple choice: ports ---
    {
        "type": "mc",
        "q": "A technician must open the firewall for secure remote command-line administration of a router. Which port should be opened?",
        "choices": ["TCP 23", "TCP 22", "TCP 3389", "UDP 69"],
        "answer": 1,
        "explain": "SSH provides encrypted CLI administration on TCP 22 and is the secure replacement for Telnet (TCP 23, cleartext). RDP on 3389 is graphical remote control, and TFTP on UDP 69 is file transfer.",
    },
    {
        "type": "mc",
        "q": "Which two ports does FTP use, and for what?",
        "choices": [
            "20 for control, 21 for data",
            "21 for control, 22 for data",
            "20 for data, 21 for control",
            "22 for data, 23 for control",
        ],
        "answer": 2,
        "explain": "FTP uses TCP 21 as the control channel (commands, login) and TCP 20 for the data channel in active mode. Both credentials and files travel in cleartext, which is why SFTP (TCP 22) is the secure replacement.",
    },
    {
        "type": "mc",
        "q": "Which port carries UNENCRYPTED web traffic, and which carries TLS-encrypted web traffic?",
        "choices": ["80 and 443", "443 and 80", "80 and 8080", "25 and 443"],
        "answer": 0,
        "explain": "HTTP uses TCP 80 with no encryption; HTTPS wraps HTTP in TLS on TCP 443. Hardening guidance is to redirect or block 80 in favor of 443.",
    },
    {
        "type": "mc",
        "q": "DHCP uses which pair of UDP ports?",
        "choices": ["68 server / 67 client", "67 server / 68 client", "53 server / 54 client", "161 server / 162 client"],
        "answer": 1,
        "explain": "The DHCP server listens on UDP 67 and the client uses UDP 68 during the DORA exchange (Discover, Offer, Request, Acknowledge). Memory hook: the server answers first and has the lower number.",
    },
    {
        "type": "mc",
        "q": "A network administrator wants routers and switches to send their event logs to a central collector. Which port must be permitted?",
        "choices": ["UDP 123", "TCP 445", "UDP 514", "TCP 636"],
        "answer": 2,
        "explain": "Syslog uses UDP 514 to forward log/event messages to a central syslog collector or SIEM. NTP is UDP 123, SMB is TCP 445, and LDAPS is TCP 636.",
    },
    {
        "type": "mc",
        "q": "Which port does the Network Time Protocol use to synchronize device clocks?",
        "choices": ["UDP 69", "TCP 179", "UDP 161", "UDP 123"],
        "answer": 3,
        "explain": "NTP runs on UDP 123 and keeps clocks synchronized via a stratum hierarchy — essential for accurate logs, certificates, and authentication. UDP 69 is TFTP and UDP 161 is SNMP polling.",
    },
    {
        "type": "mc",
        "q": "An SNMP-managed switch needs to send unsolicited alerts (traps) to the monitoring server. Which port receives them?",
        "choices": ["UDP 162", "UDP 161", "TCP 514", "UDP 123"],
        "answer": 0,
        "explain": "SNMP managers poll agents on UDP 161, while agents send unsolicited trap notifications to the manager on UDP 162. Remember: 161 = ask, 162 = alert.",
    },
    {
        "type": "mc",
        "q": "Which port must be open for clients to query an Active Directory domain controller using UNENCRYPTED LDAP?",
        "choices": ["TCP 636", "TCP 389", "TCP 443", "TCP 3389"],
        "answer": 1,
        "explain": "Plain LDAP uses TCP 389; its TLS/SSL-secured version, LDAPS, uses TCP 636. Directory lookups against Active Directory are the classic use case.",
    },
    {
        "type": "mc",
        "q": "Windows file sharing to a NAS appliance uses which protocol and port?",
        "choices": ["NFS on TCP 2049", "SMB on TCP 445", "FTP on TCP 21", "SMB on TCP 389"],
        "answer": 1,
        "explain": "Server Message Block (SMB) on TCP 445 provides Windows file and printer sharing and is the standard access protocol for NAS shares in Windows environments. LDAP is 389; NFS (used by Unix/Linux NAS clients) is not in the N10-009 port table.",
    },
    {
        "type": "mc",
        "q": "A mail client must submit outgoing email over an encrypted, authenticated connection. Which protocol and port should it use?",
        "choices": ["SMTP on TCP 25", "SMTPS on TCP 587", "SNMP on UDP 161", "SMTPS on TCP 465"],
        "answer": 1,
        "explain": "Per the N10-009 objectives, SMTPS on TCP 587 provides TLS-encrypted, authenticated mail submission from clients, while plain SMTP server-to-server relay uses TCP 25. (Port 465 is legacy implicit-TLS SMTPS, but 587 is the exam answer.)",
    },
    {
        "type": "mc",
        "q": "Which port does Microsoft SQL Server use for database connections?",
        "choices": ["TCP 1433", "TCP 3389", "TCP 1521", "TCP 3306"],
        "answer": 0,
        "explain": "Microsoft SQL Server listens on TCP 1433. Don't confuse it with RDP's 3389, Oracle's 1521, or MySQL's 3306 — the exam objective lists SQL Server 1433.",
    },
    {
        "type": "mc",
        "q": "A help desk technician needs full graphical control of a remote user's Windows desktop. Which port must be reachable?",
        "choices": ["TCP 22", "TCP 445", "TCP 3389", "TCP 1433"],
        "answer": 2,
        "explain": "Remote Desktop Protocol (RDP) uses TCP 3389 (with a UDP 3389 option) for graphical remote control of Windows systems. SSH on 22 is command-line only.",
    },
    {
        "type": "mc",
        "q": "Which ports are used by SIP to set up VoIP calls, unencrypted and TLS-encrypted respectively?",
        "choices": ["5060 and 5061", "5004 and 5005", "1720 and 1721", "5061 and 5060"],
        "answer": 0,
        "explain": "SIP signals call setup and teardown on port 5060 (unencrypted, TCP or UDP) and 5061 (TLS-encrypted). SIP only manages the session — the voice media itself typically flows over RTP/UDP.",
    },
    {
        "type": "mc",
        "q": "A switch needs its firmware image pulled from a server using a simple, connectionless, no-login protocol. Which protocol and port?",
        "choices": ["FTP on TCP 21", "SFTP on TCP 22", "TFTP on UDP 69", "HTTP on TCP 80"],
        "answer": 2,
        "explain": "TFTP uses UDP 69 with no authentication and minimal overhead, making it the traditional choice for transferring firmware and config files to network devices and for PXE boot. FTP/SFTP are heavier, TCP-based, and authenticated.",
    },
    {
        "type": "mc",
        "q": "DNS zone transfers between a primary and secondary name server use which transport and port?",
        "choices": ["UDP 53", "TCP 53", "UDP 67", "TCP 389"],
        "answer": 1,
        "explain": "Ordinary DNS queries use UDP 53 for speed, but zone transfers (and responses too large for UDP) use TCP 53 because reliable, ordered delivery is required for replicating the whole zone.",
    },
    {
        "type": "mc",
        "q": "A security audit finds Telnet enabled on network devices. What should replace it, and which ports are involved?",
        "choices": [
            "Replace Telnet (TCP 23) with SSH (TCP 22)",
            "Replace Telnet (TCP 21) with SSH (TCP 23)",
            "Replace Telnet (TCP 23) with RDP (TCP 443)",
            "Replace Telnet (TCP 25) with SFTP (TCP 22)",
        ],
        "answer": 0,
        "explain": "Telnet on TCP 23 transmits everything, including credentials, in cleartext. SSH on TCP 22 provides the same remote CLI capability fully encrypted — one of the classic insecure-to-secure protocol swaps.",
    },
    {
        "type": "mc",
        "q": "Which set pairs each insecure protocol with its secure replacement correctly?",
        "choices": [
            "HTTP→HTTPS, FTP→TFTP, LDAP→LDAPS",
            "HTTP→HTTPS, FTP→SFTP, LDAP→LDAPS",
            "HTTP→SMB, FTP→SFTP, LDAP→SNMP",
            "HTTP→HTTPS, Telnet→RDP, LDAP→LDAPS",
        ],
        "answer": 1,
        "explain": "The secure swaps are HTTP (80) → HTTPS (443), FTP (20/21) → SFTP (22), LDAP (389) → LDAPS (636), Telnet (23) → SSH (22), and SMTP (25) → SMTPS (587). TFTP is even LESS secure than FTP — no authentication at all.",
    },
    # --- multiple choice: IP types ---
    {
        "type": "mc",
        "q": "Which ICMP message types are used by the ping utility?",
        "choices": [
            "Type 3 Destination Unreachable and Type 5 Redirect",
            "Type 11 Time Exceeded and Type 3 Unreachable",
            "Type 8 Echo Request and Type 0 Echo Reply",
            "Type 13 Timestamp and Type 14 Timestamp Reply",
        ],
        "answer": 2,
        "explain": "Ping sends ICMP Echo Request (Type 8) and expects Echo Reply (Type 0), verifying reachability and measuring round-trip time. Traceroute instead relies on Time Exceeded (Type 11) messages from each hop.",
    },
    {
        "type": "mc",
        "q": "Traceroute discovers each router along a path by triggering which ICMP message?",
        "choices": ["Echo Reply (Type 0)", "Time Exceeded (Type 11)", "Redirect (Type 5)", "Source Quench (Type 4)"],
        "answer": 1,
        "explain": "Traceroute sends probes with incrementing TTLs (1, 2, 3...). Each router that decrements a TTL to 0 drops the probe and returns ICMP Time Exceeded (Type 11), revealing its address — mapping the path hop by hop.",
    },
    {
        "type": "mc",
        "q": "A router cannot deliver a packet to its destination network. Which ICMP message does it send to the source?",
        "choices": ["Destination Unreachable (Type 3)", "Echo Request (Type 8)", "Time Exceeded (Type 11)", "Router Advertisement (Type 9)"],
        "answer": 0,
        "explain": "ICMP Destination Unreachable (Type 3) reports failed delivery, with codes such as network unreachable, host unreachable, and port unreachable. It is a core diagnostic signal in troubleshooting connectivity.",
    },
    {
        "type": "mc",
        "q": "What is the correct sequence of the TCP three-way handshake?",
        "choices": [
            "SYN → ACK → SYN-ACK",
            "SYN-ACK → SYN → ACK",
            "ACK → SYN → SYN-ACK",
            "SYN → SYN-ACK → ACK",
        ],
        "answer": 3,
        "explain": "The client sends SYN, the server replies SYN-ACK, and the client completes with ACK — establishing sequence numbers in both directions before any data flows. This handshake is what makes TCP connection-oriented.",
    },
    {
        "type": "mc",
        "q": "Which TCP feature lets a receiver tell the sender how much data it can accept before being overwhelmed?",
        "choices": ["Sequencing", "Sliding window (flow control)", "Three-way handshake", "Checksum"],
        "answer": 1,
        "explain": "TCP flow control uses a sliding window: the receiver advertises available buffer space and the sender may not exceed it. The window grows and shrinks dynamically as ACKs arrive and buffers fill.",
    },
    {
        "type": "mc",
        "q": "A live VoIP audio stream should tolerate occasional packet loss but cannot tolerate retransmission delays. Which transport protocol is appropriate and why?",
        "choices": [
            "TCP, because it retransmits lost packets",
            "TCP, because it uses smaller headers",
            "UDP, because it is connectionless with minimal overhead",
            "UDP, because it guarantees ordered delivery",
        ],
        "answer": 2,
        "explain": "Real-time media uses UDP: no handshake, no ACKs, no retransmission — a late retransmitted voice packet would be useless anyway. TCP's reliability mechanisms add latency that damages call quality more than a lost packet does.",
    },
    {
        "type": "mc",
        "q": "Which protocol tunnels almost any traffic — including multicast and routing-protocol packets — across an IP network but provides NO encryption?",
        "choices": ["GRE", "ESP", "SFTP", "LDAPS"],
        "answer": 0,
        "explain": "Generic Routing Encapsulation (IP protocol 47) wraps packets in a new IP header to form a virtual point-to-point tunnel and can carry multicast and routing protocols that plain IPSec cannot. Since GRE offers no confidentiality, it is commonly run over IPSec (GRE over IPSec).",
    },
    {
        "type": "mc",
        "q": "Which IPSec protocol provides ENCRYPTION of the payload, and what is its IP protocol number?",
        "choices": ["AH, protocol 51", "ESP, protocol 50", "IKE, protocol 500", "GRE, protocol 47"],
        "answer": 1,
        "explain": "Encapsulating Security Payload (ESP) is IP protocol 50 and provides confidentiality (encryption) plus integrity, authentication, and anti-replay. AH (protocol 51) provides integrity only — never encryption. IKE uses UDP port 500, not IP protocol 500.",
    },
    {
        "type": "mc",
        "q": "What does the IPSec Authentication Header (AH) provide, and what does it NOT provide?",
        "choices": [
            "Provides encryption; does not provide integrity",
            "Provides integrity and origin authentication; does not provide encryption",
            "Provides key exchange; does not provide authentication",
            "Provides compression; does not provide anti-replay",
        ],
        "answer": 1,
        "explain": "AH (IP protocol 51) hashes the packet, including immutable header fields, to guarantee integrity and authenticity with anti-replay — but the payload stays readable. Because NAT rewrites fields AH protects, AH breaks through NAT, another reason ESP dominates.",
    },
    {
        "type": "mc",
        "q": "Which component of IPSec negotiates security associations and session keys between VPN peers, and on which port?",
        "choices": ["ESP on TCP 50", "AH on UDP 51", "IKE on UDP 500", "IKE on TCP 443"],
        "answer": 2,
        "explain": "Internet Key Exchange (IKE) runs over UDP 500, authenticating the peers and negotiating the security associations and keys (via Diffie-Hellman) before AH/ESP traffic flows. When NAT is detected, NAT-Traversal encapsulates ESP in UDP 4500.",
    },
    {
        "type": "mc",
        "q": "A site-to-site IPSec VPN between two office firewalls must encrypt entire original packets, including their IP headers. Which mode is required?",
        "choices": ["Transport mode", "Tunnel mode", "Aggressive mode", "Main mode"],
        "answer": 1,
        "explain": "Tunnel mode encapsulates the whole original packet (header and payload) inside a new IP packet — standard for gateway-to-gateway site-to-site VPNs. Transport mode protects only the payload and leaves the original header exposed, typical for host-to-host security.",
    },
    {
        "type": "mc",
        "q": "A firewall must pass an IPSec VPN using ESP with IKE. Which THREE things must be permitted?",
        "choices": [
            "TCP 50, TCP 51, and UDP 4500",
            "IP protocol 50, IP protocol 51 optionally, and UDP 500",
            "UDP 50, UDP 51, and TCP 500",
            "IP protocol 6, IP protocol 17, and TCP 443",
        ],
        "answer": 1,
        "explain": "ESP is IP protocol 50 and AH is IP protocol 51 — these are IP protocol numbers, not TCP/UDP ports — while IKE key negotiation uses UDP port 500 (plus UDP 4500 for NAT-Traversal). Confusing protocol numbers with port numbers is a classic exam trap.",
    },
    # --- multiple choice: traffic types ---
    {
        "type": "mc",
        "q": "A video server sends one stream that is received only by the hosts that have joined group 239.1.1.1. What traffic type is this?",
        "choices": ["Unicast", "Broadcast", "Multicast", "Anycast"],
        "answer": 2,
        "explain": "Multicast is one-to-many delivery to subscribed group members only, using the IPv4 Class D range 224.0.0.0/4 (224.0.0.0–239.255.255.255). Hosts join and leave groups using IGMP, and the network replicates packets only where paths diverge.",
    },
    {
        "type": "mc",
        "q": "DNS root servers advertise the same IP address from many locations worldwide, and each query is routed to the topologically nearest instance. What traffic/addressing type is this?",
        "choices": ["Anycast", "Multicast", "Broadcast", "Unicast"],
        "answer": 0,
        "explain": "Anycast assigns one IP to multiple servers; routing (BGP) delivers each packet to the nearest instance. It gives DNS root servers and CDNs low latency, load distribution, and resilience — if one node fails, traffic converges to the next nearest.",
    },
    {
        "type": "mc",
        "q": "Which protocol do hosts use to join and leave IPv4 multicast groups?",
        "choices": ["ICMP", "IGMP", "ARP", "SNMP"],
        "answer": 1,
        "explain": "The Internet Group Management Protocol (IGMP) manages IPv4 multicast group membership between hosts and routers; switches use IGMP snooping to send streams only to interested ports. ICMP is diagnostics, ARP resolves MACs, SNMP is management.",
    },
    {
        "type": "mc",
        "q": "A DHCP Discover message sent to 255.255.255.255 is an example of which traffic type, and which device stops it?",
        "choices": [
            "Broadcast, stopped by routers",
            "Multicast, stopped by switches",
            "Anycast, stopped by firewalls",
            "Broadcast, forwarded by routers by default",
        ],
        "answer": 0,
        "explain": "255.255.255.255 is the limited broadcast address, delivered to every host on the local segment (L2 destination FF:FF:FF:FF:FF:FF). Routers do not forward broadcasts — they bound the broadcast domain, which is why DHCP relay/IP helper exists for remote subnets.",
    },
    {
        "type": "mc",
        "q": "Which traffic type does IPv6 ELIMINATE entirely, and what replaces it?",
        "choices": [
            "Multicast, replaced by broadcast",
            "Unicast, replaced by anycast",
            "Broadcast, replaced by multicast",
            "Anycast, replaced by unicast",
        ],
        "answer": 2,
        "explain": "IPv6 has no broadcast. Functions that used broadcast in IPv4 (like ARP) are handled with multicast — e.g., the all-nodes group ff02::1 and solicited-node multicast for Neighbor Discovery.",
    },
    # --- true/false ---
    {
        "type": "tf",
        "q": "True or False: SFTP and SSH both use TCP port 22.",
        "answer": True,
        "explain": "SFTP is not a standalone protocol — it runs as a subsystem inside an SSH session, so it inherits SSH's TCP port 22 and its encryption. This is why the objectives list both at 22.",
    },
    {
        "type": "tf",
        "q": "True or False: UDP establishes a connection with a handshake before sending data.",
        "answer": False,
        "explain": "UDP is connectionless — no handshake, no ACKs, no retransmission, no flow control. It simply sends datagrams with an 8-byte header, which is exactly why it is fast and favored for DNS queries, VoIP, and streaming.",
    },
    {
        "type": "tf",
        "q": "True or False: The IPSec Authentication Header (AH) encrypts the packet payload.",
        "answer": False,
        "explain": "AH (IP protocol 51) provides integrity, origin authentication, and anti-replay protection but performs NO encryption — the payload remains readable. Confidentiality requires ESP (IP protocol 50).",
    },
    {
        "type": "tf",
        "q": "True or False: ICMP does not use TCP or UDP port numbers.",
        "answer": True,
        "explain": "ICMP is IP protocol 1, riding directly inside IP at Layer 3 with message types and codes instead of ports. That's why you cannot 'open a port' for ping — firewalls filter ICMP by protocol and type.",
    },
    {
        "type": "tf",
        "q": "True or False: In IPSec transport mode, the original IP header remains visible and only the payload is protected.",
        "answer": True,
        "explain": "Transport mode protects just the payload, keeping the original header for routing — typical for host-to-host security. Tunnel mode wraps the entire original packet in a new IP header, standard for site-to-site VPN gateways.",
    },
    {
        "type": "tf",
        "q": "True or False: Ordinary DNS name lookups typically use TCP port 53.",
        "answer": False,
        "explain": "Standard queries use UDP 53 for low overhead; TCP 53 is reserved for zone transfers between servers and for responses too large to fit in UDP. Both transports on port 53 belong to DNS.",
    },
    # --- fill in ---
    {
        "type": "fill",
        "q": "Secure web traffic (HTTPS) uses TCP port ______. (type the number)",
        "answers": ["443"],
        "explain": "HTTPS encrypts HTTP with TLS on TCP 443. Its insecure counterpart HTTP uses TCP 80 — one of the fundamental secure/insecure port pairs.",
    },
    {
        "type": "fill",
        "q": "The Remote Desktop Protocol (RDP) uses port ______. (type the number)",
        "answers": ["3389"],
        "explain": "RDP provides graphical remote control of Windows machines on TCP 3389 (with a UDP option on the same number). Exposed RDP is a favorite attack target, so it should be firewalled or reached via VPN.",
    },
    {
        "type": "fill",
        "q": "The secure, TLS-encrypted version of LDAP (LDAPS) uses TCP port ______. (type the number)",
        "answers": ["636"],
        "explain": "LDAPS wraps directory traffic in TLS/SSL on TCP 636, replacing cleartext LDAP on TCP 389. Remember the pair 389 → 636 alongside 80 → 443 and 23 → 22.",
    },
    {
        "type": "fill",
        "q": "The IPSec component that negotiates security associations over UDP port 500 is known by the acronym ______. (type the acronym)",
        "answers": ["ike", "internet key exchange"],
        "explain": "Internet Key Exchange (IKE) authenticates the two VPN peers and negotiates algorithms and session keys before ESP or AH traffic flows. Its NAT-Traversal variant uses UDP 4500.",
    },
    {
        "type": "fill",
        "q": "IPv4 multicast uses the Class D address block ______/4. (type the network address)",
        "answers": ["224.0.0.0", "224.0.0.0/4", "224"],
        "explain": "The multicast range is 224.0.0.0/4, spanning 224.0.0.0 through 239.255.255.255. Group membership is managed by IGMP, and routing protocols like OSPF use reserved groups such as 224.0.0.5.",
    },
    {
        "type": "fill",
        "q": "The traffic type in which one address is shared by many servers and packets are delivered to the NEAREST instance is called ______. (type your answer)",
        "answers": ["anycast"],
        "explain": "Anycast advertises the same IP from multiple locations and lets routing pick the closest — the design behind DNS root servers and CDN entry points. It provides low latency, load spreading, and automatic failover.",
    },
    # --- matching ---
    {
        "type": "match",
        "q": "Match each protocol to its port number.",
        "pairs": [
            ["SSH", "22"],
            ["Telnet", "23"],
            ["SMTP", "25"],
            ["DNS", "53"],
            ["HTTP", "80"],
            ["HTTPS", "443"],
        ],
        "explain": "These are the highest-frequency ports on the exam: SSH 22, Telnet 23, SMTP 25, DNS 53, HTTP 80, HTTPS 443. Note the secure/insecure pairs hiding here: Telnet 23 → SSH 22 and HTTP 80 → HTTPS 443.",
    },
    {
        "type": "match",
        "q": "Match each protocol to its port number.",
        "pairs": [
            ["TFTP", "69"],
            ["NTP", "123"],
            ["SNMP (polling)", "161"],
            ["SMB", "445"],
            ["Syslog", "514"],
            ["SQL Server", "1433"],
        ],
        "explain": "TFTP 69, NTP 123, and SNMP 161/162 are all UDP, as is Syslog 514; SMB 445 and SQL Server 1433 are TCP. Grouping ports by transport protocol is a fast way to double-check answers.",
    },
    {
        "type": "match",
        "q": "Match each insecure protocol to its secure replacement.",
        "pairs": [
            ["Telnet (23)", "SSH (22)"],
            ["HTTP (80)", "HTTPS (443)"],
            ["FTP (20/21)", "SFTP (22)"],
            ["LDAP (389)", "LDAPS (636)"],
            ["SMTP (25)", "SMTPS (587)"],
        ],
        "explain": "Every cleartext protocol has an encrypted counterpart: SSH replaces Telnet, HTTPS replaces HTTP, SFTP (over SSH) replaces FTP, LDAPS replaces LDAP, and SMTPS on 587 secures mail submission. Hardening questions expect these swaps.",
    },
    {
        "type": "match",
        "q": "Match each IP protocol to its identifying number.",
        "pairs": [
            ["ICMP", "IP protocol 1"],
            ["TCP", "IP protocol 6"],
            ["UDP", "IP protocol 17"],
            ["GRE", "IP protocol 47"],
            ["ESP", "IP protocol 50"],
            ["AH", "IP protocol 51"],
        ],
        "explain": "These are IP protocol numbers in the IP header, not TCP/UDP ports: ICMP 1, TCP 6, UDP 17, GRE 47, ESP 50, AH 51. Firewall rules for VPNs must permit protocols 50/51 plus UDP port 500 for IKE.",
    },
    {
        "type": "match",
        "q": "Match each traffic type to its delivery pattern.",
        "pairs": [
            ["Unicast", "One sender to one specific receiver"],
            ["Multicast", "One sender to all subscribed group members"],
            ["Anycast", "One sender to the nearest of several servers sharing an IP"],
            ["Broadcast", "One sender to every host on the local segment"],
        ],
        "explain": "Unicast is one-to-one; multicast is one-to-group (224.0.0.0/4, IGMP); anycast is one-to-nearest (DNS root servers, CDNs); broadcast is one-to-all on the segment and does not cross routers — and does not exist in IPv6.",
    },
    # --- ordering ---
    {
        "type": "order",
        "q": "Arrange the steps of establishing a TCP connection and beginning data transfer, in order.",
        "items": [
            "Client sends SYN with its initial sequence number",
            "Server responds with SYN-ACK",
            "Client sends ACK completing the handshake",
            "Data segments flow with sequence numbers and acknowledgments",
        ],
        "explain": "The three-way handshake (SYN, SYN-ACK, ACK) synchronizes sequence numbers in both directions before any data moves. Data transfer then relies on sequencing, ACKs, retransmission, and windowed flow control — the pillars of TCP reliability.",
    },
    {
        "type": "order",
        "q": "Arrange these protocols by port number from LOWEST to HIGHEST.",
        "items": ["FTP (control)", "DNS", "NTP", "LDAP", "Syslog", "RDP"],
        "explain": "FTP control is 21, DNS is 53, NTP is 123, LDAP is 389, Syslog is 514, and RDP is 3389. Practicing the ordering forces exact recall of the numbers rather than rough familiarity.",
    },
    {
        "type": "order",
        "q": "Arrange the events when an IPSec site-to-site VPN comes up and protects traffic, in order.",
        "items": [
            "IKE peers authenticate each other over UDP 500",
            "Security associations and session keys are negotiated",
            "ESP (protocol 50) begins encrypting packets in tunnel mode",
            "Encrypted packets traverse the Internet between gateways",
        ],
        "explain": "IPSec always starts with IKE on UDP 500: peers authenticate, then negotiate SAs and keys (Diffie-Hellman). Only then does ESP carry encrypted traffic — in tunnel mode for site-to-site VPNs, wrapping entire original packets in new headers.",
    },
]
