TOPIC = {
    "id": "1.5",
    "domain": 1,
    "title": "Compare and contrast transmission media and transceivers",
    "short": "Media & Transceivers",
}

TERMS = [
    ("802.11n (Wi-Fi 4)", "Wireless standard operating on both 2.4 GHz and 5 GHz; introduced MIMO; max theoretical rate 600 Mbps"),
    ("802.11ac (Wi-Fi 5)", "Wireless standard operating on 5 GHz only; MU-MIMO and wide channels; max theoretical rate about 6.9 Gbps"),
    ("802.11ax (Wi-Fi 6/6E)", "Wireless standard on 2.4/5 GHz (6E adds 6 GHz); OFDMA for dense environments; max theoretical rate about 9.6 Gbps"),
    ("4G LTE", "All-IP cellular generation with theoretical peaks around 100-300 Mbps and latency of roughly 30-50 ms"),
    ("5G", "Cellular generation using low-band, mid-band, and mmWave spectrum; theoretical peaks up to 20 Gbps and latency as low as ~1 ms"),
    ("GEO satellite", "Satellite at ~35,786 km in geostationary orbit; fixed sky position but ~600 ms round-trip latency"),
    ("LEO satellite", "Low Earth orbit constellation (e.g., Starlink at ~550 km) delivering 20-50 ms latency suitable for real-time apps"),
    ("Single-mode fiber", "Fiber with an 8-10 micron core carrying laser light in a single path; spans tens of kilometers; yellow jacket typical"),
    ("Multimode fiber", "Fiber with a 50 or 62.5 micron core carrying LED/VCSEL light in multiple paths; limited to hundreds of meters by modal dispersion"),
    ("Direct attach copper (DAC)", "Fixed-length twinaxial cable with transceivers permanently attached at both ends; cheap short-reach 10G+ links such as top-of-rack"),
    ("Twinaxial cable", "Copper cable with two inner conductors in a shared shield; the medium inside DAC cables"),
    ("RG-6", "75-ohm coaxial cable with thick conductor and good shielding; used for cable TV/DOCSIS broadband and satellite feeds"),
    ("RG-59", "Thinner 75-ohm coaxial cable with higher loss; suited to short runs and analog CCTV video"),
    ("Plenum cable", "Cable with a fire-retardant, low-smoke jacket (CMP) required by fire code in air-handling spaces such as drop ceilings"),
    ("Fibre Channel (FC)", "Dedicated lossless storage-area network (SAN) protocol; uses its own transceivers, not interchangeable with Ethernet optics"),
    ("SFP", "Small form-factor pluggable transceiver supporting 1 Gbps; successor to the GBIC"),
    ("SFP+", "Enhanced small form-factor pluggable transceiver supporting 10 Gbps in the same size as SFP"),
    ("QSFP+", "Quad small form-factor pluggable transceiver supporting 40 Gbps as four 10 Gbps lanes; can break out to 4x10G"),
    ("QSFP28", "Quad transceiver supporting 100 Gbps as four 25 Gbps lanes; the standard 100G module"),
    ("LC connector", "Small square 'little connector' with a latch; the dominant fiber connector used with SFP/SFP+ modules"),
    ("SC connector", "Square push-pull snap-in fiber connector ('stick and click'); common on older patch panels and FTTH gear"),
    ("ST connector", "Round bayonet twist-lock fiber connector ('stick and twist') found in legacy multimode installs"),
    ("MPO connector", "Multi-fiber push-on connector carrying 12+ strands in one ferrule; used for 40G/100G parallel optics"),
    ("F-type connector", "Threaded screw-on coaxial connector used for cable TV, cable modems, and satellite receivers"),
    ("BNC connector", "Bayonet quarter-twist coaxial connector used on legacy 10BASE2 Ethernet, CCTV, and test equipment"),
    ("10GBASE-T", "10 Gbps Ethernet over twisted pair; 55 m on Cat 6 or the full 100 m on Cat 6a"),
]

QUESTIONS = [
    # --- multiple choice ---
    {"type": "mc",
     "q": "Which 802.11 standard operates ONLY in the 5 GHz band and offers a maximum theoretical data rate of about 6.9 Gbps?",
     "choices": ["802.11n", "802.11ax", "802.11ac", "802.11g"],
     "answer": 2,
     "explain": "802.11ac (Wi-Fi 5) is 5 GHz only and tops out around 6.9 Gbps using MU-MIMO, 256-QAM, and 80/160 MHz channels. 802.11n uses both 2.4 and 5 GHz at up to 600 Mbps, and 802.11ax adds 2.4 GHz (and 6 GHz for 6E) at up to 9.6 Gbps."},
    {"type": "mc",
     "q": "A client requests Wi-Fi 6E to take advantage of uncongested spectrum. Which IEEE standard and band does this refer to?",
     "choices": ["802.11ax in the 6 GHz band", "802.11ac in the 5 GHz band", "802.11ax in the 5 GHz band", "802.11be in the 2.4 GHz band"],
     "answer": 0,
     "explain": "Wi-Fi 6E is 802.11ax extended into the 6 GHz band, which only 6E-capable devices may use, so it is free of legacy congestion. Plain Wi-Fi 6 is the same 802.11ax standard limited to 2.4 and 5 GHz."},
    {"type": "mc",
     "q": "Which two 802.11 standards share the same 54 Mbps maximum data rate but use different frequency bands?",
     "choices": ["802.11b and 802.11g", "802.11a and 802.11g", "802.11a and 802.11n", "802.11g and 802.11n"],
     "answer": 1,
     "explain": "802.11a runs at 54 Mbps in 5 GHz while 802.11g runs at 54 Mbps in 2.4 GHz. The exam loves this pairing because the speeds match but the bands differ. 802.11b is only 11 Mbps and 802.11n reaches 600 Mbps."},
    {"type": "mc",
     "q": "A rural clinic complains that VoIP calls over its satellite link have roughly 600 ms of delay. What is the MOST likely cause?",
     "choices": ["The modem only supports 802.11b", "Insufficient bandwidth from the provider", "DNS misconfiguration on the router", "The service uses a GEO satellite at about 35,786 km altitude"],
     "answer": 3,
     "explain": "Geostationary satellites orbit at roughly 35,786 km, so the signal's round trip imposes ~500-700 ms of propagation latency no matter how much bandwidth is purchased. LEO constellations such as Starlink orbit at ~550 km and cut latency to 20-50 ms, which is why they can support VoIP and gaming."},
    {"type": "mc",
     "q": "Which 5G spectrum range offers multi-gigabit speeds but is easily blocked by walls and has very short range?",
     "choices": ["Low-band (below 1 GHz)", "mmWave (24 GHz and above)", "Mid-band (1-6 GHz)", "The 2.4 GHz ISM band"],
     "answer": 1,
     "explain": "Millimeter wave (mmWave) frequencies above 24 GHz deliver the headline multi-gigabit 5G speeds but propagate poorly, failing to penetrate walls or foliage. Low-band travels far with modest speed gains, and mid-band is the compromise most carriers rely on."},
    {"type": "mc",
     "q": "What is the maximum segment length for 1000BASE-T Ethernet, and what minimum cable category does it require?",
     "choices": ["100 m on Cat 5e", "55 m on Cat 6", "100 m on Cat 3", "90 m on Cat 6a"],
     "answer": 0,
     "explain": "1000BASE-T (Gigabit Ethernet) runs up to the standard 100-meter twisted-pair limit and requires at least Cat 5e. The 55 m figure applies to 10GBASE-T over plain Cat 6, a different standard."},
    {"type": "mc",
     "q": "A technician must run 10GBASE-T the full 100 meters to a wiring closet. Which cable is the MINIMUM category that supports this?",
     "choices": ["Cat 5e", "Cat 6", "Cat 6a", "Cat 8"],
     "answer": 2,
     "explain": "Plain Cat 6 (250 MHz) only carries 10GBASE-T about 55 meters; Cat 6a (augmented, 500 MHz) restores the full 100 m reach. Cat 8 would also work but is a 30 m data-center cable and far from the minimum, while Cat 5e tops out at 1 Gbps."},
    {"type": "mc",
     "q": "Which Ethernet standard uses single-mode fiber at 1310 nm to reach 10 km at 10 Gbps?",
     "choices": ["10GBASE-SR", "1000BASE-LX", "1000BASE-SX", "10GBASE-LR"],
     "answer": 3,
     "explain": "10GBASE-LR (L = long) uses 1310 nm lasers over single-mode fiber for 10 km at 10 Gbps. 10GBASE-SR (S = short) is the multimode version limited to 300-400 m, and 1000BASE-LX is the 1 Gbps long-reach standard."},
    {"type": "mc",
     "q": "What is the maximum distance of 10GBASE-SR over OM3 multimode fiber?",
     "choices": ["100 m", "300 m", "10 km", "550 m"],
     "answer": 1,
     "explain": "10GBASE-SR reaches 300 m over laser-optimized OM3 multimode fiber (400 m over OM4). The 550 m figure belongs to 1000BASE-SX/LX over multimode, and 10 km requires single-mode 10GBASE-LR."},
    {"type": "mc",
     "q": "Which core diameter identifies single-mode fiber?",
     "choices": ["50 microns", "62.5 microns", "125 microns", "8-10 microns"],
     "answer": 3,
     "explain": "Single-mode fiber has a tiny 8-10 micron core that forces light from a laser down a single path, enabling runs of tens of kilometers. Multimode cores are 50 or 62.5 microns, and 125 microns is the cladding diameter shared by both types."},
    {"type": "mc",
     "q": "Why is multimode fiber limited to shorter distances than single-mode fiber?",
     "choices": ["Modal dispersion causes multiple light paths to arrive at different times", "Its copper core attenuates the signal", "It is more susceptible to EMI", "LED light travels slower than laser light"],
     "answer": 0,
     "explain": "Multimode's wide 50/62.5 micron core lets light take many paths (modes) that arrive slightly out of step; over distance this modal dispersion smears the signal. All fiber is immune to EMI, and fiber has a glass core, not copper."},
    {"type": "mc",
     "q": "A data-center engineer needs the least expensive way to connect servers to the switch at the top of the same rack at 10 Gbps. Which media is the BEST choice?",
     "choices": ["10GBASE-LR single-mode fiber", "Cat 5e patch cords", "DAC twinaxial cables", "RG-6 coaxial cable"],
     "answer": 2,
     "explain": "Direct attach copper (DAC) twinax cables with integrated SFP+ ends are the classic top-of-rack solution: cheaper and lower power than optical transceivers for runs of a few meters. Cat 5e cannot carry 10 Gbps and LR optics are overkill for in-rack distances."},
    {"type": "mc",
     "q": "How does twinaxial cable differ from coaxial cable?",
     "choices": ["Twinax uses fiber strands instead of copper", "Twinax has two inner conductors inside the shield instead of one", "Twinax is unshielded", "Twinax supports runs of several kilometers"],
     "answer": 1,
     "explain": "Twinaxial cable places two inner conductors within a common shield, whereas coax has a single center conductor. Twinax is the copper medium inside DAC cables and is limited to short reaches of roughly 1-10 meters."},
    {"type": "mc",
     "q": "Which coaxial cable type is standard for modern cable-TV and DOCSIS cable-modem installations?",
     "choices": ["RG-59", "RG-8", "Twinax", "RG-6"],
     "answer": 3,
     "explain": "RG-6 is the 75-ohm coax used for CATV, cable broadband, and satellite feeds thanks to its thicker conductor and better shielding. RG-59 is a thinner, lossier 75-ohm cable relegated to short patch runs and analog CCTV."},
    {"type": "mc",
     "q": "New cabling must be pulled through the air-handling space above a drop ceiling. Which cable is required by fire code?",
     "choices": ["Plenum-rated (CMP) cable", "Riser-rated (CMR) cable", "Standard PVC-jacketed cable", "Direct-burial cable"],
     "answer": 0,
     "explain": "Plenum spaces circulate building air, so code requires plenum-rated (CMP) cable whose jacket resists fire and emits minimal toxic smoke. Riser (CMR) cable is for vertical runs between floors and ordinary PVC jackets are prohibited in plenums."},
    {"type": "mc",
     "q": "What distinguishes plenum cable from non-plenum cable?",
     "choices": ["Plenum cable supports higher data rates", "Plenum cable has a fire-retardant, low-smoke jacket", "Plenum cable is always shielded against EMI", "Plenum cable uses thicker copper conductors"],
     "answer": 1,
     "explain": "The plenum rating is purely about the jacket material and fire safety, not electrical performance. A plenum Cat 6 cable carries data identically to non-plenum Cat 6; it simply burns more slowly and releases less toxic smoke."},
    {"type": "mc",
     "q": "A storage administrator is ordering optics to connect servers to a SAN switch. Which transceiver protocol should be specified?",
     "choices": ["DOCSIS", "Ethernet", "Fibre Channel", "SONET"],
     "answer": 2,
     "explain": "Fibre Channel is the dedicated lossless protocol for storage area networks, and FC links require Fibre Channel transceivers. Even though the module and LC connector may look identical, Ethernet and Fibre Channel optics are not interchangeable."},
    {"type": "mc",
     "q": "Which transceiver form factor supports 40 Gbps by combining four 10 Gbps lanes?",
     "choices": ["SFP+", "QSFP28", "SFP28", "QSFP+"],
     "answer": 3,
     "explain": "QSFP+ (quad SFP+) bundles four 10G lanes for 40 Gigabit Ethernet and can break out to four separate SFP+ links with a fanout cable. QSFP28 is the 100G module (4x25G), SFP+ is a single 10G lane, and SFP28 is a single 25G lane."},
    {"type": "mc",
     "q": "A switch upgrade requires 100 Gbps uplinks. Which module should be purchased?",
     "choices": ["QSFP28", "QSFP+", "SFP+", "SFP"],
     "answer": 0,
     "explain": "QSFP28 delivers 100 Gbps using four 25 Gbps lanes and is the standard 100G form factor. QSFP+ maxes out at 40G, SFP+ at 10G, and SFP at 1G."},
    {"type": "mc",
     "q": "Which connector is a small square fiber connector with a latch, commonly inserted into SFP and SFP+ modules?",
     "choices": ["SC", "LC", "ST", "MPO"],
     "answer": 1,
     "explain": "The LC (local connector, nicknamed 'little connector') is about half the size of SC and is the dominant modern fiber connector, pairing with SFP-family transceivers. SC is the larger square push-pull connector and ST is the round bayonet type."},
    {"type": "mc",
     "q": "Which connector carries 12 or more fiber strands in a single rectangular ferrule for 40G/100G parallel optics?",
     "choices": ["MPO", "LC", "BNC", "SC"],
     "answer": 0,
     "explain": "The multi-fiber push-on (MPO) connector terminates ribbon trunks of 12+ fibers at once, which is how QSFP+ 40GBASE-SR4 and QSFP28 100GBASE-SR4 optics get their parallel lanes. LC and SC each carry a single fiber per ferrule."},
    {"type": "mc",
     "q": "A DSL modem connects to the telephone wall jack using which connector?",
     "choices": ["RJ45", "F-type", "RJ11", "BNC"],
     "answer": 2,
     "explain": "RJ11 is the narrow 6-position connector used for analog phone lines and DSL. RJ45 (8P8C) is the 8-pin Ethernet connector; the two look similar but RJ11 is smaller."},
    {"type": "mc",
     "q": "Which connector uses a threaded screw-on coupling and terminates RG-6 coax for a cable modem?",
     "choices": ["BNC", "ST", "MPO", "F-type"],
     "answer": 3,
     "explain": "The F-type connector screws onto coax and is the standard for cable TV, cable modems, and satellite receivers. BNC is also a coax connector but uses a quarter-twist bayonet lock and appears on legacy Ethernet, CCTV, and test gear."},

    # --- true/false ---
    {"type": "tf",
     "q": "802.11b has a maximum theoretical data rate of 11 Mbps in the 2.4 GHz band.",
     "answer": True,
     "explain": "802.11b, the earliest widely deployed Wi-Fi standard, peaks at 11 Mbps using DSSS in the crowded 2.4 GHz ISM band. Remember 11 Mbps for 'b' versus 54 Mbps for both 'a' and 'g'."},
    {"type": "tf",
     "q": "Single-mode fiber typically uses inexpensive LED light sources, which is why it is cheaper to deploy than multimode.",
     "answer": False,
     "explain": "It is the reverse: single-mode requires precise laser light sources, which makes its optics more expensive, while multimode uses cheaper LEDs or VCSELs. Multimode is the budget choice for short in-building runs; single-mode wins on distance."},
    {"type": "tf",
     "q": "An Ethernet SFP+ module and a Fibre Channel SFP+ module are interchangeable as long as the connector type matches.",
     "answer": False,
     "explain": "Transceivers are protocol-specific: an FC module speaks Fibre Channel framing and an Ethernet module speaks 802.3, so they cannot be swapped even though both may accept LC fiber. Always match the transceiver protocol to the network type."},
    {"type": "tf",
     "q": "LEO satellite constellations such as Starlink offer far lower latency than GEO satellites because they orbit only a few hundred kilometers above Earth.",
     "answer": True,
     "explain": "Starlink satellites orbit around 550 km versus 35,786 km for GEO, so round-trip latency drops from ~600 ms to roughly 20-50 ms. That makes LEO service usable for VoIP, video conferencing, and gaming."},
    {"type": "tf",
     "q": "Cat 8 cabling supports 25/40 Gbps Ethernet but only to about 30 meters, limiting it to data-center use.",
     "answer": True,
     "explain": "Cat 8 is rated to 2000 MHz and carries 25GBASE-T/40GBASE-T, but only over roughly 30 m links, so it targets short data-center runs such as switch-to-server, not building-wide horizontal cabling."},

    # --- fill in ---
    {"type": "fill",
     "q": "802.11ax marketed for the 2.4 and 5 GHz bands is known by what Wi-Fi generation name? (type your answer)",
     "answers": ["Wi-Fi 6", "WiFi 6", "Wi-Fi6", "wifi6"],
     "explain": "The Wi-Fi Alliance labeled 802.11ax as Wi-Fi 6, with Wi-Fi 6E denoting the same standard extended into 6 GHz. 802.11n and 802.11ac are retroactively Wi-Fi 4 and Wi-Fi 5."},
    {"type": "fill",
     "q": "Twisted-pair Ethernet standards such as 1000BASE-T are limited to a maximum segment length of how many meters? (type your answer)",
     "answers": ["100", "100 m", "100 meters"],
     "explain": "The structured-cabling limit for twisted-pair Ethernet is 100 meters (typically 90 m permanent link plus 10 m of patch cords). Beyond that you need a repeater, another switch, or a move to fiber."},
    {"type": "fill",
     "q": "The multimode fiber core sizes are 50 microns and ___ microns. (type your answer)",
     "answers": ["62.5", "62.5 microns", "62.5um"],
     "explain": "Multimode fiber comes in 50 micron (OM2-OM5) and legacy 62.5 micron (OM1) core sizes, both with 125 micron cladding. Single-mode's core is only 8-10 microns."},
    {"type": "fill",
     "q": "What transceiver form factor supports a single 10 Gbps lane? (type your answer)",
     "answers": ["SFP+", "SFP plus", "SFP+ transceiver"],
     "explain": "SFP+ is the enhanced small form-factor pluggable rated for 10 Gbps, physically the same size as the 1G SFP. Keep the ladder straight: SFP 1G, SFP+ 10G, SFP28 25G, QSFP+ 40G, QSFP28 100G."},
    {"type": "fill",
     "q": "Ethernet over twisted pair uses which 8-pin modular connector? (type your answer)",
     "answers": ["RJ45", "RJ-45", "8P8C"],
     "explain": "The RJ45 (technically 8P8C) connector terminates all twisted-pair Ethernet from 10BASE-T through 10GBASE-T. Its smaller cousin RJ11 with 6 positions is for telephone and DSL lines."},
    {"type": "fill",
     "q": "1000BASE-LX over single-mode fiber and 10GBASE-LR both use lasers at a wavelength of ___ nm. (type your answer)",
     "answers": ["1310", "1310 nm", "1310nm"],
     "explain": "Long-reach optics (LX, LR) use 1310 nm lasers over single-mode fiber, while short-reach multimode optics (SX, SR) use 850 nm. Wavelength is a quick clue for classifying an optic as long or short reach."},

    # --- match ---
    {"type": "match",
     "q": "Match each 802.11 standard to its maximum theoretical data rate.",
     "pairs": [
         ["802.11b", "11 Mbps"],
         ["802.11g", "54 Mbps (2.4 GHz)"],
         ["802.11n", "600 Mbps"],
         ["802.11ac", "~6.9 Gbps"],
         ["802.11ax", "~9.6 Gbps"],
     ],
     "explain": "The rate ladder is b=11 Mbps, a/g=54 Mbps, n=600 Mbps, ac=~6.9 Gbps, ax=~9.6 Gbps. Pair it with the bands: b/g are 2.4 GHz, a/ac are 5 GHz, and n/ax are dual-band (ax adds 6 GHz as Wi-Fi 6E)."},
    {"type": "match",
     "q": "Match each connector to its typical use.",
     "pairs": [
         ["LC", "Fiber into SFP/SFP+ modules"],
         ["RJ11", "Telephone/DSL lines"],
         ["F-type", "Cable modem on RG-6 coax"],
         ["BNC", "Legacy coax Ethernet/CCTV, bayonet lock"],
         ["MPO", "12+ fiber ribbon for 40G/100G optics"],
     ],
     "explain": "LC is the small fiber connector for SFP-family optics, RJ11 serves phone/DSL, the threaded F-type terminates CATV coax, BNC bayonet-locks onto legacy coax runs, and MPO bundles a dozen or more fibers for parallel 40G/100G links."},

    # --- order ---
    {"type": "order",
     "q": "Arrange these transceiver form factors from lowest to highest maximum speed.",
     "items": ["SFP", "SFP+", "QSFP+", "QSFP28"],
     "explain": "SFP handles 1 Gbps, SFP+ raises a single lane to 10 Gbps, QSFP+ quadruples 10G lanes to 40 Gbps, and QSFP28 quadruples 25G lanes to 100 Gbps. 'Quad' always means four lanes in one module."},
    {"type": "order",
     "q": "Arrange these copper cable categories from lowest to highest rated bandwidth.",
     "items": ["Cat 5e (100 MHz)", "Cat 6 (250 MHz)", "Cat 6a (500 MHz)", "Cat 8 (2000 MHz)"],
     "explain": "Bandwidth climbs from Cat 5e at 100 MHz (1 Gbps), through Cat 6 at 250 MHz (10 Gbps to 55 m) and Cat 6a at 500 MHz (10 Gbps to 100 m), up to Cat 8 at 2000 MHz (25/40 Gbps to 30 m)."},
]
