TOPIC = {
    "id": "1.6",
    "domain": 1,
    "title": "Compare and contrast network topologies, architectures, and types",
    "short": "Topologies & Architectures",
}

TERMS = [
    ("Topology", "The layout of how network nodes are interconnected, both physically (cabling) and logically (data paths)"),
    ("Full mesh", "Topology where every node has a direct link to every other node; maximum redundancy at maximum cost"),
    ("Partial mesh", "Topology where only selected nodes are fully interconnected; a cost/redundancy compromise"),
    ("Mesh link formula", "A full mesh of n nodes requires n(n-1)/2 links; growth is quadratic"),
    ("Hybrid topology", "A combination of two or more basic topologies, such as interconnected stars; describes most real networks"),
    ("Star topology", "All nodes connect to one central device (a switch); a cable fault isolates one node but the center is a single point of failure"),
    ("Hub and spoke", "WAN version of star: branch sites (spokes) connect only to a central site (hub); spoke-to-spoke traffic transits the hub"),
    ("Point-to-point", "A single dedicated link between exactly two nodes, such as a WAN circuit or building-to-building wireless bridge"),
    ("Spine and leaf", "Two-tier data-center fabric where every leaf connects to every spine, giving uniform two-hop paths for east-west traffic"),
    ("Leaf switch", "Fabric switch that endpoints/servers connect to, often top-of-rack; uplinks to every spine, never to other leaves"),
    ("Spine switch", "Backbone switch of a leaf-spine fabric that connects only to leaf switches, never to other spines or to servers"),
    ("Three-tier hierarchical model", "Campus design of core, distribution, and access layers, each with a distinct role"),
    ("Core layer", "High-speed, highly available backbone that interconnects distribution blocks; performs no policy processing"),
    ("Distribution layer", "Aggregation layer providing inter-VLAN routing, ACLs, QoS, and policy between access and core"),
    ("Access layer", "Edge layer where end devices connect; provides PoE, port security, and VLAN assignment"),
    ("Collapsed core", "Two-tier design merging core and distribution into one layer over an access layer; suits smaller organizations"),
    ("North-south traffic", "Traffic entering or leaving the data center, such as client requests from the internet; crosses the perimeter"),
    ("East-west traffic", "Lateral server-to-server traffic within the data center, such as web tier to database tier"),
    ("Single point of failure", "Any component whose failure takes down the whole system, such as the central switch in a star"),
    ("ECMP", "Equal-cost multi-path routing; lets leaf-spine fabrics load-balance flows across all spines simultaneously"),
]

QUESTIONS = [
    # --- multiple choice ---
    {"type": "mc",
     "q": "How many links are required to build a full mesh among 6 sites?",
     "choices": ["12", "30", "15", "6"],
     "answer": 2,
     "explain": "Full mesh links = n(n-1)/2, so 6 x 5 / 2 = 15. The quadratic growth of this formula is why large networks use partial mesh or hub-and-spoke instead of full mesh."},
    {"type": "mc",
     "q": "A WAN design gives redundant links only to the four critical regional offices, while small branches get a single connection. What topology is this?",
     "choices": ["Partial mesh", "Full mesh", "Point-to-point", "Bus"],
     "answer": 0,
     "explain": "When only some nodes are richly interconnected and others are not, the topology is a partial mesh. It trades some redundancy for a large reduction in circuit costs compared with a full mesh."},
    {"type": "mc",
     "q": "What is the PRIMARY drawback of a full mesh topology as the number of sites grows?",
     "choices": ["Traffic must transit a central hub", "It provides no redundancy", "Broadcast storms increase", "The number of links grows quadratically, becoming costly and complex"],
     "answer": 3,
     "explain": "Each added node in a full mesh must link to every existing node, so links grow as n(n-1)/2 — 10 sites already need 45 circuits. Cost and management complexity explode, which is full mesh's defining weakness despite its excellent fault tolerance."},
    {"type": "mc",
     "q": "Each floor of an office is wired as a star to an access switch, and those switches interconnect with redundant links between floors. How is this overall topology BEST described?",
     "choices": ["Point-to-point", "Hybrid", "Full mesh", "Ring"],
     "answer": 1,
     "explain": "Combining two or more basic topologies — here stars joined by a partial mesh — produces a hybrid topology. Nearly all production networks are hybrids of stars, meshes, and point-to-point links."},
    {"type": "mc",
     "q": "In a star topology LAN, what happens when the central switch fails?",
     "choices": ["Only one host loses connectivity", "All connected hosts lose connectivity", "Traffic reroutes through another host", "Hosts fall back to half duplex"],
     "answer": 1,
     "explain": "The central device is the single point of failure in a star: every host's only path runs through it, so its failure downs the entire segment. By contrast, a single cable fault isolates only the one attached host."},
    {"type": "mc",
     "q": "A company connects 8 branch offices to headquarters only; branches never link to each other directly. What topology is this, and how many WAN circuits does it need?",
     "choices": ["Hub and spoke, 8 circuits", "Full mesh, 28 circuits", "Hub and spoke, 28 circuits", "Partial mesh, 16 circuits"],
     "answer": 0,
     "explain": "Branches (spokes) connecting only to a central hub form a hub-and-spoke topology needing n-1 = 8 circuits for 8 branches plus HQ. A full mesh of all 9 sites would need 9 x 8 / 2 = 36 circuits; the trade-off is that spoke-to-spoke traffic must transit the hub."},
    {"type": "mc",
     "q": "What is the main performance drawback of a hub-and-spoke WAN?",
     "choices": ["Each spoke needs multiple circuits", "The topology cannot scale past four sites", "Spoke-to-spoke traffic must pass through the hub, adding latency", "Broadcasts flood every spoke"],
     "answer": 2,
     "explain": "Because spokes have no direct links to each other, any branch-to-branch communication hairpins through the central hub, adding delay and loading the hub's circuits. The benefit is far fewer circuits than a mesh."},
    {"type": "mc",
     "q": "In a spine-and-leaf architecture, which statement is TRUE?",
     "choices": ["Spine switches interconnect for redundancy", "Every leaf switch connects to every spine switch", "Servers connect directly to spine switches", "Leaf switches connect to adjacent leaf switches"],
     "answer": 1,
     "explain": "The defining rule of leaf-spine is that each leaf uplinks to every spine, while leaf-to-leaf and spine-to-spine links are forbidden and endpoints attach only to leaves. This guarantees every server-to-server path is exactly leaf-spine-leaf."},
    {"type": "mc",
     "q": "Why does a spine-and-leaf fabric deliver predictable latency between any two servers?",
     "choices": ["All traffic is switched by a single core", "Any two leaves are always exactly two hops apart via a spine", "Spanning tree blocks redundant paths", "Servers share one large broadcast domain"],
     "answer": 1,
     "explain": "Since every leaf connects to every spine and no other inter-switch links exist, any server-to-server path is leaf-to-spine-to-leaf — always the same hop count. Uniform paths plus ECMP load balancing give consistent, predictable east-west performance."},
    {"type": "mc",
     "q": "A data-center fabric needs more server-facing ports. In a spine-and-leaf design, what is the correct way to scale?",
     "choices": ["Add another leaf switch", "Add another spine switch", "Interconnect existing leaves", "Upgrade the core layer"],
     "answer": 0,
     "explain": "Leaves provide endpoint ports, so adding a leaf adds capacity for more servers; adding a spine is how you add fabric bandwidth between leaves. Leaf-to-leaf links are never added — they would break the uniform two-hop model."},
    {"type": "mc",
     "q": "Which scenario BEST describes a point-to-point topology?",
     "choices": ["A wireless bridge linking two buildings across a street", "Six routers each connected to all the others", "Twenty PCs cabled to one switch", "Branches connecting through a central data center"],
     "answer": 0,
     "explain": "Point-to-point is a single dedicated link between exactly two nodes, such as a building-to-building wireless bridge, a leased line between two routers, or a direct fiber run. No other devices contend for the link."},
    {"type": "mc",
     "q": "In the three-tier hierarchical model, which layer is designed for maximum forwarding speed and deliberately avoids ACLs and other policy processing?",
     "choices": ["Distribution", "Access", "Core", "Leaf"],
     "answer": 2,
     "explain": "The core is the high-speed, highly available backbone; policy such as ACL filtering is kept off it so nothing slows backbone switching. Policy belongs at the distribution layer, and end devices attach at the access layer."},
    {"type": "mc",
     "q": "At which hierarchical layer would you implement inter-VLAN routing, QoS marking, and ACLs that aggregate multiple wiring closets?",
     "choices": ["Core", "Access", "Spine", "Distribution"],
     "answer": 3,
     "explain": "The distribution layer aggregates access switches and is the designated home for routing between VLANs and applying policy such as ACLs and QoS. It typically forms the boundary between the Layer 2 access domain and the Layer 3 core."},
    {"type": "mc",
     "q": "Which three-tier layer supplies PoE to IP phones, cameras, and wireless access points?",
     "choices": ["Access", "Core", "Distribution", "Aggregation"],
     "answer": 0,
     "explain": "End devices plug into the access (edge) layer, so that is where PoE, port security, 802.1X, and VLAN assignment live. Remember the mapping: end devices/PoE = access, aggregation/policy = distribution, fast backbone = core."},
    {"type": "mc",
     "q": "A 75-employee company in one building wants a hierarchical design without buying three tiers of switches. What should you recommend?",
     "choices": ["A full mesh of access switches", "A collapsed-core design merging core and distribution", "A spine-and-leaf fabric", "A single flat unmanaged switch"],
     "answer": 1,
     "explain": "A collapsed core merges the core and distribution layers into one switch tier above the access layer — the standard right-sizing for small and medium networks that cannot justify a dedicated core. It keeps hierarchy and policy while cutting cost."},
    {"type": "mc",
     "q": "In a collapsed-core architecture, which two layers are combined?",
     "choices": ["Access and distribution", "Spine and leaf", "Core and access", "Core and distribution"],
     "answer": 3,
     "explain": "Collapsed core = core + distribution functions running on the same devices, with the access layer remaining separate. End devices still connect to access switches; only the upper two tiers merge."},
    {"type": "mc",
     "q": "Traffic from an internet user reaching a company's web server through the perimeter firewall is classified as which traffic flow?",
     "choices": ["East-west", "Peer-to-peer", "North-south", "Backhaul"],
     "answer": 2,
     "explain": "North-south traffic enters or leaves the data center, crossing the perimeter where firewalls and load balancers sit. Diagrams draw the ingress/egress at the top (north), hence the name."},
    {"type": "mc",
     "q": "A web VM queries an application VM, which queries a database VM, all within the same data center. What traffic flow is this?",
     "choices": ["East-west", "North-south", "Ingress", "Client-to-server"],
     "answer": 0,
     "explain": "Lateral server-to-server traffic inside the data center is east-west, and in modern virtualized data centers it dominates total volume. Heavy east-west patterns are exactly what spine-and-leaf fabrics are optimized for."},
    {"type": "mc",
     "q": "Why did spine-and-leaf largely replace the three-tier model inside data centers?",
     "choices": ["It eliminates the need for routing protocols", "It supports longer cable runs", "Modern workloads are dominated by east-west traffic needing uniform low-latency paths", "It requires fewer switches in every case"],
     "answer": 2,
     "explain": "Virtualization and microservices made server-to-server (east-west) traffic dominant, and three-tier designs optimized for north-south flows forced variable multi-hop paths. Leaf-spine gives every pair of servers the same two-hop path with ECMP across all spines."},
    {"type": "mc",
     "q": "Which security concern is MOST associated with east-west traffic?",
     "choices": ["It saturates the internet uplink", "It bypasses perimeter firewalls, enabling lateral movement", "It cannot be encrypted", "It always uses UDP"],
     "answer": 1,
     "explain": "East-west flows stay inside the data center and often never touch the perimeter firewall, so an attacker who compromises one server can move laterally unseen. This drives microsegmentation and zero-trust designs that inspect internal traffic."},
    {"type": "mc",
     "q": "A network diagram shows two switch tiers: the top tier's switches connect to every switch in the bottom tier but not to each other, and all servers attach to the bottom tier. What architecture is depicted?",
     "choices": ["Collapsed core", "Three-tier hierarchical", "Hub and spoke", "Spine and leaf"],
     "answer": 3,
     "explain": "Top-tier switches that connect only downward to every bottom-tier switch are spines; the server-facing bottom tier switches are leaves. No spine-spine or leaf-leaf links plus servers on the bottom tier is the leaf-spine signature."},

    # --- true/false ---
    {"type": "tf",
     "q": "In a spine-and-leaf fabric, leaf switches are interconnected directly to each other to provide redundancy.",
     "answer": False,
     "explain": "Leaf-to-leaf links (and spine-to-spine links) are never built in a leaf-spine fabric. Redundancy comes from every leaf connecting to every spine: losing one spine merely reduces capacity without isolating any leaf."},
    {"type": "tf",
     "q": "A full mesh topology provides the highest fault tolerance of any topology but at the highest cost.",
     "answer": True,
     "explain": "With a direct link between every pair of nodes, a full mesh survives multiple link failures, but its n(n-1)/2 link count makes it the most expensive and complex topology. That is why it is reserved for small numbers of critical sites."},
    {"type": "tf",
     "q": "In the three-tier model, end-user devices such as PCs and printers connect directly to the distribution layer.",
     "answer": False,
     "explain": "End devices connect at the access layer; the distribution layer aggregates those access switches and applies policy. Keeping user ports off the distribution layer preserves the hierarchy's scalability."},
    {"type": "tf",
     "q": "North-south traffic describes data moving laterally between servers inside the same data center.",
     "answer": False,
     "explain": "That definition belongs to east-west traffic. North-south is traffic entering or leaving the data center — client requests coming in and responses going out through the perimeter."},
    {"type": "tf",
     "q": "A collapsed-core design is generally more scalable than a full three-tier design for very large enterprise networks.",
     "answer": False,
     "explain": "Collapsed core trades scalability for cost savings: merging core and distribution suits small-to-medium networks, but large enterprises with many distribution blocks need the dedicated core of a full three-tier design to scale."},

    # --- fill in ---
    {"type": "fill",
     "q": "What is the formula for the number of links in a full mesh of n nodes? (type your answer)",
     "answers": ["n(n-1)/2", "n(n-1) / 2", "n*(n-1)/2", "(n(n-1))/2"],
     "explain": "Each of n nodes links to n-1 others, and dividing by 2 removes double counting: n(n-1)/2. For example, 10 nodes require 45 links, which shows why full mesh scales poorly."},
    {"type": "fill",
     "q": "How many links are needed to fully mesh 10 routers? (type your answer)",
     "answers": ["45", "45 links"],
     "explain": "Applying n(n-1)/2 with n=10 gives 10 x 9 / 2 = 45. Adding an 11th router would require 10 new links, illustrating quadratic growth."},
    {"type": "fill",
     "q": "In the three-tier model, the ___ layer aggregates access switches and applies ACLs and QoS policy. (type your answer)",
     "answers": ["distribution", "distribution layer", "aggregation"],
     "explain": "The distribution (aggregation) layer sits between access and core, providing inter-VLAN routing and policy enforcement. The core stays policy-free for speed, and the access layer serves end devices."},
    {"type": "fill",
     "q": "Server-to-server traffic within a data center is called ___ traffic. (type your answer)",
     "answers": ["east-west", "east west", "eastwest"],
     "explain": "East-west traffic moves laterally between servers inside the data center, in contrast to north-south traffic that enters or exits it. Spine-and-leaf fabrics exist primarily to serve east-west flows efficiently."},
    {"type": "fill",
     "q": "In a data-center fabric, servers and endpoints connect to which tier of switch: spine or leaf? (type your answer)",
     "answers": ["leaf", "leaf switch", "leaf switches"],
     "explain": "Endpoints always attach to leaf switches, which are commonly deployed top-of-rack; spines form the backbone and connect only to leaves. Spines never host servers and never connect to each other."},

    # --- match ---
    {"type": "match",
     "q": "Match each three-tier layer or design to its primary role.",
     "pairs": [
         ["Core", "High-speed backbone with no policy processing"],
         ["Distribution", "Aggregation, inter-VLAN routing, ACLs/QoS"],
         ["Access", "End-device connectivity, PoE, port security"],
         ["Collapsed core", "Core and distribution merged for smaller networks"],
     ],
     "explain": "The three-tier model assigns speed to the core, policy and aggregation to distribution, and user/device connectivity to access. A collapsed core combines the top two tiers on one set of switches when a dedicated core is not justified."},
    {"type": "match",
     "q": "Match each topology to its defining characteristic.",
     "pairs": [
         ["Full mesh", "Every node links directly to every other node"],
         ["Hub and spoke", "Branches connect only to a central site"],
         ["Point-to-point", "One dedicated link between exactly two nodes"],
         ["Spine and leaf", "Every leaf uplinks to every spine; two-hop paths"],
         ["Hybrid", "Combination of two or more basic topologies"],
     ],
     "explain": "Full mesh maximizes redundancy at n(n-1)/2 links; hub-and-spoke centralizes with n-1 links; point-to-point joins exactly two endpoints; leaf-spine builds a uniform data-center fabric; and hybrid mixes basic shapes, describing most real networks."},

    # --- order ---
    {"type": "order",
     "q": "Arrange the path of a packet from an internet client to a campus PC through a three-tier network, in order.",
     "items": ["Edge router/firewall", "Core layer", "Distribution layer", "Access layer", "End device"],
     "explain": "North-south traffic enters at the perimeter, crosses the high-speed core, is aggregated and policy-checked at distribution, and reaches the user port at the access layer. The layers exist precisely to structure this path."},
    {"type": "order",
     "q": "Arrange these WAN topologies from fewest links to most links when connecting 6 sites.",
     "items": ["Point-to-point pair (subset of sites)", "Hub and spoke (5 links)", "Partial mesh (redundant key sites)", "Full mesh (15 links)"],
     "explain": "A single point-to-point link joins just two of the sites; hub-and-spoke needs n-1 = 5 links; a partial mesh adds selective redundancy beyond that; and a full mesh tops out at n(n-1)/2 = 15 links. Link count buys redundancy at increasing cost."},
]
