TOPIC = {
    "id": "1.7",
    "domain": 1,
    "title": "Given a scenario, use appropriate IPv4 network addressing",
    "short": "IPv4 Addressing",
}

TERMS = [
    ("Public IP address", "Globally unique, internet-routable address allocated through IANA and the regional registries"),
    ("Private IP address", "RFC 1918 address usable by anyone internally but not routable on the internet; requires NAT to reach it"),
    ("RFC 1918", "Standard reserving 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16 for private internal use"),
    ("10.0.0.0/8", "The Class A-sized private range: 10.0.0.0 - 10.255.255.255, about 16.7 million addresses"),
    ("172.16.0.0/12", "The private range covering 172.16.0.0 - 172.31.255.255; addresses outside 16-31 in the second octet are public"),
    ("192.168.0.0/16", "The private range covering 192.168.0.0 - 192.168.255.255, equal to 256 Class C networks"),
    ("APIPA", "Automatic Private IP Addressing: a 169.254.0.0/16 self-assigned link-local address indicating the client could not reach a DHCP server"),
    ("Loopback address", "The 127.0.0.0/8 range (localhost = 127.0.0.1); traffic never leaves the host, used to test the local TCP/IP stack"),
    ("NAT", "Network Address Translation: rewrites private source addresses to a public address at the network edge"),
    ("Subnetting", "Dividing one network into smaller networks by borrowing bits from the host portion of the address"),
    ("CIDR", "Classless Inter-Domain Routing: prefix-length notation such as /26 that ignores class boundaries and enables route aggregation"),
    ("VLSM", "Variable Length Subnet Mask: using different mask lengths within one network to size each subnet to its host count"),
    ("Subnet mask", "32-bit pattern of leading 1s marking which address bits are network versus host, e.g., 255.255.255.192 = /26"),
    ("Network address", "First address of a subnet with all host bits set to 0; identifies the subnet and cannot be assigned to a host"),
    ("Broadcast address", "Last address of a subnet with all host bits set to 1; reaches every host in the subnet and cannot be assigned"),
    ("Magic number", "256 minus the interesting mask octet; the increment between subnet network addresses in that octet"),
    ("Usable hosts formula", "2^h - 2, where h is the number of host bits; subtracting the network and broadcast addresses"),
    ("Class A", "First octet 1-126, default mask 255.0.0.0 (/8); over 16 million hosts per network"),
    ("Class B", "First octet 128-191, default mask 255.255.0.0 (/16); 65,534 hosts per network"),
    ("Class C", "First octet 192-223, default mask 255.255.255.0 (/24); 254 hosts per network"),
    ("Class D", "First octet 224-239; reserved for multicast group addresses, never assigned to host interfaces"),
    ("Class E", "First octet 240-255; experimental/reserved range not valid for hosts on production networks"),
    ("/30 subnet", "Mask 255.255.255.252 with exactly 2 usable addresses; the traditional choice for point-to-point router links"),
]

QUESTIONS = [
    # --- multiple choice ---
    {"type": "mc",
     "q": "Which of the following is a valid RFC 1918 private address?",
     "choices": ["172.32.10.5", "172.20.10.5", "192.169.10.5", "11.0.10.5"],
     "answer": 1,
     "explain": "The 172 private block spans only 172.16.0.0 - 172.31.255.255 (172.16.0.0/12), so 172.20.10.5 is private while 172.32.10.5 is public. Likewise 192.169.x.x is outside 192.168.0.0/16 and 11.x.x.x is outside 10.0.0.0/8 — both public."},
    {"type": "mc",
     "q": "A user's laptop shows the address 169.254.88.4 and cannot reach any network resources. What is the MOST likely cause?",
     "choices": ["The laptop failed to contact a DHCP server and self-assigned an APIPA address", "The laptop is on a private RFC 1918 network", "A static address was mistyped by the technician", "The default gateway is offline"],
     "answer": 0,
     "explain": "169.254.0.0/16 is the APIPA link-local range that a DHCP client assigns itself when no DHCP server responds. APIPA addresses are not routable, so the host can reach only other devices on the same local segment — the fix is to restore DHCP connectivity and renew the lease."},
    {"type": "mc",
     "q": "What can a host with an APIPA address communicate with?",
     "choices": ["Any internet host via NAT", "Other hosts on the same local segment only", "Any host on other internal subnets via the gateway", "Nothing at all"],
     "answer": 1,
     "explain": "APIPA (169.254.0.0/16) is link-local: it has no default gateway and routers will not forward it, so communication is limited to peers on the same segment. That still allows two APIPA hosts on one switch to talk to each other."},
    {"type": "mc",
     "q": "A technician runs 'ping 127.0.0.1' successfully. What has been verified?",
     "choices": ["The default gateway is reachable", "DNS resolution is functional", "The local TCP/IP stack is working", "The NIC's cable and switch port are good"],
     "answer": 2,
     "explain": "127.0.0.1 is the loopback/localhost address; packets to it are handled entirely inside the host's TCP/IP stack and never touch the NIC or network. A successful loopback ping proves only that the protocol stack is functional."},
    {"type": "mc",
     "q": "Why do private RFC 1918 addresses require NAT to reach the internet?",
     "choices": ["They are IPv6-only addresses", "They exceed the 32-bit address length", "They are reserved for multicast traffic", "Internet routers will not forward them because they are not globally routable"],
     "answer": 3,
     "explain": "RFC 1918 space is deliberately non-routable on the public internet — providers drop it — so a NAT device must translate the private source address to a public one at the edge. This lets thousands of internal hosts share a few public addresses, one of the key stopgaps against IPv4 exhaustion."},
    {"type": "mc",
     "q": "Which address class does 190.5.200.13 belong to, and what is its default mask?",
     "choices": ["Class C, 255.255.255.0", "Class B, 255.255.0.0", "Class A, 255.0.0.0", "Class B, 255.255.255.0"],
     "answer": 1,
     "explain": "A first octet of 128-191 makes the address Class B with a default /16 mask of 255.255.0.0. Class A is 1-126 (/8) and Class C is 192-223 (/24)."},
    {"type": "mc",
     "q": "Which class of IPv4 addresses is reserved for multicast?",
     "choices": ["Class D (224-239)", "Class E (240-255)", "Class C (192-223)", "Class A (1-126)"],
     "answer": 0,
     "explain": "Class D, first octet 224-239, holds multicast group addresses used for one-to-many delivery, such as OSPF's 224.0.0.5. Class E (240-255) is experimental/reserved and is never assigned to hosts."},
    {"type": "mc",
     "q": "Why is there no Class A network 127?",
     "choices": ["127 is reserved for APIPA", "The entire 127.0.0.0/8 block is reserved for loopback", "127 is the Class B boundary", "127 is reserved for multicast"],
     "answer": 1,
     "explain": "Class A ends at 126 and Class B begins at 128 because all of 127.0.0.0/8 is set aside for loopback testing, with 127.0.0.1 as the conventional localhost. APIPA is a different reservation at 169.254.0.0/16."},
    {"type": "mc",
     "q": "An interface is configured as 240.1.1.5. Why is this invalid for a production host?",
     "choices": ["It falls in the Class E experimental range", "It is a broadcast address", "It is an RFC 1918 private address", "It is a loopback address"],
     "answer": 0,
     "explain": "First octets 240-255 belong to Class E, which is reserved for experimental use and never assigned to hosts. A quick first-octet check — 1-126 A, 128-191 B, 192-223 C, 224-239 D, 240-255 E — classifies any address instantly."},
    {"type": "mc",
     "q": "What does CIDR notation /26 represent as a dotted-decimal subnet mask?",
     "choices": ["255.255.255.224", "255.255.255.128", "255.255.255.192", "255.255.255.240"],
     "answer": 2,
     "explain": "/26 means 26 network bits: three full octets (24 bits) plus two more bits in the fourth octet, 128 + 64 = 192, giving 255.255.255.192. The remaining 6 host bits allow 2^6 - 2 = 62 usable hosts."},
    {"type": "mc",
     "q": "How many usable host addresses exist in a /27 subnet?",
     "choices": ["32", "62", "14", "30"],
     "answer": 3,
     "explain": "A /27 leaves 5 host bits: 2^5 = 32 total addresses minus the network and broadcast = 30 usable. Always subtract 2 — the 'total addresses' figure is a classic wrong answer."},
    {"type": "mc",
     "q": "You must split 192.168.1.0/24 into exactly 4 equal subnets. Which new mask do you use?",
     "choices": ["/25 (255.255.255.128)", "/26 (255.255.255.192)", "/27 (255.255.255.224)", "/28 (255.255.255.240)"],
     "answer": 1,
     "explain": "Four subnets require borrowing 2 bits (2^2 = 4), turning /24 into /26 with mask 255.255.255.192. The magic number is 256 - 192 = 64, so the subnets are .0, .64, .128, and .192, each with 62 usable hosts."},
    {"type": "mc",
     "q": "After subnetting 192.168.1.0/24 into four /26 subnets, what is the network address of the THIRD subnet?",
     "choices": ["192.168.1.64", "192.168.1.96", "192.168.1.128", "192.168.1.192"],
     "answer": 2,
     "explain": "The /26 magic number is 64, so the subnets begin at 0, 64, 128, and 192 in the fourth octet — the third is 192.168.1.128/26. Its usable range is .129-.190 with broadcast .191."},
    {"type": "mc",
     "q": "Which subnet does host 172.16.37.99/20 belong to?",
     "choices": ["172.16.37.0/20", "172.16.16.0/20", "172.16.36.0/20", "172.16.32.0/20"],
     "answer": 3,
     "explain": "A /20 mask is 255.255.240.0, so the interesting octet is the third and the magic number is 256 - 240 = 16, placing networks at 0, 16, 32, 48... Since 37 falls between 32 and 48, the host lives in 172.16.32.0/20."},
    {"type": "mc",
     "q": "What is the broadcast address of the subnet containing 172.16.37.99/20?",
     "choices": ["172.16.47.255", "172.16.37.255", "172.16.32.255", "172.16.255.255"],
     "answer": 0,
     "explain": "The host's subnet is 172.16.32.0/20 and the next subnet starts at 172.16.48.0, so the broadcast is one less: 172.16.47.255. The usable range is therefore 172.16.32.1 through 172.16.47.254."},
    {"type": "mc",
     "q": "What is the network address for host 10.10.25.200 with mask 255.255.248.0?",
     "choices": ["10.10.25.0", "10.10.16.0", "10.10.24.0", "10.10.20.0"],
     "answer": 2,
     "explain": "255.255.248.0 (/21) makes the third octet interesting with magic number 256 - 248 = 8, so networks fall on multiples of 8: 16, 24, 32... The 25 in the third octet rounds down to 24, giving network 10.10.24.0/21 (broadcast 10.10.31.255)."},
    {"type": "mc",
     "q": "What are the first and last USABLE addresses in subnet 192.168.1.64/26?",
     "choices": ["192.168.1.64 and 192.168.1.127", "192.168.1.65 and 192.168.1.126", "192.168.1.65 and 192.168.1.127", "192.168.1.64 and 192.168.1.126"],
     "answer": 1,
     "explain": "The network address .64 and broadcast .127 are unusable, leaving .65 through .126 for hosts. A /26 always yields 62 usable addresses between its network and broadcast."},
    {"type": "mc",
     "q": "Hosts 192.168.4.50/23 and 192.168.5.60/23 cannot ping each other and there is no router between them. Are they on the same subnet?",
     "choices": ["No, /23 cannot span two third-octet values", "No, they are in different subnets", "Yes, both are in 192.168.4.0/23, so look elsewhere for the problem", "It cannot be determined from the information given"],
     "answer": 2,
     "explain": "A /23 (255.255.254.0) has magic number 2 in the third octet, so 192.168.4.0/23 spans 192.168.4.0 - 192.168.5.255 and both hosts fall inside it. Since addressing is correct, the fault must lie elsewhere (cabling, VLANs, host firewall, etc.)."},
    {"type": "mc",
     "q": "A department needs at least 100 hosts in one subnet. What is the LONGEST prefix (smallest subnet) that satisfies this?",
     "choices": ["/26", "/24", "/23", "/25"],
     "answer": 3,
     "explain": "A /25 leaves 7 host bits: 2^7 - 2 = 126 usable, which covers 100; a /26 provides only 62. Choosing the longest prefix that still fits conserves address space — the essence of VLSM design."},
    {"type": "mc",
     "q": "Which prefix is traditionally assigned to a point-to-point WAN link between two routers, and why?",
     "choices": ["/30, because it provides exactly 2 usable addresses", "/29, because it provides exactly 2 usable addresses", "/32, because it identifies a single host", "/24, because it is the classful default"],
     "answer": 0,
     "explain": "A /30 contains 4 addresses — network, two usable hosts, broadcast — perfectly matching a two-router link. Modern equipment also supports /31 (RFC 3021), which uses both of its addresses on point-to-point links."},
    {"type": "mc",
     "q": "What does VLSM allow a network designer to do?",
     "choices": ["Assign public addresses without registration", "Use different subnet mask lengths within the same network to fit each subnet's size", "Extend the 32-bit address space to 128 bits", "Translate private addresses to public ones"],
     "answer": 1,
     "explain": "Variable Length Subnet Masking sizes each subnet to its actual need — a /25 for 100 users, a /30 for a router link — inside the same address block, allocated largest-first. It requires classless routing protocols that carry the mask with each route."},
    {"type": "mc",
     "q": "Beyond subnetting, what capability does CIDR give internet routing?",
     "choices": ["Automatic address assignment", "Encryption of route advertisements", "Aggregating many networks into one summary route (supernetting)", "Elimination of the need for subnet masks"],
     "answer": 2,
     "explain": "CIDR ignores class boundaries, so contiguous networks can be advertised as one summary — for example four /24s as a single /22 — shrinking routing tables. That aggregation, along with prefix-length flexibility, is why classful routing was abandoned."},

    # --- true/false ---
    {"type": "tf",
     "q": "The address 172.31.255.10 is a private RFC 1918 address.",
     "answer": True,
     "explain": "The 172 private block runs through 172.31.255.255, so 172.31.255.10 is inside 172.16.0.0/12. Only at 172.32.0.0 does the space become public again."},
    {"type": "tf",
     "q": "A subnet's network address can be assigned to a server as long as no other host is using it.",
     "answer": False,
     "explain": "The network address (all host bits 0) identifies the subnet itself and the broadcast address (all host bits 1) reaches every host; neither may ever be assigned to a device. That is why usable hosts = 2^h - 2."},
    {"type": "tf",
     "q": "An APIPA address of 169.254.10.20 indicates that DHCP is functioning correctly.",
     "answer": False,
     "explain": "APIPA is the fallback a client uses precisely when DHCP fails — the host asked for a lease and got no answer. Seeing 169.254.x.x should immediately point troubleshooting at DHCP server reachability."},
    {"type": "tf",
     "q": "A /24 network provides 254 usable host addresses.",
     "answer": True,
     "explain": "A /24 leaves 8 host bits: 2^8 = 256 total addresses minus the network and broadcast leaves 254 for hosts. This is the everyday 255.255.255.0 network size."},
    {"type": "tf",
     "q": "Class A addresses have a first octet from 1 to 126 and a default mask of 255.0.0.0.",
     "answer": True,
     "explain": "Class A spans first octets 1-126 with a /8 default mask, giving over 16 million hosts per network. The gap at 127 exists because that entire block is reserved for loopback."},

    # --- fill in ---
    {"type": "fill",
     "q": "What is the APIPA address range in CIDR notation? (type your answer)",
     "answers": ["169.254.0.0/16", "169.254.0.0 /16", "169.254/16"],
     "explain": "APIPA link-local addresses come from 169.254.0.0/16 per RFC 3927. A host self-assigns from this range when its DHCP request goes unanswered."},
    {"type": "fill",
     "q": "What is the conventional IPv4 localhost address? (type your answer)",
     "answers": ["127.0.0.1", "127.0.0.1/8"],
     "explain": "127.0.0.1 is the standard loopback/localhost address, though the entire 127.0.0.0/8 block is reserved for loopback. Pinging it tests the local TCP/IP stack without touching the network."},
    {"type": "fill",
     "q": "The RFC 1918 private range that starts at 172.16.0.0 has what CIDR prefix length? (type your answer)",
     "answers": ["/12", "12", "172.16.0.0/12"],
     "explain": "172.16.0.0/12 covers 172.16.0.0 through 172.31.255.255 — 16 contiguous Class B-sized networks. Remember that 172.15.x.x and 172.32.x.x are public."},
    {"type": "fill",
     "q": "For mask 255.255.255.240, the magic number (subnet increment) is ___. (type your answer)",
     "answers": ["16", "sixteen"],
     "explain": "Magic number = 256 minus the interesting octet value: 256 - 240 = 16, so /28 subnets start at 0, 16, 32, 48... in the fourth octet. Each contains 16 addresses, 14 of them usable."},
    {"type": "fill",
     "q": "How many usable hosts does a /29 subnet provide? (type your answer)",
     "answers": ["6", "six"],
     "explain": "A /29 leaves 3 host bits: 2^3 - 2 = 6 usable addresses out of 8 total. Small blocks like this suit DMZ segments or device management networks."},
    {"type": "fill",
     "q": "Host 10.1.1.77 has mask 255.255.255.192. What is its subnet's network address? (type your answer)",
     "answers": ["10.1.1.64", "10.1.1.64/26"],
     "explain": "Mask .192 gives magic number 64, so subnets start at 0, 64, 128, 192; the value 77 rounds down to 64. The subnet is 10.1.1.64/26 with broadcast 10.1.1.127 and usable range .65-.126."},

    # --- match ---
    {"type": "match",
     "q": "Match each IPv4 class to its first-octet range.",
     "pairs": [
         ["Class A", "1-126"],
         ["Class B", "128-191"],
         ["Class C", "192-223"],
         ["Class D (multicast)", "224-239"],
         ["Class E (experimental)", "240-255"],
     ],
     "explain": "Classify any address by its first octet: 1-126 A (/8 default), 128-191 B (/16), 192-223 C (/24), 224-239 D for multicast, 240-255 E experimental. The missing 127 block is reserved for loopback."},
    {"type": "match",
     "q": "Match each address to what it indicates.",
     "pairs": [
         ["169.254.31.7", "APIPA - DHCP server unreachable"],
         ["127.0.0.1", "Loopback/localhost - local stack test"],
         ["10.44.2.9", "RFC 1918 private address"],
         ["8.8.8.8", "Public internet-routable address"],
         ["224.0.0.5", "Class D multicast group address"],
     ],
     "explain": "Recognizing special ranges on sight is a core exam skill: 169.254.x.x means DHCP failure, 127.x.x.x is loopback, 10/8 is private, and 224-239 first octets are multicast. Anything outside the reserved ranges, like 8.8.8.8, is public."},

    # --- order ---
    {"type": "order",
     "q": "Arrange the magic-number subnetting steps in the correct order for finding a host's subnet.",
     "items": [
         "Convert the prefix to a dotted mask and find the interesting octet",
         "Compute the magic number as 256 minus the mask value in that octet",
         "Round the host's octet value down to the nearest multiple of the magic number to get the network address",
         "Find the broadcast as one less than the next network address",
         "List the usable range between network+1 and broadcast-1",
     ],
     "explain": "The magic-number method works in this fixed sequence: identify the interesting octet, get the increment (256 - mask octet), round down for the network, take next-network-minus-one for the broadcast, and everything between is usable. Drilling this order makes exam subnetting a 30-second task."},
    {"type": "order",
     "q": "Arrange these prefixes from FEWEST usable hosts to MOST usable hosts.",
     "items": ["/30 (2 hosts)", "/28 (14 hosts)", "/26 (62 hosts)", "/24 (254 hosts)", "/23 (510 hosts)"],
     "explain": "Each bit returned to the host portion doubles the address count: /30 has 2 usable, /28 has 14, /26 has 62, /24 has 254, and /23 has 510. Shorter prefix = bigger subnet."},
]
