TOPIC = {
    "id": "1.8",
    "domain": 1,
    "title": "Summarize evolving use cases for modern network environments",
    "short": "Modern Networks",
}

TERMS = [
    ("SDN", "Software-defined networking: separates the control plane (centralized controller decisions) from the data plane (packet forwarding)"),
    ("Control plane", "The decision-making brain of the network — routing/path logic, centralized in an SDN controller"),
    ("Data plane", "The forwarding plane that actually moves packets according to the control plane's instructions"),
    ("SD-WAN", "SDN applied to wide-area networks; steers traffic per application across any mix of transports with central policy"),
    ("Application aware", "SD-WAN capability to identify traffic by application and apply per-app routing/QoS policy, not just port/IP rules"),
    ("Zero-touch provisioning", "New device pulls its full configuration automatically after being plugged in — no on-site engineer needed"),
    ("Transport agnostic", "SD-WAN works over any underlying circuit — MPLS, broadband, DSL, 4G/5G LTE, satellite — abstracted into one virtual WAN"),
    ("Central policy management", "Defining policy once in a controller/orchestrator and pushing it to every site automatically"),
    ("VXLAN", "Overlay that encapsulates Layer 2 frames in UDP/IP (MAC-in-UDP) to stretch L2 segments across a routed L3 network"),
    ("VNI", "VXLAN Network Identifier: the 24-bit segment ID allowing about 16.7 million segments versus 4,094 VLANs"),
    ("VTEP", "VXLAN Tunnel Endpoint: the switch or hypervisor that encapsulates and decapsulates VXLAN traffic"),
    ("Data center interconnect (DCI)", "Extending Layer 2 segments between separate data centers, e.g., with VXLAN, for VM mobility and DR"),
    ("Zero trust architecture", "Security model of 'never trust, always verify': every request is authenticated and authorized regardless of network location"),
    ("Least privilege access", "Granting each user, device, or service only the minimum access required for its role"),
    ("SASE", "Secure Access Service Edge: cloud service converging SD-WAN networking with a security stack (SWG, CASB, ZTNA, FWaaS)"),
    ("SSE", "Security Service Edge: the SASE security services (SWG, CASB, ZTNA, FWaaS) delivered without the SD-WAN networking component"),
    ("Infrastructure as code (IaC)", "Managing infrastructure through machine-readable definition files that are versioned and applied automatically"),
    ("Playbook", "An ordered, reusable list of automation tasks (an Ansible term) executed against many devices"),
    ("Configuration drift", "Devices gradually diverging from the approved baseline due to manual one-off changes; detected by comparing to desired state"),
    ("Dynamic inventory", "Device/host list generated in real time by querying cloud APIs or a source of truth instead of a static file"),
    ("Version control", "Tracking every change as a commit with author, time, and message; enables history review and rollback"),
    ("Branching", "Creating an isolated line of development to build and test changes before merging into the main branch"),
    ("Dual stack", "Running IPv4 and IPv6 simultaneously on the same interfaces; the preferred IPv6 transition approach"),
    ("Tunneling (IPv6)", "Encapsulating IPv6 packets inside IPv4 to cross IPv4-only networks; e.g., 6to4, ISATAP, Teredo"),
    ("NAT64", "Gateway translating IPv6 packets to IPv4 so IPv6-only clients can reach IPv4-only servers; paired with DNS64"),
    ("Link-local address (IPv6)", "fe80::/10 address auto-configured on every IPv6 interface and valid only on the local link"),
]

QUESTIONS = [
    # --- multiple choice ---
    {"type": "mc",
     "q": "What is the defining characteristic of software-defined networking (SDN)?",
     "choices": ["Replacing all copper links with fiber", "Encrypting all traffic between switches", "Separating the control plane from the data plane with centralized control", "Running routing protocols on every switch"],
     "answer": 2,
     "explain": "SDN moves path-decision logic (the control plane) out of individual devices into a centralized controller, leaving devices to forward packets (the data plane) per its instructions. This makes the network programmable through APIs and manageable as one system."},
    {"type": "mc",
     "q": "In SDN terminology, which plane is responsible for actually forwarding user packets?",
     "choices": ["Management plane", "Data plane", "Control plane", "Policy plane"],
     "answer": 1,
     "explain": "The data (forwarding) plane moves packets according to rules supplied by the control plane, while the management plane handles configuration and monitoring. Separating these planes is the core SDN idea."},
    {"type": "mc",
     "q": "An SD-WAN edge detects rising jitter on the MPLS circuit and automatically shifts only the VoIP traffic to the broadband link. Which SD-WAN feature is this?",
     "choices": ["Application-aware routing", "Zero-touch provisioning", "Configuration drift detection", "Data center interconnect"],
     "answer": 0,
     "explain": "Application awareness lets SD-WAN classify traffic by application and steer each app per policy and real-time link health — latency-sensitive VoIP moves to the better path while bulk traffic stays put. Port-based routers cannot make this per-app decision."},
    {"type": "mc",
     "q": "A new branch router is drop-shipped to a site, and the office manager just plugs in power and the WAN cable; the router then downloads its full configuration itself. What is this called?",
     "choices": ["Port mirroring", "Out-of-band management", "Configuration drift", "Zero-touch provisioning"],
     "answer": 3,
     "explain": "Zero-touch provisioning has the device phone home to the SD-WAN orchestrator, authenticate, and pull its complete configuration with no on-site engineer. It slashes branch rollout time and eliminates manual CLI errors."},
    {"type": "mc",
     "q": "An SD-WAN design mixes MPLS at headquarters, cable broadband at branches, and 5G as backup, treating them all as one virtual WAN. Which SD-WAN property does this illustrate?",
     "choices": ["Least privilege", "Transport agnosticism", "Layer 2 encapsulation", "Application awareness"],
     "answer": 1,
     "explain": "Transport agnostic means SD-WAN abstracts whatever underlying circuits exist — MPLS, broadband, DSL, LTE/5G, satellite — into a single overlay and steers traffic across them. Organizations can blend cheap broadband with or in place of MPLS."},
    {"type": "mc",
     "q": "A company must apply a new traffic-priority rule at all 150 SD-WAN branches. How is this accomplished?",
     "choices": ["Logging into each branch router's CLI", "Re-imaging each edge appliance", "Changing the policy once in the central orchestrator, which pushes it everywhere", "Mailing updated routers to each branch"],
     "answer": 2,
     "explain": "Central policy management means policy is defined once in the controller/orchestrator and automatically propagated to every site. This consistency and speed is a primary reason organizations adopt SD-WAN over box-by-box management."},
    {"type": "mc",
     "q": "A cloud provider needs tens of thousands of isolated tenant networks but 802.1Q supports only about 4,094 VLANs. Which technology solves this?",
     "choices": ["VXLAN", "SASE", "NAT64", "Spanning tree"],
     "answer": 0,
     "explain": "VXLAN's 24-bit VXLAN Network Identifier (VNI) supports roughly 16.7 million segments, shattering the 12-bit VLAN limit. It also tunnels those segments over routed IP networks, which plain VLANs cannot cross."},
    {"type": "mc",
     "q": "How does VXLAN carry Layer 2 frames across a Layer 3 network?",
     "choices": ["It converts frames into IPv6 multicast", "It uses spanning tree to bridge routers", "It replaces MAC addresses with IP addresses", "VTEPs encapsulate Ethernet frames inside UDP/IP packets (MAC-in-UDP)"],
     "answer": 3,
     "explain": "A VXLAN Tunnel Endpoint (VTEP) wraps the original Ethernet frame in a VXLAN/UDP/IP header (UDP port 4789) and sends it across the routed underlay; the far VTEP strips the wrapper and delivers the original frame. Hosts believe they share one LAN."},
    {"type": "mc",
     "q": "Two data centers 40 km apart must appear as one Layer 2 domain so VMs can migrate live between them. Which use case and technology fit?",
     "choices": ["Data center interconnect using VXLAN", "Zero-touch provisioning using SD-WAN", "Loop prevention using STP", "Address translation using NAT64"],
     "answer": 0,
     "explain": "Extending L2 between sites is data center interconnect (DCI), and VXLAN is a leading DCI method: it tunnels the L2 segment over any IP connection between the sites. This enables live VM migration and active/active designs without stretching spanning tree."},
    {"type": "mc",
     "q": "How many bits is a VXLAN Network Identifier (VNI), and roughly how many segments does that allow?",
     "choices": ["12 bits, about 4,000 segments", "16 bits, about 65,000 segments", "24 bits, about 16.7 million segments", "32 bits, about 4.3 billion segments"],
     "answer": 2,
     "explain": "The VNI is 24 bits, allowing 2^24 = about 16.7 million distinct segments, versus the 12-bit VLAN ID's ~4,094. This scale is what makes VXLAN suitable for multi-tenant clouds."},
    {"type": "mc",
     "q": "Which phrase BEST summarizes zero trust architecture?",
     "choices": ["Trust but verify at the perimeter", "Never trust, always verify — regardless of network location", "Encrypt external traffic only", "Trust all authenticated VPN users fully"],
     "answer": 1,
     "explain": "Zero trust removes location-based trust: being on the internal LAN grants nothing, and every request is authenticated, authorized, and encrypted every time. The model assumes breach, so lateral movement is constrained through microsegmentation."},
    {"type": "mc",
     "q": "Under zero trust, a user authenticated with MFA is denied a resource when connecting from a non-compliant device. Which ZTA element made this decision?",
     "choices": ["Policy-based authentication evaluating identity plus device posture and context", "A perimeter firewall ACL", "Spanning tree protocol", "Static NAT mapping"],
     "answer": 0,
     "explain": "Zero trust access decisions come from a policy engine that weighs identity together with context — device health, location, time, behavior — on every request, continuously. Valid credentials alone are not enough if the policy's other conditions fail."},
    {"type": "mc",
     "q": "In zero trust, what does the principle of least privilege require?",
     "choices": ["All users share one admin account", "Users receive full access after passing MFA once", "Each identity gets only the minimum access its role requires", "Access is granted based on physical office location"],
     "answer": 2,
     "explain": "Least privilege scopes every user, device, and service down to exactly what its job needs — often just-in-time — so a compromised account has a minimal blast radius. Authentication proves who you are; authorization and least privilege bound what you can do."},
    {"type": "mc",
     "q": "What distinguishes SASE from SSE?",
     "choices": ["SSE includes SD-WAN while SASE does not", "SASE combines SD-WAN networking with cloud security services; SSE is the security services without SD-WAN", "SASE is on-premises while SSE is cloud-only", "They are identical offerings from different vendors"],
     "answer": 1,
     "explain": "SASE = SD-WAN + a cloud-delivered security stack (SWG, CASB, ZTNA, FWaaS); SSE is that same security stack minus the networking half. An organization keeping its existing WAN but moving security to the cloud is buying SSE."},
    {"type": "mc",
     "q": "Which set of services is typically part of the SSE security stack?",
     "choices": ["OSPF, BGP, and EIGRP", "Secure web gateway, CASB, ZTNA, and firewall as a service", "DHCP, DNS, and NTP", "VXLAN, VTEP, and VNI"],
     "answer": 1,
     "explain": "SSE bundles cloud-delivered security functions: SWG for web filtering, CASB for SaaS visibility/control, ZTNA for per-application remote access, and FWaaS. Add SD-WAN to that stack and you have full SASE."},
    {"type": "mc",
     "q": "A network team stores switch configurations as code templates and deploys them with automation instead of typing CLI on each device. What is this practice called?",
     "choices": ["Infrastructure as code", "Port aggregation", "Out-of-band management", "Configuration drift"],
     "answer": 0,
     "explain": "Infrastructure as code manages device configuration through machine-readable, version-controlled definition files applied by tools like Ansible or Terraform. The result is fast, repeatable, consistent deployment — one template can build hundreds of identical devices."},
    {"type": "mc",
     "q": "An audit finds several switches whose running configurations no longer match the approved baseline after months of ad-hoc manual changes. What is this condition called?",
     "choices": ["Zero-touch provisioning", "Version branching", "Configuration drift", "Dynamic inventory"],
     "answer": 2,
     "explain": "Configuration drift is the gradual divergence of actual device state from the defined desired state. IaC tooling detects drift by comparing devices against the code baseline and can automatically remediate by re-applying it, restoring compliance."},
    {"type": "mc",
     "q": "An automation platform queries the cloud provider's API at runtime to discover which servers currently exist, rather than reading a manually maintained host list. What is this feature?",
     "choices": ["Static routing", "Dynamic inventory", "Central repository", "Conflict identification"],
     "answer": 1,
     "explain": "A dynamic inventory builds the target device list in real time from sources of truth such as cloud APIs, hypervisors, or IPAM. It is essential in elastic cloud environments where instances constantly appear and disappear."},
    {"type": "mc",
     "q": "Two engineers edit the same lines of the same switch template in Git and try to merge. What happens?",
     "choices": ["Both changes are silently combined", "The system flags a merge conflict that must be resolved before merging", "The later commit is automatically discarded", "The repository locks permanently"],
     "answer": 1,
     "explain": "Version control detects when overlapping lines were changed on both sides and raises a merge conflict, forcing a human to reconcile the edits. This conflict identification prevents one engineer's work from silently overwriting another's."},
    {"type": "mc",
     "q": "A network engineer wants to develop and test a new QoS template without any risk to the production configuration files, then have peers review it before it goes live. Which source-control workflow supports this?",
     "choices": ["Create a branch, commit changes there, and merge via a reviewed pull request", "Edit the main branch directly on the central repository", "Email the file to colleagues for comments", "Disable version control during testing"],
     "answer": 0,
     "explain": "Branching isolates work-in-progress from the stable main branch; the change is then proposed as a pull/merge request, reviewed, and merged only after approval. This gives infrastructure changes the same review discipline as software."},
    {"type": "mc",
     "q": "What is the PRIMARY reason IPv6 was created?",
     "choices": ["To encrypt all internet traffic by default", "To mitigate the exhaustion of the 32-bit IPv4 address space", "To make NAT mandatory", "To speed up Wi-Fi networks"],
     "answer": 1,
     "explain": "IPv4's ~4.3 billion addresses ran out, and NAT/private addressing were only stopgaps. IPv6's 128-bit space (about 3.4 x 10^38 addresses) permanently solves exhaustion and restores end-to-end addressing without NAT."},
    {"type": "mc",
     "q": "Which transition mechanism runs IPv4 and IPv6 simultaneously on every interface and is considered the preferred approach?",
     "choices": ["Teredo", "NAT64", "6to4 tunneling", "Dual stack"],
     "answer": 3,
     "explain": "Dual stack gives each interface both an IPv4 and an IPv6 address, using whichever protocol a destination supports (preferring IPv6) with no translation overhead. Its cost is managing two addressing plans during the transition."},
    {"type": "mc",
     "q": "An IPv6-only mobile carrier must let subscribers browse IPv4-only websites. Which combination makes this work?",
     "choices": ["NAT64 with DNS64", "Dual stack with SLAAC", "VXLAN with VTEPs", "ISATAP with APIPA"],
     "answer": 0,
     "explain": "DNS64 synthesizes AAAA records embedding the IPv4 server's address in a special prefix, giving the IPv6-only client an IPv6 destination; NAT64 then statefully translates the packets between IPv6 and IPv4. This pairing is standard in IPv6-only carrier networks."},
    {"type": "mc",
     "q": "Which IPv6 mechanism encapsulates IPv6 packets inside IPv4 so they can cross an IPv4-only network?",
     "choices": ["SLAAC", "Tunneling, e.g., 6to4 or Teredo", "DHCPv6", "Anycast"],
     "answer": 1,
     "explain": "Tunneling wraps IPv6 packets in IPv4 (6to4 automatically via 2002::/16, ISATAP within a site, Teredo in UDP to cross NAT) so IPv6 islands can communicate over IPv4 infrastructure. It is one of the three transition strategies alongside dual stack and translation (NAT64)."},

    # --- true/false ---
    {"type": "tf",
     "q": "IPv6 has no broadcast addresses; multicast performs those functions instead.",
     "answer": True,
     "explain": "IPv6 eliminated broadcast entirely — functions like all-hosts delivery use multicast groups such as ff02::1 (all nodes) and ff02::2 (all routers). This reduces the interrupt-everyone overhead broadcast imposed in IPv4."},
    {"type": "tf",
     "q": "An IPv6 host showing a fe80:: address alongside its global address indicates a configuration failure similar to APIPA.",
     "answer": False,
     "explain": "Every IPv6 interface always auto-configures a fe80::/10 link-local address by design, even when it also holds a global address — it is normal, not an error. Trouble is indicated only when a host has nothing but link-local where a global address was expected."},
    {"type": "tf",
     "q": "SASE delivers both networking (SD-WAN) and security functions as a converged cloud service.",
     "answer": True,
     "explain": "Secure Access Service Edge converges SD-WAN connectivity with cloud security services (SWG, CASB, ZTNA, FWaaS) delivered from points of presence near users. SSE is the same concept with the SD-WAN networking component removed."},
    {"type": "tf",
     "q": "In a zero trust model, a device on the internal corporate LAN is automatically trusted to access internal applications.",
     "answer": False,
     "explain": "Zero trust explicitly rejects location-based trust: internal devices must authenticate and be authorized for each resource just like external ones. The model assumes attackers may already be inside the perimeter."},
    {"type": "tf",
     "q": "A central Git repository serves as the single source of truth for a team's infrastructure code.",
     "answer": True,
     "explain": "The central repository (GitHub, GitLab, etc.) holds the authoritative version everyone clones from and pushes to, ending the problem of the latest config living on one engineer's laptop. Combined with version history, it makes every change traceable and reversible."},

    # --- fill in ---
    {"type": "fill",
     "q": "In SDN, the plane that makes forwarding decisions and is centralized in the controller is the ___ plane. (type your answer)",
     "answers": ["control", "control plane"],
     "explain": "SDN's key move is separating the control plane (decision logic) from the data plane (forwarding) and centralizing control in a software controller. Administrators program it via northbound APIs; it programs devices via southbound APIs like OpenFlow."},
    {"type": "fill",
     "q": "How many bits long is an IPv6 address? (type your answer)",
     "answers": ["128", "128 bits"],
     "explain": "IPv6 addresses are 128 bits, written as eight hextets of hexadecimal, versus IPv4's 32 bits. That yields roughly 3.4 x 10^38 addresses — effectively inexhaustible."},
    {"type": "fill",
     "q": "IPv6 link-local addresses begin with what prefix? (type your answer)",
     "answers": ["fe80::/10", "fe80", "fe80::"],
     "explain": "fe80::/10 is the link-local range auto-configured on every IPv6 interface and valid only on its local link. Compare global unicast 2000::/3, unique local fc00::/7, multicast ff00::/8, and loopback ::1."},
    {"type": "fill",
     "q": "What is the IPv6 loopback address? (type your answer)",
     "answers": ["::1", "::1/128"],
     "explain": "IPv6 reserves the single address ::1 for loopback, unlike IPv4 which reserves the entire 127.0.0.0/8 block. Pinging ::1 tests the local IPv6 stack."},
    {"type": "fill",
     "q": "The VXLAN device that encapsulates and decapsulates frames at each end of the tunnel is called a ___. (type your answer)",
     "answers": ["VTEP", "VXLAN tunnel endpoint", "tunnel endpoint"],
     "explain": "VTEPs (VXLAN Tunnel Endpoints) — switches or hypervisors — wrap Ethernet frames in VXLAN/UDP/IP headers on entry and strip them on exit. Everything between the VTEPs is ordinary routed IP."},
    {"type": "fill",
     "q": "Ansible calls its ordered, reusable list of automation tasks a ___. (type your answer)",
     "answers": ["playbook", "playbooks"],
     "explain": "A playbook defines the sequence of tasks (create VLANs, set routing, apply ACLs) to run against many devices, and it can reference reusable roles and templates. Playbooks make network changes repeatable, consistent, and reviewable."},

    # --- match ---
    {"type": "match",
     "q": "Match each SD-WAN characteristic to its description.",
     "pairs": [
         ["Application aware", "Identifies apps and steers each per policy and link quality"],
         ["Zero-touch provisioning", "New device pulls its configuration automatically"],
         ["Transport agnostic", "Works over any mix of MPLS, broadband, and LTE"],
         ["Central policy management", "One policy change propagates to every site"],
     ],
     "explain": "These four hallmarks define SD-WAN on the exam: per-application routing, self-configuring branch devices, indifference to underlying circuit type, and single-console policy control. Together they replace manual box-by-box WAN management."},
    {"type": "match",
     "q": "Match each IPv6 address type to its prefix.",
     "pairs": [
         ["Global unicast", "2000::/3"],
         ["Link-local", "fe80::/10"],
         ["Unique local", "fc00::/7"],
         ["Multicast", "ff00::/8"],
         ["Loopback", "::1"],
     ],
     "explain": "Recognize IPv6 types by prefix: 2000::/3 is public global unicast, fe80::/10 is link-local (always present per interface), fc00::/7 is private unique-local space, ff00::/8 is multicast, and ::1 is loopback. There is no broadcast type in IPv6."},
    {"type": "match",
     "q": "Match each source-control concept to its purpose.",
     "pairs": [
         ["Version control", "History of every change with rollback"],
         ["Central repository", "Single authoritative source of truth"],
         ["Conflict identification", "Flags overlapping edits for human resolution"],
         ["Branching", "Isolated line of development before merge"],
     ],
     "explain": "Storing infrastructure code in Git brings software discipline to networking: full change history, one authoritative repo, detection of clashing edits, and safe experimentation on branches merged only after review."},

    # --- order ---
    {"type": "order",
     "q": "Arrange the steps of an IaC-driven network change in the correct order.",
     "items": [
         "Create a branch from the main repository",
         "Edit the configuration template and commit the change",
         "Open a pull request for peer review",
         "Merge the approved change into main",
         "Automation deploys the new configuration to devices",
         "Compliance checks confirm no configuration drift",
     ],
     "explain": "IaC workflow mirrors software development: branch, commit, review via pull request, merge, automated deployment, then continuous compliance verification against the desired state. Every step is logged, reviewable, and reversible."},
    {"type": "order",
     "q": "Arrange the journey of an Ethernet frame across a VXLAN tunnel, in order.",
     "items": [
         "Server sends an ordinary Ethernet frame",
         "Local VTEP encapsulates the frame in VXLAN/UDP/IP with its VNI",
         "The packet is routed across the Layer 3 underlay network",
         "Remote VTEP strips the VXLAN encapsulation",
         "The original frame is delivered to the destination server",
     ],
     "explain": "VXLAN is MAC-in-UDP encapsulation: the ingress VTEP wraps the frame (UDP port 4789) tagged with the 24-bit VNI, the routed underlay carries it like any IP packet, and the egress VTEP unwraps it. The servers never know a routed network sat in the middle."},
]
