TOPIC = {
    "id": "2.1",
    "domain": 2,
    "title": "Explain characteristics of routing technologies",
    "short": "Routing Technologies",
}

TERMS = [
    ("Static routing", "Routes manually configured by an administrator; predictable and low-overhead but does not adapt to failures and does not scale"),
    ("Default route", "The route 0.0.0.0/0 (IPv6 ::/0) that matches any destination not found elsewhere in the routing table; the gateway of last resort"),
    ("Dynamic routing", "Routers exchange route advertisements and automatically build/update routing tables, converging around topology changes"),
    ("IGP (Interior Gateway Protocol)", "A routing protocol used within a single autonomous system - OSPF, EIGRP, RIP, IS-IS"),
    ("EGP (Exterior Gateway Protocol)", "A routing protocol used between autonomous systems; BGP is the only EGP in use today"),
    ("Autonomous system (AS)", "A network under one administrative control, identified by an AS number; BGP routes between them"),
    ("BGP (Border Gateway Protocol)", "Path vector exterior gateway protocol of the internet; advertises AS paths, runs over TCP port 179"),
    ("eBGP vs iBGP", "External BGP peers routers in different autonomous systems (AD 20); internal BGP peers routers within the same AS (AD 200)"),
    ("EIGRP", "Cisco-originated advanced distance vector IGP using the DUAL algorithm; default metric combines bandwidth and delay; AD 90"),
    ("DUAL", "EIGRP's Diffusing Update Algorithm - guarantees loop-free paths and precomputes feasible-successor backup routes for fast failover"),
    ("OSPF (Open Shortest Path First)", "Open-standard link state IGP; floods LSAs, runs Dijkstra SPF, uses bandwidth-based cost, organizes routers into areas; AD 110"),
    ("OSPF Area 0", "The backbone area of an OSPF network; all other areas must connect to it through Area Border Routers"),
    ("Link state protocol", "Every router floods link advertisements so all share an identical topology map, then each independently computes shortest paths (Dijkstra)"),
    ("Distance vector protocol", "Routers share their routing tables with direct neighbors ('routing by rumor') and pick paths by distance metric; e.g., RIP"),
    ("Path vector protocol", "Routing class that advertises the full autonomous-system path for each route and prevents loops by rejecting paths containing its own AS; BGP"),
    ("Administrative distance", "Trustworthiness rating of a route source; lower wins - connected 0, static 1, eBGP 20, EIGRP 90, OSPF 110, RIP 120"),
    ("Longest prefix match", "The first routing decision: the most specific route (longest subnet mask) to the destination always wins, before AD or metric are compared"),
    ("Metric", "A routing protocol's internal measure of path quality, used to pick among routes learned by the same protocol - e.g., RIP hop count, OSPF cost"),
    ("NAT (Network Address Translation)", "Rewriting private IP addresses to public ones at the network edge; static NAT is a fixed 1:1 map, dynamic NAT draws 1:1 from a pool"),
    ("PAT (Port Address Translation)", "NAT overload - many private hosts share one public IP, with sessions distinguished by unique source port numbers"),
    ("Port forwarding", "A static NAT rule mapping a public IP:port to an internal host:port so outside users can reach an internal service"),
    ("FHRP (First Hop Redundancy Protocol)", "Lets multiple routers share a virtual IP and virtual MAC as a redundant default gateway - HSRP, VRRP, GLBP"),
    ("HSRP", "Cisco-proprietary FHRP with one active and one standby router sharing a virtual IP/MAC"),
    ("VRRP", "The IETF standard, vendor-neutral FHRP; master and backup routers share a virtual IP"),
    ("GLBP", "Cisco FHRP that load-balances by handing different virtual MAC addresses to hosts so multiple gateways forward simultaneously"),
    ("Virtual IP (VIP)", "An IP address not tied to one physical device - used by FHRPs for the shared gateway and by load balancers as the client-facing service address"),
    ("Subinterface", "A logical subdivision of one physical router interface, each with its own IP/VLAN tag; enables router-on-a-stick inter-VLAN routing"),
    ("Router-on-a-stick", "Inter-VLAN routing design where one physical router interface with 802.1Q subinterfaces connects to a switch trunk port"),
]

QUESTIONS = [
    # --- Static routing ---
    {
        "type": "mc",
        "q": "A branch office has a single WAN link to headquarters and no redundant paths. Which routing approach adds the least overhead on the branch router?",
        "choices": ["OSPF in a stub area", "A static default route", "eBGP peering with HQ", "EIGRP with a feasible successor"],
        "answer": 1,
        "explain": "A stub network with one exit path is the classic static-route use case. A static default route consumes no CPU, memory, or bandwidth for routing updates and is completely predictable. Dynamic protocols add overhead with no benefit when there is only one possible path.",
    },
    {
        "type": "mc",
        "q": "Which destination/mask represents an IPv4 default route?",
        "choices": ["255.255.255.255/32", "127.0.0.1/8", "0.0.0.0/0", "169.254.0.0/16"],
        "answer": 2,
        "explain": "The default route is 0.0.0.0/0 - a prefix length of zero matches every destination address. Because longest prefix match is evaluated first, the default route is only used when no more specific route exists, making it the gateway of last resort.",
    },
    {
        "type": "mc",
        "q": "What is the primary disadvantage of static routing in a large enterprise?",
        "choices": [
            "It consumes excessive bandwidth with periodic updates",
            "It cannot adapt automatically when a link fails",
            "It is less secure than dynamic routing",
            "It requires a routing protocol license on each router",
        ],
        "answer": 1,
        "explain": "Static routes never change on their own: if a link fails, traffic is black-holed until an administrator reconfigures the route. Static routing actually uses no update bandwidth and is considered more secure than dynamic routing, but it does not scale and cannot self-heal.",
    },
    {
        "type": "tf",
        "q": "True or False: A static route is generally considered more secure than a dynamic routing protocol because there are no routing advertisements to intercept or spoof.",
        "answer": True,
        "explain": "Static routes generate no protocol traffic, so there is nothing for an attacker to poison, spoof, or eavesdrop on. This is one of static routing's advantages, along with predictability and zero protocol overhead - at the cost of no automatic failover.",
    },
    {
        "type": "fill",
        "q": "The router entry used when no other route matches a destination is called the gateway of last ______. (type your answer)",
        "answers": ["resort"],
        "explain": "The default route (0.0.0.0/0) is called the gateway of last resort because it is consulted only after every more specific route fails to match. It is typically a static route pointing at the ISP or upstream router.",
    },
    # --- Dynamic routing: classes ---
    {
        "type": "mc",
        "q": "Which routing protocol classification describes OSPF?",
        "choices": ["Link state IGP", "Distance vector IGP", "Path vector EGP", "Advanced distance vector IGP"],
        "answer": 0,
        "explain": "OSPF is a link state interior gateway protocol: every router floods LSAs to build an identical topology database, then runs Dijkstra's SPF algorithm. Path vector EGP describes BGP, and advanced distance vector describes EIGRP.",
    },
    {
        "type": "mc",
        "q": "Which statement best describes how a distance vector protocol like RIP learns routes?",
        "choices": [
            "Each router floods link advertisements so all routers build a full topology map",
            "Each router advertises the complete AS path for every prefix",
            "Routers share their routing tables with directly connected neighbors and trust what they hear",
            "A central controller computes routes and pushes them to each router",
        ],
        "answer": 2,
        "explain": "Distance vector protocols perform 'routing by rumor': each router periodically tells its neighbors what it knows, and neighbors trust those secondhand reports. Link state protocols (OSPF) flood topology information instead, and path vector (BGP) advertises AS paths.",
    },
    {
        "type": "tf",
        "q": "True or False: BGP is an Interior Gateway Protocol used to route within a single autonomous system.",
        "answer": False,
        "explain": "BGP is the Exterior Gateway Protocol - it routes between autonomous systems and is the routing protocol of the internet. OSPF, EIGRP, RIP, and IS-IS are the IGPs used within an AS. (iBGP runs inside an AS but exists to carry external routes across it.)",
    },
    {
        "type": "match",
        "q": "Match each routing protocol to its classification.",
        "pairs": [
            ["OSPF", "Link state"],
            ["RIP", "Distance vector"],
            ["EIGRP", "Advanced distance vector"],
            ["BGP", "Path vector"],
        ],
        "explain": "OSPF floods LSAs and runs Dijkstra (link state). RIP shares routing tables with neighbors using hop count (distance vector). EIGRP is Cisco's advanced/hybrid distance vector protocol using DUAL. BGP advertises full AS paths (path vector).",
    },
    # --- BGP ---
    {
        "type": "mc",
        "q": "Which protocol and port does BGP use to establish peering sessions?",
        "choices": ["UDP 520", "TCP 179", "IP protocol 89", "UDP 179"],
        "answer": 1,
        "explain": "BGP peers form sessions over TCP port 179, letting TCP provide reliable delivery. UDP 520 is RIP, and IP protocol 89 is OSPF. Knowing BGP = TCP 179 is a frequent exam point.",
    },
    {
        "type": "mc",
        "q": "Two ISPs exchange routes at an internet exchange. Their routers are in different autonomous systems. What type of BGP session is this?",
        "choices": ["iBGP", "IGP redistribution", "eBGP", "OSPF virtual link"],
        "answer": 2,
        "explain": "BGP peering between routers in different autonomous systems is external BGP (eBGP), with an administrative distance of 20. iBGP is peering between routers inside the same AS (AD 200).",
    },
    {
        "type": "mc",
        "q": "How does BGP prevent routing loops?",
        "choices": [
            "It rejects any advertisement whose AS path already contains its own AS number",
            "It uses a hop count limit of 15",
            "It runs the DUAL algorithm to compute loop-free successors",
            "It blocks redundant paths with spanning tree",
        ],
        "answer": 0,
        "explain": "As a path vector protocol, BGP carries the ordered list of autonomous systems each route has traversed. If a router sees its own AS number already in the path, accepting the route would create a loop, so it discards it. Hop limits belong to RIP and DUAL to EIGRP.",
    },
    {
        "type": "fill",
        "q": "BGP routes between autonomous systems and is known as the routing protocol of the ______. (type your answer)",
        "answers": ["internet"],
        "explain": "BGP is the only exterior gateway protocol in use and glues the internet together: every ISP and large organization advertises its prefixes to the world via BGP, with routes selected by policy and AS-path attributes rather than raw link speed.",
    },
    # --- EIGRP ---
    {
        "type": "mc",
        "q": "Which two values does EIGRP use in its composite metric by default?",
        "choices": [
            "Hop count and MTU",
            "Bandwidth and delay",
            "Cost and reliability",
            "Load and hop count",
        ],
        "answer": 1,
        "explain": "By default EIGRP's metric combines the lowest bandwidth along the path with the cumulative delay. Load and reliability exist as optional K-values but are disabled by default. Hop count is RIP's metric and cost is OSPF's.",
    },
    {
        "type": "mc",
        "q": "Which algorithm does EIGRP use to guarantee loop-free paths and maintain precomputed backup routes?",
        "choices": ["Dijkstra SPF", "Bellman-Ford", "Spanning Tree", "DUAL"],
        "answer": 3,
        "explain": "EIGRP's Diffusing Update Algorithm (DUAL) selects the best path (successor) and precomputes a loop-free backup (feasible successor), allowing near-instant failover without recomputation. Dijkstra SPF belongs to OSPF and Bellman-Ford to RIP.",
    },
    {
        "type": "tf",
        "q": "True or False: EIGRP originated as a Cisco-proprietary protocol and is classified as an advanced distance vector protocol.",
        "answer": True,
        "explain": "EIGRP was developed by Cisco (later published as an informational RFC) and is called an advanced or hybrid distance vector protocol: it shares routes with neighbors like distance vector protocols but adds DUAL, incremental updates, and fast convergence.",
    },
    # --- OSPF ---
    {
        "type": "mc",
        "q": "In a multi-area OSPF design, which area must all other areas connect to?",
        "choices": ["Area 1", "The stub area", "Area 0, the backbone", "The NSSA"],
        "answer": 2,
        "explain": "OSPF uses a two-level hierarchy in which every non-backbone area must attach to Area 0 (the backbone) through an Area Border Router. This containment of LSA flooding and SPF recalculation is what lets OSPF scale.",
    },
    {
        "type": "mc",
        "q": "What is the default OSPF hello interval and dead interval on an Ethernet network?",
        "choices": [
            "Hello 5 seconds, dead 15 seconds",
            "Hello 10 seconds, dead 40 seconds",
            "Hello 30 seconds, dead 120 seconds",
            "Hello 2 seconds, dead 6 seconds",
        ],
        "answer": 1,
        "explain": "On broadcast and point-to-point networks OSPF sends hellos every 10 seconds, and a neighbor is declared down after the 40-second dead interval (4x hello). These timers must match on both routers or the adjacency never forms.",
    },
    {
        "type": "mc",
        "q": "Two directly connected routers run OSPF but never become neighbors. Which mismatch is a likely cause?",
        "choices": [
            "Different router IDs",
            "Different process IDs",
            "Mismatched hello/dead timers or area IDs",
            "One router is the DR and the other is the BDR",
        ],
        "answer": 2,
        "explain": "OSPF adjacency requires matching hello/dead intervals, area ID, subnet/mask, and authentication. Router IDs are supposed to differ, and process IDs are locally significant only. DR/BDR roles are a normal result of adjacency, not a barrier to it.",
    },
    {
        "type": "mc",
        "q": "How is the OSPF cost metric derived by default?",
        "choices": [
            "Reference bandwidth divided by interface bandwidth",
            "Cumulative delay along the path",
            "Number of routers to the destination",
            "Administrator-assigned tag values",
        ],
        "answer": 0,
        "explain": "OSPF cost = reference bandwidth / interface bandwidth, with a default reference of 100 Mbps - so faster links get lower cost and are preferred. Modern networks raise the reference bandwidth so 10G and 100G links don't all collapse to cost 1.",
    },
    {
        "type": "fill",
        "q": "OSPF routers compute shortest paths from their link-state database using the ______ SPF algorithm. (type your answer)",
        "answers": ["dijkstra", "dijkstra's"],
        "explain": "Every OSPF router holds an identical link-state database built from flooded LSAs and independently runs Dijkstra's shortest path first algorithm to compute its own loop-free routing tree.",
    },
    # --- Route selection ---
    {
        "type": "mc",
        "q": "A router has these routes: OSPF 10.1.1.0/24, static 10.0.0.0/8, eBGP 10.1.0.0/16. A packet arrives for 10.1.1.99. Which route is used?",
        "choices": [
            "The static route, because AD 1 beats AD 20 and AD 110",
            "The eBGP route, because AD 20 beats AD 110",
            "The OSPF route, because /24 is the longest prefix match",
            "All three, load-balanced equally",
        ],
        "answer": 2,
        "explain": "Longest prefix match is evaluated before administrative distance: the /24 is the most specific route that matches 10.1.1.99, so OSPF wins despite its higher AD. AD only breaks ties between different sources for the exact same prefix.",
    },
    {
        "type": "order",
        "q": "Arrange the route-selection criteria in the order a router evaluates them.",
        "items": [
            "Longest prefix match (most specific route)",
            "Lowest administrative distance",
            "Lowest metric",
            "Load-balance across remaining equal routes",
        ],
        "explain": "The router first finds the most specific matching prefix; among identical prefixes from different sources it prefers the lowest AD; among routes from the same protocol it prefers the lowest metric; and truly equal routes are load-balanced.",
    },
    {
        "type": "mc",
        "q": "A router learns 172.16.0.0/16 from both OSPF and RIP. Which route is installed, and why?",
        "choices": [
            "RIP, because its metric is simpler",
            "OSPF, because AD 110 is lower than RIP's 120",
            "Both, load-balanced",
            "RIP, because it converges faster",
        ],
        "answer": 1,
        "explain": "The prefixes are identical, so administrative distance breaks the tie: OSPF's AD of 110 beats RIP's 120, so the OSPF route goes into the routing table. Metrics are never compared across different protocols.",
    },
    {
        "type": "mc",
        "q": "What administrative distance does an eBGP-learned route have by default?",
        "choices": ["200", "110", "90", "20"],
        "answer": 3,
        "explain": "eBGP routes have an AD of 20, making them more trusted than any IGP-learned route. iBGP is much less trusted at 200. The full ladder to memorize: connected 0, static 1, eBGP 20, EIGRP 90, OSPF 110, RIP 120, iBGP 200.",
    },
    {
        "type": "match",
        "q": "Match each route source to its default administrative distance.",
        "pairs": [
            ["Directly connected", "0"],
            ["Static route", "1"],
            ["EIGRP (internal)", "90"],
            ["OSPF", "110"],
            ["RIP", "120"],
        ],
        "explain": "Administrative distance ranks the trustworthiness of route sources; lower wins when the same prefix is learned from multiple sources. Connected 0 and static 1 are most trusted, then eBGP 20, EIGRP 90, OSPF 110, RIP 120, iBGP 200.",
    },
    {
        "type": "fill",
        "q": "A backup static route configured with a deliberately high administrative distance so it activates only when the dynamic route disappears is called a ______ static route. (type your answer)",
        "answers": ["floating"],
        "explain": "A floating static route is given an AD higher than the primary routing protocol (for example 250). It stays out of the routing table while the dynamic route exists and 'floats in' as a backup when that route is withdrawn.",
    },
    {
        "type": "tf",
        "q": "True or False: A router will compare RIP's hop-count metric directly against OSPF's cost metric to choose between routes to the same prefix.",
        "answer": False,
        "explain": "Metrics are only meaningful within a single protocol - comparing RIP hops to OSPF cost would be apples to oranges. When different protocols offer the same prefix, the router uses administrative distance, not metric, to decide.",
    },
    # --- NAT / PAT ---
    {
        "type": "mc",
        "q": "A company has one public IP address and 200 internal hosts that all need internet access simultaneously. Which technology makes this possible?",
        "choices": [
            "Static NAT",
            "Dynamic NAT",
            "PAT (NAT overload)",
            "A default route",
        ],
        "answer": 2,
        "explain": "PAT (Port Address Translation, also called NAT overload) maps many private addresses to one public address by giving each session a unique source port in the translation table. Static and dynamic NAT are both one-to-one, so a single public IP could serve only one host at a time.",
    },
    {
        "type": "mc",
        "q": "An internal web server at 192.168.10.5 must always be reachable from the internet at the same public address. Which translation type fits?",
        "choices": ["Static NAT", "Dynamic NAT", "PAT", "APIPA"],
        "answer": 0,
        "explain": "Static NAT creates a permanent one-to-one mapping between one private and one public address, ideal for published servers that must be consistently reachable from outside. Dynamic NAT mappings change over time and PAT is many-to-one for outbound traffic.",
    },
    {
        "type": "mc",
        "q": "What distinguishes dynamic NAT from PAT?",
        "choices": [
            "Dynamic NAT translates port numbers; PAT translates only IP addresses",
            "Dynamic NAT maps private hosts one-to-one to a pool of public IPs; PAT shares one public IP using unique port numbers",
            "Dynamic NAT is for inbound traffic only; PAT is for outbound only",
            "There is no difference; the terms are interchangeable",
        ],
        "answer": 1,
        "explain": "Dynamic NAT hands out public addresses one-to-one from a pool, first come first served - when the pool empties, extra hosts wait. PAT overloads a single public address by tracking each session's translated source port, which is why it conserves addresses so well.",
    },
    {
        "type": "fill",
        "q": "The rule that maps a specific port on a router's public IP to an internal host so outside users can reach an internal service is called port ______. (type your answer)",
        "answers": ["forwarding"],
        "explain": "Port forwarding (destination NAT) statically maps public_IP:port to private_IP:port - for example, forwarding TCP 443 to an internal web server. It is how services behind a PAT router are published to the internet.",
    },
    {
        "type": "tf",
        "q": "True or False: PAT keeps sessions from many internal hosts separate by assigning each translation a unique source port number.",
        "answer": True,
        "explain": "PAT's translation table records private IP:port to public IP:port pairs. Because each outbound session gets a unique public-side source port, return traffic can be matched back to the correct internal host even though everyone shares one public IP.",
    },
    # --- FHRP / VIP ---
    {
        "type": "mc",
        "q": "What problem do First Hop Redundancy Protocols solve?",
        "choices": [
            "Layer 2 switching loops caused by redundant links",
            "The default gateway being a single point of failure for hosts",
            "Public IPv4 address exhaustion",
            "Slow convergence of distance vector protocols",
        ],
        "answer": 1,
        "explain": "Hosts can only be configured with one default gateway, so if that router fails the whole subnet loses outside connectivity. FHRPs (HSRP, VRRP, GLBP) let multiple routers share a virtual IP and virtual MAC so a standby transparently takes over - hosts never notice.",
    },
    {
        "type": "mc",
        "q": "Which FHRP is an open IETF standard usable across different vendors' routers?",
        "choices": ["HSRP", "GLBP", "VRRP", "CARP is the only option"],
        "answer": 2,
        "explain": "VRRP (Virtual Router Redundancy Protocol) is the vendor-neutral IETF standard. HSRP and GLBP are Cisco proprietary - GLBP's distinguishing feature is that it also load-balances traffic across multiple gateways.",
    },
    {
        "type": "mc",
        "q": "A network team wants gateway redundancy AND wants both routers actively forwarding traffic for the subnet. Which Cisco protocol provides this?",
        "choices": ["HSRP", "GLBP", "VRRP", "OSPF"],
        "answer": 1,
        "explain": "GLBP (Gateway Load Balancing Protocol) answers ARP requests for the one virtual IP with different virtual MAC addresses, spreading hosts across multiple forwarding routers. HSRP and VRRP have only one router actively forwarding at a time.",
    },
    {
        "type": "mc",
        "q": "Clients connect to a load balancer's advertised address, which distributes their sessions across a pool of web servers. What is this shared address called?",
        "choices": ["A loopback IP", "A virtual IP (VIP)", "A broadcast address", "An APIPA address"],
        "answer": 1,
        "explain": "A virtual IP is not bound to any single physical machine - the load balancer presents the VIP to clients and forwards each session to a real server behind it. FHRPs use VIPs the same way for redundant gateways: the service address floats free of the hardware.",
    },
    {
        "type": "tf",
        "q": "True or False: In HSRP, hosts must be reconfigured with the standby router's IP address after the active router fails.",
        "answer": False,
        "explain": "The whole point of an FHRP is that hosts point at the virtual IP, not at either physical router. When the active router fails, the standby assumes the virtual IP and virtual MAC, so failover is invisible to hosts and no reconfiguration is needed.",
    },
    # --- Subinterfaces ---
    {
        "type": "mc",
        "q": "A router connects to a switch trunk carrying VLANs 10, 20, and 30 on a single physical interface and routes between them. What feature makes this possible?",
        "choices": [
            "802.1Q subinterfaces (router-on-a-stick)",
            "Port forwarding",
            "A floating static route",
            "PAT overload",
        ],
        "answer": 0,
        "explain": "Router-on-a-stick divides one physical interface into logical subinterfaces, each tagged for one VLAN (encapsulation dot1Q) and addressed in that VLAN's subnet. Each subinterface acts as the gateway for its VLAN, and the router routes between them over the single trunk link.",
    },
    {
        "type": "mc",
        "q": "Users on VLAN 20 cannot reach VLAN 10 through a router-on-a-stick setup. The router subinterfaces are configured correctly. What switch-side misconfiguration is the most likely cause?",
        "choices": [
            "The switch port to the router is an access port instead of a trunk",
            "The switch has spanning tree enabled",
            "The switch's MTU is set to 1500",
            "The router's AD values are wrong",
        ],
        "answer": 0,
        "explain": "Router-on-a-stick only works if the switch-to-router link is an 802.1Q trunk carrying all the VLANs. If the port is left as an access port, only one VLAN's untagged traffic reaches the router, so inter-VLAN routing fails. STP and default MTU are normal and harmless here.",
    },
    {
        "type": "order",
        "q": "Arrange the path of a frame from a PC in VLAN 10 to a server in VLAN 20 using router-on-a-stick.",
        "items": [
            "PC sends the frame to its default gateway (the VLAN 10 subinterface)",
            "Switch tags the frame for VLAN 10 and sends it up the trunk",
            "Router receives it on the VLAN 10 subinterface, routes it, and sends it back down the trunk tagged for VLAN 20",
            "Switch strips the VLAN 20 tag and delivers the frame to the server's access port",
        ],
        "explain": "Inter-VLAN traffic must go up to the Layer 3 device and back down - the 'stick' is the single trunk link. The switch tags frames on the trunk, the router routes between subinterfaces, and tags are stripped before delivery on access ports.",
    },
]
