TOPIC = {
    "id": "2.2",
    "domain": 2,
    "title": "Given a scenario, configure switching technologies and features",
    "short": "Switching Technologies",
}

TERMS = [
    ("VLAN (Virtual Local Area Network)", "Logical Layer 2 segmentation of a switch into separate broadcast domains; IDs 1-4094, with VLAN 1 as the default"),
    ("Broadcast domain", "The set of devices that receive each other's broadcast frames; each VLAN is its own broadcast domain"),
    ("VLAN database", "The switch's stored list of VLAN IDs, names, and states (vlan.dat on Cisco); a VLAN must exist there before ports can use it"),
    ("SVI (Switch Virtual Interface)", "A virtual Layer 3 interface for a VLAN (e.g., 'interface vlan 10'); used for switch management and inter-VLAN routing on Layer 3 switches"),
    ("Access port", "A switch port assigned to a single data VLAN that sends and receives untagged frames; used for end devices"),
    ("Trunk port", "A switch port carrying multiple VLANs between devices, identifying each frame's VLAN with an 802.1Q tag"),
    ("Native VLAN", "The one VLAN whose frames cross an 802.1Q trunk untagged; defaults to VLAN 1 and must match on both ends"),
    ("Voice VLAN", "A separate tagged VLAN on an access port so an IP phone and PC share one port, with voice traffic prioritized via CoS"),
    ("802.1Q", "IEEE VLAN trunking standard: inserts a 4-byte tag (with a 12-bit VLAN ID and 3-bit priority) into the Ethernet frame"),
    ("CoS (Class of Service)", "The 3-bit 802.1p priority field inside the 802.1Q tag, used to prioritize traffic such as voice at Layer 2"),
    ("Link aggregation", "Bundling multiple physical links into one logical link for added bandwidth and redundancy (EtherChannel/port channel/LAG)"),
    ("LACP (802.3ad)", "Link Aggregation Control Protocol - the IEEE standard for negotiating a link bundle; settings must match on both ends"),
    ("Autonegotiation", "Process by which both link ends advertise capabilities and agree on the highest common speed and duplex"),
    ("Duplex mismatch", "One side full duplex, one side half duplex - causes late collisions, CRC errors, and severe slowness while the link stays up"),
    ("Full duplex", "Simultaneous transmit and receive with no collisions; standard on modern switched links"),
    ("STP (Spanning Tree Protocol, 802.1D)", "Prevents Layer 2 loops by electing a root bridge and blocking redundant paths; converges in 30-50 seconds"),
    ("RSTP (802.1w)", "Rapid Spanning Tree - backward-compatible STP replacement that converges in seconds using discarding/learning/forwarding states"),
    ("Broadcast storm", "Loop-driven flood of endlessly circulating frames (Ethernet has no TTL) that saturates links and CPUs"),
    ("Root bridge", "The switch all STP paths lead to; elected by lowest bridge ID (priority first, lowest MAC as tiebreaker)"),
    ("Bridge ID", "Priority value (default 32768) plus the switch MAC address; lowest wins the root bridge election"),
    ("Root port", "On each non-root switch, the single port with the lowest path cost toward the root bridge"),
    ("Designated port", "The forwarding STP port on a network segment closest to the root; all root-bridge ports are designated"),
    ("BPDU (Bridge Protocol Data Unit)", "The messages switches exchange to build and maintain the spanning tree"),
    ("PortFast", "STP feature for host-facing access ports that skips listening/learning and forwards immediately; never for switch-to-switch links"),
    ("BPDU guard", "Error-disables a PortFast port if a BPDU arrives, protecting the STP topology from rogue or accidental switches"),
    ("MTU (Maximum Transmission Unit)", "Largest payload an interface sends in one frame; Ethernet default is 1500 bytes"),
    ("Jumbo frames", "Frames with an MTU around 9000 bytes; reduce per-frame overhead for storage/iSCSI traffic but must be enabled end-to-end"),
]

QUESTIONS = [
    # --- VLAN concepts ---
    {
        "type": "mc",
        "q": "What does creating a new VLAN on a switch accomplish at Layer 2?",
        "choices": [
            "It creates a new collision domain",
            "It creates a new broadcast domain",
            "It increases the MTU for assigned ports",
            "It encrypts traffic between assigned ports",
        ],
        "answer": 1,
        "explain": "Each VLAN is a separate broadcast domain: broadcasts, ARP, and unknown-unicast flooding stay within the VLAN. Collision domains are created per switch port regardless of VLANs. Traffic cannot cross between VLANs without a Layer 3 device.",
    },
    {
        "type": "mc",
        "q": "What is the valid range of usable 802.1Q VLAN IDs?",
        "choices": ["0-4096", "1-1024", "1-4094", "2-65535"],
        "answer": 2,
        "explain": "The 802.1Q tag's 12-bit VLAN ID field yields 4096 values, but 0 and 4095 are reserved, leaving 1-4094 usable. VLAN 1 is the default VLAN that all ports belong to out of the box.",
    },
    {
        "type": "mc",
        "q": "A technician assigns port 8 to VLAN 50, but VLAN 50 was never created on the switch. Users on that port have link but no connectivity. What concept explains this?",
        "choices": [
            "The port needs PortFast enabled",
            "The VLAN must exist in the VLAN database before port assignments work",
            "VLAN 50 exceeds the maximum VLAN ID",
            "The port must be converted to a trunk first",
        ],
        "answer": 1,
        "explain": "The VLAN database (vlan.dat on Cisco switches) holds each VLAN's ID, name, and state. A port assigned to a VLAN that doesn't exist - or that exists on one switch but not its neighbors - carries traffic nowhere. Always create the VLAN, then assign ports.",
    },
    {
        "type": "mc",
        "q": "A company replaces router-on-a-stick with a Layer 3 switch. What should be configured so hosts in each VLAN have a default gateway on the switch?",
        "choices": [
            "One SVI per VLAN, each with an IP address, and routing enabled",
            "A trunk port to itself",
            "BPDU guard on all uplinks",
            "A voice VLAN on every access port",
        ],
        "answer": 0,
        "explain": "A Switch Virtual Interface (SVI) is a virtual Layer 3 interface for a VLAN. On a Layer 3 switch you create an SVI per VLAN with an IP in that VLAN's subnet, enable IP routing, and hosts use the SVI addresses as gateways - inter-VLAN routing happens in hardware.",
    },
    {
        "type": "tf",
        "q": "True or False: Hosts in different VLANs can communicate directly through the Layer 2 switch as long as they are on the same physical switch.",
        "answer": False,
        "explain": "VLAN separation is enforced regardless of physical location - inter-VLAN traffic always requires a Layer 3 device (router or Layer 3 switch/SVI). That isolation is the entire purpose of VLANs for segmentation and security.",
    },
    {
        "type": "fill",
        "q": "By default, every port on a new switch belongs to VLAN ______. (type your answer)",
        "answers": ["1", "one"],
        "explain": "VLAN 1 is the default VLAN and also the default native VLAN on trunks. Security best practice is to move user, management, and native traffic off VLAN 1 because attackers know everything defaults there.",
    },
    {
        "type": "fill",
        "q": "The virtual Layer 3 interface that gives a VLAN an IP address on a switch is abbreviated ______. (type your answer)",
        "answers": ["svi", "switch virtual interface"],
        "explain": "An SVI (Switch Virtual Interface), configured as 'interface vlan X', provides Layer 3 services for a VLAN - remote management on Layer 2 switches and wire-speed inter-VLAN routing on Layer 3 switches.",
    },
    # --- Access vs trunk, native VLAN ---
    {
        "type": "mc",
        "q": "Which statement correctly contrasts access and trunk ports?",
        "choices": [
            "Access ports tag frames; trunk ports send everything untagged",
            "Access ports carry one untagged VLAN; trunk ports carry multiple VLANs using 802.1Q tags",
            "Access ports are only for routers; trunk ports are only for PCs",
            "Access ports carry multiple VLANs; trunk ports carry exactly one",
        ],
        "answer": 1,
        "explain": "Access ports belong to a single data VLAN and exchange normal untagged Ethernet frames with end devices. Trunk ports interconnect switches (or routers/hypervisors) and insert an 802.1Q tag on each frame so the receiver knows which VLAN it belongs to.",
    },
    {
        "type": "mc",
        "q": "On an 802.1Q trunk, frames belonging to which VLAN are transmitted without a tag?",
        "choices": ["The voice VLAN", "VLAN 4094", "The native VLAN", "The management VLAN"],
        "answer": 2,
        "explain": "The native VLAN is the one VLAN that crosses the trunk untagged, and inbound untagged frames are assumed to belong to it. It defaults to VLAN 1 and must be configured identically on both ends of the trunk.",
    },
    {
        "type": "mc",
        "q": "Why do security best practices recommend changing the native VLAN from VLAN 1 to an unused VLAN?",
        "choices": [
            "VLAN 1 has less bandwidth than other VLANs",
            "It mitigates VLAN hopping / double-tagging attacks and keeps untagged traffic away from user VLANs",
            "VLAN 1 cannot carry 802.1Q tags",
            "The native VLAN must be an even number",
        ],
        "answer": 1,
        "explain": "Double-tagging attacks exploit the untagged native VLAN (which everything defaults to) to hop into other VLANs. Setting the native VLAN to an unused ID with no hosts, and keeping it consistent on both trunk ends, removes that path and prevents accidental leakage.",
    },
    {
        "type": "tf",
        "q": "True or False: A native VLAN mismatch between the two ends of a trunk can cause traffic to leak between two different VLANs.",
        "answer": True,
        "explain": "If side A sends VLAN 10 untagged (its native) and side B treats untagged frames as VLAN 20 (its native), frames silently cross between VLAN 10 and VLAN 20. Switches log native VLAN mismatch warnings via CDP, and the fix is making both ends match.",
    },
    # --- Voice VLAN ---
    {
        "type": "mc",
        "q": "An IP phone and a PC share one switch port, with the PC plugged into the phone. How is traffic typically separated?",
        "choices": [
            "Both devices share the data VLAN with no separation",
            "The PC's traffic is tagged in the voice VLAN; the phone's is untagged",
            "The phone's traffic is tagged in the voice VLAN; the PC's traffic rides the untagged data VLAN",
            "The port must be configured as a full trunk with all VLANs allowed",
        ],
        "answer": 2,
        "explain": "A voice VLAN makes the access port a mini-trunk: the phone tags its traffic into the voice VLAN (learned via CDP/LLDP-MED) while the PC's frames pass through the phone untagged in the data VLAN. Voice frames also carry CoS priority so QoS can protect call quality.",
    },
    {
        "type": "mc",
        "q": "Which mechanism lets the switch prioritize voice frames at Layer 2 within the 802.1Q tag?",
        "choices": [
            "The 3-bit CoS/802.1p priority field",
            "The 12-bit VLAN ID field",
            "The frame check sequence",
            "DSCP markings in the Ethernet header",
        ],
        "answer": 0,
        "explain": "The 802.1Q tag includes a 3-bit Priority Code Point (802.1p), called Class of Service, giving 8 priority levels at Layer 2. Voice is typically marked CoS 5 so switches queue it ahead of data. DSCP is the Layer 3 equivalent in the IP header, not the Ethernet frame.",
    },
    # --- 802.1Q ---
    {
        "type": "mc",
        "q": "How does 802.1Q identify a frame's VLAN on a trunk?",
        "choices": [
            "It encapsulates the entire frame in a new 26-byte header",
            "It inserts a 4-byte tag containing a 12-bit VLAN ID into the frame",
            "It rewrites the destination MAC address with the VLAN number",
            "It prepends the VLAN name in ASCII",
        ],
        "answer": 1,
        "explain": "802.1Q inserts a 4-byte tag between the source MAC and EtherType fields (recalculating the FCS). The tag holds a 16-bit TPID (0x8100), 3 priority bits, and a 12-bit VLAN ID - hence 4094 usable VLANs. It tags rather than encapsulating the whole frame.",
    },
    {
        "type": "fill",
        "q": "The 802.1Q VLAN ID field is ______ bits long. (type your answer)",
        "answers": ["12", "twelve"],
        "explain": "The 12-bit VLAN ID field provides 2^12 = 4096 values; with 0 and 4095 reserved, VLANs 1-4094 are usable. The other notable tag fields are the 3-bit priority (CoS) and the TPID of 0x8100 that marks the frame as tagged.",
    },
    {
        "type": "match",
        "q": "Match each IEEE standard to what it defines.",
        "pairs": [
            ["802.1Q", "VLAN tagging on trunks"],
            ["802.3ad", "Link aggregation (LACP)"],
            ["802.1D", "Original Spanning Tree Protocol"],
            ["802.1w", "Rapid Spanning Tree Protocol"],
        ],
        "explain": "These four standards are high-yield exam matches: 802.1Q inserts VLAN tags, 802.3ad defines LACP link bundling, 802.1D is classic STP with 30-50 second convergence, and 802.1w is RSTP with convergence in seconds.",
    },
    # --- Link aggregation ---
    {
        "type": "mc",
        "q": "What are the two main benefits of link aggregation between two switches?",
        "choices": [
            "Loop prevention and encryption",
            "Increased aggregate bandwidth and redundancy if a member link fails",
            "Lower latency per frame and jumbo frame support",
            "Automatic VLAN creation and faster STP elections",
        ],
        "answer": 1,
        "explain": "A LAG bundles multiple physical links into one logical link: throughput scales with the member count (per-flow hashing), and if one cable fails the bundle keeps forwarding on the survivors. STP also treats the bundle as one link, so no members are blocked.",
    },
    {
        "type": "mc",
        "q": "Which protocol negotiates link aggregation bundles, and under which IEEE standard was it defined?",
        "choices": ["PAgP under 802.1X", "LACP under 802.3ad", "LLDP under 802.1AB", "LACP under 802.11ac"],
        "answer": 1,
        "explain": "LACP (Link Aggregation Control Protocol) was standardized in IEEE 802.3ad (later moved to 802.1AX). It negotiates the bundle dynamically, detecting mismatches and failed members. PAgP is Cisco's older proprietary equivalent.",
    },
    {
        "type": "mc",
        "q": "An engineer bundles four ports with LACP, but the port channel won't come up. Three ports are set to 1000/full in VLAN 10 trunk mode; the fourth is set to 100/full. What is wrong?",
        "choices": [
            "LACP supports a maximum of two links",
            "All member ports must have matching configuration, including speed",
            "LACP requires half duplex on all members",
            "The bundle needs an even number of ports at each speed",
        ],
        "answer": 1,
        "explain": "Every member of an aggregation group must match: speed, duplex, VLAN/trunk configuration, and compatible LACP modes on both ends (at least one side active). A mismatched member is suspended or the bundle fails to form.",
    },
    {
        "type": "tf",
        "q": "True or False: A single large file transfer will use the full combined bandwidth of a 4 x 1 Gbps LACP bundle.",
        "answer": False,
        "explain": "LAG distributes traffic per-flow using a hash of addresses/ports, and any single flow stays on one member link to preserve frame ordering. So one transfer maxes out at 1 Gbps; the aggregate 4 Gbps is realized across many simultaneous flows.",
    },
    # --- Speed / duplex ---
    {
        "type": "mc",
        "q": "One end of a link is hard-coded to 100 Mbps full duplex; the other end is left on autonegotiate. What duplex will the auto side most likely choose?",
        "choices": ["Full duplex", "Half duplex", "It will refuse to link up", "It alternates between full and half"],
        "answer": 1,
        "explain": "When the far end doesn't participate in autonegotiation, the auto side can detect speed but not duplex, and the standard fallback is half duplex - creating a duplex mismatch. Best practice: set both ends to auto, or hard-code both ends identically.",
    },
    {
        "type": "mc",
        "q": "Users report a server link is up but painfully slow. The switch interface shows increasing late collisions and CRC errors. What is the most likely cause?",
        "choices": [
            "A broadcast storm",
            "Jumbo frames enabled on the server",
            "A duplex mismatch",
            "An STP topology change",
        ],
        "answer": 2,
        "explain": "Late collisions and CRC/FCS errors on a link that stays up are the signature of a duplex mismatch: the half-duplex side detects 'collisions' when the full-duplex side transmits while it is sending. Throughput collapses under load even though light traffic works.",
    },
    {
        "type": "tf",
        "q": "True or False: In full-duplex operation, a switch port can transmit and receive simultaneously and collisions cannot occur on that link.",
        "answer": True,
        "explain": "Full duplex gives each direction its own wire pairs/lanes with no shared medium, so CSMA/CD is unnecessary and collisions are impossible. Any collisions counted on a modern switched link therefore indicate a misconfiguration such as a duplex mismatch.",
    },
    # --- Spanning tree ---
    {
        "type": "mc",
        "q": "What is the primary purpose of Spanning Tree Protocol?",
        "choices": [
            "To prevent Layer 2 loops and the broadcast storms they cause",
            "To aggregate multiple links into one logical link",
            "To route between VLANs",
            "To tag frames with VLAN membership",
        ],
        "answer": 0,
        "explain": "Redundant switch links create Layer 2 loops, and since Ethernet frames have no TTL, broadcasts circulate forever - a broadcast storm - along with MAC table instability. STP logically blocks redundant paths, keeping one loop-free tree while preserving failover.",
    },
    {
        "type": "mc",
        "q": "A junior admin connects two access switches with a second cable 'for backup' and within a minute the whole floor slows to a crawl with the same MACs flapping between ports. STP was disabled. What happened?",
        "choices": [
            "A duplex mismatch on the new cable",
            "A broadcast storm caused by a Layer 2 loop",
            "The VLAN database was overwritten",
            "The MTU was exceeded on the uplink",
        ],
        "answer": 1,
        "explain": "With no STP to block one path, every broadcast circulates the loop endlessly and gets re-flooded each pass, saturating links and CPUs, while source MACs appear on multiple ports (MAC table instability). This is exactly the failure STP/RSTP exists to prevent.",
    },
    {
        "type": "mc",
        "q": "How is the STP root bridge elected?",
        "choices": [
            "Highest bridge priority wins; highest MAC breaks ties",
            "Lowest bridge ID wins - lowest priority first, lowest MAC as the tiebreaker",
            "The switch with the most ports wins",
            "The first switch powered on always remains root",
        ],
        "answer": 1,
        "explain": "The bridge ID combines a priority (default 32768) with the switch MAC address, and the lowest wins. Since defaults tie, the oldest (lowest-MAC) switch often becomes root by accident - so best practice is to force your core switch to root with a low priority like 4096.",
    },
    {
        "type": "mc",
        "q": "Which STP port role is the single port on a non-root switch with the best path cost toward the root bridge?",
        "choices": ["Designated port", "Root port", "Blocked port", "Edge port"],
        "answer": 1,
        "explain": "Each non-root switch elects exactly one root port - its lowest-cost path toward the root bridge. Designated ports are the forwarding ports on each segment (all root-bridge ports are designated), and blocked/alternate ports are the redundant paths held in reserve.",
    },
    {
        "type": "mc",
        "q": "Which feature shuts down a PortFast-enabled access port if a switch is plugged into it?",
        "choices": ["Root guard", "BPDU guard", "Loop guard", "DHCP snooping"],
        "answer": 1,
        "explain": "PortFast ports face end hosts and should never receive BPDUs. BPDU guard err-disables the port the moment a BPDU arrives - meaning someone attached a switch - protecting the spanning tree topology from rogue or accidental devices.",
    },
    {
        "type": "mc",
        "q": "PCs on PortFast-disabled access ports fail to get DHCP addresses right after boot, but work if the user waits and renews. Why does PortFast fix this?",
        "choices": [
            "It increases the port speed during boot",
            "It lets the port skip the listening and learning states and forward immediately",
            "It disables the need for a DHCP server",
            "It assigns the port to the native VLAN",
        ],
        "answer": 1,
        "explain": "Classic 802.1D makes every port spend about 30 seconds in listening and learning before forwarding - long enough for a booting PC's DHCP attempts to time out. PortFast marks host-facing ports as edge ports that go straight to forwarding, since no loop is possible through an end host.",
    },
    {
        "type": "tf",
        "q": "True or False: RSTP (802.1w) converges faster than the original 802.1D STP.",
        "answer": True,
        "explain": "802.1D relies on timers and takes roughly 30-50 seconds to converge. RSTP replaces the timer-based transitions with a proposal/agreement handshake and alternate ports ready to take over, converging in a few seconds or less while staying backward compatible.",
    },
    {
        "type": "fill",
        "q": "In RSTP, the blocking, listening, and disabled states of 802.1D are merged into the single ______ state. (type your answer)",
        "answers": ["discarding"],
        "explain": "RSTP has only three port states: discarding, learning, and forwarding. Any port that isn't learning MACs or forwarding frames is simply discarding - one reason RSTP's state machine is faster and simpler than 802.1D's five states.",
    },
    {
        "type": "order",
        "q": "Arrange the 802.1D STP port states in the order a port passes through them when coming up (excluding disabled).",
        "items": ["Blocking", "Listening", "Learning", "Forwarding"],
        "explain": "A port starts blocking (BPDUs only), moves to listening (participates in the topology, 15 s), then learning (builds its MAC table, 15 s), and finally forwarding. The two 15-second forward-delay stages explain classic STP's slow convergence.",
    },
    {
        "type": "match",
        "q": "Match each STP concept to its description.",
        "pairs": [
            ["Root bridge", "Switch with the lowest bridge ID"],
            ["Root port", "A non-root switch's best path toward the root"],
            ["Designated port", "Forwarding port on each segment closest to the root"],
            ["Blocked port", "Redundant path logically disabled to break the loop"],
            ["BPDU", "Message switches exchange to build the tree"],
        ],
        "explain": "STP elects one root bridge (lowest bridge ID = priority + MAC), each other switch picks one root port toward it, each segment gets one designated port, and remaining redundant ports are blocked. BPDUs carry the election and topology information.",
    },
    # --- MTU / jumbo frames ---
    {
        "type": "mc",
        "q": "What is the default MTU of a standard Ethernet interface?",
        "choices": ["1518 bytes", "1500 bytes", "9000 bytes", "576 bytes"],
        "answer": 1,
        "explain": "The default Ethernet MTU is 1500 bytes of payload (the IP packet). The frame itself adds 18 bytes of header/FCS for 1518 total, or 1522 with an 802.1Q tag. Jumbo frames raise the MTU to around 9000 bytes.",
    },
    {
        "type": "mc",
        "q": "Why are jumbo frames commonly enabled on iSCSI storage networks?",
        "choices": [
            "They encrypt storage traffic",
            "They carry about six times the data per frame, cutting per-frame overhead and CPU interrupts",
            "They are required for VLAN tagging",
            "They reduce cable attenuation",
        ],
        "answer": 1,
        "explain": "A 9000-byte jumbo frame moves roughly 6x the payload of a 1500-byte frame with the same header and processing cost, so bulk storage transfers get higher throughput and lower CPU load. That's why SAN/iSCSI, NAS, backup, and vMotion networks use them.",
    },
    {
        "type": "mc",
        "q": "After enabling jumbo frames on servers and storage arrays, iSCSI performance gets worse and sessions drop. The most likely cause is:",
        "choices": [
            "Jumbo frames are incompatible with iSCSI",
            "A switch in the path still has its MTU at 1500, so jumbo frames are fragmented or dropped",
            "The native VLAN is mismatched",
            "LACP hashing is disabled",
        ],
        "answer": 1,
        "explain": "Jumbo frames must be enabled consistently on every device in the path - server NICs, all switches, and the storage targets. Any hop still at MTU 1500 drops or fragments the oversized frames, causing retransmissions and session failures. Jumbo is all-or-nothing end to end.",
    },
    {
        "type": "fill",
        "q": "Jumbo frames typically use an MTU of approximately ______ bytes. (type your answer)",
        "answers": ["9000", "9216"],
        "explain": "Jumbo frames raise the MTU to about 9000 bytes (many switches support up to 9216 to allow for encapsulation headers). They are used on storage and data-center networks and must be configured identically end-to-end.",
    },
    {
        "type": "tf",
        "q": "True or False: Jumbo frames only need to be enabled on the two end hosts; intermediate switches adapt automatically.",
        "answer": False,
        "explain": "Switches do not fragment Layer 2 frames - a frame larger than a port's MTU is simply dropped (or counted as a giant). Every switch, router interface, and NIC along the path must have jumbo support explicitly enabled for jumbo frames to work.",
    },
]
