TOPIC = {
    "id": "2.3",
    "domain": 2,
    "title": "Given a scenario, select and configure wireless devices and technologies",
    "short": "Wireless Devices & Technologies",
}

TERMS = [
    ("Non-overlapping channels (2.4 GHz)", "Channels 1, 6, and 11 - the only US 2.4 GHz channels whose 20+ MHz-wide signals do not overlap adjacent ones"),
    ("Channel width", "Amount of spectrum a channel occupies - 20/40/80/160 MHz; wider is faster but leaves fewer clean channels and more interference"),
    ("Channel bonding", "Combining adjacent channels into a wider one (e.g., two 20 MHz channels into 40 MHz) for higher throughput"),
    ("Regulatory domain", "Country-specific radio rules (FCC in the US, ETSI in Europe) governing legal channels and transmit power"),
    ("802.11h", "Standard adding DFS and TPC so 5 GHz Wi-Fi coexists with radar and satellite systems"),
    ("DFS (Dynamic Frequency Selection)", "Requires an AP to monitor for radar on shared 5 GHz channels and vacate the channel when radar is detected"),
    ("TPC (Transmit Power Control)", "802.11h mechanism that dynamically limits transmit power to the minimum needed, reducing interference"),
    ("2.4 GHz band", "Longest range and best wall penetration but only three non-overlapping channels and heavy interference (Bluetooth, microwaves)"),
    ("5 GHz band", "Many non-overlapping 20 MHz channels and higher throughput, with shorter range; some channels require DFS"),
    ("6 GHz band", "Spectrum opened for Wi-Fi 6E: large amounts of clean spectrum, no legacy devices, WPA3 required, shortest range"),
    ("Band steering", "AP feature that nudges dual-band-capable clients onto 5/6 GHz, leaving 2.4 GHz to legacy and IoT devices"),
    ("SSID (Service Set Identifier)", "The wireless network name, up to 32 bytes, broadcast in beacon frames"),
    ("BSSID (Basic Service Set Identifier)", "The MAC address of an AP's radio, uniquely identifying one basic service set"),
    ("ESSID (Extended Service Set Identifier)", "The same SSID shared by multiple APs on a common wired network so clients can roam among them"),
    ("Infrastructure mode", "Normal Wi-Fi operation: clients associate to an access point that bridges them to the wired LAN"),
    ("Ad hoc (IBSS)", "Peer-to-peer wireless network where devices connect directly with no access point"),
    ("Point-to-point wireless", "A dedicated wireless bridge link between two locations using high-gain directional antennas with line of sight"),
    ("Mesh network", "APs that interconnect wirelessly, relaying traffic hop-by-hop and self-healing around failed nodes"),
    ("WPA2", "Wi-Fi Protected Access 2 (802.11i): AES-CCMP encryption with a PSK 4-way handshake vulnerable to offline dictionary attacks"),
    ("WPA3", "Successor to WPA2: SAE handshake resists offline dictionary attacks, adds forward secrecy and mandatory protected management frames"),
    ("SAE (Simultaneous Authentication of Equals)", "WPA3's password-authenticated key exchange; each guess needs a live exchange, defeating offline cracking"),
    ("4-way handshake", "WPA2 key exchange between client and AP; a captured handshake can be brute-forced offline against a weak PSK"),
    ("Captive portal", "Web page that intercepts a guest's first request, requiring login/AUP acceptance before granting network access"),
    ("Guest network", "Isolated SSID/VLAN giving visitors internet access while blocking the internal network"),
    ("PSK (pre-shared key)", "One passphrase shared by all users; simple but offers no per-user accountability or revocation"),
    ("Enterprise authentication", "802.1X with a RADIUS server: per-user credentials or certificates, individual session keys, central revocation"),
    ("Omnidirectional antenna", "Radiates roughly equally in all horizontal directions (360-degree doughnut pattern); standard for APs serving surrounding clients"),
    ("Directional antenna", "Focuses energy in one direction for higher gain and range - Yagi, patch/panel, and parabolic dish types"),
    ("Antenna gain (dBi)", "Measure of how much an antenna focuses energy; higher gain means a narrower beam reaching farther"),
    ("Autonomous access point", "Standalone 'fat' AP configured and managed individually - fine for small deployments"),
    ("Lightweight access point", "'Thin' AP centrally managed by a wireless LAN controller, tunneling control and data via CAPWAP"),
    ("WLC (Wireless LAN Controller)", "Central appliance that configures lightweight APs and coordinates channels, power, roaming, and rogue detection"),
]

QUESTIONS = [
    # --- Channels / non-overlapping ---
    {
        "type": "mc",
        "q": "Three neighboring APs must be placed on non-overlapping 2.4 GHz channels in the US. Which set is correct?",
        "choices": ["1, 6, 11", "1, 5, 9", "2, 7, 12", "3, 6, 9"],
        "answer": 0,
        "explain": "2.4 GHz channels are spaced only 5 MHz apart while each signal is 20+ MHz wide, so most channels overlap their neighbors. In the US (channels 1-11), only 1, 6, and 11 are far enough apart to avoid overlap - the standard honeycomb design pattern.",
    },
    {
        "type": "mc",
        "q": "A Wi-Fi analyzer shows nearby APs on 2.4 GHz channels 1, 4, and 8, all with poor performance. Why is this layout a problem?",
        "choices": [
            "Channels above 3 are illegal in the US",
            "Channels 4 and 8 partially overlap their neighbors, causing adjacent-channel interference",
            "Three APs cannot share one band",
            "Channel 1 is reserved for Bluetooth",
        ],
        "answer": 1,
        "explain": "An AP on channel 4 overlaps both channel 1 and channel 6 territory - adjacent-channel interference that appears as noise the radios can't coordinate around, which is worse than sharing the same channel. Restricting APs to 1/6/11 eliminates the overlap.",
    },
    {
        "type": "mc",
        "q": "How many channels does the US FCC permit for normal use in the 2.4 GHz band?",
        "choices": ["14", "13", "11", "3"],
        "answer": 2,
        "explain": "The US allows channels 1-11 in 2.4 GHz; channels 12-13 are used in Europe (ETSI) and 14 only in Japan for legacy 802.11b. Of the 11 US channels, only 1, 6, and 11 are non-overlapping.",
    },
    {
        "type": "tf",
        "q": "True or False: In the 5 GHz band, standard 20 MHz channels do not overlap one another.",
        "answer": True,
        "explain": "Unlike 2.4 GHz, 5 GHz channels are spaced a full 20 MHz apart, so every 20 MHz channel is non-overlapping - roughly 25 of them in the US. This abundance of clean channels is a key reason dense deployments favor 5 GHz.",
    },
    {
        "type": "fill",
        "q": "The only non-overlapping 2.4 GHz channels in the US are 1, 6, and ______. (type your answer)",
        "answers": ["11", "eleven"],
        "explain": "Channels 1, 6, and 11 are separated by 25 MHz each - enough to keep their ~20 MHz-wide signals from overlapping. Any other 2.4 GHz channel choice overlaps at least one of them.",
    },
    # --- Channel width ---
    {
        "type": "mc",
        "q": "What is the trade-off of configuring 80 MHz channel width instead of 20 MHz?",
        "choices": [
            "Higher throughput but fewer non-overlapping channels and more interference exposure",
            "Lower throughput but better range",
            "No trade-off; wider is always better",
            "Wider channels work only in 2.4 GHz",
        ],
        "answer": 0,
        "explain": "Bonding channels multiplies throughput (~4x for 80 MHz vs 20 MHz) but consumes four channels' worth of spectrum, leaving fewer clean channels for neighboring APs and picking up more interference. Dense deployments often prefer narrower channels.",
    },
    {
        "type": "mc",
        "q": "In which band is a 160 MHz channel width most practical, and why?",
        "choices": [
            "2.4 GHz, because it has the most spectrum",
            "5 GHz, because DFS is never required there",
            "6 GHz, because its large clean spectrum offers multiple 160 MHz channels",
            "Any band, since width is independent of spectrum",
        ],
        "answer": 2,
        "explain": "160 MHz needs an enormous slice of clean spectrum. The 2.4 GHz band is too small entirely, and 5 GHz can only fit a couple of 160 MHz channels (mostly requiring DFS). The 6 GHz band (Wi-Fi 6E) offers seven 160 MHz channels in the US, making wide channels practical.",
    },
    {
        "type": "tf",
        "q": "True or False: Using 40 MHz channel width in the 2.4 GHz band is recommended for enterprise deployments.",
        "answer": False,
        "explain": "A single 40 MHz channel consumes most of the tiny 2.4 GHz band, making non-overlapping AP placement impossible and colliding with neighbors. Best practice is 20 MHz in 2.4 GHz, saving wider channels for 5 and 6 GHz.",
    },
    # --- Regulatory / 802.11h ---
    {
        "type": "mc",
        "q": "Which two mechanisms did 802.11h add for 5 GHz operation?",
        "choices": [
            "Band steering and beamforming",
            "Dynamic Frequency Selection (DFS) and Transmit Power Control (TPC)",
            "SAE and protected management frames",
            "Channel bonding and MU-MIMO",
        ],
        "answer": 1,
        "explain": "802.11h enables 5 GHz Wi-Fi to coexist with radar and satellite systems: DFS detects radar and forces the AP to vacate the channel, while TPC dynamically limits transmit power. Don't confuse it with 802.11i (WPA2 security).",
    },
    {
        "type": "mc",
        "q": "An AP operating on 5 GHz channel 100 suddenly announces a channel switch and moves all clients to channel 36. What most likely happened?",
        "choices": [
            "The AP's radio is failing",
            "DFS detected radar on the channel and the AP was required to vacate it",
            "Band steering moved the AP to 2.4 GHz",
            "The regulatory domain was changed to Japan",
        ],
        "answer": 1,
        "explain": "Channel 100 is in the DFS range shared with radar. When radar pulses are detected, regulations require the AP to leave the channel - a normal, compliant event defined by 802.11h, not a hardware fault. Brief client disruption during the move is expected.",
    },
    {
        "type": "mc",
        "q": "Why must an access point be configured with the correct country/regulatory domain?",
        "choices": [
            "It changes the SSID's language encoding",
            "Legal channels and maximum transmit power differ by country, and violating them can cause illegal interference",
            "It selects between WPA2 and WPA3",
            "It determines the AP's MAC address",
        ],
        "answer": 1,
        "explain": "Regulators like the FCC (US) and ETSI (Europe) define which channels and power levels are legal - e.g., 2.4 GHz channels 12-13 are usable in Europe but not for normal US operation. A wrong domain setting can break the law and interfere with licensed users like radar.",
    },
    # --- Frequency options / band steering ---
    {
        "type": "mc",
        "q": "Which band offers the longest range and best wall penetration?",
        "choices": ["6 GHz", "5 GHz", "2.4 GHz", "All bands propagate identically"],
        "answer": 2,
        "explain": "Lower frequencies propagate farther and pass through obstacles better, so 2.4 GHz wins on coverage. The cost is congestion: only three non-overlapping channels and interference from microwaves, Bluetooth, and neighboring networks. Range decreases as you move to 5 and 6 GHz.",
    },
    {
        "type": "mc",
        "q": "Which statement about the 6 GHz band is TRUE?",
        "choices": [
            "Legacy 802.11n clients can join after a firmware update",
            "It is available only to Wi-Fi 6E and newer devices and requires WPA3",
            "It offers only three non-overlapping channels",
            "It penetrates walls better than 2.4 GHz",
        ],
        "answer": 1,
        "explain": "The 6 GHz band was opened with Wi-Fi 6E (802.11ax extended): no legacy 802.11a/b/g/n/ac devices are permitted, WPA3 is mandatory, and the US allocation provides 59 clean 20 MHz channels. Being the highest frequency, it has the shortest range of the three bands.",
    },
    {
        "type": "mc",
        "q": "An office's 2.4 GHz band is saturated while 5 GHz sits mostly idle, even though most laptops are dual-band. Which AP feature addresses this?",
        "choices": ["Band steering", "DFS", "Captive portal", "PortFast"],
        "answer": 0,
        "explain": "Band steering detects dual-band-capable clients and encourages them onto 5/6 GHz - typically by delaying or withholding 2.4 GHz probe responses. Capable clients get the faster, cleaner band while 2.4 GHz is left for legacy and IoT devices that have no alternative.",
    },
    {
        "type": "match",
        "q": "Match each frequency band to its key characteristic.",
        "pairs": [
            ["2.4 GHz", "Longest range; only channels 1/6/11 non-overlapping"],
            ["5 GHz", "Many clean channels; DFS radar detection on some"],
            ["6 GHz", "Wi-Fi 6E only; no legacy devices; WPA3 required"],
            ["Band steering", "Pushes capable clients off 2.4 GHz"],
        ],
        "explain": "Each band trades range for capacity: 2.4 GHz reaches farthest but is congested, 5 GHz balances capacity and reach with DFS obligations, and 6 GHz offers the most clean spectrum to modern clients only. Band steering distributes clients sensibly across bands.",
    },
    # --- SSID / BSSID / ESSID ---
    {
        "type": "mc",
        "q": "What exactly is a BSSID?",
        "choices": [
            "The network name users see when connecting",
            "The MAC address of an access point's radio for a service set",
            "A group of APs sharing the same network name",
            "The controller's management IP address",
        ],
        "answer": 1,
        "explain": "The BSSID uniquely identifies one basic service set and is the MAC address of the AP radio serving it. One physical AP broadcasting several SSIDs across two bands presents a separate BSSID for each combination - which is how analyzers tell individual radios apart.",
    },
    {
        "type": "mc",
        "q": "A campus deploys 40 APs all broadcasting 'CorpWiFi' on the same wired network so laptops roam seamlessly between buildings. What describes this design?",
        "choices": [
            "An independent basic service set (IBSS)",
            "An extended service set using a shared ESSID",
            "40 separate ad hoc networks",
            "A point-to-point bridge network",
        ],
        "answer": 1,
        "explain": "Multiple APs sharing the same SSID on a common distribution system form an extended service set (ESS); the shared name is the ESSID. Clients roam between APs (each with its own BSSID) without reconfiguring. IBSS/ad hoc means no APs at all.",
    },
    {
        "type": "fill",
        "q": "The identifier for a single AP radio's service set - actually its MAC address - is the ______. (type your answer)",
        "answers": ["bssid", "basic service set identifier"],
        "explain": "SSID is the human-readable name, ESSID is that name spanning multiple APs, and the BSSID is the Layer 2 identifier (the radio's MAC) of one specific basic service set. Troubleshooters use BSSIDs to determine exactly which AP a client is associated with.",
    },
    {
        "type": "tf",
        "q": "True or False: Hiding (not broadcasting) the SSID is an effective security control that prevents attackers from finding the network.",
        "answer": False,
        "explain": "A hidden SSID is only removed from beacons - it still appears in probe and association frames, which any wireless analyzer captures in seconds. Treat SSID hiding as cosmetic; real security comes from WPA2/WPA3 encryption and strong authentication.",
    },
    # --- Network types ---
    {
        "type": "mc",
        "q": "Two office buildings 500 meters apart with clear line of sight need to be linked without trenching fiber. Which wireless network type fits best?",
        "choices": [
            "Ad hoc",
            "Infrastructure with omnidirectional APs",
            "Point-to-point bridge with directional antennas",
            "A guest network",
        ],
        "answer": 2,
        "explain": "A point-to-point wireless bridge uses a pair of high-gain directional antennas (parabolic or Yagi) aimed at each other to create a dedicated building-to-building link. Line of sight and careful aiming are required; omnidirectional coverage would waste the signal in all directions.",
    },
    {
        "type": "mc",
        "q": "Which wireless network type has devices communicating directly with each other with no access point involved?",
        "choices": ["Infrastructure", "Ad hoc (IBSS)", "Extended service set", "Lightweight"],
        "answer": 1,
        "explain": "Ad hoc mode - formally an Independent Basic Service Set (IBSS) - is peer-to-peer: stations connect directly, with no AP and no connection to a wired LAN. It suits quick device-to-device sharing but doesn't scale and lacks central security.",
    },
    {
        "type": "mc",
        "q": "A warehouse cannot run Ethernet to most AP locations. Which design lets APs relay traffic wirelessly to the few wired ones and route around a failed node?",
        "choices": ["Mesh network", "Ad hoc network", "Point-to-point links", "A single high-power AP"],
        "answer": 0,
        "explain": "In a mesh, APs interconnect over wireless backhaul, relaying traffic hop-by-hop toward wired root nodes, and the mesh self-heals by re-routing around failures. The trade-off is backhaul capacity consumed by relaying, but it eliminates cabling to every AP.",
    },
    {
        "type": "match",
        "q": "Match each wireless network type to its description.",
        "pairs": [
            ["Infrastructure", "Clients associate to an AP bridged to the wired LAN"],
            ["Ad hoc (IBSS)", "Peer-to-peer devices with no AP"],
            ["Point to point", "Directional bridge link between two sites"],
            ["Mesh", "APs wirelessly relay for each other and self-heal"],
        ],
        "explain": "Infrastructure is the normal AP-centered model. Ad hoc removes the AP entirely. Point-to-point dedicates two directional antennas to one link, typically between buildings. Mesh uses wireless backhaul between APs so only some nodes need cable.",
    },
    # --- Encryption WPA2/WPA3 ---
    {
        "type": "mc",
        "q": "Which encryption protocol does WPA2 use?",
        "choices": ["RC4 with TKIP", "AES-CCMP", "DES-CBC", "SAE"],
        "answer": 1,
        "explain": "WPA2 (802.11i) made AES-CCMP the standard, replacing WPA's interim TKIP/RC4. Note that SAE is not an encryption cipher - it is WPA3's key-exchange/authentication handshake; WPA3 still encrypts with AES (CCMP/GCMP).",
    },
    {
        "type": "mc",
        "q": "What key WPA2-Personal weakness does WPA3's SAE handshake eliminate?",
        "choices": [
            "Weak RC4 keystreams",
            "Offline dictionary attacks against a captured 4-way handshake",
            "Lack of support for AES hardware",
            "SSID broadcasting",
        ],
        "answer": 1,
        "explain": "With WPA2-PSK, an attacker who captures the 4-way handshake can brute-force the passphrase offline at leisure. SAE (a password-authenticated key exchange) requires a live exchange with the AP for every guess and provides forward secrecy, making offline cracking infeasible.",
    },
    {
        "type": "mc",
        "q": "Which WPA3 feature stops attackers from forging deauthentication frames to knock clients off the network?",
        "choices": [
            "Protected Management Frames (802.11w), mandatory in WPA3",
            "Captive portals",
            "Band steering",
            "The 12-bit VLAN tag",
        ],
        "answer": 0,
        "explain": "WPA2 left management frames unauthenticated, so anyone could spoof deauth/disassociation frames - the basis of deauth floods and evil-twin setups. WPA3 makes Protected Management Frames (802.11w) mandatory, cryptographically protecting those frames.",
    },
    {
        "type": "fill",
        "q": "WPA3-Personal replaces the pre-shared key 4-way handshake with ______, the Simultaneous Authentication of Equals. (type your answer)",
        "answers": ["sae", "simultaneous authentication of equals"],
        "explain": "SAE is a password-authenticated key exchange (the 'dragonfly' handshake). Each authentication produces fresh keys with forward secrecy, and password guesses can't be tested offline against captured traffic - the core security upgrade of WPA3-Personal.",
    },
    {
        "type": "tf",
        "q": "True or False: WPA3 provides forward secrecy, meaning a passphrase cracked in the future cannot decrypt previously captured traffic.",
        "answer": True,
        "explain": "SAE negotiates unique session keys that are not derived solely from the passphrase, so past captures stay safe even if the password later leaks. Under WPA2-PSK, by contrast, knowing the passphrase (plus the captured handshake) lets an attacker decrypt recorded sessions.",
    },
    # --- Guest networks / captive portal ---
    {
        "type": "mc",
        "q": "A hotel Wi-Fi lets guests associate, but every web request redirects to a page requiring a room number and acceptance of terms before internet access works. What is this?",
        "choices": ["A RADIUS challenge", "An evil twin", "A captive portal", "Band steering"],
        "answer": 2,
        "explain": "A captive portal intercepts the client's initial traffic and redirects it to a login/AUP page; only after acceptance or authentication is traffic released. It provides authorization and accountability for guests - though not encryption by itself.",
    },
    {
        "type": "mc",
        "q": "What is the primary design goal of a guest wireless network?",
        "choices": [
            "Giving visitors internet access while isolating them from internal resources",
            "Extending the corporate SSID's range",
            "Providing higher bandwidth than the corporate SSID",
            "Eliminating the need for encryption on the corporate network",
        ],
        "answer": 0,
        "explain": "A guest SSID maps to an isolated VLAN/subnet with firewall rules allowing internet only, often with client isolation between guests. It is a segmentation control: visitors get connectivity without any path to internal servers or user devices.",
    },
    # --- Authentication PSK vs Enterprise ---
    {
        "type": "mc",
        "q": "A company wants each employee to authenticate to Wi-Fi with individual Active Directory credentials, verified by a central server. What should be deployed?",
        "choices": [
            "WPA2-Personal with a long passphrase",
            "WPA2/WPA3-Enterprise using 802.1X and a RADIUS server",
            "MAC filtering",
            "A captive portal on an open SSID",
        ],
        "answer": 1,
        "explain": "Enterprise mode uses 802.1X: the client (supplicant) authenticates through the AP (authenticator) to a RADIUS authentication server via EAP, giving per-user credentials, unique session keys, and centralized logging. PSK gives everyone the same passphrase and no individual accountability.",
    },
    {
        "type": "mc",
        "q": "An employee leaves the company. With WPA2-Personal, what must be done to fully revoke their Wi-Fi access, and what is the Enterprise-mode alternative?",
        "choices": [
            "Nothing; access expires automatically. Enterprise requires reimaging devices",
            "Change the shared passphrase on the AP and every device; with Enterprise, simply disable their user account",
            "Block their MAC address; Enterprise requires changing the SSID",
            "Rotate the WPA2 group key only; Enterprise cannot revoke users",
        ],
        "answer": 1,
        "explain": "With a pre-shared key, the departing employee knows the same secret as everyone else, so the passphrase must be changed and re-entered on every device. Enterprise/802.1X ties access to individual accounts, so revocation is one disabled account in the directory - a key operational advantage.",
    },
    {
        "type": "tf",
        "q": "True or False: In WPA2-Enterprise, the RADIUS server takes the role of authentication server while the access point acts as the authenticator.",
        "answer": True,
        "explain": "802.1X defines three roles: the supplicant (client), the authenticator (the AP or switch, which relays and enforces), and the authentication server (RADIUS), which validates credentials via EAP methods like PEAP or EAP-TLS.",
    },
    # --- Antennas ---
    {
        "type": "mc",
        "q": "Which antenna type is best for an AP mounted in the center of an open office ceiling to serve clients in all directions?",
        "choices": ["Parabolic dish", "Yagi", "Omnidirectional", "Patch"],
        "answer": 2,
        "explain": "An omnidirectional antenna radiates a 360-degree doughnut-shaped pattern around its axis - ideal when clients surround the AP. Directional antennas (Yagi, patch, parabolic) trade that all-around coverage for focused gain in one direction.",
    },
    {
        "type": "mc",
        "q": "For a long-distance point-to-point link between two buildings several kilometers apart, which antenna provides the highest gain and narrowest beam?",
        "choices": ["Omnidirectional dipole", "Parabolic dish", "Patch panel antenna", "Internal laptop antenna"],
        "answer": 1,
        "explain": "Parabolic (dish/grid) antennas concentrate energy into a very narrow, very high-gain beam, making them the choice for long point-to-point bridges - at the cost of requiring precise aiming and clear line of sight. Yagis suit medium distances; patch antennas cover sectors.",
    },
    {
        "type": "mc",
        "q": "What does increasing antenna gain actually do?",
        "choices": [
            "Adds transmit power to the radio",
            "Focuses the existing radiated energy into a narrower beam, extending reach in that direction",
            "Increases the channel width",
            "Converts the antenna to a different band",
        ],
        "answer": 1,
        "explain": "Gain (in dBi) doesn't create power - it reshapes the radiation pattern, concentrating the same energy into a narrower beamwidth. Higher gain means longer reach in the favored direction and weaker coverage everywhere else.",
    },
    # --- Autonomous vs lightweight ---
    {
        "type": "mc",
        "q": "What distinguishes a lightweight AP from an autonomous AP?",
        "choices": [
            "A lightweight AP is centrally managed by a wireless LAN controller instead of being configured individually",
            "A lightweight AP weighs less and mounts on drywall",
            "A lightweight AP supports only 2.4 GHz",
            "An autonomous AP cannot encrypt traffic",
        ],
        "answer": 0,
        "explain": "Autonomous ('fat') APs hold their whole configuration and are managed one at a time. Lightweight ('thin') APs download config from a WLC, which centrally coordinates SSIDs, channels, power, roaming, and rogue detection - essential at scale.",
    },
    {
        "type": "mc",
        "q": "Which protocol tunnels control and data traffic between a lightweight AP and its wireless LAN controller?",
        "choices": ["RADIUS", "CAPWAP", "LLDP", "SNMP"],
        "answer": 1,
        "explain": "CAPWAP (Control And Provisioning of Wireless Access Points, successor to LWAPP) builds tunnels between lightweight APs and the WLC - control traffic on UDP 5246 and data on UDP 5247. The AP handles real-time radio functions while the controller makes management decisions (split MAC).",
    },
    {
        "type": "fill",
        "q": "The protocol that tunnels lightweight AP control and data traffic to a wireless LAN controller is ______. (type your answer)",
        "answers": ["capwap"],
        "explain": "CAPWAP (Control And Provisioning of Wireless Access Points) is the standard tunneling protocol between thin APs and their controller, using UDP 5246 for control and UDP 5247 for data. It replaced the older LWAPP.",
    },
    {
        "type": "fill",
        "q": "The IEEE amendment that added DFS and TPC for 5 GHz radar coexistence is 802.11__. (type the letter)",
        "answers": ["h", "802.11h", "11h"],
        "explain": "802.11h defines Dynamic Frequency Selection (vacate a channel when radar is detected) and Transmit Power Control (limit power to the minimum needed). Keep it distinct from 802.11i (WPA2 security) and 802.11w (protected management frames).",
    },
    {
        "type": "mc",
        "q": "A coffee shop with a single AP and no controller budget, versus a hospital with 600 APs. Which AP architecture suits each?",
        "choices": [
            "Autonomous for both",
            "Lightweight for both",
            "Autonomous for the coffee shop; controller-based lightweight APs for the hospital",
            "Lightweight for the coffee shop; autonomous for the hospital",
        ],
        "answer": 2,
        "explain": "One standalone AP is trivial to manage autonomously. At hundreds of APs, per-device management is impossible - a WLC (or cloud controller) provides zero-touch provisioning, coordinated RF, and seamless roaming, which is why large deployments use lightweight APs.",
    },
    {
        "type": "order",
        "q": "Arrange the Wi-Fi channel widths from narrowest (most non-overlapping channels available) to widest (highest throughput).",
        "items": ["20 MHz", "40 MHz", "80 MHz", "160 MHz"],
        "explain": "Channel bonding doubles width at each step: 20, 40, 80, 160 MHz. Each doubling roughly doubles throughput but halves the number of non-overlapping channels and increases interference exposure - which is why 2.4 GHz stays at 20 MHz and 160 MHz is practical mainly in 6 GHz.",
    },
    {
        "type": "order",
        "q": "Arrange the frequency bands and their signals from longest range/best wall penetration to shortest, ending with the antenna that reaches farthest of all.",
        "items": [
            "2.4 GHz with omnidirectional antenna",
            "5 GHz with omnidirectional antenna",
            "6 GHz with omnidirectional antenna",
            "Any band with a parabolic point-to-point antenna (focused beam reaches farthest)",
        ],
        "explain": "Range decreases as frequency increases - lower-frequency signals propagate farther and penetrate obstacles better, so 2.4 GHz beats 5 GHz, which beats 6 GHz. A high-gain directional antenna changes the equation entirely by focusing energy into a narrow beam for kilometers of reach.",
    },
]
