TOPIC = {
    "id": "2.4",
    "domain": 2,
    "title": "Explain important factors of physical installations",
    "short": "Physical Installations",
}

TERMS = [
    ("MDF (Main Distribution Frame)", "The building's primary wiring/equipment room holding the demarc and core network gear; all IDFs uplink to it"),
    ("IDF (Intermediate Distribution Frame)", "A secondary, per-floor wiring closet with access switches and patch panels, connected back to the MDF"),
    ("Demarcation point (demarc)", "Where the carrier's responsibility ends and the customer's begins; the ISP circuit terminates here, typically in the MDF"),
    ("Rack unit (U)", "Standard measure of vertical rack space: 1U = 1.75 inches; equipment is sized as 1U, 2U, 4U, etc."),
    ("19-inch rack", "The standard equipment rack width (between mounting rails); a common full-height rack is 42U"),
    ("Hot aisle / cold aisle", "Data center layout where rack fronts face cold supply air aisles and rears exhaust into hot return aisles, keeping air streams separate"),
    ("Port-side exhaust/intake", "Selectable switch airflow direction relative to its port face, chosen so the device's airflow matches the hot/cold aisle design"),
    ("Patch panel", "Termination point for horizontal cabling: punch-down (110 block) connections in the rear, numbered RJ45 jacks in front for patching to switches"),
    ("110 block", "Modern insulation-displacement punch-down block used on patch panels and for voice/data cross-connects"),
    ("Fiber distribution panel", "Enclosure where fiber strands are spliced/terminated and presented on couplers, protecting the fibers and their bend radius"),
    ("Bend radius", "The minimum curve a cable (especially fiber) tolerates; bending tighter causes signal loss or breakage"),
    ("Lockable rack/cabinet", "Enclosed rack with locking doors/panels providing physical security for equipment, even inside shared rooms"),
    ("UPS (Uninterruptible Power Supply)", "Battery-backed power source that rides through outages and sags long enough for graceful shutdown or generator start"),
    ("Standby (offline) UPS", "Cheapest UPS type: equipment runs on utility power and switches to battery/inverter only when power fails (brief transfer gap)"),
    ("Line-interactive UPS", "UPS with an autotransformer (AVR) that corrects sags/brownouts and surges without using the battery; small transfer time on outages"),
    ("Online (double-conversion) UPS", "UPS that permanently converts AC to DC to AC, so the load always runs from the inverter - zero transfer time and cleanest power"),
    ("PDU (Power Distribution Unit)", "Rack-mounted device distributing power to equipment; types include basic, metered, monitored, and switched"),
    ("Switched PDU", "PDU allowing remote on/off control of individual outlets - e.g., remotely power-cycling a hung device"),
    ("Metered PDU", "PDU that displays/reports its current draw so administrators avoid overloading the circuit"),
    ("Power load", "Total draw of connected equipment, planned in watts and volt-amperes; keep below circuit/UPS ratings (about 80% max)"),
    ("Volt-ampere (VA)", "Apparent power rating; watts = VA x power factor, and a UPS must not be exceeded on either its VA or watt rating"),
    ("Voltage matching", "Ensuring equipment matches the supply (120V standard NA circuits vs 208/240V data center feeds); higher voltage means less current per watt"),
    ("Humidity range (40-60%)", "Recommended relative humidity: too low invites electrostatic discharge, too high causes condensation and corrosion"),
    ("ESD (electrostatic discharge)", "Static electricity discharge that destroys electronic components; a risk when humidity is too low"),
    ("ASHRAE temperature envelope", "Recommended equipment inlet air of roughly 18-27 C (64-81 F), measured at the rack intake"),
    ("Clean agent fire suppression", "Gaseous systems (FM-200/HFC-227ea, Novec 1230, inert gas) that extinguish fires without water or residue - preferred for data centers"),
    ("Pre-action sprinkler", "Water system requiring two triggers - smoke detection to fill the pipes plus a fused head - minimizing accidental discharge risk"),
    ("CRAC unit", "Computer Room Air Conditioner - dedicated 24/7 cooling for data centers and telecom rooms"),
]

QUESTIONS = [
    # --- MDF / IDF ---
    {
        "type": "mc",
        "q": "In a multi-floor building, where does the ISP circuit terminate and where are the core routers and switches located?",
        "choices": ["In each IDF", "In the MDF", "In the elevator machine room", "In every rack's PDU"],
        "answer": 1,
        "explain": "The Main Distribution Frame is the building's primary equipment room: it houses the demarcation point where carrier services hand off, plus core routing/switching. Floor-level IDFs hold access switches and uplink back to the MDF.",
    },
    {
        "type": "mc",
        "q": "Why does a large office floor need an IDF instead of cabling every desk directly to the basement MDF?",
        "choices": [
            "Fire codes prohibit vertical cable runs",
            "Twisted-pair horizontal runs are limited to 100 meters, so distribution must be close to the users",
            "The MDF can only hold one switch",
            "IDFs provide better internet speeds",
        ],
        "answer": 1,
        "explain": "Copper twisted-pair channels max out at 100 meters, so a wiring closet (IDF) is placed per floor or area to keep every jack within reach. Each IDF's access switches then uplink to the MDF over backbone cabling, usually fiber, which supports much longer runs.",
    },
    {
        "type": "mc",
        "q": "Which best describes the relationship between the MDF and IDFs?",
        "choices": [
            "IDFs connect to each other in a ring, bypassing the MDF",
            "The MDF is optional if IDFs exist",
            "Each IDF uplinks to the MDF, typically over fiber backbone cabling",
            "The MDF is placed on the top floor and IDFs in the basement by standard",
        ],
        "answer": 2,
        "explain": "The physical plant forms a star/tree: the MDF at the center (carrier handoff plus core gear) with each IDF connected back to it via vertical/backbone cabling - usually fiber for distance and bandwidth. Users connect to their nearest IDF's access switches.",
    },
    {
        "type": "fill",
        "q": "The per-floor wiring closet that holds access switches and patch panels is called the ______ (three-letter acronym). (type your answer)",
        "answers": ["idf", "intermediate distribution frame"],
        "explain": "The Intermediate Distribution Frame is the floor-level distribution point between users' wall jacks and the building's Main Distribution Frame. IDF placement is driven by the 100-meter horizontal cabling limit.",
    },
    # --- Rack size ---
    {
        "type": "mc",
        "q": "How tall is one rack unit (1U)?",
        "choices": ["1 inch", "1.75 inches", "2.5 inches", "19 inches"],
        "answer": 1,
        "explain": "A rack unit is 1.75 inches of vertical space; a 2U appliance occupies 3.5 inches. The 19-inch figure is the standard rack width between mounting rails, not a height.",
    },
    {
        "type": "mc",
        "q": "What is the standard width of an equipment rack, and what is a common full-height size?",
        "choices": [
            "23 inches wide, 100U tall",
            "19 inches wide, 42U tall",
            "24 inches wide, 24U tall",
            "17 inches wide, 48U tall",
        ],
        "answer": 1,
        "explain": "Equipment racks are standardized at 19 inches between mounting rails (23-inch racks exist in telco but 19 is the norm), and the common full-height rack is 42U - about 6.1 feet of usable vertical space. Rack elevation diagrams plan what goes in each U.",
    },
    {
        "type": "tf",
        "q": "True or False: Heavy equipment such as UPS units should be mounted at the bottom of a rack.",
        "answer": True,
        "explain": "Placing heavy gear low keeps the rack's center of gravity down, preventing tipping during installation or seismic events. UPS units and large chassis go at the bottom; lighter switches and patch panels can live higher up.",
    },
    {
        "type": "fill",
        "q": "A 4U server occupies ______ inches of vertical rack space. (type the number)",
        "answers": ["7", "seven", "7 inches"],
        "explain": "Each rack unit is 1.75 inches, so 4U = 4 x 1.75 = 7 inches. Rack unit math shows up on the exam - remember the 1.75-inch constant and multiply.",
    },
    # --- Airflow ---
    {
        "type": "mc",
        "q": "In a hot aisle/cold aisle data center design, how are racks arranged?",
        "choices": [
            "All racks face the same direction so air flows one way through the room",
            "Rack fronts face each other across cold aisles and rears face each other across hot aisles",
            "Racks are arranged in a circle around the CRAC unit",
            "Alternating racks are left empty for airflow",
        ],
        "answer": 1,
        "explain": "Fronts (intakes) face shared cold aisles fed with supply air; rears (exhausts) face shared hot aisles that return air to the CRAC/CRAH units. Containment barriers keep hot and cold air from mixing, dramatically improving cooling efficiency.",
    },
    {
        "type": "mc",
        "q": "A new switch will be mounted with its ports facing the hot aisle so cabling stays in the rear. Which airflow option must you order so the switch breathes correctly?",
        "choices": [
            "Port-side exhaust, so hot air exits with the ports toward the hot aisle",
            "Port-side intake, so the switch draws hot-aisle air",
            "Airflow direction doesn't matter for switches",
            "No fans at all - switches are passively cooled",
        ],
        "answer": 0,
        "explain": "The switch must draw cold-aisle air and exhaust into the hot aisle like everything else in the row. With ports facing the hot aisle, that means port-side exhaust. Network gear commonly offers both fan directions precisely because port orientation varies - a mismatched unit ingests hot air and overheats.",
    },
    {
        "type": "tf",
        "q": "True or False: A switch whose airflow direction opposes the room's hot/cold aisle design can overheat even when the room's cooling is working perfectly.",
        "answer": True,
        "explain": "If a device ingests hot-aisle exhaust air instead of cold supply air, its inlet temperature can far exceed spec regardless of room capacity. Matching each device's intake/exhaust orientation to the aisle layout is part of proper installation planning.",
    },
    # --- Cabling: patch panel / fiber panel ---
    {
        "type": "mc",
        "q": "How is a copper patch panel constructed and used?",
        "choices": [
            "Horizontal cable is punched down on rear 110 blocks; front RJ45 ports patch to switch ports",
            "RJ45 plugs are crimped onto the horizontal cable and plugged directly into switches",
            "Fibers are spliced in rear trays and presented on LC couplers",
            "It amplifies signals to extend runs past 100 meters",
        ],
        "answer": 0,
        "explain": "The solid-core wiring from wall jacks is permanently punched down onto insulation-displacement (110-style) blocks on the panel's rear; the front presents numbered RJ45 jacks connected by short patch cables to switch ports. Moves and changes then never disturb the permanent wiring.",
    },
    {
        "type": "mc",
        "q": "What is the main operational benefit of terminating horizontal cabling on patch panels rather than directly on switches?",
        "choices": [
            "It doubles the usable cable distance",
            "Moves, adds, and changes only require re-patching front-side cables, leaving permanent wiring untouched",
            "It converts copper to fiber automatically",
            "It removes the need for cable labeling",
        ],
        "answer": 1,
        "explain": "The building's in-wall cabling is fragile and expensive to replace, so it's terminated once and never moved. All changes happen with cheap stranded patch cords on the front. Good labeling and documentation of panel ports remain essential.",
    },
    {
        "type": "mc",
        "q": "Besides organizing connections, what physical property of fiber does a fiber distribution panel protect?",
        "choices": ["Its shielding from EMI", "Its bend radius", "Its PoE power budget", "Its native VLAN"],
        "answer": 1,
        "explain": "Fiber bent tighter than its minimum bend radius suffers light loss (or breaks). Distribution panels include slack spools, splice trays, and routing guides that keep strands protected and gently curved while presenting LC/SC/MPO couplers for patching.",
    },
    {
        "type": "fill",
        "q": "Copper cable is attached to the rear of a patch panel using a punch-down tool onto ______ blocks. (type your answer)",
        "answers": ["110", "110 block"],
        "explain": "Modern structured cabling punches horizontal runs onto 110-style insulation-displacement blocks (the older 66 block served legacy voice). The punch-down tool seats each conductor and trims the excess in one motion.",
    },
    # --- Lockable ---
    {
        "type": "mc",
        "q": "A colocation customer shares a data hall with other tenants. Which measure protects their equipment from physical tampering?",
        "choices": [
            "Enabling WPA3 on the switches",
            "A lockable enclosed cabinet with locking front/rear doors and side panels",
            "Configuring longer passwords",
            "Placing the gear in the top 10U of an open rack",
        ],
        "answer": 1,
        "explain": "Physical access defeats most logical controls - console ports allow password recovery, and cables can be tapped or pulled. Lockable cabinets (and locked, access-controlled MDF/IDF rooms) are the baseline physical security for network installations.",
    },
    {
        "type": "tf",
        "q": "True or False: If a switch has strong passwords and SSH-only management, locking the rack it sits in provides no additional security benefit.",
        "answer": False,
        "explain": "With physical access, an attacker can use the console port and password-recovery procedures, insert rogue devices, tap or unplug cables, or simply steal hardware. Physical security (locked rooms, lockable racks) underpins every logical control.",
    },
    # --- UPS ---
    {
        "type": "mc",
        "q": "Which UPS type keeps the load permanently powered from its inverter, providing zero transfer time when utility power fails?",
        "choices": ["Standby (offline)", "Line-interactive", "Online (double-conversion)", "Metered"],
        "answer": 2,
        "explain": "An online/double-conversion UPS always converts incoming AC to DC (charging the battery) and back to clean AC through the inverter, so an outage causes no switchover at all and output power is fully conditioned. It is the most expensive type and standard for critical loads.",
    },
    {
        "type": "mc",
        "q": "A branch office suffers frequent brownouts (voltage sags). Which UPS type corrects these using an autotransformer without draining its battery?",
        "choices": ["Standby", "Line-interactive", "Basic PDU", "Generator"],
        "answer": 1,
        "explain": "Line-interactive UPSes include automatic voltage regulation (AVR) - a boost/buck autotransformer that corrects sags and swells while passing utility power through, reserving the battery for real outages. Standby units would repeatedly switch to battery, wearing it out.",
    },
    {
        "type": "mc",
        "q": "What is the realistic role of UPS battery runtime in a server room design?",
        "choices": [
            "Running all equipment for days during extended outages",
            "Providing minutes of power for graceful shutdown or to bridge until a generator starts",
            "Replacing the need for redundant power supplies",
            "Powering only the lighting",
        ],
        "answer": 1,
        "explain": "UPS batteries are sized in minutes, not hours: enough to shut servers down cleanly or carry the load through generator start-up. Long outages are the generator's job - and remember runtime shrinks sharply as load increases.",
    },
    {
        "type": "mc",
        "q": "Which UPS type provides the LEAST protection, simply switching to battery after a brief gap when power fails?",
        "choices": ["Online double-conversion", "Line-interactive", "Standby (offline)", "Delta-conversion"],
        "answer": 2,
        "explain": "A standby/offline UPS passes raw utility power through until it fails, then transfers to the inverter with a few milliseconds' gap. It is the cheapest option, fine for desktops but not for critical or brownout-prone environments.",
    },
    {
        "type": "match",
        "q": "Match each UPS type to its key characteristic.",
        "pairs": [
            ["Standby (offline)", "Switches to battery only when power fails; brief gap"],
            ["Line-interactive", "AVR autotransformer corrects brownouts without battery"],
            ["Online (double-conversion)", "Load always runs from the inverter; zero transfer time"],
            ["Generator", "Long-duration power source the UPS bridges to"],
        ],
        "explain": "The three UPS designs escalate in cost and protection: standby switches over on failure, line-interactive adds voltage regulation for sags/swells, and online double-conversion continuously rebuilds the AC waveform for zero-transfer, fully conditioned output.",
    },
    {
        "type": "order",
        "q": "Arrange the sequence of events for a well-designed data center power outage response.",
        "items": [
            "Utility power fails",
            "UPS batteries instantly carry the load",
            "Generator starts and stabilizes",
            "Load transfers from UPS to generator power",
            "Utility returns and the load transfers back",
        ],
        "explain": "The UPS exists to bridge the gap: it carries the load from the instant of failure until the generator (which needs seconds to minutes to start and stabilize) can take over. When utility power returns, the transfer switch moves the load back and the UPS recharges.",
    },
    # --- PDU ---
    {
        "type": "mc",
        "q": "The NOC needs to remotely power-cycle a hung router in a rack 300 miles away. Which PDU type makes this possible?",
        "choices": ["Basic PDU", "Metered PDU", "Switched PDU", "Any PDU with surge protection"],
        "answer": 2,
        "explain": "A switched PDU offers network-controlled on/off for individual outlets, enabling remote reboots, staggered start-up, and locking off unused outlets. Metered/monitored PDUs only measure and report power draw; basic PDUs are just outlet strips.",
    },
    {
        "type": "mc",
        "q": "What does a metered PDU add over a basic PDU?",
        "choices": [
            "Remote outlet switching",
            "A display/reporting of current draw so the circuit isn't overloaded",
            "Battery backup",
            "Voltage conversion from 120V to 240V",
        ],
        "answer": 1,
        "explain": "A metered PDU shows (locally, and often over the network) how many amps the rack is pulling, letting staff verify headroom before adding equipment. It distributes the same power as a basic PDU - the difference is visibility, not control.",
    },
    {
        "type": "tf",
        "q": "True or False: For power redundancy, a rack is typically fed by two PDUs on independent circuits, with dual-supply equipment connected to both.",
        "answer": True,
        "explain": "A/B power feeds put each of a device's two power supplies on a different PDU and upstream circuit (ideally different UPSes). Losing one feed, breaker, or PDU then causes no outage - a standard high-availability practice.",
    },
    # --- Power load / voltage ---
    {
        "type": "mc",
        "q": "A UPS is rated 1500 VA / 900 W. Which statement about loading it is correct?",
        "choices": [
            "You may load it to 1500 W since VA and watts are interchangeable",
            "The connected load must stay within BOTH the VA and the watt rating",
            "Only the VA rating matters for IT equipment",
            "The watt rating only applies while on battery",
        ],
        "answer": 1,
        "explain": "Watts (real power) = VA (apparent power) x power factor, so both ratings are hard limits: exceed either and the UPS overloads. Sizing practice also keeps sustained load to roughly 80% of rating for headroom and better battery runtime.",
    },
    {
        "type": "mc",
        "q": "Why do data centers commonly distribute power at 208V or 240V instead of 120V?",
        "choices": [
            "Higher voltage draws less current for the same wattage, reducing conductor size and heat",
            "120V cannot power servers at all",
            "208V is required for Ethernet switches",
            "Lower voltages are more dangerous",
        ],
        "answer": 0,
        "explain": "Power = voltage x current, so doubling voltage halves the current for the same load - smaller wiring, cooler distribution, higher efficiency. Most IT power supplies auto-range from 100-240V, but connectors and PDUs must match the feed.",
    },
    {
        "type": "mc",
        "q": "An admin keeps adding servers to one 20 A rack circuit until the breaker trips, downing the whole rack. What planning rule was violated?",
        "choices": [
            "Servers must be on separate VLANs",
            "Total power load must be calculated and kept below circuit capacity (about 80% for continuous loads)",
            "Racks may only hold four servers",
            "Breakers should be upgraded without changing wiring",
        ],
        "answer": 1,
        "explain": "Power load planning sums equipment draw (watts/VA) and keeps it under the circuit, PDU, and UPS ratings - with the common 80% continuous-load rule providing headroom. Metered PDUs exist to watch this in real time; a tripped breaker takes down everything on the circuit.",
    },
    {
        "type": "fill",
        "q": "Standard wall outlets in North America supply approximately ______ volts. (type the number)",
        "answers": ["120", "110", "120v"],
        "explain": "Ordinary NA branch circuits run at 120V, while data centers commonly use 208V or 240V feeds (and much of the world uses 230V). Equipment, power cords, and receptacle types must match the supplied voltage.",
    },
    # --- Environmental: humidity ---
    {
        "type": "mc",
        "q": "What is the generally recommended relative humidity range for a server room?",
        "choices": ["0-20%", "20-30%", "40-60%", "80-95%"],
        "answer": 2,
        "explain": "Roughly 40-60% RH balances the two failure modes: below that range, static builds and electrostatic discharge can destroy components; above it, condensation and corrosion attack equipment. Environmental sensors alert on excursions.",
    },
    {
        "type": "mc",
        "q": "A winter humidity reading of 15% in the IDF creates which specific risk?",
        "choices": [
            "Condensation on switch chassis",
            "Electrostatic discharge damaging components",
            "Mold growth in the cabling",
            "Reduced UPS runtime",
        ],
        "answer": 1,
        "explain": "Very dry air lets static charge accumulate on people and surfaces; a discharge of even a few hundred volts - below what a human can feel - can kill sensitive electronics. That is the 'too low' end of the humidity envelope; the 'too high' end brings condensation.",
    },
    {
        "type": "tf",
        "q": "True or False: Humidity that is too HIGH in a data center risks condensation and corrosion on equipment.",
        "answer": True,
        "explain": "Above roughly 60% RH, moisture can condense on cool surfaces and corrode contacts and boards. The recommended envelope of about 40-60% avoids both condensation (high end) and ESD (low end).",
    },
    # --- Environmental: temperature ---
    {
        "type": "mc",
        "q": "ASHRAE's recommended inlet air temperature range for IT equipment is approximately:",
        "choices": ["10-15 C (50-59 F)", "18-27 C (64-81 F)", "30-38 C (86-100 F)", "0-10 C (32-50 F)"],
        "answer": 1,
        "explain": "The ASHRAE recommended envelope for equipment intake air is about 18-27 C (roughly 64-81 F) - measured at the rack intake, not the room thermostat. Heat is the top killer of electronics, so continuous 24/7 cooling and intake-point monitoring are required.",
    },
    {
        "type": "mc",
        "q": "Switches in a 4th-floor IDF keep failing on weekends. The closet shares the office building's HVAC. What is the most likely cause?",
        "choices": [
            "Weekend power surges",
            "Building HVAC shuts down after hours, letting the closet overheat",
            "The native VLAN is mismatched",
            "Humidity is too low on weekends",
        ],
        "answer": 1,
        "explain": "Office comfort HVAC often runs on a schedule, but network equipment produces heat 24/7. A closed closet without dedicated continuous cooling can soar past safe temperatures overnight and on weekends. Telecom rooms need dedicated, always-on cooling and temperature alerting.",
    },
    # --- Fire suppression ---
    {
        "type": "mc",
        "q": "Which fire suppression approach extinguishes a data center fire without damaging running equipment?",
        "choices": [
            "Wet pipe sprinklers",
            "Deluge sprinklers",
            "A clean agent gas system such as FM-200",
            "A garden hose and Class A extinguishers",
        ],
        "answer": 2,
        "explain": "Clean agent systems flood the room with a gas (FM-200/HFC-227ea, Novec 1230, or inert gas blends) that suppresses fire chemically or by heat/oxygen effects, leaving no water or residue - equipment can keep running. Water-based systems protect the building but destroy electronics.",
    },
    {
        "type": "mc",
        "q": "Which sprinkler design requires BOTH smoke detection (to fill the dry pipes with water) AND a fused sprinkler head before water discharges?",
        "choices": ["Wet pipe", "Dry pipe", "Deluge", "Pre-action"],
        "answer": 3,
        "explain": "Pre-action systems keep pipes dry until a detection event charges them, and water still only flows if a head's fusible link melts - two independent triggers. This near-eliminates accidental water discharge, which is why data centers choose pre-action when sprinklers are mandated.",
    },
    {
        "type": "mc",
        "q": "Why do rooms protected by CO2 or inert-gas suppression systems have alarms and discharge delays?",
        "choices": [
            "The gas corrodes equipment if released too fast",
            "The agents displace or reduce oxygen and can be lethal, so people must evacuate first",
            "The alarm recharges the cylinders",
            "Regulations require testing the sirens weekly",
        ],
        "answer": 1,
        "explain": "Oxygen-displacing agents suffocate a fire - and can suffocate people. Pre-discharge alarms, time delays, and abort switches give occupants time to evacuate. Handheld electrical-fire extinguishers for such spaces should be Class C rated.",
    },
    {
        "type": "match",
        "q": "Match each environmental/fire control to its purpose.",
        "pairs": [
            ["40-60% relative humidity", "Prevents both ESD and condensation"],
            ["18-27 C inlet air", "ASHRAE recommended equipment intake range"],
            ["FM-200 clean agent", "Suppresses fire without water or residue"],
            ["Pre-action sprinkler", "Two triggers required before any water flows"],
            ["Hot/cold aisle containment", "Keeps supply and exhaust air streams separate"],
        ],
        "explain": "The environmental trio - humidity, temperature, and fire suppression - protects hardware: humidity in the 40-60% band, intake air within the ASHRAE envelope via contained airflow, and fire handled by clean agents (with pre-action sprinklers as the water backstop).",
    },
    {
        "type": "fill",
        "q": "The clean agent gas historically most associated with data center fire suppression is FM-______. (type the number)",
        "answers": ["200", "fm-200", "fm200"],
        "explain": "FM-200 (chemical name HFC-227ea) is the classic data center clean agent: it extinguishes fires rapidly without water, residue, or equipment damage. Newer alternatives include Novec 1230 and inert gas blends like Inergen.",
    },
    {
        "type": "order",
        "q": "Arrange the path of a user's network connection through the physical plant, from desk to carrier.",
        "items": [
            "Wall jack at the user's desk",
            "Horizontal cable punched down on the IDF patch panel",
            "Patch cable to the IDF access switch",
            "Fiber backbone uplink to the MDF",
            "Core equipment and the carrier demarc in the MDF",
        ],
        "explain": "Structured cabling flows: work-area jack, horizontal run to the floor's IDF patch panel, patch cord to the access switch, then backbone (vertical) fiber down to the MDF where core switching/routing and the carrier's demarcation point live.",
    },
]
