TOPIC = {
    "id": "3.1",
    "domain": 3,
    "title": "Explain the purpose of organizational processes and procedures.",
    "short": "Processes & Procedures",
}

TERMS = [
    ("Physical diagram", "Documentation showing actual devices, cable runs, ports, and locations — where equipment physically is and how it is connected"),
    ("Logical diagram", "Documentation showing subnets, VLANs, IP addressing, and routing relationships — how data flows, independent of physical location"),
    ("Rack diagram", "Elevation drawing of an equipment rack showing each device's position in rack units (1U = 1.75 inches)"),
    ("Cable map", "Documentation tracing each cable run: wall jack to patch panel port to switch port, with labels on both ends"),
    ("Layer 1 diagram", "Network diagram of physical connectivity: cables, cable types, ports, and patch panels"),
    ("Layer 2 diagram", "Network diagram of switching topology: switches, VLANs, trunks, and link aggregation"),
    ("Layer 3 diagram", "Network diagram of routing topology: routers, firewalls, IP subnets, and routing protocols"),
    ("Asset inventory", "Database of owned hardware and software including serial numbers, licensing, and warranty support status"),
    ("IPAM", "IP address management — software that tracks subnet allocation and address assignments, often integrated with DHCP and DNS"),
    ("Service-level agreement", "Contract defining measurable service commitments such as uptime percentage and repair time, with remedies for misses"),
    ("Five nines", "99.999% availability — approximately 5.26 minutes of downtime per year"),
    ("Wireless survey", "Assessment of RF coverage, interference, and AP placement in a facility; its visual output is a heat map"),
    ("Heat map", "Floor plan color-coded by wireless signal strength used to find dead zones and plan AP placement"),
    ("End-of-life (EOL)", "Vendor no longer sells or actively develops the product; limited support may continue for a time"),
    ("End-of-support (EOS)", "Vendor no longer provides any support, patches, or security updates — the product must be replaced or isolated"),
    ("Patch", "Small targeted software update that fixes bugs or security vulnerabilities"),
    ("Firmware", "Low-level software embedded in hardware devices; updating it fixes hardware-level bugs but risks bricking the device"),
    ("Decommissioning", "Formal retirement of an asset: removal from service, record updates, data sanitization, and proper disposal"),
    ("Data sanitization", "Securely erasing all data and configuration from a device before disposal so nothing can be recovered"),
    ("Change management", "Formal process ensuring changes are requested, approved, tested, scheduled, and reversible"),
    ("Rollback plan", "Documented steps, written before a change begins, for restoring the previous working state if the change fails"),
    ("Maintenance window", "Pre-approved low-impact time period during which changes are performed"),
    ("Production configuration", "The configuration currently running on a live device"),
    ("Backup configuration", "Saved copy of a device's configuration stored off the device for restoration after failure or a bad change"),
    ("Golden configuration", "Approved baseline template configuration for a device role, used to deploy new devices and audit for drift"),
]

QUESTIONS = [
    # --- Multiple choice (21) ---
    {
        "type": "mc",
        "q": "A technician needs to determine which subnets and VLANs traffic crosses between two departments. Which document should be consulted?",
        "choices": ["Rack diagram", "Physical diagram", "Logical diagram", "Cable map"],
        "answer": 2,
        "explain": "Logical diagrams show subnets, VLANs, IP addressing, and routing relationships — how data flows through the network. Physical diagrams, rack diagrams, and cable maps document where equipment is and how it is physically cabled, not the logical traffic path.",
    },
    {
        "type": "mc",
        "q": "Which document shows the exact U position of each server and switch installed in an equipment cabinet?",
        "choices": ["Rack diagram", "Logical diagram", "Layer 3 diagram", "Asset inventory"],
        "answer": 0,
        "explain": "A rack diagram (rack elevation) documents the front/rear layout of a rack, with each device's position measured in rack units (1U = 1.75 inches). It is used to plan installations and direct remote-hands work.",
    },
    {
        "type": "mc",
        "q": "A new technician must trace which switch port serves wall jack 2A-07. Which documentation provides this fastest?",
        "choices": ["Layer 3 diagram", "Wireless heat map", "Logical diagram", "Cable map"],
        "answer": 3,
        "explain": "A cable map documents the physical cabling plant: wall jack to patch panel port to switch port. Without it, tracing a run requires a toner probe and significant time. Logical and Layer 3 diagrams show addressing and routing, not physical cable paths.",
    },
    {
        "type": "mc",
        "q": "VLAN assignments and trunk links between switches belong on which network diagram?",
        "choices": ["Layer 1", "Layer 2", "Layer 3", "Physical site plan"],
        "answer": 1,
        "explain": "Layer 2 diagrams show the switching topology: switches, VLANs, trunk and access links, and link aggregation. Layer 1 diagrams show cabling and ports, while Layer 3 diagrams show routers, subnets, and routing.",
    },
    {
        "type": "mc",
        "q": "Routers, firewalls, IP subnets, and routing protocol relationships appear on which diagram type?",
        "choices": ["Layer 1 diagram", "Layer 2 diagram", "Layer 3 diagram", "Rack diagram"],
        "answer": 2,
        "explain": "Layer 3 (network layer) diagrams document routing topology: routers, firewalls, subnets, IP addressing, and routing protocols. Remember the boundary: VLANs live on the Layer 2 diagram, while the subnets mapped to those VLANs live on the Layer 3 diagram.",
    },
    {
        "type": "mc",
        "q": "An audit finds the company is running more copies of an application than it purchased. Better tracking of which asset inventory category would have prevented this?",
        "choices": ["Warranty support", "Hardware", "Licensing", "Firmware"],
        "answer": 2,
        "explain": "License tracking records what was purchased, how many seats are in use, and renewal dates. It prevents both compliance violations (using more than purchased) and waste (paying for unused seats).",
    },
    {
        "type": "mc",
        "q": "A switch fails and the admin needs to know whether the vendor will repair it at no cost. Which asset inventory field answers this?",
        "choices": ["Warranty support status", "Software version", "License count", "IP assignment"],
        "answer": 0,
        "explain": "Warranty support records track coverage terms and expiration dates for each device. They determine whether a failed device is vendor-repaired for free or replaced at the organization's cost, and they drive hardware refresh planning.",
    },
    {
        "type": "mc",
        "q": "Two servers were accidentally deployed with the same static IP, causing an outage. Which tool is designed to prevent this?",
        "choices": ["SIEM", "IPAM", "Heat map", "Rack diagram"],
        "answer": 1,
        "explain": "IP address management (IPAM) tracks every subnet and address assignment, showing which addresses are in use and which are free. Modern IPAM integrates with DHCP and DNS to detect conflicts and forecast subnet exhaustion.",
    },
    {
        "type": "mc",
        "q": "An SLA promises 99.999% uptime. Approximately how much downtime per year does this allow?",
        "choices": ["About 53 minutes", "About 5 minutes", "About 9 hours", "About 3.7 days"],
        "answer": 1,
        "explain": "Five nines (99.999%) allows roughly 5.26 minutes of downtime per year. Four nines allows about 52.6 minutes, three nines about 8.76 hours, and two nines about 3.65 days — a classic exam conversion.",
    },
    {
        "type": "mc",
        "q": "Which document contractually defines a provider's uptime commitment and the penalties for missing it?",
        "choices": ["Baseline configuration", "Asset inventory", "Service-level agreement", "Change request"],
        "answer": 2,
        "explain": "A service-level agreement (SLA) is a contract defining measurable commitments — uptime percentage, response time, repair time — plus remedies such as service credits when the provider misses them.",
    },
    {
        "type": "mc",
        "q": "Users in one corner of the building report weak Wi-Fi. What should the technician produce to visualize coverage and locate dead zones?",
        "choices": ["A logical diagram", "A wireless heat map from a site survey", "A Layer 2 diagram", "An IPAM report"],
        "answer": 1,
        "explain": "A wireless site survey measures RF signal, noise, and interference throughout the facility; its output is a heat map — a floor plan color-coded by signal strength. It is used before deployment for AP planning and afterward to validate coverage and find dead zones.",
    },
    {
        "type": "mc",
        "q": "A vendor announces a switch model will no longer be sold or receive new features, but security patches continue for three more years. Which milestone is this?",
        "choices": ["End-of-support", "Decommissioning", "End-of-life", "Baseline"],
        "answer": 2,
        "explain": "End-of-life (EOL) means the vendor has stopped selling and actively developing the product, though limited support and patches may continue for a defined period. End-of-support (EOS) comes later, when all support and security updates cease.",
    },
    {
        "type": "mc",
        "q": "What is the PRIMARY risk of continuing to run a device that has passed end-of-support (EOS)?",
        "choices": ["Its license fees increase", "New vulnerabilities will never receive security patches", "It cannot be added to a rack diagram", "Its warranty automatically renews"],
        "answer": 1,
        "explain": "After EOS the vendor provides no support or security updates of any kind, so newly discovered vulnerabilities remain exploitable forever. This is why EOS gear must be replaced or isolated, and why auditors flag it.",
    },
    {
        "type": "mc",
        "q": "Which type of update is embedded low-level software in a device and carries the risk of rendering hardware unusable if the update fails?",
        "choices": ["Firmware", "Antivirus signatures", "Browser plug-in", "Driver profile"],
        "answer": 0,
        "explain": "Firmware is low-level software embedded in hardware (switch/router images, BIOS/UEFI, NIC firmware). A failed firmware update can brick the device, so firmware changes demand maintenance windows and rollback plans.",
    },
    {
        "type": "mc",
        "q": "A decommissioned firewall is sold at auction and the buyer finds VPN credentials still in its configuration. Which step was skipped?",
        "choices": ["Change approval", "Asset tagging", "Baseline comparison", "Data sanitization"],
        "answer": 3,
        "explain": "Decommissioning requires securely erasing all data and configuration — wiping drives and clearing configs, credentials, certificates, and SNMP strings — before disposal. Skipping sanitization leaks secrets with the hardware.",
    },
    {
        "type": "mc",
        "q": "A technician wants to upgrade IOS on a core switch tonight because he has free time. According to change management, what must happen FIRST?",
        "choices": ["Take a packet capture", "Submit a change request for approval", "Update the wireless heat map", "Renew the warranty"],
        "answer": 1,
        "explain": "All production changes start with a documented change request that is reviewed and approved before any work begins. The request captures the reason, risk, rollback plan, and proposed maintenance window, creating an auditable record.",
    },
    {
        "type": "mc",
        "q": "During a change window, an upgrade fails validation. Which pre-written artifact tells the team exactly how to restore the previous working state?",
        "choices": ["The rollback plan", "The SLA", "The asset inventory", "The heat map"],
        "answer": 0,
        "explain": "A rollback plan documents the exact steps to return to the prior state and must exist before the change begins. When validation fails, the team executes the rollback rather than improvising at 2 a.m.",
    },
    {
        "type": "mc",
        "q": "Why are disruptive changes scheduled into maintenance windows?",
        "choices": ["To hide changes from the change advisory board", "To avoid updating documentation", "To perform work during pre-approved low-impact times with users notified", "To guarantee the change cannot fail"],
        "answer": 2,
        "explain": "A maintenance window is a pre-approved time period — typically off-hours — when changes may be performed with minimal business impact and with affected users notified in advance. It limits damage if something goes wrong; it does not prevent failure.",
    },
    {
        "type": "mc",
        "q": "At 2 a.m. a previously stable application breaks. What is the FIRST question good change tracking lets the on-call engineer answer?",
        "choices": ["What is the SLA penalty?", "What changed recently?", "Which rack is the server in?", "When does the warranty expire?"],
        "answer": 1,
        "explain": "Most outages follow changes, not spontaneous failures. Request process tracking (service requests / change tickets) creates an auditable history of what changed, when, and by whom — the first place to look when troubleshooting a sudden break.",
    },
    {
        "type": "mc",
        "q": "A router dies at a branch office. Which configuration artifact lets the team bring a replacement unit back to the exact prior state fastest?",
        "choices": ["The production configuration on the dead router", "The golden configuration template", "The most recent backup configuration", "The Layer 1 diagram"],
        "answer": 2,
        "explain": "A backup configuration is a saved copy of that specific device's config stored off the device, taken on schedule and around changes. Restoring it rebuilds the exact prior state. The golden config is only the generic approved template for the role, not that router's specifics.",
    },
    {
        "type": "mc",
        "q": "Security wants to verify that no branch switch deviates from the approved standard settings. Each switch's config should be compared against which artifact?",
        "choices": ["Its own running configuration", "The baseline/golden configuration", "The cable map", "Last year's backup"],
        "answer": 1,
        "explain": "The baseline/golden configuration is the approved standard template for a device role. Periodically diffing each device against it reveals configuration drift and unauthorized changes. Backups capture what a device had, not what it should have.",
    },
    # --- True/False (5) ---
    {
        "type": "tf",
        "q": "In a logical network diagram, two devices drawn adjacent to each other are always physically located near each other.",
        "answer": False,
        "explain": "Logical diagrams show subnets, VLANs, and data flow independent of physical location — logically adjacent devices can be in different buildings. Physical location and cabling belong on physical diagrams.",
    },
    {
        "type": "tf",
        "q": "End-of-support (EOS) occurs after end-of-life (EOL) and means the vendor no longer provides any patches or assistance.",
        "answer": True,
        "explain": "EOL comes first: the product is no longer sold or developed, though support may continue for a while. EOS is the later, harder deadline when all support and security updates stop — making continued use a security risk.",
    },
    {
        "type": "tf",
        "q": "One rack unit (1U) equals 1.75 inches of vertical rack space.",
        "answer": True,
        "explain": "Rack-mounted equipment is measured in rack units, where 1U = 1.75 inches (44.45 mm). Rack diagrams record each device's U position for installation planning and remote-hands work.",
    },
    {
        "type": "tf",
        "q": "A rollback plan should be created only after a change has visibly failed.",
        "answer": False,
        "explain": "The rollback plan must be written and approved as part of the change request, before implementation begins. Waiting until mid-failure to figure out how to undo a change is exactly what change management exists to prevent.",
    },
    {
        "type": "tf",
        "q": "The golden configuration is a snapshot of whatever is currently running on a specific device.",
        "answer": False,
        "explain": "The golden (baseline) configuration is the approved standard template a device of that role SHOULD match — used to deploy new devices and audit for drift. What is currently running is the production configuration, and a saved copy of it is a backup configuration.",
    },
    # --- Fill-in (5) ---
    {
        "type": "fill",
        "q": "99.999% availability is commonly nicknamed 'five ______'. (type your answer)",
        "answers": ["nines", "9s", "nine"],
        "explain": "Availability is counted in nines: 99.999% is 'five nines,' allowing only about 5.26 minutes of downtime per year. Each added nine cuts allowed downtime by a factor of ten.",
    },
    {
        "type": "fill",
        "q": "The software category that tracks IP subnet allocation and address assignments, often integrated with DHCP and DNS, is called ______. (type your answer)",
        "answers": ["IPAM", "IP address management"],
        "explain": "IPAM (IP address management) is the system of record for which subnets exist and which addresses are assigned to what. It prevents duplicate-IP conflicts and forecasts subnet exhaustion, and combined with DHCP/DNS is sometimes called DDI.",
    },
    {
        "type": "fill",
        "q": "The visual output of a wireless site survey — a floor plan color-coded by signal strength — is called a ______ map. (type your answer)",
        "answers": ["heat", "heatmap", "heat map"],
        "explain": "A heat map overlays measured (or predicted) RF signal strength onto a floor plan, revealing dead zones, overlap, and interference. Surveys are done before deployment to plan AP placement and afterward to validate coverage.",
    },
    {
        "type": "fill",
        "q": "The life-cycle milestone at which a vendor stops providing ALL support and security updates is end-of-______. (type your answer)",
        "answers": ["support", "EOS", "service"],
        "explain": "End-of-support (EOS, sometimes end-of-service-life) is when the vendor provides no patches or assistance at all. It follows end-of-life (EOL), which only means the product is no longer sold or actively developed.",
    },
    {
        "type": "fill",
        "q": "The pre-approved low-impact time period during which a change is performed is called a maintenance ______. (type your answer)",
        "answers": ["window"],
        "explain": "A maintenance window is a scheduled, pre-approved period — usually off-hours — for performing changes with minimal business impact. Users are notified in advance, and the window bounds how long the work (including any rollback) may take.",
    },
    # --- Match (2) ---
    {
        "type": "match",
        "q": "Match each network diagram type to what it shows.",
        "pairs": [
            ["Layer 1 diagram", "Cables, cable types, ports, patch panels"],
            ["Layer 2 diagram", "Switches, VLANs, trunk links"],
            ["Layer 3 diagram", "Routers, subnets, routing protocols"],
            ["Rack diagram", "Device positions in rack units"],
            ["Cable map", "Wall jack to patch panel to switch port paths"],
        ],
        "explain": "Diagrams are drawn per OSI layer: Layer 1 = physical connectivity, Layer 2 = switching/VLANs, Layer 3 = routing/subnets. Rack diagrams and cable maps document the physical plant itself. Knowing which artifact answers which question is the core of objective 3.1.",
    },
    {
        "type": "match",
        "q": "Match each configuration or life-cycle artifact to its purpose.",
        "pairs": [
            ["Production configuration", "The settings running on the live device right now"],
            ["Backup configuration", "Saved copy used to restore a device after failure"],
            ["Golden configuration", "Approved template for deploying and auditing devices"],
            ["Rollback plan", "Pre-written steps to undo a failed change"],
        ],
        "explain": "Production = current state, backup = restore copy of a specific device, golden/baseline = the standard a device should match, rollback plan = the escape hatch written before any change. Each answers a different operational question.",
    },
    # --- Order (2) ---
    {
        "type": "order",
        "q": "Arrange the steps of a formal change management process in order.",
        "items": [
            "Submit a change request with risk and impact",
            "Obtain approval from the change board",
            "Write and test the plan including rollback steps",
            "Implement during the maintenance window",
            "Validate success or execute rollback",
            "Update documentation and close the record",
        ],
        "explain": "Changes flow request → approval → planning (with rollback) → scheduled implementation → validation → documentation. Approval always precedes work, the rollback plan exists before implementation, and documentation updates close the loop so diagrams and baselines stay accurate.",
    },
    {
        "type": "order",
        "q": "Arrange the stages of a hardware asset's life cycle in order.",
        "items": [
            "Procurement and addition to asset inventory",
            "Production use with patches and firmware updates",
            "End-of-life announcement (no longer sold)",
            "End-of-support (no more patches)",
            "Decommissioning with data sanitization and disposal",
        ],
        "explain": "Assets are inventoried at purchase, maintained through software management during production, then pass EOL (no longer sold/developed) and later EOS (no support or patches at all), at which point they are decommissioned — sanitized of data and properly disposed of, with inventory records updated.",
    },
]
