TOPIC = {
    "id": "3.2",
    "domain": 3,
    "title": "Given a scenario, use network monitoring technologies.",
    "short": "Network Monitoring",
}

TERMS = [
    ("SNMP", "Simple Network Management Protocol — a manager polls device agents (UDP 161) and receives traps (UDP 162) to monitor and configure devices"),
    ("SNMP manager", "The network management station that polls agents with GET/SET requests and receives traps"),
    ("SNMP agent", "Software on a managed device that answers manager queries and sends unsolicited trap notifications"),
    ("SNMP trap", "Agent-initiated, unsolicited notification sent immediately when an event occurs, to the manager on UDP 162"),
    ("MIB", "Management information base — the hierarchical database of variables an SNMP agent can report"),
    ("OID", "Object identifier — the dotted numeric path addressing one variable in the MIB tree"),
    ("Community string", "Shared plaintext password used by SNMPv1/v2c; defaults are 'public' (read-only) and 'private' (read-write)"),
    ("SNMPv3", "SNMP version adding user-based authentication and encryption; authPriv is the level providing both"),
    ("Flow data", "Metadata about traffic conversations (source/destination, ports, byte counts) exported to a collector — no payloads"),
    ("NetFlow", "Cisco's flow-export technology reporting who talked to whom, when, and how much"),
    ("IPFIX", "IETF standard flow-export protocol derived from NetFlow v9"),
    ("sFlow", "Multi-vendor flow technology that samples 1-in-N packets rather than accounting for every flow"),
    ("Packet capture", "Recording complete packets — headers and full payloads — for deep analysis with tools like Wireshark or tcpdump"),
    ("Baseline", "Documented record of normal network behavior used as the reference for spotting abnormal conditions"),
    ("Anomaly alerting", "Automatic notification when live metrics deviate from baseline or thresholds"),
    ("Syslog", "Standard protocol for sending log messages to a central collector, traditionally over UDP 514, with severity levels 0-7"),
    ("Syslog severity 0", "Emergency — system is unusable; the most severe syslog level"),
    ("Syslog severity 7", "Debug — the least severe syslog level, used for detailed troubleshooting messages"),
    ("SIEM", "Security information and event management — aggregates logs from many sources, correlates events, alerts in real time, and retains data for compliance"),
    ("Log aggregation", "Centralizing logs from many devices so they can be searched, correlated, and retained"),
    ("API integration", "Connecting tools programmatically, typically via REST APIs exchanging JSON over HTTPS, for monitoring and automation"),
    ("Port mirroring", "Switch feature (Cisco SPAN) that copies traffic from source ports or VLANs to an analyzer's port"),
    ("Network discovery", "Scanning to find devices on the network — ad hoc (on demand) or scheduled (recurring automatic)"),
    ("Performance monitoring", "Tracking how well the network works: bandwidth, latency, jitter, loss, CPU/memory"),
    ("Availability monitoring", "Checking whether systems are up — ping and service checks producing uptime percentages"),
    ("Configuration monitoring", "Backing up device configs and diffing them against baselines to detect unauthorized change/drift"),
]

QUESTIONS = [
    # --- Multiple choice (21) ---
    {
        "type": "mc",
        "q": "An SNMP manager polls a switch for interface statistics. Which port does the agent listen on for these queries?",
        "choices": ["UDP 162", "UDP 161", "UDP 514", "TCP 443"],
        "answer": 1,
        "explain": "SNMP agents listen for manager GET/SET queries on UDP 161. UDP 162 is where the manager receives traps, and UDP 514 is syslog. Keep the 161/162 pair straight — it is a guaranteed exam fact.",
    },
    {
        "type": "mc",
        "q": "A router's fan fails and the router immediately sends an unsolicited notification to the monitoring server without being polled. What is this message called?",
        "choices": ["A GetBulk response", "A community string", "An OID walk", "A trap"],
        "answer": 3,
        "explain": "Traps are agent-initiated notifications sent the moment an event occurs, delivered to the manager on UDP 162. Polling, by contrast, is manager-initiated and only sees changes at the next polling interval.",
    },
    {
        "type": "mc",
        "q": "What is the hierarchical database of variables that an SNMP agent can report, in which each variable has a numeric identifier?",
        "choices": ["The MIB, addressed by OIDs", "The SIEM, addressed by indexes", "The baseline, addressed by counters", "The flow cache, addressed by tuples"],
        "answer": 0,
        "explain": "The management information base (MIB) is the tree-structured database of everything an agent exposes; each variable is addressed by an object identifier (OID) — a dotted numeric path like 1.3.6.1.2.1. Managers load MIB files to translate OIDs into readable names.",
    },
    {
        "type": "mc",
        "q": "During a security review, a packet capture shows the string 'public' crossing the network in cleartext alongside monitoring traffic. What is being observed?",
        "choices": ["An SNMPv3 encrypted session", "A syslog facility code", "An SNMPv1/v2c community string", "A NetFlow record"],
        "answer": 2,
        "explain": "SNMPv1 and v2c authenticate with community strings sent in plaintext; 'public' is the notorious read-only default. Anyone sniffing the wire can capture them — and a read-write string allows device reconfiguration. The fix is SNMPv3.",
    },
    {
        "type": "mc",
        "q": "Policy requires monitoring traffic to be both authenticated and encrypted. Which choice satisfies it?",
        "choices": ["SNMPv2c with a long community string", "SNMPv3 with authPriv", "SNMPv1 with an ACL", "SNMPv3 with noAuthNoPriv"],
        "answer": 1,
        "explain": "Only SNMPv3 offers real security, and its authPriv level provides both authentication (HMAC-SHA/MD5) and privacy (AES/DES encryption). v1/v2c send plaintext community strings regardless of length, and noAuthNoPriv provides neither protection.",
    },
    {
        "type": "mc",
        "q": "Which capability did SNMPv2c add over v1?",
        "choices": ["Message encryption", "Bulk retrieval and 64-bit counters", "User-based authentication", "TLS transport"],
        "answer": 1,
        "explain": "v2c added efficiency features — GetBulk retrieval and 64-bit counters for high-speed interfaces — but kept v1's insecure plaintext community-string model. Authentication and encryption arrived only with SNMPv3.",
    },
    {
        "type": "mc",
        "q": "The WAN link saturates every afternoon. Management wants to know which hosts and applications are responsible, without storing packet contents. Which technology fits?",
        "choices": ["Flow data such as NetFlow/IPFIX", "Full packet capture", "Syslog collection", "Port mirroring to a SPAN port"],
        "answer": 0,
        "explain": "Flow technologies export metadata about conversations — source/destination IPs and ports, protocol, byte counts, timestamps — to a collector. That identifies top talkers and applications cheaply. Packet capture would show contents but at enormous storage cost.",
    },
    {
        "type": "mc",
        "q": "What is the key difference between flow data and packet capture?",
        "choices": ["Flow data includes payloads; captures do not", "Flow data is metadata about conversations; captures record full packets including payloads", "Packet capture cannot be filtered", "Flow data only works on wireless networks"],
        "answer": 1,
        "explain": "Flow records summarize who talked to whom, when, on which ports, and how much — but never the data itself. Packet capture records complete packets, headers and payloads, for deep inspection. Flow scales network-wide; capture is targeted and storage-heavy.",
    },
    {
        "type": "mc",
        "q": "Which pair of tools is used to perform and analyze packet captures?",
        "choices": ["PuTTY and Telnet", "NetFlow and IPFIX", "Wireshark and tcpdump", "Nmap and IPAM"],
        "answer": 2,
        "explain": "Wireshark (GUI) and tcpdump (CLI) capture and decode complete packets. NetFlow/IPFIX export flow metadata, not packets. On a switched network the analyzer also needs port mirroring or a tap to see other devices' traffic.",
    },
    {
        "type": "mc",
        "q": "Why should an organization capture baseline metrics during normal operation?",
        "choices": ["Baselines encrypt monitoring traffic", "Abnormal conditions can only be recognized by comparison with documented normal behavior", "Baselines replace the need for alerts", "SNMP requires a baseline to function"],
        "answer": 1,
        "explain": "A baseline records normal utilization, CPU, latency, and error rates. Raw numbers are meaningless without context — 70% CPU may be fine or a crisis. Monitoring compares live metrics against the baseline to detect anomalies and to plan capacity.",
    },
    {
        "type": "mc",
        "q": "Traffic on a server VLAN suddenly spikes at 3 a.m., far above its baseline, and the NOC receives an automatic text message. Which monitoring capability generated it?",
        "choices": ["Anomaly alerting/notification", "Scheduled discovery", "Configuration drift detection", "Zone transfer"],
        "answer": 0,
        "explain": "Anomaly alerting compares live metrics with baselines/thresholds and notifies staff (email, SMS, tickets) when values deviate abnormally. Tuning matters: too many false alarms cause alert fatigue and real alerts get ignored.",
    },
    {
        "type": "mc",
        "q": "Which syslog severity level indicates 'system is unusable'?",
        "choices": ["7", "5", "2", "0"],
        "answer": 3,
        "explain": "Severity 0 is Emergency — the system is unusable. The scale runs 0 Emergency, 1 Alert, 2 Critical, 3 Error, 4 Warning, 5 Notice, 6 Informational, 7 Debug: lower number = more severe.",
    },
    {
        "type": "mc",
        "q": "A device is configured to send syslog messages at severity 4 and below (more severe). Which messages will the collector receive?",
        "choices": ["Only Warning messages", "Emergency through Warning (0-4)", "Notice through Debug (5-7)", "All messages including Debug"],
        "answer": 1,
        "explain": "Logging 'at level 4' sends level 4 (Warning) plus everything more severe: 0 Emergency, 1 Alert, 2 Critical, 3 Error. Informational (6) and Debug (7) are suppressed. Remember lower numbers are worse.",
    },
    {
        "type": "mc",
        "q": "On which port does a syslog collector traditionally listen?",
        "choices": ["UDP 161", "TCP 22", "UDP 514", "UDP 123"],
        "answer": 2,
        "explain": "Traditional syslog uses UDP port 514 (TCP 514 and TLS on 6514 exist for reliable/secure variants). Do not confuse it with SNMP's 161/162 or NTP's 123 — port-matching questions mix exactly these.",
    },
    {
        "type": "mc",
        "q": "Security wants failed VPN logins, firewall denies, and server events from dozens of devices automatically cross-referenced so related events raise a single incident alert. What should be deployed?",
        "choices": ["A syslog collector alone", "A SIEM", "An SNMP trap receiver", "A flow collector"],
        "answer": 1,
        "explain": "A SIEM ingests logs from many sources and adds correlation — linking related events across devices into one detected incident — plus real-time alerting, dashboards, and long-term retention for compliance. A plain syslog collector only centralizes and stores.",
    },
    {
        "type": "mc",
        "q": "Besides correlation and alerting, which SIEM capability directly supports compliance regimes like PCI DSS?",
        "choices": ["Long-term log retention", "Packet payload injection", "DHCP relay", "Port mirroring"],
        "answer": 0,
        "explain": "SIEMs normalize and retain logs for extended periods, satisfying compliance mandates for audit trails and enabling after-the-fact forensic investigation. Retention plus searchability is a core SIEM value beyond real-time detection.",
    },
    {
        "type": "mc",
        "q": "A monitoring platform automatically opens a helpdesk ticket in a separate ITSM system whenever an alert fires, using REST calls with JSON payloads. Which method enables this?",
        "choices": ["Community strings", "SPAN", "API integration", "Syslog forwarding"],
        "answer": 2,
        "explain": "API integration — typically REST over HTTPS exchanging JSON — lets tools interoperate: monitoring can push alerts into ticketing, pull state from controllers and clouds, and trigger automated remediation. It covers systems SNMP cannot and supports configuration as well as monitoring.",
    },
    {
        "type": "mc",
        "q": "An analyst connects a Wireshark laptop to a switch access port but captures only broadcasts and the laptop's own traffic. What must be configured to see another port's traffic?",
        "choices": ["An SNMPv3 user", "Port mirroring (SPAN) on the switch", "A DHCP reservation", "Syslog severity 7"],
        "answer": 1,
        "explain": "Switches forward frames only to their destination ports, so an analyzer sees almost nothing by default. Port mirroring (Cisco SPAN) copies traffic from chosen source ports or VLANs to the analyzer's port. Alternatively a hardware tap can be placed inline.",
    },
    {
        "type": "mc",
        "q": "Which limitation should be considered when mirroring several busy gigabit ports to a single gigabit SPAN port?",
        "choices": ["The mirror port can be oversubscribed and drop copied packets", "SPAN encrypts the copied traffic", "Mirrored traffic loses its IP headers", "SPAN only works on hubs"],
        "answer": 0,
        "explain": "Mirroring aggregates the source ports' traffic into one destination port; if combined traffic exceeds that port's capacity, copies are dropped and the capture is incomplete. Mirroring also adds switch load — reasons some deployments use dedicated taps instead.",
    },
    {
        "type": "mc",
        "q": "A network team runs a discovery scan every night that reconciles found devices against the asset inventory and flags anything new. What is this an example of?",
        "choices": ["Ad hoc discovery", "Scheduled discovery", "Packet capture", "Configuration monitoring"],
        "answer": 1,
        "explain": "Scheduled discovery runs automatically at regular intervals, continuously keeping inventory and topology accurate and catching rogue or undocumented devices. Ad hoc discovery is a one-time, on-demand scan — used during troubleshooting or after a change.",
    },
    {
        "type": "mc",
        "q": "Which monitoring solution answers 'is the service up, and what uptime percentage did we deliver this month?'",
        "choices": ["Traffic analysis", "Configuration monitoring", "Availability monitoring", "Network discovery"],
        "answer": 2,
        "explain": "Availability monitoring performs regular reachability and service checks (ICMP ping, TCP port probes, HTTP checks) and computes uptime percentages used to verify SLA compliance. Performance monitoring measures how well things work while they are up.",
    },
    # --- True/False (5) ---
    {
        "type": "tf",
        "q": "SNMP traps are sent by the agent to the manager on UDP port 162 without waiting to be polled.",
        "answer": True,
        "explain": "Traps are unsolicited, agent-initiated notifications delivered immediately when an event occurs, to the manager's UDP port 162. Polling (manager-initiated GETs to the agent's UDP 161) only observes state at each interval.",
    },
    {
        "type": "tf",
        "q": "In syslog, severity 7 (Debug) is more severe than severity 1 (Alert).",
        "answer": False,
        "explain": "Syslog severity is inverted from intuition: lower numbers are more severe. 0 is Emergency (system unusable) and 7 is Debug (least severe). Alert (1) means immediate action is required; Debug is verbose troubleshooting detail.",
    },
    {
        "type": "tf",
        "q": "NetFlow records include the full payload of every packet in the conversation.",
        "answer": False,
        "explain": "Flow data is metadata only: IPs, ports, protocol, byte/packet counts, timestamps, and interfaces. You can see that hosts exchanged 4 GB on port 443 but not what the data was. Full payloads require packet capture.",
    },
    {
        "type": "tf",
        "q": "sFlow samples one in N packets rather than accounting for every conversation, trading some accuracy for scalability.",
        "answer": True,
        "explain": "sFlow is a sampling technology: the device forwards a statistical sample of packets/counters to the collector. It scales to very high-speed multi-vendor networks but is an estimate, whereas traditional NetFlow accounts for flows more completely.",
    },
    {
        "type": "tf",
        "q": "A syslog collector by itself correlates events from multiple devices and raises security incident alerts.",
        "answer": False,
        "explain": "A syslog collector centralizes and stores logs. Correlation across sources, behavioral analytics, real-time security alerting, and compliance retention are what a SIEM adds on top of aggregation. 'Correlate events from multiple sources' is the SIEM cue phrase.",
    },
    # --- Fill-in (5) ---
    {
        "type": "fill",
        "q": "SNMP agents listen for manager queries on UDP port ______. (type your answer)",
        "answers": ["161"],
        "explain": "Manager-to-agent GET/SET queries go to UDP 161 on the agent; agent-to-manager traps go to UDP 162 on the manager. This port pair appears constantly on the exam.",
    },
    {
        "type": "fill",
        "q": "Traditional syslog messages are sent to the collector over UDP port ______. (type your answer)",
        "answers": ["514"],
        "explain": "Syslog traditionally uses UDP 514 (with TCP 514 and TLS 6514 as reliable/secure variants). Each message carries a facility and a severity from 0 (Emergency) to 7 (Debug).",
    },
    {
        "type": "fill",
        "q": "The numeric dotted identifier that addresses a single variable in the MIB tree is called an ______. (type your answer)",
        "answers": ["OID", "object identifier"],
        "explain": "Every manageable variable lives at a node of the MIB hierarchy identified by an object identifier (OID) such as 1.3.6.1.2.1.2.2.1.10. The manager loads MIB files to translate numeric OIDs into human-readable names.",
    },
    {
        "type": "fill",
        "q": "The syslog severity level 0 is named ______. (type your answer)",
        "answers": ["emergency"],
        "explain": "Level 0, Emergency, means the system is unusable — the most severe condition. The full ladder is 0 Emergency, 1 Alert, 2 Critical, 3 Error, 4 Warning, 5 Notice, 6 Informational, 7 Debug.",
    },
    {
        "type": "fill",
        "q": "Cisco's name for port mirroring, which copies traffic to an analyzer port, is ______. (type your answer)",
        "answers": ["SPAN", "switched port analyzer"],
        "explain": "SPAN (Switched Port Analyzer) is Cisco's implementation of port mirroring: the switch copies frames from source ports or VLANs to a destination port where a capture tool or IDS listens. RSPAN/ERSPAN extend it across switches.",
    },
    # --- Match (2) ---
    {
        "type": "match",
        "q": "Match each monitoring method to the visibility it provides.",
        "pairs": [
            ["SNMP polling", "Device health counters at regular intervals"],
            ["SNMP trap", "Immediate agent-initiated event notification"],
            ["Flow data", "Conversation metadata: who, what, when, how much"],
            ["Packet capture", "Full packet contents including payloads"],
            ["SIEM", "Cross-device log correlation and security alerting"],
        ],
        "explain": "Think of it as a visibility ladder: SNMP gives device counters, flow data gives conversation metadata, and packet capture gives complete contents. Traps add real-time eventing to SNMP, and the SIEM sits atop the logs correlating everything into incidents.",
    },
    {
        "type": "match",
        "q": "Match each monitoring solution to the question it answers.",
        "pairs": [
            ["Network discovery", "What devices exist on the network?"],
            ["Traffic analysis", "Who are the top talkers and what apps dominate?"],
            ["Performance monitoring", "How well is the network performing?"],
            ["Availability monitoring", "Is the service up, and what is our uptime?"],
            ["Configuration monitoring", "Did a device's config change from the standard?"],
        ],
        "explain": "Each 'solution' in objective 3.2 answers a distinct operational question. Discovery inventories devices, traffic analysis profiles usage, performance tracks bandwidth/latency/jitter/loss, availability measures up/down and SLA uptime, and configuration monitoring detects drift from baselines.",
    },
    # --- Order (2) ---
    {
        "type": "order",
        "q": "Arrange the syslog severity levels from MOST severe to LEAST severe.",
        "items": [
            "Emergency (0)",
            "Alert (1)",
            "Critical (2)",
            "Error (3)",
            "Warning (4)",
            "Notice (5)",
            "Debug (7)",
        ],
        "explain": "Syslog severity runs 0 Emergency, 1 Alert, 2 Critical, 3 Error, 4 Warning, 5 Notice, 6 Informational, 7 Debug — lower number means more severe. Mnemonic: Every Awesome Cisco Engineer Will Need Ice-cream Daily.",
    },
    {
        "type": "order",
        "q": "Arrange the steps to identify a bandwidth hog and then inspect its traffic contents.",
        "items": [
            "Compare current utilization against the baseline",
            "Review flow data to identify the top-talker host",
            "Configure port mirroring for that host's switch port",
            "Run a packet capture on the mirrored traffic",
            "Analyze payloads in Wireshark",
        ],
        "explain": "Real investigations move down the visibility ladder: the baseline confirms the spike is abnormal, flow data pinpoints who is responsible without heavy storage, then SPAN plus a targeted packet capture provides full payloads for analysis. Capturing everything first would be wasteful and slow.",
    },
]
