TOPIC = {
    "id": "3.3",
    "domain": 3,
    "title": "Explain disaster recovery (DR) concepts.",
    "short": "Disaster Recovery",
}

TERMS = [
    ("Recovery point objective (RPO)", "Maximum acceptable amount of data loss measured in time; determines how often backups or replication must run"),
    ("Recovery time objective (RTO)", "Maximum acceptable downtime — the target time to restore service after a failure"),
    ("Mean time to repair (MTTR)", "Average time required to fix a failed component and return it to service; lower is better"),
    ("Mean time between failures (MTBF)", "Average operating time between one failure and the next; a reliability measure — higher is better"),
    ("Cold site", "DR facility with space, power, and cooling only — no installed hardware or data; cheapest, recovery takes days to weeks"),
    ("Warm site", "DR facility with hardware installed but data that must be restored from backups; moderate cost, recovery in hours to days"),
    ("Hot site", "Fully operational duplicate facility with current replicated data; most expensive, failover in minutes"),
    ("Active-active", "High-availability design in which all nodes serve traffic simultaneously, giving near-instant failover"),
    ("Active-passive", "High-availability design in which a standby node waits idle and takes over when the active node fails"),
    ("Failover", "The process of shifting workload from a failed system or site to a redundant one"),
    ("Tabletop exercise", "Discussion-based walkthrough of the DR plan using a scenario; no systems are touched"),
    ("Validation test", "Hands-on DR test that actually restores backups or fails over systems to prove RTO/RPO can be met"),
    ("Disaster recovery plan", "Documented procedures, roles, and resources for restoring IT operations after a disaster"),
    ("High availability", "Designing with redundancy so services keep running through component failures"),
    ("Replication", "Continuously copying data to another system or site so the copy stays current; enables near-zero RPO"),
    ("Backup frequency", "How often backups run; set by the RPO — you can lose at most the data created since the last backup"),
    ("Heartbeat", "Health-check signal between HA nodes that a standby uses to detect active-node failure"),
    ("Load balancer", "Device distributing traffic across multiple active nodes, common in active-active designs"),
    ("Redundancy", "Duplicate components or paths that remove single points of failure"),
    ("Availability formula", "Availability rises as MTBF increases and MTTR decreases (roughly MTBF divided by MTBF plus MTTR)"),
]

QUESTIONS = [
    # --- Multiple choice (21) ---
    {
        "type": "mc",
        "q": "A business decides it can afford to lose at most one hour of transaction data in a disaster. Which metric has it defined?",
        "choices": ["RTO", "MTBF", "RPO", "MTTR"],
        "answer": 2,
        "explain": "The recovery point objective (RPO) is the maximum acceptable data loss measured in time — how far back the restored data may fall. An RPO of one hour means backups or replication must capture data at least hourly.",
    },
    {
        "type": "mc",
        "q": "Which metric directly determines how frequently backups must be taken?",
        "choices": ["RPO", "RTO", "MTTR", "MTBF"],
        "answer": 0,
        "explain": "You can lose at most the data created since the last backup, so backup frequency must be at least as tight as the RPO. A 24-hour RPO allows nightly backups; a near-zero RPO requires continuous replication.",
    },
    {
        "type": "mc",
        "q": "Management states the order-entry system must be back online within 30 minutes of any outage. Which metric is this?",
        "choices": ["MTBF", "RTO", "RPO", "SLA"],
        "answer": 1,
        "explain": "The recovery time objective (RTO) is the maximum acceptable downtime — the target time to restore service. Small RTOs demand hot sites, automated failover, and rehearsed procedures; long RTOs can tolerate rebuilding from scratch.",
    },
    {
        "type": "mc",
        "q": "Nightly backups run at 11 p.m. A server fails at 3 p.m. and is restored from the previous night's backup, losing 16 hours of data. Which objective was this loss measured against?",
        "choices": ["MTTR", "MTBF", "RTO", "RPO"],
        "answer": 3,
        "explain": "The amount of data lost — expressed in time since the last good copy — is the domain of the RPO. If losing 16 hours is unacceptable, the RPO must be tightened and backups must run more often. The RTO instead governs how long the restore itself may take.",
    },
    {
        "type": "mc",
        "q": "Over the past year a firewall model failed 4 times, and each repair averaged 2 hours. The '2 hours' figure is the:",
        "choices": ["MTBF", "RPO", "MTTR", "RTO"],
        "answer": 2,
        "explain": "Mean time to repair (MTTR) is the average time from failure to restored service, including diagnosis and fix. It measures maintainability and support responsiveness — improved with spares, documentation, and support contracts. The failure interval would be the MTBF.",
    },
    {
        "type": "mc",
        "q": "When comparing two switch models for reliability, which specification indicates how long a unit typically runs between failures?",
        "choices": ["MTBF", "MTTR", "RTO", "RPO"],
        "answer": 0,
        "explain": "Mean time between failures (MTBF) is the average operating time between one failure and the next — the standard reliability rating. Higher MTBF means fewer failures; it guides purchasing, spares stocking, and proactive replacement.",
    },
    {
        "type": "mc",
        "q": "Which pairing is correct?",
        "choices": ["RPO = downtime tolerance; RTO = data-loss tolerance", "MTTR = reliability; MTBF = repair speed", "RPO = data-loss tolerance; RTO = downtime tolerance", "MTBF = a business objective; RTO = a measured average"],
        "answer": 2,
        "explain": "RPO bounds data loss (drives backup frequency); RTO bounds downtime (drives recovery speed). MTTR is the measured average repair time and MTBF the measured reliability between failures. RPO/RTO are objectives the business sets; MTTR/MTBF are measured statistics.",
    },
    {
        "type": "mc",
        "q": "A DR facility provides floor space, power, and cooling but contains no servers, network gear, or data. What is it?",
        "choices": ["Hot site", "Cold site", "Warm site", "Mirror site"],
        "answer": 1,
        "explain": "A cold site is essentially ready real estate: after a disaster the organization must procure and install hardware, then restore data — a process taking days to weeks. It is the cheapest option and fits businesses that can tolerate a long RTO.",
    },
    {
        "type": "mc",
        "q": "A company's DR site has servers and network equipment racked and powered, but after a disaster the team must spend several hours restoring the latest backups before going live. Which site type is this?",
        "choices": ["Cold site", "Hot site", "Active-active site", "Warm site"],
        "answer": 3,
        "explain": "A warm site has the facility and hardware in place but not current data — backups must be restored and final configuration completed, giving recovery in hours to days at moderate cost. It is the classic middle ground between cold and hot.",
    },
    {
        "type": "mc",
        "q": "Which DR site type keeps data continuously replicated so operations can shift over within minutes?",
        "choices": ["Hot site", "Warm site", "Cold site", "Tabletop site"],
        "answer": 0,
        "explain": "A hot site is a fully operational duplicate of production — hardware running, applications configured, and data kept current via continuous replication. It supports near-zero RTO/RPO but costs the most, effectively a second data center.",
    },
    {
        "type": "mc",
        "q": "A startup with a very tight budget can tolerate two weeks of downtime after a catastrophic loss. Which DR site type is the most cost-appropriate?",
        "choices": ["Hot site", "Warm site", "Cold site", "Active-active data centers"],
        "answer": 2,
        "explain": "Site choice matches RTO to cost. A two-week tolerance means the days-to-weeks recovery of a cold site is acceptable, and the cold site's minimal cost (space, power, cooling only) fits the budget. Hot and warm sites buy speed the business does not need.",
    },
    {
        "type": "mc",
        "q": "In which high-availability design do ALL nodes process traffic simultaneously during normal operation?",
        "choices": ["Active-passive", "Cold standby", "Warm standby", "Active-active"],
        "answer": 3,
        "explain": "Active-active runs every node live, typically behind a load balancer, using all purchased capacity and giving near-instant failover since survivors are already serving. Active-passive keeps a standby idle until the active node fails.",
    },
    {
        "type": "mc",
        "q": "Two active-active firewalls each run at 90% capacity. What is the design flaw?",
        "choices": ["The passive unit is wasted", "If one fails, the survivor cannot absorb the total load", "Heartbeats consume too much bandwidth", "Failover will take days"],
        "answer": 1,
        "explain": "Active-active only survives a failure if the remaining nodes can carry the full combined load. Two nodes at 90% each would present 180% load to a lone survivor — an outage anyway. Capacity must be planned so N-1 nodes can handle everything.",
    },
    {
        "type": "mc",
        "q": "In an active-passive pair, how does the standby node typically know the active node has failed?",
        "choices": ["It stops receiving heartbeat health checks", "The DHCP lease expires", "A tabletop exercise detects it", "An administrator emails it"],
        "answer": 0,
        "explain": "The standby monitors heartbeat signals from the active node; when heartbeats stop (or health checks fail), the standby promotes itself and takes over the workload. This automated detection keeps failover fast, though a brief interruption occurs during takeover.",
    },
    {
        "type": "mc",
        "q": "Which is an advantage of active-passive over active-active?",
        "choices": ["It uses all purchased hardware capacity at all times", "Failover capacity is predictable and load-sharing complexity is avoided", "It provides zero-interruption failover", "It doubles throughput during normal operation"],
        "answer": 1,
        "explain": "Active-passive is simpler: no load-balancing state to synchronize, and after failover the standby carries exactly what the active carried, so capacity is predictable. The trade-offs are idle standby hardware and a brief interruption during takeover.",
    },
    {
        "type": "mc",
        "q": "A facilitator presents a ransomware scenario in a conference room and the DR team talks through each step of the plan. No systems are touched. What is this?",
        "choices": ["A validation test", "A full failover test", "A tabletop exercise", "An availability audit"],
        "answer": 2,
        "explain": "A tabletop exercise is a discussion-based walkthrough of the plan against a scenario. It is cheap and zero-risk, and excels at exposing plan gaps — unclear roles, missing contacts, wrong ordering — but it cannot prove the technology actually works.",
    },
    {
        "type": "mc",
        "q": "Which activity is a validation test rather than a tabletop exercise?",
        "choices": ["Reviewing the call tree in a meeting", "Actually failing production over to the DR site and measuring recovery time", "Reading the DR plan aloud", "Updating contact numbers in the plan"],
        "answer": 1,
        "explain": "Validation testing exercises the real technology — restoring backups, failing over, running workloads at the DR site — and measures results against RTO/RPO targets. Discussions and document reviews are tabletop activities.",
    },
    {
        "type": "mc",
        "q": "What is the most important reason to periodically test-restore backups?",
        "choices": ["To increase MTBF", "To satisfy the load balancer", "An unrestorable backup is discovered before a disaster instead of during one", "To reduce backup storage costs"],
        "answer": 2,
        "explain": "A backup that has never been test-restored is only a hope. Validation restores prove the data is complete and restorable and that staff can execute the procedure within the RTO — finding corrupt media or broken processes while there is still time to fix them.",
    },
    {
        "type": "mc",
        "q": "A company's DR plan looked complete, but a tabletop exercise revealed that two teams each believed the other would restart the database. What did the exercise accomplish?",
        "choices": ["It proved the RTO can be met", "It exposed a roles-and-responsibilities gap in the plan", "It validated the backups", "It measured MTBF"],
        "answer": 1,
        "explain": "This is exactly what tabletops are best at: surfacing unclear ownership, missing steps, and bad assumptions in the plan itself — cheaply and without touching production. Proving RTO/RPO numbers requires a hands-on validation test.",
    },
    {
        "type": "mc",
        "q": "An online brokerage requires essentially zero data loss and failover measured in seconds. Which combination fits?",
        "choices": ["Hot site with synchronous replication in an active-active design", "Cold site with weekly backups", "Warm site with nightly backups", "Tabletop exercises twice a year"],
        "answer": 0,
        "explain": "Near-zero RPO requires continuous/synchronous replication, and seconds-level RTO requires infrastructure already running — a hot site, ideally active-active so both sites serve traffic and failover is nearly instant. This is the most expensive posture, matching the strictest objectives.",
    },
    {
        "type": "mc",
        "q": "Availability improves when:",
        "choices": ["MTBF decreases and MTTR increases", "MTBF increases and MTTR decreases", "RPO increases", "Both MTBF and MTTR increase"],
        "answer": 1,
        "explain": "Availability is approximately MTBF / (MTBF + MTTR): fail less often (higher MTBF) and fix faster (lower MTTR) and uptime rises. Reliability engineering attacks both terms — better hardware raises MTBF; spares, monitoring, and runbooks cut MTTR.",
    },
    # --- True/False (5) ---
    {
        "type": "tf",
        "q": "RTO defines the maximum acceptable amount of data loss after a disaster.",
        "answer": False,
        "explain": "That is the RPO (recovery point objective). The RTO (recovery time objective) defines the maximum acceptable downtime — how quickly service must be restored. Memory hook: P = point-in-time of your last good data; T = time until you are back up.",
    },
    {
        "type": "tf",
        "q": "A higher MTBF indicates a more reliable device.",
        "answer": True,
        "explain": "MTBF is the average operating time between failures — more hours between failures means greater reliability. Contrast MTTR, where lower is better because it measures how long repairs take.",
    },
    {
        "type": "tf",
        "q": "A warm site contains installed equipment but requires data restoration before it can take over production.",
        "answer": True,
        "explain": "Warm sites have facility and hardware ready but not current data; recent backups must be restored and configuration finished, yielding recovery in hours to days at moderate cost — between cold (space only, days-weeks) and hot (mirrored, minutes).",
    },
    {
        "type": "tf",
        "q": "A tabletop exercise involves actually failing over production systems to the DR site.",
        "answer": False,
        "explain": "Tabletops are discussion-based walkthroughs — no systems are touched and production is never at risk. Actually failing over, restoring backups, and measuring against RTO/RPO is a validation test.",
    },
    {
        "type": "tf",
        "q": "In an active-passive design, the standby node's capacity is idle during normal operation.",
        "answer": True,
        "explain": "The passive node waits, monitoring heartbeats, and only carries load after a failover — paid-for capacity doing nothing day to day. That simplicity and predictable failover capacity is the trade against active-active's full utilization.",
    },
    # --- Fill-in (5) ---
    {
        "type": "fill",
        "q": "The DR metric measuring the maximum tolerable data loss (in time) is abbreviated ______. (type your answer)",
        "answers": ["RPO", "recovery point objective"],
        "explain": "The recovery point objective bounds how much data may be lost, expressed as time since the last recoverable copy. It directly dictates backup or replication frequency — tighter RPO, more frequent (and expensive) data protection.",
    },
    {
        "type": "fill",
        "q": "The DR metric measuring the maximum tolerable downtime is abbreviated ______. (type your answer)",
        "answers": ["RTO", "recovery time objective"],
        "explain": "The recovery time objective is the target time to restore service after an outage. It drives the recovery infrastructure: minutes-level RTOs need hot sites and automated failover; long RTOs can rebuild from scratch.",
    },
    {
        "type": "fill",
        "q": "The average time between one failure and the next, used to compare hardware reliability, is abbreviated ______. (type your answer)",
        "answers": ["MTBF", "mean time between failures"],
        "explain": "Mean time between failures rates reliability — higher is better. It informs purchasing decisions, spare-parts stocking, and proactive replacement schedules, and together with MTTR determines achievable availability.",
    },
    {
        "type": "fill",
        "q": "A fully mirrored DR facility with current replicated data, ready to take over in minutes, is a ______ site. (type your answer)",
        "answers": ["hot"],
        "explain": "Hot sites duplicate production — running hardware, configured applications, continuously replicated data — enabling failover in minutes at the highest cost. Cold sites are empty space (days-weeks); warm sites have gear but stale data (hours-days).",
    },
    {
        "type": "fill",
        "q": "A discussion-based DR plan walkthrough in which no systems are touched is called a ______ exercise. (type your answer)",
        "answers": ["tabletop", "table top"],
        "explain": "In a tabletop exercise a facilitator presents a disaster scenario and the team walks through the plan verbally — cheap, zero-risk, and excellent at finding plan gaps like unclear roles or missing contacts. It complements, but never replaces, hands-on validation tests.",
    },
    # --- Match (2) ---
    {
        "type": "match",
        "q": "Match each DR metric to what it measures.",
        "pairs": [
            ["RPO", "Maximum tolerable data loss, in time"],
            ["RTO", "Maximum tolerable downtime"],
            ["MTTR", "Average time to repair a failure"],
            ["MTBF", "Average operating time between failures"],
        ],
        "explain": "RPO and RTO are objectives the business sets — data-loss tolerance and downtime tolerance respectively. MTTR and MTBF are measured statistics — repair speed (lower better) and reliability (higher better). Availability rises as MTBF grows and MTTR shrinks.",
    },
    {
        "type": "match",
        "q": "Match each DR site type to its description.",
        "pairs": [
            ["Cold site", "Space, power, and cooling only; recovery in days to weeks"],
            ["Warm site", "Hardware installed; data restored from backup; hours to days"],
            ["Hot site", "Fully mirrored with replicated data; failover in minutes"],
            ["Active-active", "All nodes serving traffic with near-instant failover"],
        ],
        "explain": "The site spectrum trades cost for recovery speed: cold is cheapest and slowest, warm is the middle ground, hot is a running duplicate. Active-active is the high-availability approach where every node is already serving, so failover is essentially immediate.",
    },
    # --- Order (2) ---
    {
        "type": "order",
        "q": "Arrange the DR site types from LOWEST cost/SLOWEST recovery to HIGHEST cost/FASTEST recovery.",
        "items": [
            "Cold site",
            "Warm site",
            "Hot site",
            "Active-active dual data centers",
        ],
        "explain": "Cold (empty space, days-weeks) costs least; warm (equipment, restore data, hours-days) is the middle; hot (mirrored, minutes) costs the most of the classic three; running two active-active data centers is the ultimate — and priciest — posture with near-zero recovery time.",
    },
    {
        "type": "order",
        "q": "Arrange these recovery activities in the order they would occur when a warm site is activated after a disaster.",
        "items": [
            "Declare the disaster and activate the DR plan",
            "Travel to or remotely access the warm site",
            "Restore the latest backups onto the standby hardware",
            "Complete final configuration and testing",
            "Redirect users and resume production at the warm site",
        ],
        "explain": "Warm-site activation starts with formally invoking the plan, then using the already-installed hardware: data must be restored from backups and configuration finalized before users are cut over. The restore step is exactly why warm-site recovery takes hours to days rather than minutes.",
    },
]
