TOPIC = {
    "id": "3.4",
    "domain": 3,
    "title": "Given a scenario, implement IPv4 and IPv6 network services.",
    "short": "IPv4/IPv6 Network Services",
}

TERMS = [
    ("DHCP", "Dynamic Host Configuration Protocol — automatically leases IP addresses and options to clients; server UDP 67, client UDP 68"),
    ("DORA", "The DHCP lease sequence: Discover, Offer, Request, Acknowledge"),
    ("DHCP scope", "The pool of addresses a DHCP server may lease on one subnet, with its mask, gateway, DNS, and lease time"),
    ("DHCP exclusion", "Addresses inside a scope that the server must never lease, reserved for statically configured devices"),
    ("DHCP reservation", "A mapping of a client's MAC address to a fixed IP so the client always receives the same DHCP-managed address"),
    ("Lease time", "How long a DHCP address assignment is valid; the client attempts unicast renewal at 50% (T1)"),
    ("DHCP option 3", "Delivers the default gateway (router) address to clients"),
    ("DHCP option 6", "Delivers the DNS server addresses to clients"),
    ("DHCP options 66/67", "Deliver the TFTP/boot server name and bootfile name, used for VoIP phone provisioning"),
    ("DHCP relay / IP helper", "Router feature that converts client DHCP broadcasts to unicast and forwards them to a server on another subnet"),
    ("APIPA", "Automatic private addressing 169.254.x.x that a client self-assigns when no DHCP server can be reached"),
    ("SLAAC", "Stateless address autoconfiguration — an IPv6 host builds its own address from a router-advertised prefix plus an interface ID"),
    ("Router advertisement", "ICMPv6 message from a router carrying the IPv6 prefix and gateway information used by SLAAC"),
    ("EUI-64", "Method of building a 64-bit interface ID from a MAC address by inserting FFFE and flipping the seventh bit"),
    ("DNS", "Domain Name System — hierarchical name resolution from root to TLD to authoritative servers, port 53"),
    ("A record", "DNS record mapping a hostname to an IPv4 address"),
    ("AAAA record", "DNS record mapping a hostname to an IPv6 address"),
    ("CNAME record", "Alias record pointing one hostname at another hostname, never at an IP"),
    ("MX record", "Mail exchange record naming a domain's mail server; lowest preference number wins"),
    ("TXT record", "Text record carrying data such as SPF and DKIM email-authentication entries"),
    ("NS record", "Record listing the authoritative name servers for a domain"),
    ("PTR record", "Reverse-lookup record mapping an IP address back to a hostname, stored in in-addr.arpa zones"),
    ("Forward zone", "DNS zone resolving names to IP addresses"),
    ("Reverse zone", "DNS zone resolving IP addresses to names via PTR records under in-addr.arpa or ip6.arpa"),
    ("Authoritative answer", "DNS response from a server that hosts the zone, versus a non-authoritative answer served from a resolver's cache"),
    ("Primary DNS server", "Server holding the writable master copy of a zone; secondaries hold read-only copies via zone transfer"),
    ("Recursive resolver", "DNS server that walks root, TLD, and authoritative servers on the client's behalf and caches answers"),
    ("DNSSEC", "DNS Security Extensions — digital signatures that give DNS answers integrity and authenticity, without encryption"),
    ("DoT", "DNS over TLS — encrypts DNS queries on dedicated TCP port 853"),
    ("DoH", "DNS over HTTPS — encrypts DNS queries inside HTTPS on TCP port 443, blending in with web traffic"),
    ("Hosts file", "Local static name-to-IP file checked before DNS; its entries override DNS answers"),
    ("NTP", "Network Time Protocol — clock synchronization over UDP 123 using stratum levels, millisecond accuracy"),
    ("Stratum", "NTP distance from the reference clock: stratum 0 is the clock itself, 1 is directly attached, each hop adds one"),
    ("PTP", "Precision Time Protocol, IEEE 1588 — sub-microsecond sync using hardware timestamping, for finance and industrial systems"),
    ("NTS", "Network Time Security — adds TLS-based authentication and integrity protection to NTP"),
]

QUESTIONS = [
    # --- Multiple choice (23) ---
    {
        "type": "mc",
        "q": "In the DHCP lease process, what is the correct order of messages?",
        "choices": ["Offer, Discover, Acknowledge, Request", "Discover, Offer, Request, Acknowledge", "Request, Offer, Discover, Acknowledge", "Discover, Request, Offer, Acknowledge"],
        "answer": 1,
        "explain": "DORA: the client broadcasts a Discover, a server returns an Offer, the client broadcasts a Request accepting one offer, and the server finalizes with an Acknowledge. The Request is broadcast so other offering servers know they were declined.",
    },
    {
        "type": "mc",
        "q": "Why must the initial DHCP Discover be a broadcast?",
        "choices": ["Broadcasts are faster than unicasts", "The client has no IP address yet and does not know any server's address", "DHCP servers only have MAC addresses", "Routers forward broadcasts more reliably"],
        "answer": 1,
        "explain": "A brand-new client has no IP configuration and no knowledge of the server, so it sends from 0.0.0.0 to 255.255.255.255. This broadcast dependence is also why DHCP fails across routers without a relay agent — routers do not forward broadcasts.",
    },
    {
        "type": "mc",
        "q": "A Windows laptop shows the address 169.254.77.10. What does this indicate?",
        "choices": ["The DHCP server assigned it from the scope", "A DHCP reservation took effect", "The client could not reach a DHCP server and self-assigned an APIPA address", "SLAAC provided the address"],
        "answer": 2,
        "explain": "169.254.0.0/16 is APIPA link-local space that a client assigns itself when DHCP fails. It allows only local-subnet communication. Seeing 169.254.x.x is the classic symptom of a down or unreachable DHCP server (or a missing relay).",
    },
    {
        "type": "mc",
        "q": "A network printer must always have the same IP address, but the admin wants the assignment centrally managed by the DHCP server. What should be configured?",
        "choices": ["A reservation mapping the printer's MAC to the IP", "An exclusion for the printer's IP", "A shorter lease time", "A second scope"],
        "answer": 0,
        "explain": "A reservation ties a specific MAC address to a fixed IP: the printer still leases via DHCP (keeping central management and options) but always gets the same address. An exclusion would instead remove the address from DHCP and require static configuration on the printer.",
    },
    {
        "type": "mc",
        "q": "The router at 10.1.1.1 and two servers at 10.1.1.2-3 are statically configured inside the DHCP scope's range. How do you prevent the server from leasing those addresses to clients?",
        "choices": ["Create reservations for them", "Configure an exclusion range covering them", "Shorten the lease time", "Enable a relay agent"],
        "answer": 1,
        "explain": "An exclusion range carves addresses out of the scope so the server never offers them — the right tool for devices configured statically. Reservations are for devices that should continue using DHCP but always receive the same address.",
    },
    {
        "type": "mc",
        "q": "At what point does a DHCP client first attempt to renew its lease, and how?",
        "choices": ["At 50% of the lease (T1), via unicast to the original server", "At 100% expiry, via broadcast", "At 25% of the lease, via multicast", "At 87.5% (T2), via unicast to any server"],
        "answer": 0,
        "explain": "At T1 — half the lease time — the client unicasts a renewal Request to the server that granted the lease. If that fails, at T2 (87.5%) it broadcasts to any server (rebinding), and if the lease fully expires it must restart DORA from scratch.",
    },
    {
        "type": "mc",
        "q": "Which DHCP option delivers the default gateway to clients?",
        "choices": ["Option 6", "Option 66", "Option 3", "Option 51"],
        "answer": 2,
        "explain": "Option 3 (Router) supplies the default gateway. Option 6 supplies DNS servers, option 51 the lease time, and options 66/67 the TFTP boot server and bootfile name. The 3-vs-6 pairing is a favorite exam trap.",
    },
    {
        "type": "mc",
        "q": "New VoIP phones boot and get addresses but never download their configuration files from the provisioning server. Which DHCP options should be checked?",
        "choices": ["Options 1 and 3", "Options 66 and 67", "Options 6 and 15", "Option 51 only"],
        "answer": 1,
        "explain": "Options 66 (TFTP/boot server name) and 67 (bootfile name) tell phones where to fetch firmware and configuration at boot (Cisco phones often use option 150 for a TFTP server IP). Without them, phones get an address but cannot provision.",
    },
    {
        "type": "mc",
        "q": "Clients on a newly created VLAN receive 169.254.x.x addresses. The DHCP server sits on a different subnet and serves other VLANs fine. What is the fix?",
        "choices": ["Configure a DHCP relay / IP helper address on the new VLAN's router interface", "Add an exclusion range", "Shorten the lease time", "Enable DNSSEC"],
        "answer": 0,
        "explain": "DHCP Discovers are broadcasts, which routers drop. A relay agent (Cisco 'ip helper-address') on the client-facing interface converts the broadcast to unicast, forwards it to the server, and stamps in the gateway address so the server picks the right scope.",
    },
    {
        "type": "mc",
        "q": "How does a DHCP server with many scopes know which subnet's pool to allocate from when a relayed request arrives?",
        "choices": ["From the client's hostname", "From the relay-inserted gateway address (GIADDR) in the request", "It always uses the first scope", "From the client's DNS suffix"],
        "answer": 1,
        "explain": "The relay agent writes the receiving interface's address into the GIADDR field before forwarding. The server matches GIADDR against its scopes to choose the correct subnet's pool — this is what makes one central server able to serve dozens of subnets.",
    },
    {
        "type": "mc",
        "q": "In SLAAC, where does an IPv6 host get the 64-bit network prefix for its global address?",
        "choices": ["From a DHCPv6 server's lease", "From a Router Advertisement sent by the local router", "From the DNS server", "It generates the prefix randomly"],
        "answer": 1,
        "explain": "The host sends a Router Solicitation and the router answers (or periodically multicasts) a Router Advertisement carrying the /64 prefix and default-router information. The host appends a self-generated 64-bit interface ID — no server tracks the assignment, hence 'stateless.'",
    },
    {
        "type": "mc",
        "q": "What does the EUI-64 method do when forming an IPv6 interface identifier?",
        "choices": ["Hashes the hostname into 64 bits", "Requests an ID from the DHCPv6 server", "Uses a random number regenerated daily", "Inserts FFFE into the middle of the 48-bit MAC and flips the seventh bit"],
        "answer": 3,
        "explain": "EUI-64 expands a 48-bit MAC to 64 bits by inserting FFFE between the OUI and device halves, then inverts the seventh bit (universal/local). Because this embeds the trackable MAC, modern systems often use randomized privacy extensions instead.",
    },
    {
        "type": "mc",
        "q": "Which DNS record type maps a hostname to an IPv6 address?",
        "choices": ["A", "AAAA", "PTR", "CNAME"],
        "answer": 1,
        "explain": "AAAA ('quad-A') records hold IPv6 addresses; A records hold IPv4 addresses. PTR does the reverse (IP to name) and CNAME aliases one name to another name.",
    },
    {
        "type": "mc",
        "q": "A domain has MX records: mail1 preference 10 and mail2 preference 20. How do sending servers use them?",
        "choices": ["They try mail1 first because LOWER preference wins", "They try mail2 first because higher preference wins", "They always load-balance evenly", "They pick alphabetically"],
        "answer": 0,
        "explain": "MX preference is a priority where lower numbers win: senders deliver to the lowest-preference server first and fall back to higher numbers if it is unreachable. Equal values are load-shared.",
    },
    {
        "type": "mc",
        "q": "Where are SPF and DKIM email-authentication entries published in DNS?",
        "choices": ["In MX records", "In PTR records", "In TXT records", "In NS records"],
        "answer": 2,
        "explain": "SPF (which servers may send mail for the domain) and DKIM (public keys for mail signatures) are published as TXT records. MX names the mail servers that receive mail; it does not authorize senders.",
    },
    {
        "type": "mc",
        "q": "Which statement about CNAME records is correct?",
        "choices": ["A CNAME maps an alias to an IPv4 address", "A CNAME points an alias name at another hostname, never directly at an IP", "CNAMEs are used only in reverse zones", "A CNAME lists a domain's name servers"],
        "answer": 1,
        "explain": "A CNAME makes one name an alias for a canonical name — e.g., www.example.com pointing to webserver.example.com — and resolution then continues at the target name. IP mappings are A/AAAA records; reverse lookups are PTR; name-server listings are NS.",
    },
    {
        "type": "mc",
        "q": "In which DNS zone would the record '40.30.20.10.in-addr.arpa PTR host.example.com' appear?",
        "choices": ["A forward zone", "A stub zone", "A root zone", "A reverse zone"],
        "answer": 3,
        "explain": "Reverse zones live under in-addr.arpa (IPv4, octets reversed — this record resolves 10.20.30.40) or ip6.arpa (IPv6) and hold PTR records mapping addresses back to names. Forward zones hold A, AAAA, CNAME, MX, TXT, and NS records for name-to-IP resolution.",
    },
    {
        "type": "mc",
        "q": "nslookup returns 'Non-authoritative answer' for a record. What does that mean?",
        "choices": ["The record does not exist", "The answer came from a resolver's cache rather than a server hosting the zone", "DNSSEC validation failed", "The answer used TCP instead of UDP"],
        "answer": 1,
        "explain": "Non-authoritative answers are cached copies served by a recursive resolver until the record's TTL expires. Authoritative answers come from the zone's own name servers — the source of truth. Cached answers can be stale after a recent record change.",
    },
    {
        "type": "mc",
        "q": "What distinguishes a primary DNS server from a secondary?",
        "choices": ["Only the primary is authoritative", "The primary holds the writable zone copy; secondaries hold read-only copies received via zone transfer", "Secondaries answer only reverse lookups", "The primary must be operated by the registrar"],
        "answer": 1,
        "explain": "All record edits happen on the primary's master zone file; secondaries pull read-only copies via zone transfer (AXFR/IXFR over TCP 53) for redundancy and load sharing. Both primary and secondary are authoritative for the zone — a favorite exam nuance.",
    },
    {
        "type": "mc",
        "q": "What protection does DNSSEC provide?",
        "choices": ["Encryption of DNS queries so ISPs cannot read them", "Digital signatures proving DNS answers are authentic and unmodified", "Blocking of all recursive queries", "Compression of zone transfers"],
        "answer": 1,
        "explain": "DNSSEC signs records (RRSIG/DNSKEY/DS chain of trust) so resolvers can verify origin authenticity and integrity, defeating spoofing and cache poisoning. It does NOT encrypt anything — queries remain readable. Privacy requires DoT or DoH.",
    },
    {
        "type": "mc",
        "q": "Which port pairing for encrypted DNS transports is correct?",
        "choices": ["DoT TCP 853; DoH TCP 443", "DoT UDP 53; DoH TCP 853", "DoT TCP 443; DoH TCP 853", "DoT UDP 123; DoH TCP 80"],
        "answer": 0,
        "explain": "DNS over TLS uses dedicated TCP port 853, making it identifiable (and filterable) as DNS. DNS over HTTPS rides inside normal HTTPS on TCP 443, blending in with web traffic and making it hard for network admins to distinguish or block.",
    },
    {
        "type": "mc",
        "q": "One workstation resolves www.partner.com to the wrong address while every other machine resolves it correctly. What should be checked FIRST on that workstation?",
        "choices": ["The domain's MX records", "The local hosts file", "The TLD servers", "The DHCP scope options"],
        "answer": 1,
        "explain": "The hosts file is consulted before DNS and its entries override DNS answers, so a stale or malicious local entry affects only that machine. A single-host resolution anomaly is the classic hosts-file symptom (also a known malware trick).",
    },
    {
        "type": "mc",
        "q": "A financial exchange needs clock synchronization accurate to well under a microsecond, using hardware timestamps. Which protocol fits?",
        "choices": ["NTP", "NTS", "PTP (IEEE 1588)", "SNMP"],
        "answer": 2,
        "explain": "Precision Time Protocol, IEEE 1588, achieves sub-microsecond accuracy by timestamping packets in NIC/switch hardware and compensating for switch delays via PTP-aware boundary/transparent clocks. NTP delivers only millisecond-class accuracy; NTS merely secures NTP.",
    },
    # --- True/False (6) ---
    {
        "type": "tf",
        "q": "A DHCP client renews its lease by unicasting to the original server when 50% of the lease time has elapsed.",
        "answer": True,
        "explain": "At T1 (50%) the client sends a unicast Request to the granting server; a successful ACK resets the lease. Only if renewal keeps failing does it broadcast at T2 (87.5%), and a fully expired lease forces a new DORA exchange.",
    },
    {
        "type": "tf",
        "q": "SLAAC requires a DHCPv6 server to assign each host its IPv6 address.",
        "answer": False,
        "explain": "SLAAC is serverless: the router's advertisement supplies the prefix and the host generates its own interface ID (EUI-64 or random privacy address). DHCPv6 is the stateful alternative used when central assignment and tracking are required.",
    },
    {
        "type": "tf",
        "q": "DNSSEC encrypts DNS queries so that observers on the network cannot read them.",
        "answer": False,
        "explain": "DNSSEC provides integrity and authenticity via digital signatures — not confidentiality. Queries and responses remain readable on the wire. Encrypting DNS transport is the job of DoT (TCP 853) and DoH (TCP 443).",
    },
    {
        "type": "tf",
        "q": "Both primary and secondary DNS servers give authoritative answers for their zone.",
        "answer": True,
        "explain": "Primary vs. secondary describes where the zone is edited (writable master vs. read-only transfer copy) — both host the zone and answer authoritatively. Non-authoritative answers come from resolver caches, a different distinction entirely.",
    },
    {
        "type": "tf",
        "q": "An NTP server that synchronizes directly to a GPS reference clock is operating at stratum 1.",
        "answer": True,
        "explain": "Stratum 0 is the reference clock itself (GPS, atomic); a server directly attached to it is stratum 1; servers syncing from stratum 1 become stratum 2, and so on. Lower stratum means closer to the reference; stratum 16 means unsynchronized.",
    },
    {
        "type": "tf",
        "q": "The operating system consults DNS before checking the local hosts file.",
        "answer": False,
        "explain": "The hosts file is checked first, and its entries override DNS. That makes it useful for testing and labs — and a target for malware, plus the first thing to inspect when exactly one machine resolves a name incorrectly.",
    },
    # --- Fill-in (6) ---
    {
        "type": "fill",
        "q": "The four-step DHCP lease process is known by the acronym ______. (type your answer)",
        "answers": ["DORA"],
        "explain": "Discover, Offer, Request, Acknowledge. The client broadcasts Discover, servers Offer, the client broadcasts its Request for one offer, and the chosen server Acknowledges — creating the lease.",
    },
    {
        "type": "fill",
        "q": "DHCP option number ______ delivers the DNS server addresses to clients. (type your answer)",
        "answers": ["6"],
        "explain": "Option 6 = DNS servers; option 3 = default gateway/router; options 66/67 = TFTP boot server and bootfile for device provisioning. Keep 3 and 6 straight — they are the most commonly confused pair.",
    },
    {
        "type": "fill",
        "q": "DNS over TLS (DoT) uses TCP port ______. (type your answer)",
        "answers": ["853"],
        "explain": "DoT encrypts DNS on its own dedicated port, TCP 853, so it is recognizable as DNS traffic. DoH instead tunnels DNS inside HTTPS on TCP 443, where it is indistinguishable from ordinary web traffic.",
    },
    {
        "type": "fill",
        "q": "NTP synchronizes clocks over UDP port ______. (type your answer)",
        "answers": ["123"],
        "explain": "NTP uses UDP 123 and organizes servers into strata: stratum 0 reference clocks, stratum 1 servers attached to them, stratum 2 below that. Accurate time is essential for Kerberos, certificates, and log correlation.",
    },
    {
        "type": "fill",
        "q": "IPv4 reverse-lookup PTR records live under the special DNS domain ______. (type your answer)",
        "answers": ["in-addr.arpa", "in-addr arpa", "inaddr.arpa"],
        "explain": "Reverse zones for IPv4 sit under in-addr.arpa with the octets reversed (10.20.30.40 becomes 40.30.20.10.in-addr.arpa); IPv6 uses ip6.arpa. Mail servers and logging systems rely on these PTR lookups.",
    },
    {
        "type": "fill",
        "q": "The standard that adds TLS-based authentication to NTP is Network Time ______. (type your answer)",
        "answers": ["Security", "NTS"],
        "explain": "Network Time Security (NTS) bolts cryptographic protection onto NTP: a TLS key-establishment phase provisions keys/cookies, after which NTP packets carry authenticated fields. It guarantees responses are genuine and untampered — like DNSSEC's integrity role, but for time.",
    },
    # --- Match (2) ---
    {
        "type": "match",
        "q": "Match each DNS record type to its function.",
        "pairs": [
            ["A", "Hostname to IPv4 address"],
            ["AAAA", "Hostname to IPv6 address"],
            ["CNAME", "Alias pointing to another hostname"],
            ["MX", "Mail server for the domain, lowest preference wins"],
            ["PTR", "IP address back to hostname (reverse)"],
            ["NS", "Authoritative name servers for the zone"],
        ],
        "explain": "A and AAAA carry addresses (IPv4 and IPv6 respectively), CNAME aliases names to names, MX directs mail with lower preference values winning, PTR performs reverse lookups from in-addr.arpa/ip6.arpa zones, and NS delegates by naming the zone's authoritative servers. TXT (SPF/DKIM) rounds out the exam list.",
    },
    {
        "type": "match",
        "q": "Match each time or addressing technology to its distinguishing feature.",
        "pairs": [
            ["NTP", "Millisecond sync over UDP 123 using strata"],
            ["PTP", "Sub-microsecond sync with hardware timestamps (IEEE 1588)"],
            ["NTS", "TLS-based authentication added to NTP"],
            ["SLAAC", "Host builds its own IPv6 address from a router-advertised prefix"],
            ["DHCP reservation", "MAC address always receives the same leased IP"],
        ],
        "explain": "NTP is the general-purpose millisecond-class time protocol; PTP adds hardware timestamping for finance/industrial precision; NTS secures NTP's authenticity. SLAAC is IPv6's serverless self-addressing via RA prefixes, while a DHCP reservation pins a specific MAC to a fixed, centrally managed address.",
    },
    # --- Order (2) ---
    {
        "type": "order",
        "q": "Arrange the DHCP messages in the order they occur when a new client obtains a lease.",
        "items": [
            "Discover — client broadcasts for servers",
            "Offer — server proposes an address",
            "Request — client broadcasts acceptance of one offer",
            "Acknowledge — server finalizes the lease",
        ],
        "explain": "DORA in action: the addressless client must broadcast its Discover, servers respond with Offers, the client broadcasts a Request naming its chosen offer (so other servers withdraw), and the winning server's ACK completes the lease with all options attached.",
    },
    {
        "type": "order",
        "q": "Arrange the steps of recursive DNS resolution for www.example.com when nothing is cached.",
        "items": [
            "Client checks its local cache and hosts file",
            "Client queries its recursive resolver",
            "Resolver queries a root server and is referred to .com",
            "Resolver queries the .com TLD server and is referred to example.com's name servers",
            "Resolver queries example.com's authoritative server and gets the A record",
            "Resolver caches the answer and returns it to the client",
        ],
        "explain": "Resolution starts locally (cache, then hosts file), then the recursive resolver walks the hierarchy: root refers to the TLD, the TLD refers to the domain's authoritative servers, and the authoritative server supplies the record. The resolver caches the answer for its TTL — which is why later clients get fast, non-authoritative answers.",
    },
]
