TOPIC = {
    "id": "3.5",
    "domain": 3,
    "title": "Compare and contrast network access and management methods.",
    "short": "Access & Management Methods",
}

TERMS = [
    ("Site-to-site VPN", "Always-on encrypted tunnel between routers/firewalls that joins two networks, with no client software on user devices"),
    ("Client-to-site VPN", "Per-session encrypted tunnel from an individual remote device to a VPN concentrator on the corporate edge"),
    ("Clientless VPN", "Browser-based TLS/HTTPS portal giving remote access to published applications with no installed VPN software"),
    ("VPN concentrator", "Edge device (often a firewall) that terminates remote users' VPN tunnels and enforces authentication"),
    ("Split tunnel", "VPN mode sending only corporate-destined traffic through the tunnel; Internet traffic exits the user's local connection"),
    ("Full tunnel", "VPN mode forcing ALL of the client's traffic through the tunnel and the corporate security stack"),
    ("IPsec", "Encryption protocol suite commonly used for site-to-site VPN tunnels"),
    ("SSH", "Secure Shell — encrypted command-line access on TCP 22, supporting public-key authentication; the secure replacement for Telnet"),
    ("Telnet", "Legacy remote CLI protocol on TCP 23 that transmits everything, including credentials, in plaintext"),
    ("Public-key authentication", "SSH login using a key pair, where the private key never crosses the network"),
    ("GUI management", "Managing devices through a graphical interface such as an HTTPS web console or controller dashboard"),
    ("API management", "Programmatic device management, typically REST over HTTPS exchanging JSON, used for automation at scale"),
    ("REST API", "HTTP-based programmatic interface commonly returning JSON, used by scripts and orchestration tools"),
    ("Console port", "Physical serial port accessed with a rollover cable and terminal emulator; works with no network or IP configuration"),
    ("Rollover cable", "Serial console cable (classically RJ45 to DB9) used for direct device management"),
    ("Jump box", "Hardened intermediary host serving as the single, logged entry point for administration of a secure network segment"),
    ("Bastion host", "Hardened, exposed host designed to withstand attack; jump boxes are a management-focused example"),
    ("In-band management", "Managing devices over the same production network that carries user data; fails when the network fails"),
    ("Out-of-band management", "Managing devices over a dedicated separate path — management network, console server, or cellular — that works during outages"),
    ("Console server", "Appliance wired to many devices' console ports, providing remote out-of-band access, often with cellular backup"),
    ("Terminal emulator", "Software such as PuTTY used to open serial console or SSH sessions"),
    ("Management VLAN", "Dedicated VLAN segregating in-band management traffic from user traffic"),
    ("Lights-out management", "Server out-of-band interfaces such as iDRAC, iLO, and IPMI that work even when the OS is down"),
]

QUESTIONS = [
    # --- Multiple choice (21) ---
    {
        "type": "mc",
        "q": "A company opens a branch office and wants its LAN permanently connected to headquarters over the Internet, with no VPN software on employee PCs. Which solution fits?",
        "choices": ["Client-to-site VPN for each employee", "A clientless web portal", "A site-to-site VPN between the sites' edge firewalls", "A jump box at each site"],
        "answer": 2,
        "explain": "A site-to-site VPN is an always-on encrypted tunnel (typically IPsec) terminated on the routers/firewalls at each location, joining the networks transparently. Users simply route to the other site — no per-user clients or logins.",
    },
    {
        "type": "mc",
        "q": "Which statement correctly contrasts site-to-site and client-to-site VPNs?",
        "choices": ["Site-to-site connects one device; client-to-site connects networks", "Site-to-site is always-on between gateways; client-to-site is a per-session tunnel from an individual device", "Client-to-site requires no authentication", "Site-to-site requires client software on every PC"],
        "answer": 1,
        "explain": "Site-to-site tunnels are infrastructure: gateway devices keep them up permanently and users need no software. Client-to-site (remote access) tunnels exist only while an individual user's device is connected and authenticated to the concentrator.",
    },
    {
        "type": "mc",
        "q": "A traveling employee at a hotel needs full access to internal corporate resources from a company laptop. Which method fits?",
        "choices": ["Client-to-site VPN with the corporate VPN client", "Site-to-site VPN with the hotel", "A console cable to the hotel router", "SNMPv3"],
        "answer": 0,
        "explain": "Remote individual users run VPN client software that builds an encrypted tunnel to the corporate concentrator after authentication (ideally MFA). Site-to-site is for permanently joining networks, not roaming users.",
    },
    {
        "type": "mc",
        "q": "A contractor must reach one internal web application from a personal tablet on which nothing can be installed. Which access method fits best?",
        "choices": ["Full-tunnel IPsec client", "A clientless VPN portal over HTTPS in the browser", "A site-to-site tunnel to the contractor's home", "Telnet through the firewall"],
        "answer": 1,
        "explain": "Clientless VPNs publish applications through a TLS web portal — nothing to install, no admin rights needed, works from unmanaged/BYOD devices. Access is limited to the published apps rather than placing the whole device on the network, which suits contractors well.",
    },
    {
        "type": "mc",
        "q": "Remote workers' video streaming is overwhelming the VPN concentrator. Security agrees only traffic to corporate subnets needs the VPN. What should be configured?",
        "choices": ["Full tunneling", "A second full tunnel", "Out-of-band management", "Split tunneling"],
        "answer": 3,
        "explain": "Split tunneling sends only corporate-destined traffic through the VPN while Internet traffic exits the user's local connection, unloading the concentrator and improving performance. The trade-off: that Internet traffic bypasses corporate inspection.",
    },
    {
        "type": "mc",
        "q": "Security policy requires that ALL remote-user traffic — including general web browsing — pass through the corporate firewall and content filter. Which VPN configuration enforces this?",
        "choices": ["Full tunnel", "Split tunnel", "Clientless portal", "Site-to-site only"],
        "answer": 0,
        "explain": "A full tunnel forces every packet from the client through the VPN and out the corporate security stack, giving maximum visibility and policy control at the cost of bandwidth and latency. Split tunneling would let Internet traffic bypass inspection.",
    },
    {
        "type": "mc",
        "q": "What is the main security trade-off of split tunneling?",
        "choices": ["Corporate traffic is sent unencrypted", "The user's Internet traffic is not inspected by corporate security controls", "It disables MFA", "It requires Telnet"],
        "answer": 1,
        "explain": "With split tunneling, only corporate-bound traffic is protected and inspected; the user's direct Internet traffic bypasses the corporate firewall, proxy, and filtering entirely while the device is simultaneously connected to the corporate network — a risk position security teams must accept consciously.",
    },
    {
        "type": "mc",
        "q": "Which protocol provides encrypted command-line management of a switch over the network, and on which port?",
        "choices": ["Telnet, TCP 23", "SSH, TCP 22", "SNMP, UDP 161", "RDP, TCP 3389"],
        "answer": 1,
        "explain": "SSH encrypts remote CLI sessions on TCP 22 and supports public-key authentication. Telnet (TCP 23) offers the same CLI but transmits everything — including passwords — in plaintext and should never be used.",
    },
    {
        "type": "mc",
        "q": "A packet capture of a technician's remote CLI session shows the login password in readable text. Which protocol was used, and what should replace it?",
        "choices": ["SSH; replace with Telnet", "SNMPv3; replace with SNMPv2c", "Telnet; replace with SSH", "HTTPS; replace with HTTP"],
        "answer": 2,
        "explain": "Plaintext credentials on a CLI session are the signature of Telnet (TCP 23). SSH (TCP 22) encrypts the entire session and adds key-based authentication — it is the standard secure replacement.",
    },
    {
        "type": "mc",
        "q": "Which SSH authentication method avoids sending any password and keeps the private credential off the wire entirely?",
        "choices": ["Community strings", "Public-key authentication with a key pair", "Basic HTTP authentication", "MD5 hashing of the password"],
        "answer": 1,
        "explain": "With SSH key pairs, the server holds the public key and the client proves possession of the private key cryptographically — the private key never crosses the network. It resists password guessing and enables safe automation.",
    },
    {
        "type": "mc",
        "q": "An admin manages a wireless LAN controller through its dashboard in a web browser. Which connection method is this, and how should it be secured?",
        "choices": ["API access, secured with SSH", "Console access, secured with a rollover cable", "GUI access, secured with HTTPS", "In-band capture, secured with SPAN"],
        "answer": 2,
        "explain": "Web dashboards are GUI management — approachable and visual, ideal for occasional administration. They must run over HTTPS, never HTTP, since plain HTTP would expose credentials and session data.",
    },
    {
        "type": "mc",
        "q": "The network team must push an identical configuration change to 500 switches tonight with no typos. Which management method is designed for this?",
        "choices": ["API automation using REST/JSON scripts", "Individual SSH sessions typed by hand", "The web GUI of each switch", "Console cables and a clipboard"],
        "answer": 0,
        "explain": "APIs (typically REST over HTTPS exchanging JSON) enable programmatic, repeatable changes at scale via scripts and orchestration tools like Ansible. Automation eliminates hand-typing errors and finishes in minutes what manual sessions would take days to do.",
    },
    {
        "type": "mc",
        "q": "A brand-new switch has no IP address configured. How must the technician perform the initial configuration?",
        "choices": ["SSH to its management VLAN", "Connect to its console port with a rollover cable and terminal emulator", "Browse to its HTTPS GUI", "Send a REST API call"],
        "answer": 1,
        "explain": "Every network-based method (SSH, GUI, API) requires the device to already have an IP address. The console (serial) port works with no network or IP at all — it is the method for initial setup and for recovery of misconfigured devices.",
    },
    {
        "type": "mc",
        "q": "Which cable is classically associated with connecting a laptop to a router's console port?",
        "choices": ["Crossover cable", "Fiber patch cable", "Coaxial cable", "Rollover cable"],
        "answer": 3,
        "explain": "Console access uses a rollover cable (traditionally RJ45-to-DB9 serial, now often USB variants) with a terminal emulator such as PuTTY, classically at 9600 baud. Crossover cables connect like devices' data ports; they are not console cables.",
    },
    {
        "type": "mc",
        "q": "Firewall rules allow SSH into the secure server VLAN from exactly one hardened, MFA-protected host, which records every admin session. What is this host called?",
        "choices": ["A VPN concentrator", "A syslog collector", "A jump box (jump host)", "A DHCP relay"],
        "answer": 2,
        "explain": "A jump box is a hardened intermediary that serves as the single controlled entry point into a protected segment. Concentrating access there reduces attack surface, enforces MFA at one choke point, and produces complete session logs for audit.",
    },
    {
        "type": "mc",
        "q": "Why do administrators connect through a jump box instead of directly from their daily workstations to sensitive servers?",
        "choices": ["Jump boxes make sessions faster", "Daily workstations face email/browsing malware risks, and the jump box isolates sensitive systems from them", "Jump boxes eliminate the need for authentication", "Direct SSH is not routable"],
        "answer": 1,
        "explain": "Admin workstations are exposed to phishing and drive-by malware. Forcing access through a hardened, monitored, minimal-purpose intermediary keeps that exposure away from sensitive systems and lets firewall rules restrict management traffic to one origin.",
    },
    {
        "type": "mc",
        "q": "What is the defining characteristic of in-band management?",
        "choices": ["It requires a serial cable", "Management traffic shares the same production network as user data", "It only works during outages", "It uses cellular modems"],
        "answer": 1,
        "explain": "In-band management (SSH, HTTPS, SNMP, API over production links) is convenient and cheap but shares fate with the network: when the network is down or misconfigured, so is your access to fix it. Best practice at minimum segregates it onto a management VLAN.",
    },
    {
        "type": "mc",
        "q": "A routing mistake isolates a remote site's router from the WAN, yet engineers still reach its CLI within minutes to fix it. Which capability made this possible?",
        "choices": ["Out-of-band management via a console server with cellular backup", "A full-tunnel VPN", "In-band SSH over the failed WAN link", "A DNS PTR record"],
        "answer": 0,
        "explain": "Out-of-band management provides a dedicated path — console server, separate management network, or cellular/analog backup — that does not depend on the production network, so it works precisely when the network is broken. In-band access would have failed with the WAN.",
    },
    {
        "type": "mc",
        "q": "Which option is an example of out-of-band management for servers?",
        "choices": ["RDP to the server's production IP", "SSH over the user VLAN", "A dedicated iDRAC/iLO lights-out port on a management network", "A REST API call to the application"],
        "answer": 2,
        "explain": "Lights-out interfaces (iDRAC, iLO, IPMI) are dedicated management processors with their own network ports, reachable even when the server OS is down — the server-world equivalent of a network console server. The other options all ride the production network (in-band).",
    },
    {
        "type": "mc",
        "q": "What is the main disadvantage of out-of-band management compared with in-band?",
        "choices": ["It stops working during outages", "It cannot use encryption", "Extra cost and infrastructure — separate network gear, console servers, or cellular circuits", "It requires split tunneling"],
        "answer": 2,
        "explain": "OOB's resilience costs money: dedicated management hardware, cabling, and backup circuits, plus the obligation to secure the OOB path itself (an unsecured OOB network is a backdoor). In-band is essentially free but fails together with the production network.",
    },
    {
        "type": "mc",
        "q": "Which access design BEST balances security for a PCI server segment: (choose the most complete answer)",
        "choices": ["Telnet from any admin PC", "Split tunneling for all servers", "GUI-only management over HTTP", "All admin sessions via a hardened jump box, with device console ports wired to an out-of-band console server"],
        "answer": 3,
        "explain": "Combining a jump box (single MFA-protected, logged entry point) with out-of-band console access (management that survives network failures) covers both security and availability. Telnet and HTTP are plaintext, and split tunneling is a remote-user traffic policy, not a segment-access control.",
    },
    # --- True/False (5) ---
    {
        "type": "tf",
        "q": "A site-to-site VPN requires each employee's computer to run VPN client software.",
        "answer": False,
        "explain": "Site-to-site tunnels terminate on the routers/firewalls at each site; the tunnel is transparent infrastructure and end devices need no client or login. Client software is a characteristic of client-to-site (remote access) VPNs.",
    },
    {
        "type": "tf",
        "q": "In a full-tunnel VPN configuration, even the user's ordinary web browsing traverses the corporate network.",
        "answer": True,
        "explain": "Full tunneling routes all client traffic through the VPN and out the corporate edge, so browsing is inspected by corporate security controls — at the cost of extra latency and concentrator/WAN load. Split tunneling would send it directly to the Internet instead.",
    },
    {
        "type": "tf",
        "q": "The console port can be used to manage a device even when the device has no IP configuration and the network is down.",
        "answer": True,
        "explain": "Console access is a direct physical serial connection — no network stack involved — which is why it serves for initial configuration of new devices and for recovery during outages. It is inherently out-of-band.",
    },
    {
        "type": "tf",
        "q": "A clientless VPN typically grants the remote device full network-layer access to every internal subnet.",
        "answer": False,
        "explain": "Clientless VPNs are browser portals: users reach the specific applications the portal publishes (web apps, file shares, browser-rendered RDP/SSH). Full network-layer access requires a tunnel client. The restriction is actually an advantage for BYOD and contractor scenarios.",
    },
    {
        "type": "tf",
        "q": "Because a jump box concentrates administrative access, it must itself be hardened, patched, MFA-protected, and monitored.",
        "answer": True,
        "explain": "The jump box holds the keys to the protected segment, making it a high-value target. Its concentration of access is only a security win if the box is rigorously hardened and its sessions logged — a compromised jump box would expose everything behind it.",
    },
    # --- Fill-in (5) ---
    {
        "type": "fill",
        "q": "SSH provides encrypted CLI management over TCP port ______. (type your answer)",
        "answers": ["22"],
        "explain": "SSH uses TCP 22 and fully encrypts the session, supporting password or public-key authentication. Its insecure predecessor Telnet uses TCP 23 and sends credentials in plaintext.",
    },
    {
        "type": "fill",
        "q": "The VPN mode in which only corporate-destined traffic uses the tunnel while Internet traffic exits locally is called ______ tunneling. (type your answer)",
        "answers": ["split"],
        "explain": "Split tunneling conserves VPN bandwidth and improves performance for personal traffic, but that traffic bypasses corporate inspection. Full tunneling is the opposite: everything through the VPN and the corporate security stack.",
    },
    {
        "type": "fill",
        "q": "The hardened intermediary host that is the single entry point for administering a secure network segment is called a ______ box. (type your answer)",
        "answers": ["jump", "jump host", "jumpbox"],
        "explain": "Administrators SSH/RDP to the jump box first, then onward into the protected segment; firewall rules admit management traffic only from it. It centralizes MFA, session recording, and access revocation at one choke point.",
    },
    {
        "type": "fill",
        "q": "Management that travels over a dedicated path separate from the production network — working even during outages — is called ______ management. (type your answer)",
        "answers": ["out-of-band", "out of band", "OOB", "OOBM"],
        "explain": "Out-of-band management uses dedicated management networks, console servers, or cellular backup links, so device access survives production failures. In-band management shares the production network and fails along with it.",
    },
    {
        "type": "fill",
        "q": "A remote-access VPN that needs only a web browser and a TLS portal — no installed software — is called a ______ VPN. (type your answer)",
        "answers": ["clientless", "client-less"],
        "explain": "Clientless VPNs publish internal applications through an HTTPS portal on the gateway. They work from unmanaged and BYOD devices with nothing to install, though access is limited to the published applications rather than the whole network.",
    },
    # --- Match (2) ---
    {
        "type": "match",
        "q": "Match each connection method to its distinguishing trait.",
        "pairs": [
            ["SSH", "Encrypted CLI on TCP 22 with key-based authentication"],
            ["GUI", "Visual management via an HTTPS web console"],
            ["API", "REST/JSON scripting for automation at scale"],
            ["Console", "Physical serial access needing no network or IP"],
        ],
        "explain": "The four connection methods trade convenience, power, and prerequisites: SSH for day-to-day secure CLI, GUI for visual administration, API for programmatic bulk changes, and the console for initial setup and recovery because it alone requires no working network.",
    },
    {
        "type": "match",
        "q": "Match each access scenario to the appropriate solution.",
        "pairs": [
            ["Permanently join branch and HQ networks", "Site-to-site VPN"],
            ["Traveling employee needs full internal access", "Client-to-site VPN"],
            ["Contractor's unmanaged tablet needs one web app", "Clientless VPN portal"],
            ["All remote traffic must be inspected at HQ", "Full tunnel"],
            ["Reach a router's CLI when the WAN is down", "Out-of-band console server"],
        ],
        "explain": "Objective 3.5 is scenario matching: who connects (networks vs. one user), what can be installed (client vs. browser only), where traffic must flow (full vs. split tunnel), and whether access must survive outages (out-of-band). The keywords in each scenario map directly to one method.",
    },
    # --- Order (2) ---
    {
        "type": "order",
        "q": "Arrange the steps an administrator follows to securely configure a server inside a protected segment via a jump box.",
        "items": [
            "Authenticate to the VPN from the remote laptop",
            "SSH to the jump box and complete MFA",
            "From the jump box, SSH to the target server in the secure segment",
            "Perform the configuration change",
            "Log out so the recorded session closes",
        ],
        "explain": "Access flows outward-in: first the VPN establishes the encrypted path into the corporate network, then the jump box — the only host allowed into the secure segment — is reached with MFA, and only from it does the admin touch the target. Session recording on the jump box captures the whole trail for audit.",
    },
    {
        "type": "order",
        "q": "Arrange the bring-up steps for a brand-new router, from first power-on to automated management.",
        "items": [
            "Connect via console rollover cable and terminal emulator",
            "Configure a management IP address and enable SSH",
            "Manage the device over the network via SSH",
            "Onboard the device into API-driven automation",
        ],
        "explain": "A new device has no IP, so only the console works at first. Once a management address and SSH are configured, network-based CLI management takes over, and finally the device can be enrolled in API/automation platforms for bulk, repeatable changes — the natural maturity path of device management.",
    },
]
