TOPIC = {
    "id": "4.1",
    "domain": 4,
    "title": "Explain the importance of basic network security concepts",
    "short": "Security Concepts",
}

TERMS = [
    ("Data in transit", "Data actively moving across a network; protected with TLS, IPSec, or SSH"),
    ("Data at rest", "Data stored on disks, databases, or backups; protected with encryption such as AES full-disk encryption"),
    ("TLS", "Transport Layer Security; encrypts application traffic in transit (e.g., HTTPS) and authenticates servers with certificates"),
    ("IPSec", "Layer 3 protocol suite that encrypts and authenticates IP packets, commonly used for VPN tunnels"),
    ("PKI", "Public key infrastructure; the system of CAs, certificates, and policies that binds public keys to identities"),
    ("Certificate Authority (CA)", "Trusted entity that validates identities and digitally signs certificates"),
    ("CSR", "Certificate Signing Request; the public key plus identity info submitted to a CA to obtain a certificate"),
    ("Self-signed certificate", "Certificate signed by its own creator rather than a trusted CA; triggers browser trust warnings"),
    ("IAM", "Identity and access management; framework covering provisioning, authentication, authorization, and deprovisioning"),
    ("MFA", "Multifactor authentication; requires proofs from two or more different factor categories (know/have/are/somewhere you are)"),
    ("SSO", "Single sign-on; authenticate once to access multiple applications without re-entering credentials"),
    ("RADIUS", "AAA protocol over UDP 1812/1813 that encrypts only the password field; used for network access such as Wi-Fi, VPN, and 802.1X"),
    ("TACACS+", "AAA protocol over TCP 49 that encrypts the entire payload and separates AAA; used for network device administration"),
    ("LDAP", "Protocol for querying directory services such as Active Directory; TCP 389, or TCP 636 for LDAPS"),
    ("SAML", "XML-based standard for federated identity and web SSO between an identity provider and a service provider"),
    ("TOTP", "Time-based one-time password; short-lived code (typically 30 seconds) generated from a shared secret plus the current time"),
    ("Least privilege", "Granting users and processes only the minimum access required to perform their job"),
    ("Role-based access control", "Assigning permissions to roles based on job function, then assigning users to those roles"),
    ("Geofencing", "Virtual geographic boundary that triggers or restricts actions based on a device's location"),
    ("Honeypot", "Decoy system designed to attract attackers so their methods can be observed safely away from production"),
    ("Honeynet", "An entire network of honeypots simulating a realistic environment to study attacker behavior"),
    ("Vulnerability", "A weakness in a system, configuration, or process that could be exploited"),
    ("Exploit", "The method, technique, or code that takes advantage of a vulnerability"),
    ("Threat", "A potential actor or event that could cause harm to systems or data"),
    ("Risk", "The potential for loss, commonly expressed as likelihood times impact"),
    ("CIA triad", "Confidentiality, Integrity, and Availability; the three core goals of security"),
    ("Data locality", "Requirement that data is subject to (and may need to stay within) the laws of the region where it resides"),
    ("PCI DSS", "Payment Card Industry Data Security Standard; contractual rules for anyone storing, processing, or transmitting card data"),
    ("GDPR", "EU regulation protecting personal data of people in the EU, with 72-hour breach notification and heavy fines"),
    ("SCADA", "Supervisory control and data acquisition; ICS architecture for monitoring large-scale industrial processes"),
]

QUESTIONS = [
    # ---------------- Multiple choice ----------------
    {
        "type": "mc",
        "q": "A company emails unencrypted spreadsheets of customer data between offices but encrypts every laptop drive with AES full-disk encryption. Which statement is accurate?",
        "choices": [
            "The data is fully protected because it is encrypted at rest",
            "Data at rest is protected, but data in transit is exposed",
            "Data in transit is protected, but data at rest is exposed",
            "Full-disk encryption also protects files while they are emailed",
        ],
        "answer": 1,
        "explain": "Encryption at rest (full-disk AES) only protects stored data on the laptops. Once a file is sent over the network in cleartext email, it is unprotected data in transit. Both states need their own controls: TLS/IPSec/SSH for transit, disk/database encryption for rest.",
    },
    {
        "type": "mc",
        "q": "Which protocol pair correctly matches 'data in transit' protections?",
        "choices": [
            "TLS and IPSec",
            "AES full-disk encryption and BitLocker",
            "RAID and backups",
            "Hashing and RBAC",
        ],
        "answer": 0,
        "explain": "TLS secures application traffic (like HTTPS) and IPSec secures IP packets in VPN tunnels — both protect data moving across the network. Full-disk encryption protects data at rest, RAID/backups address availability, and hashing/RBAC address integrity and authorization.",
    },
    {
        "type": "mc",
        "q": "In PKI, what is submitted to a Certificate Authority to request a new certificate?",
        "choices": [
            "The server's private key",
            "A certificate revocation list",
            "A certificate signing request (CSR)",
            "An OCSP response",
        ],
        "answer": 2,
        "explain": "The requester generates a key pair and sends a CSR containing the public key and identity information to the CA, which validates the identity and signs the certificate. The private key never leaves the requester — sending it anywhere would compromise the whole system.",
    },
    {
        "type": "mc",
        "q": "A browser trusts a web server's certificate it has never seen before. What makes this possible?",
        "choices": [
            "The server's certificate is stored in the browser's cache",
            "The chain of trust: the cert is signed by an intermediate CA, which is signed by a root CA in the browser's trust store",
            "The certificate is self-signed by the web server",
            "The browser queried the DNS server for the certificate",
        ],
        "answer": 1,
        "explain": "Clients validate certificates by following signatures up the chain of trust — server cert to intermediate CA to a root CA whose certificate is pre-installed in the OS/browser trust store. This lets a browser trust millions of sites while only shipping a small set of trusted roots.",
    },
    {
        "type": "mc",
        "q": "A developer secures an internal test server with a self-signed certificate. What will users' browsers do when connecting?",
        "choices": [
            "Display a trust warning because no trusted CA vouches for the certificate",
            "Refuse the connection because self-signed certificates cannot encrypt traffic",
            "Accept it silently because internal addresses are exempt from validation",
            "Automatically forward the certificate to a public CA for signing",
        ],
        "answer": 0,
        "explain": "A self-signed certificate can encrypt just as strongly as a CA-signed one, but no trusted third party vouches for the identity, so browsers show a trust warning. Self-signed certs are acceptable for internal/test systems where the cert can be manually installed in trust stores.",
    },
    {
        "type": "mc",
        "q": "Which combination is a true example of multifactor authentication?",
        "choices": [
            "Password plus a PIN",
            "Password plus security questions",
            "Fingerprint plus iris scan",
            "Password plus a code from an authenticator app",
        ],
        "answer": 3,
        "explain": "MFA requires factors from different categories. A password (something you know) plus a TOTP code from an app on your phone (something you have) is two categories. Password+PIN and password+security questions are both knowledge-only; fingerprint+iris are both biometric (something you are).",
    },
    {
        "type": "mc",
        "q": "Blocking logins that originate from outside the country is an example of which authentication factor?",
        "choices": [
            "Something you know",
            "Somewhere you are",
            "Something you have",
            "Something you are",
        ],
        "answer": 1,
        "explain": "Location-based restrictions (IP geolocation, GPS, geofencing) are the 'somewhere you are' factor. They are often combined with other factors in conditional access policies — e.g., require additional verification when a login comes from an unusual location.",
    },
    {
        "type": "mc",
        "q": "Which protocol uses UDP ports 1812 and 1813 and encrypts only the password field of the access request?",
        "choices": [
            "TACACS+",
            "LDAP",
            "RADIUS",
            "Kerberos",
        ],
        "answer": 2,
        "explain": "RADIUS uses UDP 1812 for authentication/authorization and 1813 for accounting, and it encrypts only the user's password — the rest of the packet is cleartext. TACACS+ uses TCP 49 and encrypts the entire payload; LDAP is a directory protocol on TCP 389/636.",
    },
    {
        "type": "mc",
        "q": "A network team wants centralized control over exactly which IOS commands each administrator can run on routers, with the entire authentication payload encrypted. Which protocol best fits?",
        "choices": [
            "RADIUS",
            "TACACS+",
            "SAML",
            "SNMPv3",
        ],
        "answer": 1,
        "explain": "TACACS+ separates authentication, authorization, and accounting, which enables per-command authorization, and it encrypts the entire packet payload over TCP 49. It is the standard choice for network device administration; RADIUS combines auth+authorization and targets network access.",
    },
    {
        "type": "mc",
        "q": "Which is a key difference between RADIUS and TACACS+?",
        "choices": [
            "RADIUS uses TCP while TACACS+ uses UDP",
            "TACACS+ encrypts only the password while RADIUS encrypts the full payload",
            "RADIUS separates AAA functions while TACACS+ combines them",
            "RADIUS combines authentication and authorization while TACACS+ separates all three AAA functions",
        ],
        "answer": 3,
        "explain": "RADIUS (UDP 1812/1813) combines authentication and authorization into one exchange and encrypts only the password. TACACS+ (TCP 49) separates authentication, authorization, and accounting and encrypts the whole payload. The other options state the differences backwards.",
    },
    {
        "type": "mc",
        "q": "Which port is used by LDAPS (LDAP over SSL/TLS)?",
        "choices": [
            "TCP 636",
            "TCP 389",
            "TCP 49",
            "UDP 1812",
        ],
        "answer": 0,
        "explain": "Plain LDAP uses TCP 389 and LDAPS uses TCP 636. LDAP queries directory services such as Active Directory; the secure variant matters because plain LDAP binds can expose credentials on the wire.",
    },
    {
        "type": "mc",
        "q": "In SAML-based federation, which component authenticates the user and issues signed assertions?",
        "choices": [
            "The service provider (SP)",
            "The certificate authority (CA)",
            "The identity provider (IdP)",
            "The RADIUS accounting server",
        ],
        "answer": 2,
        "explain": "The identity provider (IdP) authenticates the user and issues a signed XML assertion; the service provider (the application) trusts and consumes that assertion to grant access. The SP never sees the user's password — that is the core benefit of federation.",
    },
    {
        "type": "mc",
        "q": "An employee authenticates once in the morning and can then open email, the HR portal, and a CRM without logging in again. What is this called?",
        "choices": [
            "Least privilege",
            "Single sign-on (SSO)",
            "Role-based access control",
            "Multifactor authentication",
        ],
        "answer": 1,
        "explain": "Single sign-on lets one authentication event grant access to multiple applications, commonly implemented with SAML, Kerberos, or OIDC. Because the SSO credential becomes a single point of compromise, it should be protected with MFA.",
    },
    {
        "type": "mc",
        "q": "A user's authenticator app displays a 6-digit code that changes every 30 seconds. What is being used?",
        "choices": [
            "HOTP (counter-based one-time password)",
            "A SAML assertion",
            "A digital certificate",
            "TOTP (time-based one-time password)",
        ],
        "answer": 3,
        "explain": "TOTP generates codes from a shared secret plus the current time, typically rotating every 30 seconds, so stolen codes expire almost instantly. HOTP is counter-based and does not expire on a timer. TOTP requires reasonably synchronized clocks between client and server.",
    },
    {
        "type": "mc",
        "q": "A database administrator's account can also modify firewall rules and payroll records, none of which are part of the DBA job. Which principle is being violated?",
        "choices": [
            "Least privilege",
            "Separation of trust zones",
            "Data locality",
            "Non-repudiation",
        ],
        "answer": 0,
        "explain": "Least privilege says every account gets only the minimum access needed for its job. Excess permissions expand the blast radius if the account is compromised or misused. The fix is to strip unneeded rights, typically by moving to role-based access control.",
    },
    {
        "type": "mc",
        "q": "New hires in the accounting department automatically receive the same set of permissions by being added to an 'Accounting' group. Which access control model is this?",
        "choices": [
            "Discretionary access control",
            "Role-based access control (RBAC)",
            "Mandatory access control",
            "Rule-based access control using ACLs",
        ],
        "answer": 1,
        "explain": "RBAC assigns permissions to roles based on job function and then assigns users to roles. It scales cleanly, keeps access consistent, and makes deprovisioning easy (remove the user from the role) — it is how organizations implement least privilege at scale.",
    },
    {
        "type": "mc",
        "q": "Which pairing of deception technologies is correct?",
        "choices": [
            "Honeypot = fake credentials file; honeynet = fake DNS record",
            "Honeypot = decoy network; honeynet = single decoy server",
            "Honeypot = single decoy system; honeynet = an entire network of decoy systems",
            "Honeypot = quarantine VLAN; honeynet = screened subnet",
        ],
        "answer": 2,
        "explain": "A honeypot is one decoy system made to look like a legitimate target; a honeynet is a whole network of honeypots simulating a realistic environment. Because they serve no production purpose, any interaction with them is a high-confidence indicator of attack.",
    },
    {
        "type": "mc",
        "q": "Why do honeypots produce such high-quality security alerts?",
        "choices": [
            "They run the most advanced intrusion prevention signatures",
            "They automatically patch themselves against new exploits",
            "They encrypt all traffic that touches them",
            "No legitimate user has any reason to touch them, so any interaction is suspicious",
        ],
        "answer": 3,
        "explain": "A honeypot has no production function, so essentially all traffic to it is scanning or attack activity — near-zero false positives. Defenders also use honeypots to study attacker tools and techniques while keeping them away from real assets.",
    },
    {
        "type": "mc",
        "q": "An unpatched web server is targeted by a criminal group using publicly available attack code. In this scenario, what is the EXPLOIT?",
        "choices": [
            "The unpatched flaw in the web server",
            "The attack code that leverages the flaw",
            "The criminal group",
            "The potential financial loss to the company",
        ],
        "answer": 1,
        "explain": "The exploit is the method or code that takes advantage of a vulnerability. Here the unpatched flaw is the vulnerability, the criminal group is the threat, and the potential for loss (likelihood x impact) is the risk. Keep the four terms straight — the exam tests them nearly verbatim.",
    },
    {
        "type": "mc",
        "q": "Risk is best defined as:",
        "choices": [
            "Any weakness in a system or process",
            "Any actor with intent to cause harm",
            "The likelihood of a threat exploiting a vulnerability multiplied by the impact",
            "The specific code used to attack a system",
        ],
        "answer": 2,
        "explain": "Risk is the potential for loss, commonly modeled as likelihood x impact of a threat exploiting a vulnerability. Removing the vulnerability (patching) or reducing exposure lowers risk even though threats continue to exist.",
    },
    {
        "type": "mc",
        "q": "Ransomware encrypts a hospital's patient records so staff cannot access them. Which CIA principle is PRIMARILY violated?",
        "choices": [
            "Availability",
            "Confidentiality",
            "Integrity",
            "Authentication",
        ],
        "answer": 0,
        "explain": "The defining harm of ransomware is that legitimate users can no longer access their own data — an availability violation. If the attackers also exfiltrate data (double extortion), confidentiality is violated too, but availability is the primary answer the exam expects.",
    },
    {
        "type": "mc",
        "q": "An attacker captures cleartext passwords by sniffing traffic on an unencrypted network. Which CIA principle is violated?",
        "choices": [
            "Integrity",
            "Confidentiality",
            "Availability",
            "Accountability",
        ],
        "answer": 1,
        "explain": "Eavesdropping/sniffing exposes data to an unauthorized party — a confidentiality violation. Tampering with data would violate integrity; taking a service offline would violate availability. Map attack effects to CIA principles: read = C, alter = I, deny = A.",
    },
    {
        "type": "mc",
        "q": "A retailer that stores, processes, and transmits credit card data must comply with which standard?",
        "choices": [
            "GDPR",
            "SCADA",
            "SAML",
            "PCI DSS",
        ],
        "answer": 3,
        "explain": "PCI DSS is the contractual industry standard for anyone handling payment card data. Network-relevant requirements include segmenting the cardholder data environment, encrypting card data, access control, and regular testing. GDPR concerns EU personal data privacy, not card handling specifically.",
    },
    {
        "type": "mc",
        "q": "A US company collects personal data from customers in Germany. Which regulation applies to that data, and what is one of its notable requirements?",
        "choices": [
            "PCI DSS; quarterly vulnerability scans",
            "GDPR; breach notification to authorities within 72 hours",
            "Data locality; encrypting all backups",
            "SOX; annual financial audits",
        ],
        "answer": 1,
        "explain": "GDPR protects personal data of people in the EU and applies to any organization worldwide that processes it. Notable requirements include lawful basis for processing, data-subject rights like erasure, 72-hour breach notification, and fines up to 4% of global annual revenue.",
    },
    {
        "type": "mc",
        "q": "A cloud architect must ensure certain records are stored only in data centers within the country where they were collected, per national law. Which concept is this?",
        "choices": [
            "Data locality (data residency/sovereignty)",
            "Least privilege",
            "Key escrow",
            "Geofencing",
        ],
        "answer": 0,
        "explain": "Data locality/residency means data is subject to the laws of the jurisdiction where it is collected or stored, and some laws require it to remain within specific borders. It drives cloud region selection and replication policies. Geofencing restricts device/user actions by location, not data storage location.",
    },
    {
        "type": "mc",
        "q": "Why should SCADA/ICS/OT systems be strictly segmented from the corporate IT network?",
        "choices": [
            "They generate too much broadcast traffic for office switches",
            "They require IPv6, which corporate networks rarely support",
            "They often run legacy, unpatchable software and a compromise can cause physical damage or safety incidents",
            "They must be directly reachable from the Internet for vendor support",
        ],
        "answer": 2,
        "explain": "OT/ICS/SCADA equipment commonly runs legacy software that cannot be patched without unacceptable downtime, and compromise can damage physical processes or endanger safety. Since the vulnerabilities cannot be removed, exposure must be — through strict segmentation or near-isolation with controlled gateways.",
    },
    {
        "type": "mc",
        "q": "A company deploys dozens of smart cameras and sensors. What is the BEST network design decision for them?",
        "choices": [
            "Place them on the server VLAN so they are easy to monitor",
            "Place them on a dedicated, firewalled IoT VLAN isolated from internal resources",
            "Give them public IP addresses so they can be managed remotely",
            "Connect them to the guest Wi-Fi so visitors can view them",
        ],
        "answer": 1,
        "explain": "IoT devices are notorious for default credentials, weak or absent patching, and long service lives, and they cannot run endpoint agents. Isolating them on their own segment ensures a compromised camera cannot pivot to file servers — and limits their usefulness to botnets.",
    },
    {
        "type": "mc",
        "q": "A mobile device management policy allows corporate email access only while a phone is physically on the campus, verified by GPS. Which technology enforces this?",
        "choices": [
            "Key escrow",
            "Content filtering",
            "Geofencing",
            "Single sign-on",
        ],
        "answer": 2,
        "explain": "Geofencing draws a virtual geographic boundary using GPS, Wi-Fi, cell, or IP geolocation and applies policy based on whether the device is inside or outside it. It supplies the 'somewhere you are' factor and is common in MDM and conditional access.",
    },
    {
        "type": "mc",
        "q": "Visitors at headquarters need Internet access, and employees increasingly use personal laptops for work. What is the BEST design to protect internal resources?",
        "choices": [
            "Give visitors and BYOD devices access to the corporate VLAN with strong Wi-Fi passwords",
            "Place guests on an isolated guest network and BYOD devices on their own segment with NAC posture checks",
            "Block all wireless access company-wide",
            "Require visitors to plug into spare switch ports at empty desks",
        ],
        "answer": 1,
        "explain": "Guest networks provide Internet-only access with no route to internal resources, and BYOD devices — which the company does not fully patch or control — belong on their own segment gated by NAC/MDM posture checks. The theme: untrusted or unmanaged devices never share the trusted segment.",
    },
    {
        "type": "mc",
        "q": "Which physical security control is classified as preventive rather than detective?",
        "choices": [
            "A badge-controlled electronic door lock",
            "A CCTV camera recording the server room",
            "A motion-detection alert from a surveillance system",
            "A log review of door-access events",
        ],
        "answer": 0,
        "explain": "Locks physically stop unauthorized entry, making them preventive. Cameras and their alerts primarily record and detect (with some deterrent value), and log reviews detect after the fact. Electronic/badge locks add auditability and instant revocation over traditional keys.",
    },
    # ---------------- True/False ----------------
    {
        "type": "tf",
        "q": "A password combined with answers to security questions qualifies as multifactor authentication.",
        "answer": False,
        "explain": "Both are 'something you know,' so this is two proofs from a single factor category — still single-factor. MFA requires different categories, such as a password (know) plus a hardware token or authenticator app (have) or a fingerprint (are).",
    },
    {
        "type": "tf",
        "q": "RADIUS encrypts only the password field of the access-request packet, leaving other attributes in cleartext.",
        "answer": True,
        "explain": "This is a core RADIUS weakness and a favorite exam discriminator: only the password is obfuscated, while the username and other attributes travel in cleartext. TACACS+ encrypts the entire packet payload, which is one reason it is preferred for device administration.",
    },
    {
        "type": "tf",
        "q": "A self-signed certificate provides weaker encryption than a CA-signed certificate.",
        "answer": False,
        "explain": "The cryptography can be identical — the difference is trust, not strength. With no third party vouching for the identity, clients cannot distinguish a legitimate self-signed certificate from an attacker's, which is why browsers display trust warnings.",
    },
    {
        "type": "tf",
        "q": "Promptly deprovisioning accounts when employees leave is part of the IAM lifecycle.",
        "answer": True,
        "explain": "The IAM lifecycle runs provisioning, ongoing management, and deprovisioning. Orphaned accounts of former employees are a major attack vector and a classic audit finding, so access should be disabled immediately upon separation — easiest when access is role-based.",
    },
    {
        "type": "tf",
        "q": "Security cameras are a preventive control that physically stops intruders from entering a room.",
        "answer": False,
        "explain": "Cameras are primarily detective controls (recording evidence) with a deterrent effect — they do not physically block entry. Locks, access control vestibules, and turnstiles are the preventive physical controls that actually stop entry.",
    },
    {
        "type": "tf",
        "q": "GDPR can apply to a company with no offices in Europe.",
        "answer": True,
        "explain": "GDPR protects the personal data of people in the EU regardless of where the processing organization is located. Any company worldwide that offers goods/services to or monitors people in the EU falls under it, with fines up to 4% of global annual revenue.",
    },
    # ---------------- Fill-in ----------------
    {
        "type": "fill",
        "q": "TACACS+ uses TCP port ____ for all AAA communication. (type the number)",
        "answers": ["49"],
        "explain": "TACACS+ runs over TCP port 49, giving it reliable delivery. Pair this with its other discriminators: it encrypts the entire payload and separates authentication, authorization, and accounting — ideal for per-command control of device administrators.",
    },
    {
        "type": "fill",
        "q": "RADIUS authentication uses UDP port ____. (type the number)",
        "answers": ["1812"],
        "explain": "RADIUS uses UDP 1812 for authentication/authorization and UDP 1813 for accounting (legacy deployments used 1645/1646). Remember: RADIUS = UDP, network access, password-only encryption; TACACS+ = TCP 49, device admin, full-payload encryption.",
    },
    {
        "type": "fill",
        "q": "The XML-based standard that enables web single sign-on between an identity provider and a service provider is ____. (type the acronym)",
        "answers": ["SAML", "Security Assertion Markup Language"],
        "explain": "SAML (Security Assertion Markup Language) exchanges signed XML assertions: the IdP authenticates the user and the SP consumes the assertion to grant access without ever seeing the password. Keywords: XML, federation, IdP/SP, web SSO.",
    },
    {
        "type": "fill",
        "q": "A decoy system deployed to attract attackers and observe their techniques is called a ____.",
        "answers": ["honeypot", "honey pot"],
        "explain": "A honeypot mimics a legitimate, vulnerable target but has no production purpose, so any interaction is a high-confidence sign of hostile activity. A network of them is a honeynet, which reveals lateral-movement behavior as well.",
    },
    {
        "type": "fill",
        "q": "A weakness in a system, configuration, or process that could be taken advantage of is called a ____.",
        "answers": ["vulnerability", "weakness"],
        "explain": "A vulnerability is the weakness itself — an unpatched flaw, default password, or open port. The exploit is the method used against it, the threat is the actor or event, and risk is the resulting potential for loss (likelihood x impact).",
    },
    {
        "type": "fill",
        "q": "The 'A' in the CIA triad, which is violated by a DDoS attack, stands for ____.",
        "answers": ["availability"],
        "explain": "Availability means systems and data are accessible when needed; DoS/DDoS and ransomware attack it directly. Confidentiality is violated by eavesdropping and data theft; integrity by unauthorized modification. Map every attack to the principle it primarily harms.",
    },
    # ---------------- Match ----------------
    {
        "type": "match",
        "q": "Match each authentication protocol to its distinguishing characteristic.",
        "pairs": [
            ["RADIUS", "UDP 1812/1813; encrypts only the password; network access AAA"],
            ["TACACS+", "TCP 49; encrypts entire payload; device administration AAA"],
            ["LDAP", "Directory service queries on TCP 389 (636 secured)"],
            ["SAML", "XML assertions between identity provider and service provider"],
            ["TOTP", "Time-based one-time codes that expire roughly every 30 seconds"],
        ],
        "explain": "These five discriminators cover the most-tested facts in objective 4.1. RADIUS vs TACACS+ differ on transport, encryption scope, AAA separation, and use case; LDAP is the directory lookup protocol; SAML federates web SSO; TOTP adds the time-based possession factor.",
    },
    {
        "type": "match",
        "q": "Match each authentication factor category to its example.",
        "pairs": [
            ["Something you know", "Password or PIN"],
            ["Something you have", "Smart card or authenticator app"],
            ["Something you are", "Fingerprint or iris scan"],
            ["Somewhere you are", "Login allowed only from inside a geofenced campus"],
        ],
        "explain": "MFA requires proofs from two or more different categories. Knowledge factors are things you memorize, possession factors are objects/devices you carry, inherence factors are biometrics, and location factors use GPS or network origin.",
    },
    {
        "type": "match",
        "q": "Match each security term to its definition.",
        "pairs": [
            ["Vulnerability", "A weakness that could be taken advantage of"],
            ["Exploit", "The method or code that leverages a weakness"],
            ["Threat", "An actor or event with potential to cause harm"],
            ["Risk", "Potential for loss: likelihood times impact"],
        ],
        "explain": "Chain them into a sentence: a threat uses an exploit against a vulnerability, and the resulting potential for loss is the risk. Patching removes the vulnerability, which lowers risk even though threats still exist.",
    },
    # ---------------- Order ----------------
    {
        "type": "order",
        "q": "Arrange the steps of obtaining and using a CA-signed certificate in the correct order.",
        "items": [
            "Generate a public/private key pair on the server",
            "Submit a certificate signing request (CSR) to the CA",
            "CA validates the identity and signs the certificate",
            "Install the signed certificate on the server",
            "Clients validate it via the chain of trust to a root CA",
        ],
        "explain": "The requester generates the key pair locally (the private key never leaves), sends the CSR with the public key and identity info, and the CA verifies and signs. Once installed, clients trust the certificate by following the signature chain up to a root CA in their trust store.",
    },
    {
        "type": "order",
        "q": "Arrange the identity and access management lifecycle stages in order for a single employee, from hire to departure.",
        "items": [
            "Provision the account and grant role-based access",
            "Authenticate at each login (MFA)",
            "Authorize actions per least privilege",
            "Audit and log activity (accounting)",
            "Deprovision the account upon separation",
        ],
        "explain": "IAM spans the whole identity lifecycle: create access when the user joins, then continuously authenticate, authorize, and audit during employment, and promptly remove access at separation. Delayed deprovisioning leaves orphaned accounts — a top audit finding and attack vector.",
    },
]
