TOPIC = {
    "id": "4.2",
    "domain": 4,
    "title": "Summarize various types of attacks and their impact to the network",
    "short": "Attacks",
}

TERMS = [
    ("DoS attack", "Denial of service; overwhelming a system or network from a single source so legitimate users cannot use it"),
    ("DDoS attack", "Distributed denial of service; a DoS launched simultaneously from many sources, typically a botnet"),
    ("Botnet", "A network of malware-compromised devices (bots/zombies) remotely controlled by an attacker to launch attacks like DDoS"),
    ("Volumetric attack", "DDoS category that saturates the victim's raw bandwidth with floods of traffic"),
    ("Protocol attack", "DDoS category that exhausts connection-state resources, e.g., a SYN flood of half-open TCP connections"),
    ("Application-layer attack", "DDoS category using seemingly legitimate Layer 7 requests to exhaust server application resources"),
    ("Reflection/amplification", "Sending small spoofed queries (victim's IP as source) to servers whose large responses flood the victim"),
    ("VLAN hopping", "Gaining access to traffic on a VLAN the attacker is not assigned to, via switch spoofing or double tagging"),
    ("Switch spoofing", "VLAN hopping technique where the attacker negotiates a trunk link using DTP to receive all VLANs"),
    ("Double tagging", "VLAN hopping technique using two 802.1Q tags; the first switch strips the outer native-VLAN tag"),
    ("MAC flooding", "Overflowing a switch's CAM table with bogus source MACs so it floods frames out all ports like a hub"),
    ("ARP spoofing", "Sending forged ARP replies that claim the attacker's MAC belongs to another host's IP address"),
    ("ARP poisoning", "The corrupted state where victims' ARP caches hold falsified IP-to-MAC mappings, redirecting their traffic"),
    ("DNS poisoning", "Inserting false records into a DNS resolver's cache so every client using it gets malicious answers"),
    ("DNS spoofing", "Supplying forged DNS responses so victims resolve names to attacker-controlled addresses"),
    ("Rogue DHCP server", "Unauthorized DHCP server handing out malicious gateway/DNS settings or bogus addresses"),
    ("Rogue AP", "Unauthorized wireless access point attached to the wired network, creating an uncontrolled entry point"),
    ("Evil twin", "Attacker-controlled AP broadcasting the same SSID as a legitimate network to lure clients and harvest data"),
    ("On-path attack", "Attacker secretly positioned between two parties, relaying and possibly altering their traffic (formerly MITM)"),
    ("Phishing", "Fraudulent communication impersonating a trusted entity to steal credentials or deliver malware"),
    ("Spear phishing", "Phishing targeted at a specific person or organization using personalized, researched details"),
    ("Whaling", "Spear phishing aimed at executives or other high-value targets"),
    ("Vishing", "Phishing conducted over voice calls, often with spoofed caller ID"),
    ("Smishing", "Phishing conducted via SMS text messages"),
    ("Dumpster diving", "Searching an organization's trash for documents, media, or notes containing useful information"),
    ("Shoulder surfing", "Observing someone's screen or keyboard to capture passwords or sensitive data"),
    ("Tailgating", "Following an authorized person through a secured door without presenting credentials"),
    ("Virus", "Malware that attaches to files or programs and requires user action to execute and spread"),
    ("Worm", "Malware that self-replicates across the network without user interaction"),
    ("Trojan", "Malware disguised as legitimate software that the user installs voluntarily, often opening a backdoor"),
    ("Ransomware", "Malware that encrypts data and demands payment, primarily attacking availability"),
]

QUESTIONS = [
    # ---------------- Multiple choice ----------------
    {
        "type": "mc",
        "q": "What is the key difference between a DoS and a DDoS attack?",
        "choices": [
            "DoS targets Layer 2 while DDoS targets Layer 3",
            "DDoS comes from many distributed sources (a botnet) while DoS comes from a single source",
            "DoS encrypts data while DDoS deletes it",
            "DDoS only affects wireless networks",
        ],
        "answer": 1,
        "explain": "Both aim to make a service unavailable, but a DDoS is launched simultaneously from many compromised machines (a botnet), making it far harder to filter and capable of enormous aggregate bandwidth. You cannot stop a DDoS by blocking one source IP.",
    },
    {
        "type": "mc",
        "q": "A server's TCP connection table is exhausted by thousands of half-open connections that never complete the three-way handshake. Which attack is this, and what category is it?",
        "choices": [
            "SYN flood; a protocol attack",
            "HTTP flood; an application-layer attack",
            "UDP flood; a volumetric attack",
            "Slowloris; a volumetric attack",
        ],
        "answer": 0,
        "explain": "A SYN flood sends endless SYNs (often from spoofed sources) and never completes the handshake, filling the connection backlog — the classic protocol-category DoS that exhausts state rather than bandwidth. Volumetric attacks saturate links; application-layer attacks exhaust server software resources.",
    },
    {
        "type": "mc",
        "q": "An attacker sends small DNS queries to many open resolvers with the source IP spoofed to the victim's address, and the resolvers' large responses crush the victim. What is this technique called?",
        "choices": [
            "DNS cache poisoning",
            "A reflection/amplification attack",
            "An evil twin attack",
            "VLAN hopping",
        ],
        "answer": 1,
        "explain": "Reflection uses spoofed source addresses so third-party servers send their replies to the victim; amplification adds leverage by choosing protocols (DNS, NTP, memcached) whose responses are much larger than the requests. It is a volumetric DDoS technique — not a corruption of DNS records.",
    },
    {
        "type": "mc",
        "q": "Compromised IoT devices with unchanged default passwords are most likely to be recruited into which attack infrastructure?",
        "choices": [
            "A certificate authority",
            "A honeynet",
            "A botnet used for DDoS attacks",
            "A screened subnet",
        ],
        "answer": 2,
        "explain": "Botnets like Mirai were built largely from IoT devices still using factory default credentials. The enrolled bots are then commanded to flood victims in DDoS attacks or send spam — one big reason IoT belongs on its own segmented VLAN with changed credentials.",
    },
    {
        "type": "mc",
        "q": "An attacker's laptop negotiates a trunk link with a switch by speaking DTP, then receives traffic from every VLAN. Which attack is this?",
        "choices": [
            "Double tagging",
            "MAC flooding",
            "ARP poisoning",
            "VLAN hopping via switch spoofing",
        ],
        "answer": 3,
        "explain": "Switch spoofing abuses Dynamic Trunking Protocol auto-negotiation: if the port is in a dynamic mode, the attacker's device can form a trunk, which carries all VLANs. Mitigate by disabling DTP, statically configuring access ports, and shutting unused ports.",
    },
    {
        "type": "mc",
        "q": "In a double-tagging VLAN hopping attack, why does the frame reach the victim VLAN?",
        "choices": [
            "The first switch strips the outer tag (native VLAN) and forwards the frame with the inner tag intact",
            "The attacker overwrote the switch's VLAN database",
            "The trunk port broadcast the frame to all VLANs",
            "The switch mistook the frame for a routing update",
        ],
        "answer": 0,
        "explain": "The attacker stacks two 802.1Q tags. The first switch removes the outer tag because it matches the native VLAN (sent untagged on trunks), then forwards the frame still carrying the inner tag, which the next switch obeys. Mitigations: use an unused native VLAN (not VLAN 1) and keep access ports off it.",
    },
    {
        "type": "mc",
        "q": "Which two configuration practices mitigate VLAN hopping?",
        "choices": [
            "Enable DTP everywhere and use VLAN 1 as native",
            "Disable DTP/trunk auto-negotiation and set the native VLAN to an unused VLAN ID",
            "Enable jumbo frames and port mirroring",
            "Use DHCP snooping and DNSSEC",
        ],
        "answer": 1,
        "explain": "Statically configuring ports (no DTP negotiation) defeats switch spoofing, and moving the native VLAN to an unused ID (never VLAN 1, with no access ports in it) defeats double tagging. DHCP snooping and DNSSEC address different attacks entirely.",
    },
    {
        "type": "mc",
        "q": "After an attack, a switch begins forwarding unicast frames out every port, letting an attacker sniff other users' traffic. What happened?",
        "choices": [
            "ARP poisoning redirected the default gateway",
            "A rogue DHCP server changed client subnet masks",
            "MAC flooding filled the CAM table, so the switch fails open and floods like a hub",
            "Spanning tree elected the attacker as root bridge",
        ],
        "answer": 2,
        "explain": "MAC flooding blasts the switch with frames from thousands of bogus source MACs until the CAM table is full. Unable to look up destinations, the switch floods unicast traffic out all ports like a hub, exposing it to sniffing. Port security (limiting MACs per port) prevents this.",
    },
    {
        "type": "mc",
        "q": "Which switch feature directly mitigates MAC flooding?",
        "choices": [
            "DNSSEC",
            "Port security limiting the number of MAC addresses per port",
            "URL filtering",
            "A screened subnet",
        ],
        "answer": 1,
        "explain": "Port security caps how many source MACs a port may present (e.g., 1-2) and takes a violation action (shutdown/restrict/protect) when exceeded — so a flood of bogus MACs is stopped at the first port instead of filling the CAM table.",
    },
    {
        "type": "mc",
        "q": "An attacker on the LAN sends forged, unsolicited ARP replies telling every host that the default gateway's IP maps to the attacker's MAC address. What is the immediate result?",
        "choices": [
            "The DHCP scope is exhausted",
            "Hosts send their outbound traffic to the attacker, enabling an on-path attack",
            "The switch CAM table overflows",
            "DNS queries fail with SERVFAIL errors",
        ],
        "answer": 1,
        "explain": "ARP has no authentication, so hosts cache the forged mapping (ARP poisoning) and unknowingly forward gateway-bound traffic to the attacker, who can read or modify it before relaying — a classic LAN on-path position. Dynamic ARP Inspection drops such forged ARP packets.",
    },
    {
        "type": "mc",
        "q": "How are ARP spoofing and ARP poisoning best distinguished?",
        "choices": [
            "Spoofing is the act of sending forged ARP messages; poisoning is the resulting corrupted ARP caches",
            "Spoofing targets routers while poisoning targets DNS servers",
            "Poisoning works across the Internet while spoofing is LAN-only",
            "They are unrelated attacks at different OSI layers",
        ],
        "answer": 0,
        "explain": "The terms describe technique versus outcome of the same attack: the attacker spoofs (transmits forged ARP replies), which poisons victims' caches with false IP-to-MAC mappings. Both are strictly local — ARP never crosses a router, so the attacker must be on the same LAN.",
    },
    {
        "type": "mc",
        "q": "Which technology validates ARP packets against a DHCP snooping binding table and drops forgeries?",
        "choices": [
            "DNSSEC",
            "802.1Q",
            "Dynamic ARP Inspection (DAI)",
            "Reverse ARP",
        ],
        "answer": 2,
        "explain": "DAI is the switch feature that checks each ARP packet's IP-to-MAC claim against the trusted binding table built by DHCP snooping and discards mismatches, defeating ARP spoofing/poisoning. This is why DHCP snooping is usually enabled first — DAI depends on its table.",
    },
    {
        "type": "mc",
        "q": "Users across a company typed the correct URL for their bank but all landed on a convincing fake site. Investigation shows the company's DNS resolver is returning a wrong IP for the bank's name. Which attack is this?",
        "choices": [
            "ARP poisoning",
            "MAC flooding",
            "Evil twin",
            "DNS cache poisoning",
        ],
        "answer": 3,
        "explain": "False records were planted in the resolver's cache, so every client querying that resolver receives the malicious answer until the TTL expires — a huge blast radius from one attack. DNSSEC lets resolvers verify record signatures and reject the forged data.",
    },
    {
        "type": "mc",
        "q": "What is the primary defense that allows resolvers to cryptographically verify DNS responses are authentic?",
        "choices": [
            "DNSSEC",
            "DHCP snooping",
            "Port security",
            "SAML",
        ],
        "answer": 0,
        "explain": "DNSSEC digitally signs DNS records so resolvers can validate their origin and integrity, defeating spoofed responses and cache poisoning. DHCP snooping and port security are Layer 2 defenses; SAML is a federation standard — unrelated to DNS integrity.",
    },
    {
        "type": "mc",
        "q": "Minutes after an unknown device was plugged into a conference room jack, nearby users obtained IP settings with a wrong default gateway and began routing traffic through it. What is the device?",
        "choices": [
            "An evil twin",
            "A rogue DHCP server",
            "A honeypot",
            "A TACACS+ server",
        ],
        "answer": 1,
        "explain": "A rogue DHCP server races the legitimate one to answer DISCOVER broadcasts and hands out the attacker's address as the gateway (or a malicious DNS server), placing the attacker on-path for the subnet. DHCP snooping blocks server messages on untrusted ports.",
    },
    {
        "type": "mc",
        "q": "Which switch feature drops DHCP OFFER/ACK messages that arrive on ports not designated as trusted?",
        "choices": [
            "Dynamic ARP Inspection",
            "MAC filtering",
            "DHCP snooping",
            "Spanning Tree Protocol",
        ],
        "answer": 2,
        "explain": "DHCP snooping designates only the port(s) toward the legitimate DHCP server as trusted; server-type messages arriving on any untrusted access port are dropped, neutralizing rogue DHCP. It also builds the IP/MAC/port binding table that Dynamic ARP Inspection uses.",
    },
    {
        "type": "mc",
        "q": "An employee plugs a personal wireless router into their desk network jack to get better Wi-Fi. What has the employee created?",
        "choices": [
            "An evil twin",
            "A honeypot",
            "A screened subnet",
            "A rogue access point",
        ],
        "answer": 3,
        "explain": "Any unauthorized AP attached to the wired network is a rogue AP — even a well-meaning one. It extends the internal LAN over the air, typically with weak security, letting outsiders bypass the firewall. 802.1X/NAC on switch ports and WIPS detection are the standard defenses.",
    },
    {
        "type": "mc",
        "q": "At a hotel, an attacker broadcasts an AP with the identical SSID as the hotel Wi-Fi at higher power, and guests' devices connect to it automatically, revealing their traffic. Which attack is this?",
        "choices": [
            "An evil twin",
            "A rogue DHCP server",
            "MAC flooding",
            "DNS poisoning",
        ],
        "answer": 0,
        "explain": "An evil twin impersonates a legitimate SSID (often with a stronger signal and sometimes after deauthenticating clients) so victims connect to the attacker's AP, enabling on-path interception and fake captive portals that harvest credentials. It differs from a rogue AP, which is attached to your actual network.",
    },
    {
        "type": "mc",
        "q": "What is the key difference between a rogue AP and an evil twin?",
        "choices": [
            "A rogue AP is wireless while an evil twin is wired",
            "A rogue AP is an unauthorized AP on your network; an evil twin imitates your SSID to lure clients and usually is not on your network",
            "An evil twin only attacks WPA3 networks while rogue APs attack WPA2",
            "There is no difference; the terms are interchangeable",
        ],
        "answer": 1,
        "explain": "The rogue AP's danger is the uncontrolled entry point into your internal network. The evil twin's danger is impersonation — it mimics a trusted SSID to trick clients into connecting so their traffic can be intercepted. One threatens your LAN; the other threatens your users wherever they roam.",
    },
    {
        "type": "mc",
        "q": "An attacker secretly relays and can modify communication between a user and a web server while both believe they are talking directly to each other. What does N10-009 call this?",
        "choices": [
            "A replay attack",
            "A birthday attack",
            "An on-path attack",
            "A downgrade attack",
        ],
        "answer": 2,
        "explain": "The on-path attack is the current CompTIA term for man-in-the-middle (MITM): the attacker inserts themselves into the communication path to eavesdrop, alter, or inject data. ARP poisoning, rogue DHCP, DNS spoofing, and evil twins are all common techniques for getting on-path.",
    },
    {
        "type": "mc",
        "q": "Which of the following attacks is NOT a typical way to establish an on-path position?",
        "choices": [
            "ARP poisoning of the default gateway",
            "A rogue DHCP server assigning a malicious gateway",
            "An evil twin access point",
            "Dumpster diving",
        ],
        "answer": 3,
        "explain": "ARP poisoning, rogue DHCP, and evil twins all place the attacker in the traffic path between victims and their destinations. Dumpster diving is physical social engineering — retrieving discarded documents and media — and involves no traffic interception.",
    },
    {
        "type": "mc",
        "q": "The CFO receives a highly personalized email, appearing to come from the CEO, urgently requesting a confidential wire transfer. Which attack best describes this?",
        "choices": [
            "Whaling",
            "Smishing",
            "Vishing",
            "Shoulder surfing",
        ],
        "answer": 0,
        "explain": "Whaling is spear phishing aimed at executives and other high-value 'big fish' like CFOs. The personalization and impersonation of leadership are hallmarks. Smishing uses SMS, vishing uses voice calls, and shoulder surfing is visual observation.",
    },
    {
        "type": "mc",
        "q": "A caller claiming to be from the IT help desk phones an employee and asks for their password to 'fix a mailbox issue.' Which attack is this?",
        "choices": [
            "Smishing",
            "Vishing",
            "Spear phishing",
            "Tailgating",
        ],
        "answer": 1,
        "explain": "Vishing is voice phishing — social engineering over the phone, often with spoofed caller ID and impersonation of trusted roles like IT support. The defense is procedural: legitimate IT never asks for passwords, and employees should verify callers through known channels.",
    },
    {
        "type": "mc",
        "q": "Employees receive text messages claiming a package is held and asking them to tap a link and enter payment details. Which attack is this?",
        "choices": [
            "Whaling",
            "Dumpster diving",
            "Smishing",
            "Evil twin",
        ],
        "answer": 2,
        "explain": "Smishing is phishing over SMS. The lure (a held package, an account problem) pushes urgency toward a malicious link. Same psychology as email phishing, different channel — which is why awareness training must cover text and voice channels too.",
    },
    {
        "type": "mc",
        "q": "An attacker retrieves discarded network diagrams and sticky notes with passwords from the office trash. Which attack, and what is the best defense?",
        "choices": [
            "Shoulder surfing; privacy screen filters",
            "Tailgating; access control vestibules",
            "Phishing; email filtering",
            "Dumpster diving; shredding documents and destroying old media",
        ],
        "answer": 3,
        "explain": "Dumpster diving harvests intelligence from trash — documents, org charts, credentials, and old drives — often to fuel convincing spear phishing later. Cross-cut shredding, media destruction/sanitization, and locked disposal bins are the defenses.",
    },
    {
        "type": "mc",
        "q": "While an admin types a password, a visitor standing nearby watches the keyboard and memorizes it. Which attack is this?",
        "choices": [
            "Shoulder surfing",
            "Vishing",
            "On-path attack",
            "MAC spoofing",
        ],
        "answer": 0,
        "explain": "Shoulder surfing is capturing credentials or data by direct observation — over a shoulder, through a window, or with a camera. Privacy filters, screen positioning, shielding keypads, and locking screens when stepping away are the countermeasures.",
    },
    {
        "type": "mc",
        "q": "A person carrying boxes slips through a badge-controlled door right behind an employee, without badging in and without the employee noticing. Which control BEST prevents this attack?",
        "choices": [
            "A privacy screen filter",
            "An access control vestibule (mantrap)",
            "DNSSEC",
            "Full-disk encryption",
        ],
        "answer": 1,
        "explain": "This is tailgating — following an authorized person through a secure door without credentials. An access control vestibule allows only one authenticated person through at a time, physically defeating it. Turnstiles, guards, and one-badge-one-person training also help.",
    },
    {
        "type": "mc",
        "q": "Which malware type spreads across the network by itself, with no user interaction required?",
        "choices": [
            "Virus",
            "Trojan",
            "Worm",
            "Keylogger",
        ],
        "answer": 2,
        "explain": "A worm self-replicates by exploiting vulnerabilities across the network, which is why worms can saturate links and compromise whole fleets within minutes. A virus needs a user to execute an infected file, and a trojan relies on the user voluntarily installing a disguised program.",
    },
    {
        "type": "mc",
        "q": "A user downloads a 'free video converter' that works as advertised but secretly opens a backdoor for remote attacker access. Which malware type is this?",
        "choices": [
            "Worm",
            "Trojan",
            "Ransomware",
            "Virus",
        ],
        "answer": 1,
        "explain": "A trojan masquerades as legitimate, useful software to trick the user into installing it, then performs hidden malicious actions — commonly installing a backdoor or remote access tool (RAT). Unlike viruses it does not infect other files, and unlike worms it does not self-propagate.",
    },
    {
        "type": "mc",
        "q": "How is DNS poisoning best distinguished from DNS spoofing?",
        "choices": [
            "Poisoning targets clients while spoofing targets only root servers",
            "Spoofing requires physical access while poisoning is always remote",
            "Poisoning plants false records in a resolver's cache; spoofing is the broader technique of supplying forged DNS responses",
            "They occur at different OSI layers",
        ],
        "answer": 2,
        "explain": "DNS spoofing is the technique — forging responses (racing the real server, answering from an on-path position, or via a rogue DNS server). DNS cache poisoning is the persisted result: false records lodged in a resolver's cache that then mislead every client using it. Forged responses are the usual means of poisoning.",
    },
    {
        "type": "mc",
        "q": "A user receives a mass-mailed message claiming their bank account is locked, with a link to a look-alike login page that steals credentials. Which attack is this?",
        "choices": [
            "Phishing",
            "Shoulder surfing",
            "On-path attack",
            "Dumpster diving",
        ],
        "answer": 0,
        "explain": "Generic phishing is mass, untargeted fraudulent communication impersonating a trusted entity to harvest credentials or deliver malware. When personalized for a specific target it becomes spear phishing, and when aimed at executives, whaling. Red flags: urgency, mismatched sender domains, look-alike URLs.",
    },
    # ---------------- True/False ----------------
    {
        "type": "tf",
        "q": "ARP poisoning can be launched by an attacker anywhere on the Internet against any LAN.",
        "answer": False,
        "explain": "ARP is strictly local — ARP messages never cross a router, so the attacker must already be on the same LAN/VLAN as the victims. That is why ARP attacks pair with insider access, rogue devices, or compromised hosts, and why switch-level defenses like DAI are effective.",
    },
    {
        "type": "tf",
        "q": "In a reflection/amplification DDoS, the attacker spoofs the victim's IP address as the source of queries sent to third-party servers.",
        "answer": True,
        "explain": "Spoofing the source makes the reflectors send their responses to the victim, and choosing protocols whose answers dwarf the queries (DNS, NTP, memcached) multiplies the traffic. The reflectors are innocent servers, which also hides the attacker's real address.",
    },
    {
        "type": "tf",
        "q": "Poisoning a company resolver's DNS cache affects only the single user who was targeted.",
        "answer": False,
        "explain": "Cache poisoning has a large blast radius: once the false record is in the shared resolver's cache, every client that queries that resolver receives the malicious answer until the record's TTL expires. That leverage is what makes resolver poisoning far worse than spoofing one client.",
    },
    {
        "type": "tf",
        "q": "An evil twin access point must be physically connected to the victim organization's wired network to work.",
        "answer": False,
        "explain": "An evil twin merely imitates a legitimate SSID to lure client devices into connecting; it typically provides its own uplink and never touches the real network. It is the rogue AP that is defined by being attached to your network — that distinction is a favorite exam question.",
    },
    {
        "type": "tf",
        "q": "Many sources distinguish tailgating (following without the authorized person's knowledge) from piggybacking (the authorized person knowingly holds the door).",
        "answer": True,
        "explain": "The discriminator is consent: tailgating is covert, piggybacking is a knowing courtesy. CompTIA's blueprint lists tailgating, but if both terms appear as answer choices, use the consent distinction. Both are defeated by access control vestibules and one-badge-one-person policies.",
    },
    {
        "type": "tf",
        "q": "A Slowloris-style attack that holds many HTTP connections open with very slow requests is classified as a volumetric attack.",
        "answer": False,
        "explain": "Slowloris is an application-layer (L7) attack: it uses tiny amounts of bandwidth but exhausts the web server's pool of concurrent connections with deliberately incomplete requests. Volumetric attacks work the opposite way — brute-force saturation of bandwidth with massive traffic.",
    },
    # ---------------- Fill-in ----------------
    {
        "type": "fill",
        "q": "A network of malware-compromised devices remotely controlled to launch DDoS attacks is called a ____.",
        "answers": ["botnet", "bot net", "zombie network"],
        "explain": "Botnets are built from compromised PCs and especially IoT devices, coordinated through command-and-control (C2) infrastructure. They supply the distributed firepower behind DDoS attacks, spam campaigns, and credential stuffing.",
    },
    {
        "type": "fill",
        "q": "The switch table that MAC flooding attempts to overflow is the ____ table. (type the acronym)",
        "answers": ["CAM", "content addressable memory", "MAC address"],
        "explain": "The CAM (content-addressable memory) table maps learned MAC addresses to ports. When it overflows, the switch can no longer look up destinations and floods unicast frames out all ports like a hub — exactly what the sniffing attacker wants. Port security prevents it.",
    },
    {
        "type": "fill",
        "q": "The trunk negotiation protocol abused in switch spoofing attacks, which should be disabled on access ports, is ____. (type the acronym)",
        "answers": ["DTP", "dynamic trunking protocol"],
        "explain": "Dynamic Trunking Protocol lets Cisco switch ports auto-negotiate trunking. An attacker who speaks DTP to a port left in dynamic mode can form a trunk carrying all VLANs. Statically configure ports as access mode and disable negotiation (switchport nonegotiate).",
    },
    {
        "type": "fill",
        "q": "The DNS security extension that digitally signs records so resolvers can verify their authenticity is ____.",
        "answers": ["DNSSEC", "DNS security extensions"],
        "explain": "DNSSEC adds cryptographic signatures to DNS data, letting validating resolvers detect and reject forged responses — the mitigation for DNS spoofing and cache poisoning. Note it provides integrity/authenticity, not confidentiality (queries are still visible).",
    },
    {
        "type": "fill",
        "q": "Phishing conducted over voice calls is known as ____.",
        "answers": ["vishing", "voice phishing"],
        "explain": "Vishing uses phone calls (often with spoofed caller ID) to impersonate help desks, banks, or authorities and extract credentials or payments. Related variants: smishing (SMS), spear phishing (targeted email), and whaling (targeting executives).",
    },
    {
        "type": "fill",
        "q": "The current CompTIA term for a man-in-the-middle attack is an ____ attack.",
        "answers": ["on-path", "on path"],
        "explain": "N10-009 uses 'on-path attack' for an attacker secretly relaying traffic between two parties. Recognize the older MITM name in legacy materials, and remember that ARP poisoning, rogue DHCP, DNS spoofing, and evil twins are all routes to an on-path position.",
    },
    # ---------------- Match ----------------
    {
        "type": "match",
        "q": "Match each attack to its primary mitigation.",
        "pairs": [
            ["MAC flooding", "Port security limiting MACs per port"],
            ["ARP poisoning", "Dynamic ARP Inspection"],
            ["Rogue DHCP server", "DHCP snooping with trusted ports"],
            ["DNS cache poisoning", "DNSSEC record signing"],
            ["VLAN hopping", "Disable DTP and use an unused native VLAN"],
        ],
        "explain": "These attack-to-defense pairs are the highest-yield mapping in Domain 4: each Layer 2 attack has a specific switch feature that stops it, and DNS integrity attacks are answered by DNSSEC. Expect scenario questions that describe the attack and ask for the mitigation, or vice versa.",
    },
    {
        "type": "match",
        "q": "Match each social engineering attack to its description.",
        "pairs": [
            ["Spear phishing", "Personalized email targeting a specific person or organization"],
            ["Whaling", "Phishing aimed at executives or other high-value targets"],
            ["Smishing", "Phishing delivered via SMS text message"],
            ["Dumpster diving", "Retrieving useful information from discarded trash"],
            ["Shoulder surfing", "Watching a screen or keyboard to capture sensitive data"],
            ["Tailgating", "Following an authorized person through a secured door"],
        ],
        "explain": "Social engineering attacks the human layer. The phishing family differs by targeting and channel (email/SMS/voice, generic vs. targeted vs. executive), while dumpster diving, shoulder surfing, and tailgating are physical-world techniques defeated by shredding, privacy filters, and vestibules respectively.",
    },
    {
        "type": "match",
        "q": "Match each malware type to its defining behavior.",
        "pairs": [
            ["Virus", "Attaches to files and needs user action to run and spread"],
            ["Worm", "Self-replicates across the network without user interaction"],
            ["Trojan", "Disguised as legitimate software the user installs voluntarily"],
            ["Ransomware", "Encrypts data and demands payment for the key"],
        ],
        "explain": "The discriminators: how it spreads (user-triggered vs. self-propagating), how it arrives (attached to files vs. disguised as a wanted program), and what it does (ransomware's encryption is primarily an availability attack). Worms have the biggest direct network impact via scanning and replication traffic.",
    },
    # ---------------- Order ----------------
    {
        "type": "order",
        "q": "Arrange the stages of a typical DDoS campaign in chronological order.",
        "items": [
            "Malware infects poorly secured devices",
            "Infected bots enroll in the botnet and await commands",
            "The attacker issues attack orders via command-and-control",
            "Thousands of bots flood the victim simultaneously",
            "The victim's service becomes unavailable to legitimate users",
        ],
        "explain": "DDoS is a two-phase crime: first build the weapon (compromise devices — often IoT with default credentials — into a C2-controlled botnet), then aim it (coordinate a simultaneous flood). Defenses target both phases: device hardening prevents recruitment; scrubbing and rate limiting blunt the flood.",
    },
    {
        "type": "order",
        "q": "Arrange the steps of an ARP poisoning on-path attack in the order they occur.",
        "items": [
            "Attacker joins the same LAN as the victims",
            "Attacker sends forged ARP replies mapping the gateway IP to the attacker's MAC",
            "Victims' ARP caches store the falsified entry",
            "Victim traffic destined for the gateway flows to the attacker",
            "Attacker inspects or alters the traffic, then relays it onward",
        ],
        "explain": "The attack works because ARP trusts any reply, even unsolicited ones. Once caches are poisoned, the attacker silently relays traffic so victims notice nothing while every packet passes through hostile hands. Dynamic ARP Inspection breaks step two by dropping forged ARP packets at the switch.",
    },
]
