TOPIC = {
    "id": "4.3",
    "domain": 4,
    "title": "Given a scenario, apply network security features, defense techniques, and solutions",
    "short": "Defense Techniques",
}

TERMS = [
    ("Device hardening", "Reducing a device's attack surface by disabling unused ports/services, changing defaults, and patching"),
    ("Attack surface", "The sum of all the ways an attacker could enter or affect a system"),
    ("Default credentials", "Vendor-shipped usernames/passwords published in manuals; must be changed before deployment"),
    ("Network access control (NAC)", "Framework that decides whether and how a device may join the network, often with posture assessment"),
    ("Posture assessment", "NAC health check of an endpoint (patch level, antivirus, encryption) before granting access"),
    ("Agentless NAC", "Posture checking performed without installing persistent software on the endpoint"),
    ("Quarantine VLAN", "Restricted remediation network where NAC places non-compliant devices"),
    ("Port security", "Switch feature limiting which and how many MAC addresses may appear on a port"),
    ("Sticky MAC", "Port security mode that saves dynamically learned MAC addresses into the configuration as the allowed set"),
    ("Err-disabled", "Port state after a shutdown-mode port security violation; requires administrative re-enable"),
    ("Violation mode restrict", "Port security action that drops offending traffic, keeps the port up, and logs/alerts on violations"),
    ("Violation mode protect", "Port security action that silently drops offending traffic with no logging or alerts"),
    ("802.1X", "IEEE standard for port-based network access control; no traffic passes until authentication succeeds"),
    ("Supplicant", "The 802.1X client device/software requesting network access"),
    ("Authenticator", "The 802.1X switch or AP that blocks the port and relays authentication to the server"),
    ("Authentication server", "The RADIUS server in 802.1X that validates credentials and instructs the authenticator"),
    ("EAPoL", "EAP over LAN; the framing used between supplicant and authenticator in 802.1X"),
    ("MAC filtering", "Allowing/denying devices by MAC address; weak because MACs are cleartext and easily spoofed"),
    ("Key management", "Lifecycle of cryptographic keys: generation, distribution, storage, rotation, escrow, and destruction"),
    ("Key escrow", "A trusted party holds copies of keys so encrypted data remains recoverable if the holder loses access"),
    ("HSM", "Hardware security module; tamper-resistant device for generating and storing cryptographic keys"),
    ("Key rotation", "Regularly replacing keys to limit how much data a single compromised key exposes"),
    ("Access control list (ACL)", "Ordered permit/deny rules evaluated top-down with first match wins, applied to interfaces"),
    ("Implicit deny", "The invisible rule at the end of every ACL that drops any traffic not explicitly permitted"),
    ("URL filtering", "Blocking or allowing web traffic based on the requested address, domain, or category"),
    ("Content filtering", "Inspecting the actual payload of traffic to block malware, file types, or prohibited material"),
    ("Security zone", "Logical grouping of networks/interfaces sharing one trust level, with policy enforced between zones"),
    ("Trusted zone", "The internal network under your administrative control with managed, authenticated devices"),
    ("Untrusted zone", "Networks you do not control, chiefly the Internet; assumed hostile by default"),
    ("Screened subnet", "Buffer network (formerly DMZ) between the Internet and LAN hosting public-facing servers"),
]

QUESTIONS = [
    # ---------------- Multiple choice ----------------
    {
        "type": "mc",
        "q": "During a security review, a switch in a public lobby has six unused ports that are enabled and in the default VLAN. What is the BEST hardening step?",
        "choices": [
            "Enable DTP on the unused ports for flexibility",
            "Administratively shut down the unused ports and assign them to an unused VLAN",
            "Configure the ports as trunk ports",
            "Increase the port speed to reduce exposure time",
        ],
        "answer": 1,
        "explain": "Unused but active ports let anyone who reaches the jack join the LAN with a rogue laptop, AP, or DHCP server. Shutting them down and parking them in an unused black-hole VLAN removes the entry point. 802.1X/NAC adds authentication for ports that must stay active.",
    },
    {
        "type": "mc",
        "q": "A vulnerability scan shows a router accepting Telnet, HTTP management, and SNMPv2c. Which change hardens the device most directly?",
        "choices": [
            "Disable those services and use SSH, HTTPS, and SNMPv3 instead",
            "Move the router to a faster switch port",
            "Enable jumbo frames on the management interface",
            "Add a second default gateway",
        ],
        "answer": 0,
        "explain": "Telnet, HTTP, and SNMPv1/v2c transmit credentials and data in cleartext. Hardening means disabling unneeded/insecure services and replacing them with encrypted equivalents: SSH for CLI, HTTPS for web management, SNMPv3 for authenticated, encrypted monitoring.",
    },
    {
        "type": "mc",
        "q": "What should be the FIRST configuration step when deploying a new IP camera, access point, or router?",
        "choices": [
            "Register the device's warranty",
            "Enable remote Internet management",
            "Change the default administrative password",
            "Configure port mirroring",
        ],
        "answer": 2,
        "explain": "Default credentials are published in manuals and harvested into lists that attackers and botnets (like Mirai) try automatically. Changing them before the device touches the network is the classic first hardening step, along with updating firmware and disabling unneeded services.",
    },
    {
        "type": "mc",
        "q": "Why do firmware updates belong in a device hardening program?",
        "choices": [
            "They increase link speed on trunk ports",
            "They patch the vulnerabilities that exploits target",
            "They reset devices to factory defaults",
            "They are required for DHCP snooping to work",
        ],
        "answer": 1,
        "explain": "Exploits leverage vulnerabilities; patching firmware removes those vulnerabilities and therefore lowers risk even though threats remain. A device with a strong password but old firmware is still exposed to known exploits — hardening covers credentials, services, and patch level together.",
    },
    {
        "type": "mc",
        "q": "Before granting network access, a system verifies that a connecting laptop has current patches, running antivirus, and disk encryption. Non-compliant laptops are placed in a remediation VLAN. What is this process called?",
        "choices": [
            "Content filtering",
            "Key escrow",
            "URL filtering",
            "NAC posture assessment",
        ],
        "answer": 3,
        "explain": "Network access control performs posture (health) assessment at connection time and quarantines non-compliant endpoints into a restricted network where they can be updated. Posture can be checked by a persistent or dissolvable agent, or agentlessly via scanning.",
    },
    {
        "type": "mc",
        "q": "A company cannot install software on visiting contractors' laptops but still wants to health-check them before granting access. Which NAC approach fits?",
        "choices": [
            "Agentless posture assessment",
            "Persistent agent installation",
            "Sticky MAC learning",
            "Key rotation",
        ],
        "answer": 0,
        "explain": "Agentless NAC evaluates endpoints without permanently installing software — via network scans, browser-based dissolvable checks, or infrastructure queries. It suits unmanaged BYOD and guest devices where a persistent agent is impossible; managed corporate fleets often use persistent agents for richer checks.",
    },
    {
        "type": "mc",
        "q": "A port is configured for port security with 'sticky' MAC learning. What does sticky mean?",
        "choices": [
            "The port refuses all MAC addresses until one is configured statically",
            "Dynamically learned MAC addresses are saved to the configuration and become the allowed set",
            "The port glues itself to the fastest speed negotiated",
            "MAC addresses are hashed before storage",
        ],
        "answer": 1,
        "explain": "Sticky MAC combines convenience with control: the switch learns the first connected device(s) dynamically, then writes those addresses into the running configuration so they persist as the port's permanently allowed MACs. Any different device later triggers the violation action.",
    },
    {
        "type": "mc",
        "q": "A port security violation occurs on a port configured with the default violation mode. What happens?",
        "choices": [
            "Offending frames are dropped silently and the port stays up",
            "Offending frames are dropped, logged, and the port stays up",
            "The port enters the err-disabled state and goes down until re-enabled",
            "The switch reboots to clear the CAM table",
        ],
        "answer": 2,
        "explain": "The default violation mode is shutdown: the entire port is placed in err-disabled and passes no traffic until an administrator re-enables it (or errdisable auto-recovery runs). Restrict drops and logs while staying up; protect drops silently while staying up.",
    },
    {
        "type": "mc",
        "q": "Which port security violation mode drops unauthorized traffic and keeps the port up, but generates NO log messages or alerts?",
        "choices": [
            "Shutdown",
            "Restrict",
            "Protect",
            "Err-disable",
        ],
        "answer": 2,
        "explain": "Protect silently drops frames from unauthorized MACs with no notification, which makes violations invisible to monitoring. Restrict behaves identically except it increments counters and sends syslog/SNMP alerts — that logging difference is the exam's favorite discriminator.",
    },
    {
        "type": "mc",
        "q": "An attacker unplugs a VoIP phone in the lobby and connects a laptop. The switch port immediately goes down and the interface shows err-disabled. Which feature caused this?",
        "choices": [
            "Port security in shutdown violation mode",
            "DHCP snooping",
            "Content filtering",
            "URL filtering",
        ],
        "answer": 0,
        "explain": "Port security saw an unauthorized MAC address (the laptop) on a port limited to the phone's MAC and executed the shutdown violation action, err-disabling the port. This is the standard defense against casual rogue-device connections and MAC flooding.",
    },
    {
        "type": "mc",
        "q": "In an 802.1X deployment, which component actually validates the user's credentials?",
        "choices": [
            "The supplicant",
            "The authentication server (RADIUS)",
            "The authenticator switch",
            "The DHCP server",
        ],
        "answer": 1,
        "explain": "The authenticator (switch/AP) never checks credentials — it blocks the port and relays the EAP conversation to the authentication server, typically RADIUS backed by a directory. The server decides and tells the authenticator to open the port or keep it closed.",
    },
    {
        "type": "mc",
        "q": "In wired 802.1X, what role does the workstation's 802.1X client software play?",
        "choices": [
            "Authenticator",
            "Authentication server",
            "Registration authority",
            "Supplicant",
        ],
        "answer": 3,
        "explain": "The supplicant is the client device/software requesting access. Memorize the trio: supplicant (client) talks EAPoL to the authenticator (switch/AP), which relays EAP inside RADIUS to the authentication server. Until success, the port passes only authentication traffic.",
    },
    {
        "type": "mc",
        "q": "Which protocol carries authentication frames between the supplicant and the authenticator on the LAN segment in 802.1X?",
        "choices": [
            "EAPoL (EAP over LAN)",
            "TACACS+",
            "SNMPv3",
            "LDAPS",
        ],
        "answer": 0,
        "explain": "The supplicant and authenticator exchange EAP over LAN (EAPoL) frames; the authenticator then repackages the EAP messages inside RADIUS toward the authentication server. Before authentication succeeds, EAPoL is essentially the only traffic the port permits.",
    },
    {
        "type": "mc",
        "q": "A company wants switch ports to pass NO user traffic until the connecting user authenticates against the corporate directory. Which solution applies?",
        "choices": [
            "MAC filtering",
            "URL filtering",
            "802.1X port-based network access control",
            "A screened subnet",
        ],
        "answer": 2,
        "explain": "802.1X is port-based NAC: the authenticator holds the port closed except for EAPoL until the RADIUS server validates the user's credentials (often against Active Directory). It defeats rogue devices at the jack, and on wireless it is what makes WPA2/WPA3-Enterprise 'enterprise.'",
    },
    {
        "type": "mc",
        "q": "Why is MAC filtering considered a weak security control on its own?",
        "choices": [
            "MAC addresses change every time a device reboots",
            "MAC addresses are visible in cleartext frames and easily spoofed",
            "It only works on fiber interfaces",
            "It encrypts traffic with an outdated cipher",
        ],
        "answer": 1,
        "explain": "Frame headers — including source/destination MACs — are never encrypted, even on secured Wi-Fi, so an attacker can sniff an allowed MAC and impersonate it with a one-line OS command. Treat MAC filtering as housekeeping/defense-in-depth; use 802.1X for real admission control.",
    },
    {
        "type": "mc",
        "q": "After 802.1X authentication succeeds, what can the RADIUS server dynamically instruct the switch to do with the session?",
        "choices": [
            "Assign the port to a specific VLAN or apply ACLs for that user",
            "Rewrite the client's MAC address",
            "Convert the port to a trunk carrying all VLANs",
            "Disable spanning tree on the port",
        ],
        "answer": 0,
        "explain": "802.1X supports dynamic authorization: the authentication server can return attributes that place the session into a role-appropriate VLAN or apply per-user ACLs. This merges authentication with authorization — contractors, employees, and IoT can land in different segments off the same jack.",
    },
    {
        "type": "mc",
        "q": "An engineer leaves the company and their laptop's full-disk encryption key is unrecoverable — but IT restores access using a recovery key held by the security team. Which key management practice enabled this?",
        "choices": [
            "Key rotation",
            "Perfect forward secrecy",
            "Key escrow",
            "Certificate pinning",
        ],
        "answer": 2,
        "explain": "Key escrow means a trusted party (here, internal IT) holds copies of keys or recovery keys so encrypted data stays recoverable when the key holder leaves or loses the key. Without escrow, losing the only key is self-inflicted, permanent data loss.",
    },
    {
        "type": "mc",
        "q": "Which practice limits how much data is exposed if a single cryptographic key is compromised?",
        "choices": [
            "Storing keys in configuration scripts for quick access",
            "Regular key rotation",
            "Reusing one key across all systems for consistency",
            "Emailing keys to administrators for backup",
        ],
        "answer": 1,
        "explain": "Rotating keys on a schedule (and immediately upon suspected compromise or personnel departure) caps the window and volume of data any one key can unlock. The wrong options are classic anti-patterns: hard-coded keys, key reuse, and cleartext transmission all magnify a single compromise.",
    },
    {
        "type": "mc",
        "q": "Where should an organization store its high-value private keys for strongest protection?",
        "choices": [
            "In a hardware security module (HSM)",
            "In a shared spreadsheet with restricted permissions",
            "Base64-encoded inside application source code",
            "On the public web server they protect",
        ],
        "answer": 0,
        "explain": "An HSM is a tamper-resistant hardware device purpose-built to generate, store, and use keys without ever exposing them; TPM chips and encrypted key vaults serve similar roles. Keys hard-coded in source, spreadsheets, or on exposed servers are routinely harvested by attackers.",
    },
    {
        "type": "mc",
        "q": "An ACL contains: (1) permit tcp any host 10.0.0.5 eq 443, (2) permit ip any any, (3) deny tcp any host 10.0.0.5 eq 22. Why can users still SSH to 10.0.0.5?",
        "choices": [
            "SSH is exempt from ACL processing",
            "The implicit deny overrides rule 3",
            "ACLs are processed top-down and rule 2 matches SSH traffic before rule 3 is ever evaluated",
            "Rule 1 implicitly permits all management protocols",
        ],
        "answer": 2,
        "explain": "ACLs use first-match-wins evaluation: the broad 'permit ip any any' at position 2 matches SSH packets, so the later deny is dead code. Order rules specific-before-general — move the SSH deny above the broad permit (or remove the permit-any and rely on implicit deny).",
    },
    {
        "type": "mc",
        "q": "An administrator applies a new ACL that explicitly permits only HTTPS to a server, and users immediately report that DNS and email to that server also stopped working. What is the cause?",
        "choices": [
            "The ACL corrupted the routing table",
            "The implicit deny at the end of the ACL drops all traffic not explicitly permitted",
            "HTTPS conflicts with DNS on the same interface",
            "The ACL must be rebooted to take effect",
        ],
        "answer": 1,
        "explain": "Every ACL ends with an invisible implicit deny all: anything not matched by a permit rule is dropped. Permitting only TCP 443 therefore blocks every other protocol. Add explicit permits for each required service, and optionally an explicit 'deny any log' to see what is being dropped.",
    },
    {
        "type": "mc",
        "q": "Which statement about applying ACLs is correct?",
        "choices": [
            "An ACL is applied to an interface in a direction (inbound or outbound)",
            "ACLs are evaluated bottom-up, last match wins",
            "An ACL automatically applies to all interfaces at once",
            "ACLs can only match on MAC addresses",
        ],
        "answer": 0,
        "explain": "ACLs take effect only when applied to a specific interface in a specific direction, and the same list behaves differently depending on placement. Evaluation is top-down with first match wins, and typical Layer 3/4 ACLs match source/destination IPs, protocol, and ports.",
    },
    {
        "type": "mc",
        "q": "A company wants to block employee access to all websites categorized as gambling, regardless of the pages' content. Which technology fits?",
        "choices": [
            "Content filtering",
            "Port security",
            "URL filtering",
            "Dynamic ARP Inspection",
        ],
        "answer": 2,
        "explain": "URL filtering decides based on where the user is going — the requested domain/URL or its category — blocking the request before content loads. Content filtering instead inspects what the traffic contains. 'Block a category of sites' is the URL-filtering keyword.",
    },
    {
        "type": "mc",
        "q": "Security wants to stop users from downloading executable (.exe) files from ANY website and to strip dangerous attachments from email. Which technology fits?",
        "choices": [
            "URL filtering",
            "Content filtering",
            "MAC filtering",
            "Geofencing",
        ],
        "answer": 1,
        "explain": "The requirement is about the payload (file type), not the destination address, so the traffic's contents must be inspected — content filtering. Because most web traffic is HTTPS, deep content inspection generally requires TLS inspection (decrypt-inspect-re-encrypt).",
    },
    {
        "type": "mc",
        "q": "In default zone-based firewall policy, which traffic is blocked unless a rule explicitly allows it?",
        "choices": [
            "Traffic initiated from the trusted zone to the untrusted zone",
            "Return traffic for sessions started inside the trusted zone",
            "Traffic between two hosts in the same trusted zone",
            "Traffic initiated from the untrusted zone into the trusted zone",
        ],
        "answer": 3,
        "explain": "The baseline stance: inside users may initiate outward, and stateful firewalls permit the return traffic of those sessions, but nothing from the untrusted side (Internet) may initiate into the trusted zone without an explicit rule. Publicly reachable services belong in the screened subnet instead.",
    },
    {
        "type": "mc",
        "q": "Where should a company place its public-facing web server?",
        "choices": [
            "In the screened subnet (DMZ) between the external and internal firewalls",
            "On the internal LAN next to the file servers",
            "Directly on the Internet outside all firewalls",
            "On the management VLAN",
        ],
        "answer": 0,
        "explain": "The screened subnet is the buffer zone for services that must be reachable from the untrusted Internet. The external firewall admits only the published ports (e.g., TCP 443), and the internal firewall blocks the DMZ from the LAN except for specific required flows — so a compromised web server is contained.",
    },
    {
        "type": "mc",
        "q": "A DMZ web server is compromised by an Internet attacker. In a properly designed dual-firewall screened subnet, why can't the attacker immediately reach the internal LAN?",
        "choices": [
            "The web server has no network interface",
            "The internal firewall permits only specific, minimal flows from the DMZ toward the LAN",
            "The external firewall blocks all outbound traffic from the LAN",
            "DMZ servers cannot be compromised remotely",
        ],
        "answer": 1,
        "explain": "That containment is the entire point of the screened subnet: the internal firewall stands between the DMZ and the trusted LAN, allowing only tightly scoped flows (e.g., web server to one database port). The attacker is stuck in the buffer zone rather than roaming the internal network.",
    },
    {
        "type": "mc",
        "q": "What is a three-legged (triple-homed) firewall design?",
        "choices": [
            "Three firewalls stacked in series for redundancy",
            "A firewall cluster spanning three data centers",
            "One firewall with three interfaces: outside, inside, and screened subnet",
            "A firewall that filters at Layers 3, 4, and 7 simultaneously",
        ],
        "answer": 2,
        "explain": "Instead of two separate firewalls, a single firewall with three interfaces enforces the policy matrix among Internet (outside), LAN (inside), and DMZ. It is cheaper and simpler but concentrates risk: one device is now a single point of failure and compromise.",
    },
    # ---------------- True/False ----------------
    {
        "type": "tf",
        "q": "In 802.1X, the authenticator (switch) is the component that checks the user's credentials against the directory.",
        "answer": False,
        "explain": "The authenticator only blocks the port and relays EAP between the supplicant and the authentication server; the RADIUS server makes the actual credential decision (often against Active Directory). Keep the roles straight: client = supplicant, switch/AP = authenticator, RADIUS = authentication server.",
    },
    {
        "type": "tf",
        "q": "Every ACL ends with an implicit deny, so traffic not matched by any permit rule is dropped.",
        "answer": True,
        "explain": "The implicit deny all is invisible and un-logged at the bottom of every ACL. It enforces least privilege for traffic (permit only what is needed) and explains the classic symptom of a new ACL breaking services nobody wrote a deny for. Add an explicit 'deny any log' to record what it drops.",
    },
    {
        "type": "tf",
        "q": "Port security violation modes restrict and protect both drop unauthorized traffic, but only restrict generates log messages and alerts.",
        "answer": True,
        "explain": "Both modes keep the port up and drop offending frames; the difference is visibility — restrict increments violation counters and sends syslog/SNMP notifications while protect stays silent. Shutdown (the default) err-disables the entire port instead.",
    },
    {
        "type": "tf",
        "q": "MAC filtering on a wireless network is a strong control because Wi-Fi encryption hides client MAC addresses from attackers.",
        "answer": False,
        "explain": "Even on encrypted Wi-Fi, frame headers — including MAC addresses — are transmitted in cleartext, so an attacker can sniff an authorized MAC and spoof it in seconds. MAC filtering is at best a housekeeping layer; 802.1X/WPA-Enterprise provides real admission control.",
    },
    {
        "type": "tf",
        "q": "URL filtering inspects the payload of downloaded files to detect malware.",
        "answer": False,
        "explain": "URL filtering decides based on the requested address/domain/category before content loads; it never examines payloads. Inspecting what the traffic actually contains — malware, file types, keywords, sensitive data — is content filtering, which for HTTPS requires TLS inspection.",
    },
    {
        "type": "tf",
        "q": "The term 'screened subnet' in N10-009 refers to what older materials call a DMZ or perimeter network.",
        "answer": True,
        "explain": "CompTIA's current blueprint uses 'screened subnet' for the buffer network hosting public-facing servers between the Internet and the LAN — built with two firewalls in series or a three-legged firewall. Recognize both names; 'DMZ' still appears widely in the field and in questions.",
    },
    # ---------------- Fill-in ----------------
    {
        "type": "fill",
        "q": "In 802.1X, the network device (switch or AP) that blocks the port and relays authentication is called the ____.",
        "answers": ["authenticator"],
        "explain": "The authenticator controls the port, permits only EAPoL until authentication succeeds, and shuttles EAP messages to the RADIUS authentication server, which makes the decision. The client requesting access is the supplicant.",
    },
    {
        "type": "fill",
        "q": "The framing protocol used between the supplicant and the authenticator on the wire in 802.1X is ____. (type the acronym)",
        "answers": ["EAPoL", "EAP over LAN", "EAPOL"],
        "explain": "EAP over LAN (EAPoL) carries the Extensible Authentication Protocol conversation across the LAN segment between client and switch/AP; the authenticator then encapsulates the same EAP exchange inside RADIUS toward the authentication server.",
    },
    {
        "type": "fill",
        "q": "The port security feature that saves dynamically learned MAC addresses into the switch configuration is called ____ MAC learning.",
        "answers": ["sticky", "sticky MAC"],
        "explain": "Sticky learning converts the first dynamically seen MAC address(es) into configured, persistent allowed entries — no manual typing of addresses, but the port is thereafter locked to those devices and any newcomer triggers the violation action.",
    },
    {
        "type": "fill",
        "q": "The invisible rule at the end of every ACL that drops all unmatched traffic is the implicit ____.",
        "answers": ["deny", "deny all", "deny any"],
        "explain": "The implicit deny enforces default-deny: anything you did not explicitly permit is dropped. It is also why an ACL consisting only of deny statements blocks everything, and why new ACLs often 'break' services that simply were never permitted.",
    },
    {
        "type": "fill",
        "q": "A trusted third party holding copies of encryption keys so data remains recoverable is known as key ____.",
        "answers": ["escrow"],
        "explain": "Key escrow trades a small confidentiality risk for recoverability: if the key holder departs, dies, or loses the key, the escrowed copy (for example, enterprise-held FDE recovery keys) prevents permanent data loss.",
    },
    {
        "type": "fill",
        "q": "The N10-009 term for the buffer network between the Internet and the internal LAN that hosts public-facing servers is the ____ subnet.",
        "answers": ["screened", "screened subnet", "DMZ"],
        "explain": "The screened subnet (legacy name: DMZ) sits between an external and an internal firewall — or on a third firewall interface — so Internet-facing servers can be reached without ever exposing the trusted LAN, and a compromised server stays contained in the buffer.",
    },
    # ---------------- Match ----------------
    {
        "type": "match",
        "q": "Match each 802.1X role to the device that typically plays it.",
        "pairs": [
            ["Supplicant", "The user's laptop running 802.1X client software"],
            ["Authenticator", "The access-layer switch or wireless AP"],
            ["Authentication server", "The RADIUS server checking Active Directory"],
            ["EAPoL", "The framing between client and switch on the LAN"],
        ],
        "explain": "802.1X splits port-based NAC into three roles plus the wire protocol: the supplicant asks, the authenticator gatekeeps and relays, and the authentication server decides. The supplicant-authenticator leg runs EAPoL; the authenticator-server leg runs EAP inside RADIUS.",
    },
    {
        "type": "match",
        "q": "Match each port security violation mode to its behavior.",
        "pairs": [
            ["Shutdown", "Port goes err-disabled and passes no traffic until re-enabled"],
            ["Restrict", "Drops offending frames, stays up, logs and alerts"],
            ["Protect", "Drops offending frames, stays up, no notification"],
            ["Sticky MAC", "Learned addresses saved to config as the allowed set"],
        ],
        "explain": "Shutdown (the default) is the most drastic — the whole port dies. Restrict and protect both drop only the offender's traffic and keep the port up; the sole difference is that restrict tells you about it while protect is silent. Sticky defines which MACs are allowed in the first place.",
    },
    {
        "type": "match",
        "q": "Match each security rule or zone concept to its description.",
        "pairs": [
            ["ACL", "Ordered permit/deny rules; first match wins; implicit deny at end"],
            ["URL filtering", "Blocks web requests by destination address or category"],
            ["Content filtering", "Inspects payloads for malware, file types, or banned material"],
            ["Trusted zone", "Internal network of managed, authenticated devices"],
            ["Untrusted zone", "External networks such as the Internet; assumed hostile"],
            ["Screened subnet", "Buffer network hosting public-facing servers between firewalls"],
        ],
        "explain": "These six items span the 'security rules' and 'zones' bullets of 4.3. ACLs work on packets (L3/L4), URL and content filtering work on web traffic (destination vs. payload), and zones organize the network by trust level with the screened subnet as the buffer for public services.",
    },
    # ---------------- Order ----------------
    {
        "type": "order",
        "q": "Arrange the 802.1X authentication sequence in the correct order.",
        "items": [
            "Device connects; the port allows only EAPoL traffic",
            "Supplicant sends identity/credentials via EAPoL to the authenticator",
            "Authenticator forwards the EAP exchange inside RADIUS to the authentication server",
            "Authentication server validates the credentials and returns accept (with optional VLAN/ACL)",
            "Authenticator opens the port for normal traffic",
        ],
        "explain": "Until authentication completes, the authenticator holds the port closed to everything except EAPoL. The switch never judges credentials itself — it relays them to RADIUS, which can also assign dynamic authorization (VLAN or ACL) before the port opens.",
    },
    {
        "type": "order",
        "q": "Arrange these hardening steps for a newly unboxed network device in the recommended order, from first to last.",
        "items": [
            "Change the default administrative credentials",
            "Update the firmware to the current patched version",
            "Disable unused services (Telnet, HTTP, SNMPv2c) in favor of secure ones",
            "Shut down unused physical ports and assign them to an unused VLAN",
            "Place the device into production and monitor its logs",
        ],
        "explain": "Credentials first — a device on the network with factory logins is already compromised-in-waiting. Then patch known vulnerabilities, shrink the logical attack surface (services), shrink the physical attack surface (ports), and only then deploy with ongoing monitoring.",
    },
    {
        "type": "order",
        "q": "A packet from the Internet is destined for a DMZ web server, which must then query an internal database. Arrange the path through a dual-firewall screened subnet design.",
        "items": [
            "Packet arrives from the untrusted Internet",
            "External firewall permits it only because it matches TCP 443 to the web server",
            "Web server in the screened subnet processes the request",
            "Internal firewall permits only the web server's specific database flow into the LAN",
            "Database server in the trusted zone returns the data",
        ],
        "explain": "Each firewall enforces least privilege at its boundary: the external firewall exposes only the published service, and the internal firewall allows only the narrow DMZ-to-LAN flow the application needs. The Internet never initiates directly into the trusted zone at any step.",
    },
]
