TOPIC = {
    "id": "5.1",
    "domain": 5,
    "title": "Explain the troubleshooting methodology",
    "short": "Troubleshooting Method",
}

TERMS = [
    ("Identify the problem", "Step 1 of the CompTIA methodology: gather information, question users, identify symptoms, determine if anything changed, duplicate the problem, approach multiple problems individually"),
    ("Establish a theory of probable cause", "Step 2: form a hypothesis about the cause; question the obvious and consider OSI top-to-bottom/bottom-to-top or divide and conquer approaches"),
    ("Test the theory", "Step 3: run a targeted test to confirm or disprove the theory; confirmed leads to next steps, unconfirmed leads to a new theory or escalation"),
    ("Establish a plan of action", "Step 4: plan the fix and identify potential effects, including change windows, impact on users, and rollback plans"),
    ("Implement the solution", "Step 5: execute the planned fix, changing one thing at a time, or escalate if it is beyond your skill or authority"),
    ("Verify full system functionality", "Step 6: confirm the entire system works end to end from the user's perspective and implement preventive measures"),
    ("Document findings", "Step 7 (final): record findings, actions, outcomes, and lessons learned in the ticket/knowledge base; notes are taken throughout the process"),
    ("Question users", "Step 1 activity: interview those reporting the issue with open-ended then closed questions to translate complaints into technical symptoms"),
    ("Question the obvious", "Step 2 habit: check simple likely causes first (unplugged cable, disabled port, wrong SSID) before exotic theories"),
    ("Determine if anything has changed", "Step 1 activity: check change logs and ask about recent modifications; recent change is the most common root cause"),
    ("Duplicate the problem", "Step 1 activity: reproduce the failure (ideally in a test environment) to verify symptoms and later prove the fix"),
    ("Approach multiple problems individually", "Step 1 principle: split simultaneously reported issues into separate problems and troubleshoot each independently"),
    ("Top-to-bottom approach", "Theory-building method that starts at OSI Layer 7 (application) and works down; suits application-specific symptoms"),
    ("Bottom-to-top approach", "Theory-building method that starts at OSI Layer 1 (physical) and works up; suits no-link/no-connectivity symptoms"),
    ("Divide and conquer", "Theory-building method that starts mid-OSI (often Layer 3 with ping) and moves up or down based on the test result"),
    ("Escalate", "Hand the problem to someone with more expertise, access, or authority; valid at step 3 (cannot confirm cause) and step 5 (cannot implement)"),
    ("Potential effects", "Step 4 consideration: possible impacts of the fix (downtime, affected users, risks) that drive scheduling and approval"),
    ("Preventive measures", "Step 6 additions that stop recurrence: monitoring, cable management, UPS, user training, tightened change control"),
    ("Rollback plan", "Pre-planned steps to undo a change if the fix fails; identified during step 4 planning"),
    ("Maintenance window", "Scheduled low-impact time period approved for implementing changes; part of the plan of action"),
    ("Root cause", "The underlying condition that produced the symptoms; fixing symptoms without the root cause invites recurrence"),
    ("Change management", "Formal process of approving and recording modifications; its logs answer the 'what changed?' question in step 1"),
]

QUESTIONS = [
    {
        "type": "order",
        "q": "Arrange the CompTIA 7-step troubleshooting methodology in the correct order.",
        "items": [
            "Identify the problem",
            "Establish a theory of probable cause",
            "Test the theory to determine the cause",
            "Establish a plan of action and identify potential effects",
            "Implement the solution or escalate",
            "Verify full system functionality and implement preventive measures",
            "Document findings, actions, outcomes, and lessons learned",
        ],
        "explain": "The 7 steps must be memorized in exact order: Identify, Establish theory, Test theory, Establish plan, Implement/escalate, Verify, Document. Exam questions constantly ask what a technician should do NEXT, which requires knowing this sequence cold.",
    },
    {
        "type": "order",
        "q": "A technician is working a ticket. Arrange these actions in the order the methodology requires.",
        "items": [
            "Ask the user what changed before the issue started",
            "Suspect a failed patch cable as the probable cause",
            "Swap in a known-good cable to see if the link returns",
            "Schedule the permanent cable replacement and note affected users",
            "Replace the damaged cable run",
            "Have the user confirm all applications work again",
            "Update the ticket with the root cause and resolution",
        ],
        "explain": "Each action maps to one step: questioning users (1), forming a theory (2), testing it (3), planning with potential effects (4), implementing (5), verifying functionality (6), and documenting (7). Recognizing real actions as steps is exactly how the exam tests the methodology.",
    },
    {
        "type": "order",
        "q": "Arrange these first-step activities in a logical troubleshooting flow for a new problem report.",
        "items": [
            "Gather information from logs and monitoring",
            "Question users about symptoms and recent changes",
            "Attempt to duplicate the problem",
            "Establish a theory of probable cause",
            "Test the theory",
        ],
        "explain": "Information gathering, questioning users, and duplicating the problem are all part of step 1 (identify the problem) and come before establishing a theory (step 2) and testing it (step 3). No changes are made during step 1.",
    },
    {
        "type": "order",
        "q": "Arrange what happens after a theory is CONFIRMED, in methodology order.",
        "items": [
            "Determine next steps to resolve the problem",
            "Establish a plan of action and identify potential effects",
            "Implement the solution",
            "Verify full system functionality",
            "Document findings and lessons learned",
        ],
        "explain": "When step 3 confirms the theory, you determine next steps, then formally plan the fix and its potential effects (step 4), implement (step 5), verify (step 6), and document (step 7). Implementation never comes before planning.",
    },
    {
        "type": "mc",
        "q": "A technician has just confirmed that a faulty switch uplink is the cause of an outage. According to the troubleshooting methodology, what should the technician do NEXT?",
        "choices": [
            "Replace the uplink module immediately",
            "Establish a plan of action and identify potential effects",
            "Document the findings in the ticket",
            "Escalate to the network architect",
        ],
        "answer": 1,
        "explain": "Confirming the cause completes step 3. Step 4 comes next: establish a plan of action and identify potential effects (downtime, change window, rollback). Jumping straight to implementation skips planning and is the classic trap answer.",
    },
    {
        "type": "mc",
        "q": "A technician swapped a suspect patch cable for a known-good one, but the user still has no connectivity. What should the technician do NEXT?",
        "choices": [
            "Establish a new theory of probable cause or escalate",
            "Establish a plan of action",
            "Document that the cable was not the cause and close the ticket",
            "Implement an alternative solution",
        ],
        "answer": 0,
        "explain": "The test disproved the theory. Step 3 says: if the theory is not confirmed, establish a new theory or escalate. You never proceed to planning or implementing based on a disproven theory, and the problem is not resolved so the ticket cannot close.",
    },
    {
        "type": "mc",
        "q": "Several users report an outage. The technician interviews them, reviews the change log, and reproduces the failure on a test laptop. What should the technician do NEXT?",
        "choices": [
            "Implement a fix on the affected switch",
            "Verify full system functionality",
            "Establish a theory of probable cause",
            "Establish a plan of action",
        ],
        "answer": 2,
        "explain": "Interviewing users, checking what changed, and duplicating the problem are all step 1 (identify the problem) activities. The next step in the methodology is step 2: establish a theory of probable cause.",
    },
    {
        "type": "mc",
        "q": "A technician replaced a failed router interface during an approved window and the link is now up. What should the technician do NEXT?",
        "choices": [
            "Document the actions taken and close the ticket",
            "Verify full system functionality and implement preventive measures",
            "Establish a theory of probable cause",
            "Identify potential effects of the change",
        ],
        "answer": 1,
        "explain": "Implementation (step 5) is complete, so step 6 follows: verify the entire system works from the user's perspective and add preventive measures. Documentation (step 7) only comes after functionality is verified.",
    },
    {
        "type": "mc",
        "q": "Users confirm that email and file shares work again after a fix, and the technician has enabled monitoring on the previously failed interface. What is the FINAL step the technician must complete?",
        "choices": [
            "Test the theory to determine cause",
            "Escalate to the vendor",
            "Establish a plan of action",
            "Document findings, actions, outcomes, and lessons learned",
        ],
        "answer": 3,
        "explain": "Verification and preventive measures complete step 6. The final step of the methodology is step 7: document findings, actions, outcomes, and lessons learned so the knowledge is available for future incidents.",
    },
    {
        "type": "mc",
        "q": "A help desk technician determines a problem requires configuration changes on the core router, which only the senior network team may touch. What should the technician do?",
        "choices": [
            "Make the change during lunch when traffic is low",
            "Escalate to the senior network team",
            "Document the issue and close the ticket",
            "Establish a new theory that avoids the core router",
        ],
        "answer": 1,
        "explain": "Step 5 is 'implement the solution OR escalate as necessary.' When the fix is beyond your authority or access, escalation to the appropriate team is the correct action, not an unauthorized change or abandoning the problem.",
    },
    {
        "type": "mc",
        "q": "A user reports that printing, email, and VPN all stopped working this morning. How should the technician approach this report?",
        "choices": [
            "Treat all three as one problem since they started together",
            "Fix the easiest issue first and assume the rest share its cause",
            "Approach each problem individually",
            "Escalate immediately because multiple systems are involved",
        ],
        "answer": 2,
        "explain": "The methodology's step 1 explicitly says to approach multiple problems individually. They may turn out to share a root cause, but that conclusion must come from evidence, not assumption. Bundling unrelated symptoms leads to false theories.",
    },
    {
        "type": "mc",
        "q": "While identifying a problem, which question is generally the MOST valuable to ask first?",
        "choices": [
            "Has anything changed recently?",
            "Have you tried rebooting?",
            "What operating system are you running?",
            "Is anyone else having this problem?",
        ],
        "answer": 0,
        "explain": "Determining whether anything has changed is a listed sub-task of step 1 and the highest-yield diagnostic question, because recent changes (updates, new rules, moved equipment) are the most common cause of sudden failures. Scope questions matter too, but 'what changed?' points directly at root cause.",
    },
    {
        "type": "mc",
        "q": "A technician pings the remote server's IP successfully but pinging by hostname fails, so the technician focuses on DNS and the layers above. Which troubleshooting approach is this?",
        "choices": [
            "Bottom-to-top OSI",
            "Divide and conquer",
            "Question the obvious",
            "Top-to-bottom OSI",
        ],
        "answer": 1,
        "explain": "Divide and conquer starts in the middle of the OSI model (commonly Layer 3 with ping) and moves up or down based on results. A successful IP ping rules out Layers 1-3, so the technician moves up toward DNS/application issues.",
    },
    {
        "type": "mc",
        "q": "A user's PC has no network access at all. The technician first checks the patch cable, link lights, and NIC, then moves up to IP configuration. Which approach is being used?",
        "choices": [
            "Divide and conquer",
            "Top-to-bottom",
            "Bottom-to-top",
            "Trial and error",
        ],
        "answer": 2,
        "explain": "Starting at Layer 1 (cables, link lights, hardware) and working upward is the bottom-to-top OSI approach. It suits total-connectivity failures, where physical causes are most likely.",
    },
    {
        "type": "mc",
        "q": "Only one web application is failing for a user; everything else works. The technician starts by checking the browser and application settings, then works downward. Which approach is this?",
        "choices": [
            "Top-to-bottom OSI",
            "Bottom-to-top OSI",
            "Divide and conquer",
            "Question the obvious",
        ],
        "answer": 0,
        "explain": "Starting at Layer 7 (the application) and working down is the top-to-bottom approach. It fits symptoms confined to a single application while all other connectivity works, since the lower layers are demonstrably fine.",
    },
    {
        "type": "mc",
        "q": "A technician theorizes an OSPF routing failure is causing a user's outage, spending an hour on router configs, before noticing the user's dock cable was unplugged. Which step 2 principle did the technician skip?",
        "choices": [
            "Divide and conquer",
            "Question the obvious",
            "Duplicate the problem",
            "Identify potential effects",
        ],
        "answer": 1,
        "explain": "Step 2 says to question the obvious first: simple, likely causes such as unplugged cables, disabled ports, or wrong SSIDs. A huge share of incidents are trivial physical issues that a quick check would find before deep-diving into complex theories.",
    },
    {
        "type": "mc",
        "q": "Which activity belongs to Step 4, establish a plan of action?",
        "choices": [
            "Interviewing users about symptoms",
            "Identifying potential effects and preparing a rollback plan",
            "Swapping a cable to confirm the cause",
            "Recording lessons learned",
        ],
        "answer": 1,
        "explain": "Step 4 covers planning the fix, identifying potential effects (impact, downtime), scheduling maintenance windows, and preparing rollback plans. Interviews are step 1, confirmation tests step 3, and lessons learned step 7.",
    },
    {
        "type": "mc",
        "q": "During which TWO steps does the methodology explicitly allow escalation?",
        "choices": [
            "Steps 1 and 2",
            "Steps 2 and 6",
            "Steps 3 and 5",
            "Steps 6 and 7",
        ],
        "answer": 2,
        "explain": "Escalation appears in step 3 (if the theory cannot be confirmed, establish a new theory or escalate) and step 5 (implement the solution or escalate as necessary). Knowing both escalation points resolves many tricky NEXT-step questions.",
    },
    {
        "type": "mc",
        "q": "Why should a technician attempt to duplicate a problem during Step 1?",
        "choices": [
            "It immediately reveals the root cause",
            "It verifies symptoms first-hand and later helps prove the fix worked",
            "It is required before a ticket can be opened",
            "It transfers the problem to the test environment permanently",
        ],
        "answer": 1,
        "explain": "Duplicating the problem (ideally in a lab or test setting) confirms the reported symptoms objectively and provides a repeatable test case, so after implementing a fix you can demonstrate the failure no longer occurs. It does not by itself identify the cause.",
    },
    {
        "type": "mc",
        "q": "After a fix, which action BEST demonstrates 'verify full system functionality'?",
        "choices": [
            "The link light on the switch port is green",
            "The technician can ping the default gateway",
            "The user confirms their complete workflow, and adjacent systems are checked",
            "The configuration was saved to startup",
        ],
        "answer": 2,
        "explain": "Full system functionality means end-to-end verification from the user's perspective plus confirming nothing else broke. A green link light or one successful ping only proves a small slice of the stack is working.",
    },
    {
        "type": "mc",
        "q": "Which of the following is the BEST example of implementing a preventive measure in Step 6?",
        "choices": [
            "Writing the root cause in the ticket",
            "Adding UPS protection and interface monitoring so the failure is prevented or caught early",
            "Asking the user what changed",
            "Rebooting the switch weekly without investigating why it hangs",
        ],
        "answer": 1,
        "explain": "Preventive measures reduce the chance or impact of recurrence: UPS for power-related failures, monitoring/alerting, cable management, user training. Documentation is step 7, questioning users is step 1, and blind scheduled reboots treat symptoms rather than prevent causes.",
    },
    {
        "type": "mc",
        "q": "When should a technician take notes and record information during a troubleshooting incident?",
        "choices": [
            "Only after the problem is resolved",
            "Only if the problem gets escalated",
            "Only during the identification step",
            "Throughout the entire process, with formal documentation as the final step",
        ],
        "answer": 3,
        "explain": "CompTIA's wording is to document findings, actions, outcomes, and lessons learned 'throughout the process.' You gather notes at every step, and the formal write-up in the ticket/knowledge base is completed as step 7.",
    },
    {
        "type": "mc",
        "q": "Why does the methodology recommend changing only one thing at a time when implementing or testing?",
        "choices": [
            "It reduces the paperwork required",
            "Multiple simultaneous changes require manager approval",
            "It is faster than making several changes",
            "If the problem resolves, you know exactly which change fixed it",
        ],
        "answer": 3,
        "explain": "Changing one variable at a time isolates cause and effect: when the symptom clears you know which change worked, and unnecessary changes (each a new risk) are avoided. Shotgunning multiple changes can fix the issue while leaving you unable to explain or document why.",
    },
    {
        "type": "mc",
        "q": "The service desk receives a new report that sounds similar to an existing open ticket. What is the best practice?",
        "choices": [
            "Merge it into the existing ticket automatically",
            "Treat it as a separate problem until evidence shows a shared root cause",
            "Ignore it since it is already being worked",
            "Escalate both tickets immediately",
        ],
        "answer": 1,
        "explain": "Approach multiple problems individually: similar-sounding symptoms can have unrelated causes. Investigate separately, and only consolidate when the evidence demonstrates the same root cause.",
    },
    {
        "type": "mc",
        "q": "A planned fix requires rebooting a core switch that serves 300 users. In which step should the technician have identified this impact and scheduled a maintenance window?",
        "choices": [
            "Establish a plan of action and identify potential effects",
            "Test the theory",
            "Identify the problem",
            "Verify full system functionality",
        ],
        "answer": 0,
        "explain": "Step 4 explicitly pairs the plan of action with identifying potential effects. Understanding impact (300 users offline) drives scheduling a change window, notification, and rollback planning before any implementation occurs.",
    },
    {
        "type": "tf",
        "q": "In the CompTIA methodology, establishing a theory of probable cause comes before testing the theory.",
        "answer": True,
        "explain": "Step 2 is establishing the theory; step 3 is testing it to determine the cause. You hypothesize first, then run a targeted test to confirm or disprove.",
    },
    {
        "type": "tf",
        "q": "If a fix has been implemented and appears to work, the technician can skip verification and go straight to documentation.",
        "answer": False,
        "explain": "Step 6, verify full system functionality and implement preventive measures, always precedes documentation. 'Appears to work' is not verification; the user must confirm end-to-end functionality and adjacent systems must be checked.",
    },
    {
        "type": "tf",
        "q": "Escalating a problem means the technician has failed to follow the troubleshooting methodology.",
        "answer": False,
        "explain": "Escalation is built into the methodology at steps 3 and 5. Recognizing when a problem exceeds your expertise, access, or authority and handing it to the right team is correct procedure, not failure.",
    },
    {
        "type": "tf",
        "q": "The divide and conquer approach typically begins by testing at a middle OSI layer, such as using ping at Layer 3.",
        "answer": True,
        "explain": "Divide and conquer starts mid-stack: a successful ping instantly clears Layers 1-3 so you move up; a failed ping sends you down. It is often the fastest approach when you have a hint about the problem.",
    },
    {
        "type": "tf",
        "q": "During Step 1 (identify the problem), the technician should begin making configuration changes to see what fixes the issue.",
        "answer": False,
        "explain": "Step 1 is pure information gathering: questioning users, identifying symptoms, determining what changed, duplicating the problem. No changes are made until a theory is formed, tested, and a plan is established.",
    },
    {
        "type": "tf",
        "q": "A rollback (backout) plan should be prepared as part of establishing the plan of action.",
        "answer": True,
        "explain": "Step 4 includes identifying potential effects, and a rollback plan is the safety net if the implemented fix fails or causes new problems. This ties directly into formal change management practices.",
    },
    {
        "type": "fill",
        "q": "The first step of the CompTIA troubleshooting methodology is to ________ the problem. (type your answer)",
        "answers": ["identify"],
        "explain": "Step 1 is 'Identify the problem,' which includes gathering information, questioning users, identifying symptoms, determining if anything changed, duplicating the problem if possible, and approaching multiple problems individually.",
    },
    {
        "type": "fill",
        "q": "If a theory is not confirmed during testing, the technician should establish a new theory or ________. (type your answer)",
        "answers": ["escalate", "escalate the problem"],
        "explain": "Step 3's failure branch offers exactly two options: form a new theory of probable cause or escalate to someone with more expertise or access. Proceeding to plan or implement on a disproven theory is never correct.",
    },
    {
        "type": "fill",
        "q": "The final step of the methodology is to ________ findings, actions, outcomes, and lessons learned. (type your answer)",
        "answers": ["document", "record"],
        "explain": "Step 7 is documentation: recording the problem, root cause, actions, outcome, and lessons learned in the ticketing system or knowledge base. Notes are taken throughout, but formal documentation closes the process.",
    },
    {
        "type": "fill",
        "q": "The troubleshooting approach that starts at OSI Layer 1 and works upward is called ________-to-top. (type your answer)",
        "answers": ["bottom", "bottom to top", "bottom-to-top"],
        "explain": "Bottom-to-top starts with physical checks (cables, link lights, transceivers) and climbs the OSI model. It is the natural choice when a device has no connectivity at all, since total failures are most often physical.",
    },
    {
        "type": "fill",
        "q": "In Step 4, along with establishing a plan of action, the technician must identify potential ________. (type your answer)",
        "answers": ["effects", "impacts"],
        "explain": "CompTIA words step 4 as 'establish a plan of action to resolve the problem and identify potential effects.' Effects include downtime, users impacted, and risks, which drive change approval, scheduling, and rollback planning.",
    },
    {
        "type": "match",
        "q": "Match each technician action to the methodology step it belongs to.",
        "pairs": [
            ["Asking a user what changed before the failure", "Step 1: Identify the problem"],
            ["Suspecting a duplex mismatch as the likely cause", "Step 2: Establish a theory"],
            ["Swapping in a known-good cable to check the link", "Step 3: Test the theory"],
            ["Scheduling a maintenance window and rollback plan", "Step 4: Establish a plan of action"],
            ["Having the user confirm all applications work", "Step 6: Verify full functionality"],
            ["Writing lessons learned into the knowledge base", "Step 7: Document findings"],
        ],
        "explain": "Each concrete action maps to a step: questioning users is identification, hypothesizing is theory, a quick confirmation check is testing, scheduling and rollback are planning, user confirmation is verification, and lessons learned are documentation.",
    },
    {
        "type": "match",
        "q": "Match each troubleshooting approach to its description.",
        "pairs": [
            ["Bottom-to-top", "Start at the physical layer and work up the OSI model"],
            ["Top-to-bottom", "Start at the application layer and work down the OSI model"],
            ["Divide and conquer", "Start at a middle layer and move up or down based on test results"],
            ["Question the obvious", "Check simple likely causes such as unplugged cables first"],
        ],
        "explain": "These are the step 2 approaches. Bottom-up suits total connectivity loss, top-down suits single-application failures, divide and conquer is fastest with a hint (ping at Layer 3), and questioning the obvious catches trivial causes before deep analysis.",
    },
    {
        "type": "match",
        "q": "Match each Step 1 sub-task to its purpose.",
        "pairs": [
            ["Gather information", "Collect logs, error messages, and scope data"],
            ["Question users", "Translate reported complaints into technical symptoms"],
            ["Determine if anything changed", "Check change logs for recent modifications"],
            ["Duplicate the problem", "Reproduce the failure to verify and later prove the fix"],
            ["Approach problems individually", "Keep simultaneous issues as separate investigations"],
        ],
        "explain": "All five are named sub-bullets of step 1, identify the problem. Together they define the problem objectively before any theory is formed or any change is made.",
    },
    {
        "type": "match",
        "q": "Match each situation to the correct methodology response.",
        "pairs": [
            ["Theory confirmed by testing", "Determine next steps, then establish a plan of action"],
            ["Theory disproven by testing", "Establish a new theory or escalate"],
            ["Fix requires access you do not have", "Escalate to the appropriate team"],
            ["Fix implemented and users confirm success", "Implement preventive measures, then document"],
        ],
        "explain": "These are the methodology's decision branches: confirmation flows into planning, refutation loops back to theory or escalates, authority limits trigger escalation at implementation, and success flows through verification/prevention into final documentation.",
    },
]
