TOPIC = {
    "id": "5.2",
    "domain": 5,
    "title": "Given a scenario, troubleshoot common cabling and physical interface issues",
    "short": "Cabling & Physical",
}

TERMS = [
    ("Single-mode fiber", "Small ~9 micron core using laser light at 1310/1550 nm; long-distance runs (km); typically yellow jacket"),
    ("Multimode fiber", "Larger 50/62.5 micron core using LED/VCSEL at 850 nm; short-reach runs (hundreds of meters); orange or aqua jacket"),
    ("Cat 5e", "Twisted-pair category rated for 1 Gbps at 100 m with 100 MHz bandwidth; improved crosstalk specs over Cat 5"),
    ("Cat 6", "Twisted-pair category rated 250 MHz; 1 Gbps at 100 m but 10 Gbps only to about 55 m"),
    ("Cat 6a", "Augmented Cat 6 rated 500 MHz; supports 10 Gbps for the full 100 m; resists alien crosstalk"),
    ("Cat 8", "Data-center twisted-pair rated 2000 MHz (2 GHz); 25/40 Gbps but only to about 30 m; shielded"),
    ("STP", "Shielded twisted pair; foil/braid shielding blocks EMI in noisy environments (motors, fluorescent lights); shield must be grounded"),
    ("UTP", "Unshielded twisted pair; relies on pair twisting alone to reject noise; cheaper and easier to terminate"),
    ("Crosstalk", "Signal coupling between adjacent wire pairs; NEXT is measured at the transmitter end, FEXT at the far end; twists mitigate it"),
    ("EMI", "Electromagnetic interference from motors, fluorescent ballasts, elevators; causes intermittent errors; fix by rerouting, STP, or fiber"),
    ("Attenuation", "Loss of signal strength over distance, measured in dB; copper Ethernet limited to 100 m; fix with repeaters, shorter runs, or fiber"),
    ("Improper termination", "Wiring faults at plug/jack/punchdown: opens, shorts, miswires, split pairs; detected with a cable tester/wiremap"),
    ("Split pair", "Termination fault where pins are correct but wires use wrong twisted partners; passes basic wiremap yet causes severe crosstalk"),
    ("TX/RX transposed", "Transmit and receive reversed; auto-MDI-X corrects it on copper; on fiber, swap the two strands (polarity) at one end"),
    ("Auto-MDI-X", "Interface feature that automatically detects and swaps TX/RX pairs, making crossover vs. straight-through cables irrelevant"),
    ("CRC errors", "Interface counter for frames failing the checksum (corrupted in transit); caused by bad cabling, EMI, duplex mismatch, failing hardware"),
    ("Runt", "Frame smaller than the 64-byte Ethernet minimum; typically caused by collisions or a duplex mismatch"),
    ("Giant", "Frame larger than the standard 1518-byte Ethernet maximum; typically an MTU/jumbo-frame mismatch"),
    ("Drops (discards)", "Frames discarded because buffers/queues are full; indicate congestion or oversubscription, not corruption"),
    ("Duplex mismatch", "One side full duplex, other half; link works but is slow with late collisions, runts, and CRC errors; set both sides to auto"),
    ("Error disabled", "Port state where the switch automatically shut the port after a violation (port security, BPDU guard); fix cause then shut/no shut"),
    ("Administratively down", "Port deliberately disabled with the shutdown command in configuration; re-enable with no shutdown"),
    ("Suspended (port)", "Port not forwarding due to a negotiation/consistency failure, commonly an LACP/EtherChannel parameter mismatch"),
    ("802.3af", "Original PoE, Type 1: 15.4 W at the PSE port, 12.95 W available to the powered device"),
    ("802.3at", "PoE+, Type 2: 30 W at the PSE port, 25.5 W available to the powered device"),
    ("802.3bt", "PoE++: Type 3 delivers 60 W at the PSE (51 W to PD); Type 4 delivers 90 W (71.3 W to PD) using all four pairs"),
    ("PoE power budget", "Total wattage a switch can supply across all ports; exceeding it causes devices to fail to power or randomly reboot"),
    ("Transceiver mismatch", "Ends of a link using incompatible optics: different wavelength, single-mode vs. multimode, or different speeds; link fails"),
    ("Light meter", "Optical power meter measuring received fiber signal in dBm; compares actual loss against the link's loss budget"),
    ("Attenuator", "Inline device that reduces optical power when a strong transceiver overloads the receiver on a short fiber run"),
]

QUESTIONS = [
    {
        "type": "mc",
        "q": "A technician connects two buildings 2 km apart, but the fiber link will not come up. The patch cable at one end has a yellow jacket and the transceiver at the other end is an 850 nm multimode optic. What is the MOST likely problem?",
        "choices": [
            "The fiber run exceeds single-mode distance limits",
            "Single-mode and multimode components are mismatched",
            "The transceivers are drawing too much PoE power",
            "TX and RX are transposed",
        ],
        "answer": 1,
        "explain": "Yellow jacket indicates single-mode fiber, while 850 nm optics are multimode. Core sizes and wavelengths do not match, so the link fails. Both ends must use the same fiber type with matching transceivers; 2 km also exceeds typical multimode reach anyway.",
    },
    {
        "type": "mc",
        "q": "A new workstation drop is 80 m from the closet and must support 10 Gbps over copper. Which is the MINIMUM cable category that meets the requirement?",
        "choices": [
            "Cat 5e",
            "Cat 6",
            "Cat 6a",
            "Cat 8",
        ],
        "answer": 2,
        "explain": "Cat 6 carries 10GBASE-T only to about 55 m; at 80 m you need Cat 6a, which supports 10 Gbps for the full 100 m at 500 MHz. Cat 8 also could, but it is limited to 30 m and intended for data centers, and Cat 5e tops out at 1 Gbps.",
    },
    {
        "type": "mc",
        "q": "Users on a factory floor report intermittent network errors that worsen when large motors run. The cabling is UTP routed above the machinery. Which is the BEST fix?",
        "choices": [
            "Replace the runs with shielded twisted pair or fiber",
            "Increase the switchport speed to 10 Gbps",
            "Enable jumbo frames on the switch",
            "Shorten the DHCP lease time",
        ],
        "answer": 0,
        "explain": "Motors generate EMI that couples into unshielded copper, corrupting frames intermittently. STP (properly grounded) resists EMI, and fiber is completely immune; rerouting away from the interference source also helps. Speed and DHCP settings are unrelated.",
    },
    {
        "type": "mc",
        "q": "A 120 m UTP run to a far office has a flaky link with many errors, while shorter runs from the same switch are fine. What is the MOST likely cause?",
        "choices": [
            "Attenuation from exceeding the 100 m distance limit",
            "A duplex mismatch on the switchport",
            "Crosstalk from bundled cables",
            "An exhausted PoE budget",
        ],
        "answer": 0,
        "explain": "Twisted-pair Ethernet is specified to 100 m; at 120 m attenuation weakens the signal enough to cause errors or link failure. The fix is to shorten the run, add a repeater/switch mid-span, or use fiber.",
    },
    {
        "type": "mc",
        "q": "A cable's wiremap test passes pin-for-pin, yet the gigabit link is slow and error-prone with high crosstalk readings. What termination fault does this indicate?",
        "choices": [
            "Open pair",
            "Short circuit",
            "Split pair",
            "Reversed pair",
        ],
        "answer": 2,
        "explain": "A split pair lands wires on the correct pins but with the wrong twisted partners, destroying the crosstalk cancellation the twists provide. Basic continuity testers pass it because pin-to-pin connectivity is correct; only crosstalk-capable testers catch it. Re-termination is the fix.",
    },
    {
        "type": "mc",
        "q": "One end of a patch cable was terminated to T568A and the other end to T568B. What has the installer created?",
        "choices": [
            "A rollover cable",
            "A crossover cable",
            "A straight-through cable",
            "A split-pair cable",
        ],
        "answer": 1,
        "explain": "T568A and T568B swap the green and orange pairs, so mixing standards across ends swaps TX and RX — the definition of a crossover cable. For a straight-through cable both ends must use the same standard. On modern auto-MDI-X gear it may still work, but it is a miswire if unintended.",
    },
    {
        "type": "mc",
        "q": "A new duplex fiber link between two switches shows no link, though technicians verified light leaves the transmitter on each end. What should be done FIRST?",
        "choices": [
            "Replace both transceivers",
            "Swap the A/B fiber strands at one end",
            "Install an attenuator",
            "Clean the connectors with alcohol wipes",
        ],
        "answer": 1,
        "explain": "Light leaving both transmitters but no link is the signature of transposed TX/RX (reversed polarity): each transmitter is aimed at the other's transmitter. Flipping the strand pair at one end aligns TX to RX. This is the classic fiber polarity question.",
    },
    {
        "type": "mc",
        "q": "Two older switches are connected with a straight-through cable and get no link. Connecting the same ports with a crossover cable works. What feature is missing on these switches?",
        "choices": [
            "Auto-MDI-X",
            "LACP",
            "PoE",
            "Spanning tree",
        ],
        "answer": 0,
        "explain": "Auto-MDI-X automatically detects and electrically swaps TX/RX so either cable type works. Without it, like devices (switch to switch) need a crossover cable to cross the transmit and receive pairs. Modern gigabit interfaces almost always include auto-MDI-X.",
    },
    {
        "type": "mc",
        "q": "An interface shows steadily increasing CRC errors and runts, and users report very slow transfers. The port is hard-coded to full duplex while the connected NIC autonegotiates. What is the MOST likely cause?",
        "choices": [
            "Jumbo frames enabled on one side",
            "An exceeded PoE budget",
            "Duplex mismatch",
            "Incorrect VLAN assignment",
        ],
        "answer": 2,
        "explain": "When one side is hard-coded full duplex, the autonegotiating side falls back to half duplex, producing late collisions that appear as runts and CRC errors with terrible throughput. Set both sides to autonegotiate or hard-code both identically.",
    },
    {
        "type": "mc",
        "q": "An interface counter shows many giants. What is the MOST likely cause?",
        "choices": [
            "Collisions on a half-duplex segment",
            "An MTU/jumbo-frame mismatch between devices",
            "Electromagnetic interference from lighting",
            "A broadcast storm",
        ],
        "answer": 1,
        "explain": "Giants are frames larger than the standard 1518-byte maximum, which typically means one device is sending jumbo frames while the receiving interface is not configured for them. Make the MTU consistent end to end. Collisions produce runts, not giants.",
    },
    {
        "type": "mc",
        "q": "A switch interface shows increasing output drops but zero CRC errors. What does this indicate?",
        "choices": [
            "A corrupted cable run",
            "Congestion causing buffer overruns on the interface",
            "A failing transceiver",
            "TX/RX transposed",
        ],
        "answer": 1,
        "explain": "Drops/discards mean the interface's queues filled and frames were discarded — a congestion/oversubscription symptom. Corruption problems (bad cable, transceiver, EMI) would show CRC or input errors instead. The fix is more bandwidth, QoS, or resolving the bottleneck.",
    },
    {
        "type": "mc",
        "q": "Immediately after a user plugged a personal 5-port switch into their wall jack, that switchport went down and shows err-disabled. Which feature MOST likely triggered this?",
        "choices": [
            "BPDU guard",
            "Auto-MDI-X",
            "PoE policing",
            "Flow control",
        ],
        "answer": 0,
        "explain": "BPDU guard err-disables an access port that receives spanning-tree BPDUs, which the personal switch would send. Port security (unexpected MAC addresses) is the other common trigger. The correct response is to remove the offending device, then re-enable the port with shutdown/no shutdown.",
    },
    {
        "type": "mc",
        "q": "A port shows 'administratively down.' What does this mean?",
        "choices": [
            "The switch disabled the port after a security violation",
            "An administrator deliberately shut the port down in configuration",
            "The port failed LACP negotiation",
            "The cable is unplugged",
        ],
        "answer": 1,
        "explain": "Administratively down means the shutdown command is present in the port's configuration — a human turned it off on purpose. If the port should be live, issue no shutdown. Contrast with err-disabled (switch-triggered protection) and suspended (negotiation failure).",
    },
    {
        "type": "mc",
        "q": "One member port of a four-port LACP EtherChannel shows a 'suspended' state. What is the MOST likely cause?",
        "choices": [
            "The port's speed, duplex, or VLAN settings do not match the other bundle members",
            "The cable exceeds 100 m",
            "BPDU guard triggered on the port",
            "The port is drawing too much PoE power",
        ],
        "answer": 0,
        "explain": "A suspended state typically means the port failed the port-channel's compatibility checks — its parameters (speed, duplex, allowed VLANs, mode) differ from the bundle. Align the member's configuration with the channel and it will rejoin.",
    },
    {
        "type": "mc",
        "q": "How much power does an 802.3at (PoE+) switchport supply, and how much is guaranteed to reach the powered device?",
        "choices": [
            "15.4 W supplied, 12.95 W delivered",
            "30 W supplied, 25.5 W delivered",
            "60 W supplied, 51 W delivered",
            "90 W supplied, 71.3 W delivered",
        ],
        "answer": 1,
        "explain": "802.3at PoE+ (Type 2) sources 30 W per port with 25.5 W guaranteed at the device after cable losses. 15.4/12.95 W is 802.3af, 60/51 W is 802.3bt Type 3, and 90/71.3 W is 802.3bt Type 4.",
    },
    {
        "type": "mc",
        "q": "A pan-tilt-zoom camera requires 55 W. Which PoE standard is the MINIMUM that can power it?",
        "choices": [
            "802.3af Type 1",
            "802.3at Type 2",
            "802.3bt Type 3",
            "802.3bt Type 4",
        ],
        "answer": 2,
        "explain": "802.3bt Type 3 (PoE++) sources 60 W per port (51 W at the device over four pairs), covering a 55 W sourcing need where af (15.4 W) and at (30 W) cannot. Type 4 (90 W) also works but is more than the minimum required.",
    },
    {
        "type": "mc",
        "q": "After ten additional PoE access points were installed, security cameras on the same switch began rebooting randomly and two new APs will not power on. What should the technician check FIRST?",
        "choices": [
            "The spanning-tree root bridge election",
            "The switch's total PoE power budget with show power inline",
            "The VLAN assignment of the camera ports",
            "The DHCP scope utilization",
        ],
        "answer": 1,
        "explain": "Random reboots and devices failing to power right after adding many powered devices are the signature of an exceeded PoE power budget. show power inline reveals total budget, used, remaining, and per-port draw. Fixes include a larger supply, spreading PDs across switches, or priority settings.",
    },
    {
        "type": "mc",
        "q": "A Wi-Fi 6 access point rated for 802.3at power boots but disables one radio and logs low-power warnings when connected to an older switch. What is the MOST likely cause?",
        "choices": [
            "The switchport only supplies 802.3af power",
            "The AP is in the wrong VLAN",
            "The cable is a crossover",
            "The AP's transceiver wavelength is mismatched",
        ],
        "answer": 0,
        "explain": "This is the 'incorrect standard' PoE problem: the AP needs 25.5 W (802.3at) but the port delivers only 12.95 W (802.3af), so the AP enters a degraded low-power mode and shuts down features like a radio. Use an 802.3at/bt port or a compatible power injector.",
    },
    {
        "type": "mc",
        "q": "A fiber link comes up but takes constant errors. The transceiver's DDM readings show receive power well below the specified minimum. Which is NOT a likely cause?",
        "choices": [
            "Dirty or scratched connectors",
            "A tight bend in the fiber run",
            "The run is too long for the optic's rated distance",
            "The transmit power is too strong for the receiver",
        ],
        "answer": 3,
        "explain": "Low receive power comes from excess loss: dirty/damaged connectors (the most common real-world cause), macrobends, splices, or exceeding the optic's distance rating. Excessive transmit power causes the opposite problem — receiver overload — which is fixed with an attenuator.",
    },
    {
        "type": "mc",
        "q": "Two switches in the same rack are linked with long-haul single-mode transceivers over a 2 m patch cable, and the link takes errors. What is the recommended fix?",
        "choices": [
            "Replace the patch with multimode fiber",
            "Install an inline optical attenuator",
            "Enable jumbo frames",
            "Swap TX and RX strands",
        ],
        "answer": 1,
        "explain": "Long-reach optics transmit at high power; over a very short run the receiver is overloaded (saturated), causing errors. An inline attenuator reduces the signal into the receiver's accepted range. More power is not always better on fiber links.",
    },
    {
        "type": "mc",
        "q": "A gigabit-capable PC negotiates only 100 Mbps on a run recently re-terminated by an electrician. The cable tester shows an open on pins 7 and 8. Why does the link still work at 100 Mbps?",
        "choices": [
            "100BASE-TX uses only two pairs, while 1000BASE-T requires all four",
            "The switch limits new devices to 100 Mbps",
            "Auto-MDI-X disables two pairs by default",
            "100 Mbps links tolerate open circuits on any pair",
        ],
        "answer": 0,
        "explain": "Fast Ethernet (100BASE-TX) uses two pairs, so a cable with a damaged third or fourth pair still links at 100 Mbps. Gigabit (1000BASE-T) needs all four pairs, so autonegotiation falls back. An open pair found by the wiremap means the run must be re-terminated or replaced.",
    },
    {
        "type": "mc",
        "q": "Which cable category supports 25/40 Gbps but only up to about 30 meters, making it suited for data-center switch-to-server links?",
        "choices": [
            "Cat 6a",
            "Cat 7",
            "Cat 8",
            "Cat 5e",
        ],
        "answer": 2,
        "explain": "Cat 8 operates at 2000 MHz (2 GHz) and delivers 25/40GBASE-T, but attenuation at those frequencies limits it to roughly 30 m — fine for top-of-rack data-center runs, not for 100 m horizontal cabling. Cat 6a is the 10G/100 m workhorse and Cat 7 is a shielded 600 MHz standard.",
    },
    {
        "type": "tf",
        "q": "A runt is an Ethernet frame smaller than 64 bytes, and a giant is a frame larger than 1518 bytes.",
        "answer": True,
        "explain": "64 bytes is the minimum legal Ethernet frame size and 1518 bytes the standard maximum (1522 with an 802.1Q tag). Runts usually indicate collisions/duplex mismatch; giants usually indicate an MTU or jumbo-frame mismatch.",
    },
    {
        "type": "tf",
        "q": "Single-mode fiber typically uses 850 nm light and is best suited for short runs inside a data center.",
        "answer": False,
        "explain": "That describes multimode fiber. Single-mode has a tiny ~9 micron core, uses 1310/1550 nm laser light, and spans kilometers. Multimode's larger core with 850 nm sources covers short reach such as intra-building and data-center runs.",
    },
    {
        "type": "tf",
        "q": "Because Cat 6 is rated for 10 Gbps, it can carry 10GBASE-T for the full 100 m channel.",
        "answer": False,
        "explain": "Cat 6 supports 10GBASE-T only to about 55 m under good conditions; beyond that, alien crosstalk and attenuation are too high. Cat 6a (500 MHz) is required for 10 Gbps at the full 100 m.",
    },
    {
        "type": "tf",
        "q": "An err-disabled port should simply be re-enabled with shutdown/no shutdown without any further investigation.",
        "answer": False,
        "explain": "Err-disabled means the switch detected a violation such as port security or BPDU guard. Re-enabling without removing the cause just triggers the violation again. Investigate and fix the underlying issue first, then bounce the port (or use errdisable auto-recovery).",
    },
    {
        "type": "tf",
        "q": "NEXT (near-end crosstalk) is measured at the same end of the cable as the transmitter, and excessive untwisting at a termination is a common cause.",
        "answer": True,
        "explain": "NEXT measures coupling from a transmitting pair into an adjacent pair at the near end; FEXT measures it at the far end. Maintaining pair twists to within about 13 mm (0.5 in) of the termination preserves the cancellation that keeps crosstalk low.",
    },
    {
        "type": "tf",
        "q": "STP cable shielding must be properly grounded to be effective against EMI.",
        "answer": True,
        "explain": "An ungrounded or improperly grounded shield can act as an antenna and make interference worse. Shielded systems need shielded jacks, plugs, and a proper ground path end to end.",
    },
    {
        "type": "fill",
        "q": "An Ethernet frame larger than 1518 bytes is counted as a ________ on the interface. (type your answer)",
        "answers": ["giant", "giant frame"],
        "explain": "Giants exceed the standard maximum frame size and usually point to a jumbo-frame/MTU mismatch, where one side sends large frames the other side is not configured to accept.",
    },
    {
        "type": "fill",
        "q": "802.3af PoE supplies ________ watts at the switchport. (type your answer)",
        "answers": ["15.4", "15.4w", "15.4 watts"],
        "explain": "802.3af (Type 1) sources 15.4 W per port, delivering 12.95 W to the powered device after cable loss. PoE+ (802.3at) raises this to 30 W, and 802.3bt reaches 60 W (Type 3) and 90 W (Type 4).",
    },
    {
        "type": "fill",
        "q": "The loss of signal strength as it travels down a cable, measured in dB, is called ________. (type your answer)",
        "answers": ["attenuation"],
        "explain": "Attenuation increases with distance and frequency, which is why copper Ethernet is limited to 100 m and Cat 8's 2 GHz signaling only reaches 30 m. Repeaters, shorter runs, or fiber are the remedies.",
    },
    {
        "type": "fill",
        "q": "The interface feature that automatically corrects a transposed TX/RX connection on copper links is auto-________. (type your answer)",
        "answers": ["mdi-x", "mdix", "mdi x"],
        "explain": "Auto-MDI-X senses which pairs the far end transmits on and swaps its own TX/RX electronically, eliminating the need for crossover cables between like devices on modern equipment.",
    },
    {
        "type": "fill",
        "q": "Frames that fail the frame check sequence increment the ________ error counter. (type your answer)",
        "answers": ["crc", "cyclic redundancy check"],
        "explain": "CRC errors mean frames arrived corrupted — the computed checksum did not match. Suspect bad or marginal cabling, EMI, a failing NIC/transceiver, or a duplex mismatch, and check the physical path.",
    },
    {
        "type": "match",
        "q": "Match each PoE standard to its per-port power at the PSE.",
        "pairs": [
            ["802.3af (Type 1)", "15.4 W"],
            ["802.3at PoE+ (Type 2)", "30 W"],
            ["802.3bt Type 3 (PoE++)", "60 W"],
            ["802.3bt Type 4", "90 W"],
        ],
        "explain": "Memorize af=15.4 W, at=30 W, bt Type 3=60 W, bt Type 4=90 W at the source, with 12.95/25.5/51/71.3 W respectively reaching the device. Exam scenarios give a device's draw and ask which standard or why a device is failing.",
    },
    {
        "type": "match",
        "q": "Match each cable category to its key specification.",
        "pairs": [
            ["Cat 5e", "1 Gbps at 100 m, 100 MHz"],
            ["Cat 6", "10 Gbps only to ~55 m, 250 MHz"],
            ["Cat 6a", "10 Gbps at 100 m, 500 MHz"],
            ["Cat 8", "25/40 Gbps to ~30 m, 2000 MHz"],
        ],
        "explain": "Category ratings pair a bandwidth (MHz) with achievable data rates and distances. The high-yield facts are Cat 6's 55 m limit for 10G, Cat 6a's full 100 m at 10G, and Cat 8's 30 m data-center niche.",
    },
    {
        "type": "match",
        "q": "Match each interface counter to its most likely cause.",
        "pairs": [
            ["CRC errors", "Corrupted frames from bad cable, EMI, or duplex mismatch"],
            ["Runts", "Collisions producing frames under 64 bytes"],
            ["Giants", "Jumbo/MTU mismatch producing frames over 1518 bytes"],
            ["Drops", "Full buffers from congestion or oversubscription"],
        ],
        "explain": "Each counter has a fingerprint: CRC = corruption in transit, runts = collisions (think duplex mismatch), giants = MTU mismatch, drops = congestion. Reading counters correctly points you at physical vs. configuration vs. capacity problems.",
    },
    {
        "type": "match",
        "q": "Match each port status to its meaning.",
        "pairs": [
            ["Error disabled", "Switch shut the port automatically after a violation"],
            ["Administratively down", "An admin issued shutdown in the configuration"],
            ["Suspended", "LACP/EtherChannel member failed compatibility checks"],
            ["Up/up", "Port and protocol are operational"],
        ],
        "explain": "Distinguish by who or what disabled the port: err-disabled is the switch protecting itself (port security, BPDU guard), administratively down is a deliberate human action, and suspended is a negotiation/consistency failure such as mismatched channel-member settings.",
    },
    {
        "type": "match",
        "q": "Match each signal degradation problem to its best mitigation.",
        "pairs": [
            ["Crosstalk between pairs", "Maintain twists near terminations; higher category cable"],
            ["EMI from machinery", "Shielded cable, rerouting, or fiber"],
            ["Attenuation on a long run", "Repeater/switch mid-span or fiber"],
            ["Alien crosstalk between bundled cables", "Cat 6a or looser bundling"],
        ],
        "explain": "Each impairment has a matched cure: twisting defeats pair-to-pair crosstalk, shielding/distance defeats external EMI, regeneration defeats attenuation, and Cat 6a's design specifically targets alien crosstalk between adjacent cables at 10G.",
    },
    {
        "type": "order",
        "q": "Arrange these copper cable categories from LOWEST to HIGHEST maximum data rate.",
        "items": [
            "Cat 5 (100 Mbps)",
            "Cat 5e (1 Gbps)",
            "Cat 6a (10 Gbps at 100 m)",
            "Cat 8 (25/40 Gbps)",
        ],
        "explain": "Cat 5 handles Fast Ethernet (100 Mbps), Cat 5e handles gigabit, Cat 6a carries 10 Gbps the full 100 m, and Cat 8 reaches 25/40 Gbps over short 30 m data-center runs. Bandwidth ratings rise in step: 100, 100, 500, and 2000 MHz.",
    },
    {
        "type": "order",
        "q": "Arrange the PoE standards from LEAST to MOST power supplied per port.",
        "items": [
            "802.3af (Type 1)",
            "802.3at PoE+ (Type 2)",
            "802.3bt Type 3 (PoE++)",
            "802.3bt Type 4",
        ],
        "explain": "The progression is 15.4 W, 30 W, 60 W, 90 W at the PSE (12.95, 25.5, 51, 71.3 W at the device). 802.3bt uses all four pairs to reach its higher power levels for devices like PTZ cameras, digital signage, and laptops.",
    },
    {
        "type": "order",
        "q": "A user's link is down. Arrange these Layer 1 troubleshooting actions in a sensible bottom-to-top order.",
        "items": [
            "Check the patch cable is seated and the link LED state",
            "Test the run with a cable tester for opens, shorts, and miswires",
            "Check the switchport status and error counters (show interface)",
            "Verify speed/duplex negotiation settings match",
            "Escalate or replace hardware if the port/NIC is faulty",
        ],
        "explain": "Bottom-to-top starts with the most physical checks (cable seated, link light), proves the cable itself, then moves to the switch interface's status and counters, then negotiated settings, escalating only after physical causes are eliminated.",
    },
]
