TOPIC = {
    "id": "5.3",
    "domain": 5,
    "title": "Given a scenario, troubleshoot common issues with network services",
    "short": "Network Service Issues",
}

TERMS = [
    ("Broadcast storm", "Runaway broadcast/multicast traffic from a Layer 2 loop; Ethernet has no TTL so looped frames multiply forever, saturating links and spiking switch CPU"),
    ("MAC flapping", "The same MAC address learned on multiple switch ports repeatedly; a signature symptom of a Layer 2 loop"),
    ("STP (Spanning Tree Protocol)", "802.1D protocol that prevents Layer 2 loops by electing a root bridge and blocking redundant paths"),
    ("Root bridge", "The STP switch with the lowest bridge ID (priority + MAC); becomes the reference point for the spanning tree"),
    ("Bridge ID", "Priority value plus MAC address used to elect the root bridge; lowest wins"),
    ("BPDU guard", "Err-disables an access port that unexpectedly receives BPDUs, preventing rogue switches and loops"),
    ("PortFast", "Moves an access/edge port straight to forwarding, skipping listening/learning so hosts get DHCP immediately"),
    ("Root port", "The single port on a non-root switch with the best path toward the root bridge"),
    ("Designated port", "The forwarding port on a segment; all ports on the root bridge are designated"),
    ("STP port states", "802.1D order: Blocking, Listening, Learning, Forwarding (plus Disabled)"),
    ("Incorrect VLAN assignment", "Switchport in the wrong VLAN: link is up but the device gets a wrong-subnet IP and can't reach its resources"),
    ("ACL (Access Control List)", "Ordered permit/deny rules processed top-down, first match wins, with an implicit deny at the end"),
    ("Implicit deny", "The invisible 'deny all' at the end of every ACL; anything not explicitly permitted is dropped"),
    ("Longest prefix match", "Route-selection rule: the most specific matching route (longest mask) wins before AD or metric"),
    ("Default route", "0.0.0.0/0 (IPv6 ::/0), the route of last resort used when no more specific route matches"),
    ("APIPA", "Automatic Private IP Addressing: 169.254.0.0/16 self-assigned when DHCP fails; link-local only, no gateway"),
    ("DHCP pool exhaustion", "All scope addresses leased so new clients get nothing and fall back to APIPA 169.254.x.x"),
    ("Incorrect default gateway", "Misconfigured gateway: host reaches its local subnet fine but nothing remote"),
    ("Duplicate IP address", "Two hosts sharing one IP; causes intermittent connectivity as ARP flips between their MACs"),
    ("Incorrect subnet mask", "Wrong mask changes where the host thinks its local network ends, causing boundary-dependent partial reachability"),
    ("Gratuitous ARP", "An unsolicited ARP announcement a host sends about its own IP; colliding ones reveal duplicate IPs"),
    ("DHCP snooping", "Switch feature that blocks rogue DHCP servers and starvation attacks by trusting only designated ports"),
]

QUESTIONS = [
    {"type": "mc", "q": "The entire floor's network suddenly becomes unusable, switch CPUs hit 100%, and logs show the same MAC address learned alternately on Gi0/5 and Gi0/7. What is happening?",
     "choices": ["Duplicate IP address conflict", "Layer 2 loop causing a broadcast storm", "DHCP pool exhaustion", "Incorrect subnet mask on the gateway"],
     "answer": 1,
     "explain": "MAC flapping (same MAC on multiple ports) plus network-wide slowness and CPU spikes is the classic signature of a Layer 2 loop. Because Ethernet frames have no TTL, looped broadcasts circulate forever and multiply into a storm."},
    {"type": "mc", "q": "Which feature should be enabled on access ports to prevent a rogue switch or loop from a user plugging in a mini-switch?",
     "choices": ["PortFast only", "BPDU guard", "Jumbo frames", "Proxy ARP"],
     "answer": 1,
     "explain": "BPDU guard err-disables an access port the moment it hears a BPDU, which should never appear on an edge port. It is the standard preventive control against user-introduced loops and rogue switches."},
    {"type": "mc", "q": "A PC fails to get a DHCP address when it first boots but works if the user runs release/renew about 30 seconds later. What is the most likely cause?",
     "choices": ["DHCP server is offline", "The access port is sitting in STP listening/learning while DHCP times out", "The subnet mask is wrong", "The default gateway is unreachable"],
     "answer": 1,
     "explain": "Classic 802.1D convergence takes about 30 seconds (listening + learning). The client's early DHCP requests time out while the port is not yet forwarding. The fix is PortFast on access ports, not disabling STP."},
    {"type": "mc", "q": "How is the STP root bridge elected?",
     "choices": ["Highest IP address", "Lowest bridge ID (priority, then MAC address)", "Highest MAC address", "The switch with the most ports"],
     "answer": 1,
     "explain": "The switch with the lowest bridge ID (priority value first, then lowest MAC as a tiebreaker) becomes root. Since all switches default to priority 32768, the oldest switch with the lowest MAC often wins by accident."},
    {"type": "mc", "q": "A user moves desks; the link light is on but they now receive an IP from a different subnet than before and cannot reach their department server. What is most likely wrong?",
     "choices": ["Bad network cable", "The new switchport is in the wrong VLAN", "DHCP server is down", "Duplicate IP address"],
     "answer": 1,
     "explain": "Link up but a wrong-subnet DHCP address and unreachable resources is the fingerprint of an incorrect VLAN assignment. Check with 'show vlan' and set the correct access VLAN on the port."},
    {"type": "mc", "q": "An administrator adds 'permit tcp any host 10.9.9.10 eq 443' to the BOTTOM of an ACL that already has 'deny ip any any' near the top. Users still cannot reach the server on HTTPS. Why?",
     "choices": ["The permit rule needs a reboot to apply", "ACLs process top-down, first match wins; the earlier deny matches first", "Port 443 is blocked at the physical layer", "The server's gateway is wrong"],
     "answer": 1,
     "explain": "ACLs are evaluated top-down and stop at the first match. The deny above the new permit catches the traffic before the permit is ever reached. The permit must be inserted above the deny."},
    {"type": "mc", "q": "A router's table contains 10.0.0.0/8 via A, 10.2.0.0/16 via B, and 0.0.0.0/0 via C. Which next hop is used for a packet to 10.2.3.4?",
     "choices": ["A (10.0.0.0/8)", "B (10.2.0.0/16)", "C (default route)", "The packet is dropped"],
     "answer": 1,
     "explain": "Longest prefix match decides first: /16 is more specific than /8, and the default /0 is only used when nothing else matches. Administrative distance and metric are compared only among equal-length prefixes."},
    {"type": "mc", "q": "All internal networks are reachable from a router, but nothing on the internet is. What is the most likely cause?",
     "choices": ["Duplicate IP address", "Missing or incorrect default route (0.0.0.0/0)", "STP has blocked a port", "Wrong subnet mask on a host"],
     "answer": 1,
     "explain": "Internal reachability with no external connectivity points to a missing or wrong route of last resort. 0.0.0.0/0 handles all destinations not matched by a more specific route, typically pointing to the internet edge."},
    {"type": "mc", "q": "New and returning devices cannot get online and show 169.254.x.x addresses, while already-connected users keep working. What is the cause?",
     "choices": ["Incorrect default gateway", "DHCP address pool exhaustion (or DHCP/relay down)", "Duplicate IP addresses everywhere", "ACL misconfiguration"],
     "answer": 1,
     "explain": "A 169.254 (APIPA) address means DHCP failed. Existing leases still work while new clients get nothing, which points to an exhausted scope, a down DHCP server, or a missing relay/ip helper on that VLAN."},
    {"type": "mc", "q": "A workstation can print to its local-subnet printer and reach a local file server but cannot browse any websites or reach any other office. Everyone else is fine. What single setting is most likely wrong?",
     "choices": ["Subnet mask", "Default gateway", "DNS server", "MAC address"],
     "answer": 1,
     "explain": "'Local works, all remote fails' for one host is the textbook incorrect-default-gateway fingerprint. The host can talk on its own wire but has no valid path off the subnet."},
    {"type": "mc", "q": "Two hosts experience intermittent connectivity, connections drop and revive unpredictably, and switch logs show one IP flip-flopping between two MAC addresses. What is happening?",
     "choices": ["Broadcast storm", "Duplicate IP address", "DHCP exhaustion", "Wrong VLAN"],
     "answer": 1,
     "explain": "Intermittent connectivity for two specific hosts, with an IP alternating between MACs in ARP/switch tables, is the duplicate IP signature. Traffic follows whichever host most recently answered ARP."},
    {"type": "mc", "q": "A host can communicate with some devices on what should be its subnet but not others, while everyone else works normally. Which misconfiguration best fits?",
     "choices": ["Incorrect default gateway", "Incorrect subnet mask", "STP loop", "Missing default route"],
     "answer": 1,
     "explain": "A wrong mask changes where the host believes its local network ends, so reachability becomes partial and boundary-dependent. Some address ranges resolve locally and others get misrouted, unlike a gateway problem which breaks ALL remote traffic."},
    {"type": "mc", "q": "Traceroute to a server dies at a specific application's port while a plain ping to the same destination succeeds. What does this indicate?",
     "choices": ["A routing loop", "An ACL or firewall filtering that specific port", "A duplicate IP", "DHCP exhaustion"],
     "answer": 1,
     "explain": "Routing does not discriminate by port, so a port-specific failure while ICMP succeeds points to ACL or firewall filtering, not a routing problem. Review the ACL top-down and check rule order and direction."},
    {"type": "mc", "q": "Traffic on a network flows through a slow closet access switch and performance suffers after every topology change. What is the likely STP cause?",
     "choices": ["BPDU guard is disabled", "The wrong switch became root bridge (default priorities let the oldest MAC win)", "PortFast is enabled on a trunk", "The subnet mask is wrong"],
     "answer": 1,
     "explain": "When all switches keep the default priority (32768), the switch with the lowest MAC (often the oldest, slowest one) becomes root and pulls traffic through itself. Set the core switch's priority low with 'root primary' and enable root guard."},
    {"type": "mc", "q": "Which command set best identifies why a device is in the wrong broadcast domain?",
     "choices": ["ping and traceroute", "show vlan and show interfaces switchport", "arp -a and nslookup", "show power and show config"],
     "answer": 1,
     "explain": "'show vlan' reveals port-to-VLAN assignments and 'show interfaces switchport' confirms access/trunk mode and native VLAN. Together they diagnose an incorrect VLAN assignment."},
    {"type": "mc", "q": "A statically addressed server suddenly reports an IP conflict days after the admin enabled DHCP on that subnet. What is the root cause and prevention?",
     "choices": ["Bad NIC; replace it", "The static IP was inside the DHCP pool; add an exclusion or reservation", "STP blocked the port; enable PortFast", "Wrong gateway; fix option 3"],
     "answer": 1,
     "explain": "The DHCP server eventually leased the server's static address to another client. Prevent recurrence by excluding that address from the scope or converting it to a DHCP reservation."},
    {"type": "mc", "q": "Which STP port role is placed into blocking to break a redundant loop while remaining ready as a backup path?",
     "choices": ["Root port", "Designated port", "Non-designated / blocked (alternate) port", "Access port"],
     "answer": 2,
     "explain": "The non-designated (blocked/alternate) port stops forwarding data to prevent the loop but stays available to take over if the active path fails. Seeing such a link 'down for data' is STP working, not a fault."},
    {"type": "mc", "q": "The default gateway router's interface for a subnet goes down. What symptom do users on that subnet experience?",
     "choices": ["Only one user loses remote access", "Everyone on the subnet loses remote/internet access but keeps local connectivity", "The whole company loses DNS", "APIPA addresses appear"],
     "answer": 1,
     "explain": "If the gateway itself fails, every host on that subnet shows the 'local works, remote fails' symptom simultaneously. When only one user has it, the cause is that user's own config or DHCP lease."},
    {"type": "mc", "q": "Which fix directly addresses DHCP pool exhaustion on a busy guest network?",
     "choices": ["Lengthen the lease time", "Shorten the lease time so abandoned leases return quickly", "Disable DHCP snooping", "Increase the subnet mask length"],
     "answer": 1,
     "explain": "Shortening the lease (for example from 8 days to 8 hours) returns addresses from transient guests faster. Expanding the scope and hunting rogue lease-hoggers are the other standard fixes."},
    {"type": "mc", "q": "Configuring a host with mask /16 where the correct mask is /24 causes what behavior?",
     "choices": ["The host cannot get link", "Genuinely remote hosts look 'local' so the host ARPs for them directly and fails to reach them", "All internet access is lost but local works", "Duplicate IP conflicts"],
     "answer": 1,
     "explain": "A too-large mask makes remote addresses appear on the local network, so the host ARPs for them instead of using the gateway and gets no answer. True local hosts and clearly distant internet destinations may still work, producing partial reachability."},
    {"type": "mc", "q": "Which tool sequence physically locates both machines involved in a duplicate IP conflict?",
     "choices": ["nslookup then dig", "arp -a to see the changing MAC, then show mac-address-table to find the ports", "ping -t then tracert", "show power then show vlan"],
     "answer": 1,
     "explain": "arp -a reveals the IP mapping to differing MACs; 'show mac-address-table' then maps each offending MAC to a switchport so you can walk to and disconnect the offenders."},
    {"type": "mc", "q": "After last night's firewall change, one subnet can reach a web service but a second subnet cannot, though both can ping the server. What should you check first?",
     "choices": ["The server's power supply", "The ACL rule order and which interface/direction it is applied to", "Cable termination", "The DHCP lease time"],
     "answer": 1,
     "explain": "Selective, port-aware failure right after a change screams ACL. Review the list top-down for rule ordering, the implicit deny, wrong interface, or wrong direction (in vs out)."},
    {"type": "mc", "q": "Which STP enhancement should NEVER be applied to a trunk or uplink port?",
     "choices": ["Root guard", "PortFast", "Storm control", "Loop guard"],
     "answer": 1,
     "explain": "PortFast bypasses listening/learning and belongs only on edge/access ports connecting end devices. Enabling it on a trunk or uplink risks creating a transient loop during topology changes."},
    {"type": "tf", "q": "A 169.254.x.x address on a client means the network cable or NIC is faulty.",
     "answer": False,
     "explain": "APIPA means DHCP failed (exhaustion, server down, or missing relay). The link had to be up for the client to even attempt DHCP, so it is not a cable or NIC fault."},
    {"type": "tf", "q": "Every ACL ends with an implicit deny, so any traffic not explicitly permitted is dropped.",
     "answer": True,
     "explain": "The implicit deny is the invisible final rule. Forgetting a needed permit means the implicit deny silently blocks that traffic."},
    {"type": "tf", "q": "Longest prefix match is evaluated before administrative distance during route selection.",
     "answer": True,
     "explain": "The router first finds the most specific matching prefix. Only among equal-length matches does it compare administrative distance, and then metric."},
    {"type": "tf", "q": "Disabling STP is the correct way to fix a PC that is slow to get DHCP at boot.",
     "answer": False,
     "explain": "Disabling STP invites loops. The correct fix is PortFast (with BPDU guard) on the access port so it forwards immediately."},
    {"type": "tf", "q": "A wrong default gateway breaks connectivity to the local subnet as well as remote networks.",
     "answer": False,
     "explain": "A wrong gateway leaves local-subnet communication intact because that traffic never uses the gateway. Only off-subnet/remote destinations fail."},
    {"type": "tf", "q": "Ethernet frames contain a TTL field that eventually stops a Layer 2 loop.",
     "answer": False,
     "explain": "Layer 2 Ethernet frames have no TTL, which is exactly why loops are catastrophic and require STP to prevent them. Only Layer 3 IP packets have a TTL."},
    {"type": "tf", "q": "The default route 0.0.0.0/0 is overridden by any more specific route because it has the shortest possible prefix.",
     "answer": True,
     "explain": "0.0.0.0/0 matches everything but is the least specific route, so any longer-prefix match wins. That is why a stray specific route can blackhole one destination while 'the internet still works.'"},
    {"type": "fill", "q": "What network/prefix does an APIPA (link-local) address fall within? (type the network in CIDR)",
     "answers": ["169.254.0.0/16", "169.254.0.0 16"],
     "explain": "APIPA uses 169.254.0.0/16. A client that self-assigns from this range has failed to reach a DHCP server."},
    {"type": "fill", "q": "What is the CIDR notation for the IPv4 default route? (type your answer)",
     "answers": ["0.0.0.0/0", "0.0.0.0 0"],
     "explain": "0.0.0.0/0 is the default route or 'gateway of last resort,' used when no more specific route matches."},
    {"type": "fill", "q": "The switch feature that err-disables an access port when it receives a BPDU is called ____ guard. (type one word)",
     "answers": ["bpdu"],
     "explain": "BPDU guard protects access ports from rogue switches and loops by shutting the port down if it hears spanning-tree BPDUs."},
    {"type": "fill", "q": "The same MAC address being learned repeatedly on different switch ports is called MAC ____. (type one word)",
     "answers": ["flapping"],
     "explain": "MAC flapping is a signature symptom of a Layer 2 loop, because looped copies of one frame arrive on multiple ports."},
    {"type": "fill", "q": "What is the default STP bridge priority value on most switches? (type the number)",
     "answers": ["32768"],
     "explain": "All switches default to bridge priority 32768, so the lowest MAC breaks the tie and often the oldest switch becomes root by accident."},
    {"type": "fill", "q": "A host that can reach some addresses on its segment but not others, based on address ranges, most likely has an incorrect subnet ____. (type one word)",
     "answers": ["mask"],
     "explain": "An incorrect subnet mask shifts the local/remote boundary, producing partial, boundary-dependent reachability distinct from a gateway or duplicate-IP problem."},
    {"type": "match", "q": "Match each symptom to its most likely cause.",
     "pairs": [
         ["Local subnet reachable, all remote fails", "Incorrect default gateway"],
         ["Some address ranges reachable, others not", "Incorrect subnet mask"],
         ["Intermittent drops, IP maps to two MACs", "Duplicate IP address"],
         ["New clients get 169.254 addresses", "DHCP pool exhaustion"],
         ["Network-wide slowness, CPU 100%, MAC flapping", "Layer 2 loop / broadcast storm"]],
     "explain": "Each network-service fault has a distinctive symptom fingerprint. Recognizing the fingerprint is how you answer scenario questions quickly."},
    {"type": "match", "q": "Match each STP element to its description.",
     "pairs": [
         ["Root bridge", "Switch with the lowest bridge ID"],
         ["Root port", "Best path toward the root on a non-root switch"],
         ["Designated port", "Forwarding port on a segment"],
         ["BPDU guard", "Err-disables an access port that hears a BPDU"],
         ["PortFast", "Access port jumps straight to forwarding"]],
     "explain": "Knowing STP roles and safeguards lets you distinguish a correctly blocked link from a genuine fault."},
    {"type": "order", "q": "Arrange the classic 802.1D STP port states in the order a port transitions through them.",
     "items": ["Blocking", "Listening", "Learning", "Forwarding"],
     "explain": "A port progresses Blocking, Listening, Learning, Forwarding, taking roughly 30 seconds. RSTP collapses this to discarding/learning/forwarding for faster convergence."},
    {"type": "order", "q": "Arrange these route-selection steps in the order a router applies them.",
     "items": ["Match the destination against known routes", "Prefer the longest prefix match", "Among equal prefixes, prefer lowest administrative distance", "Among equal AD, prefer the best metric"],
     "explain": "The router first finds routes that match, then picks the most specific prefix, then among equal prefixes the lowest administrative distance, then among equal AD the best metric."},
]
