TOPIC = {
    "id": "5.4",
    "domain": 5,
    "title": "Given a scenario, troubleshoot common performance issues",
    "short": "Performance Issues",
}

TERMS = [
    ("Congestion", "More traffic offered than the path can carry; queues fill, then latency and jitter rise and packets drop"),
    ("Contention", "Multiple devices competing for the same shared medium or uplink (all Wi-Fi is contention-based)"),
    ("Bottleneck", "The single slowest component that caps end-to-end performance, like a 100 Mbps port between gigabit segments"),
    ("Bandwidth", "The theoretical maximum data rate of a link, the size of the pipe"),
    ("Throughput", "The actual measured data rate achieved through a link; always less than or equal to bandwidth"),
    ("Goodput", "The rate of useful application data delivered, excluding headers and retransmissions; goodput <= throughput <= bandwidth"),
    ("Latency", "Delay for a packet to travel source to destination, usually measured as round-trip time (RTT)"),
    ("Propagation delay", "Travel time over distance, limited by the speed of light; dominates on long links like satellite"),
    ("Queuing delay", "Time a packet waits in buffers behind other traffic; the variable component that creates jitter"),
    ("Packet loss", "Packets sent but never delivered; even 1-2% wrecks TCP throughput and real-time media"),
    ("Jitter", "Variation in packet delay; packets arriving at uneven intervals; degrades VoIP and video"),
    ("QoS (Quality of Service)", "Prioritizes critical traffic (voice/video) so it does not wait behind bulk data; primary jitter/latency fix"),
    ("Jitter buffer", "Endpoint buffer that smooths uneven packet arrival at the cost of a little added delay"),
    ("RSSI", "Received Signal Strength Indicator in dBm; closer to 0 is stronger; -67 dBm is the VoIP/video design floor"),
    ("Co-channel interference", "Two APs on the same channel; they cooperate via CSMA/CA but share airtime and lose throughput"),
    ("Adjacent-channel interference", "APs on overlapping channels (e.g. 6 and 8) that cannot coordinate and corrupt each other's frames; worse than co-channel"),
    ("Non-overlapping channels", "In 2.4 GHz only channels 1, 6, and 11 do not overlap"),
    ("Sticky client", "A client that clings to a distant AP long after a closer, stronger AP is available"),
    ("Cell overlap", "Roughly 15-20% RSSI overlap between adjacent AP cells needed for smooth roaming"),
    ("802.11r", "Fast BSS Transition; pre-establishes keys so 802.1X clients roam without a slow full reauthentication"),
    ("Site survey", "Predictive or on-site RF assessment with a Wi-Fi analyzer/heatmap; the master wireless diagnostic"),
    ("Deauthentication attack", "Spoofed deauth frames knock clients off Wi-Fi; many disassociations with no RF cause should raise this flag"),
]

QUESTIONS = [
    {"type": "mc", "q": "Users report video calls stutter and freeze while large file downloads remain fast. Which metric is most likely the problem?",
     "choices": ["Bandwidth", "Jitter", "Packet size", "MAC flapping"],
     "answer": 1,
     "explain": "Jitter is variation in packet delay. Real-time streams reassemble a steady flow and break up when packets arrive unevenly, while bulk TCP transfers barely notice. The fix is QoS priority for voice/video plus jitter buffers."},
    {"type": "mc", "q": "What is the difference between bandwidth and throughput?",
     "choices": ["They are identical terms", "Bandwidth is theoretical maximum capacity; throughput is the actual rate achieved", "Bandwidth is measured; throughput is theoretical", "Bandwidth applies only to Wi-Fi"],
     "answer": 1,
     "explain": "Bandwidth is the pipe's rated capacity; throughput is what you actually move through it after overhead, congestion, and errors. A speed test measures throughput, which is always less than or equal to bandwidth."},
    {"type": "mc", "q": "An office's 2.4 GHz APs are set to channels 2, 6, and 9. What is wrong?",
     "choices": ["Nothing, those are valid", "Channels 2 and 9 overlap adjacent channels; use 1, 6, 11", "They should all be on channel 6", "2.4 GHz has no channel limits"],
     "answer": 1,
     "explain": "In 2.4 GHz the only non-overlapping channels are 1, 6, and 11. Channels 2 and 9 partially overlap their neighbors, causing adjacent-channel interference that corrupts frames, which is worse than sharing a channel."},
    {"type": "mc", "q": "A site connected by geostationary satellite reports every interactive session feels sluggish, though bulk transfers eventually complete. Why can't more bandwidth fix this?",
     "choices": ["The satellite has too much bandwidth", "The delay is propagation latency (~500-600 ms RTT) set by distance, not capacity", "It is a jitter buffer problem", "The subnet mask is wrong"],
     "answer": 1,
     "explain": "A geostationary satellite sits ~35,786 km up, adding ~250 ms each way for ~500-600 ms RTT. That is propagation delay governed by the speed of light; adding bandwidth adds lanes but cannot shorten the distance. A terrestrial or LEO path is the real fix."},
    {"type": "mc", "q": "Performance is terrible every business day from 9-11 a.m. and fine after hours. What does this pattern indicate?",
     "choices": ["A failing cable", "Congestion/utilization on a shared link", "A duplicate IP", "DNS misconfiguration"],
     "answer": 1,
     "explain": "A time-of-day pattern points to congestion, not a hardware fault. Prove it with interface-utilization graphs and baseline comparisons, then fix with capacity upgrades, QoS, or rescheduling bulk jobs."},
    {"type": "mc", "q": "Throughput between two gigabit segments is capped at about 100 Mbps. What is the most likely cause?",
     "choices": ["Jitter", "A bottleneck: one 100 Mbps port or a link that autonegotiated down", "Excess bandwidth", "A broadcast storm"],
     "answer": 1,
     "explain": "The slowest element caps the path. A single 100 Mbps port, or a NIC that autonegotiated to 100 Mbps/half duplex, throttles everything through it. Measure hop by hop to find and fix that element."},
    {"type": "mc", "q": "A company pays for 500 Mbps. Speed tests show 480 Mbps at the edge router but only 90 Mbps at a user's desktop. Where is the problem?",
     "choices": ["The ISP is throttling", "On the LAN side (duplex, cabling, Wi-Fi, or device limit) between the router and the desk", "The satellite link", "The DNS server"],
     "answer": 1,
     "explain": "Full speed at the edge but low speed at the desktop isolates the shortfall to the LAN path. Test segment by segment and check duplex/speed negotiation, cabling, Wi-Fi, and endpoint limits."},
    {"type": "mc", "q": "Which RSSI value is the common design floor for reliable VoIP and video over Wi-Fi?",
     "choices": ["-30 dBm", "-50 dBm", "-67 dBm", "-90 dBm"],
     "answer": 2,
     "explain": "-67 dBm is the widely used minimum target for real-time apps. -30 to -50 is excellent, -80 is poor and unreliable, and -90 is essentially the noise floor."},
    {"type": "mc", "q": "Employees walking to the far wing keep their laptops connected to the lobby AP at -78 dBm even though closer APs exist. What is this called?",
     "choices": ["Co-channel interference", "Sticky client behavior", "A broadcast storm", "Band steering"],
     "answer": 1,
     "explain": "The client controls roaming and clings to the original AP. Mitigate with a minimum-RSSI/client-kick threshold, lower AP power so distant clients release, and 802.11k/v/r assisted roaming."},
    {"type": "mc", "q": "Which is worse in 2.4 GHz, and why?",
     "choices": ["Co-channel, because APs never coordinate", "Adjacent-channel interference, because overlapping APs cannot coordinate and corrupt frames", "Both are equal", "Neither matters below 6 GHz"],
     "answer": 1,
     "explain": "Co-channel APs at least take turns via CSMA/CA, costing airtime. Adjacent-channel APs on overlapping channels cannot coordinate at all and directly corrupt each other's frames, so it is worse."},
    {"type": "mc", "q": "Which application type is most sensitive to latency, packet loss, AND jitter?",
     "choices": ["Bulk file transfer", "Email", "Real-time VoIP/video", "Overnight backups"],
     "answer": 2,
     "explain": "Real-time voice and video need packets on time and in order; latency, loss, and jitter all degrade them. Bulk transfers care mostly about bandwidth/throughput and tolerate delay."},
    {"type": "mc", "q": "A technician sees `* * *` at a middle hop in traceroute, but later hops respond normally. What does this usually mean?",
     "choices": ["Real packet loss at that hop", "That router simply deprioritizes or blocks ICMP replies; it is not a real outage", "A routing loop", "The destination is down"],
     "answer": 1,
     "explain": "A silent middle hop that still forwards traffic (later hops answer) usually just rate-limits or blocks ICMP. Real loss shows up end-to-end, from that hop onward. Don't declare an outage from one cosmetic silent hop."},
    {"type": "mc", "q": "Wi-Fi throughput drops sharply whenever the breakroom microwave runs. What is the cause?",
     "choices": ["Adjacent-channel interference from another AP", "Non-Wi-Fi 2.4 GHz interference from the microwave", "A sticky client", "Insufficient bandwidth"],
     "answer": 1,
     "explain": "Microwaves, Bluetooth, and cordless phones emit in the 2.4 GHz band and raise the noise floor. A spectrum/Wi-Fi analyzer reveals the interference; moving clients to 5 GHz or relocating the AP/appliance helps."},
    {"type": "mc", "q": "Which term describes the rate of useful application data delivered, excluding protocol overhead and retransmissions?",
     "choices": ["Bandwidth", "Throughput", "Goodput", "Latency"],
     "answer": 2,
     "explain": "Goodput counts only useful payload delivered to the application. The relationship is goodput <= throughput <= bandwidth."},
    {"type": "mc", "q": "VoIP calls drop the moment users walk between APs on an 802.1X (Enterprise) WLAN. What should be enabled?",
     "choices": ["PortFast", "802.11r Fast BSS Transition", "DHCP snooping", "Band steering only"],
     "answer": 1,
     "explain": "With 802.1X, a full reauthentication at each AP takes hundreds of milliseconds and drops live calls. 802.11r pre-establishes keys for near-instant secure handoffs. Verify 15-20% cell overlap too."},
    {"type": "mc", "q": "Cranking up AP transmit power to fix a coverage complaint often fails because:",
     "choices": ["Higher power reduces bandwidth", "Clients with weaker radios still cannot transmit back to the AP (asymmetric power)", "It disables QoS", "It changes the SSID"],
     "answer": 1,
     "explain": "Boosting only the AP creates a one-way link: distant clients hear the AP but their weaker radios cannot be heard in return. Balanced power, more APs, and better placement are the real fixes."},
    {"type": "mc", "q": "Users complain of choppy, robotic audio on calls while downloads and email are fast. What is the recommended mitigation?",
     "choices": ["Replace all cabling", "Implement QoS to prioritize voice, plus jitter buffers", "Increase the subnet mask", "Disable STP"],
     "answer": 1,
     "explain": "That fingerprint is jitter (or loss/latency) hitting real-time traffic. QoS priority queuing keeps voice from waiting behind bulk data, and jitter buffers smooth arrival. Target jitter under 30 ms."},
    {"type": "mc", "q": "A 48-port gigabit switch has a single 1 Gbps uplink. This is an example of:",
     "choices": ["Jitter", "Oversubscription/contention (48:1) for the uplink", "Adjacent-channel interference", "A duplicate IP"],
     "answer": 1,
     "explain": "Many ports sharing one uplink is oversubscription, a form of contention. Under load the uplink congests. Link aggregation or a faster uplink relieves it."},
    {"type": "mc", "q": "Users in a far conference room have no Wi-Fi while desks nearby are fine. Which diagnostic maps the dead zone?",
     "choices": ["nslookup", "A site survey with a Wi-Fi analyzer heatmap", "show power", "arp -a"],
     "answer": 1,
     "explain": "A site survey walks the space and maps RSSI per location, revealing coverage gaps between AP cells. Add or reposition APs to fill the hole."},
    {"type": "mc", "q": "Many clients across an office repeatedly disassociate from Wi-Fi with no RF explanation. Besides drivers and interference, what security cause should be considered?",
     "choices": ["ARP poisoning", "A deauthentication attack (spoofed deauth frames)", "DNS spoofing", "MAC flooding"],
     "answer": 1,
     "explain": "Spoofed deauthentication frames force clients off the network. Widespread disassociations with no RF cause should raise this flag; 802.11w (Protected Management Frames) mitigates it."},
    {"type": "mc", "q": "Even 1-2% packet loss severely degrades TCP throughput. Why?",
     "choices": ["TCP ignores loss entirely", "Loss triggers retransmissions and congestion-window collapse", "Loss increases bandwidth", "TCP switches to UDP"],
     "answer": 1,
     "explain": "TCP treats loss as congestion, shrinking its window and retransmitting, so throughput falls far more than the raw loss percentage would suggest. Real-time media also gets gaps and artifacts."},
    {"type": "mc", "q": "What guideline for adjacent AP cell overlap supports smooth roaming?",
     "choices": ["0% overlap", "About 15-20% overlap", "50% overlap", "100% overlap"],
     "answer": 1,
     "explain": "Roughly 15-20% RSSI overlap lets clients transition to the next AP before losing the current one. Too little causes dead gaps; too much causes constant roaming and co-channel interference."},
    {"type": "mc", "q": "Upgrading the WAN circuit does not improve performance because an old firewall behind it cannot inspect at line rate. What concept does this illustrate?",
     "choices": ["Jitter", "Bottlenecking (fix the slowest element, not the most expensive one)", "Contention ratio", "Propagation delay"],
     "answer": 1,
     "explain": "The firewall is the bottleneck, so the circuit upgrade changes nothing. Exam scenarios reward identifying and fixing the slowest element in the path."},
    {"type": "tf", "q": "A speed test measures throughput, not the link's theoretical bandwidth.",
     "answer": True,
     "explain": "Speed tests report the actual rate achieved (throughput), which is reduced from the rated bandwidth by overhead, congestion, and errors."},
    {"type": "tf", "q": "In 2.4 GHz, setting an AP to channel 3 to 'avoid the crowd on 1 and 6' improves performance.",
     "answer": False,
     "explain": "Channel 3 overlaps both 1 and 6, causing adjacent-channel interference with each. Stick to the non-overlapping set 1, 6, 11."},
    {"type": "tf", "q": "RSSI is expressed as a negative dBm value where closer to zero means a stronger signal.",
     "answer": True,
     "explain": "For example -50 dBm is stronger than -80 dBm. The scale is logarithmic; every -3 dB is roughly half the power."},
    {"type": "tf", "q": "Jitter significantly degrades bulk file transfers and web browsing.",
     "answer": False,
     "explain": "Jitter mainly harms real-time streams like VoIP and video. File transfers and browsing tolerate uneven arrival because they are not time-sensitive."},
    {"type": "tf", "q": "Adding bandwidth can eliminate the latency of a geostationary satellite link.",
     "answer": False,
     "explain": "The ~500-600 ms RTT is propagation delay from distance and the speed of light. Bandwidth adds capacity, not speed-of-light shortcuts."},
    {"type": "tf", "q": "Co-channel interference is generally worse than adjacent-channel interference in 2.4 GHz.",
     "answer": False,
     "explain": "It is the reverse. Co-channel APs coordinate via CSMA/CA and just share airtime; adjacent-channel APs cannot coordinate and corrupt frames, making adjacent-channel worse."},
    {"type": "fill", "q": "The variation in packet delay that degrades VoIP is called ____. (type one word)",
     "answers": ["jitter"],
     "explain": "Jitter is variation in delay. Target under 30 ms for good voice, and mitigate with QoS and jitter buffers."},
    {"type": "fill", "q": "In 2.4 GHz, list the three non-overlapping channels (comma separated numbers).",
     "answers": ["1 6 11", "1,6,11", "1, 6, 11"],
     "explain": "Channels 1, 6, and 11 are the only non-overlapping 2.4 GHz channels; plan APs onto them in a honeycomb."},
    {"type": "fill", "q": "What RSSI value in dBm is the common minimum design target for VoIP/video? (type the number with sign, e.g. -67)",
     "answers": ["-67", "-67 dbm"],
     "explain": "-67 dBm is the widely used floor for reliable real-time wireless applications."},
    {"type": "fill", "q": "The single slowest component that caps end-to-end performance is called the ____. (type one word)",
     "answers": ["bottleneck"],
     "explain": "Everything is only as fast as the bottleneck, so find and fix the slowest element rather than upgrading elsewhere."},
    {"type": "fill", "q": "The theoretical maximum capacity of a link is its ____. (type one word)",
     "answers": ["bandwidth"],
     "explain": "Bandwidth is the size of the pipe; throughput is what actually flows through it and goodput is the useful payload."},
    {"type": "fill", "q": "The primary technique to protect real-time voice traffic from delay behind bulk data is ____. (type the acronym)",
     "answers": ["qos", "quality of service"],
     "explain": "QoS classifies and prioritizes traffic so voice is queued ahead of bulk transfers, controlling latency and jitter."},
    {"type": "match", "q": "Match each capacity term to its meaning.",
     "pairs": [
         ["Bandwidth", "Theoretical maximum capacity of the link"],
         ["Throughput", "Actual data rate achieved"],
         ["Goodput", "Useful application data only, minus overhead"],
         ["Latency", "Delay, usually round-trip time"]],
     "explain": "The relationship is goodput <= throughput <= bandwidth. Latency is a separate delay dimension measured in time."},
    {"type": "match", "q": "Match each wireless problem to its best fix.",
     "pairs": [
         ["Adjacent-channel interference (2.4 GHz)", "Re-plan to channels 1/6/11"],
         ["Sticky clients", "Minimum-RSSI kick and lower AP power"],
         ["Coverage gap in far room", "Site survey; add/reposition APs"],
         ["VoIP drops when roaming on 802.1X", "Enable 802.11r fast roaming"],
         ["Choppy VoIP, data fine", "Implement QoS and jitter buffers"]],
     "explain": "Wireless troubleshooting maps each symptom to a targeted RF or QoS remedy; the site survey underpins most of them."},
    {"type": "order", "q": "Arrange these RSSI values from strongest to weakest signal.",
     "items": ["-30 dBm", "-50 dBm", "-67 dBm", "-80 dBm", "-90 dBm"],
     "explain": "Closer to zero is stronger. -30 is excellent, -67 is the VoIP floor, and -90 is essentially unusable noise-floor territory."},
    {"type": "order", "q": "As a link becomes increasingly congested, arrange these effects in the order they appear.",
     "items": ["Queues fill", "Latency rises", "Jitter increases", "Packets are dropped"],
     "explain": "Congestion first fills buffers, which adds delay (latency) and variable delay (jitter), and finally overflows into packet loss."},
]
