TOPIC = {
    "id": "5.5",
    "domain": 5,
    "title": "Given a scenario, use the appropriate tool or protocol to solve networking issues",
    "short": "Tools & Protocols",
}

TERMS = [
    ("Protocol analyzer", "Packet sniffer (Wireshark) that captures and decodes every layer for deep packet inspection"),
    ("ping", "Sends ICMP echo requests to test reachability, RTT latency, and packet loss"),
    ("traceroute/tracert", "Maps the hop-by-hop path using incrementing TTL; shows where traffic slows or stops"),
    ("nslookup", "DNS query tool with interactive mode to set record type and query a specific server"),
    ("dig", "Linux/macOS DNS power tool with detailed output including the ANSWER SECTION, TTLs, and timing"),
    ("tcpdump", "Command-line packet capture for Linux/Unix; the CLI counterpart of Wireshark"),
    ("netstat", "Shows the local host's active connections and listening ports (netstat -an)"),
    ("ip/ifconfig/ipconfig", "Local interface config viewers; ipconfig /all, /release, /renew, /flushdns"),
    ("arp", "Views/manages the local ARP cache (IP-to-MAC); arp -a shows the table"),
    ("Nmap", "Network Mapper: host discovery, port scanning, and service/version detection across the network"),
    ("LLDP", "Link Layer Discovery Protocol; open IEEE 802.1AB standard for multivendor neighbor discovery"),
    ("CDP", "Cisco Discovery Protocol; Cisco-proprietary Layer 2 neighbor discovery"),
    ("Speed tester", "Measures actual throughput (and latency/jitter) against a test server; iperf between owned hosts"),
    ("Toner (tone generator and probe)", "Fox-and-hound tool that traces/identifies one specific cable among many; does not test quality"),
    ("Cable tester", "Verifies copper wiremap: opens, shorts, miswires/reversed pairs, and split pairs"),
    ("Network tap", "Passive inline device that copies traffic to a monitor port without dropping or altering it"),
    ("Wi-Fi analyzer", "Surveys RF: SSIDs/BSSIDs, per-AP channel and RSSI, utilization/overlap, and rogue APs"),
    ("Visual fault locator", "Injects visible red laser into fiber so breaks, bends, and polarity show as leaking light"),
    ("OTDR", "Optical Time-Domain Reflectometer; measures loss events and distance-to-fault on long fiber runs"),
    ("show mac-address-table", "Displays MAC-to-port-to-VLAN learnings; used to locate which port a device is on"),
    ("show interface", "Shows port status, speed/duplex, and error counters (CRC, runts, giants, drops)"),
    ("show power inline", "Displays PoE budget, power used/remaining, and per-port draw and class"),
]

QUESTIONS = [
    {"type": "mc", "q": "A technician must find which switchport a device with a known IP address is plugged into. Which two commands, in order?",
     "choices": ["ping then traceroute", "show arp (IP to MAC) then show mac-address-table (MAC to port)", "nslookup then dig", "show power then show vlan"],
     "answer": 1,
     "explain": "First 'show arp' resolves the IP to its MAC, then 'show mac-address-table' maps that MAC to a switchport. Walk to that port and follow the cable. This exact two-step is a classic exam question."},
    {"type": "mc", "q": "Users can reach servers by IP but not by hostname. Which tool best tests the failing function in detail?",
     "choices": ["ping", "dig (or nslookup)", "netstat", "arp"],
     "answer": 1,
     "explain": "Name-resolves-fail-but-IP-works is a DNS problem. dig and nslookup both query DNS directly; dig gives the richer ANSWER SECTION, TTLs, and responding server."},
    {"type": "mc", "q": "A remote server seems down: ping fails from your desk but works from the server's own subnet. Which tool shows WHERE along the path traffic stops?",
     "choices": ["netstat", "traceroute/tracert", "arp -a", "show config"],
     "answer": 1,
     "explain": "traceroute maps each hop toward the destination. The point where responses stop for good (all later hops silent) marks where traffic is dropped or filtered."},
    {"type": "mc", "q": "You need to identify one unlabeled cable among 200 in a patch panel. Which tool?",
     "choices": ["Cable tester", "Toner (tone generator and probe)", "Visual fault locator", "Wi-Fi analyzer"],
     "answer": 1,
     "explain": "The toner injects a tone on one cable and the inductive probe sings when it finds that cable in the bundle. It traces/identifies a cable but does not test its quality."},
    {"type": "mc", "q": "After terminating a new copper run, which tool verifies there are no opens, shorts, miswires, or split pairs?",
     "choices": ["Toner and probe", "Cable tester (wiremap)", "OTDR", "netstat"],
     "answer": 1,
     "explain": "A cable tester performs a wiremap test pin-by-pin to catch opens, shorts, reversed/miswired pairs, and split pairs. Certifiers additionally measure length, attenuation, and crosstalk against category spec."},
    {"type": "mc", "q": "VoIP phones on one switch reboot randomly after ten new phones were installed. Which command confirms the suspected cause?",
     "choices": ["show vlan", "show power inline", "show arp", "show config"],
     "answer": 1,
     "explain": "Random reboots after adding PoE devices suggests the power budget is exceeded. 'show power inline' shows total budget, used/remaining, and per-port draw to confirm it."},
    {"type": "mc", "q": "Which tool runs ON a host to reveal that host's own listening ports and active connections?",
     "choices": ["Nmap", "netstat", "traceroute", "dig"],
     "answer": 1,
     "explain": "netstat (for example netstat -an) shows the local machine's sockets: what it is listening on and what it is connected to. Nmap, by contrast, probes OTHER hosts across the network."},
    {"type": "mc", "q": "You need to discover which TCP ports are open on hosts across a remote subnet. Which tool?",
     "choices": ["netstat", "Nmap", "arp", "ipconfig"],
     "answer": 1,
     "explain": "Nmap scans across the network for live hosts, open ports, and service versions. Only scan networks you are authorized to scan. netstat only reports the local host's own sockets."},
    {"type": "mc", "q": "A technician needs to know exactly what device is plugged into the other end of an uplink, per the switch. Which command?",
     "choices": ["show power", "show cdp neighbors / show lldp neighbors", "show arp", "ping"],
     "answer": 1,
     "explain": "CDP (Cisco) and LLDP (open 802.1AB) advertise directly-connected neighbor identity and port. 'show cdp/lldp neighbors' answers 'what is on this port?' and confirms uplinks match the diagram."},
    {"type": "mc", "q": "Which statement about LLDP vs CDP is correct?",
     "choices": ["Both are Cisco-proprietary", "LLDP is the open IEEE 802.1AB standard; CDP is Cisco-proprietary", "CDP is the open standard; LLDP is Cisco-only", "Neither works at Layer 2"],
     "answer": 1,
     "explain": "LLDP (802.1AB) is vendor-neutral and preferred in mixed environments (with LLDP-MED for VoIP). CDP is Cisco-proprietary. Both are Layer 2 neighbor-discovery protocols."},
    {"type": "mc", "q": "Which tool provides deep packet inspection with a full graphical decode of every protocol layer?",
     "choices": ["ping", "A protocol analyzer such as Wireshark", "arp", "toner"],
     "answer": 1,
     "explain": "Wireshark captures and decodes headers, flags, and payloads for deep packet inspection: incomplete DHCP exchanges, TLS handshake failures, retransmission storms. Capturing traffic not addressed to you needs a SPAN/mirror port or a tap."},
    {"type": "mc", "q": "On a GUI-less Linux server you must capture packets to a file for later analysis in Wireshark. Which tool?",
     "choices": ["nslookup", "tcpdump", "netstat", "ipconfig"],
     "answer": 1,
     "explain": "tcpdump is the CLI packet capturer. 'tcpdump -i eth0 -w file.pcap' writes a capture you can open in Wireshark, and BPF filters like 'port 53' narrow it."},
    {"type": "mc", "q": "Which command displays a switch port's speed, duplex, and error counters like CRC, runts, and giants?",
     "choices": ["show vlan", "show interface", "show route", "show arp"],
     "answer": 1,
     "explain": "'show interface' reports up/down state, speed/duplex, traffic rates, and the error counters. It is the go-to command for 'is this port healthy?' and reveals duplex mismatch (half-duplex + late collisions) and congestion (output drops)."},
    {"type": "mc", "q": "Which Windows command releases and renews a DHCP lease and can flush the DNS resolver cache?",
     "choices": ["arp", "ipconfig (/release, /renew, /flushdns)", "netstat", "tracert"],
     "answer": 1,
     "explain": "ipconfig manages the local IP configuration on Windows: /all for detail, /release and /renew for a new lease, and /flushdns to clear cached DNS records. Linux uses ip addr/ip route."},
    {"type": "mc", "q": "A fiber patch cable is suspected of having a break or bad polarity. Which tool localizes it by making light leak visibly at the fault?",
     "choices": ["Cable tester", "Visual fault locator", "Toner", "Wi-Fi analyzer"],
     "answer": 1,
     "explain": "A VFL injects visible red (~650 nm) laser light; at a break, sharp bend, or bad splice the light glows through the jacket, and it also verifies continuity/polarity on short runs. OTDR handles long-run distance-to-fault."},
    {"type": "mc", "q": "Which device provides a passive, lossless copy of traffic for an IDS or analyzer, more faithfully than a SPAN port under load?",
     "choices": ["A hub", "A network tap", "A router", "A patch panel"],
     "answer": 1,
     "explain": "A passive tap (including optical splitters) copies the full stream inline without dropping or altering it, whereas a switch SPAN/mirror port can silently drop copies under load and adds CPU cost."},
    {"type": "mc", "q": "Which command shows the routing table and the gateway of last resort on a router?",
     "choices": ["show interface", "show route (show ip route)", "show mac-address-table", "show power"],
     "answer": 1,
     "explain": "'show ip route' lists connected/static/dynamic routes with next hops, AD/metrics, and the default route. Codes flag the source: C connected, S static, O OSPF, B BGP."},
    {"type": "mc", "q": "Which command reveals the VLAN membership of each access port when diagnosing a wrong-VLAN symptom?",
     "choices": ["show vlan", "show power", "show route", "arp -a"],
     "answer": 0,
     "explain": "'show vlan' lists which VLANs exist and which access ports belong to each, the first command for 'user in the wrong VLAN' symptoms (link up, wrong-subnet DHCP, unreachable resources)."},
    {"type": "mc", "q": "Which tool surveys the RF environment to find rogue APs, channel overlap, and per-AP RSSI?",
     "choices": ["Cable tester", "Wi-Fi analyzer", "Toner", "netstat"],
     "answer": 1,
     "explain": "A Wi-Fi analyzer reports SSIDs/BSSIDs, channels, signal strength, and utilization, and hunts rogue APs. Spectrum variants also detect non-Wi-Fi interference like microwaves."},
    {"type": "mc", "q": "In a ping result showing 'Lost = 1 (25% loss)' with varying reply times, what two things is the output telling you?",
     "choices": ["Only the destination MAC", "Packet loss percentage and latency (RTT) consistency", "The routing table", "The VLAN assignment"],
     "answer": 1,
     "explain": "ping reports reachability, loss percentage, and RTT. Widely varying times suggest jitter/congestion; 'ping by IP works but by name fails' points to DNS."},
    {"type": "mc", "q": "Which command inspects the local ARP cache to spot a duplicate IP or ARP poisoning (wrong/changing MAC for an IP)?",
     "choices": ["arp -a", "show power", "tracert", "dig"],
     "answer": 0,
     "explain": "'arp -a' displays the IP-to-MAC table. A gateway or host IP mapping to an unexpected or changing MAC reveals duplicate IPs or ARP spoofing/poisoning."},
    {"type": "mc", "q": "Which fiber tool measures how much optical power actually arrives, in dBm, against the loss budget?",
     "choices": ["Visual fault locator", "Light meter (optical power meter)", "Toner", "Cable certifier"],
     "answer": 1,
     "explain": "An optical power meter (OPM/light meter) measures received power in dBm to compare against the link's loss budget. The VFL finds breaks visibly and the OTDR maps loss events by distance."},
    {"type": "mc", "q": "A running-config versus startup-config mismatch shown by 'show config' most directly means what?",
     "choices": ["The device is failing", "There are unsaved configuration changes", "STP has converged", "The PoE budget is exceeded"],
     "answer": 1,
     "explain": "show running-config is the active config in RAM; show startup-config is what loads at boot. A mismatch means changes were made but not saved, so a reboot would revert them."},
    {"type": "tf", "q": "netstat runs on the local host and shows its own connections, while Nmap probes other hosts across the network.",
     "answer": True,
     "explain": "That distinction is frequently tested: 'what is this host listening on?' is netstat; 'what ports are open on that remote server?' is Nmap."},
    {"type": "tf", "q": "dig generally provides more detailed DNS output than nslookup, including the ANSWER SECTION and TTLs.",
     "answer": True,
     "explain": "Both query DNS, but dig is the detailed, script-friendly Linux/macOS choice showing full sections, TTLs, query time, and responding server."},
    {"type": "tf", "q": "A toner/tone generator both traces a cable and certifies its Cat 6 performance.",
     "answer": False,
     "explain": "A toner only finds/identifies a cable. Verifying wiremap needs a cable tester, and certifying to a category spec needs a certifier."},
    {"type": "tf", "q": "In traceroute, a single silent middle hop (`* * *`) that still forwards to later hops is usually cosmetic, not a real outage.",
     "answer": True,
     "explain": "That router simply rate-limits or blocks ICMP replies. Real loss appears end-to-end from that hop onward, not just at one intermediate hop."},
    {"type": "tf", "q": "CDP is an open, multivendor standard while LLDP is Cisco-proprietary.",
     "answer": False,
     "explain": "It is the reverse: LLDP (802.1AB) is the open standard and CDP is Cisco-proprietary."},
    {"type": "tf", "q": "'show mac-address-table' can help detect a Layer 2 loop by showing the same MAC flapping between ports.",
     "answer": True,
     "explain": "Looped copies of one frame arrive on multiple ports, so the CAM table shows the MAC learned on different ports repeatedly, a signature of a loop."},
    {"type": "fill", "q": "Which command-line tool sends ICMP echo requests to test reachability and latency? (type the command)",
     "answers": ["ping"],
     "explain": "ping is the first-line reachability test, reporting RTT and packet loss and anchoring the divide-and-conquer approach."},
    {"type": "fill", "q": "The open IEEE 802.1AB neighbor-discovery protocol is abbreviated ____. (type the acronym)",
     "answers": ["lldp"],
     "explain": "LLDP is the vendor-neutral Layer 2 neighbor-discovery protocol; CDP is the Cisco-proprietary equivalent."},
    {"type": "fill", "q": "Which show command displays the PoE budget, used/remaining power, and per-port draw? (type the full command)",
     "answers": ["show power inline", "show power"],
     "explain": "'show power inline' is the go-to command for PoE budget scenarios such as phones that reboot after new devices are added."},
    {"type": "fill", "q": "Which CLI packet-capture tool is the command-line counterpart to Wireshark on Linux? (type the command)",
     "answers": ["tcpdump"],
     "explain": "tcpdump captures on the command line and can write .pcap files to open later in Wireshark."},
    {"type": "fill", "q": "The Windows command 'ipconfig /____' clears the local DNS resolver cache. (type the flag word)",
     "answers": ["flushdns", "flush dns"],
     "explain": "ipconfig /flushdns clears cached DNS records, useful after a DNS change or when stale records cause resolution errors."},
    {"type": "fill", "q": "The network/port scanner used for host discovery and service/version detection is ____. (type the tool name)",
     "answers": ["nmap"],
     "explain": "Nmap discovers live hosts, open ports, and service versions across a network. Only scan networks you are authorized to scan."},
    {"type": "match", "q": "Match each command-line tool to the primary question it answers.",
     "pairs": [
         ["ping", "Can I reach it, and how fast, with what loss?"],
         ["traceroute", "Where along the path does it break or slow?"],
         ["netstat", "What is this host listening on / connected to?"],
         ["arp", "Which MAC does this host map to that IP?"],
         ["dig", "Does the name resolve, in detail, per which server?"]],
     "explain": "Matching a symptom to the right diagnostic tool is the core skill of objective 5.5."},
    {"type": "match", "q": "Match each hardware tool to its job.",
     "pairs": [
         ["Toner and probe", "Trace/identify one specific cable"],
         ["Cable tester", "Wiremap: opens, shorts, miswires, split pairs"],
         ["Network tap", "Passive lossless copy of traffic"],
         ["Wi-Fi analyzer", "RF survey: channels, RSSI, rogue APs"],
         ["Visual fault locator", "Expose fiber breaks/polarity with visible light"]],
     "explain": "Physical-layer tools each solve a distinct problem; tone to find, tester to verify, tap to copy, analyzer to survey RF, VFL to light up fiber faults."},
    {"type": "match", "q": "Match each show command to what it displays.",
     "pairs": [
         ["show mac-address-table", "MAC to port to VLAN mappings"],
         ["show route", "Routing table and default route"],
         ["show interface", "Port status, speed/duplex, error counters"],
         ["show vlan", "Which VLAN each port belongs to"],
         ["show power inline", "PoE budget, used/remaining, per-port draw"]],
     "explain": "The show family interrogates switches and routers directly; each answers a specific troubleshooting question."},
    {"type": "order", "q": "Arrange the divide-and-conquer ping sequence from most local to most remote.",
     "items": ["Ping loopback (127.0.0.1)", "Ping own IP address", "Ping default gateway", "Ping a remote IP", "Ping a remote hostname"],
     "explain": "Working outward isolates where connectivity breaks: stack, NIC, local subnet, routing, then DNS. A failure at the hostname step but success at the remote IP step points to DNS."},
    {"type": "order", "q": "Arrange the steps to physically locate a device by its known IP address.",
     "items": ["Run show arp to get the MAC for the IP", "Run show mac-address-table to find the port for that MAC", "Walk to that switchport", "Follow the cable to the device"],
     "explain": "IP to MAC via show arp, MAC to port via show mac-address-table, then trace the physical cable. This chained lookup is a staple exam scenario."},
]
